### PR TITLE
config: disable FRETEQUIV filter

### PR DESCRIPTION
**Pull request by pbludov**
NOT to merge. This PR is need to find all cases like hcoles/pitest#725

### CODE REVIEW

**Comment by rnveach** [comment]
@pbludov Can you explain how you found it was connected to this and what this is?

**Comment by pbludov** [comment]
> @pbludov Can you explain how you found it was connected to this and what this is?

I extracted the code into a small example and noticed that in the case of ' list.size () > 0 ' there is one less mutator than for `!list.isEmpty()`. I looked at the bytecode of the methods, the Java code of the mutator and found that the tail of the method matches the mutated code.

Since the Pitest has a filter to suppress mutation of methods like
```
    public boolean isCommentNodesRequired() {
        return false;
    }
```
which will be no-op, this filter may be relevant to this issue. I tested this assumption and it was confirmed.

This PR is to ensure that no similar cases are left. Unfortunately, I had to repeat half of the pitests on my pc, because when the percentage of coverage decreases, the report only contains an error, without a list of differences. However, I made sure that this filter doesn't remove anything other than methods like `isCommentNodesRequired`.

**Comment by rnveach** [comment]
> Since the Pitest has a filter to suppress mutation of methods like

How did you find out about filters? I don't even see it mentioned on their website.

> when the percentage of coverage decreases, the report only contains an error

I would do a replace all for the following lines:
````
              <coverageThreshold>100</coverageThreshold>
              <mutationThreshold>100</mutationThreshold>
````

Change them to 0 and then it won't fail and still print the difference report.

**Comment by pbludov** [comment]
> How did you find out about filters? I don't even see it mentioned on their website.

They are mentioned here: https://pitest.org/quickstart/advanced/

And I forgot to say that I started with `<verbose>true</verbose>` option, which is documented here https://pitest.org/quickstart/maven/
Turning this option on will show all default properties, including the list of filters.

**Pull request closed without merging**
