### PR TITLE
Issue #14556: Bump Codenarc version to highest compatible release v2.2.0

### LINKED ISSUE #14556: Update Codenarc to highest compatible release - v2.2.0
We are using an old version of codenarc. Latest release is 3.1.0, we are using `v1.4` right now.

From checkstyle/[codenarc.groovy](https://github.com/checkstyle/checkstyle/blob/master/.ci/codenarc.groovy) : 

```
@Grapes(
        @Grab(group='org.codenarc', module='CodeNarc', version='1.4')
)
```

https://github.com/CodeNarc/CodeNarc/releases

Findings from PR https://github.com/checkstyle/contribution/pull/836 that successfully closed Issue https://github.com/checkstyle/contribution/issues/757 : 
We cannot use the latest due to older groovy version used in CI and the groovy syntax used in our scripts. We have settled on `v2.2.0`

The version bump needs to be done in the main repo too.

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Closes #14556 

Extension of Issue https://github.com/checkstyle/contribution/issues/757 and response to https://github.com/checkstyle/contribution/issues/757#issuecomment-1965744852

CodeNarc release used : `v2.2.0`
Link to page : https://github.com/CodeNarc/CodeNarc/releases

Verified changes on local : 

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:56 h
[INFO] Finished at: 2024-02-27T12:17:22+05:30
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by MANISH-K-07** [comment]
@romani , @nrmancuso 

The failing CI are unrelated, I believe.

**Comment by nrmancuso** [comment]
@MANISH-K-07 issue is approved, please link to successful codenarc execution in CI

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by nrmancuso** [comment]
>not sure why but I am unable to view the build log of [ci/semaphore](https://checkstyle.semaphoreci.com/workflows/2b72cbcb-8789-40ac-b9c5-c682788bf85b?pipeline_id=def89aa1-a5be-4700-99de-267fb2051a30).

Just checked, seems like you may not be able to without an org login. Here is a screenshot of the UI:


image

**Review by nrmancuso — APPROVED** [review]

**Pull request merged**
