### PR TITLE
supplemental: ant switch in sevntu-checkstyle/sevntu.checkstyle#915

### PR DESCRIPTION
**Pull request by rnveach**
Identified when preparing to merge https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/916

Sevntu's checkstyle skip is changing.

This PR should wait on sevntu merge and should re-run to confirm.

### CODE REVIEW

**Comment by rnveach** [comment]
Current PR's run:
https://checkstyle.semaphoreci.com/jobs/6c8c3bfc-77d8-43b4-bbf2-6da6aff786dc#L526-L528
Execution is skipped because new name has been merged yet.

**Review by romani — APPROVED** [review]

**Comment by rnveach** [comment]
Rerunning job to verify.

**Comment by rnveach** [comment]
Job is still being skipped.
https://checkstyle.semaphoreci.com/jobs/8bbdcd1c-55c4-4cb9-a24c-2e9699258498#L647

I believe ant's:
````
  <condition property="checkstyle.ant.skip">
    <isset property="checkstyle.ant.skip" />
  </condition>

  <target name="execute" unless="checkstyle.ant.skip">
````

Is just a if null or not null check, and doesnt care if it is true/false.

**Comment by rnveach** [comment]
https://checkstyle.semaphoreci.com/jobs/22982c18-9cad-4868-9f77-7e440c1b2649#L650
New run is now working as expected and no longer being skipped.

**Pull request merged**
