### PR TITLE
Detect public constructors in non-public classes in RedundantModifier

### PR DESCRIPTION
**Pull request by liscju**
check, issue #1537

### CODE REVIEW

**Comment by liscju** [comment]
Failing tests are places where there are redundant public modifier in non-public classes, i send PR for this in checkstyle/orekit https://github.com/checkstyle/Orekit/pull/7 , it should cover all errors

**Comment by romani** [comment]
0) PR to test project is merged.

1) please update javadoc and xdoc with that code example, it is not obvious.

2) please update commit message to have "issue #xxxxx" (space between)

3) please split checkstyle code update and Check update to different commits of the same PR (each commit should ref to the same issue).

**Comment by liscju** [comment]
1) DONE, updated javadoc and xdoc
2) DONE , it was even before new version of PR
3) After rebase it wasnt needed, because in this commit dff are only changes of Check

**Comment by romani** [comment]
please review failure of "NoErrorTest - Orekit"

**Comment by liscju** [comment]
My fault, when i made changes to Checkstyle/Orekit i omit 4 problems, fixed this by PR  https://github.com/checkstyle/Orekit/pull/8

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
