### PR TITLE
Extended javadoc/xdoc for RightCurlyCheck, issue #1900

### PR DESCRIPTION
**Pull request by MEZk**

### CODE REVIEW

**Comment by romani** [comment]
I do not see example " public long getId() { return id; }" in SAME option, we need to explain user behavior for that case.

**Comment by MEZk** [comment]
@romani 
Added example and explanation.

**Comment by romani** [comment]
> The brace must be on the same line as the next statement .......

so , following code is ok for SAME option ?
```
 if (a > 0) {
        //...
    } int i = 5;
```

**Comment by romani** [comment]
> Note, if you add, for example, METHOD_DEF into RightCurly's blocks to check,

please remove reference to Check as option potentially could be used in other Checks. Please explain a behavior in terms of java elements without Check mentioning.

**Comment by MEZk** [comment]
@romani 
The RightCurlyCheck in current implementation will rise violation on the following code example when brace policy is SAME:
````java
if (a > 0) {
        //...
} int i = 5;  // violation: '}' at column 9 should be alone on a line.
````

**Comment by romani** [comment]
you state "The brace must be on the same line as the next statement or ...." at the beginning and 
raise violation at 
``
if (a > 0) {
        //...
} int i = 5;  // violation: '}' at column 9 should be alone on a line.
```

description is not correct and should be fixed.
User need to read description and clearly understand what location is expected.

**Comment by MEZk** [comment]
@romani 
```'}' at column 9 should be alone on a line.``` is a result of check's logic. 
When there is no ```else``` for if-block ```shouldCheckLastRcurly``` flag will be set to true. See [getDetails()](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L326). And the Check will rise violation at [validate()](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L207). From my point of view the violation should be risen only when brace policy is ALONE, because it message refers to ALONE option.

**Comment by MEZk** [comment]
@romani 
>description is not correct and should be fixed.

Added examples and corrected violation message and descriptions.

**Comment by MEZk** [comment]
@romani 
Corrected documentation and examples.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
