### PR TITLE
spelling: fix German translation of 'tag'

### PR DESCRIPTION
**Pull request by Bananeweizen**
The German translation of 'tag' is neutral, not male (at least in the
sense of a markup tag), so it must be "das Tag", not "der Tag".
Reference: https://www.duden.de/rechtschreibung/Tag_Strukturelement_Markierung

### CODE REVIEW

**Comment by Vladlis** [comment]
@Bananeweizen 
Please make sure your commit message follows these requirements https://travis-ci.org/checkstyle/checkstyle/jobs/330023171#L1227-L1234

**Comment by Bananeweizen** [comment]
Restricting the commit message to one line and less than 200 characters is counter productive. I had to remove stuff that a reviewer should be aware of. You should really loosen that restriction. If you don't want to _read_ a long commit message, then just skip it while reading. But forcing contributors to not explain changes?

**Comment by rnveach** [comment]
> But forcing contributors to not explain changes?

We don't force contributors to not explain their changes.
In a normal issue/PR workflow, it is the issue that should have all the explanation needed. This gives users all the space they need to make whatever notes or explanations they need while keeping the commit message short and quick to read to get an idea of what is being done. This way also gives you more control of formatting and ability to add pictures or links and such. We attach issues/PR numbers to our commits so you can always look up the full details if needed.

If you need more notes added to your work, you can change the commit message to start with `Pull #5467: ` and put all the details you need in the first message of the post.
I don't really know if future contributors who look at your work for translation will do this. You can see past ones at https://github.com/checkstyle/checkstyle/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+german .

**Comment by romani** [comment]
@Bananeweizen , one of main reason to limit commit size is our automatic release notes generation, that is based on commit message partly. Benefit of auto generated release notes, ability to release quicker and more often is significantly better than some inconvenience at contributors side. We spent a lot of time to make contributions to be done easy, but some rules have to exists.
More about commits and release notes https://github.com/checkstyle/checkstyle/wiki/Release-notes-automation

Please fix commit message to reference pull number and move all required text to pull description.

**Comment by romani** [comment]
merged manually, commit message was cut to conform realease notes generation tool.

**Pull request closed without merging**
