### PR TITLE
Fix up Portuguese messages

### PR DESCRIPTION
**Pull request by victorwss**
Fix up the horrible broken Portuguese translation.

The Portuguese translation of Checkstyle is one of the worst I've seen. The current translation features very badly translated words, very broken and malformed Portuguese grammar and also mixes up inconsistently the Brazilian and European dialects. It is so awful and unreliable that many of the messages reads as utterly useless gibberish in Portuguese and most of the times that I use checkstyle (which sees that Portuguese is my language due to my Locale), for at least some messages, I must check the original English messages to make any sense of them.

I thought about opening up an issue for that. However, I think that a PR is simply more productive. My translation (hopefully) fixes all the bad Portuguese messages. Even if I took one of two of them wrong, they are waaaay better than what it was before.

I standardized them into PT_BR (Brazilian Portuguese), spoken by much more people than the PT_PT one (spoken in Portugal, Angola, Mozambique and a few other countries). I would appreciate to provide a proper PT_PT translation in the near future, using as its starting point the PT_BR one that I'm providing (just a few sentences would need to be rewritten). However, I can't provide one right now.

Here are some of the really bad examples:

----

**Example:** _Annotation array values cannot contain trailing comma._
**How it was translated:** _Anotação valores de matriz não pode conter fuga vírgula._
**What does the translation means in English:** _Matrix values annotation cannot contain comma run away._
**Proposed new translation:** _A lista de valores de um array de anotações não pode ser terminada em uma vírgula._
**Translation back in English of the proposal:** _The list of values of an annotation array cannot be finished with a comma._

----

**Example:** _Duplicate {0} tag._
**How it was translated:** _Duplicar {0} tag._
**Translating back to English:** _To duplicate tag {0}._
**How it should be interpreted by a programmer in English:** _Oops, we found the {0} tag duplicated. You should not do that!_
**How does the translation would be interpreted by a programmer in Portuguese:** _You should duplicate the tag {0}._

The problem here is that the "duplicate" word which meant to be as an adjective in English was taken as a verb in Portuguese and the result translation was exactly the opposite of what it should be. There weren't enough context in the original message for a reasonable machine translation.

**Proposed new translation:** _A tag {0} não deveria ser duplicada._
**Translation back in English of the proposal:** _The tag {0} should not be duplicated._

----

**Example:** _Don''t use trailing comments._
**How it was translated:** _Don 't usar arrastando comentários._

Yuck! Here, the sentence is part in English and part in Portuguese. "Don 't" do not means anything at all in Portuguese.

**What does the part actually translated in Portuguese means in English:** _to use dragging comments._
**Proposed new translation**: _Não use comentários no final de linhas._
**Translation back in English of the proposal:** _Do not use comments at line endings._

----

**Example:** _Must include both @java.lang.Deprecated annotation and @deprecated Javadoc tag with description._
**How it was translated:** _Deve incluir tanto @ anotação java.lang.Deprecated e tag Javadocdeprecated com a descrição._
**What does the translation means in English:** _Must include much @ annotation java.lang.Deprecated and tag Javadocdeprecated with the description._

This translation is particularly awful because one of the `@` sign was dropped and other was separated from the annotation name. "Javadocdeprecated" was smashed together into a single word. It also features horribly broken Portuguese grammar.

**Proposed new translation:** _Deveria incluir tanto a anotação @java.lang.Deprecated como a tag @deprecated do Javadoc com a devida descrição._
**Translation back in English of the proposal:** _Should include both the annotation @java.lang.Deprecated just as the @deprecated Javadoc tag with the needed description._

----

**Example:** _Default should be last label in the switch._
**How it was translated:** _Padrão deve ser a última etiqueta no interruptor._
**What does the translation means in English:** _Pattern must be the last ticket in interrupter._
**Proposed new translation:** _O default deve ser a última entrada no switch._
**Translation back in English of the proposal:** _The default must be the last input in the switch._

----

**Example:** _String literal expressions should be on the left side of an equals comparison._
**How it was translated:** _Corda expressões literais deve estar no lado esquerdo de um é igual comparação._
**What does the translation means in English:** _Literal expressions rope must be in the left side of a one is equal comparision._

WOW! That awful translation simply makes my eyes bleed!

**Proposed new translation:** _Literais de String deveriam estar no lado esquerdo de comparações feitas com equals._
**Translation back in English of the proposal:** _String literals should be in the left side of comparisons performed with equals._

----

**Example:** _Throwing ''{0}'' is not allowed._
**How it was translated:** _Jogando ''{0}'' não é permitido._
**What does the translation means in English:** _Playing ''{0}'' is not allowed._
**Proposed new translation:** _Lançar ''{0}'' não é permitido._
**Translation back in English of the proposal:** _Throw ''{0}'' is not allowed._

----

**Example:** _File match folder pattern ''{0}'' and file pattern ''{1}''._
**How it was translated (using the wrong encoding):** _Arquivo padr�o pasta jogo ''{0}'' e arquivo padr�o ''{1}''._
**What does the translation means in English:** _Standard file folder game ''{0}}'' and standard file ''{1}''._
**Proposed new translation:** _O nome do arquivo condiz com o padrão ''{0}'' para pastas e com o padrão ''{1}'' para arquivos._
**Translation back in English of the proposal:** _The file name matches the pattern ''{0}'' for folders and the pattern ''{1}'' for files._

----

**Example:** _{0} statement should not be line-wrapped._
**How it was translated:** _{0} afirmação não deve ser linha-embrulhado._
**What does the translation means in English:** _{0} affirmation should not be line-embroiled._
**Proposed new translation:** _A instrução {0} não deveria ser dividida em mais de uma linha._
**Translation back in English of the proposal:** _The instruction {0} should not be splitted into more than one line._

### CODE REVIEW

**Comment by romani** [comment]
@victorwss , non of maintainers speak Portuguese, so we filled some gaps in translations by google translator with hope that finally smb come to us and make proper translations.
Thanks a lot for your contribution.

Please change commit message to have prdefix "doc: " or "Pull #5082: " to have reference to this discussion.

**Comment by romani** [comment]
@victorwss , please rebase over our master it should fix some CI problems.
all CI should be green to let me merge PR

**Comment by victorwss** [comment]
Seems that I made it wrong, sorry. What should I do? Unpush and uncommit things, rewrite history and redo it all? Or maybe create a new pull request?

**Comment by rnveach** [comment]
@victorwss Don't delete your current branch. You still your work isolated in commit https://github.com/checkstyle/checkstyle/pull/5082/commits/d2854084bce4c0f0ab56feeca76bcafb74feaeed .
Create a brand new branch based off the latest master locally, cherry-pick the commit I mentioned, d2854084bce4c0f0ab56feeca76bcafb74feaeed , onto the new branch and force push that over your old branch on the server, `fix-portuguese-messages`.

**Comment by victorwss** [comment]
I can't see the logs of IDEA Inspections (requires login) nor wercker (gives error 401 - Unauthorized for me). Wercker is still running, but IDEA Inspections failed. What went wrong there?

The other CIs seems to be fine.

**Comment by rnveach** [comment]
> I can't see the logs of TeamCity / IDEA Inspections (requires login)

There is an option for guest login you can use that with having to sign up.
Here is what TC says:
> src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc
messages_pt.properties (2)
18: Inconsistent property value end '.'
19: Inconsistent property value end '.'

> wercker (gives error 401 - Unauthorized for me)

This is a limitation of wercker, it doesn't allow us to give out anonymous access.

**Comment by victorwss** [comment]
> 18: Inconsistent property value end '.'
19: Inconsistent property value end '.'

Hmm. those lines don't have periods in the English version, but they do have in the Portuguese one. Looking at the messages, some of them are finished with periods and others aren't. Removing those periods is trivial, but out of curiosity, what is the reason why some messages ends with periods while others doesn't?

**Comment by rnveach** [comment]
> those lines don't have periods in the English version

All of the non-portuguese languages don't end with a period for `javadoc.parse.error`.
> Javadoc comment at column {0} has parse error. Details: {1}
> Javadoc comentario en la columna {0} tiene parse error. Detalles: {1}
> Le commentaire Javadoc à la colonne {0} ne peut être analysé. Détails : {1}

> O comentário Javadoc na coluna {0} tem um erro sintático. Detalhes: {1}.

The check is asking you to remove the period after the `{1}`.

I assume the original reason for this was the details was a full sentence by itself with a period already, however, going by Issue #5094 this property isn't in use anymore and will be removed.

**Comment by rnveach** [comment]
@victorwss Please squash and keep all commits as 1.
@romani CI is currently passing. I think we can merge this once squashed.

**Comment by romani** [comment]
@victorwss , thanks a lot.

**Comment by victorwss** [comment]
@rvneach Well, since this was already been merged, next time I'll try to make it correctly in a single shot.

**Comment by romani** [comment]
if changes in translation trivial, please use commit message prefix "spelling: " to avoid referencing pull number.
Or create an issue on whole Portuguese translation and do changes steps by step(several PRs).

**Comment by romani** [comment]
>  what is the reason why some messages ends with periods while others doesn't?

no good reason, all translations come to us from community. Non of current maintainers speak any of non-English languages that we have in localizations.
It is community driven are of project, we do not have strict rules there, not now. But probably we need to write Check for this.

**Pull request merged**
