### PR TITLE
Issue #13345: Enable examples tests for AvoidInlineConditionalsCheck

### PR DESCRIPTION
**Pull request by AmitKumarDeoghoria**
### Title: Enable examples tests for AvoidInlineConditionalsCheck

**Related Issue: #13345** 

**Summary**
This pull request aims to enable example tests for the **AvoidInlineConditionalsCheck** in the project. The implementation focuses on ensuring that the AvoidInlineConditionals checks are correctly validated through comprehensive test cases, improving overall code reliability and quality.

**Key Changes Made**

- Conversion of txt file to Java File
- Enable the test cases by adding expected violations in the expected array for all example tests
- Made corresponding changes in the xml and xml.template file

### CODE REVIEW

**Comment by AmitKumarDeoghoria** [comment]
GitHub, generate website

**Comment by AmitKumarDeoghoria** [comment]
GitHub, generate website

**Review by romani — APPROVED** [review]
Thanks a lot.

Keep in mind all checks has rational, so the more you migrate the more you see what are best practices in java coding

**Comment by AmitKumarDeoghoria** [comment]
Thank you, @romani. I see it. Migrating these elements has been incredibly insightful and has deepened my understanding of best practices.I had no idea how much there was to learn.

**Pull request merged**
