### PR TITLE
Issue #10924: Update EmptyForInitializerPadCheck to use code points.

### PR DESCRIPTION
**Pull request by MUzairS15**
Issue #10924: Updated EmptyForInitializerPadCheck to use code points.
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/d0d6599dd257421f2e97c2237a7e9d8d/raw/50a659961e7cd57d052ac01c14dff0fcba07852e/config.xml

### CODE REVIEW

**Comment by MUzairS15** [comment]
Github, generate report

**Comment by MUzairS15** [comment]
```
src % cat config.xml Test.java 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name = "Checker">
    <property name="charset" value="UTF-8"/>

    <property name="severity" value="warning"/>

    <property name="fileExtensions" value="java, properties, xml"/>

    <module name="TreeWalker">
        <module name="EmptyForInitializerPad">
            <property name = "option" value = "space"/>
            </module>
    </module>

</module>

public class Test {

    void method1() {
        String s;
        int j = 0;
        s = "🤩a🤩🤩🤩🤩"; for (  ;j <s.length() // ok, but still reported
                && s.substring(j) =="🤩🧐";
              j++ ) {

        }

        s = "dadda da"; for (  ;j < s.length()
                && s.substring(j) == "dsad";
              j++ ) {

        }
    }
}
src % java -jar checkstyle-10.0-all.jar -c config.xml Test.java
Starting audit...
[WARN] /Users/shabana/Documents/OpenSource/CheckStyleTest/src/src/Test.java:6:30: ';' is not preceded with whitespace. [EmptyForInitializerPad]
Audit done.

**Comment by MUzairS15** [comment]
@nick-mancuso should I add Input with property as `nospace`?

**Review by nick-mancuso — APPROVED** [review]

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
Pitest codding
`EqualsAvoidNullCheck.java.html:<td class='covered'><pre><span  class='survived'>            if (field.findFirstToken(TokenTypes.IDENT) != null) {</span></pre></td></tr>`

Restarted

**Comment by nick-mancuso** [comment]
@MUzairS15 once this is merged, please rebase all your other PRs that depend on this one.

**Pull request merged**
