### PR TITLE
Issue #5338: moved, renamed and removed abstact declaration from Abst…

### PR DESCRIPTION
**Pull request by RoMaNiAsHkA**
Issue #5338: moved, renamed and removed abstact declaration from AbstractLoader. Also moved and renamed AbstractLoaderTest and fixed suppressions for intellij idea and checkstyle

### CODE REVIEW

**Comment by rnveach** [comment]
@romani Since this is also a backward breaking change, should we wait on merging this with PR https://github.com/checkstyle/checkstyle/pull/5324 ?

**Comment by RoMaNiAsHkA** [comment]
> Please remove the lines in intellij that say:
>                
>                <option value="AbstractClassExtendsConcreteClass" />
fixed

**Comment by romani** [comment]
it might sounds crazy ... but this class is in use https://github.com/search?l=Java&p=1&q=%22checkstyle.api.AbstractLoader%22&type=Code&utf8=%E2%9C%93
in most cases as full copy of checkstyle code, that even more crazy, but I hope they enjoy it like this.

**Comment by romani** [comment]
this is not very severe braking compatibility, I am ok to merge ti now.

**Pull request merged**
