### PR TITLE
Update Maven PMD Plugin to 3.5. #1300

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
good, but please refactor any ```return !(``` to avoid final inversion - is it bad practice and hard to read. Such Check is already implemented in Sevntu project, not yet enforced , but will be enforced soon.

**Comment by romani** [comment]
>         return !(expr.getType() != TokenTypes.LITERAL_RETURN
                || expr.getFirstChild().getType() != TokenTypes.EXPR);

that was missed, but has to be fixed.

**Comment by mkordas** [comment]
Done - can you check if this is what you meant?

**Comment by mkordas** [comment]
Well spotted, now it should be fixed.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
