### PR TITLE
Issue #2161: unify test input locations for javadoc package

### PR DESCRIPTION
**Pull request by rnveach**
new suppression needed
> JavadocMethodCheckTest.java:44: error: Total number of methods is 36 (max allowed is 35).

FileSetCheckLifecycleTest was using javadoc input files, but it doesn't look like it really needs a specific file, so I just picked one in its current directory.

### CODE REVIEW

**Comment by rnveach** [comment]
@romani please restart appveyor
> fatal: The remote end hung up unexpectedly

**Comment by romani** [comment]
checkstyle found an issue

**Comment by rnveach** [comment]
forgot the ".java" in the suppressions. fixed.

**Comment by rnveach** [comment]
@romani one travis node needs a restart

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
