### PR TITLE
minor: fix wrong Chinese translation of override

### PR DESCRIPTION
**Pull request by shiliyu**
Wrong Chinese translation: `override` was translated as `overload`. It's very confusing. BTW, happened to find a typo - fixed too!

### CODE REVIEW

**Comment by strkkk** [comment]
@shiliyu thanks for your contribution, please leave only 1 commit with changes in your branch (now you have merge commit included)

**Comment by shiliyu** [comment]
thx @strkkk. Got it.

**Comment by pbludov** [comment]
Interestingly, I never realized before that an "overridden method" actually is an "overwritten method".

**Comment by shiliyu** [comment]
surprise surprise :) you're very witty. @pbludov

**Pull request merged**
