### PR TITLE
Issue #5511: Header check fails with empty lines

### LINKED ISSUE #5511: HeaderCheck: fails with empty lines
'/var/tmp $ javac Test.java':

`/var/tmp $ cat Test.java`:

```
/*
  -----------------------------------------------------------------------------------

   example

   Copyright (c) 2001-2018 XXX

  -----------------------------------------------------------------------------------
*/

public class Test {

  public Test() {
  }
}
```

`/var/tmp $ cat checkstyle.header`:

```
/*
  -----------------------------------------------------------------------------------

   example

   Copyright (c) 2001-2018 XXX

  -----------------------------------------------------------------------------------
*/
```

`/var/tmp $ cat config.xml`:

```
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="Header">
    <property name="headerFile" value="checkstyle.header"/>
    <property name="fileExtensions" value="java"/>
  </module>
</module>
```

`/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.8-all.jar -c config.xml Test.java`:

```
Feb 05, 2018 8:00:11 PM com.puppycrawl.tools.checkstyle.Main runCli
FINE: Checkstyle debug logging enabled
Feb 05, 2018 8:00:11 PM com.puppycrawl.tools.checkstyle.Main runCli
FINE: Running Checkstyle with version: 8.8
Starting audit...
[ERROR] /data1/home/martin/x_checkstyle/Test.java:3: Line does not match expected header line of '^$'. [Header]
Audit done.
Checkstyle ends with 1 errors.
```

---------------

I found this issue upgrading from version 6.7 to 8.8.
The Header check does not match the empty lines like expected.
Looking through the CheckStyle source I would guess that the AbstractHeaderCheck method loadHeader is converting empty lines to "^$" what cannot work with the equals in the HeaderCheck isMatch method.

### PR DESCRIPTION
**Pull request by tshradheya**
Mandatory to understand and do:
Fixes #5511

**Outline of Solution**

- Moved checking of empty line to Regex as the logic is only for the Regxpheader check
- Header check empty line check shouldn't use regex

### CODE REVIEW

**Comment by rnveach** [comment]
@tshradheya Please also keep the number of commits at 1 for this issue.
https://github.com/checkstyle/checkstyle/wiki/PR-rules

**Comment by rnveach** [comment]
@tshradheya FYI
You don't have to close the PR when you rebase or amend commits.
The PR can stay open and when you force push new changes it will recognize them and re-run everything as it should.

**Comment by tshradheya** [comment]
@rnveach thanks for the information.

Actually, I am bit busy currently with other work and which is why I closed this PR.
Sorry!

**Comment by rnveach** [comment]
@tshradheya If you are giving up working on this issue, then let us know so other people can work on it instead.

**Comment by kemitix** [comment]
If no-one else is picking this up, I'm happy to do so.

**Comment by rnveach** [comment]
@kemitix Feel free to do so.

**Pull request closed without merging**
