### PR TITLE
Issue #11214: Specified violation messages in JavaNCSSCheck

### PR DESCRIPTION
**Pull request by coderdeadpool**
Issue #11214 
Specified violation messages in JavaNCSSCheck.

### CODE REVIEW

**Comment by coderdeadpool** [comment]
@Vyom-Yadav @romani I was getting error " Line should not be longer than 100 symbols [lineLength]",  so i changed this line to "NCSS: 2 (Max: 0)" but still getting errors. Please help me here.

**Comment by romani** [comment]
Please wrap line that exceed limit

**Comment by coderdeadpool** [comment]
@romani I tried wrapping line ```public void itemStateChanged(ItemEvente) { // violation 'NCSS for this method is 12 (max allowed is 0).'``` like this 
```            public void itemStateChanged(ItemEvent
                   e) { // violation 'NCSS for this method is 12 (max allowed is 0).'``` but still getting this error 
```
[ERROR] Failures:
[ERROR]   JavaNCSSCheckTest.test:65->AbstractModuleTestSupport.verifyWithInlineConfigParser:236->AbstractModuleTestSupport.verifyViolations:436 Violation lines for D:\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\metrics\javancss\InputJavaNCSS.java differ.
missing (1)   : 53
unexpected (1): 52
---
expected      : [12, 19, 24, 31, 40, 53, 60, 67, 72, 91, 92, 93, 94]
but was       : [12, 19, 24, 31, 40, 52, 60, 67, 72, 91, 92, 93, 94]
[INFO]
[ERROR] Tests run: 3957, Failures: 1, Errors: 0, Skipped: 1
```

**Comment by Vyom-Yadav** [comment]
@coderdeadpool You need to change the line number in the test case accordingly.

**Comment by coderdeadpool** [comment]
@Vyom-Yadav I did the change the line number in the test file too. but still getting the same error

**Comment by romani** [comment]
You do not need long name like itemStateChanged, shorten it.

>// violation 'NCSS for this method is 12 (max allowed is 0).

Shorten it
`// violation '.* is 12 (max allowed is 0).`

**Review by romani — APPROVED** [review]
Ok to merge if CI pass

**Comment by coderdeadpool** [comment]
@romani @Vyom-Yadav Thankyou for the help and Guidance :) .

**Pull request merged**
