### PR TITLE
German translations corrected

### PR DESCRIPTION
**Pull request by MrQNo**
Issue #3013: corrected google translations to proper german language

### CODE REVIEW

**Comment by romani** [comment]
https://travis-ci.org/checkstyle/checkstyle/jobs/114626315#L805

please redo commit and make commit a single line.
put a ref to this PR from commit, ,commit message should be "Pull #3017:  ....... "

**Comment by romani** [comment]
please squash all commits in one to resolve CI problems.

**Comment by romani** [comment]
Hm, we already have issue for this - https://github.com/checkstyle/checkstyle/issues/3013 , we need to reference #3013 in commit message.

**Comment by romani** [comment]
@MrQNo , new release will be at next Friday. It would be good if we finish this PR.
If you do not have time, I can redo your changes, just let me know.

**Comment by MrQNo** [comment]
Just redo. I simply have not the time to comply with all commit message format rules.

Mit freundlichen Grüßen
Christian H. Kuhn

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
