### PR TITLE
Issue #13345: Enable Test Cases for MethodNameCheckTest

### PR DESCRIPTION
**Pull request by Rohanraj123**
part of #13345

### CODE REVIEW

**Comment by romani** [comment]
@Rohanraj123 , before push to GitHub
Please execute "mvn clean verify" in terminal to be sure you are good.

https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/48120211/job/vqx2t0afv7vox8kt#L110

**Comment by Rohanraj123** [comment]
> @Rohanraj123 , before push to GitHub Please execute "mvn clean verify" in terminal to be sure you are good.
> 
> https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/48120211/job/vqx2t0afv7vox8kt#L110

Actually when i pushed the branch build was successfull. But then this problem occured after the CI checks over here. I know the issue now that trailing comma's needs to be removed from methodname.xml .

**Review by romani — APPROVED** [review]
Ok to merge.

**Comment by rnveach** [comment]
Please provide the differences between the old TXT file and the new Java file.

**Comment by romani** [comment]
@rnveach , diff is clearly seen in xdoc. As macros just copy content to xdoc from java file.

**Comment by Rohanraj123** [comment]
Am i supposed to show something here? Please let me know. Agree with  @romani sir's statement .

**Pull request merged**
