### PR TITLE
Coverage has been increased to 100% in MultilineDetector. Issue #1010

### PR DESCRIPTION
**Pull request by sabaka**
identical reports:
http://sabaka.github.io/MultilineDetector/master/checkstyle.html
http://sabaka.github.io/MultilineDetector/checkstyle.html

### CODE REVIEW

**Comment by romani** [comment]
windows build is not happy, please address it.

**Comment by romani** [comment]
@sabaka , please fix.

**Comment by sabaka** [comment]
It had to be fixed. Try to re run build please

**Comment by romani** [comment]
relaunched.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
