### PR TITLE
OneStatementPerLineCheck on multiple field initialization fix, issue #1237

### PR DESCRIPTION
**Pull request by MEZk**
@romani 
1) I did code refactoring to avoid duplication of the code in method getDefaultTokens since getDefaultTokens and getAcceptableTokens have the same content.

2) I removed dead code from visitSemi, so that code coverage for OneStatementPerLineCheck was increased.
Here are reports:
[before removing dead code] (http://mezk.github.io/site_before%28full%29/checkstyle.html)
[after removing dead code](http://mezk.github.io/site_after%28full%29/checkstyle.html)
git diff shows no differences.

3) I fixed bug with multiple field initialization and also provided additional tests to test [similar cases (issue #1237)](https://github.com/checkstyle/checkstyle/issues/1237). 
I ran checkstyle-tester and tested my changes with all projects which are specified at projects-to-test-on.properties.

Before my fix changes checkstyle-tester reports 3055 warnings and after my changes there are 2963 warnings. 
For example, before my changes OneStatementPerLineCheck reports that at ```Hbase/hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncProcess.java``` there is an illegal statement:
````java
private static HRegionInfo hri1r1 = RegionReplicaUtil.getRegionInfoForReplica(hri1, 1),
    hri1r2 = RegionReplicaUtil.getRegionInfoForReplica(hri1, 2);
````
but it isn't (according to issue #1237)

After the fix OneStatementPerLineCheck rises no violations for TestAsyncProcess.java.

And there are 92 similar cases. Should I send the full report because it is very huge (over 1.2 Gb) or should I report all 92 violations somehow? 

4) I also provided test inputs to cover my changes.
[cobertura report](http://mezk.github.io/cobertura/com.puppycrawl.tools.checkstyle.checks.coding.OneStatementPerLineCheck.html) after all changes.

### CODE REVIEW

**Comment by MEZk** [comment]
@romani 
http://mezk.github.io/index.html

**Comment by romani** [comment]
Please squash commits in one

**Comment by MEZk** [comment]
@romani 
Done

**Comment by romani** [comment]
1) 
> ```
    /**
     * While one statement is distributed over two or more lines.
     */
    private boolean distributedStatement;
```

name it "multilineStatement" the simple the name the better.


2)
> ```
private void visitSemiParent(DetailAST ast) {
```

Make it static  and assign value to filed in SWITCH.


3)
> ```
private void visitSemi(DetailAST ast) {
```

remove that method, move content of it to SWITCH.

4)
>```
private void visitExpr(DetailAST ast) {
```

please refactor that method to move "log" to SWITCH, and have method that return boolean to decided do violation or not.


5)
> ```
public void beginTree(DetailAST rootAST) {
```

are you sure that your new field should not be initialized there ?

6)
checkstyle.sourceforge.net/google_style.html

that Check is there, so please extend Integrational Tests for this Check -  checkstyle/src/it/java/com/google/checkstyle/test/chapter4formatting/rule43onestatement/OneStatementPerLineTest.java (it is ok to reuse Input from UTs).

7)
> I removed dead code from visitSemi, so that code coverage for OneStatementPerLineCheck was increased.

I do not see update for limits in pom.xml

8)
>``` private static HRegionInfo hri1r1 = RegionReplicaUtil.getRegionInfoForReplica(hri1, 1),
    hri1r2 = RegionReplicaUtil.getRegionInfoForReplica(hri1, 2);
```

That code should not raise any violation from this Check. Statements are separated by ";", multi-line-statement is not related.

9)
> Should I send the full report because it is very huge (over 1.2 Gb) or should I report all 92 violations somehow? 

Lets first verify that small reports are ok, and then we will decide about bigger reports.

**Comment by romani** [comment]
@MEZk , do you run into problem with such updates ?

**Comment by MEZk** [comment]
@romani 
I completely rework the check, because it detected only expression statements which are on the same line. I provided a bundle of UTs with comments to explain new check logic.

1) This variable was removed since it is not needed anymore.
>name it "multilineStatement" the simple the name the better.

2) Method visitSemiParent was removed since it is not needed anymore.
>Make it static and assign value to filed in SWITCH.

3) Method visitSemi was removed  and it content was moved to leaveToken according to new check logic.
>remove that method, move content of it to SWITCH.

4) Method visitExpr was removed since it is incorrect to check only expression statements. All 'log' was moved to visitToken.
>please refactor that method to move "log" to SWITCH, and have method that return boolean to decided do violation or not.

5) I removed 'multilineStatement' variable since it is not needed anymore.
>are you sure that your new field should not be initialized there ?

6) Done
>checkstyle.sourceforge.net/google_style.html
that Check is there, so please extend Integrational Tests for this Check - checkstyle/src/it/java/com/google/checkstyle/test/chapter4formatting/rule43onestatement/OneStatementPerLineTest.java (it is ok to reuse Input from UTs).

7) Done (100% test coverage)
>I do not see update for limits in pom.xml

8) Yes, it's fine.
>That code should not raise any violation from this Check. Statements are separated by ";", multi-line-statement is not related.

9) [REPORTS] (http://mezk.github.io)

**Pull request closed without merging**
