### PR TITLE
Issue #3847: wrong processing of return

### LINKED ISSUE #3847: NPathComplexity: wrong processing of return
from pdf specifcation of NPath algorithm
> return Statement
The return statement terminates the execution of a
C function. A return statement can also contain an
expression. Therefore, the complexity of the return
statement is NP(( expr )).

```
/var/tmp$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <module name="TreeWalker">
        <module name="NPathComplexity">
            <property name="max" value="1"/>
        </module>
    </module>
</module>

/var/tmp$ cat Demo.java 
public class Demo {
    public boolean getResult(boolean a, boolean b, boolean c) {
        return a || b || c;
    }
}


/var/tmp$ java -jar checkstyle-7.4-all.jar -c config.xml Demo.java
Starting audit...
Audit done.
```

Expected:
`[WARN] /var/tmp/Demo.java:2:5: NPath Complexity is 2 (max allowed is 1). [NPathComplexity]` 

Xdoc also need to be fixed, to make in table for `return` "Complexity expression = NP(expr)".

### PR DESCRIPTION
**Pull request by Venkatesh-24**
Closes #3847 

http://checkstyle.sourceforge.net/config_metrics.html#NPathComplexity

**Test.java**
```
public class Test {
    public boolean getResult(boolean a, boolean b, boolean c) {
        return a || b || c;  // NP(expr) + 1 => 1 + 1 = 2
    }

    // return - NP(return) = 1
    // NP(expr) = 1 
    // Total NP = 1 + 1 = 2
}

Starting audit...
[WARN] /home/loges/Documents/Venkatesh Interview/gsoc/checkstyle/Test.java:2:5: NPath Complexity is 2 (max allowed is 1). [NPathComplexity]
Audit done.
```
**config.xml**
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <module name="TreeWalker">
        <module name="NPathComplexity">
            <property name="max" value="1"/>
        </module>
    </module>
</module>
```

### CODE REVIEW

**Comment by Venkatesh-24** [comment]
Please review it @romani

**Comment by rnveach** [comment]
@Venkatesh-24 Issue is reporting bad handling of return logic in check at https://github.com/checkstyle/checkstyle/issues/3847#issue-209001798 .
Add a new test case to show the issue that needs to be fixed or that it is already fixed and this can indeed close the issue as your first post states.

**Comment by Venkatesh-24** [comment]
Hi @rnveach In #3847 this was the expected error to occur for the return statement so I made a PR showing that. Am I assuming something wrong ?? . Can you please elaborate on what I should do.

**Comment by Venkatesh-24** [comment]
Should I need to make max value as 2 in config.xml

**Comment by romani** [comment]
You need to do changes at NPathComplexityCheck.java NPathComplexityCheckTest.java and creation of some new Input files for test methods

**Comment by romani** [comment]
Github, rebase

**Comment by romani** [comment]
@Venkatesh-24 , ping, please continue PR

**Comment by Venkatesh-24** [comment]
Sorry @romani  I should have informed I am going to take up my semester exams I will not be able to contribute.

**Comment by romani** [comment]
No problem, see you later

**Pull request closed without merging**
