### PR TITLE
Issue #6658: increase mutation coverage for pitest-imports profile to 100% - IllegalImportCheck

### PR DESCRIPTION
**Pull request by developerhb**
Diff Regression config: https://gist.githubusercontent.com/developerhb/2ec7d4b5183dfeddd266be7a62aa3542/raw/e6d79a0407122a2798da3a0515fca3782b62e995/my_check.xml
Diff Regression projects: https://gist.githubusercontent.com/developerhb/2ec7d4b5183dfeddd266be7a62aa3542/raw/e6d79a0407122a2798da3a0515fca3782b62e995/projects-to-test-on.properties

### CODE REVIEW

**Comment by romani** [comment]
Travis was restarted.
CircleCI looks suspicious:
```
+InheritConfiguration.java.html:<td class='covered'><pre><span  class='survived'>                doMergeParent((DefaultConfiguration) parentChild, currentChild);</span></pre></td></tr>
+InheritConfiguration.java.html:<td class='covered'><pre><span  class='survived'>                if (id == null) {</span></pre></td></tr>
+InheritConfiguration.java.html:<td class='covered'><pre><span  class='survived'>            if (!currentAttributeMap.containsKey(attr)) {</span></pre></td></tr>
+InheritConfiguration.java.html:<td class='covered'><pre><span  class='survived'>            if (!currentMessages.containsKey(key)) {</span></pre></td></tr>
+InheritConfiguration.java.html:<td class='covered'><pre><span  class='survived'>            if (list2.contains(name)) {</span></pre></td></tr>
+InheritConfiguration.java.html:<td class='covered'><pre><span  class='survived'>        else if (parentHasChildren) {</span></pre></td></tr>
+InheritConfiguration.java.html:<td class='covered'><pre><span  class='survived'>        final boolean parentHasChildren = !parents.isEmpty();</span></pre></td></tr>
+InheritConfiguration.java.html:<td class='covered'><pre><span  class='survived'>        if (children.length &#60; 1) {</span></pre></td></tr>
+InheritConfiguration.java.html:<td class='covered'><pre><span  class='survived'>        if (parentHasChildren &#38;&#38; currentChildren.isEmpty()) {</span></pre></td></tr>
+InheritConfiguration.java.html:<td class='covered'><pre><span  class='survived'>        mergeAttributes(parent, current);</span></pre></td></tr>
+InheritConfiguration.java.html:<td class='covered'><pre><span  class='survived'>        mergeMessages(parent, current);</span></pre></td></tr>
```

I surprised on output, restarted.

**Comment by romani** [comment]
@developerhb ,
now output it expected `-IllegalImportCheck.java.html:<td class='covered'><pre><span  class='survived'>        if (!result) {</span></pre></td></tr>` please remove this line from pitest allowances.
I restarting CI one more time to retest stability.

**Comment by developerhb** [comment]
@romani 
> now output it expected `-IllegalImportCheck.java.html:<td class='covered'><pre><span class='survived'> if (!result) {</span></pre></td></tr>` please remove this line from pitest allowances.
> I restarting CI one more time to retest stability.

Done

**Comment by romani** [comment]
Please share regression report to make sure no functional changes are detected, please do this by our GitHub action

**Comment by developerhb** [comment]
@romani 
> Please share regression report to make sure no functional changes are detected, please do this by our GitHub action

I have never used Github Action. Can you please guide me.
Also I would like to know why is codecov check failing.

**Comment by romani** [comment]
https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#executing-generation

You can review recent merged PR to see examples

**Comment by developerhb** [comment]
GitHub, generate report

**Comment by developerhb** [comment]
@romani Report is generated.

**Comment by romani** [comment]
Please explain difference in report

**Comment by developerhb** [comment]
> Please explain difference in report

I think its because of the config I used

```xml
<module name="TreeWalker">
         <!-- Example of checkstyle Check usage -->
         <!-- PLEASE CHANGE IT TO CHECK YOU ARE TESTING !!!! -->
         <module name="IllegalImport">
             <property name="regexp" value="true"/>
             <property name="illegalPkgs" value="java\.util"/>
             <property name="illegalClasses"
             value="^java\.util\.(List|Arrays), ^java\.sql\.Connection"/>
         </module>

         <!-- Example of sevntu.checkstyle Check usage -->
         <!-- <module name="NestedSwitchCheck"/> -->

         <!-- usuppress javadoc parsing errors, as we test Check not a parser -->
         <module name="SuppressionXpathSingleFilter">
            <property name="message" value="Javadoc comment at column \d+ has parse error"/>
         </module>

    </module>
```

**Comment by romani** [comment]
if you found a difference it means that code is working differently with and without your change, so just take this config and input file with diff and this will be a coverage for removed IF.

**Comment by developerhb** [comment]
@romani What is my next task? How can I solve this diff problem?

**Comment by developerhb** [comment]
@romani I think I should first generate report with hard coded mutation branch and then come here again. For that I need to create a new pull request that is just for report generation purpose and not for merging. Should I go on with this?

**Comment by developerhb** [comment]
@romani I find the coverage. I am implementing it.

**Comment by developerhb** [comment]
GitHub, generate report

**Comment by developerhb** [comment]
@romani I run the regression in local only on checkstyle project and I am not getting any difference.

Here is the command I used
`groovy diff.groovy --localGitRepo ../../../College/checkstyle --baseBranch master --patchBranch 6658-pitest-imports-mutation-coverge-illegalimportcheck --config my_check.xml --listOfProjects projects-to-test-on.properties`

I have used same config that I used in generating report using Github Action.
Then also I am posting it here.

**my_check.xml**
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <property name="charset" value="UTF-8"/>

    <!-- do not change severity to 'error', as that will hide errors caused by exceptions -->
    <property name="severity" value="warning"/>

    <!-- haltOnException is required for exception fixes and reporting of all exceptions -->
    <property name="haltOnException" value="false"/>

    <!-- BeforeExecutionFileFilters is required for sources of java9 -->
    <module name="BeforeExecutionExclusionFileFilter">
        <property name="fileNamePattern" value="module\-info\.java$" />
    </module>

    <module name="TreeWalker">
         <!-- Example of checkstyle Check usage -->
         <!-- PLEASE CHANGE IT TO CHECK YOU ARE TESTING !!!! -->
         <module name="IllegalImport">
             <property name="regexp" value="true"/>
             <property name="illegalPkgs" value="java\.util"/>
             <property name="illegalClasses"
             value="^java\.util\.(List|Arrays), ^java\.sql\.Connection"/>
         </module>

         <!-- Example of sevntu.checkstyle Check usage -->
         <!-- <module name="NestedSwitchCheck"/> -->

         <!-- usuppress javadoc parsing errors, as we test Check not a parser -->
         <module name="SuppressionXpathSingleFilter">
            <property name="message" value="Javadoc comment at column \d+ has parse error"/>
         </module>
    </module>
    <!-- Example of filter -->
    <!--
    <module name="SeverityMatchFilter">
        <property name="severity" value="warning"/>
        <property name="acceptOnMatch" value="false"/>
    </module>
    -->

    <!-- as we run on regression even on non-compiled files we need to skip exceptions on them -->
    <module name="SuppressionSingleFilter">
      <property name="message" value="Exception occurred while parsing"/>
      <property name="checks" value="Checker"/>
    </module>
</module>

```

I cannot post the report here as I am facing `File Limit Exceeded` issue on Windows. But I would recommend that you try it on local and github action both in case I am making some mistake if you have some time.

Also I explained the logic why removing IF condition will not make any change in comment https://github.com/checkstyle/checkstyle/issues/6658#issuecomment-675299999

**Comment by romani** [comment]
@strkkk , can you help here ?

**Comment by romani** [comment]
I confirm problem in remote diff generator.

On local no changes
```
08:04 $ git diff
diff --git a/checkstyle-tester/my_check.xml b/checkstyle-tester/my_check.xml
index 2681927..5d62e68 100644
--- a/checkstyle-tester/my_check.xml
+++ b/checkstyle-tester/my_check.xml
@@ -20,8 +20,11 @@
     <module name="TreeWalker">
          <!-- Example of checkstyle Check usage -->
          <!-- PLEASE CHANGE IT TO CHECK YOU ARE TESTING !!!! -->
-         <module name="ThrowsCount">
-             <property name="max" value="20000000"/>
+         <module name="IllegalImport">
+             <property name="regexp" value="true"/>
+             <property name="illegalPkgs" value="java\.util"/>
+             <property name="illegalClasses"
+             value="^java\.util\.(List|Arrays), ^java\.sql\.Connection"/>
          </module>
 
          <!-- Example of sevntu.checkstyle Check usage -->
diff --git a/checkstyle-tester/projects-to-test-on.properties b/checkstyle-tester/projects-to-test-on.properties
index 5a85db6..add9ce5 100644
--- a/checkstyle-tester/projects-to-test-on.properties
+++ b/checkstyle-tester/projects-to-test-on.properties
@@ -4,7 +4,7 @@
 
 # Few projects that delivers set of unusual Java constructions that shall be correctly handled by AST visitor
 # 'InputAllEscapedUnicodeCharacters' must be skipped because it is too big and slows down JXR
-#checkstyle|git|https://github.com/checkstyle/checkstyle.git|master|**/checkstyle/src/test/resources-noncompilable/**/*,**/InputAllEscapedUnicodeCharacters.java
+checkstyle|git|https://github.com/checkstyle/checkstyle.git|master|**/checkstyle/src/test/resources-noncompilable/**/*,**/InputAllEscapedUnicodeCharacters.java
 #sevntu-checkstyle|git|https://github.com/sevntu-checkstyle/sevntu.checkstyle|master||
 #checkstyle-sonar|git|https://github.com/checkstyle/sonar-checkstyle|master||

 
$ groovy diff.groovy --localGitRepo ~/java/github/checkstyle/checkstyle --baseBranch master \
  --patchBranch developerhb/6658-pitest-imports-mutation-coverge-illegalimportcheck \
  --config my_check.xml --listOfProjects projects-to-test-on.properties
```

report is withtout diff.

**Comment by romani** [comment]
GitHub, generate report

**Comment by romani** [comment]
@developerhb , please keep syncing upstream master to your forked master
https://checkstyle.org/beginning_development.html#Starting_Development
```
 6) Update current branch and local master by pulling changes that were done
by other contributors:

          git checkout master
          git pull upstream master
          git push origin master
        
```

**Comment by strkkk** [comment]
This is probably because of girhub action job is using fork master instead of main repo master. It is resolved now and regenerated report should be fine

**Comment by developerhb** [comment]
> @developerhb , please keep syncing upstream master to your forked master

Okay @romani I will do it.

**Comment by developerhb** [comment]
> This is probably because of girhub action job is using fork master instead of main repo master. It is resolved now and regenerated report should be fine

Thank you @strkkk

**Review by romani — APPROVED** [review]

**Pull request merged**
