### PR TITLE
Issue #13213: Remove '//ok' comments from 'coding' package

### PR DESCRIPTION
**Pull request by Rohanraj123**
part of #13213 

Link to check coding Folder : https://github.com/checkstyle/checkstyle/tree/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding

### CODE REVIEW

**Comment by nrmancuso** [comment]
@Rohanraj123 this PR is massive, please pick a single check to work on.

**Comment by romani** [comment]
Yes, all other changes you can send in separate PRs.
Please split and review CI failures and address them

**Comment by Rohanraj123** [comment]
@nrmancuso Sir, you want me to pick one check like https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation
these. And then make different PR's on that. Right?

**Comment by nrmancuso** [comment]
@Rohanraj123 see comment at https://github.com/checkstyle/checkstyle/issues/13213#issuecomment-1692754441 and corresponding PR at #13609 as example

**Comment by Rohanraj123** [comment]
@nrmancuso Sorry sir for the inconvenience, I close this PR and will open the new one for new checks

**Pull request closed without merging**
