### PR TITLE
Update examples for EMBEDDED_EXPRESSION tokens, issue-#14317

### PR DESCRIPTION
**Pull request by ViswanathBalla22**
## Summary

This pull request addresses issue #14317 by updating examples for the following tokens:

- `EMBEDDED_EXPRESSION_BEGIN`
- `EMBEDDED_EXPRESSION`
- `EMBEDDED_EXPRESSION_END`

## Changes
Updated the example code to illustrate how " are rendered in the tree when using the `STR` token:
String s = STR."Hello, \{getName(firstName, lastName)}!";
to:
String s = STR."Hello, \{getName("Mr. ", firstName, lastName)}!";

### CODE REVIEW

**Comment by nrmancuso** [comment]
@ViswanathBalla22 you will need to take time to read through our command line documentation: https://checkstyle.sourceforge.io/cmdline.html

We expect the abstract syntax tree representation in the javadoc you are updating to match the code you are changing in the example. In order to complete this issue, you will need to do the folllowing:
1. Download the latest checkstyle jar
2. Create an input file, compilable with Java 21, that uses the code in your updated examples
3. Use the Checkstyle command line to print out the AST
4. Trim and edit the printed AST
5. Replace the code and AST in the javadocs for these examples

Example of checkstyle execution and output:
```
➜  src javac --enable-preview --release 21 Test.java
Note: Test.java uses preview features of Java SE 21.
Note: Recompile with -Xlint:preview for details.
➜  src javac --enable-preview --release 21 Test.java
Note: Test.java uses preview features of Java SE 21.
Note: Recompile with -Xlint:preview for details.
➜  src cat Test.java 
public class Test {
    static String firstName = "John";
    static String lastName = "Doe";

    public static void main(String[] args) {
        String s = STR."Hello, \{getName(firstName, lastName)}!";
    }

    static String getName(String firstName, String lastName) {
        return firstName + " " + lastName;
    }
}
➜  src java -jar checkstyle-10.12.8-SNAPSHOT-all.jar -t Test.java 
COMPILATION_UNIT -> COMPILATION_UNIT [1:0]
`--CLASS_DEF -> CLASS_DEF [1:0]      checkstyle-10.12.8-SNAPSHOT-all.jar                                     
    |--MODIFIERS -> MODIFIERS [1:0]
    |   `--LITERAL_PUBLIC -> public [1:0]
    |--LITERAL_CLASS -> class [1:7]
    |--IDENT -> Test [1:13]
    `--OBJBLOCK -> OBJBLOCK [1:18]
        |--LCURLY -> { [1:18]
        |--VARIABLE_DEF -> VARIABLE_DEF [2:4]
        |   |--MODIFIERS -> MODIFIERS [2:4]
        |   |   `--LITERAL_STATIC -> static [2:4]
        |   |--TYPE -> TYPE [2:11]
        |   |   `--IDENT -> String [2:11]
        |   |--IDENT -> firstName [2:18]
        |   |--ASSIGN -> = [2:28]
        |   |   `--EXPR -> EXPR [2:30]
        |   |       `--STRING_LITERAL -> "John" [2:30]
        |   `--SEMI -> ; [2:36]
        |--VARIABLE_DEF -> VARIABLE_DEF [3:4]
        |   |--MODIFIERS -> MODIFIERS [3:4]
        |   |   `--LITERAL_STATIC -> static [3:4]
        |   |--TYPE -> TYPE [3:11]
        |   |   `--IDENT -> String [3:11]
        |   |--IDENT -> lastName [3:18]
        |   |--ASSIGN -> = [3:27]
        |   |   `--EXPR -> EXPR [3:29]
        |   |       `--STRING_LITERAL -> "Doe" [3:29]
        |   `--SEMI -> ; [3:34]
        |--METHOD_DEF -> METHOD_DEF [5:4]
        |   |--MODIFIERS -> MODIFIERS [5:4]
        |   |   |--LITERAL_PUBLIC -> public [5:4]
        |   |   `--LITERAL_STATIC -> static [5:11]
        |   |--TYPE -> TYPE [5:18]
        |   |   `--LITERAL_VOID -> void [5:18]
        |   |--IDENT -> main [5:23]
        |   |--LPAREN -> ( [5:27]
        |   |--PARAMETERS -> PARAMETERS [5:28]
        |   |   `--PARAMETER_DEF -> PARAMETER_DEF [5:28]
        |   |       |--MODIFIERS -> MODIFIERS [5:28]
        |   |       |--TYPE -> TYPE [5:28]
        |   |       |   |--IDENT -> String [5:28]
        |   |       |   `--ARRAY_DECLARATOR -> [ [5:34]
        |   |       |       `--RBRACK -> ] [5:35]
        |   |       `--IDENT -> args [5:37]
        |   |--RPAREN -> ) [5:41]
        |   `--SLIST -> { [5:43]
        |       |--VARIABLE_DEF -> VARIABLE_DEF [6:8]
        |       |   |--MODIFIERS -> MODIFIERS [6:8]
        |       |   |--TYPE -> TYPE [6:8]
        |       |   |   `--IDENT -> String [6:8]
        |       |   |--IDENT -> s [6:15]
        |       |   `--ASSIGN -> = [6:17]
        |       |       `--EXPR -> EXPR [6:22]
        |       |           `--DOT -> . [6:22]
        |       |               |--IDENT -> STR [6:19]
        |       |               `--STRING_TEMPLATE_BEGIN -> " [6:23]
        |       |                   |--STRING_TEMPLATE_CONTENT -> Hello,  [6:24]
        |       |                   |--EMBEDDED_EXPRESSION_BEGIN -> \{ [6:31]
        |       |                   |--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [6:40]
        |       |                   |   `--METHOD_CALL -> ( [6:40]
        |       |                   |       |--IDENT -> getName [6:33]
        |       |                   |       |--ELIST -> ELIST [6:41]
        |       |                   |       |   |--EXPR -> EXPR [6:41]
        |       |                   |       |   |   `--IDENT -> firstName [6:41]
        |       |                   |       |   |--COMMA -> , [6:50]
        |       |                   |       |   `--EXPR -> EXPR [6:52]
        |       |                   |       |       `--IDENT -> lastName [6:52]
        |       |                   |       `--RPAREN -> ) [6:60]
        |       |                   |--EMBEDDED_EXPRESSION_END -> } [6:61]
        |       |                   |--STRING_TEMPLATE_CONTENT -> ! [6:62]
        |       |                   `--STRING_TEMPLATE_END -> " [6:63]
        |       |--SEMI -> ; [6:64]
        |       `--RCURLY -> } [7:4]
        |--METHOD_DEF -> METHOD_DEF [9:4]
        |   |--MODIFIERS -> MODIFIERS [9:4]
        |   |   `--LITERAL_STATIC -> static [9:4]
        |   |--TYPE -> TYPE [9:11]
        |   |   `--IDENT -> String [9:11]
        |   |--IDENT -> getName [9:18]
        |   |--LPAREN -> ( [9:25]
        |   |--PARAMETERS -> PARAMETERS [9:26]
        |   |   |--PARAMETER_DEF -> PARAMETER_DEF [9:26]
        |   |   |   |--MODIFIERS -> MODIFIERS [9:26]
        |   |   |   |--TYPE -> TYPE [9:26]
        |   |   |   |   `--IDENT -> String [9:26]
        |   |   |   `--IDENT -> firstName [9:33]
        |   |   |--COMMA -> , [9:42]
        |   |   `--PARAMETER_DEF -> PARAMETER_DEF [9:44]
        |   |       |--MODIFIERS -> MODIFIERS [9:44]
        |   |       |--TYPE -> TYPE [9:44]
        |   |       |   `--IDENT -> String [9:44]
        |   |       `--IDENT -> lastName [9:51]
        |   |--RPAREN -> ) [9:59]
        |   `--SLIST -> { [9:61]
        |       |--LITERAL_RETURN -> return [10:8]
        |       |   |--EXPR -> EXPR [10:31]
        |       |   |   `--PLUS -> + [10:31]
        |       |   |       |--PLUS -> + [10:25]
        |       |   |       |   |--IDENT -> firstName [10:15]
        |       |   |       |   `--STRING_LITERAL -> " " [10:27]
        |       |   |       `--IDENT -> lastName [10:33]
        |       |   `--SEMI -> ; [10:41]
        |       `--RCURLY -> } [11:4]
        `--RCURLY -> } [12:0]



```

You will need to update the method in my example to accept the new parameter, `"Mr. ".

**Comment by ViswanathBalla22** [comment]
hi @nrmancuso,

Thank you for your feedback and guidance. I'm relatively new to contributing, and I appreciate your detailed instructions.

During the setup and testing process, I encountered some challenges as a new contributor. I wanted to mention that this experience helped me learn more about the project, and I'm grateful for your guidance in navigating through it.

I will make the necessary adjustments following your instructions, and I hope to improve with each contribution. If there are any specific resources or documentation that could aid me in better understanding the process, please feel free to point me in the right direction.

Thank you once again for your patience and support.

**Comment by nrmancuso** [comment]
@ViswanathBalla22 if this issue is giving you trouble, it is totally OK to close this PR and pick up a https://github.com/checkstyle/checkstyle/labels/good%20first%20issue `good first issue` to help to understand our workflow and ramp up. Thanks for your efforts!

**Comment by ViswanathBalla22** [comment]
hi @nrmancuso ,
           In a separate environment, I created a config.xml file for Checkstyle and used the latest Checkstyle JAR to validate a Test.java file. The code in Test.java returns "Mr." based on the provided instructions. After confirming that the Checkstyle validation is successful and the code meets the required standards, I plan to update the corresponding Javadocs in the main codebase with the revised code and Abstract Syntax Tree (AST) representation, This is the approach I understand
  Is this correct way to do or this is wrong way I understand, can you give me any suggestions. And this my first contribution in open source and  thats why I am little bit talking slow to understand, but I will try my best to continue the journey in checkstyle.

**Comment by ViswanathBalla22** [comment]
Hi @nrmancuso ,

While setting up Checkstyle , I encountered an issue when using the mvn install command. The error message I received is as follows:
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.932 s
[INFO] Finished at: 2024-02-03T16:20:01+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: pre-clean, clean, post-clean, validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException

**Pull request closed without merging**
