### PR TITLE
Issue #5832: Add javadoc and xdoc Example for ClassTypeParameterName

### PR DESCRIPTION
**Pull request by jack870131**
#5832

### CODE REVIEW

**Comment by jack870131** [comment]
**CLI Test Result:**

```
Jack@Jack MINGW64 ~/Documents/tmp (master)
$ javac TestClassTypeParameterNameCheck.java

Jack@Jack MINGW64 ~/Documents/tmp (master)
$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="ClassTypeParameterName">
      <property name="severity" value="warning"/>
      <property name="format" value="^[a-zA-Z]$"/>
    </module>
  </module>
</module>

Jack@Jack MINGW64 ~/Documents/tmp (master)
$ cat TestClassTypeParameterNameCheck.java
class MyClass1<T> {} // OK
class MyClass2<t> {} // OK
class MyClass3<abc> {} // violation, the class type parameter
                       // name should match the regular expression "^[a-zA-Z]$"
Jack@Jack MINGW64 ~/Documents/tmp (master)
$ RUN_LOCALE="-Duser.language=en -Duser.country=US"

Jack@Jack MINGW64 ~/Documents/tmp (master)
$ java $RUN_LOCALE -jar checkstyle-8.11-all.jar -c config.xml TestClassTypeParameterNameCheck.java
Starting audit...
[WARN] C:\Users\asus\Documents\tmp\TestClassTypeParameterNameCheck.java:3:16: Name 'abc' must match pattern '^[a-zA-Z]$'. [ClassTypeParameterName]
Audit done.
```

**Comment by jack870131** [comment]
@romani @rnveach Request a review here. Thanks.

**Comment by romani** [comment]
@jack870131 , after any change in PR, please do a comment as DONE, to let me be notified.

**Comment by romani** [comment]
@rnveach , ping.
Please let me know if you have no time to do this, I will merge this my self, fix is non functional.

**Pull request merged**
