### PR TITLE
Issue #4437: Modified CustomImportOrderCheckTest.java and moved its input files to the customimportorder subdirectory

### PR DESCRIPTION
**Pull request by subkrish**
Issue #4437

This PR moves all inputs of CustomImportOrderCheckTest of the imports package to a new subdirectory 'customimportorder'.

### CODE REVIEW

**Comment by subkrish** [comment]
Do I need to change the name of the input files to match their corresponding tests?

**Comment by rnveach** [comment]
@ps-sp Do you have any insight into this travis error since it is your test?
> [ERROR] testBehaviourWithOnlyCommentChecks(com.puppycrawl.tools.checkstyle.TreeWalkerTest)  Time elapsed: 0.141 s  <<< FAILURE!
org.mockito.exceptions.verification.TooManyActualInvocations: 
com.puppycrawl.tools.checkstyle.TreeWalker.appendHiddenCommentNodes(
    null
);
Wanted 1 time but was 2 times.

It is weird tests don't fail until code coverage is run.

**Comment by rnveach** [comment]
@subkrish Please rebase over latest master to fix travis.

**Comment by rnveach** [comment]
@subkrish Please notify us when you make changes, we don't receive notifications on new commits.
This is why we ask everyone to say `Done` to each item we ask.

**Pull request merged**
