### PR TITLE
Issue #7657: Update doc for ReturnCount

### LINKED ISSUE #7657: Update doc for ReturnCount
https://checkstyle.org/config_coding.html#ReturnCount

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

### PR DESCRIPTION
**Pull request by Binita-tech**
Fixes #7657 
**$ cat config.xml**
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
      <module name="ReturnCount">
  <property name="max" value="3"/>
</module>
</module>
</module>
```
**$ cat MyClass.java**
```
public class MyClass {
public int method1(int x) {
if (x &lt; 0) return -1;
if (x == 0) return 1;
 return 0;
} // OK
public int method2(int x) {
if (x &lt; -2) return -2;
if (x == 0) return 0;
if (x &gt; 2) return 2;
 return 1;
 } // violation, more than three return statements
}

```
```
PS C:\Users\Dell\Desktop\Checkstyle\Test> javac MyClass.java
PS C:\Users\Dell\Desktop\Checkstyle\Test> java -jar checkstyle-9.2-all.jar -c config.xml MyClass.java
Starting audit...
[ERROR] C:\Users\Dell\Desktop\Checkstyle\Test\MyClass.java:11:5: Return count is 4 (max allowed for non-void methods/lambdas is 3). [ReturnCount]
Audit done.
Checkstyle ends with 1 errors.
```
**$ cat config.xml**
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
      <module name="ReturnCount">
  <property name="maxForVoid" value="0"/>
</module>
</module>
</module>
```
**$ cat MyClass.java**
```
public class MyClass {
public void method1(int x) { } // OK
public void method2(int x) { return; } // violation, return statements per void method
}

```
```
PS C:\Users\Dell\Desktop\Checkstyle\Test> javac MyClass.java
PS C:\Users\Dell\Desktop\Checkstyle\Test> java -jar checkstyle-9.2-all.jar -c config.xml MyClass.java
Starting audit...
[ERROR] C:\Users\Dell\Desktop\Checkstyle\Test\MyClass.java:4:1: Return count is 1 (max allowed for void methods/constructors/lambdas is 0). [ReturnCount]
Audit done.
Checkstyle ends with 1 errors.
```
**$ cat config.xml**
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
      <module name="ReturnCount">
  <property name="max" value="2"/>
  <property name="maxForVoid" value="1"/>
</module>
</module>
</module>
```
**$ cat MyClass.java**
```
public class MyClass {
public void method1() { } // OK
public void method2() { return; } // OK
public void method3(int x) {
if (x == 0) return;
return;
} // violation, more than one return statements
public int method1(int x) {
if (x &lt; 0) return -1;
return 0;
} // OK
public int method2(int x) {
if (x &lt; 0) return -1;
if (x == 0) return 1;
return 0;
 } // violation, more than two return statements in methods
}

```
```
PS C:\Users\Dell\Desktop\Checkstyle\Test> javac MyClass.java
PS C:\Users\Dell\Desktop\Checkstyle\Test> java -jar checkstyle-9.2-all.jar -c config.xml MyClass.java
Starting audit...
[ERROR] C:\Users\Dell\Desktop\Checkstyle\Test\MyClass.java:5:1: Return count is 2 (max allowed for void methods/constructors/lambdas is 1). [ReturnCount]
[ERROR] C:\Users\Dell\Desktop\Checkstyle\Test\MyClass.java:13:4: Return count is 3 (max allowed for non-void methods/lambdas is 2). [ReturnCount]
Audit done.
Checkstyle ends with 2 errors.

```
**$ cat config.xml**
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
     <module name="ReturnCount">
  <property name="max" value="3"/>
  <property name="format" value="^$"/>
</module>
</module>
</module>
```
**$ cat MyClass.java**
```
public class MyClass {
public int method1(int x) {
if (x &lt; 0) return -1;
if (x == 0) return 1;
return 0;
} // OK
public int method2(int x) {
if (x &lt; -2) return -2;
if (x == 0) return 0;
if (x &gt; 2) return 2;
return 1;
 } // violation, more than three return statements per method for all methods
}


```
```
PS C:\Users\Dell\Desktop\Checkstyle\Test> javac MyClass.java
PS C:\Users\Dell\Desktop\Checkstyle\Test> java -jar checkstyle-9.2-all.jar -c config.xml MyClass.java
Starting audit...
[ERROR] C:\Users\Dell\Desktop\Checkstyle\Test\MyClass.java:8:5: Return count is 4 (max allowed for non-void methods/lambdas is 3). [ReturnCount]
Audit done.
Checkstyle ends with 1 errors.
```
**$ cat config.xml**
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
     <module name="ReturnCount">
  <property name="max" value="0"/>
  <property name="tokens" value="CTOR_DEF"/>
</module>
<module name="ReturnCount">
  <property name="max" value="1"/>
  <property name="tokens" value="LAMBDA"/>
</module>
<module name="ReturnCount">
  <property name="max" value="2"/>
  <property name="tokens" value="METHOD_DEF"/>
</module>
</module>
</module>
```
**$ cat MyClass.java**
```
public class MyClass {
public class test1 {
public test1() { } // OK
}
public class test2 {
public test2() { return; } // OK
}
Operation test5 = (int x, int y) -&gt; x + y; // OK
Operation test6 = (int x, int y) -&gt; { return x + y; }; // Ok
Operation test7 = (int x, int y) -&gt; {
if (x > y) return x - y;
return x + y;
}; // violation, more than one return statement in lambda expressions
interface Operation {
int operation(int x, int y);
}
public int method1(int x) {
if (x > 0) return -1;
return 0;
} // OK
public int method2(int x) {
if (x &lt; 0) return -1;
if (x == 0) return 1;
return 0;
 } // violation, more than two return statements in methods
}

```
```
PS C:\Users\Dell\Desktop\Checkstyle\Test> javac MyClass.java
PS C:\Users\Dell\Desktop\Checkstyle\Test> java -jar checkstyle-9.2-all.jar -c config.xml MyClass.java
Starting audit...
[ERROR] C:\Users\Dell\Desktop\Checkstyle\Test\MyClass.java:10:36: Return count is 2 (max allowed for non-void methods/lambdas is 1). [ReturnCount]
[ERROR] C:\Users\Dell\Desktop\Checkstyle\Test\MyClass.java:20:4: Return count is 3 (max allowed for non-void methods/lambdas is 2). [ReturnCount]
Audit done.
Checkstyle ends with 2 errors.

```

### CODE REVIEW

**Comment by romani** [comment]
@Binita-tech, please make sure that all examples are compilable, please show it in PR description as javac tool compile them.

Please make sure that "mvn verify" pass on your local before you push code to GitHub and be before you do PR

**Comment by Binita-tech** [comment]
@romani, I am getting this error while running `mvn clean verify`
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.199 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest
[ERROR] testAllCheckSectionJavaDocs  Time elapsed: 1.199 s  <<< ERROR!
java.lang.Error: Error was thrown while processing src\main\java\com\puppycrawl\tools\checkstyle\checks\coding\ReturnCountCheck.java
        at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.examineCheckSection(XdocsJavaDocsTest.java:194)
        at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.testAllCheckSectionJavaDocs(XdocsJavaDocsTest.java:167)
Caused by: org.opentest4j.AssertionFailedError:
ReturnCount's class-level JavaDoc ==> expected: <

Please direct me in right direction

**Comment by romani** [comment]
Please compile your input files: `javac MyClass.java` and all others.

**Comment by Binita-tech** [comment]
After running `javac MyClass.java`, it is showing  error because I have used the same name again and again
Like this:
```
public MyClass(){ }; // OK
  public MyClass(){return;} // OK
  public MyClass(){return 0;} // violation, doesn't allow any return statements in constructors
```
Error:
`MyClass.java:5: error: constructor MyClass() is already defined in class MyClass
`

**Comment by romani** [comment]
yes, please fix compilation problems.
Checkststyle can not be executed on non-compiled sources it is limitation.

https://github.com/checkstyle/checkstyle/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

> /var/tmp $ javac YOUR_FILE.java
#[[MAKE SURE THERE IS SUCCESSFUL COMPILATION]]

this section is on good reason

**Comment by Binita-tech** [comment]
Done @romani

**Comment by romani** [comment]
Github, generate website

**Comment by romani** [comment]
@Binita-tech , please review generated web site (you can do this on your local by https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations#how-to-generate-website-only ), please beautify your code a bit by indentation of it to make it looks good for people.

**Comment by Binita-tech** [comment]
Done @romani

**Comment by Binita-tech** [comment]
Github, generate website

**Comment by pbludov** [comment]
> Done @romani

@Binita-tech you missed the indentation request.

[This](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/71b5e47_2021120352/config_coding.html#SimplifyBooleanExpression_Examples) example is well indented and easy to read.

Please format all examples that you add in this PR.

**Comment by Binita-tech** [comment]
@pbludov, can you tell me please below the line is properly indented or not so that I can do this for the rest?
```
public class MyClass {
	public int method1(int x) {
		if (x < 0) return -1;
		if (x == 0) return 1;
		return 0;
	} // OK
	public int method2(int x) {
		if (x < -2) return -2;
		if (x == 0) return 0;
		if (x > 2) return 2;
		return 1;
	} // violation, more than three return statements
}
```

**Comment by pbludov** [comment]
> @pbludov, can you tell me please below the line is properly indented or not so that I can do same for the rest?

Much better. With one note: the `ReturnCount` check reports violations in the line containing the method name. So it should be more like
```java
public class MyClass {
  public int badSign(int x) {  // violation, more than one return statements
    if (x < 0)
      return -1;
    else if (x > 0)
      return 1;
    else
     return 0;
  }

  public int sign(int x) { // OK
    final int result
      if (x < 0)
        result = -1;
      else if (x > 0)
        result = 1;
      else
        result = 0;
      return result;
  }
}
```

**Comment by Binita-tech** [comment]
Can I only change the method name keeping the code same @pbludov?

**Comment by pbludov** [comment]
> Can I only change the method name keeping the code same @pbludov?

Sure.

**Comment by Binita-tech** [comment]
I am getting this error while running `mvn clean verify`, please direct me in right direction
```
[ERROR] Failed to execute goal com.groupon.maven.plugin.json:json-schema-validator:1.2.0:validate (default) on project checkstyle: Exception while locating input file; file=https://raw
.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json: Could not find resource 'https://raw.githubusercontent.com/oasis-tcs
/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json'. -> [Help 1]
```

**Comment by Binita-tech** [comment]
Done @pbludov

**Review by romani — CHANGES_REQUESTED** [review]
this line and all other lines should be indented by +2

please read https://github.com/checkstyle/checkstyle/pull/11102#issuecomment-1001052638

please read about indentation https://checkstyle.org/config_misc.html#Indentation

**Comment by Binita-tech** [comment]
```
public class MyClass {
  public int sign(int x) {
    if (x < 0)
      return -1;
    if (x == 0)
      return 1;
    return 0;
  } // OK

  public int badSign(int x) {
    if (x < -2)
      return -2;
    if (x == 0)
      return 0;
    if (x > 2)
      return 2;
    return 1;
  } // violation, more than three return statements
}
```
Is this indented properly @romani?

**Comment by romani** [comment]
yes, a way better code to read.

**Comment by Binita-tech** [comment]
Yesterday, I had re-cloned the repository and made changes to it again, and even after pushing the commit, the file changed is still the same and even checks are not restarting, should I close this PR and open a new PR @romani?

**Comment by romani** [comment]
you do not need to reclone.
please read attetively - https://checkstyle.org/beginning_development.html#Starting_Development

**Comment by Binita-tech** [comment]
Sorry for the inconvenience, I have read that document and understood also completely but I had mistakenly re-cloned yesterday, now it's creating the problem, please tell me what should I do next?

**Comment by romani** [comment]
push your local branch (with right changes) to github
`git push origin {your_branch_on_local} issue_7657 -f`

**Comment by Binita-tech** [comment]
I had to close this PR because the above command given by you hadn't solved the problem. I will make sure that this mistake will not happen again.

**Pull request closed without merging**
