### PR TITLE
Issue #4701: No error for a misplaced javadoc tag

### PR DESCRIPTION
**Pull request by pbludov**
Issue #4701

No error for a misplaced javadoc tag

Regression test https://pbludov.github.io/issue-4701/JavadocMethod/

### CODE REVIEW

**Comment by romani** [comment]
we need to send PR to Orekit with fix to pass CI.

regression report is strange .... I need a bit more time to understand it.

**Comment by romani** [comment]
I filed PR to Orekit project - https://github.com/CS-SI/Orekit/pull/17 , ones it is merged, Werker will fail again as new violation will be found  by this PR changes.

@pbludov , 
as your fix find new violation in Orekit https://pbludov.github.io/issue-4701/JavadocMethod/Orekit/index.html#A1, please open PR against PR to fix this problem.

**Comment by pbludov** [comment]
As I see, the violation is already fixed:
https://github.com/CS-SI/Orekit/commit/b13f6c3c49e184ca56982847aaabb48914a34c40#diff-6e5cfc624f4e772a78047759e8872936

When I've changed in contribution/checkstyle-tester/projects-to-test-on.properties
from
Orekit|git|https://github.com/CS-SI/Orekit|942785a5c79b5470baec3d41cab18f3adc78280e||
to
Orekit|git|https://github.com/CS-SI/Orekit|9.0.1||
a new violation was found:

https://www.orekit.org/site-orekit-development/apidocs/org/orekit/files/ccsds/TDMFile.ObservationsBlock.html#addObservation-java.lang.String-org.orekit.time.AbsoluteDate-double-

I sent a PR to fix it:
https://github.com/CS-SI/Orekit/pull/18

**Comment by romani** [comment]
@pbludov , please rebase on latest master to fix wercker (I did merged updated for it).

**Comment by romani** [comment]
> When I've changed in contribution/checkstyle-tester/projects-to-test-on.properties
from

please contribute this change to 
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L26
by PR.

**Pull request merged**
