### PR TITLE
Issue #5463 : Update messages.properties 

### PR DESCRIPTION
**Pull request by varunu28**
Updated messages.properties for #5463

### CODE REVIEW

**Comment by varunu28** [comment]
@rnveach I have done the change in suppressions.xml. I am new to the project so can you please let me know if this change suffices the requirement?

**Comment by rnveach** [comment]
@varunu28 CI will tell you if your changes are valid before me.
Please run `mvn verify test` to make sure your local passes before pushing. CI is still failing.
Please also keep number of commits to 1.

**Comment by varunu28** [comment]
@romani Thanks for the merge.
This was my first PR for the checkstyle project. Looking forward to adding more contributions in future

**Comment by romani** [comment]
>  Is this considered a backwards breaking change because messages can be set in the suppression file?

to my mind, it is NOT braking changes. It is not serious change in behavior.  All bug fixes are change in behavior so after each version of checkstyle new violations or removal of false positives might happen....
So it is bug.
I still keep in my main decision point on label - Does this affect execution in plugins and embedded solutions? 
if yes - mark as "braking changes" to just attract more attention to change.
if no - might be better to mark it as "bug".

**Pull request merged**
