### PR TITLE
Issue #3006: Fix false positive in FinalLocalVariable when variable is assigned multiple times

### PR DESCRIPTION
**Pull request by MEZk**
#3006 

Reports (Checkstyle, Sevntu-checkstyle, Guava, FindBugs, PMD, Lombook, Spring):
http://mezk.github.io/FinalLocalVariable/index.html

All differences were modified to remove dependencies and included in UTs.

I'll squash commits if it is necessary. But 5 different problems were fixed in scope of the #3006 .

### CODE REVIEW

**Comment by romani** [comment]
> http://mezk.github.io/FinalLocalVariable/site.html

please recheck links to files, I can not open them.

**Comment by MEZk** [comment]
@romani 
Sorry, updated.

**patch-diff-report-tool** has problems with calculation of number of files which are processed.
In my report there were 7266 files processed.

**Comment by romani** [comment]
@MEZk, please do not hesitate to open issue on any problem of patch-diff-report-tool , it is our tool , you can send PR with fix :) .

**Comment by romani** [comment]
Merged as FF

**Pull request closed without merging**
