### PR TITLE
Issue #3891: removed inputs out of non-existent misc package

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3891

Removed misc folder and moved all sub-folders one level up.

### CODE REVIEW

**Comment by rnveach** [comment]
@romani ping

**Comment by romani** [comment]
@rnveach , are you sure that it will better ?
does smth force you to make such change ?

**Comment by rnveach** [comment]
@romani The UT I made to make sure everything is in it's place by the rules we set out is asking for this change.
The rules we set out was that inputs have to be in a sub-directory of the test's package and named as a as a short hand of the test.

It will be slightly odd if we have one package that does something different then all the others.
If you want `misc` to stay, I can try and change the UT around it.

**Comment by romani** [comment]
ok, one day we will make "misc" in betrer form

**Pull request merged**
