### PR TITLE
supplemental: Replaced the older version of google java style guide with newer version and deleted unnecessary test class for Annotations section

### PR DESCRIPTION
**Pull request by Zopsss**
#14937 

Replaced the older version of google style guide ( 20180523 ) with newer version ( 20220203 ) in the remaining places and also deleted `rule485annotations` directory because now it is divided into different subsections ( 4.8.5.1, 4.8.5.2, 5.8.5.3 ) and all these subsections have their own test classes. The `rule485annotations` was no longer needed anymore.

### CODE REVIEW

**Comment by Zopsss** [comment]
Didn't changed version of following sections:

https://github.com/checkstyle/checkstyle/blob/2cbddc72a30c97652a871b1373dcb80d757540b3/src/xdocs/google_style.xml#L2270-L2271

https://github.com/checkstyle/checkstyle/blob/2cbddc72a30c97652a871b1373dcb80d757540b3/src/xdocs/google_style.xml#L2309-L2310

It is done in their own separate PRs. When those PRs gets merged, it will be automatically updated.

**Comment by Zopsss** [comment]
GitHub, generate site

**Review by romani — APPROVED** [review]
Ok to merge if ci pass

**Comment by Zopsss** [comment]
GitHub, generate site

**Review by rdiachenko — APPROVED** [review]
lgtm

**Pull request merged**
