### PR TITLE
minor: bump language level in test input

### PR DESCRIPTION
**Pull request by nrmancuso**
Fixes failure noted at https://app.circleci.com/pipelines/github/checkstyle/checkstyle/17752/workflows/b1d510a4-798d-4146-b302-3f8134d40afc/jobs/260784

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge if CI pass

**Comment by romani** [comment]
Not compilable on jdk 15

**Review by strkkk — APPROVED** [review]

**Comment by romani** [comment]
Strange that pitest instability started to happen frequently
https://github.com/checkstyle/checkstyle/actions/runs/4440772857/jobs/7795005069?pr=12852#step:7:15
```
0s
Run printf "\nTo patch suppression list run:\n\n"

To patch suppression list run:

patch -p[1](https://github.com/checkstyle/checkstyle/actions/runs/4440772857/jobs/7795005069?pr=12852#step:7:1) << EOF
diff --git a/config/pitest-suppressions/pitest-common-2-suppressions.xml b/config/pitest-suppressions/pitest-common-2-suppressions.xml
index e1799fe..aa68579 100644
--- a/config/pitest-suppressions/pitest-common-2-suppressions.xml
+++ b/config/pitest-suppressions/pitest-common-2-suppressions.xml
@@ -179,14 +179,4 @@
     <description>removed call to org/xml/sax/helpers/DefaultHandler::resolveEntity</description>
     <lineContent>inputSource = super.resolveEntity(publicId, systemId);</lineContent>
   </mutation>
-
-  <!-- until https://github.com/checkstyle/checkstyle/issues/[12](https://github.com/checkstyle/checkstyle/actions/runs/4440772857/jobs/7795005069?pr=12852#step:7:13)[18](https://github.com/checkstyle/checkstyle/actions/runs/4440772857/jobs/7795005069?pr=12852#step:7:19)6 -->
-  <mutation unstable="false">
-    <sourceFile>JavaParser.java</sourceFile>
-    <mutatedClass>com.puppycrawl.tools.checkstyle.JavaParser</mutatedClass>
-    <mutatedMethod>parse</mutatedMethod>
-    <mutator>org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator</mutator>
-    <description>removed call to com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageLexer::removeErrorListeners</description>
-    <lineContent>lexer.removeErrorListeners();</lineContent>
-  </mutation>
 </suppressedMutations>
EOF
```

**Comment by romani** [comment]
Restarted

**Pull request merged**
