### PR TITLE
Issue #2549: Remove parameters validation from LocalVariableName

### PR DESCRIPTION
**Pull request by MEZk**

### CODE REVIEW

**Comment by mkordas** [comment]
@MEZk
1) Maybe we should write in docs something like that: "To validate catch parameters you can use <a href="...">ParameterName</a> check". What do you think?
2) I'd suggest to change PR and commit name to `Remove catch parameters validation from LocalVariableName`
3) How this check was limiting to just catch parameters? Wasn't it checking all parameters?

**Comment by MEZk** [comment]
@mkordas 
1) I suggest not to mention ParameterName, because it can be a bit confusing for user. 

2, 3) You are right. PR and commit messages have been changed.

**Comment by mkordas** [comment]
Thanks!

Maybe I'm wrong, but I think that this check was able to do just catch parameter validation, as shown in example that you've deleted. Can we configure `ParameterName` check in the same way? If yes, let's move this example there instead of deleting it.

**Comment by MEZk** [comment]
@mkordas 
Method parameters and catch parameters have PARAMETER_DEF type. So, ParameterName validates method and catch parameters. I've already added examples and description in xdoc/javadoc.

**Comment by mkordas** [comment]
That's what I mean. Can we configure ParameterName to skip validation of method parameters and focus just on catch parameters? In LocalVariableName apparently we were able to do that.

**Comment by MEZk** [comment]
@mkordas 
>Can we configure ParameterName to skip validation of method parameters and focus just on catch parameters? 

Hm, now I see. No, we can not skip method parameters from validation. I added only 'skipCatchParameters' option. But 'skipMethodParameters' can be added as another option [here](https://github.com/checkstyle/checkstyle/commit/176301250bfd2063f405fed4a960064e0a3e0230#diff-b9fd28f1c39c52817eb63490b6951179R127).

**Comment by mkordas** [comment]
My opinion is that we need to provide equivalent functionality for users before merging this PR and prepare some kind of small migration guide.

**Comment by romani** [comment]
> Can we configure ParameterName to skip validation of method parameters and focus just on catch parameters? 

I do not think this is required. As it is like disabling the whole Check , and new option to support. Lets brake behaviour compatibility and we will add new option by user's request later on.
@mkordas , do you agree with such approach ?

**Comment by mkordas** [comment]
I agree that additional option is not nice solution, but I'd like to submit feature request right now. I've reviewed my codebase in terms of short names usage and I find `e` or `ex` totally fine for catch parameters, but I've seen couple of methods with parameter `e` which I'd like to prohibit.
Can we create new check `CatchParameterName`? I can do the coding.

**Comment by romani** [comment]
Please take a look at - https://github.com/checkstyle/checkstyle/issues/2549#issuecomment-156321748

I think that creation of new Check will make overlapping functionality of CatchParameterName and ParameterName. I think it is better to stay in one Check and have more options in it. Another option is to have Checks and change ParameterName and completely ignore CATCH parameters (braking compatibility as we will remove option "skipCatchParameter = true" from ParameterName).

**Comment by MEZk** [comment]
@romani, @mkordas 
So, any final proposal?

I'm for new option for ParameterName to validate only Catch parameters. Let it be 'validateOnlyCatchParameter' or etc.

**Comment by romani** [comment]
>So, any final proposal?

please share your vote at #2616 .

**Comment by romani** [comment]
I will merge this PR together with #2617 . @mkordas , are you agree ?

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
