### PR TITLE
 Issue #957: Resolve problems from PMD DefaultPackage rule

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by romani** [comment]
please recheck suppressions, code is moved and you most likely need update line numbers in suppressions.

**Comment by romani** [comment]
1) 
> RequireThisCheck.java, NoWhitespaceAfterCheck.java

methods should be private. Check should not share with others their methods. All Shared functionality has to be moved to Util classes.


2)
> AbstractDeclarationCollector

make them protected, to let be used only for child classes.


3)
>
```
 -    final HandlerFactory getHandlerFactory() {
+    public HandlerFactory getHandlerFactory() {
```

Why final was removed ?

**Comment by Vladlis** [comment]
1)
> NoWhitespaceAfterCheck

done
> RequireThisCheck

the same as in AbstractDeclarationCollector
2) Done
3) Accidentally, fixed.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
