### PR TITLE
doc: Updated ANT example to add custom JAR

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
Add example of custom jars to Ant Documentation #5389

MVN CLEAN VERIFY
JarDocumentation
:

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
@nmancus1 please help me with the failing test cases!

**Comment by nmancus1** [comment]
@Rahulkhinchi03 please share error message, and describe what you do not understand, and what you have tried to do to remedy the situation. This helps others to help you.

**Comment by Rahulkhinchi03** [comment]
Untitled

@nmancus1 I am getting this error in "checkstyle.checkstyle (Job spelling)"

I tried to change the spelling but I am not getting which spelling is correct for destination directory

**Comment by nmancus1** [comment]
@Rahulkhinchi03 please link to original issue in PR description.

**Comment by Rahulkhinchi03** [comment]
will DESTDIR work?

**Comment by nmancus1** [comment]
>will DESTDIR work?

I do not know; it would be good to see a working example of a passing ant build to verify that config in documentation works as intended.

**Comment by Rahulkhinchi03** [comment]
@nmancus1 I used "destfile dir" and It worked but now I am getting a new error which is:
Untitled

I don't really have any idea about this error. Kindly help me resolve it!

**Comment by Rahulkhinchi03** [comment]
@romani please review

**Comment by rnveach** [comment]
Connection reset is just a random connection issue. I restarted the CI with the failure.

**Comment by Rahulkhinchi03** [comment]
> Connection reset is just a random connection issue. I restarted the CI with the failure.
Okay, thanks for the information.

**Comment by Rahulkhinchi03** [comment]
> Connection reset is just a random connection issue. I restarted the CI with the failure.

Okay, thanks for the information.

**Comment by Rahulkhinchi03** [comment]
@romani please review changes!

**Comment by Rahulkhinchi03** [comment]
Please review my changes, @romani

**Comment by romani** [comment]
you are fixing issue, plase update commit to have link to issue
`Issue #5389: .....`

image
please make title of section "Custom jar in class path"

**Comment by romani** [comment]
image

please fix indentation of xml block, see examples of of xml above.

**Comment by romani** [comment]
this is example of how we already do example of sevntu usage:
https://github.com/sevntu-checkstyle/checkstyle-samples/blob/634fd5fa3966f639b088e7e80b2a8f510372c339/ant-project/build.xml#L22-L30

**Review by romani — CHANGES_REQUESTED** [review]
see comments above

**Comment by Rahulkhinchi03** [comment]
@nmancus1 can you please help me with the Point1 said by sir romani?

**Comment by romani** [comment]
Try to make java ant project that use checkstyle and sevntu checkstyle as jars in lib folder, make violation in test class for Check from sevntu

**Pull request closed without merging**
