### PR TITLE
Issue #15763: fixed UpperEll's paragraphs

### PR DESCRIPTION
**Pull request by Zopsss**
Issue #15763

### CODE REVIEW

**Comment by romani** [comment]
```
Checks that long constants are defined with an upper ell. That is {@code 'L'} and not {@code 'l'}. This is in accordance with the Java Language Specification, <a href="[https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-3.10.1">Section](https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-3.10.1%22%3ESection) 3.10.1</a>.
    -</p>
     <p>
     Rationale: The lower-case ell {@code 'l'} looks a lot like {@code 1}.
     </p>
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest$JavaDocCapture.visitClass(XdocsJavaDocsTest.java:647)
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest$JavaDocCapture.visitToken(XdocsJavaDocsTest.java:595)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:393)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:466)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:331)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:215)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:101)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:340)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:299)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:226)
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.examineCheckSection(XdocsJavaDocsTest.java:187)
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.testAllCheckSectionJavaDocs(XdocsJavaDocsTest.java:160)
```

**Comment by romani** [comment]
xdoc has two files:
1) template
2) actual xdoc file that is used by maven site plugin

test phase in checkstyle generates xdoc files from template files, so we need to change template.
```
diff --git a/src/xdocs/checks/misc/upperell.xml.template b/src/xdocs/checks/misc/upperell.xml.template
index b3559dc..f57950f 100644
--- a/src/xdocs/checks/misc/upperell.xml.template
+++ b/src/xdocs/checks/misc/upperell.xml.template
@@ -9,13 +9,11 @@
     <section name="UpperEll">
       <p>Since Checkstyle 3.0</p>
       <subsection name="Description" id="Description">
-        <p>
-          Checks that long constants are defined with an upper ell. That
-          is <code>'L'</code> and not <code>'l'</code>. This is in accordance with the Java
-          Language Specification,
-          <a href="https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-3.10.1">
-          Section 3.10.1</a>.
-        </p>
+        Checks that long constants are defined with an upper ell. That
+        is <code>'L'</code> and not <code>'l'</code>. This is in accordance with the Java
+        Language Specification,
+        <a href="https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-3.10.1">
+        Section 3.10.1</a>.
 
         <p>
           Rationale: The lower-case ell <code>'l'</code> looks a lot like <code>1</code>.

```

**Comment by romani** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.12.1:site 
(default-site) on project checkstyle: Error parsing '/home/rivanov/java/github/romani/checkstyle/src/xdocs/checks/misc/upperell.xml': 
Error validating the model: Error:
[ERROR]   Public ID: null
[ERROR]   System ID: null
[ERROR]   Line number: 21
[ERROR]   Column number: 20
[ERROR]   Message: cvc-complex-type.2.3: Element 'subsection' cannot have character [children],
 because the type's content type is element-only.
[ERROR] 
```

this means that xdoc files should have some tag under `section` tag. Limitation of xdoc.

**Comment by Zopsss** [comment]
> this means that xdoc files should have some tag under `section` tag. Limitation of xdoc.

Yes, it cannot directly have text under it that means we cannot have something like:


```
<section>some text....</section>
```

So we need a tag below it like a paragraph tag or something but UplerEll.xml & upperell.xml.template needs to be same so that too will fail our build.

**Comment by romani** [comment]
change to P to DIV is workaround.

results html looks identical.
image
image

**Comment by romani** [comment]
failure in "Check no closed issue references / check_issues (pull_request) " is not related, looks like thirdparty action to get linked issues is broken , or we might have some leak in master.

**Pull request merged**
