### PR TITLE
Issue #11140: resolve FCBL_FIELD_COULD_BE_LOCAL

### PR DESCRIPTION
**Pull request by rnveach**
Issue #11140

Testing CI as I got no failures locally.

### CODE REVIEW

**Comment by rnveach** [comment]
This is a flaky test as only JDK 11 works correctly with it.
> [INFO] Total bugs: 28

````
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator$CliOptions defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator$CliOptions] In JavadocPropertiesGenerator.java FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator$CliOptions defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator$CliOptions] In JavadocPropertiesGenerator.java FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.Main$CliOptions defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.Main$CliOptions] In Main.java FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.Main$CliOptions defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.Main$CliOptions] In Main.java FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.Main$CliOptions defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.Main$CliOptions] In Main.java FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.Main$CliOptions defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.Main$CliOptions] In Main.java FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.PropertyCacheFile$ExternalResource defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.PropertyCacheFile$ExternalResource] At PropertyCacheFile.java:[line 398] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.PropertyCacheFile$ExternalResource defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.PropertyCacheFile$ExternalResource] At PropertyCacheFile.java:[line 397] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.api.AbstractCheck$FileContext defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.api.AbstractCheck$FileContext] In AbstractCheck.java FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.api.AbstractCheck$FileContext defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.api.AbstractCheck$FileContext] At AbstractCheck.java:[line 303] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck$FileContext defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck$FileContext] In AbstractFileSetCheck.java FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck$FileContext defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck$FileContext] At AbstractFileSetCheck.java:[line 251] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck$Details defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck$Details] At RightCurlyCheck.java:[line 537] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck$Details defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck$Details] At RightCurlyCheck.java:[line 539] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck$Details defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck$Details] At RightCurlyCheck.java:[line 538] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck$Details defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck$Details] At RightCurlyCheck.java:[line 540] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.coding.DeclarationOrderCheck$ScopeState defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.coding.DeclarationOrderCheck$ScopeState] At DeclarationOrderCheck.java:[line 486] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.coding.DeclarationOrderCheck$ScopeState defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.coding.DeclarationOrderCheck$ScopeState] At DeclarationOrderCheck.java:[line 489] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck$FinalVariableCandidate defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck$FinalVariableCandidate] In FinalLocalVariableCheck.java FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck$FinalVariableCandidate defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck$FinalVariableCandidate] In FinalLocalVariableCheck.java FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck$FinalVariableCandidate defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck$FinalVariableCandidate] At FinalLocalVariableCheck.java:[line 889] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck$ScopeData defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck$ScopeData] In FinalLocalVariableCheck.java FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck$ScopeData defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck$ScopeData] At FinalLocalVariableCheck.java:[line 846] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck$RuleMatchForImport defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck$RuleMatchForImport] At CustomImportOrderCheck.java:[line 1399] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck$RuleMatchForImport defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck$RuleMatchForImport] At CustomImportOrderCheck.java:[line 1400] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck$RuleMatchForImport defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck$RuleMatchForImport] At CustomImportOrderCheck.java:[line 1401] FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck$FileContext defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck$FileContext] In AbstractJavadocCheck.java FCBL_FIELD_COULD_BE_LOCAL 04:00
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck$FileContext defines fields that are used only as locals [com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck$FileContext] At AbstractJavadocCheck.java:[line 412] FCBL_FIELD_COULD_BE_LOCAL
````

**Comment by rnveach** [comment]
I am suppressing the entire check as it is creating false positives. There are instances where we have to store multiple objects and the class is the best way to do it, since we have to provide these as parameters to sets, maps, etc...

We could suppress individual classes and instances, but I personally just don't see much benefit to this right now.

**Comment by pbludov** [comment]
All these classes are inner classes. There is a possible bug in the `FCBL_FIELD_COULD_BE_LOCAL` detector.

**Comment by pbludov** [comment]
This may be related to https://openjdk.java.net/jeps/181
I can't repro this bug in my PC. Tested with OpenJDK 8,11, AdoptOpenJDK 16, Liberica JDK 17.

**Review by pbludov — APPROVED** [review]

**Comment by pbludov** [comment]
If anyone is able to reproduce this bug please create new issue at https://github.com/mebigfatguy/fb-contrib/issues

**Review by romani — APPROVED** [review]

**Pull request merged**
