### PR TITLE
 Refactor SummaryJavadocCheck into SummaryJavadoc for co…

### LINKED ISSUE #15197: Refactor SummaryJavadocCheck into SummaryJavadoc for configs
In configs, SummaryJavadoc has refactored to SummaryJavadocCheck. Hence, we have to revert back to changes. 

`<module name="SummaryJavadocCheck">` be refactored to `<module name="SummaryJavadoc">`

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Resolves #15197

### CODE REVIEW

**Comment by romani** [comment]
Apply this patch to your commit https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=22226&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111

**Comment by relentless-pursuit** [comment]
> Apply this patch to your commit https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=22226&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111
> 
> To let CI pass

I tried applying the below patch but failed. Hence, i modified the file maybe causing the issue. 

```
diff --git a/src/xdocs/checks/javadoc/summaryjavadoc.xml b/src/xdocs/checks/javadoc/summaryjavadoc.xml
index 1634e5096..15cffc95d 100644
--- a/src/xdocs/checks/javadoc/summaryjavadoc.xml
+++ b/src/xdocs/checks/javadoc/summaryjavadoc.xml
@@ -64,7 +64,7 @@
         <source>
 &lt;module name=&quot;Checker&quot;&gt;
  &lt;module name=&quot;TreeWalker&quot;&gt;
-    &lt;module name=&quot;SummaryJavadoc&quot;/&gt;
+    &lt;module name=&quot;SummaryJavadoc&quot;/&gt;
  &lt;/module&gt;
 &lt;/module&gt;
         </source>
@@ -121,7 +121,7 @@ public class Test extends Exception {
         <source>
 &lt;module name=&quot;Checker&quot;&gt;
  &lt;module name=&quot;TreeWalker&quot;&gt;
-    &lt;module name=&quot;SummaryJavadoc&quot;&gt;
+    &lt;module name=&quot;SummaryJavadoc&quot;&gt;
      &lt;property name=&quot;forbiddenSummaryFragments&quot;
        value=&quot;^This method returns.*&quot;/&gt;
    &lt;/module&gt;
@@ -134,7 +134,7 @@ public class Test extends Exception {
         <source>
 &lt;module name=&quot;Checker&quot;&gt;
  &lt;module name=&quot;TreeWalker&quot;&gt;
-    &lt;module name=&quot;SummaryJavadoc&quot;&gt;
+    &lt;module name=&quot;SummaryJavadoc&quot;&gt;
      &lt;property name=&quot;period&quot; value=&quot;&amp;#x3002;&quot;/&gt;
    &lt;/module&gt;
   &lt;/module&gt;
```

**Comment by romani** [comment]
Please make sure there is no window line ending. Looks like some invisible character difference.

**Comment by romani** [comment]
b/src/xdocs/checks/javadoc/summaryjavadoc.xml
Such files are generated, from files that are named almost the same but with "template" in name.

**Comment by relentless-pursuit** [comment]
> b/src/xdocs/checks/javadoc/summaryjavadoc.xml Such files are generated, from files that are named almost the same but with "template" in name.

You are right. But, i changed the summaryjavadoc.xml. And, didn't find the way to change anything in generate. But, i guess i can generate these files i.e. xml files. Also, i tried looking fo invisible characters and used some sed command but no help. 

Can you help with the logs? I don't see the failing CI logs. 

Also, about generating this via template, can you help me remember how?

**Comment by romani** [comment]
Just run "mvn install" , it will do all.

**Comment by relentless-pursuit** [comment]
> Just run "mvn install" , it will do all.

done

**Review by romani — APPROVED** [review]
Ok to merge

**Pull request merged**
