### PR TITLE
TreeWalker update, logging warning if AcceptableTokens are broken, issue...

### PR DESCRIPTION
**Pull request by alexkravin**
... #342

According to #342 

I investigated registerCheck() method and found no problems with getAcceptableTokens(), by default it's copy of getDefaultTokens() array, but if it's specified in Check - it will get corresponding values, but there was a comment after checking input token for acceptableTokens accessory 
```
//TODO: else log warning
```

So, if acceptableTokens are broken - there's need to put a violation - in that case there's explicit throwing of IllegalArgumentException which is handled on the next line and rethrown as CheckstyleException (before this update CheckstyleException could be thrown only in case if 
```java
final int tokenId = TokenTypes.getTokenId(token);
```
threw IllegalArgumentException, it is possible only if there's no such token at all).

Updated UT for AbbreviationAsWordInNameCheck:
there're passing the ENUM_CONSTANT_DEF token in several UTs, but there's no corresponding support in Check's code and even in test inputs, so instead of adding it to defaultTokens array just removed from UTs as it wasn't covered, perhaps there is some special meaning, if so - explain me, please and I'll look for a better way of solution.

### CODE REVIEW

**Comment by romani** [comment]
1) Set of default tokens and set of acceptable tokens are different terms.
check should clearly define all tokens that are expected by his visitToken method.
Default tokens are set of tokens that check is run on if nothing is specified in configuration.

Attention: in configuration you can specify list token on what you need to run Check. You can set up AbbreviationNameCheck to be launched on "{" token - it will definetely crash with NPE of smth weird.

Exactly the same behavior was in checkstyle before 6.2 release, checkstyle 6.1.1 + sevntu.checkstyle 1.12.0 throw exceptions on every Check as, numbering of tokens was shifted so Checks receive not exactly the same tokens they have to receive. Details at #505 .

2) please update all Checks to clearly define what Tokens are acceptable, please do that attentively, as simple copy from default to acceptable is not always true!!!

**Comment by alexkravin** [comment]
Added set of acceptable tokens to each Check that didn't have it, sure in most cases it is similar to default tokens set, but in several Checks it differs.

**Comment by romani** [comment]
> throw new IllegalArgumentException("illegal token \""
+ + token + "\" in check " + check);

Please put there note that such token is not found in list Acceptable tokens. In other case for developer will be hard to understand what is not right with his Check.

> AbbreviationAsWordInNameCheckTest.java

This Check could easily work on ENUM_CONSTANT_DEF, it just validate name of token, please add it to Allowed tokens.

> @ Test(expected = CheckstyleException.class)

please do not use that Junit feature, it do mess in logs, one day I will forbid it by https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/ForbidAnnotationCheck.java

**Comment by alexkravin** [comment]
1) Updated in TreeWalker

2) ENUM_CONSTANT_DEF was added to Acceptable tokens list and returned to UTs

3) Moved this UT to TreeWalkerTest and removed <b>expected annotation</b>, this is now done by comparing exception's message with expected one.

**Comment by romani** [comment]
1) 
https://github.com/alexkravin/checkstyle/blob/e574e4fa112c734455423e2f9f9db54ed7a214e2/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L318

you throw IllegalArgumentException exception to catch it in next line of code ? am I blind ?

**Comment by alexkravin** [comment]
1) Yes, this method is recursive, what's the better way?

2) google-style-test is passing well, the difference is in EmptyBlockCheck in sun_checks and checkstyle_checks configuration as I added to acceptable tokens all kind of tokens which have curly braces (block) such as ARRAY_INIT, INSTANCE_INIT, etc. And this Check is specified without any options

3) Updated according to java8 features and added parameter definition token.

4) See p. 2 for EmptyBlockCheck.
About NeedBracesCheck I see no connection between curly braces and this Check, so is there any need to extend acceptable tokens list?

5) Removed this update.

**Comment by alexkravin** [comment]
About NeedBracesCheck, seems to be in Acceptable Tokens list specified all possible tokens where curly braces can be skipped,

**Comment by alexkravin** [comment]
Please, rerun this build on travis

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
