### PR TITLE
Issue #3161: Format for trailing comma check in enums

### PR DESCRIPTION
**Pull request by kariem**
Discussed in sevntu-checkstyle/sevntu.checkstyle#709

Related to issue 3161

### CODE REVIEW

**Comment by kariem** [comment]
The intention of this PR is to resolve errors when running checkstyle regression in sevntu-checkstyle/sevntu.checkstyle: https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/408476345#L1063. This is executed via 

```
.ci/travis.sh checkstyle-regression
```

which in turn runs

```
mvn -e clean verify -e -DskipTests -DskipITs -Dpmd.skip=true \
    -Dfindbugs.skip=true -Dcobertura.skip=true \
    -Dmaven.sevntu-checkstyle-check.checkstyle.version=8.10
```

On the current checkstyle/checkstyle code.

However, running checkstyle-regression results in errors for two checks
- `NoWhitespaceBefore`
    > ';' is preceded with whitespace.
- `SeparatorWrap`
    > ';' should be on the previous line.

Here the relevant output:

```
...
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/Scope.java:42:4: ';' is preceded with whitespace. [NoWhitespaceBefore]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/Scope.java:42:5: ';' should be on the previous line. [SeparatorWrap]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/SeverityLevel.java:44:4: ';' is preceded with whitespace. [NoWhitespaceBefore]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/SeverityLevel.java:44:5: ';' should be on the previous line. [SeparatorWrap]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java:49:4: ';' is preceded with whitespace. [NoWhitespaceBefore]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java:49:5: ';' should be on the previous line. [SeparatorWrap]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java:52:8: ';' is preceded with whitespace. [NoWhitespaceBefore]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java:52:9: ';' should be on the previous line. [SeparatorWrap]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfo.java:359:4: ';' is preceded with whitespace. [NoWhitespaceBefore]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfo.java:359:5: ';' should be on the previous line. [SeparatorWrap]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AccessModifier.java:40:4: ';' is preceded with whitespace. [NoWhitespaceBefore]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AccessModifier.java:40:5: ';' should be on the previous line. [SeparatorWrap]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java:55:8: ';' is preceded with whitespace. [NoWhitespaceBefore]
[checkstyle] [ERROR] []/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java:55:9: ';' should be on the previous line. [SeparatorWrap]
...
```

Is it a good idea to enable all checks? In general, there might be a conflict between individual checks.

**Comment by romani** [comment]
>Is it a good idea to enable all checks? 

In general yes, and such failures show how users will experience usage of such Check. So we can predict feedback.
If any conflicts exists, this should be reflected in documentation.

------

1) Please change commit message to be "minor: .... Issue #3161"
To make release notes generation correct.

2) please try to remove ";" completely , I do not remember what Check/Rule demanding it.

**Comment by kariem** [comment]
> If any conflicts exists, this should be reflected in documentation.

I see a conflict as two opposing requirements. Just adapting the documentation does not work, if e.g. one rule enforces tabs and the other rule enforces spaces.

> Please change commit message to be "minor: .... Issue #3161"
> To make release notes generation correct.

Done

> please try to remove ";" completely , I do not remember what Check/Rule demanding it.

Semicolon is placed where it is necessary. It cannot be removed, if the enum contains a body - see [Enum Body Declarations](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.9.2). In [my last comment](https://github.com/checkstyle/checkstyle/pull/6054#issuecomment-409405662) I have summarized the checks and copied the log from the build and linked to the summary.

How should we continue here?

**Comment by romani** [comment]
Thanks a lot for details.

@rnveach , I do not see a way to activate in error severity this new Check now. http://checkstyle.sourceforge.net/config_filters.html#SuppressionXpathFilter could help to reconcile demand from NoWhitespaceBefore and SeparatorWrap . But there is no support for NoWhitespaceBefore in xpath for now. 
We need to add new Check with ignore severity for now with comment " disabled till NoWhitespaceBefore get support in SuppressionXpathFilter" ( there is no specific issue to be used).

@rnveach please confirm

**Comment by rnveach** [comment]
@romani I agree.

**Comment by romani** [comment]
@kariem , ping.
please do at least small update that we agree on.

**Comment by kariem** [comment]
@romani Done: a686af80536d271822bcca5078dec5da7b10b58b

As a reference, I have attached the full changes that will make the check go through without errors: 
[0001-Issue-3161-Format-for-trailing-comma-in-enums.patch.txt](https://github.com/checkstyle/checkstyle/files/2284592/0001-Issue-3161-Format-for-trailing-comma-in-enums.patch.txt)

**Comment by romani** [comment]
Travis failure is due to issue is not approved, I can not approve issue for now.
Issue is in script that do validation, we can ignore this failure.

**Comment by rnveach** [comment]
CI is failing because commit has `Issue #3161:` so it wrongly thinks it is part of an issue when it is ignoring that it starts with `minor` that says it isn't part of an issue.

**Pull request merged**
