### PR TITLE
bug fixed - AbbreviationAsWordInNameCheck - no need to -1

### PR DESCRIPTION
**Pull request by cyw3**
PLEASE READ before removing!!

Rules:
1) The issue you are trying to fix/resolve has to have the "approved" label.
2) Put in the description of Pull Request the reference to an issue if it exists.
   Example: "Issue: #XXXXXX"
3) Commit message should adhere to the following rules:
   a) MUST match one of the following patterns:
      ^Issue #\\d+: .*$
      ^Pull #\\d+: .*$
      ^(minor|config|infra|doc|spelling|dependency): .*$
   b) MUST contain only one line of text
   c) MUST NOT end with a period, space, or tab
   d) MUST be less than or equal to 200 characters

To avoid multiple iterations of fixes and CIs failures, please read
https://checkstyle.org/contributing.html

ATTENTION: We are not merging Pull Requests that are not passing our CIs,
but we will help to resolve issues.

Thanks for reading, remove whole this message and type what you need.

### CODE REVIEW

**Comment by rnveach** [comment]
@cyw3 Please read your first post. What issue number in our tracker is this related to?
https://github.com/checkstyle/checkstyle/wiki/PR-rules

**Comment by romani** [comment]
@cyw3 , if no feeback till end of April, we will close PR.

**Comment by rnveach** [comment]
Closing as no reply. We can relook at this if reply is given.

**Comment by romani** [comment]
I do not understand this PR at all. Closed.

**Pull request closed without merging**
