### PR TITLE
Issue #7587: Examples added for Descendant Token

### PR DESCRIPTION
**Pull request by athuma**
https://github.com/checkstyle/checkstyle/issues/7587

### CODE REVIEW

**Comment by nrmancuso** [comment]
@athuma work through all failures on local by running `mvn clean verify`, please do not push changes until this is done. Once `mvn clean verify` is passing, begin to review and fix CI errors.

**Comment by romani** [comment]
GitHub, generate website

**Comment by athuma** [comment]
is there anyone to contact i have checked for users but i am unable to find any or you can point me to any document from where i can take help @romani

**Comment by romani** [comment]
please learn from this PR - https://github.com/checkstyle/checkstyle/pull/12805

**Comment by nrmancuso** [comment]
@athuma please close this PR and find a new issue to work on, we are close to completion here: https://github.com/checkstyle/checkstyle/pull/12891

**Pull request closed without merging**
