### PR TITLE
Issue #10262: Update inputs for SimplifyBooleanReturnCheckTest

### LINKED ISSUE #10262: Update inputs for SimplifyBooleanReturnCheckTest
Child of #10080

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #10262

### CODE REVIEW

**Comment by timurt** [comment]
fix conflicts

**Comment by shashwatj07** [comment]
> fix conflicts

done

**Comment by timurt** [comment]
Github rebase

**Comment by timurt** [comment]
GitHub, rebase

**Pull request merged**
