### PR TITLE
 Issue #3729: Reevaluate tokens in IllegalTokenText

### PR DESCRIPTION
**Pull request by Vladlis**
Issue #3729

### CODE REVIEW

**Comment by rnveach** [comment]
I see, we are defining constants as both tokens that have the same value as the name,
`CLASS_DEF -> CLASS_DEF`
and where tokens have values that never change
`LITERAL_PUBLIC -> public`
I forgot about the 2nd case.

**Comment by rnveach** [comment]
@Vladlis How did you come up with these tokens?
@romani Should we update check description which is only 1 line?

**Comment by Vladlis** [comment]
@rnveach 
just looked through all [TokenTypes](http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html)

**Comment by romani** [comment]
@Vladlis , please provide update for description and examples. Thanks in advance.

**Comment by Vladlis** [comment]
@romani 
I've made description a bit clearer

**Pull request merged**
