### PR TITLE
Issue #10625: Fixed InputMissingOverrideBadOverrideFromOther.java and removed it form line length suppression

### PR DESCRIPTION
**Pull request by AbhinavRajputEXE**
#10625

### CODE REVIEW

**Comment by AbhinavRajputEXE** [comment]
@romani 
this was the file that was giving me [this](https://github.com/checkstyle/checkstyle/issues/10625#issuecomment-993886874) error.

**Comment by romani** [comment]
pitest-annotation failed it is suspicious , as we touched annotation related tests.
https://github.com/checkstyle/checkstyle/runs/4551751732?check_suite_focus=true#step:4:5283
```
6:38:08 PM PIT >> SEVERE : Tests failing without mutation: 
Description [testClass=com.puppycrawl.tools.checkstyle.checks.annotation.MissingOverrideCheckTest, name=[engine:junit-jupiter]/[class:com.puppycrawl.tools.checkstyle.checks.annotation.MissingOverrideCheckTest]/[method:testBadOverrideFromOther()]]
/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  40.704 s
[INFO] Finished at: 2021-12-16T18:38:08Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.pitest:pitest-maven:1.7.3:mutationCoverage (default-cli) on project checkstyle: Execution default-cli of goal org.pitest:pitest-maven:1.7.3:mutationCoverage failed: 1 tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
Error:  See http://pitest.org for more details.
```

**Comment by romani** [comment]
@AbhinavRajputEXE , please fix tests, make sure that "mvn verify" pass on your local before you push your code for review

**Comment by AbhinavRajputEXE** [comment]
@romani 
I tried to fix it by making some changes, but none of them worked and by reverting back the violation message to the original the error was going away, so I think the error is caused by modification in the original violation message, not because of a change in column number😅. 
But I'm not able to figure out how to fix it can you please give some hint or an example.😅

**Comment by romani** [comment]
keep suppressions, and play with modification of input file to find what line changes make UT to fail.

**Comment by AbhinavRajputEXE** [comment]
@romani 
I found out when it's causing that error but I still am not sure why it is causing this error.
So when I start removing words from the middle of the comment it gives me that error but when I remove something from the end It does not give me that error.
like
if I write this comment
`'Must include @java.lang.Override annotation when '@inheritDoc' Javadoc tag exists.'`
like
`'Must include @java.lang.Override annotation when '@inheritDoc' '`
It does not give me any error but when I remove something from the middle like
`'include @java.lang.Override when '@inheritDoc' Javadoc tag exists.'`
It throws that error.
Same was with the case with regexp
I kept the suppression while doing this btw.
what could be causing this?
or do I need to do more digging?

**Comment by romani** [comment]
> 'include @java.lang.Override when '@inheritDoc' Javadoc tag exists.'

you missed word "annotation" so message in not matching by regexp
you should do 
`include @java.lang.Override annotation when '@inheritDoc' Javadoc tag exists.`
or 
`include @java.lang.Override .* when '@inheritDoc' Javadoc tag exists.`

**Comment by AbhinavRajputEXE** [comment]
> you missed word "annotation" so message in not matching by regexp you should do `include @java.lang.Override annotation when '@inheritDoc' Javadoc tag exists.` or `include @java.lang.Override .* when '@inheritDoc' Javadoc tag exists.`

yeah😅
I actually did not do that in the file I removed it just for the example here in the comment
it is giving me errors even if I just remove "must" from the beginning and nothing else.

**Comment by AbhinavRajputEXE** [comment]
@romani 
Please check whether the new violation message is fine or not.
It's not giving any error this time.

**Comment by romani** [comment]
you did a good update, keep doing!

**Pull request merged**
