### PR TITLE
Issue #7767: Fix for WriteTag Check to include DetailAST while logging

### PR DESCRIPTION
**Pull request by yajna-pandith**
Issue #7767: Fix for WriteTag Check to include DetailAST while logging

### CODE REVIEW

**Comment by romani** [comment]
@yajna-pandith , please review this PR https://github.com/checkstyle/checkstyle/pull/7820 and do similar updates but for your Check.

**Comment by yajna-pandith** [comment]
When you say updates , this with respect to diff report right?
Adding diff report with default config and javaFiveCompatibility.

**Comment by rnveach** [comment]
@yajna-pandith Did you read the post in the link @romani mentioned with the 3 points? You need to do those same 3 points except the first one.

**Comment by yajna-pandith** [comment]
[index.pdf](https://github.com/checkstyle/checkstyle/files/4334962/index.pdf)
I have generated the diff report. I am getting warnings on the files which I have not worked on. 
This is what changed in my_check.xml
<module name="TreeWalker">
         
         
         <module name="**WriteTag**">
I uncommented this line " checkstyle|git|https://github.com/checkstyle/checkstyle.git|master|**/checkstyle/src/test/resources-noncompilable/**/*,**/InputAllEscapedUnicodeCharacters.java  " in the file projects-to-test-on.properties. 
How do I go about from here? Kindly help.  Thanks in advance.

**Comment by rnveach** [comment]
@yajna-pandith What you have provided is not the regression report we need. Please read https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#checkstyle-tester .
What we need uploaded is all the files to the web to view the website. The report generated is going to look similar to http://rveach.no-ip.org/checkstyle/regression/reports/290/ .

**Comment by yajna-pandith** [comment]
I referred the following link: <https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#checkstyle-tester > and generated a diff report. 

I created the static web site on Github using the following link: <https://pages.github.com/ > 
I tried uploading the whole folder reports/diff but I am getting message saying the there are more than 100 files in the folder and thus upload is not possible.

Instead, I have uploaded the whole folder reports/diff to google drive. This is the link : < https://drive.google.com/open?id=1Iown3yIsm-6H9zLMiqeDi1X-i2bjaG_W >

For a quick look here is the screenshot of the diff report generated. 
diff_report

**Comment by romani** [comment]
please activate all projects in property file and relaunch diff report.
Please share report in github.io we need all files in report folder, not only index.html.

**Comment by yajna-pandith** [comment]
I have activated all the projects and I have generated the diff report 

With respect to all the files in folder reports/diff, there are many files and when I try to upload them to <https://github.com/yajna-pandith/yajna-pandith.github.io/upload> I am getting this message
yajna-pandith-github io

Should I zip it and then upload it. The file size is more than 200mb and more than 100 files.

**Comment by Abhishek-kumar09** [comment]
You should not drag and drop files, instead upload to your github-repo from your machine with cli commands
```
git add .
git commit -m "YOUR MESSAGE"
git push -u origin master
```

Then enable github pages from repo setting, and check the url by writing url that goes to index.html, more specifically `reports/diff/index.html`.

**Comment by Abhishek-kumar09** [comment]
Please do
```
git remote add upstream https://github.com/checkstyle/checkstyle.git
git fetch upstream
git rebase upstream/master
```

**Comment by romani** [comment]
@yajna-pandith , please redo your branch again, there should be only single commit in your branch.

**Comment by yajna-pandith** [comment]
The below is the comment from #7740 (comment) 

2)please move Check to list Also, the filter does not support suppression inside javadoc reported by Javadoc checks: (ATTENTION I propose change wording a bit, to be precise) of https://checkstyle.org/config_filters.html#SuppressionXpathFilter . We should make it clear for user that it is still not supported as majority of violations we do not able to suppress.

3)update UTs to allow JavadocStyleCheck to be in list with other Javadoc Checks (just do hardcoded addition of its name to list of all JavadocChecks), #7740 (comment) . So there should be a list all Checks AbstractJavadocCheck and all our old implementations (JavadocMethod, JavadocStyle, JavadocType).

W.r.t point 3 , 
i)Does this simply mean the mention of write tag be removed from the list INCOMPATIBLE_CHECK_NAMES ? 
ii) Should this be added to INCOMPATIBLE_JAVADOC_CHECK_NAMES ?

Just want to whether this is issue is all about JAVADOC content correction?

**Comment by bmhm** [comment]
No changes - can this be closed now or do you still work on this?

**Comment by yajna-pandith** [comment]
It can be closed

**Pull request closed without merging**
