### PR TITLE
Restoring label feature in new workflow regression-report.yml

### LINKED ISSUE #15596: Restoring the label feature in new workflow regression-report.yml
The label feature was missing from new workflow `regression-report.yml`. We attempt to restore it. 

For a command like below, we get output as such:
```
Report label: AbstractClassName Test

Diff Regression config: https://raw.githubusercontent.com/checkstyle/test-configs/main/ArrayTrailingComma/all-examples-in-one/config.xml
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/test-configs/main/ArrayTrailingComma/all-examples-in-one/list-of-projects.properties
```

Outcome:
```
AbstractClassName Test:
https://chesktyler-reports.s3.ap-south-1.amazonaws.com/bcfb81c_2024234933/reports/diff/index.html
```

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Resolves #15596

### CODE REVIEW

**Comment by romani** [comment]
CI is red , please fix.
Do you really mean that  better to have 2 commits ?

**Comment by romani** [comment]
Oh, you fix 2 issues in one PR.

Please reference all issues in PR description  you resolving

**Comment by relentless-pursuit** [comment]
Testing results: https://github.com/checkstyle-gsoc/checkstyle/pull/23#issuecomment-2322606961

**Comment by relentless-pursuit** [comment]
> Oh, you fix 2 issues in one PR.
> 
> Please reference all issues in PR description you resolving

no, it was a mistake. dropped the comit.

**Comment by relentless-pursuit** [comment]
the issue needs approval, i guess that's why ci is red

**Comment by romani** [comment]
Please remove `.` from commit message to let CI pass.

**Review by romani — APPROVED** [review]

**Pull request merged**
