### PR TITLE
Issue #6308: made IndentLevel immutable

### PR DESCRIPTION
**Pull request by rnveach**
Issue #6308

### CODE REVIEW

**Comment by romani** [comment]
Ok to merge if CI pass

**Comment by romani** [comment]
Regression in Orekit is interesting, I do not think is right. forceStrictCondition is false by default, so multiple allowance should be.

**Comment by rnveach** [comment]
Regression just shows it is in a change in violation, so it was producing a violation before.
Yes, since force strict is off, there shouldn't be a violation at all. I believe there are other areas in the check where it does strict validation even if it isn't enabled.

**Comment by rnveach** [comment]
Just as interestingly we killed a mutation with this change.

**Comment by romani** [comment]
We already know that indentation is not ideal in behavior, so I am fine with slight regression if we get some benefits in coverage

**Comment by rnveach** [comment]
CI passed.

**Comment by rnveach** [comment]
@romani What do you specifically want me to do?
You want me to prove that bad regression is the result of IdentLevel corruption and not bad change in the PR? Or are you saying I should make more changes to correct regression even though it looks like this is an issue we have seen before?

**Comment by pbludov** [comment]
It seems that the number of bugs is even. And they make up for each other. @rnveach, please examine whether it is possible to fix them together to improve regression.

**Comment by romani** [comment]
> I should make more changes to correct regression even though it looks like this is an issue we have seen before?

I thought such new violations are result of your changes, and probably we can copy such cases to inputs and make sure regression is not happening. Is it doable ? Or ...

**Comment by rnveach** [comment]
Ok I will try to confirm new violations to make sure it isn't a bug from my changes.

**Comment by romani** [comment]
@rnveach , if can not find time to continue this PR till end of january, it is better to close PR, and reopen it ones you can make new step.

**Comment by rnveach** [comment]
It looks like changes to `MethodCallHandler.getSuggestedChildIndent`, specifically the if-else, may not be correct.

**Comment by rnveach** [comment]
New Regression: http://rveach.no-ip.org/checkstyle/regression/reports/225/

@romani I assume you want me to again look into 1 of the differences to see if it is right or not?

**Comment by romani** [comment]
> forceStrictCondition is only very widely used in LineWrappingHandler this is why other handlers don't respect it in violations.

by design. line wrapping allows to do extra spaces, some people do not like extra indentation, so it become an option to allow extra spaces in line wrapping or not.

 > Some counts went down but some areas have new violations.

I have not noticed new violations. Right now I do not see big problems in diff report. It might be ok to merge. If you see some problems , please point to them.

**Comment by rnveach** [comment]
>  it become an option to allow extra spaces in line wrapping or not.

So is it a mistake that TryHandler does it and/or doesn't call LineWrappingHandler if it is a case of wrapping?

**Comment by rnveach** [comment]
http://rveach.no-ip.org/checkstyle/regression/reports/225/openjdk10/index.html#A1
The visit token is `new[541x37]`.
This violation is coming from `NewHandler.checkLeftParen`.

@romani This is a case of corruption.
When `log` is called on 542, it is given the `IndentLevel` instance and it has a value of 8. But when the violation is displayed it magically changes to `8, 12`. Because we are giving the direct instance of `IndentLevel` to the log, we are allowing the log message to be changed when the instance is corrupted later on. We only truly finalize the violation message when `LocalizedMessage.getMessage` is called.

The ident isn't corrupted until the token `OBJBLOCK[542x44]` is visited. Corruption occurs during `ObjectBlockHandler.getIndentImpl` when `indent.addAcceptedIndent` is called on the parent's ident.

**Comment by rnveach** [comment]
Let me know if you want me to look into another case. Otherwise I am fine with merging this.

**Comment by romani** [comment]
> http://rveach.no-ip.org/checkstyle/regression/reports/225/openjdk10/index.html#A1

changed from:
`'operator new lparen' has incorrect indentation level 12, expected level should be 8, 12.`
to 
`'operator new lparen' has incorrect indentation level 12, expected level should be 8.`
So there was violation, very weird violation `level 12 should be 12` :) , your update make violation messages more reasonable and clearly highlight it as bug.
Bug was before, but is stay after - no regression.

Lets wrap this PR and merge it. This PR at least small step in good direction.

**Comment by rnveach** [comment]
> Lets prepare to merge this PR

I squashed the commit. Let me know if you need anything else.

**Comment by rnveach** [comment]
@romani ping
I thought this PR was merged already for some reason.

**Pull request merged**
