### PR TITLE
Coverage has been increased to 100% in AnnotationUseStyleCheck. Issue #908

### PR DESCRIPTION
**Pull request by sabaka**
Report before changes: http://sabaka.github.io/AnnotationUseStyle/master/checkstyle.html
Report after changes: http://sabaka.github.io/AnnotationUseStyle/checkstyle.html

Tester config: https://github.com/sabaka/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties

### CODE REVIEW

**Comment by romani** [comment]
1) please do summary of reports yourself to not force me to open them and do compare - do it 
yourself 

2) Travis is not passing, need to be fixed.

**Comment by sabaka** [comment]
Hm, don't understand fail's reason. Could you take a look please?

**Comment by romani** [comment]
simple:
```
InputAnnotationUseStyleCheckTest.java -- file name
InputAnnotationuseStyleCheckTest.java -- in test
```

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
