### PR TITLE
Use field that was unused and remove suppression. #1555

### PR DESCRIPTION
**Pull request by mkordas**
Fixes `SuppressionAnnotation` inspection violations in test code.

Description:
>Reports any inspection suppression comments or annotations.

### CODE REVIEW

**Comment by romani** [comment]
merged as FF

**Comment by baratali** [comment]
@mkordas , there are violations in eclipse after this pull-request.
screenshot
```
Description	Resource	Path	Location	Type
The method setExceptionalMethod(String) from the type AutomaticBeanTest.TestBean is never used locally	AutomaticBeanTest.java	/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/api	line 116	Java Problem
The method setName(String) from the type AutomaticBeanTest.TestBean is never used locally	AutomaticBeanTest.java	/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/api	line 120	Java Problem
The method setVal(int) from the type AutomaticBeanTest.TestBean is never used locally	AutomaticBeanTest.java	/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/api	line 112	Java Problem
The method setWrong(String) from the type AutomaticBeanTest.TestBean is never used locally	AutomaticBeanTest.java	/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/api	line 108	Java Problem
The value of the field AutomaticBeanTest.TestBean.val is not used	AutomaticBeanTest.java	/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/api	line 106	Java Problem
The value of the field AutomaticBeanTest.TestBean.wrong is not used	AutomaticBeanTest.java	/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/api	line 104	Java Problem
```

**Comment by romani** [comment]
@baratali , please propose fix yourself to let @mkordas  focus on IDEA violation for end of month.

**Comment by baratali** [comment]
@romani , my fix was the opposite of this pull request :) https://github.com/checkstyle/checkstyle/pull/1690

@mkordas , will be there a violation in IDEA if I put ``@SuppressWarnings("unused")`` back?

**Comment by mkordas** [comment]
@baratali - yes. Can't we just use this field anywhere so that Eclipse does not complain?

**Pull request closed without merging**
