### PR TITLE
Issue #2938: add XWiki project to regeression testing

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by Vladlis** [comment]
@tmortagne
xwili-commons passes checkstyle during mvn verify whereas fails on mvn compile checkstyle

Can you provide us with the full shell command you use to run this step on a clean maven repo please? You can see the commands we use in the commit 9812747

**Comment by romani** [comment]
@tmortagne,

I am succeeded to compile/install only `xwiki-commons` and `xwiki-rendering` by command:
` mvn install -DskipTests -Dxwiki.clirr.skip=true`

`xwiki-platform` have some references to artifacts that are not in maven central, skipping some modules is not a solution, I stopped doing this after 10 of modules. Too complicated, we will not use it for testing.

Running Chekcstyle by maven is also complicated:
`mvn checkstyle:check install -DskipTests -Dxwiki.clirr.skip=true` - is using sun_checks.xml, build is failed.

`mvn checkstyle:check install -DskipTests -Dxwiki.clirr.skip=true -Dcheckstyle.config.location=xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/checkstyle.xml`

At first launch it complains about xwiki custom Checks, but even after removing them from config, buils is not passed due to Checkstyle violation:
```
[INFO] Building XWiki Commons - Tools - Verification Resources 8.0-milestone-1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (default-cli) @ xwiki-commons-tool-verification-resources ---
[INFO] Starting audit...
[ERROR] /var/tmp/xwiki/xwiki-commons/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/component/ComponentCheckerAnnotationProcessor.java:109:5: Cyclomatic Complexity is 14 (max allowed is 10). [CyclomaticComplexity]
[ERROR] /var/tmp/xwiki/xwiki-commons/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:58:5: Missing a Javadoc comment. [JavadocMethod]
[ERROR] /var/tmp/xwiki/xwiki-commons/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:70:5: Cyclomatic Complexity is 11 (max allowed is 10). [CyclomaticComplexity]
[ERROR] /var/tmp/xwiki/xwiki-commons/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:76:19: ';' is preceded with whitespace. [NoWhitespaceBefore]
[ERROR] /var/tmp/xwiki/xwiki-commons/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:79: switch without "default" clause. [MissingSwitchDefault]
[ERROR] /var/tmp/xwiki/xwiki-commons/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:129:75: The String "." appears 2 times in the file. [MultipleStringLiterals]
[ERROR] /var/tmp/xwiki/xwiki-commons/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:136:43: The String "@since" appears 2 times in the file. [MultipleStringLiterals]
[ERROR] /var/tmp/xwiki/xwiki-commons/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:165:5: Missing a Javadoc comment. [JavadocMethod]
Audit done.
[INFO] There are 8 errors reported by Checkstyle 6.14.1 with xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/checkstyle.xml ruleset.
[ERROR] src/main/java/org/xwiki/tool/component/ComponentCheckerAnnotationProcessor.java:[109,5] (metrics) CyclomaticComplexity: Cyclomatic Complexity is 14 (max allowed is 10).
[ERROR] src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:[58,5] (javadoc) JavadocMethod: Missing a Javadoc comment.
[ERROR] src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:[70,5] (metrics) CyclomaticComplexity: Cyclomatic Complexity is 11 (max allowed is 10).
[ERROR] src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:[76,19] (whitespace) NoWhitespaceBefore: ';' is preceded with whitespace.
[ERROR] src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:[79] (coding) MissingSwitchDefault: switch without "default" clause.
[ERROR] src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:[129,75] (coding) MultipleStringLiterals: The String "." appears 2 times in the file.
[ERROR] src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:[136,43] (coding) MultipleStringLiterals: The String "@since" appears 2 times in the file.
[ERROR] src/main/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheck.java:[165,5] (javadoc) JavadocMethod: Missing a Javadoc comment.
```

please explain us how you are enforcing Checkstyle during a build.

**Comment by tmortagne** [comment]
> xwiki-platform have some references to artifacts that are not in maven central, skipping some modules is not a solution, I stopped doing this after 10 of modules. Too complicated, we will not use it for testing.

Yes as I indicated on #2869 platform require a custom settings.xml.

**Comment by tmortagne** [comment]
> please explain us how you are enforcing Checkstyle during a build.

On our side we execute `clean install -Pquality -U -e jacoco:report` which among other things execute Checkstyle, API breakage check (clirr) and test coverage (jacoco).

"XWiki Commons - Tools - Verification Resources" has checkstyle plugin <skipped> property to true (like all projects in https://github.com/xwiki/xwiki-commons/tree/master/xwiki-commons-tools) which mean that `mvn install` does not execute Checkstyle there. The issue is that `mvn checkstyle:check` does not take into account skipped property so it run the check on those projects but even if the checks is run I configured Checkstyle plugin to not fail the build in those projects (and those only), it just display the errors.

Now indeed custom rules in commons probably prevent the use of compile since other projects will need a packaged version of Verification Resources. If you had XWiki Nexus repository in settings.xml Maven would download it here so that would not be an issue I think (that's why checkstyle:check work well for me). It would also fix your issue with XWiki Platform.

**Comment by romani** [comment]
@tmortagne , thanks for pointing again settings.xml, I missed it somehow.

Your jenkins most likely use the same local maven repo and such builds `mvn compile chckstyle:check` are passing only due to the fact that some another Jenkins config already did "mvn install", here is my logs:
```
git clone https://github.com/xwiki/xwiki-commons/
cd xwiki-commons/
/var/tmp/xwiki/xwiki-commons [master|✔] $ mvn compile checkstyle:check
.....
[INFO] ------------------------------------------------------------------------
[INFO] Building XWiki Commons - Extension - Handler - Parent POM 8.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
.....
[ERROR] Failed to execute goal on project xwiki-commons-extension-handlers: Could not resolve dependencies for project org.xwiki.commons:xwiki-commons-extension-handlers:pom:8.0-SNAPSHOT: Could not find artifact org.xwiki.commons:xwiki-commons-extension-api:jar:tests:8.0-SNAPSHOT -> [Help 1]
[ERROR]
```

Commands that worked for me:
```
/var/tmp/xwiki/xwiki-commons [master|✔] $ mvn install -DskipTests -Dxwiki.clirr.skip=true checkstyle:check
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:49 min
```

```
/var/tmp/xwiki/xwiki-rendering [:998fbd1|✔] $  mvn install -DskipTests -Dxwiki.clirr.skip=true checkstyle:check
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:34 min
```

Platform is build-able with extra `settings.xml` file . But it is too demanding for resources  

```
/var/tmp/xwiki/xwiki-platform [:0d27d3e|✔] $ mvn -s ../settings.xml install -DskipTests -Dxwiki.clirr.skip=true checkstyle:check
```
First launch failed with OutOfMemmory
Second , abruptly self killed during execution
```
[INFO]          Could not find an exact match rule. Using 'closest' rule <replace-with class='com.google.gwt.user.client.impl.HistoryImplMozilla'/> based on fall back values. You may need to implement a specific binding in case the fall back behavior does not replace the missing binding
[INFO]    Compiling 108 permutations
[INFO]       Compiling permutation 0...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 6...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 3...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 4...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 7...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 5...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 2...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 1...
[INFO]       Compiling permutation 8...
Killed
```

I think we will use `xwiki-commons` only for regression for now. If we will make a problem for your project in future and such regression is only in  `xwiki-platform`  we will invest more time in usage `xwiki-platform` in our CI for regression testing.

**Comment by tmortagne** [comment]
@romani are you sure you are using XWiki settings.xml for commons ? I just reseted my local Maven repository and `mvn compile checkstyle:check` worked perfectly. It downloaded everything missing from XWiki nexus repository. Maybe it's related to your version of Maven, I tested with Maven 3.0.5 and 3.3

**Comment by romani** [comment]
Fixed by https://github.com/checkstyle/checkstyle/pull/2961

**Pull request closed without merging**
