### PR TITLE
Spelling: Fix spelling of name

### PR DESCRIPTION
**Pull request by ryanpcmcquen**

### CODE REVIEW

**Comment by Vladlis** [comment]
Correct commit message would be `spelling: fix spelling of a name`

**Comment by romani** [comment]
@ryanpcmcquen , thanks for help, I rebased and fixed commit message. merged.
Sorry for strict rules, but they do help a lot.

**Comment by romani** [comment]
additional fix was done at 48830f150e4adf5b9f98531a7044b419b898ed34

**Comment by ryanpcmcquen** [comment]
Rules are good! Meant to rebase but got busy. Thank you.

**Pull request closed without merging**
