### PR TITLE
Issue #7878: Resolve Pitest Issues ImportOrderCheck (7)

### PR DESCRIPTION
**Pull request by aryaniiit002**
Issue #7878

1) Pitest report
https://aryaniiit002.github.io/Issue-7878/pit-reports/202102041842/com.puppycrawl.tools.checkstyle.checks.imports/ImportOrderCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@63eaed7a_732

2) Surviving mutation:
`removed conditional - replaced equality check with true → SURVIVED
`
3)  Regression report:
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/PatchBranch_2021151721/reports/diff/index.html

Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/f4157cc7f398779c0f348e600885e7ae71ab828f/my_check.xml
Diff Regression projects: https://gist.githubusercontent.com/aryaniiit002/97577199a93846562de23a0d6304e496/raw/1e822753136da53287c702a879090c63061936f2/projects-to-test-on.properties

### CODE REVIEW

**Comment by aryaniiit002** [comment]
GitHub, generate report

**Comment by aryaniiit002** [comment]
GitHub, generate report

**Comment by aryaniiit002** [comment]
ok i am sorry this time i am gonna read it, last time i just thought may be it failed bcoz of commit message.

**Comment by romani** [comment]
@aryaniiit002 ,
you killed mutation so please remove line from pitest.sh
here is https://app.circleci.com/pipelines/github/checkstyle/checkstyle/4691/workflows/79b7938f-a7fb-4d9c-a885-2da0c605b0b2/jobs/73096

Line to remove:
`ImportOrderCheck.java.html:<td class='covered'><pre><span  class='survived'>            staticImportSeparator = isStatic &#38;&#38; separated;</span></pre></td></tr>`

**Comment by aryaniiit002** [comment]
ok i know i am not allowed to send such comments but `you killed mutation` i cnnt help bcoz i have been trying for so long, almost annoyed every one on gitter especially @Abhishek-kumar09 .... :)

**Comment by romani** [comment]
You need regression diff report to prove that this update is valid, please do

**Comment by rnveach** [comment]
If regression finds no differences, please read over 4b at https://github.com/checkstyle/checkstyle/issues/7797 and tell us why your change is the valid choice. I would read over all the 4s at this stage.

**Comment by aryaniiit002** [comment]
> You need regression diff report to prove that this update is valid, please do

i am trying [CHECKSTYLE-TESTER](https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#checkstyle-tester)
but i cannt see report/diff folder can you tell me what is wrong? it's taking too long. 

command i ran `aryaniiit002@ENIAC:~/Desktop/contribution/checkstyle-tester$ groovy diff.groovy --localGitRepo /home/aryaniiit002/Desktop/checkstyle --baseBranch master --patchBranch PatchBranch --config my_check.xml --listOfProjects projects-to-test-on.properties`
 but getting something like this in the end
 `Caught: java.io.IOException: Cannot run program "hg" (in directory "/home/aryaniiit002/Desktop/contribution/checkstyle-tester"): error=2, No such file or directory
java.io.IOException: Cannot run program "hg" (in directory "/home/aryaniiit002/Desktop/contribution/checkstyle-tester"): error=2, No such file or directory
......
....
....`

**Comment by Abhishek-kumar09** [comment]
from actions: 
```
Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Error during page generation: Error rendering Maven report: Failed during checkstyle execution:
Failed during checkstyle configuration: unable to parse configuration stream: 
```

Probably the configuration file provided by you is not correct, that's why you report generation is failing on your local as well as on github actions.


You should take this file: https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/my_check.xml as a template and modify accordingly to your subject of PR. 

For now you can replace your configuration file in the PR description with this: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/f4157cc7f398779c0f348e600885e7ae71ab828f/my_check.xml

**Comment by aryaniiit002** [comment]
Github, generate report

**Comment by aryaniiit002** [comment]
> tell us why your change is the valid choice

```
/**
     * Checks whether import groups should be separated.
     * @param isStatic whether the token is static or not.
     * @return true if imports groups should be separated.
     */
    private boolean needSeparator(boolean isStatic) {
        final boolean typeImportSeparator = !isStatic && separated;
        final boolean staticImportSeparator;
        if (staticImportsApart) {
            staticImportSeparator = isStatic && separatedStaticGroups;
        }
        else {
            staticImportSeparator = isStatic && separated;
        }
        final boolean separatorBetween = isStatic != lastImportStatic
            && (separated || separatedStaticGroups) && staticImportsApart;

        return typeImportSeparator || staticImportSeparator || separatorBetween;
    }
```

`staticImportSeparator = isStatic && separated;` 
here, the 1st thing we should revise is that we cannt use `separated` property for static imports we have `separatedStaticGroups` for that and if import is not static then `needSeparator`  depends upon `separated` property only.
now suppose import is static then `option` property is at focus, if option is set `top/bottom` that means `staticImportsApart` is true and if it is false means option set to `above/under/inflow`

for simplicity -
```
 * Whether static and type import groups should be split apart.
     * When the {@code option} property is set to {@code INFLOW}, {@code ABOVE} or {@code UNDER},
     * both the type and static imports use the properties {@code groups} and {@code separated}.
     * When the {@code option} property is set to {@code TOP} or {@code BOTTOM}, static imports
     * uses the properties {@code staticGroups} and {@code separatedStaticGroups}.
     **/
    private boolean staticImportsApart; 
```
so if `staticImportsApart` is false and if `separated` is true it does not matter where import is type or static, if it's not of the same group it should be out of group.  now if `separated` is false well then `needSeparator` is false, i guess.

**Review by romani — APPROVED** [review]
ok to merge

**Comment by aryaniiit002** [comment]
@romani  can we send PR if we killed any other mutator even if there is no issue regarding it?

**Comment by rnveach** [comment]
There should be an issue, but if not, then go ahead and start an issue and PR. We are actively trying to remove pitests where possible.

**Review by strkkk — APPROVED** [review]

**Review by pbludov — APPROVED** [review]

**Pull request merged**
