### PR TITLE
Pull #12244: Replace numbers in details and message in checker-framework.groovy

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
This PR contains:

- Replaces `temp-var-\\d+` with `temp-var` in `message` and `capture#\\d+` with `capture` in `details`

### CODE REVIEW

**Comment by romani** [comment]
@rnveach , please confirm execution on your local

**Comment by rnveach** [comment]
@Vyom-Yadav Please specify in the first post what issues this could be resolving (either fully or partially) so atleast we can start keeping track. If it resolved something partially, then please specify which part.

**Comment by rnveach** [comment]
@romani How do you wish me to confirm this?

PR https://github.com/checkstyle/checkstyle/pull/12223 was dropped which is causing weird issues at any time and in all of my PRs that I am trying to work on. There are still false differences at https://github.com/checkstyle/checkstyle/issues/12230 which this PR still gives (114 new survivings, 450 unnecessary). I was hoping we could drop the comparing issue and just go with https://github.com/checkstyle/checkstyle/issues/12243 .

**Comment by Vyom-Yadav** [comment]
@rnveach @romani @nrmancuso The problem with windows is the sequence of output, from logs in local:
```
[WARNING] D:\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\checks\imports\ImportControlLoader.java:[185,78] [argument] incompatible argument for parameter parent of FileImportControl.
  found   : @Initialized @Nullable PkgImportControl
[WARNING]
  required: @Initialized @NonNull PkgImportControl
```

Whereas it should be:
```
[WARNING] D:\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\checks\imports\ImportControlLoader.java:[185,78] [argument] incompatible argument for parameter parent of FileImportControl.
  found   : @Initialized @Nullable PkgImportControl
  required: @Initialized @NonNull PkgImportControl
[WARNING]................
```

As the script is based on the output, we get a lot of errors, tried a bunch of different solutions, but none worked so far.
Problematic code:
https://github.com/checkstyle/checkstyle/blob/fa6856985e3eb32f11ae63e56c19fc2181a50d06/.ci/checker-framework.groovy#L109-L114

Few resources:

- https://stackoverflow.com/questions/4959548/why-does-output-appear-in-wrong-order
- https://stackoverflow.com/questions/4216626/why-is-the-output-from-subprocess-in-wrong-order

Tried:
- https://wiki.sei.cmu.edu/confluence/display/java/FIO07-J.+Do+not+let+external+processes+block+on+IO+buffers
- https://leo3418.github.io/2021/06/20/java-processbuilder-stdout.html

**Comment by rnveach** [comment]
Please atleast do the other things I mentioned.

> As the script is based on the output, we get a lot of errors, tried a bunch of different solutions, but none worked so far.
Problematic code:

I think one issue is the way you are going against the output.

First, you don't really specify a start/end for capturing output. You are just grabbing everything. I wouldn't start capturing until you see `[INFO] --- maven-compiler-plugin`. Maybe hardcode some removals of `[INFO] Changes detected` and `[INFO] Compiling `.

Second, any `[WARNING]` should be removed from the start of the line regardless. I think you may be doing this, but this shouldn't be dependent on anything and just be blind.

When you do the above, you should be left with things like:
````
D:\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\checks\imports\ImportControlLoader.java:[185,78] [argument] incompatible argument for parameter parent of FileImportControl.
  found   : @Initialized @Nullable PkgImportControl
  required: @Initialized @NonNull PkgImportControl
````

Then just identify the "first" line as anything with a file path, and anything else is a consecutive line. You may have to remove extra spaces as I think I was seeing some differences in that regards.

**Comment by Vyom-Yadav** [comment]
> Please atleast do the other things I mentioned.

That is an enhancement and will not solve the current issue you are facing. #12243 just asks for  script to automatically add/remove suppressions and rely on git diff to pass/fail the build.

The real issue, which is making the checker unstable for windows is what is mentioned above.

**Comment by rnveach** [comment]
I was referring to my comment at https://github.com/checkstyle/checkstyle/pull/12244#issuecomment-1272412947to specify what is issues are being partially/fully covered here.

**Comment by Vyom-Yadav** [comment]
> I was referring to my comment at https://github.com/checkstyle/checkstyle/pull/12244#issuecomment-1272412947to specify what is issues are being partially/fully covered here.

It only covers two things, converting `\` to `/` internally, and removing numbers from `temp-var` and `capture`. The former is windows specific, and the latter one applies to any OS.

**Comment by nrmancuso** [comment]
@Vyom-Yadav why are we forced to couple windows support update with other change? “And” in PR description is a red flag to me. Discussion around implementation/ concept around suppression model here is getting messy, if we can separate out windows support changes, let’s do this.

**Comment by romani** [comment]
@Vyom-Yadav , there is conflict, please rebase.

**Comment by romani** [comment]
@Vyom-Yadav , please proceed with update, a bunch of stuff is blocked by this PR

**Comment by Vyom-Yadav** [comment]
@nrmancuso @rnveach @romani Doing more investigation, I don't think this is a script-related issue, it's more likely to be an issue with windows or maven.

Running:
```
mvn -e --no-transfer-progress clean compile -Pchecker-framework-nullness-optional-interning
```
in the cmd prompt, I still get the output:
```
[WARNING] D:\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\checks\imports\ImportControlLoader.java:[185,78] [argument] incompatible argument for parameter parent of FileImportControl.
  found   : @Initialized @Nullable PkgImportControl
[WARNING]
  required: @Initialized @NonNull PkgImportControl
```

instead of:
```
[WARNING] D:\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\checks\imports\ImportControlLoader.java:[185,78] [argument] incompatible argument for parameter parent of FileImportControl.
  found   : @Initialized @Nullable PkgImportControl
  required: @Initialized @NonNull PkgImportControl
[WARNING]................
```

**Comment by Vyom-Yadav** [comment]
Complete log at https://gist.githubusercontent.com/Vyom-Yadav/f2d88a6e765e3ad8547012d2c82b6837/raw/1476e8baa11461808f5e9011e61ae4a0a075e1d2/log.txt

**Comment by rnveach** [comment]
This PR needs to be split up more into pieces we need, and then point those pieces to their respective issues and say how complete the fix is. Windows support will require https://github.com/checkstyle/checkstyle/pull/12244#issuecomment-1272559147 to fix line handling.

For the first PR we need the `Replaces temp-var-\\d+ with temp-var in message and capture#\\d+ with capture in details` in its own PR to merge quickly. We need these values to be replaced before we put them into Details class so they are written to the XML file.

**Comment by rnveach** [comment]
@Vyom-Yadav Can we just trim this PR to just only the replaces? I noticed there is still other things like changing the hash, and removal of unstables.

**Comment by Vyom-Yadav** [comment]
> @Vyom-Yadav Can we just trim this PR to just only the replaces? I noticed there is still other things like changing the hash, and removal of unstables.

Unstable and custom hashing methods were added for handling `capture#` and `temp-var-` only, they can be safely removed.

**Comment by Vyom-Yadav** [comment]
> @nrmancuso @rnveach @romani Doing more investigation, I don't think this is a script-related issue, it's more likely to be an issue with windows or maven.

https://issues.apache.org/jira/browse/MNG-7567

**Comment by romani** [comment]
it is known problem of logging in all places, it might be unsync.
It is much better to not use such builds outputs and use reports that are synced.

**Comment by romani** [comment]
if behavior of logging is not deterministic .... and only on windows
we can have support only for Linux for now, people from windown will use our patch generation in CI.
Please take this from https://github.com/checkstyle/checkstyle/pull/12294

Looks like we need to sort all violations before saving them to file to have predictable behavior. CI will be our source of truth for what suppression file should looks like.

**Review by romani — APPROVED** [review]
let merge this  first, it is step forward.

**Comment by romani** [comment]
ok, after discussion in chat with rnveach.

@Vyom-Yadav , please split this PR in few steps and please clearly define what you are fixing.
this Checker adventure becomes messy .... we need to record all details.

**Comment by romani** [comment]
@Vyom-Yadav , if you are around please rebase and resolve conflicts. Please try to keep unstable feature in script, it might be unused now, but it might b used in future.

**Comment by Vyom-Yadav** [comment]
The patch for removing numbers from message and detail has been applied at https://github.com/checkstyle/checkstyle/pull/12294

**Comment by romani** [comment]
@Vyom-Yadav, please recreate your PR with removal of hashcode override and window s support. We still need such updates.

**Pull request closed without merging**
