### PR TITLE
Issue #13321: Kill mutation for UncommentedMainCheck-1

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for UncommentedMainCheck-1

---------

# Check
https://checkstyle.org/checks/misc/uncommentedmain.html

---------

# Mutation 
https://github.com/checkstyle/checkstyle/blob/2be5780673b9ba5397526aadab981be68f874172/config/pitest-suppressions/pitest-misc-suppressions.xml#L192-L199

---------

# Explaination 
Test added

### CODE REVIEW

**Comment by Kevin222004** [comment]
This is bug do you agree
```
kevin@inspiron-15-5510:~/Desktop/check_style$ javac Test.java
kevin@inspiron-15-5510:~/Desktop/check_style$ cat Test.java
public record Test(Integer x) {
    class inter {
        class useless {
            record unu(String K) {
                public static void main(String[] args) { // violation line no:-5
                    System.out.println("I am violated");
                }
            }
        }
    }
    
    class xyz {
        class ff {
            public static void main(String[] args) { // expected violation line :- 14

            }
        }
    }
}

kevin@inspiron-15-5510:~/Desktop/check_style$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC 
 "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
 "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="UncommentedMain">
        </module>

    </module>
</module>

kevin@inspiron-15-5510:~/Desktop/check_style$ java -jar /home/kevin/Downloads/checkstyle-10.12.1-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/kevin/Desktop/check_style/Test.java:5:17: Uncommented main method found. [UncommentedMain]
Audit done.
Checkstyle ends with 1 errors.
kevin@inspiron-15-5510:~/Desktop/check_style$ 
```

**Comment by romani** [comment]
@Kevin222004, please define what you expect to let me agree with you on what you mean.
Can we run such main method ? If we can not run them by java, they are not main methods. If we can run both, we can create issue to report two violations.

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
We can continue discussion , I just merged PR to not block it

**Comment by Kevin222004** [comment]
> Can we run such main method ?
No, we can't run that.  so that is not not violation

**Comment by romani** [comment]
Please create issue  to have no violation on code that you shared

**Pull request merged**
