### PR TITLE
Issue #2661: Enforce SimpleAccessorNameNotation of sevntu-checkstyle …

### PR DESCRIPTION
**Pull request by MEZk**
…over Checkstyle source code

### CODE REVIEW

**Comment by romani** [comment]
> sevntu_suppressions.xml
Override methods from base class

Please put in description of suppresion, a reason - https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/166

> Renaming of the method breaks BeanUtils

Ans now we run into this ancient comment again, can you give more detailed reason why we should do this? please rename as required and run "mvn verify" now we have 100% test, if problem still exists we need to put a link to issue of related project.

**Comment by MEZk** [comment]
@romani 
>Please put in description of suppresion, a reason - sevntu-checkstyle/sevntu.checkstyle#166

Done.

>Ans now we run into this ancient comment again, can you give more detailed reason why we should do this? please rename as required and run "mvn verify" now we have 100% test, if problem still exists we need to put a link to issue of related project.

Renaming method 'getAbstractOption' to 'getOption' and making it package-local (as we don't use it outside the package) resolve the problem.

**Comment by romani** [comment]
> Renaming method 'getAbstractOption' to 'getOption' and making it package-local 

I did not found any usage even in package, it is used only in this class, can we do it private ?
Or point me to the code that use it out of this class

>```
+    <suppress checks="SimpleAccessorNameNotation"
+              files="ClassDataAbstractionCouplingCheck.java|ClassFanOutComplexityCheck.java"
+              lines="71,76"/>
```

in this case lines 71 and 76 in both files are ignored, but suppressions should be strict.

**Comment by MEZk** [comment]
@romani 
1) See https://github.com/checkstyle/checkstyle/blob/3a2cb4d787e3c626bb0e2e02915cc1c37deb9d0b/src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java#L434
We use it in the UTs which is located in the same package.

**Comment by romani** [comment]
> We use it in the UTs which is located in the same package.

That is not a good reason. method has to be private. UT need to be updated.

**Comment by MEZk** [comment]
@romani 
Done

**Comment by romani** [comment]
Please remove this private getter and use field dirrectly.

**Comment by MEZk** [comment]
@romani 
Done.

**Pull request merged**
