### PR TITLE
Issue #5476: Only check internal separation when ImportOrder.separated=true

### PR DESCRIPTION
**Pull request by jonmbake**
@romani I realize this isn't approved yet, but please consider. It is a major regression from <8.3. Feel free to close if Issue #5476 is not approved.

Thanks,
Jon

### CODE REVIEW

**Comment by RohanNagar** [comment]
Can someone please review this? I consider this essential to be able to upgrade from <8.3 without breaking.

**Comment by RohanNagar** [comment]
Is someone willing to take a look at this?

**Comment by romani** [comment]
@jonmbake , 

sorry for delay.
I am try to focus myself of ImportOrder damage now .... , too much conflicting demands for behavior.
Your commit looks like almost reverting https://github.com/checkstyle/checkstyle/commit/a736d191a9d240a3a8b3a90b5651eb98b3af7d18 

please rebase your fix on latest master, and resolve CI problems.
Issue is not approved, I need to gather all fact and think one more time how we should reconcile all demands.

**Comment by romani** [comment]
Issue is not approved, main comment is https://github.com/checkstyle/checkstyle/issues/5476#issuecomment-374007438

I am closing this PR for now(to ease PR management), till we finish discussion in issue, .

**Pull request closed without merging**
