### PR TITLE
Issue #7119: fix no expected violations for empty line within import group

### PR DESCRIPTION
**Pull request by gmshake**
BLOCKED BY #7197

What has been done:

1. Issue #7119 was fixed.
2. Slightly changed behavior about how to detect empty lines. Now take comments between imports or import groups into account.

Note: merge https://github.com/checkstyle/checkstyle/pull/7197 (for #6680) before this one.

### CODE REVIEW

**Comment by rnveach** [comment]
@gmshake If this is fixing 2 separate issues, as you have 2 commits with 2 issue numbers, then I recommend only having 1 issue per PR if they can be separated.
It may be easier to merge one over the other.

Please look over travis failure.
Wercker failure is regression in pgjdbc.
> [ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/main/java/org/postgresql/ssl/SingleCertValidatingFactory.java:22: Extra separation in import group before 'javax.net.ssl.SSLContext' [CustomImportOrder]
[ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/main/java/org/postgresql/ssl/WrappedFactory.java:12: Extra separation in import group before 'javax.net.ssl.SSLSocketFactory' [CustomImportOrder]
[ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/main/java/org/postgresql/ssl/LazyKeyManager.java:33: Extra separation in import group before 'javax.crypto.Cipher' [CustomImportOrder]
[ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/main/java/org/postgresql/ssl/DbKeyStoreSocketFactory.java:11: Extra separation in import group before 'javax.net.ssl.KeyManagerFactory' [CustomImportOrder]
[ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/main/java/org/postgresql/ssl/NonValidatingFactory.java:11: Extra separation in import group before 'javax.net.ssl.SSLContext' [CustomImportOrder]
[ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/main/java/org/postgresql/ds/PGPooledConnection.java:25: Extra separation in import group before 'javax.sql.ConnectionEvent' [CustomImportOrder]

**Comment by gmshake** [comment]
@rnveach This fix is based on issue #6680, and fixing only #7119 .

It looks I do not have access to wercker, it gave me a 401 response.

For the regression in pgjdbc, I think it is expected. I would explain this further more.

The `CustomImportOrderCheck` defines `STANDARD_JAVA_PACKAGE` and the regex defaults to `^(java|javax)\.` .  Once we fixed #7119, the following code snip would certainly violates:
```java
import java.util.*;

import javax.swing.*
```

As Eclipse IDE add separate line between `java` and `javax`, and lots of projects prefer separating `java` and `javax`, it looks not kind to end user.

**Comment by gmshake** [comment]
@rnveach The travis failure look weird. I'm inspecting it yet.

**Comment by rnveach** [comment]
I pasted the failure in wercker which is pgjdbc. If @romani agrees with this logic change, we will have to make a PR to pgjdbc (or our own fork) to fix the issue to make our CI pass.

**Comment by rnveach** [comment]
@gmshake since 6680 is in another PR now, please remove it from this one.

**Comment by romani** [comment]
@gmshake , ping, please do and resolve CI issues.

**Comment by romani** [comment]
Issue is approved, I restarted Travis, so PR validation should pass, but there were other failures ... if they stay ... you need to resolve them.

**Comment by romani** [comment]
Travis failure - https://travis-ci.org/checkstyle/checkstyle/jobs/597932539#L625 :
`[WARN] /home/travis/build/checkstyle/checkstyle/src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputNoLineWrapGood.java:7: Extra separation in import group before 'java.util.concurrent.atomic.AtomicIntegerFieldUpdater' [CustomImportOrder]`

**Comment by romani** [comment]
@gmshake , lease rebase this PR on your other PR, sorry that I pushed with force to your branch, but I needed this to speedup review/merge.
You will most likely have conflicts, please resolve them.

Please address CI failures, lets prepare for final reviews. Sorry for long delay in reply.

**Comment by gmshake** [comment]
@romani You're kind!  I will manage it after #7197 .

**Comment by romani** [comment]
@gmshake , blocker PR is merged ..... this PR is unblocked but contains a lot of old comments ..... please create PR, lets start from scratch, please do not forget to provide regression report.

I am closing this PR.

**Comment by gmshake** [comment]
@romani OK.

**Pull request closed without merging**
