### PR TITLE
issue #7616:Added visibilityModifiers examples

### PR DESCRIPTION
**Pull request by AlenJoseph55**

### CODE REVIEW

**Comment by romani** [comment]
make sure that "mvn verify" works on your local, and read PR template very  attentively.

**Comment by AlenJoseph55** [comment]
MVN verify shows a lot of errors. What should I do to resolve this?

**Comment by romani** [comment]
Read all errors attentively
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=13146&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=834

And follow what verification demand. Build must be green.

**Comment by nrmancuso** [comment]
@AlenJoseph55 do you plan to continue work on this PR?

**Comment by AlenJoseph55** [comment]
Yes, But I am stuck on the errors on MVN verify. And also I caught up on exams....I will try to update the pr within 2-3 days if that is okay.

**Pull request closed without merging**
