### PR TITLE
Issue #2425: fixed invalid xml examples in xdocs

### PR DESCRIPTION
**Pull request by rnveach**
First pass.
Added new junit to find invalid XMLs or CS configurations that don't actually work, and fixed all violations.
Still todo:
-- Have to refactor junit code for complexity complaints.
-- have to verify class' examples aren't a copy of the invalid xdocs ones

Description of the more major changes:
PackageObjectFactory: I couldn't get past "NoClassDef" exception for "AbstractClassName" without this extra catch here. I don't know what I am doing different that CS' doesn't complain about this anywhere else.
NonEmptyAtclauseDescriptionCheck: It doesn't support the 'target' property at all and I didn't see any work around.
AllChecksPresentOnAvailableChecksPageTest: Renamed to 'XDocsPagesTest' since it will now house more xdoc checks.
config_regexp.xml: The whole string was not a valid regular expression format, so most of the fixes revolve around that by santizing '\' and '['.

### CODE REVIEW

**Comment by rnveach** [comment]
This is ready for review now.

I added a suppression for catching Throwable.
The original reason for this was the NoClassDef exception was being thrown and we weren't given an assertion on the file name and the XML in question. I feel we should be catching all exceptions so we can give this information to the user as we are testing many pages and many XMLs.

Most other changes are to the new junit code I added, moving stuff around to reduce complexity.

**Comment by romani** [comment]
amazing Test!


please remove suppression for catching Throwable. If we expect  NoClassDef catch it in method that is annotated by "Test" and do assert with details. All unexpected exceptions should go further to JUnit and will be printed to user. Full Stack trace exception in UTs is always OK.

**Comment by rnveach** [comment]
Done.

**Comment by rnveach** [comment]
travis node failed because of a timeout after the build success.

**Pull request merged**
