### PR TITLE
4043 - Split and Organize Checkstyle inputs by Test for OuterTypeNumber

### PR DESCRIPTION
**Pull request by tashish**
Issue : 4043 - Split and Organize Checkstyle inputs by Test for OuterTypeNumber
@romani 
Kindly review the PR and provide comments. 
Thanks
Ashish

### CODE REVIEW

**Comment by Vladlis** [comment]
@tashish 
Please follow https://github.com/checkstyle/checkstyle/wiki/PR-rules

**Comment by romani** [comment]
@tashish , please follow errors from CIs and improve the code and PR description and commit message.
All Cis should be green.
Please run "mvn verify" on you local before pushing any code to remote for review.

**Comment by tashish** [comment]
Thanks @Vladlis  and @romani for letting me know about the issues. I will address these and resubmit the PR.

**Comment by romani** [comment]
@tashish , you do not need to close PR to change smth in it.
Please reopen it , and push changes in the same branch, PR will be refreshed automatically.

**Comment by tashish** [comment]
@romani Apologies for confusion, I will use the same PR now onwards. In fact, just submitted a commit to the other open PR to address CR comment. Thanks

**Pull request closed without merging**
