### PR TITLE
Change message in SummaryJavadocCheck, #2062

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by romani** [comment]
@Vladlis, please make commit message by format "Issue #XXXXX: .............."

@sabaka , @mkordas , please share your opinion on new wording of message.

**Comment by Vladlis** [comment]
Done

**Comment by mkordas** [comment]
Proposed message is definitely more understandable than previous one, but `missed` is repeated twice. Here are my propositions:
1. `First sentence of Javadoc is incomplete or not present (period is missing)`
1. `Javadoc does not contain summary sentence ending with period`
1. `No period at the end of first sentence in Javadoc`

**Comment by romani** [comment]
I propose 'First sentence of Javadoc is incomplete    (period is missing) or not present '

**Comment by Vladlis** [comment]
@romani, sounds good

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
