### PR TITLE
Issue #7671: Update doc for NoFinalizer 

### PR DESCRIPTION
**Pull request by OmarShawky1**
Updating Update doc for NoFinalizer #7671

### CODE REVIEW

**Comment by romani** [comment]
@OmarShawky1 , please attentively read issue description (all referenced links) and PR rules https://github.com/checkstyle/checkstyle/wiki/PR-rules .

CI should be green, before human start to review code.

**Comment by OmarShawky1** [comment]
i have no clue what error is this 
image

 i failed to trace it back, this is generated from mvn clean verify -e

**Comment by strkkk** [comment]
@OmarShawky1 Please see https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by OmarShawky1** [comment]
how to sync documentation content between xml and java file? i cannot find anything near this in google nor duckduckgo or the class "XdocsJavaDocsTest"

**Comment by baratali** [comment]
@OmarShawky1 
> how to sync documentation content between xml and java file?

Find xml file in `src/xdocs/` which contains documentation for your Check and update similar to what you did in javadoc.
Example: https://github.com/checkstyle/checkstyle/pull/7634/files

Also:
1. Please make git commits from your git account. Now author is Ipowe, which doesn't exist in github
2. Please do not keep useless commits in this branch. For example now there are 10 commits, but should be only one. Please squash them into one. Read this again https://github.com/checkstyle/checkstyle/wiki/PR-rules

**Comment by OmarShawky1** [comment]
i tried to make sense of the last error but it does not make sense to me, there is no any line indication etc.
Annotation 2020-03-08 111825

**Comment by rnveach** [comment]
@OmarShawky1 You are looking at the summary. You need to scroll up and find the failing test with the full message.
Example: https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/31323852/job/g4pbjhb11q0i3fwc#L724

**Comment by OmarShawky1** [comment]
yes i did try to scroll up but i found nothing, this is the error:
[new file.txt](https://github.com/checkstyle/checkstyle/files/4304934/new.file.txt)

i did try to read it more than once but the only thing i found is 
Screenshot from 2020-03-09 08-24-52
but i never edited it

**Comment by baratali** [comment]
@OmarShawky1 , it fails because javadoc content is not the same as xdocs content of NoFinalizer check

**Comment by romani** [comment]
@OmarShawky1 , please squash al commits at one, please remove unnecessary changes.

**Pull request closed without merging**
