### PR TITLE
Added feed icons to site, issue #617

### PR DESCRIPTION
**Pull request by alexkravin**
According to #617 

As in xdocs it's possible to change only body, site will appear as it was specified in site.xml - added rss icon to the top-right corner of the site.

Added rss-long image to poweredBy section

Found google-groups image fits the most to long images.

### CODE REVIEW

**Comment by romani** [comment]
after site generation I still see "Extending Checkstyle" not under "Developers" group. please generate site and put some pages on github.io

**Comment by romani** [comment]
I do not understand why other image us used for google groups. On image on RSS is hard to read - please adjust image or use another image.

**Comment by alexkravin** [comment]
1) Because it is in scope of other issue and specified in other pr

2) updated images, please, make a review

**Comment by romani** [comment]
screenshot - 02252015 - 03 47 21 pm

Are these good images ? I can not read text for google group and RSS is ugly.

**Comment by romani** [comment]
please rebase your changes on latest sources to let Travis be happy (restart does not help).

**Comment by romani** [comment]
for user group forum - make picture to have icon of QnA and simple text on the right, without overlap:
"[icon] User Group Forum"

**Comment by alexkravin** [comment]
```
Google group image should be rectangular - I like there (with same text, but image is a bit bigger) : http://www.safeharbors.org/SHUserGroup.htm, but text should be <b>part of image</b>.
```

So... Square image with text on the right?

**Comment by romani** [comment]
yes, as I requested originally, result image is combination of image from that site or similar + text on the right(as image).

**Comment by alexkravin** [comment]
Updated google groups image

http://alexkravin.github.io/feeds/index.html

**Pull request merged**
