### PR TITLE
Issue #2625: reorganized internal tests

### PR DESCRIPTION
**Pull request by rnveach**
All the changes I said I would do are in the main issue.
This is just mostly moving files around and moving common utilities/fields to their own utility class. My main reason for creating fields is for caching and to eventually use these values for more tests.

### CODE REVIEW

**Comment by rnveach** [comment]
One change I didn't count on:
BaseCheckTestSupport.createChecker had to be made public since it is outside the same package as AllChecksTest which calls this method.

Additional questions:
1) Should `CommitValidationTest` be in the internal package?
2) Should `TestUtils` be in the internal package?

**Comment by romani** [comment]
> 1) Should CommitValidationTest be in the internal package?
2) Should TestUtils be in the internal package?

yes, make sense, for both.

> BaseCheckTestSupport.createChecker had to be made public

it is ok.

**Comment by rnveach** [comment]
@romani 
I made the changes.
I had to remove the cache fields, since I couldn't get around the errors. I think private instances will work, so if I start using these then I'll try that route.
`'public static' collection field ALL_FILES, compromising security`
`getAllFiles() 'return' of Collection field ALL_FILES`
`getAllFiles() Lazy initialization of 'static' field ALL_FILES is not thread-safe`

> please do "git mv ...... " to let git keep history

I couldn't get this to work.
EGit did the other files, but not this one for some reason. I tried to force it by moving the files back and forth, but it never took.
I did the same in the command line and `git commit` sometimes would say 'renamed' but the final amend always reverted back to delete/create for me. Maybe I am doing something wrong as I am not as familiar with the command line.

> made PackageObjectFactory public

This was needed because it was package-private, and the util class moved outside the package. TC won't allow a getter in the same package because it could escape outside the package. The only other choice was to use reflection or create a getter to get the field `moduleFactory`.

**Comment by romani** [comment]
I am ok with update, merged as FF (one commit message was reworded).

in future please never name as "minor" updates that need to be explained, full description should be provided or reference to issue should be in message.

**Pull request closed without merging**
