### PR TITLE
Issue #2285: Add possibility to track down the name of source file which caused the internal Exception or Error

### PR DESCRIPTION
**Pull request by MEZk**

### CODE REVIEW

**Comment by romani** [comment]
wrapping Errors to Exception is not good.

please do separate block of catch and do rethrow of Error:
```
catch (Error error) {
   throw new Error("....", error);
}
catch (Trowable throwable) {
   throw new Throwable("....", throwable);
}

```

**Comment by MEZk** [comment]
@romani 

1) Added ```@SuppressWarnings("ProhibitedExceptionThrown")``` to supress IDEA violation. I think that  ```@SuppressWarnings``` annotation for IDEA is better than ```//noinspection``` comment.
2) Added ```@SuppressWarnings("ProhibitedExceptionThrown")``` to allowed annotations of SuppressionAnnotation inspection.
3) Implemented UT to satisfy coverage rate.
4) Extracted method 'processFile' from 'processFiles' to decrease cyclomatic complexity. Are you OK with the name?

**Comment by romani** [comment]
>  I think that `@SuppressWarnings` annotation for IDEA is better than //noinspection comment.

If the whole team is working in InteliJIDEA - yes. But this is not true for our project. InteliJ is just another static analysis tool for us. We can switch it OFF at any time and there should be no remnants of InteliJIdea. We do not allow the same(suppression by annotation) even for Checkstyle violations. 
Update to javadoc affect in the smallest way our code.

Please use javadoc tag.

>  Are you OK with the name? 

I am ok.

1)
> rulesets/java/strictexception.xml/AvoidThrowingRawExceptionTypes

I do not see explanation of suppress.

2)
> catch (Error error) {

please move this block under catch of Exception

**Comment by MEZk** [comment]
@romani 
>Please use javadoc tag.

Done.

1) Added explanation of suppress.
2) Done

**Comment by romani** [comment]
>  //noinspection ProhibitedExceptionThrown (suppresses IntelliJ IDEA inspection)

should be in javadoc like , see example at https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L88

**Comment by MEZk** [comment]
@romani 
Done.

**Comment by romani** [comment]
merged as FF

**Pull request merged**
