### PR TITLE
Issue #8325: use maven 3.6.3-jdk-11 for wercker build

### PR DESCRIPTION
**Pull request by pbludov**
Issue #8325

### CODE REVIEW

**Comment by romani** [comment]
from wercker:
`Command: ./.ci/wercker.sh no-error-sevntu-checks`

`Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.sun:tools:jar:0 at specified path /usr/local/openjdk-11/../lib/tools.jar`

**Comment by pbludov** [comment]
> please try to use in sevntu:

We need to update Sevntu.Checkstyle to use JaCoCo. I'l start an issue for this.

**Comment by romani** [comment]
It might be not simple to upgrade, there are s lot of places to change, but doable and benefitial by all means

**Comment by pbludov** [comment]
The build succeeded.

**Pull request merged**
