### PR TITLE
Issue #5528: migration to circleci 2.0

### PR DESCRIPTION
**Pull request by romani**
Issue #5528

### CODE REVIEW

**Comment by romani** [comment]
@jsoref , can you explain what does this output mean  ? why it complain about openjdk, .... ?

```
Review results
New misspellings found, please review:
dependecies
hadoop (Hadoop, hadoop)
infinispan
lucene
openjdk
protonpack
Ubuntu
workflows
If you are ok with the output of this run, you will need to
git clone https://github.com/checkstyle/contribution.git contribution; cd contribution;
patch jsoref-spellchecker/whitelist.words <<EOF
@@ -492,0 +493 @@
+dependecies
@@ -828 +829 @@
-hadoop (HADOOP, Hadoop, hadoop)
+hadoop (Hadoop, hadoop)
@@ -911 +912 @@
-infinispan (INFINISPAN, infinispan)
+infinispan
@@ -1013 +1013,0 @@
-JOOL
@@ -1146 +1146 @@
-lucene (LUCENE, lucene)
+lucene
@@ -1380 +1380 @@
-openjdk (OPENJDK, openjdk)
+openjdk
@@ -1495 +1495 @@
-protonpack (PROTONPACK, protonpack)
+protonpack
@@ -2349 +2349 @@
-ubuntu (Ubuntu, ubuntu)
+Ubuntu
@@ -3492,0 +3493 @@
+workflows
```

**Comment by romani** [comment]
merged manually

**Comment by romani** [comment]
@jsoref , fyi https://github.com/checkstyle/checkstyle/commit/768c700f683c7e4bfbec3a7bb1c36edeca2dc6c2 , to avoid blocking PRs merge process.

**Comment by jsoref** [comment]
The spelling checker reports each case variation separately (along with plurals and possessives) because they hint at "real things that should be ignored". The jitter for open jdk was that it was no longer seeing the all uppercase version.

**Comment by romani** [comment]
> dependecies

fixed.

> workflows

added to while list

**Pull request closed without merging**
