### PR TITLE
Issue #1048: Duplicate error message for static final field in Declar…

### PR DESCRIPTION
**Pull request by liscju**
…ationOrderCheck

I had to divide ProcessModifiers into methods processModifiersState and processModifiersSubState because of CyclomaticComplexity violation when i added isStateValid variable to it.

### CODE REVIEW

**Comment by romani** [comment]
code is ok.

please provide diff reports.

**Comment by liscju** [comment]
@romani , i generated diff report on guava,openjdk,spring-framework and hibernate and the diff result is here: http://liscju.github.io/issue1048/diff/site.html , http://liscju.github.io/issue1048/before/target/site/checkstyle.html , http://liscju.github.io/issue1048/after/target/site/checkstyle.html  - the diff seem that the check is correct , the result is huge (more than 700 differences) but i tried my best to check it attentively.

I have little doubts that the commit message is 100% correct because it doesn't only prevents from duplicating error messages for static final fields, but also for only final fields like:

```java
private int i;
final int k;
```

In this instance before fix errors would be "Instance variable definition in wrong order" and "Variable access definition in wrong order.".

**Comment by romani** [comment]
merged as FF.

1)
> In this instance before fix errors would be "Instance variable definition in wrong order" and "Variable access definition in wrong order.".

Yes, you are right, please create separate issue on this.

**Comment by liscju** [comment]
@romani issue https://github.com/checkstyle/checkstyle/issues/2928

**Pull request closed without merging**
