### PR TITLE
Issue #4080: Split and Organize Checkstyle inputs by Test for SingleSpaceSeparator

### PR DESCRIPTION
**Pull request by wate123**
Issue:#4080

### CODE REVIEW

**Comment by wate123** [comment]
`SingleSpaceSeparatorCheckTest.testSpaceErrors:88->BaseCheckTestSupport.verify:191->BaseCheckTestSupport.verify:227->BaseCheckTestSupport.verify:258 error message 28 expected:<...aratorErrors.java:6:[42]: Use a single space...> but was:<...aratorErrors.java:6:[51]: Use a single space...>
`

Can't get rid off it.

**Comment by romani** [comment]
please rebase on latest code to resolve TC problem, TC problems are resolved in our master.

**Comment by wate123** [comment]
The fail test is still there after the rebase.

**Comment by rnveach** [comment]
> Can't get rid of it.

Look at `InputSingleSpaceSeparatorErrors ` and the test that is failing.
Violation is on the same line as the class name that was renamed. Violation has column position in it and because of the rename, the positioning of the violation changed.

To fix this, class name and file name must be undone and remain as they originally was. Names will be fixed in final commits for main issue.

**Comment by romani** [comment]
@wate123 , please rebase on our latest mater to resolve CI problems

**Comment by wate123** [comment]
I hate this... accidentally delete this branch

**Comment by rnveach** [comment]
@wate123 You don't have a button to re-open it?

**Comment by wate123** [comment]
@rnveach it doesn't allow me to reopen

**Comment by rnveach** [comment]
Then please open a new PR as we were almost ready to merge this

**Pull request closed without merging**
