### PR TITLE
minor: added refernce of issues 15791 & 15792 in google style coverage table for section 4.1.2 KR blocks

### LINKED ISSUE #15797: Review google style coverage table to remove links to closed issues
https://checkstyle.org/google_style.html#Google_Coverage_table

This table should not have references to closed issues with prefix "until".

### PR DESCRIPTION
**Pull request by Zopsss**
Closes #15797

### CODE REVIEW

**Comment by romani** [comment]
@Zopsss , please fix CI failure. To reference new issues from Inputs.

**Comment by romani** [comment]
GitHub, generate website

**Comment by romani** [comment]
@Zopsss , please use https://github.com/checkstyle/checkstyle/issues/15797 issue  as prefix for commit

**Comment by romani** [comment]
GitHub, generate website

**Comment by romani** [comment]
GitHub, generate website

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by Zopsss** [comment]
Sorry that you had to push changes! I wasn't active for last few days :(

**Pull request merged**
