### PR TITLE
Issue #4582: restored wercker xwiki

### PR DESCRIPTION
**Pull request by rnveach**
Issue #4582

This is the final PR.

### CODE REVIEW

**Comment by rnveach** [comment]
> Could not find artifact org.xwiki.commons:xwiki-commons-tool-enforcer-dependencies:jar:9.6-SNAPSHOT

@romani Must we rely on release versions for xwiki?

**Comment by romani** [comment]
>Must we rely on release versions for xwiki?

Whatever work for us.

**Comment by rnveach** [comment]
@romani Please review.
XWiki passed on full build in 1 minute 12 seconds.

Is it possible to double verify that snapshot was used? I don't see any logging that specifies that.

**Comment by romani** [comment]
previously it took about 2 min - https://app.wercker.com/checkstyle/checkstyle/runs/build/5950d1b4fe92eb00013b712f?step=5950d1d442d5cc000152a154 . 
But in your PR logs I see that checkstyle is started - `[INFO] Starting audit...`.... so smth works.
The only prove we can do is to remove all old versions from maven repository on local and launch build.

**Pull request merged**
