### PR TITLE
Issue #12671: Kill mutation for finalLocalVariable-3

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #12671: Kill mutation for finalLocalVariable-3

-------

# check
https://checkstyle.org/config_coding.html#FinalLocalVariable

-------

# Mutation covered 
https://github.com/checkstyle/checkstyle/blob/398035a2cc135f86523f1942b468b2b06b717919/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L30-L37

----

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
Good catch https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/74974b5_2023202805/reports/diff/intellij-community/index.html#A1

**Review by romani — CHANGES_REQUESTED** [review]
Just test extension to kill mutation.
Merging quickly as CI pass and conflict resolved

**Review by nrmancuso — APPROVED** [review]

**Pull request merged**
