### PR TITLE
Issue #7732: Update AbstractChecks to log DetailAST - IllegalC…

### LINKED ISSUE #7732: Update AbstractChecks to log DetailAST - IllegalCatch
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on IllegalCatch.

### PR DESCRIPTION
**Pull request by sulkykookie**
Fixes #7732 

This check already reports on the DetailAST node:
https://github.com/checkstyle/checkstyle/blob/34615b4a3c8f8826fb6961ed9a35449e73c16a2f/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java#L187

Diff report:
https://sulkykookie.github.io/illegalcatch/

### CODE REVIEW

**Comment by sulkykookie** [comment]
@strkkk Please review

**Comment by strkkk** [comment]
@sulkykookie in fact, you didn't fix a problem. It should log ast position instead of line, but I don't see these changes in code.

Please fix and recreate diff report.

**Comment by sulkykookie** [comment]
> @sulkykookie in fact, you didn't fix a problem. It should log ast position instead of line, but I don't see these changes in code.
> 
> Please fix and recreate diff report.

The check already logs ast position I guess. I checked the already existing test files and they already have the position:
https://github.com/checkstyle/checkstyle/blob/f9131f9536c71d963c83aab1550b7a0371aa9ff5/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheckTest.java#L60
for example.
Also the check already logs on the ast node:
https://github.com/checkstyle/checkstyle/blob/34615b4a3c8f8826fb6961ed9a35449e73c16a2f/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java#L187

I didn't quite understand what else needs a fix in this. Please help

**Comment by strkkk** [comment]
Sorry, I missed comment in original issue. It is ok, my bad.

**Pull request merged**
