### PR TITLE
add jacoco.exec to .gitignore

### PR DESCRIPTION
**Pull request by qxo**
jacoco.exec should be ignored

### CODE REVIEW

**Review by romani — CHANGES_REQUESTED** [review]
Our CI detecting any repository git changes, it doesn't detect this.

**Comment by strkkk** [comment]
@qxo jacoco file is placed inside target folder which is already mentioned in gitignore file, there is no need to add jacoco there explicitly.

**Comment by qxo** [comment]
> @qxo jacoco file is placed inside target folder which is already mentioned in gitignore file, there is no need to add jacoco there explicitly.

the  jacoco.exec will be on target folder, if we run test with mvn cmd,
But it will on project root folder. if we compile test with maven: 'mvn test-compile`, then run test on eclipse(ide) .

**Comment by romani** [comment]
I do not see it as problem in CLI and I have never had in IDEs
```
$ mvn clean test-compile
...
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ checkstyle ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1989 source files to /home/rivanov/java/github/romani/checkstyle/target/test-classes
[INFO] /home/rivanov/java/github/romani/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda5.java: Some input files use or override a deprecated API.
[INFO] /home/rivanov/java/github/romani/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda5.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/rivanov/java/github/romani/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtilTest.java: Some input files use unchecked or unsafe operations.
[INFO] /home/rivanov/java/github/romani/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtilTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.5:instrument (default-instrument) @ checkstyle ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.358 s
[INFO] Finished at: 2020-09-07T09:10:54-07:00
[INFO] ------------------------------------------------------------------------

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

```

**Comment by qxo** [comment]
> I do not see it as problem in CLI and I have never had such problem in IDEs
> 
> ```
> $ mvn clean test-compile
> ...
> [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ checkstyle ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 1989 source files to /home/rivanov/java/github/romani/checkstyle/target/test-classes
> [INFO] /home/rivanov/java/github/romani/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda5.java: Some input files use or override a deprecated API.
> [INFO] /home/rivanov/java/github/romani/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda5.java: Recompile with -Xlint:deprecation for details.
> [INFO] /home/rivanov/java/github/romani/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtilTest.java: Some input files use unchecked or unsafe operations.
> [INFO] /home/rivanov/java/github/romani/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtilTest.java: Recompile with -Xlint:unchecked for details.
> [INFO] 
> [INFO] --- jacoco-maven-plugin:0.8.5:instrument (default-instrument) @ checkstyle ---
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  16.358 s
> [INFO] Finished at: 2020-09-07T09:10:54-07:00
> [INFO] ------------------------------------------------------------------------
> 
> $ git status
> On branch master
> Your branch is up-to-date with 'origin/master'.
> nothing to commit, working directory clean
> ```

not just on ide, try this you will see:
```
git status
mvn clean test-compile exec:java -DskipTests -Dexec.mainClass=com.puppycrawl.tools.checkstyle.Main  -Dexec.classpathScope=test -Dexec.args="--help"
git status 
```
jacoco-maven-plugin:0.8.5:instrument default enable is the cause of the issue.
if we disable jacoco-maven-plugin (`-Djacoco.skip`) will slove the problem.

with `-DskipTests ` jacoco should  be skipped, ref: #8788

**Comment by romani** [comment]
Please reproduce this without `exec:java`

**Comment by romani** [comment]
please create issue on this and lets discuss problem in issue first.
I am closing PR.

**Pull request closed without merging**
