### PR TITLE
Issue #13097: Split regexp xdocs into separate pages

### PR DESCRIPTION
**Pull request by stoyanK7**
Part of #13097

### CODE REVIEW

**Comment by stoyanK7** [comment]
Github, generate site

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by nrmancuso** [comment]
@stoyanK7 please resolve conflicts

**Comment by stoyanK7** [comment]
Table descriptions are OK.

**Comment by nrmancuso** [comment]
Looks like failure in semaphore is concurrency/credits issue, not related to changes in this PR.

**Pull request merged**
