### PR TITLE
Issue #1566: ModifiedControlVariable violations fixed

### PR DESCRIPTION
**Pull request by rdiachenko**
Violations fixed:
- ModifiedControlVariable Control variable 'X' is modified.

### CODE REVIEW

**Comment by romani** [comment]
each time you propose update, please explain why it was missed from "mvn clean verify", if that Check is not used in our config - please add it. All violations that you fixing should be enforced right-away for any further commits.

**Comment by rdiachenko** [comment]
@romani 
>> Can we remove "i++" and do that ourself in FOR body?

No

>> FOR is used to hide "i" in its scope, moving it out scope is not good - we fix one issue and create another.

Which issue will it create? Please provide real examples.

Personally for me ```while``` loop is more readable here:

```
for (int reindex = i + 1; reindex < lines.length;) {
    reindex++;
}

int reindex = i + 1;
while (reindex < lines.length) {
    reindex++;
}
```

Here's another example:
```
for (Iterator<Integer> iter = list.iterator(); iter.hasNext();) {
    int a = iter.next();
}

Iterator<Integer> iter = list.iterator();
while (iter.hasNext()) {
    int a = iter.next();
}
```

**Comment by rdiachenko** [comment]
@romani 
>>  if that Check is not used in our config - please add it

```ModifiedControlVariable``` check added to our configuration.

**Comment by romani** [comment]
>```
for (Iterator<Integer> iter = list.iterator(); iter.hasNext();) {
    int a = iter.next();
}

Iterator<Integer> iter = list.iterator();
while (iter.hasNext()) {
    int a = iter.next();
}
```

What is a reason of "iter" to be visible for code outside of WHILE ?

**Comment by rdiachenko** [comment]
Reminder for me: check http://checkstyle.sourceforge.net/config_coding.html#ModifiedControlVariable. It should skip cases like this:
```
for (int i = 0; i < 10;) {
     i++;
}
```

If it doesn't work open a bug for this case.

**Comment by rdiachenko** [comment]
The aforementioned case check passed successfully, so there is not reason for a new bug, code was refactored.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
