### PR TITLE
Issue #1438: Fix handling finally in FallThroughCheck

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by romani** [comment]
code is ok.

1) please move formatting changes to separate commit.

2) please generate diff-report by ahsm tool.

**Comment by Vladlis** [comment]
1) fixed
2) http://vladlis.github.io/reports/fallthrough/
there is no differences on openjdk7, guava, CS, sevntu-CS, spring-framework, hibernate-orm, HBase, pmd, lombok-ast, elasticsearch, java-design-patterns, MaterialDesignLibrary, Orekit

**Comment by mkordas** [comment]
+1 from me, thanks @Vladlis

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
