### PR TITLE
Issue #7120: Add localization for javadoc.write.tag

### PR DESCRIPTION
**Pull request by pbludov**
Issue #7120

Fix violation of IntelliJ IDEA inspection `InconsistentResourceBundle`

### CODE REVIEW

**Comment by rnveach** [comment]
@pbludov CI failed.
> CheckstyleAntTaskTest

**Comment by romani** [comment]
Travis was restarted

**Comment by pbludov** [comment]
> If CI pass, ok to merge

Something wrong with this test:
image

JP and PT locales should fail as all other. I'm researching this.

**Comment by pbludov** [comment]
Instead of `jp-JP` we need `ja-JP` for Japanese in `travis.sh`.

`pt_PT` is correct, I just forgot to add translation for it.

**Comment by pbludov** [comment]
This issue is blocked by #7129

**Comment by romani** [comment]
Please rebase

**Comment by pbludov** [comment]
> Please rebase

Rebased and fixed.

**Pull request merged**
