### PR TITLE
Issue #5104: created internal utils package for test utils

### PR DESCRIPTION
**Pull request by rnveach**
Issue #5104 

This is to separate tests and internal tests from utils/classes that support tests.
Custom test modules will be a separate package.

### CODE REVIEW

**Comment by rnveach** [comment]
> 214: testBlockCommentPositionHasPrivateConstr() JUnit test method testBlockCommentPositionHasPrivateConstr() contains no assertions 

This is a buggy check that doesn't seem until something unrelated changes...

@romani Should I make new PR to change `assertUtilsClassHasPrivateConstructor` to return boolean so we can make assertion on it?

**Comment by romani** [comment]
>  to return boolean so we can make assertion on it everywhere it is used?

yes, keeping all `assert` in certain UT method area is always better, if code does not become over messy.

**Comment by rnveach** [comment]
@romani  I rebased but got different errors now.
> CloseAndFlushTestByteArrayOutputStream Class CloseAndFlushTestByteArrayOutputStream has only dependencies on and/or dependents in package 'com.puppycrawl.tools.checkstyle' 

I assume I should just suppress these?

**Comment by rnveach** [comment]
@romani ping
Since you never responded, I made the suppressions. Please review.

**Comment by romani** [comment]
please rebase to resolve conflict and merge this PR.
I am ok with change.

**Comment by rnveach** [comment]
Rebased, can be merged when CI passes.

**Comment by rnveach** [comment]
Merged.

**Pull request merged**
