### PR TITLE
Issue #2451: removed excess hierarchy from LocalFinalVariableNameCheck

### PR DESCRIPTION
**Pull request by rnveach**
LocalFinalVariableNameCheck now extends Check.
Copied fields, methods, and a javadoc from AbstractNameCheck.

**Comments**
I think out of all our abstract checks so far, this might be the perfect one to keep.
It only exposes "format". When will we need this to be hidden?
It only has one purpose, to validate the name, which is the only field we expose.

Classes affected by removing AbstractNameCheck:
AbstractAccessControlNameCheck, AbstractTypeParameterNameCheck
ConstantNameCheck, MemberNameCheck, MethodNameCheck, StaticVariableNameCheck, TypeNameCheck, LocalVariableNameCheck, ParameterNameCheck, ClassTypeParameterNameCheck, InterfaceTypeParameterNameCheck, MethodTypeParameterNameCheck.

### CODE REVIEW

**Comment by romani** [comment]
please let me think about deprecation of AbstractNameCheck, too much Checks using it.

**Comment by romani** [comment]
merged as FF.

lets keep AbstractNameCheck, it is ok to keep, it does not introduce any property nonrequired property to other class.

**Comment by rnveach** [comment]
@romani 
When you say keep it, you mean not to deprecate it in the end, but continue to remove its hierarchy from other classes? I assume thats what you mean since your merged this.
If we do continue to remove its hierarchy, it will need its own test class to maintain coverage.

**Comment by romani** [comment]
Do not deprecate, keep code hierarchy as is.

**Pull request closed without merging**
