### PR TITLE
Issue #15067: IllegalTypeCheck should not violate types that declared…

### LINKED ISSUE #15067: Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: IllegalType
child of #14942 : 

check doc : https://checkstyle.org/checks/coding/illegaltype.html

---

```
PS D:\CS\test> cat config.xml                                                   
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="IllegalType">
        </module>
    </module>
</module>
PS D:\CS\test> cat src/Test.java                                                
import java.util.LinkedHashMap;
import java.util.List;

record ColoredPoint(String p, String x, int c) { }
record Rectangle(ColoredPoint upperLeft, ColoredPoint lowerRight) { }

public class Test {
    void test(Object obj) {
        LinkedHashMap _ = new LinkedHashMap<>();     // violation
        if (obj instanceof LinkedHashMap<?,?> _) { }          // violation
    }
}

PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml src/Test.java
Starting audit...
[ERROR] D:\CS\test\src\Test.java:9:9: Usage of type 'LinkedHashMap' is not allowed. [IllegalType]
[ERROR] D:\CS\test\src\Test.java:10:28: Usage of type 'LinkedHashMap' is not allowed. [IllegalType]
Audit done.
Checkstyle ends with 2 errors.
PS D:\CS\test> 

```

IllegalType Check works as intended when unnamed.

### PR DESCRIPTION
**Pull request by mahfouz72**
closes #15067:  

Diff Regression config: https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/e18d938044e609684b3300dfbf9ce8ef374f4f1d/check.xml

Diff Regression projects: https://gist.githubusercontent.com/mahfouz72/a3d0af030c8f5efd0d8a39f2c14750bc/raw/a3424ad9b6f722e5de1a927e3d85e383101b2b93/projects-to-test-on.properties

### CODE REVIEW

**Comment by mahfouz72** [comment]
github, generate report

**Comment by mahfouz72** [comment]
github, generate report

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Please extend documentation as requested at https://github.com/checkstyle/checkstyle/issues/15067#issuecomment-2181723270

**Comment by mahfouz72** [comment]
github, generate site

**Comment by nrmancuso** [comment]
This PR is blocked by https://github.com/checkstyle/checkstyle/issues/15067#issuecomment-2204018255, I suggest that we close it and come back to it after we clearly define this check's purpose.

**Pull request closed without merging**
