### PR TITLE
minor: Update README.md to remove matrix

### PR DESCRIPTION
**Pull request by romani**
To test regression report workflow 

Report label: RedundantModifier/all-examples-in-one
Diff Regression config: https://raw.githubusercontent.com/checkstyle/test-configs/main/RedundantModifier/all-examples-in-one/config.xml
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/test-configs/main/RedundantModifier/all-examples-in-one/list-of-projects.properties

### CODE REVIEW

**Comment by romani** [comment]
Github, generate report for RegexpHeader/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by relentless-pursuit** [comment]
> Github, generate report for configs in PR description

Is this designed to fail?

**Comment by relentless-pursuit** [comment]
The error i see is different. 
```
Error: git repository /home/runner/work/checkstyle/checkstyle/.ci-temp/checkstyle does not have a branch with name 'forked/romani-patch-2'!
Error: forked/romani-patch-2 is not an exiting git branch!
```

**Comment by romani** [comment]
this issue is postponed until https://github.com/checkstyle/test-configs/issues/168

**Comment by romani** [comment]
second issue is https://github.com/checkstyle/checkstyle/issues/15579

**Comment by romani** [comment]
this PR will be used to do final test of https://github.com/checkstyle/checkstyle/issues/15579

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
Github, generate report for RecordComponentName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RecordComponentName/all-examples-in-one

**Pull request closed without merging**
