### PR TITLE
Issue #3015: NPE in CheckUtil#getCheckMessage

### PR DESCRIPTION
**Pull request by Vladlis**
#3015

### CODE REVIEW

**Comment by romani** [comment]
@MEZk , please review fix of @Vladlis .

1) I do not  like this approach to search for property file in different packages. We do know where it is located - https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/messages.properties

Problem was in `getCheckMessage(..)` method. But required message does no belong to Check, such message is common for all - it does not belong to Check.

All that is required is required to do is to create special method getExceptionMessage(...), and load all key from exact/hardcoded location.

2)
> // do nothing

just make a rule for yourself - never write such a text. Each exceptions swallowing should be widely described with all reasons. The best rule - never swallow exceptions.

3)
> private static String getProperty

why javadoc is missed and checkstyle does not bother you ? please investigate.

**Comment by Vladlis** [comment]
1) 
> create special method getExceptionMessage(...) 

Why do we need this method then? Where will we use it?

**Comment by romani** [comment]
> Why do we need this method? Where will we use it?

I presume it should be used in Check. changing only Util method does not make any sense. 
As problem was reproduced in Check, Check should be changed too. @MEZk , please remind us a root of the problem and how you reproduced it Check and what was your intend.

**Comment by MEZk** [comment]
@romani
Point 5:
https://github.com/checkstyle/checkstyle/pull/2967#issuecomment-193019900

When I extracted String literal to the constanct "MSG_*", then ```testAllCheckstyleMessages``` failed the build due to NPE in 'CheckUtil#getCheckMessage'. Thus,  if we use violation messages from resource bundle which is not in the same package as the target class, 'getResourceAsStream' does not load the bundle's content (it loads only the content of resource bundle associated with the current class loader).

> Example: there are two property keys ('general.fileNotFound' and 'general.exception') which are used in Tranlation#logIoException. The message resources for the keys are inside src/main/resources/com/puppycrawl/tools/checkstyle/messages.properties resource bundle. In the current implementation of TranslationCheck we use the keys as string literals, because we cannot extract them to the constants due to NPE in CheckUtil#getCheckMessage and failing of 'testAllCheckstyleMessages' as a result.

**Comment by Vladlis** [comment]
@romani
So if we actually shouldn't show these messages to user (https://github.com/checkstyle/checkstyle/issues/3015#issuecomment-199806123) then we might not need the proposed method `getExceptionMessage(...) `

**Comment by MEZk** [comment]
@romani 
I agree that we should not show the exception messages to users (as violations). The messages should be deleted from xdocs.

**Comment by romani** [comment]
@Vladlis ,

your last update is not correct. 
Here is a tiny nuance:
`MSG_JAVADOC_MISSED_HTML_CLOSE = "javadoc.missed.html.close"; ` and similar values are actually part of validation and smth that user need to be aware and have ability to override/change.
While we working with java code we rely of javac to make to correct before our parsing. But nothing can "compile" javadoc, but as we work base on grammar parser we notice HTML structure problems and we report them as exception(can not proceed parsing) to force user to fix them first. But it is not checkstyle problem it is user code problem.

**Comment by romani** [comment]
I am closing issue as "Won't fix", see reason in previous post.

that is even good that method in test code throw exception on attempt to use exception messages in with "MSG_" prefix

**Pull request closed without merging**
