### PR TITLE
minor: add a test case in RightCurlyCheckTest

### PR DESCRIPTION
**Pull request by yuchesu**
Adding a new test case to RightCurlyCheckTest to test the SAME policy in right curly option. Thanks for your review and consideration.

### CODE REVIEW

**Comment by rnveach** [comment]
@yuchesu Please keep the number of commits to 1 in this PR and look over your changes and the CI failure. Your changes should just be adding the 1 test case as you said, and should be void of any of the indentation and superfluous changes.

Also, where is adding this test case coming from? Was it discussed in another issue/PR?

**Comment by rnveach** [comment]
@yuchesu ping

**Comment by romani** [comment]
Why you think we need extra test, please explain how you found a gap.

**Comment by nick-mancuso** [comment]
We have lost contact with author of PR, and we have no ticket on this.

**Pull request closed without merging**
