### PR TITLE
Issue #6175: bump picocli to 3.8.0

### PR DESCRIPTION
**Pull request by romani**
#6175

```
$ java -jar checkstyle-8.15-SNAPSHOT-all.jar --help
Usage: checkstyle [-dghjJtTV] [--executeIgnoredModules] [--tabWidth=<tabWidth>]
                  [-c=<configurationFile>] [-C=<checkerThreadsNumber>] [-f=<format>]
                  [-o=<outputPath>] [-p=<propertiesFile>] [-s=<suppressionLineColumnNumber>]
                  [-W=<treeWalkerThreadsNumber>] [-e=<exclude>]... [-x=<excludeRegex>]... <files>...
Checkstyle verifies that the specified source code files adhere to the specified rules. By default
errors are reported to standard out in plain format. Checkstyle requires a configuration XML file
that configures the checks to apply.
      <files>...            One or more source files to verify
      --executeIgnoredModules
                            Allows ignored modules to be run.
      --tabWidth=<tabWidth> Sets the length of the tab character. Used only with "-s" option. Default
                              value is 8
  -c=<configurationFile>    Sets the check configuration file to use.
  -C, --checker-threads-number=<checkerThreadsNumber>
                            (experimental) The number of Checker threads (must be greater than zero)
  -d, --debug               Print all debug logging of CheckStyle utility
  -e, --exclude=<exclude>   Directory path to exclude from CheckStyle
  -f=<format>               Sets the output format. Valid values: xml, plain. Defaults to plain
  -g, --generate-xpath-suppression
                            Generates to output a suppression.xml to use to suppress all violations from
                              user's config
  -h, --help                Show this help message and exit.
  -j, --javadocTree         Print Parse tree of the Javadoc comment
  -J, --treeWithJavadoc     Print full Abstract Syntax Tree of the file
  -o=<outputPath>           Sets the output file. Defaults to stdout
  -p=<propertiesFile>       Loads the properties file
  -s=<suppressionLineColumnNumber>
                            Print xpath suppressions at the file's line and column position. Argument is
                              the line and column number (separated by a : ) in the file that the
                              suppression should be generated for
  -t, --tree                Print Abstract Syntax Tree(AST) of the file
  -T, --treeWithComments    Print Abstract Syntax Tree(AST) of the file including comments
  -V, --version             Print version information and exit.
  -W, --tree-walker-threads-number=<treeWalkerThreadsNumber>
                            (experimental) The number of TreeWalker threads (must be greater than zero)
  -x, --exclude-regexp=<excludeRegex>
                            Regular expression of directory to exclude from CheckStyle
```

### CODE REVIEW

**Comment by romani** [comment]
and now it is kind of unclear why we have here a bit different documentation content - https://checkstyle.org/cmdline.html#Command_line_usage

**Comment by rnveach** [comment]
CLI:
````
  -s=<suppressionLineColumnNumber>
                            Print xpath suppressions at the file's line and column position. Argument is
                              the line and column number (separated by a : ) in the file that the
                              suppression should be generated for
````
Documentation:
````
          <code>-s line:column</code> - print xpath suppressions at the file's line and column
          position. Line and column numbers are integer values separated by a <code>:</code>,
          specify
          location in the file the suppression should be generated for. The option cannot be used
          with other options and requires exactly one file to run on to be specified.
          ATTENTION: generated result will have few queries, joined by pipe(<code>|</code>).
          Together they will match all AST nodes on specified line
          and column. You need to choose only one and recheck that it works. Usage of all of them is
also ok, but might result in undesirable matching and suppress other issues.
````

`suppressionLineColumnNumber` versus `line:column` looks like it might just be we wanted the xdoc to be a bit more friendlier. Old CLI just said `<arg>` but that was probably because we couldn't control it's actual text? Can picocli support custom text for that arg?

Difference in descriptions is just xdoc is more fleshed out. I think we wanted to make sure people knew of its limitations/issues and didn't want to overburden CLI display with same information. Even though wording is slightly different between the 2, the first paragraph still convey the same information.

**Comment by rnveach** [comment]
There are other issues with xdoc versus cli, like xdoc doesn't mention our `-e` option. We probably need a UT to ensure they are in synch.

**Comment by romani** [comment]
discussion is moved to https://github.com/checkstyle/checkstyle/issues/6216

**Comment by romani** [comment]
commits were squashed and merged manually

**Pull request closed without merging**
