### PR TITLE
Issue #3574: moved DetailAST log to AbstractCheck

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3574

### CODE REVIEW

**Comment by rnveach** [comment]
Uncertain what wercker failure is in regards to:
> [WARNING] The POM for com.github.hazendaz.spotbugs:spotbugs-maven-plugin:jar:3.0.5 is missing, no dependency information available

**Comment by rnveach** [comment]
CI failure is old commit message problem that was later fixed in master

**Comment by romani** [comment]
please rebase on latest master. 
after each release it is mandatory to rebase to avoid CIs failures.

**Comment by rnveach** [comment]
Done.

**Pull request merged**
