### PR TITLE
Remove dependency to commons lang3 library

### PR DESCRIPTION
**Pull request by chrismacias**
issue #2428, updated CommonUtils to include methods and properties from lang3

### CODE REVIEW

**Comment by romani** [comment]
We should not copy code from commons-lang3 except for empty arrays. 

it is completely ok to move commons-lang3  from main dependency to test dependency:
```
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.4</version>
      <scope>test</scope>
    </dependency>
```

If for some reason we are depended to other methods, please let me know. We need to find analogue in guava. If we can not find analogue most likely we will stay with  commons-lang3 . But I need see such cases before final decision.

**Comment by chrismacias** [comment]
Those are the necessary methods that i pulled from lang3 in main checkstyle project and not in tests, i also removed constants that where used only on tests. Should i look for the respective methods in guava?

**Comment by romani** [comment]
we need to find alternatives.

Please make a list of methods we need to copy form library and in what file it is used - I will help you to find alternative or make a decision on copy of code.

**Comment by mkordas** [comment]
@romani 
My idea is to create class `EmptyArrays` and store empty arrays there. This would prevent adding even more stuff to already overloaded (and not object oriented :wink:) utils

**Comment by romani** [comment]
Yes, good idea.

**Comment by chrismacias** [comment]
what about the methods? these are referenced from lang3:
```java
    public static int[] clone(final int... array) {
        if (array == null) {
            return array;
        }
        return array.clone();
    }

    public static int[] toPrimitive(final Integer... array) {
        final int[] result;

        if (array.length == 0) {
            return new int[0];
        }
        else {
            result = new int[array.length];
            System.arraycopy(result, 0, array, 0, 1);
        }
        return result;
    }

    public static String join(final Iterator<?> iterator, final String separator) {
        String bufferString;

        if (iterator.hasNext()) {
            final Object first = iterator.next();
            if (!iterator.hasNext()) {
                return toString(first);
            }

            // two or more elements
            final StringBuilder buf = new StringBuilder(256);
            if (first != null) {
                buf.append(first);
            }

            while (iterator.hasNext()) {
                if (separator != null) {
                    buf.append(separator);
                }
                final Object obj = iterator.next();
                if (obj != null) {
                    buf.append(obj);
                }
            }
            bufferString = buf.toString();
        }
        else {
            bufferString = EMPTY;
        }
        return bufferString;
    }

    public static String join(final Iterable<?> iterable, final String separator) {
        if (iterable == null) {
            return null;
        }
        return join(iterable.iterator(), separator);
    }

    public static boolean isNotBlank(final CharSequence cs) {
        return !isBlank(cs);
    }
    public static boolean isBlank(final CharSequence cs) {
        boolean isBlank = true;
        if (cs == null) {
            return isBlank;
        }
        final int strLen = cs.length();
        if (strLen != 0) {
            for (int i = 0; i < strLen; i++) {
                if (!Character.isWhitespace(cs.charAt(i))) {
                    isBlank = false;
                }
            }
        }
        return isBlank;
    }

    public static String toString(final Object obj) {
        if (obj == null) {
            return "";
        }
        else {
            return obj.toString();
        }
    }
```

**Comment by mkordas** [comment]
Joins can be replaced by Guava's Joiner and the rest can be just inlined.

**Comment by chrismacias** [comment]
there are some other functions in Guava that can replace those methods, ill do some research

**Comment by romani** [comment]
@chrismacias , do you plan to continue ? do you need help ?

**Comment by romani** [comment]
@chrismacias , if you do not have time to finish this issue , I recommend to drop this PR and unlock issue to be resolved by other contributor.

**Comment by romani** [comment]
if no action happen till end of month , I will close this PR and issue will become unassigned to let others try to fix it.

**Pull request closed without merging**
