### PR TITLE
Issue #9217: Sonar Dashboard link doesn't work

### PR DESCRIPTION
**Pull request by AkMo3**
Closes: #9217 

$cat log pom.xml 
```
<plugin>
      <groupId>nl.demon.shadowland.maven.plugins</groupId>
      <artifactId>sonarqube-maven-report</artifactId>
      <version>0.2.2</version>
</plugin>
```
Before change URL - `https://sonarcloud.io/project/index/com.puppycrawl.tools:checkstyle`
Current URL - `https://sonarcloud.io/dashboard?id=com.puppycrawl.tools%3Acheckstyle`
Desired URL - `https://sonarcloud.io/dashboard?id=org.checkstyle%3Acheckstyle`   

I am not able to change `com.puppycrawl.tools` with `org.checkstyle`. Kindly comment on how to solve this.

### CODE REVIEW

**Comment by romani** [comment]
@AkMo3 , please share  link to documentation of this plugin to prove that update for all this tags are required.

**Comment by AkMo3** [comment]
Yup, the project and branch need to be changed. I am not very familiar with maven so it will take some time. I am trying to implement something like [sonar-maven-report](https://gitlab.com/freedumbytes/sonar-maven-report) now.

**Comment by AkMo3** [comment]
@romani Sir, I the previous code was outdated. I had updated it but I am not able to change the `com.puppycrawl.tools`. The link to documentation and repository is https://github.com/SonarQubeCommunity/sonar-maven-report.

**Comment by strkkk** [comment]
Github, generate site

**Comment by AkMo3** [comment]
Github, generate site

**Comment by AkMo3** [comment]
> If I do the following change at Line 13 of pom.xml,the desired link is generated.
> `<groupId>com.puppycrawl.tools</groupId>` -> `<groupId>org.checkstyle</groupId>`

I had made this change, and site generation is all right. But not sure if this change is appropriate.

**Comment by strkkk** [comment]
> But not sure if this change is appropriate, as main groupId is changed.

This is not appropriate, I guess it will change existing maven repository location.

**Comment by AkMo3** [comment]
> 
> 
> > But not sure if this change is appropriate, as main groupId is changed.
> 
> This is not appropriate, I guess it will change existing maven repository location.

I agree

> Is there a way to just override group id for plugin?

I feel groupId is something that cannot be overridden, even with combine.self = "override"

**Comment by AkMo3** [comment]
GitHub, generate site

**Comment by AkMo3** [comment]
Github, generate site

**Comment by AkMo3** [comment]
@strkkk I had replaced the earlier plugin with my own plugin that is hosted in maven central. Please have a look at it.

**Comment by AkMo3** [comment]
GitHub, generate webiste

**Comment by AkMo3** [comment]
Github, generate site

**Review by strkkk — APPROVED** [review]

**Comment by strkkk** [comment]
I am ok with this plugin, it fixes the problem.

@AkMo3 where can we find the source code of this plugin? May be it makes sense to host this in contribution repo?

**Comment by AkMo3** [comment]
@strkkk The source code is available at [SonarCloudUrl-maven-plugin](https://github.com/AkMo3/SonarCloudUrl-maven-plugin/) and is hosted on Sonatype OSSRH and maven central link is [SonarCloudUrl-maven-plugin/1.0.1](https://search.maven.org/artifact/com.github.akmo03/SonarCloudUrl-maven-plugin/1.0.1/maven-plugin). 

I was hoping to develop this plugin for some time to add functionality that were missing in earlier plugin. Maybe we could add after that to the contribution repository.

**Review by romani — CHANGES_REQUESTED** [review]
unfortunately we need simply remove this plugin completely from our pom.xml

We should keep in this page https://checkstyle.org/project-reports.html only reports that generate our build process and DOES not have special webservice to render content.

Sonar is special webservice and we have link/badge to it in README.md file.
We will never catch up with Sonarqube  changes for URLs. Even they(`org.codehaus.sonar-plugins`) abandoned this plugin.

Sorry for being late to provide such thoughts on how to fix it.

**Comment by AkMo3** [comment]
GitHub, rebase

**Comment by AkMo3** [comment]
GitHub, rebase

**Comment by AkMo3** [comment]
> 
> 
> unfortunately we need simply remove this plugin completely from our pom.xml
> 
> We should keep in this page https://checkstyle.org/project-reports.html only reports that generate our build process and DOES not have special webservice to render content.
> 
> Sonar is special webservice and we have link/badge to it in README.md file.
> We will never catch up with Sonarqube changes for URLs. Even they(`org.codehaus.sonar-plugins`) abandoned this plugin.
> 
> Sorry for being late to provide such thoughts on how to fix it.

No, issues. At least I got to learn Maven because of this. 
I have removed that plugin completely. But, why is this wrecker failing? 
Also please suggest some issues that I can solve since the last issue you gave to solve was amazing to solve.

**Comment by strkkk** [comment]
Github, generate site

**Comment by strkkk** [comment]
> But, why is this wrecker failing?
I restarted it, it looked like random failure

**Comment by AkMo3** [comment]
@strkkk Thanks. I was going through the issues, and the #9240 is something that would take no time, and is a bit relatable to this PR also. Should I solve it. It would take no time.

**Comment by strkkk** [comment]
@AkMo3 you can try https://github.com/checkstyle/checkstyle/issues/6893, it can be more challenging.
I cannot suggest good antlr issue, they all seem difficult to me

**Comment by AkMo3** [comment]
> I was going through the issues, and the #9240 is something that would take no time, and is a bit relatable to this > PR also. Should I solve it?
@strkkk  Also, please comment on this. And would look the issue you suggested, thanks a lot.

**Comment by strkkk** [comment]
@AkMo3 yes, feel free to take any approved issue

**Comment by AkMo3** [comment]
Can I solve it in this PR only?

**Comment by strkkk** [comment]
I think it is better to do not mix fixes.

**Comment by AkMo3** [comment]
All done in #9241. Made a new PR. Alse, I think both wrecker and semaphoreci is broken.

**Review by romani — APPROVED** [review]

**Pull request merged**
