### PR TITLE
Issue #9142: Migrate to Truth in BeforeExecutionFileFilterSetTest

### PR DESCRIPTION
**Pull request by shashwatj07**
Issue #9142

### CODE REVIEW

**Review by pbludov — APPROVED** [review]

**Review by timurt — APPROVED** [review]

**Comment by timurt** [comment]
@shashwatj07 rebase on the latest master to trigger semaphore CI

**Comment by shashwatj07** [comment]
> @shashwatj07 rebase on the latest master to trigger semaphore CI

@timurt done

**Comment by timurt** [comment]
@shashwatj07 resolve conflict `config/suppressions.xml`

**Comment by shashwatj07** [comment]
> @shashwatj07 resolve conflict `config/suppressions.xml`

done

**Pull request merged**
