### PR TITLE
Fix AbstractClassName Check on checkstyle code #945

### PR DESCRIPTION
**Pull request by Bhavik3**

### CODE REVIEW

**Comment by romani** [comment]
@Bhavik3 ,

I did not found any explanation why Factory named classes has to abstract. I do not see any reason to force user to name classes like that by default. I never used that Check for Factory classes. I reviewed Spring sources, nobody force Factory as abstract.

TODO:
1) please update default value of Check property to ```<property name="format" value="^Abstract.*$"/>``` 
2) remove your suppressions where Factory is referenced. All other suppression are correct.

**Comment by romani** [comment]
@Bhavik3 , please continue.

**Comment by Bhavik3** [comment]
@romani 

2)
Done

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
