### PR TITLE
infra: reactivate no-error-checkstyles-sevntu after sevntu#858

### PR DESCRIPTION
**Pull request by nmancus1**
Reactivates `no-error-checkstyles-sevntu` CI task now that https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/858 is merged

### CODE REVIEW

**Comment by nmancus1** [comment]
Travis has not run on this PR with last three pushes.
https://github.com/checkstyle/checkstyle/commit/c8229e19b4036eeeebe70a72255ba3c8f748fb44
https://github.com/checkstyle/checkstyle/commit/50f8d02acc8ccdd3bee026dacb53a1f0c03d86b6
https://github.com/checkstyle/checkstyle/commit/50f8d02acc8ccdd3bee026dacb53a1f0c03d86b6

**Comment by nmancus1** [comment]
GitHub, rebase

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
Config problem
https://app.travis-ci.com/github/checkstyle/checkstyle/requests

**Comment by nmancus1** [comment]
Travis build is running (and passing) now: https://github.com/checkstyle/checkstyle/pull/11218/checks?check_run_id=4863040178

**Pull request merged**
