### PR TITLE
Issue #12974: updated the Fallthroughcheck docs

### PR DESCRIPTION
**Pull request by ashutoshdubey133**
Issue: #12974 

I have modified the examples to be uniform in all the scenarios.

### CODE REVIEW

**Comment by romani** [comment]
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=14355&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=910

There is problem that javadoc and file in xdoc folder are not in sync, please debug this test to see a difference.

**Comment by ashutoshdubey133** [comment]
@romani I have corrected the problem, now the javadoc and file are in sync. The spelling check fails but the "FalThrough" and similar are intentional to show that these words will match with the given regular expression.
Also, there is an issue on while(i>=0) which says, wrong usage of ">". But this is same from the examples used previously.

**Comment by romani** [comment]
lets not show users bad spelling, lets show what user should do in right way, all hacks they can figureout themself.

**Comment by romani** [comment]
@ashutoshdubey133 , please finish PR.

**Comment by rnveach** [comment]
Assigned issue is closed. Needs to be rebased. CI needs to be green.

**Comment by romani** [comment]
We did update in other PR

**Pull request closed without merging**
