### PR TITLE
Issue #11140: resolve OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL

### PR DESCRIPTION
**Pull request by rnveach**
Issue #11140

No violations locally.

### CODE REVIEW

**Comment by rnveach** [comment]
````
[ERROR] Low: Method com.puppycrawl.tools.checkstyle.JavaAstVisitor.visitArguments(JavaLanguageParser$ArgumentsContext) uses Optional.orElseGet(null) [com.puppycrawl.tools.checkstyle.JavaAstVisitor] At JavaAstVisitor.java:[line 1922] OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL

[ERROR] Low: Method com.puppycrawl.tools.checkstyle.JavaAstVisitor.visitFormalLambdaParam(JavaLanguageParser$FormalLambdaParamContext) uses Optional.orElseGet(null) [com.puppycrawl.tools.checkstyle.JavaAstVisitor] At JavaAstVisitor.java:[line 1630] OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL

[ERROR] Low: Method com.puppycrawl.tools.checkstyle.JavaAstVisitor.visitInvOp(JavaLanguageParser$InvOpContext) uses Optional.orElseGet(null) [com.puppycrawl.tools.checkstyle.JavaAstVisitor] At JavaAstVisitor.java:[line 1445] OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL

[ERROR] Low: Method com.puppycrawl.tools.checkstyle.JavaAstVisitor.visitMethodCall(JavaLanguageParser$MethodCallContext) uses Optional.orElseGet(null) [com.puppycrawl.tools.checkstyle.JavaAstVisitor] At JavaAstVisitor.java:[line 1588] OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL

[ERROR] Low: Method com.puppycrawl.tools.checkstyle.JavaAstVisitor.visitSimpleMethodCall(JavaLanguageParser$SimpleMethodCallContext) uses Optional.orElseGet(null) [com.puppycrawl.tools.checkstyle.JavaAstVisitor] At JavaAstVisitor.java:[line 1471] OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL

[ERROR] Low: Method com.puppycrawl.tools.checkstyle.JavaAstVisitor.visitSuperSuffixDot(JavaLanguageParser$SuperSuffixDotContext) uses Optional.orElseGet(null) [com.puppycrawl.tools.checkstyle.JavaAstVisitor] At JavaAstVisitor.java:[line 1907] OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL

[ERROR] Low: Method com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck.getFirstCaseGroupOrSwitchRule(DetailAST) uses Optional.orElseGet(null) [com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck] At VariableDeclarationUsageDistanceCheck.java:[line 868] OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL

[ERROR] Low: Method com.puppycrawl.tools.checkstyle.utils.ScopeUtil.getScope(DetailAST) uses Optional.orElseGet(null) [com.puppycrawl.tools.checkstyle.utils.ScopeUtil] At ScopeUtil.java:[line 71] OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL

[ERROR] Low: Method com.puppycrawl.tools.checkstyle.utils.ScopeUtil.getScopeFromMods(DetailAST) uses Optional.orElseGet(null) [com.puppycrawl.tools.checkstyle.utils.ScopeUtil] At ScopeUtil.java:[line 84] OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL
````

**Comment by rnveach** [comment]
@pbludov This looks to be another false positives. There are no `orElseGet(null)` in the class. It is just printing violations on `orElseGet`.
https://github.com/checkstyle/checkstyle/blob/5f1f940f78f4c208055657a2061b4a358c8ccae2/src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java

**Comment by pbludov** [comment]
I can't reproduce it on my PC either. It looks like this is platform dependent. We need to add `--show-version` option to all mvn commands to figure it out. No relevant issues were found in the fb-contrib repository.

**Comment by rnveach** [comment]
Added `--show-version` temporarily.

**Comment by rnveach** [comment]
@pbludov 
````
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/share/maven
Java version: 1.8.0_282, vendor: AdoptOpenJDK, runtime: /opt/java/openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-20-generic", arch: "amd64", family: "unix"
````

**Comment by romani** [comment]
If false positive, let's report tiket to them and move forward with permanent suppression until ticket.

**Comment by pbludov** [comment]
Can't reproduce with **adoptopenjdk-8-hotspot**
```
Apache Maven 3.6.3
Java version: 1.8.0_292, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre
Default locale: en_US, platform encoding: UTF-8
```
nor **adoptopenjdk-8-openj9**
```
Apache Maven 3.8.3
Java version: 1.8.0_292, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/adoptopenjdk-8-openj9-amd64/jre
Default locale: en_US, platform encoding: UTF-8
```

Not enough details to open an issue for fb-contrib.

**Comment by romani** [comment]
It is cli problem https://cloud.drone.io/checkstyle/checkstyle/8140/1/4, @rnveach please fix it.

**Comment by rnveach** [comment]
@romani Drone failure was just to help @pbludov with reproducing. It was failing originally with the violations I showed above.

@pbludov Do you just need the `.class` file to reproduce with. Maybe you could have the CI print out the hex for you to create it locally.

**Comment by rnveach** [comment]
Pushed suppression.

**Review by romani — APPROVED** [review]

**Review by pbludov — APPROVED** [review]

**Pull request merged**
