### PR TITLE
Issue #3721: expanded message and documentation AbbreviationAsWordInName

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3721

### CODE REVIEW

**Comment by rnveach** [comment]
Shippable failure is a timeout.

**Comment by rnveach** [comment]
> > I will suppress JTreeTable as this is a Java convention for javax.swing

> That is not our convention. Nothing force us to keep name that similar to java standard. Lets avoid illusions.
Lets avoid suppressions, rename it to what ever is more reasonable.

Done.

**Comment by romani** [comment]
> /api/FileContents.java 

we can not change API now, please make new methods with correct names to use in our code.
old api methods should call new methods.
old api methods should be marked as deprecated, they will be removed in checkstyle8.

**Comment by rnveach** [comment]
> old api methods should call new methods.
old api methods should be marked as deprecated, they will be removed in checkstyle8.

Done.
Had to make 1 new test to get code coverage in FileContents.

**Pull request merged**
