### PR TITLE
Issue #4400: increase coverage of pitest-checkstyle-common profile to 92%

### PR DESCRIPTION
**Pull request by Nimfadora**
Issue #4400 

[pitest report before changes](https://nimfadora.github.io/issue4400.html)

increased mutation threshold for pitest-checkstyle-common profile by 2%
current threshold: 92%
execution time: 13:02 min

### CODE REVIEW

**Comment by Nimfadora** [comment]
@romani what should I do with imports (`CheckerTest Class 'CheckerTest' has too many dependencies (31 > 30)` in TC)? Suppress or fix somehow?

**Comment by romani** [comment]
> what should I do with imports (CheckerTest Class 'CheckerTest' has too many dependencies (31 > 30) in TC)? Suppress or fix somehow?

I increased the limit:
https://github.com/checkstyle/checkstyle/commit/f02899b24d10a2ef8f11c7e68142401bcddf5a80

**Comment by rnveach** [comment]
> I increased the limit: f02899b

@romani Should the new value be the same as one of our checks, like ClassFanOutComplexity?
https://github.com/checkstyle/checkstyle/blob/d863f040a802d58f6758da32bf939468dca9741a/config/checkstyle_checks.xml#L353

**Comment by romani** [comment]
> like ClassFanOutComplexity?

may be one day we will make config consistent, right now TC have the same config for tests and main, but suppressions are more complicated in TC (we allowed only javadoc tags). Checkstyle violations are easier to suppress on whole file (so suppression list in checkstyle config is wide).
So let it be as it is. We need to speedup pitest PR acceptance.

**Pull request merged**
