### PR TITLE
Issue #14937: Migrated section 7.3.2 Exception: Overrides to chapter wise testing

### PR DESCRIPTION
**Pull request by Zopsss**
#14937

### CODE REVIEW

**Comment by Zopsss** [comment]
Build is failing: 

```
[ERROR] com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.testAllStyleRules -- Time elapsed: 0.187 s <<< FAILURE!
google_style.xml rule '7.3.2 Exception: overrides' should have a test that exists
expected to be true
```

It will resolve once https://github.com/checkstyle/checkstyle/pull/15196 is merged

**Review by romani — APPROVED** [review]
Ok to merge if CI pass

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by rdiachenko** [comment]
@Zopsss please resolve conflicts and check ci

**Comment by Zopsss** [comment]
@rdiachenko done

**Comment by romani** [comment]
@rdiachenko , please rebase this PR after merging of referenced PR

**Comment by romani** [comment]
@Zopsss , please rebase this PR after merging of referenced PR

**Comment by Zopsss** [comment]
> @Zopsss , please rebase this PR after merging of referenced PR

We need to get https://github.com/checkstyle/checkstyle/pull/15196 merged first after that I'll rebase this PR with it. Until then CI will keep failing

**Pull request merged**
