### PR TITLE
minor: Fix indentation checks in inner annotations.

### PR DESCRIPTION
**Pull request by jakubadamek**

### CODE REVIEW

**Comment by romani** [comment]
thanks a lot for helping our project. Please do following:

1) please add 
```<suppress checks="MethodLength" files="HandlerFactory.java" lines="45"/>``` to the end of config/suppresions.xml . CIs should be green.

2) make sure that on your local, "mvn clean verify" passed without Errors.

3)
>  	minor: Fix indentation checks in inner annotations.

sorry, functional changes are never minor.  We use issue/PR numbers in release notes generation and some investigations.

You have two options:
a) update current PR description with a problem explanation (what problem you has right now, on latest release). Make a reference in commit to PR number
b) create issue with full description. Make a reference in commit to Issue number

4)
Please add negative tests inputs (test input code could be slightly modified)

5)
Please copy-paste positive and negative test cases to our ITs inputs for google style config.
https://github.com/checkstyle/checkstyle/tree/master/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation

**Comment by romani** [comment]
release 6.12 is planned to be at 31 of October.
it would very good to finish this PR before release. Do you have time to finish PR ?

**Comment by jakubadamek** [comment]
Thanks Roman, I will try.

**Comment by jakubadamek** [comment]
Hey Roman,

mvn clean verify does not pass on stock master. I get a bunch of errors,
e.g.

[ERROR]
/usr/local/google/home/jakuba/gits/checkstyle2/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDoclet.java:[32,23]
package com.sun.javadoc does not exist
[ERROR]
/usr/local/google/home/jakuba/gits/checkstyle2/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDoclet.java:[58,33]
cannot find symbol
  symbol:   class RootDoc
  location: class com.puppycrawl.tools.checkstyle.doclets.TokenTypesDoclet

Please advise how shall I fix it.

Thanks Jakub

**Comment by romani** [comment]
Travis control our master on each commit, please make sure you based on HEAD , if still a problem please share in github gist full log with -X ption for maven

**Comment by romani** [comment]
Doclet classes can not be found, please make sure that JAVA_HOME is point to jdk, not a jre

**Comment by jakubadamek** [comment]
Thanks Roman, yes, it would be something with my Java installation.

**Comment by romani** [comment]
@jakubadamek ,  do you need help ?

**Comment by jakubadamek** [comment]
Thanks Roman, no, I just need to find a bit of time.

**Comment by jakubadamek** [comment]
Hey Roman, I have done mostly what you wanted. Didn't know where to put the google style config negative tests (have added the positive ones).

**Comment by romani** [comment]
@jakubadamek , thanks for your work

1)Github show that your branch is in conflict state with latest HEAD, please rebase.

2)
> Didn't know where to put the google style config negative tests (have added the positive ones). 

You can put them somewhere there:
https://github.com/checkstyle/checkstyle/tree/master/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation
copy-paste from UTs is ok.

3) We need to make sure that there is no regression after your fix. You need to generate reports by 
https://github.com/checkstyle/contribution/tree/master/checkstyle-tester , and compare report before and after fix. There is unpolished tool that could do all this steps - https://github.com/checkstyle/checkstyle/pull/1474#issuecomment-147448596 .
If you smth is unclear during testing, let me know I will guide you.

**Comment by romani** [comment]
@jakubadamek , let us know if you need help.

FYI: one contributor recently finish tool https://github.com/attatrol/ahsm that compare results of reports, extremely useful tool, we use it almost for each PR.

**Comment by jakubadamek** [comment]
Thanks Roman. I did get a step farther but don't understand why CI is still
failing.

**Comment by romani** [comment]
after your fix, you decreased a code coverage - https://travis-ci.org/checkstyle/checkstyle/jobs/88523568#L878

This mean that that you try to propose to us code that is not completely covered by UTs - that is not acceptable :) .

to generate coverage report, please run "mvn clean cobertura:cobertura" and take a look at HTML report that is in your target folder. Search for your file, and it will show you what is missed. Example of report: http://checkstyle.sourceforge.net/cobertura/index.html

**Comment by romani** [comment]
@jakubadamek , do plan to continue ? do you need help ?

**Comment by romani** [comment]
@jakubadamek  , if you do not have time to finish this issue , I recommend to drop this PR and unlock issue to be resolved by other contributor.

**Comment by jakubadamek** [comment]
Thanks Roman, I will drop it for now.

**Pull request closed without merging**
