### PR TITLE
Issue #8839: update eclipse compiler to R17

### PR DESCRIPTION
**Pull request by pbludov**
Issue #8839 

~~All options are sorted (no more dedicated ignore section).
This makes it easier to find out which options have been added.~~

### CODE REVIEW

**Comment by romani** [comment]
> This makes it easier to find out which options have been added.

please explain how it is easier, what you do to make find new options ? Is it just import to eclipse and export from eclipse ?

Ignore section helped us a lot to reduce amount of "ignore" gradually. it might be useful in next updates to upgrade compiler version but keep new options as ignored until code is fixed.

**Comment by pbludov** [comment]
> please explain how it is easier, what you do to make find new options ? Is it just import to eclipse and export from eclipse ?

Yes, like this:

```bash
$ curl -s https://raw.githubusercontent.com/eclipse/eclipse.jdt.core/master/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/impl/CompilerOptions.java | grep -o 'org.eclipse.jdt.core.compiler.problem.[^"]*' | sort > /tmp/all-options

$ grep -o "^[^=#]*" config/org.eclipse.jdt.core.prefs > /tmp/cs-options

$ diff /tmp/cs-options /tmp/all-options
```

I'm actually use `meld` instead of `diff`.

**Comment by romani** [comment]
> Yes, like this

looks like you are in one step before placing this commands to CI and fail build is somebody upgrade eclipse compiler but does not update options.

You can update your commands with `| sort` and it will be easier detect what is new. BUT we will keep ignore list separate from others as all of them have comments and it is more user friendly.

-----

@rnveach , @strkkk , please share your thoughts on how this file should be organized: sorted or stay as is.

**Comment by pbludov** [comment]
> You can update your commands with | sort 

Good idea. I'll try to restore the order.

**Comment by pbludov** [comment]
@romani order restored

**Review by romani — APPROVED** [review]

**Pull request merged**
