### PR TITLE
minor: forbid merge commits in checkstyle

### PR DESCRIPTION
**Pull request by rnveach**
Checking if we can forbid merge commits with no issues from CI.

### CODE REVIEW

**Comment by rnveach** [comment]
It appears atleast azure and travis uses merge commits in it's CI functions so forbidding all merges won't be possible without some override.

**Comment by rnveach** [comment]
Unless there is something wrong with the check, it is reporting all merge commits using the author's commit information, so it can't be identified that way as being created by the CI itself.

**Comment by romani** [comment]
What you is a reason to forbid ?

**Comment by rnveach** [comment]
We never use merge commits and new contributors always end up with merge commits instead of rebasing the branch. Will the release notes builder even function properly with merge commits?

**Comment by romani** [comment]
> Will the release notes builder even function properly with merge commits?

I doubt it will function well.

you can choose CI that does not do merge commits (I do not remember which) to run this UT only on it.
we can have two test methods: exising one and one more test method that executes extended mode of validation to catch merge commits.
On local we can execute both test methods.

**Pull request closed without merging**
