### PR TITLE
issue #15214: migrated section 5.2.6 parameter names to whole config testing

### PR DESCRIPTION
**Pull request by Zopsss**
#15214

### CODE REVIEW

**Comment by romani** [comment]
fix commit message "Issue ....."

**Review by romani — APPROVED** [review]
commit is changed, CI should pass.

ok to merge.
Diff is not very easy, but ok

**Comment by Zopsss** [comment]
> fix commit message "Issue ....."

I intentionally kept it as "issue", I was just testing if our CI cares about camel casing or not 😅

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by romani** [comment]
@Zopsss , it is not validation of CI, it failing on `mvm verify ` on your local

**Pull request merged**
