### PR TITLE
Issue #6385: Hardcode google tokens in config

### PR DESCRIPTION
**Pull request by sd1998**
Fix for issue #6385.

### CODE REVIEW

**Comment by rnveach** [comment]
@sd1998 It looks like CI is failing.

Also we are expecting a change to `AllChecksTest.testAllCheckTokensAreReferencedInGoogleConfigFile` to show that there is validation requiring the default tokens.

**Comment by sd1998** [comment]
@rnveach To add a validation for default tokens I will have to remove the existing validation `validateAllCheckTokensAreReferencedInConfigFile` as this validation takes into account acceptable tokens (and only uses default tokens for a check if they have not been defined in the config ex: `<module name="NoWhitespaceBefore"/>` ) thus due to hardcoding the default tokens for each check `validateAllCheckTokensAreReferencedInConfigFile` will not pass for checks where  the acceptable tokens are not same as default tokens like in case of `NoWhitespaceBefore.java`

**Comment by rnveach** [comment]
> I will have to remove the existing validation validateAllCheckTokensAreReferencedInConfigFile 

Yes. You will have to replace existing validation with something new as we currently don't support what we want to it to be.

**Comment by romani** [comment]
@sd1998 , please explain what some cases are changed from "no violation" to "violation" ?
I do not expect functional changes in this PR/issue at all.

if some tokens are missed ... it is better to create separate issue on this and prove that tokens must be added and quote google style guide to prove that it is requirement of style. Changes in google style will affect a lot of people so we have to accurate with this, and we have to be public on why we did such changes, as after fix is released and user upgraded his build might fail, so there will be wave of questions to clarify ..... .

Please address CI failures, Teamcity (TC) violations you can review after login "as guest".
Let me know if some failures are not clear and you need help.

**Comment by romani** [comment]
@sd1998 , ping.

**Comment by romani** [comment]
@sd1998 , please rebase to resolve conflict and please try to update config in way to have no changes in other files (as you do not change functionality at all, you just make values explicit).

All changes that you think should be applicable to google style, please move to separate issues.

**Comment by romani** [comment]
Most likely PR #7395 will cover issue.
This PR contains unwanted changes.

**Pull request closed without merging**
