### PR TITLE
reimplement EqualsAvoidNullCheck, #1377

### PR DESCRIPTION
**Pull request by Vladlis**
Now it only flags equals calls which are called on String fields.
Reports are here: https://vladlis.github.io/
So far I've confirmed all violations on Checkstyle, SevNTU-Checkstyle, Guava, Orekit, Hibernate-orm.

### CODE REVIEW

**Comment by romani** [comment]
Reports are impressive and correct.
Code review will take some time please switch to other issue.

**Comment by romani** [comment]
@Vladlis  build is failed, please fix.

**Comment by Vladlis** [comment]
Done, I've just resent PR :)

**Comment by romani** [comment]
1)
> Checks that any combination of String literals with optional assignment 

it is not clear want is "optional assignment"

2)
> Limitations: If the equals method is overridden or

please remove that as it is not relevant to Check focused on String type only

3)
> Java's Autoboxing feature has an affect

is it still relevant ?

4)
>   @author Travis Schneeberger
  version 1.0

add yourself as author and remove version

5)
> public int[] getDefaultTokens() 

move all tokens to getAcceptable and call in all methods getAcceptable

6) 
> astType == TokenTypes.CLASS_DEF || astType == TokenTypes.ENUM_DEF
                || astType == TokenTypes.ENUM_CONSTANT_DEF

please make it in 3 lines , it would be easier to read. do the same for all other cases.

7)
> if ("equals".equals(methodName)

please rebase, you mostlikely will have violation there as the same string constant is used few time

8)
> private void checkMethodCall(DetailAST methodCall) {

please try to split method into two to make it - "single exit point method".

9)
> Plus assignment can have ill affects

is it still relevant ?

10)
>         while (objectFrame != null) {
            if (objectFrame.isClassOrEnumOrEnumConstDef()) {
                break;
            }

please move objectFrame.isClassOrEnumOrEnumConstDef() to while expression

11)
>                 || field.getLineNo() == objCalledOn.getLineNo()
                && field.getColumnNo() < objCalledOn.getColumnNo()) {

please intent line with "&&" further to the right to show user priority of expressions execution.

**Comment by Vladlis** [comment]
1)
> Checks that any combination of String literals with optional assignment

means, that any combination of String literals could be assigned to some variable
2) Done
3) Yes, benefits from autoboxing are not used yet
4) Done
5) Done
6) Done
7) Done
8) Haven't split into two, but have made it "single exit point method" - is it ok?
9) It is
10) Done
11) Done

**Comment by romani** [comment]
1)
> Checks that any combination of String literals with optional assignment 

still not clear please rethrase or provide code example to javadoc

2)
> Yes, benefits from autoboxing are not used yet

It is not clear for me why in example Integer type is used. We are focused to String type only , am I right ?

3)
> Haven't split into two, but have made it "single exit point method" - is it ok?

No, now method even more ugly. You need to single out 
```
        boolean exit = false;
        DetailAST objCalledOn = methodCall.getFirstChild().getFirstChild();
        if (objCalledOn.getType() == TokenTypes.DOT) {
            objCalledOn = objCalledOn.getLastChild();
            if (objCalledOn.getPreviousSibling().getType() == TokenTypes.DOT) {
                exit = true;
            }
        }
        if (!exit && isStringLiteral(objCalledOn)) {
            exit = true;
        }
```

to special method

4)
>                 if (field != null && (frame.isClassOrEnumOrEnumConstDef()
                        || checkLineNo(field, objCalledOn))) {

please always to a preference to indentation rather then to braces, people recognize indentation better then braces. Economizing on line numbers does not make sense. Code should be like 
```
if (field != null 
       && (frame.isClassOrEnumOrEnumConstDef()
                 || checkLineNo(field, objCalledOn)) {
```

5)
> object concatenations would not cause a NullPointerException even

why "object" is mentioned ? we validate only String

6)

http://checkstyle.sourceforge.net/config_coding.html#EqualsAvoidNull

please update xdoc to the same state as javadoc.

**Comment by Vladlis** [comment]
1) Done
2) Now I see what are you talking about. But all concatenations are still considered unsafe. Should I fix it in this PR?
3) Done
4) Fixed
5) See 2)
6) Done

**Comment by romani** [comment]
>  But all concatenations are still considered unsafe.

if we can not validate that cases 100% correctly, we should skip such cases. It better to not put violation rather then annoy user with false-positives.

**Comment by Vladlis** [comment]
> if we can not validate that cases 100% correctly

I suppose that it is better to thoroughly investigate these cases.
They are skipped for now. I propose to do it in another PR as soon as this one is accepted.

**Comment by romani** [comment]
ok, please create separate issue for that , and for now completely remove that from Check documentation and code.

**Comment by Vladlis** [comment]
Done: #1930

**Comment by romani** [comment]
>   Since, it is difficult to determine what kind of Object is being
  concatenated all ident concatenation is considered unsafe.

that text considered as completely detached, I do not understand what case it try to cover. Please rephrase or add example or places that paragraph to proper place.

**Comment by romani** [comment]
1) please update summary sentence for this check at http://checkstyle.sourceforge.net/checks.html

2) Please rebase.

3) please regenerate reports and compare them with report that I verified at the beginning of this PR (that are hosted on github). Please confirm that there is no changes between them (no regression after few refactoring iterations).

I am ready to merge your Check.

**Comment by Vladlis** [comment]
1) Done
2) Done
3) http://vladlis.github.io/ - there are no changes

**Pull request merged**
