### PR TITLE
Issue #13097: Split coding xdocs into separate pages

### PR DESCRIPTION
**Pull request by stoyanK7**
Part of #13097

### CODE REVIEW

**Comment by stoyanK7** [comment]
Github, generate site

**Review by romani — APPROVED** [review]
Ok to merge

**Review by nrmancuso — APPROVED** [review]
God to merge after resolving conflicts and rebase on latest master.

**Comment by romani** [comment]
@stoyanK7 , please fix conflict

**Comment by stoyanK7** [comment]
@romani Conflict resolved.

**Comment by romani** [comment]
@stoyanK7 ,
CI is not happy.
>[ERROR] Failures: 
[ERROR]   XdocsPagesTest.testCategoryIndexPageTableInSyncWithAllChecksPageTable:313 The summary for check CovariantEquals in the file "src/xdocs/checks/coding/index.xml" should match the summary for this check in the file "src/xdocs/checks.xml"

**Comment by stoyanK7** [comment]
@romani Done.

**Pull request merged**
