### PR TITLE
Issue #13321: Kill mutation for CommonUtil

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for CommonUtil

------

# Mutation 
https://github.com/checkstyle/checkstyle/blob/bb64c20cbcf6e543b297b6e809f379bd8746b5e7/config/pitest-suppressions/pitest-utils-suppressions.xml#L237-L245

------

# Explaination
No usage in the whole codebase

### CODE REVIEW

**Review by nrmancuso — APPROVED** [review]
Strange that Intellij/Sonar did not pick this up. Good to merge.

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by Vyom-Yadav** [comment]
> Strange that Intellij/Sonar did not pick this up. Restarted CircleCI. Good to merge.

@nrmancuso They didn't pick this because this method is used in tests. We need to modify rules to check for usage of methods in the actual code base.

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by rdiachenko** [comment]
rebased

**Pull request merged**
