### PR TITLE
Issue #9420: create example of AST for TokenTypes.ELIST

### PR DESCRIPTION
**Pull request by Binita-tech**
Closes: #9420 

ELIST
**Test.java file:**
```
import java.util.ArrayList;
public class Test {
     public static void main(String[] args) {
        new ArrayList<>(50);
    }
}
```
AST printed through CLI:
```
COMPILATION_UNIT -> COMPILATION_UNIT [1:0]
|--IMPORT -> import [1:0]
|   |--DOT -> . [1:16]
|   |   |--DOT -> . [1:11]
|   |   |   |--IDENT -> java [1:7]
|   |   |   `--IDENT -> util [1:12]
|   |   `--IDENT -> ArrayList [1:17]
|   `--SEMI -> ; [1:26]
`--CLASS_DEF -> CLASS_DEF [2:0]
    |--MODIFIERS -> MODIFIERS [2:0]
    |   `--LITERAL_PUBLIC -> public [2:0]
    |--LITERAL_CLASS -> class [2:7]
    |--IDENT -> Test [2:13]
    `--OBJBLOCK -> OBJBLOCK [2:18]
        |--LCURLY -> { [2:18]
        |--METHOD_DEF -> METHOD_DEF [3:5]
        |   |--MODIFIERS -> MODIFIERS [3:5]
        |   |   |--LITERAL_PUBLIC -> public [3:5]
        |   |   `--LITERAL_STATIC -> static [3:12]
        |   |--TYPE -> TYPE [3:19]
        |   |   `--LITERAL_VOID -> void [3:19]
        |   |--IDENT -> main [3:24]
        |   |--LPAREN -> ( [3:28]
        |   |--PARAMETERS -> PARAMETERS [3:29]
        |   |   `--PARAMETER_DEF -> PARAMETER_DEF [3:29]
        |   |       |--MODIFIERS -> MODIFIERS [3:29]
        |   |       |--TYPE -> TYPE [3:29]
        |   |       |   |--IDENT -> String [3:29]
        |   |       |   `--ARRAY_DECLARATOR -> [ [3:35]
        |   |       |       `--RBRACK -> ] [3:36]
        |   |       `--IDENT -> args [3:38]
        |   |--RPAREN -> ) [3:42]
        |   `--SLIST -> { [3:44]
        |       |--EXPR -> EXPR [4:8]
        |       |   `--LITERAL_NEW -> new [4:8]
        |       |       |--IDENT -> ArrayList [4:12]
        |       |       |--TYPE_ARGUMENTS -> TYPE_ARGUMENTS [4:21]
        |       |       |   |--GENERIC_START -> < [4:21]
        |       |       |   `--GENERIC_END -> > [4:22]
        |       |       |--LPAREN -> ( [4:23]
        |       |       |--ELIST -> ELIST [4:24]
        |       |       |   `--EXPR -> EXPR [4:24]
        |       |       |       `--NUM_INT -> 50 [4:24]
        |       |       `--RPAREN -> ) [4:26]
        |       |--SEMI -> ; [4:27]
        |       `--RCURLY -> } [5:4]
        `--RCURLY -> } [6:0]
```
**The expected update for javadoc is:**
```
 |--EXPR -> EXPR 
 |   `--LITERAL_NEW -> new 
 |       |--IDENT -> ArrayList 
 |       |--TYPE_ARGUMENTS -> TYPE_ARGUMENTS 
 |       |   |--GENERIC_START -> < 
 |       |   `--GENERIC_END -> > 
 |       |--LPAREN -> ( 
 |       |--ELIST -> ELIST 
 |       |   `--EXPR -> EXPR 
 |       |       `--NUM_INT -> 50 
 |       `--RPAREN -> )
 |--SEMI -> ;     
```

### CODE REVIEW

**Comment by AbhinavRajputEXE** [comment]
[comment](https://github.com/checkstyle/checkstyle/issues/9455#issuecomment-988130395)
Failing CI says PR is more than 20 commits old, so I guess this time also the local environment was not up to date.

**Comment by romani** [comment]
Please readhttps://checkstyle.org/beginning_development.html#Starting_Development

Commands explain how to catch up with upstream.

**Review by romani — APPROVED** [review]
Ok to merge as CI pass

**Comment by romani** [comment]
GitHub, rebase

**Comment by Binita-tech** [comment]
@romani, is this ok to merge? if so please merge so that I can raise another PR.

**Pull request merged**
