### PR TITLE
Add SuppressionAnnotationFilter

### PR DESCRIPTION
**Pull request by attatrol**
A new filter is added. It satisfies issue #1340.
It suppresses events generated from code elements annotated by user defined annotations.
It has 3 properties:
'annotationName' - a StringSet which contains annotations' names, simple or fully-qualified;
'permittedChecks' - a StringSet which contains regular expressions for checks which bypass filter;
'modifiersExcluded' - a boolean, if true them modifiers of an annotated element are excluded from suppression (including suppressive annotations themselves), set true by default.

### CODE REVIEW

**Comment by romani** [comment]
1) please create issue and describe in detail necessity of that filter

2) create xdoc files and it will come-up to HTML web site

3) fix build , and reference in commit message to github  issue.

**Comment by romani** [comment]
please clarify status of PR. 

1) are you ready for code review ?

2) we are currently in moratorium period, so no new Checks/Modules are accepted - http://checkstyle.sourceforge.net/contributing.html#Introduction . But we will get out of that state soon.

I could accept your Filter before moratorium period finish if you provide a proven way to test your functionality. UTs is very basic approach - it is not enough. I very busy right now with a fight for Checkstyle stability so I do not have a time to help you.

I need testing on real sources. We do that right now by simple tool https://github.com/checkstyle/contribution/tree/master/checkstyle-tester , that generates reports like http://mezk.github.io/index.html that help us to control changes for regressions. So I need smth like that for your Filter.

If you do not have time for such testing now , I could offer you to move that Filter to https://github.com/sevntu-checkstyle/sevntu.checkstyle project (almost copy-paste) and let you (and me) use it in non-opensource code and test it for some period. I will do release of that project right after I merge your code (after code review).

Please let me know what is your choice.

**Comment by attatrol** [comment]
1) i'm ready for review.
2) i need one day more to try to find a proper example of code for additional testing.

**Comment by attatrol** [comment]
2) you can move it to sevntu project.

**Comment by romani** [comment]
please do it yourself, xdoc part of request please store as gist and put link to PR any other place, we will use them as we start transition from sentu project to main project.

sevntu project require a bit more configurations to be created to let it be used in Eclipse-cs, sonar, .......

**Pull request closed without merging**
