### PR TITLE
Issue #5832: Code samples for Naming Checks

### PR DESCRIPTION
**Pull request by jack870131**
#5832 

The CLI test for the case:

```
Jack@Jack MINGW64 ~/Documents/tmp (master)
$ javac TestCatchParameterNameCheck.java

Jack@Jack MINGW64 ~/Documents/tmp (master)
$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="CatchParameterName">
      <property name="severity" value="warning"/>
      <property name="format" value="^[a-z][a-zA-Z0-9]+$"/>
    </module>
  </module>
</module>

Jack@Jack MINGW64 ~/Documents/tmp (master)
$ cat TestCatchParameterNameCheck.java
class FirstException extends Exception {}
class SecondException extends Exception {}
class ThirdException extends Exception {}

public class TestCatchParameterNameCheck {
  public void MyTest() {
    String str = null;
    try {
      if (str.equals("1")) {
        throw new FirstException();
      } else if (str.equals("2")) {
        throw new SecondException();
      } else {
        throw new ThirdException();
      }
    } catch (FirstException ex) { // OK
      // ...
    } catch (SecondException ex2) { // OK
      // ...
    } catch (ThirdException thirdException) { // OK
      // ...
    }
  }
}
Jack@Jack MINGW64 ~/Documents/tmp (master)
$ RUN_LOCALE="-Duser.language=en -Duser.country=US"

Jack@Jack MINGW64 ~/Documents/tmp (master)
$ java $RUN_LOCALE -jar checkstyle-8.11-all.jar -c config.xml TestCatchParameterNameCheck.java
Starting audit...
Audit done.
```

Please have a check. I have done whole mvn verify test locally and it shows that I didn't got any error for this case. However, the CI test still told me that it has the LifecycleExecutionException. Could you please tell me why this exception keep showing up?

### CODE REVIEW

**Comment by romani** [comment]
Please read logs of all failed CI items and fix problems. You need to understand how to work with CI failres and understand what they demand

**Comment by jack870131** [comment]
I know how to fix another exception in CI test now. However, I still don't know how to deal with this kind of exception. Could you give me some instructions?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (ant-phase-verify) on project checkstyle: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/travis/build/checkstyle/checkstyle/config/ant-phase-verify.xml:156: Checkstyle failed: Got 2 errors and 0 warnings.
[ERROR] around Ant part ...<ant antfile="config/ant-phase-verify.xml"/>... @ 8:47 in /home/travis/build/checkstyle/checkstyle/target/antrun/build-main.xml
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (ant-phase-verify) on project checkstyle
```

**Comment by rnveach** [comment]
@jack870131 Look at error lines above it.
https://travis-ci.org/checkstyle/checkstyle/jobs/416043612#L815
> [checkstyle] [ERROR] /home/travis/build/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/CatchParameterNameCheck.java:73:6: File contains tab characters (this is the first instance). [FileTabCharacter]
[checkstyle] [ERROR] /home/travis/build/checkstyle/checkstyle/src/xdocs/config_naming.xml:386:3: File contains tab characters (this is the first instance). [FileTabCharacter]

**Comment by jack870131** [comment]
@romani @rnveach So how could I put the //. . . in the try block and pass the javac without any error?

**Comment by romani** [comment]
>I don't know if it's OK with that.

That is ok to skip javac here and have only cli output. We do not want to put in examples too much not required code, to let user quickly and easily see how Check works

**Pull request closed without merging**
