### PR TITLE
Issue #13321: Kill mutation for UncommentedMainCheck-3

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for UncommentedMainCheck-3

---------

# Check
https://checkstyle.org/checks/misc/uncommentedmain.html

---------

# Mutation 
https://github.com/checkstyle/checkstyle/blob/2be5780673b9ba5397526aadab981be68f874172/config/pitest-suppressions/pitest-misc-suppressions.xml#L201-L208

---------

# Explaination 
In visitToken when Token is classDEF or RecordDef it call visitClassOrRecordDef where if classDepth == 0 then only currentClass will update know every time when new file come sequentially they alwyas have a class and that time the classDepth is always 0. and classdepth is reset to 0 in begintree. 

-------

# Regression 

------

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/92e6545d9dda7c3febcd4ad8f8a91443/raw/5b88dc50b3b7828cca1bce0d4d6aa47209d25647/UMC.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/360a95ed7bb60d7a0956e531199d484c4d6f6617/test-projects.properties
Report label: Regression-2

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
>new file come sequentially they alwyas have a class

New file can have only interface or record. Are you sure in your explanation?

**Review by romani — APPROVED** [review]
After reading a code, I agree on this update

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

**Review by rdiachenko — APPROVED** [review]
lgtm

**Pull request merged**
