### PR TITLE
Issue #3891: Split and Organize Checkstyle inputs by Test for coding package

### PR DESCRIPTION
**Pull request by izishared**
Issue #3891 Move test resource of coding package to new location

### CODE REVIEW

**Comment by Vladlis** [comment]
@izishared 
This PR is hard to review (140 files are changed). I recommend splitting in smaller commits. It is OK to add more than one commit in PR, but it might result in some inconvenience during fixing review points - you might need to change Nth commit in a chain of M commits.

**Comment by romani** [comment]
@izishared , issue 3891 was not assigned to you.
Please mention in issue issue that is assigned to you personally.
in commit  there should only changes for one Check test and its inputs.

if you you stuck with git, please remove your branch and fork and start from scratch.

**Comment by izishared** [comment]
@romani I'll split my commit. One commit for one test and its inputs. Ok.

**Comment by romani** [comment]
@izishared , please close this PR or rebase it resolve conflicts

**Comment by izishared** [comment]
@romani I've deleted branch and close this PR. I'll continue to do #4165

**Pull request closed without merging**
