### PR TITLE
Fix the error message

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Resolves: #15573

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationLocation/all-examples-in-one

**Comment by relentless-pursuit** [comment]
> Github, generate report for AnnotationLocation/all-examples-in-one

https://github.com/checkstyle/checkstyle/actions/runs/10605464520

**Comment by romani** [comment]
Please make commit message to follow rules that we have for commit message

**Comment by romani** [comment]
Github, generate report for AnnotationLocation/all-examples-in-one

**Comment by relentless-pursuit** [comment]
> Please make commit message to follow rules that we have for commit message

done

**Comment by romani** [comment]
Github, generate report for AnnotationLocation/all-examples-in-one

**Comment by romani** [comment]
Failed , good .
https://github.com/checkstyle/checkstyle/actions/runs/10607293845

**Pull request merged**
