### PR TITLE
Issue #10320: Update inputs for EmptyForIteratorPadCheckTest

### LINKED ISSUE #10320: Update inputs for EmptyForIteratorPadCheckTest
Child of #10080

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #10320

### CODE REVIEW

**Comment by timurt** [comment]
fix conflicts

**Comment by shashwatj07** [comment]
> fix conflicts

done

**Comment by shashwatj07** [comment]
please restart semaphore @timurt

**Comment by romani** [comment]
Restarted

**Pull request merged**
