### PR TITLE
100% test coverage for ParameterNumberCheck, OuterTypeNumberCheck, MethodLengthCheck, LineLengthCheck, FileLengthCheck, ExecutableStatementCountCheck, AnonInnerLengthCheck, issue #1024

### PR DESCRIPTION
**Pull request by MEZk**
100% test coverage for ParameterNumberCheck, OuterTypeNumberCheck, MethodLengthCheck, LineLengthCheck, FileLengthCheck, ExecutableStatementCountCheck, AnonInnerLengthCheck, issue #1024

### CODE REVIEW

**Comment by MEZk** [comment]
The problem with cobertura for class MethodCountCheck coverage remains the same.

**Comment by romani** [comment]
@MEZk , 

> public void testVisitSlistWhenParentEqualsNull()  

That is last chance option to cover a code. Please look at it attentively - it is incorrect. Slist can not have NULL as parent.  so instead of checking for null author mean condition https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheck.java#L177 that stop a WHILE loop, so please refactor code.

Please launch your changes through checkstyle-tester(https://github.com/checkstyle/contribution/tree/master/checkstyle-tester) project on all projects that are referenced in in property file. That is required to be sure that our idea that check for null is useless is true.

**Comment by MEZk** [comment]
@romani , 
yes, I think that it is unnecessary to check if parent  equals to null in while . I'll do refactoring and run tester as soon as I can.

**Comment by MEZk** [comment]
@romani ,

I found out that parent can equal to null if it is a root node because we change parent each time when we reach the end of the while loop.

```java
parent = parent.getParent();
````

That is why it is nnecessary to check if parent does not equal to null, since we won't get NPE.

```java
 while (parent != null) {
                final int type = parent.getType();
                if (type == TokenTypes.CTOR_DEF
                    || type == TokenTypes.METHOD_DEF
                    || type == TokenTypes.INSTANCE_INIT
                    || type == TokenTypes.STATIC_INIT) {
                    if (parent == contextAST) {
                        context.addCount(ast.getChildCount() / 2);
                    }
                    break;
                }
                parent = parent.getParent();
            }
```

**Comment by romani** [comment]
In theory yes that is true.
Can you make a java input file for such case ?

most likely - no. So code have to be refactored. As slist always below a CLASS token. We have tree of java class so we rely on grammar of java.

**Comment by MEZk** [comment]
@romani 
I did refactoring and also found incorrect comparsion of objects in ExecutableStatementCountCheck.

````java
if (parent == contextAST) {
    context.addCount(ast.getChildCount() / 2);
}
````

parent is an object and contextAst as well, that is why we should use equals method. 

I have already tested my changes with all tests in ExecutableStatementCountCheckTest. 
I'm going launch my changes through checkstyle-tester on all projects that are referenced in property file

**Comment by romani** [comment]
Please do push to github , i will take a look at changes.

**Comment by MEZk** [comment]
@romani 
Done

**Comment by romani** [comment]
Looks good. What about testing results ?

**Comment by MEZk** [comment]
@romani 
Here is the checkstyle-tester report
http://mezk.github.io

**Comment by romani** [comment]
What is a reason such report ? What it tells you ?

1) generate report only for your Check to make sure there is no exceptions

2) generate report before and after fix to be sure that your changes does not change logic of validation

**Comment by romani** [comment]
>also found incorrect comparsion of objects in ExecutableStatementCountCheck

Please explain why that is incorrect ? Ast tree is readonly , so it safe to compare references of  objects, and https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java does not override equals method. So no difference.

**Comment by MEZk** [comment]
@romani 
Before fix
http://mezk.github.io/site_before/index.html

After fix 
http://mezk.github.io/site_after/index.html

In both cases there are no exceptions, only warnings.

**Comment by romani** [comment]
Please leave == .

Compare reports and cinfirm that there are no difference in violations.

**Comment by MEZk** [comment]
@romani 
I launched checkstyle-tester on all projects that are referenced in in property file.

Before my changes (6.7-SNAPSHOT)
http://mezk.github.io/site_before/index.html

After my changes
http://mezk.github.io/site_after/index.html

Cobertura report
http://mezk.github.io/cobertura/

I also ran checkstyle-tester report files (before and after changes) through notepad++ compare plugin and it showed that files match (messages, violations, etc.).

**Comment by romani** [comment]
good. please squash all your commits in one.

**Comment by MEZk** [comment]
@romani 
Done.

We should discuss in Skype why cobertura reports that there are uncovered methods in MethodCountCheck.

**Comment by romani** [comment]
merged as FF, please find me in skype on Monday.

**Pull request closed without merging**
