### PR TITLE
Issue #2161: unify test input locations for coding package

### PR DESCRIPTION
**Pull request by rnveach**
final for coding package, no unused files, just mis-placed ones

### CODE REVIEW

**Comment by rnveach** [comment]
@romani appveyor looks like a bad run and needs a restart
https://ci.appveyor.com/project/Checkstyle/checkstyle/build/2327/job/3vq95gv2fy5lp5dh#L345
> Error parsing 'C:\projects\checkstyle\src\xdocs\anttask.xml.vm': line [-1] Error reading the input source: Stream closed

**Comment by romani** [comment]
not clear why InputReturnFromCatchCheck.java , InputReturnFromFinallyCheck.java
are placed at "com.puppycrawl.tools.checkstyle.checks;", please explain.

**Comment by romani** [comment]
PR is merged to not keep a lot of changes , my previous comment could be done in separate PR if required.

**Comment by rnveach** [comment]
@romani 
Both inputs are only used in DescandantTokenCheckTest which is in the "checks" package.
Since they were originally in the "coding" folder, but not used by a "coding" test, I moved them out to be in the same packageas their Test file.

**Pull request merged**
