### PR TITLE
Issue #13059: Broken Link: Github search links are broken in document…

### PR DESCRIPTION
**Pull request by Andromeda227799**
Fixing Issue https://github.com/checkstyle/checkstyle/issues/13059 by replacing all `+filename%3A` to `%20path%3A**%2F` since filenames are no more supported by github search

### CODE REVIEW

**Comment by Andromeda227799** [comment]
@romani , I updated the PR description, could you please re-run the CI

**Comment by Vyom-Yadav** [comment]
@Andromeda227799 You need to use GitHub keywords to bind your pull request to an issue. See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by Vyom-Yadav** [comment]
From CI:
```
[ERROR] [checkstyle] [ERROR] /home/vsts/work/1/s/src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java:1352: Line is longer than 100 characters (found 102). [LineLength]
```

Please fix the CI failure and make sure `mvn clean verify` passes on your local setup before creating a pull request.

**Comment by romani** [comment]
CI still failing

**Review by rnveach — APPROVED** [review]

**Review by romani — APPROVED** [review]
I meant to approve it at first place

**Pull request merged**
