### PR TITLE
Issue #11194: Bump year to 2022

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Issue #11194: Bump year to 2022

### CODE REVIEW

**Review by rnveach — APPROVED** [review]

**Comment by rnveach** [comment]
Master:
https://github.com/checkstyle/checkstyle/search?q=2021
PR:
https://github.com/Vyom-Yadav/checkstyle/search?q=2021&type=code

All changed.

**Comment by Vyom-Yadav** [comment]
It May be closed to test #11196

**Comment by romani** [comment]
We still need it as action will run next year 1 Jan.

**Comment by Vyom-Yadav** [comment]
You can also manually run it from the actions tab.

**Comment by romani** [comment]
I updated post merge request at https://github.com/checkstyle/checkstyle/pull/11196

**Comment by romani** [comment]
merged, as it blocked release of sevntu project

**Pull request merged**
