### PR TITLE
Issue #2944: add EmptyLineSeparator option to check empty lines inside methods

### PR DESCRIPTION
**Pull request by Vladlis**
#2944

Diff report over guava, checkstyle, sevntu-checkstyle, pmd, spring-framework, hibernate-orm and Orekit looks OK - http://vladlis.github.io/reports/2944/

### CODE REVIEW

**Comment by romani** [comment]
@Vladlis , please fix CIs.

**Comment by romani** [comment]
> empty.line.separator.multiple.lines.inside=There is more than 1 empty line one after another.

please use Google translator to translate message to all languages. Any translation is ok, one day native contributor will make it correct.

**Comment by Vladlis** [comment]
Done

For some reason circleCI installs 6.17-SANPSHOT and tries to use 6.18-SANPSHOT, thus fails.

**Comment by romani** [comment]
@Vladlis , please rebase your code over latest upstream master.

**Comment by Vladlis** [comment]
@romani, thanks, I thought it's already rebased )
Done

**Comment by romani** [comment]
1)
> private boolean allowMultipleEmptyLinesInsideClassMembers = true;

default is "true"
please update checkstyle config to have it as "false". We need to you all options in our config - "eat your own food". Such update should be in this PR.
Please provide updated for new violations in separate PR, to let me recheck how Check is working and merge it before.

2)
Please provide regression testing report with new option and value "true" over all projects in chekcstyle-tester.

3)
separate report(few projects) with new option as "false".

4)
> 
```
        if (astType == TokenTypes.STATIC_INIT
                || astType == TokenTypes.INSTANCE_INIT
                || astType == TokenTypes.METHOD_DEF
                || astType == TokenTypes.CTOR_DEF) {
```

https://docs.oracle.com/javase/specs/jls/se7/html/jls-6.html#jls-6.3
please make a function from this and name it - isClassMemberBlock.

5)
> private static List<Integer> getEmptyLinesToLog(List<Integer> emptyLines) {

single return.

6)
> E.g. if there are the following empty lines: 1,2,3,4,8,9 then 1 and 8 will be returned.

I might be wrong but such implementation look over complicated for such simple task.
First of all we could reports as much violations as empty lines we have. That will help user remove them quickly, and will even be beneficial when IDEs/tools start automatically resolve Checkstyle violations. 
If there is some reason behind minimizing violations - please state it in javadoc and try to do this in two steps: 1) `getEmptyLinesForReporting(...)` 2) `minimize(...)`

**Comment by Vladlis** [comment]
1)
Checkstyle does not have new violations

2) 
http://vladlis.github.io/reports/2944regression/ - no regsression

3) 
http://vladlis.github.io/reports/2944option/ - didn't find any false positive (projects: guava, checkstyle, sevntu-checkstyle, pmd, spring-framework, hibernate-orm, Orekit)

4) Done
5) Done
6) Simplified

**Comment by romani** [comment]
1)
>
```
  +            final Iterator<Integer> emptyLineIterator = emptyLines.iterator();
+            int previousEmptyLineNo = emptyLineIterator.next();
+            while (emptyLineIterator.hasNext()) {
+                final int currentEmptyLineNo = emptyLineIterator.next();
```

iterator is always read as non-simple way - too verbose.

why not  :
```
int previousEmptyLineNo = emptyLineIterator.get(0);
for (int currentEmptyLineNo : emptyLineIterator)
```

2) Reports are good, please fix the last item and I am ready to merge.

**Comment by Vladlis** [comment]
@romani 
Done

**Comment by romani** [comment]
Merged as FF

**Pull request closed without merging**
