### PR TITLE
Issue #8151: Update XpathRegressionNestedTryDepthTest to have atleat 2 tests.

### PR DESCRIPTION
**Pull request by Gaurav-Punjabi**
Resolves issue #8151

### CODE REVIEW

**Comment by Gaurav-Punjabi** [comment]
@strkkk Please review.

**Comment by romani** [comment]
Please resolve conflict

**Comment by Gaurav-Punjabi** [comment]
> Please resolve conflict

Done 👍

**Comment by romani** [comment]
@Gaurav-Punjabi , conflict, please resolve.

**Comment by Gaurav-Punjabi** [comment]
@romani I fixed the conflicts, but appveyor is failing again. I rebased with the latest master while fixing the conflicts. Can you please restart appveyor ?

**Pull request merged**
