### PR TITLE
Added new Check: CommentsIndentationCheck, issue #333.

### PR DESCRIPTION
**Pull request by MEZk**
@romani 
Differences from code, which was implemented by original author of the Check - [alexkravin](https://github.com/alexkravin/checkstyle/tree/CommentsIndentationCheck%23333) :

1) Fixed NPE at [getPreviousStmt](https://github.com/checkstyle/checkstyle/commit/30db8928ccb80fb24ef09a55d49f2badf86afacb#diff-98a10dcd6ab0642314ef374b42c293deR158), [visitSingleLineComment](https://github.com/checkstyle/checkstyle/commit/30db8928ccb80fb24ef09a55d49f2badf86afacb#diff-98a10dcd6ab0642314ef374b42c293deR137), [visitBlockComment](https://github.com/checkstyle/checkstyle/commit/30db8928ccb80fb24ef09a55d49f2badf86afacb#diff-98a10dcd6ab0642314ef374b42c293deR254).
2) Added test inputs to check NPE [at getPreviousStmt](https://github.com/checkstyle/checkstyle/commit/30db8928ccb80fb24ef09a55d49f2badf86afacb#diff-569b036e62fe04824543623da193755fR80), [at visitSingleLineComment](https://github.com/checkstyle/checkstyle/commit/30db8928ccb80fb24ef09a55d49f2badf86afacb#diff-569b036e62fe04824543623da193755fR117), [at visitBlockComment](https://github.com/checkstyle/checkstyle/commit/30db8928ccb80fb24ef09a55d49f2badf86afacb#diff-4e4948aac8ed5aaa762044ac76e11bbfR32).
3) Resolved PMD violation: TooFewBranchesForASwitchStatement:Swith are designed complex branches, and allow branches to share treatement. Using a switch for only a few branches is ill advised, as switches are not as easy to understand as if. In this case, it's most likely is a good idea to use a if statement instead, at least to increase code readability. For more information see the following [link](http://pmd.sourceforge.net/pmd-4.3.0/rules/design.html). 

Replaced switch-statementat at  [getPreviousStmt](https://github.com/MEZk/checkstyle/commit/30db8928ccb80fb24ef09a55d49f2badf86afacb#diff-98a10dcd6ab0642314ef374b42c293deR163)

````java
switch (blockBody.getType()) {
    case TokenTypes.EXPR:
        prevStmt = blockBody.getFirstChild().getFirstChild();
        break;
        default:
    prevStmt = blockBody;
        break;
}
````

with if-else-statement

````java
if (blockBody.getType() == TokenTypes.EXPR) {
    prevStmt = blockBody.getFirstChild().getFirstChild();
}
else {
    prevStmt = blockBody;
}
````

4) Added ITs.
5) Replaced link to google-style java guide at [config_misc.xml](https://github.com/checkstyle/checkstyle/commit/30db8928ccb80fb24ef09a55d49f2badf86afacb#diff-6d008890c58eff0fca4d70c2f52fccbfR185).
6) Updated google style coverage page. Updated [google_style.xml](https://github.com/checkstyle/checkstyle/commit/30db8928ccb80fb24ef09a55d49f2badf86afacb#diff-36ec9d43a841041d749cc197e1cf764eR913). Added correct link to google-style java guide. Other links should be replaced according to issue #751.
7) Provided international messages for violations.
8) Fixed checkstyle violations with checkstyle_checks.xml (left curly brace should be at the end of the line, left curly brace policy is EOL).
9) [REPORTS](http://mezk.github.io).

### CODE REVIEW

**Comment by romani** [comment]
1) 
> http://mezk.github.io/checkstyle_6.9-SNAPSHOT_i333/checkstyle.html
checkstyle/src/it/resources/

please remove from report all its resources and test resources, please see for checkstyle-tester config file on how to do that

2)
http://mezk.github.io/guava_i333/xref/guava/guava-tests/test/com/google/common/util/concurrent/JSR166TestCase.html#L257

that is unclear case, we need to investigate it, it is not a comment for code it is commented out code.
Keeping such code is not good, as GIT will store all history and no need to keep such code for history. If we find more cases like that, we might need to make special option for this.

3)
> http://mezk.github.io/guava_i333/xref/guava/guava/src/com/google/common/util/concurrent/Monitor.html#L899

that is also conner case , very similar to "2)". I think we need to put violation on that cases, and ne option introduction will be by users demand.

4) please provide report on performance changes for Guava project, we need to know how much we will be slower on Google config (that check should not use ANTLR parser for parsing javadoc, so I do not expect any serious changes in performance).

**Comment by romani** [comment]
7)
> && !areSameLevelIndented(singleLineComment, prevStatement, nextStatement)) {

please empty line after it to visually separate condition and IF-body.

8)
>                     && parentBlock.getParent().getPreviousSibling().getType()
                    == TokenTypes.LITERAL_CASE) {
                    prevBlock = parentBlock.getParent().getPreviousSibling();

separate expression and body, change indentation of "==" to be more deep as it is not the same level as "&&"

9)
> private boolean isTrailingSingleLineComment(DetailAST singleLineComment)
> private boolean isTrailingBlockComment(DetailAST blockComment) {

please explain why you need additional parsing of raw source to main(that create AST tree).
Parsing by regExp is unstable as there are number of cases "// /**/" and nested comments and .... 
All you need is Tree analysis.
NO body is ever decrypt ""^(.*\\s+/\\*.*\\*/.*\\S+.*)|(.*\\S+.*/\\*.*\\*/\\s{0,})$"" , that is not human friendly and most likely error prone.

10)
> <module name="CommentsIndentation"/>

please add that Check to end of file, as you damage all links in our style-coverage report (you shifted all Checks below to one line, so report is directed to incorrect place).

**Comment by MEZk** [comment]
@romani 
I've reviewed reports and found similar cases, where code is commented out:

Spring:
[L707](http://mezk.github.io/spring_i333/xref/spring-framework/spring-beans/src/main/java/org/springframework/beans/factory/support/ConstructorResolver.html#L707)
[L169](http://mezk.github.io/spring_i333/xref/spring-framework/spring-core/src/main/java/org/springframework/asm/ClassReader.html#L169)
[L196](http://mezk.github.io/spring_i333/xref/spring-framework/spring-core/src/main/java/org/springframework/asm/ClassVisitor.html#L196)
[L119](http://mezk.github.io/spring_i333/xref/spring-framework/spring-core/src/main/java/org/springframework/asm/FieldVisitor.html#L119)
[L113](http://mezk.github.io/spring_i333/xref/spring-framework/spring-core/src/main/java/org/springframework/asm/MethodVisitor.html#L113)
[L184](http://mezk.github.io/spring_i333/xref/spring-framework/spring-core/src/main/java/org/springframework/asm/MethodVisitor.html#L184)
[L700](http://mezk.github.io/spring_i333/xref/spring-framework/spring-core/src/main/java/org/springframework/asm/MethodVisitor.html#L700)
[L762](http://mezk.github.io/spring_i333/xref/spring-framework/spring-core/src/main/java/org/springframework/asm/MethodVisitor.html#L762)
[L835](http://mezk.github.io/spring_i333/xref/spring-framework/spring-core/src/main/java/org/springframework/asm/MethodVisitor.html#L835)

MaterialDesign:
[L31](http://mezk.github.io/MaterialDesign_i333/xref/MaterialDesignLibrary/MaterialDesign/src/com/gc/materialdesign/views/ButtonRectangle.html#L31)
[L72](http://mezk.github.io/MaterialDesign_i333/xref/MaterialDesignLibrary/MaterialDesign/src/com/gc/materialdesign/views/ButtonRectangle.html#L72)
[L116](http://mezk.github.io/MaterialDesign_i333/xref/MaterialDesignLibrary/MaterialDesign/src/com/gc/materialdesign/views/ButtonRectangle.html#L116)
[L123](http://mezk.github.io/MaterialDesign_i333/xref/MaterialDesignLibrary/MaterialDesign/src/com/gc/materialdesign/views/ButtonRectangle.html#L123)
[L64](http://mezk.github.io/MaterialDesign_i333/xref/MaterialDesignLibrary/MaterialDesign/src/com/gc/materialdesign/views/ProgressBarCircularIndeterminate.html#L64)

Interesting trailing block comments cases: 
https://github.com/MEZk/checkstyle/commit/93812cd762a4fdefa2da2a6630c26660e5cc64ca#diff-27a63edb5df91aab04ffce21a314fb07R114
https://github.com/MEZk/checkstyle/commit/93812cd762a4fdefa2da2a6630c26660e5cc64ca#diff-27a63edb5df91aab04ffce21a314fb07R123

**Comment by romani** [comment]
> Interesting trailing block comments cases: 

that is leading comment, weird and wrong approach.

> I've reviewed reports and found similar cases, where code is commented out:

thanks for investigation, we should skip that doring that task, catching commented out code vs text comments will be done separately sometime in future, but that is possible and could be automated.

> They are methods which were designed by original author of the Check

That is why you step in to finish that Check, It did not pass code review, so nothing is set in stone in it.
You responsible for whole design, so please do not hesitate to change anything.

> I don’t completely agree with you. According to Google's java style-guide:

ok, lets skip that for a while, it is ok to place violations like you did - comments have to be intended as surrounding code.

**Comment by romani** [comment]
1) Please, by separate commit, add this Check to checkstyle_checks.xml and fix all violations in our code.

2) I rechecked checkstyle and guava report - functionally Check work fine, please focus on latest polishing and prepare for merge.

3) 
http://roman-ivanov.blogspot.com/2013/10/trailing-comment-check-false-positives.html

about trailing comments false-positives

4)
I see no problems in your PR, please do "1)" and be ready to merge. I will merge you in 6.10 (in few days).

**Comment by MEZk** [comment]
@romani 
>that is leading comment, weird and wrong approach.

Nevertheless, It is from PMD's (or findbugs, not sure exactly) code, not from tests examples, that is why I decided to add that code.

Fixed PMD's violation where it was possible: DD - Anomaly: A recently defined variable is redefined. See [DataflowAnomalyAnalysis](http://pmd.sourceforge.net/pmd-4.2.5/rules/controversial.html).

>about trailing comments false-positives

Interesting, I don't like trailing comments at all, code should be self-documented).

PR was rebased onto latest master state.

**Comment by romani** [comment]
that PR is waiting for 6.9 release , to be merged at 6.10-SNAPSHOT

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
