### PR TITLE
Issue #5758: converted other line/column checks to log ast

### PR DESCRIPTION
**Pull request by rnveach**
Issue #5758

This fixes all checks in the issue.

### CODE REVIEW

**Comment by romani** [comment]
@rnveach , thanks a lot.
Changes looks good.

previously we agreed to append tests to https://github.com/checkstyle/checkstyle/tree/master/src/it/java/org/checkstyle/suppressionxpathfilter for each Check that become xpath compliant.

**Comment by rnveach** [comment]
Some changes were done in https://github.com/checkstyle/checkstyle/issues/6121 and were not added to xpath list and not added for regression.
Other checks are missing in regression that are already listed too.

**Comment by romani** [comment]
This is my bad, that I forgot about this. @pbludov actually made statement that extra work should be done is scope of #5758.

If you want to postpone `it` update, please create separate issue on this with label "easy".

**Comment by rnveach** [comment]
Done at https://github.com/checkstyle/checkstyle/issues/6207 .

**Pull request merged**
