### PR TITLE
Issue #2271:  Fix issues for Java found by Codacy static analysis tool

### PR DESCRIPTION
**Pull request by MEZk**
#2271

### CODE REVIEW

**Comment by romani** [comment]
:) , no .

we need to be consistent in validation rules. Codacy need to be updated to use values from checkstyle_checks.xml file.
All such violations are simple  chekcstyle should catch them. Why we missed this by chekcstyle validation ?

**Comment by MEZk** [comment]
@romani
Some of the files are in suppressions.xml, in addition, Codacy has it own configuration which is differ to Checkstyle's. Codacy in our case uses its default config

**Comment by romani** [comment]
so we need to update Codacy config.
if you interested in fixing this issue I could give you permission to Codacy configuration.
if you do not want to fix it completely - please provide recommendations what to change in Codacy.

**Comment by MEZk** [comment]
@romani 

Investigation:

| Rule                 | Checkstyle	| Codacy  | 
| ------------------ |:----------------:| -------:|-----:|
| ParameterNumber (ExcessiveParameterList)    | max =7                | max = 5       |
| MethodLength (ExcessiveMethodLength)    | max = 150                | max = 75       |


Suppressions for IllegalCatch (PMD's AvoidThrowingRawExceptionTypes from Codacy)
````xml
    <suppress checks="IllegalCatch"
              files="Checker.java"
              lines="315"/>
    <suppress checks="IllegalCatch"
              files="Checker.java"
              lines="320"/>
 ````
Suppressions for AvoidThrowingRawExceptionTypes from PMD
````xml
<rule ref="rulesets/java/strictexception.xml/AvoidThrowingRawExceptionTypes">
    <properties>
      <!-- There is no other way to deliver filename that was under processing.
           See https://github.com/checkstyle/checkstyle/issues/2285-->
      <property name="violationSuppressXPath" value="//MethodDeclaration[@Name='processFiles' and ../../..[@Image='Checker']]"/>
    </properties>
  </rule>
  ````
Suppressions for ParameterNumber (ExcessiveParameterList)
````xml
    <suppress checks="ParameterNumber"
              files="LocalizedMessage.java"
              lines="105, 143, 174"/>
````
I can correct Codacy's configuration
https://github.com/codacy/codacy-pmdjava/blob/master/src/main/resources/docs/patterns.json

**Comment by romani** [comment]
> Should be applied

ok, please redo commits to keep only this commit in PR.

**Comment by MEZk** [comment]
@romani 
>please redo commits to keep only this commit in PR.

Done.
Please, export and send me Codacy configuration in json-format, because I have problems importing default configuration from their github repository into my test Codacy account.
https://github.com/codacy/codacy-pmdjava/blob/master/src/main/resources/docs/patterns.json

**Comment by romani** [comment]
> Please, export and send me Codacy'c configuration which is used for Checkstyle in json-format

[codacy-conf.json.txt](https://github.com/checkstyle/checkstyle/files/223741/codacy-conf.json.txt)

**Pull request merged**
