### PR TITLE
Issue #12333: Resolve pitest for profile metrics

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #12333: Resolve pitest for profile metrics
part of https://github.com/checkstyle/checkstyle/issues/12341

### CODE REVIEW

**Comment by Kevin222004** [comment]
https://kevin222004.github.io/JAVANCSS/com.puppycrawl.tools.checkstyle.checks.metrics/JavaNCSSCheck.java.html

**Review by romani — APPROVED** [review]
ok to merge

**Comment by romani** [comment]
Travis was failing on:
>git clone --depth=50 https://github.com/checkstyle/checkstyle.git checkstyle/checkstyle
Cloning into 'checkstyle/checkstyle'...
fatal: unable to access 'https://github.com/checkstyle/checkstyle.git/': GnuTLS recv error (-54): Error in the pull function.

restarted.

**Review by nrmancuso — APPROVED** [review]
Five mutations killed with one test, awesome. Thanks a lot @Kevin222004!

**Comment by nrmancuso** [comment]
> Travis was failing on:
> 
> > git clone --depth=50 https://github.com/checkstyle/checkstyle.git checkstyle/checkstyle
> > Cloning into 'checkstyle/checkstyle'...
> > fatal: unable to access 'https://github.com/checkstyle/checkstyle.git/': GnuTLS recv error (-54): Error in the pull function.
> 
> restarted.

Failure is repeated, let's not let Travis block this PR.

**Pull request merged**
