### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by romani**
update:
PR is created by service.
https://crowdin.com/project/checkstyle
https://github.com/checkstyle/checkstyle/issues/6191

### CODE REVIEW

**Comment by rnveach** [comment]
> I don't see value in comments saying "Generated by XYZ".

Crowdin is removing the excess comments. I am ok with this unless it will also remove good comments, which I haven't seen any yet.
https://github.com/checkstyle/checkstyle/pull/10854/files#diff-2a02f5710802416f739e19a5922b6effea7625513efbffbeed748afe81c8aabcL1
> -#Generated by ResourceBundle Editor (http://eclipse-rbe.sourceforge.net)

> merging lines to make them excessively long
> is it a showstopper for introducing crowdin

I am more on the yes side for this issue. I do see value for the tool, but we need to be able to have some way to configure it from doing bad behavior.

**Comment by romani** [comment]
original message is wrong and should be fixed, see details - https://github.com/checkstyle/checkstyle/issues/6191#issuecomment-939493707

**Comment by strkkk** [comment]
FYI I cancelled all remaining drone builds because it takes too long (it runs build for every commit, but in this PR there are too many commits) and blocks other PRs

**Comment by strkkk** [comment]
@romani @rnveach about line wrappers - I asked support about it and got response
```
Dear Andrey,

Just want to say that we have created a task for our developers and they will do their best to improve the export of your .properties strings with line wrappers.
``` 
So at the moment there is no good way to do that

**Comment by rnveach** [comment]
This means all lines will be wrapped now for anything that goes above those limits?

**Comment by romani** [comment]
I need help to complete this PR.

**Comment by strkkk** [comment]
Crowdin responded that we can "change translations with wrapping" on our side, but it doesn't help imo since next time same translation will appear in diff

**Comment by strkkk** [comment]
@romani @rnveach I suggest to close this PR and delete branch, in this case crowdin will submit a new PR with diff that is left

**Comment by romani** [comment]
done

**Comment by rnveach** [comment]
@strkkk I have not seen a new PR created by crowdin.

**Pull request closed without merging**
