### PR TITLE
Issue #3323: added try-with-resources to RedundantModifierCheck

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3323 

Regression to come.

### CODE REVIEW

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/72/

All are new violations. I didn't see any that were wrong.

**Comment by rnveach** [comment]
I can't see the results for why wercker failed.
TC failure is the same as master.

**Comment by rnveach** [comment]
wrecker failure is regression failed in Orekit.
@romani 
1)
if your ok with change, I will do a PR to OREKIT to fix their issue.
2)
Wrecker ran on commit:
````
Cloning into 'Orekit'...
Note: checking out '942785a5c79b5470baec3d41cab18f3adc78280e'.
````
but [regression file ](https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L25) is for specifies `bc527a1` which is a year old. Need to be updated?
This is why my reports say no regression problems for orekit.

**Comment by romani** [comment]
> but regression file is for specifies bc527a1 which is a year old. Need to be updated?

yes, please.

> if your ok with change, I will do a PR to OREKIT to fix their issue.

yes, please do PR. Your fix is good.

**Comment by rnveach** [comment]
PR in Orekit created, waiting for their response.

**Comment by romani** [comment]
we could create fork again and fix the problem in our fork.
Please let me know when you think we should do this, to not be blocked by another project.

**Comment by rnveach** [comment]
@romani lets go ahead and create fork.

**Comment by romani** [comment]
forked version or Orekit is used.
fix is merged as FF.

**Pull request closed without merging**
