### PR TITLE
Issue #13038: Add token type parameter to isZeroDistanceToken method …

### PR DESCRIPTION
**Pull request by pymoura**
Solves Issue: #13038 - VariableDeclarationUsageDistanceCheck doesn't handle method definition properly

I added the test to verify that example described on the issue has been resolved, and distance count is 1, not 3: testVariableDeclarationUsageDistanceMethodDefinition()

Diff Regression config: https://gist.githubusercontent.com/pymoura/34e69e4da66d31b4751462ec3a866d6a/raw/25208446eda1fb6da7e8cab78d7d326eb17a9677/config_check.xml

### CODE REVIEW

**Comment by romani** [comment]
Github, generate report

**Review by jxr98 — CHANGES_REQUESTED** [review]
Did you try to add a case for method definition in function `calculateDistanceBetweenScopes()` instead of adding the zero-distance tokens? I think modifying code in that function would be a better approach than adding more zero-distance tokens.

**Comment by pymoura** [comment]
Hi @romani and @jxr98, could you take a look on the code, please? 
I added a case for class and method definition in function calculateDistanceBetweenScopes() and removed some token types from zero-distance.

@romani I'm not sure if this corrects the violation that it create before. If not, could  you help me to understand how I can fix it, please?

Thanks!

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
@pymoura , please as you finish code changes and push them, please do same separate comment in PR as  I did and will trigger automatic diff testing .
You can review results yourself to see where is still a gap

**Comment by pymoura** [comment]
Github, generate report

**Review by romani — CHANGES_REQUESTED** [review]
I worried on changes like:
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/fff0dba_2023203746/reports/diff/openjdk17/index.html#A5
And there are cases where distance becomes bigger than it was before.

They are reflected in our Inputs, and detected only by diff report.
This is not good. Please copy such cases to our Inputs.
I do not say that they are problems, but might need to come back to more precise calculations so such cases will be good to have.

**Comment by romani** [comment]
@jxr98, can you help us to review this PR and share your vision.

**Comment by jxr98** [comment]
Hi Romani, I would love to help review and contribute code to checkstyle.

**Comment by jxr98** [comment]
Hi @pymoura. Thanks for your help with this issue.
1. Could u plz rebase your commits. Ideally, we only want 1 commit in 1 pull request. 
2. Assigning the last child to variable `exprWithVariableUsage` in `CLASS_DEF` and `METHOD_DEF` cases doesn't seem to solve the problem. Plz take a look at the diff report [a](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/fff0dba_2023203746/reports/diff/spoon/xref/home/runner/work/checkstyle/checkstyle/.ci-temp/contribution/checkstyle-tester/repositories/spoon/src/main/java/spoon/reflect/visitor/ImportCleaner.java.html#L308), [b](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/fff0dba_2023203746/reports/diff/openjdk17/xref/home/runner/work/checkstyle/checkstyle/.ci-temp/contribution/checkstyle-tester/repositories/openjdk17/test/langtools/tools/javac/api/TestGetScopeResult.java.html#L662) and [c](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/fff0dba_2023203746/reports/diff/checkstyle/xref/home/runner/work/checkstyle/checkstyle/.ci-temp/contribution/checkstyle-tester/repositories/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral4.java.html#L26). From my point of view, when the first usage of a variable is in a method definition within a inner class or anonymous class, the distance should be distance(between variable definition and class definition) + 1. In addition, [this](https://checkstyle.org/writingchecks.html#Printing_a_Java_tree_structure) is the link to how to generate an AST using checkstyle. It may be helpful for this issue.

**Comment by jxr98** [comment]
Hi @pymoura, are u still working on this pr?

**Comment by pymoura** [comment]
Hi @jxr98, sorry it took me so long to reply - I got busy with work and end of quarter at school.  I would like to keep working on this pr during summer break, if it's okay.

**Comment by rnveach** [comment]
Needs to be rebased. CI needs to green.

**Comment by romani** [comment]
if no activity before  1 october , we will close PR to let somebody else to finish this update by reusage of this code

**Pull request closed without merging**
