### PR TITLE
FinalLocalVariableCheck does not check for loop Variable

### LINKED ISSUE #20: FinalLocalVariable does not check for loop variable
assigned to Bhavik Patel  by mail-list at 18 Jan 2015.

Created: 2013-02-12
Creator: Nathan 
SF: #sf695

Checkstyle version: 5.6
Check: http://checkstyle.sourceforge.net/config_coding.html#FinalLocalVariable

With FinalLocalVariable enabled, checkstyle does not complain about following code:
```
for (String s : new String[] {"A", "B", "C"}) {
System.out.println(s);
}
```
Should require:
```
for (final String s : new String[] {"A", "B", "C"}) {
System.out.println(s);
}
```

### PR DESCRIPTION
**Pull request by Bhavik3**
Fixes #20 

look at this comment only. All other previous comments are reverted.

https://github.com/Bhavik3/checkstyle/commit/92f392623197355319de1b6c8cc8b5d532b424da

### CODE REVIEW

**Comment by rdiachenko** [comment]
@Bhavik3 please squash your 4 commits into one

**Comment by Bhavik3** [comment]
commit i mentioned above is only responsible commit for merge. all other are just reverting of previous commit.
so just look at that commit.

**Comment by rdiachenko** [comment]
@Bhavik3 we can't merge just one special commit. You should squash them all into one on your side otherwise they all will be merged and present in the git history which is not what we want.

Here you can find some information about how to do squash: <a href="https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/">Git: Squash your latests commits into one</a>

**Comment by rdiachenko** [comment]
One more note:
>> Coverage decreased (-0.0%) to 89.9%

Coverage should not be decreased. Please update unit tests as well

**Comment by Bhavik3** [comment]
ya I have noted that. coverage decreased on FinalLocalVariableCheck. but i
don't understand as i have just removed one line. I don't know which unit
tests are left.
Anyways, I will have a look over it.

**Pull request closed without merging**
