### PR TITLE
minor: Updated Inputs for LeftCurlyCheck

### PR DESCRIPTION
**Pull request by MUzairS15**
Added Inputs with emoji

### CODE REVIEW

**Comment by nick-mancuso** [comment]
Check requires update, we do not need to close/ open new PRs for each check, you can just edit the PR title and description accordingly.

```
➜  java javac Test.java
➜  java cat Test.java
public class Test {
    void method1()
    /* 😊*/ { }
    void method2()
    { }
}
➜  java cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="LeftCurly">
        </module>
    </module>
</module>
➜  java java -jar checkstyle-10.0-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/nick/IdeaProjects/Tester/src/main/java/Test.java:5:5: '{' at column 5 should be on the previous line. [LeftCurly]
Audit done.
Checkstyle ends with 1 errors.


```

**Comment by MUzairS15** [comment]
Thanks for reporting @nick-mancuso, still not getting why it didn't show me🤔

**Comment by nick-mancuso** [comment]
> Thanks for reporting @nick-mancuso, still not getting why it didn't show me🤔

I should’ve made comments above more clear, my edit was to show that I made a mistake, and that it is existing behavior of check is the same with and without emoji in the comment. In my first example, I failed to place a comment in front of the curly braces. The comment in front of the curly braces is what is causing the check to miss the violation, not the emoji in it.


So, we have existing bug in check, and we can just update test inputs and make an issue if there isn’t one already.

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
Please create issue

**Pull request merged**
