### PR TITLE
Issue #9142: resolve Assertions.fail

### PR DESCRIPTION
**Pull request by rnveach**
Issue #9142

Attempting to work smarter than harder. Created and used a mass-regexp replacer to do this.

I looked over everything once.

### CODE REVIEW

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
TC failure:
```
src/test/java/com/puppycrawl/tools/checkstyle/utils
CheckUtilTest.java (1)
397: getNode() Optional.get() without 'isPresent()' check

```

**Comment by rnveach** [comment]
It looks like not all CI checks are compliant with Truth like the junits.
> 397: getNode() Optional.get() without 'isPresent()' check

There is a `isPresent` check but it is part of the failure check.

What is the best way to resolve this?

**Comment by romani** [comment]
@rnveach , keep it on `fail` or play with fancy Optional methods like `return node.ifPresentOrElse()`

**Comment by rnveach** [comment]
Reverted then for someone else to handle. I don't know Optional/lambdas enough to get the other methods it has to work.

**Comment by romani** [comment]
Github, rebase

**Comment by romani** [comment]
I did manual reabse to test rebase action alter on.

**Comment by romani** [comment]
Github, rebase

**Pull request merged**
