### PR TITLE
Issue #2523: Make DetectorOptions as final and immutable

### PR DESCRIPTION
**Pull request by MEZk**
@romani 
I need your advice on how to resolve PMD and IDEA Inspections violations:

PMD:
`
PMD Failure: com.puppycrawl.tools.checkstyle.checks.regexp.DetectorOptions:128 Rule:AccessorClassGeneration Priority:3 Avoid instantiation through private constructors from outside of the constructors class..
`
https://pmd.github.io/pmd-5.4.1/pmd-java/rules/java/design.html#AccessorClassGeneration

IDEA Inspections:
Encapsulation issues - Package-visible inner class (1)
Description: `Reports package-local inner classes. 
Use the first checkbox below to ignore package-local inner enums.
Use the seconds checkbox below to ignore package-local inner interface.
`

Memory issues - Return of instance of anonymous, local or inner class (9)
Description: `Reports return statements returning an instance of an anonymous, local, or inner class. Such instances keep an implicit reference to the outer instance. Which means the instance can prevent the outer instance from being garbage collected. Any caller of a method which returns such an instance might cause a memory leak by holding on to the instance returned.
Use the checkbox below to ignore returns from protected or package-local methods. Returns from private methods are always ignored.
`

```
Encapsulation issues:
DetectorOptions.java (1)
132: Builder Package-visible inner class Builder
```

```
Memory issues:
DetectorOptions.java (9)
128: newBuilder() Return of instance of non-static inner class Builder
144: format() Return of instance of non-static inner class Builder
154: message() Return of instance of non-static inner class Builder
164: minimum() Return of instance of non-static inner class Builder
174: maximum() Return of instance of non-static inner class Builder
184: ignoreCase() Return of instance of non-static inner class Builder
194: reporter() Return of instance of non-static inner class Builder
204: compileFlags() Return of instance of non-static inner class Builder
214: suppressor() Return of instance of non-static inner class Builder
```

### CODE REVIEW

**Comment by romani** [comment]
> Avoid instantiation through private constructors from outside of the constructors class.. 

`Instantiation by way of private constructors from outside of the constructor’s class often causes the generation of an accessor. ` we do this intentionally there as we will use upper instance righaway, this is whole idea of Builder pattern additionally that helps us avoid creation of duplication of upper class fields.
We could suppress it in config, with description.

> 132: Builder Package-visible inner class Builder

I would make it public, but upper class is also package-private. The only way out is make both of them public. I need investigate more about possible problems of "package-visiable inner classes"

> 128: newBuilder() Return of instance of non-static inner class Builder

`Use the checkbox below to ignore returns from protected or package-local methods. `
I think it is reasonable to update Inspection configuration to ignore package-local and change visibility of methods to package-private.
If we decide to make class public and its inner class as public, we need to add suppress javadoc annotation to this class and explain why memory leak will not happen in our case (Builder object is useless on its own, and required only as required object creation).

@mkordas , please share your experience on this topic

**Comment by MEZk** [comment]
@romani 
Updated, please review.

**Comment by romani** [comment]
Please squash commits to ease review

**Comment by MEZk** [comment]
@romani 
Done

**Comment by romani** [comment]
items that I would rather change:

"Encapsulation issues - Package-visible inner class" - can options inspection help us to skip violation?

"Memory issues - Return of instance of anonymous, local or inner class" can options inspection help us to skip violation? could be suppressed by javadoc annotation `@noinspection`

configuration of inspections is here - https://github.com/checkstyle/checkstyle/blob/master/config/intellij-idea-inspections.xml

**Comment by romani** [comment]
closed,  #2697 is merged instead

**Pull request closed without merging**
