### PR TITLE
Issue #13783:  Fixed typo in IndentationCheck for initialization

### PR DESCRIPTION
**Pull request by suniti0804**
Issue #13783 

This PR fixes the typo in IndentationCheck file

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by rnveach** [comment]
https://github.com/search?q=repo%3Acheckstyle%2Fcheckstyle%20initialisation%20&type=code

What about the release notes and messages file?

**Comment by romani** [comment]
Release notes are out of spelling check, there are bunch typos there, we do not care about this past problems.
We do not check spelling on commit messages, so leak of typos is easy to relate notes 

Usage in French translation is not correct match, we change only English.

**Comment by rnveach** [comment]
> Release notes are out of spelling check

Then why do we not disable old release notes for other things?
https://github.com/checkstyle/checkstyle/commits/master/src/xdocs/releasenotes_old_1-0_5-9.xml

**Comment by romani** [comment]
I don't see any violation from spell checker.
Please share link to point to violation.

**Comment by rnveach** [comment]
I am talking about our other checks, like valid links, typos ( https://github.com/checkstyle/checkstyle/commit/3104d1cd7f6b00c2bdc649fa9e644044b2517138 ).

**Comment by romani** [comment]
I don't see much reason, but if you see it, let's do it.

**Review by rnveach — APPROVED** [review]

**Pull request merged**
