### PR TITLE
Issue #7469: Use ArchUnit library to control source code - FreezingRule Experiment

### PR DESCRIPTION
**Pull request by gaurabdg**
#7469 

This experimental PR is the child of #8112 .

@romani Removal of `Class <com.puppycrawl.tools.checkstyle.checks.naming.AbbreviationAsWordInNameCheck> extends class <com.puppycrawl.tools.checkstyle.api.AbstractCheck> in (AbbreviationAsWordInNameCheck.java:0)\` (line 5 of `archunit_store/6822fb17-971a-4a6d-9985-0cef743990a1` in first commit) removes the parent error message `Cycle detected: Slice api -> Slice checks.naming -> Slice api\` (since line 5 is one of the cyclic dependency, so removing it breaks the cycle `Slice api -> Slice checks.naming -> Slice api`) found in the diff and the UT `packageCyclicDependencyTest` fails.

### CODE REVIEW

**Comment by strkkk** [comment]
@gaurabdg ping, what is the status of this code changes?

**Comment by gaurabdg** [comment]
> @gaurabdg ping, what is the status of this code changes?

In progress, waiting for @romani.

**Comment by strkkk** [comment]
@gaurabdg In this case it is better to assign PR to him or ping in gitter, because mentions does not work good now due to huge load

**Comment by gaurabdg** [comment]
> @gaurabdg In this case it is better to assign PR to him or ping in gitter, because mentions does not work good now due to huge load

Yes, discussion is ongoing in the parent PR.

**Comment by romani** [comment]
@gaurabdg , please rebase this PR, lets finish it.

**Comment by gaurabdg** [comment]
> @gaurabdg , please rebase this PR, lets finish it.

done.

**Comment by romani** [comment]
@gaurabdg , please fix commits and make CI happy.

**Comment by gaurabdg** [comment]
@romani This PR is failed on purpose as you wanted to know the diff and whether freezer fails or not https://github.com/checkstyle/checkstyle/pull/8112#discussion_r418574542

**Comment by romani** [comment]
we are not ready to store in git repo dump of some plugin to let it work.

We need somehow change `.should().beFreeOfCycles()` to let us provide cycles that we ok for now.

**Pull request closed without merging**
