### PR TITLE
Issue #4168: Split and Organize Checkstyle inputs by Test for MethodTypeParameterName

### PR DESCRIPTION
**Pull request by janiine**
This PR solves issue #4168

The "InputTypeParameterName.java" test file was copied to the folder "methodtypeparametername" since this two files still use it:
- ClassTypeParameterNameCheckTest
- InterfaceTypeParameterNameCheckTest

### CODE REVIEW

**Comment by Vladlis** [comment]
@janiine 
Please read https://github.com/checkstyle/checkstyle/issues/3891#issue-211193862

> We should start by renaming all inputs to `Input[SimpleTestName].*` ([]s are just for separation and should not be in final file name), that are used by a test. If test is named `ParenPadCheckTest`, simple name would be `ParenPad` and input would start with `InputParenPad`. Any text can be appended to the end to make the input file name unique among others for the same test.

And rename Input file according to this recommendation

**Comment by janiine** [comment]
@Vladlis I already updated the commit. Is there something else I need to do ?

**Comment by Vladlis** [comment]
@janiine 
1. Please reply to each review point which you fix, because we don't get notifications automatically after you push smth. It is point 6 in [PR-rules](https://github.com/checkstyle/checkstyle/wiki/PR-rules).

2. Input file name is still incorrect: you are organizing inputs for `MethodTypeParameterNameCheckTest`, so any input name should be `InputMethodTypeParameterName`+smth else (or nothing)

**Comment by janiine** [comment]
I already updated the commit.

**Pull request merged**
