### PR TITLE
Issue #13086: InnerAssignmentCheck failed for one line code

### PR DESCRIPTION
**Pull request by AayushSaini101**
Related: https://github.com/checkstyle/checkstyle/issues/13086

Diff Regression config: https://gist.githubusercontent.com/AayushSaini101/2db49b2556a5ed7f2df81b3624661c38/raw/d9e6dac89729ca2436edd6506fe76dcbe3feb0cd/gistfile1.txt

### CODE REVIEW

**Comment by AayushSaini101** [comment]
GitHub, generate report

**Comment by romani** [comment]
@AayushSaini101 , we need find a reason why CircleCI is executing under your account
https://app.circleci.com/pipelines/github/AayushSaini101/checkstyle/30/workflows/74e0f0f1-c45e-4537-86c8-4fdd6c7f1732/jobs/1277/steps

but for others under checkstyle org.
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/21161/workflows/2d665e72-dd38-408b-91ad-cfab725a60e0/jobs/399746

is it something you configured during fork or some special steps during PR?
to unblock mere on this PR we need to resolve this issue.

**Comment by AayushSaini101** [comment]
> @AayushSaini101 , we need find a reason why CircleCI is executing under your account https://app.circleci.com/pipelines/github/AayushSaini101/checkstyle/30/workflows/74e0f0f1-c45e-4537-86c8-4fdd6c7f1732/jobs/1277/steps
> 
> but for others under checkstyle org. https://app.circleci.com/pipelines/github/checkstyle/checkstyle/21161/workflows/2d665e72-dd38-408b-91ad-cfab725a60e0/jobs/399746
> 
> is it something you configured during fork or some special steps during PR? to unblock mere on this PR we need to resolve this issue.

No, I haven't configured any kind of config during the fork.

**Comment by romani** [comment]
@AayushSaini101 , please contact circleci CI support, in case it is defect on their side.

**Comment by AayushSaini101** [comment]
> @AayushSaini101 , please contact circleci CI support, in case it is defect on their s

Tried to resolve

**Comment by romani** [comment]
@AayushSaini101 , can you redo PR, to make Ci green?

**Pull request closed without merging**
