### PR TITLE
Empty Line Separator Check, added option for managing empty lines betwee...

### PR DESCRIPTION
**Pull request by alexkravin**
...n class members, issue #530 

Added option <b>allowMultipleEmptyLines</b> for managing empty lines between class members, default value is <b>true</b>.

Added corresponding UT and input file.

### CODE REVIEW

**Comment by romani** [comment]
build is failed.

> // 3 is the number of the pre-previous line because the numbering starts from zero.

need more explanation on this, previous usually mean "-1", pre-previous "-2"

**Comment by alexkravin** [comment]
Corrected build.

About pre-previous line:
it was taken from existing method
https://github.com/checkstyle/checkstyle/blob/378c68fed314bd99ae11acf8a92c03566e34860f/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java#L296

just analyzing previous line from this one.

Seems to be it's the feature of FileContents class from where getLines() is calling
(getLines() is method from Check which calls return getFileContents().getLines();)

**Comment by romani** [comment]
ok, but rename hasEmptyLinesBefore method to be named absolutely reflecting functionality. As "Lines" is not exact, and there is not argument that customize distance before.

**Comment by alexkravin** [comment]
renamed to <b>isPrecededByMoreThanOneEmptyLine</b> "line" is quite exact in this context, we don't need to take care about distance as we're looking for only "> 1 empty lines", so I think it's quite obvious.

**Comment by romani** [comment]
Build is failed.

Please send me link to line in code where you have " ... > 1" or " ... > 2" if lines are indexed from 0.

**Comment by alexkravin** [comment]
https://github.com/alexkravin/checkstyle/blob/4ca50aa2da01ff7477a8d043446aec864a8f435a/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java#L286

Here's checking line after token

https://github.com/alexkravin/checkstyle/blob/4ca50aa2da01ff7477a8d043446aec864a8f435a/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java#L298

Here's checking line before token (only previous line), my method is based on it.

**Comment by romani** [comment]
> Please send me link to line in code where you have " ... > 1" or " ... > 2" if lines are indexed from 0.

I meant in isPrecededByMoreThanOneEmptyLine method. Method named incorrectly.

**Comment by alexkravin** [comment]
generally speaking, this method checks only pre-previous line, in context of Check couple of methods are checking "more than 1 empty line before", so I renamed this method to <b>isPrePreviousLineEmpty</b> because it checks exactly pre-previous line.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
