### PR TITLE
config: enable PMD cache

### PR DESCRIPTION
**Pull request by rnveach**
This commit enables caching on PMD to speed up re-runs.

### CODE REVIEW

**Comment by romani** [comment]
I do not like caches. Possible leak of Bad code will cause more problems.

CI will not benefit from it.
On my local it is pretty quick.

Please explain

**Comment by rnveach** [comment]
Just like we enabled caches for checkstyle, I would like PMD cached too to help speed it up. PMD is not terribly long as checkstyle, but it does took like a minute to complete. It was only to help with running locally.
If you dont wish to make this update, then feel free to close PR.

**Comment by romani** [comment]
>Just like we enabled caches for checkstyle, 

It was ok, as it is testing of our cache.


Let's get second opinion on this, before closing.
@pbludov , please share your opinion.

**Comment by pbludov** [comment]
> @pbludov , please share your opinion.

On my system without PMD cache
```
[INFO] Total time:  29.147 s
[INFO] Finished at: 2019-07-30T10:00:36+03:00

real    0m30,305s
user    3m12,151s
sys     0m3,670s

[INFO] Total time:  29.258 s
[INFO] Finished at: 2019-07-30T10:13:12+03:00

real    0m30,409s
user    3m12,601s
sys     0m3,661s
```

with PMD cache enabled:
```
[INFO] Total time:  5.152 s
[INFO] Finished at: 2019-07-30T10:25:32+03:00

real    0m6,415s
user    0m28,622s
sys     0m0,745s

[INFO] Total time:  5.468 s
[INFO] Finished at: 2019-07-30T10:25:52+03:00

real    0m6,615s
user    0m30,466s
sys     0m0,714s
```

About five times faster. I vote for the cache. Since this does not affect the CI, if there are any problems with the cache, we will know it immediately.

**Comment by rnveach** [comment]
PMD recognizes when it's version changes:
> [INFO] Analysis cache invalidated, PMD version changed.
[INFO] Analysis cache invalidated, rulesets changed.
[INFO] Analysis cache updated
[INFO] 
[INFO] <<< maven-pmd-plugin:3.12.0:check (default) < :pmd @ checkstyle <<<

**Pull request merged**
