### PR TITLE
Sections of code should not be "commented out". Issue #46

### PR DESCRIPTION
**Pull request by sabaka**

### CODE REVIEW

**Comment by sabaka** [comment]
@romani what should I do with examples of code in comments? I wanted to remove them at first, but it can be useful sometimes.

**Comment by romani** [comment]
1)
>     /* * token representing a NULL_TREE_LOOKAHEAD */
    /* * token representing a BLOCK */
    /* * token representing a VOCAB */

What is a point to keep that in code ?

2) 
> SuppressWarningsCheck.java
> RightCurlyCheck.java

please move that in separate PR, we will merge that later. We need to ask Sonar team how to escape code in comment to avoid violation. We need code there. Please open discussion thread on their mail-list with link to PR for that files

**Comment by sabaka** [comment]
1) I thought it might be useful, but now I don't
2) #1774. https://groups.google.com/forum/#!topic/sonarqube/e5xnjMxnz04

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
