### PR TITLE
Added anchors to sections, issue #586

### PR DESCRIPTION
**Pull request by alexkravin**
According to #586 

Added anchors to each section on each site's page.

http://alexkravin.github.io/anchors/index.html

### CODE REVIEW

**Comment by mkordas** [comment]
They don't look centered:
image

I think it's because image itself isn't centered.

**Comment by romani** [comment]
image should appear on the right side of text, text should not shake on mouse over event.

I need detailed explanation why linkimage does not work for subsections.

**Comment by alexkravin** [comment]
screen
Updated image (centered)
Ok, let it be on the right side, current version: http://alexkravin.github.io/anchors/index.html

```
I need detailed explanation why linkimage does not work for subsections.
```

See my comment in issue

**Comment by alexkravin** [comment]
I do not know how to make link image after the text, so now it's done via hack by js))
http://alexkravin.github.io/anchors/config_annotation.html

**Comment by mkordas** [comment]
Remember about different resolutions - on my machine it looks like that:
image
And it is still not centered.

**Comment by romani** [comment]
I could agree on non aligned to center by vertical, but image have to appear right after text .

**Comment by alexkravin** [comment]
Updated
http://alexkravin.github.io/anchors/config_annotation.html

**Comment by romani** [comment]
good job, please apply to alll pages , and please rebase on latest code.

**Comment by alexkravin** [comment]
Rebased on latest sources

```
please apply to alll pages
```

It's already applied

**Comment by alexkravin** [comment]
Issue on maven-site-plugin due to impossibility of normal subsections reference:
http://jira.codehaus.org/browse/MSITE-741

**Comment by mkordas** [comment]
For me the anchors are too close to text and still they are not centered. Just compare these two:
image
image

**Pull request merged**
