### PR TITLE
Issue #407: Fix cache usage in presence of modules which use external resources for configuration

### PR DESCRIPTION
**Pull request by MEZk**
#407 

**Solution to #407 issue. Part 1.**

Questions that should be discussed:

1) Where should we load external resources by their URIs to calculate SHA-1 cache sum? In PropertyCacheFile?
2) Where and how we should treat exceptions if it is not possible to create URI for resource. See failded tests.
3) What default implementation should we use for method 'getExternalResources'?
Suggestions:

```java
public List<URI> getExternalResources() {
    return Collections.EMPTY_LIST;
}
```

or

```java
public Optional<List<URI>>getExternalResources() {
    return Optional.absence();
}
```

Both first and second implementation require null check in Checker, because we do not know whether user will follow the rule and return non null reference.

4) How can we be sure that user will invoke 'super.getExternalResources' , for example, in HeaderCheck and will give information about the header file (from AbstractHeaderCheck) in Checker?

### CODE REVIEW

**Comment by romani** [comment]
> Where should we load external resources by their URIs to calculate SHA-1 cache sum? In PropertyCacheFile?

No, method of PropertyCacheFile should be made public, and Checker do class of this merhod.

> 2) Where and how we should treat exceptions if it is not possible to create URI for resource. See failded tests.

if exception happen, we need to return hardcoded checksum value "##NOT_AVAILABLE##" and use it.
WE should not fail fast here. Lets check/filter to fail with most likely better message and context for user. Cache processing shallow exceptions in worst case cache is invalidated.

> 3) What default implementation should we use for method 'getExternalResources'?

No Guava in our API. Lets keep it depend only on JDK.

> 4) How can we be sure that user will invoke 'super.getExternalResources' , for example, in HeaderCheck and will give information about the header file (from AbstractHeaderCheck) in Checker? 

We can not be sure, as we can not be sure in any custom Check logic. It is ok.

**Comment by romani** [comment]
> Use DatatypeConverter#printHexBinary to convert byte 

please move to separate PR. it is not functional changes, lets merge them sooner and separately. In PR please make ref to PR not a issue (it is unrelated to issue).

**Comment by MEZk** [comment]
@romani 
>please move to separate PR. it is not functional changes, lets merge them sooner and separately. In PR please make ref to PR not a issue (it is unrelated to issue).

Done. https://github.com/checkstyle/checkstyle/pull/3093

**Comment by MEZk** [comment]
@romani 
>I do like this, most of Checks and Filters do not have external resources. but we force all of them to care about ExternalResourceHolder.
Please provide statistic of external file usage for all FileSetCheck/AstChecks/Filters grouped by type.
I think we need to put such interface only special classes.

**FileSetChecks (those which implement FileSetCheck interface)**

1) AbstractHeaderCheck holds the header file.
2) HeaderCheck (inheritor of AbstractHeaderCheck) can set the header file.
3)  RegexpHeaderCheck (inheritor of AbstractHeaderCheck) can set the header file.

**AstChecks (AbstractCheck inheritors)**
1) ImportControlCheck can set the name for the file containing the import control
configuration.

**Filters (those which implement Filter interface)**
1) SuppressionFilter can set the file name of supression file.

**Comment by MEZk** [comment]
@romani 
Take a look at 'testExternalConfigurationResourceDoesNotExist' from CheckerTest. If resource does not exist there will be the following exception:
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: non_existing_external_resource.xml
```
After the first run with cache, SHA-1 of the exception object will be: 
```
A6293AA3E263D8B1F85940BF3B5F4E8CA0131157
```
And after the second run: 
```
877725F6CDE5267AF4E3032F2E390F544FECB18F
```

Looks like the content of exception object was changed after the first run, nevertheless the exception message remained the same. That is why we cannon calculate SHA-1 hash sum based on exception object's content in case exception is happened while loading the external resource.

**Comment by romani** [comment]
1)
> invalidate.....

methods with such names should do only clear for cache, your methods do everything. Change the name.

2)
> That is why we cannon calculate SHA-1 hash sum based on exception object's content in case exception is happened while loading the external resource.

it also mean that we can not use this algorithm at all, we need stable checksum result base on content.
please try to use "MessageDigest md = MessageDigest.getInstance("MD5");"
or please use primitive "sum of chars" algorithm for now to make all UTs pass. Substitution of algorithm could be second step.

3)
For all updated Checks. Please keep in Check fields only user defined values. Create a collection only in `getExternalResourceLocations()`

**Comment by MEZk** [comment]
1) Done. Are you ok with the method 'invalidateCache' ?

2) Both SHA-1 and MD5 algorithms work fine when content of the file is not changed and when it is changed. What I meant was that the content of exception as a Java object could be changed. For example, hashCode, etc. That is why when hash sum of exception was calculated twice it was different for two exception objects.

3) Done.

**Comment by romani** [comment]
Can you share with me stacktrace that has unstable content? You showed we stable exception that give different codes.

**Comment by romani** [comment]
> 1) Done. Are you ok with the method 'invalidateCache' ?

NO.

```
     * Puts external resource of the module in cache if it has not been cached yet, or clears
     * cache if external resource of the module has been changed.
     * @param resource resource location.
     */
    private void invalidateCache(String resource) {
```

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=invalidate

"Puts external resource of the module in cache ..."
"invalidateCache"
"invalidate - make (an argument, statement, or theory) unsound or erroneous."
Where is logic ?

name a method exactly as what it doing.

**Comment by MEZk** [comment]
@romani 
>Can you share with me stacktrace that has unstable content? You showed we stable exception that give different codes.

UT 'testExternalConfigurationResourceDoesNotExist' :
Left side - first run of verify method, right side - second run of verify method.
https://www.diffchecker.com/jqw2uckj
As you can see, both stack traces are equal apart from the line where method verify was invoked.

Hash codes of exceptions:
1) 521960438
2) 1125381564
So, my assumption was confirmed. The representation of the exception objects in memory was changed between first and second run of verify method.

**Comment by MEZk** [comment]
@romani 
Further investigation

Diff in byte representation of exception objects between two runs:
https://www.diffchecker.com/1cpzh8b5

As you can see, binary representation of two exception objects are similar except for 1 value. I think the binary value represents the line number in stack trace where exception was happened. So, first exception 

```at com.puppycrawl.tools.checkstyle.CheckerTest.testExternalConfigurationResourceDoesNotExist(CheckerTest.java:726)```

second one

```at com.puppycrawl.tools.checkstyle.CheckerTest.testExternalConfigurationResourceDoesNotExist(CheckerTest.java:728)```

Therefore, SHA-1 algorithm works ok. The problem with different hash sums is caused by UT's structure. We need to find a way to test the situation where exception is happened thourgh the UT on the same line.

**Comment by romani** [comment]
> The solution lies in the reorganisation of UT

exactly. If code works fine and UT has a problems, UT need to be changed/hacked/refactored to work fine.

**Comment by romani** [comment]
1)
> processExternalConfigurationResources();

this method is not part of ` private void processFiles(List<File> files)`. It is part of configuration validation and invalidation of cache.
Put it to ` public int process(List<File> files) throws CheckstyleException `

2)
processExternalConfigurationResources --> processModuleExternalConfigurationResources --> putResourceInCacheOrClearCache

naming problem == design problem.
putResourceInCacheOrClearCache do to much, and process configs incorrectly. Case: first config is matching, second is changed, third is matched. In your implementation cache, first cofig will not be present !!!!! please make a UT for this.

You need to have code like:
if (areExtrnalResourcesChanged()) {
  //invalidate cache
  cache.clear();
 // fill cache with new resources
 fillCacheWithExternalResources();
}

3)
>
```
                if (resource == null) {
                    continue;
                }
```

please avoid this, as you create scope "if () {}"  you can put there body of loop.

4)
> public static String getConfigHashCode(Serializable object) {

as you make it public pay attention to a name .
why method is config focused ?

**Comment by romani** [comment]
@MEZk , ping.

**Comment by MEZk** [comment]
@romani 
I'm working on it, but unfortunately, do not have enough time.

**Comment by MEZk** [comment]
@romani 
1) The method was removed. The part of its content was put into 'process' method.
2) Done. See ```CheckerTest#testMultipleConfigs.```
3) Done.
4) Renamed.

>Why name "processExternalConfigurationResources" does not have Cache. It is his main reason to invalidate a cache or fill it with checksum.

The method was removed.

>Why you requesting external resources even cache is NULL (not defined by user, not required) ?
"if (cache != null) {" should be in "process" to looks similar to "destroy".

Done.

**Comment by MEZk** [comment]
@romani 
Codacy is not happy, but is it ok to refactor test classes to avoid code duplications in, for example CheckerTest ?

**Comment by romani** [comment]
yes, please do update to avoid code duplication.

**Comment by MEZk** [comment]
@romani 
Done.

**Comment by MEZk** [comment]
Rebased

**Comment by romani** [comment]
1)
>
```
                final List<String> locations =
                   ((ExternalResourceHolder) check).getExternalResourceLocations();
                if (locations != null) {
```

As we return List, we need check it for empty. 
In documentation we need to mention that we expect no-empty list, return of null by Check will cause NPE -  it is ok. Check is designed incorrectly.
If it is empty - why check implement this Interface ?
I think throw of exception is ok here to force use fix Check implementation.

2)
>
```
        for (String location : resourceLocations) {
            if (location != null) {
```

Do we really need check for null there ? User's Check could cause NPE even by simply throwing it from its code. Here null means incorrect configuration/implementation of Check - we should stop execution and force user to fix problem.

3)
> 
```
                catch (CheckstyleException ex) {
                    contentHashSum = PropertyCacheFile.getHashCodeBasedOnObjectContent(ex);
```

please put comment here why we do hashsum base on exception

4)
>
```
            int next = resourceReader.read();
            while (next > -1) {
```
https://docs.oracle.com/javase/7/docs/api/java/io/InputStreamReader.html#read%28%29
"-1" the only special value, so please make your condition strict "next != -1".

5)
>
```
    public List<String> getExternalResourceLocations() {
        final List<String> externalResources = new ArrayList<>(1);
        externalResources.add(fileLocation);
        return externalResources;
    }
```
I think it will be more readable in a format of
http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/ImmutableList.html#of%28E%29

6)
> writingjavadocchecks.xml.vm, writingfilters.xml

please avoid copy-paste , please keep chapter but in content make a link to  writingchecks.xml  content.

**Comment by MEZk** [comment]
1) Done, but there is a problem with the implementation of ExternalResourceHolder in TreeWalker. If there are not inheritors of AbstractCheck which implement ExternalResourceHolder, 'getExternalResourcesLocations' in TreeWalker will return an empty list to Checker and it will cause an exception in Checker. 
Suggestions:
-  We can check whether the list of external resource locations which is returned by AbstractCheck's inheritor in TreeWalker is empty and fail fast. In Checker we should check whether TreeWalker return an empty list and do not throw an exception. 
- We can skip empty lists in Checker and fail only if there is a null in list or list is referenced null.

testCacheFileChangeInConfig, testCacheFile, testCacheFileChangeInConfig now are failed due to the problem which is mentioned above.

What is your opinion?

2) Done.
3) Done.
4) Done.
5) Done for all modules which implement ExternalResourceHolder interface.
6) Done.

**Comment by romani** [comment]
1)
> What is your opinion?

I forgot about composite modules like Treewalker, lets allow empty lists.
But please update javadoc to warn user to that empty list make sense only for composite modules like TreeWalker.

2)
>          catch (NullPointerException ex) {

Never catch NPE.
Not sure why this Check did not stop you 
https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_sevntu_checks.xml#L32

**Comment by MEZk** [comment]
1) Done.
2) Deleted NPE tests. There is no need in their implementation. NPE which might happen in Checker is mentioned in documentation.

>Not sure why this Check did not stop you 

ForbidInstantiationCheck from SevNTU Checkstyle checks import directives and LITERAL_NEW tokens. See its [visitToken](https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/8f4ac566efe1e697207e8f202993b715cb5ed109/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidInstantiationCheck.java#L104) method.  NullPointerException class is a part of java.lang package. All classes in the java.lang package are imported by default. Thus we do not need to import java.lang.*; to use them without fully qualified names. So,  ForbidInstantiationCheck can not trigger such cases.

**Comment by romani** [comment]
>  So, ForbidInstantiationCheck can not trigger such cases.

thanks a lot. I did enforcement of this by 
https://github.com/checkstyle/checkstyle/commit/4c42b6abbe468576af41bf559d09cb0b5a8f2131

**Comment by MEZk** [comment]
@romani 
Build was fixed.

**Comment by romani** [comment]
thanks a lot, please squash all 3 in one to ease codeview.

**Comment by MEZk** [comment]
@romani 
Done.

**Comment by romani** [comment]
I am ok.

@rnveach , can do code review for this update. I and MEZk are pretty blind already.
As you give approval, I will merge this PR.

**Comment by rnveach** [comment]
@romani Feel free to accept or reject my suggestions. I don't really see anything big that would be an issue.

(1)
How about have `Checker` implement `ExternalResourceHolder` and we change `Checker.getExternalConfigurationResources` in to `getExternalResourceLocations` and call `loadExternalResources` inside `Checker.process`?
This way the chain goes all the way up and utilities have access to it for whatever they may need, if they have the `Checker` instance.

(2)
````
            int next = resourceReader.read();
            while (next != -1) {
                outputStream.write(next);
                next = resourceReader.read();
            }
````
Why one byte at a time? Why not read and write an array of bytes?
I doubt we'll read big files for this to be a serious performance issue.

(3)
Inside `areExternalResourcesChanged`:
`if (cache.isInCache(resource.location)) {`

It is not a big deal there is no else, but if a check with an external resource changed file locations and kept the same check and checker instance, `areExternalResourcesChanged` would return false since the new file location isn't in the cache from the previous run. It should return true in this scenario, and clear the cache.
I assume utilities usually create a whole new `Checker` instance, but I am talking about the scenario where it doesn't because it has direct access to all the required instances.

(4)
`loadResourceContent`

Javadoc and exception message says `external`. Why not make method name `loadExternalResourceContent` or `loadExternalResource` (content seems implied to me by the name 'load')?
Almost every other new method in the class has 'external' in it.

(5)
`getChecksResourceLocations(Set<AbstractCheck> checks)`

Why not make it an overloaded method and rename it to `getExternalResourceLocations`?

**Comment by MEZk** [comment]
@rnveach 
Thanks a lot for your review!

2) Good point. You are absolutely right. Didn't catch it.
3) Hm, I'll investigate this suggestion further.
4) Agree.
5) Agree.

**Comment by romani** [comment]
> (1) How about have Checker implement ExternalResourceHolder and we change Checker.getExternalConfigurationResources in to getExternalResourceLocations and call loadExternalResources inside Checker.process?

good point but ..... If we do not need to extend/implement smth - we should not do this now.
Right now no demand for this, so lets postpone it (right now this method is private, by interface implementation it will be public - kind of new contract with users).

 > (2)

Good point.

> (3) ..... It is not a big deal there is no else, but if a check with an external resource changed file locations and kept the same check and checker instance

This is bug :) . there should be `else {changed = true; break;}`
Use case: Imagine that cache exists in a file. New version of Checkstyle appear. New release contains update to a some Check to have additional external resource.  User update his configuration and run validation as usually. Cache will be reused, but it should not.
We need UT on this.

> (4)

make sense.

> (5)

make sense.

**Comment by MEZk** [comment]
@romani, @rnveach 
2) Done
3) Done
4) Done and also I've added UT (testCheckAddsNewResourceLocationButKeepsSameCheckerInstance) 
5) Done

**Comment by romani** [comment]
1)
> Checker invalidates cache, setup configuration, and starts analysis. 
....
private static final int BUFFER_SIZE = 1024;

No, we need to move cache out of Checker , it become too big, too much methods and unrelated to Checker fields about cache processing.
PropertyCacheFile might be good candidate for all that methods.

2) 
> private boolean areExternalResourcesChanged(List<ExternalResource> resources) 

Looks like we discussed in gitter this method implementation. Do you think that such form is better than "guava" styled ?

3)
> List<String> getExternalResourceLocations();

I do not know why we selected a List here ...... It should be a Set, to show user that unique elements are expected. It does not hurt to keep List, as amount of elements will be minimal always.
What do you think about this ?

-------

@rnveach , please review the code.

**Comment by rnveach** [comment]
`public void put(String resourceLocation, String hasSum) {`

Should be `hashSum`.

(1) sounds good.
(3) `Set` sounds fine with me.

I don't really see anything else wrong.

**Comment by MEZk** [comment]
@romani 
Why PropertyCacheFile should know anything about Checkstyle modules? If we move, for example, getExternalConfigurationResources there it will mean that PropertyCacheFile take care of each Checkstyle's module, but I think that its idea is to create and process cache.

**Comment by romani** [comment]
>Why PropertyCacheFile should know anything about Checkstyle modules?

Sure it should not, but moving all is possible but will require minor refactoing for signature of one method.
Think about this during weekend find me in gitter if you fail to resolve

**Comment by rnveach** [comment]
@MEZk 
What about have `PropertyCacheFile` receive `ExternalResourceHolder`s?

`Checker.getExternalConfigurationResources` should stay where it is but either return `Set<ExternalResourceHolder>` or a list of locations `Set<String>`.
In `Checker.process` call `cache.analyzeExternalResources(getExternalConfigurationResources())` and have it do the clear inside that method. All checker is doing is sending it the files, no clear or examine of cache.
To keep the list of the external hashes, either use a temporary map or move the inner class to inside `PropertyCacheFile`.

This sound good?

**Comment by MEZk** [comment]
@romani 
2)
>Looks like we discussed in gitter this method implementation. Do you think that such form is better than "guava" styled ?

Done as discussed.

3) Done.

@rnveach 

>In Checker.process call cache.analyzeExternalResources(getExternalConfigurationResources()) and have it do the clear inside that method. All checker is doing is sending it the files, no clear or examine of cache.

Done.

>All other methods should still be moved inside PropertyCacheFile.
To keep the list of the external hashes, either use a temporary map or move the inner class to inside PropertyCacheFile.

Done.

>Maybe call them master/global files in PropertyCacheFile instead of external.

The names do not sound good to me.

>What about have PropertyCacheFile receive ExternalResourceHolders?

Hm, maybe it is a good idea, but  as you said:

>How about have Checker implement ExternalResourceHolder and we change Checker.getExternalConfigurationResources in to getExternalResourceLocations and call loadExternalResources inside Checker.process?
This way the chain goes all the way up and utilities have access to it for whatever they may need, if they have the Checker instance.

It might be reasonable to keep getExternalResourceLocations signature for future improvements.

**Comment by romani** [comment]
@MEZk ,

0)
CIs need to be green.

1)
> 
-    private static String getConfigHashCode(Serializable object) {
+    public static String getHashCodeBasedOnObjectContent(Serializable object) {

not clear why private --> public .

2)
>  public void analyzeExternalResources(Set<String> locations) {

"analyze", look at method body. All it do is just to "fill" cache, "clean" before "fill" is just a nuance that does not mater on this level.  There are another method "put" for files, so lets use name "putExternalResources".

**Comment by MEZk** [comment]
@romani 
0) Done
1) Made private
2) Renamed (analyzeExternalResources-->putExternalResources).

**Comment by romani** [comment]
@MEZk , no more items to fix we are good to merge.

thank you very much !!!!  Merged.

**Pull request merged**
