### PR TITLE
Issue #14970: PatternVariableName should allow unnamed variables by d…

### LINKED ISSUE #14970: Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: PatternVariableName
child of #14942 
I have read check documentation: https://checkstyle.org/checks/naming/patternvariablename.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
record Point(int x, int y) { }
record square(Point upperLeft, Point lowerRight) { }

public class PatternVariables {
    void method(Object obj) {
        if (obj instanceof square(Point(int _, int y), _)) {  // violation
            System.out.println(y);
        }
    }
}
PS D:\CS\test> cat config.xml                                                                                
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
 <module name="TreeWalker">
    <module name="PatternVariableName">
    </module>
 </module>
</module>
PS D:\CS\test> java  -jar checkstyle-10.14.2-all.jar -c config.xml  src/PatternVariables.java                
Starting audit...
[ERROR] D:\CS\test\src\PatternVariables.java:6:45: Name '_' must match pattern '^[a-z][a-zA-Z0-9]*$'. [PatternVariableName]
Audit done.
Checkstyle ends with 1 errors.

```
---

**Describe what you expect in detail.**

`PatternVariableName` should allow unnamed pattern variables by default

---

### PR DESCRIPTION
**Pull request by mahfouz72**
closes #14970 

Diff Regression config: https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/77a3990c902d2dd25743c2c46ef97d25b89dc028/check.xml

Diff Regression projects: https://gist.githubusercontent.com/mahfouz72/a3d0af030c8f5efd0d8a39f2c14750bc/raw/8ca3493f88bc1003db86b40015a4c2101ab7bc94/projects-to-test-on.properties

### CODE REVIEW

**Comment by mahfouz72** [comment]
github, generate site

**Review by nrmancuso — APPROVED** [review]
Please add migration note to issue.

**Review by rnveach — APPROVED** [review]

**Review by rnveach — CHANGES_REQUESTED** [review]
Need migration note and regression.

**Comment by mahfouz72** [comment]
github, generate report

**Comment by mahfouz72** [comment]
all done

**Review by rnveach — APPROVED** [review]

**Pull request merged**
