### PR TITLE
Issue #4400: increase coverage of pitest-checkstyle-common profile to 95%

### PR DESCRIPTION
**Pull request by Nimfadora**
Issue #4400

[pitest report before changes](https://nimfadora.github.io/issue4400.html)

increased mutation threshold for pitest-checkstyle-common profile by 3%
current threshold: 95%
execution time: 13:01 min

### CODE REVIEW

**Comment by Nimfadora** [comment]
seems as cobertura fails without my changes also.

**Comment by romani** [comment]
@Nimfadora , please rebase this PR on latest master, I did bunch of fixes to master.
Wercker still could fail... we try to fix it. But your changes do not affect wercker testing at all.

**Comment by romani** [comment]
please rebase on latest master. 
after each release it is mandatory to rebase to avoid CIs failures.

**Comment by rnveach** [comment]
@romani Code coverage failed but travis passed. I think it is related to the new changes you added.
Please look into.

**Comment by romani** [comment]
@Nimfadora , please rebase one more time on our latest master, I pushed a fix to print missed coverage.
You can always recheck coverage on your local by `mvn clean compile cobertura:cobertura` and review of report at target/site/cobertura/index.html

**Comment by Nimfadora** [comment]
@romani it just says that [this](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java#L217) line has no coverage, but the following does, but there is [test](https://github.com/checkstyle/checkstyle/pull/4561/commits/6a79f668a22db3b24415999ccd4f9496f5160d1c#diff-d3579f83a8f282b51ac0416a5550130fR631) on it.

**Comment by romani** [comment]
@Nimfadora , please send me links to tests where public method `createClasspath` is called and it return two different values base on logic in IF, no reflection to get inner state is required to cover this method.

**Comment by rnveach** [comment]
@Nimfadora I ran your changes locally, and I have 100% code coverage with no problems when running cobertura in CheckstyleAntTask.
When looking at the CI reports, it doesn't look like it is connected to your current commit.
https://travis-ci.org/checkstyle/checkstyle/jobs/249678325
> commit: 13df762c
>  Failed 7 hours ago in 13 min 41 sec 

Locally:
> commit: 9dd5676fbe31ac14321ee1e4f05a6fc38523eb02
> Author and Commit Date/Time: 3 hours ago

Can you re-push to verify and not open/close PR?

**Comment by rnveach** [comment]
Nevermind, it was merged.

**Pull request merged**
