### PR TITLE
 minor: rename CheckstyleJavaParser.g4 and JavaLexer.g4 to JavaLanguageParser.g4 and JavaLanguageLexer.g4

### PR DESCRIPTION
**Pull request by nmancus1**
From discussion in GSOC discord with @rnveach , we have decided that it is a good idea to make the naming of the parser and lexer grammar consistent, i.e. `Checkstyle...`. 

The parser grammar was renamed from `JavaParser` to `CheckstyleJavaParser` to avoid fully qualifying an instance of the `JavaParser` generated ANTLR class when we create it in the existing `JavaParser` class. The `JavaLexer` lexer grammar and generated class should also follow this naming convention. 

From chat:
> If we use JavaParser , then we are using an instance of a class called JavaParser in a class called JavaParser, and I have to fully qualify the name. Also, it kept opening the wrong file when I use the keystroke/open file dialog in intellij.

https://github.com/checkstyle/checkstyle/blob/b154154b6f935086d8a3609c17534188c0d720ae/src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java#L82-L92

Untitled

image

### CODE REVIEW

**Comment by romani** [comment]
> JavaParser generated ANTLR

 We do not care of this class, can we name it AntrlJavaParser. And keep more used by humans as JavaParser.

**Comment by nmancus1** [comment]
> Checkstyle prefix in names of our classes , is really bad.

If using "Checkstyle" in the name of a class that we create and use is really bad (I don't particularly like it either), then I think that prefacing the name of a class in this project with the name of another project is not any better.

Maybe we should use a different name entirely: `JavaLanguageParser` and `JavaLanguageLexer` ? This is more in line with the naming of the `JavadocParser` and `JavadocLexer`.

**Comment by romani** [comment]
>Maybe we should use a different name entirely: JavaLanguageParser and JavaLanguageLexer ? 

Sounds better. Let me find laptop time to experience this naming conflict, and make decision on naming.

Class that we will use most of time should be named better than less frequent/generated

**Comment by romani** [comment]
image

**Comment by romani** [comment]
I think it is good to keep JavaParser class as is, as it is what we use most of time.
Generated class should be renamed.

options:
1) CheckstyleJavaParser.java , CheckstyleJavaLexer.java, CheckstyleJavaParser.g4, CheckstyleLanguageLexer.g4
2) JavaLanguageParser.java, JavaLanguageLexer, JavaLanguageParser.g4 JavaLanguageLexer.g4
3) AntlrJavaParser.java , AntlrJavaLexer.java, AntlrJavaParser.g4, AntlrJavaLexer.g4

I think option "2)" JavaLanguageParser is good proposal, I vote for it, please share a vote, before final update.

**Comment by nmancus1** [comment]
Option 2, `JavaLanguage...`.

**Comment by rnveach** [comment]
2.

**Comment by nmancus1** [comment]
Majority has chosen `JavaLanguage...`, so PR has been updated. 

```bash

➜  checkstyle git:(rename-lexer) ✗ grep -R "CheckstyleJavaParser"
➜  checkstyle git:(rename-lexer) ✗ grep -R "CheckstyleJavaLexer" 
➜  checkstyle git:(rename-lexer) ✗ grep -R "JavaLexer"           
➜  checkstyle git:(rename-lexer) ✗ 

```

**Pull request merged**
