### PR TITLE
Issue#13999: Pitest Suppression RemoveConditionalMutator_EQUAL_IF on if (child.getType() == TokenTypes.PARAMETER_DEF) {

### PR DESCRIPTION
**Pull request by Coding-Aliens**
Issue# 13999
Diff Regression config: https://gist.githubusercontent.com/Coding-Aliens/91a8ee69412b08143dddcaae95bdb15a/raw/e4966b9cfcc06693a2a663b9eace87a84dc6c1bb/javadocmethod.xml

### CODE REVIEW

**Comment by Coding-Aliens** [comment]
Diff Regression config: https://raw.githubusercontent.com/Coding-Aliens/checkstyle/new/src/xdocs/checks/javadoc/javadocmethod.xml

**Comment by Coding-Aliens** [comment]
Github, generate report

**Comment by Coding-Aliens** [comment]
Diff Regression config:
https://raw.githubusercontent.com/Coding-Aliens/checkstyle/new/src/xdocs/checks/javadoc/javadocmethod.xml

**Comment by Coding-Aliens** [comment]
GitHub, generate report

**Comment by Coding-Aliens** [comment]
GitHub, generate report

**Comment by Coding-Aliens** [comment]
GitHub, generate report

**Comment by Coding-Aliens** [comment]
Github, generate report

**Comment by Coding-Aliens** [comment]
GitHub, generate report

**Comment by rnveach** [comment]
@Coding-Aliens I believe you are misunderstanding what that command is you are trying to use.

Please look over https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#basic-difference-report-with-custom-projects-list .

What you are trying to use is for pitest and is not for website generation. There is a completely separate command for that and it is generated from the PR, not an external file.

Also please check out https://github.com/checkstyle/checkstyle/wiki/PR-rules and ensure there is only 1 commit in your PR, and no merge commits.

**Pull request closed without merging**
