### PR TITLE
Checking and see the build status

### PR DESCRIPTION
**Pull request by Taher-Ghaleb**

### CODE REVIEW

**Comment by romani** [comment]
@Taher-Ghaleb, if you send one more PR just to have fun this our CIs - I will ban you.
Is it clear ?

**Comment by Taher-Ghaleb** [comment]
@romani, I am very sorry. I forked the repository, created branches, and by mistake created the PRs to the original repository (Kindly excuse). This shouldn't recur in the future. Sorry again and thanks for your kindness.

**Comment by romani** [comment]
there should be no impact if CI is done properly. The only impact is that PRs are fighting for resources bu only one is processed on certain CI in certain time (it is limitation of our free CI account).

**Comment by Taher-Ghaleb** [comment]
I see.. Actually, our motivation of doing such a research is that we observed some GitHub projects experiencing sequences of CI build breakages (i.e., consecutive broken builds). So, we aimed to investigate such an issue from different perspectives, including running CI builds in parallel. 

Thanks for your feedback on this, @romani.

**Pull request closed without merging**
