### PR TITLE
Issue #3279: let wercker to test cloned checkstyle repo(master or PR branch

### PR DESCRIPTION
**Pull request by romani**
Issue #3279 

it was recently requested at https://github.com/checkstyle/checkstyle/pull/7078#issuecomment-533757737
but due to rash to resolve "git clone" issue, was postponed.

====

PR in contribution - https://github.com/checkstyle/contribution/pull/413
after its merge, this PR need to be updated to use master branch of contribution repo.

### CODE REVIEW

**Comment by romani** [comment]
> after its merge, this PR need to be updated to use master branch of contribution repo.

done.
Most CIs should skip execution, as changes are only for wercker.

@pbludov , please review and approve PR.

**Comment by romani** [comment]
@rnveach ,

from wercker:
> NoErrorTest - checkstyle's sevntu - 1 second

build is skipped. please investigate.

no appveyor, strange ...

**Comment by rnveach** [comment]
> build is skipped. please investigate.

https://github.com/checkstyle/checkstyle/blame/master/wercker.yml#L128
Build is disabled until new sevntu version is released.
I am not finding a PR for this. I assume it is because we broke sevntu by changing DetailAST to an interface.

**Comment by romani** [comment]
It was disabled in scope of https://github.com/checkstyle/checkstyle/pull/5324 , 2 years ago.
We need to activate it.

**Comment by rnveach** [comment]
> We need to activate it.

We can't until sevntu releases a new version and sevntu can't upgrade until eclipse-cs does unless we break from them and split the sevntu projects up.

**Comment by romani** [comment]
yes.

```
$ ./.ci/wercker.sh no-error-checkstyles-sevntu
...
Exception in thread "main" java.lang.Error: Error was thrown while processing /home/rivanov/java/github/romani/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:315)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:220)
	at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:247)
	at org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:537)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.puppycrawl.tools.checkstyle.api.DetailAST, but class was expected
	at com.github.sevntu.checkstyle.checks.coding.ForbidCertainImportsCheck.visitToken(ForbidCertainImportsCheck.java:160)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:343)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:450)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:284)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:162)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:332)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)
	... 25 more
```

**Comment by romani** [comment]
I pushed 2 more commits to explain till what time CI build items should be suppressed.

**Comment by romani** [comment]
@rnveach , 

>The PR is based on a master that is 3 commit(s) old.
The max allowed is 10

https://travis-ci.org/checkstyle/checkstyle/jobs/589945572#L301

Please fix.

**Comment by rnveach** [comment]
> Please fix.

See https://github.com/checkstyle/checkstyle/pull/7104

**Pull request merged**
