### PR TITLE
minor: udpate checker index suppressions

### PR DESCRIPTION
**Pull request by romani**
detected at https://github.com/checkstyle/checkstyle/actions/runs/7594309984/job/20685718210?pr=14314
just update as it generated by script

### CODE REVIEW

**Comment by rnveach** [comment]
Why is this an isolated update and not found in a PR?

**Comment by romani** [comment]
I have no idea what is going on

**Comment by rnveach** [comment]
According to commit list , https://github.com/checkstyle/checkstyle/commits/master , failure in master started with c403a9a86c2c445d869ee981985344c5eacd9500 which is completely unrelated. Looking at the PR's CI list, the CI did run and said it passed. https://github.com/checkstyle/checkstyle/pull/14311 . The commit before that in master, half the CI ran and checker wasn't one of them.

However, looking at the actual run in https://github.com/checkstyle/checkstyle/pull/14311 you can see that checker throw an error and died.

https://github.com/checkstyle/checkstyle/actions/runs/7593228559/job/20683478761#step:6:470
````
Warning:  Garbage collection consumed 86% of CPU during the past 60 seconds.
Error:  An exception has occurred in the compiler (11.0.21). Please file a bug against the Java compiler via the Java bug reporting page (https://bugreport.java.com/) after checking the Bug Database (https://bugs.java.com/) for duplicates. Include your program and the following diagnostic in your report. Thank you.
com.sun.tools.javac.util.ClientCodeException: java.lang.OutOfMemoryError: Java heap space
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:832)
	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1414)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1371)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.checkerframework.framework.source.SourceChecker.wrapThrowableAsBugInCF(SourceChecker.java:2671)
	at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1059)
	at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:558)
	at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:188)
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
	... 8 more
````

**Comment by rnveach** [comment]
@romani We need to update the checker CI to detect a OOM exception and mark it as a failure if it occurs.

**Comment by romani** [comment]
moved to https://github.com/checkstyle/checkstyle/issues/14396

**Pull request closed without merging**
