### PR TITLE
Issue checkstyle#13213: Removed '//ok' comments from EqualsAvoidNull

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Part of #13213 
Removed '//ok' comments from EqualsAvoidNull Module

Links to verify edited files :
InputEqualsAvoidNull :- https://github.com/checkstyle/checkstyle/pull/14255/files#diff-2379aee39e3739248dbcde250e4500a8037f81396294b3b47e891b313439c816
InputEqualsAvoidNullSuperClass :- https://github.com/checkstyle/checkstyle/pull/14255/files#diff-34f4afd0237a1761a24000724421698bbbd40b8b8abf594cd03b992dd0105a94
InputEqualsAvoidNullIgnoreCase :- https://github.com/checkstyle/checkstyle/pull/14255/files#diff-f6aecf9af99920b1c401f3f862450b9e3f9102de771430c9e20b4c8732ff1c78

Edited input-suppressions.xml :- https://github.com/checkstyle/checkstyle/pull/14255/files#diff-bce68d2e1f79333763799164fcca3578dec40d27e64256261147e62be0c101c1

### CODE REVIEW

**Comment by MANISH-K-07** [comment]
Github, generate report

**Comment by MANISH-K-07** [comment]
Sorry for this, but I fail to understand why the checks are failing. It would be really great if I could be guided through on how to approach solving this issue as I am a beginner but a very quick learner.

**Comment by romani** [comment]
You just need to click on details of red CI, click few more times to get to more detailed execution log like https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=18724&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=1328 and read error message and do some changes to

**Comment by MANISH-K-07** [comment]
Thanks a lot for the advice. It worked like a charm!

**Comment by romani** [comment]
Please remove from your PR unrelated changes

**Comment by MANISH-K-07** [comment]
I think 2 recent commits have been cloned to my local system and got squashed while rebasing. I will try removing the unrelated changed files or if not possible, will create a new clean PR.
Sorry.

**Pull request closed without merging**
