### PR TITLE
Issue #7080: fix CustomImportOrder documentation

### PR DESCRIPTION
**Pull request by romani**
Issue #7080

### CODE REVIEW

**Comment by romani** [comment]
this PR is based on very old commit of master (HEAD~30) as our git master if damaged (for a lot of commits) by modified appveyor.bat

**Comment by rnveach** [comment]
> this PR is based on very old commit of master (HEAD~30) as our git master if damaged (for a lot of commits) by modified appveyor.bat

CI bages don't say there is any problem with master

**Comment by romani** [comment]
Yes, but try to make New changes in code and diff in appveyor.bat will bite you.

**Comment by romani** [comment]
Werker is unrelated, probably due to old base commit

**Comment by romani** [comment]
@pbludov , please finalize review

**Comment by romani** [comment]
@pbludov , it would be awesome for you to finish issue with Doc and get permission to merge yourself, to sped up process

**Pull request merged**
