### PR TITLE
Standart output usage replaced with logger

### PR DESCRIPTION
**Pull request by sabaka**
System.out has been replaced with logger. We have one more warning and I'll fix it later.
Issue #46

### CODE REVIEW

**Comment by sabaka** [comment]
Unexpected. Working on it

**Comment by romani** [comment]
before each PR, execute "mvn clean verify"

**Comment by romani** [comment]
> Main.java

that class has to use standard output , it entry point from CLI so usage of output of command line is ok.
Please add that to suppressions, we already did that in PMD and Findbugs.
Please review existing configs for such rules , Sonar already reimplemented all rules from Checkstyle. PMD , FindBugs to its own tool, so please review our configs for PMD and Findbugs to see a reason of suppression.

**Comment by mkordas** [comment]
@romani - what disadvantages have loggers compared to `System.out.println` in CLI classes? OK, they need to be configured, but with proper configuration they have only advantages IMO.

**Comment by sabaka** [comment]
@romani Ok, we have System.out only in Main. If it's fine - you can close this PR and I'll ignore it.

**Comment by romani** [comment]
> what disadvantages have loggers compared to System.out.println in CLI classes? OK, they need to be configured, but with proper configuration they have only advantages IMO.

@mkordas ,
yes, but in this case we need to keep logger configuration, we could investigate how to make it in runtime (I know that possible), but I postponed decision about Logger (javacommons, log4j, logback) to later time. So that is why simple usage of "out" is OK, it is always ok in proper place. All rules that try to catch "out.print" is designed to restrict its usage in code that is not CLI - we already did refactoring and of Checkstyle to keep it in one place and moreover - in limited methods of of Main.
Usage of logger in Main is over complication.
We are library for we should be limited on amount of dependencies and extensions (CLI, ANT, .....).

**Pull request closed without merging**
