### PR TITLE
Issue #2526: reorganized checkstyle_checks.xml

### PR DESCRIPTION
**Pull request by rnveach**
reorganized modules by package and then by class.
Added package comments to show where package separation is.

Fixed old URL at the top.

Included #2518 and added extra blank line. I added 2 for each module. I can reduce this if you want. I didn't add extra lines between 2 of the same modules.
Even though we don't have direct line links anymore, some separation is good to make it easier to see where a module starts and ends.

### CODE REVIEW

**Comment by romani** [comment]
I do not share with you your ideas about new look on config.

#2518 should be closed as not relevant after update to get rid of  line numbers. Whole reason for extra lines was to keep location of module on the same line.

Right now I do not see structure at all. Config is too big, it it hard to catch grouping.

```
            EMPTY_LINE
<!-- group name from web site  -->
<module />
<module />
<module>
</module>
```

**Comment by mkordas** [comment]
I agree with Roman, IMO config should be as concise and short as possible. I would not use more than one empty consecutive line.

**Comment by rnveach** [comment]
Fixed.

**Comment by romani** [comment]
it ok for me, I will merge your code as soon as I have enough time to do release 2.13.1 .

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
