### PR TITLE
Issue #3255: removed unnecessary string fields for patterns

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3255

Removed unnecessary String fields, inlined their values into the Pattern, and renamed pattern to be same name as setter (which is what the string field was).

### CODE REVIEW

**Comment by rnveach** [comment]
@romani Travis is passing now. I tried restarting wrecker, but now it has an unrecoverable error.
````
git checkout -fq 7b36b96bea0166035cb7c67f2acc70dc694c9b3d
fatal: reference is not a tree: 7b36b96bea0166035cb7c67f2acc70dc694c9b3d
````
Both originally had the error: `[ERROR] around Ant part ...<ant antfile="config/ant-phase-verify.xml"/>... @ 7:47 in /home/travis/build/checkstyle/checkstyle/target/antrun/build-main.xml: cannot initialize module TreeWalker - Cannot set property 'file' to '/home/travis/build/checkstyle/checkstyle/config/import-control.xml' in module ImportControl: InvocationTargetException: Unable to load /home/travis/build/checkstyle/checkstyle/config/import-control.xml: unable to read file:/home/travis/build/checkstyle/checkstyle/config/import-control.xml: Server returned HTTP response code: 403 for URL: http://checkstyle.sourceforge.net/dtds/import_control_1_2.dtd`

I am going to make an issue out of this on our side that all tests must be workable in offline as it is coming up more often, even at my work computer which is behind a firewall.

**Comment by romani** [comment]
wercker is failing due to problem on wercker, relaunch does not help, I send email to support.

@rnveach ,
Recent wercker builds for PRs are passing, so I recommend to close this PR and create new PR.

**Comment by romani** [comment]
PR is merged.

**Comment by rnveach** [comment]
> I recommend to close this PR and create new PR. 
> PR is merged.

?
No new PR is needed if this was merged.

**Comment by romani** [comment]
yes, no need, I did a comment before code review.

**Pull request merged**
