### PR TITLE
Issue 10301: Update inputs for LocalFinalVariableNameCheckTest

### LINKED ISSUE #10301: Update inputs for LocalFinalVariableNameCheckTest
Child of #10080

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #10301

### CODE REVIEW

**Comment by timurt** [comment]
fix conflicts :)

**Comment by shashwatj07** [comment]
> fix conflicts :)

done :)

**Comment by timurt** [comment]
please fix conflicts

**Comment by shashwatj07** [comment]
> please fix conflicts

done

**Comment by shashwatj07** [comment]
please restart semaphore @timurt

**Review by romani — APPROVED** [review]

**Pull request merged**
