### PR TITLE
Issue #13100: Create tests from whitespace category checks xdoc examples

### PR DESCRIPTION
**Pull request by stoyanK7**
Part of #13100 

https://checkstyle.org/checks/whitespace/index.html

### CODE REVIEW

**Comment by stoyanK7** [comment]
Github, generate site

**Comment by stoyanK7** [comment]
How can we suppress this problematic whitespace?

https://app.circleci.com/pipelines/github/checkstyle/checkstyle/20325/workflows/8d65f98d-f68a-4484-a106-9c6d3f8c60ba/jobs/365186/artifacts

**Comment by romani** [comment]
Please add it to 
https://github.com/checkstyle/checkstyle/blob/fe6fbd8cd8ca9c6d0bb999099fc6f7041b649b3e/config/intellij-idea-inspection-scope.xml#L5

**Review by romani — APPROVED** [review]
Ok to merge when ci is green

**Review by nrmancuso — APPROVED** [review]
Ok to merge when CI is green

**Comment by stoyanK7** [comment]
Added to `intellij-idea-inspections.properties` since CI failed again

https://github.com/checkstyle/checkstyle/blob/722c528c36d51c5bbbabad8c2b19e57d31805d52/config/intellij-idea-inspections.properties#L1-L2

**Comment by romani** [comment]
Still red

**Comment by romani** [comment]
Please do replace.
Nobody cares that there is tab in xml/HTML.

**Comment by stoyanK7** [comment]
Done.

**Review by romani — APPROVED** [review]

**Pull request merged**
