### PR TITLE
Issue #9335: Fix referenced Google Style Guide issues in Google Check…

### PR DESCRIPTION
**Pull request by timothystone**
The references to Google Style Guide issues <code>#258</code> and
<code>#259</code> are flipped.

### CODE REVIEW

**Review by strkkk — CHANGES_REQUESTED** [review]
Please change commit message to start with `minor: <description of your changes>`

**Comment by romani** [comment]
Fix is good, but commits have to be fixed.

**Comment by timothystone** [comment]
> Fix is good, but commits have to be fixed.
> Please read https://checkstyle.org/beginning_development.html#Starting_Development

Thanks! I'll look at rebasing that.

**Comment by timothystone** [comment]
I'm going to close this PR and start over.

**Pull request closed without merging**
