### PR TITLE
spelling: fix strange japanese.

### PR DESCRIPTION
**Pull request by Nobuyuki-Inaba**

### CODE REVIEW

**Comment by romani** [comment]
I used google translator to review your changes - they are ok. Thanks a lot.

As build pass, I will merge your PR.

**Comment by Nobuyuki-Inaba** [comment]
Thanks a lot !!
I will other Japanese resource files  and send PRs in future.

**Comment by romani** [comment]
thanks a lot!

Please do one file update for each PR. This simplify changes review.

**Comment by Nobuyuki-Inaba** [comment]
I understand. I will update one file update for each PR.

**Pull request merged**
