### PR TITLE
Issue #9466: update example of AST for TokenTypes.LITERAL_CASE

### LINKED ISSUE #9466: update example of AST for TokenTypes.LITERAL_CASE
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_CASE

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

### PR DESCRIPTION
**Pull request by vinayak-gaikwad**
Resolves #9466 

```
vinayak@Gladiator:~/Documents$ cat test.java 
class test {
	public static void main(String args[]){
		int num = 1;
		switch (num) {
      		case 0:
        		num = 1;
    	}

    	switch (num) {
      		case 1 -> num = -1;
    	}
	}
}

vinayak@Gladiator:~/Documents/Opensource/checkstyle/target$ java -jar checkstyle-8.45-SNAPSHOT-all.jar -T /home/vinayak/Documents/test.java 
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|--LITERAL_CLASS -> class [1:0]
|--IDENT -> test [1:6]
`--OBJBLOCK -> OBJBLOCK [1:11]
    |--LCURLY -> { [1:11]
    |--METHOD_DEF -> METHOD_DEF [2:1]
    |   |--MODIFIERS -> MODIFIERS [2:1]
    |   |   |--LITERAL_PUBLIC -> public [2:1]
    |   |   `--LITERAL_STATIC -> static [2:8]
    |   |--TYPE -> TYPE [2:15]
    |   |   `--LITERAL_VOID -> void [2:15]
    |   |--IDENT -> main [2:20]
    |   |--LPAREN -> ( [2:24]
    |   |--PARAMETERS -> PARAMETERS [2:25]
    |   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:25]
    |   |       |--MODIFIERS -> MODIFIERS [2:25]
    |   |       |--TYPE -> TYPE [2:25]
    |   |       |   |--IDENT -> String [2:25]
    |   |       |   `--ARRAY_DECLARATOR -> [ [2:36]
    |   |       |       `--RBRACK -> ] [2:37]
    |   |       `--IDENT -> args [2:32]
    |   |--RPAREN -> ) [2:38]
    |   `--SLIST -> { [2:39]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [3:2]
    |       |   |--MODIFIERS -> MODIFIERS [3:2]
    |       |   |--TYPE -> TYPE [3:2]
    |       |   |   `--LITERAL_INT -> int [3:2]
    |       |   |--IDENT -> num [3:6]
    |       |   `--ASSIGN -> = [3:10]
    |       |       `--EXPR -> EXPR [3:12]
    |       |           `--NUM_INT -> 1 [3:12]
    |       |--SEMI -> ; [3:13]
    |       |--LITERAL_SWITCH -> switch [4:2]
    |       |   |--LPAREN -> ( [4:9]
    |       |   |--EXPR -> EXPR [4:10]
    |       |   |   `--IDENT -> num [4:10]
    |       |   |--RPAREN -> ) [4:13]
    |       |   |--LCURLY -> { [4:15]
    |       |   |--CASE_GROUP -> CASE_GROUP [5:8]
    |       |   |   |--LITERAL_CASE -> case [5:8]
    |       |   |   |   |--EXPR -> EXPR [5:13]
    |       |   |   |   |   `--NUM_INT -> 0 [5:13]
    |       |   |   |   `--COLON -> : [5:14]
    |       |   |   `--SLIST -> SLIST [6:14]
    |       |   |       |--EXPR -> EXPR [6:14]
    |       |   |       |   `--ASSIGN -> = [6:14]
    |       |   |       |       |--IDENT -> num [6:10]
    |       |   |       |       `--NUM_INT -> 1 [6:16]
    |       |   |       `--SEMI -> ; [6:17]
    |       |   `--RCURLY -> } [7:5]
    |       |--LITERAL_SWITCH -> switch [9:5]
    |       |   |--LPAREN -> ( [9:12]
    |       |   |--EXPR -> EXPR [9:13]
    |       |   |   `--IDENT -> num [9:13]
    |       |   |--RPAREN -> ) [9:16]
    |       |   |--LCURLY -> { [9:18]
    |       |   |--SWITCH_RULE -> SWITCH_RULE [10:8]
    |       |   |   |--LITERAL_CASE -> case [10:8]
    |       |   |   |   `--EXPR -> EXPR [10:13]
    |       |   |   |       `--NUM_INT -> 1 [10:13]
    |       |   |   |--LAMBDA -> -> [10:15]
    |       |   |   |--EXPR -> EXPR [10:22]
    |       |   |   |   `--ASSIGN -> = [10:22]
    |       |   |   |       |--IDENT -> num [10:18]
    |       |   |   |       `--UNARY_MINUS -> - [10:24]
    |       |   |   |           `--NUM_INT -> 1 [10:25]
    |       |   |   `--SEMI -> ; [10:26]
    |       |   `--RCURLY -> } [11:5]
    |       `--RCURLY -> } [12:1]
    `--RCURLY -> } [13:0]


```
Screenshot from 2021-07-26 11-05-36

### CODE REVIEW

**Comment by AkMo3** [comment]
Maybe rather than showing duplicate switch cases, we can show 2 different switch cases 1. switch statement and 2. Switch expression. Also, showing only the tree starting from `SWITCH_RULE` or `CASE_GROUP` would minimize the size of the tree.

**Comment by vinayak-gaikwad** [comment]
> Maybe rather than showing duplicate switch cases, we can show 2 different switch cases 1. switch statement and 2. Switch expression. Also, showing only the tree starting from `SWITCH_RULE` or `CASE_GROUP` would minimize the size of the tree.


> Maybe rather than showing duplicate switch cases, we can show 2 different switch cases 1. switch statement and 2. Switch expression. Also, showing only the tree starting from `SWITCH_RULE` or `CASE_GROUP` would minimize the size of the tree.

I am getting a compilation error while using switch expressions. Can you give me an example of the same?

**Comment by AkMo3** [comment]
> I am getting a compilation error while using switch expressions

You might be getting compilation because of using `statement` and `expression` in a single switch.  Please try something like

```
class Test {
  void foo(int num) {
    
    switch (num) {
      case 0:
        num = 1;
    }

    switch (num) {
      case 1 -> num = -1;
    }

  }
}
```

**Comment by vinayak-gaikwad** [comment]
can you suggest any changes in following AST
Screenshot from 2021-07-25 21-00-37

**Comment by AkMo3** [comment]
I would prefer something like
image

**Comment by vinayak-gaikwad** [comment]
> I would prefer something like
> image
> 

Thanks, I will apply these changes.

**Comment by AkMo3** [comment]
@vinayak-gaikwad Please merge commits into one

**Review by romani — APPROVED** [review]

**Pull request merged**
