### PR TITLE
Pull #3070: Speed up google_check validation test

### PR DESCRIPTION
**Pull request by Vladlis**
This test runs all checks in google_checks.xml over all checkstyle sources for over 12 seconds although its aim is to validate that configuration is well formed, what can be done just by Checker#configure().
Now the test takes less than 2 seconds.
https://github.com/checkstyle/checkstyle/issues/1275

### CODE REVIEW

**Comment by romani** [comment]
Yes, that test do more it should be. We already enforced xml structure validation by maven xml plugin.

But it covered real testing of google_checks.xml . The same Check is running on all files, not the one file as in UT mode.

I am ok to merge this only if update our travis.yml to have testing over googles projects against google_checks.xml , see examples as `DESC="NoExceptionTest - Guava"`

**Comment by Vladlis** [comment]
@romani 
Updated Travis. I guess now we don't need that test at all, as all validation is performed by Travis.
Benefits: `mvn verify` is faster now.

**Comment by romani** [comment]
I do not expect changes in existing travis builds.
Google checks does not contain all checks.

**Comment by Vladlis** [comment]
Fixed

**Comment by romani** [comment]
Merged as ff

**Pull request closed without merging**
