### PR TITLE
Removed unused class supression

### PR DESCRIPTION
**Pull request by olkooo**
Cleared up the unused class and suppression.
There's no test using this class.

### CODE REVIEW

**Comment by nrmancuso** [comment]
>Cleared up the unused class and suppression.
There's no test using this class.

@olkooo it appears from above that this input is being used.

```
➜  checkstyle git:(master) ✗ find . -name "InputJavadocStyle5.java"
./src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle5.java
```

Input is used at https://github.com/checkstyle/checkstyle/blob/3f31f9f303f38d86242bd4ecf67662ab2f2899a8/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java#L315

**Comment by romani** [comment]
Please run `mvn verify` before pushing changes for review. It 0 chance to be accepted if this command is failing.

**Comment by rnveach** [comment]
@olkooo Did you notice the following line above what you removed?
https://github.com/checkstyle/checkstyle/blob/1811aec9f7e65b400424773c784e3795c4977f56/config/checkstyle_resources_suppressions.xml#L178

Do you know what it means? Did you read over the issue it pointed to and understand what the issue talks about?

**Comment by rnveach** [comment]
@olkooo ping

**Comment by nrmancuso** [comment]
We have lost contact with author, anyone is welcome to reuse changes here to solve issue.

**Pull request closed without merging**
