### PR TITLE
Issue #7604 : Update doc for NonEmptyAtclauseDescription

### PR DESCRIPTION
**Pull request by coderdeadpool**
Issue #7604 : Added example for each existing config to show what code is ok and what code cause violation.

### CODE REVIEW

**Comment by romani** [comment]
@coderdeadpool , please review CI failures, all CI should be green.

**Comment by romani** [comment]
Github, generate website

**Comment by coderdeadpool** [comment]
@romani yes, am on it.
Can you please review the changes? Have I done this correctly?

**Comment by romani** [comment]
You need to share images if website and CLI outputs to prove that it works as you describe in examples

**Comment by coderdeadpool** [comment]
Hey @romani, I made some changes, but when I ran the 'mvn verify' command on my local machine, it showed an error regarding the format of the commit message. As a beginner, could you please help me with this?
I have added the commit message in the correct format as specified in the readme. And i think that is why the checks are failing here too.

**Comment by coderdeadpool** [comment]
And the format of the commit message was the only error.

**Comment by romani** [comment]
Keep single commit in your branch and in PR. Always squash commits in one commit

**Pull request closed without merging**
