### PR TITLE
infra: replace project.properties with projects.properties

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Replaces `project.properties` with `projects.properties` and add support for `yml` in `diff-report.sh`

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
@romani, the PR is up. the diff-report.sh will be modified in the other PR.

**Comment by relentless-pursuit** [comment]
Testing with updated diff-report.yml and diff-report.sh: https://github.com/checkstyle-gsoc/checkstyle/actions/runs/11262378577/job/31317940334

**Comment by relentless-pursuit** [comment]
Once, we merge this, it will be earlier for me to test the other infra PR in my own org, since i am having to modify the diff-report.sh and relying on checkout to draw the recent change.

**Review by romani — APPROVED** [review]
Lets try

**Pull request merged**
