### PR TITLE
Issue #10924: Update CustomImportOrderCheck to use codepoints

### PR DESCRIPTION
**Pull request by MUzairS15**
Issue #10924: Updated CustomImportOrderCheck to use codepoints

Diff Regression config: https://gist.githubusercontent.com/MUzairS15/840340b17ca54ece7f04ec52b4ebff88/raw/356c824588d971cfead397fd6faca01afbde51c8/config.xml

### CODE REVIEW

**Comment by MUzairS15** [comment]
Github, rebase

**Comment by MUzairS15** [comment]
Github, rebase

**Comment by nick-mancuso** [comment]
@MUzairS15 let's add proof of update required to PR description, ping me once completed.

**Comment by MUzairS15** [comment]
> @MUzairS15 let's add proof of update required to PR description, ping me once completed.

Yes, I have not completed I will ping you "all done" once completed, there are some checks which are not misbehaving need to check if they are because of suppression filters as mentioned by you.

**Comment by MUzairS15** [comment]
No update required,

**Comment by MUzairS15** [comment]
> @MUzairS15 let's add proof of update required to PR description, ping me once completed.

@nick-mancuso  
All done, let's start reviewing, have closed PRs which doesn't require update instead added test and inputs in separate PR

**Pull request closed without merging**
