### PR TITLE
Issue #10258: Update inputs for OneStatementPerLineCheckTest

### LINKED ISSUE #10258: Update inputs for OneStatementPerLineCheckTest
Child of #10080

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #10258

### CODE REVIEW

**Comment by shashwatj07** [comment]
@romani Google test uses check input for this one https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=4053&view=logs&j=89cf5cab-37fd-5e09-60f8-9a1742bde19b&t=f89aed60-e6d5-5750-95ad-83cc60b84b61&l=1198

This needs fixing https://github.com/checkstyle/checkstyle/blob/c7c0d523acd6ff0c7a60ffebd2127afb3d7da24a/src/it/java/com/google/checkstyle/test/chapter4formatting/rule43onestatement/OneStatementPerLineTest.java#L88-L90

**Comment by shashwatj07** [comment]
Github, rebase

**Comment by timurt** [comment]
fix conflicts

**Comment by shashwatj07** [comment]
> fix conflicts

done

**Pull request merged**
