### PR TITLE
doc: Add Mega-Linter to active tools list

### PR DESCRIPTION
**Pull request by nvuillam**
Issue: #8922

### CODE REVIEW

**Comment by romani** [comment]
Please make CI happy
https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/35953946/job/93cp90xu56dw1ayr#L249

**Comment by nvuillam** [comment]
@romani CI happy :) (except travis who runs for several hours :o )

**Comment by romani** [comment]
It is not so easy to make our beast happy
https://travis-ci.org/github/checkstyle/checkstyle/jobs/739048351#L288

**Comment by nvuillam** [comment]
a spellchecker who doesn't like my name ? damn I didn't expect this one 🤣 
on it :)

**Comment by romani** [comment]
Travis in not running, I sent message to support.

**Comment by nvuillam** [comment]
I added the 3 words for spell checker, if it was the only remaining issue,
it would pass with my latest commit :)

Le mar. 27 oct. 2020 à 16:00, Roman Ivanov <notifications@github.com> a
écrit :

**Comment by nvuillam** [comment]
@romani > Seems it actually passed 😄

**Pull request merged**
