### PR TITLE
Issue #2575: Create directory structure needed to store cache file

### PR DESCRIPTION
**Pull request by MEZk**
@romani 
I cannot reproduce AppVeyor test fail on my local PC.

### CODE REVIEW

**Comment by romani** [comment]
Do you try this on windows ?

**Comment by mkordas** [comment]
@MEZk 
We also need some negative test cases when directory structure can't be created - for example wrong path or no permissions.

**Comment by MEZk** [comment]
@mkordas 
>We also need some negative test cases when directory structure can't be created - for example wrong path or no permissions.

Added both tests.

**Comment by MEZk** [comment]
Paths.get() throws InvalidPathException if path is invalid. InvalidPathException is not a subclass of IOException . ```C\:invalid``` is an invalid path on OS Windows and that is why testDestroyNonExistingCache in TreeWalkerTest failed.

**Comment by MEZk** [comment]
Method [setWritable](https://github.com/MEZk/checkstyle/commit/7244f65115e0353794c39298e665dd3a1266bfb0#diff-621d00681a530ee55984af2131842777R138) (or setReadOnly) from java File class does not set permissions for directory on Windows. It does nothing at all whereath it prevents directory from writing on Linux (works correctly as specified in javadoc). This issue fails the testNonAccessibleDirectory.

Proposition:
1) Execute test only on Linux.
2) Remove test.

**Comment by romani** [comment]
please take a look at https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java#L356 and around . I had a lot of fun time with Windows-Linux file systems.

**Comment by MEZk** [comment]
@romani 
Does not work in my case. I need to make directory (not a file) as readonly. That approach does not help. Yes, it works with files, nevertheless, it does not set permissions for a directory.

**Comment by romani** [comment]
that was example that remove permission does not work in Windows and how we do workaround already.

**Comment by MEZk** [comment]
@romani 
Can we ran the test only on Linux and ignore it on Windows? Because I don't find a sollution of the problem.

**Comment by romani** [comment]
please look at https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java#L442

**Comment by MEZk** [comment]
Travis CI: cobertura reports coverage 100%
AppVeyor CI: cobertura reports  coverage  99.2 %.
Looks strange.

**Comment by romani** [comment]
@MEZk , Find me in skype for discussion

**Comment by romani** [comment]
please rebase your commit to remove TC violations, they are already fixed in HEAD of mster.

**Comment by romani** [comment]
to resolve problem with coverage you need to build coverage report in Windows OS and look what is not covered according to cobertura "mvn cobrtura:cobertura". Please share report with me if you still think it should not be a problem.

**Comment by MEZk** [comment]
@romani 
The problem with coverage has been resolved successfully.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
