### PR TITLE
Fixes PMD violations: EmptyMethodInAbstractClassShouldBeAbstract #997

### PR DESCRIPTION
**Pull request by Bhavik3**

### CODE REVIEW

**Comment by romani** [comment]
1)
>-        else if (ast.getType() != TokenTypes.PACKAGE_DEF
-                 && ast.getType() != TokenTypes.IMPORT) {
-            leaveAST(ast);
-        }

please explain that code removal.

**Comment by Bhavik3** [comment]
1)
The only class extending `AbstractTypeAwareCheck` is `JavadocMethodCheck`. And `JavadocMethodCheck` is not using that method. And by default, this method has not any implemented code. So, We can remove it.
As `AbstractTypeAwareCheck` is deprecated, In future we will not extend it for other check. So, removing `LeaveAST()` and all statement where it is called will not change functionality.

**Comment by romani** [comment]
thank you for explanation - make sense.

last item:

1)
> public void valueForPathChanged(TreePath path, Object newValue) {

please make comment as "No code , as tree is read-only"

**Comment by Bhavik3** [comment]
@romani 
Done

When will `valueForPathChanged(TreePath path, Object newValue)` be useful. As tree is always read-only, when we can change any node of tree?

**Comment by romani** [comment]
> As tree is always read-only, when we can change any node of tree?

never, we do override only satisfy compiler.

**Comment by romani** [comment]
merged as FF.

thanks a lot !!

**Pull request closed without merging**
