### PR TITLE
Issue #3233: Resolve IntelijIdea inspection violations for java8 migration

### PR DESCRIPTION
**Pull request by tcNickolas**
Issue #3233 

This change reverts commits 015fa7f and 6c1a0e1 and fixes violations of respective rules.

I got two Checkstyle violations which seemed unrelated to my changes (and caused by legitimate code), so I suppressed them using `SuppressWarnings` syntax. Please let me know if there is a different preferred way to deal with them.

### CODE REVIEW

**Comment by romani** [comment]
@tcNickolas ,
thanks for PR.

travis buils was restarted as PR description was changed - passed.

> I got two Checkstyle violations which seemed unrelated to my changes (and caused by legitimate code), so I suppressed them using SuppressWarnings syntax

it is not allowed to pollute code with such annotations. Please update line numbers at suppression file 
https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml#L14
Yes, this is a pain, it will be easier as we implement flexible suppressions base on AST tree. But for now it is line numbers.

**Comment by tcNickolas** [comment]
@romani 
I've addressed the comments, and also fixed `Interface may be annotated @FunctionalInterface` violations which I somehow missed in the first iteration.

**Comment by romani** [comment]
you are too quick.... thanks a lot

> FunctionalInterface
api/Configurable.java

Please remove changes for this annotation usage and disable that rule in configuration.
It affects API part of Checkstyle , too much tools reply on our API , I am not ready to make this as contract that all such interfaces will be functional always.
You can make separate issue on this to let us think about this a bit later, you can put a link to issue as a reason of disablement for future reference.

**Comment by tcNickolas** [comment]
I've reverted changes related to `@FunctionalInterface` annotation. This check was originally disabled as part of 015fa7f, so this discussion wouldn't be the original reason.

**Comment by romani** [comment]
@tcNickolas , thanks a lot !

let me know if want to help us with other issues, I will guide you.

**Comment by tcNickolas** [comment]
You're welcome :-)

I'd definitely like to help with something else, probably in a couple of weeks. Do you have any "good for beginners" issues in mind?

**Comment by romani** [comment]
Ok , pin me here as you be ready for smth that is more about functionality feature or refactoring

**Pull request merged**
