### PR TITLE
Do not verify overriding methods in ThrowsCount check, #1085

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by romani** [comment]
1) 
> getAnnotationName

please to one return point from method. Always try to follow that rule.

2) Please generate report by checkstyle-tester over all projects to recheck Exceptions and share a report to let us verify your results (do it yourself before sharing).

**Comment by Vladlis** [comment]
1) OK
2) the report is quite heavy, just waited until it is uploaded: http://vladlis.github.io/

**Comment by Vladlis** [comment]
2) Why static?

**Comment by Vladlis** [comment]
What's wrong with Travis? Is it because of my changes? If yes, then how do I fix this?

**Comment by romani** [comment]
that was temporal problem on Travis side, relaunched, now it is green.

**Comment by romani** [comment]
@Vladlis , please update:
1) javadoc of the class 
2) xdoc of the Check

Fact that we skip Override annotation should be described as a note in documentation.

**Comment by romani** [comment]
> Overriding methods are not checked.

Methods with "Override" or ".......Override" annotation are skipped from validation as current class can not change signature of that methods.

**Comment by romani** [comment]
> .......Override 

What is it ? please put a full name of annotation, I was not sure of full name so I put "....." to let you make it as required.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
