### PR TITLE
 Issue #6516: recognized javadocs on ...

### PR DESCRIPTION
**Pull request by rnveach**
Issue #6516 

Issue isn't approved. This isn't the end of the issue probably.
I want to get these merged and run regression again to see if I can find anything else.

### CODE REVIEW

**Comment by rnveach** [comment]
Wercker is finding regression with ` Postgresql JDBC Driver`.
> [ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/main/java/org/postgresql/copy/CopyOut.java:25: Line continuation have incorrect indentation level, expected level should be 4. [JavadocTagContinuationIndentation]

**Comment by rnveach** [comment]
@romani I assume you have no problems with issue before I start fixing wercker regression in other projects?

**Comment by romani** [comment]
Issue is approved

**Comment by rnveach** [comment]
CI passed. I rebased to resolve conflicts.

**Pull request merged**
