### PR TITLE
Issue #1566: TodoComment violations fixed

### PR DESCRIPTION
**Pull request by rdiachenko**
Violations fixed:
- TodoComment Comment matches to-do format 'TODO:'.

### CODE REVIEW

**Comment by romani** [comment]
It is not a solution, you missed an ":" at javadoc and that symbol is in code.

The same problem is in Sonar, suppression should be used, in your case, just remove that Check from config

**Comment by rdiachenko** [comment]
@romani how about these changes?
```
- * A check for 'TODO:' comments. To check for other patterns in Java comments, set
+ * A check for '<code>TODO</code>:' comments. To check for other patterns in Java comments, set
```

We can fix Checkstyle violation in this way. ":" is on its place.

**Comment by mkordas** [comment]
@romani SonarQube don't have concept of suppressing single violations. You can suppress either entire file or mark violation as "won't fix" - but it requires admin privileges.

**Comment by romani** [comment]
>  how about these changes?

:) that is hack, please put a picture with javadoc to see how that will looks like.

> but it requires admin privileges.

that is why we will use Sonar team to do that (through mail-list request).

**Comment by rdiachenko** [comment]
@romani 
>> please put a picture with javadoc to see how that will looks like

todo

**Comment by romani** [comment]
ok looks good, that is fix only for one case.

what about all others - http://nemo.sonarqube.org/dashboard/index?id=com.puppycrawl.tools%3Acheckstyle%3Asrc%2Fmain%2Fjava%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2FTodoCommentCheck.java

**Comment by rdiachenko** [comment]
@romani I understand your point. This solution works for Checkstyle only but if Checkstyle allows us to overcome the problem in such a way why can't we use this feature? Otherwise just removing this check is not enough and we will have to admit that it is a bug and we'll have to open an issue against this check.

**Comment by romani** [comment]
Because we need to show users that non of Check work fine on all cases(codes) in the world, exceptional cases are possible and it is ok to use suppressions.

**Pull request closed without merging**
