### PR TITLE
Issue 2517 2519

### PR DESCRIPTION
**Pull request by rnveach**
Removed some duplicates in regexp.

**New Requirements:**
Removed xml restriction in usage section, now section can only contain certain words.
Added URL validation for links in usage section.

### CODE REVIEW

**Comment by romani** [comment]
I presume you will update https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/google_style.xml in next PR

**Comment by romani** [comment]
thanks a lot for impressive update !

**Comment by rnveach** [comment]
> I presume you will update ...

@romani
Are we updating every instance of a master url?
There are files my test doesn't examine.
Example: cmdline.xml.vm, config_imports.xml (Example section), google_style.xml, sun_style.xml, writingchecks,xml.vm

**Comment by romani** [comment]
> cmdline.xml.vm , writingchecks.xml.vm

doe snot have line specific links , no need to validate

>  config_imports.xml 

you changed it, looks ok.

>  sun_style.xml

Empty page, we did not do this. No need to check.

> google_style.xml

I would be good to update this page with links of search rather then line number.

**Comment by rnveach** [comment]
Ok, I will update the line links.

> > config_imports.xml 
> you changed it, looks ok.
I was talking about this link: https://github.com/checkstyle/checkstyle/blob/master/config/import-control.xml
but its not a line link. I was just doing a search for "/master/".

**Comment by romani** [comment]
yes it is ok.

**Comment by rnveach** [comment]
in #2527

**Pull request merged**
