### PR TITLE
Issue #14937: Migrated section 5.2.1 Package names to chapter wise testing

### PR DESCRIPTION
**Pull request by Zopsss**
#14937

### CODE REVIEW

**Comment by Zopsss** [comment]
failing CI: https://github.com/checkstyle/checkstyle/actions/runs/9677346998/job/26698771908?pr=15134

it does not affect the PR

**Review by romani — APPROVED** [review]
ok to merge

**Comment by romani** [comment]
@Zopsss , please fix conflict

**Comment by Zopsss** [comment]
@romani done

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by rdiachenko** [comment]
@Zopsss please resolve conflicts

**Comment by Zopsss** [comment]
@rdiachenko conflicts resolved

**Comment by romani** [comment]
@Zopsss , conflict

**Review by romani — APPROVED** [review]

**Pull request merged**
