### PR TITLE
Issue #3848: Remove unnecessary if-block to increase code coverage

### PR DESCRIPTION
**Pull request by MEZk**
#3848 

Method can be defined only in class, interface, enum, annotation interface, annonymous class. For CLASS_DEF, INTERFACE_DEF, ENUM_DEF, ANNOTATION_DEF tokens we create new ClassFrame with type CLASS_FRAME. For annonymous class we create AnonymousClassFrame which extends ClassFrame and also has the type CLASS_FRAME. Thus, when we collect declarations in ```collectDeclarations```, METHOD_DEF token in always related to the frame with type CLASS_FRAME. It means that there is no need in checking the frame type.

Reports:
1) Diff http://mezk.github.io/i3848-RiquireThisCheck/diff
2) Coverage  http://mezk.github.io/i3848-RiquireThisCheck/cobertura/

### CODE REVIEW

**Comment by rnveach** [comment]
Coverage URL isn't working, but I don't think we need it as long as coverage CI is now working

**Comment by romani** [comment]
if coverage is improved, pom.xml exclude rule for this Check should be updated too to new value.

**Comment by MEZk** [comment]
@rnveach 
> Coverage URL isn't working,

Fixed.

@romani 
> if coverage is improved, pom.xml exclude rule for this Check should be updated too to new value.

Done.

**Comment by rnveach** [comment]
@MEZk will 100% be next PR?

**Comment by romani** [comment]
it is funny, but I can not relaunch circleci , as I do not have RW permissions to fork.

@MEZk , please address CI failure.

**Comment by MEZk** [comment]
@rnveach 
Yes. I decided to split fix just to easy code review and analysis.

@romani 
Done.

**Pull request merged**
