### PR TITLE
Issue #1008: Add possibility to suppress checks by id

### PR DESCRIPTION
**Pull request by MEZk**
Implemented #1008 request for SuppressionCommentFilter, SuppressWarningsFilter, SuppressWithNearbyCommentFilter.

### CODE REVIEW

**Comment by MEZk** [comment]
@romani 
Corrected issues which were discussed via Skype.

**Comment by romani** [comment]
1)
> 
```
            if (afterStart && beforeEnd && (nameMatches
                    || event.getModuleId() != null
                    && event.getModuleId().equals(entry.getCheckName()))) {
```

this code is hard to read. You need to move your extra logic to nameMatches definition or make idMatches variable.

2)
> Imagine that you have ....

Please make clear statements. "To skip validation on ............. you need ....."

3)
```
 +&lt;module name="MemberName&quot;&gt;
+  &lt;property name="id" value="ignore"/&gt;
+&lt;/module>
```

Your example is too artificial and useless. Please use example from issue - good example of how people have the same Check defined few times with different options and why ID make sense during suppression.

**Comment by MEZk** [comment]
@romani 
1) Done
2, 3) Done

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
