### PR TITLE
Visibility Modifier Check, added option allows public final fields, issu...

### PR DESCRIPTION
**Pull request by alexkravin**
...e #61

According to #61 

Added option which allows final fields to be public for supporting style of immutable classes, added UT and corresponding input, extended javadoc/xdoc

### CODE REVIEW

**Comment by romani** [comment]
The task is more compicated than just check for "final".

You need to skip public only for immutable classes , final by itself, type of field is immutable, ....  please read "Requested:" with more attention.

Plase do investigation on what is immutable classes and why they matter.

**Comment by alexkravin** [comment]
All "Requested" points are done, updated docs, there's possibility to extend default list of immutable types (I have added the most common in use, for example there're a lot of immutable classes in java.awt package, but they're not frequently in use).
Added restriction to doc, as Check doesn't control if class is immutable because this verifying would be big damage to Check's speed and I think it's out of scope of this Check, current approach should cover most of cases.

**Comment by romani** [comment]
> public final ImmutableSet&lt;String&gt; includes; // No warning

as you use types that are not default - please provide config to that code.

> typeIdentifier.getText().matches("^Immutable.+$");

? why that is not configurable ?

 > 
+ Collections.addAll(immutableClassNames, DEFAULT_IMMUTABLE_TYPES);
+ Collections.addAll(immutableClassNames, classNames);

User value always override default, if user need default + his values , he need to provide default values in new value that he pass to that setter.

> Field is considered to be immutable if it have final modifier and either a primitive type or ...

I do not see any test or code that check for alll primitive types, please provide a link

> + private static final String[] DEFAULT_IMMUTABLE_TYPES = {
+ "String",

usage of simple names is error prone, please update option to force user to provide canonical names only, and please add type recognition to that Check (you already did that in other Checks).

**Comment by alexkravin** [comment]
1) Now user values override default one, provided examples with corresponding configs in javadoc/xdoc

2) Primitive types have special tokens, here's a comment at place where this checking is:
https://github.com/alexkravin/checkstyle/blob/d3e4051b90cae327dad608afdf4f511e05f967ca/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L433

3) Types are provided via canonical names

**Comment by alexkravin** [comment]
Please rerun this build on travis after checkstyle.sourceforge.net will be available

**Comment by romani** [comment]
1) VisibilityModifierCheckTest.java

> checkConfig.addAttribute("immutableClassNames", "List, ImmutableSet");

not clear why simple names are specified, as we discussed we force user to be exact.

**Comment by alexkravin** [comment]
1) Specified canonical names in UT and docs as examples, but, sure, user is able to specify short names.

2) Extended UT input

**Comment by alexkravin** [comment]
Travis fails the build because of reset connection

**Comment by romani** [comment]
please provide reports for guava, openjdk, hibernate, and find in inernet library with a lot of immutable objects(not a guava) and test over it. Ask community to help you with testing.

**Comment by romani** [comment]
as a change is significant, I do code review of the whole Check - https://github.com/alexkravin/checkstyle/blob/e6321ea434f0e3c4735c4c0e78f8f498f8901de3/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java

1) 
> Checks visibility of class members. Only static final members may be public,

please describe whole idea of check in that first sentence. First Sentence for JavaDoc have special meaning for javadoc pages generation.

2) 
>  * declared as public if defined in final class. 

are you sure that you check final on class ?

3) 
> instance of class known

known --> user defined

4) 

> by their * canonical names 

What will be if user put non canonical name ? please describe

5) 
> Check doesn't check if class is immutable, exactly there's no checking

remove "exactly" for rephrase.

6)
> if current field is immutable and defined in final class

"immutable by matching a name to user defined list of immutable classes"

7) 
> To configure the Check passing code below:

There is no code below, below is only config.

8) 

> &lt;property name=&quot;immutableClassCanonicalNames&quot; value=&quot;java.util.List,

please do not show bad examples of names in javadoc, please use canonical names

9) 
> public final BigDecimal value; // No warning

please clearly define in javadoc that there are hardcoded set of types that is not possible to override.
So we consider them as immutable always.

10) 
> public VisibilityModifierCheck()

please remove that c-tor and keep initialization at fields level.

11) 
>  immutableClassCanonicalNames.clear();
Collections.addAll(immutableClassCanonicalNames, classNames);
fillImmutableClassShortNames(classNames);

inconsistent code, two fields are collections with same meaning but initialized differently.
should be for both fields:
collection.clear()
collection.addAll(newvalues);

12) 
>  if ((ast.getType() != TokenTypes.VARIABLE_DEF)
|| (ast.getParent().getType() != TokenTypes.OBJBLOCK))

Does it make sense after you introduced getAcceptableTokens() ?

13 )
https://github.com/alexkravin/checkstyle/blob/e6321ea434f0e3c4735c4c0e78f8f498f8901de3/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L329

please add "\n" between blocks of code there to single-out groups.

14) 
https://github.com/alexkravin/checkstyle/blob/e6321ea434f0e3c4735c4c0e78f8f498f8901de3/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L340

is there any way to simplify that IF ? I do believe that you can make it multi-level that even reduce calculate-all mess that is pointed at "13)", 

15) 
> // if has primitive

please try to avoid trailing comments as much as possible, and keep in mind that as you want to put a comment - it is big sign that code have to be changed to avoid comment.
Here I recommend to use special method - so comment text will be method name, code will become more readable.

**Comment by alexkravin** [comment]
1) Updated to "Checks visibility of class members. Only static final or immutable members may be public"

2) 
```java
allowPublicImmutableFields && classModifiers.contains("final") && isImmutableField(variableDef)
```

Here's checking  <b>final</b> on class

3) Updated

4) Added description:
if user will provide short class name all instances having
 * type matches provided will be recognized as immutable

5) Removed

6) Updated

7) And below config there's a code chunk, anyway rewrote it as:
To configure the Check passing fields of type...

8) Didn't understand this, isn't java.util.List a canonical name?

9) Added description that list will be overridden by user-defined values.

10) Done

11) Filled them in the same way.

12) This:
ast.getType() != TokenTypes.VARIABLE_DEF
doesn't have any sense, removed,
but this one:
ast.getParent().getType() != TokenTypes.OBJBLOCK
has

13) Done

14) Moved this if condition to separate method <b>canBePublic</b>, so logic in visitToken is simplified.

15) Moved to separate method.

Generated reports over Guava and Hibernate projects:

Guava:
http://alexkravin.github.io/visibilitymodifier/guava/checkstyle.html
http://alexkravin.github.io/visibilitymodifier/guava-gwt/checkstyle.html

Hibernate:
http://alexkravin.github.io/visibilitymodifier/hibernate/checkstyle.html

There're lots of warnings, in all reports about 1k.
So there will be deep analyzing, is there any need to generate more to see the same?

**Comment by romani** [comment]
Did you recheck all violations ? Can you confirm that there is no false positives?

**Comment by romani** [comment]
1)
> if (ast.getParent().getType() != TokenTypes.OBJBLOCK) {

Please explain in code reason of this IF, it is not obvious. 
I doubt that multi-return is reasonable.

2) 
> private boolean canBePublic(DetailAST variableDef, String variableName)

please apply to body of method changes that I requested, moving to separate method does not help to read that logic and performance of execution (no need to calculate all points and then validate all of them in one IF, do calculation of validation variable as close to usage as possible). In other words reduce distance from variable declaration and its first usage.

3) 
> private DetailAST getVarNameAST(DetailAST variableDefAST)

can it be static ? please recheck all other methods.

4) 
> private static List<String> getImmutableClassShortNames(String[] canonicalClassNames)

please move util methods to the bottom.

5) 
> private String publicMemberFormat = "^serialVersionUID$";

should it be final ?

6) Please order fields as we do that in other Checks, I need to see options/fileds as one code group : final constants, user accessible options/fields, .....

7) 
>  Collections.addAll(immutableClassCanonicalNames, classNames);
immutableClassShortNames.addAll(shortNames);

still a different ways to add items to collection - please use the same methods.

**Comment by alexkravin** [comment]
1) For skipping anonymous classes, provided a comment

2) all parts of condition are sequenced according to increasing of calculation complexity
moved part responsible for "immutable" calculations to the bottom of condition

3) Made all methods, which could be static, static

4) Done

5) No, as it is used in setter

6) Ordered.

7) Now
```java
        immutableClassCanonicalNames = new ArrayList<>();
        immutableClassCanonicalNames.addAll(Arrays.asList(classNames));
        immutableClassShortNames.clear();
        final List<String> shortNames = getImmutableClassShortNames(classNames);
        immutableClassShortNames.addAll(shortNames);
```


Regenerated reports with protectedAllowed=true option, so it has less violations which out of scope of this issue:

Guava:
http://alexkravin.github.io/visibilitymodifier/guava/checkstyle.html
http://alexkravin.github.io/visibilitymodifier/guava-gwt/checkstyle.html

Hibernate:
http://alexkravin.github.io/visibilitymodifier/hibernate/checkstyle.html

No false-positives were found, cases where primitive type variable or variable with type String "should be private and have accessor methods" are package-private and don't have final modifier.

**Comment by alexkravin** [comment]
Build is ok, travis dropped connection.

**Comment by romani** [comment]
1) 
> if user will provide short class name all instances having
 type matches provided will be recognized as immutable.

make it : "if user will provide short class name all that type will match to any named the same type without consideration of package"

2)
> private final List<String> immutableClassShortNames =
getImmutableClassShortNames(DEFAULT_IMMUTABLE_TYPES);

does method getImmutableClassShortNames() do smth special for Immutable classes ? Why Immutable is part of name ?

3)
>  immutableClassCanonicalNames = new ArrayList<>();
immutableClassCanonicalNames.addAll(Arrays.asList(classNames));
immutableClassShortNames.clear();
final List<String> shortNames = getImmutableClassShortNames(classNames);
immutableClassShortNames.addAll(shortNames);

Why initialization of two collections looks different again ? lines 291 and 293 have to be the same!!! Combine 294 and 295 to make it look like 292.

4)
> public int[] getDefaultTokens()

Why you do not process imports ? Please show me Input for case where you have violation on com.puppycrawl.tools.checkstyle.checks.design.String type usage.

5) 

> // to avoid checking anonymous

No trailing comments!!!! all comment are going above target code.

6) 

>  final boolean canBePublic =
"private".equals(variableScope)

if field is private then canBePublic = true , where is a logic ? how private can be public ?

7)

>  final boolean inInterfaceOrAnnotationBlock =
ScopeUtils.inInterfaceOrAnnotationBlock(variableDef);
final Set<String> mods = getModifiers(variableDef);
final String declaredScope = getVisibilityScope(mods);

What for you calculate all that variables if in 90% cases filed will be private ?

8) 

> private static DetailAST getVarNameAST(DetailAST variableDefAST)

one return

9)

> final Set<String> retVal = Sets.newHashSet();

fix the variable name

10) 

> final String[] explicitModifiers = {"public", "private", "protected"};

What a reason to create such array each time you met a filed in class ? please optimize performance.

11) 
> for (final String candidate : explicitModifiers) {

please fix the name "candidate".

**Comment by romani** [comment]
12) 
> All HTML reports

Did you recheck all 800 validation errors ? I do not trust you . Please narrow validation config to part that we fixed only.

**Comment by alexkravin** [comment]
1) Updated.

2) As it's static method and has custom logic - removed "immutable" from its name

3) I do not understand you, in first case array of string is just converted to list for passing addAll() method, in second - some logic is called, so there's a list, I see no reason to make param of setter as list or collection of short names as array, furthermore, getClassShortNames() is called at the beginning of Check to initialize corresponding field by default, no reason to complicate the logic or break performance.

4) As we force user to use only canonical names what's the reason of imports processing?
 Here's test and input of specified cases:
UT: https://github.com/alexkravin/checkstyle/blob/8238ee4465058e72f4db2eccd5e19ab40b2fff17/src/test/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheckTest.java#L132
Input:
https://github.com/alexkravin/checkstyle/blob/8238ee4465058e72f4db2eccd5e19ab40b2fff17/src/test/resources/com/puppycrawl/tools/checkstyle/InputImmutableSameTypeName.java

5) Removed this comment at all, as visitToken was rewritten and readability was simplified by introducing method isAnonymousClassVariable, so now visitToken has no extra returns

6) Renamed the method and rewrote it's logic

7) Moved the most frequent cases condition to the top, before other calculations.

8, 9, 10, 11) Not my changes at all, but fixed these points.

12) I used your advice about narrowing, is packageAllowed=true will be justified?
Did you find any false-positives?

**Comment by romani** [comment]
1)
>  As it's static method and has custom logic

logic is not custom, trip canonical names to simple names, no consideration of Immutable class at all.

2)
>  I do not understand you, 

collections should be cleared by ".clear()" in both cases.

3)
>  As we force user to use only canonical names what's the reason of imports processing?

to clearly distinguish Classes that are named the same way but located in different packages. We should without mistake treat class as immutable if it from list that user provide.

4)
>  I used your advice about narrowing, is packageAllowed=true will be justified?

skip package and protected modifiers and focus Check on public fields only.

5)
> private void visitVariableDef(DetailAST variableDef)

please move that logic back to visitToken(), as no need to spread dependencies to Checkstyle internals - "log(....)"  , between other methods.

6)
> 
 final boolean inInterfaceOrAnnotationBlock =
ScopeUtils.inInterfaceOrAnnotationBlock(variableDef);
final Set<String> mods = getModifiers(variableDef);
final String declaredScope = getVisibilityScope(mods);
final String variableScope =
inInterfaceOrAnnotationBlock ? "public" : declaredScope;
if (!"private".equals(variableScope) && !inInterfaceOrAnnotationBlock) {

what for we need to calculate mods, declaredScope ... if inInterfaceOrAnnotationBlock is true ? 

7) 

>  || ("package".equals(variableScope) && isPackageAllowed())
|| ("protected".equals(variableScope) && isProtectedAllowed())

what operation is cheaper isPackageAllowed or "package".equals(variableScope) ? What should be calculated first.

8)
> final Set<String> modifiersSet = Sets.newHashSet();

we are already at java7 , please use standard diamond operator.

9) 

>  String typeName = "";
final boolean isCanonicalName = type.getFirstChild().getType() == TokenTypes.DOT;
if (isCanonicalName) {
typeName = getCanonicalName(type);
}
else {
typeName = type.getFirstChild().getText();
}

that code even looks like separate method.

10)

>  final boolean isFinal = modifiers.branchContains(TokenTypes.FINAL);
....
return isFinal && hasImmutableType;

Does it make sense to calculate hasImmutableType if isFinal is FALSE ?

**Comment by alexkravin** [comment]
1) "Immutable" from method's name is already removed.

2) Updated. The problem was in name collision between java.util.ArrayList and java.util.Arrays.ArrayList
method Arrays.asList() does not create new instance, but just returns the view of elements as ArrayList, so now the field instantiates via creating new ArrayList<>() and specifying this view in ctor:
```java
/** List of immutable classes canonical names. */
    private List<String> immutableClassCanonicalNames = new ArrayList<>(Arrays.
            asList(DEFAULT_IMMUTABLE_TYPES));
```

Clearing is also ok now

3) You're right, added support of imports as it was done in IllegalTypeCheck, as example in UT I have created InetSocketAddress type as input class, it's one of types specified as default immutable types in Check (didn't use String because as it will collide with other inputs as they're compilable too)

There're 2 UTs responsible for testing Check's behavior when same type (short name) can appear in source.

4) Done, reports are at the bottom of this comment.

5) As import tokens are supported in Check too I think visitToken method has to be like in other Checks - with switch-case block, current:
```java
@Override
    public void visitToken(DetailAST ast)
    {
        switch (ast.getType()) {
            case TokenTypes.VARIABLE_DEF:
                if (!isAnonymousClassVariable(ast)) {
                    visitVariableDef(ast);
                }
                break;
            case TokenTypes.IMPORT:
                visitImport(ast);
                break;
            default:
                final String exceptionMsg = "Unexpected token type: " + ast.getText();
                throw new IllegalArgumentException(exceptionMsg);
        }
    }
```

6, 7) Updated this method according to performance optimization

8) Done

9) Moved to method getTypeName()

10) Updated optimization

Regenerated reports with protectedAllowed=true and packageAllowed=true option, so it has less violations which out of scope of this issue:

Guava:
http://alexkravin.github.io/visibilitymodifier/guava/checkstyle.html
http://alexkravin.github.io/visibilitymodifier/guava-gwt/checkstyle.html

Hibernate:
http://alexkravin.github.io/visibilitymodifier/hibernate/checkstyle.html

No false-positives were found by me, a lot of cases in which field looks like:
```java
public String str;
```

as it has no <b>final</b> modifier - Check puts violation on such cases.

**Comment by romani** [comment]
reports are ok.

1) The only item worry me is a StartImport, we need to describe that in Javadoc /xdoc. Any usage of on demand imports will lead to false-negatives, it is better then false-positives. Please try to make UTs that show that case.

2)
> immutableClassShortNames.remove(shortName);

as you change class fields - you have to cleanup and fill them each time in beginTree() method.
please reproduce that case in Ut and provide link to it in reply.

**Comment by alexkravin** [comment]
1) Can you provide an example of how star imports can lead to problems?
In this Check imports are in analyzing only for avoiding collisions between default type's short names and user ones and it can't be reached using star imports as compiler will force you to import one of this types explicitly.

2) I see no reason of introducing beginTree() method in this Check. As setter is called earlier - we have to initialize fields at their declaration, then clear them in beginTree() and then initialize with proper values in beginTree() and what about initializing in setter? beginTree() will just override it.

So, just for safety and easiness I introduced finishTree() method and done clearing of fields in it.
https://github.com/checkstyle/checkstyle/blob/7e70e87ac79a7047c600272a800fe59ef3bc47fe/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L653

**Comment by romani** [comment]
> 1) Can you provide an example of how star imports can lead to problems?

config: immutableClass="com.google.Factor"

code:
presume package com.elastic have class Factor too.

import com.elastic.*
class MyCLass {
public Factor;
}

By the way, we should not add to short name a class if it is not present in imports. By means of that we will avoid even false-negaives, and just not put violation if user use OnDemand imports in code.
Please do few UTs with star imports.


>  As setter is called earlier

setter is called ones for all files, you have to go with beginTree(), as if exception happen finishTree() will not be called , so you can be sure at the beginning of valiation that all fields are properly initialized.

**Comment by alexkravin** [comment]
1) Thanks, I have reproduced such case and described in UT and javadoc/xdoc
I think it will be better to leave such false-negative case, described in Restriction block of docs than try to modify collections demand on imports as there will be problems with short names collision and types from java.lang which do not require corresponding import.
Moving logic of this Check to finishTree is worse than current approach.

2) ???

Default values are initializing without setter, such initialization can be moved to beginTree, what about user-specified value? I know setter is called once, beginTree will be called on each file, so where to keep these values?

**Comment by romani** [comment]
> what about user-specified value?

as a filed that never touched in any other methods.

**Comment by alexkravin** [comment]
I understood you, introduced beginTree() method, which clears immutableClassShortNames and initializes with proper values on each file

**Comment by alexkravin** [comment]
Please, rerun travis build

**Comment by romani** [comment]
1) 
>  Star imports are out of scope of this Check. So if one of type imported via star import
collides with user specified one by its short name - there won't be Check's violation.

there is no star import - on demand import. Additionally consider a  case (false positive):
config.immutableClassName=com.google.ImmutableSet
code:
import com.google.*;
class Test {
public ImmutableSet set; // right now you will put a WARN there , right ?
}
you will not generate Short name , so class will not match - that is not correct. Please create UT on that and fix.

2)
>  ```private static final String[] DEFAULT_IMMUTABLE_TYPES = { .....```

please use http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/ImmutableList.html#of%28E,%20E,%20E,%20E,%20E,%20E,%20E,%20E,%20E,%20E,%20E,%20E,%20E...%29
that will ease all other processing.

3)
>  immutableClassCanonicalNames.clear();
immutableClassCanonicalNames.addAll(Arrays.asList(classNames));

Event that code looks weird, please use simply "="
http://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html#asList%28T...%29
the same for immutableClassShortNames

4) 
>  ```private boolean hasProperAccessModifier(DetailAST variableDef, String variableName)
{
boolean result = true;
final boolean inInterfaceOrAnnotationBlock =
ScopeUtils.inInterfaceOrAnnotationBlock(variableDef);
if (!inInterfaceOrAnnotationBlock) {
```

name of the method does not correspond to what it is doing. Move first IF out of this method to top level of code and recheck that name of method describe exactly a algorithm of method.

5) 
```
 if (hasImmutableType) {
result = true;
}
``` 

???? please optimize.

**Comment by alexkravin** [comment]
0) Removed

1) I think current docs are right, because there's no consideration about star imports in Check at all and provided example won't lead to false-positive, created UT to show it.
Consideration of star imports will lead Check to high amount of false-positives in the future and no consideration of it - will lead to rare false-negatives in its turn which are much better than false-positives.
There already is UT and input showing false-negative case.
So restriction exists and it's described.

2) Changed to ImmutableList

3) Why '=' is better than addAll()? Changed

4) Moved 'if' considers about interface or annotation block to upper method, so now method:
https://github.com/checkstyle/checkstyle/blob/0beb2bc49fb96d9661326f96845800d61b1802e7/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L428

5) https://github.com/checkstyle/checkstyle/blob/0beb2bc49fb96d9661326f96845800d61b1802e7/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L529

**Comment by alexkravin** [comment]
P.s.
consulting.xml fails the build

**Comment by romani** [comment]
> There already is UT and input showing false-negative case

I do not understand why we do not have violation at "InputImmutableStarImport2.java" , type ImmutableSet should not be recognized as immutable type, so violation should be. Lets discuss or explain.

> Why '=' is better than addAll()? Changed

less code. I do not see that change.

> 
```
 final DetailAST varNameAST = getVarNameAST(variableDef);
final String varName = varNameAST.getText();
final boolean inInterfaceOrAnnotationBlock =
ScopeUtils.inInterfaceOrAnnotationBlock(variableDef);
if (!inInterfaceOrAnnotationBlock) {
if (!hasProperAccessModifier(variableDef, varName)) {
```
optimize !!! Please think while you do coding and always minimize calculations.

**Comment by alexkravin** [comment]
1) It will be false-positive, why it should be? Isn't it better to have rare false-negatives than so obvious false-positives?

2) https://github.com/alexkravin/checkstyle/blob/8e4f71c1f2c8cd9f60438f04705ba2a7466f51f7/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L299

3) Pff.. I'm sorry squashed to one if condition

**Comment by romani** [comment]
>  It will be false-positive,

What does "will" mean, I need explanation why we do not have violation there.

> immutableClassCanonicalNames.clear();

What a reason ?

>  final DetailAST varNameAST = getVarNameAST(variableDef);
final String varName = varNameAST.getText();

I did not mean squashing, I mean lazy calculation of variables.

**Comment by alexkravin** [comment]
1) Because this type considered to be immutable

2) After applying '=' instead of addAll() no reason

3) ok

**Comment by romani** [comment]
Build failed at verify stage.

**Comment by romani** [comment]
> 1) Because this type considered to be immutabl

Ok. Please add a comment to following to explain it - it mislead me
```
if (!immutableClassCanonicalNames.contains(canonicalName)
                     && immutableClassShortNames.contains(shortName))
```

**Comment by alexkravin** [comment]
Added comment:

```
// If imported canonical class name is not specified as allowed immutable class,
            // but its short name collides with one of specified class - removes the short name
            // from list to avoid names collision
            if (!immutableClassCanonicalNames.contains(canonicalName)
                     && immutableClassShortNames.contains(shortName))
            {
                immutableClassShortNames.remove(shortName);
            }
```

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
