### PR TITLE
config: fix string to number issue in pr age check

### PR DESCRIPTION
**Pull request by rnveach**
Fix for PR age issue. I believe the issue is the number being returned is a string and not integer and so needs to be converted to an integer.
Minor changes to the displays for easier debugging.

### CODE REVIEW

**Comment by rnveach** [comment]
https://travis-ci.org/checkstyle/checkstyle/jobs/590175383#L301
> The PR is based on a master that is 5 commit(s) old.
The max allowed is 10.
eval of CMD is completed

CI is fixed now, no failures and I confirmed locally it will work the same with more than 10.

**Comment by rnveach** [comment]
Rebased on current master to pass CI.

**Comment by romani** [comment]
Ok to merge

**Comment by romani** [comment]
@pbludov , there are number of simple PR appeared in your queue, I would rather push them in next release ( tomorrow), please let me know know if you have no ability to review them in next 20 hours.

**Pull request merged**
