### PR TITLE
100% test coverage for ThrowsCountCheck, #1009

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by romani** [comment]
> ```@Test(expected = IllegalStateException.class)```

please never use "expected" argument in that annotation, as it produce stacktrace in output and it is not clear is it expected or not - please catch exception in method body, if no exception happen - fail a test.

**Comment by Vladlis** [comment]
done

**Comment by mkordas** [comment]
@romani - I've set up dedicated project on Github to show that JUnit's `expected` do not produce anything in logs: https://github.com/mkordas/expected-junit

**Comment by romani** [comment]
@mkordas , confirmed no stacktraces in logs/output, looks like that was my reference to old versions on Junit. Thanks a lot !

**Pull request merged**
