### PR TITLE
Issue #5496: fail CI if top master commit is too far back

### PR DESCRIPTION
**Pull request by rnveach**
Issue #5496

### CODE REVIEW

**Comment by rnveach** [comment]
Expecting travis to fail as top master commit is 15 behind.

**Comment by romani** [comment]
In code I see 10, let's have 10.

Ok, to test it, let's pause it for 10 PRs :)

**Comment by rnveach** [comment]
Travis currently looks like it is fast forwarding the commit to origin/master. This is why it currently says 0 commits behind master which is false. Code works on my local just fine.
https://travis-ci.org/checkstyle/checkstyle/jobs/589717878#L299

**Comment by romani** [comment]
It might be recent change, because if this was true in past, we would not required to ask rebase if CI failed, and just fixed in master.

Can we move this to other, less smart CI ?

**Comment by rnveach** [comment]
Validation is working now
https://travis-ci.org/checkstyle/checkstyle/jobs/589727959#L330
> The PR is based on a master that is 15 commit(s) old.
The max allowed is 10

Had to do a reset to the first child of the merge.

**Comment by romani** [comment]
If this is merge commit, so it diamond in dit history,  git should still keep in history from where author commit is parented. But how to get actual author commit, it is still question.

**Comment by rnveach** [comment]
Final form of the code is still working.
https://travis-ci.org/checkstyle/checkstyle/jobs/589730846#L293
> Merge: fb9736a 3173650
HEAD is now at 3173650 Issue #5496: fail CI if top master commit is too far back
The PR is based on a master that is 15 commit(s) old.
The max allowed is 10

Bash will undo merge commit if it finds one, otherwise it will work with HEAD commit if you are running CI command from local.

**Comment by rnveach** [comment]
>  if this was true in past, we would not required to ask rebase if CI failed, and just fixed in master

It may have been the less smart CIs that were the issue.
Also I am not sure how this travis would work if fast forward couldn't be done automatically (conflicts).

**Comment by romani** [comment]
Nice! You are bash hacker !

Ok to merge it.

**Comment by rnveach** [comment]
Rebased version passed as expected.
https://travis-ci.org/checkstyle/checkstyle/jobs/589731724#L298
> Merge: fb9736a bf65c78
HEAD is now at bf65c78 Issue #5496: fail CI if top master commit is too far back
eval of CMD is completed

**Pull request merged**
