### PR TITLE
minor: Enable checker framework to see results

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Enabling [Initialized Fields Checker](https://checkerframework.org/manual/#initialized-fields-checker)

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
> The Initialized Fields Checker warns if a constructor does not initialize a field.

Don't think this is really useful for checks as fields are initialized in `beginTree(..)`

**Comment by nrmancuso** [comment]
@Vyom-Yadav what are our options for individual violation suppression of this check? Also, is it possible to restrict the execution of one specific check to certain packages/file paths?

**Comment by Vyom-Yadav** [comment]
@nrmancuso I don't think integrating the initialization checker would be an easy task as we instantiate checks fields by either setter methods (properties) or by using `beginTree(..)`. Also, the check objects are created using reflection by `PackageObjectFactory`. I am going through the documentation to see if there is some way.

**Comment by nrmancuso** [comment]
>I don't think integrating the initialization checker would be an easy task as we instantiate checks fields

Agreed, this is why I asked about restricting this check to certain packages/ file path only. If we can restrict it to api and some other packages only, I think it is ok (although we still use some reflection there, too). If we have to suppress hundreds of errors for checks that we will never fix, I am not sure about the value of this check.

**Comment by romani** [comment]
> api

https://github.com/checkstyle/checkstyle/issues/12164#issuecomment-1236393577

**Comment by Vyom-Yadav** [comment]
Yes, we can.

**Pull request closed without merging**
