### PR TITLE
Issue #4867: Removed deprecated class BaseCheckTestSupport

### PR DESCRIPTION
**Pull request by subkrish**
Issue #4867 

This PR removes deprecated class BaseCheckTestSupport.

### CODE REVIEW

**Comment by rnveach** [comment]
wercker failure:
> NoErrorTest - XWiki
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:testCompile (default-testCompile) on project xwiki-commons-tool-verification-resources: Compilation failure: Compilation failure:
[ERROR] /pipeline/source/xwiki-commons/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/test/java/org/xwiki/tool/checkstyle/SinceFormatCheckTest.java:[28,39] cannot find symbol
[ERROR] symbol:   class BaseCheckTestSupport

@subkrish You must update wercker's commit hash to the commits we just had merged in xwiki.

**Comment by subkrish** [comment]
@rnveach Updated the commit hash in wercker. Done.

**Comment by rnveach** [comment]
new failure in xwiki:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:testCompile (default-testCompile) on project xwiki-commons-tool-verification-resources: Compilation failure: Compilation failure:
[ERROR] /pipeline/source/xwiki-commons/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/test/java/org/xwiki/tool/checkstyle/SinceFormatCheckTest.java:[41,28] cannot find symbol
[ERROR] symbol:   method createCheckConfig(java.lang.Class<org.xwiki.tool.checkstyle.SinceFormatCheck>)
[ERROR] location: class org.xwiki.tool.checkstyle.SinceFormatCheckTest
[ERROR] /pipeline/source/xwiki-commons/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/test/java/org/xwiki/tool/checkstyle/UnstableAnnotationCheckTest.java:[42,28] cannot find symbol
[ERROR] symbol:   method createCheckConfig(java.lang.Class<org.xwiki.tool.checkstyle.UnstableAnnotationCheck>)
[ERROR] location: class org.xwiki.tool.checkstyle.UnstableAnnotationCheckTest

https://github.com/xwiki/xwiki-commons/blob/36ebd6ae7cd8ca539619f0d28dc4461e51dcf3c4/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/test/java/org/xwiki/tool/checkstyle/SinceFormatCheckTest.java#L41
> this.checkConfig = createCheckConfig(SinceFormatCheck.class);

This method was renamed to `createModuleConfig`.
Changes to xwiki are incomplete.

**Comment by rnveach** [comment]
@subkrish @romani Method name change was done in this current release. We can't update wercker until 8.2 is released and changes made in xwiki.

@romani Should we wait or do the git patch approach?

**Comment by romani** [comment]
Please do a patch if that is simple. If not simple , we should postpone update till end of month, after release.

**Comment by romani** [comment]
we released 8.2 version, please rebase all your PRs to our latest master to avoid CI problems

**Comment by romani** [comment]
@subkrish  , do you still want to continue on this PR ?
if not , please let us know, smb else will continue this issue resolving. This active PR blocks issue to be resolved by smb else.

If no reply in next 2 weeks, I will mark PR as abandoned to let other contributors to continue.

**Comment by subkrish** [comment]
@romani @rnveach I will finish this PR in a couple of days. But before I do this one, I need to make a PR in `xwiki-commons` to update from 8.1 to 8.2 and then push this one.

**Comment by romani** [comment]
@subkrish , ones you make PR to xwiki, please rebase on our master to resolve another issue with wercker.

**Comment by romani** [comment]
@subkrish , please let me know if you experiencing problems with PR to xwiki.
Lets finish this long PR.

**Comment by subkrish** [comment]
@romani @rnveach `xwiki-commons` has already been updated to `8.2`, so I just updated `wercker.yml` to the latest commit in `xwiki-commons`.

**Comment by rnveach** [comment]
wercker froze on `NoExceptiontest - Hbase`. I am restarting it.

**Comment by rnveach** [comment]
wercker passed.

**Comment by subkrish** [comment]
@rnveach Great. I think with this PR the issue can finally closed.

**Comment by subkrish** [comment]
Yes, I'll remove those and push it again.

**Comment by subkrish** [comment]
@rnveach I have checked and made sure no file contains an instance of `BaseCheckTestSupport`. Please review.

**Comment by rnveach** [comment]
@romani Please review and merge.

**Comment by romani** [comment]
I relaunched appveyor, as it become green we are ok to merge.

**Pull request merged**
