### PR TITLE
Issue #10924: Update MethodParamPadCheck to use code points

### PR DESCRIPTION
**Pull request by MUzairS15**
Issue #10924: Updated MethodParamPadCheck to use code points

Diff Regression config: https://gist.githubusercontent.com/MUzairS15/32669c2249de13c50e3932982d828928/raw/90afd2693a5e8d65d846da75d433a5ad170edc18/config.xml

### CODE REVIEW

**Comment by MUzairS15** [comment]
```
src % cat config.xml Test.java                                 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name = "Checker">
    <property name="charset" value="UTF-8"/>

    <property name="severity" value="warning"/>

    <property name="fileExtensions" value="java, properties, xml"/>

    <module name="TreeWalker">
        <module name="MethodParamPad"/>
    </module>

</module>

class Test {
    public void test() {
        String s1 = "😂🎄😂🎄😂🎄😂🎄😂🎄😂🎄😂🎄da";java.lang.Integer.parseInt ("😆 🤛🏻 "); // violation but not reported

        String s2 = "dadsadasd";java.lang.Integer.parseInt ("hhaa"); // violation

    }
}
src % java -jar checkstyle-10.0-all.jar -c config.xml Test.java
Starting audit...
[WARN] /Users/shabana/Documents/OpenSource/CheckStyleTest/src/src/Test.java:5:60: '(' is preceded with whitespace. [MethodParamPad]
Audit done.

**Comment by MUzairS15** [comment]
Github, generate report

**Comment by nick-mancuso** [comment]
Please add case like https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b9fb2d5_2022061852/reports/diff/checkstyle/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyWithEmoji.java.html#L80 (previous false positive) to inputs.

**Comment by MUzairS15** [comment]
> Please add case like https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b9fb2d5_2022061852/reports/diff/checkstyle/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyWithEmoji.java.html#L80 (previous false positive) to inputs.

added

**Review by nick-mancuso — APPROVED** [review]

**Review by romani — APPROVED** [review]

**Pull request merged**
