### PR TITLE
Issue #2688: Fix OneStatementPerLine lambda validation

### PR DESCRIPTION
**Pull request by liscju**

### CODE REVIEW

**Comment by romani** [comment]
TC is pointing to problems that i fixed on weekends, please rebase your commit on latest code.

**Comment by liscju** [comment]
@romani - rebased

**Comment by romani** [comment]
1)
> TokenTypes.FOR_ITERATOR, TokenTypes.LAMBDA,

please do me a favour , please do place each token on its own line, please refactor existing lines.

2)
> lambdaStatementEnd and countOfSemiInLambda

not clear why it is missed in `public void beginTree(DetailAST rootAST) {`

3)
 please share diff reports.

**Comment by romani** [comment]
2)
>    lambdaStatementEnd and countOfSemiInLambda

Still an issue: not clear why it is missed in `public void beginTree(DetailAST rootAST) {` they have to be there.

3) 
please let me know if report generation is a problem for you.

**Comment by romani** [comment]
@liscju  , release will happen on Sunday, it would be good to finish this PR before release.

**Comment by liscju** [comment]
@romani 
i have problems with generating report. I would like to generate diff report for RxJava project(after trying with all projects "that contains a lot of lambda expression" and protonpack for which even simple checkstyle report generation was impossible due to OutOfMemoryException - with increased java heap size to 2 GB...) with ahsm and it constantly ends with OutOfMemoryException(even with increased heap size).

I wanted so , to sent result to repo on github, but files exceeds 100MB limits. What makes situation worse is that i cant see reports even locally - firefox is hanging....

First of all what should i do? Secondly i would like to note that generating reports before/after takes me much more time in general than development. I don't know if others have same opinion but if generating reports would be moved to some kind of continous integration server or sth it would save me really big amount of time i could have spent on actual development.

**Comment by romani** [comment]
> I would like to generate diff report for

yes, I run into this problem few days ago only. Nobody reported such problems before, unfortunately. Original author of diff-report is not responding. Most likely we need to grab his project to our hosting and fix it.

> I wanted so , to sent result to repo on github, but files exceeds 100MB limits. What makes situation worse is that i cant see reports even locally - firefox is hanging.
First of all what should i do? 

Yes, that happens then there are too much violations. To ease a problem it is good to use excludes for a project. To let checkstyle run against less amount of sources. See last parameter ("|" is delimiter) https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L43 

> Secondly i would like to note that generating reports before/after takes me much more time in general than development.

Thanks a lot for sharing feedback.
I am really sorry, that development process is not ideal :( . We do not have enough participants to make process more smooth, even we did huge progress this year to make it close to ideal.
diff-report tool just need to be fixed to support huge reports :( .
It would be good to have a automation script that takes commit and config and make a diff report ...

 
> but if generating reports would be moved to some kind of continous integration server or sth it would save me really big amount of time i could have spent on actual development.

Yes, this would be ideal, but there are no good plan for now on how to do this and there is no contributors to make at least first steps. Some ideas/dreams are described at https://github.com/checkstyle/checkstyle/wiki/Checkstyle-diff-report-genertion-service

----------------------

Please let me know if you have time to fork a ahsm tool, change it to work against XML files and generate diff report or automate diff-report generation by commit+config.
I appreciate your contributions.

PS:
html reports and diff-reports helped us a lot to catch regressions that non of UTs can do. Their roles in development is proven, even it is no a fun.

**Comment by liscju** [comment]
@romani first of all thanks for such a feedback, i have few issues to discuss:

1) 
```
Yes, that happens then there are too much violations. To ease a problem it is good to use excludes for a project. To let checkstyle run against less amount of sources. See last parameter ("|" is delimiter) https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L43
```

I will definetely try this, i am only fearing that i exclude too much that the rest of packages will not (for example) use lambda which are the most important for testing this issue.

2) 
```
Yes, this would be ideal, but there are no good plan for now on how to do this and there is no contributors to make at least first steps. Some ideas/dreams are described at https://github.com/checkstyle/checkstyle/wiki/Checkstyle-diff-report-genertion-service
```

I would be interested in doing this (especially to make my contributions more development oriented than testing), but probably most important for now would be making automation script and enhancing ahsm tool.

3) 
```
Please let me know if you have time to fork a ahsm tool, change it to work against XML files and generate diff report or automate diff-report generation by commit+config.
```

I am interested in doing this. I have forked ahsm tool, rebase master with branch with commit that changes project model from eclipse to maven. Im ready to enhance it but i probably needed more information what should i do. Maybe good place for such discussion would be under new issue in my ahsm fork(https://github.com/liscju/ahsm)?

**Comment by romani** [comment]
> I will definetely try this, i am only fearing that i exclude too much that the rest of packages 

You can use multiple lines for the same project in configuration:
```
guava-1|github|google/guava|master|**/**/test/**/*,**/guava-gwt/src-super/**/*,**/guava-tests/**/*,**/guava-gwt/test-super/**/*
guava-2|github|google/guava|master|**/**/src/**/*,**/guava/**/*
```
not ideal and not that convenient but smth that you can have right now.

> I would be interested in doing this (especially to make my contributions more development oriented than testing)

yes, This is why we did checkstye-tester. But it not finished in implementation.

> Maybe good place for such discussion would be under new issue in my ahsm fork

yes, lets do discussion on your fork. for now @attatrol is not responding. Eventually I would rather embrace it to checkstyle/contribution repo to maintain it officially from one source. Before you rush into implementation ,lets review what we need from this tool and see how to make it better. I think that doing diff base on HTML was not right approach, we need to use XML reports and generate HTML ourself (checkstyle-tester could generate xml reports together with html).

**Comment by liscju** [comment]
@romani 
```
yes, lets do discussion on your fork. for now @attatrol is not responding. Eventually I would rather embrace it to checkstyle/contribution repo to maintain it officially from one source. Before you rush into implementation ,lets review what we need from this tool and see how to make it better. I think that doing diff base on HTML was not right approach, we need to use XML reports and generate HTML ourself (checkstyle-tester could generate xml reports together with html).
```

Ok, so when you have some time please create new issue with every hint you think would be usefull to make this tool better. I totally agree that this tool eventually should be in checkstyle/contribution to prevent situation i encountered with PR that changed project model from eclipse to maven and author has not been responding.

**Comment by liscju** [comment]
@romani 
I invoked test on spring-framework, guava, and projects that has many lambda expressions and there is no difference between before/after:
http://liscju.github.io/issue2688/diff/checkstyle_merged.html

Report before - http://liscju.github.io/issue2688/before/site/checkstyle.html
Report after - http://liscju.github.io/issue2688/after/site/checkstyle.html

**Comment by romani** [comment]
issue for tool - https://github.com/checkstyle/contribution/issues/50

**Comment by romani** [comment]
CI is red, need to be fixed.

I highly recommend to run "mvn clean verify" on local before sending PR.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
