### PR TITLE
Issue #4934: Enforced WS before javadoc tags' arguments

### PR DESCRIPTION
**Pull request by ps-sp**
Issue #4934: Enforced WS before javadoc tags' arguments

### CODE REVIEW

**Comment by ps-sp** [comment]
[ANTLR report](https://4934-2-antlr.netlify.com/)

**NOTE:** I got error messages like: 
```
Unable to processPath /home/ps/workspace/checkstyle/contribution/checkstyle-tester/reports/savemaster/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.tree => /home/ps/workspace/checkstyle/contribution/checkstyle-tester/reports/diff/checkstyle/xref/savemaster/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.tree.html
```
while running `launch_diff_antlr.sh`. All such messages can be seen [here](https://gist.github.com/ps-sp/a0297e65a06d44507b4cfb81cdd4c568)

The diff reports look alright. There are two new violations in the patch.

The violation in `checkstyle` is for input `@see https://github.com/checkstyle/checkstyle/issues/1416` i.e string without quotes.

The violation in guava is for `{@link Builder#ImmutableTable.Builder()}` which is syntactically incorrect too.

**Comment by ps-sp** [comment]
[Sinlge javadoc check _(JavadocParagraph)_](https://4934-2-singlecheck.netlify.com/)

**Comment by ps-sp** [comment]
[**diff report** - _all javadoc checks_](https://4934-2-all-javadoc-checks.netlify.com/)

**Comment by ps-sp** [comment]
Wercker failure should be due to the same reason mentioned at [4550#issuecomment](https://github.com/checkstyle/checkstyle/pull/4550#issuecomment-312521474).

As @romani mentioned in [4752#issuecomment](https://github.com/checkstyle/checkstyle/issues/4752#issuecomment-323765046) we need a patch for `pgjdbc` repo, which should be used during `wercker` execution, until a permanent fix is made in the repo itself. PR for this: #5012

**Comment by romani** [comment]
you can update wercker in this PR, please close #5012 and make it in this commit.
All CIs should pass. Patch should be commented to reference PR to target repository to easily catch a time when it could be removed and it is intended to be not a permanent in wercker configuration.

**Comment by ps-sp** [comment]
>you can update wercker in this PR, please close #5012 

Done.

>and make it in this commit.

I've added another commit making easy to revert later. If that is a mistake then please let me know and I will fixup the commits.

>Patch should be commented to reference PR to target repository to easily catch a time...

Done.

**Comment by ps-sp** [comment]
@romani 
All tests have passed please have a look.

**Comment by romani** [comment]
@ps-sp , you PR to pjdbc is merged , so please remove you first commit, or update werker to use latest code .

**Comment by ps-sp** [comment]
@romani 
>so please remove you first commit

Done.

**Pull request merged**
