### PR TITLE
Issue #8264: Increase font size of website

### LINKED ISSUE #8264: Increase font size for website
As menttioned [here](https://github.com/checkstyle/checkstyle/issues/8244#issuecomment-632704253) the general font size fo the documentation is an issue. If this issue is approved I can start a PR.

### PR DESCRIPTION
**Pull request by jo2**
fix #8264 

preview: [https://jo2.github.io/checkstyle-font-size/](https://jo2.github.io/checkstyle-font-size/)

### CODE REVIEW

**Comment by strkkk** [comment]
CI is failing, line is longer than 100 chars

**Comment by jo2** [comment]
It now fails on unknown word 'navcolumn' which is a html id, but was introduced before my changes. I can refactor it in every occurence to 'navColumn' which should work (like 'leftColumn') or I can add it to the list of whitelisted words. What do you think?

**Comment by rnveach** [comment]
While the font size is easier to read, compared to other normal sites it will look big. Github uses 14px font, while we had 13px. New site's font is 17px. Original issue specified atleast 120%, which would have done 15px, and at most 130% which would is 17px (rounded).

Normal text size was increased but headers remain the same font. Menu items were increased, but left padding remains the same so it is less space with the larger font. Also in menu, `>` did not increase in size relative to font, so it looks like it shrunk and is to the bottom of the text. Date of release's font on release notes page remains small while other font is larger.

I am not fully sure about the larger font.

Why wasn't something like the following done in CSS instead?
````
body {
  font-size: 110%;
}
````

**Comment by jo2** [comment]
@rnveach I'll add what you've mentioned and update the preview. I'll also add a preview with 15px font size.

I used an absolute fontsize because otherwise it is a pain to adjust all effected elements. We can't just use `body { font-size: 125%; }` because there are some fix font-sizes set by maven-site-plugin ( for example for `td` or `li` elements) which would override the font-size set on the body. We could use css `!important`, however that is really bad practice and makes future changes much more difficult.

A second reason for a fixed font-size using px is that if more than one css-selector with `font-size: 125%` are triggered, the font size is also increased by 1.25*1.25=1.5625 instead of 1.25 which can result in side effects in this and future PRs and unexpected behaviour.

However if you want, I can try to hack something together using a percentage value. Please let me know.

**Comment by jo2** [comment]
Here are the links:
* [17px](https://jo2.github.io/checkstyle-font-large/)
* [15px](https://jo2.github.io/checkstyle-font-medium/)

**Comment by romani** [comment]
I like large font, it is easier to read.

**Comment by rnveach** [comment]
Hacking isn't needed.

I still think 17 might be too big compared to other sites.

**Comment by romani** [comment]
Let's finalize. @strkkk , @pbludov , please share preference on font size

**Comment by romani** [comment]
@jo2 , please share your preference on font size also

**Comment by strkkk** [comment]
As for me 15 looks better

**Comment by jo2** [comment]
I also think, 15px looks better, because with 17px there is less information in one view and the section headings are nearly as big as the page heading in the logo.

**Comment by romani** [comment]
@jo2 , please update PR to have font 15. Please fix CI, lets merge this PR.

**Comment by jo2** [comment]
During pulling new commits from checkstyle/master i somehow closed this pr. I'll open a new one and will link this pr in the new pr

**Pull request closed without merging**
