### PR TITLE
Add BooleanExpressionComplexity into checkstyle_checks.xml

### PR DESCRIPTION
**Pull request by MEZk**
@romani
According to issue #1052 property max of BooleanExpressionComplexity has been set to 7. 
Accordign to issue #945 BooleanExpressionComplexity has been added into checkstyle_checks.
To avoid BooleanExpressionComplexity's violations a refactoring of checksyle code has been performed.

### CODE REVIEW

**Comment by romani** [comment]
1)
> Arrays.binarySearch(

please do sorting of array, do not rely on a user to sort it, it is error prone.

2)
>     private static boolean hasProtectedModifier(boolean protectedAllowed, String variableScope) {
        return protectedAllowed && "protected".equals(variableScope);
    }

hasProtectedModifier is general name that judging by name do check of tree only and should tell truth no matter what options are user defined. Lying by name is major sin , far more serious then complicated boolean expression.
The  same for other new methods.

**Comment by MEZk** [comment]
@romani 
1) Done.
2) Corrected.
3) Done.

**Comment by romani** [comment]
1)
>            final int[] defTokensTypes = {
                TokenTypes.CTOR_DEF, ...................
                TokenTypes.ANNOTATION_DEF,
            };
            Arrays.sort(defTokensTypes);

so now you are wasting CPU by creating array and sorting array each time method is called. previous implementation was extremely quick in comparison to that. Performance should stay almost the same.

**Comment by MEZk** [comment]
@romani 
But before I added ```Arrays.sort(...)``` All arrays had been already sorted in ascending order for binary search. So what is a problem?

**Comment by romani** [comment]
because you need to do it ones in a class, wasting perfomance to make code follow some practice is not good.

But ideally that shows that Check is not correctly working and that is false positive that need to be resolved in Check to skip (we need to open issue on that). Till issue is resolved we need to suppress that Check on that Classes to not bother us with misleading requests to refactor. Find me in a call if need more explanations.

**Comment by romani** [comment]
please rebase you commit on latest master, appveyor problem is caused by by in accurate commit, that is already fixed.

**Comment by MEZk** [comment]
@romani 
For JavadocTagInfo I've made arrays as static fields of enum and also in static initializer block I've done sorting of the arrays so that the arrays will be loaded in memory once and sorting will be done once too.

I've done refactoring of hasProperAccessModifier in VisibilityModifierCheck.

**Comment by romani** [comment]
please rebase a commit to let me merge easily.

**Comment by MEZk** [comment]
@romani 
rebased

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
