### PR TITLE
Solution to Magic Number is not detected properly #1266

### PR DESCRIPTION
**Pull request by Bhavik3**

### CODE REVIEW

**Comment by Bhavik3** [comment]
@romani 
Have doubt about two lines as posted in issue.
should they be detected or not?
If yes,then there is not any logical way to do so.

**Comment by romani** [comment]
Please make single return point from methods

**Comment by Bhavik3** [comment]
@romani 
There are already such methods where multiple return statements are present.
I will do separate PR to make it one return statement.

**Comment by romani** [comment]
You add two new methods, both of them have that problem, so fix it now in new code, rest could be in separate PR

**Comment by Bhavik3** [comment]
@romani 

Done

**Comment by romani** [comment]
please see https://github.com/checkstyle/checkstyle/issues/1266#issuecomment-119058632

**Comment by romani** [comment]
I do not see any changes for new option.

**Comment by Bhavik3** [comment]
Actually, I was telling him (issue reporter, he was online so), how will he prefer by looking at PR ...
Anyway, I will enforce new option: IgnoreMethodCall, IgnoreCtorCall
or should I keep them together?

**Comment by romani** [comment]
no, please turn ALLOWED_PATH_TOKENTYPES into Check option (string , delimited by ",", as "tokens") with default values that that are in that array.

I do not like name of that array, but you can name option is as you think it should be and I come up with my variant in several hours - the most clear variant will be used.

**Comment by DTecheira** [comment]
Sorry, i was a little bussy, and I cant communicate very well in english

I think that constant are fine to be ignored

    public static final DummyObject DUMMY = new DummyObject(63L);
    
but defined this in a method should be detected.

    public void test() {
        final DummyObject dummyObject2 = new DummyObject(63L);
        final long value = dummyObjectNumber2.getLongX3(65L);
    }

**Comment by Bhavik3** [comment]
Done
Can't think good name for option.

**Comment by romani** [comment]
1)
> allowedTokensBetweenMagicNumberAndConstDef

What about "waiverStatementParentToken" or ""waiverParentToken"" ? as we search in parents only till end of statement(const definition)

2) please update javadoc and xodc for new option and examples of configuration

3) please generate reports against big projects with your new option and see what default value of it should be. Please do analysis yourself and share results.

**Comment by romani** [comment]
@Bhavik3 , do you have any progress with this issue ?

**Comment by Bhavik3** [comment]
@romani 

I will be busy here for some days. I will not be able to work on it for some days. maybe a week.

**Comment by romani** [comment]
@Bhavik3 , thanks for letting me know.

**Comment by romani** [comment]
@Bhavik3 , do you have plans to finish ?

**Comment by Bhavik3** [comment]
Actually, Placements are going on in my college. It will take few more
days. Busy right now and hard to get time to finish.

If it is that important then let me know...  I will try to make it done.

**Comment by romani** [comment]
it is ok, take your time, I will pin you in one week again.

**Comment by Bhavik3** [comment]
@romani 
Done (have a look on xdocs and javadoc)

[Finally placement is done. got placed at LinkedIn]

**Comment by romani** [comment]
What point is done ?

**Comment by Bhavik3** [comment]
1)
option renamed to "waiverParentToken"

2)
Javadoc, xdoc updated.
Have a look.

3) 
report after changes: http://bhavik3.github.io/After/checkstyle.html
report for  exceptions: http://bhavik3.github.io/Exceptions/checkstyle.html
No Exceptions....

**Comment by romani** [comment]
1)
>         int i = 0;
        for (final String token : tokens) {

please move "i" in scope of FOR, in that case FOR will be a bit longer but "i" will be inside FOR scope. Scope of variables need to be minimized.

2)
> To configure check so that it checks for method call and constructor call

That description does not correspond to configuration example. Please add a bit more examples (up to 5) to that code chunk.

3)
> Warnings: 100431 (from report)

have you reviewed all that violations ? What that report tell about ? 
please select Guava (or any other) only and test on default configuration before and after changes - reports should be identical. After that generate one more report with non default config to validate each violation (no more then 50 violations) and please confirm that all of them are valid.

**Comment by Bhavik3** [comment]
1)
Done
2)
Five examples are added.
3)
I have not make any changes for default config, so I didn't generate report for default. 
Default config:
Before: http://bhavik3.github.io/Before/checkstyle.html
After: http://bhavik3.github.io/After/checkstyle.html
Both are Identical.....

Non Default Config:
http://bhavik3.github.io/NonDefaultConfig/checkstyle.html
all violations are fine.

**Comment by romani** [comment]
1) 
> Non Default Config:

I do not see description of used config in HTML report, see example how that should look like 
http://mezk.github.io/guava_6.9-SNAPSHOT_alone_or_singleline/checkstyle.html

2)
> Five examples are added.

Right now you have  too much almost the same example by config.
please be attentive, I asked you to create one example block with few statements in it.
Should be smth like:
```
       class TestMethodCall {
          public void method2() {
              final TestMethodCall dummyObject = new TestMethodCall(62);    //violation
              final int x = 3*4    //violation
              final int x2 = 3 + 4    // ok, as waiver is PLUS
             OTHER EXAMPLES of violations and ok code due to waiver option
          }
       }
```

**Comment by Bhavik3** [comment]
1)
I don't know why config is not showing. I am using latest checkstyle-tester.
2)
sorry for that. I misunderstood it. Done

**Comment by romani** [comment]
By default it use google config https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/pom.xml#L16 , please change it to your config, push to github to share with me exact code, generate report.

**Comment by Bhavik3** [comment]
I know by default it uses google config. By default i mean was default config of MagicNumber.
My checkstyle tester: https://github.com/Bhavik3/contribution/tree/MagicNumber/checkstyle-tester

**Comment by romani** [comment]
1) 
> final int x = int(3.4)    //ok as waiver is TYPECAST

Are sure that such code is compilable ?

2)
>          final int x = 3*4    //violation
          final int y = 3/4    //ok as waiver is DIV

please add spaces before and after "*" and "/" example need to ease to read too.

**Comment by Bhavik3** [comment]
1)
changed to final int x = (int)3.4
2)
Done
4)
waiverToken comes into picture when there is a constant definition in parent statements. here "w.spanX = 4;" is not a constant definition. 
So, according to me. it is fine.

**Comment by romani** [comment]
> waiverToken comes into picture when there is a constant definition in parent statements. here w.spanX = 4; is not a constant definition. 

hmmm, ok, please define what is constant definition and what is not constant definition, with examples.

**Comment by Bhavik3** [comment]
1)
It is constant def:
`final int x = 5;
while, non-const def:
`int x = 5;

Here, in non-const def, According to your argument, ASSIGN is as waiver then we should not detect it. that does not make sense, it is clear from here.

2)
According to MagicNumberCheck, if we declare magic number as `final`, it is fine. That is why we need to check weather it is constant def or not.

Now, comes to particular case:
>> 31 w.spanX = 4;
here, `spanX` is static declaration. if it is const also then, statement is compilation error. and if it is not const, we dnt need to check for `waiverToken`.

**Comment by romani** [comment]
1)
> According to MagicNumberCheck, if we declare magic number as final, it is fine.

please describe that definition in javadoc/xdoc to let user know what we mean as constant definition.


2)
>It is constant def:
final int x = 5;
while, non-const def:
int x = 5;

if "final" is waiver for the whole statement why we need special option for that ?

> here, spanX is static declaration. if it is const also then, statement is compilation error. and if it is not const, we dnt need to check for waiverToken.

it is not clear for me why we mix final and static, static is not a constant at all. Please try to explain one more time.

**Comment by Bhavik3** [comment]
2)
>> if "final" is waiver for the whole statement why we need special option for that ?

Here, question is what happen when it is not final. then we check for waiverToken. like ` int x = 3 * 4` and waiver is `*`, we do not detect it. To provide that flexibility, we need special option. 

>> it is not clear for me why we mix final and static, static is not a constant at all. Please try to explain one more time.

static variable always initialized with some value. and if it is constant (final) also, then statement like, ` w.spanX = 4;` does not make sense at all, because we can not change that value as it is constant.

**Comment by romani** [comment]
ok , I reviewed whole Check.....

1) 
> It is fine to have one constant defining multiple numeric literals within one expression:

We need to explain use what is "constant definition". "Constant definition is any variable/filed that has 'final' modifier" - please this text above text that I quoted.

2)
>  static final double SPECIAL_DIFFERENCE = 4 - Math.PI;
  static final Border STANDARD_BORDER = BorderFactory.createEmptyBorder(3, 3, 3, 3);
  static final Integer ANSWER_TO_THE_ULTIMATE_QUESTION_OF_LIFE = new Integer(42);</code>

please remove static from that variable and change names to CamlCase. Do not mislead user that Check searching for "static final", Check do distinguishing only by FINAL - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java#L247.

3)
>           int i = i + 1; // no violation
           int j = j + 8; // violation

please change 8 to "0.5" and put "no violation" to it to show in example that extended option work.

4) 
> waiverParentToken

whole misunderstanding is in wrong name, name should be clear enough to understand how it works without reading a code. Rename it to "constantWaiverParentToken".

5)
> ASSIGN,ARRAY_INIT,EXPR, UNARY_PLUS, UNARY_MINUS, TYPECAST, ELIST, DIV, PLUS

That is also not clear to new user (That even mislead me). Please extend example with usage of each TOKEN from that list, user need to see why ASSIGN or ELIST are required. We disclose tiny nuance of our implementation so we have to be clear to user.

6)
> static variable always initialized with some value. and if it is constant (final) also, 

Static is about scope of variable, final is about re-initialization. So only final is a criteria for constant like definitions.

**Comment by Bhavik3** [comment]
1)
Done
2)
Done
3)
Done
4)
Done
5)
Done

**Comment by romani** [comment]
you forgot to update javadoc and xdoc for new name of waiverParentToken

**Comment by Bhavik3** [comment]
Done

**Comment by Bhavik3** [comment]
Done

**Comment by romani** [comment]
thanks a lot for your persistence to make it happen.

merged as FF

**Pull request closed without merging**
