### PR TITLE
ImportOrderCheck. Fix separation for static imports #1398

### PR DESCRIPTION
**Pull request by ivanov-alex**

### CODE REVIEW

**Comment by romani** [comment]
1) 
```
             // This check should be made more robust to handle
             // comments and imports that span more than one line.
```

please remove that lines , they tell nothing useful .

2) 
> private void doVisitToken(FullIdent ident, boolean isStatic, boolean previous) {

please make simple refactoring and instead of "indent" put in method "name" and "line". 
Method should receive only that data that he use for calculation of result or doing process.


3)
>  This option is helping in reconciling of this Check and other tools like
  Eclipse's Organize Imports feature.

Does this Check compliant now(after fix) with Eclipse ?

4) 
> private boolean isAlphabeticallySortableStaticImport(boolean isStatic) {

remove IF and return result directly by "return".

**Comment by romani** [comment]
appveyor is passing for master, please recommit smth in branch to re-trigger CIs builds. From this moment I expect all CIs to be green.

**Comment by ivanov-alex** [comment]
1) 
Done
2) 
Disagree. FullIdent is nothing more then name+line+column. So the method uses almost all the fields of the object. Additionally, current version is more compact, making code easier to read.
3) 
Well, in many cases it is compliant. However, Eclipse behaviour is not 100% transparent from my point of view.
For example, on my workstation I have Eclipse configuration `java,javax,org,com`. Based on that I expect all the other imports to be listed in the end of the list.

However, when I played a bit with Organize Imports to insert missing import statements for a set of objects, some were added not where I expect them:
```java
import static com.puppycrawl.tools.checkstyle.checks.imports.ImportOrderCheck.MSG_SEPARATION;

import java.io.File;

import javassist.ClassPath; //position doesn't match settings
import junit.extensions.TestSetup; //position doesn't match settings

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.internal.util.reflection.Whitebox;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import antlr.CommonHiddenStreamToken; //position doesn't match settings

import com.puppycrawl.tools.checkstyle.api.DetailAST;
import com.puppycrawl.tools.checkstyle.api.TokenTypes;
```
4) 
Done

**Comment by romani** [comment]
> some were added not where I expect them

Looks like a bug in Eclipse, try to remove all imports and let Eclipse organize them if does not match a pattern that we setup in preferences lets search for bug in Eclipse tracking system if nothing found lets report an issue.

**Comment by romani** [comment]
> || getAbstractOption() == ImportOrderOption.BOTTOM);

Please intend that line +4 , as that is not the same level of expression as previous &&

**Comment by ivanov-alex** [comment]
> Looks like a bug in Eclipse, try to remove all imports and let Eclipse organize them if does not match a pattern that we setup in preferences lets search for bug in Eclipse tracking system if nothing found lets report an issue.

Yes, I was trying to remove all imports. I will check for Eclipse defects

> Please intend that line +4 , as that is not the same level of expression as previous &&

Done

**Comment by romani** [comment]
merged as FF

**Comment by ivanov-alex** [comment]
Eclipse has a defect for this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=352891
Issued in 2011 and still in NEW

**Pull request closed without merging**
