### PR TITLE
Issue #9267: Stackoverflow error on deeply concatenated strings

### PR DESCRIPTION
**Pull request by timurt**
https://github.com/checkstyle/checkstyle/issues/9267

### CODE REVIEW

**Comment by rnveach** [comment]
My faith was not misplaced @timurt . :)

If this resolves the issue, then it seems to me we can revert https://github.com/checkstyle/checkstyle/commit/bd84b4e99b95850af89dea1a6c14f104243ba298 .
We should confirm this is fixed by running the tests through a small stack run as CI was not consistent enough to show issue.

**Comment by rnveach** [comment]
````
[ERROR] Tests run: 68, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.661 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.xpath.XpathMapperTest

[ERROR] testManyNestedNodes  Time elapsed: 0.436 s  <<< ERROR!

java.lang.StackOverflowError
````

**Comment by romani** [comment]
@timurt , please continue PR.

**Comment by timurt** [comment]
@romani @rnveach sorry for delay, i will continue working on this issue, i think i need to analyze saxonica sources more deeply :|

**Pull request closed without merging**
