### PR TITLE
Issue #12956: update branch all-ci-disabled

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #12956: update branch all-ci-disabled

Patch of orignal branch:
[all-ci-disabled-998c65dc977d457eeb645c91834018655280ef63.txt](https://github.com/checkstyle/checkstyle/files/11543915/all-ci-disabled-998c65dc977d457eeb645c91834018655280ef63.txt)

### CODE REVIEW

**Comment by Kevin222004** [comment]
@stoyanK7 Yes it is related to https://github.com/checkstyle/checkstyle/issues/12956 let me update commit message

**Comment by romani** [comment]
Hmm, too massive.
Maintainers might need to do:
Copy patch on a side.
remove branch completely
Create branch from head of master

Kevin use branch and extra changes, introduce new single commit that do all disablement. Such commit will be massively used in others PR by cherry pick.

**Comment by Kevin222004** [comment]
@romani might silly question but should I create a pr on the master branch or the new branch when it was created by the maintainer

**Comment by romani** [comment]
one more patch is applied based on your last commit:
```
git rm .github/workflows/actionlint.yml
git rm .github/workflows/bump-license-year.yml
git rm .github/workflows/bump-version-and-update-milestone.yml
git rm .github/workflows/checker-framework.yml
git rm .github/workflows/diff-report.yml
git rm .github/workflows/error-prone.yml
git rm .github/workflows/release-copy-github-io-to-sourceforge.yml
git rm .github/workflows/release-maven-perform.yml
git rm .github/workflows/release-maven-prepare.yml
git rm .github/workflows/release-new-milestone-and-issues-in-other-repos.yml
git rm .github/workflows/release-publish-releasenotes-twitter.yml
git rm .github/workflows/release-update-github-io.yml
git rm .github/workflows/release-update-github-page.yml
git rm .github/workflows/release-update-xdoc-with-releasenotes.yml
git rm .github/workflows/release-upload-all-jar.yml
git rm .github/workflows/release.yml
git rm .github/workflows/releasenotes-gen.yml
git rm .github/workflows/run-link-check.yml
git rm .github/workflows/set-milestone-on-referenced-issue.yml
git rm .github/workflows/shellcheck.yml
```

**Comment by romani** [comment]
so we simply removed all yml files from repo:
```
$ git log -1 --stat
commit 7e260639f0254c22a5365e9a7f350d91eeba8aa1
Author: Ro......ru>
Date:   Tue May 23 05:51:46 2023 -0700

    infra: disable all CI

 .circleci/config.yml                                                  | 287 ----------------------------------------------------------------------------------
 .cirrus.yml                                                           |  59 -----------------
 .github/dependabot.yml                                                |  13 ----
 .github/workflows/actionlint.yml                                      |  25 --------
 .github/workflows/bump-license-year.yml                               |  42 ------------
 .github/workflows/bump-version-and-update-milestone.yml               |  55 ----------------
 .github/workflows/check-pr-description.yml                            |  25 --------
 .github/workflows/checker-framework.yml                               |  65 -------------------
 .github/workflows/codeql-analysis.yml                                 |  66 -------------------
 .github/workflows/diff-report.yml                                     | 253 ------------------------------------------------------------------------
 .github/workflows/error-prone.yml                                     |  46 -------------
 .github/workflows/no-exception-workflow.yml                           |  48 --------------
 .github/workflows/pitest.yml                                          |  98 ----------------------------
 .github/workflows/release-copy-github-io-to-sourceforge.yml           |  47 --------------
 .github/workflows/release-maven-perform.yml                           |  63 ------------------
 .github/workflows/release-maven-prepare.yml                           |  54 ----------------
 .github/workflows/release-new-milestone-and-issues-in-other-repos.yml |  61 ------------------
 .github/workflows/release-publish-releasenotes-twitter.yml            |  49 --------------
 .github/workflows/release-update-github-io.yml                        |  54 ----------------
 .github/workflows/release-update-github-page.yml                      |  45 -------------
 .github/workflows/release-update-xdoc-with-releasenotes.yml           |  50 ---------------
 .github/workflows/release-upload-all-jar.yml                          |  49 --------------
 .github/workflows/release.yml                                         |  90 --------------------------
 .github/workflows/releasenotes-gen.yml                                |  30 ---------
 .github/workflows/run-link-check.yml                                  |  33 ----------
 .github/workflows/set-milestone-on-referenced-issue.yml               |  32 ----------
 .github/workflows/shellcheck.yml                                      |  27 --------
 .github/workflows/site.yml                                            | 176 --------------------------------------------------
 .semaphore/semaphore.yml                                              | 107 -------------------------------
 .travis.yml                                                           |  62 ------------------
 appveyor.yml                                                          |  75 ----------------------
 azure-pipelines.yml                                                   | 176 --------------------------------------------------
 32 files changed, 2362 deletions(-)
```

no result found by:
```
 ~/java/github/checkstyle/checkstyle [all-ci-disabled L|✔] 
 $ find . -name *.yml
✔ 
```

**Comment by romani** [comment]
I closing this PR, let open new PR to rest no CI and diff-report execution.

**Pull request closed without merging**
