### PR TITLE
Remove unused parameters. #1555

### PR DESCRIPTION
**Pull request by mkordas**
Fixes some `UnusedParameters` inspection violations.

Description:
>This inspection reports parameters that are not used by their methods and all method implementations/overriders.

### CODE REVIEW

**Comment by romani** [comment]
please rebase that PR.

**Comment by romani** [comment]
@mkordas , please rebase PR

**Comment by mkordas** [comment]
@romani, rebased

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
