### PR TITLE
Issue #3254: UT to verify all property types and values in XDocs

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3254

Some field names were changed to align with their setter names.
Some field types were changed to align with their uses.

All xdoc updates are result of new validation.

### CODE REVIEW

**Comment by rnveach** [comment]
@romani I may need some help with making IntelliJ happy and removing some of these suppressions.

Original IntelliJ errors: https://teamcity.jetbrains.com/viewLog.html?buildId=1271261&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsPullRequest

**Comment by romani** [comment]
Matching idea violation message to it's rule, is far from fun, we have it a lot during summer, usually googling helps by message .

**Comment by rnveach** [comment]
IntelliJ should be happy now. It is for me locally.

**Comment by romani** [comment]
from TC:
```
src/test/java/com/puppycrawl/tools/checkstyle/internal
 XdocsPagesTest.java (1)
816: getModulePropertyExpectedValue() Redundant suppression
```

please remove suppression, i might be matter of different IntelijIdea versions.

**Comment by rnveach** [comment]
The problem is there are 4 suppressions there (1 recently added) and according to original TC at https://github.com/checkstyle/checkstyle/pull/5402#issuecomment-354454243 they all are needed.

**Comment by rnveach** [comment]
redundant suppression appears with `suppression 2 diff` but goes away with `suppression 2`...

**Comment by rnveach** [comment]
I squashed commits and TC was passing. So it should be good now.
I had to convert a method suppression to an inline one.

**Pull request merged**
