### PR TITLE
Issue #13772: IllegalImport with class pattern fails on the static im…

### PR DESCRIPTION
**Pull request by aayushRedHat**
Related: https://github.com/checkstyle/checkstyle/issues/13772
Helping:  https://github.com/checkstyle/checkstyle/pull/13960 Pull request

### CODE REVIEW

**Comment by romani** [comment]
@aayushRedHat, what PR you want to be merged? It will be just definition what user name will go Git history as author, we don't care.

**Comment by AayushSaini101** [comment]
> @aayushRedHat, what PR you want to be merged? It will be just definition what user name will go Git history as author, we don't care.

Please use @AayushSaini101 , I will use aaayushRedHat as a helper

**Comment by romani** [comment]
Please convert PR to draft, to make it more visual that it is not for merge

**Comment by aayushRedHat** [comment]
> Please convert PR to draft, to make it more visual that it is not for merge

Done

**Pull request closed without merging**
