### PR TITLE
test: SummaryJavadoc perform regression testing

### PR DESCRIPTION
**Pull request by relentless-pursuit**
This PR aims to do regression-testing. 

Diff Regression config: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example3/config.xml

Diff Regression projects: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example3/list-of-projects.properties

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Action for example1: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example1/list-of-projects.properties

**Comment by relentless-pursuit** [comment]
Testing for `SummaryJavadoc/Example1`

Config file: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024163935/reports/diff/index.html

Project file: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example1/list-of-projects.properties

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024163935/reports/diff/index.html

Action: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024163935/reports/diff/index.html

Time: 44 mins 48 secs

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9355525333/job/25751059223

**Comment by relentless-pursuit** [comment]
Testing for SummaryJavadoc/Example1

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example2/config.xml

Project file: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example2/list-of-projects.properties

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024193021/reports/diff/index.html

Action: https://github.com/checkstyle/checkstyle/actions/runs/9355525333/job/25751059223

Time: **45 mins 7 secs**

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9356290759/job/25753411517

**Comment by relentless-pursuit** [comment]
Testing for `SummaryJavadoc/Example3`

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example3/config.xml

Project file: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example3/list-of-projects.properties

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024200824/reports/diff/index.html

Action: https://github.com/checkstyle/checkstyle/actions/runs/9356290759/job/25753411517

Time: **23 mins 40 secs**

**Comment by relentless-pursuit** [comment]
Total time: **2:53:35**

**Comment by relentless-pursuit** [comment]
@Romani, i calculated the cumulative time for 3 examples

**Comment by romani** [comment]
I changed title.
Closing

**Pull request closed without merging**
