### PR TITLE
Issue #13672: Kill mutation for JavadocMethod-5

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13672: Kill mutation for JavadocMethod-5

-----

# Check :- 
https://checkstyle.org/checks/javadoc/javadocmethod.html#JavadocMethod

-----

# Mutation 

https://github.com/checkstyle/checkstyle/blob/90974261a22f04f4186d69bee7e3c49cc1044fe1/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L210-L217
-----

# Explaination

Updated util class 

-----

# Regression :- 

-----

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/df2ff7a8f9969bb2c68d7251a97ffa8b/raw/6a4e81a624fa36483f23b0adcf1fc513ca6df350/JavadocMethod.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/360a95ed7bb60d7a0956e531199d484c4d6f6617/test-projects.properties
Report label: Sept-15-Regression-1

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by nrmancuso** [comment]
@Kevin222004 what do we need to do to get this PR out of draft mode?

**Comment by Kevin222004** [comment]
@nrmancuso This gone delayed because it is decided to cover it later but I will mark them for review mostly in few days after analysis

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
Please fix CIs

**Comment by romani** [comment]
Checker stit failing

**Comment by Kevin222004** [comment]
@romani ci green

**Review by romani — APPROVED** [review]
Good, know pattern where pitest highlights non functional overprotection of collection usage.

**Pull request merged**
