### PR TITLE
Enhance French translation

### PR DESCRIPTION
**Pull request by olivier-maury**
spelling: Correct French translation of design.forExtension message

### CODE REVIEW

**Comment by pbludov** [comment]
@olivier-maury please do
`git commit --amend -m "spelling: Correct French translation of design.forExtension message"`
then re-push.

This is necessary to help the release note generator do its job. Without this prefix, the generator will fail with the error "I don't know which section to put this commit in".

**Comment by romani** [comment]
@olivier-maury , we appreciate your help, but please squash all commits in one
and pull latest master code from us. It will make CI green.

**Comment by romani** [comment]
@olivier-maury , this page helps to git commands - https://checkstyle.org/beginning_development.html

**Comment by strkkk** [comment]
@olivier-maury please squash your commits into one

**Pull request merged**
