### PR TITLE
Issue #7616: Add code example for VisibilityModifier check

### PR DESCRIPTION
**Pull request by 0xbakry**
Issue: https://github.com/checkstyle/checkstyle/issues/7616

https://checkstyle.org/config_design.html#VisibilityModifier

This PR adds a code example to the documentation of the VisibilityModifier check.

Example 1: With default properties of VisibilityModifier.

Web Page:
Screenshot from 2023-03-02 20-32-24

CLI:
Screenshot from 2023-03-02 20-31-11

### CODE REVIEW

**Comment by romani** [comment]
Please fix commit message run `mvn verify` on your local .

Please add java code example for each config.

**Comment by 0xbakry** [comment]
@romani I'm trying to commit with message but it still comiting the old one. 
I will add them just after commiting this with no problem, sorry for delay i'm working on them.
thanks.

**Comment by 0xbakry** [comment]
@romani Now when i'm trying `mvn verify` i got these errors:
package javax.xml.bind does not exist
cannot find symbol symbol: variable DatatypeConverter
location: class com.puppycrawl.tools.checkstyle.PropertyCacheFile

Any hints? 
Thanks,

**Comment by romani** [comment]
https://checkstyle.org/beginning_development.html#Starting_Development

Google in Internet how to change commit message and push with force to GitHub

**Comment by 0xbakry** [comment]
@romani I changed the commit message.
But now i'm still trying `mvn verify` and get the same errors:
"package javax.xml.bind does not exist"
"cannot find symbol symbol:   variable DatatypeConverter"
I found that i need to update **pom.xml**  by adding the **JAXB dependency** and this seems not good to build the project.
I even created a new virtual machine then tried to re-build but got the same errors.
I would be thankful if you told me any hints to solve the problem.
Thanks,

**Comment by 0xbakry** [comment]
Here the whole log:
https://gist.github.com/0xbakry/8c52c95642e1f4b38df8b4a4cf192b9f

For the detection i got that there's a problem in ***JavaDoc comments***, am i right? 
I looked at the whole ***config_design.xml*** to figure out and simulate the comments style but still confused about the error.

**Comment by romani** [comment]
Yes, run this failing test in your IDE to spot a problem.

**Comment by romani** [comment]
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (ant-phase-compile) on project checkstyle: An Ant BuildException has occured: The following error occurred while executing this line: [ERROR] /home/bakry/GSoC/checkstyle/config/ant-phase-compile.xml:13: Javadoc failed: java.io.IOException: Cannot run program "javadoc": error=2, No such file or directory [ERROR] around Ant part ...<ant antfile="config/ant-phase-compile.xml"/>... @ 7:48 in /home/bakry/GSoC/checkstyle/target/antrun/build-main.xml`

Something wrong with your jdk, you need to install javadoc tool. And it is weird why ant is so misbehaving on your local, it shouldn't be executed like this.

**Comment by 0xbakry** [comment]
> 

I installed **javadoc** tool but got new error, here the log file:

**Comment by romani** [comment]
Please share log of `mvn -X verify ` command.

**Comment by 0xbakry** [comment]
I'm not sure if you want the whole file or just the errors part, but here i edited the gist:
https://gist.github.com/0xbakry/4f1c24bf780732c851f14e78e452b0d3

**Comment by romani** [comment]
from your logs:
>Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.18, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.19.0-35-generic", arch: "amd64", family: "unix"

I think you have  some unfortunate installation of jdk. Please downlaod and install to your home folder.

**Comment by 0xbakry** [comment]
@romani Hey, sorry for the delay but it took me some time to solve the problems in my environment, finally i have a successful build with my new changes, but i don't know why it fails in some checks? i looked at the log file and noticed that error:

> E: Failed to fetch https://storage.googleapis.com/bazel-apt/dists/stable/jdk1.8/binary-amd64/Packages.gz  File has unexpected size (9303 != 9101). Mirror sync in progress? [IP: 172.217.23.112 443]00:10
>    Hashes of expected file:00:10
>     - Filesize:9101 [weak]00:10
>     - SHA256:b114e136085a63c5d29fe90469ec910bf0660efe5c15204ae3d2c70fd154086e00:10
>     - SHA1:4156b65bff5ea8c702a3afe9879e4a652f870959 [weak]00:10
>     - MD5Sum:ff85769e92e84bc0ae89f7a0bd4c239d [weak]00:10
>    Release file created at: Mon, 06 Mar 2023 17:36:32 +000000:10
> E: Some index files failed to download. They have been ignored, or old ones used instead.

Is this error related to me and my changes? i also want to ask if there an option to re-run the checks again without provide a new commit.
Thanks a lot for your helping! (:

**Comment by romani** [comment]
You can always try to compile code without your changed. Our CI guaranteed to build each commit in master we have.

**Comment by 0xbakry** [comment]
@romani this's not what i mean, i made the changes and it builds without anw problem on my local machine. 
My question is why it doesn't pass the CI?

**Comment by romani** [comment]
Click on CI links and read.
There is even spelling problem

**Comment by romani** [comment]
remove unrelated commit from PR, pull latest code from our master branch - https://checkstyle.org/beginning_development.html#Starting_Development
Add code block that you added under default to be under all other configs.

**Comment by 0xbakry** [comment]
@romani I did what you told me to do, but when i try `git rebase -i HEAD~3` to squash the commits i get these commits and i'm little confused why i get them in my branch?

**Comment by romani** [comment]
I am not sure, I recommend you to drop on your local your branch, create branch with same name again, do all code changes, do commit, push to remote with force.

**Comment by 0xbakry** [comment]
I did all of that, then i did `git rebase -i HEAD~5` and found the same problem

**Comment by romani** [comment]
Do not rebase. Just do https://github.com/checkstyle/checkstyle/pull/12802#issuecomment-1474560546

**Comment by 0xbakry** [comment]
I did, i tried to do rebase after `push` and the last commit is the result of that.
and it still fails:

> #!/bin/bash -eo pipefail
export PR_NUMBER=$CIRCLE_PR_NUMBER
export PR_BRANCH_NAME=$CIRCLE_BRANCH
export SONAR_API_TOKEN=$SONAR_TOKEN
./.ci/validation.sh sonarqube
Error: Define SONAR_TOKEN environment variable

**Comment by 0xbakry** [comment]
@romani when i do `git branch -d bakry_branch` it should then delete the old changes and commits, but it doesn't. 
I did what you told me again but it still not working and i don't know why it goes like that with me, can you help me and take a look on it please?

**Comment by romani** [comment]
Delete your fork, delete all on your local for checkstyle. Do all fork/clone/branch from scratch.

**Pull request closed without merging**
