### PR TITLE
issue-7534-npe-in-MissingDeprecatedCheck

### PR DESCRIPTION
**Pull request by nmancus1**
Issue #7534: NPE in MissingDeprecatedCheck

### CODE REVIEW

**Comment by nmancus1** [comment]
I still need better test coverage to pass jacoco checks, any advice?

**Comment by strkkk** [comment]
@nmancus1 Add a unit test for this condition

**Comment by rnveach** [comment]
Issue in first post is not correct issue number.

This type of PR is special.

https://github.com/checkstyle/checkstyle/wiki/PR-rules See item 5.

It is required to add a UT to showcase problem reported in issue is fixed and will not cause an exception.

Any circleci failures is a failure with pitest (mutation testing).

**Comment by nmancus1** [comment]
@rnveach thanks, I fixed the issue number. I will begin work on the test tomorrow.  I submitted pull request for visibility to ask about UT; should I make a new test, or add to the existing test cases? Thanks for all your help.

**Comment by rnveach** [comment]
It must be in a new input file to prevent changing line numbers for existing files with existing violations.

**Comment by nmancus1** [comment]
I accidentally deleted my fork, causing an "unknown repo" above.  I pulled this PR down, added the my new code, and tried to force push back to this PR, but cannot.  Any ideas what I can do to avoid opening a new PR?

**Comment by strkkk** [comment]
I doubt you can change original repo/branch for PR. I think you can create for once again, close this one and open a new PR

**Comment by nmancus1** [comment]
@strkkk ok, that's what I was afraid of, sorry about this.  Do you have any suggestions for projects to use in `projects-to-test-on.properties` file for diff report?

**Comment by rnveach** [comment]
>  Also, do you have any suggestions for projects to use in projects-to-test-on.properties file for diff report?

We generally ask for all projects. You never know which project may give you more feedback than the others.

> I accidentally deleted my fork, causing an "unknown repo" above. I pulled this PR down, added the my new code, and tried to force push back to this PR, but cannot. Any ideas what I can do to avoid opening a new PR? I still have the original cloned fork on my PC.

Recreate the fork using the same name as the original and try pushing your branch to the new fork as if it was your old and see if this PR gets updated.

**Comment by nmancus1** [comment]
> Recreate the fork using the same name as the original and try pushing your branch to the new fork as if it was your old and see if this PR gets updated.

This has worked in the past for me, but today I get nothing but auth errors.

**Pull request closed without merging**
