### PR TITLE
Issue #6385: explicitly define default tokens in google_checks.xml

### PR DESCRIPTION
**Pull request by romani**
Issue #6385

originally proposed in PR #7252

### CODE REVIEW

**Comment by romani** [comment]
@rnveach , please explain one more time why you think we need some special UT to validate definition of default (and potentially modifieble) tokens in config?
we do have already some config in GOOGLE_TOKENS_IN_CONFIG_TO_IGNORE ([link](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java#L369)) for token we do not need.

**Comment by rnveach** [comment]
@romani My reason is the same as issue description and from problem issue which was the reason it was created.

Current config only specifies tokens that we add in addition to default. Specifically the ones that are "acceptable" and we manually enabled. Default tokens are always added to config without any way to disable. We added a new default token in a previous issue and didn't realize at the time it had an impact on one of the configurations, google. That's when we decided we would specify all tokens in google/sun that are active, even the default tokens, to ensure we realize we are adding a new token to the config and ensure it follows the rules of the config.

The whole purpose of this PR/issue, is to ensure all active tokens are added to the config as we can't do this manually. Without a UT to control it and reminds us, merging the changes to the config has no meaning. We must have the UT.

**Comment by rnveach** [comment]
> we do have already some config in GOOGLE_TOKENS_IN_CONFIG_TO_IGNORE 

This only controls acceptable tokens, not default tokens. The current UT will not do what we need. I am fine expanding the current UT if possible.

**Comment by romani** [comment]
> Current config only specifies tokens that we add in addition to default.

We put in this config tokens that we know should NOT be part of config:
https://github.com/checkstyle/checkstyle/blob/3e0e27a4acbda1857f3d89b166075144701e6c98/src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java#L86-L88
https://github.com/checkstyle/checkstyle/blob/3e0e27a4acbda1857f3d89b166075144701e6c98/src/main/resources/google_checks.xml#L215-L217
https://checkstyle.org/config_whitespace.html#NoWhitespaceBefore

So as by this PR we introduce default to be explicit, so adding new token to default will result in UT failure.

Example on NoLineWrap that is updated in this PR (one token is removed):
```
✔ ~/java/github/romani/checkstyle [6385-google-style-tokens L|✚ 1] 
$ git diff
diff --git a/src/main/resources/google_checks.xml b/src/main/resources/google_checks.xml
index 414b386..ac43346 100644
--- a/src/main/resources/google_checks.xml
+++ b/src/main/resources/google_checks.xml
@@ -63,7 +63,7 @@
         <module name="AvoidStarImport"/>
         <module name="OneTopLevelClass"/>
         <module name="NoLineWrap">
-            <property name="tokens" value="PACKAGE_DEF, IMPORT, STATIC_IMPORT"/>
+            <property name="tokens" value="PACKAGE_DEF, IMPORT"/>
         </module>
         <module name="EmptyBlock">
             <property name="option" value="TEXT"/>

$ grep -A 4 "NoLineWrap" src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
        CHECKSTYLE_TOKENS_IN_CONFIG_TO_IGNORE.put("NoLineWrap", Stream.of(
                // method declaration could be long due to "parameters/exceptions", it is ok to
                // be not strict there
                "METHOD_DEF", "CTOR_DEF",
                // type declaration could be long due to "extends/implements", it is ok to
--
        GOOGLE_TOKENS_IN_CONFIG_TO_IGNORE.put("NoLineWrap", Stream.of(
                // method declaration could be long due to "parameters/exceptions", it is ok to
                // be not strict there
                "METHOD_DEF", "CTOR_DEF", "CLASS_DEF", "ENUM_DEF", "INTERFACE_DEF")
                .collect(Collectors.toSet()));

```

UT failed:
```
org.opentest4j.AssertionFailedError: 'NoLineWrap' should have all acceptable 
tokens from check in google config or specify an override to ignore the
 specific tokens ==> 
Expected :
[STATIC_IMPORT, IMPORT, METHOD_DEF, CTOR_DEF, PACKAGE_DEF, CLASS_DEF, ENUM_DEF, INTERFACE_DEF]
Actual   :
[IMPORT, METHOD_DEF, CTOR_DEF, PACKAGE_DEF, CLASS_DEF, ENUM_DEF, INTERFACE_DEF]
<Click to see difference>
```

So it works.

**Comment by rnveach** [comment]
> `<module name="NoLineWrap">`
`-            <property name="tokens" value="PACKAGE_DEF, IMPORT, STATIC_IMPORT"/>`
`+            <property name="tokens" value="PACKAGE_DEF, IMPORT"/>`

This is not what I was referring and slightly misspoke when I said default tokens.

We should specify DEFAULT tokens if current module config specifies no tokens.

We should specify REQUIRED tokens if module config specifies any tokens.

Please see issue referenced in this issue and follow its conversations to see why this was originally an issue. Original issue was with WhitespaceAround and we currently specify no tokens for the check. We added a new default and acceptable token and it impacted google config without us realizing. UT is needed to warn us again when we modify check source. I am not referring to modifying the config, but the check source code.

**Comment by romani** [comment]
> We should write out default tokens if current module config specifies no tokens.

You probably meant `We should write out default tokens if current module config specifies no tokens AND tokens are confgurable.`

>Original issue was with WhitespaceAround and we currently specify no tokens for the check in the google config

yes, LAMBDA token was added to default ... BUT if `tokens` were defined in google config then `testAllCheckTokensAreReferencedInGoogleConfigFile` would fail to force update IGNORE list of add it to config.

> We added a new default and acceptable token and it impacted google config without us realizing. 

yes, with such modification in config, it will not be possible to add default token, without modification of UT test, and my testing with NoLineWrap shows this (in PRs commit I referenced all default tokens, in changes above commit I remove token from config to emulate situation of new token in Check).

> I think we should probably expand this to required tokens too, in that we should write out the required tokens for each check.

I do not see a reason. It might be some other problem that I am not aware of (less frequent), lets postpone to separate issue.

**Comment by rnveach** [comment]
> yes, LAMBDA token was added to default ... BUT if tokens were defined in google config then testAllCheckTokensAreReferencedInGoogleConfigFile would fail to force update IGNORE list of add it to config. So it will be easy to detect this during code review.

UT was around during that PR but it did not alert us to issue. So if you are talking about the issue that created this issue, there was no UT failure to alert us. Hence why we needed a new issue to fix the problem after it was released.

**Comment by romani** [comment]
> UT was around during that PR but it did not alert us to issue

there was nuance, if no tokens defined, validation did not happen. Now all have tokens, so it will not happen on existing Checks.

**Comment by romani** [comment]
after discussion with @rnveach  in private chat:

1) we need to have some UT to make sure that all Checks configs that are changed in this PR will be detected by this test. So if in future we add new Check to google config in default form and tokens for this Check are confgurable and contributor placed Check in default way - UT should fail.

2) additional UT to make sure that modification of required tokens (Check will be subscribed for them automatically during execution, user may skip them in config) .... it is more complicated case .... probably deserve separate issue.

**Comment by romani** [comment]
> 1. we need to have some UT to make sure that all Checks configs that are changed in this PR will be detected by this test

fixed. Testing:
```
~/java/github/romani/checkstyle [6385-google-style-tokens L|✚ 2] 
$ git diff
diff --git a/src/main/resources/google_checks.xml b/src/main/resources/google_checks.xml
index 7b8cbca..dfaab4b 100644
--- a/src/main/resources/google_checks.xml
+++ b/src/main/resources/google_checks.xml
@@ -63,7 +63,7 @@
         <module name="AvoidStarImport"/>
         <module name="OneTopLevelClass"/>
         <module name="NoLineWrap">
-            <property name="tokens" value="PACKAGE_DEF, IMPORT, STATIC_IMPORT"/>
+            <!--<property name="tokens" value="PACKAGE_DEF, IMPORT, STATIC_IMPORT"/>-->
         </module>
         <module name="EmptyBlock">
             <property name="option" value="TEXT"/>


org.opentest4j.AssertionFailedError: All default tokens should be used in config for NoLineWrap

	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:109)
	at com.puppycrawl.tools.checkstyle.internal.AllChecksTest.validateAllCheckTokensAreReferencedInConfigFile(AllChecksTest.java:429)
	at com.puppycrawl.tools.checkstyle.internal.AllChecksTest.testAllCheckTokensAreReferencedInGoogleConfigFile(AllChecksTest.java:373)
```

> 2. additional UT to make sure that modification of required tokens

I tried to think about this ... and it looks like overcaution ..... I do not want to polute config with required tokens for sure. Second approach is to keep map of required tokens in `AllChecksTest` as second copy to fail if tokens are changed in main code ..... but is looks odd a bit.
If you still think it is required .... lets postpone this to separate issue to think about this a bit more.

**Pull request merged**
