### PR TITLE
infra: restore wercker

### PR DESCRIPTION
**Pull request by nick-mancuso**
This PR can serve as an easy way to try and monitor wercker status, to be merged after solving issues noted in #11373

### CODE REVIEW

**Comment by romani** [comment]
rebased manually, previous state of wercker was green

**Review by romani — APPROVED** [review]
ok to merge.

**Comment by rnveach** [comment]
@romani Sonarqube in wercker is hanging at 3 hours. Before wrecker stopped working completely, this has been an ongoing issue.

**Comment by romani** [comment]
We can keep sonar in circleci

**Comment by romani** [comment]
But probably we can skip to use  wercker, as it is not convenient as it not showing failures to  contributors.

**Review by pbludov — APPROVED** [review]

**Comment by romani** [comment]
Let's keep wercker while gsoc selection is in progress, there might be too much PRs as usually.

**Pull request merged**
