### PR TITLE
minor: Remove closed issues that are still referenced in files

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Removed closed issues that are still referenced in files

### CODE REVIEW

**Comment by rnveach** [comment]
I thought we had a shell script that checked for this? I remember we created something that looked up issue numbers

**Comment by Vyom-Yadav** [comment]
This action https://github.com/checkstyle/checkstyle/runs/5612335973?check_suite_focus=true ?

**Review by romani — APPROVED** [review]
Sad that we didn't have issue to migrate xpath filters
New issue https://github.com/checkstyle/checkstyle/issues/11438

**Comment by romani** [comment]
@Vyom-Yadav , 

There are still some reference left
https://github.com/checkstyle/checkstyle/runs/5613163638?check_suite_focus=true

**Comment by rnveach** [comment]
> This action https://github.com/checkstyle/checkstyle/actions/workflows/no_old_refs.yml ?

https://github.com/checkstyle/checkstyle/runs/5611541403?check_suite_focus=true
https://github.com/checkstyle/checkstyle/pull/11430

The check failed, how come we didn't get some warning in the PR before merging?

**Comment by romani** [comment]
It is interesting point

**Comment by Vyom-Yadav** [comment]
> It is interesting point

Looks like the action and the shell script need some upgrades, it should also report where to do these changes, I am working on this, will make an issue about it.

**Pull request merged**
