### PR TITLE
Issue #4169: Javadoc on annotation fields support

### PR DESCRIPTION
**Pull request by pbludov**
Issue #4169

Javadoc on annotation fields support

### CODE REVIEW

**Comment by pbludov** [comment]
$ java -jar target/checkstyle-8.4-SNAPSHOT-all.jar -J src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnAnnotationField.java
```
PACKAGE_DEF -> package [1:0]
|--ANNOTATIONS -> ANNOTATIONS [1:45]
|--DOT -> . [1:45]
|   |--DOT -> . [1:39]
|   |   |--DOT -> . [1:28]
|   |   |   |--DOT -> . [1:22]
|   |   |   |   |--DOT -> . [1:11]
|   |   |   |   |   |--IDENT -> com [1:8]
|   |   |   |   |   `--IDENT -> puppycrawl [1:12]
|   |   |   |   `--IDENT -> tools [1:23]
|   |   |   `--IDENT -> checkstyle [1:29]
|   |   `--IDENT -> utils [1:40]
|   `--IDENT -> blockcommentposition [1:46]
`--SEMI -> ; [1:66]
ANNOTATION_DEF -> ANNOTATION_DEF [3:0]
|--MODIFIERS -> MODIFIERS [3:0]
|   `--LITERAL_PUBLIC -> public [3:0]
|--AT -> @ [3:7]
|--LITERAL_INTERFACE -> interface [3:8]
|--IDENT -> InputBlockCommentPositionOnAnnotationField [3:18]
`--OBJBLOCK -> OBJBLOCK [3:61]
    |--LCURLY -> { [3:61]
    |--ANNOTATION_FIELD_DEF -> ANNOTATION_FIELD_DEF [7:4]
    |   |--MODIFIERS -> MODIFIERS [7:4]
    |   |--TYPE -> TYPE [7:4]
    |   |   |--BLOCK_COMMENT_BEGIN -> /* [4:4]
    |   |   |   |--COMMENT_CONTENT -> *\n     * I'm a javadoc\n      [4:6]
    |   |   |   |   `--JAVADOC -> JAVADOC [4:7]
    |   |   |   |       |--NEWLINE -> \n [4:7]
    |   |   |   |       |--LEADING_ASTERISK ->      * [5:0]
    |   |   |   |       |--TEXT ->  I'm a javadoc [5:6]
    |   |   |   |       |--NEWLINE -> \n [5:20]
    |   |   |   |       |--TEXT ->       [6:0]
    |   |   |   |       `--EOF -> <EOF> [6:5]
    |   |   |   `--BLOCK_COMMENT_END -> */ [6:5]
    |   |   `--IDENT -> String [7:4]
    |   |--IDENT -> value [7:11]
    |   |--LPAREN -> ( [7:16]
    |   |--RPAREN -> ) [7:17]
    |   |--LITERAL_DEFAULT -> default [7:19]
    |   |   `--EXPR -> EXPR [7:27]
    |   |       `--STRING_LITERAL -> "" [7:27]
    |   `--SEMI -> ; [7:29]
    |--ANNOTATION_FIELD_DEF -> ANNOTATION_FIELD_DEF [12:4]
    |   |--MODIFIERS -> MODIFIERS [12:4]
    |   |   |--BLOCK_COMMENT_BEGIN -> /* [9:4]
    |   |   |   |--COMMENT_CONTENT -> *\n     * I'm a javadoc\n      [9:6]
    |   |   |   |   `--JAVADOC -> JAVADOC [9:7]
    |   |   |   |       |--NEWLINE -> \n [9:7]
    |   |   |   |       |--LEADING_ASTERISK ->      * [10:0]
    |   |   |   |       |--TEXT ->  I'm a javadoc [10:6]
    |   |   |   |       |--NEWLINE -> \n [10:20]
    |   |   |   |       |--TEXT ->       [11:0]
    |   |   |   |       `--EOF -> <EOF> [11:5]
    |   |   |   `--BLOCK_COMMENT_END -> */ [11:5]
    |   |   `--ABSTRACT -> abstract [12:4]
    |   |--TYPE -> TYPE [12:13]
    |   |   `--IDENT -> String [12:13]
    |   |--IDENT -> value1 [12:20]
    |   |--LPAREN -> ( [12:26]
    |   |--RPAREN -> ) [12:27]
    |   |--LITERAL_DEFAULT -> default [12:29]
    |   |   `--EXPR -> EXPR [12:37]
    |   |       `--STRING_LITERAL -> "" [12:37]
    |   `--SEMI -> ; [12:39]
    |--ANNOTATION_FIELD_DEF -> ANNOTATION_FIELD_DEF [17:4]
    |   |--MODIFIERS -> MODIFIERS [17:4]
    |   |   `--ANNOTATION -> ANNOTATION [17:4]
    |   |       |--BLOCK_COMMENT_BEGIN -> /* [14:4]
    |   |       |   |--COMMENT_CONTENT -> *\n     * I'm a javadoc\n      [14:6]
    |   |       |   |   `--JAVADOC -> JAVADOC [14:7]
    |   |       |   |       |--NEWLINE -> \n [14:7]
    |   |       |   |       |--LEADING_ASTERISK ->      * [15:0]
    |   |       |   |       |--TEXT ->  I'm a javadoc [15:6]
    |   |       |   |       |--NEWLINE -> \n [15:20]
    |   |       |   |       |--TEXT ->       [16:0]
    |   |       |   |       `--EOF -> <EOF> [16:5]
    |   |       |   `--BLOCK_COMMENT_END -> */ [16:5]
    |   |       |--AT -> @ [17:4]
    |   |       `--IDENT -> Deprecated [17:5]
    |   |--TYPE -> TYPE [18:4]
    |   |   `--IDENT -> String [18:4]
    |   |--IDENT -> value2 [18:11]
    |   |--LPAREN -> ( [18:17]
    |   |--RPAREN -> ) [18:18]
    |   |--LITERAL_DEFAULT -> default [18:20]
    |   |   `--EXPR -> EXPR [18:28]
    |   |       `--STRING_LITERAL -> "" [18:28]
    |   `--SEMI -> ; [18:30]
    |--ANNOTATION_FIELD_DEF -> ANNOTATION_FIELD_DEF [23:4]
    |   |--MODIFIERS -> MODIFIERS [23:4]
    |   |   |--ANNOTATION -> ANNOTATION [23:4]
    |   |   |   |--BLOCK_COMMENT_BEGIN -> /* [20:4]
    |   |   |   |   |--COMMENT_CONTENT -> *\n     * I'm a javadoc\n      [20:6]
    |   |   |   |   |   `--JAVADOC -> JAVADOC [20:7]
    |   |   |   |   |       |--NEWLINE -> \n [20:7]
    |   |   |   |   |       |--LEADING_ASTERISK ->      * [21:0]
    |   |   |   |   |       |--TEXT ->  I'm a javadoc [21:6]
    |   |   |   |   |       |--NEWLINE -> \n [21:20]
    |   |   |   |   |       |--TEXT ->       [22:0]
    |   |   |   |   |       `--EOF -> <EOF> [22:5]
    |   |   |   |   `--BLOCK_COMMENT_END -> */ [22:5]
    |   |   |   |--AT -> @ [23:4]
    |   |   |   `--IDENT -> Deprecated [23:5]
    |   |   `--ABSTRACT -> abstract [24:4]
    |   |--TYPE -> TYPE [24:13]
    |   |   `--IDENT -> String [24:13]
    |   |--IDENT -> value3 [24:20]
    |   |--LPAREN -> ( [24:26]
    |   |--RPAREN -> ) [24:27]
    |   |--LITERAL_DEFAULT -> default [24:29]
    |   |   `--EXPR -> EXPR [24:37]
    |   |       `--STRING_LITERAL -> "" [24:37]
    |   `--SEMI -> ; [24:39]
    `--RCURLY -> } [25:0]
```

**Comment by pbludov** [comment]
@rnveach I found a test for `BlockCommentPosition::isOnField` and wrote a similar test for `BlockCommentPosition::isOnAnnotationField`.
Also, I add a test case for `JavadocUtils.isJavadocComment` test.
Is there anything more to test?

**Comment by pbludov** [comment]
@romani @rnveach Any chance to get this PR merged?

**Comment by rnveach** [comment]
> Is there anything more to test?

The tests you wrote are hard to discern to me what is going on because they are just numbers and not showing what they are examining. This is why your first PR confused me with counts I didn't understand where they were coming from. This is why I think we should also add some full tree printing and hence why I asked you for an output of it just to be sure.
@romani ping. See my question before.

> $ java -jar target/checkstyle-8.4-SNAPSHOT-all.jar -J src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnAnnotationField.java

Please print your `MyAnnotation2` one. The one that has `noise` javadoc comments that shouldn't be picked up as javadocs in weird places.

Please generate diff reports on your changes with all Javadoc checks (https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/checks-only-javadoc-error.xml) and upload report for us all to look at.
See https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#diffgroovy-diff-report-generation

**Comment by pbludov** [comment]
The output of 
```
$ LANGUAGE=en groovy diff.groovy --localGitRepo /home/pb/src/checkstyle --baseBranch main/master --patchBranch origin/issue-4169 --config checks-only-javadoc-error.xml --listOfProjects projects-to-test-on.properties
```
is here:
https://pbludov.github.io/reports/diff/guava/index.html

**Comment by pbludov** [comment]
Annotation2 dump:
```
ANNOTATION_DEF -> ANNOTATION_DEF [238:0]
|--MODIFIERS -> MODIFIERS [238:0]
|--BLOCK_COMMENT_BEGIN -> /* [237:0]
|   |--COMMENT_CONTENT -> *Javadoc [237:2]
|   |   `--JAVADOC -> JAVADOC [237:3]
|   |       |--TEXT -> Javadoc [237:3]
|   |       `--EOF -> <EOF> [237:10]
|   `--BLOCK_COMMENT_END -> */ [237:9]
|--SINGLE_LINE_COMMENT -> // [237:13]
|   `--COMMENT_CONTENT -> noise\n [237:15]
|--AT -> @ [238:0]
|--LITERAL_INTERFACE -> interface [238:1]
|--BLOCK_COMMENT_BEGIN -> /* [238:10]
|   |--COMMENT_CONTENT -> *nope [238:12]
|   `--BLOCK_COMMENT_END -> */ [238:16]
|--IDENT -> MyAnnotation2 [238:20]
`--OBJBLOCK -> OBJBLOCK [238:43]
    |--BLOCK_COMMENT_BEGIN -> /* [238:33]
    |   |--COMMENT_CONTENT -> *nope [238:35]
    |   `--BLOCK_COMMENT_END -> */ [238:39]
    |--LCURLY -> { [238:43]
    |--ANNOTATION_FIELD_DEF -> ANNOTATION_FIELD_DEF [240:1]
    |   |--MODIFIERS -> MODIFIERS [240:1]
    |   |   |--ANNOTATION -> ANNOTATION [240:1]
    |   |   |   |--BLOCK_COMMENT_BEGIN -> /* [239:1]
    |   |   |   |   |--COMMENT_CONTENT -> *Javadoc [239:3]
    |   |   |   |   |   `--JAVADOC -> JAVADOC [239:4]
    |   |   |   |   |       |--TEXT -> Javadoc [239:4]
    |   |   |   |   |       `--EOF -> <EOF> [239:11]
    |   |   |   |   `--BLOCK_COMMENT_END -> */ [239:10]
    |   |   |   |--SINGLE_LINE_COMMENT -> // [239:14]
    |   |   |   |   `--COMMENT_CONTENT -> noise\n [239:16]
    |   |   |   |--AT -> @ [240:1]
    |   |   |   `--IDENT -> Component2 [240:2]
    |   |   |--BLOCK_COMMENT_BEGIN -> /* [240:12]
    |   |   |   |--COMMENT_CONTENT -> *nope [240:14]
    |   |   |   `--BLOCK_COMMENT_END -> */ [240:18]
    |   |   `--ABSTRACT -> abstract [240:21]
    |   |--TYPE -> TYPE [240:38]
    |   |   |--BLOCK_COMMENT_BEGIN -> /* [240:29]
    |   |   |   |--COMMENT_CONTENT -> *nope [240:31]
    |   |   |   `--BLOCK_COMMENT_END -> */ [240:35]
    |   |   `--IDENT -> String [240:38]
    |   |--BLOCK_COMMENT_BEGIN -> /* [240:44]
    |   |   |--COMMENT_CONTENT -> *nope [240:46]
    |   |   `--BLOCK_COMMENT_END -> */ [240:50]
    |   |--IDENT -> val1 [240:53]
    |   |--LPAREN -> ( [240:57]
    |   |--RPAREN -> ) [240:58]
    |   |--BLOCK_COMMENT_BEGIN -> /* [240:59]
    |   |   |--COMMENT_CONTENT -> *nope [240:61]
    |   |   `--BLOCK_COMMENT_END -> */ [240:65]
    |   |--LITERAL_DEFAULT -> default [240:68]
    |   |   `--EXPR -> EXPR [240:84]
    |   |       |--BLOCK_COMMENT_BEGIN -> /* [240:75]
    |   |       |   |--COMMENT_CONTENT -> *nope [240:77]
    |   |       |   `--BLOCK_COMMENT_END -> */ [240:81]
    |   |       `--STRING_LITERAL -> "" [240:84]
    |   `--SEMI -> ; [240:86]
    |--ANNOTATION_FIELD_DEF -> ANNOTATION_FIELD_DEF [242:1]
    |   |--MODIFIERS -> MODIFIERS [242:1]
    |   |   |--BLOCK_COMMENT_BEGIN -> /* [241:1]
    |   |   |   |--COMMENT_CONTENT -> *Javadoc [241:3]
    |   |   |   |   `--JAVADOC -> JAVADOC [241:4]
    |   |   |   |       |--TEXT -> Javadoc [241:4]
    |   |   |   |       `--EOF -> <EOF> [241:11]
    |   |   |   `--BLOCK_COMMENT_END -> */ [241:10]
    |   |   |--SINGLE_LINE_COMMENT -> // [241:14]
    |   |   |   `--COMMENT_CONTENT -> noise\n [241:16]
    |   |   `--ABSTRACT -> abstract [242:1]
    |   |--TYPE -> TYPE [242:18]
    |   |   |--BLOCK_COMMENT_BEGIN -> /* [242:9]
    |   |   |   |--COMMENT_CONTENT -> *nope [242:11]
    |   |   |   `--BLOCK_COMMENT_END -> */ [242:15]
    |   |   `--IDENT -> String [242:18]
    |   |--BLOCK_COMMENT_BEGIN -> /* [242:24]
    |   |   |--COMMENT_CONTENT -> *nope [242:26]
    |   |   `--BLOCK_COMMENT_END -> */ [242:30]
    |   |--IDENT -> val2 [242:33]
    |   |--LPAREN -> ( [242:37]
    |   |--RPAREN -> ) [242:38]
    |   |--BLOCK_COMMENT_BEGIN -> /* [242:39]
    |   |   |--COMMENT_CONTENT -> *nope [242:41]
    |   |   `--BLOCK_COMMENT_END -> */ [242:45]
    |   `--SEMI -> ; [242:48]
    |--ANNOTATION_FIELD_DEF -> ANNOTATION_FIELD_DEF [244:10]
    |   |--MODIFIERS -> MODIFIERS [244:10]
    |   |--TYPE -> TYPE [244:10]
    |   |   `--DOT -> . [244:10]
    |   |       |--DOT -> . [244:5]
    |   |       |   |--BLOCK_COMMENT_BEGIN -> /* [243:1]
    |   |       |   |   |--COMMENT_CONTENT -> *Javadoc [243:3]
    |   |       |   |   |   `--JAVADOC -> JAVADOC [243:4]
    |   |       |   |   |       |--TEXT -> Javadoc [243:4]
    |   |       |   |   |       `--EOF -> <EOF> [243:11]
    |   |       |   |   `--BLOCK_COMMENT_END -> */ [243:10]
    |   |       |   |--SINGLE_LINE_COMMENT -> // [243:14]
    |   |       |   |   `--COMMENT_CONTENT -> noise\n [243:16]
    |   |       |   |--IDENT -> java [244:1]
    |   |       |   `--IDENT -> lang [244:6]
    |   |       `--IDENT -> String [244:11]
    |   |--BLOCK_COMMENT_BEGIN -> /* [244:17]
    |   |   |--COMMENT_CONTENT -> *nope [244:19]
    |   |   `--BLOCK_COMMENT_END -> */ [244:23]
    |   |--IDENT -> val3 [244:26]
    |   |--LPAREN -> ( [244:30]
    |   |--RPAREN -> ) [244:31]
    |   |--BLOCK_COMMENT_BEGIN -> /* [244:32]
    |   |   |--COMMENT_CONTENT -> *nope [244:34]
    |   |   `--BLOCK_COMMENT_END -> */ [244:38]
    |   `--SEMI -> ; [244:41]
    |--BLOCK_COMMENT_BEGIN -> /* [245:1]
    |   |--COMMENT_CONTENT -> *nope [245:3]
    |   `--BLOCK_COMMENT_END -> */ [245:7]
    `--RCURLY -> } [246:0]
```

**Pull request closed without merging**
