### PR TITLE
Issue #12742: Badges in the README are missing

### PR DESCRIPTION
**Pull request by YehiaFarghaly**
# PLEASE READ before removing

Rules:
1) The issue you are trying to fix/resolve has to have the "approved" label.
2) Put in the description of Pull Request the reference to an issue if it exists.
   Example: "Issue: #XXXXXX"
3) Commit message should adhere to the following rules:
   a) MUST match one of the following patterns:
      ^Issue #\\d+: .*$
      ^Pull #\\d+: .*$
      ^(minor|config|infra|doc|spelling|dependency): .*$
   b) MUST contain only one line of text
   c) MUST NOT end with a period, space, or tab
   d) MUST be less than or equal to 200 characters

To avoid multiple iterations of fixes and CIs failures, please read
https://checkstyle.org/contributing.html

ATTENTION: We are not merging Pull Requests that are not passing our CIs,
but we will help to resolve issues.

Thanks for reading, remove whole this message and type what you need.

### CODE REVIEW

**Comment by YehiaFarghaly** [comment]
I tried to follow the steps of the PR/Commits as much as I could but still 2 CIs failing.

**Comment by romani** [comment]
There was spelling problem and now after update, bad word can be removed.
Please apply patch to your code change:
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=13467&view=logs&j=6a833393-c551-5000-0916-5000fd3b86e7&t=bdbbd129-77f0-5d73-ce7d-db58d34c8358&l=38

**Comment by rnveach** [comment]
@YehiaFarghaly Please see https://github.com/checkstyle/checkstyle/wiki/PR-rules .
You do not need to keep closing and opening a new PR. You just modify your existing branch and re-push the changes to the server.

**Comment by YehiaFarghaly** [comment]
@rnveach, @romani  Ok I understood Thank you

**Comment by romani** [comment]
in this PR should be single commit and only with changes for readme

**Comment by Rohitrky2021** [comment]
is this issue approved?

**Comment by romani** [comment]
Issue approved, this Pull Request not.

**Pull request closed without merging**
