### PR TITLE
JavadocType does not check parameters in inner classes, fixes  #1421

### LINKED ISSUE #1421: JavadocType ignores param tags in InnerClass
Inner classes are not checked with JavadocType check for missing or extra ``@param`` tags

The following code is Ok, but ``@param`` tags are wrong set in the javadoc
```java
    /**
     * Example inner class.
     * @param <A> documented parameter
     * @param <C> extra parameter
     */

    public static class InnerClass<A,B>
    {
    }
```

### PR DESCRIPTION
**Pull request by pbaranchikov**
Checkstyle tester output - http://pbaranchikov.github.io/checkstyle/javadoc-type/checkstyle.html

### CODE REVIEW

**Comment by romani** [comment]
@pbaranchikov , 

1) "2932" errors is not a number human can easily validate, please generate two reports (before fix and after fix) and provide a diff.

2) Please create issue and state a problem there, and then reference that issue in git commit.

3) please do rebase on latest master, to make Travis green. Appveyor could be ignored.
@mkordas , please do code-review of that changes as your are probably more familiar with that Check.

**Comment by romani** [comment]
appveyor is passing for master, please recommit smth in branch to re-trigger CIs builds. From this moment I expect all CIs to be green.

**Comment by mkordas** [comment]
I'll do code review whenever builds will be passing and issue with description will be created.

**Comment by pbaranchikov** [comment]
Report renewed. Checks for commit 3bd39984f24378e4b01148bd02423e3d04c0c851 (current master) and fix, committed upon the commit.

Parameter | Base version (master) | Applied changes
------------ | -------------
voilations found | 2651 | 2932 (+281)
Report link | http://pbaranchikov.github.io/checkstyle/javadoc-type-without-fix/checkstyle.html | http://pbaranchikov.github.io/checkstyle/javadoc-type-with-fix/checkstyle.html

Example file with violations - com/google/common/base/Predicates.java

**Comment by pbaranchikov** [comment]
@mkordas
> Build execution time has reached the maximum allowed time for your plan (40 minutes).

No errors in output, so seems like error in build configuration.

Locally my build is Ok. No errors

**Comment by romani** [comment]
appveyor is relaunched.

> Report renewed.

@pbaranchikov , please confirm that all that additional violations are correct.

**Comment by pbaranchikov** [comment]
@romani 
I walked through several dozens on them. They all are correct.

**Comment by romani** [comment]
@mkordas , please step in.

@pbaranchikov , i still do not see reference of issue in commit message, please do.

**Comment by mkordas** [comment]
Looks good for me, thanks @pbaranchikov for nice improvement. 

We just need remember that this is kind of breaking change - users will get more violations.

**Comment by romani** [comment]
@pbaranchikov , 

1) please create an issue and reference in commit message

2) please copy first paragraph of xdoc Description to javadoc ,that will help user , especially at them moment when sourceforge is down.

**Comment by romani** [comment]
Is it the same fix https://github.com/checkstyle/checkstyle/pull/1432 ?

**Comment by pbaranchikov** [comment]
> Is it the same fix #1432 ?
Yes, I've created the issue, as you requested. And liscju tried to fix it too.

**Comment by pbaranchikov** [comment]
@romani 
Points 1 and 2 done.

**Comment by romani** [comment]
@pbaranchikov , please always make a ref to issue . That is not the only reason we demand that.
That is very sad situation, that I had to reject work of another contributor.

**Pull request merged**
