### PR TITLE
test: AbbreviationAsWordInName perform regression testing

### PR DESCRIPTION
**Pull request by relentless-pursuit**
This PR is meant to test AbbreviationAsWordInName's configs. 

Diff Regression config: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/all-examples-in-one/config.xml

Diff Regression projects: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/all-examples-in-one/list-of-projects.properties

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9366625269/job/25784527427

**Comment by relentless-pursuit** [comment]
Testing for AbbreviationAsWordInName/Example1

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example1/config.xml

Project file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example1/list-of-projects.properties

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024123536/reports/diff/index.html

Action: https://github.com/checkstyle/checkstyle/actions/runs/9366625269/job/25784527427

Time: **36 mins 18 secs**

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9367314040

**Comment by relentless-pursuit** [comment]
Testing for `AbbreviationAsWordInName/Example2`

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example2/config.xml

Project file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example2/list-of-projects.properties

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024140141/reports/diff/index.html

Action: https://github.com/checkstyle/checkstyle/actions/runs/9367314040

Time: **37 mins 5 secs**

**Comment by relentless-pursuit** [comment]
Testing for `AbbreviationAsWordInName/Example3`

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example3/config.xml

Project file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example3/list-of-projects.properties

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024151436/reports/diff/index.html

Action: https://github.com/checkstyle/checkstyle/actions/runs/9369141275/job/25792893502

Time: **36 mins 6 secs**

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Testing for `AbbreviationAsWordInName/Example4`

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example4/config.xml

Project file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example4/list-of-projects.properties

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024151436/reports/diff/index.html

Action: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024164659/reports/diff/index.html

Time: **36 mins 18 secs**

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Testing for `AbbreviationAsWordInName/Example5`

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example5/config.xml

Project file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example5/list-of-projects.properties

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024181614/reports/diff/index.html

Action: https://github.com/checkstyle/checkstyle/actions/runs/9371698019/job/25801521572

Time: 36 mins 27 secs

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Testing for `AbbreviationAsWordInName/Example6`

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example6/config.xml

Project file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example6/list-of-projects.properties

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024191251/reports/diff/index.html

Action: https://github.com/checkstyle/checkstyle/actions/runs/9371698019/job/25801521572

Time: **37 mins 8 secs**

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Testing for `AbbreviationAsWordInName/Example7`

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example7/config.xml

Project file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example7/list-of-projects.properties

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024200008/reports/diff/index.html

Action: https://github.com/checkstyle/checkstyle/actions/runs/9372998438/job/25805733694

Time: 36 mins 24 secs

**Comment by romani** [comment]
I don't see https://github.com/checkstyle/test-configs/tree/main/AbbreviationAsWordInName/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9378073342/job/25820689590

**Comment by relentless-pursuit** [comment]
Testing for AbbreviationAsWordInName/all-in-one

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/all-examples-in-one/config.xml

Project file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/all-examples-in-one/list-of-projects.properties

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d296ed0_2024045201/reports/diff/index.html

Action: https://github.com/checkstyle/checkstyle/actions/runs/9378073342/job/25820689590

**Comment by romani** [comment]
Please do run all for javadoc summary

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9386358819/job/25846773537

**Comment by romani** [comment]
Total duration
46m 22s

https://github.com/checkstyle/checkstyle/actions/runs/9386358819

Decent timing.

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
@romani , it seems to be working. 

https://github.com/checkstyle/checkstyle/actions/runs/9798690179

**Pull request closed without merging**
