### PR TITLE
minor: Resolve Pitest suppression for SingleSpaceSeparatorCheck

### PR DESCRIPTION
**Pull request by Kevin222004**
minor: Resolve Pitest suppression for SingleSpaceSeparatorCheck

Related to https://github.com/checkstyle/checkstyle/pull/12283

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/55bba7110290f08feb12e3c4f36976e4/raw/a3bd29dd8d9035b48d5bbfba68042e33e4b82526/CONFIG.xml

### CODE REVIEW

**Comment by Kevin222004** [comment]
Just for testing not to merge

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
Please investigate code:
```
while (currentNode.getNextSibling() == null && currentNode.getParent() != parent) {
                    currentNode = currentNode.getParent();
                }
                currentNode = currentNode.getNextSibling();

```

It might a reason why parent node is not required, as we exist "while " by null sibling, that is reasonable

**Comment by nrmancuso** [comment]
@Kevin222004 ping

**Comment by Kevin222004** [comment]
> @Kevin222004 ping

this is not required now so i am closing it. 
due to exam right know not able to send the pr

**Pull request closed without merging**
