### PR TITLE
minor: add "cd -" to removeFolderWithProtectedFiles

### PR DESCRIPTION
**Pull request by nmancus1**
minor: add "cd -" to removeFolderWithProtectedFiles, per discussion at https://github.com/checkstyle/checkstyle/pull/7816#discussion_r395072027

### CODE REVIEW

**Comment by nmancus1** [comment]
From Travis: `./.ci/travis/travis.sh: line 10: cd: /home/travis/build/checkstyle/checkstyle/.ci-temp/pmd: No such file or directory`.  `cd -` Will reference the previous working directory (pmd in this case), which has been deleted with rmdir. We just want to make sure we're in `.ci-temp/`, correct?

**Comment by romani** [comment]
Let's do less `cd` it us always good

Please try to do `find $1 -delete`

**Comment by romani** [comment]
I testeted it on local - it works.
```
$ mkdir -p 1/2
$ find 1
1
1/2
```

ok to merge, as CI pass.

**Comment by nmancus1** [comment]
@romani is there anything else I need to do so we can merge this PR?  I wanted to get this merged before starting on https://github.com/checkstyle/checkstyle/issues/7892

**Comment by rnveach** [comment]
I am seeing nothing wrong and we were probably waiting on CI to turn green.

**Pull request merged**
