### PR TITLE
Issue #4777: fixed RequireThisCheck with NPE on case group

### PR DESCRIPTION
**Pull request by rnveach**
Issue #4777

Regression to come.

### CODE REVIEW

**Comment by rnveach** [comment]
http://rveach.no-ip.org/checkstyle/regression/reports/89/

Regression showed no differences.

**Comment by rnveach** [comment]
Rebased on latest master for changes in test support.

**Comment by rnveach** [comment]
@romani 
http://rveach.no-ip.org/checkstyle/regression/reports/90/

Turning off `validateOnlyOverlapping` is showing tons of differences and most are new NPEs.

**Comment by romani** [comment]
> We should turn off validateOnlyOverlapping for all non-exception tests

Good catch, I did sync checks-nonjavadoc-error.xml from checkstyle_checks.xml, and added `validateOnlyOverlapping=false`
https://github.com/checkstyle/contribution/commit/696c72036d2809fb8a47dadf97e52527ddc9f854
but disabled it (https://github.com/checkstyle/contribution/commit/d5349da69baa00ec28ab51d7b9fc7f5d46ec3221) as your fix still leave another exception.

**Comment by rnveach** [comment]
> as your fix still leave another exception
> Please create another issue(if problem is unrelated)

@romani Please clarify what NPE you are talking about.
The ones I found in my 2nd report was put into the referenced issue at #4586 .

**Comment by romani** [comment]
@rnveach , steps to reproduce:
```
~/java/github/checkstyle/checkstyle [master|✔] 
$ ./fast-forward-merge.sh rnveach issue_4777
...
~/java/github/checkstyle/checkstyle [master ↑·1|✚ 1] 
19:19 $ git diff
diff --git a/config/checkstyle_checks.xml b/config/checkstyle_checks.xml
index 2b88ede..b83afae 100644
--- a/config/checkstyle_checks.xml
+++ b/config/checkstyle_checks.xml
@@ -268,7 +268,9 @@
     <module name="OverloadMethodsDeclarationOrder"/>
     <module name="PackageDeclaration"/>
     <module name="ParameterAssignment"/>
-    <module name="RequireThis"/>
+    <module name="RequireThis">
+      <property name="validateOnlyOverlapping" value="false"/>
+    </module>
     <module name="ReturnCount">
       <property name="maxForVoid" value="0"/>
     </module>

~/java/github/checkstyle/checkstyle [master ↑·1|✚ 1] 
19:15 $ mvn verify -DskipTests -DskipITs
....
[ERROR] around Ant part ...<ant antfile="config/ant-phase-verify.xml"/>... @ 8:47 in java/github/checkstyle/checkstyle/target/antrun/build-main.xml: Exception was thrown while processing java/github/checkstyle/checkstyle/src/it/java/com/google/checkstyle/test/base/BaseCheckTestSupport.java: NullPointerException
```

**Comment by rnveach** [comment]
> Exception was thrown while processing java/github/checkstyle/checkstyle/src/it/java/com/google/checkstyle/test/base/BaseCheckTestSupport.java: NullPointerException

According to my regression report at http://rveach.no-ip.org/checkstyle/regression/reports/90/checkstyle/index.html#A1 , this class was already throwing this exception before my fix. So it seems it is unrelated to the fix.

**Pull request merged**
