### PR TITLE
Issue #2971: Add allowPublicFinalFields option for VisibilityModifier

### PR DESCRIPTION
**Pull request by MEZk**
#2971

@romani 

>
1) please fix CIs
2) please update xdoc files documentation, with config+code examples for new option. As options are very similar to each other, we need to help user to see a difference by examples.
3) Please generate html report with your option on opensource projects to make sure there are no exceptions and reported violations as ok.
Please use this tool - https://github.com/checkstyle/contribution/tree/master/checkstyle-tester , please read README file.
4) Please generate diff-report of execution without your option and with you options to make sure there are no regression.
Please use this tool - https://github.com/checkstyle/contribution/tree/master/patch-diff-report-tool
5) To resolve Travis failures please rebase code over latest master, it is already resolved.

1) Fixed, I had to change confdig_design.xml a bit to satisfy UTs.
2) Done.
3) Reports (allowPublicFinalFields = true, allowPublicImmutableFields = false):

[checkstyle + sevntu-checkstyle](http://mezk.github.io/i2971-VisibilityModifier/after/checkstyle/checkstyle.html)
[guava](http://mezk.github.io/i2971-VisibilityModifier/after/guava/checkstyle.html)
[pmd](http://mezk.github.io/i2971-VisibilityModifier/after/pmd/checkstyle.html)

Reports look good to me.

There are to much noise (over 2000+ violations) on such projects as Spring, Hibernate, Orekit, OpenJDK 8, findbugs. For example: [findbugs](http://mezk.github.io/i2971-VisibilityModifier/after/findbugs/checkstyle.html)

4)

Test projects: checkstyle, sevntu-checkstyle, hibernate, guava, spring, openjdk8, findbugs, pmd, lombok, elasticsearch, java-design-patterns, MaterialDesignLibrary, Orekit, apache-ant, android-launcher, apache-jsecurity, Hbase, infinispan.

4.1)
before
allowPublicImmutableFields = false

after
allowPublicImmutableFields = false
allowPublicFinalFields = false

diff reports are equal

4.2)
before
allowPublicImmutableFields = true

after
allowPublicImmutableFields = true
allowPublicFinalFields = false

diff reports are equal

5) Rebased over latest master.

@som-snytt 
Please, let me know, if you want to include your name into authors section of VisibilityModifierCheck's javadoc.

### CODE REVIEW

**Comment by som-snytt** [comment]
@MEZk Thanks for asking. This wasn't an author task, but fixing code coverage was real work.  It would be nicer if `git log` showed my contribution history. Example where I preserved a fellow's commit when squashing even though my follow-up was substantial: https://github.com/scala/scala/pull/5175/commits  But not a big deal.

Thanks again for picking this up. I ran the tester tool a couple of times but getting up to speed on config and reading results meant delays. A colleague at office loves checkstyle, is always tweaking his set-up; he had an immutable exception class with a warning, which is why I got involved.

**Comment by MEZk** [comment]
@som-snytt 
> Example where I preserved a fellow's commit when squashing even though my follow-up was substantial: https://github.com/scala/scala/pull/5175/commits But not a big deal.

Sorry, could not do this as I changed the original commit a bit. I added you as [author](https://github.com/checkstyle/checkstyle/pull/3207/files#diff-67e0d412b2b09442c70b1cd03c79b858R239), because you implemented the new option.

P.S. Rebased.

**Comment by som-snytt** [comment]
OK, thanks. I just squash into the original commit, and that keeps the author of that commit. Downside is that it means your own supplemental changes are attributed to the original author.

Also thought I'd mention that posting test results to github pages is interesting idea. I had put a placeholder at https://wallcode.github.io/checkstyle/ which gave me the idea of automatically pushing results to e.g. checkstyle/test/my-pr. That would also help for reviewing docs. By coincidence, someone just did that here http://janekdb.github.io/scala/PR-5173/scala/Console%24.html

**Comment by MEZk** [comment]
@som-snytt 
>I just squash into the original commit, and that keeps the author of that commit. 

Done.

**Comment by romani** [comment]
>  It would be nicer if git log showed my contribution history.

Sorry @som-snytt , you had enough time to make it work.

@MEZk , it is completely ok to remove @som-snytt  from author of commit. 
If changes are not complete - they are useless - code is throw away.

It is better to keep you are author as person who did complete solution and not just coding. You can mention in commit message that your work is based on @som-snytt partial patch.
At least it will give me reference to you once we start questioning your changes in future.

Author is person that make commit complete up to the merge. All other are consulter only (me is not a exception too). 

Resolution: @MEZk  should be author or commit

**Comment by som-snytt** [comment]
Yes, that's OK. I don't have a horse in this race, and different projects have different styles.

**Comment by MEZk** [comment]
@romani 
Done.

**Comment by romani** [comment]
@MEZk 

False positive
http://mezk.github.io/i2971-VisibilityModifier/after/findbugs/checkstyle.html
http://mezk.github.io/i2971-VisibilityModifier/after/findbugs/xref/findbugs/findbugs/src/java/edu/umd/cs/findbugs/detect/StreamEscape.html#L30

**Comment by MEZk** [comment]
@romani 
No, it is not a false positive. Class Stream is not in the immutableClassCanonicalNames set.
See [documentation](http://mezk.github.io/i2971-VisibilityModifier/after/findbugs/xref/findbugs/findbugs/src/java/edu/umd/cs/findbugs/detect/StreamEscape.html#L30).

> Field is known to be immutable if: - It's declared as final - Has either a primitive type or instance of class user defined to be immutable (such as String, ImmutableCollection from Guava and etc)
Classes known to be immutable are listed in immutableClassCanonicalNames by their canonical names.

If you rise the question, it can be a signal to extend documentation.

**Comment by romani** [comment]
> No, it is not a false positive (in current option implementation). Class Stream is not in the immutableClassCanonicalNames set.

Whole idea of new option is avoid additional constraint validation for immutability.
Please read issue description attentively.

in report:
```
    allowPublicImmutableFields: "false"
    allowPublicFinalFields: "true"
```

So it mean that immutability should not be checked at all (`...="false"`). If field is public and final - allow it (no violation).

from patch code : 
```
<b>allowPublicFinalFields</b> - which allows immutable fields be declared as
```

Why immutable is not referenced in name ? Why cheat on names ?
Implementation is completely incorrect and should be redone.

> Finally, if we allow public final reference to mutable objects in classes by the option, the encapsulation will be broken

good example. Without this update to Check, Chekcstyle will raise a violation on public field. User have two options: 1) make it private and do not share at all 2) make it private and make a getter on it `StringBuilder getBuilder() { return builder;}`.

case "1)" is the most preferable but not always possible if object has to be shared with other.
case "2)" will satisfy Checkstyle only but functional problem will be the same. So why bother user why option is required ?

> So why bother why option is required ? 

because it is matter of style to have public fields vs getters. Non of the style will dominate it is pure preference decision.
By new option we allow users who like NO-GETTER style access to fields to be possible. The only constraint is to declare field as final (to avoid reassignment). 
If user go further and wants to allow even reassignment - he need to deactivate Check completely.

**Comment by MEZk** [comment]
Option 'allowPublicFinalFields' has been reimplemented. Not it allows all final fields to be public.

New reports:
1) 
1.1)
before
allowPublicImmutableFields = false

after
allowPublicImmutableFields = false
allowPublicFinalFields = false

diff reports are equal

1.2)
before
allowPublicImmutableFields = true

after
allowPublicImmutableFields = true
allowPublicFinalFields = false

diff reports are equal

2) allowPublicFinalFields = true, allowPublicImmutableFields = false
checkstyle(0)
sevntu-checkstyle(0)
[findbugs(1178)](http://mezk.github.io/i2971-VisibilityModifier/findbugs/checkstyle.html)
[guava(329)](http://mezk.github.io/i2971-VisibilityModifier/guava/checkstyle.html)
[pmd(152)](http://mezk.github.io/i2971-VisibilityModifier/pmd/checkstyle.html)
[lombok(182)](http://mezk.github.io/i2971-VisibilityModifier/lombok/checkstyle.html)
[apache-ant(359)](http://mezk.github.io/i2971-VisibilityModifier/apache-ant/checkstyle.html)
[MaterialDesign(162)](http://mezk.github.io/i2971-VisibilityModifier/MaterialDesign/checkstyle.html)

**Comment by romani** [comment]
thanks a lot for update, but reports are huge, shows that there no other regression .... and too much not exactly relevant violations.
please make packageAllowed=true and protectedAllowed=true.

interesting report is a diff report of 
( packageAllowed=true and protectedAllowed=true and allowPublicImmutableFields = true)
vs
( packageAllowed=true and protectedAllowed=true and allowPublicFinalFields = true)

report should show all violations on public final fields are disappear.

**Comment by MEZk** [comment]
@romani 
>why violation on String ? String is default immutable class.

Yes, but InputPublicImmutable is not final itself.

**Comment by romani** [comment]
merged. thanks a lot !

**Pull request merged**
