### PR TITLE
Align method with its return type, and variable with its type

### PR DESCRIPTION
**Pull request by julianhyde**
For example,

```java
  public LongParameterizedType<LongClassName, AnotherLongClassName>
  foo(int arg) {
    return null;
  }
```

Also, fix a few typos.

### CODE REVIEW

**Comment by romani** [comment]
I appreciate your intention to help in the most complicated Check. Changes are too big to let me apply them without created issue and wide explanation of the change in behavior.

Please make reference to issue in commit message

Please split into two PRs typo fix and functional changes. Functional changes will require review and additional testing (i will provide instructions later)

**Comment by julianhyde** [comment]
I moved the small edits into https://github.com/checkstyle/checkstyle/pull/1139.

**Comment by romani** [comment]
@julianhyde , sorry for late reply, please provide more details and prove that style that try to introduce to Checkstyle is in demand. I see a lot of changes in Indentation Inputs that I disagree with. 

Before I start arguing, please provide reasons (the wide explanation the better) of  your update.

**Comment by julianhyde** [comment]
As far as I know this is the default formatting option in Intellij. I don't know about Eclipse.

The main case where this indentation style is necessary is where the return type is a parameterized type. In this case, there is not enough room to fix the return type and the method name on the same line.

Example:

```java
  public static LinkedHashMap<String, ImmutableList<Pair<String, BigDecimal>>>
  longMethodName(int x) {
    return null;
  }
```

In C and C++ (and especially templated C++ functions), people would often put the return type on a different line; see http://programmers.stackexchange.com/questions/200828/reason-for-placing-function-type-and-method-name-on-different-lines-in-c.

I have no objections to making this style optional if you think that not everyone would like it.

**Comment by romani** [comment]
Do you have examples of open source java projects that follow that style convention ?

I need to see that style in real code, the more projects the better, as it will be useful for testing of your changes, uts is not enough for each of our Checks. IndentationCheck is the most complicated Check, so real testing is mandatory.

**Comment by julianhyde** [comment]
I analyzed Calcite, Hive, Guava, Hadoop. I used

```bash
find . -name \*.java |xargs grep -n 'public .*<'|grep -v '[(;=]' | egrep -v ' (class|interface|enum) '
```

to find candidate methods with generic return types.

* Calcite uses this style (i.e. indent 0). Lots of examples in https://github.com/apache/incubator-calcite/blob/master/linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java.
* Hive mostly uses this style (i.e. indent 0). See https://github.com/apache/hive/blob/master/ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcOutputFormat.java#L186 but VectorizedOrcInputFormat has the method name indented 2.
* Guava mostly does not use this style (i.e. indents 2). See e.g. ImmutableSortedMap.of(). But TypeTokenTest has lots of examples that use this style (i.e. indent 0).
* Hadoop is mostly this style (indent 0), but has 2, 4, and even 6.

**Comment by romani** [comment]
Guava is used Indentation that is already implemented
http://checkstyle.sourceforge.net/google_style.html
http://checkstyle.sourceforge.net/reports/google-style/guava/

it has 300 violations that we verified on moment on implementation, they are valid problems.
Google's Java Style for indentaion - http://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s4.8.4.1-switch-indentation

All other projects I will review further ....

**Comment by romani** [comment]
I need more time to make my decision about that style support and how to do that. 
But without an special option(s), it will never be part of Checkstyle. 

IndentationCheck already serve to one style that is wide spread, after update it has to support both, without problems with original. Please share your ideas.

**Comment by romani** [comment]
I can not apply that PR as it brakes current style support.

Please create a issue with description from these comments and lets think how to make checkstyle support that style on configuration level first and then on implementation level.
Your changes will stay forever in that PR, so we could come back to them any time somebody is ready to provide solution to reconcile that indentation styles.

**Comment by julianhyde** [comment]
OK. I think I can find a way to enable this option via configuration. I will open an issue with a proposal.

**Pull request closed without merging**
