### PR TITLE
Fixed typo in Indentation check for word 'initialisation' (Fixes #13783)

### LINKED ISSUE #13783: Fix typo in Indentation check for word 'initialisation'
from https://github.com/checkstyle/checkstyle/pull/13778#discussion_r1336536013

fix typo in Indentation check for word `initialisation`
should be `initialization`

consider https://sapling.ai/usage/initialize-vs-initialise

### PR DESCRIPTION
**Pull request by shubham562004**
#13783 issue fixed.

Word 'intialisation' repaced by 'intialization'.

Also this is my first contribution and  i am looking forward to contributing to this project and grow my skills with the help of community.
please revive my PR as soon as posible.
Thanks.

### CODE REVIEW

**Comment by romani** [comment]
Always keep single commit in PR, please read CI failures and follow them

**Comment by nrmancuso** [comment]
@romani https://github.com/checkstyle/checkstyle/issues/13783#issuecomment-1777074344

**Comment by romani** [comment]
Issue is closed by https://github.com/checkstyle/checkstyle/pull/13912

Sorry for lack of tracking in issues tracker

**Comment by romani** [comment]
@shubham562004 , for contribution please read https://github.com/checkstyle/checkstyle/wiki/To-GSoC-participant it suggests best way to be more familiar with project.

**Comment by shubham562004** [comment]
@romani Thanks for your guidance.
IT is very helpfull as a newbie.

**Pull request closed without merging**
