### PR TITLE
Issue: #5393 Some contents in messages_zh.properties for imports check are not well translated

### PR DESCRIPTION
**Pull request by Apache9**
Fix for #5393 
Change the Traditional Chinese to Simplified Chinese.
Align the translation for word 'import' to '导入'.

### CODE REVIEW

**Comment by romani** [comment]
please put in commit message prefix "Issue #5393: ...." to fix CIs.
CI have to be green to let us merge PR.

**Comment by Apache9** [comment]
@romani Done.

**Comment by romani** [comment]
@Apache9 , thanks a lot.

**Comment by Apache9** [comment]
@romani You're welcome.
I've been using checkstyle for many years(IIRC start from 5.3), glad that I could contribute to this project.

**Comment by romani** [comment]
You can contribute to any other issue ;) , we can guide in development process

**Pull request merged**
