### PR TITLE
Issue #15340: created InputFile for section 5.2.2 Class Names

### PR DESCRIPTION
**Pull request by Zopsss**
#15340

### CODE REVIEW

**Comment by romani** [comment]
@Zopsss , CI is red, please fix

**Comment by Zopsss** [comment]
CI failure reason same as https://github.com/checkstyle/checkstyle/pull/15586#issuecomment-2321988141

**Review by rdiachenko — APPROVED** [review]
lgtm

**Review by romani — APPROVED** [review]
Ok to merge

**Pull request merged**
