### PR TITLE
doc: fixed broken filefilters link

### PR DESCRIPTION
**Pull request by kgeis**
doc: fixed broken filefilters link

### CODE REVIEW

**Comment by rnveach** [comment]
@kgeis Thanks for noticing that.
Please rename commit to `config: fixed broken filefilters link` and I will merge.

**Comment by romani** [comment]
It is better to make prefix "doc:" ,in this case you will be referenced as contributor in release notes

**Comment by rnveach** [comment]
@kgeis You realize we meant the actual commit name, not the PR title?

**Comment by kgeis** [comment]
@rnveach, yes, I realized that, but I thought I renamed the commit. It might be a couple of days until I can get to this. I'm not sure how rename the commit in Github, so I may need to just submit a separate PR and close this one.

**Comment by romani** [comment]
commit was amended, merged as FF.

**Pull request closed without merging**
