### PR TITLE
Issue #2899: Explanations now present to differentiate between try-with-resources tokens in Javadoc

### PR DESCRIPTION
**Pull request by subkrish**
Issue #2899

### CODE REVIEW

**Comment by MEZk** [comment]
@subkrish 
Please, use Present Simple in the commit message. Rather than writing messages that say what a committer has done. It's better to consider these messages as the instructions for what is going to be done after the commit is applied on the repo.

**Comment by romani** [comment]
@subkrish , users are hardly understand explanation by works if they do not know terminology (nobody remember all terminology). So example of tree should be provided as for other Tokens.

```
$ cat MyClass.java 
public class MyClass {
    public void foo() {
        try (BufferedReader br =
                       new BufferedReader(new FileReader(path))) {
            return br.readLine();
        }
    }

}

$ java -jar checkstyle-7.6-all.jar -t MyClass.java 
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> MyClass [1:13]
`--OBJBLOCK -> OBJBLOCK [1:21]
    |--LCURLY -> { [1:21]
    |--METHOD_DEF -> METHOD_DEF [2:4]
    |   |--MODIFIERS -> MODIFIERS [2:4]
    |   |   `--LITERAL_PUBLIC -> public [2:4]
    |   |--TYPE -> TYPE [2:11]
    |   |   `--LITERAL_VOID -> void [2:11]
    |   |--IDENT -> foo [2:16]
    |   |--LPAREN -> ( [2:19]
    |   |--PARAMETERS -> PARAMETERS [2:20]
    |   |--RPAREN -> ) [2:20]
    |   `--SLIST -> { [2:22]
    |       |--LITERAL_TRY -> try [3:8]
    |       |   |--RESOURCE_SPECIFICATION -> RESOURCE_SPECIFICATION [3:12]
    |       |   |   |--LPAREN -> ( [3:12]
    |       |   |   |--RESOURCES -> RESOURCES [3:13]
    |       |   |   |   `--RESOURCE -> RESOURCE [3:13]
    |       |   |   |       |--MODIFIERS -> MODIFIERS [3:13]
    |       |   |   |       |--TYPE -> TYPE [3:13]
    |       |   |   |       |   `--IDENT -> BufferedReader [3:13]
    |       |   |   |       |--IDENT -> br [3:28]
    |       |   |   |       `--ASSIGN -> = [3:31]
    |       |   |   |           `--EXPR -> EXPR [4:23]
    |       |   |   |               `--LITERAL_NEW -> new [4:23]
    |       |   |   |                   |--IDENT -> BufferedReader [4:27]
    |       |   |   |                   |--LPAREN -> ( [4:41]
    |       |   |   |                   |--ELIST -> ELIST [4:42]
    |       |   |   |                   |   `--EXPR -> EXPR [4:42]
    |       |   |   |                   |       `--LITERAL_NEW -> new [4:42]
    |       |   |   |                   |           |--IDENT -> FileReader [4:46]
    |       |   |   |                   |           |--LPAREN -> ( [4:56]
    |       |   |   |                   |           |--ELIST -> ELIST [4:57]
    |       |   |   |                   |           |   `--EXPR -> EXPR [4:57]
    |       |   |   |                   |           |       `--IDENT -> path [4:57]
    |       |   |   |                   |           `--RPAREN -> ) [4:61]
    |       |   |   |                   `--RPAREN -> ) [4:62]
    |       |   |   `--RPAREN -> ) [4:63]
    |       |   `--SLIST -> { [4:65]
    |       |       |--LITERAL_RETURN -> return [5:12]
    |       |       |   |--EXPR -> EXPR [5:30]
    |       |       |   |   `--METHOD_CALL -> ( [5:30]
    |       |       |   |       |--DOT -> . [5:21]
    |       |       |   |       |   |--IDENT -> br [5:19]
    |       |       |   |       |   `--IDENT -> readLine [5:22]
    |       |       |   |       |--ELIST -> ELIST [5:31]
    |       |       |   |       `--RPAREN -> ) [5:31]
    |       |       |   `--SEMI -> ; [5:32]
    |       |       `--RCURLY -> } [6:8]
    |       `--RCURLY -> } [7:4]
    `--RCURLY -> } [9:0]
```

Please grab example of tree to javadoc , format it as in other javadocs. All changed by you javadoc should have an example/layout of tree structure

**Comment by subkrish** [comment]
@romani @rnveach Changes have been made. Please review.

**Comment by romani** [comment]
Please place AST tree example to RESOURCE_SPECIFICATION. Other tokens should have a comment to redirect user to RESOURCE_SPECIFICATION for example of tree structure

**Comment by subkrish** [comment]
@romani Should I remove the existing example and add this or add this one after the existing one?

**Comment by romani** [comment]
Please move example to new place

**Pull request merged**
