### PR TITLE
Issue #6207: Add xpath regression test for ModifierOrder

### PR DESCRIPTION
**Pull request by zyrate**
Issue #6207
Add three XPath regression tests for `ModifierOrder` check.
Documentation：`https://checkstyle.sourceforge.io/config_modifier.html#ModifierOrder`.

### CODE REVIEW

**Comment by romani** [comment]
@zyrate , CI is failing.

**Comment by zyrate** [comment]
Is it beacuase there should not be a newline at end of file? @romani

**Comment by zyrate** [comment]
And I got this error when runing `mvn clean verify` locally:
image
Is it matter?

**Comment by romani** [comment]
yes, but looks like there in DNS problem with your internet provider, as it does not see checkstyle.org.
is it persistent and always happened on your side? if that is persistent problem , you can try to ignore this test to bypass it, and focus on other violations.

**Comment by romani** [comment]
> Is it beacuase there should not be a newline at end of file?

yes, keep following what CI or `mvn verify` demands.

**Review by romani — APPROVED** [review]
ok to merge if CI pass

**Comment by zyrate** [comment]
Thanks for reviewing!

**Comment by zyrate** [comment]
One error remains , please help me what's wrong:  `run-inspections` 
```txt
Intellij Idea validation is about to start
Progress output will be flushed at end. Validation is in progress ...
2023-03-14 13:36:53,074 [    171]   WARN - j.u.prefs - Prefs file removed in background /home/circleci/.java/.userPrefs/prefs.xml
2023-03-14 13:41:01,079 [ 248176]   WARN - #c.i.u.j.JBCefApp - JCEF is manually disabled in headless env via 'ide.browser.jcef.headless.enabled=false'
2023-03-14 13:45:58,464 [ 545561] SEVERE - #c.i.c.InspectionsResultUtil - Descriptions are missed for tools: PreviewPickerAnnotation
java.lang.Throwable: Descriptions are missed for tools: PreviewPickerAnnotation
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.codeInspection.InspectionsResultUtil.describeInspections(InspectionsResultUtil.java:98)
	at com.intellij.codeInspection.InspectionApplicationBase.runAnalysis(InspectionApplicationBase.java:480)
	at com.intellij.codeInspection.InspectionApplicationBase.runAnalysisOnScope(InspectionApplicationBase.java:431)
	at com.intellij.codeInspection.InspectionApplicationBase.run(InspectionApplicationBase.java:211)
	at com.intellij.codeInspection.InspectionApplicationBase.execute(InspectionApplicationBase.java:151)
	at com.intellij.codeInspection.InspectionApplicationBase.startup(InspectionApplicationBase.java:119)
	at com.intellij.codeInspection.InspectionMain.main(InspectionMain.java:115)
	at com.intellij.openapi.application.ApplicationStarter.main(ApplicationStarter.java:52)
	at com.intellij.idea.ApplicationLoader$initApplication$4.accept(ApplicationLoader.kt:185)
	at com.intellij.idea.ApplicationLoader$initApplication$4.accept(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1810)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2023-03-14 13:45:58,466 [ 545563] SEVERE - #c.i.c.InspectionsResultUtil - IntelliJ IDEA 2022.2.2  Build #IC-222.4167.29
2023-03-14 13:45:58,467 [ 545564] SEVERE - #c.i.c.InspectionsResultUtil - JDK: 17.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-03-14 13:45:58,467 [ 545564] SEVERE - #c.i.c.InspectionsResultUtil - OS: Linux
Checking results ...
There are inspection problems. Review results in 'ARTIFACTS' tab above.

Exited with code exit status 1
```

**Comment by nrmancuso** [comment]
@zyrate please read CI output you shared above: `There are inspection problems. Review results in 'ARTIFACTS' tab above.` Visit artifacts tab and view report to see failing inspections.

**Comment by romani** [comment]
@nrmancuso , looks like we need few more empty lines and message `Dear GitHub contributor, ....`

**Comment by zyrate** [comment]
Fixed

**Pull request merged**
