### PR TITLE
Issue #6207: Add Xpath regression test for LocalFinalVariableName

### PR DESCRIPTION
**Pull request by Lmh-java**
Part of issue #6207

### CODE REVIEW

**Review by MANISH-K-07 — COMMENTED** [review]
@Lmh-java ,
I think it would be better if we cover one input for Ctors and class fields

**Comment by Lmh-java** [comment]
Sure, I can do Ctors, but can you elaborate more on class fields? I don't think we need class fields here, since this is the check for final local variables inside a method (correct me if I am wrong)

**Comment by MANISH-K-07** [comment]
Thanks for the reply.. otherwise I wouldn't have gone through the check now ;)
Please hold on until we get a bit of clarity....

@romani ,
Could you please tell me why LocalFinalVariableNameCheck is only testing for three tokens (basically just parameters and try-with-resources block).
I believe this should apply to final variables in Ctors as well? Infact, it should apply to any block in general ??
Please correct me in case my understanding of this check is wrong 😅

**Comment by Lmh-java** [comment]
I took a close look at the checker. Here is a screenshot of the class-level comment.
image
So it is only checking `VARIABLE_DEF`, `PARAMETER_DEF`, and 'RESOURCE'.
The checker also re-writes `mustCheckName(DetailAST)` to only focus on local variables. The method detects variables declared in "a code block, a for initializer, or a catch parameter".

Therefore, I think I might need to include extra tests for:
- [ ] final variables declaration inside a `for` initializer.
- [ ] parameters of a method that are marked as final.
And these tests would have different Xpath structures.

Hi @MANISH-K-07 , what's your opinion about this?

**Comment by MANISH-K-07** [comment]
> Hi @MANISH-K-07 , what's your opinion about this?

Your post is basically a duplicate of my question at https://github.com/checkstyle/checkstyle/pull/14639#issuecomment-1987340360.  😂
You are partially right though, That is what the description says but I'm not sure what the Check is actually testing. I will run a few test cases as soon as I get on my laptop, and get back with answers !!

> @romani ,
> Could you please tell me why LocalFinalVariableNameCheck is only testing for three tokens (basically just parameters and try-with-resources block).
> I believe this should apply to final variables in Ctors as well? Infact, it should apply to any block in general ??
> Please correct me in case my understanding of this check is wrong 😅

Meanwhile, Let's wait for @romani to have a look at my query at https://github.com/checkstyle/checkstyle/pull/14639#issuecomment-1987340360
;)

**Review by romani — APPROVED** [review]
Ok to merge.

This Check only for local variables , not parameters.
We should have separate Check to cover parameters

**Pull request merged**
