### PR TITLE
Issue #1002: Add optional attribute to suppression filter

### PR DESCRIPTION
**Pull request by liscju**
This implementation lacks dealing with the fact that SuppressionsLoader.loadSuppressions doesnt throw exceptions only when the file is missing, the exceptions are thrown also when the supression file has bad structure. 

So i have question what should i do: should SupressionsLoader.loadSuppressions should be refactored to throw CheckstyleException and FileNotFoundException or should i do sth else to deal with this(for example it can read from CheckstyleException msg and checks if it was matching file not found error msg, but this seems like "Primitive Obsession" code smell)?

### CODE REVIEW

**Comment by romani** [comment]
TeamCity problems need to be resolved.

**Comment by romani** [comment]
@liscju ,

in SuppressionFilter.java we need to check for file existence separately or make special method in SuppressionsLoader.

We should not mix FileNotExists and CheckstyleException during parsing. If file exists and there are errors during parsing we should fail with exception (in other case we hiding a config problem).

**Comment by liscju** [comment]
@romani i sent proposition for checking if file exist in second commit, let me know what you think about it. If the proposition will be accepted i will fix style errors, if not i will try to propose sth else.

**Comment by romani** [comment]
I am ok with design.

**Comment by liscju** [comment]
@romani
 i have problems with getting 100% percent coverage. Especially closing stream in try/catch block like this:
```java
try {
            final URI uriByFilename = CommonUtils.getUriByFilename(fileName);
            sourceInput = uriByFilename.toURL().openStream();
        }
        catch (CheckstyleException ex) {
            suppressionSourceExists = false;
        }
        catch (MalformedURLException ex) {
            suppressionSourceExists = false;
        }
        catch (IOException ex) {
            suppressionSourceExists = false;
        }
        finally {
            if (sourceInput != null) {
                try {
                    sourceInput.close();
                }
                catch (IOException ex) {
                    suppressionSourceExists = false;
                }
            }
        }
```

Two others strange example to cover are : 
a) method declaration not covered:
```java
protected void finishLocalSetup() throws CheckstyleException {
```

b) simple instruction conditional not covered(where instruction is not conditional)
```java
final URI uriByFilename = CommonUtils.getUriByFilename(fileName);
```

I attaching screen of coverage report:
coveragereport

I would be gladful for any suggestions how should i cover it.

**Comment by romani** [comment]
if 100% coverage is not reachable in normal workflow we try to use PowerMock, if it can not help also, we use ugly reflection. That is not very good in general but we do this only in test area of code and we get increasable value from 100% coverage so we are ok to damage code clearness in test are. Extra comment should be placed to explain design. 

You can find bunch of examples of complicated streams mocking and ugly reflection in our test.

**Comment by mkordas** [comment]
@liscju have you tried running `mvn clean` before generating report? If you forget to do it then you'll get strange coverage results. Moreover, you can always use IntelliJ Coverage or Jacoco just to see whether coverage is really missing or it's bug in Cobertura.

**Comment by romani** [comment]
@liscju , let me know if you need help to finish this PR.

**Comment by MEZk** [comment]
@liscju 

>protected void finishLocalSetup() throws CheckstyleException {

Means that CheckstyleException  is not thrown. Implement UT in which CheckstyleException  will be thrown.

>final URI uriByFilename = CommonUtils.getUriByFilename(fileName);

There are 2 way of execution:
1) Exception does not appear in try block.
2) Exception appears on line 122.

Next, line 127 and 133. Again 2 way of execution: 
1) Condition is true, we step in if-block immediately.
2) Condition is false, we do not step in if-block and go to line 133 immediately.

Line 128. You should implement 2 UTs: first one is when IOException is not thrown in try block and second is when execution proccess goes to catch block.

The CyclomaticComplexity and similar metrix which can be calculated in IDEA and Exclipse can help you to decide how many UTs you need to cover the code.

**Comment by mkordas** [comment]
@MEZk yes, IntelliJ coverage is line based (not bytecode  based) and has some bugs, but usually when it shows something isn't covered it really isn't covered. Doesn't work another way: IntelliJ may show 100% coverage while Jacoco/Cobertura see much less.

**Comment by liscju** [comment]
@romani 
I ran into problem with using EqualsVerifier and Powermock in same test. When test is annotated with 
```java
@RunWith(PowerMockRunner.class)
@PrepareForTest({SomeClasses})
```
 and test uses EqualsVerifier there is NullPointerException in the background but the test passes and cobertura doesn't recognise equals and hashCode as covered. I created issue for this in https://github.com/jqno/equalsverifier/issues/132#issuecomment-171952488 and at this moment issue is accepted as valid. What should i do in this situation:
1) wait for issue to be resolved
2) tests using Powermock runner can be extracted to other test class, but i have no idea what this class could be named to express this situation

**Comment by romani** [comment]
some workaround has to be done.... do we any other options/workarounds ?

**Comment by liscju** [comment]
@romani it looks like at this moment either test would be split or test shouldn't use powermock and instead use some form of reflection to cover this situation(i would strongly discourage this option but certainly i will adapt to the decision)

**Comment by romani** [comment]
> of reflection to cover this situation

Life is not ideal, if we put a appropriate comment with link to issue we are waiting to be resolved, it is ok to use ugly workaround.

**Comment by liscju** [comment]
@romani where can i find solutions using reflection to cover such situation in project right now?

**Comment by romani** [comment]
I do not remember, I will take a look at your problem closely a bit later.

**Comment by mkordas** [comment]
@liscju here are some examples of using reflection mainly for testing: https://github.com/checkstyle/checkstyle/search?utf8=%E2%9C%93&q=IllegalAccessException

**Comment by jqno** [comment]
I just wanted to let you know that the issue in EqualsVerifier which is mentioned above, should now be fixed if you update to version 1.7.7.

**Comment by mkordas** [comment]
@jqno thanks a lot for helping with that!

**Comment by liscju** [comment]
Thanks for such a quick solution in equalsverifier we don't need to think about workaround anymore, i sent bumping version of equalsverifier included in a patch with solution to issue

**Comment by romani** [comment]
thanks a lot to all.

@liscju , lets make one more and make TC green.

**Comment by liscju** [comment]
@romani there are some inspection erros i have doubts how to resolve:

1) Errors are 'Scope of variable fileName is too broad' and 'Scope of variable optional is too broad', 
the code snippets is

```java
@Test
    public void testExistingSuppressionFileWithTrueOptionalThrowsIoErrorWhileClosing()
            throws Exception {
        final String fileName = "src/test/resources/com/puppycrawl/tools/checkstyle/filters/"
                + "suppressions_none.xml";
        final boolean optional = true;

        final InputStream inputStream = PowerMockito.mock(InputStream.class);
        BDDMockito.doThrow(IOException.class).when(inputStream).close();

        final URL url = PowerMockito.mock(URL.class);
        BDDMockito.given(url.openStream()).willReturn(inputStream);

        final URI uri = PowerMockito.mock(URI.class);
        BDDMockito.given(uri.toURL()).willReturn(url);

        PowerMockito.mockStatic(CommonUtils.class);
        BDDMockito.given(CommonUtils.getUriByFilename(fileName)).willReturn(uri);

        final SuppressionFilter filter = createSupressionFilter(fileName, optional);
        final AuditEvent ev = new AuditEvent(this, "AnyFile.java", null);
        Assert.assertTrue(filter.accept(ev));
    }
```

Should i move those two variables right before their uses in method(because this is the only way how them seem to me to has a 'broad scope')?


2) Error is 'Unused catch parameter ex ' in suppressionSourceExists method:

```java
private static boolean suppressionSourceExists(String fileName) {
        boolean suppressionSourceExists = true;
        InputStream sourceInput = null;
        try {
            final URI uriByFilename = CommonUtils.getUriByFilename(fileName);
            final URL url = uriByFilename.toURL();
            sourceInput = url.openStream();
        }
        catch (CheckstyleException ex) {
            suppressionSourceExists = false;
        }
        catch (IOException ex) {
            suppressionSourceExists = false;
        }
        finally {
            if (sourceInput != null) {
                try {
                    sourceInput.close();
                }
                catch (IOException ex) {
                    suppressionSourceExists = false;
                }
            }
        }
        return suppressionSourceExists;
    }
``` 
Because i dont need information about exception, but only the fact that they were thrown , the only solution(it seems to me) is to annotate method with @SuppressWarnings("unused")

3) Error is 'Instance method name testExistingSuppressionFileWithTrueOptionalThrowsIoErrorWhileClosing is too long' , now test name is describing what is testing, i have no idea how to preserve test name to describe behavior and not to be that long.

**Comment by mkordas** [comment]
@liscju my answers below:
1. Let's move them just above usages, but I'm not really sure why TC complains here.
2. You can name catch parameter `ignored`:
   image
3. Let's allow such names in [intellij-idea-inspections.xml](https://github.com/checkstyle/checkstyle/blob/master/config/intellij-idea-inspections.xml#L1036).

**Comment by romani** [comment]
> 3) testExistingSuppressionFileWithTrueOptionalThrowsIoErrorWhileClosing

I am almost always ok with long name, but 65 is more than enough for a name. It is already too much.
What about `testExistingConfigWithTrueOptionalThrowsIoErrorWhileClosing` ?

http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter there is no other config file in this Filter, I doubt that smb will find a problem with a name.

**Comment by liscju** [comment]
@mkordas , changed 1),2) according to suggestions
@romani , 3) point changed to proposed name

**Comment by romani** [comment]
@liscju , please do last minor change to make all CIs green.

**Comment by liscju** [comment]
@romani , fixes done as requested

**Comment by romani** [comment]
> `@Test(expected = CheckstyleException.class)`

please avoid usage of "expected" property of Test annotation, in this case you do not care what kind of CheckstyleException is happen, and completely rely on current implementation.
Test should be unrelated to implementation as much as possible and be strict for exception checking to validate not only type(CheckstyleException) of it but and message too, to be sure that smth that is thrown is what you expect.

FYI: https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/108 still not done :( , but this is very often mistake.

**Comment by romani** [comment]
@liscju , release will be in 10 day, it will be awesome to have this update in next release. We are almost done with this PR.

**Comment by liscju** [comment]
@romani moved checking exception expectation into a test method body in the latest commit

**Comment by romani** [comment]
merged as FF.


thanks a lot!

**Pull request closed without merging**
