### PR TITLE
 Add LineSeparatorOption.LF_CR_CRLF

### PR DESCRIPTION
**Pull request by msteiger**
This PR adds the `LineSeparatorOption.ANY` and the respective checks in `NewlineAtEndOfFileCheck`. Also, a unit test is added to cover the new functionality.

**Why is that useful?**
Our team uses common configuration files, so we need to share one setting. However, I would like to use `LF` line endings on Windows, just as git does internally to avoid file conversions. This is currently not possible.

With the `ANY` option, the two questions "Which line ending type is used?" and "Is there a new line at the end of the file" can now be looked at separately. 

I also changed the comparison method from String to byte[] in the `US_ASCII` charset, as it avoids the wrapping and is invariant to the used Locale. It is also probably a lot faster.

Sidenote: The first question is not answered yet by any of the checks yet. Maybe a new LineEnding check makes sense to ensure that all files use the same type?

I also added "InputNewlineLfAtEndOfFile.java" to `.gitattributes`, since the test explicitly covers `LF` line endings.

https://help.github.com/articles/dealing-with-line-endings/
http://git-scm.com/docs/gitattributes

### CODE REVIEW

**Comment by romani** [comment]
build id failed.
please make sure that "mvn clean verify" works well.

**Comment by msteiger** [comment]
Compilation and tests run fine. The problem seems to be this:

    [..]checks.LineSeparatorOption failed check. Branch coverage rate of 62.5% is below 100.0%
    [..]checks.LineSeparatorOption failed check. Line coverage rate of 93.3% is below 100.0%

Any idea how to fix this?

**Comment by romani** [comment]
just improve the test coverage by junit.

**Comment by msteiger** [comment]
I added more tests, now covering even more than the newly introduced functionality. Cobertura is still unhappy though. Any idea why?

https://travis-ci.org/checkstyle/checkstyle/jobs/60965148#L2762

**Comment by mkordas** [comment]
Just generate Cobertura report and it will become clear. Only one path of third condition is covered:
image

**Comment by msteiger** [comment]
I realize that you are quite serious about testing code. Makes sense for a code analytics tool, I guess. Cobertura is happy now - thanks for the hint, @mkordas.

**Comment by romani** [comment]
> I realize that you are quite serious about testing code. Makes sense for a code analytics tool, I guess. 

It is the only way to avoid regression, especially when development team is tiny. Checkstyle is library and fortunately all could be unit-tested, so now we have an approach to enforce tests over any new functionality. Full coverage does NOT ensure that code works well, but at least we sure that it does not crashes on the simple cases. All development in Checkstyle is test-driven (TDD).

I will do code review of your code in next few days, sorry for delay.

**Comment by romani** [comment]
please squash all (3) commits in one, that will simplify a code review, we do not merged commits that brake a build.

**Comment by romani** [comment]
While changes under review, please put a reference to that issue for wide description of a problem.

**Comment by msteiger** [comment]
I updated the commit message.

**Comment by romani** [comment]
I noticed, thanks a lot, I will address your PR after my vacation.

I need to think about what is 'AB' at ```ANY("AB")``` it is not clear for me, is it just smth or  ?
If that is just smth, please use "" or "##NEVER-MATCH###" (or simlar) put a description in comment why it has such value.

**Comment by romani** [comment]
> Sidenote: The first question is not answered yet by any of the checks yet. Maybe a new LineEnding check makes sense to ensure that all files use the same type?

please join to discussion of #893 .

**Comment by romani** [comment]
http://en.wikipedia.org/wiki/Newline

>  This is why a newline in character encoding can be defined as LF and CR combined into one (LF+CR, LFCR, CR+LF, CRLF).


So term ANY is not correct in our scope, as we do only cover only 3 combinations, even chances of other combinations usage is minimal in real life, and user can be crazy with defining end-of-line through SYSTEM.
So we need to rename ANY to what it actually is in a code LF_CR_CRLF.

> Matches any line separators

Please rename enum element and update its javadoc and comments.
Content of value should be "##" (instead of 'XX') as clear sign of smth non existing in java syntax and smth that will never compile.

**Comment by romani** [comment]
1) please rebase your changes on latest code (I have problem to merge), sorry for caused inconvenience.

2) we need to update Html documentation, http://checkstyle.sourceforge.net/config_misc.html#NewlineAtEndOfFile , http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.html
source of it is there https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_misc.xml#L19 and in javadoc of target class.

**Comment by romani** [comment]
Please squash commits or put issue reference to second commit message

**Comment by msteiger** [comment]
Thanks for the hint about the xml file. I've updated the brackets to match the new standard and the documentation (I also added "system" where it was still missing) and squashed (`fixup` to be precise) the changes.

**Comment by romani** [comment]
merged as FF.
thanks a lot for persistence to make accurate fix to the problem!

**Pull request closed without merging**
