### PR TITLE
Issue #8889: fix NonEmptyAtclauseDescriptionCheck for empty descriptions

### LINKED ISSUE #8889: NonEmptyAtclauseDescription does not work for @return
Check documentation: https://checkstyle.sourceforge.io/config_javadoc.html#NonEmptyAtclauseDescription

```
D:\dev\checkstyle>javac Sample.java

D:\dev\checkstyle>cat Sample.java
class Sample {
    // Bug: `@return` does not produce an error.

    /**
     * @param a xxx
     * @return
     */
    int foo(int a) {
        return a;
    }
}

D:\dev\checkstyle>cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
    "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">                                                                                                  
        <module name="NonEmptyAtclauseDescription"/>
    </module>
</module>                                                                                                               
D:\dev\checkstyle>java -Duser.language=en -Duser.country=US -jar checkstyle-8.36.2-all.jar -c config.xml Sample.java
Starting audit...
Audit done.

D:\dev\checkstyle>
```

---------------

Problem: empty `@return` clause is not reported as an error. In the test file above, if you change `@param a xxx` to `@param a`, then it reports an error there, as expected. However `@return` line produces no error.

### PR DESCRIPTION
**Pull request by strkkk**
Closes #8889 

Diff Regression projects: https://gist.githubusercontent.com/nmancus1/e3988f8092d919b5cbe70f5359c4d9e8/raw/a0f6f5860f8025c19868061dee6e0e40960b992f/projects-to-test-on.properties

Diff Regression config: https://gist.githubusercontent.com/strkkk/a6e04b73158d1ef6f563dd5aab753361/raw/c89894fe9b9c5bd8a3ddc7c17023340806449941/constant_name

### CODE REVIEW

**Comment by strkkk** [comment]
GitHub, generate report

**Comment by strkkk** [comment]
GitHub, generate report

**Review by pbludov — APPROVED** [review]
I'm OK to merge

**Comment by pbludov** [comment]
Interesting that the regression only shows violations for the `@return` tag. This seems to be the effect of automatic Javadoc generation in some IDEs.

**Review by romani — APPROVED** [review]
Ok to merge

**Pull request merged**
