### PR TITLE
Issue #11637: Resolve shellcheck SC2005

### PR DESCRIPTION
**Pull request by shubh220922**
Related to #11637

### CODE REVIEW

**Comment by shubh220922** [comment]
@romani @rnveach @nrmancuso 

### Testing results

#### Testing on master branch
upon execution of ``bash .ci/validation.sh no-error-xwiki`` , the build is successful for all the mvn and bash commands within. 

#### Testing on my branch which contains the changes of the lastest push

```
[INFO] XWiki Platform - Wiki - REST - Parent POM .......... SUCCESS [  0.193 s]
[INFO] XWiki Platform - Wiki - REST - API ................. SUCCESS [  0.199 s]
[INFO] XWiki Platform - Wiki - REST - Default implementation SUCCESS [  0.207 s]
[INFO] XWiki Platform - Wiki - Template - Default ......... SUCCESS [  0.214 s]
[INFO] XWiki Platform - Wiki - Template - Script .......... SUCCESS [  0.204 s]
[INFO] XWiki Platform - Wiki - User - Default ............. SUCCESS [  0.226 s]
[INFO] XWiki Platform - Wiki - User - Script .............. SUCCESS [  0.283 s]
[INFO] XWiki Platform - Wiki - UI - Parent POM ............ SUCCESS [  0.198 s]
[INFO] XWiki Platform - Wiki - UI - Common ................ SUCCESS [  0.203 s]
[INFO] XWiki Platform - Wiki - UI - Main Wiki ............. SUCCESS [  0.203 s]
[INFO] XWiki Platform - Wiki - UI - Wiki .................. SUCCESS [  0.206 s]
[INFO] XWiki Platform - Wiki - Workspaces Migrator ........ SUCCESS [  0.220 s]
[INFO] XWiki Platform - WYSIWYG Editor - Wiki Pages ....... SUCCESS [  0.194 s]
[INFO] XWiki Platform - XML - Script Service .............. SUCCESS [  0.202 s]
[INFO] XWiki Platform - ZIP Explorer ...................... SUCCESS [  0.203 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:21 min
[INFO] Finished at: 2023-02-18T15:44:54+05:30
[INFO] ------------------------------------------------------------------------
[INFO] 489 goals, 489 executed
╭─shubh220922@fedora ~/Desktop/checkstyle_project/checkstyle ‹SC2005› 
╰─$ 
```

It is a build success here too just like the master branch.

Now,

@rnveach is this what you expected from me in https://github.com/checkstyle/checkstyle/pull/12688#issuecomment-1416877159

**Review by romani — APPROVED** [review]
Ok to merge if proven by execution .

https://github.com/checkstyle/checkstyle/blob/c9190ed2fbb919beafeb992bbce98912c6fa8717/.ci/validation.sh#L258

We need output of line
https://github.com/checkstyle/checkstyle/blob/c9190ed2fbb919beafeb992bbce98912c6fa8717/.ci/validation.sh#L261

Here it is https://circleci.com/api/v1.1/project/github/checkstyle/checkstyle/246092/output/103/0?file=true&allocation-id=63f0981bcefe8c1514682c9a-0-build%2F66EEDF9 

>version:10.7.1-SNAPSHOT antlr4:4.11.1
[INFO] Error stacktraces are turned on.

**Comment by shubh220922** [comment]
@romani 

For this code:
image

The output is:
```
╭─shubh220922@fedora ~/Desktop/checkstyle_project/checkstyle ‹SC2005●› 
╰─$ bash .ci/validation.sh no-error-xwiki
version:10.7.1-SNAPSHOT antlr4:4.11.1
╭─shubh220922@fedora ~/Desktop/checkstyle_project/checkstyle ‹SC2005●› 
╰─$ 
```

**Review by nrmancuso — APPROVED** [review]

**Comment by nrmancuso** [comment]
travis failure is not related

**Pull request merged**
