### PR TITLE
Issue #14631: Updated SERIAL_FIELD_LITERAL of JavadocTokenTypes to new AST format

### PR DESCRIPTION
**Pull request by Prathamesh-007**
Begin #14631 

Example:
```
PS C:\Users\Hp\Desktop\4th year> cat Test.java
public class Test {
 /**
   * Some Java doc.
   * @serialField counter Integer objects counter
   */
  private void boo();
}
```

Tree:
```
PS C:\Users\Hp\Desktop\4th year> java -jar checkstyle-10.14.2-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
COMPILATION_UNIT -> COMPILATION_UNIT
`--CLASS_DEF -> CLASS_DEF
    |--MODIFIERS -> MODIFIERS
    |   `--LITERAL_PUBLIC -> public
    |--LITERAL_CLASS -> class
    |--IDENT -> Test
    `--OBJBLOCK -> OBJBLOCK
        |--LCURLY -> {
        |--METHOD_DEF -> METHOD_DEF
        |   |--MODIFIERS -> MODIFIERS
        |   |   |--BLOCK_COMMENT_BEGIN -> /*
        |   |   |   |--COMMENT_CONTENT -> *\r\n   * Some Java doc.\r\n   * @serialField counter Integer objects counter\r\n
        |   |   |   |   `--JAVADOC -> JAVADOC
        |   |   |   |       |--NEWLINE -> \r\n
        |   |   |   |       |--LEADING_ASTERISK ->    *
        |   |   |   |       |--TEXT ->  Some Java doc.
        |   |   |   |       |--NEWLINE -> \r\n
        |   |   |   |       |--LEADING_ASTERISK ->    *
        |   |   |   |       |--WS ->
        |   |   |   |       |--JAVADOC_TAG -> JAVADOC_TAG
        |   |   |   |       |   |--SERIAL_FIELD_LITERAL -> @serialField
        |   |   |   |       |   |--WS ->
        |   |   |   |       |   |--FIELD_NAME -> counter
        |   |   |   |       |   |--WS ->
        |   |   |   |       |   |--FIELD_TYPE -> Integer
        |   |   |   |       |   |--WS ->
        |   |   |   |       |   `--DESCRIPTION -> DESCRIPTION
        |   |   |   |       |       |--TEXT -> objects counter
        |   |   |   |       |       |--NEWLINE -> \r\n
        |   |   |   |       |       `--TEXT ->
        |   |   |   |       `--EOF -> <EOF>
        |   |   |   `--BLOCK_COMMENT_END -> */
        |   |   `--LITERAL_PRIVATE -> private
        |   |--TYPE -> TYPE
        |   |   `--LITERAL_VOID -> void
        |   |--IDENT -> boo
        |   |--LPAREN -> (
        |   |--PARAMETERS -> PARAMETERS
        |   |--RPAREN -> )
        |   `--SEMI -> ;
        `--RCURLY -> }
```

Command for generating AST: ``` java -jar checkstyle-10.14.2-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g" ```
sed removes the [row:column] numbers for documentation

Old Format:
Old Tree Format

New Format:
New Tree Format

### CODE REVIEW

**Review by MANISH-K-07 — COMMENTED** [review]
Everything lgtm ;)

**Comment by Prathamesh-007** [comment]
Thanks! Are you a maintainer?

**Comment by Prathamesh-007** [comment]
@romani Sir I am getting this error. Can you please help me out?
<br>
image

**Review by MANISH-K-07 — COMMENTED** [review]
You are using master branch to push all your changes and as a result, fixes for two separate issues got combined in this single PR. 
Please see https://checkstyle.org/beginning_development.html to find the concept of git branching

PS: The error is also because of the 2 commits here.

**Comment by Prathamesh-007** [comment]
Ohh ok got it. I will close this PR and create a new one's on different branches. Thanks for pointing out the mistake

**Comment by MANISH-K-07** [comment]
Please don't close and open multiple PRs....
The latest commit in this PR can be dropped via git actions and force pushed.

**Pull request closed without merging**
