### PR TITLE
PMD violations: UncommentedEmptyMethod Fixed #995

### LINKED ISSUE #995: PMD violations: UncommentedEmptyMethod
Resolve violations that do make sense (please do not fanatically follow PMD recommendations):

[INFO] --- maven-pmd-plugin:3.4:check (default-cli) @ checkstyle ---
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.DefaultLogger:148 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.DefaultLogger:154 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:57 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:63 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:69 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:88 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AutomaticBean:233 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AutomaticBean:247 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:129 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:136 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:145 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:154 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:162 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:170 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.SeverityLevelCounter:75 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.SeverityLevelCounter:81 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.SeverityLevelCounter:87 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.AbstractTypeAwareCheck:195 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.coding.IllegalTokenTextCheck:78 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck:231 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:99 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:108 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:117 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:126 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:183 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.metrics.AbstractComplexityCheck:70 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.metrics.AbstractComplexityCheck:80 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.AbstractCellEditor:114 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.AbstractTreeTableModel:103 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.AbstractTreeTableModel:264 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.FileDrop$FileDropTargetListener:332 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.ParseTreeModel:114 Rule:UncommentedEmptyMethod Priority:3 Document empty method.

### PR DESCRIPTION
**Pull request by Bhavik3**

### CODE REVIEW

**Comment by romani** [comment]
for cases with API , AbstractJavdoc please put a comment:
"no code by default, that method is not mandatory to implement in children"

instead of pasting obvious-useless comment, try to put a comment that describe a reason of empty method.

**Comment by Bhavik3** [comment]
@romani 
Done
I have put comment according to my understanding of that method. May be, I don't understand some of methods' working. have a look and tell me if any comment is not appropriate.

**Comment by romani** [comment]
1) please review my comment https://github.com/checkstyle/checkstyle/issues/997#issuecomment-113864869 , these issues are related, #977 need to be done first to reduce amount of empty methods for this issue.

2) 
> this method is not mandatory to implement in children

Sorry that is my bad comment, the is non clear term "children" ... please replace it by 
"no code by default, should be overridden only by demand at subclasses"

3)
> coding/IllegalTokenTextCheck.java

just remove that method

4)
> gui/AbstractCellEditor.java

make it "No code"

5)
> gui/AbstractTreeTableModel.java
gui/ParseTreeModel.java
gui/FileDrop.java


make it "No code, tree is read-only"

**Comment by Bhavik3** [comment]
@romani 
1)
I think that is typo....
997 or 977?

**Comment by romani** [comment]
@Bhavik3 ,
comment above was updated

**Comment by Bhavik3** [comment]
1) DONE
2) Comment changed
3) Removed
4) 5) comment updated

**Comment by romani** [comment]
1) 
> public void cancelCellEditing() {

tree is read-only .

**Comment by Bhavik3** [comment]
1) Done

**Pull request merged**
