### PR TITLE
Issue #13213: Remove "//ok" from input files  

### PR DESCRIPTION
**Pull request by Pakhi-7831**
Removed "//ok" from InputJavadocMethod_01.java, InputJavadocMethod_02.java, InputJavadocMethod_03.java and unwanted okcommitsuppresions from checkstyle-input-suppressions.xml

MINGW64__c_Users_pakhi_AppData_Roaming_SPB_Data_my_patch 06-03-2024 01_11_03 PM

### CODE REVIEW

**Review by MANISH-K-07 — COMMENTED** [review]
@Pakhi-7831 , 
`15.018s` ?? What command did you use to build?

Regarding the CI failure, please fix commit message to make CI green

**Comment by Pakhi-7831** [comment]
Used the mvn clean verify command for the build

**Comment by Pakhi-7831** [comment]
It is giving the "Line should not be longer than 100 symbols [lineLength]" error on build now and I am unable to figure the reason or  way to rectify it. Can you please provide some guidance so that i may correct it

**Review by MANISH-K-07 — COMMENTED** [review]
> It is giving the "Line should not be longer than 100 symbols [lineLength]" error on build now and I am unable to figure the reason or way to rectify it. Can you please provide some guidance so that i may correct it

I only see improper commit error : https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=20302&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=1327

I don't see where there is a linelength violation for the changes you have made
Could you provide the error log here?
You can try, the stacktrace shows you the filename and the line number of the violation, you can modify accordingly

**Comment by Pakhi-7831** [comment]
unable to understand how to fix the error shown on https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=20302&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=1327 
the current commit messages that I can see don't have "*" at the end of the message

**Review by MANISH-K-07 — COMMENTED** [review]
> the current commit messages that I can see don't have "*" at the end of the message

Omg how did I miss this !!
You must have made a mistake during rebase.. this commit msg is a combination of many previous merged commits and hence the error. Please go through agsin on how to rebase and squash, there are many resources online like google

**Review by Aagam1090 — APPROVED** [review]

**Comment by romani** [comment]
@Pakhi-7831, please fix CI failure.

**Comment by romani** [comment]
merged in other PR

**Pull request closed without merging**
