### PR TITLE
Issue #11719: Activate all group for pitest-coding-require-this-check

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
#11719
Activating `ALL` group for `pitest-coding-require-this-check`

Every mutator has been activated except `INLINE_CONSTS`

- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-coding-require-this-check/index.html

### CODE REVIEW

**Comment by nick-mancuso** [comment]
@Vyom-Yadav @baratali @pbludov should we consider splitting this profile into two profiles, keeping old one and making new one for ALL? We could also consider this for indentation check.

**Comment by Vyom-Yadav** [comment]
> @Vyom-Yadav @baratali @pbludov should we consider splitting this profile into two profiles, keeping old one and making new one for ALL? We could also consider this for indentation check.

Let's do it and see the execution time.

**Comment by nick-mancuso** [comment]
> > @Vyom-Yadav @baratali @pbludov should we consider splitting this profile into two profiles, keeping old one and making new one for ALL? We could also consider this for indentation check.
> 
> Let's do it and see the execution time.

@Vyom-Yadav ping

**Review by nick-mancuso — APPROVED** [review]
We will come back to time duration of execution in https://github.com/checkstyle/checkstyle/issues/11872, let's merge this.

**Pull request merged**
