### PR TITLE
New Check: Empty Catch Block Check, issue #571

### PR DESCRIPTION
**Pull request by alexkravin**
According to #571 

New Check was added, EmptyCatchBlockCheck is fully covered by UTs, EmptyBlockCheck was updated: removed references to checking catch blocks, updated UTs.

Updated docs.

What exactly have I do to update Coverage page (http://checkstyle.sourceforge.net/google_style.html) ?
Shouldn't it be updated automatically?

https://github.com/checkstyle/google-style-config-test will be updated asap

### CODE REVIEW

**Comment by alexkravin** [comment]
There're some problems in updating https://github.com/checkstyle/google-style-config-test 

1) It has to be possible to normally build checkstyle project.

2) If I am adding new Check to google_checks.xml (in google-style-config-test) UT says there's no such module anyway and changes of google_checks are not saved, furthermore - it's untrackable by git by default.

**Comment by romani** [comment]
Update of html page that describe coverage of googles rules is simple xdoc.

Test project use previous version of checkstyle , you need to update pom.xml and ensure new binary to be in your local maven repo.

**Comment by mkordas** [comment]
I would add example to docs when both `commentFormat` and `exceptionVariableName` are configured. Now I'm not sure how the check would behave. If I would configure both, and only  `exceptionVariableName` is met, but I don't have any comment, will it report violation or not?

**Comment by alexkravin** [comment]
such an example is in UTs, in your case it won't put any violation

**Comment by mkordas** [comment]
I know it is in UTs, however I started with reading docs and it was not clear for me at all. So my proposition is to extend docs.

**Comment by alexkravin** [comment]
@mkordas Ok, I'll do it, thanks for proposition

**Comment by alexkravin** [comment]
Update google-style-test:
https://github.com/checkstyle/google-style-config-test/pull/3

**Comment by alexkravin** [comment]
Updated google_style coverage page

**Comment by romani** [comment]
Please recheck build, travis is failed.

**Comment by alexkravin** [comment]
There was one odd whitespace, now everything is ok

**Comment by romani** [comment]
> 
- <p> Checks for empty blocks. </p>
+ <p> Checks for empty blocks, except for catch blocks. </p>

plase remove "except ...." from there, as user could do that, and Check will do work properly. New Check is required only for less stict validation.

**Comment by romani** [comment]
https://github.com/alexkravin/checkstyle/blob/509775c43d311fd0819a75bead4a5f55e67a046e/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java

1)
> The policy to verify is specified according to Check's

"There are two options to make validation less strict"

2) 
> expected|ignore

please make default as "^$", to match to nothing

3) 
> commentFormat - the format of single-line comment ....

from style guideline "....the reason this is justified is explained in a comment." So we have to support single line and block-comment. But we will match only first single line or block comment to regexp, for block comment we just do string concatenation of what we have in AST tree for content.

4)
> .\*

please make default as "^$", we should be strict by default. In Google style you will use proper values.

4) 
>   Examples:
 
Before example please explain how options are applied , by OR (any match) or AND (all should match) .

5) 
> 
private List<DetailAST> emptyCatchBlocks = new ArrayList<>();
private List<DetailAST> singleLineCommentsInEmptyCatchBlocks = new ArrayList<>();

I just do not see a reason to make this Check non stateless. Please subscribe to CATCH only and do search for first comment manually.
I might be wrong but it will simplify logic a lot.

6)
>  private String exceptionVariableName = "expected|ignore";
private String commentFormat = ".*"; 

why not a final ? as it default.

7) 
> throw new IllegalArgumentException(ast.toString());

Where is a message ? please reproduce that exception and see how informative error will be.

**Comment by alexkravin** [comment]
1) Updated

2) Done

3) Considering single-line comments and first line of multi-line comment.

4) Added

5) Yes, logic was simplified, rewrote

6) Because these fields are used in setters

7) Got rid of switch() at all

8) Generated report:

http://alexkravin.github.io/EmptyCatch/guava/checkstyle.html

But it's weird, as you can see lines are repeating, in many cases report specifies line number which is more than file's length, I checked files with strange violations with my Check and received no false-positives, perhaps something was broken whilst 6.3 release took place.

**Comment by romani** [comment]
Please test one file guava in terminal by cli to prove that lines shift is problem of maven plugin.

**Comment by alexkravin** [comment]
I can't figure out how to build executable file (checkstyle-xxx-all.jar) after build changes.

**Comment by romani** [comment]
mvn clean install -Passembly

**Comment by alexkravin** [comment]
Config:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <property name="charset" value="UTF-8"/>
  <module name="TreeWalker">
    <module name="EmptyCatchBlock"/>
  </module>
</module>
```

Tested on 2 files, results:
```
$ java -jar checkstyle-6.4-SNAPSHOT-all.jar -c checkstyle.xml Finalizer.java 
Starting audit...
Audit done.

$ java -jar checkstyle-6.4-SNAPSHOT-all.jar -c checkstyle.xml Cut.java 
Starting audit...
/home/asus/Downloads/checktest/Cut.java:96: Empty catch block.
Audit done.
```

Check puts violations at correct places.

But in report there's some mess in lines, seems to be all lines with violations from all files are squashed, e.g.:
Finalizer.java:
http://alexkravin.github.io/EmptyCatch/guava/checkstyle.html#com.google.common.base.internal.Finalizer.java

Cut.java:
http://alexkravin.github.io/EmptyCatch/guava/checkstyle.html#com.google.common.collect.Cut.java

**Comment by romani** [comment]
send me pleae link to project(sources) by which you generate report.

**Comment by romani** [comment]
1)
> commentFormat - the format of single-line comment format inside empty catch

you should check first comment not matter it is single line or multi-line . In multiline you grab whole comment content , but not only first line.

2) I need to see more tests with few comments in CATCH to be sure that only first is considered.

3) 
>```
private final Map<DetailAST, String> emptyCatchBlocksToCommentsMap = new HashMap<>();
```

check should not have any field that is not a option. STATELESS !!!

**Comment by alexkravin** [comment]
1) Updated docs.

2) Extended UT input (at the end of the input there're such examples)

3) Moved it to method.

About report, there was a problem with field - it wasn't cleared after file was processed, so moving it to method solved the problem, guava report:

http://alexkravin.github.io/EmptyCatch/guava/checkstyle.html

**Comment by romani** [comment]
build restarted.

1)
> 
```if (!"".equals(lines[i])) {```

http://docs.oracle.com/javase/7/docs/api/java/lang/String.html#isEmpty%28%29

2) remove emptyCatchBlocksToCommentsMap

**Comment by alexkravin** [comment]
1) Updated

2) Removed

**Comment by romani** [comment]
1)
> } catch (RuntimeException myException) {

 please make example in Javadoc/xdoc , for "ignore|expected", to make example more close to live usage.

2) 
> + final DetailAST singleLineComment = slistToken.findFirstToken(TokenTypes.
+ SINGLE_LINE_COMMENT);
+ final DetailAST blockComment = slistToken.findFirstToken(TokenTypes.BLOCK_COMMENT_BEGIN);
+ String commentContent = "";
+ if (singleLineComment != null) {

that cod mean that you put a priority to single line comment even two of them are present in block and single line is the last line in that block.
Please fix and provide UT to prove that it works fine on any combination of comments
please send me links to Inputs lines to prove that you covered that.

3) 
> + stmtCounter++;
+ }
+ catchBlockStmt = catchBlockStmt.getNextSibling();
+ }
+ if (stmtCounter == 0) {

Why for calculation of empty block or not empty, you count all items in block ? can you optimize that method ?

4)
> EmptyBlockCheckTest.java

please keep That Test unchanged, it is absolutely valid. Empty catch block could be checked by that Check. You create absolutely different check.
I am ok with changes at EmptyBlockCheck.java, as validation of CATCH should not be by default as it have a lot of false positives, and we should not show that, but we let user to do that on his resposibility

**Comment by alexkravin** [comment]
1) Updated

2) Fixed, 

https://github.com/checkstyle/checkstyle/blob/5ef77449b592accfcb798eba3a65b864355fc5c4/src/test/resources/com/puppycrawl/tools/checkstyle/InputEmptyCatchBlockCheck.java#L187

From that line and till the end of the file there are examples of comment combinations.

3) As I subscribed on comment nodes too I can't make simple checking for empty block as I would do if there would be no comment nodes in tree, so, what's wrong?

4) Removed only default checking, UTs where <b>catch</b> is set as an option (tokens) are unchanged, removed from getDefaultTokens() added to getAcceptableTokens()

**Comment by romani** [comment]
I still do not see changes for first comment node search that I requested for method https://github.com/alexkravin/checkstyle/commit/bb18419de0ba5f2d7de06cb34b649b92ca8e9990#diff-551a94529152cc5bc01b74dee4b104edR223

**Comment by alexkravin** [comment]
2)

final DetailAST singleLineComment = slistToken.findFirstToken(TokenTypes.
SINGLE_LINE_COMMENT);
final DetailAST blockComment = slistToken.findFirstToken(TokenTypes.BLOCK_COMMENT_BEGIN);
String commentContent = "";
if (singleLineComment != null) {
that cod mean that you put a priority to single line comment even two of them are present in block and single line is the last line in that block.
Please fix and provide UT to prove that it works fine on any combination of comments
please send me links to Inputs lines to prove that you covered that.




I have already fixed this and provided examples in UT input

**Comment by romani** [comment]
I still see 

>
```
+ final DetailAST singleLineComment = slistToken.findFirstToken(TokenTypes.
+ SINGLE_LINE_COMMENT);
+ final DetailAST blockComment = slistToken.findFirstToken(TokenTypes.BLOCK_COMMENT_BEGIN);
```

we discussed with you that there is not reason to do search for both of them, you need to manually get first element in block.

**Comment by alexkravin** [comment]
Updated
https://github.com/alexkravin/checkstyle/commit/370088b796b7040afb808957c6532dac71296c57#diff-551a94529152cc5bc01b74dee4b104edR223

**Comment by romani** [comment]
0) please regenerate HTML report, on latest config.

1) I did not found changes in google_checks.xml for new Check, as I expect it to work with non-default configuration.

2) please add to google_checks.xml configuration additional variable name - "ignored". I pretty sure they mean that (you can see that from html report). Please add few input cases at google-style-config-test for that.

**Comment by alexkravin** [comment]
0) Done

It's the same

http://alexkravin.github.io/EmptyCatch/guava/checkstyle.html

1) Updated config (exceptionVariableName=expected)

2) "ignore" was not used in google_checks.xml, only in UTs, updated google-style-test with adding UT and input for exception variable name

https://github.com/checkstyle/google-style-config-test/pull/3

3) You didn't notice it because I didn't add guava-testlib to report, I've only added main project, Check puts violation on case you specified above.

**Comment by romani** [comment]
1) please generate report on all sources that we used at http://checkstyle.sourceforge.net/reports/google-style/guava , we need to compare and do final check that nothing else is affected and nothing is missed.

2) please add changes to google_checks.xml to the end of the file, as right now you damaged most links to config at http://checkstyle.sourceforge.net/google_style.html

**Comment by alexkravin** [comment]
1) here're others:
http://alexkravin.github.io/EmptyCatch/guava/checkstyle-gwt.html
http://alexkravin.github.io/EmptyCatch/guava/test/checkstyle.html

lots of cases in second report

2) Sure, I just thought it will looks good located next to EmptyBlock, done

**Pull request merged**
