### PR TITLE
Fixed PMD violation 'ConfusingTernary' (partial fix), issue #974

### PR DESCRIPTION
**Pull request by MEZk**
@romani 
There are 6 PMD's violations after fix:

```
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.ConfigurationLoader:361 Rule:ConfusingTernary Priority:3 Avoid if (x != y) ..; else ..;.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.DetailAST:115 Rule:ConfusingTernary Priority:3 Avoid if (x != y) ..; else ..;.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationLocationCheck:229 Rule:ConfusingTernary Priority:3 Avoid if (x != y) ..; else ..;.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck:196 Rule:ConfusingTernary Priority:3 Avoid if (x != y) ..; else ..;.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:468 Rule:ConfusingTernary Priority:3 Avoid if (x != y) ..; else ..;.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.TagParser:104 Rule:ConfusingTernary Priority:3 Avoid if (x != y) ..; else ..;.
```
Those  classes require more detailed analysis of boolean expressions.

### CODE REVIEW

**Comment by mkordas** [comment]
@MEZk @romani - for me this rule is extremly controversial. Many coding styles reccomend that first branch of if should be usual, postivie case. Variable beign `null` is usually less normal and less often...

**Comment by MEZk** [comment]
@mkordas 
Hm, after some research I thnik you are defenetly right. From my point of view, that rule might be usefull to detect:
````java
if (!isSomeCondition()) {
}
else {
}
````

but not for
```java
if (something != null) {
}
else {
}
````

And also FYI:
http://sourceforge.net/p/pmd/bugs/228/
http://sourceforge.net/p/pmd/bugs/1161/

May be we can disable this rule at all or try to suppress null cases with violationSuppressXPath . What do you think?

**Comment by romani** [comment]
we need to suppress that rule , we already have Check for that cases in sevntu, as far as I remember it supports checking for "null" and even more options to make it less fanatic

**Comment by MEZk** [comment]
@romani 
The rule has been already suppressed [here](https://github.com/checkstyle/checkstyle/blob/master/config/pmd.xml#L134). Lets switch to similar checkstyle's check in nearest future.

**Pull request closed without merging**
