### PR TITLE
Issue #9882: updated TrailingCommentCheckTest to use unique input fil…

### PR DESCRIPTION
**Pull request by AmrBumadian**
Closes: #9882 
TrailingCommentCheckTest.testFormat() test was failing because of unexpected trailing comment, the Config comment, So I added it to the expected list.
@timurt @romani

### CODE REVIEW

**Review by timurt — APPROVED** [review]
Please rebase on latest master to trigger CI checks, if it pass CI, i will merge

**Comment by AmrBumadian** [comment]
@timurt Done

**Comment by romani** [comment]
Please  fix https://app.circleci.com/pipelines/github/checkstyle/checkstyle/6533/workflows/5c566ffd-d0ac-4d26-9131-ce50eec4de34/jobs/84990/parallel-runs/2/steps/2-102

You can run it on your local
`./.ci/pitest.sh pitest-misc`

**Comment by pbludov** [comment]
GitHub, rebase

**Comment by rnveach** [comment]
I am closing this as the issue is done.

**Pull request closed without merging**
