### PR TITLE
Issue #7977: Resolve Pitest Issues - JavadocMethodCheck (5)

### PR DESCRIPTION
**Pull request by HuGanghui**
The details are as follows that is the same in #7977

**Pitest report**

Link: https://huganghui.github.io/7977-JavadocMethodCheck-5/before-pitest-reports/com.puppycrawl.tools.checkstyle.checks.javadoc/JavadocMethodCheck.java.html#grouporg.pitest.mutationtest.report.html.SourceFile@1353848a_1077

Surviving mutations:
on line 1077: negated conditional → SURVIVED

**Hardcoded mutation**

mutation cs branch: https://github.com/HuGanghui/checkstyle/commit/f5642b33b1ecaa93af1f8e62403233d7b615149f
comment:
Looking at the pitest report, we can see that the surviving mutation is negated conditional → SURVIVED, so I change != -> == .

**Regression diff report**

https://huganghui.github.io//7977-JavadocMethodCheck-5/hardcoded-reports/diff/
there is no diff found.

**Code Logic Analysis**

Although there is no diff found in Regression diff report, I find that containing class ClassAlias and its relevant code is redundant, which also is mentioned in issue #7980 by @rnveach. So I do a diff report https://huganghui.github.io//7977-JavadocMethodCheck-5/remove-redundant-reports/diff/ on a branch(https://github.com/HuGanghui/checkstyle/commit/20ad567272d6ff3ac0d410fc09be4d049c7e2ab4) that remove class ClassAlias and its relevant code and result is no diff found. I also do Pitest after removing redundant code report show that it doesn't introduce new surviving mutations and solve all JavadocMethodCheck Pitest mutations including #7923, #7924, #7925, this issue, #7979,  #7980 and Based on this result, I think maybe we can remove redundant code～

### CODE REVIEW

**Comment by HuGanghui** [comment]
image

I do not know why this failure happed, please give me some help.

**Comment by gaurabdg** [comment]
@HuGanghui With all due respect, I am working on it and a discussion is ongoing. I already sent a PR regarding these issues long back.

**Comment by HuGanghui** [comment]
@gaurabdg yes, bro, I know you are working on #7980 for a long time and also know content discussion on it, i just working on #7977 and i think that removing redundant code maybe is a good solution, so provide this to Checkstyle.  I think Pitest Issues of JavadocMethodCheck itself’s solution have some duplication that in order to resolving one may influence others. 
As for the PR, I think @rnveach will properly resolve these PRs which may have some duplication~ 😊

**Comment by rnveach** [comment]
Sorry @HuGanghui . We merged the other PR as he was being reviewed first and still discussing the scope of these changes.

**Pull request closed without merging**
