### PR TITLE
minor: Optimize method distance in checkstyle.api.FullIdent

### PR DESCRIPTION
**Pull request by wilcoln**
Before Optimization:
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/before.FullIdent.java.html

After Optimization:
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/after.FullIdent.java.html

Optimization was made manually and with respect to the currently hardcoded criteria defined in the method-distance repository.

### CODE REVIEW

**Comment by romani** [comment]
@rdiachenko , please do review first, to make me sure we all understand idea of distance in same way.

**Comment by rdiachenko** [comment]
@wilcoln , could you try to put getters after a constructor and put those static methods after. In this case we will have a group of getters first, which is common. And static methods will be closer to the last append methods which are used from static methods only.

**Comment by wilcoln** [comment]
> @wilcoln , could you try to put getters after a constructor and put those static methods after.

Done, Report has been updated

**Comment by wilcoln** [comment]
@rdiachenko the new ordering is in conflict with checkstyle's ``

**Comment by romani** [comment]
After new Check is created we might end make decision to disable CustomDeclarationOrder but till that time have to follow CustomDeclarationOrder

**Comment by rdiachenko** [comment]
@wilcoln Have you tried to put both `append` methods just after the last static method which calls them? Currently, those `append` methods are separated by a group of getters. Was there any violation, what was the penalty?

**Comment by wilcoln** [comment]
@rdiachenko, I haven't try that but I doubt it will cause any change since those append functions arent used by any method in the file.

The current penalty function value is 2, which, when you look at the DSM, seems to be the optimal value as it solely comes from the already well ordered static methods group.

If you still want me to apply the changes you requested, please let me know.

**Comment by wilcoln** [comment]
I've applied the requested changes, there is no violation,  the penalty function value remains the same (= 2) and this is because the dependency isn't capture during analysis, since the methods are referenced from an instance and not directly by name. `full.append("")` instead of `append("")`.
Should we open an issue about this?

**Comment by rdiachenko** [comment]
> I've applied the requested changes, there is no violation, the penalty function value remains the same (= 2) and this is because the dependency isn't capture during analysis, since the methods are referenced from an instance and not directly by name. `full.append("")` instead of `append("")`.
> Should we open an issue about this?

@wilcoln I see, interesting case. Unfortunately, we can do nothing here. Looks like that was done intentionally to not take into account such cases. That might be because of the restriction of AST. Having such a line `full.append("")` and AST of the full class you can't say for sure whether `append` method belongs to the current class or not.

Could you move those `append` methods back and leave all getters just after static methods as before, and looks like we are done here.

**Comment by wilcoln** [comment]
Done :)

**Comment by romani** [comment]
@wilcoln , please rebase all your PRs , nondex is fixed in master.

**Pull request merged**
