### PR TITLE
Issue #9806: Javadoc support for no summary tag

### LINKED ISSUE #9806: Javadoc summary not processed inside html tags
I have read check documentation: https://checkstyle.org/config_javadoc.html#SummaryJavadoc
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
$ javac Test1.java 

$ cat Test1.java 
package com.puppycrawl.tools.checkstyle.checks.javadoc.summaryjavadoc;

/**
 * Config: default.
 */
public class Test1 {

    /**
     * <p><b>Summary Normal Javadoc.</b></p>
     */
    public void foo1() {} // ok
}

$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="SummaryJavadocCheck"/>
  </module>
</module>

$ javadoc Test1.java 
Loading source file Test1.java...
Constructing Javadoc information...
Standard Doclet version 14.0.2
Building tree for all the packages and classes...
Generating ./com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/Test1.html...
Generating ./com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/package-summary.html...
Generating ./com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/package-tree.html...
Generating ./constant-values.html...
Building index for all the packages and classes...
Generating ./overview-tree.html...
Generating ./deprecated-list.html...
Generating ./index-all.html...
Building index for all classes...
Generating ./allclasses-index.html...
Generating ./allpackages-index.html...
Generating ./system-properties.html...
Generating ./index.html...
Generating ./help-doc.html...

$ java -jar checkstyle-8.41.1-all.jar -c config.xml Test1.java 
Starting audit...
[ERROR] /home/akmo/GitHub/Test/InlineJavadoc/Test1.java:8: Summary javadoc is missing. [SummaryJavadoc]
Audit done.
Checkstyle ends with 1 errors.

```
---

**Describe what you expect in detail.**

The summary should not raise any violation

```
$ java -jar checkstyle-8.41.1-all.jar -c config.xml Test1.java
Starting audit...
Audit done.
```
Screenshot from 2021-04-03 00-41-19

---

### PR DESCRIPTION
**Pull request by kthirano**
Resolves #9806 
Diff Regression config: https://gist.githubusercontent.com/kthirano/c95d34c00557485b5e83d10e2d221f1a/raw/bef522aa4276af127c39803ff1d96c94386907ab/config.xml

### CODE REVIEW

**Comment by angelsjiang** [comment]
@AkMo3 
Hi, could you please check if this change takes care of the issue?
Thanks!

**Comment by AkMo3** [comment]
The implementation looks good! Please generate the report. You can visit [checkstyle-tester](https://github.com/checkstyle/contribution/tree/master/checkstyle-tester) It will be better to connect with @romani or any other maintainer until the end of next week as I am currently inactive till 19th Jun.

**Comment by pbludov** [comment]
> https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/c773dec_2021203631/reports/diff/index.html

@kthirano, the report is not good. [Here](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/c773dec_2021203631/reports/diff/infinispan/index.html) the violations were removed, but they are valid.

For https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/c773dec_2021203631/reports/diff/infinispan/index.html#A1 the generated Javadoc is

> Defines how to configure a new named cache produced by this FactoryBean: NONE: Configuration starts with a new Configuration instance.

This is definitely not what the author want. There is a missing period. If a Javadoc starts with `<p>`, then the period should be inside this paragraph. I.e.
```
<p>First sentence.</p>
```
is good, but
```
<p>First sentence</p>
<p>Second sentence.</p>
```
is bad.

Note that
```
<b>Bold</b> normal.
```
is also valid.

**Comment by nmancus1** [comment]
@kthirano please let us know if you plan to continue work on this PR, otherwise we will close it in March 2022.

**Comment by nick-mancuso** [comment]
We have lost contact with author, anyone is welcome to reuse code and continuing working on this issue.

**Pull request closed without merging**
