### PR TITLE
infra: remove --fail-with-body from pr-description.sh

### PR DESCRIPTION
**Pull request by nrmancuso**
Noticed at https://github.com/checkstyle/checkstyle/actions/runs/3531403281/jobs/5924533074, check of PR description was silently failing.

```
0s
Run ./.ci/pr-description.sh
curl: option --fail-with-body: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
Commit messages from github: ...
Issue number: 
PR validation succeeded.
```

### CODE REVIEW

**Comment by rnveach** [comment]
> was silently failing

What should we be doing to avoid these silent fails?

**Comment by nrmancuso** [comment]
> > was silently failing
> 
> What should we be doing to avoid these silent fails?

Do less piping and always check exit value of curl commands maybe?

**Comment by rnveach** [comment]
> Do less piping and always check exit value of curl commands maybe?

I am not a bash programmer so I can't really provide valuable insight. :)

Is it piping that is hiding the failure or is it the `${}`? Can we atleast confirm this?

**Comment by romani** [comment]
this option is ~1 year old only in curl - https://curl.se/mail/lib-2021-03/0056.html
action is using latest-ubuntu, so sad.

**Review by romani — APPROVED** [review]
commit is updated.

ok to merge as CI pass

**Comment by rnveach** [comment]
> we can not use bash feature fail on failure in middle of pipe ... because ... in this script

So it is the pipe that causing the hidden failure?
Can we add it to other scripts so they don't have hidden issues?

> we use grep -E "$REGEXP" | cat in this script, so we expect failed commands

Is the failure because the regexp doesn't match like if they don't have issue number and thats what we are checking?

**Comment by romani** [comment]
Pipe is not causing it.
Without bash flag that I mentioned above, failure in the middle swallowed.

**Comment by rnveach** [comment]
ok, it makes sense now. Maybe we should see if we can silo off commands that can fail and those that shouldn't from the grep.

@romani What about this? It has no grep.
````
COMMITS=$(curl -s -H "Authorization: token $READ_ONLY_TOKEN" "$LINK_COMMITS" \
             | jq '.[0] | .commit.message')
````

**Review by rnveach — APPROVED** [review]

**Comment by romani** [comment]
If we refactor code to avoid greps or narrow them to specific segments, I am ok to enable  failures in pipelines.
I already did somewhere enablement of such  mode in code and disablement after.

**Pull request merged**
