### PR TITLE
Issue #9593: updates example of AST for TokenTypes.UNARY_MINUS

### PR DESCRIPTION
**Pull request by gurleennsidhuu**
Closes: #9593
BEFORE:
be
AFTER:
af

### CODE REVIEW

**Comment by SGanguly1999** [comment]
Heading is fine @gurleennsidhuu please revert back to what it was before

image

Talking about this one

**Comment by gurleennsidhuu** [comment]
> Also update your branch to the latest changes **checkstyle .checkstyle(Job-pr age)** is failing

Can you please help me with that? How do I do this?

**Comment by SGanguly1999** [comment]
You can follow this one:--1> https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository.
                                         2>https://stackoverflow.com/questions/3876977/update-git-branches-from-master/28505516

**Review by romani — CHANGES_REQUESTED** [review]
javadoc should use CLI output with minor corrections as defined in issue.
Please take a look in example PR.
rebase PR to latest code to pass CI

**Comment by romani** [comment]
If no response in 5 days, I will close PR

**Pull request closed without merging**
