### PR TITLE
Issue #4090: Split and Organize Checkstyle inputs by Test for Paramet…

### PR DESCRIPTION
**Pull request by GabrielBercaru**
Issue: #4090

### CODE REVIEW

**Comment by rnveach** [comment]
@GabrielBercaru Please read over https://github.com/checkstyle/checkstyle/wiki/PR-rules .
You don't need to create a new PR to make changes.

**Comment by GabrielBercaru** [comment]
I have forked a new copy of Checkstyle but TeamCity still fails. Logging in as a guest showed that there are errors and warnings, what is causing them?

**Comment by rnveach** [comment]
@GabrielBercaru TC failure can be ignored. It is broken on their side.

**Comment by MEZk** [comment]
@romani 
Can we merge this PR?

**Pull request merged**
