### PR TITLE
Issue #13321: Kill mutation for OrderedPropertiesCheck-1

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for OrderedPropertiesCheck-1

---------

# Check :- 
https://checkstyle.org/checks/misc/orderedproperties.html#OrderedProperties

-----------

# Mutation :- 
https://github.com/checkstyle/checkstyle/blob/20a52f70548476a4ca3bb0f56e4d8fcd9cd775b7/config/pitest-suppressions/pitest-misc-suppressions.xml#L57-L82

----------

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/c3213434af8523d918594b88ce5554f7/raw/3565cfcd975e228af515bb34ce22c83afce0a7c7/opc.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/360a95ed7bb60d7a0956e531199d484c4d6f6617/test-projects.properties
Report label: Regression-2

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
Github, generate report

**Review by romani — APPROVED** [review]
Ok to merge.
Weird code but we definitely not use Properties type fully.

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

**Review by rdiachenko — APPROVED** [review]
lgtm

**Pull request merged**
