### PR TITLE
Issue#2633 Fix GenericWhitespace to not trigger error when it ends line

### PR DESCRIPTION
**Pull request by liscju**

### CODE REVIEW

**Comment by romani** [comment]
1) This check is in Google style - http://checkstyle.sourceforge.net/google_style.html#a4.6.2
so please update IT tests https://github.com/checkstyle/checkstyle/blob/master/src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/GenericWhitespaceTest.java too, copy paste from UTs is ok.

2) please resolve problem that is found by TC.

**Comment by liscju** [comment]
1) DONE
2) DONE, waiting for TC result

**Comment by romani** [comment]
>  "Exiting Check covers ..." - shouldn't be existing instead of exiting? I would send PR to site sources but i have no idea where are they.

yes, please fix typo, you are welcome with separate PR for this.

**Comment by romani** [comment]
1) Why you put "//Compilable with Java8" in input file ?
I do not see there java8 syntax , please remove this line.

**Comment by liscju** [comment]
@romani 
> 1) Why you put "//Compilable with Java8" in input file ?
>I do not see there java8 syntax , please remove this line.

DONE - removed as requested

**Comment by romani** [comment]
merged as FF, thanks a lot.

**Pull request closed without merging**
