### PR TITLE
Marked maxLineLength as '@Deprecated' at LeftCurlyCheck, issue #965.

### PR DESCRIPTION
**Pull request by MEZk**
See issue #965 for investigation notes.

### CODE REVIEW

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/issues/965#issuecomment-124849628

**Comment by romani** [comment]
@MEZk , lets finish that PR

**Comment by romani** [comment]
@MEZk , lets finish that PR , it hanging too long.

**Comment by MEZk** [comment]
Changes in UTs:

1) Added [line 93](https://github.com/MEZk/checkstyle/commit/e8e1a72649b65a7eb8c4c9b031af2e6301277038#diff-5e045b04dda6de74c388fdc1537e4520R93) at testDefault2 since left curly brace policy is EOL by default and at InputLeftCurlyMethod.java  [left curly](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/InputLeftCurlyMethod.java#L27) is on a new line.
2) Added [line 98](https://github.com/MEZk/checkstyle/commit/e8e1a72649b65a7eb8c4c9b031af2e6301277038#diff-5e045b04dda6de74c388fdc1537e4520R98) at testDefault2 since left curly brace policy is EOL by default and at InputLeftCurlyMethod.java [left curly](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/InputLeftCurlyMethod.java#L27) is on a new line.
3) Added [line 100](https://github.com/MEZk/checkstyle/commit/e8e1a72649b65a7eb8c4c9b031af2e6301277038#diff-5e045b04dda6de74c388fdc1537e4520R100) at testDefault2 since left curly brace policy is EOL by default and at InputLeftCurlyMethod.java [left curly](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/InputLeftCurlyMethod.java#L65) is on a new line.
4) Added [line 103](https://github.com/MEZk/checkstyle/commit/e8e1a72649b65a7eb8c4c9b031af2e6301277038#diff-5e045b04dda6de74c388fdc1537e4520R103) at testDefault2 since left curly brace policy is EOL by default and at InputLeftCurlyMethod.java [left curly](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/InputLeftCurlyMethod.java#L80) is on a new line.
5) Added [line 192](https://github.com/MEZk/checkstyle/commit/e8e1a72649b65a7eb8c4c9b031af2e6301277038#diff-5e045b04dda6de74c388fdc1537e4520R192) at testDefaultWithAnnotations since left curly brace policy is EOL by default and at InputLeftCurlyAnnotations.java [left curly](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/InputLeftCurlyAnnotations.java#L27) is on a new line.
6) Added [line 193](https://github.com/MEZk/checkstyle/commit/e8e1a72649b65a7eb8c4c9b031af2e6301277038#diff-5e045b04dda6de74c388fdc1537e4520R193) at testDefaultWithAnnotations since left curly brace policy is EOL by default and at InputLeftCurlyAnnotations.java [left curly](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/InputLeftCurlyAnnotations.java#L50) is on a new line.
7) Added [line 194](https://github.com/MEZk/checkstyle/commit/e8e1a72649b65a7eb8c4c9b031af2e6301277038#diff-5e045b04dda6de74c388fdc1537e4520R194) at testDefaultWithAnnotations since left curly brace policy is EOL by default and at InputLeftCurlyAnnotations.java [left curly](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/InputLeftCurlyAnnotations.java#L58) is on a new line.
8) Added [line 295](https://github.com/MEZk/checkstyle/commit/e8e1a72649b65a7eb8c4c9b031af2e6301277038#diff-5e045b04dda6de74c388fdc1537e4520R295) at testCoverageIncrease since left curly brace policy is NLOW by default and at InputScopeInnerInterfaces2.java [left curly](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/InputScopeInnerInterfaces2.java#L12) is on a new line and prefious statement is not a statement spanning multiple lines and EOL policy is uses while checking. See [right curly brace policy](statement spanning multiple lines).
9) Added [line 296](https://github.com/MEZk/checkstyle/commit/e8e1a72649b65a7eb8c4c9b031af2e6301277038#diff-5e045b04dda6de74c388fdc1537e4520R296) at testCoverageIncrease since left curly brace policy is NLOW by default and at InputScopeInnerInterfaces2.java [left curly](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/InputScopeInnerInterfaces2.java#L21) is on a new line and prefious statement is not a statement spanning multiple lines and EOL policy is uses while checking. See [right curly brace policy](statement spanning multiple lines).
10) Added [line 297](https://github.com/MEZk/checkstyle/commit/e8e1a72649b65a7eb8c4c9b031af2e6301277038#diff-5e045b04dda6de74c388fdc1537e4520R297) at testCoverageIncrease since left curly brace policy is NLOW by default and at InputScopeInnerInterfaces2.java [left curly](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/InputScopeInnerInterfaces2.java#L30) is on a new line and prefious statement is not a statement spanning multiple lines and EOL policy is uses while checking. See [right curly brace policy](statement spanning multiple lines).
11) Added [line 298](https://github.com/MEZk/checkstyle/commit/e8e1a72649b65a7eb8c4c9b031af2e6301277038#diff-5e045b04dda6de74c388fdc1537e4520R298) at testCoverageIncrease since left curly brace policy is NLOW by default and at InputScopeInnerInterfaces2.java [left curly](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/InputScopeInnerInterfaces2.java#L39) is on a new line and prefious statement is not a statement spanning multiple lines and EOL policy is uses while checking. See [right curly brace policy](statement spanning multiple lines).

**Comment by romani** [comment]
Please remove SuppressWarnings for PMD violations, suppression in standalone config file should br enough, production code should be clear from extra markers.

**Comment by MEZk** [comment]
>Please remove SuppressWarnings for PMD violations, suppression in standalone config file should br enough, production code should be clear from extra markers.

Done.

**Comment by romani** [comment]
changes are ok to merge, please provide reports to prove that no regression is introduced. 
I expect no changes between before-after reports.

**Comment by MEZk** [comment]
@romani 
I checked against guava with default configuration. There are 3 differences in checkstyle-tester reports before (99) and after (102).
[Reports](http://mezk.github.io)
**after:**

*'{' at column 1 should be on the previous line.*
[Line 32](http://mezk.github.io/guava_i965_after/xref/guava/guava-testlib/src/com/google/common/collect/testing/TestStringSetGenerator.html#L32), by default left curly brace policy is EOL, but left curly is on a new line.

*'{' at column 3 should be on the previous line.*
[Line 1178](http://mezk.github.io/guava_i965_after/xref/guava/guava-testlib/test/com/google/common/testing/NullPointerTesterTest.html#L1178), by default left curly brace policy is EOL, but left curly is on a new line.

*'{' at column 5 should be on the previous line.*
[Line 212](http://mezk.github.io/guava_i965_after/xref/guava/guava/src/com/google/common/collect/Constraints.html#L212), by default left curly brace policy is EOL, but left curly is on a new line.

So, as you can see, the differences, which were mentioned above, are similar to differences in UTs, which I described in my previous comment.

**Comment by romani** [comment]
please rebase, I am ready to merge.

**Comment by MEZk** [comment]
@romani
Done

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
