### PR TITLE
Coverage has been increased to 100% in UniquePropertiesCheck. Issue #1290

### PR DESCRIPTION
**Pull request by sabaka**
without changes in code

### CODE REVIEW

**Comment by sabaka** [comment]
Have no idea. It went fine on macos and linux. Please try to restart

**Comment by romani** [comment]
still a problem, please recheck other build parameters as jdk version and ....

**Comment by sabaka** [comment]
@romani should work now. Verify passed on java 7 and 8 locally.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
