### PR TITLE
Issue #7651: Update doc for NestedForDepth

### PR DESCRIPTION
**Pull request by Rainy0707**
Fixes Issue #7651 

WebsiteView_NestedFor

$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="NestedForDepth">
            <property name="max" value="3"/>
        </module>
    </module>
</module>

$ cat Test.java
public class Test {

    public void myTest() {
        for(int i=0; i<10; i++){
                for(int j=0; j<i; j++){
                        for(int k=0; k<j; k++){
                                for(int l=0; l<k; l++){
                                        for(int m=0; m<l; m++){
                                        }
                                }
                        }
                }
        }

        for(int i=0; i<10; i++){
                for(int j=0; j<i; j++){
                        for(int k=0; k<j; k++){
                                for(int l=0; l<k; l++){
                                }
                        }
                }
        }
    }

}

$ java -jar checkstyle-8.30-all.jar -c config.xml Test.java
Starting audit...
[ERROR] C:\Users\1\Desktop\New_folder\Test.java:8:41: Nested for depth is 4 (max allowed is 3). [NestedForDepth]
Audit done.
Checkstyle ends with 1 errors.

### CODE REVIEW

**Comment by rnveach** [comment]
@Rainy0707 Please read https://github.com/checkstyle/checkstyle/wiki/PR-rules and your first post in this PR.

**Comment by Rainy0707** [comment]
@rnveach I have made the changes in the comment body of the request.  How to run the checks again?

**Comment by rnveach** [comment]
@Rainy0707 Please look over item 2 and 3 in the PR rules. The CI is failing in other places the first post. Please run `mvn clean verify` locally and fix any failures reported.

**Comment by Rainy0707** [comment]
@rnveach I had not run the commands in cmd before generating the pull request. Can you guide me how can I revert back the commit and try again using the command line arguments.

PS: I tried running mvn clean verify and it was passing on the local machine.

**Comment by rnveach** [comment]
> Can you guide me how can I revert back the commit and try again using the command line arguments.

Delete the branch locally and recreate it. You can save your specific changes to another location temporarily and then bring them back when the branch is ready.

You do not need to do this to just use the commands. You can use them whenever you want to check your work but you will need to squash your commits as we expect only 1 commit in this PR.

> I tried running mvn clean verify and it was passing on the local machine.

Did the tests run? The CI is saying there a re test failures so there is some disconnect. I can tell just looking at your commit names the CI failures are correct as the commits must follow a specific pattern in naming convention.

**Comment by Rainy0707** [comment]
@rnveach I made the changes and squashed the commits into one. However, the commits are made in the branch 'my-new-check' and the pull request is comparing the master branch.
Also, while running mvn clean verify on local machine, I am getting below error:


[ERROR] Failures:
[ERROR]   JavadocPropertiesGeneratorTest.testHelp:234 Unexpected output log ==> expected: <Usage: java com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator [-hV]
       --destfile=<outputFile> <inputFile>
      <inputFile>   The input file.
      --destfile=<outputFile>
                    The output file.
  -h, --help        Show this help message and exit.
  -V, --version     Print version information and exit.
> but was: <Usage: java com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator [-hV]
       --destfile=<outputFile> <inputFile>
      <inputFile>   The input file.
      --destfile=<outputFile>
                    The output file.
  -h, --help        Show this help message and exit.
  -V, --version     Print version information and exit.

Please suggest the next step.

**Comment by rnveach** [comment]
> the commits are made in the branch 'my-new-check' and the pull request is comparing the master branch.

From what I am seeing on the server, the branch name is `master` in your own fork and not `my-new-check`. You may want to get more familar with git and its commands.

Regardless, the name of the branch doesn't matter. As described above, you would create a new branch off of checkstyle's master commit and not the fork's.

> while running mvn clean verify on local machine, I am getting below error:

You would need to push your branch to the server to see what the issue is. What is currently pushed to the server has no failure in that test.

**Comment by Rainy0707** [comment]
@rnveach I tried in the master branch and used the same naming convention as mentioned however CI test is again failing. Can you let me know the exact mistake that mioght be there.

**Comment by Rainy0707** [comment]
@rnveach all checks have passed now

**Comment by romani** [comment]
@Rainy0707 , please read  https://github.com/checkstyle/checkstyle/wiki/PR-rules
and attentively read issue description, especially `PLEASE READ`. 
Please follow rules.

**Comment by Rainy0707** [comment]
@romani please find below the website screenshot and the output of the commands:

Checkstyle_website_result

$ cat config.xml
<?xml version="1.0"?>
 <!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
 <module name="Checker">
   <module name="TreeWalker">
     <module name="NestedForDepth">
     <property name="max" value="3"/>
     </module>
   </module>
 </module>

$ cat Test.java
public class Test {

    public void myTest() {
        for(int i; i<10; i++){
                for(int j; j<i; j++){
                        for(int k; k<j; k++){
                                for(int l; l<k; l++){
                                        for(int m; m<l; m++){
                                        }
                                }
                        }
                }
        }

        for(int i=0; i<10; i++){
                for(int j; j<i; j++){
                        for(int k; k<j; k++){
                                for(int l; l<k; l++){
                                }
                        }
                }
        }
    }

}

$ java -jar checkstyle-8.30-all.jar -c config.xml Test.java
Starting audit...
[ERROR] C:\Users\1\Desktop\New_folder\Test.java:8:41: Nested for depth is 4 (max allowed is 3). [NestedForDepth]
Audit done.
Checkstyle ends with 1 errors

**Comment by Rainy0707** [comment]
@romani  Sorry for the inconvenience. It seems that the result for 'cat config.xml' couldn't be pasted properly in the earlier comment hence, pasting it again

$ cat config.xml
<?xml version="1.0"?>
 <!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
 <module name="Checker">
   <module name="TreeWalker">
     <module name="NestedForDepth">
     <property name="max" value="3"/>
   </module>
 </module>

**Comment by Rainy0707** [comment]
@romani the output for 'cat config.xml' is not showing in the final comment. I am pasting the output from command line but on updating the comment the output is not appearing.
Please refer the screenshot for the same

Capture

**Comment by romani** [comment]
Please move all ( screenshot and outputs ) to PR description. Please fix extra unnecessary indentation of code.

**Comment by Rainy0707** [comment]
@romani  I have made the requested changes. Please verify.

**Comment by romani** [comment]
@Rainy0707 , please rebase one more time, tight now there is conflict, merge is not possible.
Please keep in PR only your commit, THERE MUST BE 1 commit only !!!

please read https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history
if still problem, please drop out local branch, pull latest changes from us https://checkstyle.org/beginning_development.html#Starting_Development and make branch again from scratch.

**Comment by Rainy0707** [comment]
@romani please check if it is correct now

**Comment by romani** [comment]
There should be single commit in this PR. Please redo your branch from scratch.

**Comment by Rainy0707** [comment]
@romani I dropped the local clone and started the branch from scratch and rebased the commits however, I am not sure how to get only one commit in this PR. Do I need to open a new PR as any changes in the branch leads to a new commit as soon as I push changes.

Sorry for the inconvenience.

**Comment by romani** [comment]
please make a backup of your repo on local filesystem.
drop your fork, fork from us one more time, clone your fork to  your local, follow https://checkstyle.org/beginning_development.html (and apply all changed from you backup)

**Comment by Rainy0707** [comment]
@romani  I dropped my fork and created a new fork. However, now I am not able to commit on this pull request. The changes are only in my branch. Should I open a new pull request?

**Comment by romani** [comment]
please send new PR

**Comment by rnveach** [comment]
When you drop a fork while working on a PR, it disconnects from the fork and becomes lost in limbo. Never delete a fork while working on a PR.

Only way to resolve is to close this PR and start a new PR.

**Comment by romani** [comment]
@Rainy0707 , please create new PR

**Pull request closed without merging**
