### PR TITLE
Issue#13999: Resolve pitest suppression for getParamater() of Javadoc…

### PR DESCRIPTION
**Pull request by Coding-Aliens**
Issue: #13999 : 
Resolve pitest suppression for getParamater() of JavadocMethod
Thanks @Zopsss for the config and proj files.
Regression
Diff Regression config: https://gist.githubusercontent.com/Zopsss/e5c173e3f7d020c335e73260cabc8c25/raw/c15d7975221b4eca529841f31631860b1e10ef50/JavadocMethod.xml

Diff Regression projects: https://gist.githubusercontent.com/Zopsss/22adadb570e4deb95296917244c580b3/raw/29ea756eada8915637b76678db4f46048c198808/projects-to-test-on-for-github-action.properties

Report label: JavadocMethod-1

### CODE REVIEW

**Comment by Coding-Aliens** [comment]
Github, generate report

**Comment by Coding-Aliens** [comment]
Github, generate report

**Comment by Coding-Aliens** [comment]
Github, generate report

**Comment by Coding-Aliens** [comment]
Github, generate report

**Comment by Coding-Aliens** [comment]
There is no difference. 
Explanation: following the java AST from astexplorer.net, the children of the formalParameterList should be formalParameter, there's no need to check if their type is parameter
This PR is finished and ready for reviewing

**Comment by romani** [comment]
> https://astexplorer.net/

is not about checkstyle Ast.
please use https://checkstyle.org/cmdline.html#Command_line_usage with `-t` and share reasons why why it worked fine before your change and will be good after your change.

**Comment by romani** [comment]
@nrmancuso , do we have a way to analyse grammar to prove that there is no other IDENT under PARAMETERS that are not under PARAMETER_DEF ?

**Comment by nrmancuso** [comment]
> @nrmancuso , do we have a way to analyse grammar to prove that there is no other IDENT under PARAMETERS that are not under PARAMETER_DEF ?

Visual inspection of our grammar/ast building is really the only way to do this.

**Comment by nrmancuso** [comment]
>If we built a super file that contained all possibly ANTLR routes, then it could be used programmatically to say if something is absolute or not. The problem is ensuring this file does contain all routes and keeps updated with new antlr.

The length of your "super file" would approach infinity ;)

**Comment by romani** [comment]
Ok investigation is not easy, if regression if report is clean we will merge .

@Coding-Aliens , please confirm that you understand how to get checkstyle AST.
It is must have knowledge when we come to functional fixes in Checks.

**Comment by Coding-Aliens** [comment]
|   |--PARAMETERS -> PARAMETERS [41:33]
        |   |   |--PARAMETER_DEF -> PARAMETER_DEF [41:33]
        |   |   |   |--MODIFIERS -> MODIFIERS [41:33]
        |   |   |   |--TYPE -> TYPE [41:33]
        |   |   |   |   `--IDENT -> String [41:33]
        |   |   |   `--IDENT -> type [41:40]
        |   |   |--COMMA -> , [41:44]
Here is one AST, an element "COMMA" found, analyzing its impact

**Comment by Coding-Aliens** [comment]
In that example, Children of PARAMETERS are either PARAMETER_DEF or COMMA. The func adds the children of PARAMETER_DEF or COMMA with Type INDENT to the output list. Since COMMA doesn't have a child with type INDENT, there is no need to verify if the type is PARAMETER_DEF. 
I think this applies to all other methods, the program will run well.
Ready for reviewing now.

**Comment by romani** [comment]
I think we are good to skip, here is example of tree https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#PARAMETER_DEF

**Review by romani — APPROVED** [review]
Ok to merge

**Review by nrmancuso — APPROVED** [review]
@Coding-Aliens thanks a lot!

**Comment by nrmancuso** [comment]
Rebasing on latest master branch, good to merge once CI is green.

**Pull request merged**
