### PR TITLE
Issue #14806: Re-enable YAMLSchemaValidation to test on IDEA v2022.3.3

### LINKED ISSUE #14806: Re-enable and Monitor `YAMLSchemaValidation` inspection
Follow-up of https://github.com/checkstyle/checkstyle/pull/14696#pullrequestreview-2006660651

[inspection-results/YAMLSchemaValidation.xml
](https://output.circle-artifacts.com/output/job/ab162cce-e22e-4921-9f14-8dc473901855/artifacts/0/home/circleci/project/target/inspection-results/YAMLSchemaValidation.xml)We had stable failure of inspection validation `YAMLSchemaValidation`
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/23624/workflows/e04a197a-8172-4262-9fa3-de02579854c4/jobs/506740/artifacts

```
<problems is_local_tool="true">
<problem>
<file>file://$PROJECT_DIR$/.github/workflows/site.yml</file>
<line>14</line>
<module>project</module>
<entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/.github/workflows/site.yml"/>
<problem_class id="YAMLSchemaValidation" severity="WARNING" 
      attribute_key="WARNING_ATTRIBUTES">Validation by JSON Schema</problem_class>
<description>Schema validation: Property 'name' is not allowed</description>
<highlighted_element>name: "Site"</highlighted_element>
<language>yaml</language>
<offset>0</offset>
<length>12</length>
</problem>
```

This problem is a false positive. Facing instability with this inspection, it had been disabled at https://github.com/checkstyle/checkstyle/commit/65314ea6904f8a09482d6d1f673dc4fd715f0c77

We have migrated IDEA to highest true scopes release `v2022.3.3` at #14696 

~~Hoping that the migration has fixed this problem~~ (https://github.com/checkstyle/checkstyle/issues/14806#issuecomment-2063439340), 
we need to try and re-enable this inspection.

https://github.com/checkstyle/checkstyle/blob/0707dd5ac38b2f0fd4af9941070ea2615c17f335/config/intellij-idea-inspections.xml#L4109-L4111

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Aims to resolve #14806 

### Not ready for merge....

### CODE REVIEW

**Comment by MANISH-K-07** [comment]
One upside being we don't have failure at check_issues anymore :)

**Comment by MANISH-K-07** [comment]
Links to `ci/circleci: run-inspections` of each push will be posted below....
## Re-runs

1. [RUN1](https://app.circleci.com/pipelines/github/checkstyle/checkstyle/25214/workflows/817798be-575a-4998-bb59-a61e261df573/jobs/576504?invite=true#step-104-109_91) - Pass

**Comment by MANISH-K-07** [comment]
Unfortunately, the problem still persists :(
https://output.circle-artifacts.com/output/job/4946fcff-c418-4172-b566-5e343cb6d7b7/artifacts/0/home/circleci/project/target/inspection-results/YAMLSchemaValidation.xml

@romani , what do you suggest we do? Report this to jetBrains?

**Comment by romani** [comment]
Still problem https://circleci.com/gh/checkstyle/checkstyle/576639

**Pull request closed without merging**
