### PR TITLE
Issue #4575: Modified BooleanExpressionComplexityCheckTest.java and moved its input files to the 'booleanexpressioncomplexity' subdirectory

### PR DESCRIPTION
**Pull request by subkrish**
Issue #4575 

This PR moves all inputs of BooleanExpressionComplexityCheckTest of the metrics package to a new subdirectory 'booleanexpressioncomplexity'.

### CODE REVIEW

**Comment by romani** [comment]
please rebase on latest master. 
after each release it is mandatory to rebase to avoid CIs failures.

**Comment by subkrish** [comment]
@romani Rebased. Done. Please review.

**Comment by romani** [comment]
@subkrish , please rebase one more time, I just fixed master build failure for Travis and Appveyor

**Comment by subkrish** [comment]
@romani @rnveach Rebased. Done. Please review.

**Pull request merged**
