### PR TITLE
Issue #10412: Update inputs for UnusedImportsCheckTest

### LINKED ISSUE #10412: Update inputs for UnusedImportsCheckTest
Child of #10080

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #10412

### CODE REVIEW

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
CI should be green
`ERROR] /home/vsts/work/1/s/src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImports15Extensions.java:0: All check input files in the 'src/(it|test)/resources*/' folder must                    have trailing comments "// ok" and/or "// violation". [StyleValidationCommentInInputs]`

**Comment by shashwatj07** [comment]
> CI should be green
> `ERROR] /home/vsts/work/1/s/src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImports15Extensions.java:0: All check input files in the 'src/(it|test)/resources*/' folder must have trailing comments "// ok" and/or "// violation". [StyleValidationCommentInInputs]`

fixed

**Comment by romani** [comment]
@shashwatj07 , CI failure - https://cloud.drone.io/checkstyle/checkstyle/4575/4/2

**Comment by romani** [comment]
Still failure

**Comment by romani** [comment]
Github, rebase

**Comment by romani** [comment]
@shashwatj07 , there is CI problem
```
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsAnnotations.java:8: error: package annotations should be in file package-info.java
17s
3	@MyAnnotation1
17s
4	^
```

**Comment by shashwatj07** [comment]
> @shashwatj07 , there is CI problem
> 
> ```
> src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsAnnotations.java:8: error: package annotations should be in file package-info.java
> 17s
> 3	@MyAnnotation1
> 17s
> 4	^
> ```

fixed now, cirrus needs to be re-run

**Pull request merged**
