### PR TITLE
Issue #957: Remove PMD DefaultPackage rule from excludes

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by romani** [comment]
please explain a reason of suppressions

> DetectorOptions

should become public

> NeverSuppress

please explain, I do not see where violation could be.

**Comment by Vladlis** [comment]
@romani
In NeverSuppress https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/NeverSuppress.java#L29:
if public - Class 'MatchSuppressor' is made visible outside its defined scope
if protected - Class member declared 'protected' in 'final' class
if private - it is used in DetectorOptions

In DetectorOptions all violated methods return instance of non-static inner class 'Builder'.

I'll update the comment in suppression when you accept it.

**Comment by romani** [comment]
>  static final MatchSuppressor INSTANCE = new NeverSuppress();

make it public. Restriction of visibility to package does not do any good. If smb wants to use it, it will find a way to do it. If smb want to use non API class from different package - already get responsibility that it could change in any way that package is required.

> In DetectorOptions all violated methods return instance of non-static inner class 'Builder'

What is a harm to make them public ?

**Comment by Vladlis** [comment]
> make it public

Done
> What is a harm to make them public ?

From IntelliJ IDEA inspection:
> Reports return statements returning an instance of an anonymous, local, or inner class. Such instances keep an implicit reference to the outer instance. Which means the instance can prevent the outer instance from being garbage collected. Any caller of a method which returns such an instance might cause a memory leak by holding on to the instance returned.

**Comment by romani** [comment]
>    make it public
Done

please remove it from suppression.

> From IntelliJ IDEA inspection

In general this rule is right, but not in this case. It is done by pattern Builder. Inner class create outerclass, their life cycles are bonded. There is no memory leak there. We need to suppress Intelij inspection by javadoc tag (see `@noinspection` examples in our code).

-----------

tag `violationSuppressXPath` should be removed completely in PMD config.

**Comment by romani** [comment]
merged as FF, I will do additional fixes myself.

**Pull request closed without merging**
