### PR TITLE
Issue #9921: updated IllegalTypeCheckTest to use unique input files f…

### LINKED ISSUE #9921: update IllegalTypeCheckTest to use unique input file for each test method
IllegalTypeCheckTest.java file reuses some Input files few times in few different test method.
Expected: each test method in Test class should use its own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
Closes #9921 
Made minor changes and created unique Input files for each method.

### CODE REVIEW

**Comment by Devansu-Yadav** [comment]
@romani @timurt Can u pls review my PR? These are my last PRs for GSoC 2nd issues.

**Comment by romani** [comment]
Please fix https://cloud.drone.io/checkstyle/checkstyle/3207/5/3

**Comment by Devansu-Yadav** [comment]
@romani Fixed it!

**Comment by Devansu-Yadav** [comment]
@romani I am really excited to contribute more to Checkstyle. Could you please suggest some issues that I should start working on? 
I was planning to take up PI test issues(GSoC 3rd issue) or create child issues for #3547 and start working on them. What do you think, Sir?

**Comment by Devansu-Yadav** [comment]
@romani @timurt A friendly reminder to review the PR.

**Review by romani — APPROVED** [review]
thanks a lot !

**Pull request merged**
