### PR TITLE
minor: add Input to PR

### PR DESCRIPTION
**Pull request by romani**
just for testing of https://github.com/checkstyle/checkstyle/issues/15518

https://github.com/checkstyle/test-configs

on new Input:
by full path, copy from github.
by last folder and name of file
by name of file

Report label: Traliing comment all
Diff Regression config: https://raw.githubusercontent.com/checkstyle/test-configs/main/TrailingComment/all-examples-in-one/config.xml
Diff Regression projects: https://gist.githubusercontent.com/romani/b8806e1865854452561ddd7d7fa9797a/raw/a779bdeb5f2b183967ec8bc0a46b90a58b439d48/project.properties

### CODE REVIEW

**Comment by romani** [comment]
Github, generate report for RegexpHeader/all-examples-in-one

**Comment by romani** [comment]
@relentless-pursuit , one more example of failure in report generation do no post/comment 

https://github.com/checkstyle/checkstyle/actions/runs/10615491567/job/29425103291#step:10:436

**Comment by romani** [comment]
Github, generate report for Regexp/all-examples-in-one

**Comment by romani** [comment]
One more failure to run report 
https://github.com/checkstyle/checkstyle/actions/runs/10618482161

And make error comment.

**Comment by romani** [comment]
Github, generate report for RegexpHeader/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RedundantModifier/all-examples-in-one

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
This is invalid PR, we need compul

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by romani** [comment]
Github, generate report by config from /finalparameters/InputFinalParameters6.java

**Comment by romani** [comment]
Github, generate report by config from finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by romani** [comment]
Github, generate report by config from /finalparameters/InputFinalParameters5.java

**Comment by romani** [comment]
Github, generate report by config from InputFinalParameters5.java

**Comment by relentless-pursuit** [comment]
Hi @romani, since we don't have InputFinalParameters5.java in this PR, and the new changes i am trying to work on should give report failure, right?

**Comment by relentless-pursuit** [comment]
> There is no 6, but there is a 5. https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
> 
> I tested on 5 so no error is expected

But, the changes I am working on it will give error if the file is not a part of PR. This is the process, right?
I see the above as a defect because 5 is not a part of the PR.

**Comment by romani** [comment]
In this PR I don't remove input 5, I just add input 6, so all inputs should work 1-6 in this PR triggering

**Comment by romani** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java

**Comment by romani** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by romani** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by romani** [comment]
Github, generate report by config from InputFinalParameters6.java

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for ParenPad/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for ParameterNumber/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for ParameterName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for ParameterAssignment/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for PackageName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for PackageDeclaration/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for OuterTypeFilename/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for FallThrough/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for ExplicitInitialization/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for EmptyLineSeparator/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for EmptyLineSeparator/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for EmptyForIteratorPad/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for EmptyForInitializerPad/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for EmptyForInitializerPad/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
GitHub, generate report

**Comment by romani** [comment]
GitHub, generate report

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by relentless-pursuit** [comment]
GitHub, generate report

**Comment by romani** [comment]
GitHub, generate report

**Comment by romani** [comment]
Github, generate report by config from InputFinalParameters5.java

**Comment by romani** [comment]
Github, generate report for MultipleStringLiterals/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for IllegalTokenText/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for Regexp/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for InterfaceMemberImpliedModifier/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for NeedBraces/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for RegexpHeader/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for Regexp/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RegexpHeader/Example2

**Comment by romani** [comment]
Github, generate report for TrailingComment/Example4

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
I cancelled both, 
Even on this small set of projects it hanging https://github.com/checkstyle/checkstyle/actions/runs/11315313643/job/31466328580

>Diff Regression config: https://raw.githubusercontent.com/checkstyle/test-configs/main/TrailingComment/all-examples-in-one/config.xml
Diff Regression projects: https://gist.githubusercontent.com/romani/b8806e1865854452561ddd7d7fa9797a/raw/daeeb3bcebadfa933a51418eeacd062e9432ad84/project.properties

**Comment by romani** [comment]
Github, generate report for TrailingComment/Example3

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for TrailingComment/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for TrailingComment/all-examples-in-one

**Comment by relentless-pursuit** [comment]
> Github, generate report for TrailingComment/all-examples-in-one

https://github.com/checkstyle/checkstyle/actions/runs/11356274188

**Comment by romani** [comment]
Testing is over.
Summer project is done.

We will create new PR if anything extra in test is required

**Pull request closed without merging**
