### PR TITLE
Issue #3616: Fix/suppress TC "Deprecated member is still used" errors

### PR DESCRIPTION
**Pull request by Vladlis**
#3616

### CODE REVIEW

**Comment by rnveach** [comment]
@Vladlis TC is broken right now. How can we verify that these changes are good?

**Comment by Vladlis** [comment]
@rnveach 
I did a few commits in the same branch and looks like this comparison doesn't work correctly in such case.
We can compare with master: `Total: 2643 (+0 -0) Errors: 1393 (+0 -0)` - 3 errors are fixed.

**Comment by rnveach** [comment]
I am hesitant to fix TC issues when TC isn't reporting stuff right.
@romani What is your opinion?

**Comment by romani** [comment]
@rnveach , base on latest comment from TC support, they will not rollback to previous version of IntelijIdea, so TC will be failed for sometime, there will be new violations from TC 100%.
we will just need to resolve them as TC is fixed.
So I am fine to merge this PR for now.

**Pull request merged**
