### PR TITLE
Issue #3551, a complete implementation, fixing #6680 and #7119

### PR DESCRIPTION
**Pull request by gmshake**
What has been done:

1. Issue #6680 was fixed, robustly.
2. Issue #7119 was fixed.
3. Slightly changed behavior about how to detect empty lines.  Now take comments between imports or import groups into account.

### CODE REVIEW

**Comment by rnveach** [comment]
@gmshake CI is failing.
Also your commit references a closed issue. Please update it to an open issue you are fixing.

**Comment by rnveach** [comment]
@gmshake ping

**Comment by gmshake** [comment]
@rnveach  I'm closing this as it was split into two separate ones,  https://github.com/checkstyle/checkstyle/pull/7197 and https://github.com/checkstyle/checkstyle/pull/7198

**Comment by gmshake** [comment]
@rnveach ping

**Comment by rnveach** [comment]
Feel free to close it since it is split.

**Pull request closed without merging**
