### PR TITLE
minor: fix indentation in config examples

### PR DESCRIPTION
**Pull request by strkkk**
Fix indentations
image

image

### CODE REVIEW

**Review by rnveach — APPROVED** [review]

**Review by pbludov — APPROVED** [review]

**Comment by romani** [comment]
@strkkk 

```
✘-1 ~/java/github/romani/checkstyle [master|✚ 1] 
17:36 $ git diff
diff --git a/config/checkstyle_checks.xml b/config/checkstyle_checks.xml
index d66ac2e..52f398e 100644
--- a/config/checkstyle_checks.xml
+++ b/config/checkstyle_checks.xml
@@ -85,6 +85,12 @@
     <property name="id" value="regexpMultilineDefault"/>
   </module>
   <module name="RegexpMultiline">
+    <property name="id" value="noIndentationInXmlSource"/>
+    <property name="format" value="&lt;source&gt;\r?\n\s+"/>
+    <property name="fileExtensions" value="xml"/>
+    <property name="message" value="Content of source tag should not be intended"/>
+  </module>
+  <module name="RegexpMultiline">
     <property name="id" value="noConsecutiveLines"/>
     <property name="format" value="\r?\n[\t ]*\r?\n[\t ]*\r?\n"/>
     <property name="fileExtensions" value="java,xml,properties"/>
```
result:
```
[INFO]      [echo] Checkstyle started (checkstyle_checks.xml): 03/11/2020 05:21:46 PM
[INFO] [checkstyle] Running Checkstyle  on 1384 files
[ERROR] [checkstyle] [ERROR] ...src/xdocs/beginning_development.xml:37: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/beginning_development.xml:56: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/beginning_development.xml:64: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/beginning_development.xml:72: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/beginning_development.xml:81: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/beginning_development.xml:92: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/beginning_development.xml:102: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/beginning_development.xml:112: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/beginning_development.xml:124: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/beginning_development.xml:132: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_coding.xml:1760: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_coding.xml:6196: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_coding.xml:6211: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_coding.xml:6501: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_coding.xml:6526: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_coding.xml:6534: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_filters.xml:1273: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_metrics.xml:167: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_naming.xml:2574: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_naming.xml:3022: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_naming.xml:3042: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_naming.xml:3063: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_sizes.xml:367: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_sizes.xml:415: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_sizes.xml:1289: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_sizes.xml:1313: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/config_sizes.xml:1341: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/writingchecks.xml:198: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/writingchecks.xml:632: Content of source tag should not be intended [noIndentationInXmlSource]
[ERROR] [checkstyle] [ERROR] ...src/xdocs/writingchecks.xml:640: Content of source tag should not be intended [noIndentationInXmlSource]
```

can we use our check for this ?

**Comment by strkkk** [comment]
@romani I have added a check and corrected other violations

**Comment by romani** [comment]
@strkkk ,
you modified regexp,
do we have problems with what I suggested ?

still problem (but detected by my regexp):
https://github.com/checkstyle/checkstyle/blob/3fc9dd98ad6ed963e2cfcd2e630f7031ec5b0c1e/src/xdocs/config_metrics.xml#L167-L169
https://checkstyle.org/config_metrics.html#BooleanExpressionComplexity

**Comment by strkkk** [comment]
@romani I made check specific for config examples, not for all indentation issues in docs. Original intention of this PR was to fix only issues with configs

**Comment by romani** [comment]
I already tired of this problem in our code, I pushed one more commit for other items.
one more issue is created https://github.com/checkstyle/checkstyle/issues/8961

**Comment by romani** [comment]
Github, generage wesite

**Comment by romani** [comment]
I forgot to update message in this Check instance

**Comment by romani** [comment]
message fixed and verified for spelling.

**Pull request merged**
