### PR TITLE
Issue #7753: Update AbstractChecks to log DetailAST - NoLineWrap

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
resolves Issue #7753 

[Diff Report](https://abhishek-kumar09.github.io/7753/reports/diff/index.html)

### CODE REVIEW

**Comment by strkkk** [comment]
@Abhishek-kumar09 FYI your check is duplicated in report
image

**Comment by Abhishek-kumar09** [comment]
> @Abhishek-kumar09 FYI your check is duplicated in report

I will update the report soon.

**Comment by strkkk** [comment]
@Abhishek-kumar09 no need to update, it is just for you to pay attention to it in the future.

**Comment by Abhishek-kumar09** [comment]
> @Abhishek-kumar09 no need to update, it is just for you to pay attention to it in the future.

Ok I will pay more attention next time. ThankYou.

**Pull request merged**
