### PR TITLE
Issue #148 magic number detection: option to ignore magic numbers in fie...

### PR DESCRIPTION
**Pull request by ychulovskyy**
...ld declarations

### CODE REVIEW

**Comment by romani** [comment]
1) please udpate javadoc and provide example of config and code and tsame for xdoc

2) please confirm that you ahve no exceptions on launch of https://github.com/checkstyle/contribution/tree/master/checkstyle-tester against all projects

**Comment by ychulovskyy** [comment]
@romani contribution becomes complicated. Is it possible to automate step 2 with Travis CI?

**Comment by romani** [comment]
It is not complicated all that steps are minimal and focused on quality, just send code is not enough. I need to be sure that by fixing  minor you do not introduce serious regression unintensionally.

I am open to improvement and ease of any of that process.
To my knowledge of travis , it will not help. Travis kills build process that takes more then 10 min.

Testing can be automated only for exception catching - https://github.com/checkstyle/resources/blob/master/test-no-exceptions.sh , generated report have to be reviewed by human to catch false positives.

In checkstyle-tester you do not need too much, just uncomment all projects in property file , change config to have only your check and run launcher. Please read README file for details, or ask me.

**Comment by ychulovskyy** [comment]
@romani It's not about easy/hard.
GitHub is so popular because it's easier to use than patches or SVN branches. One click - done.
Similar with open source projects. I contribute because it's easy, I receive pleasure and see immediate feedback.
IMHO, there are 2 big items that stops people from contributing into CheckStyle:
1. Need to do checkout another project, do manual steps, upload a report to my GitHub repo... it's just to complicated, and not related to contribution developers want to do. It's overhead.
Need to automate it's somehow. If Travis CI kills build after 10 minutes - create 10 projects to avoid timeouts.
2. Need to wait a year before a new feature migrated from sevntu-checkstyle to checkstyle project. It's just too much. People wants everything and right now ;)
Why not to mark new features as "Experimental". Developers can use experimental checks if they want, but it's not guaranted that the Check API is stable. If checks are independent - it's not a problem that an experimental check fails.

**Comment by romani** [comment]
> GitHub is so popular because it's easier to use than patches or SVN branches. One click - done

:) let not mix all together, quick contribution and valiable contribution is diferent things. Call me in skype , I will tell you a lot, jut do not want to type too much there with explanations,

> I contribute because it's easy,

I receive al ot of contributions for documentation and minors, and I do belive people do not checkout sources, just do that from web. But changes in code is NOT A FUN !! It is responsibility. If smb want to throw in us peace of sh..t and claim that fix a problem - it will not work. I have a lot of examples in my experience, just call me in skype I will tell you a lot of stories.

> Need to do checkout another project, do manual steps,

contributor have to do even more and all that manually :( - he need to think about update, he need to install developemnt environment, he need to do a testing not only in UT , but at least on his own closed sources, ....... Yes, we are not ideal in formulating all that steps but we do progress each time. I am open to proposals and help in that area.

> Need to automate it's somehow. If Travis CI kills build after 10 minutes - create 10 projects to avoid timeouts.

I am open to proposals, I do not know how to to that with Travis. A lot can be mproved in Chekcstyle workflow I do not have time to do all. 

> Need to wait a year before a new feature migrated from sevntu-checkstyle to checkstyle project.

:) please reread my post in mail-list about moratorium period, if stil not a clear please call me. 

> but it's not guaranted that the Check API is stable. 

Each time I decided to brake compatibility, I have a mail from Eclispe-cs author with complains. I even do not know all tools that use checkstyle API and internals (any Check option is also API).

> Why not to mark new features as "Experimental"

Where can do that mark ? in documentation that nobody read ? user read documentation only after he got a problem that he cann ot figureout easily.
Please be a little bit exact and please move that talk to mail-list, and lets finish Check changes there.

By separate project I allow them to use their Check right after implementation (in all IDEs and systems). Allow to use result even before merge to experimental project ! I can sometime not completely agree on the idea, but it is already in use without any pain to others. 
I have examples of good ideas that failed after extensinve usage over few years. Please call me I will give them to you easily.

One more time :  find me in skype, I will run over each of that items one more time, as want you to understand all nuances.

**Comment by romani** [comment]
without publicly published test report, your PR will wait till I have time to do that myself, activity in project is growing .... it could be a while.

**Comment by romani** [comment]
@ychulovskyy , if you finish that PR before Saturday , your changed will be released in 6.5 .

**Comment by romani** [comment]
> ./test-no-exceptions.sh 

No Exceptions were detected.

**Comment by romani** [comment]
> checkstyle-tester 

no exceptions detected.

**Comment by romani** [comment]
merged manually as FF, and all missed parts are updated.

**Pull request closed without merging**
