### PR TITLE
Make RedundantModifier checks if inner types declared in interface ...

### PR DESCRIPTION
**Pull request by liscju**
has redundant static modifier, fixes part of #1242. With PR #1463 closes issue #1242.

### CODE REVIEW

**Comment by liscju** [comment]
Those two fails are in Orekit build :

https://github.com/checkstyle/Orekit/blob/master/src/main/java/org/orekit/files/general/OrbitFile.java#L30 => redundant public modifier

https://github.com/checkstyle/Orekit/blob/master/src/main/java/org/orekit/propagation/events/handlers/EventHandler.java#L39 => redundant public modifier

**Comment by romani** [comment]
Please send PR to our fork, before merge CIs should be green

**Comment by liscju** [comment]
I sent PR to checkstyle/orekit https://github.com/checkstyle/Orekit/pull/2/files ( merged at this moment) and to original project https://github.com/CS-SI/Orekit/pull/2

**Comment by romani** [comment]
last minor:

> getDefaultTokens()

please reuse getAcceptableTokens() , to avoid copy paste.

**Comment by liscju** [comment]
@romani reused getAcceptableTokens as requested

**Comment by romani** [comment]
thanks a lot, merged as FF

**Pull request closed without merging**
