### PR TITLE
Issue #7023: include all commits for CI checks between head and master

### PR DESCRIPTION
**Pull request by rnveach**
#7023

### CODE REVIEW

**Comment by rnveach** [comment]
@romani appveyor is not in CI list. Is it ok to merge?

**Comment by rnveach** [comment]
https://circleci.com/gh/checkstyle/checkstyle/27444?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
CircleCI skipped its own run even though its YML was changed.
https://github.com/checkstyle/checkstyle/pull/7090/files#diff-1d37e48f9ceff6d8030570cd36286a61L21
I am not seeing the YML file for CircleCI as part of the file check.

This isn't correct right?

**Comment by rnveach** [comment]
Since they are all unrelated to the changes I made, I will go ahead and merge this. I will not close issue until we confirm the fix more in the blocked PR.

**Comment by romani** [comment]
Ok to merge, just trigger few not-for-merge PRs to test, with few commits in PR.

**Comment by romani** [comment]
>This isn't correct right?

Strange. Let's test it again

**Comment by rnveach** [comment]
Running the command locally:
````
[[ $(git diff --name-only 6e6540f7b21907c2dcaf37aa1503d379eb29822c 372594608a0c3f86294c1eb03b09b73e67b0329f | grep -vE ".github|appveyor.yml|.travis.yml|\.ci/|fast-forward-merge.sh|LICENSE|LICENSE.apache20|README.md|release.sh|RIGHTS.antlr|shippable.yml|codeship|shippable.sh|wercker.yml|wercker.sh|intellij-idea-inspections.xml|org.eclipse.jdt.core.prefs|Jenkinsfile" | wc -c) -gt 0 ]] && echo false || echo true
````
does not reproduce the issue. It prints `true` and that sets `SKIP_CI_BY_FILES` to `false`.

https://circleci.com/gh/checkstyle/checkstyle/27439
Does show:
````
SKIP_CI_BY_FILES=true
build is skipped ...
````

https://circleci.com/gh/checkstyle/checkstyle/27438
Did have a bash failure which is the build before the one in question. Is it possible something didn't end right with the failure and affect the next build, like a left over file from `.ci-temp`?

**Pull request merged**
