### PR TITLE
Use EqualsVerifier to test FilterSet and remove obsolete code. #1088

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
this is API class, unfortunately - we can not remove methods so easy. Please explain reasons in detail.

**Comment by mkordas** [comment]
Good catch. I've removed these methods as they are not used in Checkstyle at all. But as this is API, other projects may use it. I'll check it in `checkstyle-maven-plugin`. Should I check it anywhere else?

Moreover, first step would be to deprecate these methods, right?

**Comment by romani** [comment]
You can not even imagine how much projects use our lubrary,  we do not know all if them.

My idea is to keep that class with all its methods for now, as it is now. One day we will have time to define classes should be in api and in what form, current state of api package is unfortunately big.

**Comment by mkordas** [comment]
OK, it's good idea. I won't delete any methods, but I will fix all `equals` and `hashCode` that do not follow contract and good practices (as kind of bug fix). What do you think?

**Comment by romani** [comment]
Yes. Please use Idea generation for that methods ( java7 form).

**Comment by mkordas** [comment]
OK, I will do. Actually the default IDEA Java 7 generated code do not follow our code standards. Variable is not final and ifs do not have braces, so it needs some tuning :)

**Comment by romani** [comment]
I did additional manual changes, it is ok.

**Comment by mkordas** [comment]
One more thing - I've just realized that `FilterSetTest` do not test `FilterSet` at all, it tests only "filter set" feature of `CsvFilter`. So before I proceed, some more cleanup is needed.

**Comment by romani** [comment]
merged as FF

**Comment by mkordas** [comment]
I see that you've merged this PR, so we changed public API: `FilterSet` doesn't have `toString` and `getFilters` anymore. Are you sure this is fine?

**Comment by romani** [comment]
My mistake, i will restore removed methods as mark them as deprecated

**Comment by romani** [comment]
methods are restored, I decided to not do deprecation for now - https://github.com/checkstyle/checkstyle/commit/d6205babad3ada2845d35174148e8deaf88aefc0

**Pull request closed without merging**
