### PR TITLE
Issue #13213: Remove '//ok' comments from Input files (ImportOrder)

### PR DESCRIPTION
**Pull request by relentless-pursuit**
part of https://github.com/checkstyle/checkstyle/issues/13213

link to check documentation: https://checkstyle.org/checks/imports/importorder.html

```
% awk '/UnnecessaryOkComment/ {getline nextLine; if (nextLine ~ /importorder/ && nextLine !~ /customimportorder/) print $0}' checkstyle-input-suppressions.xml | wc -l
     347

% awk '/UnnecessaryOkComment/ {getline nextLine; if (nextLine ~ /importorder/ && nextLine !~ /customimportorder/) print $0}' checkstyle-input-suppressions.xml | wc -l
       0

```

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
This completes the removal of // ok for `com/puppycrawl/tools/checkstyle/checks/imports`

**Review by nrmancuso — APPROVED** [review]
Ok to merge,  @relentless-pursuit please resolve conflicts

**Comment by relentless-pursuit** [comment]
> Ok to merge, @relentless-pursuit please resolve conflicts

done

**Comment by relentless-pursuit** [comment]
I couldn't verify any issue with PR description. Can we retrigger the job?

**Review by romani — APPROVED** [review]
ok to merge

**Comment by relentless-pursuit** [comment]
> ok to merge

```
2023-09-04T13:49:23.2309218Z Requested labels: ubuntu-22.04
2023-09-04T13:49:23.2309607Z Job defined at: checkstyle/checkstyle/.github/workflows/check-pr-description.yml@refs/pull/13692/merge
2023-09-04T13:49:23.2309799Z Waiting for a runner to pick up this job...
2023-09-04T13:49:23.4100251Z Job is waiting for a hosted runner to come online.
2023-09-04T13:49:27.0996453Z Job is about to start running on the hosted runner: GitHub Actions 17 (hosted)
2023-09-04T13:49:29.6151706Z Current runner version: '2.308.0'
2023-09-04T13:49:29.6181078Z ##[group]Operating System
2023-09-04T13:49:29.6181945Z Ubuntu
2023-09-04T13:49:29.6182407Z 22.04.3
2023-09-04T13:49:29.6182696Z LTS
2023-09-04T13:49:29.6183033Z ##[endgroup]
2023-09-04T13:49:29.6183393Z ##[group]Runner Image
2023-09-04T13:49:29.6183742Z Image: ubuntu-22.04
2023-09-04T13:49:29.6184154Z Version: 20230821.1.0
2023-09-04T13:49:29.6184750Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230821.1/images/linux/Ubuntu2204-Readme.md
2023-09-04T13:49:29.6185435Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230821.1
2023-09-04T13:49:29.6185950Z ##[endgroup]
2023-09-04T13:49:29.6186346Z ##[group]Runner Image Provisioner
2023-09-04T13:49:29.6186728Z 2.0.266.1
2023-09-04T13:49:29.6187069Z ##[endgroup]
2023-09-04T13:49:29.6187833Z ##[group]GITHUB_TOKEN Permissions
2023-09-04T13:49:29.6188482Z Contents: read
2023-09-04T13:49:29.6188837Z Metadata: read
2023-09-04T13:49:29.6189410Z Packages: read
2023-09-04T13:49:29.6189834Z ##[endgroup]
2023-09-04T13:49:29.6193569Z Secret source: None
2023-09-04T13:49:29.6194139Z Prepare workflow directory
2023-09-04T13:49:29.6939075Z Prepare all required actions
2023-09-04T13:49:29.7130290Z Getting action download info
2023-09-04T13:49:29.9020691Z Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
2023-09-04T13:49:30.5513719Z ##[error]Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_9dafcfd5-42f8-404c-90eb-7152e536021f/18ff663b-c33b-4ab2-8c65-15044abca57a.tar.gz. return code: 2.
```

logs don't look like usual. any issues with ci?

**Comment by relentless-pursuit** [comment]
> some CI system problem, restated.

can we merge it?

**Pull request merged**
