### PR TITLE
Issue #11214: specified violation message in EmptyForInitializerPadCheck

### LINKED ISSUE #11214: Specify violation messages in input files
Single Check might have multiple violations messages, we need to see exact violation message if Check has multiple messages, to be sure that violation of correct type is placed at right line.

Violation messages have not been specified in certain input files, a list of checks in which violation message is not specified in the input file and have more than one violation message key has been specified here-
https://github.com/checkstyle/checkstyle/blob/72f182241a3b8a6d905328dfcfc9739dfffac9bd/src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java#L99

To Do-

- Pick a check (single Check Inputs files update in single Pull Request) To allocate Check update for you please make comment in issue "I am on XxxxxCheck"
- Find all input files that use that check
- Add violation message at the end of the `// violation` comment
- Remove the check from the suppression list

Same has been demonstrated at 461cd048bb059ea6948945104682fb99d4e155dc
If the violation message contains special regex characters, escape that character.
Ignore input files using more than a single check.

Ignore lines with multiple violations, eg-
```
// 2 violations
// 2 violations above
// 4 violations below
```
and any other violation message of this nature.

List of Checks: 

- [x]   RegexpCheck
- [x]   EmptyForInitializerPadCheck
- [ ]   JavadocStyleCheck
- [x]   SummaryJavadocCheck

Old tracker (some might be outdated):

- [x] RightCurlyCheck
- [x] EqualsAvoidNullCheck
- [x] MethodParamPadCheck
- [x] DescendantTokenCheck
- [x] RequireThisCheck
- [x] EqualsHashCodeCheck
- [x] JavaNCSSCheck
- [x] ReturnCountCheck
- [x] AnnotationUseStyleCheck
- [x] EmptyLineSeparatorCheck
- [x] OrderedPropertiesCheck
- [x] AbstractJavadocCheck
- [x] DeclarationOrderCheck
- [x] MissingOverrideCheck
- [x] AbstractClassNameCheck
- [x] MethodCountCheck
- [x] PackageDeclarationCheck
- [x] JavadocTypeCheck
- [x] LeftCurlyCheck
- [ ] RegexpCheck
- [x] WhitespaceAfterCheck
- [x] MultipleVariableDeclarationsCheck
- [x] EmptyForInitializerPadCheck
- [x] UnnecessaryParenthesesCheck
- [x] JavadocMethodCheck
- [x] ModifierOrderCheck
- [x] MissingDeprecatedCheck
- [x] RegexpOnFilenameCheck
- [x] RedundantImportCheck
- [x] EmptyBlockCheck
- [x] UniquePropertiesCheck
- [x] WhitespaceAroundCheck
- [x] OperatorWrapCheck
- [x] GenericWhitespaceCheck
- [ ] EmptyForIteratorPadCheck
- [ ] JavadocStyleCheck
- [x] JavadocPackageCheck
- [x] FallThroughCheck
- [x] WriteTagCheck
- [x] TranslationCheck
- [x] FileTabCharacterCheck
- [x] ImportOrderCheck
- [x] JavadocContentLocationCheck
- [x] JavadocParagraphCheck
- [ ] SummaryJavadocCheck
- [x] DefaultComesLastCheck
- [x] AnnotationLocationCheck
- [ ] CustomImportOrderCheck
- [x] NewlineAtEndOfFileCheck
- [x] VariableDeclarationUsageDistanceCheck
- [x] ImportControlCheck

format it like:
https://github.com/checkstyle/checkstyle/blob/5b2a0efc8c577d6382effe818b0d94d489397352/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderOnlyModifiers.java#L16

if message is long, we can shorten it by regexp usage (but do not over use regexp, message should be readable):
https://github.com/checkstyle/checkstyle/blob/4bd9856de41ae74c903bf8468b3355ded0b73a58/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullEnhancedInstanceof.java#L15

There are a lot of examples in code just search for `// violation` in Input files for more examples.

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #11214: specified violation message in EmptyForInitializerPadCheck

### CODE REVIEW

**Comment by Kevin222004** [comment]
@Vyom-Yadav  please give a look on line 10 in file https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforinitializerpad/InputEmptyForInitializerPad2.java

here // violation is defined but in file
https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheckTest.java
there is no method define  in this EmptyForInitializerPadChecktest.java file

I have not make any changes in that file

**Comment by romani** [comment]
Please remove from input file all content of class, it should be empty class. 
It tests only invalid property definition, violation inside are not a focus.
https://github.com/checkstyle/checkstyle/blob/e17350d48ea7bccffd0c58c622fae9113fdd7db4/src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheckTest.java#L107

**Comment by Kevin222004** [comment]
@romani  please review It is correct or not

**Comment by romani** [comment]
Keep looking at CIs failures and try to understand and fix them

**Review by romani — APPROVED** [review]
Ok to merge if CI pass

**Pull request merged**
