### PR TITLE
doc: clearly explain commit message requirements

### PR DESCRIPTION
**Pull request by Bananeweizen**
Since I had a hard time learning the commit message requirements in my previous pull request, I hereby update the contribution page to better explain that to future contributors.

### CODE REVIEW

**Comment by Bananeweizen** [comment]
@romani The change already mentioned the precise format including the colon, but I've rephrased it. The page also already explains that issues have to be approved, just _outside_ the area I changed. Everything you requested is there.

**Comment by rnveach** [comment]
Please see https://github.com/checkstyle/checkstyle/commit/af143768faed1090f57d4b47d10a997b4bf7a8e7 for list of changes requested.

**Comment by Bananeweizen** [comment]
I have read the commit and which changes are requested. I can only repeat: All of the requested changes are there already.
* precise format of the commit message for small changes, including colon: https://github.com/checkstyle/checkstyle/pull/5576/files#diff-221505797d030b93fc5e160af6b2c86bR142
* removed space at end of line: https://github.com/checkstyle/checkstyle/pull/5576/commits/6d4b8d7690b6f9a14c59ccb03d4669809e1a910e#diff-221505797d030b93fc5e160af6b2c86bR143 and  https://github.com/checkstyle/checkstyle/pull/5576/commits/6d4b8d7690b6f9a14c59ccb03d4669809e1a910e#diff-221505797d030b93fc5e160af6b2c86bR147
* requirement that issues need to be approved first: https://github.com/checkstyle/checkstyle/pull/5576/commits/6d4b8d7690b6f9a14c59ccb03d4669809e1a910e#diff-221505797d030b93fc5e160af6b2c86bR50

**Comment by rnveach** [comment]
@romani Please finish your review.

**Comment by Bananeweizen** [comment]
Sorry, please change this on your own.

**Pull request closed without merging**
