### PR TITLE
Issue #13693: use marco property in module templates

### PR DESCRIPTION
**Pull request by romani**
Issue #13693

no updates in javadoc until #13626

this is RP to agree on, if all good, other PR, will be batched with 5-7 modules.

### CODE REVIEW

**Comment by rnveach** [comment]
If we are going to work on expanding the properties macro, why don't we fix the issue identified with it creating the URLs?

**Comment by romani** [comment]
Please share link to such issue

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/pull/13721
https://github.com/checkstyle/checkstyle/issues/13722

**Comment by romani** [comment]
Thanks a lot.
I will skip updates in modules that has affected types of property, where link is changing.
We are waiting for such issue to be resolved.

But let's keep merging updates where link is not changing, and just some html indentation affected.

**Comment by romani** [comment]
@rnveach , I can reduce batch size to 5  to make it easier to review.
I such PRs we just need to be sure that links are same, I will try to be attentive and put on a side issues problematic cases.

**Comment by rnveach** [comment]
There wouldn't be a concern if we just fixed the problem sooner than later.

**Review by rnveach — APPROVED** [review]

**Comment by romani** [comment]
@rnveach , I try to help in this project only for no brain activity, and keep my brain time only for pitest project.

To let both project to be finished.

**Review by nrmancuso — APPROVED** [review]

**Pull request merged**
