### PR TITLE
Issue #5790: Upgrade to PMD 6.6.0

### PR DESCRIPTION
**Pull request by pbludov**
Issue #5790

Release 6.6 seems to be more stable than its 6.X predecessors.

### CODE REVIEW

**Comment by rnveach** [comment]
wercker failure is in Apache Struts looks unrelated:
> Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'InterfaceMemberImpliedModifier' class, it is also not possible to instantiate it as

**Comment by romani** [comment]
Wercker was restarted.

@pbludov, please explain removal of OptimizableToArrayCall at issue, it would be awesome to briefly cover all changes

**Comment by pbludov** [comment]
this should be done in #5949

OptimizableToArrayCall suppression make no sense now.

**Comment by rnveach** [comment]
@pbludov I think you need to update your branch on the latest master.
Your top commit is based on 69ef08a20f4432c001bfa940b53feca6e7628b95 which is Jun 30th. 
`InterfaceImpliedModifierCheck` came in 327b556b97952a087b0e246f6537a6fec897991e after your top commit.

**Comment by romani** [comment]
Wercker hanged for 4 hours at Xwiki build item.
Restarted.

**Comment by pbludov** [comment]
> Please rebase on latest master to fix recent failures from Travis.

done

**Pull request merged**
