### PR TITLE
100% conditional coverage for visitToken(), leaveToken() and leaveMemberDef(), issue#1024

### PR DESCRIPTION
**Pull request by MEZk**
100% conditional coverage for visitToken(), leaveToken() and leaveMemberDef(), issue#1024

### CODE REVIEW

**Comment by romani** [comment]
As it 100% coverage, i need to see update in pim.xml with removal of line that correspond to ExecutableStatementCountCheck.

Please put a space to commit message before "#".

**Comment by romani** [comment]
@MEZk , did you see my comment ?

**Comment by MEZk** [comment]
@romani It's only for methods

**Comment by romani** [comment]
@MEZk , ok , please change commit message and let me merge that changes.

**Comment by MEZk** [comment]
@romani done

**Comment by romani** [comment]
merged as FF.

**Pull request closed without merging**
