### PR TITLE
Add new check WhitespaceAfterLastMemberCheck

### PR DESCRIPTION
**Pull request by liscju**
I need to check if there is a whitespace after last member of the class, is there a way to do this with one of the existing check? Because I did not find a checkstyle check that fulfills my requirements I wrote this check as a proposal of the solution(it is work in progress, it does not adhere to commit rules etc).

Would it be possible to add this kind of check to checkstyle?

### CODE REVIEW

**Comment by romani** [comment]
new Checks are not allowed for now.

more details are at http://checkstyle.sourceforge.net/contributing.html#Introduction second "attention".

**Comment by liscju** [comment]
> new Checks are not allowed for now.

Ok, can you tell me is there an existing check that fulfills my need or which check would be suitable to add this as an option? Or this kind of check is not suitable for Checkstyle and should I send PR to sevntu.checkstyle?

**Comment by rnveach** [comment]
Google groups is a better location for these kinds of things where you are asking questions instead of posting issues/fixes.

I think the closest thing to what you want might be `EmptyLineSeparatorCheck`, but it purposefully skips over the last method/field/etc to not require a empty line after it.

**Comment by romani** [comment]
> can you tell me is there an existing check that fulfills my need or which check would be suitable to add this as an option?

please post mail-list question

>  Or this kind of check is not suitable for Checkstyle and should I send PR to sevntu.checkstyle?

sevntu project is a place for new Checks to pass testing.

**Pull request closed without merging**
