### PR TITLE
minor: reformat code to match upcoming checks

### PR DESCRIPTION
**Pull request by pbludov**
minor: reformat code to match upcoming checks

### CODE REVIEW

**Comment by rnveach** [comment]
> Caused by: java.lang.NoSuchMethodError: com.puppycrawl.tools.checkstyle.api.FileContents.getBlockComments()Lcom/google/common/collect/ImmutableMap;
	at com.github.sevntu.checkstyle.checks.coding.ForbidCCommentsInMethodsCheck.beginTree(ForbidCCommentsInMethodsCheck.java:66)

Failing CI will be fixed today.

**Comment by rnveach** [comment]
CI was failing due to a timeout. I restarted it and it is passing now.

**Comment by romani** [comment]
Third commit contains a undesirable changes in inner blocks (while, try, if, ...).
But as we discussed before we will think about rules for such cases after implementation of basic validation.

**Comment by rnveach** [comment]
@romani Is all of third commit change undesirable or is there specific ones?

**Comment by pbludov** [comment]
I thought that the format is "blank line for types" and "no blank lines for everything else".
@romani, please clarify your point of view.

**Comment by romani** [comment]
Let's look at cases like https://github.com/checkstyle/checkstyle/commit/df1742a79c25cf39004e6dcd0a423c0c6a8d72eb#diff-551495ce0115474ce5092d66856a2a08L134 and other cases where empty line was removed after left curly of try,if,while,... blocks. Some of them were done intentionally to ease readability of code and visually decide where multiline method signature is finished. If you again to mail list examples from me, you can see more clear examples where extra empty line do good job to ease reading.
As I stated from the begging of issue, I do not have strict rules how to detect cases where empty line is required and where it is optional, I just know that as soon method signature or IF or ... become multiline/line wrapped it is high chance that empty line could do a good job.
But for now we do minimal required validation by simple Check, enhancement will be next step, next issues.

**Comment by rnveach** [comment]
@romani Thanks.
As you see things you want fixed in the next step, please create issues on them and mark them as requiring the main check to be implemented first so we don't forget these things.

**Comment by romani** [comment]
I am too much uncertain on design to open clear issue, one day it will be raised again and we can see what it should be extension on future new Checks or smth completely new or ....

**Pull request merged**
