### PR TITLE
Issue #652: New CLI option to print Javadoc comment parse tree

### PR DESCRIPTION
**Pull request by baratali**
Part of #652

New option was added ``-j`` or ``--javadocTree``. Allows to print parse tree of the javadoc comment. Input file should contain only content of the javadoc comment (that is described in 'Command Line' web-page).
Example.
Input file:
```html
<p>
My {@code Class}
</p>
@see never
```
Output:
```
JAVADOC -> <p>\r\nMy {@code Class}\r\n</p>\r\n@see never<EOF> [0:0]
|--HTML_ELEMENT -> <p>\r\nMy {@code Class}\r\n</p> [0:0]
|   `--PARAGRAPH -> <p>\r\nMy {@code Class}\r\n</p> [0:0]
|       |--P_TAG_OPEN -> <p> [0:0]
|       |   |--OPEN -> < [0:0]
|       |   |--P_HTML_TAG_NAME -> p [0:1]
|       |   `--CLOSE -> > [0:2]
|       |--NEWLINE -> \r\n [0:3]
|       |--TEXT -> My  [1:0]
|       |   |--CHAR -> M [1:0]
|       |   |--CHAR -> y [1:1]
|       |   `--WS ->   [1:2]
|       |--JAVADOC_INLINE_TAG -> {@code Class} [1:3]
|       |   |--JAVADOC_INLINE_TAG_START -> { [1:3]
|       |   |--CODE_LITERAL -> @code [1:4]
|       |   |--WS ->   [1:9]
|       |   |--TEXT -> Class [1:10]
|       |   |   |--CHAR -> C [1:10]
|       |   |   |--CHAR -> l [1:11]
|       |   |   |--CHAR -> a [1:12]
|       |   |   |--CHAR -> s [1:13]
|       |   |   `--CHAR -> s [1:14]
|       |   `--JAVADOC_INLINE_TAG_END -> } [1:16]
|       |--NEWLINE -> \r\n [1:17]
|       `--P_TAG_CLOSE -> </p> [2:0]
|           |--OPEN -> < [2:0]
|           |--SLASH -> / [2:1]
|           |--P_HTML_TAG_NAME -> p [2:2]
|           `--CLOSE -> > [2:3]
|--NEWLINE -> \r\n [2:4]
|--JAVADOC_TAG -> @see never [3:0]
|   |--SEE_LITERAL -> @see [3:0]
|   |--WS ->   [3:4]
|   `--REFERENCE -> never [3:5]
|       `--PACKAGE -> never [3:5]
`--EOF -> <EOF> [3:10]
```

### CODE REVIEW

**Comment by romani** [comment]
@baratali , teamcity is red https://teamcity.jetbrains.com/viewLog.html?buildId=721558&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsPullRequest

**Comment by baratali** [comment]
I don't understand what is wrong:
TeamCity says:
```
DetailNodeTreeStringPrinter.java (1)
145: parseFile() Contents of collection text are queried, but never updated
```
Here is that method:
```java
    private static DetailNode parseFile(File file) throws IOException {
        final FileText text = new FileText(file.getAbsoluteFile(),
            System.getProperty("file.encoding", "UTF-8"));
        return parseJavadocAsDetailNode(text.getFullText().toString());
    }
```

Maybe it is false positive like this [stackoverflow-question](http://stackoverflow.com/questions/30458975/content-of-collection-never-updated-warning-in-intellij-idea), because [FileText extends AbstractList](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java#L57).

@romani, can you please have a look?

**Comment by romani** [comment]
1)
> can you please have a look?

valid point from TC, but we can not resolve it right now - https://github.com/checkstyle/checkstyle/issues/3034. All we can do for now is to do suppressions by javadoc tag `@noispection` with a reason description.

2)
> codecov failure

please rebase your code over our latest `master`. 

3)
>
```
 -            "3: " + getCheckMessage(MSG_KEY_UNRECOGNIZED_ANTLR_ERROR, 0, null),
+            "3: " + getCheckMessage(JavadocDetailNodeParser.MSG_KEY_UNRECOGNIZED_ANTLR_ERROR,
```

as we create ref-copy of string constant please use "MSG_KEY_UNRECOGNIZED_ANTLR_ERROR" instead of "JavadocDetailNodeParser.MSG_KEY_UNRECOGNIZED_ANTLR_ERROR"

4)
>
```
+          For example:
+          <source>
+          /**
+           * Test method.
```

please remove wrong example, you already described that `/**` should be removed from file.

**Comment by baratali** [comment]
1) In progress...
2) Done
3) Done
4) Done

**Comment by baratali** [comment]
@romani , looks like ``@noinspection`` annotation doesn't work. TeamCity fails with:
```
src/main/java/com/puppycrawl/tools/checkstyle
 DetailNodeTreeStringPrinter.java (1)
146: parseFile() Redundant suppression
```
See first commit: https://github.com/checkstyle/checkstyle/pull/3028/commits/25ddf6a78fa4288bd1cfbf9f2698a717364f18cc#diff-7edd2e2b29b3678fd99b85fb06514732R143

Singleline comment works and suppresses the warning (seconds commit passed TeamCity checks).
See second commit: https://github.com/checkstyle/checkstyle/pull/3028/commits/f14a4d91a8ea279b56bb162df05160d0c567ec8d

**Comment by romani** [comment]
Merged as FF

**Pull request closed without merging**
