### PR TITLE
Issue #1833: Fixed redundant modifier false positive for abstract classes in interfaces.

### PR DESCRIPTION
**Pull request by MEZk**
1) Fixed redundant modifier false positive for abstract classes in interfaces.
2) Extended javadoc/xdoc for classes inside of interfaces.
3) Extended javadoc/xdoc for enums.

### CODE REVIEW

**Comment by romani** [comment]
please rebase and generate reports to ensure no regression (identical reports)

**Comment by romani** [comment]
1) 
> Checks for non public class constructor and enum constructor redundant modifier.

please update first sentence to include brief description of all that Check do. Please beware that first sentence is special sentence as it is detached from whole javadoc and  placed in summary pages of javadoc. In our case we also do summary even at xdoc http://checkstyle.sourceforge.net/checks.html . That page also need to be updated.

2)
> Variables in interfaces 

please that terminology with link to JDK , I think it shoul be named as "field"

3)
>```    public class ClassWithProtectedInnerClass {
        protected class ProtectedClass {
```

please swap name, as Inner should be inside, example below is also need to be updated.

4)
> For non-public protected classes public modifier is not obsolete,

please rephrase that protected class can not have public modifier

**Comment by romani** [comment]
5) this Check does not have any options , can you put "//violation" comment to lines in Inputs where violation is expected to be precise.

**Comment by MEZk** [comment]
@romani 
1) Done
2) You are right, *fields*. See [9.1.4. Interface Body and Member Declarations ] (https://docs.oracle.com/javase/specs/jls/se7/html/jls-9.html)
3) Done
4) Done
5) Done

REPORTS: http://mezk.github.io

**Comment by romani** [comment]
>protected class can not have public modifier

That is true, inly one modifier is allowed

**Comment by MEZk** [comment]
@romani 
>update a comment
Done

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
