### PR TITLE
fix JavadocParagraph allows new line before the next paragraph, #1332

### PR DESCRIPTION
**Pull request by Vladlis**
[reports](http://vladlis.github.io/) show that the number of violations in guava, openjdk7, hibernate-orm and spring framework is not less, than it was before changes

### CODE REVIEW

**Comment by romani** [comment]
please confirm that all 48 additional violations on Guava are valid

**Comment by Vladlis** [comment]
1) Confirmed.
2) Actually, openjdk9 has even greater amount of violations - over 17900
Here are numbers for some other projects:
> <b>name: new violations - checked files</b>
sevntu-checkstyle:        26 - 291
checkstyle:                    170 - 1111
lombok-ast:                   8 - 91
pmd:                              32 - 1106
elasticsearch:                47 - 4135
java-design-patterns:    0 - 238
MaterialDesignLibrary: 13 - 30
RxJava:                        708 - 409
apache-ant:                  228 - 861
android-launcher:         0 - 39
guava:                          48 - 1691
openjdk7:                     15852 - 13652
openjdk9:                     17900 - 
hibernate-orm:             24 - 6271
spring-framework:        61 - 5911

It can be seen that google's style is observed in the majority of checked projects (all except from openjdk and RxJava), so it makes sense, to make a new boolean option, which says whether to check that if paragraph tag is immediately followed by text or not and this option should have default value <b>false</b>

**Comment by romani** [comment]
If most of project follow Google's notation, validation for P need to be activated by default, so value is true. Did you make a typo ?

**Comment by Vladlis** [comment]
@romani, yes
new option allowNewlineParagraph says whether to <b>allow</b> to place paragraph tag not immediately before the text. That is why it is <b>false</b> by default.

**Comment by romani** [comment]
ok, by by default that option should be switched ON, thanks a lot for investigation.

lets back to implementation:

1) Please add information about new option to javadoc and please extend javadoc/xdoc with examples of usage and bad&good code samples.

2) Add yourself to authors of Check

3) 
> isImmediatelyFollowedByText

please remove IF and directly return result.

4)
> allows to place text of a paragraph not immediately after a P tag

pay attention that you use "not" to describe smth, that is root of the naming problem. What about "tagImmediatelyBeforeFirstWord" name of option ?  ... and you will not need "not" any more.

**Comment by Vladlis** [comment]
1) Done
2) Done
3) Done
4) Fixed, now the new option is called <code>tagImmediatelyBeforeFirstWord</code> and its default value is <code>true</code>

**Comment by romani** [comment]
please fix Travis problems.

**Comment by romani** [comment]
appveyor is passing for master, please recommit smth in branch to re-trigger CIs builds. From this moment I expect all CIs to be green.

**Comment by Vladlis** [comment]
Fixed

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
