### PR TITLE
Issue #3187: aligned setters with String collection fields and broke old compatibility

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3187 

basically changed only:
`````
void set(String s) {
    field = s.split(",");
}
````
into:
````
void set(String... s) {
    field = s;
}
````

### CODE REVIEW

**Comment by rnveach** [comment]
@romani 
It looks like travis failure with XWiki is showing an issue with how `IllegalInstantiation`'s setter isn't working as users thought.

Travis Error:
https://travis-ci.org/checkstyle/checkstyle/jobs/130923497#L7360
> [ERROR] /home/travis/build/checkstyle/checkstyle/xwiki-commons/xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/Sax2Dom.java:152:33: Instantiation of java.lang.String should be avoided. [IllegalInstantiation]

Configuration:
https://github.com/xwiki/xwiki-commons/blob/02f7260a982f8e19fcccaafa3fd4261220ffe079/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/checkstyle.xml#L165-L167
>     <module name="IllegalInstantiation">
      <property name="classes" value="java.lang.Boolean, java.lang.String"/>

Code:
https://github.com/xwiki/xwiki-commons/blob/c6ec6b4559977667e020090313580dd037f654fa/xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/Sax2Dom.java#L152
> final String text = new String(ch, start, length);

Issue is the space after the comma. We aren't taking it out so instead of looking for `java.lang.String` we were incorrectly looking for `<space>java.lang.String`.
Our unit tests don't have this scenario, hence why it went unnoticed.

**Comment by romani** [comment]
good catch.

but right now we use xwiki code directly from their github.
Two options to resolve build failure:
1) contact xwiki and report problems to them to let them fix them now instead of during future upgrade to new version
2) make a fork of their project and switch our Travis to our fork, our fork need to be updated to avoid violations.

**Comment by rnveach** [comment]
PR in XWiki created, waiting for their response.

**Comment by rnveach** [comment]
PR was merged, rebased to see if travis would pass.

@romani I believe XWiki will still fail.
Change was introduced into `master`, but we are validating against [release `xwiki-commons-8.0-milestone-1`](https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L100).

**Comment by romani** [comment]
@rnveach , lets update our contibutions project to reference to commit hash where such fix is merged.
it will let CI pass.

**Comment by rnveach** [comment]
@romani Done.

**Comment by romani** [comment]
@rnveach , I am ready to merge.

please change commits prefix from `Issue #3187:` to `Pull #3189` as current fixes are not about UT fixes - they are braking compatibility (as all plugins might need to update their metadata). We need to update Pull topic to be descriptive about a change, Pull description need to state braking changes.

**Comment by romani** [comment]
merged as FF

**Comment by rnveach** [comment]
Done.

**Comment by tsjensen** [comment]
Can you please explain how this PR breaks backward compatibility?
From what I can see, the change only fixes the space-around-separator problem, so any previously valid configuration files should continue to work, shouldn't they?

**Comment by romani** [comment]
yes, xml configuration should work as it was. 
Behavior is changed. 
Signature of Check's public methods is changed - this kind of breaking compatibility for some tools.
So I decided to mark it like this just in case.

**Pull request closed without merging**
