### PR TITLE
SwingConstants is an interface, not a class.

### PR DESCRIPTION
**Pull request by tweimer**
See above.

### CODE REVIEW

**Comment by romani** [comment]
Commit message format is not Ok, prefix is missed.

Contribution was done from web, we need to find a reason why user skip to read instructions on commit message.

**Comment by tweimer** [comment]
@romani  Sorry, I should have read the instructions **before** actually comitting it.  I couldn't change it afterwards. Do you want me to make a new PR?

**Comment by rnveach** [comment]
@tweimer Just amend your previous commit and force push the changes to the server.
Github will recognize the changes and act accordingly.

**Comment by romani** [comment]
unfortunately github does not allow to change commit message, so during contributions from WEB, user need to read PR template before submitting changes to PR. So if user read it it can do "Back" and put message in better form. The only drawback is there will be two branches on client fork side, but this is minor.

@tweimer , can you be honest with us and share why you did this ? I try to understand what we need to change in template to force user to read it.

**Comment by romani** [comment]
commit message was redone, merged manually.

**Comment by tweimer** [comment]
@romani Like I said, I edited the file and entered the commit message before I have read the template. There is no hint about that when you edit a file through the web site.

I have read the guidelines after having edited the file, I should have done it before, I admit. My fault, sorry.

**Comment by romani** [comment]
It is natural that you try to edit/contribute smth before you read all rules.
but after you did change and put a git commit message, github get you to PR page where rules are in description of PR (some idea that user will read this text). If read it, you could press "Back" in browser to redo commit message ... but you removed PR template text and make a PR.

You are not alone with such behavior, almost nobody did it right, so I try to understand what could we improve to avoid such bad experience.

**Comment by tweimer** [comment]
Yes, I guess I should have deleted that fork and redo it.

**Pull request closed without merging**
