### PR TITLE
Issue #4727: fixed FinalLocalVariable scanning anonymous classes

### PR DESCRIPTION
**Pull request by rnveach**
Issue #4727

Regression to come.

### CODE REVIEW

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/83/

> [ERROR] src/main/java/org/orekit/models/earth/EarthITU453AtmosphereRefraction.java:[97,28] (coding) FinalLocalVariable: Variable 'refrac' should be declared final.

https://github.com/CS-SI/Orekit/blob/f5748aa8809cdfb0e96b090875c7e689abe12705/src/main/java/org/orekit/models/earth/EarthITU453AtmosphereRefraction.java#L97
Orekit's failure needs a PR to fix.

**Comment by romani** [comment]
> Orekit's failure needs a PR to fix.
Sevntu probably will need a fix too.

do you plan to do this ?

**Comment by rnveach** [comment]
@romani I was waiting to see how we handle wercker in breaking backward compatibility PRs.
https://github.com/checkstyle/checkstyle/pull/4767
https://github.com/checkstyle/checkstyle/pull/4755

If we plan to disable most/all of wercker, I can probably get this PR by without having to make some or all PRs to 3rd party repositories.
If wercker stays enabled, I will make the needed PRs.

**Comment by romani** [comment]
> If wercker stays enabled, I will make the needed PRs to make CI green.

wercker will stay enabled, as we will use config file substitution(patch or override) approach.
Please proceed with PRs to projects. In worse scenario wercker could be disabled for VERY small period of time.

**Comment by rnveach** [comment]
PRs were created in current regression failures, but I cannot see future ones without wercker continuing on or doing it manually.
@romani Is there no way we can change wercker to fail after everything has run?

**Comment by rnveach** [comment]
2 PRs were merged but Orekit still fails because it uses a specific commit. I will make the update.

**Comment by rnveach** [comment]
HtmlUnit now failed.

**Comment by romani** [comment]
> @romani Is there no way we can change wercker to fail after everything has run?

yes, just change wercker commands to not return non zero exit code. The most easy way is to pipe with "cat": "mvn ...... | cat"

**Comment by romani** [comment]
@rnveach , please rebase, there is a conflict.

**Comment by rnveach** [comment]
Rebased. I will continue with PRs.

**Comment by rnveach** [comment]
Patch for HtmlUnit was created at https://sourceforge.net/p/htmlunit/bugs/1906/ .

**Comment by rbri** [comment]
Patch is applied to the HtmlUnit code. Thanks

**Comment by rnveach** [comment]
@romani wercker and CI are now passing.

**Comment by rnveach** [comment]
Rebased on latest master for changes in test support.

**Pull request merged**
