### PR TITLE
Issue #5604: activation of sonar validation in PRs

### PR DESCRIPTION
**Pull request by romani**
small step for #5604 
it does not integrate Sonar to PR status in githubl, but should show statistics on sonarqube.io , I will investigate further how to make complete integration.

### CODE REVIEW

**Comment by romani** [comment]
Secret variables are not accessible in PR at all https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings .

So we have to put sonar to CI that doesn't not show logs to other users.

**Comment by romani** [comment]
example of Gate  failure when some new violation is introduced:
image
but it does not fail a maven build.

**Comment by romani** [comment]
@rnveach and @pbludov , please review.
I am not sure how reliable it will be .... but we can always disable it when required.

**Comment by rnveach** [comment]
CI is failing.

**Comment by rnveach** [comment]
> CI failures are expected, please review wercker only.

wercker failed.

**Comment by romani** [comment]
Second commit is for demo, failed by design.

**Comment by romani** [comment]
second commit was removed, ones CI pass, this PR could be merged.

**Pull request merged**
