### PR TITLE
Issue #4586: Moved resources for JavadocType check test

### PR DESCRIPTION
**Pull request by djydewang**
Issue #4586: Something wrong with InputJavadoc.java when I move it to subdirectory.
1.Copied&Renamed `InputInner.java,InputJavadoc.java,InputNoJavadoc.java,InputPublicOnly.java,InputTags.java,InputParamsTags.java` to the javadoctype subdirectory.Because they were used by the other check tests.

2.Moved&Renamed the remianing resources for JavadocTypeCheckTest to the javadocstyle subdirectory.

### CODE REVIEW

**Comment by romani** [comment]
from Travis:
```
[checkstyle] [ERROR] /home/travis/build/checkstyle/checkstyle/src/test/java/com/
puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java:132:9: 
File contains tab characters (this is the first instance). [FileTabCharacter]
```

**Comment by djydewang** [comment]
Because it was wrong every time when I moved `InputJavadoc.java` to subdirectory not only for JavadocTypeCheckTest.And there is no error message that you mentioned but just some error with `ant-phase-verify.xml `when I run `mvn verify` at local.So I want to get more information about it by PR checks.
Now I pass `mvn verify`.Thanks for your help.

**Comment by rnveach** [comment]
> > [checkstyle] [ERROR] /home/travis/build/checkstyle/checkstyle/src/test/java/com/
puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java:132:9: 
File contains tab characters (this is the first instance). [FileTabCharacter]

> What is a problem with InputJavadoc.java ?

Inputs should not be located in `java` folder. They should be in resources.

**Comment by djydewang** [comment]
Yes,I am sure they are in `resources` floder.

**Pull request merged**
