### PR TITLE
Add tests for equals and toString in SuppressionCommentFilter. #1088

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
travis:

[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.filters.SuppressionCommentFilter:296 Rule:UnusedPrivateField Priority:3 Avoid unused private fields such as 'checkRegexp'..

[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.filters.SuppressionCommentFilter:296 Rule:SingularField Priority:3 Perhaps 'checkRegexp' could be replaced by a local variable.

**Comment by mkordas** [comment]
Fixed. We should have 94% coverage after merging this.

**Comment by romani** [comment]
As you improve a coverage, please update pom.xml to prove that .

**Comment by mkordas** [comment]
Done

**Comment by romani** [comment]
> 
```
else {
   tagMessageRegexp = null;
}
```

will it be better to make "tagMessageRegexp = null;" before that IF to avoid IF_ELSE at all? 

It will be easier to read to my mind (I am always afraid of code that set NULL by condition to particular variable/field ) and no performance hit at all.

**Comment by mkordas** [comment]
> will it be better to make "tagMessageRegexp = null;" before that IF to avoid IF_ELSE at all?

Not possible, as final field can be assigned only once

After additional thinking, I've decided to mark `tagCheckRegexp` and `tagMessageRegexp` as `transient` as they are fully derived during object construction. 

Moreover, `Pattern` is not equal to other `Pattern` with the same regexp, so putting them to `equals` and `hashCode` didn't make sense. Please see https://stackoverflow.com/questions/10055034/java-comparing-two-pattern-objects

**Comment by romani** [comment]
thanks for removing code :) .

merged as FF

**Pull request closed without merging**
