### PR TITLE
Issue #7301: fix source display for firefox

### PR DESCRIPTION
**Pull request by jo2**
Issue #7301:
* Fix source display in firefox

how it was before:
image
according to @rnveach there should be some space between the text of the code snippet and its border. This already works in chrome (merged in https://github.com/checkstyle/checkstyle/pull/7302) and this pr fixes that for firefox.

image

### CODE REVIEW

**Comment by rnveach** [comment]
> Fix source display in chrome

Is this the firefox fix or is that still coming?

**Comment by jo2** [comment]
yeah, it is. Sorry i got that confused.

**Comment by romani** [comment]
@jo2 , as you reference already closed issue ...
Please describe what problem do you address in issue, probably picture of problem is the best approach,  .... and second picture of how it become.

PR title is for "chrome", PR description is about "firefox", commit is about "chrome"

**Comment by rnveach** [comment]
Issue stemmed from conversation in https://github.com/checkstyle/checkstyle/pull/7302#discussion_r353460191 . Specific problem was identified at https://github.com/checkstyle/checkstyle/pull/7302#discussion_r354423542 .

**Comment by romani** [comment]
But last comment in such review thread state that I
problem was resolved. I am confused

**Comment by rnveach** [comment]
@romani problem was resolved after you had merged the PR. See timestamps.

**Comment by romani** [comment]
Ok, let's share details of what is a problem in issue one more time as summary (with pictures). I will test on my side.

**Comment by jo2** [comment]
updated description. I also found an image stil not working. fixed it in new commit

**Comment by romani** [comment]
@jo2 , please fix commit message, it is the first what engineers we when asking "WHY this line was changed?" it should not be misleading

**Comment by jo2** [comment]
will update commit message and squash commits

**Comment by romani** [comment]
I split changed back to two commits, as they are not related, and I want to keep this padding change separate, I think it will be questioned in future several times.

padding works fine on my FF.

**Comment by rnveach** [comment]
Can be merged when CI is done.

**Pull request merged**
