### PR TITLE
 Issue #13877: SpotBugs checks a map with containsKey(), before using…

### PR DESCRIPTION
**Pull request by AayushSaini101**
Related: https://github.com/checkstyle/checkstyle/issues/13877

Originally posted as https://github.com/checkstyle/checkstyle/pull/13890

### CODE REVIEW

**Comment by romani** [comment]
@rnveach , please accept this PR without CI.
I will create copy of this PR to recheck all green CI, but I will do this if you agree with such update

**Comment by nrmancuso** [comment]
Why/how did @TanayMorakhia author this commit, but it is sent by @AayushSaini101? @AayushSaini101 help is to understand your workflow that produces such commits. I don’t think you will get credit as the author of this work.

**Comment by AayushSaini101** [comment]
> Why/how did @TanayMorakhia author this commit, but it is sent by @AayushSaini101? @AayushSaini101 help us to understand your workflow that produces such commits. I don’t think you will get credit as the author of this work; when we merge this PR, whoever merges it will become the committer.

Actually I deleted my old fork because some of ci are not passing due to some issue in CI . After creating new fork I pushed pr by rebasing old commits that might be the reason. Sorry I will create new PR @romani

**Comment by AayushSaini101** [comment]
> > Why/how did @TanayMorakhia author this commit, but it is sent by @AayushSaini101? @AayushSaini101 help us to understand your workflow that produces such commits. I don’t think you will get credit as the author of this work; when we merge this PR, whoever merges it will become the committer.
> 
> Actually I deleted my old fork because some of ci are not passing due to some issue in CI . After creating new fork I pushed pr by rebasing old commits that might be the reason. Sorry I will create new PR

@romani @nrmancuso Closing this PR

**Pull request closed without merging**
