### PR TITLE
Issue #11286: EmptyLineSeparator can now also check empty lines after block start and before block end

### LINKED ISSUE #11286: EmptyLineSeparator does not catch missing line separator before field declaration
The documentation of EmptyLineSeparator says "Checks for empty line separators before package, all import declarations, **fields**, constructors, methods, nested classes, static initializers and instance initializers."
In particular, it doesn't work for fields, see example below.
Since a field is also known as an instance variable, I expect the VARIABLE_DEF to catch it, but it doesn't.

I have read check documentation: https://checkstyle.sourceforge.io/config_whitespace.html#EmptyLineSeparator
https://checkstyle.sourceforge.io/checks/whitespace/emptylineseparator.html#EmptyLineSeparator
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
peter@pangolin:~/Downloads/checkstyle$ javac Test.java 

peter@pangolin:~/Downloads/checkstyle$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
	"-//Puppy Crawl//DTD Check Configuration 1.3//EN"
	"http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
<module name="Checker">
	<module name="TreeWalker">
		<module name="EmptyLineSeparator"/>
	</module>
</module>

peter@pangolin:~/Downloads/checkstyle$ cat Test.java 
class Test {
	int i = 0; // Checkstyle doesn't catch missing line break before this line. Should be caught by VARIABLE_DEF?
	Test() { // Checkstyle DOES catch missing line break before this line. Caught by CTOR_DEF.
	}
}

peter@pangolin:~/Downloads/checkstyle$ RUN_LOCALE="-Duser.language=en -Duser.country=US"

peter@pangolin:~/Downloads/checkstyle$ java $RUN_LOCALE -jar checkstyle-9.3-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/peter/Downloads/checkstyle/Test.java:3:9: 'CTOR_DEF' should be separated from previous line. [EmptyLineSeparator]
Audit done.
Checkstyle ends with 1 errors.
```

---
**Expected: Checkstyle reports 2 violations, one for CTOR_DEF and one for VARIABLE_DEF.**
**Actual: Checkstyle reports 1 violation, for CTOR_DEF.**
---

To give an idea of the code style I want to enforce:

```java
class AlwaysNewlineAfterClassDeclaration {

    int field = 0; // Newline before is required.
}

class AlsoInAnymousInnerClasses {

    Supplier<String> supplier = new Supplier<>() {

        public String get() { // Newline before is required.
        }
    }
} // Newline before is prohibited.

class UnlessEmpty {
} // Newline before is prohibited.
```

So I want to be able to configure the following violations:

```java
class AlwaysNewlineAfterClassDeclaration {
    int field = 0; // Violation.
}

class AlsoInAnymousInnerClasses {

    Supplier<String> supplier = new Supplier<>() {
        public String get() { // Violation.
        }
    }

} // Violation, out of scope of this issue.

class UnlessEmpty {

} // Violation, out of scope of this issue.
```

### PR DESCRIPTION
**Pull request by peterdemaeyer**
Closes #11286: EmptyLineSeparator can now also check empty lines after block start and before block end.

To enable checking of empty line separator also after block start (left curly):
* Added property `requireEmptyLineAfterBlockStart`. The default is `false` for backward compatibility.

to enable checking of _no_ empty line separator before block end (right curly):
* Added allowed token `RCURLY` to allow also checking before this token. This is _not_ included in the default for backward compatibility.
* Added property `allowNoEmptyLineBeforeBlockEnd`. The default is `false` for backward compatibility. This requires the above `RCURLY` to be included in tokens to work.
* Added message "no.empty.line.separator" for these violations of empty lines before block end that should not be there. EN, DE, FR, ES translations done.

Known issues:
* FI, JA, PT, TR, ZH translations for the new message are TODO, which makes the build fail. I'll need some help translating those. I can use Google Translate, but even that will be very challenging for languages such as JA.
* JaCoCo fails with 96 % coverage, apparently I am missing some branches, but I don't know which ones. When I run `EmptyLineSeparatorCheckTest` in IntelliJ, it shows me 100 % class/method/line coverage, so I don't know which branches I am missing... I can figure this out for myself if I spend some time investigating, but if someone could point me in the right direction that would help.

### CODE REVIEW

**Comment by romani** [comment]
Before we proceed with polishing, we need to agree on design and make issue "approved"

**Comment by romani** [comment]
Second commit violate rules, please fix it, to let our CI be green.

**Comment by peterdemaeyer** [comment]
I'm trying to address the CI failures, but it's hard for me to identify what the problem is.
My local build  `mvn clean verify` is green with OpenJDK Java 11 and 17 on Ubuntu Linux, which means I can't reproduce the failures locally.
For example, when I look at **Travis CI - Pull Request** [failure](https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/566540204), it fails with 17 Checkstyle failures which I am not getting locally and which are in classes that I did not touch.

**Comment by romani** [comment]
Travis is fixed, it was leak from latest commit in master.

**Comment by rnveach** [comment]
@peterdemaeyer Do you plan to finish this PR?

**Comment by peterdemaeyer** [comment]
Trying to breathe some life back into my branch, I rebased it once more. `mvn clean verify` is green on my system, but there are 5 checks failing in the CI/CD pipeline. One of them is a test failure of one of my new tests - I can investigate that. For some of the other failures I have less of a clue. For example there is a timeout on MacOS JDK11. And then some whitespace (mutation?) tests result in an obscure "Error: Process completed with exit code 1."

**Comment by romani** [comment]
Recheck test failure https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/45365072/job/y2gbvfo7ycvxl5lh#L812
All others should be resolved also, timeout we can restart

**Comment by peterdemaeyer** [comment]
The failing test only happens on Cirrus CI, which runs on Windows. The error is about a resource which is not found:

```
[ERROR] Tests run: 51, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.547 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheckTest
[ERROR] testEmptyLineSeparatorBeforeClassDef  Time elapsed: 0.015 s  <<< ERROR!
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Failed to read C:\projects\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\whitespace\emptylineseparator\InputEmptyLineSeparatorDefaultPackageEmptyLineBeforeClassDef.java
	at com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheckTest.testEmptyLineSeparatorBeforeClassDef(EmptyLineSeparatorCheckTest.java:143)
Caused by: java.nio.file.NoSuchFileException: C:\projects\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\whitespace\emptylineseparator\InputEmptyLineSeparatorDefaultPackageEmptyLineBeforeClassDef.java
	at com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheckTest.testEmptyLineSeparatorBeforeClassDef(EmptyLineSeparatorCheckTest.java:143)
```

Indeed, the path is wrong. This particular resource is in the _default_ package, because it explicitly checks a compiling Java file without "package" declaration. In virtually all other cases, resources are in the same resource package as the test itself. This is thus an exception. On my Linux desktop, this works, but on this particular Cirrus CI, it seems the test framework stubbornly looks for the resource in the wrong directory.

**Comment by rnveach** [comment]
Discussion ongoing since issue isn't approved

**Comment by romani** [comment]
Sorry I do not see future of this PR, alternative proposal is at https://github.com/checkstyle/checkstyle/issues/11286#issuecomment-1831170887

**Pull request closed without merging**
