### PR TITLE
Sonar violation: Catch Exception instead of Throwable.

### PR DESCRIPTION
**Pull request by damianszczepanik**
Pull #825

### CODE REVIEW

**Comment by damianszczepanik** [comment]
I've fixed one Sonar violation but also reduced duplicated code by providing one utility method and passing the same message to LocalizedMessage for all cases.

**Comment by damianszczepanik** [comment]
Nice results: pass, pass, failed...

**Comment by romani** [comment]
I do not agree with Sonar on that violation http://roman-ivanov.blogspot.com/2015/03/catch-exception-or-catch-throwable-when.html

refactoring for moving LocalizedMessage creation to method is correct.

**Comment by damianszczepanik** [comment]
Interesting point of view, really! There are also two more aspects as a outcome from your example:
1. Based on official Sun/Oracle guideline you should not catch such cases and let the application die http://docs.oracle.com/javase/7/docs/api/java/lang/Error.html however I understand that this is not what you would like to release on production
2. If you don't expose such error you won't be informed by end-user about such cases so if this is checkstyle error (not 3rd party) that would be nice to know and fix.

So before we start to talk about it let me publish new PR :)

Can you configure Sonar rules to make sure we have the correct report, one you approved?

**Comment by damianszczepanik** [comment]
Looks like jdk8 does not like my PRs!

**Comment by romani** [comment]
From travis:
com.puppycrawl.tools.checkstyle.TreeWalker failed check. Line coverage rate of 90.6% is below 91.0%

**Comment by romani** [comment]
> catch (Error | Exception ex) 

Why not a Throwable ? It is way to avoid Sonar violation ? I do believe it will complain about catching Error.

**Comment by damianszczepanik** [comment]
Based on [this information](https://dev.lds.org/sonar/rules/show/squid:S1181?layout=false) you are right. I've compared old rules on local Sonar list and it did not complain about Error.

I've removed additional duplicated code.

**Comment by mkordas** [comment]
Please rebase on latest code

**Comment by romani** [comment]
> ParseTreeInfoPanel.java

that update is not the same, please change a message or keep catches as separate

=====================
TreeWalker.java


> - catch (final RecognitionException re) {

I do not understand why you removed that catch, it is not the same as TokenStreamRecognitionException
http://www.antlr2.org/javadoc/antlr/ANTLRException.html , please explain why "TokenStreamException" is missed too.

**Comment by damianszczepanik** [comment]
1. Message of this exception is not validated by test so it will be useful for human who can read the full reason based on exception type, cause exception and message. For that reason I believe it does not make sense to keep the same code twice. I changed message to more generic so details will be available by getMessage() method

2. I've merged this with Throwable. I updated `catch (Throwable)` to be more generic so the `RecognitionException` is useless now. I left comment so if you find out why we need to catch 'any' exception this would be helpful

**Comment by romani** [comment]
merged as FF, thanks a lot!

please try to make changes smaller on uncertain code, it will ease acceptance process.

**Pull request closed without merging**
