### PR TITLE
Update macos image

### PR DESCRIPTION
**Pull request by nrmancuso**
Noticed at https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=11277&view=results, azure is retiring 10.5 images and having rolling brownouts now.

### CODE REVIEW

**Comment by nrmancuso** [comment]
> Several CI failures

Looks like failure to download artifact, rebased

**Review by romani — APPROVED** [review]
Ok to merge If ci is green

**Review by rnveach — CHANGES_REQUESTED** [review]
Missed
https://github.com/checkstyle/checkstyle/blob/0c71a28b27ceae71c0879dfd99b72c2da02f218f/azure-pipelines.yml#L114
markdownlint

**Comment by romani** [comment]
Ok, looks like all other PRs are blocked by this, whoever is close to keyboard please push update to markdown job in azure.

**Comment by nrmancuso** [comment]
@romani done

**Review by romani — APPROVED** [review]

**Review by rnveach — APPROVED** [review]
when CI passes

**Pull request merged**
