### PR TITLE
Split and Organize Checkstyle inputs by Test for NoWhitespaceAfter #3931

### PR DESCRIPTION
**Pull request by bansalayush**
Modified NoWhiteapceAfterCheckTest.java and moved its test files to subdir

### CODE REVIEW

**Comment by rnveach** [comment]
@bansalayush CI will help you solve your problems.
First you have compile problems.
> [ERROR] /home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputNoWhitespaceAfterArrayDeclarations.java:[3,8] duplicate class: com.puppycrawl.tools.checkstyle.checks.whitespace.InputNoWhitespaceAfterArrayDeclarations
[ERROR] /home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterMethodRef.java:[7,8] duplicate class: com.puppycrawl.tools.checkstyle.checks.whitespace.InputNoWhitespaceAfterMethodRef
[ERROR] /home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarations2.java:[7,8] duplicate class: com.puppycrawl.tools.checkstyle.checks.whitespace.InputNoWhitespaceAfterArrayDeclarations2
[ERROR] /home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterSynchronized.java:[3,1] duplicate class: com.puppycrawl.tools.checkstyle.checks.whitespace.InputNoWhitespaceAfterSynchronized
[ERROR] /home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhiteSpaceAfterFormerNpe.java:[3,8] duplicate class: com.puppycrawl.tools.checkstyle.checks.whitespace.InputNoWhiteSpaceAfterFormerNpe

They probably stem from the fact that if you look at your changes, https://github.com/checkstyle/checkstyle/pull/3971/files , in the test you named files `InputNoWhitespaceAfter`, but none of the new files you added are named that. They should be a 1 to 1, any file in test you rename should appear as a move/copy to it's new location.

When you have that fixed, please rebase off the latest master and squash all commits to 1 and keep them at 1.

**Comment by rnveach** [comment]
@bansalayush As you are fixing CI, please squash all commits to 1 and rebase off the latest master.

**Comment by rnveach** [comment]
@bansalayush ping

**Comment by rnveach** [comment]
@bansalayush ping
Since we are out of proposal deadline, do you think you can finish this?

**Comment by rnveach** [comment]
@bansalayush If there is no activity by May 1st, PR will be closed as incomplete and issue will be open to others.

**Comment by romani** [comment]
PRs is closed as we lost connection with student, any contributor could continue this work to make it done.

**Pull request closed without merging**
