### PR TITLE
minor: changed the input file path in test file

### PR DESCRIPTION
**Pull request by Kevin222004**
Found at  #11446

### CODE REVIEW

**Comment by Kevin222004** [comment]
@Vyom-Yadav sorry for the delay

**Comment by romani** [comment]
I do not understand, how it use to work, such mistake usually results in test failure

**Comment by rnveach** [comment]
@romani Looking at exception message expected, it is processing a failure on the configuration given before even the file is processed. See `Cannot set property 'groups' to '/^javax'`. This test does not use BDD, so its not getting it's configuration from the input file, but from the java code.

If anything, this shows the input file is not even needed and could be swapped with just random text like "notaRealFile" to make it clear.

**Comment by romani** [comment]
@Kevin222004, if this file is used only by one test method, please keep file but make it's class to be empty.

**Comment by Kevin222004** [comment]
> @Kevin222004, if this file is used only by one test method, please keep file but make it's class to be empty.

The class is already an empty class 

> 
> https://github.com/checkstyle/checkstyle/blob/master/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder5.java
> 
> Should be no header comment, no imports.

if I remove imports and header comment it shows the error 
[ERROR] [checkstyle] [ERROR] /home/kevin/Desktop/C_Style/checkstyle/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder5.java:0: All check input files in the 'src/(it|test)/resources*/' folder must                    have trailing comments "// ok" and/or "// violation". [StyleValidationCommentInInputs]

**Comment by romani** [comment]
Put on line with class "// ok" to bypass this violation

**Review by romani — APPROVED** [review]

**Pull request merged**
