### PR TITLE
Utils classes have been moved to utils package

### PR DESCRIPTION
**Pull request by sabaka**

### CODE REVIEW

**Comment by mkordas** [comment]
@sabaka - I believe we should create issue for that with some context and reason for change. BTW this change will introduce IDEA Inspection violation for class like `com.puppycrawl.tools.checkstyle.utils.Utils`:
>**ClassNamePrefixedWithPackageName**
Reports classes whose names are prefixed with their package names, irrespective of capitalization. While occasionally reasonable, this is often due to a poor naming scheme, and may be redundant and annoying.

**Comment by romani** [comment]
1) commit always has to have ref to issue
issue need to be create or description of PullRequest extended and link to PR is provided in commit message

2) 
> ClassNamePrefixedWithPackageName

correct violation, should be fixed, it could be done in separate commit of the same PR

**Comment by sabaka** [comment]
It contains methods for too different purposes to rename it in something meaningful. I propose create issue and split this file to different files with different purposes and do review of others utils and classes which can contain utils methods.

**Comment by romani** [comment]
1) please rebase.
2) please provide description of udpate in issue, to share with other motivation (link to original issue, DSM, dependency, strange dependency, more clear dependency , dependency to stateless code)
3) we need to move and split Utils.java  in the same PR , to not bother users with multiple changes in out Utils. So I propose to split Utils.java into two files TokenUtils.java (TOKEN_VALUE_TO_NAME; TOKEN_IDS; and related ) and  CommonUtils.java (all other methods) . @mkordas , please share your opinion on new file names .

**Comment by mkordas** [comment]
@romani - your proposition of names is really good

**Comment by sabaka** [comment]
rebased
splitted

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
