### PR TITLE
Issue #11140: solve PSC_PRESIZE_COLLECTIONS

### PR DESCRIPTION
**Pull request by pbludov**
Part of #11140

Usually the number of elements is known already. It makes sense to create an array/list of the right size in advance.
But sometimes (for recursive code) it will be problematic. Two such cases are suppressed.

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
@pbludov , please fix conflict

**Comment by romani** [comment]
Pitest design is not happy

**Comment by pbludov** [comment]
> 

The problematic line is
```java
        final List<String> typeClassNames = new ArrayList<>(typeArgs.getChildCount() / 2);
```
The violation line: `2. Replaced integer division with multiplication → SURVIVED`
It's true: the test will be successful at any capacity of the list.

**Review by romani — APPROVED** [review]

**Review by strkkk — APPROVED** [review]

**Pull request merged**
