### PR TITLE
Issue #2666: Print name of the Check after printing violation message 

### PR DESCRIPTION
**Pull request by MEZk**
New message looks like:

```
Starting audit...
[WARNING] /media/andreiselkin/TOURO/IDEA_Projects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/InputMain.java:3:14: Name 'InputMain' must match pattern '^[a-z0-9]*$'. [TypeName]
[WARNING] /media/andreiselkin/TOURO/IDEA_Projects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/InputMain.java:5:7: Name 'InputMainInner' must match pattern '^[a-z0-9]*$'. [TypeName]
Audit done.
```

### CODE REVIEW

**Comment by romani** [comment]
1)
> private static final int BUFFER_CUSHION = 12;

if we presume that there will be extension of BriefLogger , we need to make it protected.
Why 12 ? 

2)
> protected String formErrorMessage(AuditEvent event, SeverityLevel severityLevel

for each implementation, please put in javadoc format of generated message

3)
> protected static class BriefLogger extends DefaultLogger {
class BriefLogger extends DefaultLogger {

I might miss smth but these classes are equal. We need to reuse implementation.

4)
>```         final int bufLen = fileName.length() + message.length()
            + BUFFER_CUSHION;
        final StringBuilder sb = new StringBuilder(bufLen);
```

I do not like such calculations, bufLen should be a bit bigger then result message. why 12  is cusion? please put this as comment to code.

5)
> ```
     BriefLogger(OutputStream out) {
         super(out, true, out, false, false);
     }
```

if we override message format, why we need to specify 5th argument to parent class? smth is broken now in design....

**Comment by MEZk** [comment]
1) BriefLogger extends DefaultLogger and uses both BUFFER_CUSHION and printSeverity in formErrorMessage that is why I have made the variables protected. 

2) Done.

3) Done.

4) I don't know why we use just 12 for BUFFER_CUSHION in DefaultLogger. Maybe 12 is an priori value. I don't think that BUFFER_CUSHION is useful in this situation. fileName.length() + message.length() should be enough. 

5) Removed that constructor. We still need printSeverity as a constructor parameter in BriefLogger because testTagPrintSeverityTrue in WriteTagCheckTest uses this parameter. See https://github.com/checkstyle/checkstyle/blob/75da2ef6ac77766baac7016606457dc1f7bbfd7b/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java#L89

**Comment by romani** [comment]
Usage of protected fields is evil, please make it private and put it as argument to formatMessage method.

**Comment by romani** [comment]
3)
> protected static final int BUFFER_CUSHION = 12;

Cushion need to defined in such level to avoid realocation of memory in most cases. 12 is not enough.
You have format "[SEVERITY LEVEL] filePath:lineNo:columnNo: message. [CheckName]"
CusionSize = maxLenght(Severity) + lenthOfAllSeparators + 2 * maxLength(CheckName)

It should be different for each Logger , as not all loggers have CheckName. So we need to move this variable back to method formatMessage

4)
>
```
+        final char leftBrace = '[';
+        final char rightBrace = ']';
+        final char space = ' ';
```

you will not do any good for performance and seriously decrease readability of code, please do as it was before.

5)
> protected String formErrorMessage(AuditEvent event, SeverityLevel severityLevel) {

Here is design problem of this class. We use "printSeverity" as configuration of this class from UTs to and override this method to override behaviour of formatMessage. We need to refactor this class to provide to DefaultLogger class who can format String  base on `AuditEvent event, SeverityLevel severityLevel`. In this case we can remove "printSeverity" from base class at all, and do customization in UTs level.

6)
> BriefLogger.java

please rename it to BriefUtLogger.java to state its purpose by name.

7)
> BriefLogger.java
 public void auditStarted(AuditEvent event) {

strange that we override only auditStarted .... both should be overriden or non.

8)
> "[WARNING] %1$s:3:14: "

As we try to mimic java Loggers, they do "[WARN]", please investigate usage of "WARN" vs "WARNING" in other tools

**Comment by romani** [comment]
@MEZk , requested updates are not very complicated, do you have problems with them ?

**Comment by MEZk** [comment]
@romani 
The problem is that we can not change the position of [SEVERITY LEVEL] in message from UTs. it always comes after file path when we invoke ```verify```. See https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java#L165. 

Since testTagPrintSeverityTrue in WriteTagCheckTest sets printSeverity to true. See https://github.com/checkstyle/checkstyle/blob/75da2ef6ac77766baac7016606457dc1f7bbfd7b/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java#L89, we need two different types of violation message:

1) [SEVERITY LEVEL] filePath:lineNo:columnNo: message. [CheckName]  - for default logger.
2) filePath: [SEVERITY LEVEL]: lineNo:columnNo: message. - for UTs.

**Comment by romani** [comment]
you can brake WriteTagCheck , see https://github.com/checkstyle/checkstyle/issues/2506
This Check is broken by design and should be removed, and should not affect others. It is even nonsense that some Check is preventing us to refactor logger.

**Comment by MEZk** [comment]
@romani 
1) Fixed.
2) Created new class LogMessageFormatter to format log messages base on arguments. All actions related to log message formatting have been moved to LogMessageFormatter. Now formatting is a responsibility of LogMessageFormatter.
3) Hm, and what about: ```bufferLength = fileNameLength + messageLength + lengthOfAllSeparators + severityNameLength + checkNameLength``` for each log message? Some of the messages contain severity level name and different set of separators, other contain check name.
4) Done.
5) Done.
6) Done.
7) Done.
8) In process. For now I've left [WARNING]

>you can brake WriteTagCheck , see #2506
This Check is broken by design and should be removed, and should not affect others. It is even nonsense that some Check is preventing us to refactor logger.

UT has been rearranged.

**Comment by MEZk** [comment]
@romani 
What is wrong with TeamCity? I did not touch IndentationCheckTest or NewHandlerTest

**Comment by romani** [comment]
most likely they updated a version of inspection tool on their server and now it detects more problem, I will take a look later.

**Comment by romani** [comment]
1)
> new LogMessageFormatter(true, true)
new LogMessageFormatter(false, false)

main code use `true,true` . test code use `false,false` it is a good sign that   `private final boolean printSeverity;  private final boolean printCheckName;` should be hosted in class that is in test area.
Hint: LogMessageFormatter should be an interface.

2)
>```     @Override
    public void auditFinished(AuditEvent event) {
```

you did override, but you do not call parent class implementation. Parent class do close streams. Who will close them now ?

3)
>```
    @Override
    public void fileFinished(AuditEvent event) {
        infoWriter.flush();
    }

    @Override
    public void fileStarted(AuditEvent event) {
        // No need to implement this method in this class
    }
```

it is not related to your changes, but please swap location of these methods, to make them logical.

4)
> new LogMessageFormatter(true, true);
formatter.formErrorMessage(event);

First of all usage of `Error` is not appropriate as severity is part of event not smth is defined by logic.
Prefix `form` ... please looks around on how people to name such stuff
https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html , so I propose name to be `format`.

**Comment by romani** [comment]
> What is wrong with TeamCity?

Do not pay attention, if after merge this reproduce on master - I will suppress these violations.

**Comment by romani** [comment]
@MEZk , release will happen on Sunday, it would be good to finish this PR before release.

**Comment by MEZk** [comment]
@romani 
1) Done
2) Done
3) Done
4) Done

**Comment by romani** [comment]
looks good, almost ready to merge.

last item:

please rename LogMessageFormatter to AuditEventFormatter as it do processing of AuditEvent to String and how this string will be used it different story (LogMessage is term of certain usage).

**Comment by MEZk** [comment]
@romani 
Interface: AyditEventFormatter
Implementation for DefaultLogger: AuditEventDefaultFormatter
Implementation for Uts : AuditEventUtFormatter

Are they good names?

**Comment by romani** [comment]
All names are good

**Comment by MEZk** [comment]
@romani 
2) Short statistic:

[WARNING]
Maven
Spring
JaCoCo
Java (Standart severity levels) See https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html

[WARN]
log4j. See http://logging.apache.org/log4j/2.x/log4j-api/apidocs/index.html
cobertura

Nevertheless, [WARN] is more compact. New message format will be too long if we use [WARNING]. This is my point of view.

**Comment by romani** [comment]
Ok , please do WARN.

**Comment by MEZk** [comment]
@romani 
Changing severity level name form WARNING to WARN will break compatibility. Now we and users of checkstyle use:
```xml
<property name="severity" value="warning"/>
```

**Comment by MEZk** [comment]
@romani 
Done

**Pull request merged**
