### PR TITLE
Issue #6320: added new tests to kill mutations for multiple packages 

### PR DESCRIPTION
**Pull request by rnveach**
Issue #6320

Since we added the mutator everywhere, I am dumping all the tests I had saved up for incomplete packages that I was still working on.

### CODE REVIEW

**Comment by rnveach** [comment]
coding package dropped from 115 to 96.

**Comment by romani** [comment]
Ones minor comment is addressed, ok to merge.

**Comment by rnveach** [comment]
@romani it seems something was up with circle ci. Quite a few jobs had been queued for 14 hrs and it looked like no one was running, so I cancelled a few and tried re-running them.

**Comment by rnveach** [comment]
@romani Your review item is done and CI is passing.

**Comment by rnveach** [comment]
@romani 
> ** ci/circleci: pitest6 ** — Your tests passed on CircleCI!
> **ci/circleci: pitest8 ** — Your tests passed on CircleCI!

Is there suppose to be a `pitest7`? I am not seeing it in the CI list.

**Pull request merged**
