### PR TITLE
Issue #10264: Update inputs for SuperCloneCheckTest

### LINKED ISSUE #10264: Update inputs for SuperCloneCheckTest
Child of #10080

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #10264

### CODE REVIEW

**Comment by timurt** [comment]
fix conflicts

**Comment by shashwatj07** [comment]
> fix conflicts

done

**Comment by timurt** [comment]
fix conflicts :(

**Comment by shashwatj07** [comment]
> fix conflicts :(

done :(

**Pull request merged**
