### PR TITLE
Issue #14137: Enable `IsInstanceLambdaUsage` check

### PR DESCRIPTION
**Pull request by rickie**
Issue #14137.

This PR enables the https://error-prone.picnic.tech/bugpatterns/IsInstanceLambdaUsage/ check.

### CODE REVIEW

**Comment by rickie** [comment]
> ⚠️ Failed to start an instance: FAILED_PRECONDITION: Monthly compute limit exceeded!

😬

**Comment by rickie** [comment]
I see similar failures on other branches 🤔.

**Comment by romani** [comment]
Cirius is unfortunate by CI provider.
Checker- index - is some leak, we investigating.
Azure is restarted.

If Azure pass, we can merge.

**Review by romani — APPROVED** [review]
ok to merge if Azure pass

**Pull request merged**
