### PR TITLE
Issue #3976: Split and Organize Checkstyle inputs by Test for EmptyForIteratorPad

### LINKED ISSUE #3976: Split and Organize Checkstyle inputs by Test for EmptyForIteratorPad
subtask of #3891 .

do a copy of all test input files to separate folder for EmptyForIteratorPad .
Not any other Check should use new inputs.

### PR DESCRIPTION
**Pull request by shivanshsoni**
fixes #3976

### CODE REVIEW

**Comment by rnveach** [comment]
@shivanshsoni Again, you do not need to keep closing and creating a new PR.
You said the last time was the last. Do not close this PR, do not delete the branch.

> my git shell is not responding to this branch.

Please show console output of what you are talking about so we can help you.

**Comment by shivanshsoni** [comment]
Sorry Sir, I will not do this again

**Comment by shivanshsoni** [comment]
@rnveach  what is this codecov report

**Comment by rnveach** [comment]
@shivanshsoni I suggest you run `mvn clean verify` before pushing your changes. It will test most of the CI failures.
Also please keep the number of commits to just 1.

**Comment by shivanshsoni** [comment]
@rnveach My CI check failing on this issue. Please suggest some changes :>Line matches the illegal pattern '\s+$'. [RegexpSingleline]

**Comment by MEZk** [comment]
@shivanshsoni 
1) You need to remove whitespaces at the end of the lines 51, 52, 53
https://github.com/checkstyle/checkstyle/pull/4010/files#diff-90137c3a994ad28f8b348b9faef28036R51

2) Replace tabs with whitespaces on line 52.

**Comment by shivanshsoni** [comment]
@MEZk I removed tabs but still Ci is failing

**Comment by shivanshsoni** [comment]
@rnveach Please suggest changes acoording to 
https://ci.appveyor.com/project/Checkstyle/checkstyle/build/6419/job/0uk5o75jk8st4789#L3223

**Comment by Vladlis** [comment]
@shivanshsoni 
you have 3 errors from Checkstyle - https://travis-ci.org/checkstyle/checkstyle/jobs/211693259#L370-L372
To resolve these errors:
1) Remove trailing spaces on lines 51 and 52;
2) Use only spaces for indentation, no tabs.

Also checkout https://github.com/checkstyle/checkstyle/wiki/PR-rules, you are breaking the second point.

**Comment by shivanshsoni** [comment]
@Vladlis As I am removing trailing spaces on line 51 and 52 it shows indentation error

**Comment by Vladlis** [comment]
@shivanshsoni 
Maybe because you have invalid indantation?
Please stop constantly pushing your changes, you are polluting our CIs. Just pass `mvn clean verify` locally first - that would be a good step forward.

**Comment by shivanshsoni** [comment]
@romani This have passed all the tests and it is ready to merge now

**Pull request merged**
