### PR TITLE
infra: update jdk for eclipse static analysis

### PR DESCRIPTION
**Pull request by nrmancuso**
Noticed at https://checkstyle.semaphoreci.com/jobs/a2f1d5ba-6547-45a8-a9b1-fc00c7f7c49c, we need to update jdk for this job to 17 (major ver. 61)

### CODE REVIEW

**Comment by nrmancuso** [comment]
Link to semaphore execution: https://checkstyle.semaphoreci.com/workflows/4815f09c-12df-48d6-b0f3-40ebcf838836?pipeline_id=df083745-bd5d-42f0-87c6-ad29e6df5241

**Comment by rnveach** [comment]
https://checkstyle.semaphoreci.com/jobs/03067066-250a-4b0a-9518-ee586b8b65d5
````
15. ERROR in /home/semaphore/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java (at line 869) 00:22
	fileMock, new ArrayList<Pattern>()); 00:22
	              ^^^^^^^^^ 00:22
Redundant specification of type arguments <Pattern> 00:22
---------- 00:22
16. ERROR in /home/semaphore/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java (at line 905) 00:22
	fileMock, new ArrayList<Pattern>()); 00:22
	              ^^^^^^^^^ 00:22
Redundant specification of type arguments <Pattern>
````

**Comment by rnveach** [comment]
@nrmancuso Same error at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/1019 .

**Comment by rnveach** [comment]
Hmm, I wasn't expecting a merge commit to be added.

**Comment by nrmancuso** [comment]
I will fix on my local, you have to manually select rebase in GitHub

**Comment by romani** [comment]
Do we know why it becomes a problem unexpectedly?

**Comment by nrmancuso** [comment]
@romani The jar used for this job was compiled with jdk17, so I assume that eclipse migrated from 11 to 17

**Comment by romani** [comment]
Better for us to stay on jdk 11 version and migrate to jdk 17 after summer

**Review by rnveach — APPROVED** [review]

**Comment by nrmancuso** [comment]
@romani done

**Review by romani — APPROVED** [review]

**Pull request merged**
