### PR TITLE
Issue #3202: ARRAY_INIT whitespace follow check deleted, test cases a…

### PR DESCRIPTION
**Pull request by kazachka**
Issue #3202

WhitespaceAround updated to check ARRAY_INIT token.
Some additional test cases added to WhitespaceAroundTest and InputWhitespace test resource. Fixed array initialization in InputEmptyTypesAndCycles test resource.

### CODE REVIEW

**Comment by romani** [comment]
@kazachka ,

> InputWhitespace.java

I see only empty line, not sure what is it for.

> InputEmptyTypesAndCycles

please revert new-line symbol at the end of file. It is not related to your update.

> InputWhitespaceAroundArrayInitialization

please put comments "// valid" and "// missing WS" as trailing comment (on the same line as statement where violation is expected.)

**Comment by romani** [comment]
Please do few cases with violations for structures like COLORS3 COLORS4 .

All other looks good, we are ok to start regression testing on real opensource code

**Comment by romani** [comment]
@kazachka , please follow steps to run regression testing and please share report online - https://github.com/checkstyle/contribution/tree/master/checkstyle-tester .
If there are too much violations please limit amount of projects in configuration file. If you have questions on launch please ask them in gitter chat room or email.

**Comment by kazachka** [comment]
Report:
https://kazachka.github.io/

**Comment by romani** [comment]
@kazachka ,

35K violations it is too much ! I can not review them all, please keep no more than 1K.

All links to sources are not working, Example: 
https://kazachka.github.io/xref/Hbase/hbase-annotations/src/main/java/org/apache/hadoop/hbase/classification/InterfaceAudience.html#L53
please upload sources too, I need them to verify.

**Comment by kazachka** [comment]
New report with 300+ violations, links working:
https://kazachka.github.io/

**Comment by romani** [comment]
@kazachka , please make a config of your Check that only validating ARRAY_INIT , there  is no reason for me review violations like `'+' is not preceded with whitespace.` .
Please regenerate report.

**Comment by kazachka** [comment]
Done:
https://kazachka.github.io/

**Comment by romani** [comment]
@kazachka ,

0) report is good, I did not find any false positives.

1)
looks like people are not on the same position about formatting of such braces.
https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace
> Optional just inside both braces of an array initializer
    new int[] {5, 6} and new int[] { 5, 6 } are both valid

So we can not do this as default behavior. Please remove this Token from getDefaultTokens.

2) after a fix of "1)" please generate diff report(https://github.com/checkstyle/contribution/tree/master/patch-diff-report-tool) on default tokens and share with me on github.io .

**Comment by kazachka** [comment]
Diff-report:
https://kazachka.github.io/diff-report-part1/
https://kazachka.github.io/diff-report-part2/

**Comment by romani** [comment]
repots are empty, not clear why.
I need diff-report for between two reports over guava:
1) report on default set of tokens
2) report on changed set of token, all defaults + ARRAY_INIT.

**Comment by kazachka** [comment]
Updated:
https://kazachka.github.io/diff-report/

**Pull request merged**
