### PR TITLE
Issue #3308: fixed EqualsHashCode equals method parameter test

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3308

Updated documentation. Changed some code to use our utility method, which checked for static that our old code didn't. Checking parameter for `Object` or `java.lang.Object`.
Regression to come.

### CODE REVIEW

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/77/

@romani Wrecker failure is regression failure in xwiki.
[ERROR] src/main/java/org/xwiki/crypto/pkix/params/PrincipalIndentifier.java:[49,5] (coding) EqualsHashCode: Definition of 'equals()' without corresponding definition of 'hashCode()'.
https://github.com/xwiki/xwiki-commons/blob/c6ec6b4559977667e020090313580dd037f654fa/xwiki-commons-core/xwiki-commons-crypto/xwiki-commons-crypto-pkix/src/main/java/org/xwiki/crypto/pkix/params/PrincipalIndentifier.java#L50

To me this seems like a false positive since it is an interface and has no absolute body. If a class implements the interface, they won't be `required` to implement the body of those methods since `Object` has them by default.
You agree that this type of violation should be skipped?

If this is a false positive, how do we want to handle an abstract class where it defines one method but the other isn't defined or is abstract? I think that should still be a violation. It only shouldn't be a violation if both are not defined or both are abstract with no body.

**Comment by rnveach** [comment]
After a re-look, this is only coming up now because `CheckUtils.isEqualsMethod` doesn't check if the method is `public` which the original implementation did. That's why this case is coming up as a difference , but the original issue and question still remains if the code had `public` written in.

**Comment by MEZk** [comment]
@rnveach 
hashCode and equals full signatures from Object class:

public boolean equals(Object obj)
public native int hashCode()

So they have to be both public. I think if someone decided to override either hashCode or equals, both methods must be public otherwise there should be a violation.

For example:

```java
public class B {
  public int hashCode(int i) {return 1;} // violation (no public equals)
  private boolean equals(Object o) {return true;} 
}
```

This should be OK  [7.1 release]:

```java
public class A {
  private int hashCode(int i) {return 1;} 
  private boolean equals(Object o) {return true;}
}
```

This works fine  [7.1 release]:

```java
public class C {
  privateint hashCode(int i) {return 1;}
  public boolean equals(Object o) {return true;}   // violation (Definition of 'equals()' without corresponding definition of 'hashCode()')
}
```

False negative [7.1 release]:
```java
public class TestClass1 {
    public int hashCode() {return 1;} // 
    public int equals(Object o) {return 1;}
}
```

**Comment by romani** [comment]
> To me this seems like a false positive since it is an interface and has no absolute body.

yes, lets skip such cases, lets focus Check on IMPLEMENTATION of methods.

> how do we want to handle an abstract class where it defines one method but the other isn't defined or is abstract?

violation, as abstract class should be implemented correctly without relying to child classes.

>  It only shouldn't be a violation if both are not defined or both are abstract with no body.

yes.

--------------------------------

for MEZk comments:

> From my point of view, the check should also check:

yes, the more exact the better.

> However, there is no need in checking for public visibility modifiers in interfaces as interface methods are public by default.

yes, but beware that interfaces could have methods implementations in jdk8.

**Comment by MEZk** [comment]
>but beware that interfaces could have methods implementations in jdk8.

Yes. This is prohibited by javac:
```java
public interface ITest{
    default boolean equals(Object o) {
        return true;
    }
}
```

And this is allowed:
```java
public interface test {
    default boolean equals(String o) {
        return true;
    }
}
```

**Comment by romani** [comment]
@rnveach ,

> To me this seems like a false positive since it is an interface and has no absolute body. If a class implements the interface, they won't be required to implement the body of those methods since Object has them by default.
You agree that this type of violation should be skipped?

yes, lets skip abstract declarations of such methods (in interfaces and abstract classes).

Example of how xwiki enforce equals to be implemented in all related classes:
https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-core/xwiki-commons-crypto/xwiki-commons-crypto-pkix/src/main/java/org/xwiki/crypto/pkix/params/x509certificate/DistinguishedName.java

No violations is expected on xwiki project.

**Comment by rnveach** [comment]
@romani 
Sorry for the delay, everything should be done.

**Comment by romani** [comment]
@rnveach , no connection to rveach.no-ip.org , please recheck.

**Comment by romani** [comment]
@rnveach , please address last 2 points.

**Comment by rnveach** [comment]
@romani 
Sorry for the delay, those 2 points are done.

I did add 2 additional changes.
I accommodated `native` methods after I thought I saw one in regression, but it really just had an invalid parameter: http://rveach.no-ip.org/checkstyle/regression/reports/78/findbugs/index.html#A12
I then accommodated `static` methods after I realized `equals` handled it by default, but `hashCode` didn't.

Nothing changed in regression since the last report.

**Pull request merged**
