### PR TITLE
#7695 Update for RegexpMultiline

### PR DESCRIPTION
**Pull request by kalakandi**
Resolve of issue #7695 

Screenshot_2020-03-19 checkstyle – Regexp(1)

###  Example of  Default output 1 :
This check doesn't provide any configurable property.

<hr>

### Example of Default output 2 :

$ cat config2.xml

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
        <module name="RegexpMultiline">
            <property name="matchAcrossLines" value="true"/>
            <property name="format" value="System\.out.*print\("/>
    </module>
</module>
```

<hr>
$ cat test_2.java 

```
void method() {
  System.out. // violation
  print("Example");
  System.out.
  print("Example");
}

```

<hr>
$ java -jar checkstyle-8.30-all.jar -c config2.xml test_2.java

```
Starting audit...
[ERROR] /home/methorthodox/New Folder/test_2.java:3: Line matches the illegal pattern 'System\.out.*print\('. [RegexpMultiline]
Audit done.
Checkstyle ends with 1 errors.
```

<hr>

### Example of Non default output 1:

$ cat config1.xml

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
      <module name="RegexpMultiline">
        <property name="format" value="System\.(out)|(err)\.print(ln)?\("/>
    </module>
</module>
```

<hr>

$ cat TEST1.java 

```
void method() {
    System.out.print("Example"); // OK
    System.out.println("Example"); // OK
    System.out. // OK
    print("Example");
    System.out. // OK
    println("Example");
    System.out.print //OK
    ("Example");
    System.out.println //OK
    ("Example");
    System. // violation
    out.print("Example");
    System. // violation
    out.println("Example");  
}
```

$ java -jar checkstyle-8.30-all.jar -c config1.xml TEST1.java

```
Starting audit...
[ERROR] /home/methorthodox/New Folder/TEST1.java:2: Line matches the illegal pattern 'System\.(out)|(err)\.print(ln)?\('. [RegexpMultiline]
[ERROR] /home/methorthodox/New Folder/TEST1.java:3: Line matches the illegal pattern 'System\.(out)|(err)\.print(ln)?\('. [RegexpMultiline]
[ERROR] /home/methorthodox/New Folder/TEST1.java:4: Line matches the illegal pattern 'System\.(out)|(err)\.print(ln)?\('. [RegexpMultiline]
[ERROR] /home/methorthodox/New Folder/TEST1.java:6: Line matches the illegal pattern 'System\.(out)|(err)\.print(ln)?\('. [RegexpMultiline]
[ERROR] /home/methorthodox/New Folder/TEST1.java:8: Line matches the illegal pattern 'System\.(out)|(err)\.print(ln)?\('. [RegexpMultiline]
[ERROR] /home/methorthodox/New Folder/TEST1.java:10: Line matches the illegal pattern 'System\.(out)|(err)\.print(ln)?\('. [RegexpMultiline]
Audit done.
Checkstyle ends with 6 errors.
```
<hr>

### Example of Non default output 2:

$ cat config2.xml

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
        <module name="RegexpMultiline">
            <property name="matchAcrossLines" value="true"/>
            <property name="format" value="System\.out.*print\("/>
    </module>
</module>
```

<hr>

$ cat TEST2.java 

```
void method() {
    System.out. // violation
    print("Example");
    System.out // vioaltion
    .print("Example");
    System.out.print("Example"); // OK
    System. // violation
    out.print("Example");
    System // violation
    .out.print("Example");
    System.out.print // violation
    ("Example");
  }
```

<hr>
$ java -jar checkstyle-8.30-all.jar -c config2.xml TEST2.java

```
Starting audit...
[ERROR] /home/methorthodox/New Folder/TEST2.java:2: Line matches the illegal pattern 'System\.out.*print\('. [RegexpMultiline]
Audit done.
Checkstyle ends with 1 errors.
```

### CODE REVIEW

**Comment by kalakandi** [comment]
@romani review and pls help!!

**Comment by gaurabdg** [comment]
Hey you can view the error log and resolve the checkstyle errors corresponding to the line numbers

**Comment by kalakandi** [comment]
@romani reviews and help Please!!

**Comment by romani** [comment]
Please update config to place Check under Checker ( remove Treewalker at all ) https://checkstyle.org/config_regexp.html#RegexpMultiline_Parent_Module

Please look at examples https://checkstyle.org/config_regexp.html#RegexpMultiline_Example_of_Usage for more details

**Comment by rnveach** [comment]
@kalakandi ping

**Comment by strkkk** [comment]
Closed as abandoned

**Pull request closed without merging**
