### PR TITLE
Issue #10450: Update inputs for MemberNameCheckTest

### LINKED ISSUE #10450: Update inputs for MemberNameCheckTest
Child of #10080

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #10450

### CODE REVIEW

**Comment by romani** [comment]
Please fix CI

**Comment by shashwatj07** [comment]
> Please fix CI

done

**Comment by romani** [comment]
Still bunch of failures, from checkstyle.
https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations#how-to-generate-checkstyle-report how to run only checkstyle.

**Comment by romani** [comment]
GitHub, rebase

**Pull request merged**
