### PR TITLE
Issue #4592: merged module test support and fileset test support

### PR DESCRIPTION
**Pull request by rnveach**
Issue #4592

As brought up in https://github.com/checkstyle/checkstyle/pull/4840#discussion_r130085063 , our module support class didn't support anything other than Checks.
I changed module support to now handle filesets and renamed the methods so it is more obvious what they are doing.

The main changes are in `AbstractModuleTestSupport`, removing `BaseFileSetCheckTestSupport`, and a change in `TreeWalkerTest.testWithCheckNotHavingTreeWalkerAsParent`.

### CODE REVIEW

**Comment by rnveach** [comment]
Extra changes were needed in `UnusedImportsCheckTest` and it's inputs because they made references to the class I removed. It still references production code and we should look into removing those references as inputs should be completely standalone.

**Comment by rnveach** [comment]
https://travis-ci.org/checkstyle/checkstyle/jobs/258693607#L514
> ./.ci/travis/travis.sh: line 61: html2text: command not found

**Comment by rnveach** [comment]
@romani I've tried restarting travis jobs multiple times but it seems they keep timing out and being killed off. Groovy also throws an exception and I'm not sure why.

**Comment by romani** [comment]
Travis is moving with servers to new ubuntu , there is warning message.
Smth is broken on their side, cache is lost for sure , so that is why download process is long, but strange that it is time-outed after 3 min of execution, timeout was about 10 min of inactivity.
I restarted it one more time.
If become blocker , we could use "dist: precise" as they suggested to go back to previously used linux distro

**Comment by rnveach** [comment]
> dist: precise

Added. Looks like travis is passing now.

**Comment by romani** [comment]
ok, update distribution is merged in separate PR, please update  this PR to ready to merge state.

**Comment by rnveach** [comment]
@romani rebased.

**Comment by rnveach** [comment]
@romani All CI passed.

**Pull request merged**
