### PR TITLE
minor: Hardcoded Mutation in SuppressionCommentFilter

### PR DESCRIPTION
**Pull request by shubh220922**
Diff Regression config: https://gist.githubusercontent.com/shubh220922/36609075008b5d16b3b2afb6e759635b/raw/f510316e7ee3d1f46cef3282e5d1af1825a096e6/config.xml

### CODE REVIEW

**Comment by shubh220922** [comment]
Github, generate report

**Comment by shubh220922** [comment]
Github, generate report

**Comment by shubh220922** [comment]
Github, generate report

**Comment by shubh220922** [comment]
snap! It keeps failing.

@romani  whats going wrong? Please help.

**Comment by stoyanK7** [comment]
@shubh220922 You can go to `Actions` and search for your workflow.

https://github.com/checkstyle/checkstyle/actions?query=workflow%3ADiff-Report++

Failing workflow
https://github.com/checkstyle/checkstyle/actions/runs/4402015444/jobs/7708752006#step:9:2246
```
Error:  /home/runner/work/checkstyle/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java:[661,40] variable tagMessageRegexp might not have been initialized
```

**Comment by shubh220922** [comment]
@stoyanK7 ahh.. got it. Thanks.

Also, @stoyanK7 , I wanted to disable my CI completely but, as you can see, some of my CIs are still active. I deleted all the YAML files before pushing but the CI wouldn't disappear. Could you assist as to what I did wrong.

**Comment by romani** [comment]
To disable all CIs you need to cherry pick this commit in your branch https://github.com/checkstyle/checkstyle/commit/998c65dc977d457eeb645c91834018655280ef63

**Comment by stoyanK7** [comment]
@romani I think this `disable-all-ci` branch needs updating since we renamed some workflows to `kebab-case`.

**Pull request closed without merging**
