### PR TITLE
doc: fix indentation of config example

### PR DESCRIPTION
**Pull request by strkkk**
Fix ugly indent
image

### CODE REVIEW

**Comment by strkkk** [comment]
@romani @rnveach I cannot see what is wrong with codeship, it redirects me to "create new organization" page

**Comment by rnveach** [comment]
Codeship can be ignored. It is just a bunch of timeouts.

**Comment by strkkk** [comment]
> lets push students who are working on these examples to fix them

Yeah, it was a better solution.

**Comment by rnveach** [comment]
For a simple fix, I will merge this.

Please remember to look for this type of things in student's issues and PRs.

**Comment by romani** [comment]
@rnveach , @strkkk
If we want students to fix such cases, we need to explain them how to generate web site and ask them to share screenshot on PR creation, it should be part of issue description.

**Pull request merged**
