### PR TITLE
minor: test openjdk10 repo

### PR DESCRIPTION
**Pull request by nmancus1**
This is just a test related to https://github.com/checkstyle/contribution/pull/527#issuecomment-927211709

Diff Regression projects: https://gist.githubusercontent.com/nmancus1/eda82b4710a94cfb14779a8752784545/raw/f28735639e0904aa675a874a16042084ebb14e9c/projects.properties

Diff Regression config: https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/my_check.xml

Diff Regression patch config: https://gist.githubusercontent.com/nmancus1/19560c1866ca4eabbf3d3ad8a90a213d/raw/9f62a21fa2fd5297a18b99e0f5ef4080e114cf4c/patchconfig.xml

### CODE REVIEW

**Comment by rnveach** [comment]
````
Exception in thread "main" java.lang.Error: Error was thrown while processing /home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/src/main/java/openjdk10/test/hotspot/jtreg/gc/TestBigObj.java
...
Caused by: java.lang.OutOfMemoryError: Java heap space
````

**Comment by nmancus1** [comment]
Yes, this is being caused by OOM in `FileText#readFile`:

```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:686)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:228)
	at com.puppycrawl.tools.checkstyle.api.FileText.readFile(FileText.java:211)
	at com.puppycrawl.tools.checkstyle.api.FileText.<init>(FileText.java:170)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:326)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:289)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)

```

I have been trying to reproduce this locally, but no luck yet. For what it's worth, this file is gigantic:

```bash

➜  gc git:(dev) cat TestBigObj.java | wc -l
65588

```

**Comment by rnveach** [comment]
Yea, sometimes CI has lower memory than usual. I would say put the file to the ignore list if it can't be made stable.

**Comment by nmancus1** [comment]
>  I would say put the file to the ignore list if it can't be made stable.

We currently ignore the exclusion list in the projects file for diff report generation, this would require enabling excludes via the `--allowExcludes` option.

**Comment by rnveach** [comment]
Sorry, I forgot. So we are still blocked from using openjdk10?

**Comment by nmancus1** [comment]
> So we are still blocked from using openjdk10?

From this issue in `FileText` now, yes. I wanted to do more investigation before creating an issue or commenting in https://github.com/checkstyle/contribution/pull/527#issuecomment-927211709 .

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
GitHub, rebase

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
Report is failed:
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by romani** [comment]
CI execution is limited by memory, it is fine, as we know 9.x is excessive on memory, until it is fixed, no reason even try.

Let's move this report/config to PR where @nmancus1  try to fix memory usage.

**Comment by nmancus1** [comment]
> Let's move this report/config to PR where @nmancus1 try to fix memory usage.

Done, I am closing this.

**Pull request closed without merging**
