### PR TITLE
rm .classpath (as its on .gitignore, else leads to confusing changed file status)

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by romani** [comment]
.classpath should be used , please remove it from .gitignore (it was added by mistake)

**Comment by jsotuyod** [comment]
Is it really usefull to have `.classpath` on the repository?

Just as `.project` it is automatically generated by Maven (either through the Eclipse plugin doing `mvn eclipse:eclipse` or by m2e plugin, when importing the project from source).

I see no point in having this on the repository and commited everytime a dependency changes (that's one of the reasons there is a pom in the first place); and specially not since `.project` is not part of the project itself either.

**Comment by romani** [comment]
we have autogenerated sources, as far as I remember it is specified in .classpath 
https://github.com/checkstyle/checkstyle/blob/master/.classpath#L9

we also need: https://github.com/checkstyle/checkstyle/blob/master/.classpath#L12

Eclipse still not that good to catch all that stuff, even Intelij Idea can not do that clearly.

If you know how to setup Eclipse to do all automatically please propose a PR. Before PR , please recheck it twice as we had a lot of problems with that files.

**Comment by jsotuyod** [comment]
https://github.com/checkstyle/checkstyle/blob/master/.classpath#L9 is already added by Eclipse plugin since it's added here: https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L523

https://github.com/checkstyle/checkstyle/blob/master/.classpath#L12 doesn't seem necessary, since target/genrated-sources/antlr is created by Eclipse plugin / m2e during th `generate-sources` phase...

The one thing that breaks though is that both the java grammar and javadoc grammars are dumped to the same folder, and the `antlr-maven-plugin` / `antlr4-maven-plugin` adds both entries to the `sourceSet`, and therefore, are added to Eclipse's project.

To fix this, the `antlr4-maven-plugin` configuration should be changed to:

```
        <configuration>
          <visitor>true</visitor>
          <sourceDirectory>${basedir}/src/main/resources/</sourceDirectory>
          <outputDirectory>${project.build.directory}/generated-sources/antlr/</outputDirectory>
          <includes>
            <include>com/puppycrawl/tools/checkstyle/grammars/javadoc/*.g4</include>
          </includes>
        </configuration>
```

This way, it will properly get the package, and use the proper folder within the same `${project.build.directory}/generated-sources/antlr/` classpathentry.

This means removing the `package` from the header on both `.g4` files do avoid having them duplicated (notice files are generated in the same folder, with the same pacage, it's just confiuration changes). Tested this on my machine and works fine with both eclipse and m2e plugins.

If there are no issues with removing the optional flag in the classpathentry (since, again, `generate-sources` is called by both plugins and I see no scenario where it would be missing, not to mention why if missing it should not complain), or removing the package from the headers (again, should be harmless); I'll gladly submit a PR for anyone to test.

**Comment by jsotuyod** [comment]
For the curious, the commit to get this done is [here](https://github.com/Monits/checkstyle/commit/9bca7feab37b3ab6489eacbf167ce82c4a0d3fba)

You can clone my fork and check it out if still in doubt.

**Comment by romani** [comment]
@jsotuyod , thanks a lot for your suggestion , with your changes eclipse 4.4.2 able to import Checkstyle , it take a LOT of time of doing smth for Eclipse, but eventually(several minutes) it stops compiling.

Do you know how to explain Eclipse to suppress warnings on some folders? 
Example that exists in our .classpath:
```
	<classpathentry kind="src" output="target/classes" path="target/generated-sources/antlr">
		<attributes>
			<attribute name="ignore_optional_problems" value="true"/>
			<attribute name="optional" value="true"/> <!-- !!!!!! -->
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
```

I mainly need .classpath file for this "optional" field to suppress warnings of Eclipse on generate sources and test inputs.
If that not possible, I will push to repository Eclipse's (.project and .classpath) files to let contributors use them out-of-the-box.

**Comment by jsotuyod** [comment]
Using `mvn eclipse:eclipse` doesn't allow that AFAIK, but m2e does. With the current configuration on my fork, m2e generates:

```
        <classpathentry kind="src" output="target/classes" path="target/generated-sources/antlr">
                <attributes>
                        <attribute name="optional" value="true"/>
                        <attribute name="maven.pomderived" value="true"/>
                </attributes>
        </classpathentry>
```

**Comment by jsotuyod** [comment]
There is no support for that in maven eclipse plugin, and I believe m2e either (not sure though).

**Comment by romani** [comment]
https://issues.apache.org/jira/browse/MECLIPSE-735

I am closing that issue as I am going to push ".project" file and keep Eclipse configuration on remote.

@jsotuyod , please copy your explanation to separate issue and please do PR with your changes. Your changes are good step forward, and might be after MECLIPSE-735 is fixed and released all will be fine and I will remove Eclipse configs from repo.

**Pull request closed without merging**
