### PR TITLE
Issue #1031: Improve documentation for CovariantEquals check

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by romani** [comment]
Build is failed, please fix

**Comment by Vladlis** [comment]
Fixed

**Comment by romani** [comment]
@mkordas , as author of issue, please review and merge.

**Comment by mkordas** [comment]
@romani, @Vladlis 
I'm on it

**Comment by mkordas** [comment]
1. I think we need to explain what "covariant" means somewhere in first paragraph
1. Sometimes `java.lang.Object` is used, sometimes just `Object`
2. `the enumerations` - you mean enums?
1. `The reason is to point that` - not correct grammatically
1. `especially is the class is used with` - something is missing in this sentence
1. `insidious` - should we really use so uncommon words in our docs?
1. `mysterious behavior will result` - not correct grammatically
1. Code samples do not render well:
image

@Vladlis, this is just partial review. Can you please check grammar and wording by yourself and fix everything you will spot? Would be also nice if you presented in PR rendering results (can be obtained by executing `site -Dlinkcheck.skip=true -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true -Dcheckstyle.ant.skip=true`).

**Comment by romani** [comment]
@Vladlis , please remove leading spaces for code samples, please make code formatted correctly.

**Comment by Vladlis** [comment]
@mkordas 
http://vladlis.github.io/reports/covariant_eq/config_coding.html#CovariantEquals

1.  Done.
2. Only ```Object``` now.
3. Yes, replaced with ```enums```.
4. 5. 6. Fixed.
7. I do not agree, explain please.
8. Done.

**Comment by mkordas** [comment]
@Vladlis 
Thanks for the fixes.

> 7) I do not agree, explain please.

The typical phrase is `behavior will result in ...`. But as we don't have `in ...` part, better would be to write just `the behavior might be mysterious`.

Additional comments:

1. I would add information why covariant `equals` in enums is bad practice. Something like: `it may cause having two different enum values that are equal using covariant enum method, and not equal when compared normally`
2. `what may lead` -> `and it may lead`

Other than that changes are nice and good to merge.

**Comment by Vladlis** [comment]
@mkordas, Done.

**Comment by mkordas** [comment]
Thanks @Vladlis, great job! Integrated as c384da04a254a05b06e257a090490a9fefdf0209

**Pull request closed without merging**
