### PR TITLE
Issue #11637: Resolve shellcheck SC2088

### PR DESCRIPTION
**Pull request by Kevin222004**
Part of #11637 

Refrence :- https://www.shellcheck.net/wiki/SC2088

### CODE REVIEW

**Comment by Kevin222004** [comment]
I am not seen travis running over here is it disabled or what??

**Comment by nrmancuso** [comment]
> I am not seen travis running over here is it disabled or what??

We are out of credits, we are working on a solution.

**Comment by Kevin222004** [comment]
how to verify that the script is working properly although the change are not big and logical but still

**Review by romani — APPROVED** [review]
Travis will be restored on Monday

**Comment by Kevin222004** [comment]
@romani I have practice intermediate shell script and also learning github action bot can you please ping me on issue related that to get a good start.  As of know there are various  issue opened related to it.

**Comment by shubh220922** [comment]
> @romani I have practice intermediate shell script and also learning github action bot can you please ping me on issue related that to get a good start. As of know there are various issue opened related to it.

@romani yes. Even I want to work on little harder issues related to shellchecks and bash files of checkstyle.

**Pull request merged**
