### PR TITLE
doc: Remove 'url' option from ImportControl xdoc

### PR DESCRIPTION
**Pull request by MEZk**
Removed description of 'url' option, since ImportControl does not have the option.

### CODE REVIEW

**Comment by mkordas** [comment]
@MEZk, thanks for spotting that!

@romani, this option was removed in 4be4abc6360709a49b231277a2513905332f9e50. Most probably it was accidental, but on the other hand no one has complained since then... What do you think? Should we bring this option back?

**Comment by romani** [comment]
@ivanov-alex , can you remind us why options it was removed ?

setUrl change "root" member , so it does not looks like dead option.

Most likely we think that "setFile" should cover this
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java#L138
but
```
		URI uri = new File("http://checkstyle.sourceforge.net/anttask.html").toURI();
		System.out.println(uri);
```
will output: 
```
file:/var/tmp/http:/checkstyle.sourceforge.net/anttask.html
```

so to make setFile completely cover setUrl we need to update its code.

**Comment by MEZk** [comment]
@romani 
Try to use the check and run checkstyle with the 'url' option. You will get Exception that the property does not exist. That is why we should investigate the problem.

**Comment by romani** [comment]
I am closing this Pull, as we have to restore that option/property. Issue is created https://github.com/checkstyle/checkstyle/issues/2231.

**Pull request closed without merging**
