### PR TITLE
minor: disable section validation

### PR DESCRIPTION
**Pull request by stoyanK7**
From https://github.com/checkstyle/checkstyle/pull/13103#issuecomment-1570440101

>  I think test is just strict enforcement of doc to be present. Back in several years, web site was very very very inconsistent. So such hack in Junit helped put situation under control.
> 
> Now layout are changing, we do not expect new Checks in near future, so we disable this check or some part of it and create issue to come back to it at the end , when we will have already final layout.
> 
> It was part of project to setup best practices ( wiki page) and enforce some of them. Please create create two issues to deal with it later at summer.

### CODE REVIEW

**Comment by romani** [comment]
CI is not happy

**Comment by nrmancuso** [comment]
@stoyanK7 please ping me once CI is happy

**Comment by stoyanK7** [comment]
@nrmancuso Ping.

**Comment by nrmancuso** [comment]
@stoyanK7 are we able to just use `@Disabled` annotation with comment like `until #13118`?

**Review by nrmancuso — APPROVED** [review]
Ok, we have git history of test to base new one on, I am good.

**Comment by stoyanK7** [comment]
> @stoyanK7 are we able to just use `@Disabled` annotation with comment like `until #13118`?

You're right. I went a bit too harsh on those tests by deleting them 😂. Though they will have to be rewritten.

**Pull request merged**
