### PR TITLE
Issue #10043: Fixed SuppressWarnings not working on local variables

### PR DESCRIPTION
**Pull request by RandyLovevivi**
Issue #10043

The bug in line 12 is caused by the following line [lastColumn = nextAST.getColumnNo() - 1;](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java#L338)
It will lead to the 8 of the method2() be out of the range of the SuppressWarnings and will not be suppressed. The end position of the SuppressWarnings will be located to the ";" at the end of the code line. If it minus one, it will not cover the "8", which is just before the ";" .

### CODE REVIEW

**Comment by romani** [comment]
Please fix `[ERROR] [checkstyle] [ERROR] /drone/src/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheckTest.java:49:17: 'array initialization' child has incorrect indentation level 16, expected level should be 12. [Indentation]`

Make sure mvn verify pass on your local

**Comment by romani** [comment]
Please rebase on latest sources to fix CI

**Review by romani — APPROVED** [review]
Ok to merge if CI pass

**Comment by RandyLovevivi** [comment]
I don't know how to rebase on latest sources. Do I need to create a new pull request?

**Comment by romani** [comment]
Please make single commit in PR.

**Comment by strkkk** [comment]
@RandyLovevivi you can google this stuff, e.g. https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

There is a workaround - you can squash commits and force push them here and then add comment "Github, rebase" to trigger action to rebase your branch

**Comment by romani** [comment]
Single commit please

**Comment by romani** [comment]
merged at https://github.com/checkstyle/checkstyle/pull/11609

**Pull request closed without merging**
