### PR TITLE
Enforce all checks to override getRequiredTokens method, #655 

### PR DESCRIPTION
**Pull request by MEZk**

### CODE REVIEW

**Comment by romani** [comment]
please rebase , I will review your PR next day

**Comment by romani** [comment]
Following could be done as separate PR or the same issue:
it would be good to have UT that load all "xxxxxxxxxxxxCheck" classes from classpath and run them with default config on empty file to make sure Default never conflicts with Acceptable and Requred vs Acceptable - the most critical problem as we have to work without problems by default. 
Plus few tests on checking UserDefined tokens over Acceptable and Required for any Check.

**Comment by MEZk** [comment]
@romani 
Sorry for delay.

1)
>please rebase 

Done

2)
>please explain that update in detail, all that tokens help to control scope . Please move that update to separate commit , you update is too big to be easily applied, lets merge simple refactoring first and then functional udpate.

My bad, incorrect. To fix I've changed getAcceptableTokens returned values, so, in accordance with [check's documentation](http://checkstyle.sourceforge.net/config_coding.html#FinalLocalVariable#FinalLocalVariable), acceptable tokens are PARAMETER_DEF, VARIABLE_DEF.

3)
>change a logic to call getAcceptableTokens in all methods.

Lost that check's methods during bulk update. Now fixed.

4)
>Following could be done as separate PR or the same issue:

Should I wait till [changes](https://github.com/mkordas/checkstyle/commit/6d6ef1702a18d3c4fc7969bd9abd3239b073fc7d) by @mkordas will be accepted? And also there should be an additional check whether getRequiredTokens returns EMPTY_INT_ARRAY.

**Comment by romani** [comment]
> My bad, incorrect. To fix I've changed getAcceptableTokens returned values, so, in accordance with 

And now this does not make sense at all. getAcceptableTokens should be the biggest set in Check.
getRequiredTokens the smallest. All your changes to Checks in that PR is damage.
Please recheck why UTs did not catch that.

> Should I wait till changes by @mkordas will be accepted?

Now that PR have conflicts, please add that commit to you PR.

> commit: 	Updated all checks to have getRequiredTokens and getAcceptableTokens

Please move it to separate PR, it is huge and it is very time consuming to verify it again and again.

**Comment by MEZk** [comment]
@romani 
>And now this does not make sense at all. getAcceptableTokens should be the biggest set in Check.
getRequiredTokens the smallest. All your changes to Checks in that PR is damage.
Please recheck why UTs did not catch that.

Returned values of getAcceptableTokens() for FinalLocalVariableCheck are incorrect, because the check is specified only for  TokenTypes.VARIABLE_DEF and TokenTypes.PARAMETER_DEF. See [documentation](http://checkstyle.sourceforge.net/config_coding.html#FinalLocalVariable). But now user can specify such tokens as TokenTypes.CTOR_DEF or TokenTypes.IDENT for the check and that will be incorrect token types and the check will do nothing at all.

````java
    public int[] getAcceptableTokens() {
        return new int[] {
            TokenTypes.IDENT,
            TokenTypes.CTOR_DEF,
            TokenTypes.METHOD_DEF,
            TokenTypes.VARIABLE_DEF,
            TokenTypes.INSTANCE_INIT,
            TokenTypes.STATIC_INIT,
            TokenTypes.LITERAL_FOR,
            TokenTypes.SLIST,
            TokenTypes.OBJBLOCK,
            TokenTypes.PARAMETER_DEF,
        };
    }
````

If we change acceptable tokens to

````java
    @Override
    public int[] getAcceptableTokens() {
        return new int[] {
            TokenTypes.VARIABLE_DEF,
            TokenTypes.PARAMETER_DEF,
        };
    }
````

user will be allowed to use only TokenTypes.VARIABLE_DEF and TokenTypes.PARAMETER_DEF. But the check will not work correctly (it will throw NPE) without required tokens:

````java
    @Override
    public int[] getRequiredTokens() {
        return new int[] {
            TokenTypes.IDENT,
            TokenTypes.CTOR_DEF,
            TokenTypes.METHOD_DEF,
            TokenTypes.INSTANCE_INIT,
            TokenTypes.STATIC_INIT,
            TokenTypes.LITERAL_FOR,
            TokenTypes.SLIST,
            TokenTypes.OBJBLOCK,
        };
    }
````

So, there should be only two token types which are returned by getAcceptableTokens, otherwise documentation is incorrect.

**Comment by MEZk** [comment]
@romani 
>
And now this does not make sense at all. getAcceptableTokens should be the biggest set in Check.
getRequiredTokens the smallest. All your changes to Checks in that PR is damage.
Please recheck why UTs did not catch that.

1) According to documentation FinalLocalVariableCheck can be specified only for PARAMETER_DEF, VARIABLE_DEF:

screenshot

2) Now getAcceptableTokens() returns: 

````java
TokenTypes.IDENT,
TokenTypes.CTOR_DEF,
TokenTypes.METHOD_DEF,
TokenTypes.VARIABLE_DEF,
TokenTypes.INSTANCE_INIT,
TokenTypes.STATIC_INIT,
TokenTypes.LITERAL_FOR,
TokenTypes.SLIST,
TokenTypes.OBJBLOCK,
TokenTypes.PARAMETER_DEF,
````
So, user can use the following configuration of the check:

```xml
<module name="FinalLocalVariable">
     <property name="token" value="CTOR_IDENT, IDENT"/>
 </module>
```

and with the configuration check will do nothing at all. In addition to this, it is contrary to the documentation. That is why we should change acceptable tokens set to TokenTypes.VARIABLE_DEF and TokenTypes.PARAMETER_DEF.

3) We can not change required tokens set, because all that tokens are used in visitToken() and without them NPE will occur.

4)
If we change getDefaultTokens set to TokensType.VARIABLE_DEF (in accordance with check's documentation) the testDefault() in FinalLocalVariableCheckTest will throw NPE:

```
Aug 16, 2015 9:42:46 PM com.puppycrawl.tools.checkstyle.TreeWalker processFiltered
SEVERE: NullPointerException occurred during the analysis of file /media/andreiselkin/TOURO/IDEA_Projects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/coding/InputFinalLocalVariable.java.
java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.insertVariable(FinalLocalVariableCheck.java:318)
	at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.visitToken(FinalLocalVariableCheck.java:195)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:396)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:492)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:325)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:201)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:75)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:260)
	at com.puppycrawl.tools.checkstyle.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:121)
	at com.puppycrawl.tools.checkstyle.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:108)
	at com.puppycrawl.tools.checkstyle.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:95)
	at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheckTest.testDefault(FinalLocalVariableCheckTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

So my changes prevent user from using incorrect tokens from configuration and do not throw NPE.

**Comment by MEZk** [comment]
@romani 
Please move it to separate PR, it is huge and it is very time consuming to verify it again and again.

Done, see https://github.com/checkstyle/checkstyle/pull/1723

**Comment by MEZk** [comment]
@romani 
Maybe we should create seperate PR for FinalLocalVariableCheck and MethodCountCheck to solve problems in getAcceptableTokens, getRequiredTokens and getDefaultTokens.

**Comment by romani** [comment]
1) Please separate  FinalLocalVariableCheck and MethodCountCheck to separate PR.

2) 
>  all_checks_with_default_config.xml

can you load all Check from classpath by java? by special XML file you make it easy to introduce new Check and forget to update that file.

**Comment by MEZk** [comment]
@romani 
Please, take a look at [AllChecksWithDefaultConfigTest](https://github.com/MEZk/checkstyle/commit/dc0b1d99e0a8d7a5a7407f76db2eba2913a74b40#diff-77bfd3865009a55956759f167933c352R35)

**Comment by romani** [comment]
thanks a lot ! merged as FF

I reverted fix for switching method to abstract as we will do that in 7.0 version , as it is serious incompatibility with all Checks that exists in the world.

**Pull request closed without merging**
