### PR TITLE
Issue #14014: Ignore left curly in line wrapping indentation handler

### LINKED ISSUE #14014: Indentation: Switch expression doesn't pass with LeftCurlies on newlines
I have read check documentation: https://checkstyle.sourceforge.io/checks/misc/indentation.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
$ javac Test.java
$ cat Test.java
public class Test
{
    public void test()
    {
        String otherValue = switch("test") 
        {  // violation
            case "test" -> "hi";

            default -> null;
        };
    }
}
$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="Indentation"/>
  </module>
</module>
$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
$ java $RUN_LOCALE -jar checkstyle-10.12.4-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/markus/tmp/checkstyle-test/Test.java:6:9: '{' has incorrect indentation level 8, expected level should be 12. [Indentation]
Audit done.
Checkstyle ends with 1 errors.

$ javac Test.java
$ cat Test.java
public class Test
{
    public void test()
    {
        String otherValue = switch("test") 
            {
            case "test" -> "hi";

            default -> null;
        };
    }
}
$ java $RUN_LOCALE -jar checkstyle-10.12.4-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/markus/tmp/checkstyle-test/Test.java:6:13: 'switch lcurly' has incorrect indentation level 12, expected level should be 8. [Indentation]
Audit done.
Checkstyle ends with 1 errors.
```

---

**Describe what you expect in detail.**
Checkstyle can be passed, following the suggested outputs of the Indendation check is just an infinite loop.
Note that I intentionally left out the `LeftCurly` module with `option=nl` as it's not needed to reproduce this

### PR DESCRIPTION
**Pull request by jungm**
This fixes #14014 

Diff Regression config: https://gist.githubusercontent.com/jungm/22d6a6a07b5505de2abadc3f68f9e418/raw/697705cfa8a06a514d5c163746de8a7c40391923/config.xml
Report label: forceStrictCondition=true

### CODE REVIEW

**Comment by romani** [comment]
Good.
Please trigger automatic regression by GitHub action
Please read https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#executing-generation

Example on how we do this: https://github.com/checkstyle/checkstyle/pull/13424 but you need config with indentation check only. There are more examples in PRs.

**Comment by jungm** [comment]
GitHub, generate report

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Please do:
1. Generate another regression report using the module at https://checkstyle.sourceforge.io/checks/misc/indentation.html#Example3-config
2. Create new test/test input using exact configuration and code from issue report, also showing violations on under-indented `{`

**Comment by jungm** [comment]
GitHub, generate report

**Review by romani — APPROVED** [review]
Ok to merge

**Review by nrmancuso — APPROVED** [review]
Awesome, thanks a lot for your contribution!

**Comment by romani** [comment]
@jungm , as we going close to merge, please let me know if you need this fix to be released after merge. We can trigger release.

**Review by rnveach — APPROVED** [review]

**Comment by jungm** [comment]
@romani a release would be awesome!
Not 100% required from my side, but I would obviously prefer it over using a snapshot build

**Comment by romani** [comment]
@jungm , thanks a lot for fix
https://checkstyle.org/releasenotes.html#Release_10.12.5 

do not hesitate to send more PRs with fixes :) .

**Pull request merged**
