### PR TITLE
Issue #5409: fixed intellij 2017.3 violations part 1

### PR DESCRIPTION
**Pull request by rnveach**
Issue #5409 

I will generate regression on the changes in the Check.

The sheer amount of duplication in `AvoidEscapedUnicodeCharactersCheck` is very sad.
I will create another issue once this PR is merged to sort the unicodes and split them apart better so they are easier to read.

### CODE REVIEW

**Comment by rnveach** [comment]
Travis failure is because Issue isn't approved.

**Comment by rnveach** [comment]
Here is regression: http://rveach.no-ip.org/checkstyle/regression/reports/152

No differences.

**Comment by romani** [comment]
Please make a copy paste of  violations you try to resolve to let verify you actions

**Comment by rnveach** [comment]
http://rveach.no-ip.org/checkstyle/regression/reports/issue5409.html
Fixes all `RegExp group   145 warnings`.
Fixes all `Error handling group   1 warning`.
Fixes all `Memory issues group   1 warning`.

**Pull request merged**
