### PR TITLE
Remove assignments to variables declared in for statements. #1555

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
1)
> private static String stripOffCheckstylePrefix(String value) {

that is not good, please use local variable with different name in LOOP instead. Your method is not single exit point also ;) .

2)
>         for (int i = 0; i < line.length(); i++) { 

FOR is used to hide "i" in its scope, moving it out scope is not good - we fix one issue and create another. Can we remove "i++" and do that ourself in FOR body?

**Comment by mkordas** [comment]
Regarding 2) - this would introduce another violation - there is inspection `Reports for loops that lack initialization, condition, or update clauses.`

**Comment by romani** [comment]
after additional review...

We definitely have conflicts of Checks/Rules :) , not a rare case.

Extending scope of variable is a sin as making fields as public for no reason. "Reports for loops that lack initialization, condition, or update clauses." is controversial as it demand FOR to be fully declared in curly braces (author of that validation rule forget that re-factoring from FOR to WHILE disclosure of iterator appear).

Absence of  incrementation part in FOR is easy to catch by user, so we do not make logic more obscure, in comparison to WHILE they are identical from this perspective, in FOR does not extend visibility of iterator variable.

Please disable "Reports for loops that lack initialization, condition, or update clauses." in configuration with appropriate comment.

**Comment by mkordas** [comment]
Let's fix that in #1642.

**Comment by mkordas** [comment]
>Extending scope of variable is a sin as making fields as public for no reason
I don't think it is a sin, because all methods should be small and they should do exactly one thing - then scope of variable is small anyway :)

**Pull request closed without merging**
