### PR TITLE
issue969: Fix upper/lower case conversation, enhance tests

### PR DESCRIPTION
**Pull request by precoder**
Upper/lower case conversations fixed for issue #969 .
Find bugs configuration related with #896 removed.
Both
mvn clean install
mvn verify
builds successfully. 
CLI test command mentioned in issue #969 runs successfully after this fix.

### CODE REVIEW

**Comment by romani** [comment]
Thanks a lot !!!!

merged as FF.

Next time please make a ref to issue in comment as ".... . Issue #969". Github will do a link to issue automatically.

**Comment by precoder** [comment]
You are always welcome, It was a nice experience for me.
I have also learned a lot about the github workflow.
If there are any other improvements I can do in my free time I would want to help in the future..

**Comment by romani** [comment]
you can select any unassined issue, or i can suggest an issue, please let me know your choice

**Comment by precoder** [comment]
I can reproduce issue #1018 
but it seems to be also related with issue #596 under your comment point 7.
I can take it or you can assign any other issue to me.

**Comment by romani** [comment]
@precoder, #926 is assigned to you, please switch all further talks to mail-list https://groups.google.com/forum/#!forum/checkstyle-devel to avoid polluting issues with unrelated comments.

**Pull request closed without merging**
