### PR TITLE
Issue #13321: Kill mutation for JavadocMethod-10

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for JavadocMethod-10

-----

# Check :- 
https://checkstyle.org/checks/javadoc/javadocmethod.html#JavadocMethod

-----

# Mutation 
https://github.com/checkstyle/checkstyle/blob/d4b1aec93f4c9e3d6b8eeed8556187e342c1bb33/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L93-L100
and 
https://github.com/checkstyle/checkstyle/blob/d4b1aec93f4c9e3d6b8eeed8556187e342c1bb33/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L219-L334

-----

# Explaination
I found this code non used

-----

# Regression :- 

Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/61dfc10_2023134726/reports/diff/index.html

Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/61dfc10_2023162021/reports/diff/index.html

-----

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/df2ff7a8f9969bb2c68d7251a97ffa8b/raw/6a4e81a624fa36483f23b0adcf1fc513ca6df350/JavadocMethod.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/21e3934e85f802e2fbd48af06d122364/raw/604256badd733d8568064f371d55657c04b00dfd/test-projects-2.properties
Report label: Regression-1

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
I can see this code is useless doing nothing

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
@Kevin222004 , please resovle conflict and prepare PR for review.

**Comment by Kevin222004** [comment]
https://github.com/checkstyle/checkstyle/pull/13356#issuecomment-1657185905 done ci passed

**Review by romani — APPROVED** [review]
Ok to merge.
Impressive!

**Review by rdiachenko — APPROVED** [review]
lgtm

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

**Pull request merged**
