### PR TITLE
Issue #2818: Add support for lambda expression in LeftCurlyCheck

### PR DESCRIPTION
**Pull request by liscju**

### CODE REVIEW

**Comment by romani** [comment]
1)
> InputLeftCurlyNewLineOptionWithLambda

please add comment "// compilable with java8",  look at other files. files with such comment will be used in compilation check by Travis.

2)
code is ok, I am ready to merge your code.

**Comment by liscju** [comment]
@romani , added "//Compilable with Java8" to InputLeftCurlyNewLineOptionWithLambda.java

**Comment by liscju** [comment]
@romani, cirlceci error is:
```
Testing Checkstyle started
Cloning hg repository 'openjdk' to src/main/java/openjdk folder ...
requesting all changes
adding changesets
transaction abort!
rollback completed

abort: Connection reset by peer case $CIRCLE_NODE_INDEX in 0) eval $TEST_1 ;; 1) eval $TEST_2 ;; 2) eval $TEST_3 ;; 3) eval $TEST_4 ;; esac returned exit code 255
```

**Comment by romani** [comment]
relaunched , but Travis have problems with UTs  https://travis-ci.org/checkstyle/checkstyle/builds/109728014

**Comment by liscju** [comment]
@romani, UTs are fixed

**Comment by romani** [comment]
Travis is not happy, as you propose non compilable code :) . Please fix.
https://travis-ci.org/checkstyle/checkstyle/jobs/109754183#L120

**Comment by liscju** [comment]
@romani fixed this :P sorry for wasting valuable maintainer time for such issues

**Comment by romani** [comment]
keep an eye on CIs.
I will not merge is CI is red. If CI is not right, CI need to be fixed first.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
