### PR TITLE
Issue #11131: replace 'if' with assumeTrue/False in tests

### LINKED ISSUE #11131: Replace assertions guarded by 'if' with assumeXXX methods in tests
Leftover of #10932

There were some if in the tests due to the incompatibility of Powermock with assumeXXX.

Detected by @rnveach at #10932 (comment)

### PR DESCRIPTION
**Pull request by pbludov**
Fixes #11131

This is leftover of #10932 

There were some `if` in the tests due to the  incompatibility of Powermock with `assumeXXX`.

Detected by @rnveach at https://github.com/checkstyle/checkstyle/issues/10932#issuecomment-1001087308

### CODE REVIEW

**Comment by rnveach** [comment]
why not assign it to the issue if its leftover?

**Comment by romani** [comment]
@pbludov , please fix conflict

**Review by romani — APPROVED** [review]
Ok to merge

https://howtodoinjava.com/junit5/junit-5-assumptions-examples/

**Comment by pbludov** [comment]
> why not assign it to the issue if its leftover?

Created #11131

**Review by rnveach — APPROVED** [review]
File conflict.

**Pull request merged**
