### PR TITLE
Issue #2161: unify test input locations for javadoc package

### PR DESCRIPTION
**Pull request by rnveach**
3rd time is the charm

### CODE REVIEW

**Comment by rnveach** [comment]
appveyor is the other problem I'm not sure how to fix
https://ci.appveyor.com/project/Checkstyle/checkstyle/build/2289/job/ihvk6878l7x9dy76#L646

**Comment by romani** [comment]
I need to recheck that path to file is not hardcoded in settings.

**Comment by romani** [comment]
from TC:
```
JavadocParseTreeTest.java (1)
68: getPath() Method getPath() may be 'static'
```

**Comment by romani** [comment]
now MaxOS is failing with the same error - NoClassDefFound, so issue is more or less stable - https://travis-ci.org/checkstyle/checkstyle/jobs/85443210#L2193 .

What OS you use on your local ?

**Comment by rnveach** [comment]
I missed the static message. It is fixed.

My local is Windows with Eclipse Luna.
I am getting the NoClassDefFound exception locally, but I don't see how my changes made it.
When I get off work, I'll play around with it more. I don't have my IT folder compilable, so maybe that will help me.

**Comment by rnveach** [comment]
@romani I think I figured it out.
The test file InputJavaDocTagContinuationIndentation had a class named JavaDocTagContinuationIndentation, which is in the same package and has the same class name as the actual Check. I believe the compiler was getting confused between the 2, used the wrong one, and caused the exception.
I assume Eclipse didn't complain because it's the test folder.

**Comment by romani** [comment]
merged as FF

**Pull request merged**
