### PR TITLE
Issue #15456: Specify violation message for Nested Block  

### PR DESCRIPTION
**Pull request by Pakhi-7831**
Issue #15456: Specify violation message for Nested Block

### CODE REVIEW

**Comment by romani** [comment]
Please read and watch videos on how to succeed in first contributions https://checkstyle.org/beginning_development.html#Starting_Development

you do not need to close PR to fix problems in branch, it almost impossible to write code that pass CI on first try, so amendments always happens.

**Review by romani — APPROVED** [review]
ok to merge if CI pass.

thanks a lot !!!

**Comment by Pakhi-7831** [comment]
> Please read and watch videos on how to succeed in first contributions https://checkstyle.org/beginning_development.html#Starting_Development
> 
> you do not need to close PR to fix problems in branch, it almost impossible to write code that pass CI on first try, so amendments always happens.

ok, will keep this in mind in the future, thanks!!

**Comment by romani** [comment]
@Pakhi-7831 , please do one more update for messages in some javadoc check to make sure you practiced amendments of PRs.
thanks in advance

**Pull request merged**
