### PR TITLE
Issue #1293: Improved coverage for ReturnCountCheck

### PR DESCRIPTION
**Pull request by baratali**

### CODE REVIEW

**Comment by baratali** [comment]
I'm fixing

**Comment by baratali** [comment]
Problem with TreeWalkerTest
```
Running com.puppycrawl.tools.checkstyle.TreeWalkerTest
Aug 05, 2015 5:30:47 PM com.puppycrawl.tools.checkstyle.TreeWalker processFiltered
SEVERE: TokenStreamRecognitionException occurred during the analysis of file C:\Users\appveyor\AppData\Local\Temp\1\junit2279633045981160930\file.java.
Aug 05, 2015 5:30:47 PM com.puppycrawl.tools.checkstyle.TreeWalker processFiltered
SEVERE: NoViableAltException occurred during the analysis of file C:\Users\appveyor\AppData\Local\Temp\1\junit7968588349812936247\file.java.
C:\Users\appveyor\AppData\Local\Temp\1\junit7968588349812936247\file.java:1:2: unexpected token: classD
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:180)
	at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:460)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:197)
	at com.puppycrawl.tools.checkstyle.TreeWalkerTest.testProcessWithParserTrowable(TreeWalkerTest.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
 
Aug 05, 2015 5:30:47 PM com.puppycrawl.tools.checkstyle.TreeWalker registerCheck
WARNING: Check 'com.puppycrawl.tools.checkstyle.TreeWalkerTest$BadJavaDocCheck' waits for comment type token ('SINGLE_LINE_COMMENT') and should override 'isCommentNodesRequred()' method to return 'true'
```

**Comment by baratali** [comment]
It seems that error message is different on Windows: https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheckTest.java#L81

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
