### PR TITLE
Ignore non-private members in VisibilityModifierCheck when annotated.

### PR DESCRIPTION
**Pull request by emilong**
This PR is in response to an old feature request (http://sourceforge.net/p/checkstyle/feature-requests/597/) that I also wanted. :)

### CODE REVIEW

**Comment by romani** [comment]
thanks for helping us to move stuff from old  issue tracker to new place.

Some items to fix before merge:

1) 
> mIgnoredAnnotationFormat

please make it static final private.

2) 
> mIgnoreAnnotated
> mIgnoredAnnotationPattern

too much class members, please keep only mIgnoredAnnotationPattern with default value from mIgnoredAnnotationFormat, get exp should be applied each time.

3) 
> throw new ConversionException("unable to parse " + aPattern, e);

rethrow to top, Check do not know what to do on failure, it is business of top level

4) 
> + final DetailAST firstIgnoredAnnotation =
+ AnnotationUtility.containsMatchingAnnotation(aAST, getIgnoredAnnotationPatternRegex());
+ final boolean hasIgnoredAnnotation = mIgnoreAnnotated
+ && firstIgnoredAnnotation != null;

please make it like a function and move after " !"private" " condition , the easiest conditions go first.

5) 

> + public static DetailAST containsMatchingAnnotation(final DetailAST aAST,
+ Pattern aAnnotationPattern)

please move that method to check as static function. Changes to API package is not allowed. I am sorry that we have utils in API, we will fix that soon.
Additionally please use 1 return point from method.

6) 
> throw new NullPointerException("the aAST is null");

please never throw NPE, use IllegalAgrument

7) Please recheck code coverage report, coverall detected decrease in coverage that usually sign of smth obvious missed.

**Comment by romani** [comment]
pelase rebase that change from checkstyle:master, we applied huge code refactoring, sorry if that seriously harden your work.

**Comment by emilong** [comment]
Hi @romani - thanks so much for taking time to review the code in detail! I'll address your comments in a few days when I have time to revisit.

**Comment by romani** [comment]
@emilong, is there any chance to provide update in next 7 days (for example) ?

If not, we could update your PR to proper state, but you most likely will loose your author reference on that changes.

**Comment by alexkravin** [comment]
@romani,

I think you can close this PR as I referenced these changes in #689

**Pull request closed without merging**
