### PR TITLE
Issue #7270: change repeat of header to repeat-x

### PR DESCRIPTION
**Pull request by jo2**
Issue: #7270 

image

### CODE REVIEW

**Comment by romani** [comment]
Yes, there are bunch of changes from others

**Comment by jo2** [comment]
Those changes happend due to the rebase on the current checkstyle/master. had to do this because travis ci kept failing due to the original master being more than 10 commits old. I don't why git didn't recognize those changes as the changes happend in master though.

**Comment by romani** [comment]
To fix wercker please rebase one more time, I merged fix yesterday.

**Comment by rnveach** [comment]
travis failures seem unrelated as they are seen in another PR.

**Pull request merged**
