### PR TITLE
Issue #2880 - fixing non-compilable java 8 code

### PR DESCRIPTION
**Pull request by rnveach**
Some commits and code could use some fixing, but this gets the basic idea across.
Mostly opening this to ask for help on specific areas by making comments on them.

Travis failure is only from Java 8 code that is failing to compile.
Current count is 13 errors in 6 files.

I made a new folder, resource-java8, to hold all compilable java8 code. I thought this was better then building a black list of all the files in noncompilable to not copy over for compiling.

### CODE REVIEW

**Comment by romani** [comment]
@rnveach , this way I can not help you ,as I do not know is you do a comment for yourself or it is as question.

for idea of java8 folder ..... it looks a bit complicated.
What is we adjust Travis to use "$JAVA_HOME/bin/javac" to compile files that we would like 
```
$ javac checkstyle/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammars/java8/Input*
grammars/java8/InputMethodReferences3.java:14: error: not a statement
    MyClass<T>::myMethod;
           ^
grammars/java8/InputMethodReferences3.java:14: error: ';' expected
    MyClass<T>::myMethod;
              ^
grammars/java8/InputMethodReferences3.java:14: error: not a statement
    MyClass<T>::myMethod;
                ^
3 errors
```

All incorrect file that we need for testing we could rename to have in name "Incorrect" so we will filter them out.

**Comment by rnveach** [comment]
@romani 
>  I do not know is you do a comment for yourself or it is as question.

All comments on code are questions asking for help fixing the line to compile.
First line is the compile error eclipse gives me. Second line is the check it is tied to and if this line is dependent on any code coverage and the lines the coverage is on. Code coverage means it must be fixed in a precise way and if we decide to remove the line, the check must change to be 100% code coverage. The rest of the text is just my comments on what the CC is looking for and thoughts.

**Comment by romani** [comment]
so summary is:
1) all Inputs that are required by Check need be moved to spacial Input file that will be out of java8 folder and create special issue on it. All proposal and discussions need to be moved to new issue.
2) Travis need to be updated to compile java8 sources separately by javac, list of java8 files need to be created by shell command (no hardcodes for input file names in Travis).

**Comment by rnveach** [comment]
@romani 

> Input file that will be out of java8 folder 

We can move the file to a separate folder from the Check, but we recently just made it so all inputs for a check are in the same package as the Check itself. Even if we just put a copy of the file into java8, we will lose compile check for validity on its original if it is ever modified for future issues.
Please decide if you want:
1) all inputs in the package they belong to, or
2) to make java8 a special case and move all java 8 input files into the `grammars\java8` folder and renamed to have their check as part of the file name, or
3) let me know if you have any other ideas.

My plan to find all Java8 input files in their subfolders for travis compile check was to just rename the files to the pattern `InputJava8*.java`, keeping them in their current folders, and use something like the command `javac $(find src/test/resources-noncompilable/* | grep 'InputJava8.*\.java')` (source: http://stackoverflow.com/a/5194940).

**Comment by romani** [comment]
right now 
checkstyle/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/InputSuperClone.java is located in `resources-noncompilable` and used by Check. That is not correct , I do not know how I missed this file to appear in this folder but it does not matter now.
This file has to stay there till we fix the Check+coverage+..... . Separate issue need to be created for this, it is not related to java8 at all.

> 2) to make java8 a special case and move all java 8 input files into the grammars\java8 folder and renamed to have their check as part of the file name,

Right now all java8 sources that are used by Parser UTs should be there.
https://github.com/checkstyle/checkstyle/tree/master/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammars/java8

There might be another Inputs that are used by Checks, we will move them to appropriate package on a moment of moving to compilable resources folder.

> all inputs in the package they belong to

we could make an order in non-compilable resources too, but please do this in separate commit or PR.

> My plan to find all Java8 input files in their subfolders 

Please find all files that contains "//Compilable with Java8". Looks like there are a lot of java8 files in `checks` folder. If comment is missed please add it.

**Comment by rnveach** [comment]
@romani 
I made all java 8 files to the `grammars/java8` directory and gave them names based on what type of java 8 they are testing and the check that uses them for the test. I gave them the comment "//Compilable with Java8".

> all java8 sources that are used by Parser UTs should be there... grammars/java8
> Please find all files that contains "//Compilable with Java8"

Since we are moving the files to `grammars/java8`, I thought it easier to have the command just look in that directory for all the files to compile check. 3 files currently have this tag outside that directory that need to be fixed in the next issue to be compilable.

**Comment by romani** [comment]
>
```
 -        verify(checkConfig, getNonCompilablePath("InputSuppressWarningsHolder.java"), expected);
+        verify(checkConfig, getJava8Path("InputSuppressWarningsHolder.java"), expected);
```

I do not understand this . Why check/module should use grammar tests ?  I know that we might still have examples where Checks use non-their Inputs. But this is not good.

**Comment by rnveach** [comment]
@romani Is this better? No files moved, just fixed their compile issues and added their java 8 comment.

The following files had their comment about compilable by java 8 removed until we fix them: `InputFinalLocalVariableNameLambda`, `InputIllegalInstantiation2`, `InputInnerAssignmentLambdaExpressions`

**Comment by romani** [comment]
merged as FF.

thanks a lot !!

**Pull request closed without merging**
