### PR TITLE
Issue #13213: Remove '//ok' from atclauseorder

### PR DESCRIPTION
**Pull request by OmarShawky1**
Part of Issue #13213 

# Updates
1. Removed *atclauseorder* suppresion rules from checkstyle-input-suppressions.xml
2. Removed unnecessary // ok from all previously suppressed java files accordingly.

Edit: I have no clue why the 6 tests are failing but I expect that they are from the past configurations. Please help me figure it out if I didn't get it.

### CODE REVIEW

**Comment by nrmancuso** [comment]
>Removed unnecessary // ok from all previously suppressed java files accordingly.

This isn't done, and is why CI is failing. Please update these files and make sure that `mvn clean verify` is passing on your local before pushing your changes up.

**Comment by OmarShawky1** [comment]
Sorry. forgot to add files before amending while pushing :D

**Comment by OmarShawky1** [comment]
Did I miss something? The edit has been up for 3 days.

**Review by romani — APPROVED** [review]
Ok to merge

**Pull request merged**
