### PR TITLE
config: bump sevntu to 1.36.0

### PR DESCRIPTION
**Pull request by romani**

### CODE REVIEW

**Comment by romani** [comment]
https://storage-download.googleapis.com/maven-central/index.html

>and updated again 11/7/2019

So need to wait for sync completion

**Comment by romani** [comment]
After new artifact appeared at https://mvnrepository.com/artifact/com.github.sevntu-checkstyle/sevntu-checks it become available at Google mirror.

From https://storage-download.googleapis.com/maven-central/index.html

>We are currently mirroring the repo 12 times a day for the Americas bucket and 4 times / day for EU & Asia.

So looks like artifact should appear in Maven search index first, be synced to Google mirror.

Travis was restarted

**Comment by rnveach** [comment]
@romani 5 tests failed.
https://travis-ci.org/checkstyle/checkstyle/jobs/614013497#L1097

**Comment by romani** [comment]
Failures looks unrelated but :
```

[ERROR] Failures: 
[ERROR]   CheckerTest.testDefaultLoggerClosesItStreams:1337 Flush count was not expected expected:<3> but was:<4>
[ERROR]   CheckerTest.testXmlLoggerClosesItStreams:1362 Flush count was not expected expected:<0> but was:<1>
[ERROR]   XpathFileGeneratorAuditListenerTest.testCorrectOne:168->verifyOutput:309 expected number of flushes expected:<1> but was:<2>
[ERROR]   XpathFileGeneratorAuditListenerTest.testCorrectTwo:199->verifyOutput:309 expected number of flushes expected:<1> but was:<2>
[ERROR]   XpathFileGeneratorAuditListenerTest.testOnlyOneMatching:227->verifyOutput:309 expected number of flushes expected:<1> but was:<2>
[INFO] 
[ERROR] Tests run: 3363, Failures: 5, Errors: 0, Skipped: 0
```

**Comment by romani** [comment]
Ok, now behavior is consistent, we have the same on master build https://travis-ci.org/checkstyle/checkstyle/jobs/614737434#L1095

I am merging this PR

**Pull request merged**
