### PR TITLE
Issue #7413: remove obsolete import handling from JavadocMethodCheck

### PR DESCRIPTION
**Pull request by rnveach**
Issue #7413

This is the only thing left I can see that can be done from the remains of my old #7116 branch.

Regression to come.

### CODE REVIEW

**Comment by romani** [comment]
Probably minor is not good prefix, as we remove token from acceptable list, plugins will be affected.

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/281/

No differences.

**Comment by rnveach** [comment]
Waiting on CI to pass before re-pushing.

**Comment by rnveach** [comment]
CI passed. Just renamed commit.

**Pull request merged**
