### PR TITLE
Issue #11720: Kill surviving mutation in DefaultLogger related to closing streams

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
#11720 

### Diff Reports:
 N/A

The missing test case was added.

### CODE REVIEW

**Comment by nick-mancuso** [comment]
@Vyom-Yadav please resolve conflicts

**Comment by Vyom-Yadav** [comment]
> @Vyom-Yadav please resolve conflicts

Done.

**Comment by nick-mancuso** [comment]
@Vyom-Yadav  please resolve one more time :)

**Comment by Vyom-Yadav** [comment]
@nick-mancuso Done :)

**Review by baratali — APPROVED** [review]

**Review by nick-mancuso — APPROVED** [review]

**Comment by nick-mancuso** [comment]
Travis build failure and no-error-xwiki failure are not related to changes in this PR.

**Pull request merged**
