### PR TITLE
Issue #8602: Make getter method for sourceClass in LocalizedMessage

### PR DESCRIPTION
**Pull request by HuGanghui**
Issue #8602: Make getter method for sourceClass in LocalizedMessage

### CODE REVIEW

**Comment by HuGanghui** [comment]
@romani please approve Issue  #8602

**Comment by HuGanghui** [comment]
local test is build success, but now 

* wercker/build — Wercker pipeline failed, and I can not see where have problem, please give me some help.
* continuous-integration/travis-ci/pr  need approve issue
* ci/circleci: pitest8 — Your tests failed on CircleCI.  [ERROR] Failed to execute goal org.pitest:pitest-maven:1.4.9:mutationCoverage (default-cli) on project checkstyle: Mutation score of 99 is below threshold of 100 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.pitest:pitest-maven:1.4.9:mutationCoverage (default-cli) on project checkstyle: Mutation score of 99 is below threshold of 100

**Comment by romani** [comment]
@HuGanghui , please rebase to resolve CIs

**Comment by HuGanghui** [comment]
rebased, now **continuous-integration/travis-ci/pr** need approve issue

**Comment by HuGanghui** [comment]
this issue can be solved by another way, so this PR is not needed now.

**Pull request closed without merging**
