### PR TITLE
Issue #11163: Enforced file size commentsindentation

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Part of #11163 
Enforced filesize on remaining checks of commentsindentation module.

### CODE REVIEW

**Comment by MANISH-K-07** [comment]
@romani 
The failing checks are Cirrus - JDK17 and two other checks because of the Out of Memory exception.
Screenshot_2024-01-24-03-28-19-39_40deb401b9ffe8e1df2f1cc5ba480b12
And..
Screenshot_2024-01-24-03-30-12-87_40deb401b9ffe8e1df2f1cc5ba480b12

All others are green.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/7630359181/job/20785856626?pr=14338#step:6:101

This is growing concerns, .... It will be messy if we continue to merge without workaround.

**Comment by romani** [comment]
@MANISH-K-07, do you able to reproduce this problem of Checker on your local ?

**Comment by MANISH-K-07** [comment]
> @MANISH-K-07, do you able to reproduce this problem of Checker on your local ?
> 
> I restarted Checker method-resource..... .

In fact NO, the build is a clean success and the problem with Checker checks does not show on my local system.
However, I agree that the failing CI on the server is a huge pain and needs to be resolved asap.
I'm not sure if this is relevant but my system is 64 bit and I have preset the heap size of JVM to 8192m.

**Comment by MANISH-K-07** [comment]
> https://github.com/checkstyle/checkstyle/actions/runs/7630359181/job/20785856626?pr=14338#step:6:101
> 
> This is growing concerns, .... It will be messy if we continue to merge without workaround.

**_@romani_**  , I was kind of waiting for you to raise this!!

Ever since the OOM exception started to pop up, I have tried to find a workaround by searching for all possible alternatives to resolve this issue and in the process read the [Oracle Java Documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/memleaks002.html).  After a bit of understanding, the only thing that came to my mind was to **_expand the memory size of the JVM's heap_**. The [OOM exception/issue](https://github.com/checkstyle/checkstyle/actions/runs/7630359181/job/20785856626?pr=14338#step:6:101) at hand is the result of the Gc using up >98% of the mem. 
As per my understanding of the [pom.xml](https://github.com/checkstyle/checkstyle/blob/master/pom.xml) , the preset initialmem and maxmem for the Checker checks are 1024m & **_4048m_** respectively, which obviously is the root cause of the problem at present.

**_Proposed fix :_** 
I think expanding the maxmem to higher size (like 8192m as in my local system or whatever **limit that you recommend**) is most likely to resolve this issue. I can try to implement the said fix by changing the preset maxmem for Checker Framework so that this is of no longer concern to the project.

Correct me if my understanding is wrong anywhere, elsewise Should I raise an Issue regarding this?
I would love to work on said issue and guarantee to resolve it most likely by EoD or tomorrow!!

**Comment by MANISH-K-07** [comment]
So, I have tried and implemented the proposed fix by expanding the maxmem to 8192m on a new branch on my system 
and the build is a success!!
There are no errors or warnings. The code works completely fine....

image

**Comment by romani** [comment]
@MANISH-K-07, thanks a lot for explanation, please send PR to increase memory.

**Comment by MANISH-K-07** [comment]
> @MANISH-K-07, thanks a lot for explanation, please send PR to increase memory.


Done..

I raised a new Issue [#14346](https://github.com/checkstyle/checkstyle/issues/14346) stating the problem at hand.
Also, I have created a PR [#14347](https://github.com/checkstyle/checkstyle/pull/14347) in which I have implemented the fix.

**_All it needs is your approval...._**

Hope this works as expected and the failing CIs are of no further concern to the project!!

**Review by romani — APPROVED** [review]
Ok to merge

**Pull request merged**
