### PR TITLE
Issue #7582: Adds examples to doc for LeftCurly

### PR DESCRIPTION
**Pull request by Perin-Mangukiya**
Issue: #7582, adds examples for option 'nlow'

### CODE REVIEW

**Comment by romani** [comment]
GitHub, generate website

**Comment by Perin-Mangukiya** [comment]
I had made changes. Please run the checks again.

**Comment by Perin-Mangukiya** [comment]
@romani I had made changes. Please run the checks again.

**Comment by Perin-Mangukiya** [comment]
@romani  DONE

**Pull request closed without merging**
