### PR TITLE
Issue #13345: Enable IlegalTokenTextCheckExamplesTest

### PR DESCRIPTION
**Pull request by Coding-Aliens**
Issue #13345 
Problem dectected in src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/Example3.java
Text block isn't allowed in source11, replaced it with eleven space, "\" and one "

### CODE REVIEW

**Comment by romani** [comment]
Put issue number to PR description

**Comment by romani** [comment]
Please recheck https://github.com/checkstyle/checkstyle/blob/master/src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/Example1.java

This is how we handle test sources for modern jdk

**Comment by Coding-Aliens** [comment]
All right. Still working on it.

**Comment by romani** [comment]
Keep single commit always.
https://checkstyle.org/beginning_development.html#Starting_Development how to deal with git for rebase.

**Comment by Coding-Aliens** [comment]
OK, fixing conflicts

**Comment by Coding-Aliens** [comment]
Sorry to mess it up, there are too more commits, could you please close it? I will start a new pull request

**Pull request closed without merging**
