### PR TITLE
config: bump maven-compiler-plugin to 3.10.1

### PR DESCRIPTION
**Pull request by romani**
detected in azure 

https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=9169&view=logs&j=1a6076f9-5826-5ba0-19ba-deaff2e35eea&t=5f46bc98-6f46-512e-6656-5fbfb1d03e4d&l=577

### CODE REVIEW

**Comment by rnveach** [comment]
Why didn't dependabot notify us?

**Comment by romani** [comment]
I have no idea, but I noticed it by few weeks.

**Comment by pbludov** [comment]
> Why didn't dependabot notify us?

Version 3.10.0 is broken and was skipped: https://github.com/checkstyle/checkstyle/pull/11313

**Comment by pbludov** [comment]
Now the build is failing with
 ```
 [WARNING] Error creating missing package info classes
java.nio.file.NoSuchFileException: /home/travis/build/checkstyle/checkstyle/target/test-classes/org/checkstyle/suppressionxpathfilter/javadocstyle/SuppressionXpathRegression/package-info.class
    at sun.nio.fs.UnixException.translateToIOException (UnixException.java:92)
    at sun.nio.fs.UnixException.rethrowAsIOException (UnixException.java:111)
    at sun.nio.fs.UnixException.rethrowAsIOException (UnixException.java:116)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel (UnixFileSystemProvider.java:219)
    at java.nio.file.spi.FileSystemProvider.newOutputStream (FileSystemProvider.java:478)
    at java.nio.file.Files.newOutputStream (Files.java:220)
    at java.nio.file.Files.write (Files.java:3425)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.createMissingPackageInfoClasses (AbstractCompilerMojo.java:1364)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1229)
    at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:183)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
```

**Comment by pbludov** [comment]
The source of this warning is that there is no parent directory for the generated package-info.class file.
The fix is already submitted: https://github.com/apache/maven-compiler-plugin/pull/121

**Pull request merged**
