### PR TITLE
Fixes #1224 NullPointerException at java.util.regex.Pattern from com.puppycrawl.tools.checkstyle.checks.regexp.DetectorOptions.getPattern

### LINKED ISSUE #1224: NullPointerException at java.util.regex.Pattern from com.puppycrawl.tools.checkstyle.checks.regexp.DetectorOptions.getPattern
I've hit the NPE below, funnily enough when using the Eclipse Checkstyle Plugin (v6.5.0 installed from http://eclipse-cs.sf.net/update today) on checkstyle's own code (this repository, not the Eclipse plug-in), and activating it's very own https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml !! ;-)

This NPE error clearly has nothing much to do with the Eclipse Plugin but comes from core CS.

I'll see if I still have the energy to submit a PR about this, or if I'll have to leave this one to you...

PS: Do you know if it's possible to easily update the core CS JAR used by the Eclipse Plugin?

```
Error
Thu Jun 18 19:43:03 CEST 2015
Errors running builder 'Checkstyle Builder' on project 'checkstyle'.

java.lang.NullPointerException
	at java.util.regex.Pattern.<init>(Pattern.java:1350)
	at java.util.regex.Pattern.compile(Pattern.java:1054)
	at com.puppycrawl.tools.checkstyle.checks.regexp.DetectorOptions.getPattern(DetectorOptions.java:200)
	at com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.processLines(MultilineDetector.java:70)
	at com.puppycrawl.tools.checkstyle.checks.regexp.RegexpMultilineCheck.processFiltered(RegexpMultilineCheck.java:51)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:270)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:159)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:300)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:171)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by romani** [comment]
1) 
> "empty.regexp";

make it "regexp.empty"

2)
>  if (Strings.isNullOrEmpty(options.getFormat())) {
 options.getReporter().log(0, EMPTY);
 return;

please make single point of exit from method. Abrupt return is ok only certain cases, but not in your case.

**Comment by romani** [comment]
release 6.8 will be in 4 days, it will be good to finish that PR before.

**Comment by vorburger** [comment]
implemented both code review feedbacks

**Comment by romani** [comment]
please squash commits in one ans put at the end of commit message reference to github issue like (". #xxxxxxx")

**Comment by vorburger** [comment]
@romani  did you see I actually did do the squash 4 days ago? I was hoping you could merge this in time for 6.8 .. released yesterday, you missed to merge this one? Anything else holding you back from merging this?

**Comment by romani** [comment]
@vorburger , sorry I missed that, github did not notify about such changes, amount of posts did not change in PRs page so I did not take a look inside, preparation for 6.8 was busy ..... . Next time please do not hesitate to bother me with additional post to PR like "done".

I did gig regression in 6.8 release so I am going to do 6.8.1 - your changes will be included.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
