### PR TITLE
Issue #13097: Split filters xdocs into separate pages

### PR DESCRIPTION
**Pull request by stoyanK7**
Part of #13097

### CODE REVIEW

**Comment by stoyanK7** [comment]
Github, generate site

**Review by romani — APPROVED** [review]
Ok to merge if CI green.

@stoyanK7 , please fix CI

**Review by romani — APPROVED** [review]

**Comment by stoyanK7** [comment]
@nrmancuso Fixed conflicts.

**Comment by romani** [comment]
Github, generate site

**Comment by romani** [comment]
Semaphore failure is not related. We can merge after @nrmancuso approval.

**Review by nrmancuso — APPROVED** [review]

**Pull request merged**
