### PR TITLE
Issue #10811: Reviewed Translation

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
Fixes Issue #10811

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
GitHub, rebase

**Comment by Rahulkhinchi03** [comment]
I'll be fixing the CI in 1-2 days

**Comment by rnveach** [comment]
@Rahulkhinchi03 This PR is massive and too big for one PR.

Even putting that aside, I am not understanding how your works connect to the issue. The issue is about fixing translations, and even the issue itself is not clear and was never thoroughly clarified on each point and separation. I am also seeing changes outside of just simple translations as much java code is changed as well.

We need this pr/issue split and a clear idea of what is being changed and what reviewers are looking at.

**Comment by Rahulkhinchi03** [comment]
@rnveach what do you think I should do? Should I continue with PR or work on something else?

**Comment by rnveach** [comment]
@Rahulkhinchi03 As I said, to move forward we need this broken up into smaller pieces. Specifying what each change is doing and why.

I am just re-iterating what is said in the issue ( https://github.com/checkstyle/checkstyle/issues/10811#issuecomment-968374955 ) which you should read through before starting a PR.

**Comment by romani** [comment]
I agree this PR is not reviewable

**Comment by Rahulkhinchi03** [comment]
Okay I am closing this PR.

**Pull request closed without merging**
