### PR TITLE
Issue #2941: fixed incorrect expected indentations

### PR DESCRIPTION
**Pull request by rnveach**
If indentation expects a line to be at position `X,Y` then we should report `X,Y` not `A,B`.

On the 2 lines modified, right before them the indent variable being used when calling `isAcceptable` is completely different than the variable/values sent to the error message routine.

### CODE REVIEW

**Comment by romani** [comment]
Are you sure that functional changes - printed amount of suggested indentions is a "minor" ? 
I do not think so, please create issue or update this PR will all details to show how behaviour will change for users.

**Comment by rnveach** [comment]
Like I said, error messages aren't reporting the correct indentations in specific scenarios. The users will either see different expected indentation levels in the error message, or will see a new level of acceptable indentation.
I put this as minor, because I don't see this as changing functionality. We are not changing calculated indentation levels. We should always be reporting indentation levels we are checking against in our errors. These 2 cases don't do that. This is similar to checking if a number is a 5 and reporting an error saying we expected a 9.

Change 1 is in `BlockParentHandler.checkLCurly`:
The code is verifying indentation against `curlyIndent()` but if it is not acceptable, the error being reported is based on `getIndent()`. The difference between the 2 is the amount of `braceAdjustment`.
There are no tests that currently showcase this, but I found this while looking into a different indentation issue. As an example, the user will see expected indentation of `4,8,12` but we are actually checking against `8,12,16` (if `braceAdjustment` is 4).
I can provide a real example if it is needed.
 
Change 2 is in `ObjectBlockHandler.checkRCurly`:
The code is verifying indentation against a custom variable `level` but if it is not acceptable, the error being reported is based on `curlyIndent()`. The difference between the 2 is pretty big, as `level` has `braceAdjustment` plus a new acceptable indentation of `level's first indentation + lineWrappingIndentation`.
This is seen in the tests as a new indentation level is displayed in the error message. Test: https://github.com/rnveach/checkstyle/commit/7a73706f3b452898dcee34c377c0008fed7fe563#diff-88d68aaf0963249939255684219c43b1R781
Code: https://github.com/checkstyle/checkstyle/blob/0ac6fe40394082ddecdfb1919754ac81413f8045/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputInvalidArrayInitIndent.java#L40
`curlyIndent()` is always 4, adding the `lineWrappingIndentation` to it, which is a value of 4, always produces the value of 8. So the acceptable indentations are 4 and 8 in the tests, and not just 4.


Do you still want me to create an issue?

**Comment by romani** [comment]
> The users will either see different expected indentation levels in the error message, or will see a new level of acceptable indentation.

if user see a difference - it is not a minor. Please copy explanation to issue, and redo commit message.

**Comment by rnveach** [comment]
@romani Done. Issue #2941.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
