### PR TITLE
Issue #1254: Fix JavadocVariableCheck when assigning a lambda as a field

### PR DESCRIPTION
**Pull request by ARoundSquare**
https://github.com/checkstyle/checkstyle/issues/1254

### CODE REVIEW

**Comment by romani** [comment]
Please put to InputNoJavadocNeededInLambda comment that it is compilable by java8 ,  look at other files for example.
It will allow Travis find it and to validate it compilable status.

**Comment by Vladlis** [comment]
@ARoundSquare, please, rebase your PR on the latest master to avoid this kind of circleCI failure

**Comment by romani** [comment]
@ARoundSquare, please rebase your changes on latest code, checkstyle is switched to jdk8 for compilation (resources-noncompilable is not required any more java8 sysntax, it will even cause build problem on Travis)

**Comment by ARoundSquare** [comment]
Sorry for the lack of updates, work has been particularly stressful this past week. I should have it rebased and fixed up sometime this weekend.

**Comment by romani** [comment]
@ARoundSquare , ping .

**Comment by romani** [comment]
@ARoundSquare , is there any chance to continue ? 
If you do not have time please let me know, smb else will finish your work. I just do not want to keep this issue and PR blocked by you.

**Comment by MEZk** [comment]
@romani 
Please, close this one in favor of https://github.com/checkstyle/checkstyle/pull/3520

**Pull request closed without merging**
