### PR TITLE
Issue #4092: ClassFanOutComplexity: count complexity base annotations/extends/implements/methods params

### LINKED ISSUE #4092: ClassFanOutComplexity: count complexity base  annotations/exetend/implements/methods params
base on https://github.com/checkstyle/checkstyle/pull/3924#issuecomment-288740206

Check need to consider type usage in:
- annotations
- extends and implements (as interfaces could have behavior from java8)
- method parameters

Examples need to be added to xdoc to show users what affects a calculation.

### PR DESCRIPTION
**Pull request by shivanshsoni**
fixes #4092

### CODE REVIEW

**Comment by MEZk** [comment]
@shivanshsoni 
Please fix CIs violations. All CIs except for TeamCity CI should be green.

**Comment by rnveach** [comment]
@shivanshsoni ping

**Comment by shivanshsoni** [comment]
@rnveach Sorry Sir, I was very busy with my college projects and technical fest. I have full responsibility of a club. But I will be free today as today is last day of the technical fest. I will start this work from tomorrow and surely solve this issue. Sir, please try to understand.......

**Comment by rnveach** [comment]
@shivanshsoni ping
Do you still wish to continue with this?

**Comment by shivanshsoni** [comment]
@rnveach  Yes Sir I want to continue but I am busy with my finals these days...

**Comment by shivanshsoni** [comment]
I really want to be in GSOC. what should i do now?

**Comment by romani** [comment]
@shivanshsoni , please finish your PR.
rebase on latest our master to resolve all wercker and TC problems that are not related to your code

**Comment by shivanshsoni** [comment]
@romani Ok Sir

**Comment by romani** [comment]
if no action happen till 1st june, we will close this PR, to ease our management of PRs

**Comment by shivanshsoni** [comment]
@romani ok cool. I  will complete it before 20th may. It is my promise. My exams will end on  15th may and i will start work on this and other issues. 
Thanks for giving time.

**Comment by romani** [comment]
@shivanshsoni , ping, last warning before I close PR at the end of the week.

**Comment by romani** [comment]
connection with @shivanshsoni  is lost, PR is closed as incomplete.
If smb want to continue from scratch or from where @shivanshsoni is finished, please be welcome .

**Pull request closed without merging**
