### PR TITLE
Issue #9394: update example of AST for TokenTypes.ARRAY_DECLARATOR

### LINKED ISSUE #9394: update example of AST for TokenTypes.ARRAY_DECLARATOR
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#ARRAY_DECLARATOR

needs to be extended to show example of AST in format that printed by our CLI (change "+-" to "`-").
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

### PR DESCRIPTION
**Pull request by vivek286**
Closes #9394 
WhatsApp Image 2021-03-15 at 8 51 34 PM

Expected update example of AST for TokenTypes.ARRAY_DECLARATOR

WhatsApp Image 2021-03-15 at 8 58 17 PM

### CODE REVIEW

**Comment by vivek286** [comment]
@rdiachenko please review if you have time

**Comment by vivek286** [comment]
@romani, please review if you have time

**Comment by rdiachenko** [comment]
@vivek286 please update description according to https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes (check PR example mentioned)

**Comment by romani** [comment]
@vivek286 , please keep image of updated javadoc, not how it was before PR.

**Review by romani — APPROVED** [review]

**Pull request merged**
