### PR TITLE
Issue #2451: removed excess hierarchy from IllegalTokenTextCheck

### PR DESCRIPTION
**Pull request by rnveach**
'updateRegexp' is a new method to centralize creating the pattern.
Had to remove 'setCompileFlags' from AbstractFormatCheck to get code coverage to pass.

Everything else is a copy.

### CODE REVIEW

**Comment by rnveach** [comment]
I'll wait for my other PR to be accepted, then I'll restore 'setCompileFlags' and put this class on ignore for code coverage. It will be deprecated in 2 PRs.

**Comment by romani** [comment]
depends on #2500 .

**Comment by romani** [comment]
please rebase this PR

**Comment by romani** [comment]
@rnveach , please launch "mvn clean verify" on you local before PR to catch most problems before bothering Travis.

**Comment by rnveach** [comment]
@romani 
This computer I am currently on won't let me do a full verify.
> [ERROR] Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.0:validate (default) on project checkstyle: While parsing D:\Rickys\Java\checkstyleWorkspaceEclipse\checkstyle\src\site\resources\files\suppressions_none.xml: null: NullPointerException -> [Help 1]

Also, all I changed was the pom for suppressing coverage. I didn't think I could mess that up. :)

**Comment by romani** [comment]
merged as FF

**Comment by romani** [comment]
@rnveach , if your PC resources are limited, it might be convenient for you to use Travis for your account and your fork from us. You can validate your branches on your own Travis before doing PR , without waiting a queue :) . I some time do this when I need to test stuff on Windows.

**Pull request closed without merging**
