### PR TITLE
Issue #12241: removes package private constructors and pmd association

### PR DESCRIPTION
**Pull request by rnveach**
Issue #12241

### CODE REVIEW

**Comment by rnveach** [comment]
Issue isn't approved, so just that part of the CI is expected to fail.

**Review by romani — APPROVED** [review]
ok to merge.

I like no `package` visibility

**Review by nrmancuso — APPROVED** [review]
I am good with changes here, but it is not clear to me whether issue is fully closed by this PR or not.

**Comment by rnveach** [comment]
>  whether issue is fully closed by this PR

The issue is fully closed by this PR. No subsequent ones are planned.

What couldn't be changed in this PR (modifier back to `private`) is required to stay to continue to compile the project.

**Pull request merged**
