### PR TITLE
Update TokenTypes.java

### PR DESCRIPTION
**Pull request by shubham11941140**
Issue: #9515: update example of AST for TokenTypes.MINUS

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
@shubham11941140 Please see https://github.com/checkstyle/checkstyle/pull/9611, see how he has written the PR description. 
Adding cli and screenshots are strongly recommended.

Please edit your commit message: 
Commit message should adhere to the following rules:
```
a) MUST match one of the following patterns:
^Issue #\d+: .$
^Pull #\d+: .$
^(minor|config|infra|doc|spelling|dependency): .*$
b) MUST contain only one line of text
c) MUST NOT end with a period, space, or tab
d) MUST be less than or equal to 200 characters
```

**Comment by shubham11941140** [comment]
> 
> 
> @shubham11941140 Please see #9611, see how he has written the PR description.
> Adding cli and screenshots are strongly recommended.
> 
> Please edit your commit message:
> Commit message should adhere to the following rules:
> 
> ```
> a) MUST match one of the following patterns:
> ^Issue #\d+: .$
> ^Pull #\d+: .$
> ^(minor|config|infra|doc|spelling|dependency): .*$
> b) MUST contain only one line of text
> c) MUST NOT end with a period, space, or tab
> d) MUST be less than or equal to 200 characters
> ```

**Comment by pbludov** [comment]
please do not close PR, just do `git commit -a --amend` to update your PR, then `git push --force <branch> origin` to push the changes you made.

**Review by shubham11941140 — COMMENTED** [review]
Issue #9515.

**Comment by shubham11941140** [comment]
The code is perfectly working and I have edited my commit message, but it is still showing that some checks are not successful.

**Comment by Abhishek-kumar09** [comment]
Squash all your commits into one.

**Comment by shubham11941140** [comment]
How to squash all commits?

**Pull request closed without merging**
