### PR TITLE
Issue #4080: Split and Organize Checkstyle inputs by Test for SingleSpaceSeparator

### PR DESCRIPTION
**Pull request by wate123**
Issue: #4080

### CODE REVIEW

**Comment by rnveach** [comment]
@wate123 https://github.com/checkstyle/checkstyle/wiki/PR-rules
We are expecting only your commit. Please rebase off latest master and make sure your changes for `SingleSpaceSeparator` are in one commit.

**Comment by romani** [comment]
Please rebase your fix on our master, in PR should be only one commit - your changes

**Comment by wate123** [comment]
sure. I will. I mess up all my work..

**Comment by rnveach** [comment]
@wate123 You still need to rebase on latest master. You have conflicts.

**Comment by rnveach** [comment]
@wate123 ping

**Comment by wate123** [comment]
Sorry. I was too busy on my school homework. I will fix it soon.

**Comment by rnveach** [comment]
@wate123 ping

**Pull request closed without merging**
