### PR TITLE
Make Checkstyle GUI editor shows line number,column number and syntax

### PR DESCRIPTION
**Pull request by liscju**
highlighting, fixes part of #951. I used RSyntaxTextArea (https://github.com/bobbylight/RSyntaxTextArea) as the easiest way to get line numbering in jtextarea, what is more it supports highlighting java syntax. Secondly i added status bar below editor to show which line number,column number caret is targeting.

### CODE REVIEW

**Comment by romani** [comment]
1) please share screenshot of how that is looks now

2) please recheck with authors of that project that re-discribution in our ".......-all.jar" is ok for their License. https://github.com/bobbylight/RSyntaxTextArea/blob/master/src/main/dist/RSyntaxTextArea.License.txt , I would ask them on forum or as github issue. 
Please recheck that after our "-all.jar" generation we have their license in it.

3) Testing. As you might notice that we do huge fight with non tested code now. GUI is sitting in exclude area only because I wanted to focus team on critical part of our library first. But 100% coverage for GUI is very desirable. I know that with GUI that is really hard but we need to go to this target.
As you use custom UI components please investiagate how  they support UTesting. We could use some testing tools like - https://github.com/UISpec4J/UISpec4J

**Comment by liscju** [comment]
1)
image

2) 
I cant find RSyntaxTextArea license in "all-jar", probably it lacks it. I asked in github site of the project what we should do to not violate their license restrictions.

3) 
What kind of testing do you mean, more like unit testing gui components or integration testing? So far gui lacks test at all ( or i cant find it), so i have little idea how this should look like. It should be integration testing like:

* When user choose file , it shows it in editor
* When user move cursor on editor,  status bar line/column number change

or unit testing:

* when we invoke method , it should change state of (mocked) gui

**Comment by romani** [comment]
1) 
> I asked in github site of the project what we should do to not violate their license restrictions.

Please share a link to their site I need to see official confirmation from them. 
Our "-all" jat is distributed as checkstyle-6.8.1-all.jar
http://sourceforge.net/projects/checkstyle/files/checkstyle/6.8.1/
According to their license we need to put their license file to our jar, we create "all" jar by profile "assembly" in pom - https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L976.

2)
> What kind of testing do you mean, more like unit testing gui components or integration testing?

unit testing, during our UT phase in maven

3)
> So far gui lacks test at all

yes, we ignore them - https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L1135 , and that have to started to improve.

4)
> when we invoke method , it should change state of (mocked) gui

to make UI testing we need to do refactoring of our code to clearly separate UI and presentation layer/logic(POJO classes).  POJO classes could be easily unit-testable as all other classes. UI classes should have no logic at all and just contain layout and rendering content from presentation layer.

**Comment by romani** [comment]
@liscju , do you have time to finish that PR ?

**Comment by liscju** [comment]
@romani  i will work on it next week

Roman Ivanov <notifications@github.com> napisał(a):

**Comment by liscju** [comment]
https://github.com/bobbylight/RSyntaxTextArea/issues/134#issuecomment-126815507 - license issue of rsyntaxtree component

**Comment by mkordas** [comment]
@romani, are we sure that we want to keep GUI in main repo? It's used only and rarely by Checkstyle developers I believe. After introducing this change, every person in the world using Checkstyle would need to download RSyntaxTree and have it on classpath... My proposition is to move it to Contribution repo and release as Checkstyle 7.0

**Comment by romani** [comment]
> are we sure that we want to keep GUI in main repo

I never ok so easily with additional dependency.
I am ok to keep GUI in library till it use jdk only - my preference . 
I do not like additional dependency, but I ok to see how contributor can provide solution, decision of hosting we could make later.

**Comment by romani** [comment]
to make teamcity pass ,  just rebase on latest master

**Comment by liscju** [comment]
I have problem with ending this PR . As a last part of PR @romani requested to split GUI into presentation and logic layer but i have many doubts about how to do it. GUI has nearly no logic at all, it is all about displaying result and dividing this into MVC pattern with one controller method(load file) , one model(parsed tree) and rest of the code in view seems like total overkill. Another thing is testing it properly - with application focused entirely on displyaing data, it looks like best unit test i can get would be sth like: loading prepared file in application and checking if consecutive rows in tree displayer have expected values - what seems more like integration than unit testing. I would be grateful for any ideas/comments what should i do

**Comment by mkordas** [comment]
@liscju, I agree that there's a lot to improve in current GUI regarding structure, design and testability.

As for me, any integration test involving as much code and features as possible would be good start. We cannot lock down bad design by unit tests. End-to-end would enable us to freely redesign solution without falling into regression hell.

There's one more thing - regardless of testing probably we shouldn't add any additional dependency to Checkstyle at that point. On the other hand solution provided by you looks really nice. 
I see two solutions:
- accept this PR, but move GUI to contribution repo before next release
- find solution without any additional library
@romani, what are your thoughts on that?

**Comment by liscju** [comment]
@romani suggested using https://github.com/UISpec4J/UISpec4J for our testing and i ran into problem with it. To use UISpec4J in maven we have to specify dependency classifier for given jdk , to see more what im talking about see 
https://github.com/UISpec4J/UISpec4J/issues/24#issuecomment-140204601

So far i didn't get the answer from author if there is any way to overcome this. So what we should do with it:

1) Wait for author if he sees any solution to it
2) Search for another library for gui testing
3) We assume that gui will be moved to another repository and developers will be able to change dependency to maven accordingly for their version.

**Comment by romani** [comment]
Unfortunately I need to close this PR, even I like how it GUI looks .

Reasons:
1) We can not introduce extra dependency to our project, especially for GUI. We are embedded in a lot of projects, extra dependency is not ok.
2) Status of GUI package in our library is not clear for now, looks like we need to split project into two parts (GUI and library), but I am not ready now to do this. Too much issues need to be resolved in main code.

@liscju , even I close your PR, your changes will not be lost as github is storing them even you drop your fork. This PR is referenced in corresponding Issue, Issue is not closed, so ones we get to it, we will review your fix one more time.

**Pull request closed without merging**
