### PR TITLE
Issue #3472: Add METHOD_REF to tokens of OperatorWrapCheck

### PR DESCRIPTION
**Pull request by agcuda**
Issue #3472 

Add METHOD_REF to accepted tokens for OperatorWrapCheck and update documentation

### CODE REVIEW

**Comment by romani** [comment]
Please make a general UT on this.
Please copy that UTs to ITs, our ITs do test of Google config.

**Comment by agcuda** [comment]
No problem for the UT. Regarding the IT I have a doubt: currently google config does not contain METHOD_REF in the list of OperatorWrap operators, how can I write an IT for this feature? Of course I could add it to PR #3381.

**Comment by romani** [comment]
Please do UTs.
For ITs , you are right. Lets add  to input files of IT code , but comments "warn" you will put in PR when that token is introduces to config.

**Comment by romani** [comment]
`::` is not used in guava code , so no regression testing of Guava is required.

**Comment by romani** [comment]
as UTs and ITs are done , I am ready to merge.

**Comment by agcuda** [comment]
I have added UTs and ITs. Looking at the logs, CircleCI failed because of a networking issue.

**Comment by romani** [comment]
Codacy could be ignored, it is their internal problem

**Pull request merged**
