### PR TITLE
minor: fix violations from future EmptyLineBeforeAtClauseBlock (#6192)

### PR DESCRIPTION
**Pull request by josephmate**
**How I inserted a newline before existing violating at-clauses in the code base:**
I believe it would be extremely difficult for me to fix all the violations manually and error prone. There were about **1900 violation**s. As a result, I took the violations from https://github.com/checkstyle/checkstyle/pull/7932 and I put together a small script to fix them for me: https://github.com/josephmate/FixAtClauseError

### CODE REVIEW

**Comment by pbludov** [comment]
@josephmate Please use your tool to make a PR to https://github.com/sevntu-checkstyle/sevntu.checkstyle repo.

**Comment by rnveach** [comment]
PR needs to be rebased as there is already a conflict.

**Comment by josephmate** [comment]
@rnveach : conflict was in  src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java. I fixed it.

**Comment by josephmate** [comment]
> @josephmate Please use your tool to make a PR to https://github.com/sevntu-checkstyle/sevntu.checkstyle repo.

@pbludov : ok I will.

**Comment by josephmate** [comment]
@pbludov : done https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/810

**Comment by romani** [comment]
@josephmate , thanks a lot!!!
Sorry that our policy on this is too hard, but it give us big insight on a pain that users will have after release of update.

**Comment by romani** [comment]
@josephmate , please move this link to script to issue description, user would love to reuse it on their codebase.

**Pull request merged**
