### PR TITLE
FileContents.getFileName() - resolve issue #1205

### PR DESCRIPTION
**Pull request by tsjensen**

### CODE REVIEW

**Comment by tsjensen** [comment]
Build fails because of

    [INFO] Confusing to have methods com.puppycrawl.tools.checkstyle.api.AuditEvent.getFileName() and com.puppycrawl.tools.checkstyle.api.FileContents.getFilename() [com.puppycrawl.tools.checkstyle.api.AuditEvent] At AuditEvent.java:[line 86]

which is in the nature of this change. Do you have an exclusion method for this?

**Comment by romani** [comment]
yes, we need to put exclusion in https://github.com/checkstyle/checkstyle/blob/master/config/findbugs-exclude.xml , please do.


you can verify build on local by "mvn clean verify".

**Comment by tsjensen** [comment]
Done.

**Comment by romani** [comment]
please squash to one commit, i am ready to merge

**Comment by tsjensen** [comment]
Done.

**Pull request merged**
