### PR TITLE
Issue #8274: Update java.g to allow new tokens to be added

### PR DESCRIPTION
**Pull request by nmancus1**
Issue #8274: Update java.g to allow new tokens to be added

### CODE REVIEW

**Comment by nmancus1** [comment]
I'm not sure why all those other commits are now listed in the "files changed", please let me know if I need to resolve this before merging.

**Comment by pbludov** [comment]
@nmancus1, please rebase

**Comment by nmancus1** [comment]
@pbludov Fixed.

**Comment by esilkensen** [comment]
@romani should I merge a small PR like this one after @pbludov has already approved, or better to always pass it on to you / @rnveach for a final review?

**Comment by rnveach** [comment]
I am going to merge this though it looks like not all of CI ran. Only 6 jobs are listed and we usually have more.

**Pull request merged**
