### PR TITLE
Issue #14123: Fix transitive dependency rejection after Guava upgrade to 32.1.3-jre

### LINKED ISSUE #14123: Transitive dependency rejection after Guava upgrade to 32.1.3-jre
With checkstyle 10.12.6 guava was upgraded from 32.0.1-jre to 32.1.3-jre
Since there'S also a transitive dependency to `com.google.collections:google-collections:1.0` through `org.apache.maven.doxia:doxia-core:1.12.0` gradle task `:checkstyleMain` fails with:
```
> Could not resolve all files for configuration ':checkstyle'.
   > Could not resolve com.google.guava:guava:32.1.3-jre.
     Required by:
         project : > com.puppycrawl.tools:checkstyle:10.12.6
      > Module 'com.google.guava:guava' has been rejected:
           Cannot select module with conflict on capability 'com.google.collections:google-collections:32.1.3-jre' also provided by [com.google.collections:google-collections:1.0(runtime)]
   > Could not resolve com.google.collections:google-collections:1.0.
     Required by:
         project : > com.puppycrawl.tools:checkstyle:10.12.6 > org.apache.maven.doxia:doxia-core:1.12.0 > org.codehaus.plexus:plexus-container-default:2.1.0
      > Module 'com.google.collections:google-collections' has been rejected:
           Cannot select module with conflict on capability 'com.google.collections:google-collections:1.0' also provided by [com.google.guava:guava:32.1.3-jre(jreRuntimeElements)]
```

There's a workaround reported here: https://github.com/gradle/gradle/issues/27035#issuecomment-1814589243
But I guess it's better to exclude `com.google.collections:google-collections:1.0` because it's part of guava anyway.

See also https://github.com/slugify/slugify/actions/runs/7125400022/job/19431918771?pr=175 if you need a reproduction.

### PR DESCRIPTION
**Pull request by nrmancuso**
Related to #14123

Reproduction of issue: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/23869/workflows/92d24c51-2e5b-48b6-9aba-0ebd9141432b/jobs/517216

Not able to reproduce with the latest snapshot: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/23868/workflows/1de3ed9f-abaa-4836-a720-403b7b397fa5/jobs/517169/steps (CI is green)

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
I have been reading through the issue and related comments. And, what i have understood is the removal of doxia, as a final fix. Can I help in any manner?

**Comment by nrmancuso** [comment]
> I have been reading through the issue and related comments. And, what i have understood is the removal of doxia, as a final fix. Can I help in any manner?

I really have no idea what to do here, @relentless-pursuit I welcome any help you can provide :)

**Comment by nrmancuso** [comment]
@relentless-pursuit I am going to close this, feel free to reuse anything here. I would suggest to first make sure that you can reproduce the issue in CI, or we are just guessing if the fix actually works (like last time).

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit I am going to close this, feel free to reuse anything here. I would suggest to first make sure that you can reproduce the issue in CI, or we are just guessing if the fix actually works (like last time).

Sure, I will come back to this PR if i hear any recent development. So far, from the comments what I have understood is getting rid of doxia. Meanwhile, I will focus on other issues and hanging PRs.

**Pull request closed without merging**
