### PR TITLE
Issue #525: Support for Default IntelliJ IDEA Formatiing in CustomImp…

### PR DESCRIPTION
**Pull request by GabrielBercaru**
Issue: #525

### CODE REVIEW

**Comment by rnveach** [comment]
@GabrielBercaru Please fix failing CI.

**Comment by romani** [comment]
please rebase on latest code to resolve TC problem, TC problems are resolved in our master.

**Comment by romani** [comment]
if no action happen till 1st june, we will close this PR, to ease our management of PRs

**Comment by romani** [comment]
@GabrielBercaru , ping, last warning before I close PR at the end of the week.

**Comment by romani** [comment]
connection with @GabrielBercaru  is lost, PR is closed as incomplete.
If smb want to continue from scratch or from where @GabrielBercaru is finished, please be welcome .

**Pull request closed without merging**
