### PR TITLE
Issue #11681: adds maven-source-plugin for test sources

### PR DESCRIPTION
**Pull request by rnveach**
Issue #11681

### CODE REVIEW

**Comment by rnveach** [comment]
Running `mvn clean package` now produces "-sources.jar" and "-test-sources.jar".

@romani How would I confirm what deployment will do? Run the test deployment script?

**Comment by romani** [comment]
Please share here ` du -h ` for them

**Comment by rnveach** [comment]
````
$ ll
drwxr-xr-x  9 www-data www-data     4096 May 31 21:54 ./
drwxrwxrwx 11 nobody   nogroup      4096 May 31 21:53 ../
-rw-r--r--  1 www-data www-data  2019932 May 31 21:54 checkstyle-10.4-SNAPSHOT.jar
-rw-r--r--  1 www-data www-data  1735271 May 31 21:54 checkstyle-10.4-SNAPSHOT-sources.jar
-rw-r--r--  1 www-data www-data 10299902 May 31 21:54 checkstyle-10.4-SNAPSHOT-tests.jar
-rw-r--r--  1 www-data www-data  3730563 May 31 21:54 checkstyle-10.4-SNAPSHOT-test-sources.jar

````

**Review by romani — APPROVED** [review]
ok to merge.
size of sources is not bigger than size of binaries that we already uploading to maven repo.

**Comment by rnveach** [comment]
@romani If you deploy this to maven as described above, this can be tested via similar method at https://github.com/rnveach/checkstyle-backport-jre8/commit/7032abdb5ec9d48e9e61079625bd8c7f547f4dd5

**Review by pbludov — APPROVED** [review]

**Review by pbludov — APPROVED** [review]

**Pull request merged**
