### PR TITLE
Remove unused private field, issue #744

### PR DESCRIPTION
**Pull request by mkordas**
All violations of PMD rule [UnusedPrivateField](http://pmd.sourceforge.net/pmd-5.2.3/pmd-java/rules/java/unusedcode.html#UnusedPrivateField) are fixed.

### CODE REVIEW

**Comment by romani** [comment]
can we enforce build failure on any new violations from PMD  (changes in pom.xml)? after that we could mark #744 as fixed and never come back to it.

**Comment by romani** [comment]
merged as FF

**Comment by mkordas** [comment]
I'll enforce failure when we'll deal with all PMD violations. Still, by default maven-pmd-plugin has only three rulesets enabled: _basic.xml_, _unusedcode.xml_ and _imports.xml_. There are multiple more rulesets in PMD that are valuable, but this means hundreds of new violations...

**Comment by romani** [comment]
hundreds of violations - it is good :), please enforce build failure right now and then create issue to activate all other rules and resolve their problems if rule work fine for us.

FYI: we will do the same for Checkstyle, Findbug, Sonar, ..... all that violations should be fixed, that tools should control quality of our code and quality of PRs.

**Comment by mkordas** [comment]
@romani, I agree with the approach you proposed. We'll make build failing on any new violation... but do you know how to do it for Sonar?

**Comment by romani** [comment]
> but do you know how to do it for Sonar?

As far as I know Sonar is not configurable for us, Sonar team use it default config.

**Pull request closed without merging**
