### PR TITLE
Remove unnecessary // ok comments from UnnecessaryParenthesesCheck.java

### PR DESCRIPTION
**Pull request by aloksharma060**
This pull request removes unnecessary "// ok" comments from the src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java
file. This change aims to enhance code clarity by eliminating comments that do not provide significant value to the codebase.

### CODE REVIEW

**Comment by romani** [comment]
Please read https://checkstyle.org/beginning_development.html#Starting_Development

And watch videos , it shows by example how to do contribution.

**Comment by romani** [comment]
Please update same in xdoc folder, for xml file that is named as a Check.

**Comment by aloksharma060** [comment]
@romani should i generate pull request again for src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java

**Comment by aloksharma060** [comment]
@romani I have generated pull request again for  src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java by following the steps from
https://checkstyle.org/beginning_development.html#Starting_Development

**Comment by romani** [comment]
Please watch all videos.

**Comment by aloksharma060** [comment]
> Please update same in xdoc folder, for xml file that is named as a Check.

Should i generate a seperate Pr for git add src/xdocs/checks/coding/unnecessaryparentheses.xml  @romani

**Comment by romani** [comment]
no, keep xml update in this PR.
keep single commit in PR always.
Run "mvn clean verify" on your local to make sure build is passing.

read message from build error https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=24236&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=1396
and follow what it requires.

**Comment by aloksharma060** [comment]
@romani am changing the commit message that follows the rules 
git commit --amend -m "Issue #13213: Remove unnecessary comments from unnecessaryparentheses.xml"
Still after running mvn clean verify its showing the same error

**Comment by aloksharma060** [comment]
> I still see 2 commits. If you are stuck, Please push to GitHub to let me see

I have pushed the commit please check it @romani

**Comment by romani** [comment]
Please make single commit and format message of commit as required. Test is failing with message on what is wrong

**Comment by aloksharma060** [comment]
> Please make single commit and format message of commit as required. Test is failing with message on what is wrong

I have made a single commit and pushed it check it @romani

**Comment by romani** [comment]
Please look at GitHub page, at tab , commits.

**Comment by aloksharma060** [comment]
@romani I have pushed some commits check it and if still it encounters issue i will delete the files and clone it again.

**Comment by romani** [comment]
image

I hope you see 2 commits

**Comment by aloksharma060** [comment]
> Please look at GitHub page, at tab , commits.

The test are failing as it is causing some error in pom.xml file

**Comment by aloksharma060** [comment]
@romani Close this PR i will generate a new PR with single commit From branch (my-new-check-v2)

**Pull request closed without merging**
