### PR TITLE
Issue #3898: Field check and splits done for whitespaceAround

### PR DESCRIPTION
**Pull request by nikshinde1996**
Issue #3898

### CODE REVIEW

**Comment by romani** [comment]
please do not close this PR.
fix CI, failures - https://travis-ci.org/checkstyle/checkstyle/builds/210077971

before pushing changes please make sure that "mvn verify" is passing on your local.

**Comment by MEZk** [comment]
@nikshinde1996 
Please follow [PR rules](https://github.com/checkstyle/checkstyle/wiki/PR-rules).

**Comment by rnveach** [comment]
@nikshinde1996 ping

**Comment by rnveach** [comment]
@nikshinde1996 ping
Since we are out of proposal deadline, do you think you can finish this?

**Comment by nikshinde1996** [comment]
The local build fails in my computer.... I will be working on it. Still can you make this issue open for other contributors to work upon.

**Comment by romani** [comment]
PRs is closed as we lost connection with student, any contributor could continue this work to make it done.

**Pull request closed without merging**
