### PR TITLE
Issue #15340: created inputformatted file for section 3.3.1 No wild card imports

### PR DESCRIPTION
**Pull request by Zopsss**
~~#15340~~ #15449 

~~added extra code so formatter does not remove unused imports~~

excluded rule331nowildcard from google-java-format.sh

### CODE REVIEW

**Review by romani — CHANGES_REQUESTED** [review]
image


please restore missed single line comments. If formatter need extra empty lines, please add them in orignal Input too, to have no diff around such lines

please remove in original file import for `String`, it is irrelevanl in this context.

after that , there will be almost no diff.

**Comment by Zopsss** [comment]
release notes causing CI failure:

https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/50507787/job/rxtj93q2ahk3ylk5

linelength module is failing

**Comment by romani** [comment]
Rebased

**Review by romani — APPROVED** [review]
Ok to merge.
No diff.

**Comment by romani** [comment]
@Zopsss ,

>No diff.

Why we can not simply make original import to be fully formatted ? And not deal with InputFormatted at all.

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by romani** [comment]
Tests are failing

**Comment by romani** [comment]
tests are fixed.

**Review by romani — APPROVED** [review]
ok to merge

**Pull request merged**
