### PR TITLE
Issue: Update doc for NestedIfDepth #7652

### PR DESCRIPTION
**Pull request by coraljain**
PLEASE READ before removing!!

Rules:
1) The issue you are trying to fix/resolve has to have the "approved" label.
2) Put in the description of Pull Request the reference to an issue if it exists.
   Example: "Issue: #XXXXXX"
3) Commit message should adhere to the following rules:
   a) MUST match one of the following patterns:
      ^Issue #\\d+: .*$
      ^Pull #\\d+: .*$
      ^(minor|config|infra|doc|spelling|dependency): .*$
   b) MUST contain only one line of text
   c) MUST NOT end with a period, space, or tab
   d) MUST be less than or equal to 200 characters

To avoid multiple iterations of fixes and CIs failures, please read
https://checkstyle.org/contributing.html

ATTENTION: We are not merging Pull Requests that are not passing our CIs,
but we will help to resolve issues.

Thanks for reading, remove whole this message and type what you need.

### CODE REVIEW

**Comment by rnveach** [comment]
@coraljain Please read https://github.com/checkstyle/checkstyle/wiki/PR-rules and your first post in this PR.

**Comment by rnveach** [comment]
@coraljain ping

**Comment by coraljain** [comment]
@rnveach I am really sorry for the delay, I will post the changes at the earliest.

**Comment by coraljain** [comment]
@romani @rnveach while running the command git rebase -i HEAD~2, I am getting a list of following files given in screenshot. However, while running the git push origin master, it showed 2 files were updated. 

Please suggest how to resolve this issue.


Screen Shot 2020-03-11 at 10 21 43 PM

**Comment by romani** [comment]
@coraljain , your PR is completely messed up.
please copy your changes to some other folder and drop all your branches and follow https://checkstyle.org/beginning_development.html#Starting_Development to create all from scratch. if still does not work - drop a fork and do it from scratch.

**Comment by coraljain** [comment]
@romani - I have dropped my fork and created a new fork, but now I am unable to commit on this pull request and the changes are only in my branch. Please suggest next steps.

**Comment by rnveach** [comment]
@coraljain Nothing can be done in this PR since you dropped your fork. Never drop a fork when you have an existing PR going on.

You will need to create a brand new PR and close this one.

**Comment by strkkk** [comment]
Closed as abandoned

**Pull request closed without merging**
