### PR TITLE
Issue #6207: Add Xpath regression test for MethodTypeParameterName

### PR DESCRIPTION
**Pull request by Kexin2000**
Part of issue #6207

### CODE REVIEW

**Review by MANISH-K-07 — COMMENTED** [review]
Please don't merge this before #14713 

#14713 consists of two commits and I won't be able to squash this current PR's xpath file suppression into the first commit and it might get messy..

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/pull/14713 is merged

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by MANISH-K-07** [comment]
> Ok to merge

@romani , this commit still consists of files named with old pattern and there is no suppression for this check.
There are supposed to be failing integration workflows on rebase 😕

**Comment by romani** [comment]
@MANISH-K-07 , please send fix  to fix it forward. Just one check update, I will merge immediately

**Comment by MANISH-K-07** [comment]
Give me 5 mins

**Comment by MANISH-K-07** [comment]
> @MANISH-K-07 , please send fix to fix it forward. Just one check update, I will merge immediately

> Give me 5 mins

@romani , please see PR #14719

**Pull request merged**
