### PR TITLE
correction of parsing of attributes in AtclauseOrderCheck, #1152

### PR DESCRIPTION
**Pull request by Vladlis**
as the number of uncovered with UT lines increased after changes, I also had to change a UT to increase the coverage and pass cobertura

### CODE REVIEW

**Comment by romani** [comment]
please split by "," and to trim, see my comment to the issue with link to correct approach.

**Comment by Vladlis** [comment]
Done

**Comment by romani** [comment]
1) Please explain reason of update in UT.

2) Please add UT for testing a trim, that test should fail on previous implementation of setter.

**Comment by Vladlis** [comment]
1) The updated UT covers setTagOrder(), which was not done earlier.
2) Done, I just updated the same test to do do this.

**Comment by Vladlis** [comment]
@romani, what does this error mean? 
> mvn clean verify

passes successfully on my machine, when I run it using oraclejdk8
>java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) Server VM (build 25.45-b02, mixed mode)

**Comment by romani** [comment]
That is Java Virtual Machine crash :)  (I doubt that is caused by your changes), I relaunched a build, I saw that previously on Travis, usually relaunch helped.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
