### PR TITLE
Issue #5389: Add example to Ant Documentation showcasing custom-jar u…

### PR DESCRIPTION
**Pull request by nthakur34**
…sage

Add example doc for Issue #5389 - update ANT examples

### CODE REVIEW

**Comment by romani** [comment]
Please fix spelling issues.

How we can be confident that this config works? Can you share link to project where such config is tested?

If no project exists, can you send PR to https://github.com/sevntu-checkstyle/checkstyle-samples/tree/master to have one more example for ant, and CI will keep it up to date.

**Comment by nrmancuso** [comment]
@nthakur34 do you plan to continue work on this PR?

**Comment by rnveach** [comment]
@romani samples is already using a sevntu ant.

Sevntu config.
https://github.com/sevntu-checkstyle/checkstyle-samples/blob/master/ant-project/checkstyle.xml#L10
Sevntu maven.
https://github.com/sevntu-checkstyle/checkstyle-samples/blob/master/ant-project/ivysettings.xml#L13
Sevntu dependency.
https://github.com/sevntu-checkstyle/checkstyle-samples/blob/master/ant-project/ivy.xml#L6
Sevntu being pulled in by lib from ivy.
https://github.com/sevntu-checkstyle/checkstyle-samples/blob/master/ant-project/build.xml#L30
https://github.com/sevntu-checkstyle/checkstyle-samples/blob/master/ant-project/build.xml#L36-L37
https://github.com/sevntu-checkstyle/checkstyle-samples/blob/master/ant-project/build.xml#L18

**Comment by rnveach** [comment]
GitHub, generate website

**Comment by rnveach** [comment]
@romani I confirmed the example works by first running `checkstyle ant` in `checkstyle-samples` (to pull down depdendencies and setup lib folder) and running it with the following build XML:
````
<?xml version="1.0" encoding="utf-8" ?>
<project xmlns:ivy="antlib:org.apache.ivy.ant" name="ant-sample" default="build" basedir=".">

    <target name="checkstyle"
            description="Generates a report of code convention violations.">

        <path id="checkstyle.lib.path">
            <fileset dir="lib" includes="*.jar"/>
        </path>

        <taskdef resource="com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties"
                 classpathref="checkstyle.lib.path"/>

        <checkstyle config="checkstyle.xml"
                    failOnViolation="false">
          <classpath>
            <pathelement path="${checkstyle.lib.path}"/>
            <pathelement location="lib/sevntu-checks-1.42.0.jar"/>
          </classpath>

          <formatter type="xml" tofile="checkstyle_report.xml"/>
          <fileset dir="src" includes="**/*.java"/>
        </checkstyle>

    </target>

</project>
````

Majority of xml is copied from documentation.

Output:
````
> ant checkstyle
Buildfile: M:\checkstyleWorkspaceEclipse\checkstyle-samples\ant-project\build.xml

checkstyle:
[checkstyle] Running Checkstyle 10.3.4 on 1 files

BUILD SUCCESSFUL
Total time: 0 seconds
````

**Comment by romani** [comment]
Is it possible to copy this xml to example project and run right after existing task ?

**Comment by rnveach** [comment]
technically yes, but you really aren't gaining much more. Yes, your specifying custom location for sevntu, but your classpath much set up already for checkstyle since it requires all it's dependencies.

**Pull request merged**
