### PR TITLE
minor: refactor long lambdas

### PR DESCRIPTION
**Pull request by strkkk**
Fix of violations from https://github.com/checkstyle/checkstyle/pull/8896
Change lambdas to be not more than 10 lines

### CODE REVIEW

**Comment by rnveach** [comment]
commit message should make some mention to connect this to #8896 .

@romani Maybe we should create a new commit message prefix for this type of changes.

**Comment by romani** [comment]
`minor: refactor long lambdas for #8896`

If you have in mind good prefix please let me know

**Comment by strkkk** [comment]
@romani @rnveach it can be `tech: bla bla bla`

Commit message is updated to mention #8896

**Comment by romani** [comment]
Everything is "tech"

**Comment by strkkk** [comment]
@romani done

**Review by rnveach — APPROVED** [review]
I am approving but I don't see line count as a good method because as seen users will just remove an empty line to satisfy it. Some empty lines are good separation for easier reading of separate thoughts.

**Comment by rnveach** [comment]
> Please put space after "PR" (before "#") to let GitHub bind it to issue

Shouldn't that be issue and not pr since the number is the issue?

> If you have in mind good prefix please let me know

What about `Supplemental: .... for Issue #XXXX`.

**Comment by romani** [comment]
> Shouldn't that be issue and not pr since the number is the issue?

it should be issue, better to remove "PR"

> Supplemental: .... for Issue #XXXX.

`supplemental: .... for Issue #XXXX.` I am ok with this.

**Review by romani — APPROVED** [review]

**Pull request merged**
