### PR TITLE
Issue #14436: Enforced naming convention for illegalcatch

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Part of #14436 

Renamed input files and test methods of annotationonsameline module to follow naming convention.

The following files test accordingly : 

-  InputIllegalCatchCheckDefaultTokens- 
    tests for violations of default tokens in catch()

- InputIllegalCatchCheckMultipleExceptions- 
    tests for violations in catch() holding multiple exceptions

- InputIllegalCatchCheckSuperclassThrowable- 
    tests for violations related to usage of Superclass Throwable in catch()

- InputIllegalCatchCheckSuperclassException- 
    tests for violations related to usage of Superclass Exception in catch()

### CODE REVIEW

**Comment by MANISH-K-07** [comment]
@romani ,
Looks like Cirrus - JDK17 is running on empty even before month's half 😄

**Comment by MANISH-K-07** [comment]
@nrmancuso 
Please review if the naming is precise

**Comment by MANISH-K-07** [comment]
@romani 
Please review if the naming is precise

**Review by romani — APPROVED** [review]
Ok to merge

**Pull request merged**
