### PR TITLE
Issue #3085: fixed escaping in RegexpOnFilename examples

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3085 

I accidentally double escaped the examples for the check.

### CODE REVIEW

**Comment by rnveach** [comment]
travis failure is because issue is unapproved.

**Comment by romani** [comment]
looks like it is not solution due to https://github.com/checkstyle/checkstyle/issues/3085#issuecomment-207134416 .

We need to find a reason and update doc with missed nuance.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/issues/3085#issuecomment-214099585

Until the issuer replies, I believe the problem is they are using JXR instead of running CS directly.

**Comment by romani** [comment]
fix for documentation is merged.

**Pull request merged**
