### PR TITLE
Issue #13328: Kill mutation for OneStatmentPerLineCheck-4

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13328: Kill mutation for OneStatmentPerLineCheck-4

-----

# Check 
https://checkstyle.org/config_coding.html#OneStatementPerLine

------

# Mutation 
https://github.com/checkstyle/checkstyle/blob/6324a9d693324eb755c2cdfdbd90c2300d3c7f02/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L183-L190

-----

# Explaination 
Test added

-----

# Regression 

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/3bd236a24ed8eacd760e6b12b47f7455/raw/97d7a64aa97fc35488a6db5d7345ee23ae9b9507/olc.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/21e3934e85f802e2fbd48af06d122364/raw/604256badd733d8568064f371d55657c04b00dfd/test-projects-2.properties
Report label: Regression-2

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
@Kevin222004 There is a case in diff report https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/4a8ac32_2023143000/reports/diff/intellij-community/index.html

**Comment by romani** [comment]
@Kevin222004 , please rebase and use extend input by case in diff report.

**Comment by Kevin222004** [comment]
Only one single diff is found from the whole regression. once again I have spent hours to figure out this but I really don't find anything.

So after making an assumption I go to Intellij repo to find what was the previous file of it and I found 
the code something like https://github.com/JetBrains/intellij-community/blob/master/plugins/InspectionGadgets/test/com/siyeh/igfixes/migration/try_finally_can_be_try_with_resources/Catch.java
```
  void m() throws IOException {
    InputStream in = null;
    try<caret> {
      in = new FileInputStream("filename");
    }catch (Exception e) {
    }finally{
      in.close();
    }
  }
```

I am suspecting that diff is because of this code. I have not done extra testing to prove this but will provide soon.

**Comment by Kevin222004** [comment]
@romani Test added :)

**Review by romani — APPROVED** [review]
The best form of PR for Pitest.
Quick merge

**Pull request merged**
