### PR TITLE
Issue #13109: Kill mutation for FileText 2

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13109: Kill mutation for FileText 2

--------------

# Mutation covered 
https://github.com/checkstyle/checkstyle/blob/82b6ac46193fafdfbcfc5dacbb848004c36a82e4/config/pitest-suppressions/pitest-api-suppressions.xml#L75-L82

--------------

# Explaination
Our code is
```
    public FileText(FileText fileText) {
        file = fileText.file;
        charset = fileText.charset;
        fullText = fileText.fullText;
        lines = fileText.lines.clone();
        if (fileText.lineBreaks == null) {
            lineBreaks = null;
        }
        else {
            lineBreaks = fileText.lineBreaks.clone();
        }
    }

```

Here the part of code  
```
        if (fileText.lineBreaks == null) {
            lineBreaks = null;
        }
```

is mutated as 
```
        if (fileText.lineBreaks == null) {
        }
```

Here the condition in if statment is 
something like 
```
fileText.lineBreaks == null
```

know if we see logically their is 2 possiblity 
either `fileText.lineBreaks` is `null` or it is
`not null`  if it is null then the if block will
execute and in the case of `not null` else will execute.

know instead of doing this `fileText.lineBreaks == null` in if block and set the lineBreaks to null 
 we can change the if condition to 
```
        if (fileText.lineBreaks != null) {
            lineBreaks = fileText.lineBreaks.clone();
        }
```
so the new code look like 
```
    public FileText(FileText fileText) {
        file = fileText.file;
        charset = fileText.charset;
        fullText = fileText.fullText;
        lines = fileText.lines.clone();
        if (fileText.lineBreaks != null) {
            lineBreaks = fileText.lineBreaks.clone();
        }
        else {
            lineBreaks = null;
        }
    }
```

Here `lineBreaks` set to null which is its default value and this is constructor. so if we remove the default value it won't effect anything.
in this case when `fileText.lineBreaks == null` by default it will asign  `lineBreaks = null;`
it will not make any effect to code

so finall code we write as 
```
    public FileText(FileText fileText) {
        file = fileText.file;
        charset = fileText.charset;
        fullText = fileText.fullText;
        lines = fileText.lines.clone();
        if (fileText.lineBreaks != null) {
            lineBreaks = fileText.lineBreaks.clone();
        }
    }
```

### CODE REVIEW

**Comment by Kevin222004** [comment]
How to do regression testing here?

**Comment by Kevin222004** [comment]
ready for review

**Comment by romani** [comment]
resolve Checker violation.

This class is used by all Checks and Filters, I think this is a case where we do not need diff regression. Green CI is enough.

**Comment by Kevin222004** [comment]
Done
I have suppressed the new surviving one.
Reason
`<message>the constructor does not initialize fields: lineBreaks</message>`
if I will initialize the lineBreak then it is still the same pitest issue their

**Review by romani — APPROVED** [review]
Ok to merge

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

**Pull request merged**
