### PR TITLE
Issue #7144: aligned javadoc/xdoc for ImportControl

### PR DESCRIPTION
**Pull request by pbludov**
Issue #7144 (part of #5750)

Second commit to change `<h4>` to `<p>` to avoid `header used out of sequence` error issued by the javadoc tool.

### CODE REVIEW

**Comment by rnveach** [comment]
Can be merged when CI passes.

**Comment by pbludov** [comment]
>>error: header used out of sequence: `<h4 id="blacklist-example">Example of blacklist mode</h4>`

https://stackoverflow.com/questions/32950918/using-html-headings-out-of-sequence

In the xdocs, there is no error: "Examples" section is `<h3>`,  "blacklist example" is `<h4>`.

**Comment by romani** [comment]
Travis and TC were restarted

**Comment by romani** [comment]
Travis and TC were restarted

**Comment by romani** [comment]
I do not understand problem

**Comment by pbludov** [comment]
> I do not understand problem

CI failed with error: `header used out of sequence: <h4 id="blacklist-example">Example of blacklist mode</h4>` due to xdocs for ImportControl contains `<h4>` [here](https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_imports.xml#L1196):

**Comment by rnveach** [comment]
> In Javadocs there is no <h1> nor <h2>, nor <h3>.

According to https://stackoverflow.com/a/30957355/1016482 the header tags are allowed. It sounds like the error is stating that the headers must be used in order and not skip around.

**Comment by romani** [comment]
I am ok to have P tag instead

**Comment by pbludov** [comment]
> > `In Javadocs there is no <h1> nor <h2>, nor <h3>.`
> 
> According to https://stackoverflow.com/a/30957355/1016482 the header tags are allowed. It sounds like the error is stating that the headers must be used in order and not skip around or go backwards.

Yes. [The specs](https://www.w3.org/TR/WCAG20-TECHS/G141.html#G141-description) say:
> To facilitate navigation and understanding of overall document structure, authors should use headings that are properly nested (e.g., h1 followed by h2, h2 followed by h2 or h3, h3 followed by h3 or h4, etc.).

By the way, [here](https://checkstyle.org/config_imports.html#ImportControl_Examples) the `h1` heading is missing:

h2 IllegalImport
h3 Examples
h4 Example of blacklist mode

**Pull request merged**
