### PR TITLE
Issue #7583: Added example for default config of if else tokens

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Issue #7583: Added example for default config of if else tokens

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
I don't think we need to add more examples, but if it's needed just drop a comment.

**Comment by Vyom-Yadav** [comment]
Github, generate web site

**Comment by Vyom-Yadav** [comment]
Github, rebase

**Comment by Abhishek-kumar09** [comment]
The issue is `Update doc for NeedBraces` and you have opened Pr for  `dded example for default config of if else tokens`.
Please read: https://checkstyle.org/config_blocks.html#NeedBraces
and add valid and invalid code examples both.

**Comment by Vyom-Yadav** [comment]
Add examples for each existing config to show what code is ok and what code causes violations. This is written in the issue description, something else also needs to be done?

**Comment by Abhishek-kumar09** [comment]
Write cases following default cases of properties.
like on with emptyBody, see the table in the documentation and make examples for default config.

**Comment by Vyom-Yadav** [comment]
Error as I set up a new upstream

**Pull request closed without merging**
