### PR TITLE
Issue #10271: Update inputs for VariableDeclarationUsageDistanceCheckTest

### LINKED ISSUE #10271: Update inputs for VariableDeclarationUsageDistanceCheckTest
Child of #10080

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #10271

### CODE REVIEW

**Comment by timurt** [comment]
fix conflicts

**Comment by shashwatj07** [comment]
> fix conflicts

done

**Comment by timurt** [comment]
fix conflicts

**Comment by shashwatj07** [comment]
> fix conflicts

done

**Pull request merged**
