### PR TITLE
Statements shouldn't be nested too deep. Issue #46

### PR DESCRIPTION
**Pull request by sabaka**
Nested if, for, while, switch and try statements is a key ingredient for making what's known as "Spaghetti code". Such code is hard to read, refactor and therefore maintain.

### CODE REVIEW

**Comment by romani** [comment]
1) Please provide description of Rule in each PR (or link to Rule) to prove intend , see PRs from Michal as example.

2)
>         if (!node.canRead()) {
            return result;

I do not agree with additional "return".

**Comment by sabaka** [comment]
Ok, let think about how deep we can nest blocks and ask sonar team to change this rule for us.
If you ask me, 3 is not enough. I think we have to have at least 4.
It will reduce amount of ridiculous changes in code, which I should do with current profile.

**Comment by romani** [comment]
1) please rebase

2) please redo changes where extra "return" appear, @rdiachenko do fight minimize amount of "return" in our code please consult with him for approaches to do refactoring without "return" .

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
