### PR TITLE
Issue #13213: removed suppressions related to inputinnerassignment

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Part of #13213 

removed UnnecessaryOkComment suppressions related to inputinnerassignment module

### CODE REVIEW

**Comment by MANISH-K-07** [comment]
@romani 
cc @nrmancuso 

Observed in PR #14488 , confirmed in the current PR : 
The  CircleCI workflow ci `no-error-xwiki` is failing again.

I previously worked on recovering the CI and set it to a stable commit but we closed the issue as the CI was working fine later.
Will using a stable SHA help now ?

**Review by romani — APPROVED** [review]
ok to merge

**Comment by romani** [comment]
@MANISH-K-07 , can you send xwiki a PR to fix checkstyle problem ?

**Comment by MANISH-K-07** [comment]
> @MANISH-K-07 , can you send xwiki a PR to fix checkstyle problem ?

@romani ,

The failure was a result of their latest commit https://github.com/xwiki/xwiki-rendering/commit/35f2d28904a791aab23ee1c5a5e5caba32b7b73b .
They have reverted this commit just a few hours ago and our CI seems healthy now.

Wouldn't it be helpful if we update our shell to a stable commit to avoid these issues ??

**Comment by romani** [comment]
It also problematic, as soon as they bump a version, old version stopping to compile.  They leak checkstyle violations less than do version bumps

**Pull request merged**
