### PR TITLE
Issue #2112: Fix IllegalStateException in JavadocTypeCheck

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by mkordas** [comment]
@Vladlis 
Code sample in #2112 is just:
```
/** @param x */
class Test {}
```
In test you provide 
```
/** @param <X The wrong type param. */
class Test {}
```

Can you confirm that both of these snippets produce the same exception? If yes, why not use simpler one from issue? `<` suggests that it has something to do with generics.

**Comment by Vladlis** [comment]
@mkordas
> Can you confirm that both of these snippets produce the same exception?

Sure

**Comment by mkordas** [comment]
@romani, I'm done with review, PR looks good

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
