### PR TITLE
Issue: #9373 Add example of AST for TokenTypes.ASSIGN

### PR DESCRIPTION
**Pull request by anshuman10398**
Closes: #9373 
Added The example of AST for TokenTypes.ASSIGN, used the simple assignment example (a = b; ), refer to the image for clarification.
image

### CODE REVIEW

**Comment by strkkk** [comment]
@anshuman10398 pls fix ci

**Comment by anshuman10398** [comment]
@strkkk how do i trigger the tests again?

**Comment by hungleba** [comment]
@anshuman10398 you can use "git commit --amend -m <message>" then "git push origin <branch name> --force" to trigger the test without creating a new PR.

**Comment by anshuman10398** [comment]
Thanks @hungleba

**Comment by strkkk** [comment]
@anshuman10398 please do not open/close PRs.

**Comment by anshuman10398** [comment]
@strkkk yeah sure, that was a beginner mistake, sorry :)

**Pull request closed without merging**
