### PR TITLE
doc: Update comment in google_checks.xml

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by Vladlis** [comment]
@mkordas, you also need to update all links in "Example of Usage" sections, such as https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_blocks.xml#L108-L109 and links in the google_style.xml, such as https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/google_style.xml#L167

**Comment by mkordas** [comment]
@Vladlis - thanks, well spotted. On the other hand all builds are green, so it shows how fragile current solution is. I don't think we should proceed without solid test that will check our references to the check usages.

**Comment by romani** [comment]
it is very hard to validate this, as line numbers are always exists in file.
we use linkcheck plugin to validate dead links, but this plugin does not have "check/verify"  goal and links will exists but reference to wrong place.

@mkordas , I recommend to keep the same line numbers in header and apply changes that want to introduce.

> https://google-styleguide.googlecode.com/svn-history/r130/trunk/javaguide.html

we need to change it to our cached location - http://checkstyle.sourceforge.net/reports/google-java-style.html , latest document on github.io could not correspond to our config .

**Comment by mkordas** [comment]
@romani, I meant JUnit test that goes through every example usage link and checks that at given line there is `<module name="XXXX"` occurence.
The main point of this PR is removing obsolete newlines, so if not possible I will just close it.

**Comment by mkordas** [comment]
Line-based references are not used anymore for `google_checks`, so this PR can be reopened.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
