### PR TITLE
make checkstyle.xml inheritable

### PR DESCRIPTION
**Pull request by qxo**
so we  can reuse the IT asset(checkstyle.xml) , and  just add module need modify.

ie: base google_checks.xml 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Checkstyle//DTD Checkstyle Configuration 1.4//EN"
    "https://checkstyle.org/dtds/configuration_1_4.dtd">
<module name="Checker" parent="google_checks.xml">
  <property name="tabWidth" value="4" />
  <property name="basedir" value="${checkstyle.basedir}" />
  <module name="LineLength">
    <property name="fileExtensions" value="java" />
    <property name="max" value="${checkstyle_LineLength_max}" default="130" />
    <property name="ignorePattern" value="^package.*|^import.*|a href|href|http://|https://|ftp://" />
  </module>
  <module name="TreeWalker">
    <module name="NoWhitespaceAfter">
      <property name="tokens" value="DOT" />
      <property name="allowLineBreaks" value="true" />
    </module>

    <module name="Indentation">
      <property name="basicOffset" value="4" />
      <property name="braceAdjustment" value="0" />
      <property name="caseIndent" value="4" />
      <property name="throwsIndent" value="4" />

    </module>
  </module>
</module>
```

------

Related discussion: #2873

### CODE REVIEW

**Comment by qxo** [comment]
@romani  @olivier-maury @rnveach  please review and merge this PR, thanks:)

**Review by rnveach — CHANGES_REQUESTED** [review]
We can't merge PR when CI is failing.

**Comment by romani** [comment]
we have not finished discussion on this topic https://github.com/checkstyle/checkstyle/issues/2873

**Comment by qxo** [comment]
@romani @rnveach  I can not see the detail of  [Wercker pipeline failed](https://app.wercker.com/checkstyle/checkstyle/runs/build/5f6572cc7e996800080ea970)
I need a help, thanks:)

**Comment by romani** [comment]
@qxo , please stop coding for a bit,
lets agree on expected behavior and design first. That is why we demand issue creation first and make sure maintainers put "approved" label on it before PR, to avoid efforts on coding that we will not accept.

`<module name="Checker" parent="google_checks.xml">`
is problematic concept as module is same entity and could be nested in other modules, BUT `google_checks.xml` is file (that contain another root module).
if this allowed it could be even `<module name="Indentation" parent="google_checks.xml">` that is weird.

Lets create issue or use existing and discuss design first.

**Comment by qxo** [comment]
> @qxo , please stop coding for a bit,
> lets agree on expected behavior and design first. That is why we demand issue creation first and make sure maintainers put "approved" label on it before PR, to avoid efforts on coding that we will not accept.
> 
> `<module name="Checker" parent="google_checks.xml">`
> is problematic concept as module is same entity and could be nested in other modules, BUT `google_checks.xml` is file (that contain another root module).
> if this allowed it could be even `<module name="Indentation" parent="google_checks.xml">` that is weird.
> 
> Lets create issue or use existing and discuss design first.

This first commit is my feature code , other just for fix the ci issues of the project.
English is not my native language,  there may have some language issues for discuss.
Maybe code is my best idea:)

Should we change the root node from "module" to as 'checker' or something other?
ie:
```
<module name="Checker" parent="google_checks.xml">
```
or
```
<checker  parent="google_checks.xml">
```

**Pull request closed without merging**
