### PR TITLE
Issue #3287: added exclude directory option

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3287

Issue is not yet approved.

### CODE REVIEW

**Comment by romani** [comment]
@rnveach ,

issue is approved.

please rebase PR to avoid red CIs. CI on master is green now.

Looks like you also need to change implementation too.

**Comment by romani** [comment]
@rnveach , issue is approved, lets finish this PR.

**Comment by rnveach** [comment]
@romani I updated this PR with what was discussed in the issue.

TC is failing again with the same issue as other PR, but I based this one is based on latest master.

**Comment by romani** [comment]
1)
> --xclude

please make it clear without reading documentation - "--exclude-regexp". The same for variable/constant names.
Short name "x" is ok.

2)
> String s

single char variables are not ok, please name it "value"

3)
> listFiles

update in this method  should be moved to separate method that calculate "allow"

**Comment by rnveach** [comment]
1,2,3 are done.

> single char variables are not ok, please name it "value"

We allow it [here](https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L358). Should that be `false`?

**Comment by romani** [comment]
> We allow it here. Should that be false? 

I know. It usually to ease naming for indexed loops. I do not remember why we switched this property in config. We could reconsider it in separate issue.

**Comment by rnveach** [comment]
@romani Travis failure says PR has no issue reference and issue is unapproved which isn't true.

**Pull request merged**
