### PR TITLE
Fix RightCurlyCheck with same option not to rise expression in single…

### PR DESCRIPTION
**Pull request by liscju**
…-line blocks - issue #1416 
Add additional guard to not raise error when block is in single line, removed test which test old behaviour of one line block(raising error)

### CODE REVIEW

**Comment by romani** [comment]
build is failed , please verify by "mvn clean verify" before you do PR.

**Comment by liscju** [comment]
@romani Fixed build

**Comment by romani** [comment]
I will review your code after #1355 , your changes is easier to rebase is required.

**Comment by MEZk** [comment]
@liscju 
You do not check the following cases at [singleLineBlock](https://github.com/checkstyle/checkstyle/pull/1423/files#diff-9b2a5f9e69b254b923cb4fd7420cb9a4R209)

````java
void foo() {int a;} int nextToken;
````
It is not a singleLineBlock. Do not use getNextToken method, because it works incorrectly. I prepare fix for that situation.

**Comment by liscju** [comment]
@MEZk thanks for comment, i'll definetely gonna to check it ( even though this PR gonna be closed because of duplication with yours:P)

**Comment by MEZk** [comment]
@liscju 
There might be some merge conflicts, but it will be easy to solve them, because your changes do not seriously affect my. All you need - do rebasing after my PR.

**Comment by romani** [comment]
@liscju , 
please rebase your changes on master, #1355 is merged. 
please generate HTML reports to prove that you do not introduce any regressions and only your cases are disappear from validation. Example: http://mezk.github.io/

**Comment by liscju** [comment]
Deleted use cases:

From testDefault():
if (flag) { System.err.println("it is ok."); } 

From testSame():
if (flag) { System.err.println("it is ok."); } 

All in testForceLineBreakBefore2()
} else { break; }
} catch (Exception e) { break; } finally { break; }
if (flag) { System.err.println("foo"); }

I launched checkstyle-tester on guava sources with RCurlyCheck and published result here http://liscju.github.io/issue1416/site/checkstyle.html . All four warning are about closing bracket in if statement being alone in line before line with else.

**Comment by romani** [comment]
1)
> All in testForceLineBreakBefore2()

please restore then test, if you have not violations it does not mean that you do not need that test. We test both correct code and incorrect.

2) 
we use that Check in Google config
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L63
so please update ITs Inputs with valid and invalid use cases.

3)
report in correct, please do changes requested in 1) and 2) and I am ready to merged your fix.

**Comment by romani** [comment]
@liscju , do you have time to continue this PR ?

**Comment by liscju** [comment]
@romani i am already on summer holiday , i will work on this issue by the end of a week

Roman Ivanov <notifications@github.com> napisał(a):

**Comment by romani** [comment]
take your time, enjoy a holiday, thanks for notification.

**Comment by liscju** [comment]
1) DONE - restored test removing non valid cases from it
2,3)  I have no idea where should i update IT inputs and how this should look like

**Comment by romani** [comment]
IT:
https://github.com/checkstyle/checkstyle/blob/master/src/it/java/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/LeftCurlyRightCurlyTest.java

from IT you can find Input files that are used, example - https://github.com/checkstyle/checkstyle/blob/master/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/LeftCurlyInput_Braces.java
all lines that have violation are marked as "//warn".

test input that you added to UTs Inputs should "copied" to IT Inputs and violation line should be marked as "//warn".

**Comment by liscju** [comment]
I added in LeftCurlyRightCurlyTest test rightCurlyTestSame to test same situations as i tested in UT, new test file for integration test is RightCurlyInputSame, but definetely it should be reviewed to check if i understand it (adding new IT tests) correctly.

**Comment by romani** [comment]
merged as FF.

thanks a lot for your persistence to fix that issue, I appreciate that.

if you have time, please generate report against Guava before and after fix - https://github.com/checkstyle/checkstyle/wiki/How-to-generate-Checkstyle-report-for-Google-Guava-project
if some false-positives are fixed by your changes, you can report that to https://github.com/google/guava/issues/1891 after 6.10 release.

**Comment by liscju** [comment]
Before fix guava report:
http://liscju.github.io/issue1416Guava/beforeFix/target/site/checkstyle-aggregate.html

After fix guava report:
http://liscju.github.io/issue1416Guava/afterFix/target/site/checkstyle-aggregate.html

Reports are the same

**Comment by romani** [comment]
ok, thanks a lot !

**Pull request closed without merging**
