### PR TITLE
minor: remove and shrinks excess helper input files

### PR DESCRIPTION
**Pull request by rnveach**
Identified from https://github.com/rnveach/checkstyle/commits/verify_test_inputs_used .

### CODE REVIEW

**Comment by rnveach** [comment]
It seems odd to me that this helper input is required to have ok/warning comments when it is not parsed.

We cannot remove helpers that use an active import unless we make it non-compilable.

**Comment by rnveach** [comment]
Wercker failure:
> Exception in thread "main" java.lang.Error: Error was thrown while processing /pipeline/source/.ci-temp/contribution/checkstyle-tester/src/main/java/local-checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserNoStackOverflowOnDeepStringConcat.java

This error seems unrelated to my PR. Everything else is passing.

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
GitHub, rebase

**Comment by romani** [comment]
@rnveach , we do not need to shrink Inputs, we more weird code the better, it will give us benefits by side effects and we will less depend on diff report.

**Comment by rnveach** [comment]
@romani Ok. If we leave helpers in like this, then it will create more overrides in https://github.com/rnveach/checkstyle/commits/verify_test_inputs_used if we decide to implement something like this. This kind of verification will force new contributors to use a single file for their inputs.

**Pull request merged**
