### PR TITLE
Issue 2944 - EmptyLineSeparator to check empty lines inside methods

### PR DESCRIPTION
**Pull request by ychulovskyy**
#2944

It become a little bit hard to contribute because:
1. Checkstyle import order is different from standard IDEA setting (OK, it's described here http://checkstyle.sourceforge.net/idea.html but is there any reason to do so?)
2. Default IDEA indentation is different from Checkstyle setting for Array items
3. Any reason to declare each method variable as final? It's harder to read and doesn't really helps to avoid issues since if you modify the variable then Checkstyle will not ask you to mark the variable as final.
4. Failed to execute goal org.jacoco:jacoco-maven-plugin:0.7.5.201505241946:check (default-check) on project checkstyle: Coverage checks have not been met.
In logs I see "[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.AbstractDeclarationCollector: lines covered ratio is 0.00, but expected minimum is 1.00" but I haven't touched the file!

### CODE REVIEW

**Comment by romani** [comment]
> It become a little bit hard to contribute because

Welcome back to Checkstyle , during a year we did a lot . Yes, now it become harder to contribute ugly, fragile, untested, dead, ... code. But if you are not going to contribute such code, CI + code review + your manual testing will follow you to make good code.  Rules for all contributions are severe. Right now it is much easier to control code quality , bugs, regressions in comparison to what we had 1 year ago.

> but is there any reason to do so?

Each IDEs have different formats for imports order. Defaults formats are not matching. Contributor can use any of them. We are not IDEA focused. We do more focus to Eclipse. 
Our ImportOrder Check is not ideal, if you know how to make it better - please be welcome.

>  Default IDEA indentation is different from Checkstyle setting for Array items

happens, we do not consider IDEA format as primary. It would be geed to have ready to use IDEA formatter file in our repo. Please be welcome to create it.

> Any reason to declare each method variable as final?

I personally do like this style. Few reasons:  it was there already for all code, it is not bad style, some our contributors do like this style, and voted to keep it, we have to use all Checks against our code, .... .
Please think about it as "fanatic point" in our team.

> Failed to execute goal org.jacoco:jacoco-maven-plugin

We do not use jacoco. it exists in config, but we failed to make it work. We are still rely on cobertura . It suits us better. You can find checkstyle issue about jacoco and read all details.

---------------

Please follow instructions:
https://travis-ci.org/checkstyle/checkstyle/jobs/110815061#L788

Code coverage problem should be resolved:
https://travis-ci.org/checkstyle/checkstyle/jobs/110815063#L948

**Comment by romani** [comment]
thanks a lot.

Why I am looking into your code, please start testing.
You need prepare 2 diff reports:
1)with new option as FALSE  on 
2) with new option as TRUE.
3) share both results(html sites) on your github.io to our team for verification.
generation of html report tool - https://github.com/checkstyle/contribution/tree/master/checkstyle-tester
diff report generation tool - https://github.com/checkstyle/contribution/tree/master/patch-diff-report-tool

**Comment by ychulovskyy** [comment]
@romani I thought everything is automated. There is nothing about such requirements on Contribution page http://checkstyle.sourceforge.net/contributing.html

**Comment by romani** [comment]
> I thought everything is automated. 

:( , not everything, even we already have tools for testing (they are not finished, but they works),  there is no easy way(but possible) create configuration base on proposed batch. Human is still required to create required configuration file for testing functionality that is changed. There are a lot of room for improvements, so you are welcome as contributor.

> There is nothing about such requirements on Contribution page

`The last step of verification that all works fine please do testing of your functionality on any open-source project (Spring, Hibernate, ....). Here is how to do it from ....` 

Here is a demand for testing.
Not all patches require manual testing, and manual verification of results. I make a decision base on PR individually.

You need to prove that your change do not lead to Exceptions by stress testing of your new option on all open-source projects that we have in checkstyle-tester.
Additionally we need special diff report for Guava projects to make sure that we are not introducing any unexpected behaviour, as this Check is used in Google Style(google_checks.xml).

**Comment by romani** [comment]
1) please make all formatting changes in separate PR.
FYI: formatting at `isViolatingEmptyLineBetweenFieldsPolicy` was done on purpose, and have to stay unchanged. One day IDEA will support this.

2) Please add config and code example to javadoc and xdoc to explain user when violation will be, and what code is valid.

3)
> private boolean allowMultipleEmptyLinesInsideClassMembers;

default is `true`. To keep compatibility with previous behaviour.

4)
> checkForMultipleLinesInside(ast);

please follow naming convention that is in this Check, "process......"

5)
> `if (emptyLines.size() < 2) {`

please make it "<=1" . It is much easier to understand.

6)
> getNextSequenceStartNo

single return point from method.

7)
> logEmptyLines

please inline this function. it is only ones.

8)
In javdoc and xdoc please make a note that option become inactive , if there are no  Tokens  
```
            TokenTypes.CLASS_DEF,
             TokenTypes.INTERFACE_DEF,
             TokenTypes.ENUM_DEF,
             TokenTypes.STATIC_INIT,
             TokenTypes.INSTANCE_INIT,
             TokenTypes.METHOD_DEF,
             TokenTypes.CTOR_DEF,
```

**Comment by ychulovskyy** [comment]
@romani Deleted fork by mistake. That is why I've created new pull request.
Code review items has been fixed.
The reports haven't been generated since the tool works for Linux only. I use Windows.

**Comment by romani** [comment]
> The reports haven't been generated since the tool works for Linux only. I use Windows.

please read README file https://github.com/checkstyle/contribution/tree/master/checkstyle-tester , it is working on windows too, windows CI use it to test each commit.

**Comment by ychulovskyy** [comment]
@romani Sorry, it becomes time-consuming. Feel free to reject the pull request.

**Comment by romani** [comment]
@ychulovskyy , if you do not want to continue, please put a note in PR and allow me/others to let finish your PR. You could loose your authorship of commit, but functionality will merged eventually.

**Pull request closed without merging**
