### PR TITLE
Issue #5350: aviod usage of messages attribute in suppression xml

### PR DESCRIPTION
**Pull request by romani**
Issue #5350

I do not now how to enforce this in CI but let unblock users first.

### CODE REVIEW

**Comment by rnveach** [comment]
@romani This is breaking one of your rules in which we should show users example of functionality in our project. You are asking this for xpath filter to use a valid use case. With this removed, suppression by message isn't used anywhere in our project.
What is wrong with enforcing config to a specific locale as specified at https://github.com/checkstyle/checkstyle/issues/5350#issuecomment-351078885 ?
With this fully removed, users can again write bad/incomplete javadocs in the test tier which is what this fixed. See https://github.com/checkstyle/checkstyle/commit/2a4e5e6d9bc027ac1afc387d2a7392d87e9394d0 .

**Comment by romani** [comment]
>This is breaking one of your rules in which we should show users example of functionality in our project.

Yes, all such cases are unfortunate.  But imagine what user will value more, ability to build out of the box or example of usage for very simple functionality.

I am planning to update xdoc to bring user attention that suppression by message is not stable, it is not the first time to stamble on this ( we had a case with imports order for intellij idea)

>What is wrong with enforcing config to a specific locale as specified at #5350 (comment) ?

Replied there.


>If we don't validate it, then we lose any hope of maintaining a style.

We validate it in main code. We just ignore it in test code, where comments are usually not good to have. Even we would like to enforce smth it will force us to think about better suppression model ( by message id, ....).

**Comment by rnveach** [comment]
> think about better suppression model ( by message id, 

This was my latest comment in the issue. Lets make a new issue on it.
Can we do a temporary fix like enforcing english locale and then remove it when we have suppression by message id instead of letting the test tier javadocs go down in style?

**Comment by rnveach** [comment]
Same warning will need to be added to https://github.com/checkstyle/checkstyle/pull/6172

**Comment by romani** [comment]
squashed, merged manually

**Pull request closed without merging**
