### PR TITLE
Issue #4900: refactored DetailASTTest.testTreeStructure

### PR DESCRIPTION
**Pull request by rnveach**
Issue #4900

Blocked by https://github.com/checkstyle/checkstyle/pull/6629

### CODE REVIEW

**Comment by rnveach** [comment]
https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/23659270/job/yro2l23r0foo9cvk#L179
> com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred while parsing file C:\projects\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\grammar\InputGrammar.java.
	at com.puppycrawl.tools.checkstyle.api.DetailASTTest.testTreeStructure(DetailASTTest.java:428)
Caused by: antlr.TokenStreamRecognitionException: Unexpected character 0xaf in identifier
	at com.puppycrawl.tools.checkstyle.api.DetailASTTest.testTreeStructure(DetailASTTest.java:428)

Weird I don't get this on my local.

**Comment by romani** [comment]
@rnveach , all CIs are green, fyi.

**Comment by rnveach** [comment]
> I do not see change in pmd config.

Done.

> all CIs are green

I was hoping to merge DetailAST interface first, but I might just do this one first if we decide to group more breaking changes together.

**Comment by rnveach** [comment]
@romani feel free to review now.

**Pull request merged**
