### PR TITLE
Issue #11446: Update CheckerTest With VerifyWithInlineConfigParser

### PR DESCRIPTION
**Pull request by piyush-1234**
Issue: #11446 

this pr is not ready, as pitest are failing.

pitests are failing, working on that.

### CODE REVIEW

**Comment by rdiachenko** [comment]
@piyush-1234 please move this PR to a draft state if it is not ready for review.

**Comment by piyush-1234** [comment]
hi @romani , i have written a test case to cover some of these mutations 

` <mutation unstable="false">
+    <sourceFile>Checker.java</sourceFile>
+    <mutatedClass>com.puppycrawl.tools.checkstyle.Checker</mutatedClass>
+    <mutatedMethod>processFile</mutatedMethod>
+    <mutator>org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator</mutator>
+    <description>removed call to java/lang/Exception::printStackTrace</description>
+    <lineContent>ex.printStackTrace(pw);</lineContent>
+  </mutation>
+
+  <mutation unstable="false">
+    <sourceFile>Checker.java</sourceFile>
+    <mutatedClass>com.puppycrawl.tools.checkstyle.Checker</mutatedClass>
+    <mutatedMethod>processFile</mutatedMethod>
+    <mutator>org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator</mutator>
+    <description>removed call to java/util/SortedSet::add</description>
+    <lineContent>fileMessages.add(new Violation(1,</lineContent>
+  </mutation>
+
+  <mutation unstable="false">
+    <sourceFile>Checker.java</sourceFile>
+    <mutatedClass>com.puppycrawl.tools.checkstyle.Checker</mutatedClass>
+    <mutatedMethod>processFile</mutatedMethod>
+    <mutator>org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator</mutator>
+    <description>removed call to java/io/IOException::getMessage</description>
+    <lineContent>new String[] {ioe.getMessage()}, null, getClass(), null));</lineContent>
+  </mutation>
+
+  <mutation unstable="false">
+    <sourceFile>Checker.java</sourceFile>
+    <mutatedClass>com.puppycrawl.tools.checkstyle.Checker</mutatedClass>
+    <mutatedMethod>processFile</mutatedMethod>
+    <mutator>org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator</mutator>
+    <description>removed call to java/lang/StringBuffer::toString</description>
+    <lineContent>new String[] {sw.getBuffer().toString()},</lineContent>
+  </mutation>
+
+  <mutation unstable="false">
+    <sourceFile>Checker.java</sourceFile>
+    <mutatedClass>com.puppycrawl.tools.checkstyle.Checker</mutatedClass>
+    <mutatedMethod>setCharset</mutatedMethod>
+    <mutator>org.pitest.mutationtest.engine.gregor.mutators.experimental.MemberVariableMutator</mutator>
+    <description>Removed assignment to member variable charset</description>
+    <lineContent>this.charset = charset;</lineContent>
+  </mutation>`

issues i am facing :
1. no of lines in the test class exceeded.
2. also i have dought in using FileSetCheck as anonymous directly as its process method implementation is final so abstractFileSetCheck will not help through DUmbFIleSetCheck 

looks like i am stuck here.
need some help.

**Comment by romani** [comment]
You try to fix all at ones, it is not easy.
Can make PR for the each method separately? So we will discuss it separately and merge step by step.

**Comment by piyush-1234** [comment]
> You try to fix all at ones, it is not easy. Can make PR for the each method separately? So we will discuss it separately and merge step by step.

ok then, raising method by method then

**Pull request closed without merging**
