### PR TITLE
Resolved warnings during '-all.jar' generation, issue #756

### PR DESCRIPTION
**Pull request by alexkravin**
Resolved warnings during project assembling (building -all.jar)

### CODE REVIEW

**Comment by romani** [comment]
please explain a reason of "scope=provided" ?
Please provide what jars have the same classes, and I expect to use "exclude" of dependency in pom configuration.

**Comment by alexkravin** [comment]
As you can see in warning log, there's a mention about shade plugin which I used to solve the problem, so exclude or any other hacks required.

Packages org.abego.XXX are duplicated, one from parent's pom org.oss.sonatype and other from antlr4-runtime

I'm not sure about version of this package from parent-pom, so no exclusion from antlr4 dependency are needed.

**Comment by romani** [comment]
"provided" that is real hack, "provide" feature is not for this, please read http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

>  one from parent's pom org.oss.sonatype

please give me a name of it.

**Comment by alexkravin** [comment]
I rechecked the versions of duplicated dependencies and they're similar
From antlr's pom:
```
<dependencies>
		<dependency>
			<groupId>org.abego.treelayout</groupId>
			<artifactId>org.abego.treelayout.core</artifactId>
			<version>1.0.1</version>
		</dependency>

	</dependencies>
```

From parent:
```
<parent>
    <artifactId>oss-parent</artifactId>
    <groupId>org.sonatype.oss</groupId>
    <version>9</version>
  </parent>

->

<groupId>org.abego.treelayout</groupId>
    <artifactId>org.abego.treelayout.core</artifactId>
    <version>1.0.1</version>
```

So in this case we can resolve the problem by dependency's exclusion, updated.

**Comment by romani** [comment]
we need to use version that is in antlr and skip a parent version, please use dependencyManagement tag, read http://stackoverflow.com/questions/2681759/is-there-anyway-to-exclude-artifacts-inherited-from-a-parent-pom

Please put a comment in pom to describe a reason of override.

**Comment by alexkravin** [comment]
Same versions, what's the reason of complexing?

**Comment by alexkravin** [comment]
As expected, dependencyManagement is used when parent pom is accessible.
So in our case removing duplicate or provide via shade-plugin, I'm sure there're a lot of cases to do the same but no reason to test here all of them.

**Comment by alexkravin** [comment]
maven-dependency-plugin helped in this problem.
Updated

**Comment by alexkravin** [comment]
During analyzing the problem I found out the best way would be <b>provided</b> scope as it was done by me in first commit.

So there's no exclusion from parent or smth else as it's specified here:
http://maven.40175.n5.nabble.com/Is-there-a-way-to-exclude-a-inherited-dependency-td120406.html
The last comment shows there's no easy way.

Provided scope means expected dependency is provided at a runtime, in our case antlr brings this dependency at a runtime, so there's no need to package this dependency explicitcly.

Looks now
libs64

After update
libs65

Antlr is packaged, so all its dependencies would be available.

**Comment by romani** [comment]
I did not receive from you answer to simple question:

from what artifact that conflicts are commitng, I need 2 links to line number in poms from two artifacts that have that conflicting dependency.

**Comment by alexkravin** [comment]
From pom.xml:
https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L19
https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L184

**Comment by romani** [comment]
both of that links should be pointed to line as ```<artifactId>org.abego.treelayout.core</artifactId>```, so please find exact POM xmls that have that conflicting lines in dependency.

**Comment by romani** [comment]
completely wrong way to resolve a problem. closed.

**Pull request closed without merging**
