### PR TITLE
Issue #3201: Add new property to ignore inline array trailing comma

### PR DESCRIPTION
**Pull request by kukreja-vikramaditya**
Issue #3201

### CODE REVIEW

**Comment by kukreja-vikramaditya** [comment]
@romani Could you please restart TeamCity and Shippable runs?

**Comment by kukreja-vikramaditya** [comment]
@romani 

https://kukreja-vikramaditya.github.io/checkstyle-diff-reports/

For diff reports.
There are a lot of violations in this ... Can you tell me whether anonymous arrays be included? I am not clear on including such arrays when searching for inline cases?

Please advise.

**Comment by romani** [comment]
@kukreja-vikramaditya ,

sorry for late reply, but took me some time to understand that smth is weird in this feature request.
please participate at https://github.com/checkstyle/checkstyle/issues/3201#issuecomment-325128722

> Can you tell me whether or not anonymous arrays should be included?

please ask this question to author of issue, please join to discussion in issue.

**Comment by kukreja-vikramaditya** [comment]
Closing this and starting new PR as per #3201 comment

**Pull request closed without merging**
