### PR TITLE
Issue #5116: enabled eclipse compiler check in test code

### PR DESCRIPTION
**Pull request by rnveach**
Issue #5116

### CODE REVIEW

**Comment by rnveach** [comment]
Only warning remains is `At least one of the problems in category 'deprecation' is not analysed due to a compiler option being ignored` which I'm not sure what it is related to as I don't get this in eclipse.

**Comment by rnveach** [comment]
@romani It looks like the infos for the eclipse compiler are only on `@SuppressWarnings("deprecation")` in test and this is the only example of the 3 times we use. There are many other cases of using deprecated methods where we don't put a suppression.
Do we not use these annotations to suppress deprecations, so I should just remove them?

**Comment by romani** [comment]
> Do we not use these annotations to suppress deprecations, so I should just remove them?

All of them appear to suppress some warnings in the past, if smth changed and now they are useless or .... we can remove them

**Comment by rnveach** [comment]
@romani IDEA is passing now.
Travis is failing because issue isn't approved.
This removes all eclipse violations in test.

**Comment by rnveach** [comment]
Rebased.
Can be merged once CI passes.

**Comment by rnveach** [comment]
Merged

**Pull request merged**
