### PR TITLE
Issue #12224: document limitation regarding same-name imports

### PR DESCRIPTION
**Pull request by stoyanK7**
Issue #12224

### CODE REVIEW

**Comment by stoyanK7** [comment]
Github, generate site

**Comment by stoyanK7** [comment]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/330b831_2022161150/config_imports.html#UnusedImports

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
I think it makes sense to reference issue in commit, I can change title of issue to be `unusedimport: add limitation regarding same-name imports`

**Comment by romani** [comment]
Issue title is updated, please change commit message to reference it.

**Comment by stoyanK7** [comment]
@romani Done.

**Pull request merged**
