### PR TITLE
Issue #56: fix NPathComplexityCheck

### PR DESCRIPTION
**Pull request by attatrol**
Issue #56 .

This PR is currently incomplete: it lacks single mock test to satisfy cobertura 100% coverage demand.
1. It implements correct calculation of NPath complexity for conditional with complex boolean expression, even for those containing ternary operator.
2. It adds calculation for return operator.
3. It fixes calculation for switch statement.
4. It doesn't implement NPath calculation for try-catch-finally statements yet. It is a question if we need such calculation. Pmd doesn't implement this calculation and there is no formula in original paper.
5. I have no idea of how to perform regressional test for this check.

### CODE REVIEW

**Comment by romani** [comment]
1)
Please resolve TC  violations

2)
> //debugInto(ast);

please  remove commented out code

3)
> 
```
        for (bracketed = ast.findFirstToken(TokenTypes.LPAREN).getNextSibling(); bracketed
                .getType() != TokenTypes.RPAREN; bracketed = bracketed.getNextSibling()) {
```

look weird and ugly. Please make it good to read.

4)
Code update is huge. Do you try to fix all issues on NPath ? https://github.com/checkstyle/checkstyle/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Npath

**Comment by attatrol** [comment]
@romani ,
1)

> Please resolve TC violations

 Done
2)

> please remove commented out code

Done

3)

> 
>             for (bracketed = ast.findFirstToken(TokenTypes.LPAREN).getNextSibling(); bracketed
>                     .getType() != TokenTypes.RPAREN; bracketed = bracketed.getNextSibling()) {
> 
> look weird and ugly. Please make it good to read.

Done.

4)

> Code update is huge. Do you try to fix all issues on NPath ?

This PR fixes switch statement calculation and implements return statement calculation as described in Nejmeh's article, issue #146 is unrelated. Personally i think issue author is wrong in his thought that check should analyze code blocks and determine if there is an exit point.
Issue  #616 (continue and break statements) is hard to solve because we have to store additional data about all loops we have entered (labeled break statements would be particulary hard), this is beyond stack calculator we have now.

Indeed the update is huge because i had to reclassify tokens according to the way how their expressions are placed in AST and add additional stack for the storing expression values. I understand that regression testing wille be hard, i compared my report with pmd report with an ad-hoc modified patch-diff-report-tool with guava as tested code and found that i have about 75% coincidences. However there are inaccuraces in pmd itself.

**Comment by romani** [comment]
>  issue #146 is unrelated. Personally i think issue author is wrong in his thought that check should analyze code blocks and determine if there is an exit point.

please share your opinion publicly - it is valuable. If you can prove that by quotes from Npath algorithm description it will be awesome.

> Issue #616 (continue and break statements) is hard to solve because we have to store additional data about all loops we have entered (labeled break statements would be particulary hard), this is beyond stack calculator we have now.

It this is just hard and require more time - it is ok. If that request conflicts with original NPath algorithm, we will implement this request by special option. Please share your opinion in that issue.

5)
> public int[] getDefaultTokens() {
public int[] getAcceptableTokens() {

the same collelction - please call getAcceptableTokens from getDefaultTokens

6)
> public int[] getRequiredTokens() {

If we define this set, it mean that user could launch Chekc only on this set of tokens. What is a reason for this ? Algoritm is general and expected to analyse whole code without any exceptions.

**Comment by romani** [comment]
7) 
> rangeValueStack , expressionValueStack

do we really need "Stack" in names, collections usually looks ok withtout "Map", "List" prefixes/sufixes.
please remove.

8)
> 
```
    public void beginTree(DetailAST rootAST) {
        processedExpressionRange.resetRange();
    }
```

not all class fields are cleaned in beginTree. All Class fields that are not options should be reseted to initial state as the same instance of check is reused for all files.
It is time to make it automatically detected - #2939 is created.


9)
>
```
        final int expressionValue = basicBranchingFactor + countLogicalOperators(ast);
       processedExpressionRange.setRange(ast, getLastToken(ast));
       pushValue(expressionValue);
```

distance between `final int expressionValue ` and `pushValue(expressionValue)` should be minimal.


10)
>
```
            else if (type == TokenTypes.QUESTION) {
                number += 2;
```

please explain in comment what is "2".

**Comment by romani** [comment]
11)
>
````
            case TokenTypes.LITERAL_DEFAULT:
                visitBranch(0);
                break;
            case TokenTypes.CASE_GROUP:
                visitCaseGroup(ast);
````

Please inline `visitCaseGroup` to the SWITCH it will be more clear  why  DEFAULT processing is different from CASE_GROUP. It will not create any complexity raise for metrics.

12)
> visitMethodDef, visitBranch

single&simple statement methods .... Does it make sense to in-line them to SWITCH ?

13)
> private int countLogicalOperators(DetailAST ast) 
private DetailAST getLastToken(DetailAST ast) {
private int countCaseTokens(DetailAST ast) {

could be `static` ?

14)
> SpatialRange

I do not like this word "Spatial" can you rename it ? can you explain why "Spatial" ?

**Comment by romani** [comment]
@attatrol , it will be so awesome to fix this issue.

**Comment by romani** [comment]
@attatrol , do you plan to continue this PR ?

It is hanging for very long time. 

If you do not have time please do not block this issue to be resolved and allow us to finish. You might loose authorship of your change.

**Comment by attatrol** [comment]
@romani,
i can't do anything for this check until i pass summer session, should i revoke PR?

**Comment by romani** [comment]
@attatrol ,
no need to revoke a PR, I could ask smb else to finish your PR, just need to get confirmation from you that you are ok to let other person to finish.

**Comment by attatrol** [comment]
i'm ok, please inform me if someone is assigned

**Comment by romani** [comment]
you will see comments/activity in this PR if smb agree to finish your work.

**Comment by romani** [comment]
work will be continued at  #3785

**Pull request closed without merging**
