### PR TITLE
Added feeds icons to Checkstyle's site, issue #617

### PR DESCRIPTION
**Pull request by alexkravin**
Added rss and google groups icons with corresponding links to checkstyle's twitter and mail-list (google group).

As banners and such links are specifying in site.xml - these logos will appear in all pages.

### CODE REVIEW

**Comment by romani** [comment]
1) 
Point "1)" from issue is not done. Expected location square of images is below "
Last Published: 2015-02-01  | Version: 6.3 " and above "Release 6.3" alligned to right side of the page

2) images should be : http://www.freepik.com/free-psd/bold-orange-rss-subscribe-buttons-psd_597344.htm

google group image should be like there (with same text, but image is a bit bigger) : http://www.safeharbors.org/SHUserGroup.htm

All images should be hosted on our site.

**Comment by alexkravin** [comment]
Added images, they're hosted in <b>images</b> folder of the site

http://alexkravin.github.io/site/releasenotes.html
example

**Comment by romani** [comment]
1) 
> Point "1)" from issue is not done. Expected location square of images is below "
Last Published: 2015-02-01 | Version: 6.3 " and above "Release 6.3" alligned to right side of the page

that top conner images should be seen only at one page - releasenotes.html. Images should be square by form as I described in original issue.

2)
RSS is not a Twitter , find link to rss at https://sourceforge.net/p/checkstyle/news/?source=navbar

3) 
>> google group image should be like there (with same text, but image is a bit bigger) : http://www.safeharbors.org/SHUserGroup.htm

I do not see the same text !!!!, please make sure that google_group banner is looks the same as all other banners - rectangle by form.

4) Rectangle Rss image should be posted  on left side.

**Comment by alexkravin** [comment]
Expected location square of images is below "
Last Published: 2015-02-01 | Version: 6.3 " and above "Release 6.3" alligned to right side of the page

2) images should be : http://www.freepik.com/free-psd/bold-orange-rss-subscribe-buttons-psd_597344.htm

-------------------------------

Images should be square by form as I described in original issue.
Rectangle Rss image should be posted on left side.

So, where exactly images should be located?

**Comment by romani** [comment]
I updated original issue with all that additional comments, I am closing that issue to avoid any further misunderstandings

**Pull request closed without merging**
