### PR TITLE
Issue #7587: Examples added for Descendant Token

### PR DESCRIPTION
**Pull request by athuma**
Issue #7587

I have added all the examples except for assert statement and method with too many expression.
I am not getting how to test these two configs please check all the other changes and merge this.

I have opened a PR earlier but because of some mistake it got closed that's why raising new PR sorry for the confusion.

### CODE REVIEW

**Comment by romani** [comment]
Please fix all problems that CI points to.

**Comment by romani** [comment]
GitHub, generate website

**Comment by athuma** [comment]
can you please describe in detail what should i do now?

**Comment by romani** [comment]
Click in all CI failures, like https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=13379&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=1397

And do update on code as it requires.

**Comment by athuma** [comment]
when i imported checkstyle into eclipse as a maven project i got build errors in eclipse are these errors caused by those build errors in eclipse? 
i am not getting how to solve these errors can you please help @romani

**Comment by nrmancuso** [comment]
@athuma please share links to failures that you do not understand, error messages, and what you have tried so far to resolve errors.

**Comment by athuma** [comment]
@nrmancuso
1. https://github.com/checkstyle/checkstyle/pull/12798/checks?check_run_id=11763822316
2. https://github.com/checkstyle/checkstyle/pull/12798/checks?check_run_id=11763909620
3. https://github.com/checkstyle/checkstyle/pull/12798/checks?check_run_id=11763822362

These 3 i am not getting and i have resolved the error for the pull request comment

**Comment by athuma** [comment]
now the errors are coming because of the comment message of each commit added now

**Comment by athuma** [comment]
@romani what should i do now?

**Comment by romani** [comment]
Do single commit, and make sure `mvn verify ` passing on your local .

After push, review CI failures and try to Google them or investigate how to resolve.

**Comment by athuma** [comment]
i think this is looking too much messy i will start fresh @romani

**Comment by nrmancuso** [comment]
@athuma please do not close/open PRs, this just generates a bunch of noise. You can fixup/squash/amend commits in this PR, please reopen it and do this.

**Comment by athuma** [comment]
sorry @nrmancuso i am new to git let me do this one time i will not close and open PR again

**Pull request closed without merging**
