### PR TITLE
Issue #2541: Activate forbidden-apis on test input files

### PR DESCRIPTION
**Pull request by MEZk**
issue #2541 

@romani 
Just want to show that actiovation of forbiddes-apis on test input files results in ArrayIndexOutOfBoundsException inside forbidden-apis itself.

I am not able to get the full stacj trace even with ```mvn verify -e -X```.

```
[INFO] --- forbiddenapis:2.2:testCheck (default) @ checkstyle ---
[DEBUG] Configuring mojo de.thetaphi:forbiddenapis:2.2:testCheck from plugin realm ClassRealm[plugin>de.thetaphi:forbiddenapis:2.2, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[DEBUG] Configuring mojo 'de.thetaphi:forbiddenapis:2.2:testCheck' with basic configurator -->
[DEBUG]   (f) bundledSignatures = [jdk-unsafe, jdk-deprecated, jdk-system-out, jdk-non-portable]
[DEBUG]   (f) classesDirectory = /Touro/IDEA_Projects/checkstyle/target/test-classes
[DEBUG]   (f) classpathElements = [/Touro/IDEA_Projects/checkstyle/target/test-classes, /Touro/IDEA_Projects/checkstyle/target/classes, /home/andreiselkin/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar, /home/andreiselkin/.m2/repository/org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.jar, /home/andreiselkin/.m2/repository/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.jar, /home/andreiselkin/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar, /home/andreiselkin/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar, /home/andreiselkin/.m2/repository/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar, /home/andreiselkin/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar, /home/andreiselkin/.m2/repository/org/apache/ant/ant/1.9.7/ant-1.9.7.jar, /home/andreiselkin/.m2/repository/org/apache/ant/ant-launcher/1.9.7/ant-launcher-1.9.7.jar, /home/andreiselkin/.m2/repository/junit/junit/4.12/junit-4.12.jar, /home/andreiselkin/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar, /home/andreiselkin/.m2/repository/com/github/stefanbirkner/system-rules/1.16.0/system-rules-1.16.0.jar, /home/andreiselkin/.m2/repository/nl/jqno/equalsverifier/equalsverifier/2.1.3/equalsverifier-2.1.3.jar, /home/andreiselkin/.m2/repository/org/powermock/powermock-api-mockito/1.6.5/powermock-api-mockito-1.6.5.jar, /home/andreiselkin/.m2/repository/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar, /home/andreiselkin/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar, /home/andreiselkin/.m2/repository/org/powermock/powermock-api-mockito-common/1.6.5/powermock-api-mockito-common-1.6.5.jar, /home/andreiselkin/.m2/repository/org/powermock/powermock-api-support/1.6.5/powermock-api-support-1.6.5.jar, /home/andreiselkin/.m2/repository/org/powermock/powermock-module-junit4/1.6.5/powermock-module-junit4-1.6.5.jar, /home/andreiselkin/.m2/repository/org/powermock/powermock-module-junit4-common/1.6.5/powermock-module-junit4-common-1.6.5.jar, /home/andreiselkin/.m2/repository/org/powermock/powermock-core/1.6.5/powermock-core-1.6.5.jar, /home/andreiselkin/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar, /home/andreiselkin/.m2/repository/org/powermock/powermock-reflect/1.6.5/powermock-reflect-1.6.5.jar, /home/andreiselkin/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar, /home/andreiselkin/.m2/repository/org/eclipse/jgit/org.eclipse.jgit/4.4.1.201607150455-r/org.eclipse.jgit-4.4.1.201607150455-r.jar, /home/andreiselkin/.m2/repository/com/jcraft/jsch/0.1.53/jsch-0.1.53.jar, /home/andreiselkin/.m2/repository/com/googlecode/javaewah/JavaEWAH/0.7.9/JavaEWAH-0.7.9.jar, /home/andreiselkin/.m2/repository/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar, /home/andreiselkin/.m2/repository/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar, /home/andreiselkin/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar, /home/andreiselkin/.m2/repository/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar, /home/andreiselkin/.m2/repository/org/slf4j/slf4j-simple/1.7.21/slf4j-simple-1.7.21.jar, /home/andreiselkin/.m2/repository/org/jacoco/org.jacoco.agent/0.7.7.201606060606/org.jacoco.agent-0.7.7.201606060606-runtime.jar, /usr/lib/jvm/java-8-oracle/jre/../lib/tools.jar]
[DEBUG]   (f) disableClassloadingCache = false
[DEBUG]   (f) excludes = [**/Main.class, **/GeneratedJavaLexer.class, **/JavadocParser.class]
[DEBUG]   (f) failOnMissingClasses = true
[DEBUG]   (f) failOnUnresolvableSignatures = true
[DEBUG]   (f) failOnUnsupportedJava = false
[DEBUG]   (f) failOnViolation = true
[DEBUG]   (f) internalRuntimeForbidden = false
[DEBUG]   (f) localRepository =       id: local
      url: file:///home/andreiselkin/.m2/repository/
   layout: default
snapshots: [enabled => true, update => always]
 releases: [enabled => true, update => always]

[DEBUG]   (f) packaging = jar
[DEBUG]   (f) remoteRepositories = [      id: sonatype-nexus-snapshots
      url: https://oss.sonatype.org/content/repositories/snapshots
   layout: default
snapshots: [enabled => true, update => daily]
 releases: [enabled => false, update => daily]
,       id: central
      url: https://repo.maven.apache.org/maven2
   layout: default
snapshots: [enabled => false, update => daily]
 releases: [enabled => true, update => daily]
]
[DEBUG]   (f) skip = false
[DEBUG]   (f) targetVersion = 1.8
[DEBUG] -- end configuration --
[INFO] Scanning for classes to check...
[INFO] Reading bundled API signatures: jdk-unsafe-1.8
[INFO] Reading bundled API signatures: jdk-deprecated-1.8
[INFO] Reading bundled API signatures: jdk-system-out
[INFO] Reading bundled API signatures: jdk-non-portable
[INFO] Loading classes to check...
[INFO] Scanning classes for violations...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:55 min
[INFO] Finished at: 2016-08-06T21:16:24+03:00
[INFO] Final Memory: 139M/738M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal de.thetaphi:forbiddenapis:2.2:testCheck (default) on project checkstyle: Execution default of goal de.thetaphi:forbiddenapis:2.2:testCheck failed: 65535 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal de.thetaphi:forbiddenapis:2.2:testCheck (default) on project checkstyle: Execution default of goal de.thetaphi:forbiddenapis:2.2:testCheck failed: 65535
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal de.thetaphi:forbiddenapis:2.2:testCheck failed: 65535
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 65535
	at de.thetaphi.forbiddenapis.asm.ClassReader.readLabel(Unknown Source)
	at de.thetaphi.forbiddenapis.asm.ClassReader.a(Unknown Source)
	at de.thetaphi.forbiddenapis.asm.ClassReader.a(Unknown Source)
	at de.thetaphi.forbiddenapis.asm.ClassReader.b(Unknown Source)
	at de.thetaphi.forbiddenapis.asm.ClassReader.accept(Unknown Source)
	at de.thetaphi.forbiddenapis.asm.ClassReader.accept(Unknown Source)
	at de.thetaphi.forbiddenapis.Checker.checkClass(Checker.java:602)
	at de.thetaphi.forbiddenapis.Checker.run(Checker.java:619)
	at de.thetaphi.forbiddenapis.maven.AbstractCheckMojo.execute(AbstractCheckMojo.java:444)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 

```

### CODE REVIEW

**Comment by romani** [comment]
Just open an issue against that project

**Comment by MEZk** [comment]
@romani 
Done. https://github.com/policeman-tools/forbidden-apis/issues/108

**Comment by MEZk** [comment]
@romani 
InputAnnotationLocation4.class causes the exception. I excluded it ```**/checks/annotation/InputAnnotationLocation4*``` and got 105 violations. Working on the fix.

**Comment by MEZk** [comment]
@romani 
All forbidden-apis violations were fixed. ```InputAnnotationLocation4``` was excluded from validation.

**Pull request merged**
