### PR TITLE
Improve Test Reliability

### PR DESCRIPTION
**Pull request by Vampire**
- make tests work more reliably on Windows

  If Git is used without modifying line endings, you have
  Linux line endings on Windows too. The tests assumed that
  on Windows the files have Windows line endings.
  With this commit, it works properly with both.

- run tests with English locale and UTF-8 encoding

  This improves reliability of tests, as for example on a German Windows system
  the tests break without this because of encoding of error messages.

- reset the test stream for each test

  Without the reset, the stream fills with "Audit done." messages
  and the real unexepcted message does not get print in the failure message.

### CODE REVIEW

**Comment by rnveach** [comment]
> make tests work more reliably on Windows

I am a Windows user and I have no issues with tests. I use Eclipse and maven to run tests. What exactly is your problem?

> If Git is used without modifying line endings, you have Linux line endings on Windows too. The tests assumed that on Windows the files have Windows line endings.

It is required to enable `core.autocrlf` for windows. See http://checkstyle.sourceforge.net/beginning_development.html#Before_development .

I personally am not ready to say we can drop this requirement as most windows platforms will default to save files with `\r\n` lines and we don't have a check to validate if all line endings in repo is `\n`. There was a discussion about this at https://github.com/checkstyle/checkstyle/issues/893 which also discussed some drawbacks from a check and it should be git's responsibility to maintain line endings and `autocrlf` does this.

> run tests with English locale and UTF-8 encoding

Why is this a windows issue and will this change impact our ability to swap the locale out for another one which we do in CI testing.
See https://github.com/checkstyle/checkstyle/blob/master/.ci/travis/travis.sh#L20-L58 .

> reset the test stream for each test

Same question as previous.

**Comment by rnveach** [comment]
> reset the test stream for each test
> Without the reset, the stream fills with "Audit done." messages
and the real unexpected message does not get print in the failure message.

For my local, we always get a brand new stream every test run, so 2 tests can't be using the other test's stream by mistake.
However, if `verify` is called twice in the same test like `CheckerTest.testCacheAndCheckWhichDoesNotImplementExternalResourceHolderInterface` then the stream is filled with the previous run's text and could be verifying the wrong results.

I agree with this change, but I think we should keep the `flush`. There is also 2 files named `AbstractModuleTestSupport` and both need to be changed.

**Comment by Vampire** [comment]
> > make tests work more reliably on Windows
> 
> I am a Windows user and I have no issues with tests. I use Eclipse and maven to run tests. What exactly is your problem?

The problem is what I described after that line.

> > If Git is used without modifying line endings, you have Linux line endings on Windows too. The tests assumed that on Windows the files have Windows line endings.
> 
> It is required to enable `core.autocrlf` for windows. See http://checkstyle.sourceforge.net/beginning_development.html#Before_development .
> 
> I personally am not ready to say we can drop this requirement as most windows platforms will default to save files with `\r\n` lines and we don't have a check or CI to validate if all line endings in repo is `\n`. There was a discussion about this at #893 which also discussed some drawbacks from a check and it should be git's responsibility to maintain line endings and `autocrlf` does this.

Well, I personally hate it when a VCS mangles files automagically.
I have globally set `autocrlf` to `input` just to remind me to change line ending to LF if I have it at CRLF accidentally on some file, but I don't like to have Git automatically change line endings on checkout, besides that it wastes space on my local disk.

How about requiring not to have `autocrlf` at `false` for CS instead? For the result in the repository this would mean the same whether it is set to `true` or `input`, which is line endings in the repository are LF. And for most users this should be the case.

With my changes the tests work properly on Windows, whether someone has linux line endings or windows line endings doesn't matter anymore. You could actually also add another build job that runs with `autocrlf` set to `input` or `false` on the Windows build machines to make sure it stays like that in the future.

> > run tests with English locale and UTF-8 encoding
> 
> Will this change impact our ability to swap the locale out for another one which we do in CI testing.
> See https://github.com/checkstyle/checkstyle/blob/master/.ci/travis/travis.sh#L20-L58 .

Ah, very good question, didn't have that on the radar.
You are right, the way I did it, the property was ignored and always en_US.UTF-8 used.
I removed it from the surefire configuration and instead added it as property. This way the commandline supplied property overwrites the property defined in the POM and so the tests run as expected.
If I now add `-DargLine='-Duser.language=de -Duser.country=DE -Xms1024m -Xmx2048m'` to the commanline test run with my latest changes, it again fails.

> > for example on a German Windows system the tests break without this because of encoding of error messages.
> 
> Why is our german CI passing and yours is failing? Can you provide an example of a failure?

Probably because you test on Linux where the default encoding is UTF-8 where the problem does not happen. On Windows with German locale and default encoding you get errors like these:

grafik

> > reset the test stream for each test
> > Without the reset, the stream fills with "Audit done." messages and the real unexepcted message does not get print in the failure message.
> 
> Same question as previous item. I will have to look into this some as I have not seen anything like this.

It is not too obvious.
The problem is, **if** one of the test that is not the first one fails, then the stream contains `Audit done.` lines of the previous successful tests.
I have seen this when I looked into the tests that failed on Windows with LF line endings and debugged at that place, seeing that this is most probably not like intended.
With the `reset()` the stream has the unexpected error message as first line and the `Audit done.` as second line, so the unexpected error message is shown in the failed assertion.
Without the `reset()` the failed assertion just shows `Audit done.` which is not the unexpected error message and does not really help solving the test failure.
You don't see the issue because the tests are green and if the tests would not be green, there is some output and it is not instantly obvious that it is the wrong output.

> For my local, we always get a brand new stream every test run, so 2 tests can't be using the other test's stream by mistake.
> However, if `verify` is called twice in the same test like `CheckerTest.testCacheAndCheckWhichDoesNotImplementExternalResourceHolderInterface` then the stream is filled with the previous run's text and could be verifying the wrong results.

I don't know anymore with which tests it happened, but I have seen it with at least three different ones which is why I did the `reset()` calls.

> I agree with this change, but I think we should keep the `flush`.

Whatfor if I may ask?
It is a `ByteArrayOutputStream`, so `flush()` is a no-op and as I do a `reset()` the stream is resetted anyway.

> There is also 2 files named `AbstractModuleTestSupport` and both need to be changed.

Ok, also adapted.

**Comment by rnveach** [comment]
@Vampire Like @romani has stated in another PR, lets break this discussion up as there are multiple things going on in 1 and we may not be able to agree on everything to merge in 1 big chunk.

> reset the test stream for each test

Make this another PR with a minor change. I feel this can go forward the fastest.

> make tests work more reliably on Windows
> run tests with English locale and UTF-8 encoding

Make these 2 separate issues.

**Comment by rnveach** [comment]
> > I agree with this change, but I think we should keep the flush.

> Whatfor if I may ask?

Just my preference, but it is a stream so you should always flush it. I understand the implementation for this class doesn't do anything, but it could do something in a future JRE or if we switch the stream type.
This is really minor and I am ok if it is ignored.

I will answer other questions in issues so it is not lost in this thread.

**Comment by romani** [comment]
@Vampire , please split fixes in separate PRs to ease verification.

**Comment by romani** [comment]
Discussion is too big to treat such commits as minors, please create separate issues on this and let's validate your cases. Commit messages should have references to such reasons/discussion.

**Comment by Vampire** [comment]
Split into three followups

**Pull request closed without merging**
