### PR TITLE
Issue #3332: Added void-elements

### PR DESCRIPTION
**Pull request by ps-sp**
#3332 : Added void elements `<keygen>`, `<source>`, `<track>`, `<wbr>`

### CODE REVIEW

**Comment by ps-sp** [comment]
@Vladlis Please have a look. Thanks.

**Comment by ps-sp** [comment]
[javadoc checks diff reprot](https://3332-voidelements-javadoc-checks.netlify.com/)

**Comment by ps-sp** [comment]
[antlr report](https://3332-voidelements-antlrreport.netlify.com/)

**Comment by romani** [comment]
@ps-sp , please rebase , there are conflicts.
@Vladlis , ok to merge ones ALL CIs pass.

**Comment by ps-sp** [comment]
@Vladis 
Appveyor is failing due to inability to install cygwin again and again. Please hava a look. Thank you,

**Comment by Vladlis** [comment]
As this failure can be ignored I am merging (https://github.com/checkstyle/checkstyle/pull/4751#issuecomment-324785749)

**Pull request merged**
