### PR TITLE
Issue #10267: Update inputs for UnnecessarySemicolonAfterOuterTypeDeclarationCheckTest

### LINKED ISSUE #10267: Update inputs for UnnecessarySemicolonAfterOuterTypeDeclarationCheckTest
Child of #10080

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #10267

### CODE REVIEW

**Comment by timurt** [comment]
fix conflicts

**Comment by shashwatj07** [comment]
> fix conflicts

done

**Comment by timurt** [comment]
fix conflicts

**Comment by shashwatj07** [comment]
> fix conflicts

done

**Comment by shashwatj07** [comment]
Github, rebase

**Pull request merged**
