### PR TITLE
Issue #5565: add REMOVE_SWITCH mutator to pitest

### PR DESCRIPTION
**Pull request by pbludov**
Issue #5565

This PR is expecting to fail.

### CODE REVIEW

**Comment by romani** [comment]
wercker  is due to commit during code-freeze and my inability to make release, please do rebase one more time to fix it, but it does not required as we are interested in Shippable only. 

I moved pre-release commits (that are damaging wercker) , release is postponed.

**Comment by romani** [comment]
from logs of shippable:
```
PROFILE="pitest-checkstyle-xpath" 
...
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.3.2:mutationCoverage (default-cli) on project checkstyle: Mutation score of 89 is below threshold of 100 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.pitest:pitest-maven:1.3.2:mutationCoverage (default-cli) on project checkstyle: Mutation score of 89 is below threshold of 100
```

We will not see diff in logs, as level of coverage is below 100 on big value, diff is printing when such check is passed by pitest but in report there are some uncovered/survived items.

**Comment by rnveach** [comment]
@pbludov Since we can't see reports, can you post a report from one of the failures so we can see what kind of validation this mutator is doing?

**Comment by pbludov** [comment]
@romani
Here we are: https://pbludov.github.io/pitest/index.html

Some of them just a false positives, like this one:
https://pbludov.github.io/pitest/pitest-checkstyle-utils/com.puppycrawl.tools.checkstyle.utils/CheckUtils.java.html#org.pitest.mutationtest.report.html.SourceFile@613c0aba_164
But most of them are for really missed cases.

**Comment by rnveach** [comment]
> Some of them just a false positives, like this one:

Ateast 1 mutation is correct here.
https://github.com/checkstyle/checkstyle/blob/58327e1dd9707b09f82ae2d4d4ce14c253247154/src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilsTest.java#L343
We don't have a test asserting the method provides a different result than `0` for `NUM_DOUBLE`. All examples in this test can't be `0` to show that the method works, as `0` is the same as the default case.

**Comment by romani** [comment]
https://pbludov.github.io/pitest/pitest-checks-annotation/com.puppycrawl.tools.checkstyle.checks.annotation/AnnotationUseStyleCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@7a6694b9_340

screenshot_pitest_coverage_switch_default

1. RemoveSwitch 0 mutation → KILLED
2. RemoveSwitch 1 mutation → KILLED
3. RemoveSwitch 2 mutation → KILLED
4. RemoveSwitch 3 mutation → SURVIVED

Yes, unfortunate conflict of interests, "default:"  is required by some Rule/Check, but we can not make a test on it, as there should be no other value enum. It just best practice for further extensions on enums to have default in switches.
Coverage is possible but will require bunch of reflection/powermock/..... . Does not make sense.

Too much "wontfix" cases ... . I am voting against introduction of mutation , at least for now. I hope in future pitest will have better suppression abilities from configuration to keep suppression on leash and easy to apply.
We have now home made list of suppression by bash post report processing - it is not very mature processing, we can not handle such survived items here.

**Comment by pbludov** [comment]
The redundant `default` case is a common practice. I think this is why the mutator is in the experimental tree for 4 years.

**Comment by rnveach** [comment]
@pbludov @romani Why don't we ask maintainers of pitest to make an option to ignore `default` if it is the only problem?

**Comment by romani** [comment]
@rnveach , I am not ready to state that this will help to start to use, but please feel free to open issue/discussion on this topic at pitest project.

**Pull request closed without merging**
