### PR TITLE
Issue #8023: Add input file for Java14 records 

### PR DESCRIPTION
**Pull request by nmancus1**
Issue #8023: Add records input

Examples taken from:
https://blogs.oracle.com/javamagazine/records-come-to-java
https://alidg.me/blog/2020/2/9/java14-records-in-depth
https://openjdk.java.net/jeps/359

compilation is checked by:
https://github.com/checkstyle/checkstyle/blob/15ba4ccd6adfa2486658d5b36588831c1a1006d3/.travis.yml#L289-L293

### CODE REVIEW

**Comment by romani** [comment]
@nmancus1 , please keep CI happy all the time - https://travis-ci.org/github/checkstyle/checkstyle/jobs/693436338#L636

**Comment by romani** [comment]
@nmancus1 , did you find any interesting examples in openjdk project ?
I stumbled a lot on records in openjdk14.

**Comment by nmancus1** [comment]
> please keep CI happy all the time

What should I do in this case?  Isn't this failing since we can't parse this file yet?

> did you find any interesting examples in openjdk project 

Yes, should I provide more examples?

**Comment by romani** [comment]
from travis:
```
[INFO]      [echo] Checkstyle started (checkstyle_resources_checks.xml): 01/06/2020 01:11:03 PM
[INFO] [checkstyle] Running Checkstyle  on 1853 files
[ERROR] [checkstyle] [ERROR] /home/travis/build/checkstyle/checkstyle/src/test/resources-noncompilable
```

Checkstyle should not try to parse such files at all, we do not support non-compilable files at all, please investigate our config do not filter out such files.
all is here - https://github.com/checkstyle/checkstyle/blob/master/config/ant-phase-verify.xml

> should I provide more examples?

if examples are different in some way - yes,
if no interesting cases - just make it clear in pr description that nothing special found.

**Comment by nmancus1** [comment]
>Checkstyle should not try to parse such files at all, we do not support non-compilable files at all

We are still checking them with config `checkstyle_resources_checks.xml`; `OuterTypeFilenameCheck` is causing the issue.  I have explicitly added InputJava14Records.java to the excludes list.

**Comment by esilkensen** [comment]
Looks good to me once CI is green!

**Comment by nmancus1** [comment]
I'm switching this to draft to be able to add some trickier cases that I've come across today.

**Comment by romani** [comment]
@pbludov , @esilkensen , please do not allow commit message to start from issue, if it does not fix issue. in release notes it will looks like we provided support for this issue, but do not, and we just did some preparation fix for this issue. in such case you can do `minor: .... (#8023)`

**Comment by pbludov** [comment]
My bad. I didn't even look at the commit description. I'll keep it in mind for the future.

**Pull request merged**
