### PR TITLE
Fix Header causing exception with default config, issue #1129.

### PR DESCRIPTION
**Pull request by MEZk**
After fix Header does not rise any violation with [default config](https://github.com/checkstyle/checkstyle/commit/6fbce5c80b62931ad2f532819f15791a36cdb6ba#diff-6e886340e5a2ff9bd26e48165c70663dL58). In accordance with [manual](http://checkstyle.sourceforge.net/config_header.html#RegexpHeader) default value for property ```header``` is ```null```. 

[Reports](http://mezk.github.io/index.html).

### CODE REVIEW

**Comment by romani** [comment]
1)
>         final DefaultConfiguration checkConfig =
            createCheckConfig(RegexpHeaderCheck.class);
        createChecker(checkConfig);

Please recheck that there are no violations in test. Please update Xdoc and Javadoc to explain that to user.


2)
>  config/checkstyle_checks.xml 

please configure it check header of our code. Each Check that we have should work against our code and do some validation.

**Comment by MEZk** [comment]
@romani 
1)
>Please recheck that there are no violations in test. Please update Xdoc and Javadoc to explain that to user.

Done. I've also used checkstyle-tester with default configuration for HeaderCheck & RegexpHeaderCheck:

````xml
<module name = "Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <module name="RegexpHeader"/>
    <module name="Header"/>
    <module name="TreeWalker">
    </module>
</module>
````
And there are no violations and exceptions. Projects which were tested: openjdk, guava, hibernate. See [reports](http://mezk.github.io).

2)
>please configure it check header of our code. Each Check that we have should work against our code and do some validation.

Done.
I've created [java_regexp.header](https://github.com/checkstyle/checkstyle/commit/193f4939fec70e312479cd84ed938a892b5a17c1#diff-4f3d5a57ee25a40a6eff3896bb1853e7R1) as a header file for RegexpHeader module and created new property in [ant-phase-verify.xml](https://github.com/checkstyle/checkstyle/commit/193f4939fec70e312479cd84ed938a892b5a17c1#diff-e70aa0384ec275f925183489857b630dR37) and [build.xml](https://github.com/checkstyle/checkstyle/commit/193f4939fec70e312479cd84ed938a892b5a17c1#diff-6edd9be85b7019cc3d36931c8d89a4d6R39)  to point ```java_regexp.header```. I've also excluded ```java_regexp.header``` from [validation](https://github.com/checkstyle/checkstyle/commit/193f4939fec70e312479cd84ed938a892b5a17c1#diff-600376dffeb79835ede4a0b285078036R738).

**Comment by romani** [comment]
> Foundation, Inc., \d\d Temple Place, Suite \d\d\d, Boston, MA  \d\d\d\d\d-\d\d\d\d  USA

please make header as strict as possible. 

> In default configuration the check does not rise any violations. Default values of properties are used.

remove second sentence. And stress that header will match any value, what about no header at all? I think it should raise an violation on that.

**Comment by MEZk** [comment]
@romani 
>what about no header at all? I think it should raise an violation on that.

In default configuration we do not specify ```header``` property:

````xml
 <module name="RegexpHeader"/>
````

This means that  ```header``` property is absent, isn't it? The Check raises violation when ```headerFile``` is missed or ```headerFile``` property equals to ```""```

Or, do you mean that we should check is there any header in input file at all when we use default configuration? For example, input file:

````java
package com.somedomainname;

public class A {
}
````
This file does not begin with header and the check should raise violation.

**Comment by romani** [comment]
If user activate a Check smth should happen to user understant that it works.

I think that by default Check should demand header with any content (default value of header property is ".*")

> This means that header property is absent, isn't it?

Yes, default value should be used.

> For example, input file:

Right, violation should be there.

**Comment by MEZk** [comment]
@romani 
rebased

**Comment by romani** [comment]
I agree with you on "no violation by default" as this Check is not Treewlaker child, so could be used for any extension and as result only user know what is a comment in that file, examples: "<!--" , "#", "--", ";", "//", "/*" ....

**Comment by romani** [comment]
merged as FF

**Pull request merged**
