### PR TITLE
Issue #4801: add suppressions on some of WeakerAccess can be private cases

### PR DESCRIPTION
**Pull request by Nimfadora**
Issue #4801

### CODE REVIEW

**Comment by Nimfadora** [comment]
@romani weaker access fix is described [here](https://github.com/checkstyle/checkstyle/issues/4681#issuecomment-314579793)
Maybe I misunderstood you, can you describe in more detail what do you expect me to do with this violation?

**Comment by romani** [comment]
my comment was:
=================================
>    Declaration access can be weaker inspection 164 warnings

Should be updated to following, all other need to be resolved except for AbstractXxxxxxx classes.
violations in AbstractJavadocCheck should be suppressed, as such methods will be in use ones we make javadoc parser/Checks officially public to use by community.
In Abstract classes we can easily do "can be private", all other should be sent by PR for case by case processing.
```
  <inspection_tool class="WeakerAccess" enabled="true" level="WARNING" enabled_by_default="true">
    <scope name="Tests" level="WARNING" enabled="false">
      <option name="SUGGEST_PACKAGE_LOCAL_FOR_MEMBERS" value="false" />
      <option name="SUGGEST_PACKAGE_LOCAL_FOR_TOP_CLASSES" value="false" />
      <option name="SUGGEST_PRIVATE_FOR_INNERS" value="false" />
      <disabledExtension id="junit" />
    </scope>
    <option name="SUGGEST_PACKAGE_LOCAL_FOR_MEMBERS" value="false" />
    <option name="SUGGEST_PACKAGE_LOCAL_FOR_TOP_CLASSES" value="false" />
    <option name="SUGGEST_PRIVATE_FOR_INNERS" value="false" />
    <disabledExtension id="junit" />
  </inspection_tool>
```
=================================

But I do not see update in intellij config in this PR.
It is partial fix ?

**Comment by Nimfadora** [comment]
@romani as it stated in pr name it is fix for abstract classes, the way that I interpret your words:
>In Abstract classes we can easily do "can be private"

**Comment by romani** [comment]
@Nimfadora ,

please make setting like this
image

and fix only "Can be private" cases.
All "Can be protected" please send as WIP PR to review one more time and most likely approve suppression in classes bu javadoc tag.

**Comment by Nimfadora** [comment]
@romani seems like pitest failed, but I cannot access wercker

**Comment by rnveach** [comment]
@Nimfadora wercker is not pitest, it is regression.
> Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.isUserDefinedArrangementOfThis(RequireThisCheck.java:511)

Please rebase on latest master as we have fixed this issue.

**Comment by Nimfadora** [comment]
@rnveach something wrong with travis:
```
* What went wrong:
Could not resolve all files for configuration ':sbe-tool:compileClasspath'.
> Could not find org.agrona:agrona:0.9.7-SNAPSHOT.
  Searched in the following locations:
      file:/home/travis/.m2/repository/org/agrona/agrona/0.9.7-SNAPSHOT/maven-metadata.xml
      file:/home/travis/.m2/repository/org/agrona/agrona/0.9.7-SNAPSHOT/agrona-0.9.7-SNAPSHOT.pom
      file:/home/travis/.m2/repository/org/agrona/agrona/0.9.7-SNAPSHOT/agrona-0.9.7-SNAPSHOT.jar
      https://repo1.maven.org/maven2/org/agrona/agrona/0.9.7-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/org/agrona/agrona/0.9.7-SNAPSHOT/agrona-0.9.7-SNAPSHOT.pom
      https://repo1.maven.org/maven2/org/agrona/agrona/0.9.7-SNAPSHOT/agrona-0.9.7-SNAPSHOT.jar
  Required by:
      project :sbe-tool
```

**Comment by Nimfadora** [comment]
@romani I have added suppessions to all "can be private" cases which break tests. All that pass normally I will send in the next PR.

**Comment by romani** [comment]
@Nimfadora , I do not understand this PR, suppression is not a fix.

>cases which break tests.

what tests ?

**Comment by Nimfadora** [comment]
@romani AutomaticBean#tryCopyProperty uses reflection to set Check field values during tests, so if I make setter private than AutomaticBean cannot set this property and throws exception. This way making setters private breaks tests.

**Comment by rnveach** [comment]
> if I make setter private than AutomaticBean cannot set this property and throws exception

@Nimfadora Because of this, all Message fields and Setter/Getter methods we have in our modules will need suppressions, right? This will be alot of suppressions.
Does it make sense to create a huge test, in a separate package from the module, who's purpose is to show IntelliJ that they need to be public by doing something like: `new ModuleCheck().setCustomField(null)`

**Comment by Nimfadora** [comment]
> Because of this, all Message fields and Setter/Getter methods we have in our modules will need suppressions, right?
@rnveach yes, it is true.

**Comment by romani** [comment]
closed in favor of PR #4924

**Pull request closed without merging**
