### PR TITLE
Issue #2160: Add information about static analysis tools to README.md

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
I planned to put smth like this to http://checkstyle.sourceforge.net/contributing.html#Quality_matters 
We should not overload our README, even with badges.
Are you ok with that ?

It would be better to have link to SAT, link its config, its suppression, amount of activated validation rules.
Instructions on how to run them before sending PR.
You will need this instructions each time somebody send PR without running SATs on local.

**Comment by mkordas** [comment]
Sure, but for me this would be another step. I'd like to see one sentence summary on main page with all SATs we use and then we can redirect to Quality Matters for more details.

**Comment by romani** [comment]
too much information and it will grow, you already missed 100% coverage. Amount of Tools will grow.

**Comment by romani** [comment]
all knowledge about SATs requerd only at stage of http://checkstyle.sourceforge.net/contributing.html
most our users do not contribute and just use
that is normal, I use a lot of opensource projects and I do not contribute to them
All I need from README of them is how to use project information , how to start use it
each time smb send PR , you need to have one link to send him where all details of contribution (validation, UT run, commit message, ....)
users even need to know how to run that on all OSs and how to run Idea inspection from terminal (by command line)
in other case they will PRs just to test code and not as signal that they are ready

**Pull request closed without merging**
