### PR TITLE
Fix bug at RightCurlyCheck: Curly brace '}' should be on line by itself not reported for method with annotation, #1014 

### PR DESCRIPTION
**Pull request by MEZk**
@romani 
Fixed issue #1014 and provided additional UTs.
How many (and what) projects should I use to generate report after my changes with checkstyle-tester?

### CODE REVIEW

**Comment by MEZk** [comment]
Travis fails the build due to the problem between GitGub and Travis:

```
Testing Checkstyle started
Requesting a tar: 'wget https://api.github.com/repos/checkstyle/checkstyle/tarball/master -O src/main/java/checkstyle-checkstyle.tar.gz'
--2015-06-28 21:36:50--  https://api.github.com/repos/checkstyle/checkstyle/tarball/master
Resolving api.github.com (api.github.com)... 192.30.252.139
Connecting to api.github.com (api.github.com)|192.30.252.139|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-06-28 21:36:50 ERROR 403: Forbidden.
The command "eval $CMD" exited with 8.
```
[full failure report] (https://travis-ci.org/checkstyle/checkstyle/jobs/68730164)

Other jobs successfully done.

**Comment by romani** [comment]
>How many (and what) projects should I use to generate report after my changes with checkstyle-tester?

The more the better :). Please squash commits.

**Comment by MEZk** [comment]
@romani 
I'll send reports soon.

**Comment by romani** [comment]
> and after fix it does.

right, because "}" has to be "alone" on a line as it was requested in config - http://checkstyle.sourceforge.net/property_types.html#rcurly.

**Comment by romani** [comment]
reports looks ok, and looks like https://github.com/checkstyle/checkstyle/issues/1019 is reasonable additional fix for that that, as that Check generate too much noice.

**Comment by romani** [comment]
> RightCurlyCheckSuperInput.java

please remove that input and Override any method from Object class.

**Comment by MEZk** [comment]
>please remove that input and Override any method from Object class.

My mistake, fixed.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
