### PR TITLE
Issue:#5832:extra sapce

### PR DESCRIPTION
**Pull request by 7h3-3mp7y-m4n**

### CODE REVIEW

**Comment by nrmancuso** [comment]
@7h3-3mp7y-m4n thanks for finding this typo, but we cannot make this change in the scope of #5832, this issue is closed. Please update commit message to be `doc: remove extra space`, and make sure that `mvn clean verify` is passing on your local before updating PR

**Comment by 7h3-3mp7y-m4n** [comment]
Thanks for the information @nrmancuso , But I'm facing an issue while using `mvn clean verify ` . Can you tell me how to resolve this 
Screenshot 2023-03-25 at 2 30 16 PM

**Comment by romani** [comment]
read https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=13681&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=808

**Comment by 7h3-3mp7y-m4n** [comment]
thanks @romani I'll work on it

**Comment by 7h3-3mp7y-m4n** [comment]
Issue has been resolved, please check .

**Comment by nrmancuso** [comment]
@7h3-3mp7y-m4n please make CI happy, all checks must pass to merge PR.

**Pull request closed without merging**
