### PR TITLE
Issue #2161: unify test input locations for javadoc package

### PR DESCRIPTION
**Pull request by rnveach**

### CODE REVIEW

**Comment by rnveach** [comment]
@romani
> src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc
 ParseTreeBuilder.java (565)
> 59: treeOneSimpleHtmlTag() Local variable name Rohae doesn't match regex '[a-z][A-Za-z\d]*' 

Is this another suppression needed?

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml#L72 this should be enough.

**Comment by rnveach** [comment]
yes but TC is throwing errors about it, is it just a bad build? I'm trying running it again.
The file changes package location in this commit, could that effect the suppressions somehow?

**Comment by romani** [comment]
please update path to ParseTreeBuilder at https://github.com/checkstyle/checkstyle/blob/master/config/intellij-idea-inspection-scope.xml#L2

**Comment by rnveach** [comment]
@romani look at the latest commit, I saw that and changed it but it didn't help TC

**Comment by romani** [comment]
hmm, very strange, try to close this PR , and open new PR

**Pull request closed without merging**
