### PR TITLE
dependency: bump pitest-maven from 1.9.3 to 1.9.4

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
`EXPERIMENTAL_RETURN_VALUES_MUTATOR` and `RETURN_VALS` has been removed at https://github.com/hcoles/pitest/commit/c9b046285332b650c82f9d5d72d37af8adcf4c59

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
@nick-mancuso @rnveach ping, we need this merged to upgrade pitest to `1.9.4`

**Comment by nick-mancuso** [comment]
@Vyom-Yadav we should update dependency in the same commit/ PR, please add pitest maven Verizon bump and we will close #12027 

Remember to change commit message accordingly.

**Review by nick-mancuso — APPROVED** [review]
That is one way to kill mutations that I had not considered :)

**Comment by nick-mancuso** [comment]
We can close https://github.com/checkstyle/checkstyle/pull/12027 in favor of this.

**Comment by Vyom-Yadav** [comment]
We can also close https://github.com/checkstyle/checkstyle/issues/12013 and https://github.com/checkstyle/checkstyle/issues/11719 as `1.9.4` addresses that too.

**Comment by romani** [comment]
TC is all red in all repos, lets skip it and proceed with merge.

**Review by rnveach — COMMENTED** [review]
Is github display wonky or am I seeing new pitest suppressions added? If so, I am just curious if we know why?

**Comment by Vyom-Yadav** [comment]
> Is github display wonky or am I seeing new pitest suppressions added? If so, I am just curious if we know why?

No new mutations are added, the unnecessary ones were removed, I confirmed it on local.

**Review by rnveach — CHANGES_REQUESTED** [review]
Code sorting issue fix in https://github.com/checkstyle/checkstyle/pull/12029

**Comment by romani** [comment]
@rnveach , are you sure in your comment? pR blocks itself ?

**Comment by Vyom-Yadav** [comment]
Sorting fix is in #12045

**Review by romani — APPROVED** [review]

**Review by rnveach — APPROVED** [review]

**Pull request merged**
