### PR TITLE
Issue #13345: MissingOverrideCheck

### PR DESCRIPTION
**Pull request by Guneetsinghtuli**
Part of #13345

### CODE REVIEW

**Comment by romani** [comment]
Before pushing to GitHub, ply make sure that `mvn clean verify ` pass on your local.

**Comment by romani** [comment]
Read CI failure: https://app.travis-ci.com/github/checkstyle/checkstyle/builds/265756287#L1515

```
Proper commit message should adhere to the following rules:
    1) Must match one of the following patterns:
        ^Issue #\d+: .*$
        ^Pull #\d+: .*$
        ^(minor|config|infra|doc|spelling|dependency|supplemental): .*$
    2) It contains only one line of text
    3) Must not end with a period, space, or tab
    4) Commit message should be less than or equal to 200 characters
```

**Comment by Guneetsinghtuli** [comment]
@romani I am facing an problem while trying to solve this on running `mvn clean verify` the test is failing, anyway you can help me with this

**THE OUTPUT**
```
[ERROR] Failures: 
[ERROR]   MissingOverrideCheckExamplesTest.testExample1:48->AbstractModuleTestSupport.verifyWithInlineConfigParser:239->AbstractModuleTestSupport.verify:312->AbstractModuleTestSupport.verify:350->AbstractModuleTestSupport.verify:372->AbstractModuleTestSupport.verify:402->AbstractModuleTestSupport.lambda$verify$1:405 Violations for /Users/guneetsingh/Development/Open Source/src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/Example1.java differ.
missing (2)   : 37:5: The Javadoc test3 tag is not valid at this location., 42:5: The Javadoc test4 tag is not valid at this location.
unexpected (2): 37:5: The Javadoc {@inheritDoc} tag is not valid at this location., 42:5: The Javadoc {@inheritDoc} tag is not valid at this location.
---
expected      : [32:5: Must include @java.lang.Override annotation when '@inheritDoc' Javadoc tag exists., 37:5: The Javadoc test3 tag is not valid at this location., 42:5: The Javadoc test4 tag is not valid at this location.]
but was       : [32:5: Must include @java.lang.Override annotation when '@inheritDoc' Javadoc tag exists., 37:5: The Javadoc {@inheritDoc} tag is not valid at this location., 42:5: The Javadoc {@inheritDoc} tag is not valid at this location.]
[INFO] 
```

**.txt file to java file**
```
class Test extends SuperClass {

    /** {@inheritDoc} */
    @Override
    public void test1() { // OK

    }

    /** {@inheritDoc} */
    public void test2() { // violation, 'Must include @java.lang.Override annotation when '@inheritDoc' Javadoc tag exists'

    }

    /** {@inheritDoc} */
    private void test3() { // violation, 'The Javadoc {@inheritDoc} tag is not valid at this location'

    }

    /** {@inheritDoc} */
    public static void test4() { // violation, 'The Javadoc {@inheritDoc} tag is not valid at this location'

    }
}
```
**The test**
```
public void testExample1() throws Exception {
        final String[] expected = {
                "32:5: " + getCheckMessage(MSG_KEY_ANNOTATION_MISSING_OVERRIDE, "test2"),
                "37:5: " + getCheckMessage(MSG_KEY_TAG_NOT_VALID_ON, "test3"),
                "42:5: " + getCheckMessage(MSG_KEY_TAG_NOT_VALID_ON, "test4"),
        };
        verifyWithInlineConfigParser(getPath("Example1.java"), expected);
    }
```

**Comment by romani** [comment]
Always keep single commit in branch and make sure that mvn clean verify  pass on your local.

**Comment by nrmancuso** [comment]
@Guneetsinghtuli please do not open and close PRs

**Comment by Guneetsinghtuli** [comment]
Will keep that in mind next time

**Pull request closed without merging**
