### PR TITLE
Issue #13677: migrate MatchXpathCheck to properties macros in xml.tem…

### PR DESCRIPTION
**Pull request by romani**
Issue #13677

### CODE REVIEW

**Comment by romani** [comment]
@stoyanK7 , please what is wrong in my steps to use macros

**Comment by stoyanK7** [comment]
@romani Just checked. `isSetterMethod` returns `false` for `setQuery`

**Comment by nrmancuso** [comment]
>Something you can do is to add "MatchXpathCheck.setQuery" to SUPERCLASS_SETTERS

Please do not abuse this collection, we need to fix the actual issue.

**Comment by stoyanK7** [comment]
> Please do not abuse this collection, we need to fix the actual issue.

Opening issue right now.

**Comment by stoyanK7** [comment]
PR with fix is at https://github.com/checkstyle/checkstyle/pull/13681

**Comment by romani** [comment]
@stoyanK7 , please take my changes to your PR

**Comment by stoyanK7** [comment]
Done. Added to my PR.

**Pull request closed without merging**
