### PR TITLE
Issue #14875: fix links to be relative for styleguides

### PR DESCRIPTION
**Pull request by romani**
Issue #14875

related to https://github.com/checkstyle/checkstyle/pull/15253

### CODE REVIEW

**Comment by romani** [comment]
GitHub, generate website

**Review by rnveach — APPROVED** [review]
Please show there are none left.

I think we should consider adding a RegExp for this.

**Review by nrmancuso — APPROVED** [review]

**Comment by romani** [comment]
this update does not fix issue, there are still more:
```
✔ ~/java/github/romani/checkstyle [i14875-relative-links L|⚑ 2] 
15:05 $ ag "https://checkstyle.org/styleguides"
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java
40: * <a href="https://checkstyle.org/styleguides/google-java-style-20220203/javaguide.html#s5.3-camel-case">

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java
38: * <a href="https://checkstyle.org/styleguides/google-java-style-20220203/javaguide.html#s4.8.6.1-block-comment-style">

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java
36: * href="https://checkstyle.org/styleguides/sun-code-conventions-19990420/CodeConventions.doc5.html#a2992">

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java
38: * <a href="https://checkstyle.org/styleguides/sun-code-conventions-19990420/CodeConventions.doc2.html#a1852">
43: * <a href="https://checkstyle.org/styleguides/sun-code-conventions-19990420/CodeConventions.doc2.html#a1852">

src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/AbbreviationAsWordInNameCheck.xml
10: &lt;a href="https://checkstyle.org/styleguides/google-java-style-20220203/javaguide.html#s5.3-camel-case"&gt;

src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/indentation/CommentsIndentationCheck.xml
11: &lt;a href="https://checkstyle.org/styleguides/google-java-style-20220203/javaguide.html#s4.8.6.1-block-comment-style"&gt;

src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/DeclarationOrderCheck.xml
10: &lt;a href="https://checkstyle.org/styleguides/sun-code-conventions-19990420/CodeConventions.doc2.html#a1852"&gt;
15: &lt;a href="https://checkstyle.org/styleguides/sun-code-conventions-19990420/CodeConventions.doc2.html#a1852"&gt;

src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MultipleVariableDeclarationsCheck.xml
13: href="https://checkstyle.org/styleguides/sun-code-conventions-19990420/CodeConventions.doc5.html#a2992"&gt;

```

**Comment by romani** [comment]
we still have full links in meta files and in javadoc.

javadoc content is distributed as zip in maven, so we should not use their relative links.
metadata is also content that can be copied to any place in plugin and be viewed from unpredictable location.

**Comment by romani** [comment]
links to styleguides are working fine in such reports.

**Pull request merged**
