### PR TITLE
Issue #13999: Kill mutaton for AbstractJavadocCheck

### PR DESCRIPTION
**Pull request by Rohanraj123**
Related #13999 

**Mutation 1:** 

https://github.com/checkstyle/checkstyle/blob/d14a4039d4ded7e5bd66fe1f30be3a310fc6c2c9/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L21-L28

Diff Report:
Diff regression config: Still to update

Report label: Issue#14545-Report

### CODE REVIEW

**Comment by nrmancuso** [comment]
@Rohanraj123 please be the first reviewer on your PR; leave comments on changes and explain why we need to handle two mutations in one PR.

**Comment by Rohanraj123** [comment]
> explain why we need to handle two mutations in one PR.

@nrmancuso Updated the initial comment.

**Comment by Rohanraj123** [comment]
Github, generate report

**Comment by Rohanraj123** [comment]
Github, generate report

**Review by rnveach — CHANGES_REQUESTED** [review]
> [Rohanraj123](https://github.com/Rohanraj123) marked this pull request as ready for review

We need regression report for this PR.

> Diff regression config : https://raw.githubusercontent.com/Rohanraj123/Rohanraj123.github.io/8743d5695486fb97a69d3ad38eb6dedd99bcaf5b/DiffReportIssue14545

@Rohanraj123 What did you specifically put in to your configuration and how do you feel it will show proper regression for this change?

> Explanation 
> since we are processing the nodes here only, processing the node again by giving IF condition is useless

I am sorry, but I do not following your explanation. Are you saying we call `shouldBeProcessed` on the exact same node 2+ times?

**Comment by Rohanraj123** [comment]
> What did you specifically put in to your configuration and how do you feel it will show proper regression for this change?

These are the checks I put in my_checks.xml file to generate the single regression report. 
```
AtclauseOrder
JavadocBlockTagLocation
JavadocMissingLeadingAsterisk
JavadocMissingWhitespaceAfterAsterisk
JavadocParagraph
JavadocTagContinuationIndentation
MissingDeprecated
NonEmptyAtclauseDescription
RequireEmptyLineBeforeBlockTagGroup
SingleLineJavadoc
SummaryJavadocCheck
```
These are the checks we need to generate the regression report for.
Please guide me if I am wrong.

**Comment by Rohanraj123** [comment]
> We need regression report for this PR.

I have updated the regression report link. Please check it once_

**Comment by Rohanraj123** [comment]
> I am sorry, but I do not following your explanation. Are you saying we call `shouldBeProcessed` on the exact same node 2+ times?

Okay let me explain my understanding  of this change : 
`
 DetailNode curNode = root;`
This line says that current node is root node. Since root node of tree can not be null we are going to enter the outer loop. 
i.e `while (curNode != null)`.

Now this loop will run until current node is not null. And we will update currentNode inside the loop to their child nodes. 

`boolean waitsForProcessing = shouldBeProcessed(curNode)`
 This line basically returns the boolean value whether current node should be processed or not on the basis of whether this node presents in JavadocTokens or not. 

Now we may have a true of false value of waitsForProcessing variable. 
If it be true. 
It will visit the JavadocToken of current node. 
because of this line : 
```
if (waitsForProcessing) { 
                visitJavadocToken(curNode);
            }
```

other wise now it will visit to its first child node . 
Now Inner loop will run until the current node and child node will be not null .

If waitsForProcessing will be true. hence it must have visited the javadocToken yet. so it will leave this time else if it be false then now `tovisit` will be the next sibling of that first child node. 

Now the main thing comes to the picture. 
If `tovisit == null`
that means if the next sibling is null we have to move back to our parent node.

Now the main part. 
why are we using this extra if condition here
```
if (curNode != null) {
                        waitsForProcessing = shouldBeProcessed(curNode);
                    }
```

If we are visiting the child nodes then it must be the case that `currNode  != null` then only we visited the first child node. 

Second part of the question : Why we need to remove the shouldBeProcessed method second time. 
since we are on that parent node now. because current node has moved to parent node using `getparent `method. 
Then why are we calling shouldBeProcessed method again on the parentNode from where we have came . And if current node be on root node. then there would be no parent node that means its null then also it will not check the condition. 

In the end we are just making the child node as current node so to perform the recursive condition. 

Now please letme know If my understaning is wrong somewhere. Would definately learn a lot from this.

**Comment by Rohanraj123** [comment]
Github, generate report

**Comment by rnveach** [comment]
@Rohanraj123 Try saying the phrase without putting any extra empty lines or spaces into the post.

**Comment by Rohanraj123** [comment]
Github,generate report

**Comment by Rohanraj123** [comment]
Yet not working !!

**Comment by Rohanraj123** [comment]
Github,generatereport

**Comment by rnveach** [comment]
The phrase is listed at https://github.com/checkstyle/checkstyle/blob/master/.github/workflows/diff-report.yml#L38
I believe it has to be solely that and nothing else. Please also delete your old tries that did not work.

**Comment by Rohanraj123** [comment]
GitHub, generate report

**Comment by rnveach** [comment]
Maybe the reaction is delayed, but it does look it ran.
https://github.com/checkstyle/checkstyle/actions/runs/8129061417/job/22215695200
It looks like it failed to parse the first post.

**Comment by rnveach** [comment]
Just glancing through the code, it looks like another spacing issue in your post.
https://github.com/checkstyle/checkstyle/blob/master/.ci/diff-report.sh#L94C54-L94C76
No space between the words and `:`.

**Comment by Rohanraj123** [comment]
> No space between the words and `:`.

Updated the first post and removed all the spaces in between !

**Comment by Rohanraj123** [comment]
GitHub, generate report

**Comment by rnveach** [comment]
You may be able to see the list of runs and their outputs at https://github.com/checkstyle/checkstyle/actions?query=workflow%3ADiff-Report if it is not privileged, to tell what is going on with it.

**Comment by nrmancuso** [comment]
It is likely that the explanation in the PR description is too detailed for this action to handle. It might be better to move explanation to a comment and have only the issue reference and report parameters in the description.

**Comment by Rohanraj123** [comment]
**Why two mutations:** 

While dealing with this mutation: 
https://github.com/checkstyle/checkstyle/blob/d14a4039d4ded7e5bd66fe1f30be3a310fc6c2c9/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L21-L28

This was the code I needed to remove: 
https://github.com/checkstyle/checkstyle/blob/d14a4039d4ded7e5bd66fe1f30be3a310fc6c2c9/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L387-L389

now if we needed to replace it with false as per the PITest. then to hardcode the the mutation we need to remove that if statement fully because it is not getting reached due to being false. 

While doing that there is one more mutation: 
https://github.com/checkstyle/checkstyle/blob/d14a4039d4ded7e5bd66fe1f30be3a310fc6c2c9/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L39-L45
referring to the code: 
https://github.com/checkstyle/checkstyle/blob/d14a4039d4ded7e5bd66fe1f30be3a310fc6c2c9/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L388

which was being removed while dealing with the first mutation. So it also targeted this second one. Thats why I removed two mutations in this PR only. Although If not allowed I can try to work on one mutation as well. 

**Explanation:** 
In this walk method we are just processing the nodes. Now when we look at the while condition i.e
```
 while(curNode != null)
boolean waitsForProcessing = shouldBeProcessed(curNode);
```
since we are processing the nodes here only, processing the node again by giving IF condition is useless
```
if (curNode != null)
waitsForProcessing = shouldBeProcessed(curNode);
```
because we are processing the `curNode `till the time current node does not gets empty or `null `using `while loop` only then using one more if condition to perform the same task doesnt make any sense

**Comment by Rohanraj123** [comment]
Github, generate report

**Comment by romani** [comment]
@Rohanraj123 , please continue it or let's close it and we will be back to it later from scratch.

**Comment by Rohanraj123** [comment]
> @Rohanraj123 , please continue it or let's close it and we will be back to it later from scratch.

I will continue my work on this issue.

**Comment by romani** [comment]
@Rohanraj123 , ping.

**Comment by romani** [comment]
@Rohanraj123 , we will close PR if no changes provided before 1 August.
You can always reopen PR when you have a time to continue.

**Comment by Rohanraj123** [comment]
Github, generate website

**Comment by Rohanraj123** [comment]
Replacing this PR with the new one. There's a lot of clutter in here!

**Comment by Rohanraj123** [comment]
Github, generate report

**Pull request closed without merging**
