### PR TITLE
Issue #7593: Add example for Transaltion's each existing config

### PR DESCRIPTION
**Pull request by Zaljumaei**
Issue https://github.com/checkstyle/checkstyle/issues/7593 : Add example 

TranslationCheck
 output:

CL1Translation

CL2Translation

### CODE REVIEW

**Comment by rnveach** [comment]
@Zaljumaei Please ensure you run `mvn verify` before pushing to ensure your changes will pass basic CI.
Please fix test failures and re-push. Keep the number of commits in the PR to 1 while you continue to make the CI green.
You don't need to close a PR to update it. You can keep it open and continue pushing changes.
https://github.com/checkstyle/checkstyle/wiki/PR-rules has some info on this.

**Comment by Zaljumaei** [comment]
@rnveach could you please check the examples if they are enough clear to understand
 at first, I become error because of the space, then I solved them, but after that, I become an error in another file in which I didn't change anything .

**Comment by Zaljumaei** [comment]
@romani  thank u for replying. There are a lot of errors like this which I don't know how to go with them 
[ERROR] testWhitespaceAroundAfterEmoji  Time elapsed: 0.027 s  <<< FAILURE!
com.google.common.truth.AssertionErrorWithFacts:
Actual and expected violations differ.
expected to match: 25:(?:\d+:)?\s.*'\+' is not preceded with whitespace.*
but was          : 25:22: Vor '+' fehlt ein Leerzeichen.
        at com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheckTest.testWhitespaceAroundAfterEmoji(WhitespaceAroundCheckTest.ja
va:559)
 
but in my changes there are no errors.

**Comment by romani** [comment]
Please run tests in English locale.

We are working on locale fix https://github.com/checkstyle/checkstyle/pull/12511

**Comment by romani** [comment]
@Zaljumaei , please finish PR.

**Comment by romani** [comment]
we lost connection to author

**Pull request closed without merging**
