### PR TITLE
Issue:#9394 update example of AST for TokenTypes.ARRAY_DECLARATOR

### PR DESCRIPTION
**Pull request by vivek286**
Issue:#9394

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Squash all your into one.

Also your commit message should follow template like
```
Issue #9394: <Your commit message>
```

**Comment by vivek286** [comment]
How to squash all in one commit?

**Comment by vivek286** [comment]
how to Squash all your into one?

**Comment by romani** [comment]
https://checkstyle.org/beginning_development.html#Starting_Development

**Comment by Abhishek-kumar09** [comment]
You can squash all your git commits and edit your commit message:
Take help from here: https://stackoverflow.com/questions/1657017/how-to-squash-all-git-commits-into-one
Also read: https://checkstyle.org/beginning_development.html#Starting_Development

**Pull request closed without merging**
