### PR TITLE
config: bump pitest to 1.9.9

### PR DESCRIPTION
**Pull request by romani**
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=11909&view=logs&j=1a6076f9-5826-5ba0-19ba-deaff2e35eea&t=5f46bc98-6f46-512e-6656-5fbfb1d03e4d&l=618

In maven central from oct 25

### CODE REVIEW

**Comment by rnveach** [comment]
https://github.com/hcoles/pitest/compare/1.9.8...1.9.9

I am expecting pitest message to change for switches from the issue I reported and fixed this release.

**Comment by romani** [comment]
Our output is too fancy, git diff output is more practical. Now this PR requires a bit of laptop time.
@nrmancuso , @Vyom-Yadav , FYI.

**Comment by rnveach** [comment]
This is why I was including pitest in https://github.com/checkstyle/checkstyle/issues/12243

**Comment by romani** [comment]
Better to avoid mega issues

**Comment by nrmancuso** [comment]
We can close this in favor of https://github.com/checkstyle/checkstyle/pull/12428

**Pull request closed without merging**
