### PR TITLE
Added tests in JavadocTokenTypesTest

### PR DESCRIPTION
**Pull request by ps-sp**
Issue #5186: Added a test to disallow changes in values of fields in 'JavadocTokenTypes'

### CODE REVIEW

**Comment by ps-sp** [comment]
Upon adding the following test:

```
    @Test
    public void testTotalNumberOfTokenTypes() {
        final int actualNumberOfTokenTypes =
                JavadocTokenTypes.class.getDeclaredFields().length - 1;
        assertEquals("Enusre that no new token(field) was added to"
                        + " `JavadocTokenTypes.java` without updating this test first",
                162, actualNumberOfTokenTypes);
    }
```

cobertura produces the following error:

```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JavadocTokenTypesTest.testTotalNumberOfTokenTypes:39 Enusre that no new token(field) was added to `JavadocTokenTypes.java` without updating this test first expected:<162> but was:<163>
[INFO] 
[ERROR] Tests run: 2532, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[ERROR] There are test failures.
```

**But no tests fail in `mvn clean test`**

**Comment by ps-sp** [comment]
The field `RULE_TYPES_OFFSET` has been made public. There are no more private fields in `JavadocTokenTypes.java`

Hence, [JavadocUtils.java#L91](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java#L91) do not have any hits. Cobertura fails to pick this up. Ideally it should detect
 this right ?

**Comment by ps-sp** [comment]
While running `mvn org.apache.maven.plugins:maven-pmd-plugin:3.8:check` on **master** a processing error is encountered:
 
```
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building checkstyle 8.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-pmd-plugin:3.8:check (default-cli) > :pmd @ checkstyle >>>
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:pmd (pmd) @ checkstyle ---
[WARNING] There are 1 PMD processing errors:
[WARNING] /home/ps/workspace/checkstyle/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/GeneratedJavadocTokenTypesTest.java: Error while processing /home/ps/workspace/checkstyle/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/GeneratedJavadocTokenTypesTest.java
[INFO] 
[INFO] <<< maven-pmd-plugin:3.8:check (default-cli) < :pmd @ checkstyle <<<
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:check (default-cli) @ checkstyle ---
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.681 s
[INFO] Finished at: 2017-10-18T23:54:33+05:30
[INFO] Final Memory: 59M/833M
[INFO] ------------------------------------------------------------------------
```

This happens because of erraneous modifications to `config/pmd-test.xml` in #5193 _(Sorry)_. It has been fixed in this commit. A separate commit is not needed for that right ?

**Comment by romani** [comment]
RULE_TYPES_OFFSET had to be private, please use reflection is you need that value

**Comment by ps-sp** [comment]
@romani 

>RULE_TYPES_OFFSET have to be private, please use reflection is you need that value

Done.

**Comment by romani** [comment]
@ps-sp please follow CIs complains
```1. ERROR in /home/travis/build/checkstyle/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypesTest.java (at line 38)
	public void testTokenValues() throws IllegalAccessException {
	^^^^^^^^^^^^^^^^^^^^^^
The declared exception IllegalAccessException is not actually thrown by the method testTokenValues() from type JavadocTokenTypesTest
```

**Pull request merged**
