### PR TITLE
Issue #13097: Split modifiers xdocs into separate pages

### PR DESCRIPTION
**Pull request by stoyanK7**
Part of #13097

### CODE REVIEW

**Comment by stoyanK7** [comment]
Github, generate site

**Review by romani — APPROVED** [review]
Ok to merge

**Review by nrmancuso — APPROVED** [review]

**Comment by nrmancuso** [comment]
@stoyanK7 please resolve conflicts

**Comment by stoyanK7** [comment]
@nrmancuso Done.

**Comment by nrmancuso** [comment]
Failure in CI:
`##[error]We stopped hearing from agent Azure Pipelines 3. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=84661`

Not related to changes here.

**Pull request merged**
