### PR TITLE
Issue #8151: Updated XpathRegressionOneTopLevelClassTest to have atle…

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
Resolves  `XpathRegressionOneTopLevelClassTest` : #8151

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
GitHub, rebase

**Comment by romani** [comment]
@Rahulkhinchi03, please rebase manually, looks like action is not working

**Review by romani — APPROVED** [review]
Ok to merge as CI pass

**Comment by Rahulkhinchi03** [comment]
@romani I have to create a minor commit too, right?

`minor:: Issue Referencing` and change:



-->

Until https://github.com/checkstyle/checkstyle/issues/`11549`

Also, Id should be `ReportASTInViolation`

**Comment by romani** [comment]
Yes

**Review by romani — APPROVED** [review]

**Pull request merged**
