### PR TITLE
Issue #3573: resovle design problem of FileContentsHolder

### PR DESCRIPTION
**Pull request by timurt**
https://github.com/checkstyle/checkstyle/issues/3573

### CODE REVIEW

**Comment by MEZk** [comment]
@timurt 
Please, rebase and resolve conflicts.

@romani 
I'm ok with the changes.

**Comment by romani** [comment]
I relaunched wercker, @timurt please review if it fail again

**Comment by romani** [comment]
@timurt , please update patch, there is wercker problem.

**Comment by MEZk** [comment]
@timurt 
You did not provide patch for https://github.com/real-logic/simple-binary-encoding.git.
See https://github.com/MEZk/checkstyle/blob/66b2c68ca34d398cbab96ca2d7265455931668c5/.ci/travis/travis.sh#L66-L66

**Comment by timurt** [comment]
@MEZk 
But `agrona` has no `FileContentsHolder`, `SuppressionCommentFilter` and `SuppressWithNearbyCommentFilter` inside config file.
Error says 

> Could not find org.agrona:agrona:0.9.7-SNAPSHOT

I tried to execute commands locally and I got the same error. Then I compiled https://github.com/real-logic/agrona and placed jars inside local maven repo folder. After this I had no errors.

I searched inside maven central for `org.agrona:agrona:0.9.7-SNAPSHOT`. But the latest version is [0.9.6](https://mvnrepository.com/artifact/org.agrona/Agrona) it means project was built and should be placed inside `/home/travis/.m2/repository/org/agrona/agrona/0.9.7-SNAPSHOT`, am I wrong?

**Comment by rnveach** [comment]
@timurt Please ignore simple-binary-encoding error. It is in master.

**Comment by rnveach** [comment]
simple-binary-encoding error is in master too.

**Pull request merged**
