### PR TITLE
Issue #6191: add config file for crowdin integration

### PR DESCRIPTION
**Pull request by strkkk**
Issue #6191 

Added config for crowdin integration.
It takes as original all messages.properties files, output will be added to same location with country code suffix, as it is now.

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge

**Review by rnveach — COMMENTED** [review]
So what is the purpose of this YML? I am not seeing any CI being run for crowdin?

**Comment by strkkk** [comment]
@rnveach this is necessary step to enable integration with crowdin. It wont appear in ci list, it is used for localization.
Users will have ability to correct translations in crowdin ui and checkstyle repo will receive PR with corrections.

The next step is enable integration in crowin website

**Comment by rnveach** [comment]
We can only complete this step after this is merged? We can't enable now and see it's results in this PR?

**Review by rnveach — APPROVED** [review]

**Pull request merged**
