### PR TITLE
Issue #2161: unify test input file names

### PR DESCRIPTION
**Pull request by rnveach**
pass 1 of file renames.

Test resource file names should start with "Input". If I renamed a file, I also remove "Check" and "Test" from the end of its name to prevent confusion with the actual Check and Test files. Pass 2 will be more aggressive with this.
I did not rename "com.puppycrawl.tools.checkstyle.checks.design.InetSocketAddress" as a test requires it to have the same class name as "java.net.InetSocketAddress".

Fixed package name identified and reported in Issue #2406, which is line 216 of VisibilityModifierCheckTest.

### CODE REVIEW

**Comment by romani** [comment]
As we keep input files in resources, "Input" prefix does not make any sense now and waste of space. Do you think it is better to put "Input" to the end to let user find required file ?

src/....../checks/annotation
AnnotationUseStyleCheck.java
MissingDeprecatedCheck.java
....

test/src/....../checks/annotation
AnnotationUseStyleCheckTest.java
MissingDeprecatedCheckTest.java
....

test/resources/....../checks/annotation
AnnotationUseStyleInput.java
AnnotationUseStyleCompicatedInput.java
MissingDeprecatedInput.java
MissingDeprecated2Input.java
.......

**Comment by rnveach** [comment]
Prefix/suffix, doesn't really matter to me. I feel we should keep one or the other to make it stand out like "Test" and "Check".
The majority of our files are already prefixed. Every input file, and test, will have to change to make it a suffix if we decide to go that way.

**Comment by romani** [comment]
ok, thanks for sharing your thoughts , we go with Input as prefix for now.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
