### PR TITLE
Issue #4581: Reorganize token methods in GenericWhitespaceCheck

### PR DESCRIPTION
**Pull request by subkrish**
Issue #4581 

This PR reorganizes the token methods in `GenericWhitespaceCheck`. After this PR is approved, similar changes will be made for other checks as well.

### CODE REVIEW

**Comment by subkrish** [comment]
@rnveach @romani AppVeyor seems to be failing due to some internal error.
```
[ERROR] Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.0.1:validate (default) on project checkstyle: Failed to load schema with public ID null, system ID src/main/resources/com/puppycrawl/tools/checkstyle/suppressions_1_0.dtd: The markup in the document preceding the root element must be well-formed. -> [Help 1]
```

I pushed twice but it didn't make any difference.

**Comment by rnveach** [comment]
The DTD issue is in master, so you can ignore it for now.

**Comment by romani** [comment]
I relaunched appveyor. In master appveyor is green now. 
If still a problem please rebase on latest master code.

**Comment by subkrish** [comment]
@romani @rnveach Since this looks to be good, similar changes must be made in all other files as well, right?

**Comment by rnveach** [comment]
@subkrish Yes, we want changes to all checks.

**Pull request merged**
