### PR TITLE
Issue #11134: Delete rebase.yml

### LINKED ISSUE #11134: Github CI does not run upon `Github, rebase` action
After PRs are rebased with `Github, rebase`, all other CI runs except for Github CI.

Example from https://github.com/checkstyle/checkstyle/pull/10999:
image

Another example, from https://github.com/checkstyle/checkstyle/pull/11112:

image

<details>
 <summary>Click to see tasks that ran in each PR</summary>

```
@cirrus-ci
Cirrus - JDK17 Successful in 20m — Task Summary
Details
@romani
IDEA Inspections Pull Request (Checkstyle) — TeamCity build finished
Details
@travis-ci
Travis CI - Pull Request Successful in 17m — Build Passed
Details
@azure-pipelines
checkstyle.checkstyle Successful in 13m — Build #20211228.10 succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK11 verify) Successful in 13m — Job MacOS JDK11 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK13 verify) Successful in 11m — Job MacOS JDK13 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK14 verify) Successful in 10m — Job MacOS JDK14 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK8 verify) Successful in 9m — Job MacOS JDK8 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job OpenJDK11 verify) Successful in 6m — Job OpenJDK11 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job markdownlint) Successful in 19s — Job markdownlint succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job pr-age) Successful in 12s — Job pr-age succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job spelling) Successful in 23s — Job spelling succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test) Successful in 2m — Job test succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-de) Successful in 3m — Job test-de succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-es) Successful in 3m — Job test-es succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-fi) Successful in 2m — Job test-fi succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-fr) Successful in 3m — Job test-fr succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-ja) Successful in 2m — Job test-ja succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-pt) Successful in 3m — Job test-pt succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-tr) Successful in 3m — Job test-tr succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-zh) Successful in 2m — Job test-zh succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job versions) Successful in 22s — Job versions succeeded
Details

ci/circleci: no-error-xwiki — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-cassandra-storm-tapestry-javadoc — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-hadoop-apache-groovy-scouter-javadoc — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-lucene-and-others-javadoc — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-only-javadoc — Your tests passed on CircleCI!
Details

ci/semaphoreci/pr: Checkstyle CI pipeline on Semaphore — The build passed on Semaphore 2.0.
Details

continuous-integration/appveyor/pr — AppVeyor build succeeded
Details

continuous-integration/drone/pr — Build is passing
Details

security/snyk (checkstyle) — No manifest changes detected in 1 project
Details

wercker/build — Wercker pipeline passed

```
</details>

In each, a total of 32 checks ran.

---------------------------
Expected behavior of CI:

Example:
image

Note there is a total of 62 checks normally.

<details>
 <summary>Click to see tasks that ran in PR with no rebase action</summary>

```
@github-actions
Check PR Description / Analyze (pull_request) Successful in 6s
Details
@github-actions
CodeQL / Analyze (java) (pull_request) Successful in 4m
Details
@github-actions
Pitest / pitest-annotation (pull_request) Successful in 2m
Details
@github-actions
no-exception testing / no-exception-openjdk16 (pull_request) Successful in 62m
Details
@github-actions
Pitest / pitest-ant (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-api (pull_request) Successful in 3m
Details
@github-actions
Pitest / pitest-blocks (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-coding (pull_request) Successful in 7m
Details
@github-actions
Pitest / pitest-common (pull_request) Successful in 3m
Details
@github-actions
Pitest / pitest-common-2 (pull_request) Successful in 3m
Details
@github-actions
Pitest / pitest-design (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-filters (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-header (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-imports (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-indentation (pull_request) Successful in 8m
Details
@github-actions
Pitest / pitest-javadoc (pull_request) Successful in 8m
Details
@github-actions
Pitest / pitest-main (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-metrics (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-misc (pull_request) Successful in 4m
Details
@github-actions
Pitest / pitest-modifier (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-naming (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-packagenamesloader (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-regexp (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-sizes (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-tree-walker (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-utils (pull_request) Successful in 4m
Details
@github-actions
Pitest / pitest-whitespace (pull_request) Successful in 3m
Details
@github-actions
Pitest / pitest-xpath (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-java-ast-visitor (pull_request) Successful in 4m
Details
@cirrus-ci
Cirrus - JDK17 Successful in 22m — Task Summary
Details
@github-code-scanning
Code scanning results / CodeQL Successful in 2s — No new or fixed alerts
Details
@romani
IDEA Inspections Pull Request (Checkstyle) — TeamCity build finished
Details
@travis-ci
Travis CI - Pull Request Successful in 27m — Build Passed
Details
@azure-pipelines
checkstyle.checkstyle Successful in 10m — Build #20211222.17 succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK11 verify) Successful in 8m — Job MacOS JDK11 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK13 verify) Successful in 7m — Job MacOS JDK13 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK14 verify) Successful in 9m — Job MacOS JDK14 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK8 verify) Successful in 6m — Job MacOS JDK8 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job OpenJDK11 verify) Successful in 5m — Job OpenJDK11 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job markdownlint) Successful in 21s — Job markdownlint succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job pr-age) Successful in 11s — Job pr-age succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job spelling) Successful in 26s — Job spelling succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test) Successful in 2m — Job test succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-de) Successful in 3m — Job test-de succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-es) Successful in 3m — Job test-es succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-fi) Successful in 3m — Job test-fi succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-fr) Successful in 3m — Job test-fr succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-ja) Successful in 3m — Job test-ja succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-pt) Successful in 3m — Job test-pt succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-tr) Successful in 3m — Job test-tr succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-zh) Successful in 3m — Job test-zh succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job versions) Successful in 21s — Job versions succeeded
Details

ci/circleci: no-error-xwiki — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-cassandra-storm-tapestry-javadoc — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-hadoop-apache-groovy-scouter-javadoc — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-lucene-and-others-javadoc — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-only-javadoc — Your tests passed on CircleCI!
Details

ci/semaphoreci/pr: Checkstyle CI pipeline on Semaphore — The build passed on Semaphore 2.0.
Details

continuous-integration/appveyor/pr — AppVeyor build succeeded
Details

continuous-integration/drone/pr — Build is passing
Details

security/snyk (checkstyle) — No manifest changes detected in 1 project
Details

wercker/build — Wercker pipeline passed
Details

```
</details>

### PR DESCRIPTION
**Pull request by stoyanK7**
Resolves #11134 as requested in https://github.com/checkstyle/checkstyle/issues/11134#issuecomment-1493417403
> Please remove rebase action from our repo, as a fix for this issue.

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge.
This PR need review from all maintainers to become familiar how to do this now

**Comment by stoyanK7** [comment]
Pasting the link here as well.

https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/

**Review by nrmancuso — APPROVED** [review]

**Review by rnveach — APPROVED** [review]

**Comment by rnveach** [comment]
@romani Can we disable the merge commit?

image

**Comment by romani** [comment]
I don't see option for this in settings, there is only one checkbook, to enable this feature.

**Pull request merged**
