### PR TITLE
RedundantModifier checks if enum constructor has redundant private

### PR DESCRIPTION
**Pull request by liscju**
modifier, fixes part of #1242

### CODE REVIEW

**Comment by romani** [comment]
please analyse failure on "CS-SI/Orekit" project and share reports (checkstyle-tester project, see other PRs for example) for this project before and after fix to let me validate change too.

**Comment by liscju** [comment]
Analysis on CS-SI/Orekit is on http://liscju.github.io/site/checkstyle.html, i check all and additional warnings with CS-SI/Orekit is because of redundant private modifier of constructor in enum. There are few older with redundant public modifier in interface. I dont know why it includes guava in check, i comment it out in projects-to-test-on.properties in contribution/checkstyle-tester

**Comment by mkordas** [comment]
@liscju - checkstyle-tester do not delete sources when you comment them out - so you need to delete them manually from `src` directory. 
Should we raise pull request to Orekit with fixes to these violations? Otherwise we'll have failing master...

**Comment by romani** [comment]
@liscju , please open issue to project CS-SI/Orekit with request to update enums and remove all redundant modifiers.

I did fork https://github.com/checkstyle/Orekit, so please do PR with changes to our fork first (I will merge it immediately), and then make link that commit in CS-SI/Orekit issue. Travis will become green and I will merge this PR.

**Comment by liscju** [comment]
1) Send PR to https://github.com/checkstyle/Orekit with changes
2) In https://github.com/CS-SI/Orekit they disabled making issues because they have their own tracking system - i tried to subscribe to it but one has to wait for administration approval for it. I tried to subscribe to their mailing-list but after few hours waiting for confirmation letter on mail i give it up. So i opened PR https://github.com/CS-SI/Orekit/pull/1

**Comment by romani** [comment]
I merged yor changes to testing project, relaunched  travis but there still 10 problems, please recheck

**Comment by liscju** [comment]
In all of the those 10 places where 'RedundantModifier: Redudundant private' in travis failed build was thrown, private modifier was removed by PR, to check this see links below. There was (probably) problem with caching , you can see that in failed build https://travis-ci.org/checkstyle/checkstyle/jobs/72033966 variable CMD1 is still cloning from original project , not fork i PR to.

https://github.com/checkstyle/Orekit/blob/master/src/main/java/org/orekit/data/PolynomialParser.java#L76

https://github.com/checkstyle/Orekit/blob/master/src/main/java/org/orekit/errors/OrekitMessages.java#L191

https://github.com/checkstyle/Orekit/blob/master/src/main/java/org/orekit/files/ccsds/CCSDSFrame.java#L213

https://github.com/checkstyle/Orekit/blob/master/src/main/java/org/orekit/frames/BulletinAFilesLoader.java#L317

https://github.com/checkstyle/Orekit/blob/master/src/main/java/org/orekit/frames/HelmertTransformation.java#L156

https://github.com/checkstyle/Orekit/blob/master/src/main/java/org/orekit/frames/Predefined.java#L263

https://github.com/checkstyle/Orekit/blob/master/src/main/java/org/orekit/time/Month.java#L108

https://github.com/checkstyle/Orekit/blob/master/src/main/java/org/orekit/time/UTCTAIBulletinAFilesLoader.java#L315

https://github.com/checkstyle/Orekit/blob/master/src/main/java/org/orekit/utils/AngularDerivativesFilter.java#L47

https://github.com/checkstyle/Orekit/blob/master/src/main/java/org/orekit/utils/CartesianDerivativesFilter.java#L47

**Comment by romani** [comment]
>  variable CMD1 is still cloning from original project , not fork i PR to.

yes, travis is know base on what commit it do build and always redo it for the same commit.
Please make new PR do rebase from master to create new commit SHA1, that will create new Travis build base on news hashes.

**Comment by liscju** [comment]
New PR done in #1463

**Pull request closed without merging**
