### PR TITLE
Issue #9221: Record definition grammar elements out of order

### PR DESCRIPTION
**Pull request by nmancus1**
Issue #9221: Record definition elements "record component list" and "implements clause" out of order in AST.

Check behavior regression reports:
https://nmancus1.github.io/diff_reports_9122/diff_config1/index.html
https://nmancus1.github.io/diff_reports_9122/diff_config2/index.html
https://nmancus1.github.io/diff_reports_9122/diff_config3/index.html
https://nmancus1.github.io/diff_reports_9122/diff_config4/index.html
https://nmancus1.github.io/diff_reports_9122/diff_config5/index.html
https://nmancus1.github.io/diff_reports_9122/diff_checks-only-javadoc-error/index.html
https://nmancus1.github.io/diff_reports_9122/diff_checks-sevntu-error/index.html

Antlr regression reports:
https://nmancus1.github.io/diff_reports_9122/antlr_diff_checkstyle/index.html
https://nmancus1.github.io/diff_reports_9122/antlr_diff_guava/index.html

### CODE REVIEW

**Review by romani — APPROVED** [review]
@pbludov ,I do not remember that we have that much false positives in diff report.
I this reports I see a lot of equal violations that are marked as diff

**Comment by pbludov** [comment]
> @pbludov ,I do not remember that we have that much false positives in diff report.

This is well known problem. Both `ImportOrder` and `CustomImportOrder` checks report "Extra separation" violation.
But only first message will be logged. Which one will be first depends on the phase of the moon. This behaviuor can be changed [here](https://github.com/checkstyle/checkstyle/blob/1e3fb3fae940bf7ea340592f7f0cda3af1b320e3/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L55) by replacing `HashMap` with any ordered map. But there may be some nuances related to threading in the future. Another way is to report "Extra separation" violation twice.

**Review by pbludov — APPROVED** [review]

**Review by strkkk — APPROVED** [review]

**Comment by nmancus1** [comment]
Github, rebase

**Comment by rnveach** [comment]
> here by replacing HashMap with any ordered map.

I think you mean the `Set` has to be replaced with a `TreeSet`. The key of the map is on the token. The order of the tokens is defined by our antlr tree and changing that map won't effect the other of the tokens. The difference issue is most likely connected to order the checks are executed, which is what the value of the `HashMap` is, the set of checks.

**Comment by rnveach** [comment]
@romani On a separate note for that `HashMap`, why is the key the token **String** and not the token **Integer** ? I would assume the integer would be faster since its a single value of not a concatenation of multiple values.

**Review by rnveach — APPROVED** [review]
@nmancus1 Antlr tree differences show tokens are out of order compared with the source and this fixes resolves this.

Has there been any additional looks to see if any other new grammar added for records shows that may need to be fixed too?

**Comment by rnveach** [comment]
I am going to assume it is safe to merge even though CI is complaining.

**Comment by romani** [comment]
> Both ImportOrder and CustomImportOrder checks report "Extra separation" violation.

we need to remove such Checks from regression, to make report easy to review. Noise in reports always hide problems.

**Comment by nmancus1** [comment]
> we need to remove such Checks from regression, to make report easy to review. Noise in reports always hide problems.

Would it be a good idea to remove `LITERAL_*` tokens from WhitespaceAround?  Removing ImportOrder checks from a completely unrelated change seems ok, But I would not feel good about removing Whitespace checks.

**Comment by romani** [comment]
> Would it be a good idea to remove LITERAL_* tokens from WhitespaceAround?

I do not remember this problem, please remind me.

**Comment by nmancus1** [comment]
> I do not remember this problem, please remind me.

Example: https://nmancus1.github.io/diff_reports_9122/diff_config5/infinispan/index.html

**Comment by rnveach** [comment]
@romani 
> we need to remove such Checks from regression

I recommend we just change the underlying code to not cause this, regardless if this will be re-usable in threads or not until we implement threading.

**Comment by rnveach** [comment]
> On a separate note for that HashMap, why is the key the token String and not the token Integer ?

I see why now. User passes in specific tokens as a text through configuration. We have to support that plus required/default tokens so we just went with `String`. There is no conversion of user pass in tokens to integer, so we would have to build that out if we were to switch the map's key.

**Comment by romani** [comment]
> I recommend we just change the underlying code to not cause this, 

@rnveach , We can create issue on this, but this should not block/damage regression testing that we do now.
https://github.com/checkstyle/checkstyle/issues/9251

-----

@nmancus1 , lets discuss it at https://github.com/checkstyle/checkstyle/issues/9252
I would need your help to understand why this happens.

**Pull request merged**
