### PR TITLE
Custom Import Order Check, rewrote compare method, issue #234

### PR DESCRIPTION
**Pull request by alexkravin**
Rewrote method <b>compare</b>, now it has single exit point, contains 3 times less code and it's readable.

### CODE REVIEW

**Comment by romani** [comment]
> currentImport

Please rename all arguments, as in static and stateliss method should not be current and previous, look at compare methods in jdk for good names.

**Comment by alexkravin** [comment]
what about current approach?

```java
private static int compare(String importStatement, String precededImportStatement)
    {
        int result = 0;
        final String[] importTokens = importStatement.split("\\.");
        final String[] precededImportTokens = precededImportStatement.split("\\.");
        for (int i = 0; i < importTokens.length; i++) {
            if (i == precededImportTokens.length) {
                break;
            }
            final String importToken = importTokens[i];
            final String precededImportToken = precededImportTokens[i];
            result = importToken.compareToIgnoreCase(precededImportToken);
            if (result != 0) {
                break;
            }
        }
        return result;
    }
```

**Comment by alexkravin** [comment]
p.s.

this method is fully-covered by UTs, I think coverage decreased because previous version of this method was fully-covered too, but it was 3 times longer (in code lines).

**Comment by romani** [comment]
Move common part of arguments names to method name, and see how arg named http://docs.oracle.com/javase/7/docs/api/java/util/Comparator.html

**Comment by alexkravin** [comment]
refactored, also removed method <b>countDomains</b> which was used only in previous version of method <b>compare</b>

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
