### PR TITLE
Issue #6207: add class data abstraction coupling xpath regression tests

### PR DESCRIPTION
**Pull request by chris-carneiro**
Part of Issue #6207

### CODE REVIEW

**Review by romani — CHANGES_REQUESTED** [review]
Thanks a lot.
We usually ask to have 3 test methods.
Please add test for interface https://checkstyle.org/checks/metrics/classdataabstractioncoupling.html#Description
And change second test to violate Enum.

It will make xpath expressions to be different.

**Comment by chris-carneiro** [comment]
> Thanks a lot. We usually ask to have 3 test methods. Please add test for interface https://checkstyle.org/checks/metrics/classdataabstractioncoupling.html#Description And change second test to violate Enum.
> 
> It will make xpath expressions to be different.

Oups I misunderstood that part, sorry about that, hope it's okay now

**Review by romani — APPROVED** [review]
ok to merge if CI pass.

thanks a lot!!!!

**Comment by romani** [comment]
@chris-carneiro , do you need any help with next issue ? do not hesitate to ask any questions.

**Comment by chris-carneiro** [comment]
> @chris-carneiro , do you need any help with next issue ? do not hesitate to ask any questions.

@romani tight schedule, will contribute again when I have more time!

**Pull request merged**
