### PR TITLE
Issue checkstyle #11163: Enforced file size on inputs on InputComment…

### LINKED ISSUE #11163: Enforce file size on Java inputs
From https://github.com/checkstyle/checkstyle/pull/11156#pullrequestreview-845293639

We need to get statistics on how long our Input files and get median value and enforce file size to not above this value.

As we usually do:
Enforce rules with long list of suppression
All suppressions can be resolved in separate PRs

Rationale: big input files a hard to review, hard to debug.

### PR DESCRIPTION
**Pull request by mahfouz72**
issue #11163:
force file size on inputs on InputCommentsIndentationCommentIsAtTheEndOfBlock

### CODE REVIEW

**Comment by romani** [comment]
Read attentively, all is printed https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=18916&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=1474

Run on your local `mcn verify ` and fix all errors. Push to GitHub only when this command is passing.

**Comment by mahfouz72** [comment]
mvn verify is passing on my local but some CI still fails

**Review by romani — APPROVED** [review]
Ok to merge. We have unfortunately 2 CI failing for unrelated to change reasons.

**Comment by romani** [comment]
@mahfouz72 , please update all for CommentsIndentation Check, to make it be completed done and checked as task.

**Comment by mahfouz72** [comment]
@romani Okay will do, already raised a PR for one Check. and Will do the remaining Checks for CommentIndentation after 2 days right after my exams

**Pull request merged**
