### PR TITLE
Issue #3770: extending OverloadMethodsDeclarationOrderCheck to group by modifiers…

### PR DESCRIPTION
**Pull request by ilanKeshet**
Issue #3770: extending OverloadMethodsDeclarationOrderCheck to support user defined grouping by method modifiers

### CODE REVIEW

**Comment by romani** [comment]
I sent mail to wercker support to address the issue.

**Comment by ilanKeshet** [comment]
@romani, Thanks for the quick feedback, I'll address the issues

**Comment by romani** [comment]
@ilanKeshet , is there some problems with implementation we could help ?

**Comment by ilanKeshet** [comment]
@romani thanks for your offer of help, and my apologies for not letting you in earlier, 
No, there are no problems, I didn't have time to work on the solution at since I was sent to the US by my employer.

**Comment by romani** [comment]
@ilanKeshet , if you know that you will not work on the issue for some long time , lets close PR and reopen it when you have time to continue.

**Pull request closed without merging**
