### PR TITLE
Fix typos in docs of TranslationCheck

### PR DESCRIPTION
**Pull request by Mariam-maghraby**
# PLEASE READ before removing

Rules:
1) The issue you are trying to fix/resolve has to have the "approved" label.
2) Put in the description of Pull Request the reference to an issue if it exists.
   Example: "Issue: #XXXXXX"
3) Commit message should adhere to the following rules:
   a) MUST match one of the following patterns:
      ^Issue #\\d+: .*$
      ^Pull #\\d+: .*$
      ^(minor|config|infra|doc|spelling|dependency): .*$
   b) MUST contain only one line of text
   c) MUST NOT end with a period, space, or tab
   d) MUST be less than or equal to 200 characters

To avoid multiple iterations of fixes and CIs failures, please read
https://checkstyle.org/contributing.html

ATTENTION: We are not merging Pull Requests that are not passing our CIs,
but we will help to resolve issues.

Thanks for reading, remove whole this message and type what you need.

### CODE REVIEW

**Comment by Mariam-maghraby** [comment]
It didn't pass some checks although it passed and built successfully using ` mvn clean verify` on my device.

**Comment by nrmancuso** [comment]
@Mariam-maghraby please read PR description and do all that it requires, and make CI happy

**Comment by Mariam-maghraby** [comment]
@nrmancuso I guess by now I followed all the PR rules, but I still can't make CI happy :"), Can you please tell me if I missed anything?

**Comment by romani** [comment]
Read PR description, and do what is written here

**Comment by romani** [comment]
We lost connection to contributor. Better to fit from scratch

**Pull request closed without merging**
