### PR TITLE
Issue #14715: Enforced new naming convention in IT area - Part One

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Part of #14715 

PR in response to https://github.com/checkstyle/checkstyle/issues/14715#issuecomment-2020382490

I got rid of suffixes like "....One/1" wherever possible and replaced with proper suffixes.
For example : 

- SuppressionXpathRegressionArrayTrailingCommaOne --> `InputXpathArrayTrailingCommaLinear`
- SuppressionXpathRegressionArrayTrailingCommaTwo --> `InputXpathArrayTrailingCommaMatrix`

In commit : 

```
            "AbbreviationAsWordInName",
            "AbstractClassName",
            "AnnotationLocation",
            "AnnotationOnSameLine",
            "AnnotationUseStyle",
            "AnonInnerLength",
            "ArrayTrailingComma",
            "ArrayTypeStyle",
```

### CODE REVIEW

**Comment by rnveach** [comment]
I believe it was mentioned we should stick to 20 files max and a round number of checks. This PR has 47 files but I will still review it.

**Comment by MANISH-K-07** [comment]
> I believe it was mentioned we should stick to 20 files max and a round number of checks. This PR has 47 files but I will still review it.

@rnveach , I will further limit to 20 files / 2-3 checks max. This would take atleast 50 PRs to close in this case

**Comment by rnveach** [comment]
This was why I was originally saying for others to assist with this and not have you do it alone. You can always create more than one PR at a time for this. The best way to accomplish this since we have the suppression list is to do items sporadically. Like do the first 2, skip 6 or so, do the next 2, and so on. That is the best way to avoid git conflicts when one PR is merged.

**Review by rnveach — APPROVED** [review]

**Comment by MANISH-K-07** [comment]
@rnveach , I am on par with what you said, I think @romani wants to close this issue in a subtle way unlike the other easy issues which are filtered by label. I have no problem sending multiple PRs at once like you said as long as the fix gets merged :)

Is this commit good for merge ?

**Comment by MANISH-K-07** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/8467334447/job/23197981375#step:4:2400

```
[INFO] ------------------------------------------------------------------------
------------ grep of linkcheck.html--BEGIN
Checking internal (checkstyle website) and external links.
--- .ci-temp/linkcheck-suppressions-sorted.txt	2024-03-28 12:45:20.802042203 +0000
+++ .ci-temp/linkcheck-errors-sorted.txt	2024-03-28 12:45:20.802042203 +0000
@@ -1,3 +1,5 @@
+<a class="externalLink" href="https://www.baeldung.com/java-double-brace-initialization">https://www.baeldung.com/java-double-brace-initialization</a>: 403 Forbidden
+<a class="externalLink" href="https://www.baeldung.com/java-double-brace-initialization">https://www.baeldung.com/java-double-brace-initialization</a>: 403 Forbidden
 <a href="AbstractExpressionHandler.html#checkChildren(com.puppycrawl.tools.checkstyle.api.DetailAST,int%5B%5D,com.puppycrawl.tools.checkstyle.checks.indentation.IndentLevel,boolean,boolean)">AbstractExpressionHandler.html#checkChildren(com.puppycrawl.tools.checkstyle.api.DetailAST,int%5B%5D,com.puppycrawl.tools.checkstyle.checks.indentation.IndentLevel,boolean,boolean)</a>: doesn't exist.
 <a href="AbstractExpressionHandler.html#checkChildren(com.puppycrawl.tools.checkstyle.api.DetailAST,int%5B%5D,com.puppycrawl.tools.checkstyle.checks.indentation.IndentLevel,boolean,boolean)">AbstractExpressionHandler.html#checkChildren(com.puppycrawl.tools.checkstyle.api.DetailAST,int%5B%5D,com.puppycrawl.tools.checkstyle.checks.indentation.IndentLevel,boolean,boolean)</a>: doesn't exist.
 <a href="AbstractExpressionHandler.html#checkChildren(com.puppycrawl.tools.checkstyle.api.DetailAST,int%5B%5D,com.puppycrawl.tools.checkstyle.checks.indentation.IndentLevel,boolean,boolean)">AbstractExpressionHandler.html#checkChildren(com.puppycrawl.tools.checkstyle.api.DetailAST,int%5B%5D,com.puppycrawl.tools.checkstyle.checks.indentation.IndentLevel,boolean,boolean)</a>: doesn't exist.
------------ grep of linkcheck.html--END
```

@romani , should we be concerned about this ? I'm not sure where this got induced 😕

**Comment by romani** [comment]
I am not sure, but if this not making CI red, we can ignore it for a bit, sometime web links are not stable.

**Comment by MANISH-K-07** [comment]
> I am not sure, but if this not making CI red, we can ignore it for a bit, sometime web links are not stable.

@romani , unfortunately CI `Check no broken links / check_issues (push)` is red in master

image

I don't think any change of this commit introduced broken links or any links in general.
We need to find out the source of these links and remove them from our code and until then suppress these, I believe

**Comment by romani** [comment]
If this problem stays for longer, we can disable link-check-plugin to check such link, there is already bunch of such excludes in pom.xml

**Comment by MANISH-K-07** [comment]
So, leave the failing CI as is for now and ignore in PRs ?

**Pull request merged**
