### PR TITLE
Issue #1487: Improve code coverage of CheckstyleAntTask

### PR DESCRIPTION
**Pull request by Vladlis**
Issue #1487

Current coverage is [here](http://vladlis.github.io/reports/cobertura/com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.html).

Strange thing is that in `testEmptyConfig()` here `checker` is null: https://github.com/Vladlis/checkstyle/blob/cb9979644b598156ca1155a76cb61ae1aac6c2e0/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java#L334

but it still goes inside `if`
-checkstyle - -projects-checkstyle - checkstyle - -projects-checkstyle-src-main-java-com-puppycrawl-tools-checkstyle-ant-checkstyleanttask java - intellij idea 15 0 1

### CODE REVIEW

**Comment by Vladlis** [comment]
@romani, can you take a look on the appveyor problem please?

**Comment by romani** [comment]
1)
>
```
        Checker checker = null;
        try {
            checker = createChecker();
```

to reproduce problem when checker is null in `finally` you need to throw exception in createChecker, please look around for Powermock examples on how we do this. in other tests.

2)
Please do coverage of setters by simply calling them from UT. For now (and only for now), It is ok to skip tests that actually test that changes by such setters change behaviour properly.

**Comment by Vladlis** [comment]
1) Please see screenshot above - checker is null, but condition in `if` doesn't work. Am I miss smth ?
2) Do you mean setters, which are still nor covered?

**Comment by romani** [comment]
> Please see the screenshot above - checker is null, but condition in if doesn't work. Am I miss smth ?

please report bug to Intelij Idea.

> 2) Do you mean setters, which are still nor covered?

yes.

**Comment by romani** [comment]
>
```
  +    <!-- Fixing will break compatibility -->
+    <suppress checks="SimpleAccessorNameNotation"
+              files="CheckstyleAntTask\.java"
+              lines="553"/>
```

please rename field to be just `type`. Class already named as `Formatter` , no need to `formatter` prefix for fields.

**Comment by Vladlis** [comment]
@romani, please relaunch Travis

2) Done

> please rename field to be just type

Done

1) 
I don't think it is IntelliJ IDEA issue, as Eclipse has the same problem and both cobertura and codecov show that the condition is not covered, even though it can be seen in the cobertura [report](http://vladlis.github.io/reports/cobertura/com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.html), that the condition `if (checker != null)` is evaluated 15 times and only 12 times it is `true`.

I have no idea why this happens. We might need ask other contributors.

**Comment by romani** [comment]
> I have no idea why this happens.

please point me to a Test code where you mocking `checker` to be null in `finally`.
Please put "sysout.println" to code and print `checker` value. Travis will show us .

**Comment by romani** [comment]
merged as FF.

to simplify investigation I merged this PR.
please create another PR with additional fix.

**Pull request closed without merging**
