### PR TITLE
Issue#11446 update checker test with verify inline config parser

### PR DESCRIPTION
**Pull request by piyush-1234**
Issue: #11446

### CODE REVIEW

**Comment by romani** [comment]
sonar do not like this update - https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER&sinceLeakPeriod=true&pullRequest=14228&id=org.checkstyle%3Acheckstyle

pitest also not happy - https://github.com/checkstyle/checkstyle/actions/runs/7418265057/job/20185977693?pr=14228#step:7:23 as such test required to cover some functionality 

@piyush-1234 , please  investigate pitest, as it is hard blocker.

**Comment by piyush-1234** [comment]
> sonar do not like this update - https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER&sinceLeakPeriod=true&pullRequest=14228&id=org.checkstyle%3Acheckstyle
> 
> pitest also not happy - https://github.com/checkstyle/checkstyle/actions/runs/7418265057/job/20185977693?pr=14228#step:7:23 as such test required to cover some functionality
> 
> @piyush-1234 , please investigate pitest, as it is hard blocker.

@romani , i have fixed the sonar, 
should we fix the pittest for the checker first in another pr, as successful pittest is needed for this pr.

**Comment by nrmancuso** [comment]
@piyush-1234 ping

**Comment by piyush-1234** [comment]
> @piyush-1234 ping

Hey hi @nrmancuso , sorry for delay to fix this issue, I will resume my work now, as I have been suffering from medical issues from last month so I was busy in medical appointments, 
I will fix this early as possible

**Comment by romani** [comment]
I closing this PR, it is better to start new

**Pull request closed without merging**
