### PR TITLE
Issue #3502: VariableDeclarationUsageDistance

### PR DESCRIPTION
**Pull request by GitToasterhub**
Issue #3502: VariableDeclarationUsageDistance

### CODE REVIEW

**Comment by GitToasterhub** [comment]
@rnveach as you told here https://github.com/checkstyle/checkstyle/issues/3502 I considered theese lines of code,and I offer to consider theese changes .

**Comment by Vladlis** [comment]
@GitToasterhub 
`Issue #3954: MethodParamPad Test input split` - this commit is already merged, please rebase on master to avoid extra changes in diff

**Comment by GitToasterhub** [comment]
@Vladlis I made a new branch and made my new changes there actually,and i made fetch upstream,and rebase on master ,so why then previous commit is pulled,how can I delete it to make only 1?

**Comment by rnveach** [comment]
> I made a new branch

@GitToasterhub Continue using the same branch, don't start a new branch or new PR.

> why then previous commit is pulled,how can I delete it to make only 1?

Read point 2 in https://github.com/checkstyle/checkstyle/wiki/PR-rules .
When you push your changes back, you will need to use the `--force` option.

**Comment by GitToasterhub** [comment]
Oh... I hate git really .. it made all files commited

**Comment by romani** [comment]
please rebase on our latest code , I just merged a fix for wercker CI to our master.

@GitToasterhub , please resolve CIs problems.

**Comment by GitToasterhub** [comment]
@romani When I do rebase for example git rebase -i HEAD~2 then my previous commit files are included to PR as well.Is it OK,or I am doing something wrong?

**Comment by romani** [comment]
you need to pull from main repo all changes to your fork - please read https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/Development-workflow-with-Git%3A-Fork%2C-Branching%2C-Commits%2C-and-Pull-Request

**Comment by GitToasterhub** [comment]
OH YES!! Finally. :) At least I made it in 1 commit.. now I have to work on CI problems. :)

**Comment by rnveach** [comment]
@GitToasterhub ping

**Comment by GitToasterhub** [comment]
@rnveach what does it mean?

**Comment by rnveach** [comment]
@GitToasterhub my `ping` was that we have not heard from you in 4 days on this PR.
Do you plan to finish it?

**Comment by GitToasterhub** [comment]
@rnveach Yeah,of course I had few very busy days unfortunately.And i am a bit stuck with this issue

**Comment by GitToasterhub** [comment]
Oh oh .. wait a while I seem to have found a way,I am gonna push changes,so you can see.

**Comment by GitToasterhub** [comment]
Hope my changes will work..

**Comment by romani** [comment]
@GitToasterhub , do not push new code to remote till on your local "mvn verify" pass without errors.

**Comment by MEZk** [comment]
@GitToasterhub 
Please, fix TC violation:
```
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding
 VariableDeclarationUsageDistanceCheck.java (1)
397: calculateDistanceInSingleScope() Value of post-increment expression dist++ is used
```

**Comment by rnveach** [comment]
@GitToasterhub ping, travis is still failing.
Since we are out of proposal deadline, do you think you can finish this?

**Comment by GitToasterhub** [comment]
@rnveach 
I am totally stuck so I decide to close PR ,but I am going to work on this and other issues,in  case I will find solution i will make new PR with new ideas

**Pull request closed without merging**
