### PR TITLE
Issue #5489: Fixed indentation in config_modifier.xml & config_namin…

### PR DESCRIPTION
**Pull request by varunu28**
…g.xml

minor change in config_modifier.xml and fixed indentation in config_naming.xml #5489

### CODE REVIEW

**Comment by rnveach** [comment]
wercker
> Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.puppycrawl.tools:checkstyle:jar:8.9-SNAPSHOT

Please ensure you are rebased on the latest master.

**Comment by varunu28** [comment]
@rnveach I did a rebase to the master and the current status of the fork repo shows that it is ahead of master by 1 commit i.e. the current commit

**Comment by romani** [comment]
@varunu28 , please do rebase one more time. 
I moved pre-release commits (that are damaging werker) , release is postponed.

**Comment by varunu28** [comment]
@romani Done the rebase

**Comment by varunu28** [comment]
@romani Can you please merge this PR. Thanks

**Comment by varunu28** [comment]
@romani Can you please merge this commit 
I checked the logs for "CI failure" and it is showing a pass status on the logs

**Pull request merged**
