### PR TITLE
Issue #10815: make build fail on javadoc warnings

### PR DESCRIPTION
**Pull request by pbludov**
Issue #10815 

Turn on `failOnWarnings` and exclude all generated code.

### CODE REVIEW

**Review by rnveach — APPROVED** [review]
I assume you verified this works and will solve the issue?

**Comment by pbludov** [comment]
> I assume you verified this works and will solve the issue?

Yes. On my PC `mvn clean site` fails on such case now:
```
1 warning
[WARNING] Javadoc Warnings
[WARNING] /home/pbludov/src/github.com/pbludov/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalkerFilter.java:34: warning: @return has already been specified
[WARNING] * @return false if the event is not accepted.
[WARNING] ^
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

(here an extra `@return` added to `TreeWalkerFilter`).


Note that the Javadoc tool will generate pages only for public types and members by default.

By change the visibility to `private` there is 12 errors and 29 warnings.

**Comment by pbludov** [comment]
This build will fail if the Javadoc tool reports any violations:
https://github.com/checkstyle/checkstyle/runs/3681844869?check_suite_focus=true#step:3:416

**Comment by rnveach** [comment]
> By change the visibility to private there is 12 errors and 29 warnings.

I think we should create a new issue for changing to private. We are already particular on our Javadocs from our checks. It would make sense we do the same with any other tool as long as it doesn't damage us.

**Review by romani — APPROVED** [review]
We actually can scan whole output of build and fail if any warning happens from any plugin.

Previously we were limited to do this as there were bunch of not resolvable warning from anttl2

**Pull request merged**
