### PR TITLE
Issue #4947: split illegalClassNames for IllegalType for short names

### PR DESCRIPTION
**Pull request by rnveach**
Issue #4947

I expect mutation to fail as I haven't added any new tests.
I will run regression for differences too.

### CODE REVIEW

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/103/

Here is one example of a positive from this change.
http://rveach.no-ip.org/checkstyle/regression/reports/103/Vavr/index.html#A2
`scala.collection.immutable.HashSet` was accidentally picked up before as an invalid type of `java.util.HashSet`.

All the other differences are wrongly picked up from importing `java.util.*` and assuming the class mentioned is from that package.

**Comment by rnveach** [comment]
Pitest: http://rveach.no-ip.org/checkstyle/regression/pitest-reports/4/

Percentage hasn't changed, but I will still try to add some new tests and inputs.

**Comment by romani** [comment]
>  I will still try to add some new tests under the code I changed.

in your new method "beginTree" th only line is red is clean for internal Check state. You can make test that do execution on few files to make it affect UTs.

**Comment by rnveach** [comment]
@romani I have added the test that enforces the requested line of the pitest.
I have increased the % for pitest because of this.

**Pull request merged**
