### PR TITLE
minor: fix failing master build (related to #11536)

### PR DESCRIPTION
**Pull request by nick-mancuso**
Noticed at https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/567406582 and https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/567482195, we have somehow damaged master build with this commit: 1d29e97c030935ce2e7ce13a5e7014a9944b0f7e

Link to Travis build that must pass in this PR: https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/567487468

### CODE REVIEW

**Comment by nick-mancuso** [comment]
@romani @strkkk CI in PR for this was green except for pitest-coding, I wonder how this passed Travis in PR but failed in master?

**Comment by romani** [comment]
it might make sense to make check for git diff in other CI too, for example Azure, if it missed it is very visible as count drops significantly

**Comment by nick-mancuso** [comment]
I agree, let’s make an issue on this.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/issues/11554

**Pull request merged**
