### PR TITLE
Issue #410: Some amendments in WritingJavadocChecks wiki-page

### PR DESCRIPTION
**Pull request by baratali**
#410

### CODE REVIEW

**Comment by baratali** [comment]
What is wrong with my commit message?
Due to logs, commit message contains newline symbol at the end, but there is no that symbol when I do commit :)

**Comment by rnveach** [comment]
@baratali 
See Issue #3168. This is similar to what happened before.

Your PR passed travis (because of newline/whitespace) but failed after it was merged (whitespace was most likely removed but it ended with a period).
The issue probably is the new line at the end, but commit messages also shouldn't end with a period.
I assume the util you are using is adding the new line?

**Comment by romani** [comment]
@baratali , please remove all "." from commit message.
If you want to describe fix in two sentence - most likely there should be 2 commits.
If you want to structure/scope message , please use other separator , we already use ":" that kind of mean group.

Your message should looks like:
`Issue XXXXX: WritingJavadocChecks wiki-page: Some amendments`
or 
Issue XXXXX: WritingJavadocChecks wiki-page - Some amendments

**Comment by rnveach** [comment]
@baratali I downloaded your commit `6039187` and it still has the new line in it and `CommitValidationTest` still failed locally for me.

**Comment by romani** [comment]
`mvn test -Dtest=CommitValidationTest` is failing .... strange

**Comment by rnveach** [comment]
@romani Yes, like I mentioned before it is because he has a new line on the end of the commit message.
I said in the issue [here](https://github.com/checkstyle/checkstyle/issues/3168#issuecomment-218593977) the whitespace (new line, space, tab, etc) was allowing the period before and the merge with master was trimming the message.

I'm not sure why only his commits have new lines on the end. It must be something he is doing to create the message.
We can redo the test to trim the message like github is currently doing on a merge if you wish. This would ignore the whitespaces on the end.

**Comment by romani** [comment]
@rnveach , i did amend of his commit to make sure no newline, still failing.
My commits are ignored by such test.

**Comment by rnveach** [comment]
After some searching it seems `git` by default adds a new line to the message.
https://github.com/git/git/blob/a0c4ddf6776dfcd9ea778e22abf1fbdcfa56d3aa/builtin/commit.c#L162-L163
`EGit` in Eclipse allows us to have a commit with no new line.
There doesn't seem a way to prevent it in `git`, and we will have to redo our tests to allow it.

**Comment by romani** [comment]
merged as FF.

**Pull request closed without merging**
