### PR TITLE
Issue #7763: Fix for TrailingComment to log column number in log

### PR DESCRIPTION
**Pull request by yajna-pandith**
Issue #7763: Fix for TrailingComment to log column number in log

### CODE REVIEW

**Comment by strkkk** [comment]
@yajna-pandith please fix CI

**Comment by romani** [comment]
@yajna-pandith , please rebase to fix wercker, 

please fix Travis failure - https://travis-ci.org/github/checkstyle/checkstyle/jobs/666942625#L618

**Comment by romani** [comment]
@yajna-pandith , ping

**Comment by yajna-pandith** [comment]
I tried , yet not getting it fixed.

**Pull request closed without merging**
