### PR TITLE
Issue #7705: add no error regression for contribution repo

### PR DESCRIPTION
**Pull request by rnveach**
Issue #7705

### CODE REVIEW

**Comment by rnveach** [comment]
> Caused by: org.codehaus.plexus.resource.loader.ResourceNotFoundException: Could not find resource 'https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-8.31-SNAPSHOT/config/checkstyle_checks.xml'.

We need to separate out checkstyle version for running from checkstyle version for config usage.

**Comment by rnveach** [comment]
Blocked by https://github.com/checkstyle/contribution/pull/452

**Comment by romani** [comment]
Blocker PR is merged, please proceed.

**Comment by rnveach** [comment]
Everything is ready just need to re-run CI.

**Pull request merged**
