### PR TITLE
Issue #11214: Specified violation message in FallThroughCheck

### PR DESCRIPTION
**Pull request by ricardovogel**
Issue: #11214 (FallThroughCheck)

### CODE REVIEW

**Comment by romani** [comment]
GitHub, rebase

**Review by romani — APPROVED** [review]
Ok to merge if CI pass

**Comment by nick-mancuso** [comment]
@ricardovogel please manually rebase on latest master branch.

**Comment by ricardovogel** [comment]
> @ricardovogel please manually rebase on latest master branch.

Done, I'm sorry for the delay

**Pull request merged**
