### PR TITLE
Issue #15218: formatted input files for section 7.1.3 Block tags to follow google style guide rules

### PR DESCRIPTION
**Pull request by Zopsss**
#15218

### CODE REVIEW

**Comment by romani** [comment]
please fix CI

**Comment by romani** [comment]
please revert renaming,
it make it impossible to visually confirm that you did nothing extra.
Create separate issue for renaming. we will do this in separate activity.

**Comment by Zopsss** [comment]
reverted the renaming, will send a new PR for it after this PR is merged

**Comment by romani** [comment]
Diff is complicated, I need more dedicated time to review it

**Comment by Zopsss** [comment]
@romani

**Review by romani — APPROVED** [review]
ok to merge

**Review by rdiachenko — APPROVED** [review]
lgtm

**Pull request merged**
