### PR TITLE
Issue #14814: refactor recursive checkline into iterative method

### PR DESCRIPTION
**Pull request by mohitsatr**
Part of #14814 : ```checkLine``` method in SinglelineDetector.java

### CODE REVIEW

**Comment by romani** [comment]
image

Regression diff is required for:
RegexpSinglelineCheck
RegexpSinglelineJavaCheck

**Comment by romani** [comment]
@mohitsatr , please apply https://github.com/checkstyle/checkstyle/actions/runs/11496590075/job/31998508905?pr=15807#step:7:8
to let CI be green.

**Comment by romani** [comment]
Github, generate report for RegexpSingleline/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RegexpSinglelineJava/all-examples-in-one

**Comment by romani** [comment]
@mohitsatr , what makes this PR draft ?

**Comment by mohitsatr** [comment]
Im not sure what this is 
```
<checkerFrameworkError unstable="false">
    <fileName>src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/SinglelineDetector.java</fileName>
    <specifier>argument</specifier>
    <message>incompatible argument for parameter start of Matcher.find.</message>
    <lineContent>while (matcher.find(startPosition)) {</lineContent>
    <details>
      found   : @GTENegativeOne int
      required: @NonNegative int
    </details>
  </checkerFrameworkError>

```
am i supposed to add this into checker-index-suppressions.xml ?

**Comment by romani** [comment]
```
public boolean find(int start) {
        int limit = getTextLength();
        if ((start < 0) || (start > limit))
            throw new IndexOutOfBoundsException("Illegal start index");
        reset();
        return search(start);
    }
```

it is asking to put this annootation in our code https://checkerframework.org/api/org/checkerframework/checker/index/qual/NonNegative.html
https://checkerframework.org/manual/#index-annotating-fixed-size

`@NonNegative int startPosition = 0;`

But we are not sure yet on usage of this tool to mark all variables about with annotations. it might be too much noise, too explicit.

Please add this violation to suppression for now.

**Comment by romani** [comment]
@mohitsatr , please apply this patch https://github.com/checkstyle/checkstyle/actions/runs/11537241602/job/32114421297?pr=15807#step:7:8

**Review by romani — APPROVED** [review]
Ok to merge if CI is green

**Review by rdiachenko — APPROVED** [review]
lgtm

**Review by romani — CHANGES_REQUESTED** [review]
Please fix CI

**Comment by mohitsatr** [comment]
this is after I added these violations to suppression : https://github.com/checkstyle/checkstyle/actions/runs/11537241602/job/32114421297?pr=15807#step:7:8

this is before any suppression : https://github.com/checkstyle/checkstyle/actions/runs/11552062444/job/32150373658?pr=15807

**Comment by romani** [comment]
Please apply patch https://github.com/checkstyle/checkstyle/actions/runs/11552062444/job/32150373658?pr=15807#step:7:8 to your commit

**Comment by mohitsatr** [comment]
@romani Im not sure how :
1. running ```git diff && git diff > target/checker-index.patch``` creates an empty checker-index.patch file. 
Should I put the following in this file :
```7. diff --git a/config/checker-framework-suppressions/checker-index-suppressions.xml b/config/checker-framework-suppressions/checker-index-suppressions.xml ```
```8. index 04726b9..16173ef 100644 ``` 

2. and since target/ directory is added .gitingore files , how will i include this in my commit ?

**Comment by romani** [comment]
>Should I put the following in this file :

Yes.

**Comment by Zopsss** [comment]
@mohitsatr If you're using IntelliJ Idea then you can directly apply patch as shown in the below Screenshot:

Screenshot 2024-10-31 140538

Right click on the patch file and then click `Apply Patch`, delete the patch file once it is applied.

> and since target/ directory is added .gitingore files , how will i include this in my commit ?

you dont need to. `/target` directory is automatically generated when you run `mvn clean verify`, so no need to add it in commit. You can think of it as a `build` folder if you're coming from Web Dev background.

**Comment by mohitsatr** [comment]
thanks @Zopsss for this. I was pretty confused about this before. now i have got it

**Review by romani — APPROVED** [review]
Thanks a lot

**Comment by romani** [comment]
@mohitsatr , thanks a lot for fix.

I hope you can help us to fix https://github.com/checkstyle/checkstyle/issues/15837 so nobody will be confused anymore.

**Pull request merged**
