### PR TITLE
doc: Add Mega-Linter in Active Tools list & reorder table

### PR DESCRIPTION
**Pull request by nvuillam**
Issue: #8922 

With "Squash & merge" option , the commit title will follow the contributing rule :)

### CODE REVIEW

**Comment by strkkk** [comment]
@nvuillam please
1. Make only 1 commit with commit message like `Issue #8922: <your message>`
2. Exclude any changes that are not related to issue, such as xml formatting and table reordering.

**Comment by nvuillam** [comment]
Will make another PR, ok :)

**Comment by strkkk** [comment]
@nvuillam and please do not close/open PRs to avoid spam notications to maintainers, it all can be done in one PR

**Comment by nvuillam** [comment]
Oops too late sorry :/
I won't do it again, I promise 😢

**Pull request closed without merging**
