### PR TITLE
Issue #9489: add example of AST for TokenTypes.LITERAL_PROTECTED

### PR DESCRIPTION
**Pull request by Ritik2604**
Issue: #9489 

LITERAL_PROTECTED photo

Source used to generate AST:
```
public class MyClass{
    protected int x;
}
```
Generated AST:

```
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> MyClass [1:13]
`--OBJBLOCK -> OBJBLOCK [1:20]
    |--LCURLY -> { [1:20]
    |--VARIABLE_DEF -> VARIABLE_DEF [2:2]
    |   |--MODIFIERS -> MODIFIERS [2:2]
    |   |   `--LITERAL_PROTECTED -> protected [2:2]
    |   |--TYPE -> TYPE [2:12]
    |   |   `--LITERAL_INT -> int [2:12]
    |   |--IDENT -> x [2:16]
    |   `--SEMI -> ; [2:17]
    `--RCURLY -> } [3:0]

```
# printing a line only for code that we care
$ java -jar checkstyle-8.41-all.jar -t MyClass.java | grep "2:"
    |--VARIABLE_DEF -> VARIABLE_DEF [2:2]
    |   |--MODIFIERS -> MODIFIERS [2:2]
    |   |   `--LITERAL_PROTECTED -> protected [2:2]
    |   |--TYPE -> TYPE [2:12]
    |   |   `--LITERAL_INT -> int [2:12]
    |   |--IDENT -> x [2:16]
    |   `--SEMI -> ; [2:17]

Expected Update for JavaDoc:

```
VARIABLE_DEF -> VARIABLE_DEF
 |--MODIFIERS -> MODIFIERS
 |   `--LITERAL_PROTECTED -> protected
 |--TYPE -> TYPE
 |   `--LITERAL_INT -> int
 |--IDENT -> x
 `--SEMI -> ;
```

### CODE REVIEW

**Comment by Ritik2604** [comment]
Why there are these many errors??  :-(

**Comment by Ritik2604** [comment]
@romani Please help me out.

**Comment by CryptoSingh1337** [comment]
Please squash 2 commits into 1 and your commit message should look like this:

Ex: **Issue #"IssueNo": add example of AST for TokenTypes.RESOURCES**
or refer to a [PR](https://github.com/checkstyle/checkstyle/pull/9716)

Proper commit message should adhere to the following rules:
    1) Must match one of the following patterns:
        ^Issue #\d+: .*$
        ^Pull #\d+: .*$
        ^(minor|config|infra|doc|spelling|dependency|supplemental): .*$
    2) It contains only one line of text
    3) Must not end with a period, space, or tab
    4) Commit message should be less than or equal to 200 characters

**Comment by romani** [comment]
Please read https://checkstyle.org/beginning_development.html#Starting_Development on how to do amendments in PR

**Comment by Ritik2604** [comment]
@romani really need your help 
how to remove previous 2 commits inorder to squash them and do again final commit
and now they are 4 extra commits how can I squash them my GIT does not show that previous commits to squash

**Comment by romani** [comment]
Try to redo your branch from scratch based on latest come our master

**Comment by Ritik2604** [comment]
I didnt get it

**Comment by romani** [comment]
Backup your changes.
Drop/remove your local branch.
Get latest master from upstream, create new beach from it, apply code changes, push to GitHub with "--force".

**Comment by Ritik2604** [comment]
@romani there is no errors now you can merge or not? or i have to make new PR .

**Pull request closed without merging**
