### PR TITLE
Issue #14516: Updated LITERAL_NEW outdated examples and AST of TokenTypes.java to new format of AST print

### LINKED ISSUE #14516: update TokenTypes.java to new format of AST print
We need to update https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html to reflect the current printed  abstract syntax tree representation.

Example of old style (note the `+` and lack of `->`):
```
 +--LITERAL_NEW (new)
     |
     +--LITERAL_FLOAT (float)
     +--ARRAY_DECLARATOR ([)
     +--ARRAY_INIT ({)
         |
         +--EXPR
             |
             +--NUM_FLOAT (3.0f)
         +--COMMA (,)
         +--EXPR
             |
             +--NUM_FLOAT (4.0f)
         +--RCURLY (})

```

Example of new style:
```
 LITERAL_NEW -> new
  |--IDENT -> ArrayList
  |--TYPE_ARGUMENTS -> TYPE_ARGUMENTS
  |   |--GENERIC_START -> <
  |   `--GENERIC_END -> >
  |--LPAREN -> (
  |--ELIST -> ELIST
  |   `--EXPR -> EXPR
  |       `--NUM_INT -> 50
  `--RPAREN -> )

```

Example of where we need to update: https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#PARAMETERS , there might be more, ABSTRACT, STRICTFP, LITERAL_NEW, SINGLE_LINE_COMMENT.

How to generate our AST via command line:
```
➜  src cat Test.java
public class Test {
    String s = "";
}
➜  src java -jar checkstyle-10.13.0-all.jar -t Test.java | sed 's/->/-\&gt;/g; s/\[[0-9]\+:[0-9]\+\]//g'
COMPILATION_UNIT -&gt; COMPILATION_UNIT 
`--CLASS_DEF -&gt; CLASS_DEF 
    |--MODIFIERS -&gt; MODIFIERS 
    |   `--LITERAL_PUBLIC -&gt; public 
    |--LITERAL_CLASS -&gt; class 
    |--IDENT -&gt; Test 
    `--OBJBLOCK -&gt; OBJBLOCK 
        |--LCURLY -&gt; { 
        |--VARIABLE_DEF -&gt; VARIABLE_DEF 
        |   |--MODIFIERS -&gt; MODIFIERS 
        |   |--TYPE -&gt; TYPE 
        |   |   `--IDENT -&gt; String 
        |   |--IDENT -&gt; s 
        |   |--ASSIGN -&gt; = 
        |   |   `--EXPR -&gt; EXPR 
        |   |       `--STRING_LITERAL -&gt; "" 
        |   `--SEMI -&gt; ; 
        `--RCURLY -&gt; } 
```

Note that this `sed` command escapes the `>` character and removes the line:column numbers for our documentation. Also, please be aware that we may need to update the existing code sample to be a bit more substantial.

For more details about Checkstyle's command line usage, see: https://checkstyle.org/cmdline.html#Command_line_usage

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Aims to close #14516

EDIT : Changed link to TokenTypes of our docs to be more specific
https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html

Updated Inputs based on suggestions from review :

```
E:\MANISH\Workspace>cat Test.java
import java.util.ArrayList;
import java.util.List;

public class Test {
    List<String> l = new ArrayList<String>();
}

```
```
E:\MANISH\Workspace>cat Test.java
public class Test {
    String[] strings = new String[3];
}

```
```
E:\MANISH\Workspace>cat Test.java
public abstract class Supplier<Integer> {
    public abstract Integer get();
}
public class Test {
    Supplier<Integer> s = new Supplier<>() {
        @Override
        public Integer get() {
            return 42;
        }
    };
}

```
// Outdated Inputs used previously : 

```
public class Test {
  float[] test = new float[]
    {
      3.0f,
      4.0f
    };
}
```
```
E:\MANISH\Workspace>cat Test.java
import java.io.File;

public class FilenameFilter {}
public class Test {
    FilenameFilter test = new FilenameFilter()
    {
      public boolean accept(File dir, String name)
      {
        return name.endsWith(".java");
      }
    };
}
```

### CODE REVIEW

**Comment by MANISH-K-07** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/8169226261/job/22332869352?pr=14617#step:6:19

This failure doesn't look related to my changes ??

**Comment by MANISH-K-07** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/8169226261/job/22332869352?pr=14617#step:6:19

Is this failure related to my changes ??

```
Error:  Plugin org.pitest:pitest-maven:1.15.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.pitest:pitest-maven:jar:1.15.8: Could not transfer artifact org.pitest:pitest-maven:pom:1.15.8 from/to nexus-codehaus-snapshot (https://oss.sonatype.org/content/repositories/codehaus-snapshots/): transfer failed for https://oss.sonatype.org/content/repositories/codehaus-snapshots/org/pitest/pitest-maven/1.15.8/pitest-maven-1.15.8.pom: Unknown host oss.sonatype.org: Temporary failure in name resolution -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.pitest:pitest-maven:1.15.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.pitest:pitest-maven:jar:1.15.8
```

@romani , 
I have checked [TokenTypes.java](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java) for such old formats of AST and this is the last I could find. I think the issue can be closed now ??

**Comment by nrmancuso** [comment]
Github, generate website

**Review by nrmancuso — CHANGES_REQUESTED** [review]
We need to update the outdated/contrived examples to be complete declarations. Please replace the three existing examples with:

1. `List<String> l = new ArrayList<String>();` (generic object instantiation)
2. `String[] strings = new String[3];` (array initialization)
3. 
```
    Supplier<Integer> s = new Supplier<>() {
        @Override
        public Integer get() {
            return 42;
        }
    };
```
(anonymous class)

It is good to have complete declarations to see each token in it's full context.

**Comment by MANISH-K-07** [comment]
```
    /**
     * The {@code new} keyword.  This element is used to define
     * new instances of objects, new arrays, and new anonymous inner
     * classes.
     *
     * <p>For example:</p>
     *
     * <pre>
     * List&lt;String&gt; l = new ArrayList&lt;String&gt;();
     * </pre>
     *
     * <p>parses as:</p>
     * <pre>
     * VARIABLE_DEF -&gt; VARIABLE_DEF
     *  |--MODIFIERS -&gt; MODIFIERS
     *  |--TYPE -&gt; TYPE
     *  |   |--IDENT -&gt; List
     *  |   `--TYPE_ARGUMENTS -&gt; TYPE_ARGUMENTS
     *  |       |--GENERIC_START -&gt; &lt;
     *  |       |--TYPE_ARGUMENT -&gt; TYPE_ARGUMENT
     *  |       |   `--IDENT -&gt; String
     *  |       `--GENERIC_END -&gt; &gt;
     *  |--IDENT -&gt; l
     *  |--ASSIGN -&gt; =
     *  |   `--EXPR -&gt; EXPR
     *  |       `--LITERAL_NEW -&gt; new
     *  |           |--IDENT -&gt; ArrayList
     *  |           |--TYPE_ARGUMENTS -&gt; TYPE_ARGUMENTS
     *  |           |   |--GENERIC_START -&gt; &lt;
     *  |           |   |--TYPE_ARGUMENT -&gt; TYPE_ARGUMENT
     *  |           |   |   `--IDENT -&gt; String
     *  |           |   `--GENERIC_END -&gt; &gt;
     *  |           |--LPAREN -&gt; (
     *  |           |--ELIST -&gt; ELIST
     *  |           `--RPAREN -&gt; )
     *  `--SEMI -&gt; ;
     * </pre>
     *
     * <p>For example:</p>
     * <pre>
     * String[] strings = new String[3];
     * </pre>
     *
     * <p>parses as:</p>
     * <pre>
     * VARIABLE_DEF -&gt; VARIABLE_DEF
     *  |--MODIFIERS -&gt; MODIFIERS
     *  |--TYPE -&gt; TYPE
     *  |   |--IDENT -&gt; String
     *  |   `--ARRAY_DECLARATOR -&gt; [
     *  |       `--RBRACK -&gt; ]
     *  |--IDENT -&gt; strings
     *  |--ASSIGN -&gt; =
     *  |   `--EXPR -&gt; EXPR
     *  |       `--LITERAL_NEW -&gt; new
     *  |           |--IDENT -&gt; String
     *  |           `--ARRAY_DECLARATOR -&gt; [
     *  |               |--EXPR -&gt; EXPR
     *  |               |   `--NUM_INT -&gt; 3
     *  |               `--RBRACK -&gt; ]
     *  `--SEMI -&gt; ;
     * </pre>
     *
     * <p>For example:</p>
     * <pre>
     * Supplier&lt;Integer&gt; s = new Supplier&lt;&gt;() {
     *     @Override
     *     public Integer get() {
     *         return 42;
     *     }
     * };
     * </pre>
     *
     * <p>parses as:</p>
     * <pre>
     * VARIABLE_DEF -&gt; VARIABLE_DEF
     *  |--MODIFIERS -&gt; MODIFIERS
     *  |--TYPE -&gt; TYPE
     *  |   |--IDENT -&gt; Supplier
     *  |   `--TYPE_ARGUMENTS -&gt; TYPE_ARGUMENTS
     *  |       |--GENERIC_START -&gt; &lt;
     *  |       |--TYPE_ARGUMENT -&gt; TYPE_ARGUMENT
     *  |       |   `--IDENT -&gt; Integer
     *  |       `--GENERIC_END -&gt; &gt;
     *  |--IDENT -&gt; s
     *  |--ASSIGN -&gt; =
     *  |   `--EXPR -&gt; EXPR
     *  |       `--LITERAL_NEW -&gt; new
     *  |           |--IDENT -&gt; Supplier
     *  |           |--TYPE_ARGUMENTS -&gt; TYPE_ARGUMENTS
     *  |           |   |--GENERIC_START -&gt; &lt;
     *  |           |   `--GENERIC_END -&gt; &gt;
     *  |           |--LPAREN -&gt; (
     *  |           |--ELIST -&gt; ELIST
     *  |           |--RPAREN -&gt; )
     *  |           `--OBJBLOCK -&gt; OBJBLOCK
     *  |               |--LCURLY -&gt; {
     *  |               |--METHOD_DEF -&gt; METHOD_DEF
     *  |               |   |--MODIFIERS -&gt; MODIFIERS
     *  |               |   |   |--ANNOTATION -&gt; ANNOTATION
     *  |               |   |   |   |--AT -&gt; @
     *  |               |   |   |   `--IDENT -&gt; Override
     *  |               |   |   `--LITERAL_PUBLIC -&gt; public
     *  |               |   |--TYPE -&gt; TYPE
     *  |               |   |   `--IDENT -&gt; Integer
     *  |               |   |--IDENT -&gt; get
     *  |               |   |--LPAREN -&gt; (
     *  |               |   |--PARAMETERS -&gt; PARAMETERS
     *  |               |   |--RPAREN -&gt; )
     *  |               |   `--SLIST -&gt; {
     *  |               |       |--LITERAL_RETURN -&gt; return
     *  |               |       |   |--EXPR -&gt; EXPR
     *  |               |       |   |   `--NUM_INT -&gt; 42
     *  |               |       |   `--SEMI -&gt; ;
     *  |               |       `--RCURLY -&gt; }
     *  |               `--RCURLY -&gt; }
     *  `--SEMI -&gt; ;
     * </pre>
     *
     * @see #IDENT
     * @see #DOT
     * @see #LPAREN
     * @see #ELIST
     * @see #RPAREN
     * @see #OBJBLOCK
     * @see #ARRAY_INIT
     * @see FullIdent
     **/
    public static final int LITERAL_NEW = JavaLanguageLexer.LITERAL_NEW;
```

The anonymous class example is giving a parse error : 

```
[INFO] --- exec-maven-plugin:3.2.0:java (default) @ checkstyle ---
[WARNING]
java.lang.IllegalArgumentException: [ERROR:4342] Javadoc comment at column 8 has parse error. Missed HTML close tag 'pre'. Sometimes it means that close tag missed for one of previous tags.
```
image

AST is generated but putting it in the javadoc is throwing parse error. I don't see anywhere the html tag is open ?

**Comment by MANISH-K-07** [comment]
Github, generate website

**Comment by MANISH-K-07** [comment]
@nrmancuso ,
The PR description has been updated with the code of new inputs for reference. I have used examples that you have suggested.

**Comment by nrmancuso** [comment]
@MANISH-K-07 please do me a favor: add a separate commit to change the link to TokenTypes here: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/90dd5f0_2024194118/writingchecks.html#Understanding_token_sets

Instead of https://checkstyle.sourceforge.io/apidocs/index.html, please do https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html

commit can be like: `doc: make tokentypes link more specific`.

**Comment by MANISH-K-07** [comment]
Github, generate website

**Comment by MANISH-K-07** [comment]
Rebased on master

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e977ea3_2024023221/writingchecks.html#
Final webpage with updated link to TokenTypes

**Review by nrmancuso — APPROVED** [review]
Massive improvement, thanks a lot @MANISH-K-07 !

**Pull request merged**
