### PR TITLE
Issue #5759: Update AbstractParenPadCheck to log DetailAST

### PR DESCRIPTION
**Pull request by pbludov**
Issue #5759 AbstractParenPadCheck
regression report https://pbludov.github.io/issue-5759/parenpad/

### CODE REVIEW

**Comment by pbludov** [comment]
>Missing changes to add check to xdoc if check is fully supported.

done.

**Comment by rnveach** [comment]
`is followed by whitespace` moved back by 1 character.
`is preceded with whitespace.` moved forward by 1 character.
before all violations were on whitespace, so it moved closer to the nearest token (`(` or `)`).

**Comment by romani** [comment]
http://checkstyle.sourceforge.net/config_filters.html#SuppressionXpathFilter_Description it is better to mention name without "Check" suffix, as in xdoc with name Check without prefix.

**Comment by romani** [comment]
> Once all checks

I never trust in promises :) to be in good shape eventually. 
Code should be in good in each step, and next step my never come, even it is very simple.

**Pull request merged**
