### PR TITLE
Issue #8859: Add SpongePowered/Configurate Checkstyle run to CI

### PR DESCRIPTION
**Pull request by nmancus1**
Issue #8859: Add SpongePowered/Configurate Checkstyle run to CI

### CODE REVIEW

**Comment by romani** [comment]
@zml2008 , please help us to udpate gradle command exact problem to output of build.
contributors should see all failures easily in web.

**Comment by zml2008** [comment]
Looks like Gradle isn't finding the snapshot build of checkstyle:

```
* What went wrong:02:29
Execution failed for task ':core:checkstyleMain'.02:29
> Could not resolve all files for configuration ':core:checkstyle'.02:29
   > Could not find com.puppycrawl.tools:checkstyle:8.37-SNAPSHOT.02:29
     Searched in the following locations:02:29
       - https://jcenter.bintray.com/com/puppycrawl/tools/checkstyle/8.37-SNAPSHOT/maven-metadata.xml02:29
       - https://jcenter.bintray.com/com/puppycrawl/tools/checkstyle/8.37-SNAPSHOT/checkstyle-8.37-SNAPSHOT.pom02:29
       - file:/home/semaphore/.m2/repository/com/puppycrawl/tools/checkstyle/8.37-SNAPSHOT/maven-metadata.xml02:29
       - file:/home/semaphore/.m2/repository/com/puppycrawl/tools/checkstyle/8.37-SNAPSHOT/checkstyle-8.37-SNAPSHOT.pom02:29
       - https://repo.maven.apache.org/maven2/com/puppycrawl/tools/checkstyle/8.37-SNAPSHOT/maven-metadata.xml02:29
       - https://repo.maven.apache.org/maven2/com/puppycrawl/tools/checkstyle/8.37-SNAPSHOT/checkstyle-8.37-SNAPSHOT.pom02:29
     Required by:02:29
         project :core
```

Where should I have gradle look for the snapshot artifact? Maven local (`~/.m2/repository`) was where I was expecting it, but would it be on Sonatype OSS or somewhere else instead? I don't see how anything but a local build could respond to the changes in a specific PR.

Looking at the [no error test on PMD](https://checkstyle.semaphoreci.com/jobs/0a5f25a8-7d9b-4eed-a3c7-51f44c75262a#L939), it seems to be fetching checkstyle 8.37-SNAPSHOT from Sonatype OSS snapshots:

```
Downloading from sonatype-nexus-plugin-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/puppycrawl/tools/checkstyle/8.37-SNAPSHOT/checkstyle-8.37-20201002.191008-55.jar02:18
Downloaded from sonatype-nexus-plugin-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/puppycrawl/tools/checkstyle/8.37-SNAPSHOT/checkstyle-8.37-20201002.191008-55.jar (1.6 MB at 2.4 MB/s)
```

Is this the correct behaviour? If so I can make Configurate match.

**Comment by romani** [comment]
It is mistake to get snapshot from remote, we need to teach Gradle to get it from maven local repository

**Comment by zml2008** [comment]
```
       - file:/home/semaphore/.m2/repository/com/puppycrawl/tools/checkstyle/8.37-SNAPSHOT/maven-metadata.xml02:29
       - file:/home/semaphore/.m2/repository/com/puppycrawl/tools/checkstyle/8.37-SNAPSHOT/checkstyle-8.37-SNAPSHOT.pom
```

It looks like Gradle is looking in maven local, but isn't finding it there. The PMD test isn't finding it in maven local either -- so both probably need to be fixed. Where is checkstyle being built in the semaphore script?

**Comment by romani** [comment]
Thanks a lot.
https://github.com/checkstyle/checkstyle/blob/master/.semaphore/semaphore.yml
Build of checkstyle is missing.
It should be `mvn install -Pno-validations`
Before https://github.com/checkstyle/checkstyle/blob/master/.semaphore/semaphore.yml#L64

**Comment by romani** [comment]
@zml2008 , I fixed CI config, now it works, but I noticed that build still compile Java and test sources, if you can suggest us a command on how to do checkstyle execution without compilation, it would be awesome.

**Comment by romani** [comment]
@zml2008 , if you know how to speedup execution please share we will improve in next PR

**Comment by zml2008** [comment]
Sadly compiling sources is part of what Gradle's checkstyle plugin does. See https://github.com/gradle/gradle/blob/af00297f532c11422e279a5f4575ab83f850879e/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java#L137 -- the checkstyle task for each source set is configured to depend on the compiled classes of that source set. If that's not necessary, it may be something Gradle itself should fix.

**Pull request merged**
