### PR TITLE
Issue #13345: Enable examples tests for GenericWhitespaceCheck

### PR DESCRIPTION
**Pull request by AmitKumarDeoghoria**
### Title: Enable examples tests for GenericWhitespaceCheck

**Related Issue: #13345** 

**Summary**
This pull request aims to enable example tests for the **GenericWhitespaceCheck** in the project. The implementation focuses on ensuring that GenericWhitespace checks are correctly validated through comprehensive test cases, improving overall code reliability and quality.

**Key Changes Made**

- Conversion of txt file to Java File
- Enable the test cases by adding expected violations in the expected array for all example tests
- Made corresponding changes in the xml and xml.template file

### CODE REVIEW

**Comment by AmitKumarDeoghoria** [comment]
GitHub, generate website

**Comment by AmitKumarDeoghoria** [comment]
GitHub, generate website

**Review by romani — CHANGES_REQUESTED** [review]
Please fix compile error https://app.circleci.com/pipelines/github/checkstyle/checkstyle/28763/workflows/84bade25-4f86-466a-907c-bb552ec6146b/jobs/725529

**Comment by AmitKumarDeoghoria** [comment]
GitHub, generate website

**Review by romani — APPROVED** [review]
Thanks a lot!!

**Pull request merged**
