### PR TITLE
spelling: Update messages_fr.properties

### PR DESCRIPTION
**Pull request by sebastienaubry**
Fixed syntax (En français, "espace" est féminin quand il s'agit du caractère.)

### CODE REVIEW

**Comment by rnveach** [comment]
@sebastienaubry Please rename commit message to `spelling: Update messages_fr.properties`.
This way it will pass CI.

**Comment by rnveach** [comment]
@sebastienaubry You updated the PR title and not the commit message. Please also keep number of commits as 1. Let us know if you plan to do more updates.

**Comment by sebastienaubry** [comment]
Hi,
I fixed this spelling error directly on Github (and 2 more in further commits). Is there any way to rename the commit message directly on Github? 
Thanks

**Comment by rnveach** [comment]
Not from github. If you are done with modifications, I will squash the commits for you.

**Comment by sebastienaubry** [comment]
I am done, thank you very much.

**Comment by romani** [comment]
Thanks a lot.

**Pull request merged**
