### PR TITLE
minor: remove obsolete pmd suppression

### PR DESCRIPTION
**Pull request by pbludov**
Issue https://github.com/hcoles/pitest/issues/377 seems to be resolved.
Local run of `pmd:check` succeeded on my PC.

### CODE REVIEW

**Comment by rnveach** [comment]
> Issue hcoles/pitest#377 seems to be resolved.

How so? Issue is still open in pitest. If you are sure it was resolved somewhere, then we should make a post to issue that it can be closed.

**Comment by romani** [comment]
I can not close pitest issue, it is not authored by me.
but it is not a problem any more after bunch of refactoring.

**Comment by rnveach** [comment]
We can still post and ping the owner that it can be closed.

**Comment by romani** [comment]
I did comment in pitest issue

**Pull request merged**
