### PR TITLE
Issue #2161: unify test input locations

### PR DESCRIPTION
**Pull request by rnveach**
rest of import package

### CODE REVIEW

**Comment by rnveach** [comment]
@romani How do you want me to handle this error?
https://ci.appveyor.com/project/Checkstyle/checkstyle/build/2250/job/79h92xapni99qn4e#L179
> [checkstyle] C:\projects\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\imports\ImportOrderCheckTest.java:45: error: Total number of methods is 36 (max allowed is 35).

**Comment by romani** [comment]
do it like https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml#L46
It is not reasonable to split a code of test of this Check into two UT-files.

**Comment by rnveach** [comment]
done

**Comment by romani** [comment]
Merged as ff.

Thanks s lot.

**Pull request closed without merging**
