### PR TITLE
Issue #3491: DetailAst class unclear logic in addChilld method

### PR DESCRIPTION
**Pull request by GitToasterhub**
Issue #3491: DetailAst class unclear logic in addChilld method

### CODE REVIEW

**Comment by romani** [comment]
@GitToasterhub  , please rebase on our latest code , I just merged a fix for wercker CI to our master.
please squash commits in one. Resolve CIs problems.

**Comment by GitToasterhub** [comment]
Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (ant-phase-verify) on project checkstyle: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] C:\projects\checkstyle\config\ant-phase-verify.xml:48: Checkstyle failed: Got 1 errors and 0 warnings.
[ERROR] around Ant part ...<ant antfile="config/ant-phase-verify.xml"/>... @ 7:47 in C:\projects\checkstyle\target\antrun\build-main.xml


I haven't changed anything except 1 method stated in Changed files of PR.Ant process fails as well when I run it on my local copy of project..

**Comment by romani** [comment]
@GitToasterhub , please read log attentively

https://ci.appveyor.com/project/Checkstyle/checkstyle/build/6509/job/mjvpndplavixa48w#L3228
```
execute:
     [echo] Checkstyle started: 18/03/2017 06:41:06 PM
[checkstyle] Running Checkstyle 7.7-SNAPSHOT on 930 files
[checkstyle] [ERROR] C:\projects\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\api\DetailAST.java:157:25: 'typecast' is not followed by whitespace. [WhitespaceAfter]
     [echo] Checkstyle finished: 18/03/2017 06:41:43 PM
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

just follow formatting guidelines.

**Comment by romani** [comment]
looks like moved to new PR - #4054

**Pull request closed without merging**
