### PR TITLE
Issue #537 refactored tests from blocks package.

### PR DESCRIPTION
**Pull request by ychulovskyy**

### CODE REVIEW

**Comment by romani** [comment]
Thanks a lot, Please do one more step in refactoring and do getCheckMessage call ones in tests.

**Comment by ychulovskyy** [comment]
I'll update it for messages that has no parameters.
But will not for messages that accepts parameters, since introducing many constants will make it unreadable.
Is it OK with you?

**Comment by romani** [comment]
yes, keep UT readable and simple.

**Comment by romani** [comment]
merged, additional request could be done in separate PR.

**Pull request closed without merging**
