### PR TITLE
UT coverage 100% for ImportControlCheck #1128

### PR DESCRIPTION
**Pull request by ivanov-alex**
and for ImportControlLoader

### CODE REVIEW

**Comment by romani** [comment]
src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/import_control_MODIFIED_FOR_UT.dtd

has to be stored out of production code and resources, for example at src/test/resources/com/.....

**Comment by ivanov-alex** [comment]
Agree, moved to src/test...

**Comment by romani** [comment]
1) > e.printStackTrace();

do not print exceptions - if  expect them do nothing  and have comment "//expected" or if not expected - do not catch it.

2)
please move all resources to "import" sub package(sub-folder)

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
