### PR TITLE
config: define explicitly dist version for Travis, to address #6851

### PR DESCRIPTION
**Pull request by romani**
#6851

### CODE REVIEW

**Comment by romani** [comment]
This doesn't resolve the issue

**Comment by pbludov** [comment]
From https://travis-ci.community/t/cannot-install-oracle-jdk-11/3892/5

> looks like the “headless” download is no longer supported by Oracle. When triggering a download from their web site https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html  you’re forwarded to the Oracle login page.

**Comment by rnveach** [comment]
We may just have to remove everything oracle.

**Comment by romani** [comment]
moved to #6861

**Pull request closed without merging**
