### PR TITLE
Issue #9515: update example of AST for TokenTypes.MINUS

### PR DESCRIPTION
**Pull request by shubham11941140**
Issue: #9515: update example of AST for TokenTypes.MINUS

### CODE REVIEW

**Comment by SGanguly1999** [comment]
@shubham11941140 please check whether your changes are passing `mvn verify`. Also squash your commits into one.

[Beginning Development](https://checkstyle.sourceforge.io/beginning_development.html).Follow this if you are finding it hard.

**Comment by shubham11941140** [comment]
I am not able to understand how to check it passes mvn verify command and the commits are not squashing even after using CLI?

**Comment by SGanguly1999** [comment]
Perform 

`git log`

and show me the screenshot for first three issues you are getting

**Comment by SGanguly1999** [comment]
If the first three issues are yours then do

`git rebase -i HEAD~3`

You will get an interactive editor 

which will show something like this:-

```
pick ....
pick ...
pick ....
```
Covert two the picks into squash and leave one. Change the commit message after it. Your commits are squashed into one

**Comment by shubham11941140** [comment]
Actually I run those commands but and it says it is rebased but no changes are shown in the repository.

**Review by romani — CHANGES_REQUESTED** [review]
code update is ok, but CI should be green
please rebase and squash commits.

**Comment by romani** [comment]
merged in another PR

**Pull request closed without merging**
