### PR TITLE
Issue #13345: Enable example test for parameterassignment

### PR DESCRIPTION
**Pull request by AayushSaini101**
Related: https://github.com/checkstyle/checkstyle/issues/13345

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by AayushSaini101** [comment]
> Ok to merge

Please add hactober tag

**Comment by romani** [comment]
How did you fixed circle CI ?

**Comment by AayushSaini101** [comment]
> How did you fixed circle CI ?

The main issue was due to two accounts merging in the account. I remove one account from config

**Comment by romani** [comment]
@AayushSaini101 , please fix all your other PRs .

**Comment by AayushSaini101** [comment]
> @AayushSaini101 , please fix all your other PRs .
I have to create new PR for all. In the existing PR I cannot able to resolve them

**Comment by romani** [comment]
@AayushSaini101 , please close all PRs and open new. Red CI will always be red flag for mentors.

**Comment by nrmancuso** [comment]
@romani we still have some issue in this PR, it shows 106 checks passed vs 112 in other PRs. @AayushSaini101 please investigate which checks are missing and share in here.

**Comment by romani** [comment]
several CircleCIs are missed, strange, rebasing ....

**Review by nrmancuso — APPROVED** [review]

**Pull request merged**
