### PR TITLE
Issue 2451: removed excess hierarchy from RequireThisCheck

### PR DESCRIPTION
**Pull request by rnveach**
RequireThisCheck was the only one using AbstractDeclarationCollector, so all fields/methods were copied.
Since the abstract class had some overrides, they had to be duplicated for RequireThisCheck.

### CODE REVIEW

**Comment by rnveach** [comment]
> com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck failed coverage check. Branch coverage rate of 98.5% is below 100.0%

I am not sure why I am getting this error since I have a line in the pom saying it overrides the default min, just like AbstractDeclarationCollector did.

**Comment by romani** [comment]
screenshotfromcobertura

**Comment by rnveach** [comment]
@romani 
I know where the missing coverage is. AbstractDeclarationCollector had missing coverage too.
I was refering to this line in the pom:
https://github.com/rnveach/checkstyle/commit/2ecad28821673e9ec01af0617a36e729ca2e4a7f#diff-600376dffeb79835ede4a0b285078036L1630

With these lines we are telling it to not require 100% for RequireThisCheck. It should now only require a max of 98% but it is still complaining that it must be 100%.

**Comment by romani** [comment]
you do update for jacoco-maven-plugin, but we use cobertura to enforce coverage.
We tried to use jacoco , but it not that good as cobertura for our project. So we have config but we do not use it. We do not remove it as it might be that jacoco finally resolve issues. Cobertura is not updating for long time :( .

Decrease of coverage is not ok, we spend too much time to make 100% coverage.

**Comment by rnveach** [comment]
I'm sorry, I wasn't trying to reduce coverage but I realized now where all my confusion came from.
Since I was just copying code and the old class isn't in use anymore, I assumed it had some type of override on coverage for it. When I found the coverage in the POM, I thought that was it, not realizing it was jacoco.

I reverted my changes for jacoco, and added the test "testDefaultSwitch" to fill the coverage.

**Comment by romani** [comment]
merged as FF.

thanks a lot !

**Pull request closed without merging**
