### PR TITLE
Issue #5003: increased coverage of pitest-checks-whitespace to 98%

### PR DESCRIPTION
**Pull request by Nimfadora**
Issue #5003

[report before changes](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.whitespace/index.html)

coverage of pitest-checks-whitespace was increased by 3%
current threshold: 98

### CODE REVIEW

**Comment by romani** [comment]
@Nimfadora , UTs are failing.

**Comment by romani** [comment]
if wercker fails , please rebase on our latest code

**Comment by romani** [comment]
@Nimfadora , please provide regression reports for checks (in their default configuration) that you updated.
https://github.com/checkstyle/contribution/tree/master/checkstyle-tester diff.groovy , please read README for usage instructions.

**Comment by Nimfadora** [comment]
@romani regression report is [here](https://nimfadora.github.io/diff5003/index.html)

**Pull request merged**
