### PR TITLE
Issue #13213: Remove "// ok" from onestatementperline

### PR DESCRIPTION
**Pull request by Lmh-java**
Part of Issue: #13213

1. Remove "// ok" comments from 6 classes under onestatementperline.
2. Remove corresponding suppress statements in config/checkstyle-input-suppressions.xml

### CODE REVIEW

**Review by MANISH-K-07 — COMMENTED** [review]
Everything lgtm....
Looks like you have already verified the build locally ;)
We encourage all new contributors to follow this to ease the review process

**Review by romani — APPROVED** [review]
Ok to merge if ci pass

**Comment by Lmh-java** [comment]
Hi, do you have an idea why CI is failing? Here is the last log before it fails


> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/usr/share/groovy/lib/groovy-2.4.21.jar) to method java.lang.Object.finalize()
> WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> New surviving mutation(s) found:
> 
> Source File: "OneStatementPerLineCheck.java"
> Class: "com.puppycrawl.tools.checkstyle.checks.coding.OneStatementPerLineCheck"
> Method: "beginTree"
> Line Contents: "lastVariableResourceStatementEnd = 0;"
> Mutator: "org.pitest.mutationtest.engine.gregor.mutators.experimental.MemberVariableMutator"
> Description: "Removed assignment to member variable lastVariableResourceStatementEnd"
> Line Number: 152

**Comment by MANISH-K-07** [comment]
Looks like there is one surviving mutation..
Needs to be dealt with

**Review by nrmancuso — APPROVED** [review]
Ok to merge once CI passes, I just approved github actions workflows to run. @Lmh-java thanks for your contribution!

**Comment by Lmh-java** [comment]
Hi, is it fine to keep references to the issue, since I am just completing part of the issue, and CI fails because of that.

**Review by romani — APPROVED** [review]
Ok to merge if ci pass

**Comment by nrmancuso** [comment]
Failure in Cirrus is not related to changes here.

**Pull request merged**
