### PR TITLE
Issue #2126: Improve code coverage for TokenTypesDoclet

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by mkordas** [comment]
@Vladlis, two initial comments:

1. Let's resolve compilation issue
2. Assertions like `@Test(expected = IllegalArgumentException.class)` should be used only if tested thing is one liner. Your test would pass right now, even if `IllegalArgumentException` was thrown from first line of your test.

**Comment by Vladlis** [comment]
@mkordas
1. Please look at build failures: java 7 requires one format of com.sun.tools.javadoc.JavadocTool.getRootDocImpl, whereas java 8 demands another. What should I do?
2. Is it better now? - [link](https://github.com/checkstyle/checkstyle/pull/2158/files#diff-c96508ecf9888bd5c3590a913a858ebfR98)

**Comment by mkordas** [comment]
@Vladlis, indeed, the signature has been changed:
Java 7: [http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/7u40-b43/com/sun/tools/javadoc/JavadocTool.java](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/7u40-b43/com/sun/tools/javadoc/JavadocTool.java#JavadocTool.getRootDocImpl%28java.lang.String%2Cjava.lang.String%2Ccom.sun.tools.javadoc.ModifierFilter%2Ccom.sun.tools.javac.util.List%2Ccom.sun.tools.javac.util.List%2Cboolean%2Ccom.sun.tools.javac.util.List%2Ccom.sun.tools.javac.util.List%2Cboolean%2Cboolean%2Cboolean%29)
Java 8: [http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/com/sun/tools/javadoc/JavadocTool.java#JavadocTool.getRootDocImpl%28java.lang.String%2Cjava.lang.String%2Ccom.sun.tools.javadoc.ModifierFilter%2Ccom.sun.tools.javac.util.List%2Ccom.sun.tools.javac.util.List%2Cjava.lang.Iterable%2Cboolean%2Ccom.sun.tools.javac.util.List%2Ccom.sun.tools.javac.util.List%2Cboolean%2Cboolean%2Cboolean%29)

We need to keep compatibility with both JDKs, so either we need to use reflection here, or avoid calling this method at all.

> Is it better now?

Yes, now is fine.

**Comment by Vladlis** [comment]
@mkordas, fixed

**Comment by mkordas** [comment]
1) Do we really need shared state between tests in `private static JavadocTool javadocTool;` and by using `@BeforeClass`? Generally tests should be as much independent as possible.
2) Let's be consistent and use static import for all assertions.
3) Same goes to `final` - let's use it everywhere or not at all. @romani, what's your opinion? Should all local variables be `final` in tests where possible?
4) `paramTypes.length == 12` - magic number, we need to assign it to constant.
5) `private static Method getMethod()` - can we choose some more descriptive name?
6) By looking at test
```java
@Test
public void testCheckOptions() {
    final Context context = new Context();
    Messager.preRegister(context, "");

    String[][] options = new String[3][1];
    Assert.assertFalse(TokenTypesDoclet.checkOptions(options, Messager.instance0(context)));

    options[0][0] = "-destfile";
    Assert.assertTrue(TokenTypesDoclet.checkOptions(options, Messager.instance0(context)));

    options[1][0] = "-destfile";
    Assert.assertFalse(TokenTypesDoclet.checkOptions(options, Messager.instance0(context)));
}
```
I have absolutely no idea what it does and checks. Can you make it more expressive? If not possible, maybe we need Javadoc here?
7) In `public void testFields()` we assert that exception is thrown. But why we expect exception there? Test name says only about testing fields.
8) What's the reason behind the contents of `InputTokenTypesDoclet.java`? Can it be some simpler file?

**Comment by Vladlis** [comment]
1) 
> Generally tests should be as much independent as possible

ok
2) done
3) ok
4) done
5) is it fine now?
6) added comments
7) there are five cases when fields are not acceptable:
- field is not static;
- field is not public;
- field is not final;
- field has type different from int;
- field lacks javadoc.

All of these cases are tested in this test and in the last case exception is thrown.
8) sure, it can, I've just copied it from actual TokenTypes :)

**Comment by mkordas** [comment]
Thanks @Vladlis 

1) 
>is it fine now?

I would change `getGetRootDocImplReflection` to `getMethodGetRootDocImplByReflection`
2) `assertEquals(2, TokenTypesDoclet.optionLength("-destfile")); assertEquals(0, TokenTypesDoclet.optionLength("-doclet"));` - can you explain in test why we expect `0` and `2` there?
3) `JAVA8_PARAMETERS_NUMBER` - I'd rather invert that if and make constant for Java 7. It's because Java 9 will stay probably the same as Java 8 :)
4) 
> there are five cases when fields are not acceptable

Please make those 5 cases somehow visible in unit test - maybe separate test with proper name for each case? Also, can you explain in test why we require them to be `public static final int` with Javadoc?

**Comment by romani** [comment]
> 3) Same goes to final - let's use it everywhere or not at all. @romani, what's your opinion? Should all local variables be final in tests where possible?

I am against polluting of code by extra modifiers, I am ok me skip modifier and non of the tools demand it.

> if (paramTypes.length == JAVA8_PARAMETERS_NUMBER) {

I do not like that approach, please check java version in runtime and avoid reflection If that is not possible due to compilation problem - so please keep reflection but please isolate code for different version in different blocks of IF-ELSE. That will be ease to refactor as we switch to java8 completely.

**Comment by romani** [comment]
please rebase

**Comment by Vladlis** [comment]
> I would change getGetRootDocImplReflection to getMethodGetRootDocImplByReflection

done
> ```assertEquals(2, TokenTypesDoclet.optionLength("-destfile")); assertEquals(0, TokenTypesDoclet.optionLength("-doclet"));``` - can you explain in test why we expect ```0``` and ```2``` there?

Explained in [comment]()

> please check java version in runtime

done
> Why coverages limits are not changed ?

fixed
> e --> expected

done
> Please make those 5 cases somehow visible in unit test

I guess that five separate tests would be redundant. I've met lots of cases in CheckStyle when similar inputs were tested in the same test. So let's group four cases together?

> Also, can you explain in test why we require them to be ```public static final int``` with Javadoc?

provided comments, please check whether I've got the reason right :)

**Comment by romani** [comment]
merged as FF.


problem at codecov is due to introduction of new file to coverage. Rest of fixes that mkordas would like to require could be applied to another PR of this issue.

**Pull request closed without merging**
