### PR TITLE
minor: fix conflicts between last 2 commits

### PR DESCRIPTION
**Pull request by rnveach**
This fixes a conflict between the last 2 commits because translation inputs were moved to a new folder.

### CODE REVIEW

**Comment by rnveach** [comment]
@romani 
> `[ERROR]   TranslationCheckTest.testLogOutput:190 Unexpected log output expected:<...ationCheckFireErrors[_de.properties">`
`<error line="0" severity="error" message="Key &apos;anotherKey&apos; missing." source="com.puppycrawl.tools.checkstyle.checks.TranslationCheck"/>`
`</file>`
`<file name="/home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/translation/InputTranslationCheckFireErrors.properties"]>`
`</file>`
`</checksty...> but was:<...ationCheckFireErrors[.properties">`
`</file>`
`<file name="/home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/translation/InputTranslationCheckFireErrors_de.properties">`
`<error line="0" severity="error" message="Key &apos;anotherKey&apos; missing." source="com.puppycrawl.tools.checkstyle.checks.TranslationCheck"/]>`
`</file>`
`</checksty...>`

I can't reproduce this locally but it is happening on windows and linux.

My current thought right now is the `HashSet` we are using in the check at https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java#L168 and https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java#L540 is causing the order of the files to be different when we move them to a different directory.

**Comment by rnveach** [comment]
I am trying changing the order of the files in the output XML files to see if it will pass.
Locally this fails for me.

**Comment by romani** [comment]
I merged it just unblock CI - make it green.
But if it fails for you, it mean it will fails for some others, it is better to continue to investigate.

**Comment by romani** [comment]
still fails on my side:
```
[ERROR] Failures: 
[ERROR]   TranslationCheckTest.testLogOutput:190 Unexpected log output expected:<...ationCheckFireErrors[.properties">
</file>
<file name="....checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/translation/InputTranslationCheckFireErrors_de.properties">
<error line="0" severity="error" message="Key &apos;anotherKey&apos; missing." source="com.puppycrawl.tools.checkstyle.checks.TranslationCheck"/]>
</file>
</checksty...> but was:<...ationCheckFireErrors[_de.properties">
<error line="0" severity="error" message="Key &apos;anotherKey&apos; missing." source="com.puppycrawl.tools.checkstyle.checks.TranslationCheck"/>
</file>
<file name="..../checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/translation/InputTranslationCheckFireErrors.properties"]>
</file>
</checksty...>
[INFO] 
```

**Pull request merged**
