### PR TITLE
StackOverflow in java.util.regex fixed #1221

### LINKED ISSUE #1221: StackOverflow at java.util.regex.*
java.util.regex.Matcher apparently has known issues which cause will cause StackOverflow for certain RegExps on certain input (Google it, there are various blog posts, JDK bug reports which are closed or non-action-ed). 

This "fact of live" (the JDK is not going to fix this) can cause Checkstyle to abruptly stop unexpectedly - without any indication as to which input file made it choke for what regexp (once you know that, you can use excludes or refine the regexps it seems).

Checkstyle should never fail that abruptly, and instead treat a StackOverflow at java.util.regex.* more gracefully.

I have a unit test illustrating this problem, and a PR with proposed fixes for this issue which I'll post in a minute.

PS: This bug can be confused with https://github.com/checkstyle/checkstyle/issues/48 (like I initially did), but is actually completely unrelated to that one, which is a StackOverflow in Checkstyle's own com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch code that uses recursion itself; this one is technically completely different - other than also being about a StackOverflow.

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
This PR currently fails due to formatting errors in my proposed code. I'm too lazy to interpret the output of the console and insert spaces to make it happy without being able to see the same in the IDE. I'm currently blocked :) from using the Eclipse Checkstyle Plugin due to https://github.com/checkstyle/checkstyle/issues/1224 ..

If you can confirm that you're willing to merge this, perhaps I'll adjust the formatting after all ;)

**Comment by romani** [comment]
ok, let me read fix with attention, it is not obvious fix....

**Comment by vorburger** [comment]
OK fixed those minor formatting problems for Checkstyle-on-checkstyle, and PR is now green.. merge?

**Comment by romani** [comment]
Thanks a lot for your detailed issue and fix .... very interesting issue.

few more minors, before merge:

1) 
> // TODO Use a 3rd-party 

please remove TODO, you can open issue instead.

2)
> // shit happens

please avoid bad words, that is not place for emotions

3)
> // now needs 10'000 or 100'000

please put that above a statement on separate line.

**Comment by romani** [comment]
release 6.8 will be in 4 days, it will be good to finish that PR before.

**Comment by vorburger** [comment]
implemented code review feedback

**Comment by romani** [comment]
please squash commits in one ans put at the end of commit message reference to github issue like (". #xxxxxxx")

**Comment by vorburger** [comment]
@romani  did you see I actually did do the squash 4 days ago? I was hoping you could merge this in time for 6.8 .. released yesterday, you missed to merge this one? Anything else holding you back from merging this?

**Comment by romani** [comment]
@vorburger , sorry I missed that, github did not notify about such changes, amount of posts did not change in PRs page so I did not take a look inside, preparation for 6.8 was busy ..... . Next time please do not hesitate to bother me with additional post to PR like "done".

I did gig regression in 6.8 release so I am going to do 6.8.1 - your changes will be included.

**Comment by romani** [comment]
merged

**Pull request closed without merging**
