### PR TITLE
Issue #2539: Fix RequireThis check false-positive on methods

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by romani** [comment]
@Vladlis , please prepare diff reports, there should be decrease of violations amount.

**Comment by romani** [comment]
@Vladlis , CI is failed at src/xdocs/config_coding.xml please fix. I will start review after CI become green.

**Comment by Vladlis** [comment]
Fixed.
I've made reports only against CS, SevNTU-CS and Guava, as the check produces really a lot of violations and reports are hard to compare. The reports show total decrease of violations, however some new violations have appeared, such as
```xml
<file name="/home/vlad/projects/contribution/checkstyle-tester/src/main/java/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/DetectorOptions.java">
<error line="142" column="13" severity="warning" message="Reference to instance variable &apos;reporter&apos; needs &quot;DetectorOptions.this.&quot;." source="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck"/>
<error line="153" column="13" severity="warning" message="Reference to instance variable &apos;compileFlags&apos; needs &quot;DetectorOptions.this.&quot;." source="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck"/>
<error line="163" column="13" severity="warning" message="Reference to instance variable &apos;format&apos; needs &quot;DetectorOptions.this.&quot;." source="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck"/>
<error line="173" column="13" severity="warning" message="Reference to instance variable &apos;message&apos; needs &quot;DetectorOptions.this.&quot;." source="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck"/>
<error line="183" column="13" severity="warning" message="Reference to instance variable &apos;minimum&apos; needs &quot;DetectorOptions.this.&quot;." source="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck"/>
<error line="193" column="13" severity="warning" message="Reference to instance variable &apos;maximum&apos; needs &quot;DetectorOptions.this.&quot;." source="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck"/>
<error line="203" column="13" severity="warning" message="Reference to instance variable &apos;ignoreCase&apos; needs &quot;DetectorOptions.this.&quot;." source="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck"/>
<error line="213" column="13" severity="warning" message="Reference to instance variable &apos;suppressor&apos; needs &quot;DetectorOptions.this.&quot;." source="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck"/>
<error line="222" column="13" severity="warning" message="Reference to instance variable &apos;message&apos; needs &quot;DetectorOptions.this.&quot;." source="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck"/>
<error line="222" column="49" severity="warning" message="Reference to instance variable &apos;message&apos; needs &quot;DetectorOptions.this.&quot;." source="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck"/>
<error line="223" column="13" severity="warning" message="Reference to instance variable &apos;suppressor&apos; needs &quot;DetectorOptions.this.&quot;." source="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck"/>
<error line="223" column="52" severity="warning" message="Reference to instance variable &apos;suppressor&apos; needs &quot;DetectorOptions.this.&quot;." source="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck"/>
</file>
```
I cannot say why exactly these violations were not spotted before, but they are correct.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
