### PR TITLE
Issue #13005: LineLength check documentation incorrectly shows how to…

### PR DESCRIPTION
**Pull request by Andromeda227799**
Fixing Issue #13005 by replacing TreeWalker with Checker

### CODE REVIEW

**Comment by Andromeda227799** [comment]
Hey @romani could you help me identify why the CI failed?

**Comment by romani** [comment]
please all commits in one. each PR should have only one commit.

**Comment by Andromeda227799** [comment]
> please all commits in one. each PR should have only one commit.
> 
> CI is restarted.

I have done that just now, CI is running, hopefully, it passes 🤞

**Review by romani — APPROVED** [review]
Ok to merge if CI is all green

**Comment by romani** [comment]
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=14426&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=815

Please make sure commit message was done as it was required.

**Comment by Andromeda227799** [comment]
@romani CI passed!

**Pull request merged**
