### PR TITLE
Issue #15340: created InputForamtted file for section 4.8.4.2 Fall through commented

### PR DESCRIPTION
**Pull request by Zopsss**
~~#15340~~ #15449

### CODE REVIEW

**Comment by rdiachenko** [comment]
> Check no closed issue references / check_issues

not related to this PR

> Google-Java-Format / test

@Zopsss please check, you didn't format everything in the file

**Comment by romani** [comment]
Formatter can no fix such violations as it is not clear what to do: comment or break.
Only author or code fix it.
So violations will stay.

**Comment by Zopsss** [comment]
> @Zopsss please check, you didn't format everything in the file

I formatted the code with version 1.23, it didn't seem to be changing indentation then I tried formatting with 1.22 and it changed the indentation according to diff given at: https://github.com/checkstyle/checkstyle/actions/runs/10632635950/job/29475989068?pr=15591

In CI it is mentioned that we're using version 1.23:

> Run ./.ci/google-java-format.sh .ci-temp/google-java-format-1.23.0-all-deps.jar

But the code is being formatted based on 1.22, don't know the reason behind what it causing it to do so.

**Comment by Zopsss** [comment]
> And ..... Why we can not simply make original import to be fully formatted ? And not deal with InputFormatted at all.

you mean for sections like this, there should be only formatted file, no need of original file?

**Comment by romani** [comment]
I mean, can we remove https://github.com/checkstyle/checkstyle/blob/5472ce3b3127d0c6f69bfa6b94978d1792667fe6/.ci/google-java-format.sh#L53 
and simply format `rule4842fallthrough/InputFallThrough.java`
and do not have `rule4842fallthrough/InputFormattedFallThrough.java`

**Comment by Zopsss** [comment]
> I mean, can we remove
> 
> https://github.com/checkstyle/checkstyle/blob/5472ce3b3127d0c6f69bfa6b94978d1792667fe6/.ci/google-java-format.sh#L53
> 
> 
> and simply format `rule4842fallthrough/InputFallThrough.java`
> and do not have `rule4842fallthrough/InputFormattedFallThrough.java`

done

**Comment by romani** [comment]
CI is red.
Please run formatter by CLI on your local

**Comment by Zopsss** [comment]
> CI is red. Please run formatter by CLI on your local

I used latest version of formatter ( 1.23 ) to format the code, the diff CI is giving: 

```diff
diff --git a/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java b/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java
index 05a2c79..6253523 100644
--- a/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java
+++ b/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java
@@ -147,7 +147,7 @@ public class InputFallThrough {
           break;
         case 2:
           i++;
-        // fallthru
+          // fallthru
         case 3:
           i++;
           break;
@@ -177,7 +177,7 @@ public class InputFallThrough {
           { // violation 'should be on the previous line'
             i++;
           }
-        // fallthru
+          // fallthru
         case 12:
           if (false) {
             break;
@@ -194,7 +194,7 @@ public class InputFallThrough {
           } else {
             // do nothing
           }
-        // fallthru
+          // fallthru
         case 15:
           do {
             System.identityHashCode("something");
@@ -213,7 +213,7 @@ public class InputFallThrough {
           while (cond) {
             break;
           }
-        // fallthru
+          // fallthru
         case 19:
           try {
             i++;
@@ -232,7 +232,7 @@ public class InputFallThrough {
           } catch (Error e) {
             return;
           }
-        // fallthru
+          // fallthru
         case 21:
           try {
             i++;
@@ -251,7 +251,7 @@ public class InputFallThrough {
           } finally {
             i++;
           }
-        /* fallthru */
+          /* fallthru */
         case 23:
           switch (j) {
             case 1:
@@ -263,7 +263,7 @@ public class InputFallThrough {
           }
         case 24:
           i++;
-        /* fallthru */ case 25:
+          /* fallthru */ case 25:
           i++;
           break;
 
@@ -276,7 +276,7 @@ public class InputFallThrough {
             default:
               return;
           }
-        // fallthru
+          // fallthru
         default:
           // this is the last label
           i++;
@@ -294,15 +294,15 @@ public class InputFallThrough {
 
         case 1:
           i++;
-        // fallthru
+          // fallthru
         case 2:
           { // violation 'should be on the previous line'
             i++;
           }
-        // fallthru
+          // fallthru
         case 3:
           i++;
-        /* fallthru */ case 4:
+          /* fallthru */ case 4:
           break;
         case 5:
           i++;
@@ -3[20](https://github.com/checkstyle/checkstyle/actions/runs/10646915320/job/29514297175?pr=15591#step:5:21),10 +320,10 @@ public class InputFallThrough {
 
         case 1:
           i++;
-        /* fallthru */
+          /* fallthru */
         case 2:
           i++;
-        /* fallthru */ case 3:
+          /* fallthru */ case 3:
           break;
         case 4:
           i++;
@@ -341,10 +341,10 @@ public class InputFallThrough {
 
         case 1:
           i++;
-        /*fallthru*/
+          /*fallthru*/
         case 2:
           i++;
-        /*fallthru*/ case 3:
+          /*fallthru*/ case 3:
           break;
         case 4:
           i++;
@@ -[36](https://github.com/checkstyle/checkstyle/actions/runs/10646915320/job/29514297175?pr=15591#step:5:37)2,10 +362,10 @@ public class InputFallThrough {
 
         case 1:
           i++;
-        /* falls through */
+          /* falls through */
         case 2:
           i++;
-        /* falls through */ case 3:
+          /* falls through */ case 3:
           break;
         case 4:
           i++;
@@ -[38](https://github.com/checkstyle/checkstyle/actions/runs/10646915320/job/29514297175?pr=15591#step:5:39)3,10 +383,10 @@ public class InputFallThrough {
 
         case 1: // violation 'Fall through from previous branch of the switch statement.'
           i++;
-        /* Continue with next case.  */
+          /* Continue with next case.  */
         case 2: // violation 'Fall through from previous branch of the switch statement.'
           i++;
-        /* Continue with next case. */ case 3:
+          /* Continue with next case. */ case 3:
           // violation above 'Fall through from previous branch of the switch statement.'
           break;
         case 4:
```

is based on previous version of formatter ( 1.22 ) 

in CI it is mentioned that we are using version 1.23:

```
Run ./.ci/google-java-format.sh .ci-temp/google-java-format-1.23.0-all-deps.jar
```

but the formatted code is of version 1.22, maybe something's wrong with our CI? @romani

**Comment by romani** [comment]
moved to https://github.com/checkstyle/checkstyle/pull/15603

**Pull request closed without merging**
