### PR TITLE
Issue #4401: increase coverage of pitest-checks-header profile to 100%

### PR DESCRIPTION
**Pull request by Nimfadora**
Issue #4401 

[pitest report before changes](https://nimfadora.github.io/issue4401.html)

### CODE REVIEW

**Comment by rnveach** [comment]
@Nimfadora Is this a true 100%? Does report say '79/79'?

**Comment by Nimfadora** [comment]
@rnveach yes it is 79/79

**Comment by rnveach** [comment]
Thanks for confirmation.

**Comment by romani** [comment]
@Nimfadora , thanks a lot for fix, but please focus on non-checks profiles first, all GSoC PRs are about non Check changes, we are about to start merging them.

**Pull request merged**
