### PR TITLE
Issue #13501: Kill mutation for DetailAstImpl-5

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13501: Kill mutation for DetailAstImpl-5

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java

-------

# Mutations 
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L3-L10

------------

# Explaination

https://github.com/checkstyle/checkstyle/blob/0dba32b6c8c29977d74af675078501fa8052c10f/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L50

This line is mutated. 

The reason of removal is whenever any node is created and set it as parent, child, nextSibling, previousSibling. every time the method is called https://github.com/checkstyle/checkstyle/blob/0dba32b6c8c29977d74af675078501fa8052c10f/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L443-L447
where childCount is assigned to `NOT_INITIALIZED`.  

--------------

# Regression 

Report-1 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/part3-report/index.html

Report-2 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/sevntu-check-regression_part_1-report/index.html

Report-3 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/checks-nonjavadoc-error-report/index.html

Report-4 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/sevntu-check-regression_part_2-report/index.html

Report-5 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/checks-only-javadoc-error-report/index.html

Report-6 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/part1-report/index.html

Report-7 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/part5-report/index.html

Report-8 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/part6-report/index.html

Report-9 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/part4-report/index.html

Report-10 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/antlr-report/index.html

Report-11 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/part2-report/index.html

Report-12 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/part3-report/index.html

Report-13 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/sevntu-check-regression_part_1-report/index.html

Report-14 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/checks-nonjavadoc-error-report/index.html

Report-15 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/sevntu-check-regression_part_2-report/index.html

Report-16 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/checks-only-javadoc-error-report/index.html

Report-17 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/part1-report/index.html

Report-18 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/part5-report/index.html

Report-19 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/part6-report/index.html

Report-20 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/part4-report/index.html

Report-21 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/antlr-report/index.html

Report-22 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/part2-report/index.html

### CODE REVIEW

**Comment by Kevin222004** [comment]
Diff found in 

Report-10 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/antlr-report/index.html

**Comment by Kevin222004** [comment]
Report-10 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/antlr-report/index.html

Report-21 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/antlr-report/index.html

@nrmancuso can you please tell me why report 10 has diff because both are the same report

**Comment by nrmancuso** [comment]
> Report-10 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-38-05/antlr-report/index.html
> 
> Report-21 :- https://kevin222004.github.io/reports/DetailAstImpl2/2023-08-27-T-21-51-36/antlr-report/index.html
> 
> @nrmancuso can you please tell me why report 10 has diff because both are the same report

Make sure to click through to the output file; both are stackoverflow, but from a different location. This is not a concern.

**Review by romani — APPROVED** [review]
Ok to merge

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by rdiachenko** [comment]
rebased

**Pull request merged**
