### PR TITLE
Adding "all" warning key in SuppressWarningsHolder

### PR DESCRIPTION
**Pull request by gallandarakhneorg**
Related to the issue #2275, this pull request provides the code for supporting the `"all"` argument to `@SuppressWarnings` annotations.

### CODE REVIEW

**Comment by romani** [comment]
Thanks a lot contribution.

please do this minor update, squash all in one commit.
I am ready to merge.

**Comment by gallandarakhneorg** [comment]
Do you explain me with the travais cli has failed? I do not find any clear error message in the travis log.

**Comment by rnveach** [comment]
@gallandarakhneorg 
https://travis-ci.org/checkstyle/checkstyle/jobs/84254441#L431
> fatal: unable to access 'http://github.com/apache/hbase/': Recv failure: Connection reset by peer

**Comment by romani** [comment]
Build item is relaunched

**Comment by gallandarakhneorg** [comment]
Thank you @romani. It was out of my control.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
