### PR TITLE
Issue #13809: kill mutation for AbstarctRootNode

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13809: kill mutation for AbstarctRootNode

## Mutation
https://github.com/checkstyle/checkstyle/blob/d316b893da935d33736e90321b909f9b72d835d8/config/pitest-suppressions/pitest-xpath-suppressions.xml#L3-L10

Attributes are not allowed by design:
https://github.com/checkstyle/checkstyle/blob/a7fa83a3de92486dd7033b45bc5364ca3eae9725/src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractRootNode.java#L73-L75

### CODE REVIEW

**Comment by Kevin222004** [comment]
I am not finding any query in which attribute axis is used as a root just like I created a test for an `ancestor-or-self` axis
https://github.com/checkstyle/checkstyle/pull/13771.

**Review by romani — APPROVED** [review]
No attributes on root.
Root is 
https://github.com/checkstyle/checkstyle/blob/a7fa83a3de92486dd7033b45bc5364ca3eae9725/src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java#L315-L317

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by rdiachenko** [comment]
rebased

**Comment by romani** [comment]
@Kevin222004 , please resolve conflict

**Pull request merged**
