### PR TITLE
Issue #1293: One more unit test for PackageDeclarationCheck

### PR DESCRIPTION
**Pull request by baratali**
coverage 100%

### CODE REVIEW

**Comment by baratali** [comment]
I don't know why Travis has failed. Can we relaunch it?

**Comment by MEZk** [comment]
@baratali 
It's Travis CI memory crash. Resend your last commit.

**Comment by baratali** [comment]
@MEZk, thanks

**Comment by MEZk** [comment]
@baratali, you are welcome. And it would be good to provide cobertura's coverage report to proof that code coverage for the check is 100%.

**Comment by rdiachenko** [comment]
@MEZk this change proofs that the code coverage for the check is 100%: https://github.com/checkstyle/checkstyle/pull/1334/files#diff-600376dffeb79835ede4a0b285078036L1118

```
- <regex><pattern>.*.checks.coding.PackageDeclarationCheck</pattern><branchRate>75</branchRate><lineRate>85</lineRate></regex>
```

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
