### PR TITLE
Issue #2161: unify test input locations

### PR DESCRIPTION
**Pull request by rnveach**
Are you ok with "TEST_LOCATION" or would you rather I override "getPath"?
One PR per test?

### CODE REVIEW

**Comment by romani** [comment]
yes, overridden getPath will looks more compact ,thanks for suggestion.

> One PR per test?

yes, it will be easy to verify changes. if changes are so obvious, you can do one PR with multiple commits.

**Comment by rnveach** [comment]
"getPath" override goes on the bottom of the class?

**Comment by romani** [comment]
please do to the top, bellow setUp and other overrides. It is small method, should not take a lot of space.

**Comment by romani** [comment]
in future PRs please make "getPath(String filename)"  signature as single line, not sure why it is two line in base class. One line signature is good.

**Comment by rnveach** [comment]
will do

**Pull request merged**
