### PR TITLE
Replace hardcoded message in WhitespaceAfterCheck with property value  (i18n), issue #967

### PR DESCRIPTION
**Pull request by MEZk**
@romani 
I replaced hardcoded message in WhitespaceAfterCheck (```message = new Object[]{"cast"}```) with property value ```ws.typeCast``` .
I also made internationalization  (i18n) for all supported languages in accordance with:
[eng] (https://en.wikipedia.org/wiki/Type_conversion)
[de] (https://de.wikipedia.org/wiki/Typumwandlung)
[es] (https://es.wikipedia.org/wiki/Conversi%C3%B3n_de_tipos)
[fi] (http://people.uta.fi/~jl/opk/muuttujat.html#muunnos)
[fr] (https://fr.wikipedia.org/wiki/Conversion_de_type)
[ja] (https://ja.wikipedia.org/wiki/%E5%9E%8B%E5%A4%89%E6%8F%9B)
[pt] (https://pt.wikipedia.org/wiki/Convers%C3%A3o_de_tipos)
[tr] (https://technet.microsoft.com/tr-tr/library/ms191530%28v=sql.110%29.aspx)

### CODE REVIEW

**Comment by romani** [comment]
please put as github comment final messages for typecast for all language. I hope you will notice mistake yourself.

**Comment by MEZk** [comment]
@romani 
Fixed.

**Comment by romani** [comment]
> please put as github comment final messages for typecast for all language. 

just do it. I do not see a fix.

**Comment by MEZk** [comment]
I deleted unnecessary ``` ' ' ``` 

eng: type cast. (typecast?)
de: typumwandlung.
es: conversión de tipos.
fi: tyypin muunnos.
fr: conversion de type.
ja: 型変換.
pr: conversão de tipos.
tr: türü dönüştürme.

Maybe I'm a bit inattentive)

**Comment by romani** [comment]
Please give me whole message, that will be printed to user. That message i do not understand.

**Comment by MEZk** [comment]
@romani 
I understood the problem. I also updated UT (testCast) for i18n. 

Now the messages are: 
```
eng: 88:21: 'typecast' is not followed by whitespace.
de: 88:21: Nach 'typumwandlung' folgt kein Leerzeichen.
es: 88:21: 'conversión de tipos' no está seguido de espacio en blanco.
fi: 88:21: 'tyypin muunnos' :ta ei edellä välilyönti.
fr: 88:21: Il manque une espace après 'conversion de type'.
ja: 88:21: '型変換' の後にホワイトスペースがありません。
pt: 88:21: 'conversão de tipos' não é seguido de espaço em branco.
tr: 88:21: 'türü dönüştürme' ifadesinden sonra boşluk kullanılmamış.
```

**Comment by romani** [comment]
looks good, please do squash of commits.

**Comment by MEZk** [comment]
@romani 
Done

**Comment by romani** [comment]
hmmm, I do not like that solution.....

Translation of a word is never works fine, as context is required.

Please redo changes to introduce new message variable there "cast" is written there as text, it is ok to have 80% similar messages.

**Comment by MEZk** [comment]
@romani 
Yes, it depends on context.
Do you suggest to leave the world 'cast' for all languages and just introduce new message variable (for example, ```ws.cast=cast```) in all property files for all languages?

**Comment by romani** [comment]
make  ws.typeCast the same as ws.notFollowed and put "cast" as part of message

if java code you just select whole message and do not do any concatenations or substitutions.

**Comment by romani** [comment]
release 6.8 will be in 4 days, it will be good to finish that PR before.

**Comment by MEZk** [comment]
@romani 
I made ws.typeCast the same as ws.notFollowed and put "cast" as part of message. I also tried to make refactoring to avoid additional if-else logic and code duplication.

Please, check my changes. 
Do you think that it is a good solution to implement a new method ```checkToken``` with som logic from ```visitToken```? I tried to shorten ```visitToken```.

````java
private void checkToken(DetailAST targetAST, String warningMessage, Object... message) {
        final String line = getLine(targetAST.getLineNo() - 1);
        final int after =
            targetAST.getColumnNo() + targetAST.getText().length();

        if (after < line.length()) {

            final char charAfter = line.charAt(after);
            if (targetAST.getType() == TokenTypes.SEMI
                && (charAfter == ';' || charAfter == ')')) {
                return;
            }
            if (!Character.isWhitespace(charAfter) && !isEmptyForIterator(targetAST)) {

                log(targetAST.getLineNo(),
                        targetAST.getColumnNo() + targetAST.getText().length(),
                        warningMessage,
                        message);
            }
        }
    }
````

 Is it a good idea to make warning message as a parameter of ```checkToken``` ?

**Comment by romani** [comment]
good step forward but not ideal.

1)
> visitToken(DetailAST ast) {

please move "final DetailAST targetAST;" inside IF block, as nobody need it outside of IF block.

2)
> private void checkToken(DetailAST targetAST, String warningMessage, Object... message)

there is mess in arguments, it is not clear how to use method , without reading it logic - sign of strange design.
Solution: move "log(...." out of it and make that method static.

**Comment by MEZk** [comment]
@romani 
1) Done. And I also moved 
```java
 final Object[] message
 ```
inside else block:

````java
 else {
            final Object[] message = new Object[]{ast.getText()};
            if (!isFollowedByWhitespace(ast)) {
                log(ast.getLineNo(),
                    ast.getColumnNo() + ast.getText().length(),
                    WS_NOT_FOLLOWED,
                    message);
            }
        }
````
because it is used only there.

2) I renamed checkToken on isFollowedByWhitespace and updated javadoc. Do you see any smells in it?

**Comment by romani** [comment]
1) 
please keep ref to issue in commits

2)
> final Object[] message = new Object[]{ast.getText()};

move it as close to usage as possible.

3)
> private boolean isFollowedByWhitespace(DetailAST targetAST) 

I asked you to make that function as static - please do - It will become much better then.

**Comment by MEZk** [comment]
@romani 
If a do isFollowedByWhitespace() as static, I can't use getLine() and isEmptyForIterator() inside, because they are not static and can't be referenced from static context. In this case It is necessary to change check logic in some way.

**Comment by romani** [comment]
:) yes, it is necessary to do refactoring, 2 min to do - move getLine() out of method and put String as parameter. Very straight forward refactoring.

**Comment by MEZk** [comment]
@romani 
1) Ok
2) Done
3) Done, I wanted to do something like this but in the same time I hoped to use as less parameters as possible.

**Comment by romani** [comment]
merged as FF.

> 3) Done, I wanted to do something like this but at the same time I hoped to use as less parameters as possible

optimizing arguments from 2 to 1 - doe snot make any sense. "Less arguments" is   when it come to 7 and more.
Please focus on minimizing fields in class, and !!reasonable!! usage of util methods (stateless) and design of your class we be much better.

**Pull request closed without merging**
