### PR TITLE
Issue #7876: Fix for ImportOrderCheck(6)

### PR DESCRIPTION
**Pull request by yajna-pandith**
Issue #7876: Fix for ImportOrderChec(6)

### CODE REVIEW

**Comment by yajna-pandith** [comment]
Diff I am generating

**Comment by rnveach** [comment]
@yajna-pandith You may have provided fix for the issue but you have not provided any of the requested reports in the main issue at https://github.com/checkstyle/checkstyle/issues/7797 . We asked to see every step of the way to ensure you know how to work with pitest for the future.

**Comment by yajna-pandith** [comment]
<https://github.com/yajna-pandith/yajna-pandith.github.io>
This repository contains the reports as requested in #7797 .

When tried to render html pages I am getting an error i am trying to resolve that.

**Comment by rnveach** [comment]
Your reports seem to be working fine. https://yajna-pandith.github.io/pit-reports/202003200105/

Please post the link to all the reports.

**Comment by yajna-pandith** [comment]
https://yajna-pandith.github.io/site-reports-7876/index.html 
Failsafe, surefire, jacoco, dsm, pmd and all the other reports are in the above link.

**Comment by romani** [comment]
>render html pages I am getting an error i am trying to resolve that.

Please share a link (gist GitHub.com) to all output from report generator we will help.

**Comment by rnveach** [comment]
@yajna-pandith ping

**Comment by romani** [comment]
@yajna-pandith , ping, please finish PR.

**Comment by romani** [comment]
PR is rebased on latest code, ok to merge ones CI pass.

**Pull request merged**
