### PR TITLE
Issue #6207: Add xpath regression test for AvoidInlineConditionals 

### PR DESCRIPTION
**Pull request by mincong-h**
This PR adds XPath regression test for suppression filter on [AvoidInlineConditionals](https://checkstyle.org/config_coding.html#AvoidInlineConditionals) check, see #6207. Also, fix related code snippets in documents.

### CODE REVIEW

**Comment by rnveach** [comment]
@mincong-h I recommend only 1 PR at a time until https://github.com/checkstyle/checkstyle/pull/6984 is merged. If either PRs opened are merged right now, the other will have to be redone to correct the change in the other.

**Comment by mincong-h** [comment]
> code is ok, but it is better to have two test methods and two inputs or at least more then one `warn` for suppression in one input.

I'm not aware other kinds of inputs for this check. For now, I added two more tests and inputs, based on the 3 expected warnings in `AvoidInlineConditionalsCheckTest`:

```java
        final String[] expected = {
            "32:29: " + getCheckMessage(MSG_KEY),
            "33:20: " + getCheckMessage(MSG_KEY),
            "46:34: " + getCheckMessage(MSG_KEY),
        };
        verify(checkConfig, getPath("InputAvoidInlineConditionals.java"), expected);
```

Please let me know if they are incorrect.

> second commit please name "doc: fix sample code of AvoidInlineConditionals to be compilable"
> it should not be related to issue you have.

Changed. Thanks!

> for future: such refacotring it is better to place in PR as first commit, in case of amendment in issue related commit, it will require less efforts for you.

:+1:

I changed the commits. The PR is ready to be reviewed again. :)

**Comment by mincong-h** [comment]
Sorry I missed one line in the assertion, which causes test failures in [build 17760](https://travis-ci.org/checkstyle/checkstyle/builds/574177772)... Fixed now:

```diff
         final String[] expectedViolation = {
-            "9:31: " + getCheckMessage(AvoidInlineConditionalsCheck.class,
+            "8:31: " + getCheckMessage(AvoidInlineConditionalsCheck.class,
                 AvoidInlineConditionalsCheck.MSG_KEY),
         };
```

**Comment by rnveach** [comment]
> it is better to have two test methods and two inputs or at least more then one warn for suppression in one input.

For regression, the rule so far had been 1 test per `log` call. If a check only had 1 `log` call, we usually only had 1 test.

**Comment by romani** [comment]
Ok, let's proceed with such rule. I will not ask for additional cases.
We can always extend tests later on if problem happen.
If Check updated with new log statement, we unlikely to remember to update xpath, but it is ok.

**Comment by romani** [comment]
@rnveach is over busy with other PRs, this PR is simple, 2 reviews is enough.

**Pull request merged**
