### PR TITLE
Coverage has been increased to 100% in CommentSuppressor. Issue #1010

### PR DESCRIPTION
**Pull request by sabaka**
Reports are identical:
http://sabaka.github.io/CommentSuppressor/master/checkstyle.html
http://sabaka.github.io/CommentSuppressor/checkstyle.html

### CODE REVIEW

**Comment by romani** [comment]
@sabaka , before PR always run "mvn clean verify" , do not waste your, Travis, my time.

**Comment by romani** [comment]
@sabaka , do you see that failure ?

**Comment by sabaka** [comment]
@romani yes, I do.
Have not found solution yet.

**Comment by romani** [comment]
Please change https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java#L53 to create that object at this line, setter should be removed.

**Comment by sabaka** [comment]
@romani it doesn't work. Checkstyle calls setIgnoreComments() before befinTree() and we get NPE.
But looks like I managed it.

**Pull request merged**
