### PR TITLE
Update AbstractFileSetCheck to use verifyWithInLineConfigParser

### PR DESCRIPTION
**Pull request by Rohanraj123**
Related : #11446

### CODE REVIEW

**Comment by Rohanraj123** [comment]
@romani I seek little help on this PR !. I debugged it but yet not found why moduleName is not being found. Need some help !

**Comment by romani** [comment]
Let's find example of modules that are under Checker.

https://checkstyle.org/checks/sizes/linelength.html#Parent_Module

https://github.com/checkstyle/checkstyle/blob/b2d758b1c7dba5870f698b4c4e3795f91aea32e0/src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthSimple.java#L2

So it works for some modules. Please debug Linelengh test to see how it gets loaded.

**Comment by piyush-1234** [comment]
Facing similar kind of issue, @Rohanraj123 I ll be on ur side to work on this issue.

**Comment by romani** [comment]
@piyush-1234, @Rohanraj123 here is fix for your problem
https://github.com/checkstyle/checkstyle/pull/14119/commits/a324bb8e888fb5c11a5e725907b0a646471bcd62

please continue.

**Comment by piyush-1234** [comment]
> @piyush-1234, @Rohanraj123 here is fix for your problem [a324bb8](https://github.com/checkstyle/checkstyle/commit/a324bb8e888fb5c11a5e725907b0a646471bcd62)
> 
> please continue.

Thanx @romani , for help, sorry I wasn't able to spend time on the issues from last 4days, as I am in some medical emergency, I ll be resume my work soon.

**Comment by Rohanraj123** [comment]
@romani Thankyou so much for your help !. I was adding same thing `"com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheckTest$ViolationFileSetCheck"`
it was just that I was adding `AbstractFileSetCheck` instead of `AbstractFileSetCheckTest`. Would love to contribute more on this issue...

**Comment by romani** [comment]
Please contribute more to same issue, as you did not remove reference to Test is exclusion in pom xml , it means more fixes are required.

**Pull request merged**
