### PR TITLE
Import Order Check, added option allows alphabetical grouping order in s...

### PR DESCRIPTION
**Pull request by alexkravin**
...tatic group, issue #12

According to #12 

Added option which lets to order static group of imports in alphabetical order if this group if grouped by <b>top</b> or <b>bottom</b> options.

Added UTs and inputs, updated docs.

### CODE REVIEW

**Comment by alexkravin** [comment]
The same coverage problem, but I've tested and it's ok

**Comment by romani** [comment]
that tool detect that after update coverage is decreased, that is not allowed any more. UT coverage should be improved after each bug fixing. I expect changes in pom.xml to bigger numbers on each bug fix.

**Comment by alexkravin** [comment]
Now everything is ok

**Comment by romani** [comment]
Chamges at pom fot this Check has to happen, as increase in performance or removal of line at all (if you did 100% coverage)

**Comment by alexkravin** [comment]
Updated pom.xml

**Comment by romani** [comment]
Please add test cases with static on demand imports and please let us know how eclipse and intelijIdeado that

**Comment by alexkravin** [comment]
Added corresponding test cases, eclipse sorts them in the same way as common.
Idea does the same except for putting <b>java</b> packages to the end of import's list, but it's configurable.

**Comment by romani** [comment]
merged as FF.

**Pull request closed without merging**
