### PR TITLE
Issue #4472: Fix EmptyBlockCheck NPE with annotation default keyword

### PR DESCRIPTION
**Pull request by soon**
Issue #4472 

---------

Diffs with `LITERAL_DEFAULT`: https://soon-checkstyle-diffs.github.io/issue-4472-npe/index.html

Diffs with default module properties: https://soon-checkstyle-diffs.github.io/issue-4472/index.html

### CODE REVIEW

**Comment by romani** [comment]
@soon , we need regression diff report on this fix. Please provide for all projects that we have in property file.

**Comment by soon** [comment]
Diffs with `LITERAL_DEFAULT`: https://soon-checkstyle-diffs.github.io/issue-4472-npe/index.html

Diffs with default module properties: https://soon-checkstyle-diffs.github.io/issue-4472/index.html

**Comment by rnveach** [comment]
> can new regression tool create for us such config ?

We are still working through default configuration. Even properties may not fully generate all possibilities and get most information from existing tests.

**Comment by rnveach** [comment]
@soon Can you confirm if any of differences are anything besides an NPE?

**Comment by soon** [comment]
@rnveach I looked through all reports and all diffs are because of NPE

**Comment by rnveach** [comment]
Thanks. I am good than.

**Pull request merged**
