### PR TITLE
Issue #3497: Split Guard class

### PR DESCRIPTION
**Pull request by jochenvdv**
Issue #3497  

This is a work in progress.

I have decided to use an abstract base class anyway, because I feel without one the code wasn't clean.
For your convenience I made all changes in logically separated commits (will squash later).
All unit tests, coverage and style checks pass locally.
Please let me know if anything should be done differently (I am only just learning Java).

Things that possibly still need to be done (should this maybe be a separate PR?):

- [ ] Rename `PkgControl` to `ImportControl`
- [ ] Refactor tests for `PkgControl`:
    - [ ] Rename and reorganize test files (are separate files really needed for one class being tested?)
    - [ ] Add tests that use ClassImportRule (it is covered by already by `ImportControlCheckTest` though)
- [ ] Double-check if all documentation is using the new names

### CODE REVIEW

**Comment by romani** [comment]
thanks a lot, code looks good, please squash all in one commit and I will merge it.

**Comment by romani** [comment]
> Rename PkgControl to ImportControl

ok to change. could be in separate PR if that is easy for you.

> are separate files really needed for one class being tested?

We prefer testing by functional tests (base on real input files + real config). We use pure UTs only if that is close to impossible to do that by real input file and config.

> Refactor tests for PkgControl

please provide proposals.

> Double-check if all documentation is using the new names

Classes that you change are not public and visible to user. Only Check properties are public, all other internal classes are not visible to user. All our documentation is located at javadocs and files for maven site - https://github.com/checkstyle/checkstyle/tree/master/src/xdocs

**Comment by jochenvdv** [comment]
@romani I have squashed my commits. It seems the CircleCI build failed because of something unrelated.

I decided to keep this PR as is and maybe do the other stuff later in a separate PR.

**Comment by romani** [comment]
yes, problem is related to our recent changes, I did some changes in configuration and relaunched your build, I will see how it finish.

**Comment by romani** [comment]
CI is passed, thanks a lot for contribution.
For other changes please create separate issue(s) or send PRs with commit that have in message prefix "minor:"

**Pull request merged**
