### PR TITLE
extention for SingleJavadocLine, #1063

### PR DESCRIPTION
**Pull request by Vladlis**
I'll provide a tester report later.
So far, I've successfully tested the Check on checkstyle, sevntu-checkstyle and guava projects.

### CODE REVIEW

**Comment by Vladlis** [comment]
Something wrong with travis again?

**Comment by romani** [comment]
no, read failure message - coverage should not decrease

```
[ERROR] com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocUtils failed coverage check. Branch coverage rate of 66.6% is below 83.0%
[ERROR] com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocUtils failed coverage check. Line coverage rate of 80.6% is below 91.0%
```

**Comment by Vladlis** [comment]
@romani, I see, but I've made no changes in the files related to this failure. In addition, it has passed on jdk7

**Comment by romani** [comment]
Please generate html report before and after your change and share on github.io

**Comment by romani** [comment]
reports are still required ..... meanwhile .....

1)
> &lt;module name=&quot;ThrowsCount&quot;&gt;

please generate html of your javadoc and read it

2)
> ignoreTags

typo in name,

3)
> new ArrayList<String>();

use diamond operator

4)
> Collections.addAll(ignoredTags, tags.split(", "));

Please let me know from there you grab that code ? 
Correct way to do this is https://github.com/checkstyle/checkstyle/commit/835a5700d8d70436b198c80aba63f843da0b4dab#diff-01491bb8516b661ce590f3bc79015eedR235
please open an issue to resolve that also in place from where you copied that approach.

5)
>  Checks if comment has in-line tags tags which are not ignored.

"tags tags", please fix. Please also put in Javadoc link where developer could read about difference from javadoc tag and javadoc inline tag. I do not remember that difference now.

**Comment by romani** [comment]
I do not see your comments on each of my point

**Comment by Vladlis** [comment]
@romani,
1) Done
2) Done
3) Done, but why? Good coding style?
4) Done
5) Done

**Comment by Vladlis** [comment]
@romani, just was distracted by your e-mail for a minute

**Comment by Vladlis** [comment]
@romani 
also the failure caused by cobertura previously was connected with my changes: the method JavadocUtils.branchContains() is not used anymore, which led to reduction of coverage.
I restored the coverage by an additional UT in JavadocUtilsTest.

**Comment by romani** [comment]
1)
> Done, but why? Good coding style?

Because it is just simplification of format, without any reducing of information.

2)
> final String[] sTags = tags.split(", ");

do split by "," as I pointed in a link.

3)
>
```
 final List<String> ignoredTags = new ArrayList<>();
 final String[] sTags = tags.split(", ");
 for (int i = 0; i < sTags.length; i++) {
 sTags[i] = sTags[i].trim();
 }
 Collections.addAll(ignoredTags, sTags);
```

what for you need Array ? can you store directly to collection ?

4)
> 5) Done

I need link to some oracle.com where described definition of that terms, I still do not see how to distinguish tag and inline tag. That http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.html#JAVADOC_INLINE_TAG does not describe a difference.

**Comment by Vladlis** [comment]
1) OK
2) Done
3) you mean this like?
> final List<String> ignoredTags = new ArrayList<>();
        final String[] sTags = tags.split(",");
        for (int i = 0; i < sTags.length; i++) {
            ignoredTags.add(sTags[i].trim());
        }
        this.ignoredTags = ignoredTags;

By the way, why don't add directly to 
> this.ignoredTags

4)Done

**Comment by Vladlis** [comment]
reports:
http://vladlis.github.io/hibernate.spring.lombok.pmd/
http://vladlis.github.io/openjdk/
http://vladlis.github.io/guava/
http://vladlis.github.io/checkstyles/
http://vladlis.github.io/therest/

**Comment by romani** [comment]
> By the way, why don't add directly to 

Because public method of Check is used from outside of Check to configure it from XML file, we can not create in XML sequence of methods calls, so one option should be set by one human friendly string value.

**Comment by Vladlis** [comment]
@romani 
I mean, why firstly parsed attribute is added to the local List
https://github.com/checkstyle/checkstyle/commit/835a5700d8d70436b198c80aba63f843da0b4dab#diff-01491bb8516b661ce590f3bc79015eedR240
and then the reference is copied to the global List?
https://github.com/checkstyle/checkstyle/commit/835a5700d8d70436b198c80aba63f843da0b4dab#diff-01491bb8516b661ce590f3bc79015eedR240
Why do not add parsed value directly to the global List?

**Comment by romani** [comment]
1) 
> private boolean hasJavadocInlineTags(DetailNode javadocRoot)

can you refactor this method somehow ? it is too difficult to read, too much checks for NULL. Did you cover it 100% in UTs ?
Distance from definition of hasNotIgnoredTag and first usage is too big.

2)
> return javadocTagSection != null
&& !ignoredTags.contains(JavadocUtils.getFirstChild(javadocTagSection).getText()

expression is too long, hard to read, please move "!ignoredTags.contains(javadocTagSection.getText())" to special method , you already can use it in 3 places.

3) Please confirm that coverage for new lines of code is 100%.

**Comment by romani** [comment]
> I mean, why firstly parsed attribute is added to the local List
and then the reference is copied to the global List?
Why do not add parsed value directly to the global List?

I do not understand your questions, please find me in chat room.

**Comment by romani** [comment]
Please confirm that before your fix and after there is no differenes, that Check is used in Google config so guava project should not be affected.

Please launch https://github.com/checkstyle/google-style-config-test to verify that google will not be affected.

Looks like in your reports you launched Check in default mode, so please confirm that there is no difference in reports before and after fix. Please run your check in non default mode on some projects and compare reports, to be sure that it skip only cases that you instructed him in config.

**Comment by Vladlis** [comment]
Thanks to @romani I've understood, that 
1) adding directly to the global list (this.ignoredTags) is also acceptable, however, if this list had had default value, then it must have been cleared
2) the existing code has better readability 
3) the expected number of elements is small, so with no harsh memory limitations we should not be bothered by an additional local collection. In addition, the default value will be deleted by GC even faster.

**Comment by Vladlis** [comment]
@romani 
1) Done
2) Done
3) There is no line in in pom.xml, which specifies the coverage of the check below 100%. However I've also published a cobertura report on http://vladlis.github.io/

So far I've tested it on guava only (http://vladlis.github.io/). I'll do the rest a bit later.

**Comment by romani** [comment]
thanks for coverage.

Rest of report is almost useless.
Please speak with @MEZk about what is a role of report in our development process. if after discussion you still do not understand what report should be done - please give me a call.

**Comment by Vladlis** [comment]
@romani, OK
also, google-style-config-test runs with successfully on both default and non-default config of the Check

**Comment by romani** [comment]
1) 
> ```<b>ignoredTags</b> ```

please add some text above to explain what is it

2) 
>  private boolean hasJavadocTags(DetailNode javadocRoot) {

please add to javadoc some note that custom tags will also processed by such method. Please add UT for custom tag ignorance.

3)
> isTagNotIgnored 

method should be named in positive naming patterns (refactor to avoid "Not")

4)
> private boolean hasJavadocTags(DetailNode javadocRoot) {

it is not clear why you check only for first tag . Please create UT where first tag is in ignore list and second tag is not.

5)
> ```
+ while (!hasNotIgnoredTag && javadocTagSection != null) {
+ if (javadocTagSection.getType() == JavadocTokenTypes.JAVADOC_INLINE_TAG) {
+ hasNotIgnoredTag = isTagNotIgnored(javadocTagSection);
+ }
+ javadocTagSection = JavadocUtils.getNextSibling(javadocTagSection);
+ }
```

can it be done as util method by search of next sibling token by certain type ? getNExtSibling(ast, JavadocTokenTypes.JAVADOC_INLINE_TAG)

> 
```
private boolean isTagNotIgnored(DetailNode javadocTagSection) {
...
    isTagNotIgnored = !ignoredTags.contains(javadocTag);
```

please remove negative from name.
Please refactor a method to have have addtitional method getTagName() .

**Comment by romani** [comment]
please do not forget to update IT at https://github.com/checkstyle/checkstyle/tree/master/src/it for that Check/Style Rule

**Comment by Vladlis** [comment]
1) Done
2) Done
3) Done
4) Explained in javadoc for this method: block at-clauses can be identified only at the beginning of a line
5) Done

Also, updated IT, as now "@inheritDoc" is ignored by default, which is not allowed by google java style, but is widely used in, for instance, openjdk7. You can see reports here: http://vladlis.github.io/
I am not sure about making "@see" ignored by default and am going to investigate usage of {@link} and {@code}.

**Comment by romani** [comment]
good !!! you are in one step from completion.

0) I reviewed all you reports and now it is clear that people are ok with inline-tags in singleline javadoc. Please add additional boolean option "ignoreInlineTags" with TRUE by default.
In google config it should be "false" till they fix their style guide (I think then mean that, but document has to updated first).

1)
> InputSingleLineJavadocCheck.java

please add more test with HTML tags and text before and after at-clauses

----------

SingleLineJavadocCheck.java

2)
> author baratali

please add yourself

3)
> DEFAULT_IGNORED_TAGS

we can not change a behaviour of google config. All javadoctokens should be violated till they chnage a Style guide.

4)
> +// JavadocTreePrinter.printTree(ast);

please remove old code

5)
>isSingleLineJavadoc()

please make it isSingleLineJavadoc(getBlockCommentAst()) , because it unclear why you in allother parts examine ast but in that method do not.

6) 
> hasJavadocInlineTags  .... return hasNotIgnoredTag;

Please try to avoid "Not" as much as possible at any names! Avoid negative names as much as possible !!!!! Please refactor.
Hint: please use word "found" and "break;" statement.

7)
> hasNotIgnoredTag = !isTagIgnored(javadocTagSection);
	javadocTagSection = JavadocUtils.getNextSibling(
	 javadocTagSection, JavadocTokenTypes.JAVADOC_INLINE_TAG);

related to "6", ask yourself why you need to calculate javadocTagSection is hasNotIgnoredTag become "true" ? avoid extra calculation - it is good sign of bad method design.

**Comment by Vladlis** [comment]
0) Done
1) Done
2) Done :)
3) Got rid of this constant
4) Done
5) Done
6) Done
7) Done

**Comment by romani** [comment]
please provide new reports , as that is the only way to recheck correctness of your Check.

**Comment by romani** [comment]
1) 
google_checks.xml

as you shift down lines in that file, please update all lines like https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/google_style.xml#L121 to point to actual line in config.
Example: http://checkstyle.sourceforge.net/google_style.html
to build site "mvn clean site -Dlinkcheck.skip=true"

2) please provide new reports , as that is the only way to recheck correctness of your Check.
the main reports against guava before and after your fixes - there should be no changes.

3) 
> private boolean isSingleLineJavadoc(DetailAST blockCommentStart) {

if method do not use any class members, what modifier is better to place on it ?

4) > hasJavadocInlineTags

has Javadoc Inline Tags ?  ==> is NOT Ignored Tag  ==> has Forbidden Tag 

you ask for search just tag, what does forbidden mean in that context ? what for add one more term  for a tag

5) > !isTagIgnored(javadocTagSection)

move it inside of expression of IF.

**Comment by Vladlis** [comment]
1) Done
2) Done: http://vladlis.github.io/
3) this ain't even my method) Fixed
4) Ran out of ideas, hope that foundUnignoredTag is suitable, it does not contain "not" and is not a new term
5) Done

**Comment by romani** [comment]
> Ran out of ideas, hope that foundUnignoredTag is suitable, it does not contain "not" and is not a new term

as give you hint before, just use "found".

**Comment by romani** [comment]
1) > Done: http://vladlis.github.io/

Looks very good, we are on right way to do that validation.

2) please final rename of variable and I am ready to do a merge.

Thanks a lot !!!

**Comment by Vladlis** [comment]
2) Done

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
