### PR TITLE
Issue #15763: fixed paragraph tag placement in some files

### PR DESCRIPTION
**Pull request by Zopsss**
part of #15763

### CODE REVIEW

**Comment by Zopsss** [comment]
not sure why build is failing

**Comment by romani** [comment]
I pushed commit.
https://github.com/checkstyle/checkstyle/pull/15737/files#diff-6d25a0aded27563391601304bd93333e6d7cad4b30497b8cc5796fe7453abe01L13

you need to change xdoc template file to make same removal of tags.

**Comment by romani** [comment]
Please change commit to reference https://github.com/checkstyle/checkstyle/issues/15763

Lets proceed with updates.

If you have problems to understand how to upgrade, let's create PR for single Check update first, and then start updating more Checks.

**Comment by romani** [comment]
@Zopsss , please proceed with this issue , while you blocked by other

**Review by romani — APPROVED** [review]
ok to merge if CI pass.

thanks a lot for update !!!

**Pull request merged**
