### PR TITLE
minor: remove unnecessary pmd suppressions

### PR DESCRIPTION
**Pull request by rnveach**
Removed unnecessary PMD suppressions.

### CODE REVIEW

**Comment by romani** [comment]
@rnveach , please rebase to fix Travis

as Travis pass, ok to merge.
how did you found such unnecessary suppressions ?

**Comment by rnveach** [comment]
> how did you found such unnecessary suppressions ?

Manually removing the suppressions and seeing what violations came up and which weren't in the original suppression list. Not guaranteed I missed one.

**Comment by rnveach** [comment]
Travis:
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheckTest$JavadocCatchCheck:481 Rule:JUnitAssertionsShouldIncludeMessage Priority:3 JUnit assertions should include a message.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheckTest$JavadocCatchCheck:484 Rule:JUnitAssertionsShouldIncludeMessage Priority:3 JUnit assertions should include a message.

Weird appveyor doesn't report these.

**Comment by rnveach** [comment]
> Couldn't determine a download url for 11-GPL on linux-x64
The command "~/bin/install-jdk.sh --target "/home/travis/openjdk11" --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "GPL" --cacerts" failed and exited with 1 during .

I tried restarting and got this twice.

**Comment by daniilyar** [comment]
Jenkins, test this please

**Comment by pbludov** [comment]
JDK11 build was broken after fixing JDK12 build:
https://travis-ci.community/t/install-of-openjdk11-is-failing-again/3061

**Comment by rnveach** [comment]
CI passed so I hope they fixed it.

**Pull request merged**
