### PR TITLE
Issue#7687 : update doc for ImportOrder

### PR DESCRIPTION
**Pull request by aryaniiit002**
Update doc for ImportOrder
"module name="ImportOrder"/> and java code example are added"

I tried to do everything as per rules, let me know my mistakes so that i can improve for next time

### CODE REVIEW

**Review by Vyom-Yadav — COMMENTED** [review]
please attentively read all in #7687  and all pages in links.
Please take a look at examples PRs and do the same.
make sure "mvn verify" ,in you terminal pass without errors, and send PR only after this.
Read attentively error messages from all failing tools and follow them.

**Comment by aryaniiit002** [comment]
> please attentively read all in #7687 and all pages in links.
> Please take a look at examples PRs and do the same.
> make sure "mvn verify" ,in you terminal pass without errors, and send PR only after this.
> Read attentively error messages from all failing tools and follow them.
> Also please rebase your branch on most latest our master

**Comment by aryaniiit002** [comment]
I think i did something wrong....I closed my PR

**Comment by Vyom-Yadav** [comment]
You deleted your branch so your PR closed

**Comment by aryaniiit002** [comment]
But i am still getting Delete Branch option just below your comment...
and i didn't do mvn clean verify may be that's why i failed......

**Comment by Vyom-Yadav** [comment]
@aryaniiit002 ping me on gitter if you face any problems.

**Pull request closed without merging**
