### PR TITLE
Issue #5060: activate org.eclipse.jdt.core.compiler.problem.unnecessaryElse

### PR DESCRIPTION
**Pull request by romani**
Issue #5060

Discussion point https://github.com/checkstyle/checkstyle/issues/5060#issuecomment-536335043

### CODE REVIEW

**Comment by romani** [comment]
```
1. ERROR in /home/travis/build/checkstyle/checkstyle/src/main/java/
com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java (at line 606)
  else {
      final int ruleIndex = ex.getCtx().getRuleIndex();
      final String ruleName = recognizer.getRuleNames()[ruleIndex];
      final String upperCaseRuleName = 
                  convertUpperCamelToUpperUnderscore(ruleName);
      errorMessage = new ParseErrorMessage(lineNumber,
              MSG_JAVADOC_PARSE_RULE_ERROR, charPositionInLine
               , msg, upperCaseRuleName);
  }

Statement unnecessarily nested within else clause. 
The corresponding then clause does not complete normally
----------
----------
2. ERROR in /home/travis/build/checkstyle/checkstyle/src/main/java/
com/puppycrawl/tools/checkstyle/SuppressionsStringPrinter.java (at line 76)
  else {
            final String exceptionMsg = String.format(Locale.ROOT,
                    "%s does not match valid format 'line:column'.",
                    suppressionLineColumnNumber);
            throw new IllegalStateException(exceptionMsg);
        }

Statement unnecessarily nested within else clause. 
The corresponding then clause does not complete normally
----------
----------
3. ERROR in /home/travis/build/checkstyle/checkstyle/src/main/java/
com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java (at line 245)
  else {
                result.append(text);
            }

Statement unnecessarily nested within else clause. 
The corresponding then clause does not complete normally
```

**Comment by romani** [comment]
1. https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java#L593-L614
2. https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/SuppressionsStringPrinter.java#L63-L82
3. https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java#L229-L250

**Comment by romani** [comment]
from web:
Unnecessary 'else' statement
When enabled, the compiler will issue an error or a warning  whenever it encounters an unnecessary else statement (e.g. 
```
if  (condition) 
  return; 
else 
  doSomething();
```
).
Expected code 
```
if  (condition) 
  return; 
doSomething();
```

Looks reasonable. I am voting to activate this validation.
@rnveach  and @pbludov , please vote.

**Comment by rnveach** [comment]
I am fine in adding this new check.

I personally did not enable this check in my own project. Some things it put errors on I thought weren't so bad as an if-else like if both terminate in different ways but there were others where I did agree with it. I never looked into more to see what I think my requirements were to maybe look into my own check.

**Comment by pbludov** [comment]
We do not use `return` statement in the middle of the method, right?
As for expressions like
```
if (condition) {
  foo();
  break;
}
else {
  bar();
}
```
I think that the version without `else` is easier to read.

**Pull request merged**
