### PR TITLE
config: upgrade pitest to 1.4.7

### PR DESCRIPTION
**Pull request by rnveach**

### CODE REVIEW

**Comment by rnveach** [comment]
pitest failure in `./.ci/pitest.sh pitest-api`
> 2 tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
> `<[LITERAL_ASSERT, LITERAL_SUPER, ENUM_CONSTANT_DEF, TYPE_UPPER_BOUNDS, TYPE_PARAMETERS, NUM_DOUBLE, ANNOTATIONS, LITERAL_SWITCH, LITERAL_PROTECTED, LITERAL_SHORT, FOR_CONDITION, MINUS, LITERAL_LONG, FOR_INIT, OBJBLOCK, LITERAL_NULL, ANNOTATION, COMMENT_CONTENT, LITERAL_TRUE, LITERAL_CHAR, BLOCK_COMMENT_END, ANNOTATION_FIELD_DEF, POST_DEC, PARAMETER_DEF, TYPE, LITERAL_INT, BSR, ENUM, LABELED_STAT, ANNOTATION_MEMBER_VALUE_PAIR, TYPECAST, PLUS_ASSIGN, LITERAL_SYNCHRONIZED, LPAREN, DOT, LITERAL_CATCH, LITERAL_IF, BAND, INTERFACE_DEF, BNOT, LOR, METHOD_CALL, AT, ELLIPSIS, ARRAY_INIT, FOR_EACH_CLAUSE, LITERAL_THROWS, CHAR_LITERAL, CASE_GROUP, POST_INC, SEMI, LITERAL_FINALLY, ASSIGN, RESOURCE_SPECIFICATION, GENERIC_START, STATIC_IMPORT, IMPORT, SL, VARIABLE_DEF, LITERAL_DOUBLE, RCURLY, SR, RESOURCE, COMMA, BAND_ASSIGN, METHOD_DEF, LITERAL_VOID, NUM_LONG, LITERAL_TRANSIENT, $$pitCoverageProbeSize, LITERAL_THIS, LCURLY, MINUS_ASSIGN, TYPE_LOWER_BOUNDS, TYPE_ARGUMENT, LITERAL_CLASS, INSTANCE_INIT, DIV, LITERAL_VOLATILE, STAR, UNARY_MINUS, FOR_ITERATOR, NOT_EQUAL, LE, LITERAL_INTERFACE, LITERAL_FLOAT, LITERAL_INSTANCEOF, LT, BOR_ASSIGN, SL_ASSIGN, ELIST, ANNOTATION_ARRAY_INIT, MODIFIERS, LITERAL_BREAK, TYPE_PARAMETER, EXTENDS_CLAUSE, LITERAL_DEFAULT, STATIC_INIT, BSR_ASSIGN, TYPE_EXTENSION_AND, BOR, LITERAL_THROW, LITERAL_PRIVATE, BXOR, LITERAL_BYTE, WILDCARD_TYPE, FINAL, RPAREN, PARAMETERS, SR_ASSIGN, LITERAL_STATIC, EMPTY_STAT, UNARY_PLUS, LAMBDA, STAR_ASSIGN, LITERAL_CONTINUE, BXOR_ASSIGN, RBRACK, CTOR_CALL, LITERAL_FALSE, DO_WHILE, LITERAL_PUBLIC, LITERAL_WHILE, INC, PLUS, GENERIC_END, CTOR_DEF, DIV_ASSIGN, LNOT, SLIST, LAND, LITERAL_ELSE, STRICTFP, ABSTRACT, QUESTION, LITERAL_NEW, SINGLE_LINE_COMMENT, LITERAL_RETURN, EXPR, INDEX_OP, BLOCK_COMMENT_BEGIN, PACKAGE_DEF, NUM_FLOAT, IMPLEMENTS_CLAUSE, LITERAL_DO, EOF, GE, RESOURCES, DEC, MOD, EQUAL, LITERAL_BOOLEAN, CLASS_DEF, LITERAL_TRY, COLON, ENUM_DEF, ANNOTATION_DEF, NUM_INT, GT, LITERAL_NATIVE, METHOD_REF, TYPE_ARGUMENTS, DOUBLE_COLON, MOD_ASSIGN, IDENT, LITERAL_FOR, SUPER_CTOR_CALL, STRING_LITERAL, ARRAY_DECLARATOR, LITERAL_CASE]>
 but was:  <[LITERAL_ASSERT, LITERAL_SUPER, ENUM_CONSTANT_DEF, TYPE_UPPER_BOUNDS, TYPE_PARAMETERS, NUM_DOUBLE, ANNOTATIONS, LITERAL_SWITCH, LITERAL_PROTECTED, LITERAL_SHORT, FOR_CONDITION, MINUS, LITERAL_LONG, FOR_INIT, OBJBLOCK, LITERAL_NULL, ANNOTATION, LITERAL_TRUE, COMMENT_CONTENT, LITERAL_CHAR, POST_DEC, ANNOTATION_FIELD_DEF, PARAMETER_DEF, BLOCK_COMMENT_END, TYPE, LITERAL_INT, BSR, ENUM, LABELED_STAT, ANNOTATION_MEMBER_VALUE_PAIR, TYPECAST, LITERAL_SYNCHRONIZED, PLUS_ASSIGN, LPAREN, DOT, LITERAL_CATCH, LITERAL_IF, BAND, INTERFACE_DEF, LOR, BNOT, METHOD_CALL, AT, ELLIPSIS, ARRAY_INIT, FOR_EACH_CLAUSE, LITERAL_THROWS, CHAR_LITERAL, CASE_GROUP, POST_INC, SEMI, LITERAL_FINALLY, ASSIGN, RESOURCE_SPECIFICATION, STATIC_IMPORT, GENERIC_START, IMPORT, SL, VARIABLE_DEF, LITERAL_DOUBLE, RCURLY, SR, RESOURCE, COMMA, BAND_ASSIGN, METHOD_DEF, LITERAL_VOID, NUM_LONG, LITERAL_TRANSIENT, LITERAL_THIS, LCURLY, MINUS_ASSIGN, TYPE_LOWER_BOUNDS, TYPE_ARGUMENT, LITERAL_CLASS, INSTANCE_INIT, DIV, LITERAL_VOLATILE, STAR, UNARY_MINUS, FOR_ITERATOR, NOT_EQUAL, LE, LITERAL_INTERFACE, LITERAL_FLOAT, LITERAL_INSTANCEOF, BOR_ASSIGN, LT, SL_ASSIGN, ELIST, ANNOTATION_ARRAY_INIT, MODIFIERS, LITERAL_BREAK, EXTENDS_CLAUSE, TYPE_PARAMETER, LITERAL_DEFAULT, STATIC_INIT, BSR_ASSIGN, TYPE_EXTENSION_AND, BOR, LITERAL_THROW, LITERAL_PRIVATE, LITERAL_BYTE, BXOR, WILDCARD_TYPE, FINAL, RPAREN, PARAMETERS, SR_ASSIGN, EMPTY_STAT, UNARY_PLUS, LITERAL_STATIC, LITERAL_CONTINUE, LAMBDA, STAR_ASSIGN, BXOR_ASSIGN, RBRACK, CTOR_CALL, LITERAL_FALSE, DO_WHILE, LITERAL_PUBLIC, LITERAL_WHILE, INC, PLUS, GENERIC_END, CTOR_DEF, DIV_ASSIGN, LNOT, SLIST, LAND, LITERAL_ELSE, STRICTFP, ABSTRACT, QUESTION, LITERAL_NEW, SINGLE_LINE_COMMENT, LITERAL_RETURN, INDEX_OP, EXPR, BLOCK_COMMENT_BEGIN, PACKAGE_DEF, IMPLEMENTS_CLAUSE, NUM_FLOAT, LITERAL_DO, EOF, GE, RESOURCES, MOD, DEC, EQUAL, LITERAL_BOOLEAN, CLASS_DEF, LITERAL_TRY, COLON, ENUM_DEF, GT, NUM_INT, ANNOTATION_DEF, LITERAL_NATIVE, METHOD_REF, TYPE_ARGUMENTS, DOUBLE_COLON, IDENT, MOD_ASSIGN, LITERAL_FOR, SUPER_CTOR_CALL, STRING_LITERAL, ARRAY_DECLARATOR, LITERAL_CASE]>`

Main differences in expected vs actual is some items are in different order but expected has `$$pitCoverageProbeSize` which is the real cause of the failure. It doesn't appear in actual.

I will report the issue.

**Comment by rnveach** [comment]
Appveyor failure is problems downloading powermock.
https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/24229469/job/0nhlmlo3gem3jhkv
> Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Access denied to: https://repo.maven.apache.org/maven2/org/powermock/powermock-api-mockito2/2.0.2/powermock-api-mockito2-2.0.2.pom , ReasonPhrase:Forbidden.

Travis is passing.

**Comment by rnveach** [comment]
@romani Are you ok with merging this since appveyor doesn't use pitest or should we still wait for full CI be green?

**Comment by romani** [comment]
Let's merge and monitor it

**Pull request merged**
