### PR TITLE
Got rid of javadoc warning, issue #548

### PR DESCRIPTION
**Pull request by alexkravin**
According to #548 

Got rid of javadoc warning

### CODE REVIEW

**Comment by romani** [comment]
Please introduce "java.version" variable and use it in all maven and ant configs, to never miss place to change after next java update.

**Comment by alexkravin** [comment]
Ok, done.

**Comment by romani** [comment]
Ant should use maven variable, change in one place should affect all required places.

**Comment by alexkravin** [comment]
Ok, I didn't know about conformity of maven and ant.

**Pull request merged**
