### PR TITLE
CheckstyleAntTask support force localeLanguage so the tests can passed on os with non-english locale(ie:zh_CN)

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
Continuation of #8791

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CheckerTest.testDuplicatedModule:1440 error message 0 ==> expected: <[ERROR] C:\Users\ASUS\AppData\Local\Temp\junit16874340039343564405\file7532748469163123785.java:1: 文件未以空行结尾。 [ModuleId]> but was: <Starting audit...>
[ERROR]   DefaultLoggerTest.testNewCtor:316 Violation should contain message `audit started`
expected to contain:
    Starting audit...
but was:
    开始检查……
    检查完成。
    
[ERROR]   DefaultLoggerTest.testNullArgs:273 Violation should contain exception info, but was 检查错误： myfile ==> expected: <true> but was: <false>
[ERROR]   MissingOverrideCheckTest.testBadAnnotationOverride:122->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 17:(?:\d+:)?\s.*include.*@java.lang.Override.*when.*'@inheritDoc'.*
but was          : 17:5: 存在 '@inheritDoc' Javadoc 注释时，必须含有 @java.lang.Override 注解。
[ERROR]   MissingOverrideCheckTest.testBadOverrideFromObject:54->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 15:(?:\d+:)?\s.*Must include @java.lang.Override annotation when '@inheritDoc' Javadoc tag exists..*
but was          : 15:5: 存在 '@inheritDoc' Javadoc 注释时，必须含有 @java.lang.Override 注解。
[ERROR]   MissingOverrideCheckTest.testBadOverrideFromObjectJ5Compatible:72->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 15:(?:\d+:)?\s.*Must include @java.lang.Override annotation when '@inheritDoc' Javadoc tag exists..*
but was          : 15:5: 存在 '@inheritDoc' Javadoc 注释时，必须含有 @java.lang.Override 注解。
[ERROR]   MissingOverrideCheckTest.testBadOverrideFromOther:92->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 17:(?:\d+:)?\s.*Must include @java.lang.Override annotation when '@inheritDoc' Javadoc tag exists..*
but was          : 17:5: 存在 '@inheritDoc' Javadoc 注释时，必须含有 @java.lang.Override 注解。
[ERROR]   MissingOverrideCheckTest.testNotOverride:148->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 15:(?:\d+:)?\s.*The Javadoc \{@inheritDoc} tag is not valid at this location..*
but was          : 15:5: 此处不应有Javadoc注释： {@inheritDoc} 。
[ERROR]   ArrayTrailingCommaCheckTest.testAlwaysDemandTrailingComma:72->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 15:(?:\d+:)?\s.*Array should contain trailing comma..*
but was          : 15:26: 数组尾元素后应有逗号','。
[ERROR]   ArrayTrailingCommaCheckTest.testDefault:46->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 23:(?:\d+:)?\s.*Array should contain trailing comma..*
but was          : 23:9: 数组尾元素后应有逗号','。
[ERROR]   DeclarationOrderCheckTest.testAvoidDuplicatesForStaticFinalFields:223->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 14:(?:\d+:)?\s.*Static variable definition in wrong order..*
but was          : 14:5: 静态属性定义顺序错误。
[ERROR]   DeclarationOrderCheckTest.testDeclarationOrderInterfaceMemberScopeIsPublic:204->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 21:(?:\d+:)?\s.*Static variable definition in wrong order..*
but was          : 21:5: 静态属性定义顺序错误。
[ERROR]   DeclarationOrderCheckTest.testDeclarationOrderRecordsAndCompactCtors:194->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 21:(?:\d+:)?\s.*Constructor definition in wrong order..*
but was          : 21:9: 构造器定义顺序错误。
[ERROR]   DeclarationOrderCheckTest.testDefault:72->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 16:(?:\d+:)?\s.*Variable access definition in wrong order..*
but was          : 16:5: 属性访问器定义顺序错误。
[ERROR]   DeclarationOrderCheckTest.testForwardReference:181->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 20:(?:\d+:)?\s.*Variable access definition in wrong order..*
but was          : 20:5: 属性访问器定义顺序错误。
[ERROR]   DeclarationOrderCheckTest.testOnlyConstructors:88->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 53:(?:\d+:)?\s.*Static variable definition in wrong order..*
but was          : 53:9: 静态属性定义顺序错误。
[ERROR]   DeclarationOrderCheckTest.testOnlyModifiers:116->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 16:(?:\d+:)?\s.*Variable access definition in wrong order..*
but was          : 16:5: 属性访问器定义顺序错误。
[ERROR]   DeclarationOrderCheckTest.testVariableAccess:214->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 23:(?:\d+:)?\s.*Variable access definition in wrong order..*
but was          : 23:5: 属性访问器定义顺序错误。
[ERROR]   DefaultComesLastCheckTest.testDefault:74->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 31:(?:\d+:)?\s.*Default should be last label in the switch..*
but was          : 31:9: default 应为 switch 块最后一个元素。
[ERROR]   DefaultComesLastCheckTest.testDefaultComesLastSwitchExpressions:95->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 16:(?:\d+:)?\s.*Default should be last label in the switch..*
but was          : 16:13: default 应为 switch 块最后一个元素。
[ERROR]   DefaultComesLastCheckTest.testDefaultComesLastSwitchExpressionsSkipIfLast:107->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 33:(?:\d+:)?\s.*Default should be last label in the switch..*
but was          : 33:13: default 应为 switch 块最后一个元素。
[ERROR]   DefaultComesLastCheckTest.testSkipIfLastAndSharedWithCase:51->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 23:(?:\d+:)?\s.*Default should be last label in the case group..*
but was          : 23:13: 默认值应为案例组中的最后一个标签。
[ERROR]   EqualsAvoidNullCheckTest.testEqualsAvoidNullTextBlocks:241->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 13:(?:\d+:)?\s.*String.*should.*be.*left.*of.*equals.*
but was          : 13:24: 字符串常量应出现在 equals 比较的左侧。
[ERROR]   EqualsAvoidNullCheckTest.testEqualsNested:177->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 25:(?:\d+:)?\s.*left .* of .* equalsIgnoreCase.*
but was          : 25:44: 字符串常量应出现在 equalsIgnoreCase 比较的左侧。
[ERROR]   EqualsAvoidNullCheckTest.testEqualsOnTheSameLine:160->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 14:(?:\d+:)?\s.*left .* of .* equals.*
but was          : 14:28: 字符串常量应出现在 equals 比较的左侧。
[ERROR]   EqualsAvoidNullCheckTest.testEqualsWithDefault:97->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 44:(?:\d+:)?\s.*left .* of .* equalsIgnoreCase.*
but was          : 44:27: 字符串常量应出现在 equalsIgnoreCase 比较的左侧。
[ERROR]   EqualsAvoidNullCheckTest.testEqualsWithoutEqualsIgnoreCase:149->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 245:(?:\d+:)?\s.*left .* of .* equals.*
but was          : 245:21: 字符串常量应出现在 equals 比较的左侧。
[ERROR]   EqualsAvoidNullCheckTest.testInputEqualsAvoidNullEnhancedInstanceof:202->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 15:(?:\d+:)?\s.*left .* of .* equals.*
but was          : 15:45: 字符串常量应出现在 equals 比较的左侧。
[ERROR]   EqualsAvoidNullCheckTest.testMisc:213->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 20:(?:\d+:)?\s.*left .* of .* equals.*
but was          : 20:17: 字符串常量应出现在 equals 比较的左侧。
[ERROR]   EqualsAvoidNullCheckTest.testRecordsAndCompactCtors:226->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 15:(?:\d+:)?\s.*left .* of .* equals.*
but was          : 15:23: 字符串常量应出现在 equals 比较的左侧。
[ERROR]   EqualsHashCodeCheckTest.testEqualsParameter:115->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 16:(?:\d+:)?\s.*without .* of 'equals\(\)'..*
but was          : 16:9: 重写'hashCode()'方法后，必须重写'equals()'方法。
[ERROR]   EqualsHashCodeCheckTest.testNoEquals:60->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 10:(?:\d+:)?\s.*without .* of 'equals\(\)'..*
but was          : 10:5: 重写'hashCode()'方法后，必须重写'equals()'方法。
[ERROR]   EqualsHashCodeCheckTest.testSemantic:51->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 96:(?:\d+:)?\s.*without .* of 'hashCode\(\)'..*
but was          : 96:13: 重写'equals()'方法后，必须重写'hashCode()'方法。
[ERROR]   ClassFanOutComplexityCheckTest.testClassFanOutComplexityMultiCatchBitwiseOr:280->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 27:(?:\d+:)?\s.*Complexity is 5.*
but was          : 27:1: 类的分散复杂度： 5 （最多： 4）。
[ERROR]   ClassFanOutComplexityCheckTest.testImplementsAndNestedCount:239->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 26:(?:\d+:)?\s.*Complexity is 3.*
but was          : 26:1: 类的分散复杂度： 3 （最多： 0）。
[ERROR]   ParenPadCheckTest.testParenPadCheckEmoji:506->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:431 Actual and expected violations differ.
expected to match: 25:(?:\d+:)?\s.* is preceded with whitespace.*
but was          : 25:45: ')' 前不应有空格。
[ERROR]   SuppressionCommentFilterTest.testArgumentSuppression:255->verifySuppressedWithParser:282->AbstractModuleTestSupport.verifyFilterWithInlineConfigParser:251->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressioncommentfilter\InputSuppressionCommentFilter7.java differ.
unexpected (1): 110
---
expected      : [45, 48, 51, 54, 55, 59, 60, 64, 67, 70, 71, 75, 96, 103, 109, 118]
but was       : [45, 48, 51, 54, 55, 59, 60, 64, 67, 70, 71, 75, 96, 103, 109, 110, 118]
[ERROR] Errors: 
[ERROR]   DefaultLoggerTest.testLocaleIsSupported:239 » NoSuchMethod com.puppycrawl.tool...
[INFO] 
[ERROR] Tests run: 3663, Failures: 37, Errors: 1, Skipped: 1
```

**Comment by Rahulkhinchi03** [comment]
@romani  sir, there is some issue I guess.
When I run a single test, then it runs but when I run a test as a whole then I get an error on the same test which was passed before when ran single.

**Comment by Rahulkhinchi03** [comment]
@romani sir, The tests were passing for these errors, but I am getting an error when I run mvn clean verify

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/pull/8791#issuecomment-998328150 

I closes that PR, we need issue to be created first to explain problem and show problem to us.

**Pull request closed without merging**
