### PR TITLE
Issue #1566: Constructor definition in wrong order fixed

### PR DESCRIPTION
**Pull request by rdiachenko**
Violations fixed:
- DeclarationOrder Constructor definition in wrong order.

### CODE REVIEW

**Comment by rdiachenko** [comment]
@romani do you have any idea why the build failed?

The only one job failed with:
```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by romani** [comment]
please rebase, I have conflicts

**Comment by rdiachenko** [comment]
@romani rebase done

**Comment by romani** [comment]
conflicts again, please rebase

**Comment by rdiachenko** [comment]
@romani rebase done

**Pull request merged**
