### PR TITLE
Fix PMD violations from UseVarargs rule, issue #999

### PR DESCRIPTION
**Pull request by mkordas**
The changes are fully backward-compatible. Method with vararg can be invoked both using array and list of parameters.

### CODE REVIEW

**Comment by romani** [comment]
did you check Maven plugin ? it is do check for signature of some our classes. We can not brake compatibility with it, we too rely on it for testing. Please generate HTML report by checkstyle-tester to prove that.

**Comment by romani** [comment]
@lkoe , can you confirm that eclipse-cs will be ok with such change ?

**Comment by lkoe** [comment]
Should be no Problem from the looks of it...
Am 28.04.2015 02:12 schrieb Roman Ivanov <notifications@github.com>:

**Comment by mkordas** [comment]
Varargs are backwards compatible, please see http://stackoverflow.com/questions/2925153/can-i-pass-an-array-as-arguments-to-a-method-with-variable-arguments-in-java. But I can prepare the report if you want :)

**Comment by romani** [comment]
No need to publish report, just confirm that it works

**Comment by romani** [comment]
Some links about good and bad of varargs:
http://stackoverflow.com/a/14252221/1015848
http://stackoverflow.com/a/770675/1015848

**Comment by romani** [comment]
merged as FF

**Comment by mkordas** [comment]
@romani, I confirm that Checkstyle Maven Plugin works fine with latest `checkstyle-6.7-SNAPSHOT`

**Comment by romani** [comment]
thanks a lot! compatibility with plugin is vital for now.

**Pull request closed without merging**
