### PR TITLE
Issue #11637: Resolve shellcheck SC2016

### PR DESCRIPTION
**Pull request by shubh220922**
Related to #11637.

Doc link: https://www.shellcheck.net/wiki/SC2016

Also important: https://www.shellcheck.net/wiki/SC2154

### CODE REVIEW

**Review by nrmancuso — CHANGES_REQUESTED** [review]
@shubh220922 these look like system/maven properties that we do not want to expand, we can suppress each individually.

**Comment by shubh220922** [comment]
@nrmancuso Done. Suppressions have been made at respective places. But, what is wrong with making a permanent suppression in``shellcheckrc`` file?

**Comment by nrmancuso** [comment]
> @nrmancuso Done. Suppressions have been made at respective places. But, what is wrong with making a permanent suppression in`shellcheckrc` file?

While these all look like places that we do not want bash to expand a variable, there is no guarantee about future usages :)

**Review by nrmancuso — APPROVED** [review]
I am good as CI passes

**Comment by shubh220922** [comment]
Fixing CI.

**Comment by nrmancuso** [comment]
@shubh220922 failure in azure is not related to your changes. The failing job is `mvn clean verify` ran on MacOS.

**Comment by shubh220922** [comment]
@nrmancuso alright. But wouldn't merging this PR create ``mvn clean verify`` issue on MacOS as per the CI.

**Comment by nrmancuso** [comment]
@shubh220922 it is probably just a random failure, we will have someone with access restart this job before we merge :)

**Pull request merged**
