### PR TITLE
Issue #13321: Kill mutation for JavadocMethod-7

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for JavadocMethod-7

-----

# Check :- 
https://checkstyle.org/checks/javadoc/javadocmethod.html#JavadocMethod

-----

# Mutation 
https://github.com/checkstyle/checkstyle/blob/d4b1aec93f4c9e3d6b8eeed8556187e342c1bb33/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L147-L163

-----

# Explaination

no argsCurlyMatcher will execute and add the `@inheritdoc` in tags list.

getMethodsTag is called by only checkComment method in which all the condition in if and else use only ast.getline no not tag's coloum is used any where which we make it to 0 

so their is no such use of tag column here 

-----

# Regression :- 

-----

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/df2ff7a8f9969bb2c68d7251a97ffa8b/raw/6a4e81a624fa36483f23b0adcf1fc513ca6df350/JavadocMethod.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/c16e31ce9283effe5b7ca057999d1b58/raw/b7eda4dd43b3b3c0d9eeba3030e1a22993123b04/github-action-projects2.properties
Report label: Project-list-3

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
@Kevin222004 , please update Checker suppression and convert PR to ready for review.

This is good example how we follow pitest to remove extra code in non AST based checks if regression can not find anything.
Such Checks will be rewritten in future projects. Java code will not be reused so this pitest activity extends our test base (that will be reused) or main code is shrinking.

**Review by romani — APPROVED** [review]
ok to merge

**Comment by romani** [comment]
hmm, unrelated pitest:
https://github.com/checkstyle/checkstyle/actions/runs/6831156451/job/18580202698?pr=13342#step:7:15
```
patch -p1 << EOF
diff --git a/config/pitest-suppressions/pitest-common-suppressions.xml b/config/pitest-suppressions/pitest-common-suppressions.xml
index fe31289..47a734a 100644
--- a/config/pitest-suppressions/pitest-common-suppressions.xml
+++ b/config/pitest-suppressions/pitest-common-suppressions.xml
@@ -9,6 +9,15 @@
     <lineContent>final String stripped = CommonUtil.relativizeAndNormalizePath(basedir, fileName);</lineContent>
   </mutation>
 
+  <mutation unstable="false">
+    <sourceFile>Checker.java</sourceFile>
+    <mutatedClass>com.puppycrawl.tools.checkstyle.Checker</mutatedClass>
+    <mutatedMethod>finishLocalSetup</mutatedMethod>
+    <mutator>org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator</mutator>
+    <description>removed call to com/puppycrawl/tools/checkstyle/LocalizedMessage::setLocale</description>
+    <lineContent>LocalizedMessage.setLocale(locale);</lineContent>
+  </mutation>
+
   <mutation unstable="false">
     <sourceFile>Checker.java</sourceFile>
     <mutatedClass>com.puppycrawl.tools.checkstyle.Checker</mutatedClass>
EOF
```

**Comment by Kevin222004** [comment]
I am looking on that

**Comment by Kevin222004** [comment]
In my local no new surviving is found so probably it will pass as it is re-run

**Review by nrmancuso — APPROVED** [review]
Provided explanation is incorrect, we use the column number from the collection of tags in a bunch of places. Examples:
 - https://github.com/checkstyle/checkstyle/blob/50c667276b33db03da0bd3bef68c0364348393f6/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java#L798
 - https://github.com/checkstyle/checkstyle/blob/50c667276b33db03da0bd3bef68c0364348393f6/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java#L926
 - https://github.com/checkstyle/checkstyle/blob/50c667276b33db03da0bd3bef68c0364348393f6/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java#L886

I see no real evidence that this mutation can't be killed by test input.

However, I am good to merge this update; we have a bunch of clean regression tests, and potential ROI for finding some obscure test case in probably not worth it.

**Pull request merged**
