### PR TITLE
Issue #6477: Improve IllegalType check documentation and extend default forbidden classes

### LINKED ISSUE #6477: Documentation of IllegalType
Could you maybe improve a bit the documentation of `IllegalType`?

The only thing it says is "Checks that particular classes or interfaces are never used. Rationale: Helps reduce coupling on concrete classes.".

But why should one never use a `HashMap` or a `TreeSet` or the other classes in the default list?
And if those, why not also `ArrayList`, `ConcurrentHashMap` and so on?

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #6477

### CODE REVIEW

**Comment by rnveach** [comment]
@Vampire wercker failure
> NoErrorTest - XWiki
> [INFO] --- maven-checkstyle-plugin:3.0.0:check (default) @ xwiki-commons-component-default ---
[INFO] Starting audit...
[WARN] /pipeline/source/.ci-temp/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/main/java/org/xwiki/component/annotation/ComponentDescriptorFactory.java:159: Comment matches to-do format 'TODO'. [TodoComment]
[ERROR] /pipeline/source/.ci-temp/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/main/java/org/xwiki/component/internal/StackingComponentEventManager.java:50:13: Usage of type 'Stack' is not allowed. [IllegalType]
Audit done.
[INFO] There is 1 error reported by Checkstyle 8.19-SNAPSHOT with checkstyle.xml ruleset.
[ERROR] src/main/java/org/xwiki/component/internal/StackingComponentEventManager.java:[50,13] (coding) IllegalType: Usage of type 'Stack' is not allowed.

This is because of new items you added to default forbidden classes.
If we go through with this change, you will need to update projects who use default configuration.

**Comment by rnveach** [comment]
@romani Please ensure you are ok with new default list.

**Comment by Vampire** [comment]
I'll look into it once the list is approved by romani

**Comment by romani** [comment]
@Vampire , issue is approved, with note that we should update Rationale in more clear way, as with such such new defaults Check become more aggressive so it will attract more users to read documentation.

**Comment by Vampire** [comment]
About the XWiki Wercker failure, what would be the way to go?
Configuring their check to not include `Stack`?
I'm surely not gonna rewrite their complete code to not use `Stack` anymore.

**Comment by rnveach** [comment]
@Vampire did you look at their only file that is producing violations?
Type is coming from the parameter of an overridden method from a sub-class that is not code they have written. All that is needed is a suppression for these 2 lines.

**Comment by Vampire** [comment]
Yep, I just added `StringBuffer`to the list. Before it was `Stack` it complained about and I grepped their repo and found several `Stack`s. That's why I ask how you usually handle such things. How much it is I don't know yet, I'm right now trying to get the wercker builds to run locally, especially as I cannot see the wercker builds.

**Comment by romani** [comment]
> That's why I ask how you usually handle such things.

we use such projects in our CI as real life examples on how people use Checks and how testing it on real code, where engineers might not be happy to change code in the way Check demand, so it give us ideas that other users might think in the same way.

As this Check become more aggressive, we become to see design issues in it. Types from `@Override` methods should be ignored, as class just follow contract of extend, no way to resolve this.

We have to provide PR to xwiki project with fix of code or configuration (as last option). You can fork their repository, do required fixes, and update our wercker config to point to your fork/branch. Ones CI pass and we agree on fix, we have to send PR to xwiki and persuade them to merge it. Ones xwiki merge is done, we change your PR to point back to original xwiki repo, CI pass, we merge your code.

I recommend to split Rationale update to separate PR, and merge it quicker.
Issue with skipping validation when `@Override` is present, should be resolved/merged first (separate issue).

>Configuring their check to not include Stack?
I'm surely not gonna rewrite their complete code to not use Stack anymore.

I think you can create issue on them and discuss this, They might agree on suppression, and they will fix it later on themself.
Before going to them I would recommend to analyze they code to make sure, it is not problem of Check (as we already see with `@Override`).

> especially as I cannot see the wercker builds.

let us know if you need any help with this. Unfortunately this is limitation of wercker.

**Comment by Vampire** [comment]
@romani before I put that effort in, can you share your thoughts about the new list of classes? Do you think it is sensible?

**Comment by romani** [comment]
Changes in default, and extension of validation scope is always not easy.

What I see as problem is that Check looks like deroute from it original goal or smth is lost in documentation so it hard to make a decision.
As I recommended before, let's do this update is two steps:
- Update documentation to clearly define Check goals and what for it should be used. Release it to public, on next weekend.
- Review your list one more time, And make a decision to expand a list or not. If expand, think about users who will get new violations after upgrade, how can we help them to explain/resolve/suppress new violations.

Let's pause this PR for a bit, and let's clearly formulate rationale/goal of Check.

**Comment by Vampire** [comment]
> As this Check become more aggressive, we become to see design issues in it. Types from `@Override` methods should be ignored, as class just follow contract of extend, no way to resolve this.

For parameter types I agree, see #6612.

> We have to provide PR to xwiki project with fix of code or configuration (as last option). You can fork their repository, do required fixes, and update our wercker config to point to your fork/branch. Ones CI pass and we agree on fix, we have to send PR to xwiki and persuade them to merge it. Ones xwiki merge is done, we change your PR to point back to original xwiki repo, CI pass, we merge your code.

Done, actually wasn't that much to change in xwiki.
I did this during my vacation this week.

> I recommend to split Rationale update to separate PR, and merge it quicker.

We can of course do this if you want.

> Issue with skipping validation when `@Override` is present, should be resolved/merged first (separate issue).

See #6613,

> What I see as problem is that Check looks like deroute from it original goal or smth is lost in documentation so it hard to make a decision.

I don't think so.

The rationale says the check is to reduce coupling on concrete classes.
Almost all types that are already in the list or are added by me follow the same goal of not having `Collection` and `Map` implementations as parameters, return types, variable types, field types and so on, but instead use their respective interface to program against.

Some exceptions that do not fit to that rationale, but fit to the name of the check are for example `Vector`, `Stack` or `StringBuffer`.
Those classes should not be used at all, as there are newer, better, faster replacementes and even their own JavaDoc recommends to use the other classes instead.
Also the first of these, `Vector` was already present in the first checkin that was made for this check, so while it does not exactly fit the rationale, I'd say it fits the original idea of the check and also the name.
The check is called `IllegalType`, not `CheckCoupling`. :-)

>     * Update documentation to clearly define Check goals and what for it should be used. Release it to public, on next weekend.
> Let's pause this PR for a bit, and let's clearly formulate rationale/goal of Check.

So how do you want it?
The changes I made to the docs?
An additional update of the rationale to include semantically things like `Vector`, `Stack` and `StringBuffer`?
As a modification of this PR?
As new PR?
...?

**Comment by romani** [comment]
@Vampire ,

> The rationale says the check is to reduce coupling on concrete classes.

lets extend this with " and use interfaces instead if possible".
"if possible" is critical as it force check to ignore such types in extend/implements and probably in other places.

> Those classes should not be used at all, as there are newer, better, faster replacements and even their own JavaDoc recommends to use the other classes instead.

so it is different rationale. It is complete ban of certain types reference in code (something like this can be archived by ImportControl).
Mix of patterns is design problem, such Checks will never work well, in most case people will misuse them (again it is sign of bad design).

So what we are going to validate by this check: 
1) complete banning of type reference 
2) recommend to use interface where it is possible. 

I think after bunch of updates this Check is more like IllegalType https://github.com/checkstyle/checkstyle/commits/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java as we damaged this Check by implementation of "IllegalType should check extends & implements" and "IllegalType does not check type arguments/parameters" ... even in doc we have clear definition that "illegalClassNames - Classes that should not be used as types in variable declarations, return values or parameters"(NOT everywhere). 
So orignally this Check was designed for enforcing interfaces instead of concrete classes, but end up with forbidding types in general.

So I would recommend to change Rationale to make it forbid type to be used at any place. 
Instead of extending defaults as you suggested. Change to well known problematic classes (not a list of concrete types that are good and well used). `illegalClassNames` should follow `tokens` property and detected illegalTypes in trget defined by `tokens`.

Do you agree with such update? (complete opposite to your PR, but finally we got to roots of problem)

**Comment by romani** [comment]
I am closing this PR for now, to focus on agreement of expected update in issue.
we will reopen this PR ones we come to agreement.

**Pull request closed without merging**
