### PR TITLE
Add possibility to configure targets for ParenPad check, #1189

### PR DESCRIPTION
**Pull request by Vladlis**
Reports from checkstyle-tester: http://vladlis.github.io - there are no differences after changes in default config.

### CODE REVIEW

**Comment by romani** [comment]
1)
>``` * empty for iterators and {@link EmptyForInitializerPadCheck EmptyForInitializerPad}
 * to validate empty for initializers. Typecasts are also not checked, as there is
 * {@link TypecastParenPadCheck TypecastParenPad} to validate them.```

strange is that I do not see check for that at visit token, but it should be done as one of first checks

2)
> public int[] getDefaultTokens() 

getDefaultTokens is identical to getAcceptableTokens, copy-paste, so please do public int[] getDefaultTokens() {return getAcceptableTokens();}

3)
> public void visitToken(DetailAST ast) {

make it as switch it will make logic a bit more clear to read.

4)
>```
 if (isToProcessInExpression(childAst)) {
 visitExpression(childAst);
 }
```

smth strange base on visitToken method, visitExpression should be called only on METHOD_CALL, EXPR, QUESTION, but here we have check for all Acceptable tokens inside isToProcessInExpression. Please explain.

5)
> Checks parens in default tokens, except from

please remove "default". as "default token" is a term of Check, it is already used

6)
>visitDefault

please explain why "isPreceedsEmptyForInit" and "isFollowsEmptyForIterator" should be called on all token, why not to filter out FORs at the most top level - visitToken().

7)
>``` private boolean isToProcessInExpression(DetailAST ast) {
 boolean isToProcessInExpression = true;```

there is good pattern name for such cases - "boolean result = true" . It is the same clear but the shortest.
Please fix in all other similar methods

8)
>private static boolean isInTypecast(DetailAST ast) {

Looks like to clearly understand how to distinguish static method candidate you need to automate it :).  One of your next task will be https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/339


9) 
> config_whitespace.xml

please fix indentation of elements , and I do not see changes to description of Check that you did in javadoc. Ideally xdoc should be the same as javadoc, or xdoc a bit more extended.
9

**Comment by Vladlis** [comment]
1) Done
2) Done
3) Done
4) renamed it to processExpression
Here
```java
if (isToProcessInExpression(childAst)) {
 processExpression(childAst);
 }
```
it is called recursively in order to find and process all the parens in METHOD_CALL, EXPR, QUESTION except from those in AcceptableTokens, so not to conflict, when some tokens, which could be found inside  METHOD_CALL, EXPR, QUESTION, have a different option.
So, processExpression() is called on METHOD_CALL, EXPR, QUESTION from visitToken() and then recursively called on all the tokens except from AcceptableTokens
5) Done
6) Fixed. Didn't want to duplicate code
7) Done
8) Fixed
9) Done

**Comment by romani** [comment]
1) 
```
 if (childAst.getType() == TokenTypes.LPAREN) {
processLeft(childAst);
}
if (childAst.getType() == TokenTypes.RPAREN && !isInTypecast(childAst)) {
```

make as IF_ELSE

2)
> isToProcessInExpression

I still do not like that method, ..... please rename it to be "isAsseptableToken" and use inversion in IF.
Please give me java code examples when it will be used.

3)
>  final DetailAST parenAst = ast.findFirstToken(TokenTypes.LPAREN);
if (parenAst != null) {

please use "ast.branchContains(TokenTypes.LPAREN)"

4)
So changes to are huge, we need to recheck regression, please start report generation, I presume there should be no changes.

**Comment by Vladlis** [comment]
1) Done
2) Done
an example has been already provided in UT, but I've added one more not so complex:
```java 
boolean fooo = this.bar(( true && false ) && true);
```
it is VARIABLE_DEF[123X4] in the AST below:
-checkstyle inputparenpad java
if the Check is run with properties
```xml
<property name="tokens" value="METHOD_CALL"/>
<property name="option" value="NOSPASE"/>
```
then it is expected to have no violations, as METHOD_CALL's parens are not preceded or followed by any spaces in contrast to parens in EXPR. That is why it is important to stop while traversing METHOD_CALL if an Acceptable Token is met - if this token should have been checked, it would have been visited by visitToken() and then checked.

3) I still have to keep this code for LITERAL_NEW and ENUM_CONSTANT_DEF as they can contain LPAREN and RPAREN as not direct children.

4) everything is OK - http://vladlis.github.io/

**Comment by romani** [comment]
1)
> else {  if (childAst.getType() == TokenTypes.RPAREN && !isInTypecast(childAst)) {

Why not just "else if (........"
Please add to "esle if" even "if (!isAcceptableToken(childAst)) {" as only one block will be executed for one WHILE iteration

2)
> an example has been already provided in UT, but I've added one more not so complex

thanks a lot that helped me to understand a logic. So we need to put that as a comment to code, as it is not that obvious. "Traverse all subtree tokens that are will never be configured to be launched in visitToken"

3) do final recheck for by reports, and I will do merge.

**Comment by Vladlis** [comment]
1) Done
2) Done
3) Done: http://vladlis.github.io/

**Comment by romani** [comment]
@Vladlis , please recheck pushed commit, non of points from my last comment is done.

**Comment by Vladlis** [comment]
@romani,
Sorry, fixed and rechecked again.

**Comment by romani** [comment]
Now explain your decision about moving isAcceptableToken above, i expected else-if structure. isAcceptableToken is not light opreration to make on each token. Even more, please optimize search in that array by sorting it in advance.

**Comment by Vladlis** [comment]
@romani, I did binary search over AcceptableTokens.
As for calling isAcceptableToken - my mistake, I didn't want to duplicate 
>  processExpression(childAst);

but it is better, then calling isAcceptableToken() where it is not needed

**Comment by romani** [comment]
Read attentively - http://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html#binarySearch%28int[],%20int%29
example: http://www.tutorialspoint.com/java/util/arrays_binarysearch_int.htm

after a fix please send me a link to !!new!! UT that covers a problem that you missed, your tests are passing now but Check does not work correctly.

**Comment by Vladlis** [comment]
@romani, fixed: made default order of AcceptableTokens unsorted and added sort to isAcceptableToken(). There is no need in a new UT, as testConfigureTokens() checks this case.

**Comment by romani** [comment]
>    private boolean isAcceptableToken(DetailAST ast) {
        boolean result = false;
        final int[] acceptableTokens = getAcceptableTokens();
        Arrays.sort(acceptableTokens);


What is a reason to sort array on each token Check !? do you expect it to be different each time ?

**Comment by Vladlis** [comment]
Fixed

**Comment by romani** [comment]
initialization should be done in C-tor or at filed declaration(prefereable) - single point of initialization.

**Comment by romani** [comment]
release 6.8 will be in 4 days, it will be good to finish that PR before.

**Comment by Vladlis** [comment]
Done in C-tor, as initialization at filed declaration is not possible, because Asrrays.sort() is void.

**Comment by romani** [comment]
C-tor calling a public method, not good solution, not clear why pmd muis that.

**Comment by Vladlis** [comment]
@romani 
I've made ParenPadCheck final => it cannot have any sub-classes => no consequences because of use of overridable method

**Comment by romani** [comment]
:) you are cheating , please remove final from class, and make change inside class to avoid calling public method.

**Comment by Vladlis** [comment]
fixed

**Comment by romani** [comment]
merged as FF, Thanks a lot !

**Pull request closed without merging**
