### PR TITLE
Issue #13999: Resolve pitest suppression for walk method of AbstractJavadocCheck

### PR DESCRIPTION
**Pull request by TanayMorakhia**
part of #13999 

Diff Regression config: https://gist.githubusercontent.com/TanayMorakhia/431cb93bf15c238967db9914a3d164ec/raw/575ff26646e5f029e9f9053a8878f27859bb186b/AbstractJavaDocCheck.xml

Diff Regression projects: https://gist.githubusercontent.com/TanayMorakhia/f3a248e4d705e5b3e0defe44c8bc8452/raw/6a2871822b807d93bcb58a449f79d94a55702f35/project.properties

### CODE REVIEW

**Comment by TanayMorakhia** [comment]
Github, generate report

**Comment by TanayMorakhia** [comment]
Github, generate report

**Comment by TanayMorakhia** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/7745731528/job/21122392399?pr=14404#step:7:23

This mutation is not surviving on local and is this related to this pr ?

**Comment by TanayMorakhia** [comment]
Github, generate report

**Comment by romani** [comment]
Extra pitest survival is required to be removed https://github.com/checkstyle/checkstyle/actions/runs/7745731528/job/21122392399?pr=14404#step:7:23

Please share your analysis on why this code is not required. It might not required for existing Checks but might be required in general (one of future Check)

**Pull request closed without merging**
