### PR TITLE
Issue #3575: changed module setters for file

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3575

File conversion.

### CODE REVIEW

**Comment by romani** [comment]
I think we have to deprecate this setter. User need to define String and we will search it in classpath, url, filesystem, .... .

Recently discussed at #3578 .

**Comment by rnveach** [comment]
I saw that just after putting in this PR.
@romani 
Should I deprecate it now or should we drop this PR? When it is removed completely, we will have to make special test for code coverage for the changes in `AutomaticBean`.

**Comment by jochenvdv** [comment]
I was going to change `setFile` to use `CommonUtils.getUriByFilename()` to support URLs and resources in the `file` property so I think it is best to drop this PR.

**Comment by jochenvdv** [comment]
See PR #3583.

Can you explain the change from `string` to `String`?

**Comment by romani** [comment]
lets drop this PR.

**Comment by romani** [comment]
> Can you explain the change from string to String?

just to be clear on what java type is used

**Pull request closed without merging**
