### PR TITLE
Issue #13765: Add proper naming format

### PR DESCRIPTION
**Pull request by AayushSaini101**
Related: https://github.com/checkstyle/checkstyle/issues/13765

### CODE REVIEW

**Review by nrmancuso — APPROVED** [review]
Ok to merge as CI passes

**Comment by AayushSaini101** [comment]
> Ok to merge as CI passes

Please mark hactober accepted

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
Weird, I have no permission to rerun failing CI 

@AayushSaini101 , can you rerun?

**Comment by AayushSaini101** [comment]
> Weird, I have no permission to rerun failing CI
> 
> @AayushSaini101 , can you rerun?

No , I don't have permission

**Comment by romani** [comment]
Rebased by GitHub

**Pull request merged**
