### PR TITLE
Issue #13321: Kill mutation for Xpath profile

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for Xpath profile

------

# Mutation 
https://github.com/checkstyle/checkstyle/blob/89e3ffcf7c2a7f764c5e76d52af25d8283b3d3b3/config/pitest-suppressions/pitest-xpath-suppressions.xml#L57-L73
and 
https://github.com/checkstyle/checkstyle/blob/89e3ffcf7c2a7f764c5e76d52af25d8283b3d3b3/config/pitest-suppressions/pitest-xpath-suppressions.xml#L84-L91

---------

# Explaination 
All are default value and they are in constructor

### CODE REVIEW

**Review by Vyom-Yadav — APPROVED** [review]
LGTM! Those are the default values.

CI Failure is unrelated.

**Review by romani — APPROVED** [review]
Ok to merge.

Just removal of null assignments that are happening already before ctor execution

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by rdiachenko** [comment]
rebased

**Comment by nrmancuso** [comment]
@romani looks like @Vyom-Yadav already reviewed and approved, I will merge this

**Review by nrmancuso — APPROVED** [review]

**Pull request merged**
