### PR TITLE
Remove dead code from ElseHandler in Indentation check. #1270

### PR DESCRIPTION
**Pull request by mkordas**
Reports are the same:
```
--- target/checkstyle-result.xml
+++ target-6.8.1/checkstyle-result.xml
@@ -2 +2 @@
-<checkstyle version="6.9-SNAPSHOT">
+<checkstyle version="6.8.1">
```

### CODE REVIEW

**Comment by romani** [comment]
merged as FF

**Comment by mkordas** [comment]
@romani - I don't thing this commit went to master, can you recheck?

**Comment by romani** [comment]
sorry, my bad, merged.

**Comment by mkordas** [comment]
thanks :)

**Pull request closed without merging**
