### PR TITLE
Issue #4191: Split and Organize Checkstyle inputs by Test for ParameterName 

### PR DESCRIPTION
**Pull request by Shubhk15**
#This PR resolves the issue #4191.
Following files were moved to parametername:
InputOverrideAnnotaion.java (renamed to InputParameterNameOverrideAnnotation.java)
InputOverrideAnnotaionNoNPE.java (renamed to InputParameterNameOverrideAnnotationNoNPE.java)
InputAccessModifier.java (renamed to InputParameterNameAccessModifier.java)
InputParameterNameReceiver.java

### CODE REVIEW

**Comment by rnveach** [comment]
@Shubhk15 Please read over https://github.com/checkstyle/checkstyle/wiki/PR-rules include point 1 and 2 and 4.
Please rebase over latest master with no merge commits.

**Comment by Shubhk15** [comment]
@rnveach  Can you please guide me further on what else to be done?

**Comment by rnveach** [comment]
@Shubhk15 The PR rules stated it all, none of which you have done.
We expect only 1 commit with your changes.
CI must pass. I suggest you run `mvn verify` locally before pushing again.

**Comment by Shubhk15** [comment]
@rnveach 
Can you help me resolve these-
It states that the error is in change in line number but no such changes were made
Thanks.
error

**Comment by rnveach** [comment]
@Shubhk15 It has to do with your changes to the input file.
Violations are on parameters of constructor and class name was changed to match input file name.

Because we don't want to modify tests in the scope of this issue, you will have to keep file names as old names and we will rename them later.
Please revert file names to their original names. You can keep package name change.

**Comment by Shubhk15** [comment]
Do you mean to revert back all the changes made in these files including the file name, like change in the method name and all?

**Comment by rnveach** [comment]
> Do you mean to revert back all the changes made in these files including the file name, like changes in the method name and all?

For just the 3 inputs identified in your picture at https://github.com/checkstyle/checkstyle/pull/4195#issuecomment-293687665 , restore the file name to the original name and restore the class name to the original name.
Only thing that can remain changed is package name.

Confirm by running `mvn verify` and that those failing tests and all tests now pass.

Please also look over the https://github.com/checkstyle/checkstyle/wiki/PR-rules again.
Commits must stay at 1 and only 1.

**Comment by Shubhk15** [comment]
@rnveach Is this PR okay?
Also i couldn't understand why TeamCity build failed. Do i have to make any more changes to pass that too?

**Comment by rnveach** [comment]
@Shubhk15 TC can be ignored for now, just make sure you are rebased on the latest master.

**Pull request merged**
