### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Kevin222004**
Not to merge 
diff report execution with no ci

----------------------------------------

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/c515fe44cd311783e6cbdf0f5788b4d3/raw/15647eeebde66f0c3a366f655442b02b4d55efef/equal.xml

### CODE REVIEW

**Comment by Kevin222004** [comment]
GitHub, generate report

**Comment by Kevin222004** [comment]
@romani report has successfully generated 
can i close this know

**Comment by romani** [comment]
Such execution took only 34 seconds, if reason is not obvious, we can ignore it and let it run

**Comment by Kevin222004** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/5059500838/workflow?pr=13085#:~:text=.github/workflows/no%2Dold%2Drefs.yml

Their is no any other file then diff-report.yml

```
kevin@inspiron-15-5510:~/Desktop/check_style/checkstyle/checkstyle$ find . -type f -name "*.yml"
./.github/workflows/diff-report.yml

```
I am not sure how it has been executed

**Pull request closed without merging**
