### PR TITLE
Issue #15851: suppress LeftCurlyNl for switch expressions

### PR DESCRIPTION
**Pull request by romani**
Issue #15851

Diff Regression config: https://raw.githubusercontent.com/checkstyle/checkstyle/refs/heads/master/src/main/resources/google_checks.xml
Diff Regression patch config: https://raw.githubusercontent.com/checkstyle/checkstyle/2b51ddc169412cdbdd347746a860629f74dac55e/src/main/resources/google_checks.xml
Diff Regression projects: https://gist.githubusercontent.com/romani/43e3ccdd18eea023a3d0e405b64a5414/raw/345cb17301fe37544e56d659306395ca1a4e9a8f/guava-project.properties

### CODE REVIEW

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
@bradleylarrick , fyi.

if you can pretest this fix on your source  it would be awesome. 
to build:
`mvn clean package -Pno-validations` for '-all' jar or `mvn clean install -Pno-validations` for mvn jar

**Comment by bradleylarrick** [comment]
I'm still seeing the same error:
````
[~/temp] java -jar checkstyle-10.20.1-SNAPSHOT-all.jar -c google_checks.xml Test.java
Starting audit...
[WARN] C:\Users\bradley\temp\Test.java:4:4: <p> tag should not precede HTML block-tag '<div>', <p> tag should be removed. [JavadocParagraph]
Audit done.
[~/temp] cat -n Test.java
     1  /**
     2   * Plugin to standardize all directions to their appropriate abbreviation.
     3   *
     4   * <p><div style="padding: 1em 1em 1em">
     5   *
     6   * <table>
     7   * <caption></caption>
     8   * <thead>
     9   * <tr>
    10   * <th scope="col" style="padding: .3em 4em 0 0; text-align: left">Direction
    11   * <th scope="col" style="padding: .3em 4em 0 0; text-align: left">Abbreviation
    12   * </tr>
    13   * </thead>
    14   * <tbody>
    15   * <tr>
    16   * <td>East</td> <td>E</td>
    17   * </tr>
    18   * </tbody>
    19   * </table>
    20   *
    21   * </div>
    22   */
    23  public class Test {
    24
    25    /** Default constructor. */
    26    public Test() {
    27      super();
    28    }
    29  }
````

**Comment by rdiachenko** [comment]
I checked out this PR branch and tested on my localhost as follows:

```
$ mvn clean package -Passembly,no-validations
$ cp target/checkstyle-10.20.1-SNAPSHOT-all.jar .
$ cat TestCurly.java
public class TestCurly {
  /** Default Constructor. */
  public TestCurly() {
    // Intentionally left blank.
  }
  /** Test Method. */
  public void testMethod() {
    if (result.length > rpos) {
      switch (modulus) {
        case 1 -> { // one octet remaining; add two bits and load 2 quintets
          workarea = workarea << 2;
          rpos = loadCodes(workarea, result, rpos, 2);
        }
        case 2 -> { // two octet remaining; add four bits and load 4 quintets
          workarea = workarea << 4;
          rpos = loadCodes(workarea, result, rpos, 4);
        }
        case 3 -> { // three octets remaining; add one bit and load 5 quintets
          workarea = workarea << 1;
          rpos = loadCodes(workarea, result, rpos, 5);
        }
        case 4 -> { // four octets remaining; add 3 bits and load 7 quintets
          workarea = workarea << 3;
          rpos = loadCodes(workarea, result, rpos, 7);
        }
        default -> {} // Will never get here
      }
    }
  }
}

$ java -jar checkstyle-10.20.1-SNAPSHOT-all.jar -c google_checks.xml TestCurly.java
Starting audit...
[WARN] /private/var/tmp/checkstyle/TestCurly.java:1:1: Missing a Javadoc comment. [MissingJavadocType]
[WARN] /private/var/tmp/checkstyle/TestCurly.java:7:3: 'METHOD_DEF' should be separated from previous line. [EmptyLineSeparator]
Audit done.
```

If I run it against master branch, it fails:
```
java -jar checkstyle-10.20.1-SNAPSHOT-all.jar -c google_checks.xml TestCurly.java
Starting audit...
[WARN] /private/var/tmp/checkstyle/TestCurly.java:1:1: Missing a Javadoc comment. [MissingJavadocType]
[WARN] /private/var/tmp/checkstyle/TestCurly.java:7:3: 'METHOD_DEF' should be separated from previous line. [EmptyLineSeparator]
[WARN] /private/var/tmp/checkstyle/TestCurly.java:10:19: '{' at column 19 should be on a new line. [LeftCurlyNl]
[WARN] /private/var/tmp/checkstyle/TestCurly.java:14:19: '{' at column 19 should be on a new line. [LeftCurlyNl]
[WARN] /private/var/tmp/checkstyle/TestCurly.java:18:19: '{' at column 19 should be on a new line. [LeftCurlyNl]
[WARN] /private/var/tmp/checkstyle/TestCurly.java:22:19: '{' at column 19 should be on a new line. [LeftCurlyNl]
Audit done.
```

So, the fix works fine.

**Review by rdiachenko — APPROVED** [review]
lgtm

**Review by Zopsss — APPROVED** [review]
LGTM

**Comment by bradleylarrick** [comment]
I pulled the latest checkstyle code this morning and my issue seems to be resolved.

**Pull request merged**
