### PR TITLE
Issue #5439: New Check: Enforce or deny a blank line after the left curly brace

### PR DESCRIPTION
**Pull request by pbludov**
Issue #5439: New Check AfterLeftCurly

### CODE REVIEW

**Comment by rnveach** [comment]
@pbludov CI is failing. Reason looks like bad javadoc.

**Comment by pbludov** [comment]
@rnveach 
> CI is failing. Reason looks like bad javadoc.

The AfterLeftCurlyCheck refers to BeforeRightCurlyCheck in the documentation. And vise versa.
Since @romani wants to split them into two independent issues, these errors are expected.

**Comment by rnveach** [comment]
Yet we can't merge them with failing CI.

**Comment by romani** [comment]
CI is failed as issue is not approved.
Please update issue description to let me review design and recheck one more time that we are right way.

**Comment by pbludov** [comment]
@romani done.

**Comment by pbludov** [comment]
screenshot--2018-01-13-16-38-13

**Comment by romani** [comment]
:), please move this to issue as plain text, only issue is referenced in commit and release notes.

I already see naming problem (AfterLeftCurly and blankLine=false - sound weird), so I need to think we need to discuss it.

**Pull request closed without merging**
