### PR TITLE
Issue #8938: put user content to env variable at workflows/diff_report.yml

### PR DESCRIPTION
**Pull request by romani**
Issue #8938

### CODE REVIEW

**Review by strkkk — APPROVED** [review]

**Review by rnveach — CHANGES_REQUESTED** [review]
Concern.

Also CI is not passing.

**Comment by romani** [comment]
wercker is failed with:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (checkstyle-validation) on project spring-cloud-gcp-docs: Execution checkstyle-validation of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check: java.lang.NoSuchMethodError: 'void com.puppycrawl.tools.checkstyle.Checker.setClassLoader(java.lang.ClassLoader)'`

**Comment by romani** [comment]
@rnveach , please find me in chat to resolve concern.

**Comment by romani** [comment]
Github, rebase

**Review by rnveach — APPROVED** [review]

**Pull request merged**
