### PR TITLE
Issue #6726: aligned javadoc/xdoc for SuppressionCommentFilter

### PR DESCRIPTION
**Pull request by pbludov**
Issue #6726 (part of #5750)

The `Notes` section now before `Properties`.

### CODE REVIEW

**Comment by pbludov** [comment]
@romani @rnveach ping

Please help me with `SuppressionCommentFilter.Tag` class. It is `public` but undocumented.
Should it be documented or redesigned to be `private`?

**Comment by rnveach** [comment]
I don't know why it is public. I don't see it needing being public but it should be in another PR outside this issue, IMO.
Regardless, the nested class should not be documented in our xdoc.

**Comment by romani** [comment]
if nobody use this class, make it private, we can skip documenting it.

**Comment by romani** [comment]
from TC:
>src/main/java/com/puppycrawl/tools/checkstyle/filters
SuppressionCommentFilter.java (1)
555: Tag Protected nested class Tag 

@pbludov ,
can you keep it public for now ?
to resolve CI issues and lets merge this big update. 
I already see 2 PRs in sequential blocked state, not good.
It is better to avoid such situations.

**Comment by rnveach** [comment]
@pbludov Can we finish this PR now that others are merged?
There is a git conflict.

**Comment by pbludov** [comment]
> @pbludov Can we finish this PR now that others are merged?

done. Rebased to the latest master.

**Pull request merged**
