### PR TITLE
Issue #13421: Add since in javadoc of each property setter for whitespace checks

### PR DESCRIPTION
**Pull request by stoyanK7**
Part of #13421 

---
Adds `@since` to each property setter.

Taken from https://checkstyle.sourceforge.io/checks/whitespace/index.html

### CODE REVIEW

**Comment by nrmancuso** [comment]
Semaphore is restarted

**Review by nrmancuso — APPROVED** [review]
Ok to merge as CI passes

**Comment by rnveach** [comment]
@stoyanK7 
> Taken from https://checkstyle.sourceforge.io/checks/whitespace/index.html

Please delete sourceforge from your history and use https://checkstyle.org/ . :)

**Comment by nrmancuso** [comment]
Failure in nondex is not related to changes here: https://checkstyle.semaphoreci.com/workflows/7fc4eb4e-855f-4d69-a991-6fb31e78a2d2?pipeline_id=f2030aae-8765-4f23-a60a-f66129044b7f

**Pull request merged**
