### PR TITLE
Fixed problems with UTs on Windows, issue #612

### PR DESCRIPTION
**Pull request by alexkravin**
According to #612 

Extended UTs and Checks to normally pass on Windows.
Most of problems were in lack of carriage return - <b>'\r'</b> in OS different from Windows.

2 UTs were skipped while running on Windows:

1) JavadocParseTreeTest - one of inputs crashes generated by antlr JavadocParser, this place in UT is commented.

https://github.com/alexkravin/checkstyle/blob/48af2b6259f6090c21a256402ec166cbf5b1af6b/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParseTreeTest.java#L240

2) Encoding problems with InputGrammar.java and corresponding UT Generated14JavaLexer - test passes in eclipse, but fails in maven which supposes literal's are different.

https://github.com/alexkravin/checkstyle/blob/48af2b6259f6090c21a256402ec166cbf5b1af6b/src/test/java/com/puppycrawl/tools/checkstyle/grammars/GeneratedJava14LexerTest.java#L24

### CODE REVIEW

**Comment by romani** [comment]
I will put on pause that PR as it reveils problem in Javadoc grammar, no extra "\r" should be generated, @baratali please comment that issue.

**Comment by baratali** [comment]
You are right. Grammar does not support '\n\r' as newline symbol. I'll fix it.

**Comment by alexkravin** [comment]
@baratali,
In Windows newline denoted as:
1) Carriage return
2) New line
Like in old typewriter, so '\r\n'

**Comment by baratali** [comment]
I added support of '**\n\r**' in Javadoc grammar. Also I changed '**\n**' in UTs by ***System.getProperty("line.separator")***. All UTs passes successfully on Windows 7(64bit) and Ubuntu 14.04(64bit).
Commit: https://github.com/baratali/checkstyle/commit/87bfa005186520f95569d7aa7b7b758766b7a3c8
Please take a look.

**Comment by romani** [comment]
@baratali, looks ok, please compare generated report against java9 sources before and after fix and do PR.

**Comment by romani** [comment]
I am closing that PR as changes will be different from original, baratali will provide separate PR with reference to original issue in commit message.

**Pull request closed without merging**
