### PR TITLE
Issue #13345: Enable TestCases for GenericWhitespaceCheckExamplesTest

### PR DESCRIPTION
**Pull request by chrccl**
Issue #13345: Enable TestCases for GenericWhitespaceCheckExamplesTest

### CODE REVIEW

**Comment by chrccl** [comment]
Hi @romani, can you help me with the failure checks? When i run mvn verify locally I got this error:
GenericWhitespaceCheckError
I don't understand why miss a violation when the test on the example was:
GenericWhitespaceCode

**Comment by Zopsss** [comment]
Hey @chrccl the error is trying to say that there are only 5 violations but you have provided 6 violations. Remove the following line from the `testExample2` method and try again:

```
  "21:26: " + getCheckMessage(MSG_WS_FOLLOWED, ">"),
```

**Comment by chrccl** [comment]
Hi @Zopsss  thank you for helping! Incredibly I've got the same error:
UpdateGenericCheckstyleWhitespaceError
I don't understand why I have to delete this line:
 ` "21:26: " + getCheckMessage(MSG_WS_FOLLOWED, ">"),`
In Example2.java in that line (row = 21, column = 26) there is a violation! Why don't I have to indicate it in the testExample2 method?

**Comment by MANISH-K-07** [comment]
> Hey @chrccl the error is trying to say that there are only 5 violations but you have provided 6 violations. Remove the following line from the `testExample2` method and try again:
> 
> ```
>   "21:26: " + getCheckMessage(MSG_WS_FOLLOWED, ">"),
> ```

@chrccl , if you have noticed, the whitespace after '>'  in line:17 is not a violation according to the Google Java Style Guide. 
I think the whitespace after the '>' in line:21 is also not being considered a violation. Maybe, try making the comment as '//ok, because.... ' and removing the violation as expected from 'testExample2' like Zopsss already suggested.
Or if the whole point of the check is to expect a violation for the whitespace, I think adding another whitespace ought to throw the violation.

Do correct me if I am wrong!!

**Comment by chrccl** [comment]
> > Hey @chrccl the error is trying to say that there are only 5 violations but you have provided 6 violations. Remove the following line from the `testExample2` method and try again:
> > ```
> >   "21:26: " + getCheckMessage(MSG_WS_FOLLOWED, ">"),
> > ```
> 
> @chrccl , if you have noticed, the whitespace after '>' in line:17 is not a violation according to the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace). I think the whitespace after the '>' in line:21 is also not being considered a violation. Maybe, try making the comment as '//ok, because.... ' and removing the violation as expected from 'testExample2' like Zopsss already suggested. Also modify the genericwhitespace.xml file accordingly. Or if the whole point of the check is to expect a violation for the whitespace, I think maybe adding another whitespace ought to throw the violation.
> 
> Do correct me if I am wrong!!

Hi @MANISH-K-07 and thank you too for helping me! The whitespace after '>' in line:17 is not a violation because after there isn't a method name or a constructor like in line: 21 (https://checkstyle.org/checks/whitespace/genericwhitespace.html#GenericWhitespace)
However, I tried both the idea of adding another whitespace and indicating that line with the comment 'ok, because...'; thus, modifying the genericwhitespace.xml file as well. Regarding the "double whitespace," "mvn verify" still gives me the same error. As for the second idea, the error now is as follows:
UpdateGenericCheckstyleWhitespaceError
Does anyone have any ideas?

**Comment by MANISH-K-07** [comment]
I can see in your snapshot that the issue with line:21 has been resolved?

Coming to the error at present, that is in line:22.
The problem is with the error message which you have provided in the GenericWhitespaceCheckExamplesTest.java ?

**Comment by chrccl** [comment]
> I can see in your snapshot that the issue with line:21 has been resolved?
> 
> Coming to the error at present, that is in line:22. The problem is with the error message which you have provided in the GenericWhitespaceCheckExamplesTest.java ? How about trying to change that message accordingly....?

The problem is that I provide exactly what it wants... if you see, on the left of the image there is GenericWhitespaceCheckExamplesTest.java and for line 22 I pass "MSG_WS_ILLEGAL_FOLLOW" that is the message for that violation.

**Comment by MANISH-K-07** [comment]
> > I can see in your snapshot that the issue with line:21 has been resolved?
> > Coming to the error at present, that is in line:22. The problem is with the error message which you have provided in the GenericWhitespaceCheckExamplesTest.java ? How about trying to change that message accordingly....?
> 
> The problem is that I provide exactly what it wants... if you see, on the left of the image there is GenericWhitespaceCheckExamplesTest.java and for line 22 I pass "MSG_WS_ILLEGAL_FOLLOW" that is the message for that violation. For line 21 I don't have error anymore

Is it not showing expected to match as "is not followed by whitespace.." ?
Whereas you have passed the 'MSG_WS_ILLEGAL_FOLLOW' which is showing "is followed by an illegal character." msg

**Comment by MANISH-K-07** [comment]
One step at a time.. great that line:21 isn't an issue now!!

Is it not showing expected to match as "is not followed by whitespace.." ?
Whereas you have passed the 'MSG_WS_ILLEGAL_FOLLOW' which is showing "is followed by an illegal character." msg
Maybe change the error msg in the violation comment accordingly to the second one....?

**Comment by chrccl** [comment]
> One step at a time.. great that line:21 isn't an issue now!!
> 
> Is it not showing expected to match as "is not followed by whitespace.." ? Whereas you have passed the 'MSG_WS_ILLEGAL_FOLLOW' which is showing "is followed by an illegal character." msg Maybe change the error msg in the violation comment accordingly to the second one....?

Changing the violation comment works!!!
UpdateGenericCheckstyleWhitespaceError
Thank you very much for the help!!!

**Comment by MANISH-K-07** [comment]
Thought So!!
See.. One step at a time always works....

Happy to Help!!

**Comment by sktpy** [comment]
@chrccl, you are indeed correct.
As per the documentation `List a = new ArrayList<> ();` should throw a violation as the right right angle bracket (">") precedes a constructor in this case, and therefore should not be followed with whitespace, as evident in the example shown in the [documentation](https://checkstyle.org/checks/whitespace/genericwhitespace.html#Example2-code).

I have created an issue for the same, so that it doesn't goes unnoticed in this closed PR.

Also, for future reference, there is no need to close an existing PR and reopen another for doing some changes.
You can add additional changes by pushing new commits to your branch, just make sure to squash any additional commits. ([Reference](https://checkstyle.org/beginning_development.html#Starting_Development))

**Comment by chrccl** [comment]
Perfect, can you link me the issue that you have created, please? Thank you
for the tip for changing the PR instead of closing it!
Do you think that I have to create the issue for this thing linking my new
PR?
Thank you again for your help!

Il giorno mer 24 gen 2024 alle ore 19:38 Saket ***@***.***>
ha scritto:

**Comment by sktpy** [comment]
@chrccl https://github.com/checkstyle/checkstyle/issues/14344

**Pull request closed without merging**
