### PR TITLE
Issue #4365: Split and Organize Checkstyle inputs by Test for checks …

### PR DESCRIPTION
**Pull request by sharang108**
Solution for Issue #4365 

> subtask of #3891
> 
> move / do a copy of all test input files to a separate folder for all checks in header package.
> Not any other Check should use new inputs.

### CODE REVIEW

**Comment by rnveach** [comment]
@sharang108 Please re-read first post in this PR and do what it asks.
CI will need to pass before we start reviewing. Right now your tests are failing.

**Comment by sharang108** [comment]
@rnveach The local test `mvn clean verify` is showing build successful. see [Log](https://drive.google.com/open?id=0B4EGn0doEHtPLTNnYkk2R1p6aWs)

**Comment by rnveach** [comment]
@sharang108 We can't go by your local, only what our CIs say.
Start by confirming that you have committed and pushed everything from your repository.

**Comment by sharang108** [comment]
@rnveach Well you've said that if the changes pass machine test, then I can commit them and create pull request for the related issue.

**Comment by rnveach** [comment]
> Anyway what should I do next?

Did you confirm that you have committed and pushed everything from your repository?

> I don't understand the error Logs on the CIs.

https://travis-ci.org/checkstyle/checkstyle/jobs/239900704#L647
> Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: /home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/header/regexpheader/regexp.header5

After some looking, problem is because your branch is out of date. We added new tests and files, and your PR doesn't move those files so it can't find them.
Please rebase on the latest master.

**Pull request closed without merging**
