### PR TITLE
test: RequiredThis execution time of regession report

### PR DESCRIPTION
**Pull request by relentless-pursuit**
This PR tests the execution time of regession report of RequiredThis.

Diff Regression config: https://raw.githubusercontent.com/checkstyle/test-configs/main/RequireThis/all-examples-in-one/config-all-in-one.xml
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/test-configs/main/RequireThis/all-examples-in-one/list-of-projects.properties

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9830583436

**Comment by relentless-pursuit** [comment]
Example 1: 38 mins

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9833573426

**Comment by relentless-pursuit** [comment]
Example 2: 37 mins

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9838180414

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9839670468

**Comment by relentless-pursuit** [comment]
Example 4: 40 mins

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9842026489

**Comment by relentless-pursuit** [comment]
Example5: 41 mins

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9843549748

**Comment by relentless-pursuit** [comment]
Example6: 44 mins

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9844320823

**Comment by romani** [comment]
Test is done. 
No changes is required in list of projects except we need to add one more that referenced at https://github.com/checkstyle/test-configs/issues/20

**Pull request closed without merging**
