### PR TITLE
doc: Fix wording in SuppressionSingleFilter and SuppressionXpathSingleFilter

### PR DESCRIPTION
**Pull request by vanam**
Hi,
while reading documentation for [SuppressionFilter](https://checkstyle.org/filters/suppressionfilter.html) and [SuppressionXpathSingleFilter](https://checkstyle.org/filters/suppressionxpathsinglefilter.html) I found several sentences difficult to read due to grammatical errors.

Here is my attempt to fix it.

### CODE REVIEW

**Comment by romani** [comment]
thanks a lot!!
please run on your local `mvn clean verify` it will guide you on how to fix isssues.

`[ERROR]   XdocsJavaDocsTest.testAllCheckSectionJavaDocs:160->examineCheckSection:187`

**Comment by vanam** [comment]
Sorry for the inconvenience. I ended up manually writing xdoc. I thought it can be somehow generated but I didn't a way to do so at [Contributing](https://checkstyle.org/contributing.html). `mvn clean site` did not change xdoc.

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
@vanam, thanks a lot for update!!
Do not hesitate to send more contributions.

Unfortunately we didn't finish last step to do all automatically.
But xdoc files are generated by `mvn test`.  That is why we usually recommend just run run `mvn verify ` and put in commit all that changed automatically.

**Review by nrmancuso — APPROVED** [review]

**Review by rnveach — APPROVED** [review]

**Pull request merged**
