### PR TITLE
 Issue #9935: Moved all the examples from description to example section

### PR DESCRIPTION
**Pull request by AbhinavRajputEXE**
Fixes Issue #9935: Examples were in the wrong section, moved all the examples to the example section from the description section.

CommentIndentation

### CODE REVIEW

**Review by romani — CHANGES_REQUESTED** [review]
Please squash both commit in one

**Comment by romani** [comment]
Please fix CI problems.

**Comment by AbhinavRajputEXE** [comment]
Hey @romani 
I've fixed that CI problem now and all the checks were successful.
A silly mistake I made while writing the commit message when I was rebasing caused those errors.

**Comment by romani** [comment]
GitHub, generate web site

**Review by romani — APPROVED** [review]
Looks good.
Thanks a lot for fix.

**Pull request merged**
