### PR TITLE
Issue #11140: Resolve PMB_POSSIBLE_MEMORY_BLOAT issue 1

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
Related to https://github.com/checkstyle/checkstyle/issues/11140

```
PMB_POSSIBLE_MEMORY_BLOAT
This class defines static fields that are Collections, StringBuffers, or StringBuilders that do not appear to have any way to clear or reduce their size. That is, a collection is defined and has method calls like
{add(), append(), offer(), put(), ...}
with no method calls to removal methods like
{clear(), delete(), pop(), remove(), ...}
This means that the collection in question can only ever increase in size, which is a potential cause of memory bloat.

If this collection is a list, set or otherwise of static things (e.g. a List>String> for month names), consider adding all of the elements in a static initializer, which can only be called once:
 private static List<String> monthNames = new ArrayList<String>(); static { monthNames.add("January"); monthNames.add("February"); monthNames.add("March"); ... } 

```

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
GitHub, rebase

**Comment by Rahulkhinchi03** [comment]
GitHub, rebase

**Comment by nick-mancuso** [comment]
We only use this map in one method:

```
➜  checkstyle git:(master) grep -R "NAME_TO_FULL_MODULE_NAME\.get(" -B1
src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java-    private Object createFromStandardCheckSet(String name) throws CheckstyleException {
src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java:        final String fullModuleName = NAME_TO_FULL_MODULE_NAME.get(name);
--
...
```

Why can't we just use lazy initialization? It looks like the changes in this PR are just obfuscating the static initialization of ` NAME_TO_FULL_MODULE_NAME`  for spotbugs check. Please explain/ prove how your changes improve performance.

**Comment by romani** [comment]
I would rather keep suppression, than do such update that is hard to read

**Comment by nick-mancuso** [comment]
From documentation:
`If this collection is a list, set or otherwise of static things (e.g. a List>String> for month names), consider adding all of the elements in a static initializer, which can only be called once`

So, the issue is that we never remove or reduce the number of elements in this map within this class, but it is not clear to spotbugs that we do use a static initialization since we do it from another method.

I agree with @romani that we should keep suppression, but let's add a comment to the supression explaining why we keep it (readability) and link to discussion here.

**Comment by romani** [comment]
We should not update code and suppression should stay forever.

**Comment by romani** [comment]
I marked PMB_POSSIBLE_MEMORY_BLOAT as done in issue

**Pull request closed without merging**
