### PR TITLE
Remove unnecessary qualifiers. #1555

### PR DESCRIPTION
**Pull request by mkordas**
Fixes `UnnecessarilyQualifiedStaticUsage` inspection violations.

Description:
>Reports calls to static methods or accesses of static fields on the current class which are qualified with the class name. Such qualification is unnecessary, and may be safely removed.

### CODE REVIEW

**Comment by romani** [comment]
as far as I remember Eclipse will complain about that methods that static and called from non static method, I will recheck

**Comment by romani** [comment]
Here is good explanation http://stackoverflow.com/questions/2695893/why-is-it-preferable-to-call-a-static-method-statically-from-within-an-instance and i am agree this that.

**Comment by mkordas** [comment]
But I haven't added `.this` - I've just cleaned up code removing unnecessary qualifiers. IDEs display all static method in _italics_, so there's no confusion.

**Comment by romani** [comment]
it is not related to "this" it is good demarcation line between instance and class. Most likely it is old school habits.
Eclipse is not complaining about missed class name before static method, so there is no conflicts.

@rdiachenko , @sabaka , @baratali , what do you think ? please vote.

**Comment by sabaka** [comment]
I don't see anything bad in this case. Obviously we must call static methods like  MyClass.staticMethod() outside the class, but when you call it within MyClass it makes me feel like we call foreign method.

**Comment by rdiachenko** [comment]
@romani I go along with @mkordas because:
- using class name before its static methods/fields is like using ```this``` before instance methods/fields. It seems redundant and complicates code reading
- when I see such a call ```AnnotationUtility.getAnnotationHolder(ast);``` I usually suppose that ```getAnnotationHolder(ast)``` is called from some class where "some class" is definitely not the current class

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
