### PR TITLE
Fix PMD violations from 'optimizations' ruleset in Checkstyle, issue #942

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
Please comment a reason of excludes.

**Comment by mkordas** [comment]
First we need to discuss in #942 what we won't fix at all, what we want to fix as separate issue and what we want to resolve within this issue. 

This is just initial commit to enable other rules from 'optimizations' ruleset as soon as possible.

**Comment by romani** [comment]
answered, 

but lets have a rule to have a suppression with explanation (ref to issue, or comment, or .... ), see example https://github.com/checkstyle/checkstyle/blob/master/config/findbugs-exclude.xml

**Comment by mkordas** [comment]
done

**Comment by romani** [comment]
ok, but please spit into two commits , as changes are unrelated to each other

**Comment by romani** [comment]
@mkordas , please do.

**Comment by mkordas** [comment]
done

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
