### PR TITLE
Issue #12160: execution of 'R: Update github.io' with '10.3.3' faililng

### LINKED ISSUE #12160: execution of 'R: Update github.io' with '10.3.3' faililng
https://github.com/checkstyle/checkstyle/runs/8170868585?check_suite_focus=true

```
Run ./.ci/update-github-io.sh 10.3.3
TARGET_VERSION=10.3.3
error: pathspec 'checkstyle-10.3.3' did not match any file(s) known to git
Error: Process completed with exit code 1.
```

please do `git fetch ---tags` after clone.

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
Fixes #12160

### CODE REVIEW

**Comment by romani** [comment]
Please share prove of testing

**Comment by Rahulkhinchi03** [comment]
@romani please check: https://github.com/checkstyle/checkstyle/issues/12160#issuecomment-1236281156

**Review by romani — APPROVED** [review]
ok, lets try

**Review by romani — APPROVED** [review]
ok to merge

**Pull request merged**
