### PR TITLE
Issue #941: Update import ordering in google_checks.xml according to changes in Google Style Guide

### PR DESCRIPTION
**Pull request by MEZk**
#941

1) Updated import ordering in google_checks.xml according to changes Google Style Guide
2) Updated ITs
3) CustomImportOrder still has issues with checking the exact number of blank lines between groups. In addition, it allows to have one or more blank lines even if separateLineBetweenGroups is set to false. However, Google Style Guide ([section 3.3.3](https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing)) says that `If there are both static and non-static imports, a single blank line separates the two blocks. There are no other blank lines between  import statements.` As a result of the issues we cannot provide the correct configuration.

3.1) Example of wrong behavior:

``` xml
<module name="CustomImportOrder">
    <property name="sortImportsInGroupAlphabetically" value="true"/>
    <property name="separateLineBetweenGroups" value="true"/>
    <property name="customImportOrderRules" value="STATIC###THIRD_PARTY_PACKAGE"/>
</module>
```

The following code examples do not rise any violations:

``` java
import static com.puppycrawl.tools.checkstyle.utils.AnnotationUtility.containsAnnotation;
import static com.puppycrawl.tools.checkstyle.utils.AnnotationUtility.getAnnotation;


import com.puppycrawl.tools.checkstyle.checks.design.FinalClassCheck;
import com.puppycrawl.tools.checkstyle.checks.design.ThrowsCountCheck;
import com.puppycrawl.tools.checkstyle.checks.design.VisibilityModifierCheck;
import com.sun.accessibility.internal.resources.*;
import java.util.Arrays;
import java.util.BitSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.NoSuchElementException;
import javax.accessibility.Accessible;
import org.apache.commons.beanutils.converters.ArrayConverter;

public class InputCustomImportOrderValid {
}
```

``` java
import static com.puppycrawl.tools.checkstyle.utils.AnnotationUtility.containsAnnotation;
import static com.puppycrawl.tools.checkstyle.utils.AnnotationUtility.getAnnotation;

import com.puppycrawl.tools.checkstyle.checks.design.FinalClassCheck;
import com.puppycrawl.tools.checkstyle.checks.design.ThrowsCountCheck;
import com.puppycrawl.tools.checkstyle.checks.design.VisibilityModifierCheck;
import com.sun.accessibility.internal.resources.*;

import java.util.Arrays;
import java.util.BitSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.NoSuchElementException;
import javax.accessibility.Accessible;
import org.apache.commons.beanutils.converters.ArrayConverter;

public class InputCustomImportOrderValid {
}
```

``` java
import static com.puppycrawl.tools.checkstyle.utils.AnnotationUtility.containsAnnotation;
import static com.puppycrawl.tools.checkstyle.utils.AnnotationUtility.getAnnotation;

import com.puppycrawl.tools.checkstyle.checks.design.FinalClassCheck;

import com.puppycrawl.tools.checkstyle.checks.design.ThrowsCountCheck;
import com.puppycrawl.tools.checkstyle.checks.design.VisibilityModifierCheck;
import com.sun.accessibility.internal.resources.*;


import java.util.Arrays;
import java.util.BitSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.NoSuchElementException;
import javax.accessibility.Accessible;
import org.apache.commons.beanutils.converters.ArrayConverter;

public class InputCustomImportOrderValid {
}
```

3.2) Example of wrong behavio

``` xml
<module name="CustomImportOrder">
    <property name="sortImportsInGroupAlphabetically" value="true"/>
    <property name="separateLineBetweenGroups" value="false"/>
    <property name="customImportOrderRules" value="STATIC###THIRD_PARTY_PACKAGE"/>
</module>
```

The following code example does not rise any violations too:

``` java
import static com.puppycrawl.tools.checkstyle.utils.AnnotationUtility.containsAnnotation;
import static com.puppycrawl.tools.checkstyle.utils.AnnotationUtility.getAnnotation;

import com.puppycrawl.tools.checkstyle.checks.design.FinalClassCheck;
import com.puppycrawl.tools.checkstyle.checks.design.ThrowsCountCheck;
import com.puppycrawl.tools.checkstyle.checks.design.VisibilityModifierCheck;
import com.sun.accessibility.internal.resources.*;
import java.util.Arrays;
import java.util.BitSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.NoSuchElementException;
import javax.accessibility.Accessible;
import org.apache.commons.beanutils.converters.ArrayConverter;

public class InputCustomImportOrderValid {
}
```

### CODE REVIEW

**Comment by romani** [comment]
from previous PR:

> Item that I do not like is: if google simplified rules, we do not need to CustomImportOrder Check at all and should use http://checkstyle.sourceforge.net/config_imports.html#ImportOrder

is there a reason to stay on CustomImportOrder ?

**Comment by MEZk** [comment]
@romani
I think [ImportOrder](http://checkstyle.sourceforge.net/config_imports.html#ImportOrder) also has the same problems with blank lines.

**Comment by romani** [comment]
ok, lets merge this, refactoring to usage of ImportOrder could be done in separate issue.

> I think ImportOrder also has the same problems with blank lines.

it will be addressed soon. One contributor is already assigned to tackle this problem.

**Comment by romani** [comment]
> Example of wrong behavior:

@MEZk , please open issues on that cases.

**Comment by rnveach** [comment]
@MEZk Were these new issues created? I don't see any reference to this PR for them.

**Comment by MEZk** [comment]
@rnveach 
I'll create them ASAP: one for CutomImportOrder and one for ImportOrder.

**Comment by romani** [comment]
Already exists for ImportOrder - #2143 .

**Pull request merged**
