### PR TITLE
infra: test inspections on old commit

### PR DESCRIPTION
**Pull request by nrmancuso**
This is a test to see if inspections still pass on old commit, if so, it means that there was probably some change on checkstyle side that caused new failure (dependency update, etc.)

DO NOT MERGE

One of the last passing inspections builds, from commit 7a75f4de6: 
First run (original run on master 18 days ago), successful: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/15655/workflows/fb3432b8-e53f-49df-9fd4-84e67b3a6cc6/jobs/187987

Rerun (today) of same workflow after problems began, successful: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/15655/workflows/24f32664-9bda-42f8-86b3-5c6731d903e0/jobs/192336

----------------------
inspections still passes on old base commit: https://github.com/checkstyle/checkstyle/pull/12362/commits/d437572109c83ac66ca6576751f16a8b010626b5

### CODE REVIEW

**Comment by nrmancuso** [comment]
@rnveach @romani looks like something changed on Checkstyle repo side to cause violation instability

**Comment by rnveach** [comment]
@nrmancuso If Checkstyle is responsible, does this mean we missed a failure in a PR? Do we have the specific commit?

**Comment by nrmancuso** [comment]
> @nrmancuso If Checkstyle is responsible, does this mean we missed a failure in a PR? Do we have the specific commit?

From what I can tell, the first failure in master was form direct commit at: https://github.com/checkstyle/checkstyle/commit/5f165db1cee1cdb2d9ce47adbb68626e77689b3c

**Comment by nrmancuso** [comment]
Dropped commit where we started to see failure, and supression commit to test

**Comment by nrmancuso** [comment]
Now testing removal of notes on latest head of main

**Comment by nrmancuso** [comment]
Ok, seems like release notes caused instability :) Very strange. Obviously we can't remove them, but at least we figured out what to report to IDEA.

**Comment by nrmancuso** [comment]
Seems like IDEA does not the the `Notes` section :) https://github.com/checkstyle/checkstyle/pull/12362/commits/083e862dd315f090db029f14af31a62eaeb52070

**Comment by rnveach** [comment]
@nrmancuso Is this PR still needed?

**Comment by nrmancuso** [comment]
> @nrmancuso Is this PR still needed?

Yes, it is serving as a reminder to me that we need to archive some release notes.

**Comment by nrmancuso** [comment]
Release notes are archived, see https://github.com/checkstyle/checkstyle/pull/12399

Ticket is opened with IDEA, see https://youtrack.jetbrains.com/issue/IDEA-305945/DeprecatedIsStillUsed-inspection-False-negativeerror-loop-caused-by-length-of-unrelated-XML-file

I am closing this PR, it has served it's purpose.

**Pull request closed without merging**
