### PR TITLE
Issue #4539: fixed MethodCount from counting methods in wrong definition

### PR DESCRIPTION
**Pull request by rnveach**
Issue #4539

Regression to come.

### CODE REVIEW

**Comment by rnveach** [comment]
Normal module regression: http://rveach.no-ip.org/checkstyle/regression/reports/86/

**Comment by rnveach** [comment]
Single token regression: http://rveach.no-ip.org/checkstyle/regression/reports/87/

**Comment by romani** [comment]
regression is good as it shows that each scope/block become independent.

but in documentation we have:
> Checks the number of methods declared in each type. This includes the number of each scope (private, package, protected and public) as well as an overall total. 

> each type 

we need to make sure that anonymous classes are counted separately.

> as well as an overall total.

it puzzle me .... what doe sit mean.

=======================

We need to extend examples area to show how we count methods in different types and we do not mix counted between sibling inner classes.

**Comment by rnveach** [comment]
> > as well as an overall total.

> it puzzle me .... what doe sit mean.

I assume they mean, you count total number of only `private` methods in definition (`maxPrivate` property) or you can count total number of ALL methods in definition (`maxTotal` property).

I will work on documentation.

**Comment by rnveach** [comment]
> Single token regression: http://rveach.no-ip.org/checkstyle/regression/reports/87/

I accidentally copy/pasted the wrong configuration. That report has the severity set to ignore, so it is a no-exception test.

This is the real single token regression: http://rveach.no-ip.org/checkstyle/regression/reports/88/

**Comment by romani** [comment]
@rnveach , please do update in xdoc.
please recheck host rveach.no-ip.org , I got 503 error code .

**Comment by rnveach** [comment]
> I got 503 error code .

Regression is on a VM in the host. You will get that error if I happen to close the VM.
I restarted it, so reports should be up.

**Comment by romani** [comment]
> I will work on documentation.

please do.
Regression is ok, I counted some cases manually - works good.

**Comment by rnveach** [comment]
@romani I rebased and added more documentation.
Let me know if you think it needs more.

**Comment by rnveach** [comment]
Rebased on latest master for changes in test support.

**Pull request merged**
