### PR TITLE
Issue #13345: Enable StaticVariableNameCheckExamplesTest

### PR DESCRIPTION
**Pull request by kapilgahlot1998**
Issue: #13345

### CODE REVIEW

**Comment by romani** [comment]
CI is red, please investigate and fix, all should be green

**Comment by kapilgahlot1998** [comment]
@romani 
Is there a limit ?? Cirrus - JDK17 phase failed with below error
⚠️ Failed to start an instance: FAILED_PRECONDITION: Monthly compute limit exceeded!

Should I wait till the next month ??

**Comment by romani** [comment]
We should not, update us simple enough to merge safely without this CI

**Comment by romani** [comment]
GitHub, generate website

**Comment by romani** [comment]
Please look at picture at https://github.com/checkstyle/checkstyle/issues/13345

It shows that only comment content is changing, but line numbers of java code and code itself is same in all examples

**Comment by kapilgahlot1998** [comment]
I accidently pushed all the commit that came from rebase. Honestly Not sure how to fix that. I tried to fix but not able to solve. So closing this PR. Will create another one.

**Pull request closed without merging**
