### PR TITLE
Issue #3605: enable certain SAXParserFactory features.

### PR DESCRIPTION
**Pull request by liutikas**
Issue #3605: enable certain SAXParserFactory features.

### CODE REVIEW

**Comment by rnveach** [comment]
@liutikas CI is failing because of improper commit message.
Please see https://travis-ci.org/checkstyle/checkstyle/jobs/181539876#L828-L837

Also please squash all commits and keep as 1.

**Comment by liutikas** [comment]
@rnveach I updated the commit message and squashed the commits.

I looked at "IDEA Inspections Pull Request"  check and it seems that I did not add any new warnings. I am not sure why it is failing.

**Comment by rnveach** [comment]
@romani It looks like IDEA updated to newest IntelliJ version. 1255 violations.
@liutikas Please ignore IDEA as I believe this is unrelated to your change.

**Comment by romani** [comment]
@liutikas , IDEA could be ignored by you in this PR.
Please explain in issue a reason of second feature that you enabled. We need more details as we can not completely recheck your requests so we need all possible details to explain this code. There might appear some conflict of interests in future, so details are required.

**Comment by liutikas** [comment]
Sure thing, both features load-external-dtd and external-general-entities are [normally default set to true](https://xerces.apache.org/xerces2-j/features.html). Our company has set their java defaults to false as it can lead to cross scripting attacks if not handled correctly. load-external-dtd feature allows to load external DTD into a an XML document and external-general-entities feature allows to these these external DTDs in <ENTITY> elements. Using these two we are able to compose configuration files from multiple XML files. Since both of these features are enabled by default in default java set ups it should be a no-op for most checkstyle users.

**Comment by romani** [comment]
reason was moved to issue.

**Pull request merged**
