### PR TITLE
Remove empty methods. #1555

### PR DESCRIPTION
**Pull request by mkordas**
Fixes `EmptyMethod` inspection violations in test code.

Description:
>This inspection reports methods where:
- method is empty OR
- all implementations of interface method are empty OR
- method is empty itself and is overridden only by empty methods
Note that a method containing only the super() call and passing its own parameter is also considered empty.  This inspection is automatically suppressed for methods annotated with special annotations, for example, EJB annotations javax.ejb.Init and javax.ejb.Remove.

### CODE REVIEW

**Comment by romani** [comment]
please suppress that Rule or skip it for API package.
We can not change API now.

**Comment by mkordas** [comment]
Inspections in IDEA can be suppressed only by `@SuppressWarnings("inspectionName")` - do we want these in our code?

**Comment by mkordas** [comment]
Changes for API package are reverted.

**Comment by romani** [comment]
> Inspections in IDEA can be suppressed only by @SuppressWarnings("inspectionName") - do we want these in our code?

I personally dislike  any extra code/comments that some SAT (static analysys tool) force to use. 
But on the same time we use it from JDK already - SuppressWarnings("deprecated"), ....... .

**Comment by romani** [comment]
one more thought:
JDKs validation is unavoidable so it is ok to use markers/annotations to suppress smth, all other tools (FB, PMD, Checkstyle, Sonar, IntelijIdea, .................. ) are optional very overlapping and each of it try to implement features of another tool, so one day IntelijIdea could completely overlap PMD functionality with better quality and provide CI plugins to completely deprecate PMD. So one day PMD will not be used in our project but all its suppressions will stay in code.

Another though is that you read a code you want to focus on logic and do not want to see extra distructing stuff that some tool (not related to logic) have there false-positive or author wontfix it.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
