### PR TITLE
Issue #3159: Reduce the number of tasks performed by Travis CI

### PR DESCRIPTION
**Pull request by MEZk**
#3159 

@romani

1) All Travis CI's jobs were copied to Wercker CI except for generation of release notes and testing of PR format. nemo.sonarqube.com phase was commented out since I do not have permissions.
2) Cache was set up for Maven to avoid reloading of dependencies during execution.
3) I have to add ```rm -rf contribution``` for NoExceptionTests to avoid the following prblem:
wercker_issue1
4) We have to decide which phases will migrate to Wercker CI from Travis CI.
5) We have to design worckflow for Checkstyle at Wercker CI. See http://devcenter.wercker.com/docs/workflows/index.html
6) We have to create pipelines in order to execute jobs in parallel and use different containers (aka boxes) to test on different OS. The profiles can be found at https://hub.docker.com/ . Wercker CI offers free account which allows to execute two pipelines in parallel at once (http://wercker.com/pricing/). Each pipeline should set up mvn cache to the same folder.

As I see it:
screenshot at 2016-06-19 13 30 44

7) Test, compile phases should be copied to Wercker CI for sure as we faced probles with Docker (https://github.com/checkstyle/checkstyle/issues/3177). 
8) Lets create projects-for-wercker.properties. Apache Struts should definitely be there.

Wercker CI's build for my local checkstyle repo with only one pipeline (all steps are executed successively):
https://app.wercker.com/#MEZk/checkstyle/build/57666e3d7cab8d010000f304

### CODE REVIEW

**Comment by romani** [comment]
please rebase your branch, sonar problem should be resolved

**Comment by MEZk** [comment]
@romani 
The same problem after rebasing
https://travis-ci.org/checkstyle/checkstyle/jobs/138822400#L1496

**Comment by romani** [comment]
please update PR and move only "test de/fr/....." + "release notes generation" + "java8 inputs should NOT".
If all goes fine from performance perspective - we will move "NoErrorTests - xxx "
Travis will stay main CI server.

**Comment by romani** [comment]
> As I see it:

I do not think we need Windows build, we already use Appveyor (completely windows focused CI).
MacOS testing is interesting. During java8 migration we had to remove MacOS testing as Travis does not support it for now - https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L301.

**Comment by MEZk** [comment]
@romani 
>please update PR and move only "test de/fr/....." + "release notes generation" + "java8 inputs should NOT".

Done. You need to create the GITHUB_AUTH_TOKEN environment variable at Wercker CI. Wercker CI does not have environment variable which stores PR number (TRAVIS_PULL_REQUEST). That is why I use WERCKER_GIT_BRANCH and change the condition for releasenotes generation script:

```
if [[ ${WERCKER_GIT_BRANCH} != 'master' ]]; then exit 0; fi
```
The whole list of Wercker's environment variables: http://devcenter.wercker.com/docs/environment-variables/available-env-vars.html

>MacOS testing is interesting. During java8 migration we had to remove MacOS testing as Travis does not support it for now - https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L301.

Wercker CI uses docker containers and, unfortunately, I have found that Docker does not support OSx containers at all. It is possible to install Docker on OSx, but we can not create Docker container with OSx.
See http://serverfault.com/questions/607443/can-mac-os-x-be-run-inside-docker

**Comment by romani** [comment]
> Should I remove the phases which were moved to Wercker CI from Travis CI or comment them out?

remove. Git store all changes.
I sometime keep stuff as commented out as a reminder to bring it back.

**Comment by romani** [comment]
@MEZk , wercker can not relaunch certain phase of build , we can NOT put "Release notes generation" to it, as it fails due to forgotten tags on issue very often - I need simple way to relaunch it. Travis do have ability to relaunch certain phase.

**Pull request merged**
