### PR TITLE
Minor Code Style Fixes Found By Eclipse

### PR DESCRIPTION
**Pull request by rnveach**
Methods can be static
Exceptions not actually thrown
Unnecessary casts

No actual logic changed.

### CODE REVIEW

**Comment by rnveach** [comment]
Removed `Unnecessary casts` as it is preventing TC violations

**Comment by romani** [comment]
What detected all that minors ? Please put that commit message as you have two commits and no issue.

**Comment by rnveach** [comment]
Eclipse points these issues out when `Java Compiler > Errors/Warnings` is set to a `error` instead of `warn` or `ignore`.

**Comment by MEZk** [comment]
@romani 
Interesting, why StaticMethodCandidate did not catch the cases. They are false negatives I guess.

**Comment by rnveach** [comment]
@MEZk We ran into this the last time I did an update on static methods.
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/421#issuecomment-186232556
> the problem is in TokenTypes - we cannot be sure that it is not an instance variable from a parent class.

**Comment by rnveach** [comment]
@romani 
> Please put that commit message 

Done.

**Comment by romani** [comment]
merged as FF

**Pull request merged**
