### PR TITLE
Issue #3369: Added NonDex to pom.xml and .travis.yml

### PR DESCRIPTION
**Pull request by azy2**
Issue #3369

Added NonDex to prevent tests that assume a deterministic order on non-deterministic APIs.

NonDex runs the tests and randomly explores different orderings of certain APIs.

### CODE REVIEW

**Comment by romani** [comment]
I can not merge this PR as it will fail our CI:

Even on latest sources:

Test Name |	9928532 |	9969976 |	10011420 
-------------- | -------------- | -------------- | -------------- 
com.puppycrawl.tools.checkstyle.TreeWalkerTest#testAcceptableTokens |	✖ |	✔ |	✖ 
com.puppycrawl.tools.checkstyle.checks.TranslationCheckTest#testRegexpToMatchPartOfBaseName |	✖ |	✔ |	✖ 

Not sure what mean for now .... need to read about this validation

**Comment by romani** [comment]
issue #3378 is created, this PR and commit need to be reference this issue

**Comment by romani** [comment]
@azy2 , now plugin give no errors.

please do items that I mentioned in previous comment and I am ready to merge .

**Comment by azy2** [comment]
@romani I lost the fork I made this pull request with. So I am going to close this and make a new one that does all that you asked in a single commit. I'm sorry for the inconvenience.

**Pull request closed without merging**
