### PR TITLE
Issue #11163: Enforced filesize CorrectParagraph

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Part of #11163 
Enforced file size on InputAbstractJavadocCorrectParagraph file.

### CODE REVIEW

**Review by romani — APPROVED** [review]
ok to merge if CI pass

**Comment by MANISH-K-07** [comment]
It seems that the format of comments is failing somewhere. I'll check and get back in a few mins

**Comment by romani** [comment]
```
[ERROR] com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheckTest.testWithMultipleChecks -- Time elapsed: 0.003 s <<< ERROR!

com.puppycrawl.tools.checkstyle.api.CheckstyleException: Config comment not specified properly in /home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocCorrectParagraph.java

	at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.parse(InlineConfigParser.java:210)

	at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.parse(InlineConfigParser.java:190)

	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.verifyWithInlineConfigParser(AbstractModuleTestSupport.java:235)
```

it might need spaces after all properties.
We added them to ease extension of Check with new property easily, but we should not demand them, they should be optional.

**Comment by MANISH-K-07** [comment]
Yep.. I noticed that
I reverted the spaces already and tried removing excess lines inside the comment blocks.

The file had 130 lines which is just 10+ limit.. So, I didn't want to unnecessarily create a new file.
Hope this works!!

**Comment by romani** [comment]
Please split file

**Comment by MANISH-K-07** [comment]
Done.
Waiting for checks..

**Review by romani — APPROVED** [review]
Ok to merge.

**Pull request merged**
