### PR TITLE
Issue #3796: No unnecessary text shall be present in Javadoc ASTs

### PR DESCRIPTION
**Pull request by ps-sp**
Issue #3796: No unnecessary text shall be present in Javadoc ASTs

### CODE REVIEW

**Comment by ps-sp** [comment]
@rnveach @romani @Vladlis Please have a look. Thanks.

**Comment by ps-sp** [comment]
I was going to make `DetailNodeTreeStringPrinterTest` extend `BaseCheckTestSupport` for this one but I didn't. I feel it should be handled in #4381  since the refactoring of the Javadoc tests in that issue may even demand that we change their classes. This is because we sort of parse javadoc twice. Once with ANTLR and then we convert all the nodes to `DetailNode`. Right now the javadoc tests to be refactored are verifying the ANTLR parser and rightfully belong to the `JavadocParseTreeTest` class. But if we start verifying the final tree that gets generated then those tests should perhaps belong to `DetailNodeTreeStringPrinterTest`. We can discuss it further under that issue.

**Comment by rnveach** [comment]
> I feel it should be handled in #4381 

I thought we were going to make that a priority and do it next since we keep bringing it up and wanting it.

**Comment by ps-sp** [comment]
@rnveach look at [this](https://github.com/checkstyle/checkstyle/issues/4381#issuecomment-304503845). 4381 has this as a precursor. We can't do 4381 without this or else we would have to again change all the trees we create in 4381. 4381 is indeed a priority.  

Almost every line would be a change in ANTLR regression. Perhaps it would suffice to run ANTLR regression on a couple of projects with extensive javadoc ?

**Comment by ps-sp** [comment]
> We need to update all xdocs with changes to printed tree.

done.

**Comment by rnveach** [comment]
> We can't do 4381 without this or else we would have to again change all the trees we create in 4381

Seeing more changes in test wouldn't be a bad thing. Before the xdoc change, there was not a lot of differences in the tests.

**Comment by ps-sp** [comment]
@rnveach 
We will have to redo all the nodes with children for all the input files we create in 4381 if we do 4381 before this ? I too feel it is better to have this one done before 4381. Do you want me to do 4381 before this ?

**Comment by rnveach** [comment]
> you want me to do 4381 before this ?

We will finish this.

> https://ci.appveyor.com/project/Checkstyle/checkstyle/build/7927/job/v9uu51qsij0y9mcm
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.6:site (default-site) on project checkstyle: failed to get report for org.apache.maven.plugins:maven-project-info-reports-plugin: Unable to load the mojo 'dependencies' (or one of its required components) from the plugin 'org.apache.maven.plugins:maven-project-info-reports-plugin:2.9': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) No implementation for org.apache.maven.shared.jar.classes.JarClassesAnalysis was bound.
[ERROR] while locating org.apache.maven.report.projectinfo.DependenciesReport
[ERROR] at ClassRealm[plugin>org.apache.maven.plugins:maven-project-info-reports-plugin:2.9, parent: ClassRealm[plugin>org.apache.maven.plugins:maven-site-plugin:3.6, parent: sun.misc.Launcher$AppClassLoader@55f96302]] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.apache.maven.plugins:maven-project-info-reports-plugin:2.9:dependencies)

This is a weird error I haven't seen before.
I will try to restart.

**Comment by ps-sp** [comment]
@rnveach yeah thanks. `mvn -e -Pno-validations site` ended with _BUILD SUCCESS_ for me

**Comment by ps-sp** [comment]
[summary javadoc diff report](https://issue3796-diffreport1.netlify.com/protonpack/index.html)

**Comment by rnveach** [comment]
@romani This PR blocks all other @ps-sp PRs because they rely code for #4381. @ps-sp and mentor want this first before they start that issue.

**Pull request merged**
