### PR TITLE
Issue #5640: Other validations should be off during the pitest check

### PR DESCRIPTION
**Pull request by pbludov**
Issue #5640 

It looks like the Pitest minions are doing some unwanted work.
This PR will make them focus on the Pitest checks only.

### CODE REVIEW

**Comment by romani** [comment]
looks like reason of travis failure - https://github.com/travis-ci/travis-ci/issues/8600

**Comment by pbludov** [comment]
This PR affects only the `Shippable`. All other CI can be ignored.
Interesting, there is some failed pitest checks. How could it be?

**Comment by rnveach** [comment]
> Interesting, there is some failed pitest checks. How could it be?

I am looking at it some, there is only 1 difference before pitest is started in output.
> [INFO] Skipping JaCoCo execution because property jacoco.skip is set.

Pitest execution is hard to compare between 2 runs because everything is run in random order.
I noticed when profile `no-validations` is added, generated mutations drop by 45. Killed mutations drop by 47. Number of tests increase by 13.
Every mutator besides `VoidMethodCallMutator` has a difference in counts.

**Comment by rnveach** [comment]
For `com.puppycrawl.tools.checkstyle.checks.javadoc.utils` package, the only class to have different mutations is `InlineTagUtils.java`. When profile no-validations is added, mutations for the class drop by 6 from 16 to 10.

Line 68 and 108 loses all mutations. That is the only difference.

**Comment by rnveach** [comment]
Removing `<jacoco.skip>true</jacoco.skip>` from `no-validations` brings the mutations back.

**Comment by rnveach** [comment]
> InlineTagUtils.java
> Line 68 and 108 loses all mutations. That is the only difference.

Lost mutations are:
````
1. changed conditional boundary → KILLED
2. Changed increment from 1 to -1 → KILLED
3. negated conditional → KILLED
````

These changes look false. There is no +1 or conditional on these lines. jacoco must have converted these for-each loops to a for loop with an incrementer.
@pbludov Please update expected mutations in our scripts. They are false since jacoco modified the class files.

**Comment by romani** [comment]
I removed no-validation from execution at https://github.com/checkstyle/checkstyle/commit/dac8dda2f923ad67a235dd58635a94f443141946#diff-033d042b39454e8e066ab38fd89610a5 , I did it on good reason, as only "test" phase is required, not whole "verify", so we can not return `-Pno-validations` back, we need to fix problem in different way.

**Comment by rnveach** [comment]
@romani If we don't want to use the whole profile, all that should be needed is to disable jacoco. No other tool kicked in during pitest.

**Comment by romani** [comment]
I started #5644, lets see how it pass, it worked for my local.

**Comment by romani** [comment]
fixed by  #5644

**Pull request closed without merging**
