### PR TITLE
Issue #11446: Update CommentsIndentationCheckTest to use verifyWithInlineConfigParser

### PR DESCRIPTION
**Pull request by stoyanK7**
Addresses #11214  
and #11446 
 
* Updates all `CommentsIndentationCheckTest` methods to use `verifyWithInlineConfigParser()`.
* Adds violation messages to all related `InputCommentsIndentation*.java` files.

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
@stoyanK7 Can you please split this into two PRs, there are issues open for both types of changes (#11446 and #11214)

**Comment by stoyanK7** [comment]
Is it possible to split the changes into two commits in this PR since they are kind of dependent on each other and it's going to be a headache separating them? My fault for not taking this into consideration.

**Comment by Vyom-Yadav** [comment]
> Is it possible to split the changes into two commits in this PR since they are kind of dependent on each other and it's going to be a headache separating them into PRs? My fault for not taking this into consideration.

Not a problem, separate commits will also work :)

**Comment by stoyanK7** [comment]
Added the other issue in the PR as well. Somebody please run 'Check PR Description / Analyze' again.

**Review by romani — APPROVED** [review]
ok to merge

**Pull request merged**
