### PR TITLE
Issue #4373: add Spotbugs to the project

### PR DESCRIPTION
**Pull request by Nimfadora**
Issue #4373

Spotbugs was added to the project. All checks that are excluded in findbugs are also excluded here.
Generating report has shown no bugs.

### CODE REVIEW

**Comment by rnveach** [comment]
Travis failure looks valid:
````
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.1:prepare (default-cli) on project checkstyle: Can't release project due to non released dependencies :
[ERROR] com.github.hazendaz.spotbugs:spotbugs-maven-plugin:maven-plugin:3.0.5-SNAPSHOT:runtime
[ERROR] com.github.hazendaz.spotbugs:spotbugs-maven-plugin:maven-plugin:3.0.5-SNAPSHOT:runtime
````

**Comment by romani** [comment]
@Nimfadora, what a reason to use snapshot dependency.
We do not want unstable builds, please use previous released version

**Comment by Nimfadora** [comment]
@rnveach, @romani there is no release version of spotbugs maven plugin yet. Actually there is no official spotbugs plugin at all. This plugin is a fork from findbugs-plugin made by one of community members for own purpose. More about it you can read [here](https://github.com/spotbugs/spotbugs/issues/8). In #4373 @romani said it is ok to use it... Besides, I guess it is the only way to use spotbugs in parallel with findbugs since, as I understood, it is supposed to use the same plugin.

**Comment by romani** [comment]
Looks like there is no other versions, see tail of https://github.com/spotbugs/spotbugs/issues/8
@Nimfadora , let's try to use exact snapshot version:
https://oss.sonatype.org/content/repositories/snapshots/com/github/hazendaz/spotbugs/spotbugs-maven-plugin/3.0.5-SNAPSHOT/spotbugs-maven-plugin-3.0.5-20170625.010219-2.jar
Version: 3.0.5-20170625.010219-2

**Comment by romani** [comment]
@Nimfadora ,
please do update like:
```
-    <maven.spotbugs.plugin.version>3.0.5-SNAPSHOT</maven.spotbugs.plugin.version>
+    <maven.spotbugs.plugin.version>3.0.5-20170628.020218-3</maven.spotbugs.plugin.version>
```
build is passing on my side with such update.
Ones we merge this PR, author of this plugin can publish stable release.

**Comment by romani** [comment]
ok ,we failed to cheat maven release plug, it still see this as SNAPSHOT....

@Nimfadora , please make second commit in this PR to make some violation(damage the code) from spotbugs , travis item should failed. Ones it works we ask to plugin author to make a release version.

**Comment by romani** [comment]
spotbugs is failed with:
```
[INFO] --- spotbugs-maven-plugin:3.0.5-SNAPSHOT:check (default-cli) @ checkstyle ---
[INFO] BugInstance size is 300
[INFO] Error size is 0
[INFO] Total bugs: 300
```

so it is prove that it works.
@Nimfadora , thanks a lot, please remove this commit.
I asked author of this plugin to make strict release version.
So please update your first commit to reference "3.0.5" version and remove usage of "sonatype-snapshot" repo completely.
PR will hang till plugin release is done, ones it is done, I will relaunch failed CIs items and merge PR.

**Pull request merged**
