### PR TITLE
Issue #15340: created InputFormatted file for section 4.8.7 Modifiers

### PR DESCRIPTION
**Pull request by Zopsss**
#15340 

[4.8.7 Modifiers](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.8.7-modifiers)

### CODE REVIEW

**Comment by Zopsss** [comment]
Test is failing:

```

Violation lines for C:\OpenSource\checkstyle\src\it\resources\com\google\checkstyle\test\chapter4formatting\rule487modifiers\InputFormattedModifierOrder.java differ.
unexpected (34): 21, 24, 32, 37, 39, 47, 52, 57, 84, 86, 91, 93, 95, 97, 99, 129, 131, 133, 135, 137, 139, 141, 156, 158, 160, 162, 167, 169, 171, 188, 190, 198, 203, 208
---
expected       : [79, 104, 115, 214, 226, 229, 233]
but was        : [21, 24, 32, 37, 39, 47, 52, 57, 79, 84, 86, 91, 93, 95, 97, 99, 104, 115, 129, 131, 133, 135, 137, 139, 141, 156, 158, 160, 162, 167, 169, 171, 188, 190, 198, 203, 208, 214, 226, 229, 233]
```

The unexpected violations are for following type of code, this is formatted code:

```java
abstract @MyAnnotationFormatted public void fooMet1();

protected final synchronized strictfp @MyAnnotationFormatted void fooMethod7() {}

final synchronized strictfp @MyAnnotationFormatted public void fooMethod5() {}
```

Original code:

```java
abstract @MyAnnotation2 public void fooMet1();

final strictfp synchronized protected @MyAnnotation2 void fooMethod7() {}

synchronized final strictfp @MyAnnotation2 public void fooMethod5() {}
```

All the unexpected violations are for similar kind of code.

The violation message is:

```
'@MyAnnotationFormatted' annotation modifier does not precede non-annotation modifiers.
```
 
There's no explicit rule mentioned for annotations, I checked both sections: [4.8.7 Modifiers](https://google.github.io/styleguide/javaguide.html#s4.8.7-modifiers), [4.8.5 Annotations](https://google.github.io/styleguide/javaguide.html#s4.8.5-annotations)

Im not sure if this is a defect from our side or google side. Should we keep such code?

**Comment by Zopsss** [comment]
semaphore can be ignored

**Review by romani — APPROVED** [review]
ok to merge,

but issue on formatter should be created

**Review by rdiachenko — APPROVED** [review]
lgtm

@Zopsss please reply with the link to the created issue, so we don't forget and this PR can be merged.

**Comment by romani** [comment]
I will keep tracking on this issue until issue is created.

**Comment by romani** [comment]
@Zopsss , please create issue on formatter

**Comment by Zopsss** [comment]
@romani @rdiachenko https://github.com/google/google-java-format/issues/1152

**Pull request merged**
