### PR TITLE
Fixed error for test permissions

### PR DESCRIPTION
**Pull request by MaksimP**

### CODE REVIEW

**Comment by romani** [comment]
I did additional update in shell file 54058853b973e93b85677b09a840e136c41e6285 , please take a look.

**Comment by MaksimP** [comment]
Shell works on the TravisCI is not correct. I made a mistake LF - CRLF. Git indexed, but not given to add a commit and i added space. Bug LF-CRLF removed, but  TravisCI not working correct. It works on turnover. Hi display valid files.
https://travis-ci.org/checkstyle/checkstyle/jobs/189112523

**Comment by MaksimP** [comment]
on my computer works fine

**Comment by romani** [comment]
Next time please share such nuaces in PR description.
Please redo your changes on latest code.

**Comment by rnveach** [comment]
@romani Master is failing on this new test.
See: https://travis-ci.org/checkstyle/checkstyle/jobs/189184883#L192

**Pull request closed without merging**
