### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by romani**

### CODE REVIEW

**Comment by rnveach** [comment]
It looks to me like this PR is trying to undo some recent changes we made to the properties.

**Comment by strkkk** [comment]
I triggered sync in crowdin, so changes are picked up. 

There are some issues - translations for metadata are not translated.

@romani it looks like our project is suspended, as page https://crowdin.com/translate/checkstyle/47/en-es shows (I tried to change spanish translation)

**Comment by romani** [comment]
I filled form for free open source usage yesterday, may be next week we become unblocked.

**Comment by romani** [comment]
We are approved as OSS organization, @strkkk please proceed

**Comment by strkkk** [comment]
to test post processor that crowdin support provided, I will close this PR, remove branch and do resync to create other PR

**Pull request closed without merging**
