### PR TITLE
Issue #3117: Add ability to differentiate annotation placement in foreach, for loops, parameter definition

### PR DESCRIPTION
**Pull request by MEZk**
#3117 

@romani 
Fixed for foreach, for loops, catch, method, lambdas parameters.
I'm not able to generate regression reports against Apache-Apex, as I have got the following exceptions (before and after changes):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.apache.maven.jxr.pacman.JavaFileImpl.parse(JavaFileImpl.java:108)
	at org.apache.maven.jxr.pacman.JavaFileImpl.<init>(JavaFileImpl.java:64)
	at org.apache.maven.jxr.pacman.FileManager.getFile(FileManager.java:68)
	at org.apache.maven.jxr.pacman.PackageManager.parse(PackageManager.java:123)
	at org.apache.maven.jxr.pacman.PackageManager.process(PackageManager.java:161)
	at org.apache.maven.jxr.JXR.xref(JXR.java:262)
	at org.apache.maven.plugin.jxr.AbstractJxrReport.createXref(AbstractJxrReport.java:279)
	at org.apache.maven.plugin.jxr.AbstractJxrReport.executeReport(AbstractJxrReport.java:473)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

However,  I generated regression reports against the following projects:
1) pmd
2) lombok
3) spring-framework
4) java-design-patterns
5) MaterialDesignLibrary
6) Hbase
7) apache-ant
8) apache-jsecurity
9) android-launcher
10) infinispan
11) protonpack
12) jOOL
13) RxJava
14) checkstyle-with-excludes
15) sevntu-checkstyle-with-excludes
16) findbugs-with-excldues
17) hibernate-orm-with-excludes
18) guava-mvnstyle

with the following configuration:

```xml
<module name = "Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <module name="TreeWalker">
         <module name="AnnotationLocation">
         	 <property name="allowSamelineMultipleAnnotations" value="false"/>
         	 <property name="allowSamelineSingleParameterlessAnnotation" value="false"/>
         	 <property name="allowSamelineParameterizedAnnotation" value="false"/>
         	 <property name="tokens" value="CLASS_DEF, INTERFACE_DEF,
ENUM_DEF, METHOD_DEF, 
CTOR_DEF, VARIABLE_DEF, 
ANNOTATION_DEF, TYPECAST,
LITERAL_THROWS, IMPLEMENTS_CLAUSE, 
TYPE_ARGUMENT, LITERAL_NEW, 
DOT, ANNOTATION_FIELD_DEF"/>
         </module> 
    </module>
</module>
```

Take into account that I had to exclude PARAMETER_DEF from tokens as it produces to much noise. Reports before and after are equal which is quite strange (I can't believe that all the projects do not use annotations in foreach / for loops, for instance Spring, Hibernate). 
Nevertheless, I generated report against Guava and added PARAMETER_DEF into tokens set. As you can see from the report there is a huge regression: annotations for parameter types were removed from report after changes.
http://mezk.github.io/i3117-AnnotationLocationCheck/guava_diff/index.html

### CODE REVIEW

**Comment by romani** [comment]
> ALLOWED_ANNOTATION_POSITIONS

rename ALLOWED_SINGLELINE_ANNOTATION_PARENTS

> I can't believe that all the projects do not use annotations in foreach / for loops, for instance Spring, Hibernate

it is possible. it is java8 syntax and it do overload code with details that not required usually.
People use annotations mostly in parameters (where we declare what kind of type we need) and return types (full details on what we return), inside method code is trusted and over-protection and over-declaration do not good.

**Comment by MEZk** [comment]
@romani
>rename SINGLELINE_ANNOTATION_PARENTS

Done

>it is not a regression , it huge step forward to correct validation. As all such cases are valid and making them multi-line will damage readability

Yes, I ment that there were many differencies in reports between and after changes.

Few more reports.
[hibernate](http://mezk.github.io/i3117-AnnotationLocationCheck/hibernate_diff)
[Hbase](http://mezk.github.io/i3117-AnnotationLocationCheck/HBase_diff)
[Apache-Struts](http://mezk.github.io/i3117-AnnotationLocationCheck/struts_diff)
[spring](http://mezk.github.io/i3117-AnnotationLocationCheck/spring_diff)
[findbugs](http://mezk.github.io/i3117-AnnotationLocationCheck/findbugs_diff)
[guava](http://mezk.github.io/i3117-AnnotationLocationCheck/guava_diff)

Config:
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name = "Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <module name="TreeWalker">
         <module name="AnnotationLocation">
         	 <property name="allowSamelineMultipleAnnotations" value="false"/>
         	 <property name="allowSamelineSingleParameterlessAnnotation" value="false"/>
         	 <property name="allowSamelineParameterizedAnnotation" value="false"/>
         	 <property name="tokens" value="CLASS_DEF, INTERFACE_DEF,
         	 ENUM_DEF, METHOD_DEF,
         	 CTOR_DEF, VARIABLE_DEF,
         	 PARAMETER_DEF, ANNOTATION_DEF,
         	 TYPECAST, LITERAL_THROWS,
         	 IMPLEMENTS_CLAUSE, TYPE_ARGUMENT,
         	 LITERAL_NEW, DOT, ANNOTATION_FIELD_DEF"/>
         </module> 
    </module>
</module>
```

**Comment by romani** [comment]
@MEZk , I fixed leftovers from 1.7 -> 1.8 migration, please rebase your branch on master.

**Comment by MEZk** [comment]
@romani 
Looks like Cobertura does not support java 8 properly. Should I replace searching in stream with simple loop ?

**Comment by romani** [comment]
Please create issue on cobertura and use old syntax.

Please deactivate dsm plugin in separate PR. Issue is already created.

Ignore sonar for now.

**Comment by MEZk** [comment]
@romani 
>Please create issue on cobertura and use old syntax.

Done. See https://github.com/mojohaus/cobertura-maven-plugin/issues/21 . Cobertura instrumentation and check phases work OK, but cobertura report generation phase does not support java 1.8.

>Please deactivate dsm plugin in separate PR. Issue is already created.

Done. See https://github.com/checkstyle/checkstyle/pull/3291

**Comment by romani** [comment]
@MEZk , just an idea, if report generation is problematic, could we skip report generation for problematic files ?

**Pull request merged**
