### PR TITLE
Issue #9463: update example of AST for TokenTypes.LITERAL_BOOLEAN

### PR DESCRIPTION
**Pull request by Venkatesh-24**
Closes: #9463

Screenshot from 2021-11-15 12-33-37

```
**Test.java**
public class Test { 
  public boolean flag;
}

**AST**
java -jar checkstyle-9.0.1-all.jar -t Test.java
`--CLASS_DEF -> CLASS_DEF [4:0]
    |--MODIFIERS -> MODIFIERS [4:0]
    |   `--LITERAL_PUBLIC -> public [4:0]
    |--LITERAL_CLASS -> class [4:7]
    |--IDENT -> Test [4:13]
    `--OBJBLOCK -> OBJBLOCK [4:18]
        |--LCURLY -> { [4:18]
        |--VARIABLE_DEF -> VARIABLE_DEF [5:2]
        |   |--MODIFIERS -> MODIFIERS [5:2]
        |   |   `--LITERAL_PUBLIC -> public [5:2]
        |   |--TYPE -> TYPE [5:9]
        |   |   `--LITERAL_BOOLEAN -> boolean [5:9]
        |   |--IDENT -> flag [5:17]
        |   `--SEMI -> ; [5:21]
        `--RCURLY -> } [6:0]

# Printing the code that we care
java -jar checkstyle-9.0.1-all.jar -t Test.java | grep 5:
|--VARIABLE_DEF -> VARIABLE_DEF [5:2]
|   |--MODIFIERS -> MODIFIERS [5:2]
|   |   `--LITERAL_PUBLIC -> public [5:2]
|   |--TYPE -> TYPE [5:9]
|   |   `--LITERAL_BOOLEAN -> boolean [5:9]
|   |--IDENT -> flag [5:17]
|   `--SEMI -> ; [5:21]
```
**Expected update for javadoc**

```
VARIABLE_DEF -> VARIABLE_DEF
  |--MODIFIERS -> MODIFIERS
  |   `--LITERAL_PUBLIC -> public
  |--TYPE -> TYPE
  |   `--LITERAL_BOOLEAN -> boolean
  |--IDENT -> flag
  `--SEMI -> ;
```

### CODE REVIEW

**Comment by Venkatesh-24** [comment]
please review it @romani

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
Please fix CI https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=6108&view=logs&j=89cf5cab-37fd-5e09-60f8-9a1742bde19b&t=f89aed60-e6d5-5750-95ad-83cc60b84b61&l=1147

**Comment by Venkatesh-24** [comment]
@romani can you please point me to some resource which tells what caused this error openjdk 11 verify is failing do I need to use open jdk instead of oracle jdk

**Comment by romani** [comment]
From my link above:
```
[INFO]      [echo] Checkstyle started (checkstyle_checks.xml): 26/11/2021 02:41:45 PM
[INFO] [checkstyle] Running Checkstyle  on 1444 files
[ERROR] [checkstyle] [ERROR] /home/vsts/work/1/s/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:1538: Trailing whitespace is not allowed [noTrailingWhitespace]
[ERROR] [checkstyle] [ERROR] /home/vsts/work/1/s/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:1553: Trailing whitespace is not allowed [noTrailingWhitespace]
[ERROR] [checkstyle] [ERROR] /home/vsts/work/1/s/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:1554: Javadoc tag '@see' should be preceded with an empty line. [RequireEmptyLineBeforeBlockTagGroup]
[INFO]
```

**Comment by Venkatesh-24** [comment]
Thanks @romani I will do it

**Comment by Venkatesh-24** [comment]
After I made the changes I was getting merge conflicts after I resolve those conflicts I am not able to squash the commits.

**Pull request closed without merging**
