### PR TITLE
Issue #9994: Added support for LITERAL_SWITCH token in RightCurlyCheck

### LINKED ISSUE #9994: LITERAL_SWITCH token support in RightCurlyCheck
Currently [RightCurlyCheck](https://checkstyle.sourceforge.io/config_blocks.html#RightCurly) accepts a lot less tokens (18 tokens) than [LeftCurlyCheck](https://checkstyle.sourceforge.io/config_blocks.html#LeftCurly) (24 tokens).
It is unclear if this is just a mistake or if there is some underlying reason. This issue aims at adding support for `LITERAL_SWITCH` token in `RightCurlyCheck`.

Solving this issue will help solve Issue #3547(Child issue of #3547).

For **LeftCurlyCheck**:-
```
$ cat Test.java
public class Test{
    public static void foo() {
        switch (mode) { // violation
            case 1:
                x = 1;
                break;
            default :
                x = 0;
        }
    }
}

$ cat config_for_LITERALSwitch.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="LeftCurly">
            <property name="option" value="nl"/>
            <property name="tokens" value="LITERAL_SWITCH, LITERAL_CASE, LITERAL_DEFAULT"/>
        </module>
    </module>
</module>

$ java -jar checkstyle-8.42-all.jar -c config_for_LITERALSwitch.xml Test.java
Starting audit...
[ERROR] /home/devansu/Java_Development/Test.java:3:23: '{' at column 23 should be on a new line. [LeftCurly]
Audit done.
Checkstyle ends with 1 errors.
```

For **RightCurlyCheck**:-
```
$ cat Test.java
public class Test{
    public static void foo() {
        switch (mode) {
            case 1:
                x = 1;
                break;
            default :
                x = 0; } // expected violation
    }
}


$ cat config_for_LITERALSwitch.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="RightCurly">
          <property name="option" value="alone"/>
        </module>
    </module>
</module>

$ java -jar checkstyle-8.42-all.jar -c config_for_LITERALSwitch.xml Test.java
Starting audit...
Audit done.
```
Expected:- Violation for the right curly brace(on 4:27) or a way to enable violation on this token.

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
Closes #9994 
LITERAL_SWITCH token support added in RightCurlyCheck.

P.S:- This PR is still incomplete and I am working on it. I am adding changes and will add the Diff Regression reports once done with these changes.

### CODE REVIEW

**Comment by rnveach** [comment]
@Devansu-Yadav Do you plan to continue this? This PR looks like it will need to add new test cases to show that the new token is working as expected.

**Comment by Devansu-Yadav** [comment]
@rnveach I want to continue working on this PR. I need a little bit of help. Should I proceed with implementing this method? [https://github.com/checkstyle/checkstyle/issues/9994#issuecomment-838714231]()

**Comment by rnveach** [comment]
@Devansu-Yadav ping

**Comment by Devansu-Yadav** [comment]
@rnveach Apologies for being inactive here. I was a bit busy with academics and internships. I am working on this issue and will be pushing more changes.

**Comment by Devansu-Yadav** [comment]
@rnveach @romani Just to give you an update, I have made some changes to add the support for `LITERAL_SWITCH` token and the next step for me is to write tests to check the functionality of this token.

**Comment by rnveach** [comment]
@Devansu-Yadav ping

**Comment by Devansu-Yadav** [comment]
> @Devansu-Yadav ping

@rnveach I'm still working on the Unit tests. I'll be pushing the changes soon.

**Comment by Devansu-Yadav** [comment]
@romani @rnveach Apologies for the delay in updates for this PR. Unfortunately, I won't be able to continue working on this PR due to multiple other commitments like Academics and Internships. I tried my best to find out time to finish off the work on this PR but I haven't been able to do so :(

Please assign this issue to other contributors who would like to take this up. Feel free to close this PR since incomplete work would make it very difficult for anyone to take up this issue and continue the work. I'll try my best to help/support any contributor who takes up this issue. Apologies for my inactivity on this issue for so long 😅

**Comment by nmancus1** [comment]
Author is unable to continue PR, anyone is welcome to reuse code and continue work on this issue.

**Pull request closed without merging**
