### PR TITLE
Added column number into violation messages for RightCurlyCheck and LeftCurlyCheck, issue #1511.

### PR DESCRIPTION
**Pull request by MEZk**
1) Added column number into violation messages for RightCurlyCheck and LeftCurlyCheck, issue #1511.
3) Done refactoring of [validate] (https://github.com/checkstyle/checkstyle/commit/8572e8c4f3533a43a34b81279a33adaf87f0a354#diff-9b2a5f9e69b254b923cb4fd7420cb9a4R180) to make it static.
4) Added if/else at [visitToken](https://github.com/checkstyle/checkstyle/commit/8572e8c4f3533a43a34b81279a33adaf87f0a354#diff-9b2a5f9e69b254b923cb4fd7420cb9a4R159) to save performance since an array which is returned by getLines() [is used inside validate](https://github.com/checkstyle/checkstyle/commit/8572e8c4f3533a43a34b81279a33adaf87f0a354#diff-9b2a5f9e69b254b923cb4fd7420cb9a4R217) only when ```shouldStartLine = true ``` . 
5) Updated UTs / ITs.
6) Replaced tabs with whitespaces at [test inputs](https://github.com/checkstyle/checkstyle/commit/8572e8c4f3533a43a34b81279a33adaf87f0a354#diff-3e07270ac2c8370f3e36b5345cfbc68fL56)

7) 
>
public void setShouldStartLine(boolean flag) {
add to javadoc

What did you mean? ```setShouldStartLine```  has been already explained in [javadoc](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L101) and [xdoc](https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_blocks.xml#L502).

### CODE REVIEW

**Comment by romani** [comment]
1)
>      try {
         ...
     }
     finally {

please add "}" as the end of structure at new line, it is not good to have partly compilable code.

2)
too much changes, lets split, refactoring and message update to different PRs. Refactoring should be proven by reports that it does not cause regressions.

3)
> What did you mean? setShouldStartLine has been already explained in javadoc and xdoc.

https://github.com/MEZk/checkstyle/blob/8572e8c4f3533a43a34b81279a33adaf87f0a354/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
It is missed in javadoc of the class .

**Comment by MEZk** [comment]
@romani 
1) Done.
2) Removed changes caused by refactoring.
3) Done.

**Comment by romani** [comment]
> Variable shouldStartLine sets whether the check

variable? please look like options are described in other Checks.

**Comment by romani** [comment]
> +line.alone=''{0}'' at column {1} should be alone on a line.

we need to update international messages as we introduce new parameter, messages generation could fail. Please do that by automatic translators.

**Comment by MEZk** [comment]
@romani 
>we need to update international messages as we introduce new parameter, messages generation could fail. Please do that by automatic translators.

Done.

**Comment by romani** [comment]
merged as FF, I did not close issue as I am waiting postponed PR with 
refactoring

**Pull request closed without merging**
