### PR TITLE
IndentationCheck. Refactoring: got rid of anonymous classes.

### PR DESCRIPTION
**Pull request by pirat9600q**
Got rid of anonymous classes.

### CODE REVIEW

**Comment by romani** [comment]
@pirat9600q , please fix build failure - https://travis-ci.org/checkstyle/checkstyle/jobs/50946871#L3552

please confirm that your changes does not change behaviour  in UTs, google-style-config-test and over guava with only one Check activated. Please always do that.

**Comment by pirat9600q** [comment]
Fixed build failure.
Reports for guava with only one(Indentation) Check enabled.
[Before Refactoring](http://pirat9600q.github.io/IndentationCheck_beforeRefactoring/checkstyle.html)
[After refactoring](http://pirat9600q.github.io/IndentationCheck_afterRefactoring/checkstyle.html)
results for google-style-config-test will be provided later.

**Comment by romani** [comment]
Please make Check configuration as it is in google_checks.xml and validate over guava 17 as we did in or report.

**Comment by pirat9600q** [comment]
Check is already configured as it is in google_checks.xml.
Checkstyle-tester configurations used to generate reports are:
[old Check](https://github.com/pirat9600q/checkstyle-tester/tree/Checkstyle_IndentationCheck)
[new Check](https://github.com/pirat9600q/checkstyle-tester/tree/Checkstyle_IndentationCheck_refactored)

**Comment by romani** [comment]
@pirat9600q ,

> - public final DetailAST getFirstNode()
+ protected final DetailAST getFirstNode()

I am not sure why you did that change , please explain.

**Comment by romani** [comment]
merged as FF.

**Pull request closed without merging**
