### PR TITLE
Issue #6858: Remove TreeWalker#validateDefaultTokens

### PR DESCRIPTION
**Pull request by strkkk**
#6858

### CODE REVIEW

**Comment by rnveach** [comment]
@strkkk Please fix CI and undo alot of the unnecessary formatting changes not related to the issue.

**Comment by romani** [comment]
@strkkk , please try to figure out and share with us reason (probably some ide setting) of such unnecessary changes

**Comment by strkkk** [comment]
Nevermind, I removed all changes except things that related with issue.

**Comment by strkkk** [comment]
CI is green now. It looks like code that was deleted hid some missing things in tests, I added them to make pitest happy.

**Pull request merged**
