### PR TITLE
Issue #5232 check os and linux

### PR DESCRIPTION
**Pull request by jirawat001**
add check to Os because not check to same os

### CODE REVIEW

**Comment by rnveach** [comment]
@jirawat001 What is this change for? You don't reference an issue number.

**Comment by romani** [comment]
We do not merge fixes that do not have wide explanation , please provide , in other case this PR will be closed

**Comment by jirawat001** [comment]
This is PR can to merge?

**Comment by romani** [comment]
please clearly describe where exactly you have problem, and share full log of build if you have build failure.
I need a lot of details/logs/explanation on why this is required.

This update is not required at all, we are completely ok. ALL CIs are green without it.

Please make sure all CIs in this PR are green. We do not merge PR that can not pass CIs.

**Comment by romani** [comment]
no details provided , I am closing this PR.

**Pull request closed without merging**
