### PR TITLE
Branch input executable statement count

### PR DESCRIPTION
**Pull request by GabrielBercaru**
Issue: #3991

### CODE REVIEW

**Comment by MEZk** [comment]
Please follow [PR rules](https://github.com/checkstyle/checkstyle/wiki/PR-rules).

**Comment by GabrielBercaru** [comment]
Can you please tell me what point on the PR rules page is not ok?

**Comment by MEZk** [comment]
@GabrielBercaru 
Point 2.

**Comment by rnveach** [comment]
@GabrielBercaru You do not need to close this PR and start a new one. Just force push your changes to the existing branch and git will automatically notice the changes and update the PR and the CIs.

**Pull request closed without merging**
