### PR TITLE
Issue #8908: Do clean in all Travis maven commands

### LINKED ISSUE #8908: Do clean in all Travis maven commands
from https://github.com/checkstyle/checkstyle/pull/8906#issuecomment-712854492

https://travis-ci.org/github/checkstyle/checkstyle/jobs/737307315#L669
```
[INFO] --- spotbugs-maven-plugin:4.1.4:spotbugs (spotbugs) @ checkstyle ---
[INFO] Fork Value is true
     [java] The following classes needed for analysis were missing:
     [java]   org.jacoco.agent.rt.internal_f3994fa.Offline
[INFO] Done SpotBugs
```

The same at master build
https://travis-ci.org/github/checkstyle/checkstyle/jobs/736045569#L634

problem is caused by fact that we do build to warm up local maven repo
https://travis-ci.org/github/checkstyle/checkstyle/jobs/736045569#L256 (in batch mode to not exceed log size limit), and next maven command with spotbugs doesnot use `mvn clean`, so test jars with jacoco are reused.

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #8908

### CODE REVIEW

**Comment by romani** [comment]
@shashwatj07 , root problem is this line 
https://github.com/checkstyle/checkstyle/blob/7e16783f521e2a96f6c33f9c2bd4b59387ad78a8/.travis.yml#L329

so it is Travis specific problem only due to local cache creation, limitation of Trvis on log size, ..... .

please put command `mvn clean` after  L329 and issue will be resolved.

**Review by romani — CHANGES_REQUESTED** [review]
see comment above

**Comment by shashwatj07** [comment]
I'm sorry. My bad.
It's done now. @romani

**Comment by romani** [comment]
It is not your bad, I was by bad to made bad issue description and mislead on solution.
your solution triggered extra thoughts in my mind that we do something wrong .....

Thanks a lot for fix.

**Review by romani — APPROVED** [review]
ok to merge is CI green

there will be failure as we demand "-e" for all mvn commands.
please do `mvn -e clean`

**Comment by romani** [comment]
@shashwatj07 , ^^

**Comment by shashwatj07** [comment]
> please do `mvn -e clean`

done

**Pull request merged**
