### PR TITLE
Issue #7725: Update AbstractChecks to log DetailAST - AvoidStarImport

### PR DESCRIPTION
**Pull request by akki111singh**
Fixes Issue #7725 
Log update:
https://github.com/checkstyle/checkstyle/blob/abf829f542023e089c741c55f73098cae52dcb12/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java#L240

diff report:
https://akki111singh.github.io/diff/index.html

### CODE REVIEW

**Comment by akki111singh** [comment]
@romani please review

**Comment by rnveach** [comment]
@akki111singh Please rebase on latest master. There is conflicts.

**Comment by romani** [comment]
@akki111singh , please rebase to resolve conflicts.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/wiki/PR-rules
See item 2. You should only have 1 commit in this PR. You shouldn't have any merge commits.

**Comment by akki111singh** [comment]
> https://akki111singh.github.io/diff
> Regression report is incorrect. For this kind of change we are expecting differences just like our UTs.
> https://akki111singh.github.io/diff/android-launcher/index.html
> `AvoidStarImport` is not in the config and you are not testing `ThrowsCount`. Please add your check to this config and re-run regression.

Done

**Comment by akki111singh** [comment]
> https://github.com/checkstyle/checkstyle/wiki/PR-rules
> See item 2. You should only have 1 commit in this PR. You shouldn't have any merge commits.

done @rnveach

**Pull request merged**
