### PR TITLE
Issue #10659: Migrate to Inline Config Parser in RightCurlyCheckTest

### PR DESCRIPTION
**Pull request by shashwatj07**
#10659

### CODE REVIEW

**Comment by romani** [comment]
CI is red

**Comment by shashwatj07** [comment]
> CI is red

It's because of line length exceeding 100.
Shall we support ```// 2 violations below``` and ```// 2 violations above``` comments too? It shall fix this problem here.

**Comment by romani** [comment]
>Shall we support // 2 violations below and // 2 violations above comments too? 

Yes.
We have freedom to do anything until it is clear where violation is located

**Comment by shashwatj07** [comment]
@romani https://github.com/checkstyle/checkstyle/issues/10665

**Comment by romani** [comment]
@shashwatj07 , blocker is merged, please continue

**Review by romani — APPROVED** [review]

**Pull request merged**
