### PR TITLE
Issue #13809: Kill mutation in Checker-3

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13809: Kill mutation in Checker-3

--------

Mutation 

https://github.com/checkstyle/checkstyle/blob/8c8bc0c6102823206ca3a562b01b26882fc242fa/config/pitest-suppressions/pitest-common-suppressions.xml#L21-L28

### CODE REVIEW

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by rdiachenko** [comment]
rebased

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

No decompiler seems to get it right [mutant2.class.gz](https://github.com/checkstyle/checkstyle/files/13060201/mutant2.class.gz).

I can come up with different types of solution for this but strangely no decompiler gives compilable code, please try if you have time.

**Comment by romani** [comment]
Added to https://github.com/checkstyle/checkstyle/issues/13142

**Pull request merged**
