### PR TITLE
Issue #7116: remove AbstractTypeAwareCheck and combine to JavadocMethod

### PR DESCRIPTION
**Pull request by rnveach**
Issue #7116

First PR of this issue. Removes `AbstractTypeAwareCheck` and merges it into JavadocMethodCheck.

Regression to come.

### CODE REVIEW

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/275/

No differences.

**Comment by rnveach** [comment]
TC is not listed in CI.

**Comment by rnveach** [comment]
TC still did not show up.

**Comment by romani** [comment]
Strange, and now our master build is red https://teamcity.jetbrains.com/viewLog.html?buildId=2587947&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsMaster please send fixes.

**Comment by romani** [comment]
Looks like there is auth problem between TC and GitHub , error is shown at https://teamcity.jetbrains.com/buildConfiguration/Checkstyle_IdeaInspectionsPullRequest

**Comment by romani** [comment]
not sure why, but TC lost auth credentials, I updated 
image

image

Please try again.

**Comment by rnveach** [comment]
TC still didnt show

**Comment by romani** [comment]
Your build is here https://teamcity.jetbrains.com/viewLog.html?buildId=2588296&buildTypeId=Checkstyle_IdeaInspectionsPullRequest , but still not clear why it is skipped in CI list

**Comment by rnveach** [comment]
> Private method only used from inner class (Errors) (1)
JavadocMethodCheck.java (1)
986: tryLoadClass() Method tryLoadClass()

I suppressed it for now. There is no point in trying to rewrite the code when it will be removed shortly.

**Comment by rnveach** [comment]
TC passed from the link I provided. Other CIs listed here are passing.
I will merge this.

**Pull request merged**
