### PR TITLE
Issue #2966: Upgrade maven-site-plugin to 3.5.1

### PR DESCRIPTION
**Pull request by Vladlis**
#2966

### CODE REVIEW

**Comment by romani** [comment]
Why old velosity 1.5 is used ? Latest is 1.7 .  It will trigger the same notification about old version usage.

Please add explanation comment above each override or additional dependency

**Comment by Vladlis** [comment]
> Why old velosity 1.5 is used 

Fixed
> Please add explanation comment

Added

**Comment by romani** [comment]
> add SAX2 driver

That explain nothing. Why we need this ?

**Comment by romani** [comment]
fix is merged as FF.

validation for apidocs links are enabled in linkcheck plugin.

**Pull request merged**
