### PR TITLE
Issue #3143 : maxForVoid for ReturnCount Check

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3143

**maxForVoid** counts empty return statements.
**max** counts non-empty return statements.

Any violation I wasn't sure how to fix properly, I left as a suppression. Feel free to provide any insight on the best way to fix them.

Questions:
(1)
> This code ... with maxForVoid=1 should fire violation.
private void checkThrows() {
...
        if (throwsAst == null) {
            return; /// should be violation with maxForVoid=1, as one return is at end of method
        }
....
    }

Are we sure we want to include *hidden* return statements at the end of the method in the count?
It isn't specifically written out in the code and some people may not understand that there is an implied `return` statement there.
Count for `max` is based on *written* returns, so it seems that `maxForVoid` should follow suite.
The above can show violations when `maxForVoid` is set to 0, meaning no `return` statement should be written.

### CODE REVIEW

**Comment by romani** [comment]
1)
> To disallow any returns of this type

This is hard to understand , lets be more exact "To disallow any "return;" in void retun type method ...."

2)
> private int maxForVoid = 2;

I think you made 2 by looking on "max", but as we have one return that in "hidden"(at the end of the method) we need to make "maxForVoid=1" to allow the same number of exit points as for non-void typed methods.

3)
>
```
/** Counter for return void statements. */
+        private int countVoid;
```

I think we can reuse the same class, as we count return in both cases.
how to treat this count(void or non-void) is up to Check .

4)
> Are we sure we want to include hidden return statements at the end of the method in the count?

no, lets not count it, user need to easily do "find"="return" and found all places in a code.
maxForVoid=0 - no "return" literal is expected.
maxForVoid=1 - one "return" literal is ok 
...

> Count for max is based on written returns, so it seems that maxForVoid should follow suite.

yes, right.

5)
> Any violation I wasn't sure how to fix properly, I left as a suppression. Feel free to provide any insight on the best way to fix them.

It is ok.
update for code is too big and valuable, I will take a look at suppressions after merge and provide a fix if required.

**Comment by rnveach** [comment]
Fixed 1, 2 and 3.

From XWiki test:
> [ERROR] src/main/java/org/xwiki/job/internal/DefaultJobProgress.java:[180,5] (coding) ReturnCount: Return count is 2 (max allowed is 1).

**Comment by romani** [comment]
> Travis failure is from XWiki test

Lets propose an code update to xwiki project, it will be good user acceptance testing for such typical case.
I can not merge code when CI red. We have other ways to do workaround(xwiki fork and update) but CI should be green to let me merge.

**Comment by rnveach** [comment]
PR in XWiki created, waiting for their response.

**Comment by romani** [comment]
@rnveach , looks like was blocked by commit from #3189 .
Please rebase to make CI green.

**Comment by rnveach** [comment]
@romani Done.

**Comment by romani** [comment]
merged as FF, thanks a lot !

**Comment by romani** [comment]
xwiki-commons is updated, commit 4992e06ac8edf2b7357e459f650aa42ec5e12f74

**Pull request merged**
