### PR TITLE
Issue #12327: Resolve Switch case mutation for ParenPad

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #12327: Resolve Switch case mutation for ParenPad

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/e206f8b15b0d8c04e1d6b1fbded90dbe/raw/287387889a74449dab21e1da7b07c3167e3397d1/config.xml

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
No need for regression even regular CI job find problem https://github.com/checkstyle/checkstyle/actions/runs/3304403664/jobs/5453781529#step:5:4416

**Comment by Kevin222004** [comment]
report
https://kevin222004.github.io/SolvedSwitchALL/com.puppycrawl.tools.checkstyle.checks.whitespace/ParenPadCheck.java.html

mutation was at line 250 which is totally green now :)

**Review by rnveach — APPROVED** [review]

**Review by romani — APPROVED** [review]

**Pull request merged**
