### PR TITLE
#7649 Update for Modified Control Variable

### PR DESCRIPTION
**Pull request by AnishaSrivastava1411**
Resolve issue #7649 

Example:
Screenshot from 2020-03-19 01-35-33

Example:
Screenshot from 2020-03-19 01-34-28

Output of default examples: 
Example 1:
$ cat config.xml
Screenshot from 2020-03-19 03-27-38

$ cat Test.java
Screenshot from 2020-03-19 03-28-20

Example 2:
$ cat config.xml
Screenshot from 2020-03-19 03-27-34

$ cat Test.java
Screenshot from 2020-03-19 03-28-28

$ java -jar checkstyle-8.30-all.jar -c config1.xml Test1.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - The processing instruction target matching "[xX][mM][lL]" is not allowed.:5:6
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:318)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:263)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:365)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:324)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:187)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:124)
Caused by: org.xml.sax.SAXParseException; systemId: file:/home/anisha/dir/config1.xml; lineNumber: 5; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanPIData(XMLScanner.java:745)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanPIData(XMLDocumentFragmentScannerImpl.java:1049)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanPI(XMLScanner.java:713)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:891)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:84)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:196)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:311)
	... 5 more
Checkstyle ends with 1 errors.

$ java -jar checkstyle-8.30-all.jar -c config2.xml Test2.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - The processing instruction target matching "[xX][mM][lL]" is not allowed.:5:6
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:318)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:263)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:365)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:324)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:187)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:124)
Caused by: org.xml.sax.SAXParseException; systemId: file:/home/anisha/dir/config2.xml; lineNumber: 5; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanPIData(XMLScanner.java:745)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanPIData(XMLDocumentFragmentScannerImpl.java:1049)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanPI(XMLScanner.java:713)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:891)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:84)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:196)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:311)
	... 5 more
Checkstyle ends with 1 errors.

### CODE REVIEW

**Comment by AnishaSrivastava1411** [comment]
@strkkk Request for review and please specify error, why it is failing.

**Comment by wltan** [comment]
> $ java -jar checkstyle-8.30-all.jar -c config1.xml Test1.java
> com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - The processing instruction target matching "[xX][mM][lL]" is not allowed.:5:6
> at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:318)
> at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:263)
> at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:365)
> at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:324)
> at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:187)
> at com.puppycrawl.tools.checkstyle.Main.main(Main.java:124)
> Caused by: org.xml.sax.SAXParseException; systemId: file:/home/anisha/dir/config1.xml; lineNumber: 5; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.
> at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
> at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanPIData(XMLScanner.java:745)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanPIData(XMLDocumentFragmentScannerImpl.java:1049)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanPI(XMLScanner.java:713)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:891)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
> at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
> at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
> at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
> at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
> at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
> at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:84)
> at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:196)
> at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:311)
> ... 5 more
> Checkstyle ends with 1 errors.
> 
> $ java -jar checkstyle-8.30-all.jar -c config2.xml Test2.java
> com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - The processing instruction target matching "[xX][mM][lL]" is not allowed.:5:6
> at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:318)
> at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:263)
> at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:365)
> at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:324)
> at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:187)
> at com.puppycrawl.tools.checkstyle.Main.main(Main.java:124)
> Caused by: org.xml.sax.SAXParseException; systemId: file:/home/anisha/dir/config2.xml; lineNumber: 5; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.
> at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
> at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanPIData(XMLScanner.java:745)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanPIData(XMLDocumentFragmentScannerImpl.java:1049)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanPI(XMLScanner.java:713)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:891)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
> at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
> at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
> at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
> at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
> at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
> at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
> at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:84)
> at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:196)
> at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:311)
> ... 5 more
> Checkstyle ends with 1 errors.

This doesn't look right, seems like Checkstyle somehow crashed here. Normally you would see something like `Starting Audit` and `Audit Done` instead of a stack trace.

It might be due to your UTF-8 encoding for the config file, although I'm not 100% certain.

**Comment by AnishaSrivastava1411** [comment]
@wltan Sir may you please guide, how should I resolve this.

**Comment by wltan** [comment]
> @wltan Sir may you please guide, how should I resolve this.

I'm not a mentor, no need to be so formal with me 😅

Anyway my config files usually don't have the `encoding="UTF-8"` on the first line, whereas yours does. This is what I would use:
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <module name="TreeWalker">
        <module name="ModifiedControlVariable"/>
    </module>
</module>
```
And my output will look something like this:
```
D:\checkstyletest>java -jar -Duser.language=en -Duser.country=US checkstyle-8.30-all.jar -c config.xml test\*.java 
Starting audit...
[ERROR] D:\checkstyletest\test\Test.java:4:20: Control variable 'i' is modified. [ModifiedControlVariable]
[ERROR] D:\checkstyletest\test\Test.java:5:36: Control variable 'i' is modified. [ModifiedControlVariable]
[ERROR] D:\checkstyletest\test\Test.java:8:37: Control variable 'i' is modified. [ModifiedControlVariable]
[ERROR] D:\checkstyletest\test\Test.java:11:59: Control variable 'i' is modified. [ModifiedControlVariable]
[ERROR] D:\checkstyletest\test\Test.java:12:57: Control variable 'i' is modified. [ModifiedControlVariable]
[ERROR] D:\checkstyletest\test\Test.java:20:36: Control variable 'm' is modified. [ModifiedControlVariable]
[ERROR] D:\checkstyletest\test\Test.java:27:37: Control variable 'i' is modified. [ModifiedControlVariable]
[ERROR] D:\checkstyletest\test\Test.java:28:37: Control variable 'k' is modified. [ModifiedControlVariable]
Audit done.
```
Obviously the directories won't be the same as your environment, but I hope you get the general idea on what a violation looks like.

The `encoding="UTF-8"` is the only difference I can see that causes Checkstyle to crash on your side. You can try removing it and see what happens.

This is just for the issues with the sample runs above. For the failing CI tests I'm not in a position to help as I'm not an expert on it either. Good luck!

**Comment by AnishaSrivastava1411** [comment]
@wltan Thankyou , it was helpful.
I also tried by removing UTF-8, still I am getting the same output.

**Comment by strkkk** [comment]
@AnishaSrivastava1411 Please format code in examples (indentation) and reduce amount of examples, there are too many.
And make CI happy.

**Pull request closed without merging**
