### PR TITLE
Fix FallThrough check violation in code, issue #945

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
Please explain why you have changes in Check.
why coverage violation frim coverage check ?

**Comment by mkordas** [comment]
FallThrough check detected problem in our code. This was definitely non intentional:
```java
                 case TokenTypes.PACKAGE_DEF:
                     if (ast.getLineNo() > 1 && !hasEmptyLineBefore(ast)) {
                         log(ast.getLineNo(), MSG_SHOULD_BE_SEPARATED, ast.getText());
                     }
                     if (hasNotAllowedTwoEmptyLinesBefore(ast)) {
                         log(ast.getLineNo(), MSG_MULTIPLE_LINES, ast.getText());
                     }
                 default:
                     if (nextToken.getType() != TokenTypes.RCURLY && !hasEmptyLineAfter(ast)) {
                         log(nextToken.getLineNo(), MSG_SHOULD_BE_SEPARATED, nextToken.getText());
                     }
                     if (hasNotAllowedTwoEmptyLinesBefore(ast)) {
                         log(ast.getLineNo(), MSG_MULTIPLE_LINES, ast.getText());
                     }
```
As you see` if (hasNotAllowedTwoEmptyLinesBefore(ast))` is executed twice for `TokenTypes.PACKAGE_DEF`. 

My additions are attempt to resolve that problem, and add a `break;` before `default:`.

**Comment by romani** [comment]
thanks a lot, from phone that was not clearly seen.

Please do me a favour, move "if (!hasEmptyLineAfter(ast)) {" above "if (hasNotAllowedTwoEmptyLinesBefore(ast)) {" to show that conditions are almost the same as in "default:" but a bit different.

**Comment by mkordas** [comment]
Sure, done.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
