### PR TITLE
Issue #12129: build checkstyle SNAPSHOT before execution other projects validaiton

### PR DESCRIPTION
**Pull request by romani**
Issue #12129

### CODE REVIEW

**Review by pbludov — APPROVED** [review]

**Review by rnveach — CHANGES_REQUESTED** [review]
I thought CIs already did this?

I am seeing semaphore still doing a clean install before running validation commands, so that seems like an issue and double installs.

Wercker can be ignored since it does 1 install for all runs.

`no-exception-workflow.yml` has something similar but it calls `no-exception-test.sh`. Do we want to make similar changes here?

**Comment by rnveach** [comment]
Double install
https://checkstyle.semaphoreci.com/jobs/9c21040f-4402-4a8a-9cb0-4257aaf17458#L556
https://checkstyle.semaphoreci.com/jobs/9c21040f-4402-4a8a-9cb0-4257aaf17458#L751

**Comment by romani** [comment]
@rnveach , I removed mvn install for checkstyle from semaphore

**Comment by rnveach** [comment]
> no-exception-workflow.yml has something similar but it calls no-exception-test.sh. Do we want to make similar changes here?

So is this a no?

**Comment by romani** [comment]
Such shell file operate on diff.groovy 
https://github.com/checkstyle/checkstyle/blob/master/.ci/no-exception-test.sh

Groovy do build by itself.

**Comment by rnveach** [comment]
> Groovy do build by itself.

So why do we do an install ... https://github.com/checkstyle/checkstyle/blob/master/.github/workflows/no-exception-workflow.yml#L24
Before groovy kicks in ... https://github.com/checkstyle/checkstyle/blob/master/.ci/no-exception-test.sh#L62

Isn't this another example of doing a double install?

**Comment by romani** [comment]
good catch.

https://github.com/checkstyle/contribution/blob/1b3e33600898a849791dc88c90df2bb3f80400e7/checkstyle-tester/diff.groovy#L210-L219

https://github.com/checkstyle/contribution/blob/1b3e33600898a849791dc88c90df2bb3f80400e7/checkstyle-tester/diff.groovy#L28-L33

**Comment by romani** [comment]
I removed install from `.github/workflows/no-exception-workflow.yml`

**Comment by rnveach** [comment]
Can merge when CI passes.

**Comment by romani** [comment]
Cancelled jobs are restarted

**Review by nrmancuso — APPROVED** [review]

**Pull request merged**
