### PR TITLE
update doc for ClassFanOutComplexity

### PR DESCRIPTION
**Pull request by shashwat70**
Issue #7691 

`mvn verify` passes successfully:

The website looks as follows:

### CODE REVIEW

**Comment by shashwat70** [comment]
@rnveach please help. Why did this check fail?

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/wiki/PR-rules
See item 1 through 3. Issue number must be in your commit. Running local verify will guide you on commit title format.

**Comment by rdiachenko** [comment]
@shashwat70 any update on this PR?

**Comment by shashwat70** [comment]
I was facing some issues with the forked repo. So, I re-forked it and initiated a new PR.

**Pull request closed without merging**
