### PR TITLE
Issue #3896: Test failed due to locale message settings. (with non-En…

### PR DESCRIPTION
**Pull request by Luolc**
…glish locale settings)

#3896 

http://www.luolc.com/checkstyle-diff-report/issue3896/
No difference. It is an issue about localization which can only be reproduced on a non-English environment.

### CODE REVIEW

**Comment by romani** [comment]
I did launch of your branch on my local.

I got:
```
$ mvn clean integration-test failsafe:verify -DargLine='-Duser.language=zh -Duser.country=CN'
....
Failed tests: 
  DetailNodeTreeStringPrinterTest.testParseFileWithError:65 expected:<[ERROR:0] Javadoc [comment at column 1 has parse error. Missed HTML close tag 'qwe'. Sometimes it means that close tag missed for one of previous tags.]> but was:<[ERROR:0] Javadoc [第 1 个字符解析错误。缺少 HTML 闭合标签： 'qwe'。 有时这代表前一标签未闭合。]>
```

I do reproduce on my local failure before your fix:
```
$ mvn clean integration-test failsafe:verify -DargLine='-Duser.language=zh -Duser.country=CN'
....
Failed tests: 
  HeaderCheckTest.testCacheHeaderFile:265->BaseCheckTestSupport.verify:211->BaseCheckTestSupport.verify:231->BaseCheckTestSupport.verify:262 error message 0 expected:<...InputHeader.java:1: [Missing a header - not enough lines in file.]> but was:<...InputHeader.java:1: [缺少 header - 行数不足。]>
  HeaderCheckTest.testCacheHeaderWithoutFile:289->BaseCheckTestSupport.verify:211->BaseCheckTestSupport.verify:231->BaseCheckTestSupport.verify:262 error message 0 expected:<...InputHeader.java:1: [Line does not match expected header line of 'Test'.]> but was:<...InputHeader.java:1: [当前行与被期待的 header: 'Test' 不符。]>
  HeaderCheckTest.testNotMatch:185->BaseCheckTestSupport.verify:195->BaseCheckTestSupport.verify:231->BaseCheckTestSupport.verify:262 error message 0 expected:<...igs/java2.header:2: [Line does not match expected header line of '// checkstyle: Checks Java source code for adherence to a set of rules.'.]> but was:<...igs/java2.header:2: [当前行与被期待的 header: '// checkstyle: Checks Java source code for adherence to a set of rules.' 不符。]>
  HeaderCheckTest.testStaticHeader:74->BaseCheckTestSupport.verify:195->BaseCheckTestSupport.verify:231->BaseCheckTestSupport.verify:262 error message 0 expected:<...InputHeader.java:1: [Missing a header - not enough lines in file.]> but was:<...InputHeader.java:1: [缺少 header - 行数不足。]>
```

so current CI tests are not working at all :( .

**Comment by romani** [comment]
@Luolc , I have the same UT failure for DE language (with your patch , on my local) 
```
Failed tests: 
  DetailNodeTreeStringPrinterTest.testParseFileWithError:65 expected:<[ERROR:0] [Javadoc comment at column 1 has parse error. Missed HTML close tag 'qwe'. Sometimes it means that close tag missed for one of previous tags].> but was:<[ERROR:0] [Der Javadoc-Kommentar an Position 1 führt zu einem Parserfehler. Fehlender schließender HTML-Tag 'qwe'. Manchmal bedeutet dies, dass der schließende Tag eines vorgehenden Tags fehlt].>
```

**Comment by Luolc** [comment]
@romani, So weird... It seems that we still miss smth. It is my turn who can not reproduce the bug. As you commented at https://github.com/checkstyle/checkstyle/issues/3896#issuecomment-284448568, although we can fix this specific bug quickly, the CI problem should be taken seriously. We will face similar bugs if CI is not able to validate the localization problems.

Any further suggestions? I don't know how to improve CI currently, help needed. IMO, it is better to open an new issue. Current issue describes a specific bug and does not accurately express the CI problem. Now we know there is a CI problem, but maybe after a long time people will feel puzzled.

**Comment by Luolc** [comment]
@romani 
Since I cannot reproduce the bug, it takes me more time to locate the problem. I cannot print a stack trace. It was searched manually.
The error message is thrown at https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinter.java#L91-L101, it is also a `LocalizedMessage`.

According to what we have learnt on the localization problem by now, setting the locale in specific test method should help. I update the commit, but cannot validate it on my local. Please have a check whether the fix works or not.

**Comment by rnveach** [comment]
@romani 
> Failed tests: DetailNodeTreeStringPrinterTest.testParseFileWithError

Since we have identified a cache issue for `LocalizedMessage`, maybe your issue is still the same. The only reason why someone else can't reproduce it would probably be the order the tests are run in.
If the current fix doesn't work for you, try removing the populating of the cache so the cache is never used.
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java#L299-L306
Comment lines 301, 304, and 305.
If it fixes it, its still a cache issue and order matters. Otherwise, something else is still wrong.

**Comment by Luolc** [comment]
@romani Is there anything else I could do for this PR? 😄 
The locale problem is still bothering me. I could add a `-DargLine='-Duser.language=en -Duser.country=US'` when using `mvn verify` to avoid the failure, which works well. But I don't know how to avoid it when running some other command in `.travis.yml`, like `./.ci/travis/travis.sh cobertura-check` for codecov. It will fail due to the same locale problem.

**Comment by Vladlis** [comment]
@Luolc 
Here is the command to run cobertura by maven so that you can add arguments:
https://github.com/checkstyle/checkstyle/blob/master/.ci/travis/travis.sh#L185

**Comment by Luolc** [comment]
@Vladlis Got it! I will have a try. Thanks! 😉

**Comment by romani** [comment]
@Luolc , did you try it ?

**Comment by Luolc** [comment]
@romani I cannot reproduce the failure mentioned at https://github.com/checkstyle/checkstyle/pull/3942#issuecomment-284526929 by running maven command. But the test could fail when running test inside Intellij. It is solved in the latest commit.

**Comment by Luolc** [comment]
@romani 
> The reason of problem is that for this Tests using getCheckMessage from base test class(BaseCheckTestSupport), that do load of file as resource NOT as localized bundle. Checks to loading by ResourceBundle class that is why they are localized.

I did know that. This is the most basic reason.

> Usage of ROOT in this cases will not do localization at all.

I also don't think setting locale manually inside test methods is a good practice. But in the original code, we did handle localization problem in this way. There are many locale settings in test methods among the whole project. I thought there might be some reasons which I hadn't realized yet for original contributors to handle the problem in that way. Therefore I just followed the way.

It is nice of us to make a fix to get rid of ROOT locale in test methods. But we may need a lot of refactors.

**Comment by rnveach** [comment]
@romani I agree so I am merging.

**Pull request merged**
