### PR TITLE
Issue #2237: Add basic thread-safety to Javadoc checks

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
I think it is do make sense to change our pom.xml to use multi-threading as you did at https://github.com/checkstyle/checkstyle/pull/1122 to let is be tested by Travis.

**Comment by mkordas** [comment]
@romani, I wanted to include multithreaded execution to Surefire, but then I get multiple various exceptions from PowerMock. This library is very problematic for us recently...

**Comment by romani** [comment]
merged as FF
thanks a lot for details, good to know. We need benefit from PowerMock more then quick UT launch.

**Comment by mkordas** [comment]
@romani, shouldn't we try Mockito? I think it is more reliable solution for mocking non-static and non-final methods.

**Comment by romani** [comment]
ok, but resolve problem we most likely need to get rid of PowerMock, but we need mock static methods. If coverage is not reduced I am ok to change.

**Pull request closed without merging**
