### PR TITLE
Issue #3910: CommitValidationTest: add character limit to line

### PR DESCRIPTION
**Pull request by sagar-shah94**
Issue: #3910

### CODE REVIEW

**Comment by rnveach** [comment]
I am not expecting old changes that were already merged.

@sagar-shah94 Can you rebase over the latest master.
Only changes should be the new message display. I want to make sure no undesired effects come from merging this.

**Comment by sagar-shah94** [comment]
@romani Done

**Comment by romani** [comment]
PR should contain only one commit.
please squash them in one and push with force to the existing branch.

**Comment by sagar-shah94** [comment]
@romani squashed 2 commits into 1

**Comment by sagar-shah94** [comment]
@romani please merge if it is approved.

**Comment by romani** [comment]
Here is one more place https://github.com/checkstyle/checkstyle/blob/master/.github/PULL_REQUEST_TEMPLATE.md please append text there too.

**Comment by sagar-shah94** [comment]
@romani Done.

**Comment by MEZk** [comment]
@romani 
I think it is ready to be merged.

**Pull request merged**
