### PR TITLE
Issue #4581: Reorganize token methods in coding, imports, indentation folders

### PR DESCRIPTION
**Pull request by subkrish**
Issue #4581

This PR reorganizes the token methods in `coding`, `imports`, and `indentation` folders.

### CODE REVIEW

**Comment by subkrish** [comment]
@romani @rnveach For some reason, `mvn clean verify org.pitest:pitest-maven:mutationCoverage -Ppitest-checks-coding,no-validations` is failing on Shippable but on my local machine its passing. What is the issue here?

**Comment by romani** [comment]
Failure from shippable logs:
```
Survived items:target/pit-reports/201711140637/com.puppycrawl.tools.checkstyle.checks.coding/NoFinalizerCheck.java.html:<td class='survived'> target/pit-reports/201711140637/com.puppycrawl.tools.checkstyle.checks.coding/NoFinalizerCheck.java.html:<td class='uncovered'><pre><span class='survived'> return getRequiredTokens();</span></pre></td></tr>
```

Please confirm that such method NoFinalizerCheck.getRequiredTokens is covered by mutations.

**Comment by subkrish** [comment]
@romani For some reason, even though the build passed on my local machine it did not show me the failure like it did on Shippable. Yes, those lines you have mentioned do not have coverage for mutations and failed. I will revert the changes made to the `NoFinalizerCheck` file.

**Comment by subkrish** [comment]
@rnveach @romani All CIs have passed. Please review.

**Comment by rnveach** [comment]
@subkrish 
> For some reason, even though the build passed on my local machine it did not show me the failure like it did on Shippable.

Pitest rounds, so most likely this is the issue.
Coverage could have been 99.9%, it rounds it to 100% and passes as it matches 100%. Shippable does extra test to make sure all lines are marked as covered.

**Pull request merged**
