### PR TITLE
minor: Refactoring. Add helper method. Discussed in #2232

### PR DESCRIPTION
**Pull request by ivanov-alex**

### CODE REVIEW

**Comment by mkordas** [comment]
I like this refactoring, but usually private helper methods are placed at the bottom of the class, not at the top, as they are the least significant.

**Comment by romani** [comment]
Please put issue number to front , as it us fix in scope this issues, content is minor, so minor should be after ":".

**Comment by ivanov-alex** [comment]
done

**Comment by romani** [comment]
please add space :)

**Comment by romani** [comment]
"Issue #2231: minor refactoring,  helper method was added"

**Comment by ivanov-alex** [comment]
fixed

**Comment by romani** [comment]
Merged as ff

**Pull request merged**
