### PR TITLE
Version Bumps for equalsverfier 3.0

### PR DESCRIPTION
**Pull request by rnveach**

### CODE REVIEW

**Comment by rnveach** [comment]
it seems TC doesn't recognize equalsverfier changes

**Comment by romani** [comment]
> src/test/java/com/puppycrawl/tools/checkstyle/api
 FilterSetTest.java (1)
33: testEqualsAndHashCode() JUnit test method testEqualsAndHashCode() contains no assertions 


https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/api/FilterSetTest.java

**Comment by rnveach** [comment]
@romani It seems to me we had issues before where new versions of plugins caused issues and were eventually resolved. I don't remember any specifics, but I think one was guava with new annotations.

**Comment by rnveach** [comment]
I took out jgit and rebased on the latest master to see if it is still an issue.

**Comment by rnveach** [comment]
https://teamcity.jetbrains.com/viewLog.html?buildId=1683686&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsPullRequest
TC is still failing.

**Comment by romani** [comment]
Please create issue on Intellij Idea inspections, and let's suppress new version bump to this artifact at https://github.com/checkstyle/checkstyle/blob/master/config/version-number-rules.xml with comment "till ...."

**Comment by romani** [comment]
@jqno , are you aware fo this issue with IntellijIdea ? 
You are using Idea on your side, how you resolve this problem ?

**Comment by jqno** [comment]
I don't understand how a version bump of only EqualsVerifier would cause this. Maybe the inspections have also been updated?

I have heard of this particular problem (a friend of mine has also run into it), so in EqualsVerifier 3.0 I've added a `report()` method. Now you can write something like this:

```
var ev = EqualsVerifier.forClass(Foo.class).report();
assertEquals(EqualsVerifierReport.SUCCESS, ev);
```

That way you can use EqualsVerifier with an assert, which should satisfy the checker.

**Comment by romani** [comment]
I am ok with such workaround, @rnveach please try.

**Comment by rnveach** [comment]
Done.

**Comment by rnveach** [comment]
Weird pmd passes for me locally.

**Pull request merged**
