### PR TITLE
Issue #10391: Violate original verify method and suppress errors

### LINKED ISSUE #10391: Violate original verify method and suppress errors
prerequisite for #10390

1. create rule for restricting usage of `AbstractModuleTestSupport.verify`
2. generate suppressions for violations

Note: please add extra spaces between suppressions

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #10391

### CODE REVIEW

**Comment by romani** [comment]
@shashwatj07 , do you need help in this PR ?

**Comment by shashwatj07** [comment]
> @shashwatj07 , do you need help in this PR ?

Yes, I'm unable to figure out why it is unable to resolve the API signature.

**Comment by romani** [comment]
`[ERROR] Failed to execute goal de.thetaphi:forbiddenapis:3.1:check (default) on project checkstyle: Parsing signatures failed: Class 'com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport' not found on classpath while parsing signature: com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport#verify(com.puppycrawl.tools.checkstyle.api.Configuration, java.lang.String, java.lang.String[]) -> [Help 1]`

**Comment by romani** [comment]
I used https://github.com/timurt/checkstyle/commit/0a3852052f3807651cfb72c043c07e7612e119c8 as base
updated a bit to make more separated between main and test sources.

Attention: we can not avoid global configuration of bundledSignatures (it is error during build), so I used copy-paste of all signatures.
```
          <bundledSignatures>
            <bundledSignature>jdk-non-portable</bundledSignature>
            <bundledSignature>jdk-system-out</bundledSignature>
            <bundledSignature>jdk-deprecated</bundledSignature>
            <bundledSignature>jdk-unsafe</bundledSignature>
          </bundledSignatures>
```

tested:
```
~/java/github/romani/checkstyle [timurt/issue-10391 L|✚ 1] 
$ mvn forbiddenapis:testCheck@forbiddenapis-test
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ------------------< com.puppycrawl.tools:checkstyle >-------------------
[INFO] Building checkstyle 8.46-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- forbiddenapis:3.1:testCheck (forbiddenapis-test) @ checkstyle ---
[INFO] Scanning for classes to check...
[INFO] Reading bundled API signatures: jdk-non-portable
[INFO] Reading bundled API signatures: jdk-system-out
[INFO] Reading bundled API signatures: jdk-deprecated-1.8
[INFO] Reading bundled API signatures: jdk-unsafe-1.8
[INFO] Reading API signatures: /home/rivanov/java/github/romani/checkstyle/config/signatures-test.txt
[INFO] Loading classes to check...
[INFO] Scanning classes for violations...
[ERROR] Forbidden method invocation: com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport#verify(com.puppycrawl.tools.checkstyle.api.Configuration, java.lang.String, java.lang.String[]) [Use inline config parser instead.]
[ERROR]   in com.puppycrawl.tools.checkstyle.checks.whitespace.GenericWhitespaceCheckTest (GenericWhitespaceCheckTest.java:97)
[ERROR] Forbidden method invocation: com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport#verify(com.puppycrawl.tools.checkstyle.api.Configuration, java.lang.String, java.lang.String[]) [Use inline config parser instead.]
[ERROR]   in com.puppycrawl.tools.checkstyle.checks.whitespace.GenericWhitespaceCheckTest (GenericWhitespaceCheckTest.java:107)
[ERROR] Forbidden method invocation: com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport#verify(com.puppycrawl.tools.checkstyle.api.Configuration, java.lang.String, java.lang.String[]) [Use inline config parser instead.]
[ERROR]   in com.puppycrawl.tools.checkstyle.checks.whitespace.GenericWhitespaceCheckTest (GenericWhitespaceCheckTest.java:116)
[ERROR] Forbidden method invocation: com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport#verify(com.puppycrawl.tools.checkstyle.api.Configuration, java.lang.String, java.lang.String[]) [Use inline config parser instead.]
[ERROR]   in com.puppycrawl.tools.checkstyle.checks.whitespace.GenericWhitespaceCheckTest (GenericWhitespaceCheckTest.java:123)
[ERROR] Forbidden method invocation: com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport#verify(com.puppycrawl.tools.checkstyle.api.Configuration, java.lang.String, java.lang.String[]) [Use inline config parser instead.]
[ERROR]   in com.puppycrawl.tools.checkstyle.checks.whitespace.GenericWhitespaceCheckTest (GenericWhitespaceCheckTest.java:130)
[ERROR] Forbidden method invocation: com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport#verify(com.puppycrawl.tools.checkstyle.api.Configuration, java.lang.String, java.lang.String[]) [Use inline config parser instead.]
[ERROR]   in com.puppycrawl.tools.checkstyle.checks.whitespace.GenericWhitespaceCheckTest (GenericWhitespaceCheckTest.java:137)
[ERROR] Forbidden method invocation: com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport#verify(com.puppycrawl.tools.checkstyle.api.Configuration, java.lang.String, java.lang.String[]) [Use inline config parser instead.]
[ERROR]   in com.puppycrawl.tools.checkstyle.checks.whitespace.GenericWhitespaceCheckTest (GenericWhitespaceCheckTest.java:146)
[ERROR] Forbidden method invocation: com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport#verify(com.puppycrawl.tools.checkstyle.api.Configuration, java.lang.String, java.lang.String[]) [Use inline config parser instead.]
[ERROR]   in com.puppycrawl.tools.checkstyle.checks.whitespace.GenericWhitespaceCheckTest (GenericWhitespaceCheckTest.java:153)
[ERROR] Scanned 2783 class file(s) for forbidden API invocations (in 1.46s), 8 error(s).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.309 s
[INFO] Finished at: 2021-08-01T12:51:55-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal de.thetaphi:forbiddenapis:3.1:testCheck (forbiddenapis-test) on project checkstyle: Check for forbidden API calls failed, see log. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
✘-1 ~/java/github/romani/checkstyle [timurt/issue-10391 L|✚ 1] 
12:51 $ git diff
diff --git a/pom.xml b/pom.xml
index 478706f..e386060 100644
--- a/pom.xml
+++ b/pom.xml
@@ -1547,48 +1547,36 @@
 .........
-                <exclude>**/GenericWhitespaceCheckTest.class</exclude>
+                <!-- <exclude>**/GenericWhitespaceCheckTest.class</exclude> -->
 
                 <exclude>**/IllegalThrowsCheckTest.class</exclude>
 

```

**Review by romani — APPROVED** [review]
ok to merge.

**Review by timurt — APPROVED** [review]

**Pull request merged**
