### PR TITLE
Issue #15456: Specify violation messages for UncommentedMain

### PR DESCRIPTION
**Pull request by AmitKumarDeoghoria**
Issue: #15456

### CODE REVIEW

**Comment by AmitKumarDeoghoria** [comment]
Hey @romani  @Zopsss  I made all the changes suggested. Thanks for the help and please do let me know if it's okay now.

**Comment by romani** [comment]
Please read issue one more time or see example PRs

You missed `We need to remove suppression list that we introduced at`

**Comment by AmitKumarDeoghoria** [comment]
Hey @romani removed the violation from the the suppression list. Check Once.

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
@AmitKumarDeoghoria , 
thanks a lot for help
please do one more fix in scope of this issue to make sure you can do it from first try and we can safely can more further.
thanks in advance.

**Comment by AmitKumarDeoghoria** [comment]
Thank you for the guidance, @romani . I’ll do my best to incorporate your feedback and look forward to submitting more PRs in the future.

**Pull request merged**
