### PR TITLE
Issue #2405: FinalLocalVariable false-positive in SWITCH

### PR DESCRIPTION
**Pull request by Bhavik3**

### CODE REVIEW

**Comment by Vladlis** [comment]
@Bhavik3, please, do not forget to remove the suppression (https://github.com/checkstyle/checkstyle/issues/2405#issuecomment-153898873) after the issue is fixed

**Comment by romani** [comment]
We use non snapshot version in sevntu project, i will make a reminder to myself to remove suppression. Or @Bhavik3 can send the PR with note to apply after 6.14 release.

**Comment by romani** [comment]
0) Your update is not simple so we need report over testing projects before and after fix. Please generate a diff-report by https://github.com/attatrol/ahsm 

1) please rename `scope` to `scopeVariables` for local field and class field, it is a collection so should be plural

2) 
> int foo = 1;     // line 5

Line 5 ? please remove such comments or substitide by "// violation" and "// ok"

3) please create a test cases
```
        switch (i) {
            case 1:
                int foo = 1;     // violation
                break;
            default:
        }
        switch (i) {
            case 1:
                int foo = 1;     // no violation
                break;
            default:
                foo = 2;     // no violation
                break;
        }
```

4)
```
                    for (DetailAST node : scope.values()) {
                        log(node.getLineNo(), node.getColumnNo(), MSG_KEY, node
                            .getText());
                    }
```

that is a copy-paste please move it below a switch.

**Comment by Bhavik3** [comment]
@romani 

I have made some changes in the code and generating checkstyle report.

But I am getting problem generating report. can anyone please help me.
checkstyle tester: https://github.com/Bhavik3/contribution/tree/issue2405/checkstyle-tester
Result: https://gist.github.com/Bhavik3/53eaef26e4741413aed5

**Comment by romani** [comment]
source of exception : https://maven.apache.org/plugins/maven-site-plugin/xref/org/apache/maven/plugins/site/render/ReportDocumentRenderer.html#L241
Exception info: https://docs.oracle.com/javase/7/docs/api/java/lang/LinkageError.html

you have some problem with jar
```
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.4</version>
```

I would recommend you to remove ~/.m2/reporsitory/org/apache/commons/commons-lang3  and let maven download it again.

If does not help pelase update https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/launch.sh#L81 and add "-X" parameter to mvn and provide logs again.

**Comment by romani** [comment]
@Bhavik3 , ping.

**Comment by romani** [comment]
@Bhavik3 , ping

**Comment by romani** [comment]
@Bhavik3  , release will happen on Sunday, it would be good to finish this PR before release.

**Comment by Bhavik3** [comment]
@romani 

I was out of town for two week. so could not work on it. I will finish it today.

How can I generate jar file for ahsm ?

**Comment by romani** [comment]
https://github.com/attatrol/ahsm/pull/3

**Comment by Bhavik3** [comment]
@romani 

Getting this outOfMemoryError.
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Arrays.java:2694)
        at java.lang.String.<init>(String.java:203)
        at org.jsoup.parser.CharacterReader.cacheString(CharacterReader.java:352)
        at org.jsoup.parser.CharacterReader.consumeData(CharacterReader.java:167)
        at org.jsoup.parser.TokeniserState$1.read(TokeniserState.java:27)
        at org.jsoup.parser.Tokeniser.read(Tokeniser.java:50)
        at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:49)
        at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:43)
        at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:53)
        at org.jsoup.parser.Parser.parseInput(Parser.java:30)
        at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:132)
        at org.jsoup.helper.DataUtil.load(DataUtil.java:41)
        at org.jsoup.Jsoup.parse(Jsoup.java:103)
        at attatrol.ahsm.site.SiteParser.parse(SiteParser.java:47)
        at attatrol.ahsm.Main.getContent(Main.java:206)
        at attatrol.ahsm.Main.mergingStage(Main.java:130)
        at attatrol.ahsm.Main.main(Main.java:88)
```

I think it is because of I am using many projects to test on.

**Comment by liscju** [comment]
@romani @Bhavik3 
``` Getting this outOfMemoryError. ```

Im also running into this problem frequently, even when i increase heap size(by removing line in launch.sh specifying heap size)

**Comment by romani** [comment]
@Bhavik3 , @liscju , yes not I have it during #1485 , smth is wrong I try to investigate or make reports not that big. Please generate report without ashm tool as we do before and share them.

@attatrol , we do need you assistance.

**Comment by Bhavik3** [comment]
I have generated report for these projects:
```
android-launcher|github|android/platform_packages_apps_launcher|android-2.1_r2.1p2
apache-ant|github|apache/ant|ANT_194|**apache-ant/src/tests/**/*,apache-ant/src/etc/testcases/
Hbase|github|apache/hbase|1.1.0.1
Orekit|github|CS-SI/Orekit|bc527a1
```

out of these, android-launcher and Hbase have difference in report which we needed.
http://bhavik3.github.io/ahsm_android-launcher/checkstyle_merged.html
http://bhavik3.github.io/ahsm_Hbase/checkstyle_merged.html

**Comment by romani** [comment]
merged as FF.

thanks a lot !

**Pull request merged**
