### PR TITLE
To Top button on website

### LINKED ISSUE #8533: To Top Button on website
As mentioned in #8244 a button which scrolls to the top of the page would be nice.

### PR DESCRIPTION
**Pull request by jo2**
fix #8533 

[preview](https://jo2.github.io/checkstyle-top-button-right/index.html)

### CODE REVIEW

**Comment by jo2** [comment]
I don't have access to the team city, so I can't see what the issue is with that. The AppVeyor fails due to old links (checkstyle.sourceforge.io and not checkstyle.org) being used. I didn't change those lines so I think that problems originates from somewhere else. I can fix it for this PR if you'd like, though.

**Comment by strkkk** [comment]
@jo2 
Errors from teamcity:
```
src/site/resources/js
checkstyle.js (6)
1:  JSHint: 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz). (W104)
3:  JSHint: 'arrow function syntax (=&gt;)' is only available in ES6 (use 'esversion: 6'). (W119)
4:  JSHint: Missing &quot;use strict&quot; statement. (E007)
8:  JSHint: 'arrow function syntax (=&gt;)' is only available in ES6 (use 'esversion: 6'). (W119)
14:  JSHint: 'arrow function syntax (=&gt;)' is only available in ES6 (use 'esversion: 6'). (W119)
15:  JSHint: Missing &quot;use strict&quot; statement. (E007)
```

```
src/site/resources/js
checkstyle.js (15)
1:  JSLint: Unexpected ES6 feature 'let'.
3:  JSLint: Unexpected ES6 feature '=&gt;'.
3:  JSLint: Expected '&quot;' and instead saw '''.
3:  JSLint: Undeclared 'window'.
4:  JSLint: Expected '&quot;' and instead saw '''.
5:  JSLint: Expected '&quot;' and instead saw '''.
6:  JSLint: Expected '&quot;' and instead saw '''.
8:  JSLint: Unused 'e'.
8:  JSLint: Unexpected ES6 feature '=&gt;'.
8:  JSLint: Expected '&quot;' and instead saw '''.
14:  JSLint: Undeclared 'window'.
14:  JSLint: Expected '&quot;' and instead saw '''.
14:  JSLint: Unexpected ES6 feature '=&gt;'.
16:  JSLint: Expected '&quot;' and instead saw '''.
18:  JSLint: Expected '&quot;' and instead saw '''.
```
```
src/site/resources/css
site.css (1)
127:  Convert CSS color value to HEX
```
```
src/site/resources/js
checkstyle.js (1)
15:  Magic number '500' 
```

**Comment by romani** [comment]
@jo2, did you close PR intentionally ?

**Comment by jo2** [comment]
I had errors with my git history so I had to make a force push which closed this PR.

**Pull request closed without merging**
