### PR TITLE
Issue #12458: Resolve pitest suppression for SuppressionCommentFilter

### PR DESCRIPTION
**Pull request by shubh220922**
Related to #12458 and #12341

Mutation has been hardcoded to study CI.

### CODE REVIEW

**Comment by shubh220922** [comment]
Work on this PR will resume in a few weeks upon conclusion of my exams.

**Comment by shubh220922** [comment]
I'm working on this pr now.

**Comment by shubh220922** [comment]
Diff Regression config:  https://gist.githubusercontent.com/shubh220922/36609075008b5d16b3b2afb6e759635b/raw/f510316e7ee3d1f46cef3282e5d1af1825a096e6/config.xml

**Comment by shubh220922** [comment]
Github, generate report

**Comment by romani** [comment]
@shubh220922, can you do this on your local? 
PR creates a lot of other CI executions that are prone to fail.

**Comment by shubh220922** [comment]
d

**Comment by shubh220922** [comment]
@romani it is becoming slightly difficult for me to figure out what exactly will help kill this thing.

```java
// Expand regexp for check and message
            // Does not intern Patterns with Utils.getPattern()
            String format = "";
            try {
                format = CommonUtil.fillTemplateWithStringsByRegexp(
                        filter.checkFormat, text, commentFormat);
                tagCheckRegexp = Pattern.compile(format);

                if (filter.messageFormat == null) {
                    tagMessageRegexp = null;
                }
                else {
                    format = CommonUtil.fillTemplateWithStringsByRegexp(
                            filter.messageFormat, text, commentFormat);
                    tagMessageRegexp = Pattern.compile(format);
                }

                if (filter.idFormat == null) {
                    tagIdRegexp = null;
                }
                else {
                    format = CommonUtil.fillTemplateWithStringsByRegexp(
                            filter.idFormat, text, commentFormat);
                    tagIdRegexp = Pattern.compile(format);
                }
            }
```

The mutated line is ``tagMessageRegexp = null;``
Removing assignment to ``tagMessageRegexp`` is surviving. 

I tried a lot of debugging but couldn't figure out how to kill this. 
I thought of removing that line of code but it failed that way.

``tagMessageRegexp`` would be null if and only if ``filter.messageFormat`` is null. I think rather than adding test cases to kill this mutation we could assign ``tagMessageRegexp`` null by default just like how ``messageFormat`` is null by default.

Then, we could just check if ``messageFormat`` is null or not. If it is not null then only we should proceed to assign ``tagMessageRegexp`` some not null value else ``tagMessageRegexp`` should remain null.

In simple words I want the code to be more like below:

```java
// Expand regexp for check and message
            // Does not intern Patterns with Utils.getPattern()
            String format = "";
            tagMessageRegexp = null;   //<- assign ``tagMessageRegexp`` null by default
            try {
                format = CommonUtil.fillTemplateWithStringsByRegexp(
                        filter.checkFormat, text, commentFormat);
                tagCheckRegexp = Pattern.compile(format);

                if (filter.messageFormat != null) {      //<- if condition for ``tagMessageRegexp`` is removed as it is assigned null above
                    format = CommonUtil.fillTemplateWithStringsByRegexp(
                            filter.messageFormat, text, commentFormat);
                    tagMessageRegexp = Pattern.compile(format);
                }

```

**Comment by nrmancuso** [comment]
@shubh220922 seems reasonable, please send changes. In most cases, it is better to just update PR and add a review comment yourself asking questions directly on code.

**Comment by shubh220922** [comment]
@nrmancuso yes. Im busy with exams, just in few days I'll send PR for this.

**Comment by shubh220922** [comment]
@nrmancuso 

Well it seems trying to declare it ``null`` by default isin't an option because it is declared ``final``. If I had to declare it ``null`` by default, I will have to make a suppression for it maybe. 

```java
/** The parsed message regexp, expanded for the text of this tag. */
        private final Pattern tagMessageRegexp;
```

That is the reason why I think this if else statement exists in first place:

```java
if (filter.messageFormat == null) {
                    tagMessageRegexp = null;
                }
                else {
                    format = CommonUtil.fillTemplateWithStringsByRegexp(
                            filter.messageFormat, text, commentFormat);
                    tagMessageRegexp = Pattern.compile(format);
                }
```

I'm debugging and will fix it the conventional way.

**Comment by shubh220922** [comment]
@nrmancuso please assist in this. I'm not finding any idea to kill ``tagMessageRegexp`` since ``tagMessageRegexp`` is expanded form of the regexp of the tag, where can a difference be spotted so that mutation can be killed?

**Comment by shubh220922** [comment]
@romani I'll push some changes I made soon.

Also, to bring to your notice, the documentation for SuppressionCommentFilter needs to be updated. Majority time was lost in figuring out the documentation on website.

**Comment by romani** [comment]
>  Majority time was lost in figuring out what the documentation said on website specifically for SuppressionCommentFilter.

pelase send a separate PR to update it, now you know all details and see a problem.

**Comment by shubh220922** [comment]
@romani PR incoming for that.

**Comment by shubh220922** [comment]
@romani Kindly approve the issue: https://github.com/checkstyle/checkstyle/issues/12827

**Review by romani — CHANGES_REQUESTED** [review]
I do not see any removal of suppression

**Comment by nrmancuso** [comment]
@shubh220922 where are we at on this PR?

**Comment by shubh220922** [comment]
@nrmancuso I'm sure I can kill this mutation with a bit of work as it a hard one to fix. That's why I was killing relatively easy mutants. I'll push changes for this by today.

**Comment by shubh220922** [comment]
I'll come to this issue some time later. Open for others to work on.

**Pull request closed without merging**
