### PR TITLE
config: bump guava version

### PR DESCRIPTION
**Pull request by rnveach**
guava bump.

### CODE REVIEW

**Comment by romani** [comment]
@rnveach , looks like all violations from TeamCity are valid and new changes of guava 20.
I relaunched PR on Teamcity - result is the same. Master build is stable.
Please fix TC violations in the same commit.

**Comment by rnveach** [comment]
New guava has issues with map/sets when calling `add` or `put`. For some reason it thinks these results should be examined.
I don't see why we should examine these results, so all of them will need suppressions.

The only difference between 19 and 20 for these classes was the addition of `@CanIgnoreReturnValue` to the methods, but it seems like IntelliJ doesn't recognize the annotation for its system.
https://github.com/google/guava/commit/f6da31136af15dd324d56d253bc17c5b9afe9759#diff-7ed40f507101a8625df970c98abcbc55

@romani Do we still want to update to the latest guava?

**Comment by romani** [comment]
>  Do we still want to update to the latest guava?

kind of yes, in other case we will miss updates for another libraries. We usually keep updating , right after release. Such approach have its prons and cons, but for last 2 years I see more benefits.

from TC:
> TranslationCheck.java (1)
447: checkTranslationKeys() Result of Multimap.putAll() is ignored

https://github.com/google/guava/blame/master/guava/src/com/google/common/collect/Multimap.java#L246
So boolean result was there from 2010 year as minimum, strange that we have violation only now.
but from javadoc `@return {@code true} if the multimap changed` is useful , but for us it will mean in logic as IllegalStateException and will require not simple UT. In case it is ok by logic that collection is not changed - it will be problem/violations for other tools , as they will complain about nonused variable.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PackageNamesLoader.java#L118

`Set.add` return a boolean and it is ignored, no violation from IntelijIdea.
Here is configuration of this inspection, look like we need to update its configuration : 
screenshot-intelijidea-returnisignored

**Comment by romani** [comment]
https://github.com/google/guava/issues/2629 is created.

@rnveach , for now we have two options: 
1) to put all that IntelijIdea violations to suppressions
2) figure-out  how to ignore new version of guava by our version validation - https://www.versioneye.com/user/projects/5504ca834a1064774400049a (I will investigate this)

**Comment by rnveach** [comment]
> There is no configuration to ignore certain version

I found this link that talks about muting dependencies you don't wish to incorporate: https://blog.versioneye.com/2014/11/12/mute-dependencies/
It even says `The mute feature even effects the project dependency badge.`.

**Comment by romani** [comment]
yes, guava 20 is muted for some time till guava team reply on issue. if no reply happen, we will need to update version to be up-to-date.

**Comment by rnveach** [comment]
Waiting on fix in https://youtrack.jetbrains.com/issue/IDEA-158576 which should be in IntelliJ 2016.3

**Comment by romani** [comment]
let me close this PR, I will reopen it as 2016.03 be released.

**Comment by romani** [comment]
Intelij Idea 2016.3 is released , lets try this PR one more time.....

**Comment by rnveach** [comment]
@romani TC is still failing the same, but I'm not sure it is a new fail or the same one. I don't have permission to restart TC. I can't rebase since I accidentally put this into checkstyle instead of my own repo, so I am closing this and will open a new one to reference this.

**Pull request closed without merging**
