### PR TITLE
Issue #2929: Add test to verify PR description

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
it should not be a part of Checkstyle code base (it is not related ), move it to separate project of https://github.com/checkstyle/contribution.

**Comment by mkordas** [comment]
@romani so how related is commit message validator in that case? Do you
want me to setup entire project with all quality tools for just 10 line
test?

**Comment by romani** [comment]
a bit closer as it do not use any in web - all on local. It is validation before PR , before github.
But ideally it would be good to move it out of Checkstyle too, but it is ok till it does not use web services.

Example of tool is https://github.com/checkstyle/contribution/tree/master/releasenotes-xdoc-builder - it is outside of checkstyle codebase. 

> Do you want me to setup entire project with all quality tools for just 10 line test?

create a folder under "contributions" and put 10 lines of code there. We should not pollute in main code base. Maintaining main code base become more and more complicated.

**Comment by mkordas** [comment]
@romani Do you mean I should create Maven project with all dependencies and Checkstyle + one test or I should create this test in some existing project?

**Comment by romani** [comment]
It should be a separate  project (maven , shell ,groovy ,......). 
I do not understand why you need Checkstyle as dependency, you code have no dependency on "com.puppycrawl" even now.

All it has to do is to grab TRAVIS_PULL_REQUEST from environment , issue number from commit (not all commits and PR have corresponding issues!!!, ,some PRs are referencing themself) and make sure that Issue that is referenced in commit message is referenced in PR description.

I would make it as a script (bash, groovy), it should be simple. But I am not insisting.

**Comment by mkordas** [comment]
@romani I meant Checkstyle to check code style. In case of Groovy probably I need CodeNarc? Or you want to check style manually?
For Bash I think it's a bit too complicated, as I need to use regexps and GitHub API

**Comment by romani** [comment]
> Or you want to check style manually?

I am not fanatic in "contributions" area, code should work and be just not ugly. 

> For Bash I think it's a bit too complicated, as I need to use regexps and GitHub API

it is ok to use bash, as regexp is so native in linux/unix commands. Api could be used by "curl".
I am not insisting. Just use what you comfortable with and make it work :).

**Comment by romani** [comment]
@mkordas , I am closing PR , your code should be hosted at https://github.com/checkstyle/contribution project

**Pull request closed without merging**
