### PR TITLE
config: checkerframework.version 3.27.0

### PR DESCRIPTION
**Pull request by romani**
Version bump

https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=11909&view=logs&j=1a6076f9-5826-5ba0-19ba-deaff2e35eea&t=5f46bc98-6f46-512e-6656-5fbfb1d03e4d&l=608

### CODE REVIEW

**Comment by rnveach** [comment]
````
[INFO] --- maven-enforcer-plugin:3.1.0:enforce (enforce-versions) @ checkstyle ---
Warning:  
Dependency convergence error for org.checkerframework:checker-qual:jar:3.27.0:compile paths to dependency are:
+-com.puppycrawl.tools:checkstyle:jar:10.5-SNAPSHOT
  +-org.checkerframework:checker-qual:jar:3.27.0:compile
and
+-com.puppycrawl.tools:checkstyle:jar:10.5-SNAPSHOT
  +-org.checkerframework:checker:jar:3.25.0:compile
    +-org.checkerframework:checker-qual:jar:3.25.0:runtime
and
+-com.puppycrawl.tools:checkstyle:jar:10.5-SNAPSHOT
  +-org.checkerframework:checker:jar:3.25.0:compile
    +-org.checkerframework:checker-util:jar:3.25.0:runtime
      +-org.checkerframework:checker-qual:jar:3.25.0:runtime

Error:  Rule 2: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
````

**Comment by rnveach** [comment]
> New surviving error(s) found:
> Unnecessary suppressed error(s) found and should be removed:

Looks like `checkstyle` was removed inside `@LTLengthOf`.

**Comment by rnveach** [comment]
I pushed an update.

**Comment by romani** [comment]
I think we can merge.
Drone CI doesn't want to run, I tried to restart, no effect.

**Review by rnveach — APPROVED** [review]

**Pull request merged**
