### PR TITLE
Issue #6207: Expanded regression testing for LocalVariableName

### PR DESCRIPTION
**Pull request by SteLeo1602**
Issue: #6207  
[LocalVariableName check documentation](https://checkstyle.org/checks/naming/localvariablename.html#LocalVariableName)

### CODE REVIEW

**Comment by romani** [comment]
```
ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.831 s <<< FAILURE! -- in com.puppycrawl.tools.checkstyle.internal.XpathRegressionTest
[ERROR] com.puppycrawl.tools.checkstyle.internal.XpathRegressionTest.validateInputFiles -- Time elapsed: 0.041 s <<< FAILURE!
Check name 'LocalVariableName' should be included in input file: /home/vsts/work/1/s/src/it/resources/org/checkstyle/suppressionxpathfilter/localvariablename/InputXpathRegressionLocalVariableNameInnerClass.java
expected to start with: LocalVariableName
but was               : RegressionLocalVariableNameInnerClass
	at com.puppycrawl.tools.checkstyle.internal.XpathRegressionTest.validateInputDirectory(XpathRegressionTest.java:279)
	at com.puppycrawl.tools.checkstyle.internal.XpathRegressionTest.validateInputFiles(XpathRegressionTest.java:255)
	
```

**Comment by romani** [comment]
It is hard to spot a problem.
Last we merged was recently https://github.com/checkstyle/checkstyle/commit/1ea48d56049a0596eb017bc14ba57413aba4042e and it had no such problem.

Please debug, reuse exception stacktrace and please share what code expect to be correct.

**Comment by SteLeo1602** [comment]
> ```
> ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.831 s <<< FAILURE! -- in com.puppycrawl.tools.checkstyle.internal.XpathRegressionTest
> [ERROR] com.puppycrawl.tools.checkstyle.internal.XpathRegressionTest.validateInputFiles -- Time elapsed: 0.041 s <<< FAILURE!
> Check name 'LocalVariableName' should be included in input file: /home/vsts/work/1/s/src/it/resources/org/checkstyle/suppressionxpathfilter/localvariablename/InputXpathRegressionLocalVariableNameInnerClass.java
> expected to start with: LocalVariableName
> but was               : RegressionLocalVariableNameInnerClass
> 	at com.puppycrawl.tools.checkstyle.internal.XpathRegressionTest.validateInputDirectory(XpathRegressionTest.java:279)
> 	at com.puppycrawl.tools.checkstyle.internal.XpathRegressionTest.validateInputFiles(XpathRegressionTest.java:255)
> 	
> ```

Done

**Review by romani — APPROVED** [review]
Ok to merge if ci pass

**Pull request merged**
