### PR TITLE
Update antlr to 4.5.1

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
Travis is not happy.

**Comment by romani** [comment]
appveyor is passing for master, please recommit smth in branch to re-trigger CIs builds. From this moment I expect all CIs to be green.

**Comment by romani** [comment]
UTs are failing, I will not merge that PR till CIs are green.

**Comment by mkordas** [comment]
Sure, I'm still working on it. It's just a minor release, but update is not that easy as couple of things have changed.

**Comment by romani** [comment]
I recommend you to postpone you upgrade for next releases, to avoid problems for projects that use us as dependency.

**Comment by romani** [comment]
Please explain update for pom.xml , that exclusion was added recently, history should point to issue.

**Comment by mkordas** [comment]
Antlr doesn't contain `org.abego.treelayout` dependency anymore, so this exclusion becomes obsolete: https://github.com/antlr/antlr4/pull/955/files

**Comment by mkordas** [comment]
No warnings in logs:
```
[INFO] --- maven-shade-plugin:2.4:shade (default) @ checkstyle ---
[INFO] Including org.apache.commons:commons-lang3:jar:3.4 in the shaded jar.
[INFO] Including antlr:antlr:jar:2.7.7 in the shaded jar.
[INFO] Including org.antlr:antlr4-runtime:jar:4.5.1 in the shaded jar.
[INFO] Including commons-beanutils:commons-beanutils-core:jar:1.8.3 in the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.1.1 in the shaded jar.
[INFO] Including commons-cli:commons-cli:jar:1.3.1 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:18.0 in the shaded jar.
[INFO] Attaching shaded artifact.
```

**Comment by romani** [comment]
confirmed , no WARN.

**Pull request merged**
