### PR TITLE
Issue #13100: Create tests from annotation category checks xdoc examples

### PR DESCRIPTION
**Pull request by stoyanK7**
Part of #13100

https://checkstyle.org/checks/annotation/index.html

### CODE REVIEW

**Comment by romani** [comment]
Inspection was restarted

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
Github, generate site

**Comment by nrmancuso** [comment]
CircleCI had some downtime, I have rebased this PR

**Review by nrmancuso — APPROVED** [review]

**Comment by nrmancuso** [comment]
Ok to merge as CI passes

**Comment by nrmancuso** [comment]
@stoyanK7 please resolve conflicts

**Pull request merged**
