### PR TITLE
Issue #10625: Fixed InputRedundantModifierFinalInTryWithResource.java git push origin my-new-check

### PR DESCRIPTION
**Pull request by AbhinavRajputEXE**
#10625

### CODE REVIEW

**Comment by AbhinavRajputEXE** [comment]
@romani 
> @AbhinavRajputEXE, please send PR 

The build was passing if I add the violation comment in front of the `=` sign as the `final` keyword and the message are in the same line that way,
But I guess putting the violation comment in between the expression in front of the `=` sign is not appropriate
so what should I change here?

**Comment by romani** [comment]
I pushed a fix.

Please do not limit yourself, in changes of Input files, Input files are not real logic, it can be any code, even nonsense. All we care is structure of statement/blocks.

**Comment by AbhinavRajputEXE** [comment]
Understood @romani sir
and thanks for the help😅

**Comment by romani** [comment]
GitHub, rebase

**Pull request merged**
