### PR TITLE
config: upgrade pmd to 6.14.0

### PR DESCRIPTION
**Pull request by Dichotomia**

### CODE REVIEW

**Comment by rnveach** [comment]
@Dichotomia Please don't close and recreate PRs. If you need to change something, just amend the previous commit.

https://github.com/checkstyle/checkstyle/pull/6711
> Also this is an upgrade of PMD to 6.14.0 not 3.14.0.
> Commit message should be config: upgrade pmd to 6.14.0.

**Comment by romani** [comment]
Strange that our build did not find this upgrade https://travis-ci.org/checkstyle/checkstyle/jobs/527002574

**Comment by rnveach** [comment]
@romani 
> Strange that our build did not find this upgrade 

Build says it checked for that.
https://travis-ci.org/checkstyle/checkstyle/jobs/527002574#L2329

Maven says it was released April 28th, 3 days before our build run.
I ran the command locally and `pmd-java` or any of the others doesn't show in up in the XMLs even though the XMLs report other things that are up to date.

> https://www.mojohaus.org/versions-maven-plugin/dependency-updates-report-mojo.html
> Requires dependency resolution of artifacts in scope: runtime.

Once I moved dependency outside list of `pluginManagement` it showed up on `dependency-updates-report.xml`. I don't think it does plugin dependencies.

When I run `property-updates-report` it reports `maven.sevntu-checkstyle-check.checkstyle.version` (8.20) and `pmd.version` (6.14.0). So maybe we need to move all versions to properties.

**Comment by romani** [comment]
This plugin did check for plugin updates for sure, this functionality might be damaged in recent plugin versions, but it did work.

Moving all version to properties is not very good to my mind, as it make reading of pom a bit complicated.
We probably need to report issue on this plugin.

**Comment by romani** [comment]
Let's merge this PR

**Comment by Dichotomia** [comment]
Commit amended

**Comment by rnveach** [comment]
@Dichotomia thanks.

**Pull request merged**
