### PR TITLE
Issue #14715: Enforced new naming convention on visibilitymodifier in IT area

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Part of #14715 

Enforced new naming convention on visibilitymodifier in IT area

### CODE REVIEW

**Comment by MANISH-K-07** [comment]
@romani , please see https://github.com/checkstyle/checkstyle/issues/6981#issuecomment-2019264691
Is that okay with you or do you want me to close the issue in a few PRs ?

**Comment by MANISH-K-07** [comment]
Failing ci doesn't seem related
https://github.com/checkstyle/checkstyle/actions/runs/8433856776/job/23095802696?pr=14721#step:6:24

**Comment by romani** [comment]
> test (common-2)

restated

**Review by romani — APPROVED** [review]
ok to merge is ci pass

**Comment by MANISH-K-07** [comment]
From https://github.com/checkstyle/checkstyle/issues/14715#issuecomment-2020382490, 20 files would mean approx 5-8 modules. I will keep sending PRs timely

**Pull request merged**
