### PR TITLE
Deleted cache from Utils class

### PR DESCRIPTION
**Pull request by damianszczepanik**
Issue #845

### CODE REVIEW

**Comment by romani** [comment]
What is the reason that stop you from removing that method completely from that class ? its just takes two arguments and do operation on them.

**Comment by romani** [comment]
@damianszczepanik , it would be good to finish that PR till weekends , as I plan to do release 6.5 .

**Comment by damianszczepanik** [comment]
Which method do you mind? Both `getPattern` are used out of this class and invoked from many methods.

**Comment by romani** [comment]
one line method getPattern is not required in util class

**Comment by damianszczepanik** [comment]
Ok, so correct me if I don't catch up with you. You expect to remove `getPattern` method from `Utils` and use `Pattern.compile` in each place where this method is currently invoked? So make this method more or less like inline.

**Comment by romani** [comment]
Yes, just temove that method from Util class and do update in other classes.

**Comment by damianszczepanik** [comment]
- removed both methods
- removed try-catch blocks in setters and use method in `Utils` that fires Exception when `Pattern.compile()` fails
- added missing javadoc for setters so it is clear now when and which exception is thrown (previously exception might be thrown but there is no information in javadoc about it)
- removed cache from `Utils` class
- small improvements for javadoc

**Comment by romani** [comment]
will be in 6.5

**Pull request merged**
