### PR TITLE
Issue #14881: remove null from visitJavaDocToken in SummaryJavadocCheck

### PR DESCRIPTION
**Pull request by mohitsatr**
part of #14881 : remove null usage from `visitJavaDocToken`

### CODE REVIEW

**Comment by romani** [comment]
code became less readable, please consider update like https://github.com/checkstyle/checkstyle/pull/16014/files

**Comment by mohitsatr** [comment]
`.orElseThrow()` is what other methods in codebase are using, to get the value. 


https://github.com/checkstyle/checkstyle/blob/4763b54bb77ca4fd1bc04db38430ac11c5c010d3/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java#L558-L559

https://github.com/checkstyle/checkstyle/blob/4763b54bb77ca4fd1bc04db38430ac11c5c010d3/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java#L176-L177

as pointed here https://github.com/gaul/modernizer-maven-plugin/issues/300#issuecomment-2526350760, there is no difference between the two.
i will with `.orElseThrow`

**Comment by romani** [comment]
>there is no difference between the two.
.orElseThrow or .get() with suppression ?

Not different , but ugly to read.
So I am more and more against this validation in our project.

**Comment by romani** [comment]
Restarted, passed.

**Comment by mohitsatr** [comment]
> Do you see that code becomes more explicit without null ?

sure. now i see it. null was totally unnecessary there. but my inexperienced eyes wouldn't have told that in first glance.

**Pull request merged**
