### PR TITLE
Spelling: Fixed some typos in documentation

### PR DESCRIPTION
**Pull request by AlenJoseph55**

### CODE REVIEW

**Comment by romani** [comment]
Single commit please, follow commit message format.

**Comment by romani** [comment]
Spelling should be spelling to it pass commit message validation

**Comment by AlenJoseph55** [comment]
Yeah okay, I will squash the commits in no time. Its just I couldn't rebase  `my-new-check` branch. I don't know why. I followed every instructions on the https://checkstyle.org/beginning_development.html but I couldn't rebase it. I will try and make these tests pass.

**Comment by romani** [comment]
https://www.google.com/search?q=YouTube+how+to+rebase+and+squash&oq=YouTube+how+to+rebase+and+squash+&aqs=chrome..69i57j33i160l4j33i299j33i22i29i30l3.18863j0j7&client=ms-android-google&sourceid=chrome-mobile&ie=UTF-8#sbfbu=1&pi=YouTube%20how%20to%20rebase%20and%20squash

**Comment by AlenJoseph55** [comment]
Thank you, I closed the pull request because I just realised that I didn't create the pull request from master branch.  Sorry for keep doing this.... It's just I am working on this for more than 10 days. I just want to make this work.

**Pull request closed without merging**
