### PR TITLE
Issue #13345: Enable LambdaParameterNameCheckExamplesTest

### PR DESCRIPTION
**Pull request by TarunAlapati-git**
Issue: https://github.com/checkstyle/checkstyle/issues/13345

Development changes :

* Modified the text files Example 1 and 2 to java input files
* ensured checkstyle is succeeded
* removed unwanted // OK comment

### CODE REVIEW

**Comment by romani** [comment]
@TarunAlapati-git , please do not close PRs, just do update and push with force to same branch in GitHub.

**Comment by TarunAlapati-git** [comment]
@romani Sure, i actually rebased the latest changes from master onto my branch and then force pushed my updated commit which basically took not only the latest commit but all the new rebased commits too during the pull request, to avoid that i made this new PR

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
@TarunAlapati-git, please help to fix more.

**Comment by TarunAlapati-git** [comment]
@romani Sure, i am currently working on issue https://github.com/checkstyle/checkstyle/issues/11446, will get back to this once i raise the PR there and solve more of these

**Pull request merged**
