### PR TITLE
Replace String literals of length one with char literals. #1555

### PR DESCRIPTION
**Pull request by mkordas**
Fixes `LengthOneStringsInConcatenation` inspection violations.

Description:
>Reports String literals of length one being used in concatenation. These literals may be replaced by equivalent character literals, gaining some performance enhancement.

### CODE REVIEW

**Comment by romani** [comment]
I need investigate that , I remember smb already tried to do that, I rejected that request as it not a problem any more in Java, I need to investigate that problem again.

Please share with me some links that prove that your request is valid to speed up a process.

**Comment by mkordas** [comment]
Here's the detailed analysis: http://stackoverflow.com/questions/24859500/java-concatenate-char-literal-x-vs-single-char-string-literal-x - looks like char concatenation is a bit faster, but difference is small. But we use rule to mandate `StringBuilder.append()` with chars, so let's be consistent here.

**Comment by romani** [comment]
Thanks for link. Good answer is : http://stackoverflow.com/a/24860328/1015848

I do not like that update because it make code inconsistent in string concatenations.
> ```return "Token[" + getText() + '(' + getLineNo() + 'x' + getColumnNo() + ")]";```

- people will never remember to convert string to chars as users put a string massage and then inject variable usage.
- It looks strange, future contributors will pause on that code to see to figure-out a reason
- string concatenations should be consistent by format.
- we are not in a performance-problem in that area, so premature optimization in expense of readability is not good.

**Comment by rdiachenko** [comment]
@mkordas I agree with @romani as:
- it is hard to remember to use chars in string concatenations
- chars usage complicates refactoring (e.g.: changing ```getText() + ':'``` to ```getText() + ": "```. We have to do more movements)

**Comment by mkordas** [comment]
@rdiachenko @romani - 100% agree with you, let's not do that.

**Pull request closed without merging**
