### PR TITLE
Issue #12059: direct commits to master branch while branch is protected

### LINKED ISSUE #12059: direct commits to master branch while branch is protected
detected at https://github.com/checkstyle/checkstyle/actions/runs/2856078774/attempts/1
```

Run git config --global user.name 'github-actions[bot]'
[master 0e30f41] minor: Bump release version to 10.3.3
 1 file changed, 1 insertion(+), 1 deletion(-)
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: You're not authorized to push to this branch. 
Visit https://docs.github.com/articles/about-protected-branches/ for more information.        
To https://github.com/checkstyle/checkstyle
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/checkstyle/checkstyle'
Error: Process completed with exit code 1.
```
In setting of repo we have:
image

image

**Expected:**
we need to find way to add action-user to protected group or make some other workaround.

I did workaround by removing protection from master branch, but it is not desirable approach.

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
Fixes #12059

### CODE REVIEW

**Comment by romani** [comment]
Do same branch protection in your fork and confirm that it works.

**Comment by Rahulkhinchi03** [comment]
@romani I still don't have permission. Please check: 
dvsdv

Special REPO: https://github.com/Rahulkhinchi03/Checkstyle-special

**Comment by romani** [comment]
Do not fork us. 
Just create absolutely new repository from scratch. Put in it it pom.xml file and your action. Do testing

**Comment by Rahulkhinchi03** [comment]
Just found that these restricted permissions are only available for organization rules. I have my own organization. I will work on that and update.

**Comment by Rahulkhinchi03** [comment]
Just found that these restricted permissions are only available for organization rules. I have my own organization, I will work on that.


 `ERROR FOUND without update`: https://github.com/DeCodeCafe/temp-cs/runs/7874977598?check_suite_focus=true

sdvgsvgd

-> According to [THIS COMMENT](https://github.com/pascalgn/automerge-action/issues/3#issuecomment-476177683), We can't give permission to `Github-actions`

Possible solutions that can help us:
- To create a `PERSONAL ACCESS TOKEN` and use it as `SECRET` - [TESTING](https://github.com/DeCodeCafe/temp-cs/runs/7878745734?check_suite_focus=true)

**Comment by romani** [comment]
Lets put a pause on this issue for now, lets me discuss with maintainers , we might be able to remove this restriction in settings as it will affect all Actions that modify code.

**Comment by Rahulkhinchi03** [comment]
Closing this PR as the issue is resolved with removing the branch protection rule.

**Pull request closed without merging**
