### PR TITLE
Issue #4042: Split and Organize Checkstyle inputs by Test for MethodL…

### PR DESCRIPTION
**Pull request by GabrielBercaru**
Issue: #4042

### CODE REVIEW

**Comment by rnveach** [comment]
@GabrielBercaru See https://github.com/checkstyle/checkstyle/wiki/PR-rules points 2 and 9.
Do not keep creating new PRs.

**Comment by GabrielBercaru** [comment]
@rnveach 
I see that CI failed with the following message, could you please point me out what went wrong?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project checkstyle: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/travis/build/checkstyle/checkstyle && /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /home/travis/build/checkstyle/checkstyle/target/surefire/surefirebooter409357032786880588.jar /home/travis/build/checkstyle/checkstyle/target/surefire/surefire7334870033003967325tmp /home/travis/build/checkstyle/checkstyle/target/surefire/surefire_06264073246983358891tmp

**Comment by Vladlis** [comment]
@GabrielBercaru it is Travis problem
`The forked VM terminated without properly saying goodbye.`
reason: `VM crash or System.exit called`
I've restarted failed job.

**Comment by GabrielBercaru** [comment]
@Vladlis Thanks for restarting Travis, could this PR get reviewed?

**Pull request merged**
