### PR TITLE
Issue #3153: IllegalTokenTextCheck does not work with COMMENT_CONTENT…

### PR DESCRIPTION
**Pull request by romani**
#3153

… token

### CODE REVIEW

**Comment by rnveach** [comment]
@romani The same fix has to be applied to `IllegalTokenCheck`.
See https://github.com/checkstyle/checkstyle/issues/3153#issuecomment-216529728

**Comment by rnveach** [comment]
Test Failure: New lines in the message won't work for testing as we expect the whole violation to be on one line. See https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java#L161

**Comment by romani** [comment]
Yes, I know , the same behaviour is on local. 
I did not have enough time to fix it properly in one day , so I just put code on remote as is.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
