### PR TITLE
Issue #5440: New Check: Enforce or deny a blank line before the right curly brace

### PR DESCRIPTION
**Pull request by pbludov**
Issue #5440: New Check BeforeRightCurly

### CODE REVIEW

**Comment by rnveach** [comment]
@pbludov CI is failing here too for same reason.

**Comment by pbludov** [comment]
@rnveach The reason is the same as for https://github.com/checkstyle/checkstyle/pull/5441#issuecomment-355835917

**Comment by romani** [comment]
CI is failed as issue is not approved.
Please update issue description to let me review design and recheck one more time that we are right way.

**Comment by pbludov** [comment]
@romani done.

**Comment by pbludov** [comment]
screenshot--2018-01-13-16-41-34

**Comment by romani** [comment]
:), please move this to issue as plain text, only issue is referenced in commit and release notes.

**Comment by rnveach** [comment]
@pbludov Why did you close and delete this PR?
Do you not plan to work on it anymore?

**Comment by pbludov** [comment]
It was an accident. This is not a problem, I have a backup.
The PR has not changed for a very long time, so nothing will be lost.

**Comment by rnveach** [comment]
@pbludov Did you make the change @romani asked for?
> please move this to issue as plain text

**Comment by voz** [comment]
@pbludov this would be a useful check for us. Thanks for moving it forward.

**Comment by dbelyaev** [comment]
@pbludov Was this feature just closed and never got to production code?

**Comment by romani** [comment]
Yes, looks like simply forgotten.

To move forward we need to update issue with comment to explain design in more details to let maintainers review it and approve issue.

https://checkstyle.org/report_issue.html#How_to_request_new_Check.2FModule.3F

**Pull request closed without merging**
