### PR TITLE
Issue #1566: 'Fields and methods should be before inner classes' violations fixed

### PR DESCRIPTION
**Pull request by rdiachenko**
Inner classes were moved to the end of outer classes.

### CODE REVIEW

**Comment by romani** [comment]
please rebase , too much conflicts now, you will be first on next iteration.

**Comment by rdiachenko** [comment]
@romani rebase done

**Comment by romani** [comment]
build was failed, during rebuild I merged about 10 PRs, so now we have conflicts one more time, please rebase again.

**Comment by rdiachenko** [comment]
@romani rebase done

**Pull request merged**
