### PR TITLE
Issue:#9596

### PR DESCRIPTION
**Pull request by brngylni**
Fix to   #9596 

This is the verified version of previous PR. Checked with 
`mvn clean verify.` 

Here is the view of rendered file : 

Screenshot from 2021-04-05 18-12-08

### CODE REVIEW

**Comment by AkMo3** [comment]
@brngylni `mvn clean verify` check would not pass due to the wrong commit message. Please fix the violation. Also, please provide the source file you used to generate AST, and show that it is compilable.

**Comment by brngylni** [comment]
> @brngylni `mvn clean verify` check would not pass due to the wrong commit message. Please fix the violation. Also, please provide the source file you used to generate AST, and show that it is compilable.

Shall I open a new PR ?

**Comment by AkMo3** [comment]
> Shall I open a new PR ?

No, please try to do all changes in this PR only.

**Comment by romani** [comment]
fix branch structure on your local and push with "--force" to github.

**Comment by brngylni** [comment]
> fix branch structure on your local and push with "--force" to github.

I accidentally closed that PR. I am sorry.

**Pull request closed without merging**
