### PR TITLE
Issue #7892: clean up after shippable

### PR DESCRIPTION
**Pull request by nmancus1**
Update for #7892: clean up after Shippable runs.

### CODE REVIEW

**Comment by nmancus1** [comment]
In this case, it makes more sense to run as a job after Shippable completes, since all jobs in Shippable use tools in contribution.

**Comment by romani** [comment]
I do not think we need to clean up disk of CI, all will be lost, right after execution is finished.


We did clean up after each execution point, to avoid extra caches files folders on localhost. But we do not care about CI

**Comment by nmancus1** [comment]
@romani so, still remove after each item, like in #8040?

**Comment by romani** [comment]
Yes, each itt need to cleanup after itself, In CI we just do validation on no leftovers.
No leftovers means:
No git diff in repo
No folders in .ci-temp folder, but it might be ok to keep files

**Comment by nmancus1** [comment]
> No git diff in repo

The diff report is in the `contribution/checkstyle-tester/reports/` directory anyway, so that should get removed when `.ci-temp/contribution` does, after each item has ran. So, to validate, we should only need to make sure`.ci-temp` is empty, right?

**Comment by romani** [comment]
>make sure.ci-temp is empty, right?

Yes

**Comment by nmancus1** [comment]
@romani I should open a new PR for empty validation, or just make those change here?

**Comment by romani** [comment]
Please do it here, PR is small, so it will be good to fix issues and enforce it never appear in same commit.

**Pull request merged**
