### PR TITLE
Issue #11163: Enforce file size on InputJavadocStyle10

### PR DESCRIPTION
**Pull request by 0xbakry**
Issue #11163

- Split `InputJavadocStyle10.java` into 4 `Input*.java` files each less than 120 lines.
- Split `testEmptyJavadoc()` into 4 tests.

### CODE REVIEW

**Comment by romani** [comment]
This is good, but please do update for all inputs of this Check, not a single input.

**Comment by romani** [comment]
If CI green, I will merge this, further update can be done in separate PR

**Comment by romani** [comment]
@0xbakry , please do not forget https://github.com/checkstyle/checkstyle/actions/runs/4526987557/jobs/7972905857?pr=12916#step:3:9

I fixed and restarted it for you

**Comment by 0xbakry** [comment]
> I fixed and restarted it for you

Thanks! i'll remember to include it next time.

**Comment by 0xbakry** [comment]
> but please do update for all inputs of this Check, not a single input.

Sorry, but i didn't get exactly what do you mean.
I'll update the four `Input*.java` to have more tests in `testEmptyJavadoc[1-4]()`.
did i get your point right?

**Comment by 0xbakry** [comment]
Great, that's what i though first but "further update can be done in separate PR" confused me a littele bit.

**Pull request merged**
