### PR TITLE
Issue #6320: enable REMOVE_CONDITIONALS for all with moving all survived to known list

### PR DESCRIPTION
**Pull request by romani**
Issue #6320

this is get scope of survived items, next commit will be register all survived.

### CODE REVIEW

**Comment by rnveach** [comment]
If this related to PR #6357 , please note I also added another mutator that we haven't started dealing with when I posted on surviving mutants.

See https://github.com/checkstyle/checkstyle/pull/6357#discussion_r250822323 .
This is the `NON_VOID_METHOD_CALLS` mutator. Return value is replaced with default value of the type. See http://pitest.org/quickstart/mutators/#NON_VOID_METHOD_CALLS .

**Comment by romani** [comment]
@rnveach , please review, I will squash during manual merge

**Comment by romani** [comment]
I think it would take some time for us to process existing ignore list, I do not want to have huge list of ignores, as we ignore all mutations on line, not a certain.

**Comment by romani** [comment]
rebased and merged manually

**Pull request closed without merging**
