### PR TITLE
doc: change "nmancus1" to "Nick Mancuso" in release notes

### PR DESCRIPTION
**Pull request by nmancus1**
Change username  "nmancus1"  to "Nick Mancuso" in release notes.

### CODE REVIEW

**Comment by strkkk** [comment]
@nmancus1 you should update your local git config with your full name to avoid such issues in future

**Comment by rnveach** [comment]
> you should update your local git config with your full name to avoid such issues in future

This needs to be done otherwise it will be an issue again in the next release.

**Comment by romani** [comment]
@rnveach, @strkkk 
prefix should be "minor" for updates, to be skipped in release notes.
We generate releasenotes based on commits. it is better to skip such updates from notes.

**Comment by nmancus1** [comment]
> This needs to be done otherwise it will be an issue again in the next release.

I've fixed this, thank you.

**Pull request merged**
