### PR TITLE
Issue #11140: Resolve PMB_POSSIBLE_MEMORY_BLOAT issue 1

### PR DESCRIPTION
**Pull request by SampathKumarAmex**
Fixing one of the possible memory bloat issues highlighted by spotbugs.

Related to https://github.com/checkstyle/checkstyle/issues/11140

### CODE REVIEW

**Comment by SampathKumarAmex** [comment]
Please help to resolve the `Wercker pipeline` failure. I couldn't see the error details by clicking the details link.

**Comment by rnveach** [comment]
Wercker failure is sonar failure:
https://sonarcloud.io/summary/new_code?id=org.checkstyle%3Acheckstyle&pullRequest=11217
18 code smells

Most seem to be `Remove this array creation and simply pass the elements.`.
Example:
https://github.com/checkstyle/checkstyle/pull/11217/files#diff-b0b05754b0b42252aaaee0d49b2d40900e79af7882548b37ac198ed944d4572fR439

**Comment by rnveach** [comment]
In addition to making CI green, please remove all commits except your own. There should only be 1 commit showing for this PR.

**Comment by SampathKumarAmex** [comment]
> In addition to making CI green, please remove all commits except your own. There should only be 1 commit showing for this PR.

May I know the reason for having only one commit per PR? If one commit is required, the merge process can have [squash commit option](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) correct?

I am unsuccessful in squashing my commits due to the below error message.

```
Unable to squash. Squashing replays all commits up to the last one required for the squash. A merge commit cannot exist among those commits.
```

Happy to do it if you can share the steps. Thank you!

**Comment by nmancus1** [comment]
@SampathKumarAmex

> ` A merge commit cannot exist among those commits.`

You must drop merge commit, then you can squash/ fixup others.

**Comment by rnveach** [comment]
@SampathKumarAmex ping

**Comment by nick-mancuso** [comment]
We are keeping this suppression forever, we will not damage readability just to make spotbugs happy. `PMB_POSSIBLE_MEMORY_BLOAT` is checked off in issue.

**Pull request closed without merging**
