### PR TITLE
Issue #5040: Rename JavadocLexer rule to a more meaningful name

### PR DESCRIPTION
**Pull request by Vladlis**
#5040

### CODE REVIEW

**Comment by rnveach** [comment]
Why do we have this line here if it isn't used anywhere else?

**Comment by romani** [comment]
@Vladlis , rnveach raise good question. 
can we remove this line completely ?

**Comment by Vladlis** [comment]
@rnveach @romani 
without this rule we won't be able to correctly recognize cases like https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/javadocTags/InputInnerBracesInCodeTag.javadoc#L1 - it helps to determine whether `}` is a part of code inside an inline tag (`@code` or `@literal`) or it closes this inline tag.
Example of a tree with this rule:
```
JAVADOC -> JAVADOC [0:0]
|--JAVADOC_INLINE_TAG -> JAVADOC_INLINE_TAG [0:0]
|   |--JAVADOC_INLINE_TAG_START -> { [0:0]
|   |--CODE_LITERAL -> @code [0:1]
|   |--WS ->   [0:6]
|   |--TEXT -> {{{}}{{}}}  [0:7]
|   `--JAVADOC_INLINE_TAG_END -> } [0:19]
`--EOF -> <EOF> [0:20]
```
and without it
```
JAVADOC -> JAVADOC [0:0]
|--JAVADOC_INLINE_TAG -> JAVADOC_INLINE_TAG [0:0]
|   |--JAVADOC_INLINE_TAG_START -> { [0:0]
|   |--CODE_LITERAL -> @code [0:1]
|   |--WS ->   [0:6]
|   |--TEXT -> {{{ [0:7]
|   `--JAVADOC_INLINE_TAG_END -> } [0:11]
|--TEXT -> }{{}}} } [0:12]
`--EOF -> <EOF> [0:20]
```

**Comment by rnveach** [comment]
I see, so the label isn't what matters it is the `-> type(CHAR)` which basically forces the `Skobki`/`Brackets` to instead be identified as `CHAR` which we use in other places.

**Pull request merged**
