### PR TITLE
Issue #15214: Migrated section 4.6.1 vertical whitespace to whole config testing

### PR DESCRIPTION
**Pull request by Zopsss**
#15214

### CODE REVIEW

**Review by romani — APPROVED** [review]
ok to merge.

this PR should be viewed without spaces to get better picture that no vilations are lost/added

**Comment by Zopsss** [comment]
> this PR should be viewed without spaces to get better picture that no vilations are lost/added

the changes were very simple, I just moved the extra class inside the main class:

https://github.com/checkstyle/checkstyle/blob/66eaed6539d463b6de50b5972f57647e53458a56/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule461verticalwhitespace/InputVerticalWhitespace.java#L86-L101

added some missing javadoc and renamed some variables.

**Comment by Zopsss** [comment]
Semaphore CI failure can be ignored

**Review by rdiachenko — APPROVED** [review]
lgtm

**Pull request merged**
