### PR TITLE
Issue #11214: Specify violation messages for AbstractClassNameCheck

### PR DESCRIPTION
**Pull request by stoyanK7**
Addresses issue #11214
Specifies the violation messages for `AbstractClassNameCheck` in all relevant `Input..` files.
## Changes
* Specified violation messages for `AbstractClassNameCheck` in 5 files
	* Escaped RegEx special characters in the message. For instance, 
		`^Abstract.+$` -> `\^Abstract\.\+\$`
	* I got `Line should not be longer than 100 symbols [lineLength]` when  	running `mvn clean verify` so I moved the problematic `// violation '..'` 	comments above the violation line and changed them to `// violation below '..'`. This is what I noticed other people did.
* Changed the row numbers in `expected` variables in `AbstractClassNameCheckTest` due to the moved `// violation` comments.
* Removed the check from the suppresion list in `InlineConfigParser`.
## ~~Pull request is not ready to merge yet~~
The biggest outlier is in the `InputAbstractClassNameFormerFalsePositive` file where the first comment(around line 12) **itself** was too long(more than 100 characters) for one row so I tried to split it in 2 rows. The comment should be
`// violation below 'Name 'InputAbstractClassNameFormerFalsePositive' must match pattern '\^Abstract\.\+\$'.'`, not what is in the commit right now(without the pattern):
Screenshot from 2022-06-21 23-17-16

I tried both stuff like 
```java
abstract public class InputAbstractClassNameFormerFalsePositive {
// violation above
// 'Name 'InputAbstractClassNameFormerFalsePositive' must match pattern '\^Abstract\.\+\$'.'
```
or
```java
// violation below
// 'Name 'InputAbstractClassNameFormerFalsePositive' must match pattern '\^Abstract\.\+\$'.'
abstract public class InputAbstractClassNameFormerFalsePositive {
```
but no success there. On the second one I believe if I put `// violation below` directly above the class declaration, it might work but then the readability is sacrifised.

What options are there? Changing the class name? Leaving it as I did it without mentioning the pattern?

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
@stoyanK7,
When I was resolving https://github.com/checkstyle/checkstyle/pull/11449, I faced the same issue (i.e. long comment)

My comment was: `// violation tag should be placed immediately before the first word, with no space after.`

I tried: `// violation tag should be placed immediately before the first word'`

And It worked for me. You can check the comments of my closed PR, where I did mistakes: https://github.com/checkstyle/checkstyle/pull/11433

**Comment by stoyanK7** [comment]
Thank you @Rahulkhinchi03! From your pull request discussion see that wrapping violation messages is not supported. The current violation comment I have in this pull request passes the checks, I was just wondering if it is okay leaving it as it is without the pattern mentioned.

**Comment by Rahulkhinchi03** [comment]
> wrapping violation messages is not supported. The current violation comment I have in this pull request passes the checks

Writing 2 violations together in 1 line is not supported. Looking at your PR, I can't see you wrapping violations.

FAIL: `// 2 violations below 'Javadoc content should start from the next line after * /\*\*.'`
PASS: `// violation 2 lines below 'Javadoc content should start from the next line after * /\*\*.'`

I believe you can try what I did in my PR and we can wait for the mentors to review your PR.

**Comment by stoyanK7** [comment]
Thank you @Vyom-Yadav! Thats what I needed to know :) . The change is pushed now.

Also, am I allowed to work on one more check?

**Review by Vyom-Yadav — APPROVED** [review]

**Comment by Vyom-Yadav** [comment]
> Also, am I allowed to work on one more check?

Yes you can.

**Review by romani — APPROVED** [review]
thanks a lot for update

**Pull request merged**
