### PR TITLE
Enable AvoidNestedBlocks check for Checkstyle, issue #945

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
visibility in switch block is not very intuitive, it is better to think about a each case as a function with its own scope of names. I am in favour of non-shares scopes for names as it helps each case to use any names that suite its context. 

Are you agree ?

we need to somehow to avoid that violation, if not possible - we need to provide proposal for Check update to let users(and us first of all) use that Check without compromise. Till issue is resolved, we have to use suppression.

**Comment by mkordas** [comment]
Agreed, #947 created.

**Comment by mkordas** [comment]
#947 closed, commit updated.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
