### PR TITLE
Issue #6807: Add an alone_or_empty option to RightCurlyOption.

### PR DESCRIPTION
**Pull request by ILMTitan**
Issue #6807: Add a RightCurlyOption.ALONE_OR_EMPTY

This new option matches the allows right curly placement of the Google Style Guide.

### CODE REVIEW

**Comment by rnveach** [comment]
@ILMTitan Where in issue is it suggested to add this new option?

**Comment by ILMTitan** [comment]
@rnveach It is not actually, but it is the only way to fix the problem.

RightCurlyOption.ALONE disallows, but the Google Style Guide allows, this:

```
    void emptyMethod() {}
```

RightCurlyOption.ALONE_OR_SINGLEINE allows, but the Google Style Guide diallows, this:

```
    void singleLineMethod() {someStatement();}
```

The possible solutions as I seem them are:

1. Change one of the existing option behaviors.
2. Add a new option.
3. Don't support the Google Style Guide.

I think 2 is the best option.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/issues/6807#issuecomment-501983298
If it is not defined in the issue and agreed upon, then you need to showcase what you are doing to get approval from the admins. New property can be ok, but it is now big undertaking to define all scenarios on what it means and how it will handle any situation.

@romani ping

**Comment by pbludov** [comment]
> RightCurlyOption.ALONE disallows, but the Google Style Guide allows, this:
> 
> ```java
>     void emptyMethod() {}
> ```

I think that empty code blocks should be verified by a special check, as they may conflict with `LeftCurlyOption` and/or `RightCurlyOption` checks.

**Comment by romani** [comment]
@ILMTitan , while decision on new Check or ..... is very heavy 
can you check that workaround with suppression at https://github.com/checkstyle/checkstyle/issues/6807#issuecomment-580508583 works for you ? if it works well, we can embed such filter in google config and ease a problem.

**Comment by romani** [comment]
@ILMTitan , we need to move all your logic to separate Check.

new Check with possible name as RightCurlyAloneOrEmpty should be separate from RightCurly but can copy any functionality it needs and cover singe case, ones implemented it should replace existing RightCurly instance in google config.

Can you fix issue in way of new Check ?

**Comment by romani** [comment]
if there will be no reply till end of February, we will close this PR. Request for new Check is moved to #7541 issue.

**Comment by rnveach** [comment]
I am closing this PR as there has been no response.

**Pull request closed without merging**
