### PR TITLE
Issue #2108: Split all modules to be separate at config_naming.html

### PR DESCRIPTION
**Pull request by Vladlis**
Site after changes - http://vladlis.github.io/reports/site/config_naming.html

### CODE REVIEW

**Comment by mkordas** [comment]
@Vladlis 
1) We are doing huge changes here, so maybe we can also sort all checks alphabetically?
2) With this PR logic in `com.puppycrawl.tools.checkstyle.AllChecksPresentOnAvailableChecksPageTest` can be simplified - please refactor.
3) Can we somehow improve formatting of `<a>` tags? Instead of:
```
<a
href="apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#CLASS_DEF">CLASS_DEF</a>
```
this might be better solution:
```
<a href="apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#CLASS_DEF">
  CLASS_DEF
</a>
```
4) `<p> com.puppycrawl.tools.checkstyle.checks.naming </p>` - please remove all obsolete spaces where possible

Thanks for the update, it's great step forward. There's probably still a lot to improve on that page, but let's keep this PR limited.

**Comment by romani** [comment]
@Vladlis , please do not forget to update link from site/checks.html to new documentation paragraphs

**Comment by Vladlis** [comment]
1) done
2) done
3) I've formatted it in a way "Example of Usage" is formatted.
4) done
> please do not forget to update link from site/checks.html

done

**Comment by mkordas** [comment]
@romani, I'm done with review, can you step in?

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
