### PR TITLE
Issue #9515

### PR DESCRIPTION
**Pull request by shubham11941140**
Issue #9515: update example of AST for TokenTypes.MINUS

### CODE REVIEW

**Comment by nmancus1** [comment]
@shubham11941140 please do not create multiple PR's for the same issue. Now that you have opened https://github.com/checkstyle/checkstyle/pull/9642, close this one.

**Comment by shubham11941140** [comment]
I have used mvn verify and it says build success but yet this tells that checks are failing.
How am I supposed to rectify these checks, please tell soon

**Comment by pbludov** [comment]
@shubham11941140 please rebase to the latest upstream.

**Comment by Devansu-Yadav** [comment]
@shubham11941140 You can rebase to the latest upstream using the workflow that is already created by the mentors/maintainers:-
Just type `Github, rebase` in the comments here. This workflow will make your branch in level with the latest upstream and all CI tests should pass.
(PS:- Don't forget to pull your branch in your local system after doing the above.)

**Review by romani — APPROVED** [review]
in next PR please update descrition to show how javadoc is rendered.

**Pull request merged**
