### PR TITLE
Issue #2661: Enforce SingleBreakOrContinueCheck of sevntu-checkstyle …

### PR DESCRIPTION
**Pull request by yaziza**
…over Checkstyle source code

### CODE REVIEW

**Comment by MEZk** [comment]
@yaziza 
SingleBreakOrContinueCheck is not a part of Sevntu Checkstyle release version.

**Comment by yaziza** [comment]
Hi @MEZk,

roman told me to send a PR to checkstyle in order to merge this after we release the SingleBreakOrContinueCheck to Seventu-CS:

https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/416#issuecomment-168277361

**Comment by romani** [comment]
I am ok with changes, looks good and reasonable.

Merge is postponed till sevntu-checkstyle next release - 1.18.

**Comment by romani** [comment]
converted to #2830

**Pull request closed without merging**
