### PR TITLE
Issue #408: Update Checkstyle GUI in order to display Javadoc tokens

### PR DESCRIPTION
**Pull request by baratali**
#408

### CODE REVIEW

**Comment by baratali** [comment]
I'm looking into TeamCity problems...

**Comment by romani** [comment]
travis problems are not problems, restarted.
Teamcity violations need to be resolved.

**Comment by baratali** [comment]
One of the issues: "Absolute alignment constant BorderLayout.EAST used"
Don't really understand why I shouldn't use such constants. I haven't found neither a description of that violation nor proposed solutions.

**Comment by romani** [comment]
Please fix all others, i will investigate this violation

**Comment by romani** [comment]
https://docs.oracle.com/javase/7/docs/api/java/awt/BorderLayout.html 

> In addition, BorderLayout supports the relative positioning constants, PAGE_START, PAGE_END, LINE_START, and LINE_END. In a container whose ComponentOrientation is set to ComponentOrientation.LEFT_TO_RIGHT, these constants map to NORTH, SOUTH, WEST, and EAST, respectively.

So , just use different constant , LINE_END .

**Comment by romani** [comment]
1)
> // temporary disabled. Have to deal with Javadoc nodes as well

please put a ref to github issue 

2)
>
```
             default:
                value = null;
```


Why not to throw exception ?

**Comment by baratali** [comment]
@romani 
1) Done.
2) Agree. Replaced with throwing an exception.

**Comment by romani** [comment]
3)
> private static final String[] MODES_TITLES = {

We need to minimize code in UI part.
please move this to Model, it should be close to ParseMode, and even part of it.

**Comment by baratali** [comment]
3) Mode titles have been integrated into ParseMode enum.
@romani , please review again.

**Comment by romani** [comment]
4)
> getChildCount, getChild, getValueAt

please do single return.

5)
> new JLabel("  Modes:  "

bordering by spaces :), can we use http://docs.oracle.com/javase/tutorial/uiswing/components/border.html ?

**Comment by MEZk** [comment]
@romani @baratali 
Can COLUMN_NAMES array become an enum and be used in getColumnClass,  getValueAtDetailNode, and getValueAtDetailAST instead of magic numbers?

**Comment by romani** [comment]
That are not magic numbers, but sequence of columns in table from first to last. Enum items are not related to columns order.

**Pull request merged**
