### PR TITLE
Issue #3041: RequireThisCheck doesn't see outer classes for anonymous classes

### PR DESCRIPTION
**Pull request by Vladlis**
Issue #3041

Diff reports: https://vladlis.github.io/3041/index.html

### CODE REVIEW

**Comment by rnveach** [comment]
https://vladlis.github.io/3041/checkstyle/index.html#A32
https://vladlis.github.io/3041/checkstyle/xref/home/vlad/workspace/opensource/contribution/checkstyle-tester/repositories/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/InputNullModifiers.java.html#L12

This looks like a bug that went unnoticed. Anonymous class has a instance field and we weren't marking it's uses as requiring `this`.
We should add this as an example to our inputs/tests.

**Comment by Vladlis** [comment]
@rnveach 
ok, done

**Comment by romani** [comment]
Nondex on Travis is not happy with update, please fix.

**Comment by romani** [comment]
@Vladlis, Please explain why you think https://vladlis.github.io/3041/checkstyle/index.html#A7 is expected.

**Comment by rnveach** [comment]
@romani This is the same as the one I pointed out.
Variable is an instance field, and we have `validateOnlyOverlapping` turned off. There is also nothing documented that we will not validate anonymous classes. It seems to me they should require `this`.

**Comment by romani** [comment]
I can not reproduce problem with nondex on my local:
```
$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
$ uname -a
Linux mylaptop 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

@rnveach , can you try to run on your side ?

**Comment by rnveach** [comment]
@romani The same, no failures locally on Windows 7.
This issue looks the exact same as https://github.com/TestingResearchIllinois/NonDex/issues/98 which is still unsolved. I'll post this to the same issue.

I will try making a new PR to see if it is reproducible. If it is, I'll play around with it and see if I can find anything.

**Comment by Vladlis** [comment]
@rnveach @romani 
I cannot reproduce nondex failure locally too.

@romani
> Please explain why you think https://vladlis.github.io/3041/checkstyle/index.html#A7 is expected.

I agree with @rnveach,
In this particular case `packageName` needs this, as it is an instance variable of the anonymous implementation of Filter.

```java
handler.setFilter(new Filter() {
    private final String packageName = Main.class.getPackage().getName();
    @Override
    public boolean isLoggable(LogRecord record) {
        return record.getLoggerName().startsWith(packageName);
    }
});
```

**Comment by romani** [comment]
> In this particular case packageName needs this, as it is an instance variable of the anonymous implementation of Filter.

confirmed.

**Comment by romani** [comment]
@Vladlis , please skip failed tests in nondex, we already have examples for this.

**Comment by romani** [comment]
I am fine with code and report, I did review of bunch of cases in guava , no problems found.
@rnveach , please do review.
@Vladlis , good job!

**Comment by romani** [comment]
@Vladlis , please provide a workaround for Travis

**Comment by romani** [comment]
@Vladlis , ping.

**Comment by Vladlis** [comment]
@romani 
CI is green, I've made rebase

**Comment by romani** [comment]
Strange that nondex issue disappear

**Pull request merged**
