### PR TITLE
Issue #9323: replace branch name with hash in diff report action

### LINKED ISSUE #9323: Generated link is incorrect if fork branch name has hash sign
Found during #9288 

Patch branch has `#` in it, so github action takes branch name and includes this into link.
Generated link looks like https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/Issue_#9271_2021125041/reports/diff/index.html, but it is incorrect(shows access denied) because `#` is a special sign.

Possible solutions - exclude hash sign from branch name or take hash from branch name and use it instead of branch name

### PR DESCRIPTION
**Pull request by strkkk**
Closes #9323 

Branch name is replaced with 7 chars commit sha, which protects link from any special chars that can be in branch name

### CODE REVIEW

**Comment by romani** [comment]
Why not 7 character identifier as GitHub does for short commit identification, so it will be very easy to validate to what commit report belongs to

**Comment by strkkk** [comment]
> 
> 
> Why not 7 character identifier of most top commit as GitHub does for short commit identification, so it will be very easy to validate to what commit report belongs to

it can be like this as well. Taking hash from branch name was easier to implement because branch name is there already, but to find commit hash you need to dig into github event. No other reasons except for my laziness

**Comment by romani** [comment]
Looks like they have variable for this

**Review by romani — CHANGES_REQUESTED** [review]
better to use commit short SHA

**Comment by strkkk** [comment]
@romani I have checked - GITHUB_SHA variable is not the commit in pull request, it is commit sha that "triggered a pull request". That is latest commit in master branch, since workflow is triggered by commit, not latest commit in branch. So that wont make much sense. For example, open any actions run, e.g. https://github.com/checkstyle/checkstyle/actions/runs/629037453 - there is a commit hash but it is from master branch.
What do you think?

**Comment by strkkk** [comment]
@romani I have added extraction of this information from PR info.

 FYI env variable GITHUB_SHA points to latest master commit in our case, not PR head commit.

**Review by romani — APPROVED** [review]

**Pull request merged**
