### PR TITLE
Issue #13321: Kill mutation for ScopeUtil-3

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for ScopeUtil-3

------

# Mutation 
https://github.com/checkstyle/checkstyle/blob/bb64c20cbcf6e543b297b6e809f379bd8746b5e7/config/pitest-suppressions/pitest-utils-suppressions.xml#L336-L343

------

# Explaination
The logic has not been changed. only design is changed

The reason to not follow pitest is we can do it in less time-complexity by following my changes. :)

-------

# Regression 
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/63cd42f1f26093d981dad219eb8986eb/raw/4cc3d4b44b54b551ceb2f723c0dff753d548f7ff/su3.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/360a95ed7bb60d7a0956e531199d484c4d6f6617/test-projects.properties
Report label: Regression-2

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
@romani ready for review

**Review by romani — APPROVED** [review]
Good refactoring

**Comment by romani** [comment]
@Kevin222004 , please fix CI.

**Review by rdiachenko — APPROVED** [review]
lgtm

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

**Comment by romani** [comment]
@Kevin222004 , please resolve conflict

**Pull request merged**
