### PR TITLE
Issue #9304: Resolve Pitest Issues - HeaderCheck

### PR DESCRIPTION
**Pull request by aryaniiit002**
Fixes https://github.com/checkstyle/checkstyle/issues/9304

1. Pitest report: https://aryaniiit002.github.io/Checkstyle-reports/Issue-%239304/pit-reports/202102171623/com.puppycrawl.tools.checkstyle.checks.header/HeaderCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@79513efe_186

2. Surviving mutation: `removed conditional - replaced equality check with false → SURVIVED`

3. Regression report: https://aryaniiit002.github.io/Checkstyle-reports/Issue-%239304/diff/index.html

### CODE REVIEW

**Comment by aryaniiit002** [comment]
```
    /** Empty array to avoid instantiations. */
    private static final int[] EMPTY_INT_ARRAY = new int[0];

    /** Specify the line numbers to ignore. */
    private int[] ignoreLines = EMPTY_INT_ARRAY;
```

```
    /**
     * Setter to specify the line numbers to ignore.
     *
     * @param list comma separated list of line numbers to ignore in header.
     */
    public void setIgnoreLines(int... list) {
        if (list.length == 0) {
            ignoreLines = EMPTY_INT_ARRAY;
        }
        else {
            ignoreLines = new int[list.length];
            System.arraycopy(list, 0, ignoreLines, 0, list.length);
            Arrays.sort(ignoreLines);
        }
    }
```
i totally agree that this is a nice way of code writing but there we are having a mutator surviving, 
so i believe there are some redundant code here if you look at the code you will see that there is no need of if-else conditions 

`ignoreLines` is by default `EMPTY_INT_ARRAY` and `list` can be empty or not if it's not empty then `else` part would play but if we remove the conditions and test for `list` not empty even then our output would not change `ignoreLines` would be empty, no array copy would happen and no sorting, we will not any errors

**Comment by aryaniiit002** [comment]
and if this feels good there another similar mutator in 
RegexpHeaderCheck.java

Pitest report:  https://aryaniiit002.github.io/Checkstyle-reports/Issue-%239304/pit-reports/202102171623/com.puppycrawl.tools.checkstyle.checks.header/RegexpHeaderCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@39197b07_249

**Comment by aryaniiit002** [comment]
please feel free to review whenever you are free, no pressure :)

**Review by nmancus1 — APPROVED** [review]
>  there is another similar mutator in
RegexpHeaderCheck.java

If an issue is not open for this surviving mutation, please do so.

@strkkk @pbludov please assign next reviewer.

**Review by pbludov — APPROVED** [review]

**Review by strkkk — APPROVED** [review]

**Pull request merged**
