### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by Linde7777**
Issue: #11352

### CODE REVIEW

**Comment by romani** [comment]
Please do single commit, and minimize changes to what you going to add, no extra changes

**Comment by Linde7777** [comment]
> Please do single commit, and minimize changes to what you going to add, no extra changes

Thanks, I gonna try to fix it.   
Does 'single commit' means I should leave only 1 commit in this pull request and remove other commits?

**Comment by Linde7777** [comment]
I use ```git rebase``` ```git push --force```, and it caused this pull request to be closed. I don't remember some git commands I performed, now the situation is so confusing now that I don't know what keywords to google to solve this problem, can I fork the repository again then make a new pull request?

**Comment by Linde7777** [comment]
> > Does 'single commit' means I should leave only 1 commit in this pull request and remove other commits?
> 
> Yes. https://github.com/checkstyle/checkstyle/wiki/PR-rules - item 2.

I use ```git rebase``` ```git push --force```, and it caused this pull request to be closed. I don't remember some git commands I performed, now the situation is so confusing now that I don't know what keywords to google to solve this problem, can I fork the repository again then make a new pull request?

**Pull request closed without merging**
