### PR TITLE
Issue #7096: remove deprecated properties from JavadocMethodCheck

### PR DESCRIPTION
**Pull request by rnveach**
Issue #7096

### CODE REVIEW

**Comment by romani** [comment]
Removal of properties that were disabled completely a while ago, can be done at any time at user config, can you send PR to Orekit , we can wait a bit to avoid keeping in master reference to personal fork ( it is easy to forget about it).

**Comment by rnveach** [comment]
@romani Changes were sent to orekit and they have taken them into their repository but not into master. They follow git-flow and merged to a development branch that will eventually go to master at some later point.
See https://github.com/CS-SI/Orekit/pull/22#issuecomment-534164054

The changes to the CI use the branch that was part of the PR to orekit.

**Comment by romani** [comment]
We do not care, if after merge, no errors in repo on any tag/hash let's use it.

**Comment by rnveach** [comment]
>  no errors in repo on any tag/hash let's use it.

Done.

**Pull request merged**
