### PR TITLE
Fix PMD violations from 'strings' ruleset, issue #873

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
Please remove static import, we do not use isBlank that much to economize on names.

Please investigate ability to suppress pmd violations by standalone config, i do not like when code is extended by tools hints, code should clean.

**Comment by mkordas** [comment]
> Please remove static import, we do not use isBlank that much to economize on names.

Done
> Please investigate ability to suppress pmd violations by standalone config

This is longer discussion and investigation. To keep the code clean, I've decided to use `List<String>` and `StringUtils.join()` instead. Performance-wise should be almost the same.

**Comment by romani** [comment]
Please squash commits, i am ready to merge

**Comment by mkordas** [comment]
Done

**Pull request merged**
