### PR TITLE
Issue #4437: Modified ImportControlCheckTest.java and moved its input files to the importcontrol subdirectory

### PR DESCRIPTION
**Pull request by subkrish**
Issue #4437

This PR moves all inputs of ImportControlCheckTest of the imports package to a new subdirectory 'importcontrol'.

### CODE REVIEW

**Comment by subkrish** [comment]
Should I rename them to something like `ImportControlOne.xml`, etc.?

**Comment by rnveach** [comment]
> > getPath("import-control_one.xml")

> Should I rename them to something like ImportControlOne.xml, etc.?

Test is named `ImportControlCheckTest`, so inputs must start with `InputImportControl`.
I am fine with `InputImportControlOne` and etc...

**Comment by rnveach** [comment]
@subkrish Please also rebase on latest master to test travis fix.

**Comment by subkrish** [comment]
Rebased on latest master. Done.

**Pull request merged**
