### PR TITLE
Issue #4582: restored wercker hibernate search

### PR DESCRIPTION
**Pull request by rnveach**
Issue #4582

### CODE REVIEW

**Comment by rnveach** [comment]
@romani Do you know what this error is about?
> Caused by: java.lang.RuntimeException: can not run elasticsearch as root

**Comment by romani** [comment]
We need to find way to skip execution of elastic search plugin, I thought I did this before, they might change smth, if no luck, we can ask hibernate team for help

**Comment by rnveach** [comment]
@romani hibernate-search passed

**Comment by romani** [comment]
referenced hash is commit that we contributed to make it work - https://github.com/hibernate/hibernate-search/commit/285c557fb51bbdf4bc81af8950c466f2ec336e9d
in future we should update that place to reference some tag.

**Pull request merged**
