### PR TITLE
Issue #3033: added more support for openjdk 8 and 9

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3033

This fixes all issues with openjdk except for 
* the variable declaration:
````
@B Object o = new @B String @B [3];
````
`test/tools/pack200/typeannos/TypeUseTarget.java:40:8: expecting "class", found 'Object'`
Which looks like antlr is confused about what it is and may require some rewriting somewhere.

* and the variable definition:
````
int compile-error;
````
`/javax/xml/bind/jxc/8073519/InputWithError.java:28:10: unexpected token: compile`
Which I am surprised the `-` is allowed.

`parameterIdent` was created so everything for `id` is under it.
Regression will follow.

### CODE REVIEW

**Comment by romani** [comment]
> Which I am surprised the `-` is allowed

it is not allowed, it is jdk testing on wrong java files. We need to keep them in excludes.
checkstyle should not run on sources that are not compiled by `javac`.

> Which looks like antlr is confused about what it is and may require some rewriting somewhere.

please place a commands you used to receive output it will help a lot to understand the issue.
If file is not compilable - checkstyle should exclude it from validation.

**Comment by rnveach** [comment]
@romani 

> it is jdk testing on wrong java files ...We need to keep them in excludes.

Ok.
It is the only one. Like I said, run of 8 and 9 only left these 2 issues.

> please place a commands you used to receive output

I just used `checkstyle-tester` with just a TreeWalker config and a custom CS version that didn't stop once it received an exception (just to get all errors in one run), and with `projects-to-test-on.properties` with no exclusions on 8 and 9.
JavaC compiled it.
````
$ javac -version
javac 1.8.0_72-internal
$ javac downloads/openjdk8/test/tools/pack200/typeannos/TypeUseTarget.java
$ 
````
Here is shortened report, which is also compilable:
````
$ cat TestClass.java
package test;

import java.lang.annotation.Target;
import java.lang.annotation.ElementType;

public class TestClass {
    void method() {
        @B Object o = new @B String @B [3];
    }
}
@Target(ElementType.TYPE_USE)
@interface B { }

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
    </module>
</module>

$ java -jar checkstyle-6.19-all.jar -c TestConfig.xml TestClass.java
Starting audit...
TestClass.java:8:12: expecting "class", found 'Object'
TestClass.java:8:30: unexpected token: String
TestClass.java:8:40: unexpected token: [
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:281)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:196)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:396)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:330)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:161)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: MismatchedTokenException occurred during the analysis of file TestClass.java.
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:193)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:301)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:271)
    ... 4 more
Caused by: TestClass.java:9:5: expecting EOF, found '}'
    at antlr.Parser.match(Parser.java:211)
    at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:211)
    at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:440)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:175)
    ... 7 more
Checkstyle ends with 1 errors.
````

**Comment by romani** [comment]
> Here is shortened report, which is also compilable (I checked):

please move this to separate issue.

> Like I said, run of 8 and 9 only left these 2 issues.

not clear why we miss such failures by CI:
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-for-circle.properties
we

> Issue #3033

please create separate issue for each grammar fix (current PR is ok, just need reference to specific issue), 3033 was created to only classify problems. 
Separate issues will make our release notes clear for users when and what was fixed.

**Comment by romani** [comment]
@rnveach 

> not clear why we miss such failures by CI:

It is due to suppressions at checkstyle-tester/projects-for-circle.properties . Please provide an update to this file to minimize exclude scope as much as possible.

PR could be closed as it will be spit in few PRs.

**Pull request closed without merging**
