### PR TITLE
Issue #13321: Kill mutation for SummaryJavaDocCheck-8

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for SummaryJavaDocCheck-8

-----

# Check :- 
https://checkstyle.org/checks/javadoc/summaryjavadoc.html#SummaryJavadoc

-----

# Mutation 
https://github.com/checkstyle/checkstyle/blob/8f4e75f45df394afb71147fd35b25535f7dda40d/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L934-L941

-----

# Explaination

isPeriodNotAtEnd is called only at 
https://github.com/checkstyle/checkstyle/blob/8f4e75f45df394afb71147fd35b25535f7dda40d/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java#L508-L510

know in this method as a sentence summaryVisible is passed which we get from getVisibleContent
https://github.com/checkstyle/checkstyle/blob/8f4e75f45df394afb71147fd35b25535f7dda40d/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java#L580-L583
which already return string with trim

-----

# Regression :- 

-----

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/61eaa69fe98585b6ee1882ca082362bc/raw/316ca02ce9fd290119d9bfc560f2b11e84a1b685/Summary.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/360a95ed7bb60d7a0956e531199d484c4d6f6617/test-projects.properties
Report label: new-Regression-2

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Review by romani — APPROVED** [review]
Ok to merge if reports are clean

**Comment by Kevin222004** [comment]
failure not relates to changes

**Comment by Kevin222004** [comment]
Github, generate report

**Review by rdiachenko — APPROVED** [review]
lgtm

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

**Comment by romani** [comment]
@Kevin222004 , pr is ready for merge, please fix conflict.

**Comment by Kevin222004** [comment]
@romani done

**Pull request merged**
