### PR TITLE
Issue #9488: updated example of AST for TokenTypes.LITERAL_PRIVATE

### LINKED ISSUE #9488: update example of AST for TokenTypes.LITERAL_PRIVATE
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_PRIVATE

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

### PR DESCRIPTION
**Pull request by theanmolsharma**
fixes #9488 : 

Screenshot 2021-03-28 at 5 03 57 PM

Source used to generate AST:
```
public class MyClass {
    private int x;
}
```

Generated AST:
```
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> MyClass [1:13]
`--OBJBLOCK -> OBJBLOCK [1:21]
    |--LCURLY -> { [1:21]
    |--VARIABLE_DEF -> VARIABLE_DEF [2:4]
    |   |--MODIFIERS -> MODIFIERS [2:4]
    |   |   `--LITERAL_PRIVATE -> private [2:4]
    |   |--TYPE -> TYPE [2:12]
    |   |   `--LITERAL_INT -> int [2:12]
    |   |--IDENT -> x [2:16]
    |   `--SEMI -> ; [2:17]
    `--RCURLY -> } [3:0]
```

Expected Update for JavaDoc:
```
VARIABLE_DEF -> VARIABLE_DEF
 |--MODIFIERS -> MODIFIERS
 |   `--LITERAL_PRIVATE -> private
 |--TYPE -> TYPE
 |   `--LITERAL_INT -> int
 |--IDENT -> x
 `--SEMI -> ;
```

### CODE REVIEW

**Review by CryptoSingh1337 — CHANGES_REQUESTED** [review]
Ci failure
`[ERROR] [checkstyle] [ERROR] /drone/src/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:1405: Javadoc tag '@see' should be preceded with an empty line. [RequireEmptyLineBeforeBlockTagGroup]`

please add a blank line after `</pre>`
Like:
```
* </pre>
*
* @see
```

**Review by romani — APPROVED** [review]

**Review by romani — CHANGES_REQUESTED** [review]
Ci should be all green

**Comment by romani** [comment]
@theanmolsharma , please fix https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/38442111/job/vfx07n98axfjk629#L251
Make sure that `mvn verify` passing on your local before you push.

**Comment by romani** [comment]
Github, rebase

**Comment by theanmolsharma** [comment]
Github, rebase

**Review by romani — APPROVED** [review]

**Pull request merged**
