### PR TITLE
Fix NPE when setting classpath.

### PR DESCRIPTION
**Pull request by asheldon**
Issue introduced with b8ca6a585b824e91b3b8c72dd5cc53c0eb0ab0f1

### CODE REVIEW

**Comment by romani** [comment]
sorry, that was caused by https://github.com/checkstyle/checkstyle/commit/b8ca6a585b824e91b3b8c72dd5cc53c0eb0ab0f1, how much that cause problem to you ?

**Comment by asheldon** [comment]
In terms of functionality, this was a 100% break for me. In terms of debugging, I spent more time remembering how to do a pull request in GitHub.

**Comment by romani** [comment]
Can you wait till next release - 6.4  ? I try to do release ones a month(end of month).

**Comment by asheldon** [comment]
Yes, I can wait for 6.4.

**Pull request merged**
