### PR TITLE
Issue #3797: fix default and acceptable tokens for NPathComplexityCheck

### PR DESCRIPTION
**Pull request by kazachka**
Issue #3797

### CODE REVIEW

**Comment by romani** [comment]
Issue 56 is not related.
It is separate general issue, please create an issue that explains why this is required to be done and make reference to it in commit.

xdoc is also need to be updated, as you did in original PR.

**Comment by romani** [comment]
I already created you #3797, so just reference it kin git commit message.

**Comment by kazachka** [comment]
Updated PR and commit issue references

**Comment by romani** [comment]
I canceled Travis build for MacOS manually it is fine to skip it.

**Pull request merged**
