### PR TITLE
Issue #7779: JavadocStyleCheck incorrectly allows "style" tag

### LINKED ISSUE #7779: JavadocStyleCheck incorrectly allows "style" tag
From https://github.com/checkstyle/checkstyle/pull/7717#issuecomment-593454809
`style` is one of the `ALLOWED_TAGS` in JavadocStyleCheck:
https://github.com/checkstyle/checkstyle/blob/12c6e69fe7de3d462f5ca117dc4a6f0ba51a1d7c/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L209-L218

However this is not reflected in the javadoc or xdoc: https://checkstyle.org/config_javadoc.html#JavadocStyle

On closer analysis, it seems that `<style>` is not even a valid javadoc tag.

```
D:\checkstyletest>type config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <module name="TreeWalker">
        <module name="JavadocStyle"/>
    </module>
</module>

D:\checkstyletest>cd test

D:\checkstyletest\test>type Test.java
/**
 * First sentence.
 *
 * <div>this is a valid tag</div>
 * <var>this is also a valid tag</var>
 * <foo>this is not a valid tag</foo>
 * <style>is this a valid tag?</style>
 *
 */
public class Test {}
D:\checkstyletest\test>javadoc --version
javadoc 11.0.5

D:\checkstyletest\test>javadoc Test.java
Loading source file Test.java...
Constructing Javadoc information...
Standard Doclet version 11.0.5
Building tree for all the packages and classes...
Test.java:6: error: unknown tag: foo
 * <foo>this is not a valid tag</foo>
   ^
Test.java:6: error: unknown tag: foo
 * <foo>this is not a valid tag</foo>
                               ^
Test.java:7: error: unknown tag: style
 * <style>is this a valid tag?</style>
   ^
Test.java:7: error: unknown tag: style
 * <style>is this a valid tag?</style>
                              ^
Generating .\Test.html...
Generating .\package-summary.html...
Generating .\package-tree.html...
Generating .\constant-values.html...
Building index for all the packages and classes...
Generating .\overview-tree.html...
Generating .\index-all.html...
Building index for all classes...
Generating .\allclasses-index.html...
Generating .\allpackages-index.html...
Generating .\deprecated-list.html...
Building index for all classes...
Generating .\allclasses.html...
Generating .\allclasses.html...
Generating .\index.html...
Generating .\help-doc.html...
4 errors

D:\checkstyletest\test>cd ..

D:\checkstyletest>java -jar -Duser.language=en -Duser.country=US checkstyle-8.30-all.jar -c config.xml test\Test.java
Starting audit...
[ERROR] D:\checkstyletest\test\Test.java:6:32: Extra HTML tag found: </foo> [JavadocStyle]
Audit done.
Checkstyle ends with 1 errors.
```

Since javadoc does not recognize the `style` tag, I would expect that Checkstyle raises a violation for it as well. This should be achievable by dropping `style` from `ALLOWED_TAGS`.

### PR DESCRIPTION
**Pull request by wltan**
Fix #7779: JavadocStyleCheck incorrectly allows "style" tag
Sample run:
```
D:\checkstyletest>type config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <module name="TreeWalker">
        <module name="JavadocStyle"/>
    </module>
</module>

D:\checkstyletest>cd test

D:\checkstyletest\test>type Test.java
/**
 * First sentence.
 *
 * <div>this is a valid tag</div>
 * <var>this is also a valid tag</var>
 * <foo>this is not a valid tag</foo>
 * <style>is this a valid tag?</style>
 *
 */
public class Test {}
D:\checkstyletest\test>javadoc --version
javadoc 11.0.5

D:\checkstyletest\test>javadoc Test.java
Loading source file Test.java...
Constructing Javadoc information...
Standard Doclet version 11.0.5
Building tree for all the packages and classes...
Test.java:6: error: unknown tag: foo
 * <foo>this is not a valid tag</foo>
   ^
Test.java:6: error: unknown tag: foo
 * <foo>this is not a valid tag</foo>
                               ^
Test.java:7: error: unknown tag: style
 * <style>is this a valid tag?</style>
   ^
Test.java:7: error: unknown tag: style
 * <style>is this a valid tag?</style>
                              ^
Generating .\Test.html...
Generating .\package-summary.html...
Generating .\package-tree.html...
Generating .\constant-values.html...
Building index for all the packages and classes...
Generating .\overview-tree.html...
Generating .\index-all.html...
Building index for all classes...
Generating .\allclasses-index.html...
Generating .\allpackages-index.html...
Generating .\deprecated-list.html...
Building index for all classes...
Generating .\allclasses.html...
Generating .\allclasses.html...
Generating .\index.html...
Generating .\help-doc.html...
4 errors

D:\checkstyletest\test>cd ..

D:\checkstyletest>java -jar -Duser.language=en -Duser.country=US checkstyle-8.31-SNAPSHOT-all.jar -c config.xml test\Test.java
Starting audit...
[ERROR] D:\checkstyletest\test\Test.java:6:32: Extra HTML tag found: </foo> [JavadocStyle]
[ERROR] D:\checkstyletest\test\Test.java:7:31: Extra HTML tag found: </style> [JavadocStyle]
Audit done.
Checkstyle ends with 2 errors.
```
The `<style>` tag now (correctly) raises a violation, where it previously did not.

Diff report (excluding OpenJDK): https://wltan.github.io/checkstyle-reports/2020-03-05/styletag/diff/
Diff report (OpenJDK 7/8/9/10): https://wltan.github.io/checkstyle-reports/2020-03-05/styletag-openjdk/diff/

### CODE REVIEW

**Comment by strkkk** [comment]
> Diff report (is this how it works?): https://wltan.github.io/checkstyle-reports/styletag/diff/

Yes, but please put there more projects (as much as possible)

**Comment by rnveach** [comment]
JavadocStyle has many options. Make sure your changes will be hit in regression with the changes you are making. We should also have a UT, if there isn't one already, showing now we will bring up violations on `style` tag.

**Comment by wltan** [comment]
> > Diff report (is this how it works?): https://wltan.github.io/checkstyle-reports/styletag/diff/
> 
> Yes, but please put there more projects (as much as possible)

Noted. It might take a bit of time to get the full report up as each run takes quite a while on my system. I'll try and get something up in the next day or so.

> JavadocStyle has many options. Make sure your changes will be hit in regression with the changes you are making. We should also have a UT, if there isn't one already, showing now we will bring up violations on `style` tag.

I tried building on top of the existing unit tests that check HTML tags, but I'm not 100% confident that I know my way around the testing system, so I will have to figure it out if this CI doesn't pass for whatever reason.

**Comment by wltan** [comment]
After running the test on OpenJDK I found that there *are* additional violations created in OpenJDK 9 and 10. Diff report (added to first comment as well): https://wltan.github.io/checkstyle-reports/styletag-openjdk/diff/

However, it looks like the code causing the violations are code samples (judging by the `@code` and `<pre>` tags around it) and not meant to be used as actual javadoc tags. This I believe is under issue #5482.

**Comment by romani** [comment]
I would not recommend to pay that much attention to such regression. This Check implementation is deprecated, we will pay special attention only after this Check reimplemented to AST paser.

I am ok with regression.

**Comment by wltan** [comment]
> This Check implementation is deprecated, we will pay special attention only after this Check reimplemented to AST paser.

What does this require exactly? From what I understand so far:
1. Rewrite `JavadocStyleCheck` to extend from `AbstractJavadocCheck` instead of `AbstractCheck` (example: [SingleLineJavadocCheck](https://github.com/checkstyle/checkstyle/blob/8bf05ced07bb04c7240ae9f60ecda3c628e9b6f6/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java#L75))
2. Traverse the Javadoc comment itself using `DetailNode` instead of directly using the raw `TextBlock` content

I'm thinking this could be a good starting point for the GSoC project "Coverage of Documentation Comments Style Guide". There seems to be a few open javadoc issues waiting for this fix, so it'd be good if we can address those to improve coverage.
- Escaping inline blocks: #3351 - #5482 - #2413 (duplicates?)
- Additional configurations: #3241
- Validating first letter: #3468

**Pull request merged**
