### PR TITLE
Issue #2396: added ast regression testing

### PR DESCRIPTION
**Pull request by rnveach**
Issue #2396.

Added new class for AST testing with Java grammar.
This gives us a full working, printable tree of our grammar and shows the code it can process is valid Java. It also puts all of this in one test so its easier to run with than scanning the entire project.
Almost every line connects to a unique part of the grammar coverage.

My final goal is to have this connected with code coverage (line coverage only). I'll make another issue for this as there seems to be some dead spots in the grammar that can be removed. Once it is connected to CC, we can make sure any additions from Java 8 are shown.

Lexer is at 91% coverage by cobertura (141 lines missing). Recognizer is at 95% (211 lines missing).
I left `testUnusedMethods` in since it was a nicer version of some of my hacks on the class to get higher line coverage.

If this is merged, the issue can be closed.

### CODE REVIEW

**Comment by romani** [comment]
good.

> Lexer is at 91% coverage by cobertura (141 lines missing). Recognizer is at 95% (211 lines missing).

If we start talking about parser regression and its coverage to catch missed part of grammar. Does it make sense to enforce current limits by cobertura configuration and fail a build if coverage is going down. :) Enforce code coverage to grow after each update for grammar.

**Comment by rnveach** [comment]
@romani 
We can start it now. I wasn't sure you wanted it part of this same issue.

My original plan was to first get 100% line coverage if you approved of some of the reflection hacks to gain that, as most missing lines are error handling and can't be hit normally.
Since we are talking about it, here is an example:
````
AssertGeneratedJavaLexer.verifyFail("mSTD_ESC", 'a');
AssertGeneratedJavaLexer.verifyFail("mSTD_ESC", '0', (char) 0xFFFF);
AssertGeneratedJavaLexer.verifyFail("mCHAR_LITERAL", '\'', '\'');
AssertGeneratedJavaLexer.verifyFailNoGuessing("mID_PART", '¿');
````

Since we aren't at 100%, if we start CC now we have to remember to manually check the % and possibly change it for each update. Removing bad grammars will make the % go up of course. Adding new grammars with unreachable error protections could make % go down even if all new grammar is hit. Also without 100%, we probably could keep the same percentage in an update but still miss some new grammar portions in coverage.
Percentages aren't that exact to work with when you know you will have some missing coverage, but I didn't see any options for a different counting measure like number of lines.

**Comment by romani** [comment]
> My original plan was to first get 100% line coverage if you approved of some of the reflection hacks to gain that, as most missing lines are error handling and can't be hit normally.

I am ok.

> Adding new grammars with unreachable error protections could make % go down even if all new grammar is hit.

please put that config in this PR. We did the same for all our code in 2015, we started to some numbers in limits, and during 2015 were able to make it 100%(all exceptions are removed). But limits have to set right now.

**Comment by rnveach** [comment]
@romani Done.

**Comment by romani** [comment]
we need precise coverage(branch and line) for each generated file
com/puppycrawl/tools/checkstyle/grammars/GeneratedJavaLexer.java
com/puppycrawl/tools/checkstyle/grammars/GeneratedJavaRecognizer.java
com/puppycrawl/tools/checkstyle/grammars/GeneratedJavaTokenTypes.java

In other case it is definitely useless, and we will unlikely come to 100%.

**Comment by rnveach** [comment]
@romani Done.
TokenTypes isn't needed. Cobertura reports N/A for the class.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
