### PR TITLE
Issue #3812: Fixed google_checks.xml to disallow abbreviations in identifier names

### LINKED ISSUE #3812: Change google_checks.xml to disallow abbreviations in identifiers names in accordance with Google Style Guide
From [Google Java Style Guide section 5.3](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case):

> Recommended: if any word already has a conventional camel-case appearance in common usage, split this into its constituent parts (e.g., "AdWords" becomes "ad words"). Note that a word such as "iOS" is not really in camel case per se; it defies any convention, so this recommendation does not apply.

> lowercase everything (including acronyms), then uppercase only the first character of:
... each word, to yield upper camel case, or
... each word except the first, to yield lower camel case

Thus, we need to set ```allowedAbbreviationLength``` to 0. This issue need to be done after https://github.com/checkstyle/checkstyle/issues/3721

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #3812 
Diff report: https://shashwatj07.github.io/diff4/index.html

### CODE REVIEW

**Comment by rnveach** [comment]
@shashwat70 Please provide regression of AbbreviationAsWordInName inside google config with switch from 1 to 0.

**Comment by shashwat70** [comment]
> @shashwat70 Please provide regression of AbbreviationAsWordInName inside google config with switch from 1 to 0.

Added link in PR description.

**Comment by shashwat70** [comment]
@romani ping

**Comment by romani** [comment]
@shashwatj07 , please recheck website , I got 404.
Sorry for delay in reply.

**Comment by shashwatj07** [comment]
> @shashwatj07 , please recheck website , I got 404.
> Sorry for delay in reply.

done @romani

**Comment by romani** [comment]
@shashwatj07 , please rebase one more time, there is conflict.

**Comment by shashwatj07** [comment]
> @shashwatj07 , please rebase one more time, there is conflict.
> 
> code changes is good, ok to merge ones CI become happy

Done. Dying to see green CI now. @romani

**Comment by shashwatj07** [comment]
CI is green. Awaiting merge. @romani

**Pull request merged**
