### PR TITLE
Fixed NumberFormatException on Japanese environment

### PR DESCRIPTION
**Pull request by e-taka**
Fixed NumberFormatException, because message_ja.properties has invalid format elements.

### CODE REVIEW

**Comment by romani** [comment]
Thanks a lot. Build will fail as we have strict format for commit message.

Please create issue, show how to reproduce priblem by CLI, and reference issue number in commit message.

**Comment by mkordas** [comment]
@e-taka 
Are you able to [fix the commit message](http://stackoverflow.com/questions/8981194/changing-git-commit-message-after-push-given-that-no-one-pulled-from-remote)?

**Comment by e-taka** [comment]
I'm sorry for being late, changed the commit message.

**Comment by romani** [comment]
merged as FF.

thanks a lot !

**Pull request closed without merging**
