### PR TITLE
minor: check this out

### PR DESCRIPTION
**Pull request by rnveach**
Testing.

Not for merging.

### CODE REVIEW

**Comment by rnveach** [comment]
@romani ping CI did not fail

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/pull/11247/checks?check_run_id=4988769277
Adding `exit 1` did not fix the issue. I am not sure what the problem is.

**Comment by romani** [comment]
```
script:
  - ./.ci/travis.sh init-m2-repo
  - ./.ci/travis.sh run-command "$CMD"

after_success:
  - ./.ci/travis.sh run-command-after-success
  - ./.ci/travis.sh deploy-snapshot
  - ./.ci/travis.sh git-diff
  - ./.ci/travis.sh ci-temp-check

```

after success ..... we need to move 
```
  - ./.ci/travis.sh git-diff
  - ./.ci/travis.sh ci-temp-check

```

to "scripts"

**Comment by rnveach** [comment]
Why are the other 2 allowed to stay if the others fail and don't fail the build?

**Comment by romani** [comment]
> Is it possible to build a way to test/regresssion shell scripts?

rephrase question.

**Comment by rnveach** [comment]
Fix seems to be working but Hibernate also has unstaged changes.
https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/557598798#L7066
> Untracked files:
	apache-maven-3.8.1-bin.zip
	apache-maven-3.8.1/

**Comment by romani** [comment]
We can try to change command we run over hibernate to skip this file creation, or simply remove it in our bash script.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/pull/11247/checks?check_run_id=5029286021
Fix is resolving travis now, I'll create a new PR

**Comment by romani** [comment]
fixed in https://github.com/checkstyle/checkstyle/pull/11272

**Pull request closed without merging**
