### PR TITLE
Issue #4586:Split and Organize Checkstyle inputs by Test for checks in 'javadoc' package 

### PR DESCRIPTION
**Pull request by djydewang**
Issue #4586 
Some thing is wrong When I run `mvn clean verify`:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:testCompile (default-testCompile) on project checkstyle: Compilation failure: Compilation failure: [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodInheritDoc.java:[6,5] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypePublicOnly.java:[49,13] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypePublicOnly.java:[54,5] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypePublicOnly.java:[59,15] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypePublicOnly.java:[64,12] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodPublicOnly.java:[49,13] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodPublicOnly.java:[54,5] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodPublicOnly.java:[59,15] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodPublicOnly.java:[64,12] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodScopeAnonInner.java:[35,5] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodSetterGetter.java:[67,5] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodSetterGetter.java:[69,12] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/InputJavadocVariablePublicOnly.java:[49,13] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/InputJavadocVariablePublicOnly.java:[54,5] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/InputJavadocVariablePublicOnly.java:[59,15] 方法声明无效; 需要返回类型 [ERROR] /home/bbg/project/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/InputJavadocVariablePublicOnly.java:[64,12] 方法声明无效; 需要返回类型`
And I don't kown how to fix it.
Please help me.
Thanks.

### CODE REVIEW

**Comment by romani** [comment]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:testCompile (default-testCompile) on project checkstyle: Compilation failure: Compilation failure:
[ERROR] /home/rivanov/java/github/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodSetterGetter.java:[67,5] invalid method declaration; return type required

you did 
 ...yle/checks/javadoc/InputSetterGetter.java → ...ethod/InputJavadocMethodSetterGetter.java

error line
```
InputSetterGetter() {}
```

you changed name of file/class but did not change name of c-tor.

**Comment by romani** [comment]
@djydewang , please split your huge commit into few, to let us review it easily.
each PR should cover update only for one Check and their inputs.

**Comment by djydewang** [comment]
Thanks!I get it.

**Comment by romani** [comment]
before pushing to remote please make sure that `mvn verify` is passing on your local.
please fix all violations from all CIs.

**Comment by romani** [comment]
@djydewang , changes in catalog.xml are not expected in you issue.
But problem with file content is valid, commit message was changed and merged manually - https://github.com/checkstyle/checkstyle/commit/1d3a04af7a446e71f566d33d6230373de3601318.

**Pull request closed without merging**
