### PR TITLE
Issue #9142: resolve Assertions.assertTrue

### PR DESCRIPTION
**Pull request by rnveach**
Issue #9142

More automated changes and I reviewed them again to ensure formatting was still good since these are more likely to be longer.

### CODE REVIEW

**Comment by rnveach** [comment]
After this PR, only 4 suppressions can be removed.
````
FinalLocalVariableCheckTest
ReturnCountCheckTest
AllBlockCommentsTest
AllSinglelineCommentsTest
````

**Comment by romani** [comment]
@rnveach , please merge https://github.com/checkstyle/checkstyle/pull/11090 first.

**Comment by romani** [comment]
Merged, please rebase and fix violations.
I used IDE to search by pattern of Regexp Check, to quickly iterate over all possible violation. It took me 30 min to update whole codebase.

**Comment by rnveach** [comment]
Done.

**Comment by romani** [comment]
I merged in alignment of ".thah" with ".isTrue"

**Review by romani — APPROVED** [review]
appoved

**Pull request merged**
