### PR TITLE
Deleted System.exit() and delegated exit control into separate method.

### PR DESCRIPTION
**Pull request by damianszczepanik**
Issue #596

### CODE REVIEW

**Comment by romani** [comment]
1) 
> author Oliver Burn

please put your name there instead, it look like whole Class need to be rewritten

2) 
>  private static final Options OPTS = new Options();
static {

that static block is not required, as it will be used only ones - it be somewhere in inner method or class

3) 
> OPTS.addOption("c", true, "The check configuration file to use.");

"Sets the check configuration file to use."

4) 
> private Main()

please move it below "public static void main(String[] args)"

5) 
> public static void main(String[] args)

even you placed "exit(1)" to  one method it does not change a logic, and logic is still abrupt.
We need to comeup to following model:
```
main() {
exitCode = 0;
 try{
    clOptions = parse(args);
    // at this point we should not use CommandLine class at all, we should use our  POJO object that contain options
  final AuditListener listener = createListener(line, out, closeOut);
  final Checker c = createChecker(config, listener);
  final List<File> files = getFilesToProcess(line);
  final int numErrs = c.process(files);
  exitWithCode(numErrs);   // not sure about this
 }
catch (*Exception) {
  printErrorMessage()
  exitCode = 1
 }
finally () {
  c.destroy()
}
exit(exitCode)
}
```

6) 
>  final AuditListener listener = createListener(line, out, closeOut);
final List<File> files = getFilesToProcess(line);

we should not use CommandLine object ("line") there, methods should receive exact values for processing. 

7) 
>  final List<File> files = getFilesToProcess(line);
final Checker c = createChecker(config, listener);
final int numErrs = c.process(files);

reorder to minimize distance between definition of variable and fist usage

8)
>  c.destroy();
exitWithCode(numErrs);

We need to recheck that we exit from main() only then we have ERRORs events by severity(that is defined in config file), only WARN events should not rise an error code.

9)
>  private static Checker createChecker(Configuration config,
AuditListener nosy)

please rename last parameter

10)
> traverse(new File(element), files);

we need to refactor that method to return collection of files, changing arguments is not good 

11)
> return null; // can never get here

remove it.

12)
> private static void traverse(File node, List<File> files)

just curious if java7 have some good similar util method

13)
>  catch (final IOException ex) {
exitWithMessage(String.format("Unable to load properties 

Exception is swallowed.

**Comment by damianszczepanik** [comment]
1. Done
2. It is also used in at least two places. I moved it to builder method so should look better now.
3. Done
4. Done
5. Done
6. Done
7. There might be `listener` xor `checker` xor `files` together so worrying about small details IMO is waste of time
8. Tell me more. '0' is also exit code so provide guide line what do you expect me to do
9. Done
10. Done
11. Done
12. There is some [generic method](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#walkFileTree-java.nio.file.Path-java.nio.file.FileVisitor-) but it's more like iterator than collection. Better solution which I've already used is implemented by apache io but we don't include this library in pom.xml. Any suggestion?
13. Don't see a reason for printing out the full stacktrace to end user who is interested in how to fix the problem not what happened

**Comment by romani** [comment]
@damianszczepanik ,

> AutomaticBean.java

please contribute that change at separate PR.

> There might be listener xor checker xor files together so worrying about small details IMO is waste of time

you typed that answer more time than you could swap line following lines :) :
```
final List files = getFilesToProcess(line);
final Checker c = createChecker(config, listener);
```
that improve readability of code. Please do.

> Tell me more. '0' is also exit code so provide guide line what do you expect me to do

please ignore that point, I rechecked a code and Checker return amount of ERRORs (https://github.com/damianszczepanik/checkstyle/blob/1eb3c3d9fab46a7cf8b12affb5c390fe81154983/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L59), this is exact ly what we need. All is fine.

> Better solution which I've already used is implemented by apache io but we don't include this library in pom.xml. 

ok, no need to use whole library for one method, we do care about amount of libraries we use , as pack them together in "xxxxx-all.jar" and distribute. But lets put a comment above a method that it could be substituted.

> Don't see a reason for printing out the full stacktrace to end user who is interested in how to fix the problem not what happened

Any details would help, especially if we crash. 90% or our users are java developers they will read it easily, and they will give us back that stackstrace to issue tracker during reporting a problem. So we print that details to ease our future iteration with users on problem resolving.

1)
> private static final Options OPTS = buildOptions();

no reason to have it, move to builder function or parseCLI ... .

2) 
>    public static void main(String[] args)
    {
        boolean parseResult = false;
        try {
            parseCli(args);
            parseResult = true;
        }

Checkstyle is not for parsing CLI , ParseCLI is pre-step before actual processing, that should be clearly seen in that method. Please return from parseCLI a bean with ready to use configuration information. Use that configuration bean to actually run Checkstyle.

3) 
>         catch (final ParseException e) {
            System.err.println("Could not parse parameters:" + e.getMessage());
        }
        catch (final Exception e) {
            System.err.println("Could not execute Checkstyle:" + e.getMessage());
        }

please do not hide stacktrace - let it crash with all details to user.

4) 
> private static List<File> getFilesToProcess(String[] remainingArgs)

please rename a argument, static method is out of scope of bussines login of Main, it is just a util method that ready to be moved to other class at any time.

5)
>         if (files.isEmpty()) {
            throw new CheckstyleException("Must specify files to process, found 0.");
        }

Does it make sense to place that at code that manage Checker preparation ? it is definitely not a util method business.

6) 
>  private static AuditListener createListener(CommandLine line,

"ComandLine line" --> "String format"

7) 
>                 throw new IllegalArgumentException("Invalid output format. Found '" + format
                        + "' but expected 'plain' or 'xml'.");

We need to be consistent in type of exception we throw, in rest of the code it is CheckstyleException

8) 
> private static Configuration loadConfig(CommandLine line,

the same as "6)", No ComandLine type should be to "String configPath"

9)
>             throw new CheckstyleException(String.format(
                    "Unable to load properties from file '%s' because: '%s'."
                    , file.getAbsolutePath(), ex.getMessage()));

do not swallow cause exception, put is last argument for c-tor.

**Comment by romani** [comment]
@ damianszczepanik , release 6.6 will be on that weekends, do you have time to finish that PR ?

**Comment by damianszczepanik** [comment]
Tomorrow,  hopefully

**Comment by damianszczepanik** [comment]
0~1. Done
2. I split this logic into two methods but not sure if this is what you expected
3. Added
4. Done
5. As long as it is not pure util method implemented somewhere else - I'm not sure but lets make this change
6. Done - however sometimes I need to read your twice to understand your mind :)
7. Done
8. Done
9. Done

... but one of the build failed

**Comment by romani** [comment]
merged as FF.

I decided to merge your code even it is not final version of it, but it far better then previous implementation, I will put in issue additional comments. Issue is not resolved. Let me know if still have desire to continue.

**Pull request closed without merging**
