### PR TITLE
Issue #13345: Enable examples tests for upperell

### PR DESCRIPTION
**Pull request by AayushSaini101**
Part of https://github.com/checkstyle/checkstyle/issues/13345

### CODE REVIEW

**Comment by romani** [comment]
Please do single commit in PR

**Comment by AayushSaini101** [comment]
> Please do single commit in PR

@romani ,  the mvn clean verify is passed in my local, but still checks failing. 
image

**Review by romani — APPROVED** [review]
ok to merge

**Comment by AayushSaini101** [comment]
> ok to merge

Please tag hactober accepted

**Review by nrmancuso — APPROVED** [review]

**Comment by nrmancuso** [comment]
CircleCI failure is not related to changes here, it is failing in other PRs from forked branches

**Pull request merged**
