### PR TITLE
Issue #11968: false Postive In VariableDeclarationUsageDistance

### PR DESCRIPTION
**Pull request by arinmodi**
Closes : #11968 : VariableDeclarationUsageDistance not able to handle try with resources properly

Diff Regression config: https://gist.githubusercontent.com/arinmodi/911bd345758c522c77efe6b82afc8c4e/raw/13d8c333a277c0cdb45ce865d43ea3dfde9f27f6/VariableDeclarationUsageDistance.xml

### CODE REVIEW

**Comment by arinmodi** [comment]
Github, generate report

**Comment by arinmodi** [comment]
Github, generate report

**Comment by arinmodi** [comment]
@Vyom-Yadav @romani, can please review this ?

**Comment by romani** [comment]
please add to test cases:
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b182772_2022180059/reports/diff/apache-struts/index.html#A3
please all distinct code examples from https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b182772_2022180059/reports/diff/index.html that our test input code base is missing for this Check. We should not rely much on regressions, all/most possible usages of structures/.... should be in our tests.

add https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b182772_2022180059/reports/diff/apache-struts/index.html#A2 and explain why it become 3 ? distance is 2.

**Comment by nrmancuso** [comment]
Github, generate report

**Comment by nrmancuso** [comment]
@arinmodi do you plan to continue work on this PR? If not, we will close it soon.

**Comment by romani** [comment]
@jxr98, please help to finish fix for this issue. We lost connection to author. So this PR is closed.

**Comment by jxr98** [comment]
No problem.

**Comment by jxr98** [comment]
Github, generate report

**Comment by romani** [comment]
@jxr98, please create your own PR

**Pull request closed without merging**
