### PR TITLE
Use EqualsVerifier to test equals methods. #1555

### PR DESCRIPTION
**Pull request by mkordas**
Fixes `ObjectEqualsNull` inspection violations.

Description:
>Reports on calls to .equals() which have null as an argument. The semantics of such calls are almost certainly not what was intended.

### CODE REVIEW

**Comment by romani** [comment]
hmmm, I completely do not see a problem.

> Reports on calls to .equals() which have null as an argument. The semantics of such calls are almost certainly not what was intended.

we do not check for NULL in method that is not right, and need to be fixed. But why fix is "final" ? please send me some links to educate me.

**Comment by mkordas** [comment]
Making class final is not related to IDEA Inspection. It is to satisfy EqualsVerifier only.

**Comment by romani** [comment]
and no I confused completely, please split IDEA and EqualsVerifier fixes into different PR, I still do not understand a reason for "final".

**Comment by mkordas** [comment]
@romani - I've decided do use 4 commits instead of 1 to show you exact reasons of each change. Is it more clear now?

**Comment by romani** [comment]
merged as FF, thanks a lot.

My concern is that most of our classes do not have "final" on that methods and you fix only that case.
Most likely you will do that in next, if that is true, please do that in one PR as chances of conflicts in that methods are minimal.

**Comment by mkordas** [comment]
@romani - it's because of IntMatchFilter uses `instanceof IntMatchFilter` in equals method. I can replace it with `.getClass()` and remove final modifiers.

**Comment by romani** [comment]
interesting nuance, lets revert "final"

**Pull request closed without merging**
