### PR TITLE
Issue #7804: Resolve Pitest Issues - CustomImportOrderCheck (3)

### LINKED ISSUE #7804: Resolve Pitest Issues - CustomImportOrderCheck (3)
Child issue of https://github.com/checkstyle/checkstyle/issues/7797 ,

https://github.com/checkstyle/checkstyle/blob/abf829f542023e089c741c55f73098cae52dcb12/.ci/pitest.sh#L79

### PR DESCRIPTION
**Pull request by DXTkastb**
fixes #7804

### CODE REVIEW

**Comment by DXTkastb** [comment]
@romani @rnveach  could you please help me here.  I received this error in Travis CI: 
`no error test on simple-binary-encoding" USE_MAVEN_REPO="true" CMD="./.ci/travis/travis.sh no-error-test-sbe`
I couldn't understand this problem. Can you please elaborate as to why this could occur?

**Comment by DXTkastb** [comment]
@strkkk @rnveach, please review.

**Comment by romani** [comment]
@DXTkastb , please provide few regression diff reports (on all projects, on few different configs of Check) to make sure we remove code and there is no changes at all.

**Comment by DXTkastb** [comment]
@romani , New diff report: https://dxtkastb.github.io/importordernewdiff/index.html

I have attached both new and old diff report to the issue page comment.

**Comment by DXTkastb** [comment]
please review.

**Pull request merged**
