### PR TITLE
Issue #3946: code cleanup xdocs/config_annotation.xml

### PR DESCRIPTION
**Pull request by shahdivyam**
Made changes to the xdocs/config_annotation.xml to match the following formatting. 
TOKEN1
,TOKEN2
,TOKEN3
.
Resolves the issue partially, will make seperate PR's for each of the xdocs/*.xml files where code cleanup is required.

### CODE REVIEW

**Comment by rnveach** [comment]
@shahdivyam Read over https://github.com/checkstyle/checkstyle/wiki/PR-rules .
Keep number of commits at 1.
Please fix failing CI.

**Comment by rnveach** [comment]
@shahdivyam ping! Do you have any issues?

**Comment by romani** [comment]
@shahdivyam , ping. If you lost interest to continue this PR, please just close this PR, to not block other.

in no reply till 1 March, PR will be close.

**Comment by romani** [comment]
@rnveach ,
from logs:`[ERROR]   XdocsPagesTest.testAllCheckSections:313->validateCheckSection:389->validatePropertySection:465->validatePropertySectionProperties:575->validatePropertySectionPropertyTokens:641 config_annotation.xml section 'AnnotationLocation' should have all the acceptable tokens expected:<... of tokens CLASS_DEF[, INTERFACE_DEF, ENUM_DEF, METHOD_DEF, CTOR_DEF, VARIABLE_DEF, PARAMETER_DEF, ANNOTATION_DEF, TYPECAST, LITERAL_THROWS, IMPLEMENTS_CLAUSE, TYPE_ARGUMENT, LITERAL_NEW, DOT, ANNOTATION_FIELD_DEF].> but was:<... of tokens CLASS_DEF[ ,INTERFACE_DEF ,ENUM_DEF ,METHOD_DEF ,CTOR_DEF ,VARIABLE_DEF ,PARAMETER_DEF ,ANNOTATION_DEF ,TYPECAST ,LITERAL_THROWS ,IMPLEMENTS_CLAUSE ,TYPE_ARGUMENT ,LITERAL_NEW ,DOT ,ANNOTATION_FIELD_DEF ].>
`

main diff part:
`CLASS_DEF[, INTERFACE_DEF,`
`CLASS_DEF[ ,INTERFACE_DEF ,`

do we need to update expected result in  UT (or just ignore such difference)?

**Comment by rnveach** [comment]
> do we need to update expected result in UT (or just ignore such difference)?

UT has to be changed somehow, either by how we parse or what we require, otherwise it will always fail.
Since UT has to change, you cannot change 1 page at a time unless you disable the UT until the end.

We should try to change the display from `XXX[space],` to `XXX,[space]`.
That text is generated for the expected comes from a common utility that other projects can use and it would be very odd to have it print the text the other way.

So we should fix how the parsing is done.
https://github.com/checkstyle/checkstyle/blob/90f20e09869c71eb22190ad9c1d46d5deec324a5/src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java#L646
https://github.com/checkstyle/checkstyle/blob/90f20e09869c71eb22190ad9c1d46d5deec324a5/src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java#L650

The text content contains the `\n`s so it should be possible.

**Pull request closed without merging**
