### PR TITLE
Issue #11741: Indentation: false positives when switch expression is invocation target

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #11741: Indentation: false positives when switch expression is invocation target

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/172e69e9677186ad5cd37555bca056ad/raw/156954868238915e55b08254a9ae8b0b8b2ed550/indent.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/b044524b744ed7a8ba2780d49ca4c0bc/raw/fb851ad906625c40e1e556b546acf43eefa53050/JDK22.properties
Report label: Jdk-22-Project

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by nrmancuso** [comment]
@Kevin222004 please use projects file from other PR to generate report (with newer openjdks)

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
@nrmancuso can you pelase take a look at this report generation error https://github.com/checkstyle/checkstyle/actions/runs/7300582537

**Comment by nrmancuso** [comment]
@Kevin222004 looks like out of memory error, see
https://github.com/checkstyle/checkstyle/actions/runs/7300582537/job/19895526866#step:9:571

These manifest strangely sometimes. This can happen on larger repos like openjdk when there is a lot of differences. Let’s just try openjdk 22, Java maintainers are good about keeeping older inputs from previous versions.

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Please Start reviewing I will try to generate the report. It is actually failing on my local as well with same kind of error.

**Comment by nrmancuso** [comment]
@Kevin222004 you can try openjdk21 project from https://github.com/checkstyle/contribution/pull/821 with one only one indentation module at a time  to reduce memory usage

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by nrmancuso** [comment]
@Kevin222004 please try again with only one indentation check module

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/6aa4037_2023142119/reports/diff/openjdk21/index.html#A18 looks like a messages demands even more weird indentation.

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Pr is not ready for review Updated to generate regression report

**Comment by nrmancuso** [comment]
>Pr is not ready for review Updated to generate regression report


@Kevin222004 let's put this PR in draft mode to have a clear signal to other maintainers

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
@nrmancuso @romani can you please look at this pr and give some suggestions to improve it.

**Comment by nrmancuso** [comment]
> @nrmancuso @romani can you please look at this pr and give some suggestions to improve it.

@Kevin222004 can you be more specific?

**Comment by romani** [comment]
Test failure:
```
[ERROR] Failures: 
[ERROR]   AllTestsTest.testAllInputsHaveTest:63->walk:87->lambda$testAllInputsHaveTest$2:64->verifyInputFile:154 Resource must start with 'Input' or 'Expected': com/puppycrawl/tools/checkstyle/checks/indentation/indentation/NewSwitch$Internal.class
expected to be true
[ERROR] Errors: 
[ERROR]   ArchUnitSuperClassTest.testChecksShouldHaveAllowedAbstractClassAsSuperclass:99 » UnsupportedClassVersion com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpression4$ResultException has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
[ERROR]   ImmutabilityTest.<clinit>:196 » UnsupportedClassVersion com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpression4$ResultException has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
[ERROR]   ImmutabilityTest.testClassesWithMutableFieldsShouldBeStateful » NoClassDefFound Could not initialize class com.puppycrawl.tools.checkstyle.internal.ImmutabilityTest
[ERROR]   ImmutabilityTest.testFieldsInStatelessChecksShouldBeImmutable » NoClassDefFound Could not initialize class com.puppycrawl.tools.checkstyle.internal.ImmutabilityTest
[ERROR]   ImmutabilityTest.testUtilClassesImmutability » NoClassDefFound Could not initialize class com.puppycrawl.tools.checkstyle.internal.ImmutabilityTest
[INFO] 
[ERROR] Tests run: 4910, Failures: 1, Errors: 5, Skipped: 505

```

**Comment by romani** [comment]
Please add this case to Inputs https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b9a6a62_2024172931/reports/diff/openjdk21/index.html#A1
Interesting why we get violation on it. It might be due to previous indentation is wrong, but let's be confident.

Please remove binary class files from PR.

**Comment by Kevin222004** [comment]
https://github.com/checkstyle/checkstyle/pull/14165#issuecomment-1884678451 

> @Kevin222004 can you be more specific?

@nrmancuso I meant to ask about the approach and the way I am fixing this issue.

I have once again tried to start from the beginning but in the end, I come to the same conclusion that getIndent() needs to be updated.

 After the recent report, I can see that the majority of issues are in the code something like `return switch(...) {..}` 
I will update this and hope the diff will become minimal.

**Comment by nrmancuso** [comment]
@Kevin222004 if I had to guess, issue originates in some other handler that deals with expressions. We might need to make changes there too.

**Comment by romani** [comment]
If issue results in avalanche of fixes, due to our findings in diff report. We can stop, prove that updated Check works same as before on specific code structure, create separate issue on it, and merge this PR.

**Comment by Kevin222004** [comment]
> @Kevin222004 if I had to guess, issue originates in some other handler that deals with expressions. We might need to make changes there too.

I think I have to study a bit more for this PR.

**Comment by romani** [comment]
@Kevin222004, please keep in mind that this Check is most compliated Check in our project, it is also have some design problems that might not allow to do good behavior on all cases. That is why we have https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2024-Project-Ideas#project-name-reconcile-formatters-of-eclipse--netbeans-and-intellij-idea-ides-by-checkstyle-config as dealing with this module is not easy. 
If you feel that this update is too complicated for you, do not hesitate to abandon PR and close it, no reason to be burned by this issue, you can fix numerous others meanwhile and will help user a way more what fix of this issue. And you can come back to this update a bit later, as you become more experienced.

**Comment by Kevin222004** [comment]
I am closing this pr and will come with some good solution.

**Pull request closed without merging**
