### PR TITLE
Clarify misleading command line tool (CLI) output solves #1062

### PR DESCRIPTION
**Pull request by Bhavik3**

### CODE REVIEW

**Comment by romani** [comment]
@Bhavik3 ,

> 
Found Audit violations >> exit(0)
Found Audit errors >> exit(numOfErrors)

so we have some misunderstanding there. Checkstyle report all his findings as violations, not as errors. Checkstyle have an concept of Severity - http://checkstyle.sourceforge.net/config.html#Severity . So user configuration is defining how severe Checkstyle violations - it could be even "ignore". Warnings are never smth that fail validation. Validation is failed only by ERRORs (unexpected exception, of user defined in config).

So please use ```final int errorCount = counter.getCount();``` to return from Main.main().

**Comment by Bhavik3** [comment]
@romani 

If checkstyle finds any Errors, Main.main() will return with NumOfErrors.
If checkstyle finds Violations and not any Errors, Main.main() will return with NumOfViolations.
This is what I am doing right now.

If this is not how we want, then what should be the return value for each of the following states:

If checkstyle finds any Errors:
If checkstyle finds Violations and not any Errors:
If checkstyle finds no Violations and not any Errors:

**Comment by romani** [comment]
Now I see there we have misunderstanding, in original issue we have 
> Solution:
Found CLI violation >> exit(-1)
Found other error (but not CLI violations) >> exit(-2)
Found Audit violations >> exit(0)
Found Audit errors >> exit(numOfErrors)

we do not need count of violations. we only care about ERRORs

so text should be :
Found CLI-violations >> exit(-1)
Found other error/exception (but not CLI-violations) >> print exception details + exit(-2) 
Found any Audit checkstyle-violations but no checkstyle-violations  ERROR severity >> exit(0)
Found Audit checkstyle-violations of ERROR severity >> exit(numOfErrors)


Sorry for confusion.

**Comment by romani** [comment]
FYI: checkstyle violations by default are ERRORs - http://checkstyle.sourceforge.net/config.html#Severity , but user can change that in config file.

**Comment by Bhavik3** [comment]
@romani 
ok, I thought by default value is 'Warning'.

I have one more confusion. in case of non-existing config file or non-existing target file, is it CLI violation or Exception?

**Comment by romani** [comment]
Cli violation. Exception we throw only we run to unexpected situation, for example, user defined a big folder with sources to validate, checktyle launched, folder is accessible and checkstyle cached in memory list of files, but user remove some file from folder and checkstyle will throw exception as file was there ta the beginning and disappeared on moment of processing - completely unexpected situation

**Comment by Bhavik3** [comment]
@romani 

Ok,
According to my new commit on this PR, exit status for testNonExistingConfigFile is '-2'. should I change that?

And also have a look on other UTs and let me know.

**Comment by romani** [comment]
yes, please change.

If you can check some common problems before processing - it is expected  - so exception based logic should be avoided.

**Comment by Bhavik3** [comment]
@romani 

I was thinking of checking for config file (does it exist at specify path or not) at validateCli(CommandLine cmdLine). just like we do for '-p' option. But I think this changes in code base  is not appropriate in this PR.

**Comment by romani** [comment]
yes, please do as separate PR.

**Comment by romani** [comment]
@Bhavik3 , let finish that PR.

thanks in advance for your help.

**Comment by Bhavik3** [comment]
DONE

**Comment by romani** [comment]
@Bhavik3 ,

1)
I do not like that logic.

please refactor code to avoid usage of
```
 int errorCounter = 0;
boolean cliViolations = false;
boolean checkstyleFailed = false;
```

please use the only "int exitCode;" , and please make it calculation right a place where problem/violation/exception is caught.

2)
> exitStatus = -1 * 2;

please use just "-2"

**Comment by Bhavik3** [comment]
@romani 

1)
Done

2)
I can not use "exitStatus = - 2". It is throwing Magic number violation. that's why I am using "-1 * 2".

**Comment by romani** [comment]
:) , so please define a canstant with a name to avoid that violation.

**Comment by romani** [comment]
It whould be good to use +1 to constat too, to explain what does it mean

**Comment by Bhavik3** [comment]
@romani 
Done

**Comment by romani** [comment]
Please remove trailing comments, they are not required anymore, as all written in java code.

**Comment by Bhavik3** [comment]
comments removed ..

**Comment by romani** [comment]
looks good, thanks a lot !

**Comment by romani** [comment]
@Bhavik3 ,

please let me know if want to continue practising java contributing to our project - I will point you to next task, or you can choose it yourself.

**Pull request merged**
