### PR TITLE
Issue #13321: Kill mutation for CheckUtil-3

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for CheckUtil-3

-----

# Mutation 
https://github.com/checkstyle/checkstyle/blob/f4a33f90bf8eda8ef2cdf7f66fd60878d2aa1736/config/pitest-suppressions/pitest-utils-suppressions.xml#L57-L73

-----

# Explaination

loop run 1 time more

-----

# Regression :- 

Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e3b2e2a_2023230520/reports/diff/index.html

Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e3b2e2a_2023062205/reports/diff/index.html

-----

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/b64bf63db7a5fb640a79fd489180d853/raw/3f60390b4addc0a147b265b4220f1dc22b82a164/loop.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/360a95ed7bb60d7a0956e531199d484c4d6f6617/test-projects.properties
Report label: Regression-2

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Review by rdiachenko — APPROVED** [review]
lgtm

**Review by romani — APPROVED** [review]
Ok to merge.

@Kevin222004 , please keep adding such cases to our report of unfortunate cases

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

**Comment by romani** [comment]
Semaphore was restarted

**Pull request merged**
