### PR TITLE
Add post fields for Mailing List page, issue #743

### PR DESCRIPTION
**Pull request by Mebibyte**
Requires the group to allow posting by email. This can be set by going to Settings -> Group Settings -> Posting Options -> Allow posting by email.

### CODE REVIEW

**Comment by romani** [comment]
please remove "checkstyle-announce@googlegroups.com", nobody except of me could do post there.

**Comment by romani** [comment]
please do a reference to original issue in git commit, not at github mesage, you can check that by "git log" copmmand on your local

**Comment by Mebibyte** [comment]
Done. I thought you wouldn't want the post field for announce, but I went ahead and added it just in case. Removed that, and modified the git commit. Thanks for the help!

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
