### PR TITLE
added a lot of testing stuff

### PR DESCRIPTION
**Pull request by m-mikula**

### CODE REVIEW

**Comment by mkordas** [comment]
@m-mikula 
Thanks for the PR, here are my initial comments:
* please fix failing builds
* you should not mix different stuff in one PR - please split into a few smaller ones
* use descriptive commit messages according to our convention - `Issue #XXXX: YYYY`
* avoid any merge commits in PR, squash commits where possible

**Comment by romani** [comment]
@m-mikula , please squash all in one and let us see changes clearly to help you with other violations.

**Comment by mkordas** [comment]
@m-mikula, are you going to finish this PR? Can we help you in some way?

**Comment by romani** [comment]
release 6.11will be on this Sunday (27th of September), it would be good to finish this PR before release

**Comment by romani** [comment]
@m-mikula , please redo/rebase your PR as one commit.

1)
> src/xdocs/beginning_development.xml

please send as separate PR , commit message should be "doc: ................." .

2)
> AFlawlessExample.java and test.properties and files other 

All files that you need , please place to "resource" folder , see for examples location of "Input.........java" files.

3)
> CheckStyleAntTaskListenerTypeTest.java , .... CheckstyleAntTaskPropertyTest.java

should be merged to one test class - CheckstyleAntTaskTest.java

4)
> emptyCheck.xml

emptyConfiguration.xml

5)
There are more problems with implementation, please do point that I described above and we will continue

**Comment by romani** [comment]
@m-mikula , do you have time to finish PR ? It is completely ok to abandone PR and issue. Blocking issue resoving is not ok, another developer can continue your work.

**Comment by romani** [comment]
@m-mikula ,

release 6.12 is planned to be at 31 of October.
it would very good to finish this PR before release. Do you have time to finish PR ?

**Comment by romani** [comment]
@m-mikula , please let us know if want to abandon this PR. It is completely ok.

Another contributior could continue your work and finish this issue. I just do not want to have this issue hanging and be occupied.

If in a two week(14 days) no activity happen, I will close this PR.

**Comment by romani** [comment]
PR is closed.

**Pull request closed without merging**
