### PR TITLE
Issue #2135: Fix exception at NeedBraces check in enhanced for loops

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by mkordas** [comment]
>please make it single-exit-point method

Done, but are you sure it's more understandable right now? Method does the same in 4 lines more.

>please add to Input test case from issue to prove that case is covered.

Done.

**Comment by romani** [comment]
Line numbers are never good metric, short doest not mean easy to read and debug.  I am more and more confident that single point of exit do a lot for method maintenance. Abdrupt logic is quick to write but it will waste more time during maintenace. 

Anothet example: @sabaka refactored code to enforce single break from loop, and code become better.

**Comment by mkordas** [comment]
I also agree with general rule, but just compare the following two:
```java
        final DetailAST forEachClause = literalFor.findFirstToken(TokenTypes.FOR_EACH_CLAUSE);
        final DetailAST firstToken;
        if (forEachClause != null) {
            firstToken = forEachClause.findFirstToken(TokenTypes.EXPR);
        }
        else {
            firstToken = literalFor.findFirstToken(TokenTypes.EXPR);
        }
        return firstToken;
```

```java
        final DetailAST forEachClause = literalFor.findFirstToken(TokenTypes.FOR_EACH_CLAUSE);
        if (forEachClause != null) {
            return forEachClause.findFirstToken(TokenTypes.EXPR);
        }
        return literalFor.findFirstToken(TokenTypes.EXPR);
```

In this specific case I'm able to understand the second one faster - it's simpler and more concise.

**Comment by romani** [comment]
As you write code, do not be focused on how you will understand that later( own code is always beatiful), think about other engineer experience who will come there for the first time and need min time to understand a debug easily.

**Comment by mkordas** [comment]
Makes sense, debugging is a little bit easier in the first case.

**Comment by romani** [comment]
Main point is that idea of sinlge-exit-point there are a lot of exception and I do not know all possible cases, i learn them day by day. For now all my ideas for additional options for that Check are at sevntu project - ReturnCountExtended good step forward from ReturnCount but not a final implementation ;).

Keep questioning my requests for any update, i also could live in illussions and do not know all best practices. One day you will be right.

**Pull request merged**
