### PR TITLE
Issue #5431: Remove dependencies of tools.jar

### PR DESCRIPTION
**Pull request by romani**
Issue #5431

continuation of #5485 to pass CI

### CODE REVIEW

**Comment by romani** [comment]
TC is passed. ALL other CIs , passed in original PR. merged

**Comment by pbludov** [comment]
Thanks, @romani !
Now the chekstyle can be build with the JDK9. But some tests are failing due to the Powermock issues.
I investigate the Powermock V2 now. Unfortunately, it's still in beta stage and has a lot of issues.
But there is no plan to support JDK9 in the Powermock 1.x, so there is no alternative.

**Comment by romani** [comment]
@pbludov , Please propose by PR new Travis build items to enforce compilation (without tests) on jdk9.
We should not allow anybody to damage your achievement.

**Comment by pbludov** [comment]
@romani I'm really close to this. There just one minor issue related to changed message text in `java.lang.IllegalAccessException`. This can be easily fixed by replacing `String.startsWith` with `String.contains`

**Comment by romani** [comment]
Please Trust my experience, enforce build status now, when you finish test update you will just remove skip of tests from Travis as prove of final fix, I would even recommend to skip certain tests, and step by step remove skiped items.

**Comment by pbludov** [comment]
@romani done: https://github.com/checkstyle/checkstyle/pull/5562

**Pull request merged**
