### PR TITLE
Issue #12203: Added missing words in checkstyle docs

### PR DESCRIPTION
**Pull request by NitishKumar06**
Fix: #12203

### CODE REVIEW

**Comment by strkkk** [comment]
Github, rebase

**Comment by NitishKumar06** [comment]
@strkkk Do you want to rebase the branch?

**Comment by strkkk** [comment]
yes, github action for some reason dont work, please do it manually

пт, 30 сент. 2022 г., 14:46 Nitish Kumar ***@***.***>:

**Comment by NitishKumar06** [comment]
@strkkk My local branch is already upto date.

**Review by strkkk — APPROVED** [review]

**Review by romani — APPROVED** [review]

**Pull request merged**
