### PR TITLE
Issue #1290: coverage has been increased to 100% in TranslationCheck

### PR DESCRIPTION
**Pull request by sabaka**
Without impotent changes in code.
But I have no idea how to check messages. Check puts them to DefaultLogger and then to some PrintWriter...

### CODE REVIEW

**Comment by romani** [comment]
What for you check for null ? It is already done by library

https://code.google.com/p/guava-libraries/source/browse/guava/src/com/google/common/io/Closeables.java?r=d5de86dc98b759183762543e3e977743e781d923#97

https://code.google.com/p/guava-libraries/source/browse/guava/src/com/google/common/io/Closeables.java?r=d5de86dc98b759183762543e3e977743e781d923#76

**Comment by sabaka** [comment]
@romani hm, was it always here? I believe I had NPE last time when I worked with this check. Anyway now it works without it and check has been deleted.

**Comment by romani** [comment]
As you use reflection please prove in a comment that it is not possuble to test by usual way to let Check run on nonexisting file.

**Comment by sabaka** [comment]
What kind of proof do you want?

**Comment by romani** [comment]
Just some word why you can run it usual way and instead of path put "".

**Comment by sabaka** [comment]
I can't put wrong file here. Checkstyle fails before check started. I saw some usage of file or handling of this in Checker, or somewhere in checks running part. So I had to do it with reflection to improve coverage.

**Comment by romani** [comment]
Please put that explanation to the code as comment, as there is no reference from commit to PR.

**Comment by sabaka** [comment]
Done

**Comment by romani** [comment]
merged as FF

try to avoid in comments personal sentences "I .... , We ....", use "It is ...."

**Pull request closed without merging**
