### PR TITLE
Issue #5573: SuppressWithNearbyCommentFilter NPE

### LINKED ISSUE #5573: SuppressWithNearbyCommentFilter NPE
````
$ cat TestClass.java
public class TestClass {
    void method() {
        // -@csl[FinalLocalVariable](5) my comment
        String s = "";
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="FinalLocalVariable" />

<module name="SuppressWithNearbyCommentFilter">
<property name="commentFormat" value="-@csl\[(\w{8,}((\||\(|\))\w+)*)\]\((\d+)\) .{10,}" />
<property name="checkFormat" value="$1" />
<property name="influenceFormat" value="$3" />
</module>
    </module>
</module>

$ java -jar checkstyle-8.8-all.jar -c TestConfig.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:299)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:217)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:523)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:438)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:211)
Caused by: java.lang.NullPointerException
    at java.util.regex.Matcher.appendReplacement(Matcher.java:804)
    at java.util.regex.Matcher.replaceAll(Matcher.java:955)
    at java.lang.String.replaceAll(String.java:2223)
    at com.puppycrawl.tools.checkstyle.utils.CommonUtils.fillTemplateWithStringsByRegexp(CommonUtils.java:539)
    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter$Tag.<init>(SuppressWithNearbyCommentFilter.java:328)
    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.addTag(SuppressWithNearbyCommentFilter.java:279)
    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagCommentLine(SuppressWithNearbyCommentFilter.java:269)
    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagSuppressions(SuppressWithNearbyCommentFilter.java:253)
    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagSuppressions(SuppressWithNearbyCommentFilter.java:235)
    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.accept(SuppressWithNearbyCommentFilter.java:202)
    at com.puppycrawl.tools.checkstyle.TreeWalker.getFilteredMessages(TreeWalker.java:215)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:194)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:83)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:320)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:290)
    ... 4 more
Checkstyle ends with 1 errors.
````

I am expecting now exception.
I am trying to write a comment like `// -@cs[MoveVariableInside(If|Else)](6)` to be able to suppress multiple checks at a single location.
If the characters `(` or `)` can never be allowed, then we should display that as an error message instead of an NPE.

### PR DESCRIPTION
**Pull request by DXTkastb**
fixes #5573

### CODE REVIEW

**Comment by rnveach** [comment]
@DXTkastb 
https://travis-ci.org/github/checkstyle/checkstyle/jobs/673834029#L905
````
Caused by: java.lang.IllegalArgumentException: 

    at com.puppycrawl.tools.checkstyle.utils.CommonUtil.fillTemplateWithStringsByRegexp (CommonUtil.java:549)

    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter$Tag.<init> (SuppressWithNearbyCommentFilter.java:510)

    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.addTag (SuppressWithNearbyCommentFilter.java:468)

    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagCommentLine (SuppressWithNearbyCommentFilter.java:458)

    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagSuppressions (SuppressWithNearbyCommentFilter.java:442)

    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagSuppressions (SuppressWithNearbyCommentFilter.java:424)

    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.accept (SuppressWithNearbyCommentFilter.java:391)
````

**Comment by DXTkastb** [comment]
New output for the issue:
```
kaustubh@dxtk:~$ cat Test.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="FinalLocalVariable" />

<module name="SuppressWithNearbyCommentFilter">
<property name="commentFormat" value="-@csl\[(\w{8,}((\||\(|\))\w+)*)\]\((\d+)\) .{10,}" />
<property name="checkFormat" value="$1" />
<property name="influenceFormat" value="$3" />
</module>
    </module>
</module>
kaustubh@dxtk:~$ cat Test.java
public class TestClass {
    void method() {
        // -@csl[FinalLocalVariable](5) my comment
        String s = "";
    }
}

kaustubh@dxtk:~$ java -jar checkstyle-8.3.jar -c Test.xml Test.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Test.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:304)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:400)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:324)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:187)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:124)
Caused by: java.lang.IllegalArgumentException: unable to compute null regex group: $3
	at com.puppycrawl.tools.checkstyle.utils.CommonUtil.fillTemplateWithStringsByRegexp(CommonUtil.java:551)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter$Tag.<init>(SuppressWithNearbyCommentFilter.java:526)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.addTag(SuppressWithNearbyCommentFilter.java:466)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagCommentLine(SuppressWithNearbyCommentFilter.java:456)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagSuppressions(SuppressWithNearbyCommentFilter.java:440)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagSuppressions(SuppressWithNearbyCommentFilter.java:422)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.accept(SuppressWithNearbyCommentFilter.java:389)
	at com.puppycrawl.tools.checkstyle.TreeWalker.getFilteredMessages(TreeWalker.java:181)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:160)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)
	... 5 more
Checkstyle ends with 1 errors.

```

Code analysis:

We needed to update code in CommonUtil.java to throw this new error:

Code added:

            if (template.matches("(^(\\$\\d+))$")
                    && Integer.parseInt(template.substring(1)) <= matcher.groupCount()
                    && matcher.group(Integer.parseInt(template.substring(1))) == null) {
                throw new IllegalArgumentException("unable to compute null regex group: "
                        + template);
            }
            else {
                result = result.replaceAll("\\$" + i, matcher.group(i));
            }

This If-condition checks whether the passed value is of the form: example '$7' and then computes '7' is less than groupCount() of regular-exp(because we are not throwing out of bound exception) and the last condition checks regular group corresponding to 7 is null or not.

**Comment by DXTkastb** [comment]
I'll resolve the checks and push the changes shortly.

**Comment by DXTkastb** [comment]
@rnveach, please review.

**Comment by DXTkastb** [comment]
Also, I wanted to know what configuration should be used for diff reports.

**Comment by romani** [comment]
dashboardUrl=https://sonarcloud.io/dashboard?id=org.checkstyle%3Acheckstyle&pullRequest=8072

**Comment by romani** [comment]
fix is invalid, see new comments in issue

**Pull request closed without merging**
