### PR TITLE
Issue #9866: update PackageNameCheckTest.java to use unique input fil…

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
fixes Issues: #9866

### CODE REVIEW

**Comment by romani** [comment]
@shashwatj07 , please guide new contributor on how to make this update. You are the most experienced in this area.

**Comment by shashwatj07** [comment]
@Rahulkhinchi03 Hello, Rahul! Welcome to the community!
Do you need help with this PR? Please respond so we can discuss further.

**Comment by romani** [comment]
@Rahulkhinchi03 , please finish PR.

**Comment by shashwatj07** [comment]
@romani fix is merged https://github.com/checkstyle/checkstyle/pull/10316, we can close this PR and corresponding issue

@Rahulkhinchi03 I'm sorry for taking it from you but this was a blocker. You're always welcome to contribute. Please let me know when you're back and I'll help you pick a nice issue.

**Pull request closed without merging**
