### PR TITLE
dependency: bump pitest-maven from 1.7.3 to 1.7.4

### PR DESCRIPTION
**Pull request by rnveach**
Bumps [pitest-maven](https://github.com/hcoles/pitest) from 1.7.3 to
1.7.4.
- [Release notes](https://github.com/hcoles/pitest/releases)
- [Commits](https://github.com/hcoles/pitest/compare/1.7.3...1.7.4)

---
updated-dependencies:
- dependency-name: org.pitest:pitest-maven
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

### CODE REVIEW

**Comment by rnveach** [comment]
@romani This fixes the issue as recommended by pitest.
https://github.com/hcoles/pitest/issues/750#issuecomment-1030776825

**Comment by rnveach** [comment]
Not sure what is up with drone.

**Review by romani — APPROVED** [review]
Good.

**Comment by romani** [comment]
Strange it is green https://cloud.drone.io/checkstyle/checkstyle/8668

**Pull request merged**
