### PR TITLE
Issue #12717: Remove admins from white list on commit validation

### PR DESCRIPTION
**Pull request by stoyanK7**
Part of #12717

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
@stoyanK7 , please fix
Idea inspection 
```
<problem_class id="ArraysAsListWithZeroOrOneArgument" severity="ERROR" attribute_key="ERRORS_ATTRIBUTES">Call to 'Arrays.asList()' with too few arguments</problem_class>
<description>Call to <code>asList()</code> with only one argument #loc</description>
```

**Comment by stoyanK7** [comment]
Alright.

**Comment by rnveach** [comment]
I would like to wait on merging this for a bit to get status of https://github.com/checkstyle/checkstyle/issues/12717#issuecomment-1416809230

**Comment by romani** [comment]
it is better to merge this PR sooner to let system fail my/your PR on any typo.

**Review by rnveach — APPROVED** [review]

**Pull request merged**
