### PR TITLE
Issue #7760: regex singleline java

### PR DESCRIPTION
**Pull request by ImmortalRabbit**
Fixes Issue: #7760 

It's basically, same as this Pull Request #8012. Just wanted to point out my contribution to this issue and maybe writing into separate lines will look better.

I will close this PR, if it's not necessary.

### CODE REVIEW

**Comment by ImmortalRabbit** [comment]
I know that this commit message causing an error: 
Revert "Issue #7760: minor fix"

What should I do next?
Fix an issue to be able to merge? Or Pull Request #8012 is enough for both issues?

@romani

**Comment by rnveach** [comment]
@ImmortalRabbit See https://github.com/checkstyle/checkstyle/wiki/PR-rules .

Please squash all your commits to 1 and ensure `mvn verify` passes before pushing to the server.

**Comment by ImmortalRabbit** [comment]
> @ImmortalRabbit See https://github.com/checkstyle/checkstyle/wiki/PR-rules .
> 
> Please squash all your commits to 1 and ensure `mvn verify` passes before pushing to the server.

Could you review my pull request?

What I can do with this error? 
```
Transfer failed for http://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-api/5.6.2/junit-jupiter-api-5.6.2.jar 501 HTTPS Required
```
I have just run `mvn clean verify` and it was `BUILD SUCCESS`

**Comment by timurt** [comment]
@ImmortalRabbit please rebase on latest master

**Pull request closed without merging**
