### PR TITLE
Fix PMD violations from 'logging-jakarta' ruleset, issue #871

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
Please separate these commits to separate PR, please ad a tests for simple empty class that caused NPE at TreeWalker.

**Comment by mkordas** [comment]
Are you sure? These commits are not independent. My changes in first commit decreased coverage, so I've added second commit that increases it. I can create two PR, but there will be merge conflicts.

**Comment by romani** [comment]
ok, I just thought that did a mistake in combining two commits in one PR, and I have concerns for first commit and thought that code coverage could be merged easily before. Here is my concerns : 

1) 
> private static final Log LOG = LogFactory.getLog(Checker.class);

please read - http://wiki.apache.org/commons/Logging/StaticLog
I like static loggers :) in my applications, but here we are in library, I do not believe it is good idea to be static in Checkstyle.

2) 
>  LOG.debug(message, e);
 throw new RuntimeException(message);

please do not do LOG and THROW, and never swallow of original exception. There are number of places to read about that , one of it is
http://roman-ivanov.blogspot.com/2013/08/exception-logging-log-and-rethrow-vs.html

**Comment by mkordas** [comment]
1) In the document there is recommendation only about *library that may be deployed within a container of some sort (such as a J2EE server)*. I don't believe anyone uses Checkstyle within such container.
2) I absolutely agree, but is it really in scope of this PR? This is about problems detected by PMD. We can create another issue and PR to deal with LOG and THROW. Possibly there are more places in code like that that must be fixed.

**Comment by romani** [comment]
> I don't believe anyone uses Checkstyle within such container.

we are library, we need to allow other to use us at any place. Please remove static.

>  I absolutely agree, but is it really in scope of this PR?

yes, please open another issue, with ref to that lines and request to do further search for such dab practice.

> couldn't we use Sevntu checks to do code review of Checkstyle?

no, some of checks are not ready yet, on acceptance to sevntu  project we have to check code over checkstyle with idea that we will have to fix all that violations (recommendation, not a demand). For nearest future I only dream about all checkstyle's  Checks execution over its code. That also will be a long fight, as most of Checks are not ready to be used in real code (they are too academic).

**Comment by mkordas** [comment]
> Please remove static.

In this PR we are attempting to fix PMD violations. By removing `static` I introduce new ones, e.g.
* `PMD Failure: com.puppycrawl.tools.checkstyle.Checker:61 Rule:ProperLogger Priority:3 Logger should be defined private static final and have the correct class.`

I believe we need common approach for all loggers and this should be separate issue. Marking just 4 loggers as `private final` and suppressing these cases with PMD while leaving the rest as `private static final` won't change much. Another question is if we need logging in all the classes where it is present now.

> yes, please open another issue

Please see #927

**Comment by romani** [comment]
> I believe we need common approach for all loggers and this should be separate issue.

ok, now I see that problem is already several classes and you do not introduce bad practice , and just follow existing approach. Please create an issue on that.

> Another question is if we need logging in all the classes where it is present now.

Logging is bad and useless in checkstyle, need to be improved to let us diagnose problem on client side.
I even do not like apache logging, I would rather switch to slf4j one we have time ( dream :) ).

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
