### PR TITLE
Issue #9176: Fix for no-error-pgjdbc is failing with "reference not a tree"

### LINKED ISSUE #9176: no-error-pgjdbc is failing on master build
From wercker logs at https://github.com/checkstyle/checkstyle/pull/9165#pullrequestreview-565968475: 

```
export WERCKER_STEP_ROOT="/pipeline/script-478eddfa-c09f-4e37-abfa-4a5495adf8ad"
export WERCKER_STEP_ID="script-478eddfa-c09f-4e37-abfa-4a5495adf8ad"
export WERCKER_STEP_OWNER="wercker"
export WERCKER_STEP_NAME="script"
export WERCKER_REPORT_NUMBERS_FILE="/report/script-478eddfa-c09f-4e37-abfa-4a5495adf8ad/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/script-478eddfa-c09f-4e37-abfa-4a5495adf8ad/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/script-478eddfa-c09f-4e37-abfa-4a5495adf8ad/artifacts"
source "/pipeline/script-478eddfa-c09f-4e37-abfa-4a5495adf8ad/run.sh" < /dev/null
Command: ./.ci/wercker.sh no-error-pgjdbc
CS_version: 8.40-SNAPSHOT
Cloning into 'pgjdbc'...
fatal: reference is not a tree: f41cc39001febd824242afa5cb474fa0a52c1081

```
Full log found here:  https://app.wercker.com/checkstyle/checkstyle/runs/build/5ffd31ad237ec90008309fe4?step=5ffd334a64bf9700082de76b

This appears to be related to changes at https://github.com/checkstyle/checkstyle/commit/8381cd6a965583e6431ea4b4dd4d60979fc47138

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Fixes #9176

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge as CI pass

**Comment by romani** [comment]
@Abhishek-kumar09 , please create PR to pgjdbc repo to be merged after our release if there is some incompatibility in behavior

**Comment by Abhishek-kumar09** [comment]
> please create PR to pgjdbc repo to be merged after our release if there is some incompatibility in behavior

Ok, will check and create the PR.

**Comment by Abhishek-kumar09** [comment]
Issue not approved faiure, otherwise good. I had checked the no-error-pgjdbc locally it was success.

**Comment by Abhishek-kumar09** [comment]
@romani ping

**Pull request merged**
