### PR TITLE
Issue #4538: Removed the remaining files from 'indentation' directory

### PR DESCRIPTION
**Pull request by subkrish**
Issue #4538 

This PR removes any extra files left in the 'indentation' directory.

### CODE REVIEW

**Comment by romani** [comment]
@subkrish , do we have a copy of this file somewhere ? It will be sad to loose such a big test case

**Comment by subkrish** [comment]
@romani I don't think so. What should I then with this file?

**Comment by romani** [comment]
If there is now copy of it that already in use, let's use this input.

**Comment by subkrish** [comment]
What can we set so that this file can be used? We would need a UT that is different from the existing ones.

**Comment by romani** [comment]
Just create UT method IndentationTest and run validation over it as we do with other input files.

**Comment by subkrish** [comment]
@romani @rnveach Sorry, Looks like I found the file. `InputIndentationLambda1.java` is the same as `InputFinalInDefaultMethods.java`. I think the file can be removed from the folder.

**Comment by romani** [comment]
confirmed - https://www.diffchecker.com/TQVZEQig , they are identical from Indentation perspective.

**Pull request merged**
