### PR TITLE
Pull #5363: added missing annotation token definition

### PR DESCRIPTION
**Pull request by rnveach**
Identified at https://github.com/checkstyle/checkstyle/issues/5307#issuecomment-352132626 .
We had specifics to annotation interfaces, but we never used or collected them.

I will post regression soon.

### CODE REVIEW

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/145/
No differences.

> `target/site/cobertura/com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.html:<tr>  <td class="numLineCover">&nbsp;880</td>  <td class="nbHitsUncovered"><a title="Line 880: Conditional coverage 50% (1/2).">&nbsp;1499</a></td>  <td class="src"><pre class="src"><span class="srcUncovered">&nbsp;<a title="Line 880: Conditional coverage 50% (1/2).">        <span class="keyword">if</span> (frame == <span class="keyword">null</span>) {</a></span></pre></td></tr>`

`frame` can't be `null` now, so I'll remove this and redo regression.

**Comment by rnveach** [comment]
http://rveach.no-ip.org/checkstyle/regression/reports/146/
New regression removing uncovered code. No differences.

**Comment by romani** [comment]
Please confirm that there is no extra uncovered or survived code in Check , https://github.com/checkstyle/checkstyle/blob/master/shippable.yml#L82 , this check is in exclude list.

**Comment by rnveach** [comment]
@romani http://rveach.no-ip.org/checkstyle/regression/pitest-reports/14/com.puppycrawl.tools.checkstyle.checks.coding/RequireThisCheck.java.html
There are no new uncovered mutations for this PR.

You can compare it to an old report at http://rveach.no-ip.org/checkstyle/regression/pitest-reports/5/com.puppycrawl.tools.checkstyle.checks.coding/RequireThisCheck.java.html (from https://github.com/checkstyle/checkstyle/issues/5008#issuecomment-349407166 ).

**Pull request merged**
