### PR TITLE
Improve French translation for annotations warnings

### PR DESCRIPTION
**Pull request by don-vip**
Pull #3278: improve French translation for annotations warnings

### CODE REVIEW

**Comment by romani** [comment]
Yes, non of mainteners know french, but we had a lot f missed translations that needed to be filled. Google translate was a solution.

Thanks for update, please change commit message to reference PR number like "Pull #3278: ..." and push to your branch with force option. We have strict rules for commit messages as they are used in release notes generation

**Comment by don-vip** [comment]
Done :)

**Comment by romani** [comment]
CI is red , as commit message is not follow required format, please change commit message to be single line and start with "Pull #3278: "

**Comment by don-vip** [comment]
Ok sorry, this time it should be OK.

**Comment by romani** [comment]
Travis build "NoExceptionTest - Checkstyle, sevntu-checkstyle" is expected for now.
Appveyor build is relaunched.

**Comment by romani** [comment]
merged , thanks a lot !
You are welcome with other fixes.

**Comment by don-vip** [comment]
thank you :)

**Pull request merged**
