### PR TITLE
Resize and move RSS icon used on main page, issue #886

### PR DESCRIPTION
**Pull request by mkordas**
### Before:
image
### After:
image

### CODE REVIEW

**Comment by romani** [comment]
Intention was to keep all banner of the same size, can you change a picture to follow that intention if that not hard to do

**Comment by mkordas** [comment]
It has 120 px width as others, except Twitter one.

**Comment by romani** [comment]
Width is the same but height is different

**Comment by mkordas** [comment]
OK, I've resized it to have the same height as Github banner (53 px).

**Comment by mkordas** [comment]
If you want I may make also Sourceforge banner to have 53 px height. Right now it has only 30 px.

**Comment by romani** [comment]
It would be good to have them almost the same size, i am ok to lower height to occupy less vertical space and be viwed after first scroll.

**Comment by mkordas** [comment]
Do you mean to make Github banner to have only 30 px height? Then we would need to change it entirely, probably without _social coding_ subtitle.

**Comment by romani** [comment]
When I started to introduce that banners , I have an idea to keep GITHUB banner the biggest and the top to redirect users to it (instead of sourseforge). If you do not like that we could change that, in other case keep it as is to be more attractive(easy to click) to users.

**Comment by mkordas** [comment]
OK, so is there anything that could be improved in this pull request? RSS icon is already shrunk to 120x36.

**Comment by romani** [comment]
this is your PRs, if you can not propose new image that looks better - please close it.

**Pull request closed without merging**
