### PR TITLE
Issue #9372: Add example of AST for TokenTypes.ANNOTATION_MEMBER_VALU…

### PR DESCRIPTION
**Pull request by hungleba**
Closes: #9372 
Adding an example and tree for ANNOTATION_MEMBER_VALUE_PAIR: "@MyAnnotation(someField1 = "Hello")

### CODE REVIEW

**Comment by strkkk** [comment]
@hungleba pls fix ci failures

**Comment by hungleba** [comment]
@strkkk There were no errors on "mvn clean verify". I'm trying to fix it, but do you know what might cause the CI failures?

**Comment by anshuman10398** [comment]
@hungleba you just need to link the issue in PR description

**Comment by hungleba** [comment]
@anshuman10398 maybe that is the issue. Let me try to trigger it again, thank you.

**Comment by nmancus1** [comment]
@hungleba  thanks for your contribution. We have just updated the wiki for [Good practice on how to update AST in TokenTypes](https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes) with a better example. Please have a look and update this PR.

**Comment by hungleba** [comment]
@nmancus1 I've updated the PR, and the screenshot of index.html
Capture

**Comment by romani** [comment]
Please reread https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes I updated it recently.

**Comment by romani** [comment]
there should be single commit in your PR, please make sure that CI is passing
https://checkstyle.org/beginning_development.html#Starting_Development
make sure https://checkstyle.org/contributing.html#Build passing on your local

**Comment by romani** [comment]
if no activity in next 7 days,  PR will be closed

**Pull request closed without merging**
