### PR TITLE
Fix FallThroughCheck fails on if with no else, issue #1395.

### PR DESCRIPTION
**Pull request by MEZk**
@romani 
[Reports issue#1395](http://mezk.github.io)

| Source | 6.8.1-RELEASE | 6.9-SNAPSHOT | Сomparison
|:-----------|------------:|:------------:|-----------:|
| hibernate       |        [8](http://mezk.github.io/hibernate_6.8.1_issue1395/checkstyle.html) |     [8](http://mezk.github.io/hibernate_6.9-SNAPSHOT_issue1395/checkstyle.html)     | equal
| spring     |      0 |    0    | equal
| checkstyle       |        [67](http://mezk.github.io/checkstyle_6.8.1_issue1395/checkstyle.html)|     [68](http://mezk.github.io/checkstyle_6.9-SNAPSHOT_issue1395/checkstyle.html)  | +1 violation [(line 160) ](http://mezk.github.io/checkstyle_6.9-SNAPSHOT_issue1395/xref/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.html#L160)   
| sevntu-checkstyle         |          [3](http://mezk.github.io/sevntu-checkstyle_6.8.1_issue1395/checkstyle.html) |      [3](http://mezk.github.io/sevntu-checkstyle_issue1395/checkstyle.html) | equal

[cobertura coverage report after fix](http://mezk.github.io/cobertura_issue1395/com.puppycrawl.tools.checkstyle.checks.coding.FallThroughCheck.html)

Additional [test inputs](https://github.com/checkstyle/checkstyle/commit/29a3d60dfa6a7ab1c6383b68af343f9ce2757d72#diff-a66b9e060d0527888fa4f1cce592b67cR12).
I'll provide more reports if needed.

And due to FinalLocalVariableCheck line 160, Travis fails the build, because the following code rises violation:

````java
case TokenTypes.PARAMETER_DEF:
    if (ScopeUtils.inInterfaceBlock(ast)
         || inAbstractOrNativeMethod(ast)
         || inLambda(ast)) {
         break;
         } // The break statement is absent
 case TokenTypes.VARIABLE_DEF: //line 160
    if (ast.getParent().getType() != TokenTypes.OBJBLOCK
````
```
[checkstyle] /home/travis/build/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java:160:13: Fall through from previous branch of the switch statement.
```  

Do you think that we should suppress the violation?
````java
case TokenTypes.PARAMETER_DEF:
    if (ScopeUtils.inInterfaceBlock(ast)
         || inAbstractOrNativeMethod(ast)
         || inLambda(ast)) {
         break;
         }
         // fallthrough
 case TokenTypes.VARIABLE_DEF: //line 160
    if (ast.getParent().getType() != TokenTypes.OBJBLOCK
````

### CODE REVIEW

**Comment by romani** [comment]
> Do you think that we should suppress the violation?

Suppression is too easy fix :) , that code smells.
We need to refactor that Check to avoid such situation of "fall-through" , please investigate logic of a Check and propose solutions (there is definitely sign of dead logic).

**Comment by MEZk** [comment]
@romani 
Maybe it will be a good idea to seperate the problem of FinalLocalVariableCheck (new issue, because anyway it needs refactoring) and FallThroughCheck? For now we can supress violation to avoid Travis CI not to fail the build. And after I can look at FinalLocalVariableCheck. I think we should wait a bit when @rnveach look at test inputs, new ideas might appear.

**Comment by romani** [comment]
your idea of separation of problems is good and right intention , but :) 

https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2015-Project-Ideas#project-name-practice-what-you-preach

Ability to update checkstyle's code is perfect prove such update make sense and user will benefit from it and it will not change their code to ugly. I will not allow do make our code ugly , as we are first target of your update.  

So please do that by separate commit in the same PR.

**Comment by romani** [comment]
appveyor is passing for master, please recommit smth in branch to re-trigger CIs builds. From this moment I expect all CIs to be green.

**Comment by MEZk** [comment]
@romani 
rebased. 
Fixed problem with FinalLocalVariableCheck.

Project which were tested with FinalLocalVariableCheck: checkstyle, sevntu-checkstyle, openjdk, guava.
Check configuration:
````xml
<module name="FinalLocalVariableCheck">
    <property name="tokens" value="VARIABLE_DEF, PARAMETER_DEF" />
</module>
````

Before changes:
before

After changes:
after

Diff results. No output - files are equal.
diff

**Comment by romani** [comment]
1)
>             case TokenTypes.PARAMETER_DEF:
            case TokenTypes.VARIABLE_DEF:

One "case" - one "brake". 

2)
> && isVariableInForInit(ast)

Why we will calculate that for PARAMETER_DEF ?  please minimize amount of conditions for "case TokenTypes.PARAMETER_DEF"  and "case TokenTypes.VARIABLE_DEF"

3)
> private static boolean isAlwaysTrueIf(DetailAST ifToken) {

please remove that, Checkstyle will never be that smart to catch all stupidities of user. That is even good that we point such cases.

**Comment by romani** [comment]
better :)

> 
                if (!(ScopeUtils.inInterfaceBlock(ast) || inLambda(ast)
                        || inAbstractOrNativeMethod(ast))
                            && !ast.branchContains(TokenTypes.FINAL)) {

please adjust indentation of "&&" to clearly see level of execution. You write program for human, not for computer, so make code easy read and understand.

**Comment by romani** [comment]
> !(ScopeUtils.inInterfaceBlock(ast) || inLambda(ast)
                        || inAbstractOrNativeMethod(ast))

please refactor "!(.....)" , it is very hard to read inversion on complicated expression , please read javadoc https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/AvoidConditionInversionCheck.java

**Comment by MEZk** [comment]
@romani 
1) Done.
2) Done. ````shouldCheckEnhancedForLoopVariable````, ````ast.getParent().getType() != TokenTypes.OBJBLOCK````, and ````isVariableInForInit are unnecessary```` for PARAMETER_DEF.
3) Done.

>please refactor "!(.....)" , it is very hard to read inversion on complicated expression , please read javadoc https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/AvoidConditionInversionCheck.java

I used De Morgan's laws :+1: 
! (a V b V c) = !a & !b & !c

**Comment by romani** [comment]
>                 if (!inLambda(ast)
                        && !ScopeUtils.inInterfaceBlock(ast)
                        && !inAbstractOrNativeMethod(ast)
                        && !ast.branchContains(TokenTypes.FINAL)) {

as all part of expression become equal , please order them by complexity of execution/processing (the easiest to the first) and explain me a reason of that :). The same for "case TokenTypes.VARIABLE_DEF:".

**Comment by MEZk** [comment]
@romani 
Since we use ```&&``` operator, it means that, if the first condition in the whole conditional statement is false, we do not need to check other parts of the whole condition and use computing resources, because the whole condition statement will be false. That is why we can reduce the amount of operations which will be performed by reordering the parts of conditional statement (the easiest, the less complex to the first).

I've ordered all part of expression in accordance with their complexity. I calculated complexity of each method which is a part of the whole expression with IDEA [MetricsReload plugin](http://blog.jetbrains.com/idea/2014/09/touring-plugins-issue-1/).

1) case TokenTypes.PARAMETER_DEF
 ```ScopeUtils.inInterfaceBlock(ast)``` has the biggest cyclomatic complexity (V(g) = 5), then ```inAbstractOrNativeMethod(ast)``` (V(g) = 3, V'(g) = 4), then ```ast.branchContains``` which invokes```getBranchTokenTypes``` inside, and it has cyclomatic complexity V(g) = 3 and V'(g) = 3,  and the last ```inLambda(ast)``` has V(g) = 1.

2) case TokenTypes.VARIABLE_DEF
```ast.branchContains``` which invokes```getBranchTokenTypes``` inside and it has cyclomatic complexity V(g) = 3, then ```shouldCheckEnhancedForLoopVariable``` has V(g) = 1 but V'(g) = 2, and then ```isVariableInForInit``` with V(g) = 1 and V'(g) = 1.

scopeutils
finalvariablecheck
branchcontains

eV(g) - essential cyclomatic complexity;
iV(g) - design complexity;
V'(g) - extended cyclomatic complexity;
V(g) - cyclomatic complexity.

Since after last changes (did not add new lines/logic etc, only reorganising condition parts) cobertura reports that line coverage decreased from 100% to 98%, I've also refactored ```inAbstractOrNativeMethod``` and made one exit point in the method, so that line coverage increased to 100%.

**Comment by romani** [comment]
merged as FF.

**Pull request closed without merging**
