### PR TITLE
Issue #2239: Extend RequireThis check message

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by romani** [comment]
1)
> if (frame instanceof ClassFrame

instanceof is ok to use only there is no any other way to do this. Please make getType() method and return type of frame.

2)
> ``` +            if (frame.getFrameName().equals(getNearestClassFrameName())) {
+                log(ast, MSG_VARIABLE, ast.getText(), "");
+            }
+            else {
+                log(ast, MSG_VARIABLE, ast.getText(), frame.getFrameName() + POINT);
+            }
```

move this to function and reuse, please try to move usage of this function to "switch" as it was. when logging is present in SWITCH is transparent for developer where is reporting points.

3)
>```
 -require.this.variable=Reference to instance variable ''{0}'' needs \"this.\".
+require.this.variable=Reference to instance variable ''{0}'' needs "{1}this.".
```

is it not clear why you removed escaping of quotation marks.

4)
All messages file need to be updated.

5)
Update is serious, Diff report is required on a lot of projects.

**Comment by romani** [comment]
1)
> public static final String POINT = ".";

please remove this constant, you use it only ones.

2)
> instanceof is ok to use only there is no any other way to do this. Please make getType() method and return type of frame.

`instanceOf` should not be used. `frame.getType()` need to return DetailAST (CLASS_DEF, METHOD_DEF, SLIST) instead of class name. Keep casting to certain type of class, findbug violations need to be suppressed (on the whole file is ok) with message "Structure of frames rely on AST stucture, that rely on correct/compilable java files. It is ok there to have direct casts to subtypes. Any problem in runtime do mean serious problems in algorithm or AST generation."

3)
> ```* <p>Limitations: I'm not currently doing anything about static variables```

please remove personal statement like "I'm .....", make statement general.

4)
> ```* <p>Much of the code for this check was cribbed from Rick Giles's
 * {@code HiddenFieldCheck}.</p>```

please remove this.

**Comment by Vladlis** [comment]
> instanceof is ok to use only there is no any other way to do this. Please make getType() method and return type of frame.

fixed
> move this to function and reuse, please try to move usage of this function to "switch" as it was. when logging is present in SWITCH is transparent for developer where is reporting points.

done
> is it not clear why you removed escaping of quotation marks.

I thought it is redundant, but as I see now escaping is used almost in all properties, so I put it back.

> All messages file need to be updated.

done
> please remove this constant, you use it only ones.

done
> frame.getType() need to return DetailAST (CLASS_DEF, METHOD_DEF, SLIST) instead of class name.

it returns enum values now
> please remove personal statement like "I'm .....", make statement general.

done
> please remove this.

done
> Update is serious, Diff report is required on a lot of projects.

As the check triggers a great amount of violations it was problematic for me to run it on a lot of projects due to the lack of memory. However, I've tested it on CS, SevNTU-CS, HBase, Orekit and Guava and reports are identical.
```
vlad@vlad-N61PC-M2S ~/Документы $ diff before.xml after.xml
2c2
< <checkstyle version="6.13">
---
> <checkstyle version="6.14-SNAPSHOT">
```

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
