### PR TITLE
Issue #7075: recreate appveyor.bat

### PR DESCRIPTION
**Pull request by romani**
Issue #7075

Few commits to make it clear, after any rebase operation (on my local), git fall in same problem, so lets keep two commits.

EDIT: ~~related PR to avoid such issue in future - https://github.com/checkstyle/checkstyle/pull/7076~~ - merged to this PR

tested by https://github.com/checkstyle/contribution/pull/410 , https://travis-ci.org/checkstyle/contribution/builds/587018870

### CODE REVIEW

**Comment by rnveach** [comment]
Mostly questions back:
1) Why 2 commits instead of 1? Can't you merge the 2 commits into 1 now that you have it fixed. Won't we lose history for the entire file (blame) because of this, or are we losing the history regardless?

2) Our CI never found a problem with the file. Obviously you ran the other CI with your fix to show it works ( https://github.com/checkstyle/contribution/pull/410 ).
Shouldn't we add something to our own CI to check this for next time? Something like https://github.com/checkstyle/contribution/issues/409#issuecomment-532351159

**Comment by rnveach** [comment]
appveyor isn't listed in CI here either.

**Comment by strkkk** [comment]
I agree, I commit is easier to check in this case.

**Comment by romani** [comment]
I can not redo 1st commit.
If I touch/amend it by any means, repo come to same problematic state:
```
~/java/github/romani/checkstyle [master ↓·2↑·2|✔] 
$ git rebase -i HEAD~2
error: Your local changes to the following files would be overwritten by merge:
	.ci/appveyor.bat
Please, commit your changes or stash them before you can merge.
Aborting
Could not apply 4c0772d71de0ecd6df210ffe3a3bcf260f13f22b... Issue #7075: remove  appveyor.bat to create it later
✘-1 ~/java/github/romani/checkstyle [:64e96f7|✚ 1]
```
the only way out of this state is make temporal commit and checkout back to master (even reset does not help).

**Comment by romani** [comment]
still not appveyor build.... let me change some java file.

**Comment by rnveach** [comment]
> I still think we should avoid cycle dependencies (between repos) in CI

I am talking about adding a regression test of the PR's repo, but an external repo. It wouldn't be a cycle.

Similar to:
https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh#L166
https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh#L174
But just change it to local checkstyle and have it use the local PR repo.

**Comment by romani** [comment]
Please approve PR, we will think more after master code is fixed

**Comment by romani** [comment]
You can send update to Travis as next PR

**Pull request merged**
