### PR TITLE
Issue #3671: Remove deprecated property maxLineLength from LeftCurlyCheck

### PR DESCRIPTION
**Pull request by Kietzmann**
#3671

### CODE REVIEW

**Comment by romani** [comment]
We need to send PR to pgjdbc to avoid usage of this field.

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.415 s
[INFO] Finished at: 2017-07-04T15:35:44+00:00
[INFO] Final Memory: 38M/964M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check
 (default-cli) on project postgresql: Failed during checkstyle configuration: cannot initialize module
 TreeWalker - Property 'maxLineLength' in module LeftCurly does not exist, please check the
 documentation -> [Help 1]

```

**Comment by rnveach** [comment]
@romani Please see example and discussion at https://github.com/checkstyle/checkstyle/issues/3855#issuecomment-282307879 for why don't we keep this property.

**Comment by Kietzmann** [comment]
@romani 
Could you please make some feedback on rnveach post? Thanks

**Comment by romani** [comment]
discussion is going on at https://github.com/checkstyle/checkstyle/issues/3855#issuecomment-313551376

**Comment by romani** [comment]
@Kietzmann , discussion is finished, please proceed with PR to pgjdbc project.

**Comment by romani** [comment]
@Kietzmann , did you do PRs to projects ?

**Comment by Kietzmann** [comment]
Nope

2017-07-27 8:30 GMT+03:00 Roman Ivanov <notifications@github.com>:

**Comment by rnveach** [comment]
@Kietzmann This PR can't continue until wercker is green and that requires updates in external projects.
Do you plan to make them?

**Comment by Kietzmann** [comment]
No, I don't

2017-07-27 14:24 GMT+03:00 rnveach <notifications@github.com>:

**Comment by romani** [comment]
ok , I am closing this PR for now, looks like it will not be continued in most recent future.

**Pull request closed without merging**
