### PR TITLE
Issue #3126: Fix CommentsIndentation false-positive in singleline comment after a block comment

### PR DESCRIPTION
**Pull request by Vladlis**
#3126 
Report: http://vladlis.github.io/reports/3126/index.html

### CODE REVIEW

**Comment by romani** [comment]
codecov failures looks like problem of service.

**Comment by romani** [comment]
report show too much false-negatives for me.

I expect changes only for cases with two sequential comments where violation on second correctly indented comment disappear.
First few cases are removing violation of wrongly indented multi-line comments - http://vladlis.github.io/reports/3126/index.html#A1

**Comment by Vladlis** [comment]
@romani 
I'd rather say these cases were false-positive, which are also fixed:
http://vladlis.github.io/reports/3126/index.html#A1 - comment has the same level, as the `if` statement before
http://vladlis.github.io/reports/3126/index.html#A2 - the same level as the previous comment
http://vladlis.github.io/reports/3126/index.html#A3 - the same level as a method definition
http://vladlis.github.io/reports/3126/index.html#A4 - the same level as a class definition
and so on

**Comment by romani** [comment]
ok, lets come to details:

```
          if (snapshotSkipFlush) {
          /*
           * This is to take an online-snapshot without force a coordinated flush to prevent pause
           * The snapshot type is defined inside the snapshot description. FlushSnapshotSubprocedure
           * should be renamed to distributedSnapshotSubprocedure, and the flush() behavior can be
           * turned on/off based on the flush type.
           * To minimized the code change, class name is not changed.
           */
            LOG.debug("take snapshot without flush memstore first");
          } else {
```

Why this case is valid ? why comment should be on the same level as IF ? 
This comment is inside a block so it has to follow indentation of all statements in block so it should be indented the same as "LOG.debug......".

**Comment by Vladlis** [comment]
@romani 
> Why this case is valid ?

You're right, it's not.
Please, see new report http://vladlis.github.io/reports/3126_1/index.html - a lot of violations is added and they seem correct to me.

**Comment by romani** [comment]
false-positives:

1)
http://vladlis.github.io/reports/3126_1/index.html#A6
Why expected indentation is "3" ? is it another issue ?

1.1)
looks similar to "1"
http://vladlis.github.io/reports/3126_1/index.html#A47
http://vladlis.github.io/reports/3126_1/index.html#A57
Why "50" is expected ?

2)
http://vladlis.github.io/reports/3126_1/index.html#A13
current indentation is correct as IF-ELSE block is finished( even it does not have a brace for ELSE), so comment should have the same indentation as IF.

**Comment by Vladlis** [comment]
1) Thanks, didn't notice! Yes, this is another problem, but it is not worth a separate issue. Fixed.
2) Looks like a part of https://github.com/checkstyle/checkstyle/issues/3125

**Comment by romani** [comment]
Please fix CI problems.


> 2) Looks like a part of #3125

Ok, but as now it become a falsepositive we need resolve #3125 as next issue, to make sure that there will be no regression between releases.

**Comment by Vladlis** [comment]
> Please fix CI problems.

Done.
> we need resolve #3125 as next issue

OK

**Comment by romani** [comment]
CI problem is due to master branch problem - #3168 . Not a this PR problem.

please provide diff report for latest code.

**Comment by Vladlis** [comment]
> please provide diff report for latest code.

https://vladlis.github.io/reports/3126_2/index.html

**Comment by romani** [comment]
1)
> https://vladlis.github.io/reports/3126_2/index.html#A9
```
-Block comment has incorrect indentation level 0, expected is 3, indentation should be the same level as line 239.
+Block comment has incorrect indentation level 0, expected is 4, 3, indentation should be the same level as line 234, 239.

234 				return x;	// (NOT (NOT_BETWEEN a b) ) => (BETWEEN a b)
235 /* This can never happen because this rule will always eliminate the child NOT.
236 			case NOT:
237 				return x.getFirstChild();			// (NOT (NOT x) ) => (x)
238 */
239 			default:
```

I do not understand why this is a valid violation. Why "4,3" ? 


2)
> https://vladlis.github.io/reports/3126_2/index.html#A81
Block comment has incorrect indentation level 12, expected is 16, indentation should be the same level as line 139.

```
138             try {
139                 registering = (RegisteringActivatable)
140                     Activatable.register(desc);
141 
142                 System.err.println("second activate and deactivate " +
143                                    "object via method call");
144             } catch (ActivationException e) {
145                 System.err.println("received exception from registration " +
146                                    "call that should have failed...");
147             }
148 
149             /*
150              * no longer needed because the security manager
151              * throws an exception during snapshot
152              */
153             /*
154             try {
155                 registering.shutdown();
156 
157                 System.err.println("received exception from remote " +
158                                    "call that should have failed...");
159             } catch (RemoteException e) {
160             }
161             */
```

false positive, comment position is correct.

**Comment by romani** [comment]
@Vladlis , ping .

**Comment by Vladlis** [comment]
@romani 
1) this file is indented with tabs
2) Fixed

Diff report against 6.18:
https://vladlis.github.io/reports/3126_3/index.html

all false-positives or false-negatives I've in the report are referenced from these issues: https://github.com/checkstyle/checkstyle/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+CommentsIndentation+

**Comment by romani** [comment]
@Vladlis , please update your https://github.com/checkstyle/contribution/tree/master/patch-diff-report-tool to the latest version.

**Comment by Vladlis** [comment]
2) Done
3) ok

**Comment by romani** [comment]
merged as FF.

It would be very good to fix #3220 and #3166 to avoid introduction of bad false-positives to users.

**Pull request closed without merging**
