### PR TITLE
Issue #13321: Kill mutation for ScopeUtil

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for ScopeUtil

------

# Mutation 
https://github.com/checkstyle/checkstyle/blob/bb64c20cbcf6e543b297b6e809f379bd8746b5e7/config/pitest-suppressions/pitest-utils-suppressions.xml#L345-L352

------

# Explaination
I have change the design. And this will not be cheat to pitest because. we have three if statment so each time all the condition will be checked. Instead of doing that I convert it into if-else if-else would be better.
I have changed the position of 
```
        else if (node.getType() == TokenTypes.RESOURCE) {
            localVariableDef = node.getChildCount() > 1;
        }

        // catch parameter?
        else if (node.getType() == TokenTypes.PARAMETER_DEF) {
            final DetailAST parent = node.getParent();
            localVariableDef = parent.getType() == TokenTypes.LITERAL_CATCH;
        }
```

the reason is 
```
        else if (node.getType() == TokenTypes.RESOURCE) {
            localVariableDef = node.getChildCount() > 1;
        }
```
condition inside it which is assigned to `localVariableDef`.

if we follow mutation then also it might not possible to find test using regression as well.

-------

# Regression 
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/811066dafa00871bdf97dc6ec3d58962/raw/863854d2d20d1a8a493a34c237e0452375d6f34a/su1.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/360a95ed7bb60d7a0956e531199d484c4d6f6617/test-projects.properties
Report label: Regression-2

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by nrmancuso** [comment]
>if we follow mutation then also it might not possible to find test using regression as well.

Why "might not be possible"? What is preventing us from hardcoding this mutation and generating tests?

**Comment by romani** [comment]
@Kevin222004 , please reply question above. If you already tried, share a link to PR where you tried.

**Review by romani — APPROVED** [review]
After reading code closely, it is clear that old code just did 3 matching of node.getType() to specific token type. So it is clear switch or sequential if-else.

I am ok to merge

**Comment by Kevin222004** [comment]
https://github.com/checkstyle/checkstyle/pull/13479#issuecomment-1656812049 
@nrmancuso I have started regression after hardcoding mutation at https://github.com/checkstyle/checkstyle/pull/13485.

The thing I was trying to mention here is that this mutation is happening because of its design and the way the how conditions are there.

**Comment by rdiachenko** [comment]
@Kevin222004 please resolve a conflict

**Comment by Kevin222004** [comment]
Conflict resolved

**Review by rdiachenko — APPROVED** [review]
lgtm

**Pull request merged**
