### PR TITLE
Issue #12716: Fix forgotten links

### PR DESCRIPTION
**Pull request by stoyanK7**
Part of #12716 

In https://github.com/checkstyle/checkstyle/pull/12727 we forgot to edit those 4 lines. I realised while working on https://github.com/checkstyle/checkstyle/pull/12739#discussion_r1106182620.

### CODE REVIEW

**Review by rnveach — APPROVED** [review]

**Comment by rnveach** [comment]
We should review the badges we have listed on main page. https://github.com/checkstyle/checkstyle

I am not seeing things like dependabot and others.

**Comment by rnveach** [comment]
From my browser console:
````
GEThttps://camo.githubusercontent.com/b1788a227a5361a9317135a1de2d14eb57e3091e64998af914f412f8706b1861/68747470733a2f2f6170692e646570656e6461626f742e636f6d2f6261646765732f7374617475733f686f73743d676974687562267265706f3d636865636b7374796c652f636865636b7374796c65
[HTTP/2 404 Not Found 71ms]

GEThttps://camo.githubusercontent.com/19ac978e4131209e3f011422639babe2e481c34e91f8502206224839d8fb9f70/68747470733a2f2f6170692e636f646163792e636f6d2f70726f6a6563742f62616467652f3361646631326434333433313462613862333832373765613436643363343462
[HTTP/2 404 Not Found 148ms]

GEThttps://camo.githubusercontent.com/a544d940b73b9dbbdd8ed95a0cf7d302ebaa86cdffcab77c8f11fabf7135d2c1/68747470733a2f2f627574746f6e2e666c617474722e636f6d2f666c617474722d62616467652d6c617267652e706e67
[HTTP/2 400 Bad Request 230ms]

GEThttps://github.com/checkstyle/checkstyle/actions/workflows/no_old_refs.yml/badge.svg
[HTTP/2 404 Not Found 100ms]

GEThttps://github.com/checkstyle/checkstyle/actions/workflows/run_link_check.yml/badge.svg
[HTTP/2 404 Not Found 82ms]

````

**Comment by stoyanK7** [comment]
I checked the img links and these are the faulty ones:

https://api.dependabot.com/badges/status?host=github&repo=checkstyle/checkstyle

https://api.codacy.com/project/badge/3adf12d434314ba8b38277ea46d3c44b

https://button.flattr.com/flattr-badge-large.png -> this one redirects to flattr.com

**Comment by rnveach** [comment]
Please create an issue or PR to fix them.

**Review by romani — APPROVED** [review]
Ok to merge

**Pull request merged**
