### PR TITLE
Coverage Improvement on FinalLocalVariableCheck

### PR DESCRIPTION
**Pull request by Bhavik3**

### CODE REVIEW

**Comment by romani** [comment]
thanks a lot, I appreciate your time and desire to help, but can you help us to restrict the best coverage quality by implementing #722 ?

After that is done nobody will reduce coverage that you thoroughly improved. That PR will be just an evidence that you really improved coverage and on what level.

**Comment by romani** [comment]
@Bhavik3 , please let me know if you do not have time to continue contribute to checkstyle, it is ok. I will apply that PR in that case.

**Comment by Bhavik3** [comment]
I will do it. 
I was out of town for some days. so could not done it.
now I will start work on it.
@romani

**Comment by romani** [comment]
@Bhavik3, 
as #757 is merged, I expect there changes in pom.xml to confirm how much coverage is improved

**Comment by Bhavik3** [comment]
DONE
@romani

**Comment by romani** [comment]
and now that is clear improvement, thanks a lot !

**Pull request merged**
