### PR TITLE
Issue #8552: Removed all "at-clause"

### LINKED ISSUE #8552: change all "at-clause" terms to "block tag" from source code and documentation
change all "at-clause" terms to "block tag" from source code and documentation ..  all places.

identified at https://github.com/checkstyle/checkstyle/issues/6192#issuecomment-663861910.

current cases:
```
✔ ~/java/github/romani/checkstyle/src [master L|✔] 
$ ag "at-clause"
main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java
242:     * @param atNode at-clause node.

main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java
36: * Checks that a Javadoc block can fit in a single line and doesn't contain at-clauses.
37: * Javadoc comment that contains at least one at-clause should be formatted in a few lines.
48: * Property {@code ignoredTags} - Specify at-clauses which are ignored by the check.
65: * To configure the check with a list of ignored at-clauses
66: * and make inline at-clauses not ignored:
107:     * Specify at-clauses which are ignored by the check.
115:     * Setter to specify at-clauses which are ignored by the check.

main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
33: * Checks the indentation of the continuation lines in at-clauses. That is whether the continued

main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
41: * Note: Google used the term "at-clauses" for block tags in their guide till 2017-02-28.
53: * Property {@code target} - Specify the list of targets to check at-clauses.
133:     * Specify the list of targets to check at-clauses.
150:     * Setter to specify the list of targets to check at-clauses.

main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
37: * and one blank line before the at-clauses block if it is present.</li>

main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java
29: * Checks that the at-clause tag is followed by description.
121:     * Tests if at-clause tag is empty.
123:     * @param tagNode at-clause tag.
124:     * @return true, if at-clause tag is empty.

main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties
1:at.clause.order=At-clauses have to appear in the order ''{0}''.
31:non.empty.atclause=At-clause should have a non-empty description.

xdocs/config_javadoc.xml
35:          Note: Google used the term "at-clauses" for block tags in their guide till 2017-02-28.
61:              <td>Specify the list of targets to check at-clauses.</td>
1159:            at-clauses block if it is present.
1688:          Checks the indentation of the continuation lines in at-clauses. That is whether the
2787:          Checks that the at-clause tag is followed by description.
2921:           contain at-clauses. Javadoc comment that contains at least one at-clause
2948:              <td>Specify at-clauses which are ignored by the check.</td>
2972:          To configure the check with a list of ignored at-clauses and make
2973:          inline at-clauses not ignored:

xdocs/google_style.xml
2032:                  <a href="styleguides/google-java-style-20180523/javaguide.html#s7.1.3-javadoc-at-clauses">

xdocs/checks.xml
428:            <td>Checks the indentation of the continuation lines in at-clauses.</td>
632:            Checks that the at-clause tag is followed by description.</td>
800:              at-clauses.</td>

site/resources/styleguides/google-java-style-20180523/javaguide.html
1115:<a name="s7.1.3-javadoc-at-clauses"></a>
```

**Attention** we should NOT update `site/resources/styleguides/google-java-style-20180523/javaguide.html` as it is not our file, it is copy from Google page.

### PR DESCRIPTION
**Pull request by sarthakhanda**
Issue #8552 : 

- [x] Removed all "at-clause" terms from source code and documentation as requested. 
- [x] NOT updated site/resources/styleguides/google-java-style-20180523/javaguide.html

### CODE REVIEW

**Comment by romani** [comment]
Please reference issue number in commit

Please run `mvn verify` on local

**Comment by romani** [comment]
Squash all commits in one, build Will not pass without it

**Comment by romani** [comment]
You do not need to close PR, just push your changes with "--force"

**Comment by romani** [comment]
See what you need to do in git

**Comment by sarthakhanda** [comment]
Yeah just running it on my local for any errors

**Pull request closed without merging**
