### PR TITLE
config: bump saxon to 9.9.1-5

### PR DESCRIPTION
**Pull request by romani**
https://travis-ci.org/checkstyle/checkstyle/jobs/583818724#L1148

### CODE REVIEW

**Comment by rnveach** [comment]
````
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for net.sf.saxon:Saxon-HE:9.9.1-4 paths to dependency are:
+-org.xwiki.commons:xwiki-commons-tool-verification-resources:11.8-SNAPSHOT
  +-com.puppycrawl.tools:checkstyle:8.25-SNAPSHOT
    +-net.sf.saxon:Saxon-HE:9.9.1-4 (managed) <-- net.sf.saxon:Saxon-HE:9.9.1-5
and
+-org.xwiki.commons:xwiki-commons-tool-verification-resources:11.8-SNAPSHOT
  +-com.puppycrawl.tools:checkstyle:8.25-SNAPSHOT
    +-net.sf.saxon:Saxon-HE:9.9.1-4
````

**Comment by romani** [comment]
> Puppet

I removed application configuration at https://pipelines.puppet.com/checkstyle/apps, there should be no such failure in future. Puppet is removed from list of CIs - #7017 .

**Comment by romani** [comment]
> wercker

looks like we need to override this version in xwik, I will take a look.

**Comment by rnveach** [comment]
@romani We are using custom version of xwiki due to break in configuration.
https://github.com/xwiki/xwiki-commons/blob/e841351fe40898230c18a695d03a5aac07b3a505/pom.xml#L597-L602
They are already on 9.9.1-5.

https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh#L57
We should be able to just update our version or go back to the original if their config is fixed.

As a final option, would skipping this enforcer help any?
https://github.com/xwiki/xwiki-commons/blob/e841351fe40898230c18a695d03a5aac07b3a505/pom.xml#L139
We just need checkstyle to run.

**Comment by rnveach** [comment]
Testing xwiki revert.

**Comment by rnveach** [comment]
wercker looks to be passing now

**Comment by romani** [comment]
yes, xwiki is already upgraded to latest version - https://github.com/xwiki/xwiki-commons/pull/77

**Pull request merged**
