### PR TITLE
Issue #11569: fix ClassMemberImpliedModifierCheck for nested record

### LINKED ISSUE #11569: A false negative about the rule ClassMemberImpliedModifier
I have read check documentation: https://checkstyle.sourceforge.io/config_modifier.html#ClassMemberImpliedModifier
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac Test.java

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
    "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <property name="severity" value="error"/>
  <property name="fileExtensions" value="java, properties, xml"/>
  <module name="TreeWalker">
    <module name="ClassMemberImpliedModifier" />
  </module>
</module>

/var/tmp $ cat Test.java
public class Test {
  Object obj = new Object() {
    public record BadRecord() {}  // should report a warning in this line
  };
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-10.1-all.jar -c config.xml Test.java
Starting audit...
Audit done.
```
---
**Describe what you expect in detail.**
---
Hi, I found a false negative about the rule ClassMemberImpliedModifier. CheckStyle should have reported a warning in line 3. But it does not. Thanks for your consideration.
Static modifier is expected to be present.

### PR DESCRIPTION
**Pull request by strkkk**
Closes #11569

Diff Regression config: https://gist.githubusercontent.com/strkkk/238b6c97492ff6ffdb3be1603deca8fc/raw/b813fdd41472f62f3b0952b53a5670f6b61a7e11/config_single_2.xml

### CODE REVIEW

**Comment by strkkk** [comment]
Github, generate report

**Review by romani — APPROVED** [review]
ok to merge

**Review by rnveach — APPROVED** [review]

**Comment by nrmancuso** [comment]
@strkkk please rebase, CircleCI had an outage yesterday

**Comment by romani** [comment]
I will merge this PR myself to triggered new release after merge.

**Comment by strkkk** [comment]
Github, rebase

**Comment by strkkk** [comment]
> please rebase, CircleCI had an outage yesterday

@nrmancuso done

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/4426192072/jobs/7762182133#step:7:24
https://github.com/checkstyle/checkstyle/actions/runs/4426192072/jobs/7762182278#step:7:24

```

--- a/config/pitest-suppressions/pitest-common-suppressions.xml
+++ b/config/pitest-suppressions/pitest-common-suppressions.xml
@@ -45,6 +45,15 @@
     <lineContent>final String stripped = CommonUtil.relativizeAndNormalizePath(basedir, fileName);</lineContent>
   </mutation>
 
+  <mutation unstable="false">
+    <sourceFile>Checker.java</sourceFile>
+    <mutatedClass>com.puppycrawl.tools.checkstyle.Checker</mutatedClass>
+    <mutatedMethod>finishLocalSetup</mutatedMethod>
+    <mutator>org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator</mutator>
+    <description>removed call to com/puppycrawl/tools/checkstyle/LocalizedMessage::setLocale</description>
+    <lineContent>LocalizedMessage.setLocale(locale);</lineContent>
+  </mutation>
+
   <mutation unstable="false">
     <sourceFile>Checker.java</sourceFile>
     <mutatedClass>com.puppycrawl.tools.checkstyle.Checker</mutatedClass>
EOF
```

and

```
diff --git a/config/pitest-suppressions/pitest-common-2-suppressions.xml b/config/pitest-suppressions/pitest-common-2-suppressions.xml
index e1799fe..843be38 100644
--- a/config/pitest-suppressions/pitest-common-2-suppressions.xml
+++ b/config/pitest-suppressions/pitest-common-2-suppressions.xml
@@ -135,6 +135,15 @@
     <lineContent>return root;</lineContent>
   </mutation>
 
+  <mutation unstable="false">
+    <sourceFile>JavaParser.java</sourceFile>
+    <mutatedClass>com.puppycrawl.tools.checkstyle.JavaParser</mutatedClass>
+    <mutatedMethod>parse</mutatedMethod>
+    <mutator>org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator</mutator>
+    <description>removed call to com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageLexer::removeErrorListeners</description>
+    <lineContent>lexer.removeErrorListeners();</lineContent>
+  </mutation>
+
   <mutation unstable="false">
     <sourceFile>JavaParser.java</sourceFile>
     <mutatedClass>com.puppycrawl.tools.checkstyle.JavaParser</mutatedClass>
@@ -153,6 +162,15 @@
     <lineContent>child = child.getNextSibling()) {</lineContent>
   </mutation>
 
+  <mutation unstable="false">
+    <sourceFile>JavadocPropertiesGenerator.java</sourceFile>
+    <mutatedClass>com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator</mutatedClass>
+    <mutatedMethod>getFirstJavadocSentence</mutatedMethod>
+    <mutator>org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_EQUAL_ELSE</mutator>
+    <description>removed conditional - replaced equality check with false</description>
+    <lineContent>if (matcher.find()) {</lineContent>
+  </mutation>
+
   <mutation unstable="false">
     <sourceFile>JavadocPropertiesGenerator.java</sourceFile>
     <mutatedClass>com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator</mutatedClass>
@@ -179,14 +197,4 @@
     <description>removed call to org/xml/sax/helpers/DefaultHandler::resolveEntity</description>
     <lineContent>inputSource = super.resolveEntity(publicId, systemId);</lineContent>
   </mutation>
-
-  <!-- until https://github.com/checkstyle/checkstyle/issues/12186 -->
-  <mutation unstable="false">
-    <sourceFile>JavaParser.java</sourceFile>
-    <mutatedClass>com.puppycrawl.tools.checkstyle.JavaParser</mutatedClass>
-    <mutatedMethod>parse</mutatedMethod>
-    <mutator>org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator</mutator>
-    <description>removed call to com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageLexer::removeErrorListeners</description>
-    <lineContent>lexer.removeErrorListeners();</lineContent>
-  </mutation>
 </suppressedMutations>
```

**Comment by strkkk** [comment]
@romani this stuff does not seem to be related with my changes

**Comment by romani** [comment]
@strkkk , I am about to merge this PR

**Comment by romani** [comment]
hmm, after rerun still failling - https://github.com/checkstyle/checkstyle/actions/runs/4426192072/jobs/7786402532#step:8:18

**Comment by romani** [comment]
I relaunched whole pitest one more time (for commit after rebase)

**Comment by nrmancuso** [comment]
@romani @rnveach @strkkk CircleCI probably still has sanctions on RU, so it did not run in PR. Local records were language level 15, we need to create new test input file. CI is failing now: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/17752/workflows/b1d510a4-798d-4146-b302-3f8134d40afc/jobs/260784

**Pull request merged**
