### PR TITLE
Issue #4106: organized Checkstyle inputs by Test for AbstractClassName

### PR DESCRIPTION
**Pull request by Nimfadora**
Issue #4106

### CODE REVIEW

**Comment by romani** [comment]
Teamcity problems are not related to changes, reason is https://github.com/checkstyle/checkstyle/issues/3616#issuecomment-289604813

**Comment by Nimfadora** [comment]
@romani, I see. Meanwhile, could you give me some other task if my changes to this task look good?

**Comment by romani** [comment]
mentioned you in another issue

**Comment by romani** [comment]
@Nimfadora , please pin us in gitter chat if you need help with issue selection.

**Pull request merged**
