### PR TITLE
Issue #14899: Updated google coverage page regarding section 7.1.2 Paragraphs

### PR DESCRIPTION
**Pull request by Zopsss**
issue #14899

discussed at https://github.com/checkstyle/checkstyle/pull/14901#discussion_r1622428372

updated coverage page and added message addressing to the new issue for section 7.1.2 Paragraphs

### CODE REVIEW

**Comment by romani** [comment]
@Zopsss , please reference in commit https://github.com/checkstyle/checkstyle/issues/14899
it is better to mark cocmmit with issue that will be closed after merge.

**Review by romani — APPROVED** [review]

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by rdiachenko** [comment]
@romani not sure whether it was intentionally cancelled
image

**Comment by romani** [comment]
@rdiachenko , it will be fixed at https://github.com/checkstyle/checkstyle/pull/15023

**Pull request merged**
