### PR TITLE
Issue #12081: Github action Copy site to sourceforge

### LINKED ISSUE #12081: Github action "Copy site to sourceforge"
https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/diagrams-manual-trigger.md

we need to make action to do `run Github action "Copy site to sourceforge '10.3.1'"` (action takes human provided version as input)
see https://github.com/checkstyle/checkstyle/blob/master/.ci/copy-site-to-sourceforge.sh, reuse it.
see when I executed such script https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#perform-release-build

for testing, create your own projects on sourceforge and test script execution.

ATTENTION: lest postpone this task for later....
There might be BIG problem to authorize copy by SSH/SCP, I am still placing password manually(interactive mode), it will be blocker during execution in girhub (non-interactive mode)

```
✔ ~/java/github/checkstyle/checkstyle [master|✔] 
 $ ./.ci/copy-site-to-sourceforge.sh $PREV_RELEASE $NEW_RELEASE
PREVIOUS RELEASE version:10.3
RELEASE version:10.3.1
Please provide password for romanivanov,checkstyle@shell.sourceforge.net
Pseudo-terminal will not be allocated because stdin is not a terminal.

You already have a shell created.

Clone by ssh only to avoid passwords on push
Cloning into 'checkstyle.github.io'...
```

------

strange it works fine now.

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
Fixes #12081

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
Found a better way:

```
name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "tests/a.txt,tests/b.txt"
        target: "test"
```

**Comment by romani** [comment]
did you test it with sourceforge ? they have very special way to handle ssh.

**Comment by Rahulkhinchi03** [comment]
> did you test it with sourceforge ? they have very special way to handle ssh.

I believe the special way to handle ssh is by sshpass?

**Comment by romani** [comment]
No, please create sourforge project to experience it.

**Pull request closed without merging**
