### PR TITLE
minor: renaming indentation methods to more natural name

### PR DESCRIPTION
**Pull request by rnveach**
renamed startsLine to isOnStartOfLine.
boolean methods should start with 'is'. Even the javadoc for the method says 'is at the start of a line'.

### CODE REVIEW

**Comment by romani** [comment]
is a matter of how you ask question in your mind: "Is it on start of line ?", "Does it start a line ?" 

Both ways are ok. Example: http://docs.oracle.com/javase/7/docs/api/java/lang/String.html from all boolean methods only one have "isXXXXX" format "isEmpty". Format without "is" is compact in most cases, but some time name with "is" is more elegant.

Current form of name is compact and still clear (at least for me), but I am ok with new format too, not a critical for me.

@mkordas , what format do you like ? are you agree with suggested update ?

**Comment by romani** [comment]
@mkordas , please pay attention to this PR.

**Comment by mkordas** [comment]
@romani thanks for pinging me

@rnveach we have dedicated inspection for that: [BooleanMethodNameMustStartWithQuestion](https://github.com/checkstyle/checkstyle/blob/master/config/intellij-idea-inspections.xml#L178). The word `start` is on our [whitelist](https://github.com/checkstyle/checkstyle/blob/master/config/intellij-idea-inspections.xml#L188). Of course it's rather matter of style and convention, but if we wanted to change anything here, we need to modify also this inspection and fix all other places in the code where methods start with `starts`.

**Comment by romani** [comment]
Looks like we can not come to absolute agreement, so ....

@rnveach , I am with merge of this PR only if you fix at least one issue for this Check. As an author of Check (nobody is maintaining it now) you have power to change name as you want to make development easier. I this this will be fair.

If you are not ok, please share more evidences of your idea, or propose another idea.

**Comment by rnveach** [comment]
@romani I am fine with that, that is one of the reasons I started looking over the check.
When I get time, I will look over the issues for this and pick something to fix.

**Comment by romani** [comment]
merged as FF.

ok, I trust you.

**Pull request closed without merging**
