### PR TITLE
Issue #9503: updated example of AST for TokenTypes.LITERAL_TRY

### LINKED ISSUE #9503: update example of AST for TokenTypes.LITERAL_TRY
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_TRY

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
Closes #9503 
CheckStyle_try_changed_PR_photo

```
$ cat Test.java

public class Test{
    void foo() {
        try { } finally {}
    }
}
```
AST in CLI for the above Java file:-
```
$ java -jar checkstyle-8.41-all.jar -T Test.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> Test [1:13]
`--OBJBLOCK -> OBJBLOCK [1:17]
    |--LCURLY -> { [1:17]
    |--METHOD_DEF -> METHOD_DEF [2:4]
    |   |--MODIFIERS -> MODIFIERS [2:4]
    |   |--TYPE -> TYPE [2:4]
    |   |   `--LITERAL_VOID -> void [2:4]
    |   |--IDENT -> foo [2:9]
    |   |--LPAREN -> ( [2:12]
    |   |--PARAMETERS -> PARAMETERS [2:13]
    |   |--RPAREN -> ) [2:13]
    |   `--SLIST -> { [2:15]
    |       |--LITERAL_TRY -> try [3:8]
    |       |   |--SLIST -> { [3:12]
    |       |   |   `--RCURLY -> } [3:14]
    |       |   `--LITERAL_FINALLY -> finally [3:16]
    |       |       `--SLIST -> { [3:24]
    |       |           `--RCURLY -> } [3:25]
    |       `--RCURLY -> } [4:4]
    `--RCURLY -> } [5:0]
```
```
# printing lines we are concerned with:-
$ java -jar checkstyle-8.41-all.jar -T Test.java | grep "3:"
|       |--LITERAL_TRY -> try [3:8]
|       |   |--SLIST -> { [3:12]
|       |   |   `--RCURLY -> } [3:14]
|       |   `--LITERAL_FINALLY -> finally [3:16]
|       |       `--SLIST -> { [3:24]
|       |           `--RCURLY -> } [3:25]
```
Expected update for JavaDoc:-
```
LITERAL_TRY -> try 
 |--SLIST -> { 
 |   `--RCURLY -> } 
 `--LITERAL_FINALLY -> finally 
     `--SLIST -> { 
         `--RCURLY -> } 
```

### CODE REVIEW

**Comment by Devansu-Yadav** [comment]
@romani @timurt @pbludov  Can u pls review this PR?

**Comment by timurt** [comment]
@Devansu-Yadav old example is large, what do you think if we simplify it?

I think simple `try` + `finally` is enough

**Comment by Devansu-Yadav** [comment]
> @Devansu-Yadav old example is large, what do you think if we simplify it?
> 
> I think simple `try` + `finally` is enough

@timurt Yes, that would be better! Can we go for an empty `try` + `finally` block or maybe just single-line comments inside them?

**Comment by romani** [comment]
@Devansu-Yadav ,

just make it `try { } finally {}`
no comments required.

**Comment by Devansu-Yadav** [comment]
> @Devansu-Yadav ,
> 
> just make it `try { } finally {}`
> no comments required.

Done! Updated PR description as well.

**Review by romani — APPROVED** [review]

**Pull request merged**
