### PR TITLE
Issue #4723: fix all cases from the fourth part of idea violations

### PR DESCRIPTION
**Pull request by Nimfadora**
Issue #4723

### CODE REVIEW

**Comment by romani** [comment]
Please rebase this PR to have actual state of what is left

**Comment by Nimfadora** [comment]
@romani travis failed to run apt-get install

**Comment by rnveach** [comment]
> Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/pool/main/o/oracle-java8-installer/oracle-java8-installer_8u131-1~webupd8~2_all.deb  Unable to connect to ppa.launchpad.net:http:
> The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install xsltproc xmlstarlet oracle-java8-installer" failed and exited with 100 during .

Restarting.

**Comment by romani** [comment]
In this PR it is expected to have changes only in inspections config, all other changes should be in separate PR for merge.

**Pull request merged**
