### PR TITLE
Issue #13213: Remove '//ok' comments from InputSpecialEscapeSequences

### PR DESCRIPTION
**Pull request by Livinglaser3**
Issue #13213: Remove '//ok' comments from InputSpecialEscapeSequences

### CODE REVIEW

**Comment by romani** [comment]
please remvoe updated file from [checkstyle-input-suppressions.xml](https://github.com/checkstyle/checkstyle/blob/b6301c189ef5d2d731a755fa9a2e84aa0677494a/config/checkstyle-input-suppressions.xml#L68-L70)

**Comment by Livinglaser3** [comment]
Hi @romani  There are no occurrences of suppressions for the above file in checkstyle-input-suppressions.xml

**Comment by romani** [comment]
You are removed them from IT folder, but issue was about regular test Inputs.

In next PR please send update for inputs from another folder.

**Review by romani — APPROVED** [review]
Ok to merge if ci pass

**Comment by Livinglaser3** [comment]
updated the description please rerun the job

**Pull request merged**
