### PR TITLE
minor: remove //ok Comment

### PR DESCRIPTION
**Pull request by Kevin222004**
minor: remove //ok Comment

### CODE REVIEW

**Review by nrmancuso — APPROVED** [review]
Ok to merge as CI passes

**Comment by rnveach** [comment]
CI won't fail on an unnecessary suppression.

**Review by romani — APPROVED** [review]

**Comment by Kevin222004** [comment]
@rnveach I updated please check

**Comment by nrmancuso** [comment]
@Kevin222004 please make sure to reference failing CI in PR description, please do not assume that reviewers have all context.


@rnveach this PR addresses failure in master at https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=16033&view=logs&j=eb841e9f-6e1e-5c29-3ad5-74ec2c658069&t=a9b761e6-b8d5-50cf-467a-54967189cab2, we leaked failure between suppression PR and pitest PR.

**Comment by nrmancuso** [comment]
@rnveach please confirm you are good

**Pull request merged**
