### PR TITLE
Issue #11865: solve regexp can be simplified

### PR DESCRIPTION
**Pull request by pbludov**
Part of #11865

All `[A-Za-z0-9_]` replaced with `\w`, `[0-9]` replaced with `\d`.

Also, `[A-Za-z0-9]` replaced with `[A-Za-z\d]`. It looks a bit strange for me, but the inspection works in this way.

### CODE REVIEW

**Comment by pbludov** [comment]
The PR is ready for review. I'm not going to assign anyone till GSOC ends.

**Comment by romani** [comment]
@pbludov , please resolve conflict

**Review by romani — CHANGES_REQUESTED** [review]
Ok

**Review by romani — APPROVED** [review]
Okok

**Review by nick-mancuso — COMMENTED** [review]
I am OK to update java code for this inspection, since all our java code is well tested and regexp in Java is system agnostic. Also, we have the intellij inspection to make `\w` and `\d` consistent in our code base (at least in some of our codebase, this is another discussion). But, I am not a big fan of migrating all scripts to this, as I have doubts about it's portability (both for OS and grep/perl/awk, etc.), and we have no way to enforce new format going forward. Also, if we match some unicode digit by accident in a script (`\d` is **not** equivalent to [0-9]), this will be very difficult to debug, especially in cases where we are using the result as an integer. Additionally, by using `\d` in cases like pmd inspections (such as `classPattern`), we are  extending allowed naming conventions in our project. Example: `MyClass८৮੮૮୮௮౮೮` is now a valid identifier. @romani @pbludov are we sure about this update?

**Comment by pbludov** [comment]
I don't like these changes either. Let's drop this PR.

**Comment by romani** [comment]
@pbludov , can we revert \d ? And keep rule suppresed or disabled

**Comment by rnveach** [comment]
@romani @pbludov Is there any piece of this PR we are going to salvage?

**Comment by romani** [comment]
I think we can close PR as even author do not like it, and too much "false positives" or "wont fix".
in case somebody want to continue, we can reopen this PR or reuse branch.

**Pull request closed without merging**
