### PR TITLE
Issue #1566: Checkstyle violations fixes

### PR DESCRIPTION
**Pull request by rdiachenko**
The following violations were fixed:
- AvoidNestedBlocks
- FinalLocalVariable
- UnusedImports
- RegexpSingleline: Using THIS as a lock is a bad practice (use class variable instead)

### CODE REVIEW

**Comment by romani** [comment]
>``` - * @see JavadocNodeImpl
+ * @see com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocNodeImpl```

I am not sure about this. Is it our Check demand that ? we already have UnusedImport in checkstyle_checks.xml , please single out that update in separate PR, we will discuss it.

**Comment by rdiachenko** [comment]
@romani it is ok if we leave just a simple JavadocNodeImpl and remove unused import. It was my mistake, I fixed it.

**Comment by romani** [comment]
if UnusedImport give us false positives - issue has to be created to fix that.

merged as FF

**Comment by rdiachenko** [comment]
@romani there is an option in UnusedImports ```processJavadoc``` with ```false``` default value. I changed it to ```true``` so violations disappeared.

**Comment by mkordas** [comment]
@rdiachenko @romani - shouldn't we make it default option then? Is there any serious impact on performance with this option enabled?

**Comment by rdiachenko** [comment]
@mkordas there is a reason why we made the default value as ```false``` (http://checkstyle.sourceforge.net/config_imports.html#UnusedImports):
>> Optionally: it is referenced in Javadoc comments. This check is off by default, as it is considered bad practice to introduce a compile time dependency for documentation purposes only. As an example, the import java.util.Date would be considered referenced with the Javadoc comment {@link Date}. The alternative to avoid introducing a compile time dependency would be to write the Javadoc comment as {@link java.util.Date}.

**Comment by romani** [comment]
When I first run into a problem that reference in javadoc (special format of multi-line comment) require "import" I was surprised.

I agree that javadoc should live its own live and do not affect class implementation. Extra import is extra dependecies - should be avoided.

But for our code - we need to make processJavadoc as TRUE, as we need to use options that Checks have (just another ITs for a Check+option).

@rdiachenko , please create issue to make options as TRUE - https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L192

**Comment by rdiachenko** [comment]
@romani issue created: #1627

**Pull request closed without merging**
