### PR TITLE
Issue #12671: Kill mutation for finalLocalVariable

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #12671: Kill mutation for finalLocalVariable

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/6e271c2ae713051c0a30111211de5627/raw/9f34341ce6c7feabbda4bc3d59fa62df427d775d/FinalLocal.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/360a95ed7bb60d7a0956e531199d484c4d6f6617/test-projects.properties
Report label: Regression-Aug-4-2

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
rebased and conflict is resolved we will move forward with removal of code as we see that diff report finds nothing.

**Comment by rnveach** [comment]
I would be extremely careful removing this type of code.

We are removing items from the array on a leave token in this code. This code is the only time we remove items from the array. This means we are always adding to the array, so every method, every inner class is being collected together into this one array. We have seen weird issues before because of this type of behavior and code type.

I am not seeing a reset on this variable on a new file, so it seems we are event collecting items across multiple files basically making this a multi-file check it it is true.

**Comment by romani** [comment]
CI job for no exceptions is failing with `Caused by: java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects` that contribute to same reason as described above, as collection is growing.

**Comment by rnveach** [comment]
Tests like `testFinalLocalVariableSwitchAssignment` leak data after the file is run.

`prevScopeUninitializedVariables: [[res[92x15]], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]`

In addition, we run Checkstyle twice during our tests. Once during `verify(Checker checker, File[] processedFiles, Map<String, List<String>> expectedViolations)` and the second during `getActualViolationsForFile(Configuration config, String file) throws Exception`.

**Comment by romani** [comment]
@rdiachenko , please help to crack this heavy puzzle.

**Comment by rdiachenko** [comment]
Resolved by https://github.com/checkstyle/checkstyle/pull/13814

**Pull request closed without merging**
