### PR TITLE
Issue #7833: Create code of conduct

### PR DESCRIPTION
**Pull request by akki111singh**
Issue #7833

### CODE REVIEW

**Comment by akki111singh** [comment]
@rnveach  please review

**Comment by romani** [comment]
@akki111singh , please resolve CI https://travis-ci.org/github/checkstyle/checkstyle/jobs/671975281#L296 failure meanwhile.

**Comment by akki111singh** [comment]
@romani  i am not getting what the error is can you please help

**Comment by pbludov** [comment]
> @romani i am not getting what the error is can you please help

The error is
```bash
There are now fewer misspellings than before.
.ci/jsoref-spellchecker/whitelist.words could be updated
```
To fix the error please do
```bash
patch '.ci/jsoref-spellchecker/whitelist.words' <<EOF
@@ -553,3 +553,3 @@
 hne
-Homepage
+homepage
 horizontalwhitespace
EOF
```

**Comment by akki111singh** [comment]
> @akki111singh , please resolve CI https://travis-ci.org/github/checkstyle/checkstyle/jobs/671975281#L296 failure meanwhile.

@romani  done

**Comment by akki111singh** [comment]
@pbludov Thanks it helped

**Comment by strkkk** [comment]
@romani please review CoC

**Comment by akki111singh** [comment]
@romani updated accordingly

**Pull request merged**
