### PR TITLE
Issue #2661: Enforce CustomDeclarationOrder of sevntu-checkstyle over Checkstyle source code

### PR DESCRIPTION
**Pull request by MEZk**

### CODE REVIEW

**Comment by romani** [comment]
I reverted latest commit from contribution repo, travis should pass after rebase

**Comment by romani** [comment]
please proceed with this order, if you find some cases where readability is damaging , add them to temporal suppression and lets discuss.

even update in *Utils  classes is ok.

**Comment by MEZk** [comment]
@romani 
There are some contradictions left.

1) The foloving violations of DeclarationOrderCheck from Checkstyle main repo contradicts to CustomDeclarationOrderCheck from SevNTU-Checkstyle:
````
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Main.java:121:5: error: Static variable definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Main.java:124:5: error: Static variable definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Main.java:127:5: error: Static variable definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Main.java:130:5: error: Static variable definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Main.java:133:5: error: Static variable definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Main.java:136:5: error: Static variable definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Main.java:139:5: error: Static variable definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Main.java:142:5: error: Static variable definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Main.java:145:5: error: Constructor definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java:71:5: error: Constructor definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java:90:5: error: Static variable definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractTypeAwareCheck.java:413:9: error: Constructor definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java:99:5: error: Static variable definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/gui/Main.java:56:5: error: Static variable definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/gui/Main.java:59:5: error: Static variable definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/gui/Main.java:62:5: error: Constructor definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtils.java:86:5: error: Constructor definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java:86:5: error: Constructor definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java:94:5: error: Static variable definition in wrong order.

```

2) The foloving violations of OverloadMethodsDeclarationOrder from Checkstyle main repo contradicts to CustomDeclarationOrderCheck from SevNTU-Checkstyle:
````
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporter.java:140: error: Overload methods should not be split. Previous overloaded method located at line '62'.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporter.java:159: error: Overload methods should not be split. Previous overloaded method located at line '127'.
````

3) The foloving violations of VariableDeclarationUsageDistance from Checkstyle main repo contradicts to CustomDeclarationOrderCheck from SevNTU-Checkstyle:
````
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java:99:5: error: Variable access definition in wrong order.
/checkstyle/checks/TranslationCheck.java:103:5: error: Variable access definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java:109:5: error: Variable access definition in wrong order.
[checkstyle] checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java:94:5: error: Variable access definition in wrong order.
````

**Comment by romani** [comment]
Do we have a chance to make them work with same demand for structure, customdeclarationorder config need to be changed

**Comment by MEZk** [comment]
@romani 
>customdeclarationorder config need to be changed.
Done.

**Pull request merged**
