### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by romani**

### CODE REVIEW

**Comment by strkkk** [comment]
ok, now it does not add new single quotes, but removes existing. Not good.

**Comment by romani** [comment]
@strkkk , should we disable for now integration with this service ?
until problems with `'` are resolved. 

Do you have thread with support on this ? how they think it should work ?

**Comment by strkkk** [comment]
@romani I am discussing possibilities with them. I do not have much time for it, but will resume it soon.

It looks like there is no good way to resolve quotes issues, since these triple curly braces are lost in process of translation.

I see only 2 ways:
- change messages to do not have odd number of quotes and avoid `{}` in it + change escape policy back to 1
- do not use crowdin

**Comment by romani** [comment]
> avoid {} in it

we can do this, it is symbols not a part of English.

>  do not have odd number of quotes 

this is more challenging, as quotes are part of some language words.

**Comment by rnveach** [comment]
> Is it possible to not use odd numbers of quotes ? most cases are single quote.
I am surprised that we run into this problem are first very technical project that is multi-language ..... do they have example how such problems should be handled ?

This is something built into property files and not something specific to crowdin. It's just their flaky parsing is trying to bring the issue to our attention.

Single quotes for no reason at all must always be doubled. If the single quote is not doubled, I am pretty sure the quote does not get printed at all to the output. The single quote is basically an escaping character for properties similar as like XML has `&amp;` for `&` as `&` is treated as the start of something special in XMLs.

**Comment by romani** [comment]
@strkkk m I think it is time to close this PR and remove integration for this service for now, we can try in 1-2 years again

**Comment by romani** [comment]
@strkkk , did you contact Crowdin ?

**Comment by strkkk** [comment]
@romani no, unfortunately I do not have time for that.

I am closing PR

**Pull request closed without merging**
