### PR TITLE
Issue #1292: AbstractHeaderCheck coverage has been increased to 100%

### PR DESCRIPTION
**Pull request by sabaka**
Without changes in check's code

### CODE REVIEW

**Comment by mkordas** [comment]
@sabaka, Travis still says `com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck failed coverage check. Line coverage rate of 96.4% is below 100.0%` - does it work for you locally?

Moreover TeamCity has couple of complains - can you look at them? Also rebase should help here as well.

**Comment by sabaka** [comment]
@mkordas, Yes, ``mvn clean verify`` works fine on local. I sent log to Roman.
I'm going to investigate problem today, but a bit later.

**Comment by mkordas** [comment]
@sabaka, do you use Java 8 to run `mvn` locally? If not, this might be the issue.

**Comment by sabaka** [comment]
@mkordas 
``` $ mvn -v
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T12:57:37+01:00)
Maven home: /opt/apache-maven-3.3.3
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"```

**Comment by mkordas** [comment]
Yeah, so let's try with Java 8 - we agreed to use it as our main development JDK.

**Comment by romani** [comment]
Please share logs at mail-list

**Comment by romani** [comment]
Java7 is used by Travis too , see Sonar matrix item https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L53

**Comment by mkordas** [comment]
@romani, `cobertura:cobertura` does not fail on too coverage not being enough, so I still believe using Java 8 locally would help to solve issue.

**Comment by romani** [comment]
Yes, lets use java8 as main dev jdk.

**Comment by romani** [comment]
@mkordas , my Idea can not find any problems with this code.

codecov could be ignored, most likely it is a problem in service as it is not configured to put status, it has to place a comment as it do in other PRs.

**Comment by mkordas** [comment]
@romani, @sabaka, there are two issues in this commit:
* Statically imported element 'fail' is unnecessarily qualified with 'Assert' at line 142 
* 'new IOException()' without arguments at line 153

Additional comments:
1) `public void setHeaderTwiceTest()` - we have convention to begin test names with `test` I believe
2) `testIoExceptionWhenLoadHeader` -> `testIoExceptionWhenLoadingHeader`
3) testIoExceptionWhenLoadHeader checks two things I believe - please split it into two tests

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
