### PR TITLE
Remove dependency to commons-lang3 library.

### PR DESCRIPTION
**Pull request by kaj**
As suggested in #2428.

### CODE REVIEW

**Comment by kaj** [comment]
Eh ...  Illegal commit message?   Ok, I'll remove this pull request and create a new one.

**Comment by kaj** [comment]
Replaced by #3027

**Comment by romani** [comment]
You could just do rebase and git push --force to your remote branch, PR will be rebuild automatically.

**Comment by kaj** [comment]
Thanks, I actually did a push --force on my other branch (referenced in #3027).  That branch contains some fixes that this one does not.

**Pull request closed without merging**
