### PR TITLE
Fixed: Parse errors can result in a NPE in the SuppressWarningsHolder,  issue #1489

### PR DESCRIPTION
**Pull request by MEZk**

### CODE REVIEW

**Comment by romani** [comment]
1) Checkstyle does not support execution on non-compiled files any crashes are possible.
Please reproduce the problem by correct test case.

2) catching NPE is not required , just let that Exception go to upper level - it will fail a test.

**Comment by MEZk** [comment]
@romani 
>1) Checkstyle does not support execution on non-compiled files any crashes are possible.
Please reproduce the problem by correct test case.

From author of the issue:
>I'm able to reproduce this using any rules file with a SuppressionFilter and a syntactically incorrect file, ...

And I read original Checkstyle-IDEA issue:
https://github.com/jshiell/checkstyle-idea/issues/127

They Also try to reproduce NPE on syntactically incorrect file. But I'll try to find out a way to reproduce it in correct way.

**Comment by romani** [comment]
Running Checkstyle on non compiled sources is error prone, exception could happen even at Checks. Please find me for a call.

**Comment by romani** [comment]
Checkstyle will never work properly on non-compilable sources :
http://checkstyle.sourceforge.net/writingchecks.html#Limitations

if any problem with compilation exists - behavior could be weird and unexpected. Non compilable code could create unexpected AST Tree structure and all Checks expect tree structure to be the same for all cases that java support.

**Pull request closed without merging**
