### PR TITLE
Issue #3208: Add better support for chained methods

### PR DESCRIPTION
**Pull request by kevinconaway**
@rnveach @romani Fixes for #3208.  Please review.

### CODE REVIEW

**Comment by kevinconaway** [comment]
Not sure why the teamcity build failed, the results are difficult to interpret

**Comment by rnveach** [comment]
@kevinconaway Since the messages are in files you didn't change, it could be related to you using an old master. Try rebasing on the latest master.
[your pr](https://github.com/kevinconaway/checkstyle/commits/issue-3208) vs [master](https://github.com/checkstyle/checkstyle/commits)

**Comment by kevinconaway** [comment]
Yup, good call, that check is passing now.

**Comment by romani** [comment]
@kevinconaway , please squash your commits in one.

@rnveach , please provide code review, you better know that Check than I.

@kevinconaway , UTs is basic testing, but we need regression testing on big projects.
Please use https://github.com/checkstyle/contribution/tree/master/checkstyle-tester to generate HTML report  on some project. There will be a lot of violations - do not worry. Please use https://github.com/checkstyle/contribution/tree/master/patch-diff-report-tool  to make a diff of latest "master" branch and your branch. Diff report need to be shared on github.io for us to review and confirm that there are no regression.

**Comment by kevinconaway** [comment]
Thats seems fairly time consuming (not counting the time it took to track down and fix the issue).  I'd prefer to wait until after code review is complete before spending more time generating these reports.

Is that fair?

**Comment by romani** [comment]
kind of yes, but code review might result in some changes only. While it is under review , you can slowly get to know how to run reports, and ask us questions. Regeneration of reports will not take you that much time as first launch.

Regression testing could show you how bad, good your solution.

**Comment by rnveach** [comment]
@romani
Testing wise, the new code works for the situations I just put in the issue for non-Eclipse IDEs.
The change looks like the right location to me.

@kevinconaway 
I think we need 2 more minor changes though.
1) `areMethodsChained` can be declared static.
2) We should add 1-2 negative/violation test cases (where `)` and `(` are on the same line and not the same line) to make sure we don't overlook required indentation message in future changes. Current change had no effect on our other current tests. A negative case should also appease mutation testing.

I also agree with romani on running regression reports sooner rather than later, especially for this check. I believe this check should be run on all projects, as you never know which project you'll uncover bugs with. I have tried making changes for this check and all tests passed fine but when running regression before the PR, I uncovered issues my changes made that were not being seeing otherwise.

Once you have your computer setup for regression, it is very easy to run it multiple times. I personally use [launch_diff.sh](https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/launch_diff.sh) to manage almost the entire process for me. Usually only takes maybe 30 minutes for the process to finish on all projects.

**Comment by kevinconaway** [comment]
Here is what I did to run the regression report:

In the checkstyle project, I switched to my branch and ran:
`mvn clean install -DskipTests -Dcobertura.skip=true -Dfindbugs.skip=true -Dpmd.skip=true` to install the project locally.

I then went to the _checkstyle-tester_ project and ran:

`./launch.sh -Dcheckstyle.config.location=my_check.xml`

I copied the results from _target/site_ to my personal github pages repo.  Those reports are available here: https://kevinconaway.github.io/checkstyle-tester-3339/

I also copied the _target/checkstyle-result.xml_ file to /_tmp/patched-result.xml_

In the checkstyle repo, I switched back to the master branch and ran:
`mvn clean install -DskipTests -Dcobertura.skip=true -Dfindbugs.skip=true -Dpmd.skip=true` to instal the project locally

I went back to the _checkstyle-tester_ project and re-ran:

`./launch.sh -Dcheckstyle.config.location=my_check.xml`

I copied the _target/checkstyle-result.xml_ file to /_tmp/master-result.xml_

I ran the patch diff tool on those two reports:

`java -jar target/patch-diff-report-tool-0.1-SNAPSHOT-jar-with-dependencies.jar --baseReport /tmp/master-result.xml --patchReport /tmp/patched-result.xml --output target/diff`

I then copied the _target/diff_ folder to my personal page, which is available here:

https://kevinconaway.github.io/checkstyle-diff-3339/

Is that correct?

**Comment by romani** [comment]
thanks a lot, while we reviewing your results , please make sure that in PR you have only one commit, all changes are rebased on master.

Did you review results yourself ? Do you see regression or all changes are expected ?

**Comment by kevinconaway** [comment]
> Did you review results yourself ? Do you see regression or all changes are expected ?

Its hard to tell, there are apparently 208635 warnings so I can't diff them all.  Running both reports produced the same number of warnings so I guess that is a good sign, right?

**Comment by kevinconaway** [comment]
> We should add 1-2 negative/violation test cases (where ) and ( are on the same line and not the same line) to make sure we don't overlook required indentation message in future changes. 

@rnveach I'm not sure what you mean here.  Would you mind explaining further?

**Comment by rnveach** [comment]
@kevinconaway 
> Would you mind explaining further?

Your junit produces no violations on formatted code, so it shows it works as intended under the right conditions. I consider this a positive test case.
It should produce violations on improperly formatted code, in this case when the code is not indented enough. I consider this a negative test case. If we add/remove your change and this negative junit stayed, we should see different indentation levels being requested. This allows us to review changes in the future that could want these violations messages to change.
In short, in the new test the variable [expected](https://github.com/checkstyle/checkstyle/pull/3339/commits/d95adb46f475cdff0ccd7a72435412db5e416406#diff-88d68aaf0963249939255684219c43b1R1690) shouldn't be an empty array. Look at some of the other tests for examples.

> I can't diff them all

The report you linked to, https://kevinconaway.github.io/checkstyle-diff-3339/, is the diff and it shows all the messages are the same. So there is no difference.

> I guess that is a good sign, right?

This is a good sign the change doesn't break existing functionality but because this is a fix for an issue, it also shows that none of the code tested has this issue in it. It could mean its a rare case. This is why I like to run the diff on all projects, as you never know which one will stand out. @romani can decide if you should do more or if it is enough.

**Comment by kevinconaway** [comment]
@rnveach understood, thanks.  I was able to get the `launch_diff.sh` to work with a little tweaking.  Below are the results for the projects that I ran it on:

https://kevinconaway.github.io/launch-diff-results-3339/

As you can see, only the Hbase project had differences but I'm not quite sure what to make of them.  The affected code seems to use non-standard indentation so I'm unsure what the correct result should be.

@romani thoughts?

**Comment by romani** [comment]
> launch-diff-results-3339

Correct.

> checkstyle-diff-3339

Ok, but mean that test projects are not good for testing of this feature.

> https://github.com/checkstyle/checkstyle/issues/3208#issuecomment-226659383

As you come from Apache Spark project, can you share diff report base on it. We need code base that use chained methods a lot. Can you propose some other project ?

**Comment by kevinconaway** [comment]
I'm not a member of the Apache Spark project, just a user of it.  That said, the spark project is written mostly, if not entirely in scala.

**Comment by romani** [comment]
merged as FF.

If smth found as bad regression, at least we have single commit to revert.

**Comment by kevinconaway** [comment]
Thanks @romani

**Pull request merged**
