### PR TITLE
Issue #13627: Enable macros to fix missing 'javadoc.unclosedHtml'

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Part of https://github.com/checkstyle/checkstyle/issues/13627

### CODE REVIEW

**Review by nrmancuso — APPROVED** [review]

**Comment by nrmancuso** [comment]
@relentless-pursuit i think we linked the wrong issue, don’t we have one specifically to activate macros for violation messages in checks?

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit i think we linked the wrong issue, don’t we have one specifically to activate macros for violation messages in checks?
> 
> Re: [#13815 (comment)](https://github.com/checkstyle/checkstyle/pull/13815#discussion_r1344142754)

I did the PR based on a comment by @rnveach on my PR https://github.com/checkstyle/checkstyle/pull/13815. i assumed to have just macros done for these files. But, i can update the commit message and PR based on the feedback.

**Review by rnveach — APPROVED** [review]

**Review by rnveach — CHANGES_REQUESTED** [review]
Issue number doesn't appear correct. Also I think we have suppression file for this. I am searching.

**Comment by rnveach** [comment]
Suppression file: https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle-non-main-files-suppressions.xml#L184

**Comment by rnveach** [comment]
Issue number should be https://github.com/checkstyle/checkstyle/issues/13627 . It appears it was closed incorrectly as we must have 15 lines or so in the suppression file.

I am re-opening this issue.

**Comment by rnveach** [comment]
@relentless-pursuit I am sure it is obvious now, but when I originally said these were 2 separate issues, that means they should have 2 separate numbers. I missed conversation with @nrmancuso in this thread, and it wouldn't have been the end to merge this with wrong number, but this shed light on some things we missed and forgot about. An issue was closed as completed, when it wasn't. I couldn't find 1 issue for a set of suppressions that were to be removed, and I made sure to comment other issues on remaining items listed in suppressions.

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit I am sure it is obvious now, but when I originally said these were 2 separate issues, that means they should have 2 separate numbers. I missed conversation with @nrmancuso in this thread, and it wouldn't have been the end to merge this with wrong number, but this shed light on some things we missed and forgot about. An issue was closed as completed, when it wasn't. I couldn't find 1 issue for a set of suppressions that were to be removed, and I made sure to comment other issues on remaining items listed in suppressions.
> 
> If your unsure what issue number to use, please ask us before opening the PR. I had to hunt just to find the correct issue for this.

Sure, will keep that in mind.

**Comment by romani** [comment]
Issue number should be https://github.com/checkstyle/checkstyle/issues/13627

Please update commit message and PR description

**Comment by romani** [comment]
@rnveach , please review.

**Comment by relentless-pursuit** [comment]
@romani can we add hacktoberfest-accepted label to it?

**Review by rnveach — APPROVED** [review]

**Pull request merged**
