### PR TITLE
100% test coverage for FinalClassCheck, #1009

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by mkordas** [comment]
Good job, but we shouldn't print any stacktraces in tests. Just leave catch block empty and follow the pattern from other tests to avoid Checkstyle violation.

**Comment by romani** [comment]
no stacktraces or any other debug output in Maven output/logs during testing phase - only success or failure flags.

**Comment by Vladlis** [comment]
@mkordas actually checkstyle doesn't allow to leave it empty 
[checkstyle] /home/vlad/eclipseProjects/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java:85: Empty catch block.
anyway, I've decided to print stacktrace just to put something into the catch block until I figure out what to do, as I thought, that NPE sholdn't appear in FinalClassCheck at all

**Comment by romani** [comment]
use ```assertTrue(true);``` to do smth in catch block, but NPE should not appear at all, Checkstyle throw NPE only on unexpected errors that are bugs.

**Comment by mkordas** [comment]
@Vladlis, as I initlially wrote, please how it is done in other tests: https://github.com/checkstyle/checkstyle/blob/0f58857d73933c7b6b7e62f0c7c16ad7af51556f/src/test/java/com/puppycrawl/tools/checkstyle/checks/ClassResolverTest.java#L44
@romani `assertTrue(true)` could also be detected by Checkstyle as something silly/unnecessary, exactly the same as empty statement (`;`).

**Pull request closed without merging**
