### PR TITLE
Issue #3891: reorganized filters package inputs

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3891

No inputs in main directory. https://github.com/rnveach/checkstyle/tree/issue_3891_3/src/test/resources/com/puppycrawl/tools/checkstyle/filters

Please take extra look at code like :
>              "http://checkstyle.sourceforge.net/files/suppressions_none.xml",
>             "https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/site/resources/"
>               + "files/suppressions_none.xml",

File was renamed. Will this affect `checkstyle.sourceforge.net` and need to be renamed too?
We shouldn't be relying on these type of tests as stuff needs to change in PR, like file names and contents. So check may have weird results in PR and once merged.

### CODE REVIEW

**Comment by romani** [comment]
@rnveach ,

yes, just search it - https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_filters.xml#L521
this file is user facing, web site version of it should not change in name. 

to recheck links are not broken on website - use 
https://github.com/checkstyle/checkstyle/blob/master/.ci/run-link-check-plugin.sh

**Comment by rnveach** [comment]
@romani 
> run-link-check-plugin.sh

This check passes so does that mean my changes are fine?

> yes, ... this file is user facing, web site version of it should not change in name.

So your saying my changes will affect the site? So I have to undo these renames as they can't be changed at all?
Why do we link to these files instead of embedding them in the page like we do other examples?

**Comment by romani** [comment]
test should not force their rules on "src/site/resources" it is web site file, it is not file for test.
if test is using it, it should treat it as any other file from web - as is.

> This check passes so does that mean my changes are fine?

there might be some suppressions, sourseforge do have some SSL settings that this plugin does not support, so there a lot of suppressions.

>  So I have to undo these renames as they can't be changed at all?

please do

> Why do we link to these files instead of embedding them in the page like we do other examples?

no very good reason, probably to ease user work - just click to download.
and we use this file in test to probably test loading of file from web by url.

**Comment by rnveach** [comment]
I will do undo my renames.

So how does this file which is in a deep sub-directory get moved to `files` so I can verify none of my other renames will cause problems?

**Comment by romani** [comment]
file is not in test resources, it is checkstyle/src/site/resources/files/suppressions_none.xml

**Comment by rnveach** [comment]
ah i see, I mistook the master links for a different area.
So I just need to revert those strings, not any files.

**Comment by rnveach** [comment]
Done.

**Pull request merged**
