### PR TITLE
Clean up open streams, issue #778

### PR DESCRIPTION
**Pull request by mkordas**
All violations of Fildbugs rule [OBL: Method may fail to clean up stream or resource](http://findbugs.sourceforge.net/bugDescriptions.html#OBL_UNSATISFIED_OBLIGATION) are fixed.

### CODE REVIEW

**Comment by mkordas** [comment]
I was not able to use try-with-resources in `UniquePropertiesCheck` due to decreased coverage on bytecode level even though on code level it was 100% :confounded:

**Comment by romani** [comment]
as you do no functional changes, I am ok to change pom file with new (slightly less) values for coverage for that Check.

I introduced coverage enforcement only to control that UTs are not reduced in strength after bug fixing, that usually very hard to catch.

**Comment by mkordas** [comment]
Let's leave it as it is, lower coverage on not visible code may be confusing for someone. Tools are not ready for try-with-resources yet.

**Comment by romani** [comment]
ok, merged as FF.

yes, it is not critical point for us, in next few years tools will be be more smart or smth else will change.

**Pull request closed without merging**
