### PR TITLE
Issue #13097: Split design xdocs into separate pages

### PR DESCRIPTION
**Pull request by stoyanK7**
Part of #13097

### CODE REVIEW

**Comment by stoyanK7** [comment]
Github, generate site

**Comment by romani** [comment]
2 CI failures

**Comment by stoyanK7** [comment]
Super weird failures. Before: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/19024/workflows/0128d256-c5bf-4e80-9434-8097b2526959/jobs/312584?invite=true#step-103-2438

```
------------ grep of linkcheck.html--BEGIN
501c501
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheck.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheck.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr></table></td></tr>
------------ grep of linkcheck.html--END
Exit code:1

Exited with code exit status 1
```

After(fix is pushed at https://github.com/checkstyle/checkstyle/compare/cec964e66a5efafb712a855f924044b3bdf4641b..f3bc28921296cf72c31795796dd773ffefd6fe57):
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/19028/workflows/bde48c77-41e1-4100-ba30-ae43ae3e5923/jobs/312749?invite=true#step-103-2437
```
[INFO] ------------------------------------------------------------------------
------------ grep of linkcheck.html--BEGIN
49,50c49,50
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/api/AbstractCheck.FileContext.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr></table></td></tr>
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/api/AbstractCheck.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/api/AbstractCheck.FileContext.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr>
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/api/AbstractCheck.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr>
61,62c61,62
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.FileContext.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr></table></td></tr>
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.FileContext.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr>
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr>
68c68
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/api/AuditEvent.html#%3Cinit%3E(java.lang.Object,java.lang.String,com.puppycrawl.tools.checkstyle.api.Violation)">../AuditEvent.html#%3Cinit%3E(java.lang.Object,java.lang.String,com.puppycrawl.tools.checkstyle.api.Violation)</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/api/AuditEvent.html#%3Cinit%3E(java.lang.Object,java.lang.String,com.puppycrawl.tools.checkstyle.api.Violation)">../AuditEvent.html#%3Cinit%3E(java.lang.Object,java.lang.String,com.puppycrawl.tools.checkstyle.api.Violation)</a>: doesn't exist.</i></td></tr>
79c79
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/api/FileText.html#%3Cinit%3E(com.puppycrawl.tools.checkstyle.api.FileText)">../FileText.html#%3Cinit%3E(com.puppycrawl.tools.checkstyle.api.FileText)</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/api/FileText.html#%3Cinit%3E(com.puppycrawl.tools.checkstyle.api.FileText)">../FileText.html#%3Cinit%3E(com.puppycrawl.tools.checkstyle.api.FileText)</a>: doesn't exist.</i></td></tr>
103c103
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/Checker.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/Checker.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr>
261c261
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr>
532c532
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/checks/regexp/CommentSuppressor.html#%3Cinit%3E(com.puppycrawl.tools.checkstyle.api.FileContents)">../../checks/regexp/CommentSuppressor.html#%3Cinit%3E(com.puppycrawl.tools.checkstyle.api.FileContents)</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/checks/regexp/CommentSuppressor.html#%3Cinit%3E(com.puppycrawl.tools.checkstyle.api.FileContents)">../../checks/regexp/CommentSuppressor.html#%3Cinit%3E(com.puppycrawl.tools.checkstyle.api.FileContents)</a>: doesn't exist.</i></td></tr>
603c603
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/ConfigurationLoader.InternalLoader.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/ConfigurationLoader.InternalLoader.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr>
634c634
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoader.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoader.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr>
712c712
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/PackageNamesLoader.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/PackageNamesLoader.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr>
732c732
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/TreeWalker.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/TreeWalker.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr>
749c749
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/XmlLoader.html#%3Cinit%3E(java.util.Map)">#%3Cinit%3E(java.util.Map)</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/XmlLoader.html#%3Cinit%3E(java.util.Map)">#%3Cinit%3E(java.util.Map)</a>: doesn't exist.</i></td></tr>
782c782
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGenerator.html#%3Cinit%3E(com.puppycrawl.tools.checkstyle.api.DetailAST,int,int,int,com.puppycrawl.tools.checkstyle.api.FileText,int)">../../xpath/XpathQueryGenerator.html#%3Cinit%3E(com.puppycrawl.tools.checkstyle.api.DetailAST,int,int,int,com.puppycrawl.tools.checkstyle.api.FileText,int)</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGenerator.html#%3Cinit%3E(com.puppycrawl.tools.checkstyle.api.DetailAST,int,int,int,com.puppycrawl.tools.checkstyle.api.FileText,int)">../../xpath/XpathQueryGenerator.html#%3Cinit%3E(com.puppycrawl.tools.checkstyle.api.DetailAST,int,int,int,com.puppycrawl.tools.checkstyle.api.FileText,int)</a>: doesn't exist.</i></td></tr>
1303c1303
< <td><i><a href="com/puppycrawl/tools/checkstyle/xpath/iterators/ReverseListIterator.html#%3Cinit%3E(java.util.Collection)">com/puppycrawl/tools/checkstyle/xpath/iterators/ReverseListIterator.html#%3Cinit%3E(java.util.Collection)</a>: doesn't exist.</i></td></tr></table></td></tr>
---
> <td><i><a href="com/puppycrawl/tools/checkstyle/xpath/iterators/ReverseListIterator.html#%3Cinit%3E(java.util.Collection)">com/puppycrawl/tools/checkstyle/xpath/iterators/ReverseListIterator.html#%3Cinit%3E(java.util.Collection)</a>: doesn't exist.</i></td></tr>
------------ grep of linkcheck.html--END
Exit code:16

Exited with code exit status 1


```

**Comment by stoyanK7** [comment]
I will make linkcheck plugin more forgiving. It is creating problems just because of a `</table>` tag.

**Comment by stoyanK7** [comment]
Github, generate site

**Review by romani — APPROVED** [review]
ok to merge

**Review by nrmancuso — APPROVED** [review]

**Comment by stoyanK7** [comment]
@nrmancuso Done.

**Comment by stoyanK7** [comment]
Table descriptions are OK.

**Comment by nrmancuso** [comment]
Looks like failure in semaphore is concurrency/credits issue, not related to changes in this PR.

**Pull request merged**
