### PR TITLE
Issue #13213: Remove '//ok' comments from Input files (RedundantImport and UnusedImport)

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Part of https://github.com/checkstyle/checkstyle/issues/13213

Link to check documentation: https://checkstyle.org/checks/imports/redundantimport.html, https://checkstyle.org/checks/imports/unusedimports.html
```

% grep -A 1 'UnnecessaryOkComment' checkstyle-input-suppressions.xml | grep -B 1 'unusedimports' | sed '/^--$/d' | grep -c 'UnnecessaryOkComment'

30

% grep -A 1 'UnnecessaryOkComment' checkstyle-input-suppressions.xml | grep -B 1 'unusedimports'        
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsAnnotations.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsRecordsAndCompactCtors.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsRecordsAndCompactCtors.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsRecordsAndCompactCtors.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsRecordsAndCompactCtors.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsRecordsAndCompactCtors.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsRecordsAndCompactCtors.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsRecordsAndCompactCtors.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsRecordsAndCompactCtors.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsRecordsAndCompactCtors.java"/>
--
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImports15Extensions.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsArrayRef.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsBug.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsFromJavaLang.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsFromJavaLang.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsFromJavaLang.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsFromJavaLang.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsJavadocQualifiedName.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsShadowed.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsShadowed.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsShadowed.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsShadowed.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsShadowed.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsShadowed.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsShadowed.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsShadowed.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsWithBlockMethodParameters.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsWithNewlinesInsideTags.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsWithValueTag.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]unusedimports[\\/]InputUnusedImportsWithoutWarnings.java"/>

% grep -A 1 'UnnecessaryOkComment' checkstyle-input-suppressions.xml | grep -B 1 'unusedimports'
% grep -A 1 'UnnecessaryOkComment' checkstyle-input-suppressions.xml | grep -B 1 'unusedimports' | sed '/^--$/d' | grep -c 'UnnecessaryOkComment'

0

```
```
% grep -A 1 'UnnecessaryOkComment' checkstyle-input-suppressions.xml | grep -B 1 'redundantimport'
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]redundantimport[\\/]InputRedundantImportBug.java"/>
  <suppress id="UnnecessaryOkComment"
            files="checks[\\/]imports[\\/]redundantimport[\\/]InputRedundantImportWithoutWarnings.java"/>
% grep -A 1 'UnnecessaryOkComment' checkstyle-input-suppressions.xml | grep -B 1 'redundantimport'| grep -c 'UnnecessaryOkComment'
2

% grep -A 1 'UnnecessaryOkComment' checkstyle-input-suppressions.xml | grep -B 1 'redundantimport'
% grep -A 1 'UnnecessaryOkComment' checkstyle-input-suppressions.xml | grep -B 1 'redundantimport'| grep -c 'UnnecessaryOkComment'
0

```

### CODE REVIEW

**Comment by nrmancuso** [comment]
@relentless-pursuit please read https://github.com/checkstyle/checkstyle/wiki/PR-rules attentively, and always make sure that `mvn clean verify` is passing on your local before pushing a branch up.

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit please read https://github.com/checkstyle/checkstyle/wiki/PR-rules attentively, and always make sure that `mvn clean verify` is passing on your local before pushing a branch up.

Yes. I was stuck with the grep command as they are multiple lines. Trying to figure out how to show the output.

**Review by romani — APPROVED** [review]
ok to merge

**Comment by romani** [comment]
@nrmancuso , I think relentless-pursuit is ready to send PRs for package.

**Review by nrmancuso — APPROVED** [review]

**Comment by nrmancuso** [comment]
> @nrmancuso , I think relentless-pursuit is ready to send PRs for package.

That is fine, but I would still prefer by check to make for easier review.

**Pull request merged**
