### PR TITLE
Issue #9455: add AST example for TokenTypes.INSTANCE_INIT

### LINKED ISSUE #9455: update example of AST for TokenTypes.INSTANCE_INIT
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#INSTANCE_INIT

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #9455

Generated doc:

image

---

Command line run:

image

### CODE REVIEW

**Comment by AkMo3** [comment]
@Youssef1313 Please change `>` to `&gt;`.

**Review by romani — CHANGES_REQUESTED** [review]
I do not see INSTANCE_INIT token in AST

**Comment by Youssef1313** [comment]
My bad. Fixed it @romani .

**Comment by romani** [comment]
`[ERROR] [checkstyle] [ERROR] /Users/runner/work/1/s/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:311: Trailing whitespace is not allowed [noTrailingWhitespace]`

please fix problem, CI should be green.

**Pull request closed without merging**
