### PR TITLE
Issue #6207: Add Xpath Regression Test for OperatorWrap

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #6207: Add Xpath Regression Test for OperatorWrap

### CODE REVIEW

**Comment by Kevin222004** [comment]
I am getting the error Audit Done for file src/it/resources/org/checkstyle/suppressionxpathfilter/operatorwrap/SuppressionXpathRegressionOperatorWrapPreviousLine.java
please guide me to solve this

**Comment by rnveach** [comment]
Your error is: (https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=8007&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=1140)
````
[ERROR]   XpathRegressionOperatorWrapTest.testOperatorWrapPreviousLine:88 error message 0
expected: /SuppressionXpathRegressionOperatorWrapPreviousLine.java:5:19: '=' should be on the previous line.
but was : Audit done.
````

Your expected results do not match your actual. You will need to look into it and identify why there is the difference.

**Comment by Kevin222004** [comment]
@rnveach  Can you please give me some more guidance to solve it . I have tried a lot but still can't figure it out

**Comment by rnveach** [comment]
Start debugging `runVerifications` ( https://github.com/checkstyle/checkstyle/blob/a8ac66635e2c5a0eb70d32b4e88d0715addfb04c/src/it/java/org/checkstyle/suppressionxpathfilter/AbstractXpathTestSupport.java#L198 ) and look where the failure is coming from.
There are 4 main areas. https://github.com/checkstyle/checkstyle/blob/a8ac66635e2c5a0eb70d32b4e88d0715addfb04c/src/it/java/org/checkstyle/suppressionxpathfilter/AbstractXpathTestSupport.java#L213-L216
Which one is failing. Then look into what each does and that will help you narrow down things more on what is the fault.

**Comment by Kevin222004** [comment]
@rnveach  I have tried to debug the code and try out to figure it out and I have tried to make  various changes via the reference of  

https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap

but in violation of previous line,
 it is showing message should be on new line or Audit done

**Comment by rnveach** [comment]
Then provide more information on what you found. Which of the verify methods is it failing at. What is it trying to do at the failure.

**Comment by romani** [comment]
Please make sure you can print ast tree by CLI https://checkstyle.sourceforge.io/cmdline.html#Command_line_usage
And you played with our UI tool https://checkstyle.sourceforge.io/writingchecks.html#The_Checkstyle_SDK_Gui to deal with ast math by xpath

**Comment by Kevin222004** [comment]
@romani while running 
java -jar checkstyle-10.0-all.jar -c /sun_checks.xml MyClass.java  I am getting 



and according to documentation for while i am running command with -g it is lik 
Screenshot from 2022-03-14 18-08-03
Screenshot from 2022-03-14 18-08-31
Screenshot from 2022-03-14 18-08-40

**Comment by romani** [comment]
Please do not run validation by CLI with sun config, use config file that you use in test (single Check only), please run with xpath related options to see AST and able to match a node by xpath. If you match node by xpath you can suppress by this xpath violation

**Comment by Kevin222004** [comment]
@romani I have successfully print out the AST tree

COMPILATION_UNIT -> COMPILATION_UNIT [1:0]
|--PACKAGE_DEF -> package [1:0]
|   |--ANNOTATIONS -> ANNOTATIONS [1:45]
|   |--DOT -> . [1:45]
|   |   |--DOT -> . [1:22]
|   |   |   |--DOT -> . [1:11]
|   |   |   |   |--IDENT -> org [1:8]
|   |   |   |   `--IDENT -> checkstyle [1:12]
|   |   |   `--IDENT -> suppressionxpathfilter [1:23]
|   |   `--IDENT -> operatorwrap [1:46]
|   `--SEMI -> ; [1:58]
`--CLASS_DEF -> CLASS_DEF [3:0]
    |--MODIFIERS -> MODIFIERS [3:0]
    |   `--LITERAL_PUBLIC -> public [3:0]
    |--LITERAL_CLASS -> class [3:7]
    |--IDENT -> SuppressionXpathRegressionOperatorWrapPreviousLine [3:13]
    `--OBJBLOCK -> OBJBLOCK [3:64]
        |--LCURLY -> { [3:64]
        |--VARIABLE_DEF -> VARIABLE_DEF [4:1]
        |   |--MODIFIERS -> MODIFIERS [4:1]
        |   |--TYPE -> TYPE [4:1]
        |   |   `--LITERAL_INT -> int [4:1]
        |   |--IDENT -> b [4:5]
        |   |--ASSIGN -> = [5:3]
        |   |   `--EXPR -> EXPR [5:5]
        |   |       `--NUM_INT -> 10 [5:5]
        |   `--SEMI -> ; [5:7]
        |--VARIABLE_DEF -> VARIABLE_DEF [6:1]
        |   |--MODIFIERS -> MODIFIERS [6:1]
        |   |--TYPE -> TYPE [6:1]
        |   |   `--LITERAL_INT -> int [6:1]
        |   |--IDENT -> c [6:5]
        |   |--ASSIGN -> = [6:7]
        |   |   `--EXPR -> EXPR [7:2]
        |   |       `--NUM_INT -> 10 [7:2]
        |   `--SEMI -> ; [7:4]
        `--RCURLY -> } [8:0]

**Comment by Kevin222004** [comment]
@romani I have tried so many ways to do but I cant solve it
[ERROR]   XpathRegressionOperatorWrapTest.testOperatorWrapPreviousLine:88 error message 0
expected: /SuppressionXpathRegressionOperatorWrapPreviousLine.java:5:19: '=' should be on the previous line.
but was : Audit done.

**Comment by romani** [comment]
there was mistake in config of Check 
you copied input file from example (right way) but did not copied config of Check 
https://checkstyle.org/config_whitespace.html#OperatorWrap_Examples

I pushed right changes.
Please read attentively my changes, please do few more issues for xpath regression to practice this.

**Comment by Kevin222004** [comment]
> there was mistake in config of Check you copied input file from example (right way) but did not copied config of Check https://checkstyle.org/config_whitespace.html#OperatorWrap_Examples
> 
> I pushed right changes. Please read attentively my changes, please do few more issues for xpath regression to practice this.

@romani this is such a huge help for me(Not only for this Pull request, but in general).

**Review by romani — APPROVED** [review]

**Pull request merged**
