### PR TITLE
Issue #13893: Migrate illegaltype.xml.template to use properties temp…

### PR DESCRIPTION
**Pull request by AayushSaini101**
Related: https://github.com/checkstyle/checkstyle/issues/13893

### CODE REVIEW

**Comment by AayushSaini101** [comment]
Hi @romani @rnveach Can you please help to resolve the CI, Lincheck. is failing the logs are: 

```

----------- grep of linkcheck.html--BEGIN
Checking internal (checkstyle website) links only.
800a801
> <td><i><a href="apidocs/constant-values.html#com.puppycrawl">#com.puppycrawl</a>: doesn't exist.</i></td></tr>
1339a1341
> <td><i><a href="property_types.html#subset_of_tokens_TokenTypes">../../property_types.html#subset_of_tokens_TokenTypes</a>: doesn't exist.</i></td></tr>
------------ grep of linkcheck.html--END

```
This is the row: 
```

<tr>
              <td>memberModifiers</td>
              <td>Control whether to check only methods and fields with any of the specified modifiers. This property does not affect method calls nor method references nor record components.</td>
              <td><a href="../../property_types.html#subset of tokens TokenTypes">subset of tokens TokenTypes</a></td>
              <td><code>{}</code></td>
              <td>6.3</td>
            </tr>



```

**Comment by rnveach** [comment]
> `../../property_types.html#subset_of_tokens_TokenTypes</a>: doesn't exist.`

What is confusing about the error? It checks that links point to a valid location. Are you saying this link should be valid?

**Comment by romani** [comment]
Link should be as before `<td>subset of tokens
                <a href="../../apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html">TokenTypes</a>`

**Comment by AayushSaini101** [comment]
> Link should be as before `<td>subset of tokens <a href="../../apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html">TokenTypes</a>`

Yes, @romani Required some changes in the statement of PropertiesMacro.java

```
else if (SiteUtil.JAVADOC_TOKENS.equals(propertyName)) {
            final AbstractJavadocCheck check = (AbstractJavadocCheck) instance;
            final List<String> configurableTokens = SiteUtil
                    .getDifference(check.getAcceptableJavadocTokens(),
                            check.getRequiredJavadocTokens())
                    .stream()
                    .map(JavadocUtil::getTokenName)
                    .collect(Collectors.toList());
            sink.text("subset of javadoc tokens");
            writeTokensList(sink, configurableTokens, SiteUtil.PATH_TO_JAVADOC_TOKEN_TYPES);
        }
```

**Comment by romani** [comment]
Did not hesitate to do changes in code and push to GitHub. It will give us full context of change.

**Comment by rnveach** [comment]
@romani @AayushSaini101 This invalid link is the same as https://github.com/checkstyle/checkstyle/pull/13721 which pointed to issue https://github.com/checkstyle/checkstyle/issues/13722 . This PR isn't the only one facing this issue.

**Comment by romani** [comment]
@AayushSaini101 , is there some ability to update code to have hardcoded map/list of  modules and properties that will have description and links as it was before?
Such hack will be commented with "until https://github.com/checkstyle/checkstyle/issues/13722"

In scope of https://github.com/checkstyle/checkstyle/issues/13722 we will fix properly to avoid hardcoded

**Comment by rnveach** [comment]
We should just fix the issue instead of making things worse.

**Pull request closed without merging**
