### PR TITLE
Issue #2326: Fix reusability of JavaDoc checks

### PR DESCRIPTION
**Pull request by Vampire**

### CODE REVIEW

**Comment by romani** [comment]
tests are failing, please fix them

**Comment by Vampire** [comment]
Ah, sorry, was just the commit message. I took the ones from 6.4.1 as example, as I fixed it there initially. (It is the version used by the SonarQube plugin)
Should be ok now.

**Comment by rnveach** [comment]
@Vampire appveyor fail is because master is failing, please wait for master fix, then you'll have to rebase.

**Comment by Vampire** [comment]
Yep, this time it is because of master failing, thanks for the hint, I'll keep an eye.

**Comment by Vampire** [comment]
Ok, another try :-)

**Comment by romani** [comment]
@Vampire ,

please rebase your changes, sorry, you come up in middle of huge refactoring, please pay attention that now all resources at "com/puppycrawl/tools/checkstyle/checks/javadoc".

I am ok with functional changes. I do not see problems.
UTs changes are still under review.... need just a little more time (we try to use guava in priority to apache commons, I need to review why we still have apache commons in our dependencies).


@baratali , what is your status ?

**Comment by Vampire** [comment]
@romani On rebasing I also wanted to remove the commons-collection usage. As Guava has no OrderedMap like commons-collection, I wanted to switch to LinkedHashMap as parameter to guarantee iteration order. But your checkstyle rules prevent this. Is there any alternative to be used?
Otherwise I'd have to declare the parameter as Map and *hope* that callers use a LinkedHashMap for order guarantee.

**Comment by Vampire** [comment]
@romani I rebased now and removed the commons-collections usages. For now I just expect a Map and wrote a JavaDoc comment that it should be a LinkedHashMap if multiple files messages are put into the map. If there is another way, please tell me and I'll change it again. I also added the one-file test that @baratali suggested.

**Comment by romani** [comment]
@Vampire , thank you very mush for your time.

> Do you prefer that the test works with just that one file and my changes about being able to test with errors from multiple files reverted?

lets keep both tests, the more tests the better, and your tests are a bit different.

last required updates:
1) 
> OrderedMap --> Map

Keeping warning in Javadoc never works well - code should force engineer to do things in right way.
And we are almost done with removing dependency to commons-lang3 .
Lets look on a problem from different side - we should not demand from author of UTs order of violations and order of files. It is not a contract of Checkstyle. Lets update a bit ```protected void verify(Checker checker, File[] processedFiles, Map<String, String[]> expectedMessages)``` and store actual messages to Map<name_of_fIle,array_of_violations> and do intersection. For now we could rely on order of violations in one file.
Does it make sense ? If "yes" please do.

Reason: in UTs we need to focus on convenience and easy to read code, rather than performance.

2)
> ```Entry<String, String[]> expectedMessage```

please rename it to expectedViolations

3)
> final String[] expected

final String[] expectedMessages

4)
> final String actual

final String actualResult

**Comment by Vampire** [comment]
2-4) not relevant anymore, as the code is gone

> lets keep both tests, the more tests the better, and your tests are a bit different.

Sure, no problem, I thought so too, that's why I added the one-file test.

> Keeping warning in Javadoc never works well - code should force engineer to do things in right way.

That's exactly why I wanted to use LinkedHashMap as parameter, but your Checkstyle checks didn't allow that.

> And we are almost done with removing dependency to commons-lang3 .

I removed the dependency to it in AbstractJavadocCheckTest that was there before my changes already. It was not really helpful there anyway as the parameter is a var-arg.

> Lets look on a problem from different side - we should not demand from author of UTs order of violations and order of files. It is not a contract of Checkstyle. Lets update a bit protected void verify(Checker checker, File[] processedFiles, Map<String, String[]> expectedMessages) and store actual messages to Map and do intersection.

Did so now. I just didn't want to change the paradigm. But if you say the order should not be guaranteed, I have absolutely no problem in doing it that way.

> For now we could rely on order of violations in one file.

Could, should or have to? The current version still relies on the order of violations in one file. But it would be easy to change it so that the order within the file is unimportant too.

**Comment by Vampire** [comment]
Travis Job 5205.23 is hangig and doesn't start

**Comment by romani** [comment]
awesome ! I am almost ready to merge. 

Do you need hot-fix release 6.4.2 ? As I know Checkstyle Sonar plugin does not work with Checkstyle 6.5 and up. We usually do not do such old hotfixed, but you did great job, I could bother with non trivial release.

>Could, should or have to? The current version still relies on the order of violations in one file. 

we could. Just do NOT change this, keep it as is. UTs could rely on order of violations inside a file. We will change this as we come to multi-thread approach of validation, in future.

1)
> import static com.google.common.collect.Maps.difference;
import static com.google.common.collect.Maps.filterValues;

please avoid static imports usage for guava, we are ok to junit static imports.

2)
> assertTrue(message.toString(), missingVio ................

please make it multi-line (at least 2 lines).



@mkordas , do you see any problems with this such update ?

**Comment by Vampire** [comment]
> Do you need hot-fix release 6.4.2 ? As I know Checkstyle Sonar plugin does not work with Checkstyle 6.5 and up. We usually do not do such old hotfixed, but you did great job, I could bother with non trivial release.

Well, depends on whether the SQ guys would create a release with it.
I personally do not hardly depen on it.
I originally developed the fix on the 6.4.1 tag and patched the SQ Checkstyle Plugin with my modified version, so that our analysis works again.

> please avoid static imports usage for guava, we are ok to junit static imports.

As you wish, is removed

> please make it multi-line (at least 2 lines).

Done

**Comment by romani** [comment]
@mkordas , I ma ready to merge, please take a glance. I will do merge tomorrow.

**Comment by mkordas** [comment]
@romani - changes look good for me.

Just one general question - is making the field non-final the only way to fix the issue? Maybe there is a way to keep one instance of `DescriptiveErrorListener`, but invoke it in such way it cannot has any stale state. @Vampire, what do you think?

**Comment by romani** [comment]
merged as FF.

> is making the field non-final the only way to fix the issue? 

we moved instance creation to each Javadoc parsing processing.

> Maybe there is a way to keep one instance of DescriptiveErrorListener, but invoke it in such way it cannot has any stale state

lets think about this during Javadoc performance optimization. Functional changes are going forward.

**Comment by Vampire** [comment]
@mkordas, @romani: Sure, would be no problem. Just introduce a "reset" method that sets offset to "0" and errorMessage to "null", then call the reset method instead of creating a new instance.

**Pull request closed without merging**
