### PR TITLE
Issue #2989: SummaryJavadocCheck period fix

### PR DESCRIPTION
**Pull request by ybbpgfjtey**
[2989](https://github.com/checkstyle/checkstyle/issues/2989)
Fix the issue, and fix other bugs:
- Some false negative. ~~fixed~~

```
E:\test>type config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="SummaryJavadoc">
        </module>
    </module>
</module>

E:\test>type TestSummaryJavadocFalseNegative.java
public class TestSummaryJavadocFalseNegative extends Exception {

    /**
     * JAXB 1.0 only default validation event handler
     */
    public static final byte NUL = 0;

    /**
     * @throws Exception if an error occurs.
     */
    public void foo1() throws Exception {

    }

    /**
      * @return 1.
      */
    public int foo2(){
        return 1;
    }

    /**
      * <a href="mailto:vlad@htmlbook.ru"></a>
      */
    public void foo3() {

    }
}

E:\test>java -jar checkstyle-6.16.1-all.jar -c config.xml TestSummaryJavadocFalseNegative.java
Starting audit...
Audit done.
```

qq 20160308003237
- One false positive. ~~fixed~~

```
E:\test>type config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="SummaryJavadoc">
        </module>
    </module>
</module>

E:\test>type TestSummaryJavadocFalsePositive.java
public class TestSummaryJavadocFalsePositive {

    /** 
      * {@inheritDoc} */
    public String toString(){
        return "";
    }
}

E:\test>java -jar checkstyle-6.16.1-all.jar -c config.xml TestSummaryJavadocFalsePositive.java
Starting audit...
[ERROR] E:\test\TestSummaryJavadocFalsePositive.java:3: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
Audit done.
Checkstyle ends with 1 errors.
```
- One weird behavior. **Keep the same way with JDK**

```
E:\test>type config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="SummaryJavadoc">
        </module>
    </module>
</module>

E:\test>type TestSummaryJavadocWeird.java
public class TestSummaryJavadocWeird {
    /** 
     *  A {@code Foo.  Foo}
     */
    public void foo(){

    }

}

E:\test>java -jar checkstyle-6.16.1-all.jar -c config.xml TestSummaryJavadocWeird.java
Starting audit...
Audit done.
```

qq 20160308004408

### CODE REVIEW

**Comment by ybbpgfjtey** [comment]
It is a little bit weird.
Some CIs reported:
```
SummaryJavadocTest.testIncorrect:74->BaseCheckTestSupport.verify:111->BaseCheckTestSupport.verify:139 error message 0 expected:<...ryJavaDocCheck.java:[14]: First sentence of ...> but was:<...ryJavaDocCheck.java:[9]: First sentence of ...>
```

but actually it is [9].
[link](https://github.com/checkstyle/checkstyle/commit/1ef8eb22b8cf55b63612281d99c533d913aeab2e#diff-4ee920a468c047a2df4f0096396dc569L71)

**Comment by romani** [comment]
impressive update :) , but you try to fix too much in the same issue.
Lets split that to few issues (users also need to know that you fixed number of problems , we use fixed issue in generation of release notes) and fix them by separate PRs and separate testing.

> What should I do?
Rewrite javadoc for that class, or just change my code to tolerance this?

please do separate issue, and will discuss it separately.
Please keep in this PR update only for unicode period. It is ok if some other bugs will stay in code. You will fix them by other PRs.
CIs has to be green.

**Comment by romani** [comment]
@ybbpgfjtey , please follow my recommendations it will ease code review and code acceptance.

**Comment by ybbpgfjtey** [comment]
@romani 
Sorry, I am too busy recently.
I'd almost done. 
There's only one last thing here:
```
 /** Leaves while, do, for, if, try, ? (in ?::) or switch. */
```
The question mark will be considered as a sentence breaker by javadoc.

**Comment by ybbpgfjtey** [comment]
@romani 
Cis reported these two errors:
# 1 
```
SummaryJavadocTest.testCorrect:49->BaseCheckTestSupport.verify:111->BaseCheckTestSupport.verify:151 unexpected output: C:\projects\checkstyle\src\it\resources\com\google\checkstyle\test\chapter7javadoc\rule72thesummaryfragment\InputCorrectSummaryJavaDocCheck.java:32: First sentence of Javadoc is incomplete (period is missing) or not present. expected:<0> but was:<1>
···
but InputCorrectSummaryJavaDocCheck.java:32 is not a javadoc start line.
You can see it [here](https://github.com/ybbpgfjtey/checkstyle/blob/issue_2989/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputCorrectSummaryJavaDoc.java#L32)

# 2
```
SummaryJavadocTest.testIncorrect:74->BaseCheckTestSupport.verify:111->BaseCheckTestSupport.verify:139 error message 0 expected:<...ryJavaDocCheck.java:[14]: First sentence of ...> but was:<...ryJavaDocCheck.java:[9]: First sentence of ...>
```
but actually it is [9].
You can see it [here](https://github.com/ybbpgfjtey/checkstyle/blob/issue_2989/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java#L72)


Is it because of I can not change code in "src/test/resources"?

**Comment by rnveach** [comment]
@ybbpgfjtey 

1)
You are looking at the wrong file. Be careful of files with similar names in different packages.
This is the file the error is reporting: https://github.com/checkstyle/checkstyle/blob/eeec3dc1d23916462560403a27a4ae94260d61f3/src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule72thesummaryfragment/InputCorrectSummaryJavaDocCheck.java#L32

You will have to change the files/tests in "src/test" to correct the errors so travis turns green.

**Comment by ybbpgfjtey** [comment]
@rnveach 
Thank you. 
But what is that test working for?
Same class, same method, but diffrent folder.

**Comment by rnveach** [comment]
All tests are verifying that Check works as expected under various conditions. This shows us the Check will have a expected behavior in a certain situation and new changes don't break old behavior that is valid.
The "IT" folder is showing and proving that our checks match only Google's documented style. We are limiting ourselves only to Google's style.
The "Test" folder shows all behavior of CheckStyle's checks and options. These can be similar to Google, slightly different, or complete opposite. The sky is the limit here.

**Comment by ybbpgfjtey** [comment]
@rnveach 
OK, I got it.

**Comment by rnveach** [comment]
@ybbpgfjtey 
> But I can not pass most tests in my computer, Win 10, because of something like line separator or so.

Have you tried setting "autocrlf" to "true" for the git repository. (Don't forget to hard reset the entire workspace if you turn this on).
If that doesn't work, then you can always turn on travis for your personal fork and run travis there before making the PR for the main repository.

**Comment by ybbpgfjtey** [comment]
@rnveach 
No, I'v turned "autocrlf" down.
How to turn on travis for my personal fork?

**Comment by ybbpgfjtey** [comment]
@romani 
Is it OK? or if there's something I should do?

**Comment by romani** [comment]
@ybbpgfjtey , thanks a lot for your fixes. I will come close to your PR in next few days, sorry for delay.

I still do not see how you split fixes to separete issues as i requested few days ago, but will review this PR again

**Comment by ybbpgfjtey** [comment]
@romani 
I hadn't split fixes, because it is very tricky to use javadoc's api to analyse sentence, and leaves bugs in it.

**Comment by romani** [comment]
as you try to keep all in one - you over complicate acceptance process as you have to do full retest of Check.

1)
> One weird behavior. Keep the same way with JDK

I do not want to fix it back ones jdk resolve it.
I do not not like this update. Please open bug on JDK and make sure that chekcstyle do report violation on such code. 

2)
As you decided to go by one Issue/PR - please squash all commits in one and be ready for detailed codereview 

3) please start testing of your changes on real code. Please use checkstyle-tester project - https://github.com/checkstyle/contribution/tree/master/checkstyle-tester to generate HTML reports over big opensource projects.  Please make sure there are no exceptions happening. Please share report at github.io , all instructions are in README file.

4) as a separate report, please make diff report https://github.com/checkstyle/contribution/tree/master/patch-diff-report-tool for Guava and openjdk(7 or 8 or 9) projects. Make sure that all difference in behaviour are smth you actually fixed. Please share report at github.io .

**Comment by ybbpgfjtey** [comment]
1) 
I will try to fix it;
2)
done;
3)
I will try to do this;
4)
I will try to do this;
5)
I don't get it. 
It is not that we can't use <a> in first sentence.
This is illegal:
```
<a href="mailto:vlad@htmlbook.ru"></a>
```
This is legal(one period after it):
```
<a href="mailto:vlad@htmlbook.ru"></a>.
```
6)
Is it means I shall change xdoc?
7)
> else if (firstSentence.endsWith(period)) {
> I do not like this condition as period is smth that make a first sentence and we already used it.

I write this because we get first sentence, but that first sentence may end with other sentence delimiter.
8)
>   final List<DetailNode> stack = new LinkedList<>();
> stack vs List. So what is it ?
It is a stack to traverse ast tree, I will change it's name to make it more understandable.
9)
I will try to change it's algorithm, and add more comment to explain it.

**Comment by romani** [comment]
> Is it means I shall change xdoc?

yes, please do. To show your work on our web site.

> I don't get it. 

check do valitation of two cases:
- first sentence is present 
- first sentence doe snot have some pattern.

but in javadoc/xdoc we described only one validation (second)

**Comment by ybbpgfjtey** [comment]
> but that first sentence may end with other sentence delimiter.
> please provide example for this, it is not obvious.

```
Sentence one, end with a exclamation mark ! Sentence two.
```
method `getFirstSentece` will get `Sentence one, end with a exclamation mark !` , and it does not  end with a period. But this one will be used as *first sentence in JDK*.



If we go straight to get something that end with a period (i.e. : `Sentence one, end with a exclamation mark ! Sentence two.`), then that may not be the real first sentence. It is a false negative.

**Comment by rnveach** [comment]
@ybbpgfjtey
> > module-info.java:30:1: unexpected token: module

> What does it means?

Your branch is based off an old master. Please rebase your branch off the latest master and the circleci issue should go away.

**Comment by romani** [comment]
@ybbpgfjtey , please post as comment to PR when you finish all points that i raised from "I will " to "done". I will continue code review.
Please let me know if smth is not clear and you need some help.

**Comment by ybbpgfjtey** [comment]
@romani 
Thank you, I'm almost done.
patch-diff-report-tool has some bugs.
1. can't build without argument: `-Dcheckstyle.skip=true`
2. can't execute, errors:
```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 31: XMLDiffGen_report_2016.03.30_21:16:11
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
        at com.github.checkstyle.Main.parseCliToPojo(Main.java:207)
        at com.github.checkstyle.Main.main(Main.java:134)
```
until I changed line 207 of `com.github.checkstyle.Main` to a static path.

**Comment by romani** [comment]
> patch-diff-report-tool has some bugs.

please do not hesitate to report any problem to https://github.com/checkstyle/contribution/issues .
Please make sure that you use latest version of this tool.

> can't build without argument: -Dcheckstyle.skip=true

please report issue with steps to reproduce to https://github.com/checkstyle/contribution/issues , we are eager to help.
I presume you have problem with https://github.com/checkstyle/contribution/tree/master/checkstyle-tester , I need details to help you.

> It is illegal to have ':' in windows path.

sorry, thanks for pointing to the problem. Please update to "_" and send fix as PR.

> checkstyle tester executed too slow, cost me more than 1 hour

please show me your command and config. Please make sure that you run only your Check.
Unfortunately javadooc Checks that are based on ANTLR are slow. see https://github.com/checkstyle/checkstyle/pull/3055. Please try to generate report with smaller amount of projects. 

> Should use multi thread.

We are single thread tool by design :( . Mutithread mode is future plan.

**Comment by ybbpgfjtey** [comment]
Everything's done.

most of the diffrent 
[Uploading diff.zip…]()
：
#1 url
···
/**
 * Used to avoid http://bugs.sun.com/view_bug.do?bug_id=6558557
 */
···
#2 version number
```
/**
 * @since 11.0
 */
```

#3 first sentence end with other period
```
/**
 * The "base64url" encoding specified by <a
 * href="http://tools.ietf.org/html/rfc4648#section-5">RFC 4648 section 5</a>, Base 64 Encoding
 * with URL and Filename Safe Alphabet, also sometimes referred to as the "web safe Base64."
 * (This is the same as the base 64 encoding with URL and filename safe alphabet from <a
 * href="http://tools.ietf.org/html/rfc3548#section-4">RFC 3548</a>.)
 *
 * <p>The character {@code '='} is used for padding, but can be {@linkplain #omitPadding()
 * omitted} or {@linkplain #withPadChar(char) replaced}.
 *
 * <p>No line feeds are added by default, as per <a
 * href="http://tools.ietf.org/html/rfc4648#section-3.1"> RFC 4648 section 3.1</a>, Line Feeds in
 * Encoded Data. Line feeds may be added using {@link #withSeparator(String, int)}.
 */

/**
  * TODO(user):  This was copied verbatim from Striped64.java... standardize this?
  */
```


#4 not a period dot
```
/**
 * @see #expectContents(java.util.Collection)
 *
 * @param elements expected contents of {@link #container}
 */
```

**Comment by romani** [comment]
thanks a lot for update, but .....
please reply "Done"  to EACH point that I raised.

You missed:
`2)
As you decided to go by one Issue/PR - please squash all commits in one and be ready for detailed codereview . Please move all changed in javadoc in checkstyle code to separate PR to let me merge it first and keep in this PR changes only for code to ease code review.
`
All formatting changes (spaces) should be separated in separate commit.

Please publish diff report to github.io , as I will review it from mobile phone and other maintainers could look at results too.

**Comment by ybbpgfjtey** [comment]
> You missed:

Is it means I should squash all commits in one?


> Please publish diff report to github.io

I'v already published diff report:
[diff.zip](https://github.com/checkstyle/checkstyle/files/200956/diff.zip)

**Comment by romani** [comment]
> Is it means I should squash all commits in one?

Please move all changed in javadoc in checkstyle code to separate PR to let me merge it first.
Functional changes should be separated from all other changes.

> I'v already published diff report

https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/README.md , please search for "DEPLOY: " and please follow instructions.

**Comment by romani** [comment]
@ybbpgfjtey ,

it is good to mention in this issue http://checkstyle.sourceforge.net/config_javadoc.html#JavadocStyle
property "endOfSentenceFormat". Looks like we did big mistake when we introduced `period` property as String, we need to make it RegExp as it is in JavadocStyle. This will allow user define what symbol should be allowed at the end of sentence.

code review (please reply as "done" for each point): 

1)
> `Javadoc summary sentence</a> does not contain phrases that are not recommended to use.`

should be "Javadoc summary sentence</a> exists , finish with period symbol and does not contain phrases that are not recommended to use."
Please update xdoc file too.

2)
>
```
        return new int[] {
            JavadocTokenTypes.JAVADOC,
        };
```

please make it single line as it is in `public int[] getAcceptableTokens() {`

4)
> senetence breaker

sentence breaker

5)
> firstSentence = trimAndRemoveTailAsterisks(sentences.substring(0, firstBreakIndex));

why we need to do trimAndRemoveTailAsterisks one more time ? and not do this in another part of IF.

6)
> `final Deque<DetailNode> astVisitor `

it is not  a Visitor it is 'nodesToVisit'

7)
>
```
                final DetailNode[] children = node.getChildren();
                for (int i = children.length - 1; i >= 1; i--) {
                    astVisitor.addFirst(children[i]);
                }
```

happens in code twice, very similar code. Please make a static function from it.

8)
> `result.append(node.getText().replace('.', '#').replace('!', '#').replace('?', '#'));`

I do not like this, you change javadoc to get first sentence, but you do not restore original text when you send it matching method.

9)
http://www.oracle.com/technetwork/articles/java/index-137868.html#firstsentence

>This sentence ends at the first period that is followed by a blank, tab, or line terminator, or at the first tag (as defined below)

Why we consider text inside tags (inline tags) ?

10)
> // For compatbility, accept text in javadoc tag.

for compatibility with what ?

11)
> javadocText = CharMatcher.WHITESPACE.trimAndCollapseFrom(javadocText, ' ');

Do you know why `trimAndCollapseFrom` is required ?
http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/CharMatcher.html#trimAndCollapseFrom%28java.lang.CharSequence,%20char%29
we need to deliver to match processing line as is without any collapsing.

**Comment by ybbpgfjtey** [comment]
Sorry, my father is ill, I will finish this later.

**Comment by romani** [comment]
take your time.

**Comment by romani** [comment]
@ybbpgfjtey, we merged #3040, so you can use CLI to build AST Tree for java_javadoc. It should help during development.

**Comment by romani** [comment]
@ybbpgfjtey , ping.

**Comment by ybbpgfjtey** [comment]
@romani  lagging int hospital.

**Comment by romani** [comment]
@ybbpgfjtey , ping.

**Comment by romani** [comment]
@ybbpgfjtey , is there any chance to continue ?
If you do not have time please let me know, smb else will finish your work. I just do not want to keep this issue and PR blocked by you.

**Comment by romani** [comment]
PR become unmanageable and complete mess.
Some problems were moved to separate issues .

PR is closed as incomplete.

**Pull request closed without merging**
