### PR TITLE
Issue #6207: Added Xpath IT regression test for StaticVariableName

### PR DESCRIPTION
**Pull request by AayushSaini101**
Related: https://github.com/checkstyle/checkstyle/issues/6207

### CODE REVIEW

**Comment by AayushSaini101** [comment]
Tried to Pass all CI: https://github.com/checkstyle/checkstyle/pull/13956

**Comment by AayushSaini101** [comment]
@romani Please check this

**Review by romani — APPROVED** [review]
Ok to merge

**Review by nrmancuso — CHANGES_REQUESTED** [review]
> Tried to Pass all CI: #13956

The commit in this PR does not have the same SHA as the referenced PR. @AayushSaini101 we need to see all CI passing in each PR; please fix your account or use the other account in the referenced PR to make contributions.

**Comment by romani** [comment]
moved t ohttps://github.com/checkstyle/checkstyle/pull/14074

**Pull request closed without merging**
