### PR TITLE
Sections of code should not be "commented out". Issue #46

### PR DESCRIPTION
**Pull request by sabaka**
Comments with code examples removed.

### CODE REVIEW

**Comment by romani** [comment]
@sabaka , please put there a link to mail-list post .

**Comment by sabaka** [comment]
https://groups.google.com/forum/#!topic/sonarqube/e5xnjMxnz04

We can close it, I suppose.

**Comment by romani** [comment]
I will request Sonar team to suppress it a bit later, please send me detailed report of what to suppress please make it in a from convenient for sonar team

**Comment by sabaka** [comment]
@romani they have done it already. Link to document with list of violations to suppress has been shared with you.

**Pull request closed without merging**
