### PR TITLE
Issue #14937: Migrated section 4.8.4.2 Fall-through Commented to chapter wise testing

### PR DESCRIPTION
**Pull request by Zopsss**
#14937

### CODE REVIEW

**Comment by Zopsss** [comment]
failing Ci: https://checkstyle.semaphoreci.com/jobs/40445541-cbb5-4ad7-8430-46cb15fdc2c4

not concerned with the PR

**Review by romani — APPROVED** [review]
ok to merge

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by rdiachenko** [comment]
Rebased

**Pull request merged**
