### PR TITLE
minor: add java compilation version comment and fix example

### PR DESCRIPTION
**Pull request by stoyanK7**
I saw that it is version 14 from https://rules.sonarsource.com/java/RSPEC-6208
> In Java 14 there is a new way to write cases in Switch Statement and Expression when the same action should be performed for different cases.

### CODE REVIEW

**Comment by nrmancuso** [comment]
I do not see this input file at https://app.circleci.com/pipelines/github/checkstyle/checkstyle/18996/workflows/7027ed9d-b216-40a8-84a0-6275e6557a13/jobs/311362/parallel-runs/0/steps/0-102, unless I am missing something. 

However, when I check out this branch, I see that it is up to date, and grep from script shows this file:
```
➜  checkstyle git:(pull-13248) ✗ git log -9 --oneline | cat                             
8a0a616d4 minor: add java compilation version comment and fix example
1faa04cfb Issue #13100: Create tests from LambdaBodyLength xdoc examples
38a460553 Issue #13100: Create tests from NoWhitespaceBeforeCaseDefaultColon xdoc examples
568e860c7 Issue #13100: Create tests from SeparatorWrap xdoc examples
d67024a83 Issue #13100: Create tests from OperatorWrap xdoc examples
1d5223d0f Pull #13176: Fail linkcheck on internal broken site link
607368774 Issue #13100: Create tests from FileTabCharacter xdoc examples
307ff3ff7 infra: add compilation of non-compilable examples
9cf9d7985 Issue #13100: Create tests from NoWhitespaceBefore xdoc examples
➜  checkstyle git:(pull-13248) ✗ grep -Rl --include='*.java' ': Compilable with Java14' \
        src/test/resources-noncompilable \
        src/xdocs-examples/resources-noncompilable | grep Example1
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/Example1.java

```

**Comment by stoyanK7** [comment]
> I do not see this input file at https://app.circleci.com/pipelines/github/checkstyle/checkstyle/18996/workflows/7027ed9d-b216-40a8-84a0-6275e6557a13/jobs/311362/parallel-runs/0/steps/0-102, unless I am missing something.

@nrmancuso Is this a run from the PR where you extended the javac validation job?

**Comment by nrmancuso** [comment]
No, it is from this PR :)

**Comment by stoyanK7** [comment]
Why the failure at https://app.circleci.com/pipelines/github/checkstyle/checkstyle/18994/workflows/5e070380-742d-4283-9741-711af7d1c255/jobs/311291?invite=true#step-102-65 then, but file is not shown here..
```
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/Example1.java:26: error: : expected
      case 3, 4
            ^
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/Example1.java:28: error: : expected
      case 4,
            ^
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/Example1.java:36: error: : expected
      case MONDAY, FRIDAY, SUNDAY: System.out.println("  6"); break;
                 ^
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/Example1.java:36: error: not a statement
      case MONDAY, FRIDAY, SUNDAY: System.out.println("  6"); break;
                   ^
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/Example1.java:36: error: ';' expected
      case MONDAY, FRIDAY, SUNDAY: System.out.println("  6"); break;
                         ^
5 errors

Exited with code exit status 1
```

**Comment by nrmancuso** [comment]
javac14 from master branch: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/18999/workflows/07b01809-2cfb-42cf-9473-8311298c6307/jobs/311492

**Comment by nrmancuso** [comment]
Ok, case constant came out of preview in Java 14: https://openjdk.org/jeps/361, so file is compiled but we do not see `....java uses preview language features.`. We are good here :) @stoyanK7 sorry for the confusion.

**Comment by stoyanK7** [comment]
@nrmancuso No worries. Point out such things because this area is still unknown to me.

**Pull request merged**
