### PR TITLE
Issue #903: Skip type annotations from validation of ModifierOrderCheck (part 2)

### PR DESCRIPTION
**Pull request by MEZk**
@romani 

#903

In accordance with [jsr308](http://types.cs.washington.edu/jsr308/specification/java-annotation-design.html) source locations for annotations on types that follow modifiers are:

1) [Method return types](https://github.com/MEZk/checkstyle/blob/8e77474df0d76db7049ff60700856f485c3b1f2f/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/InputTypeAnnotations.java#L87).
2) [Method and constructor parameter definitions](https://github.com/MEZk/checkstyle/blob/8e77474df0d76db7049ff60700856f485c3b1f2f/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/InputTypeAnnotations.java#L51).
3) [Fields definitions] (https://github.com/MEZk/checkstyle/blob/8e77474df0d76db7049ff60700856f485c3b1f2f/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/InputTypeAnnotations.java#L16).
4) [Constructor declarations](https://github.com/MEZk/checkstyle/blob/8e77474df0d76db7049ff60700856f485c3b1f2f/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/InputTypeAnnotations.java#L105).

Nevertheless, there are a few nuances:

* Type annotations cannot be applied to void, for example:

````java
public class MyClass {

// public @TypeAnnotation void foo() {} <-- compile time error

    @Target({
        ElementType.FIELD, ElementType.LOCAL_VARIABLE, ElementType.PARAMETER,
        ElementType.TYPE_PARAMETER, ElementType.TYPE_USE})
    @interface TypeAnnotation {
    }
}
````

* Annotation can precede 'void' if it is an annotation on method, for example:

````java
public class MyClass2 {
    public @MethodAnnotation void foo() {} // violation!!!
    @MethodAnnotation public void foo() {} // correct order.
    @interface MethodAnnotation { }
}
````

That is why if it is annotation on void type, we rely on javac, if it is annotation on method which precedes 'void' and it breaks modifier order, the check will rise violation, as it is shown in the example.

@pniederw
Please, take a look.

### CODE REVIEW

**Comment by romani** [comment]
>  if it is annotation on method which precedes 'void' and it breaks modifier order, the check will rise violation, as it is shown in the example.

correct.

**Comment by romani** [comment]
code is ok, I am ready to merge.

please provide diff reports for few projects : guava, ..... .

**Comment by MEZk** [comment]
@romani 
Fix was tested on the following projects:
1) checkstyle
2) sevntu-checkstyle
3) guava
4) hibernate
5) spring

[Reports](http://mezk.github.io/ModifierOrderReports/result/site.html).

**Comment by romani** [comment]
merged as FF

**Comment by pniederw** [comment]
@MEZk This resolved my problem. Thanks!

**Pull request closed without merging**
