### PR TITLE
increased coverage in class DesignForExtensionCheck, #1009

### PR DESCRIPTION
**Pull request by Vladlis**
also fixed testGetRequiredTokens() methods in the package

### CODE REVIEW

**Comment by romani** [comment]
please split fix for getRequiredToken and 100% coverage to different commits(different PR is also OK, but not strictly required), with appropriate messages.

as you did 100% for a Check please remove appropriate line in pom.xml for cobertura configuration, as java file got 100% exclusion is not required any more, eventually there will be no exclusions for 100% rule.

**Comment by Vladlis** [comment]
done

**Comment by romani** [comment]
please rebase your changes on latest code, sorry for caused inconvenience.

**Comment by Vladlis** [comment]
done

**Comment by romani** [comment]
merged

**Pull request merged**
