### PR TITLE
Issue #9527: update MissingJavadocTypeCheckTest to use unique Input file

### PR DESCRIPTION
**Pull request by CryptoSingh1337**
Closes: #9527
Made some changes in existing unit tests, added unique input file for each unit tests in MissingJavadocTypeCheckTest

### CODE REVIEW

**Comment by CryptoSingh1337** [comment]
@romani @pbludov @nmancus1 please review this.

**Comment by CryptoSingh1337** [comment]
@romani @pbludov @nmancus1 @strkkk please review this.

**Comment by CryptoSingh1337** [comment]
@romani please review this.

**Comment by CryptoSingh1337** [comment]
@romani @pbludov @nmancus1 @strkkk please review this.

**Review by romani — APPROVED** [review]
Remove items from suppression same as done at https://github.com/checkstyle/checkstyle/commit/4c4d6f8678ded8e25f3f7c70395f75dbb99be359

**Review by romani — CHANGES_REQUESTED** [review]
See above

**Comment by CryptoSingh1337** [comment]
@romani I have to remove only those files which I have changed from suppression. Am I right?

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
Yes

**Pull request merged**
