### PR TITLE
Issue #6207: Add Xpath Regression Test for EmptyBlock

### PR DESCRIPTION
**Pull request by kthirano**
Partial for Issue: #6207
Add xpath regression test for EmptyBlock

### CODE REVIEW

**Comment by kthirano** [comment]
```
mvn clean verify
```
failed at code coverage, though we only added test cases. Is there a good fix?

**Comment by angelsjiang** [comment]
Hello! Just to clarify the situation a bit more, when @kthirano forked the checkstyle repo, cloned, checked out branch, made some changes, and tried to run `mvn clean verify`, it kept failing at coverage test ratio not meeting the expected ratio 0.98, but he got 0.97 instead. However, when I and @cwjoshuak cloned his forked repo and ran `mvn clean verify` with his new changes, the project was built successfully both times, and we did not fail at coverage test at all.
We were very curious what might been the problem, could you give us some clue?
(fyi we worked together as a group)

**Comment by romani** [comment]
@kthirano , please remove second commit from your PR, there should be only one commit in this PR.

**Comment by romani** [comment]
GitHub, rebase

**Comment by rnveach** [comment]
I rebased the branch and fixed the errors I saw.

**Review by romani — APPROVED** [review]

**Pull request merged**
