### PR TITLE
Issue #5832: extend examples for CatchParameterName

### PR DESCRIPTION
**Pull request by jack870131**

### CODE REVIEW

**Comment by romani** [comment]
@jack870131 , please review CIs failures and resolve them

**Comment by jack870131** [comment]
I don't know why no matter what I add to the documentation. It would report the error on mvn verify

**Comment by rnveach** [comment]
>  It would report the error on mvn verify.

What is the error? Please provide us as much details as possible.

**Comment by jack870131** [comment]
Such as the error like this:

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.125 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest
[ERROR] testAllCheckSectionJavaDocs(com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest)  Time elapsed: 0.125 s  <<< ERROR!
java.lang.Error: Error was thrown while processing src\main\java\com\puppycrawl\tools\checkstyle\checks\naming\CatchParameterNameCheck.java
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.examineCheckSection(XdocsJavaDocsTest.java:156)
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.testAllCheckSectionJavaDocs(XdocsJavaDocsTest.java:129)
Caused by: org.junit.ComparisonFailure: 
CatchParameterName's class-level JavaDoc expected:<...t;/module>
</pre>[
<p>
The following example demonstrates how the check validates parameter names conform to a format specified by the format property
</p>
<p>
Configuration:
</p>
<pre>
<module name="CatchParameterName">
  <property name="format" value="^[a-z][a-zA-Z0-9]+$"/>
</module>
</pre>
<p>
Code example:
</p>
<pre>
public void test(String s1, int num, char[] charArray) { // OK
  ...
}
</pre>] @since 6.14> but was:<...t;/module>
</pre>[] @since 6.14>
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.examineCheckSection(XdocsJavaDocsTest.java:156)
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.testAllCheckSectionJavaDocs(XdocsJavaDocsTest.java:129)

No matter how I change the content in the check documentation (even I copied and pasted others form who have successfully pull request), mvn verify always told me that I got this kind of error. I am a freshman to checkstyle. Could you please help me with that please. I'll appreciate that.

**Comment by rnveach** [comment]
> XdocsJavaDocsTest
> CatchParameterName's class-level JavaDoc expected ...

Any changes you make to the XML file has to be made to the Java file that the text is associated to. The 2 have to be kept in synch. So you need to update the CatchParameterNameCheck file.

**Pull request closed without merging**
