### PR TITLE
Fix AvoidEscapedUnicodeCharacters Check in Checkstyle Code. #945

### PR DESCRIPTION
**Pull request by Bhavik3**

### CODE REVIEW

**Comment by Bhavik3** [comment]
I can't think of sentence for the reason of that suppression.

**Comment by romani** [comment]
"all disallowed characters are stored there", please also make suppression to whole file (not only a line)

**Comment by Bhavik3** [comment]
Done

**Comment by romani** [comment]
please put extension to name of the file in suppression to be exact

**Comment by Bhavik3** [comment]
done

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
