### PR TITLE
Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 6

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 6

covering 
https://github.com/checkstyle/checkstyle/blob/81448ea434cda883b748d3d2c77b2f58a8b22bbe/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L111-L118

### CODE REVIEW

**Comment by Kevin222004** [comment]
GitHub, generate report

**Comment by Kevin222004** [comment]
@rdiachenko please review this as well

**Review by romani — APPROVED** [review]
as where is no regression - lets remove.

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by romani** [comment]
@rdiachenko , let's keep @Vyom-Yadav as mandatory reviewer, he has big exposure to pitest fixes before.
As we balance our knowledge and level of quality and consideration between us, we can probably skip all-mrentors reviews.
But for  first few weeks let's use 3 review.

**Pull request merged**
