### PR TITLE
Issue #10197: Updated inputs for CovariantEqualsCheckTest

### LINKED ISSUE #10197: Update inputs for CovariantEqualsCheckTest
Child of #10080

### PR DESCRIPTION
**Pull request by shashwatj07**
Resolves #10197

### CODE REVIEW

**Comment by timurt** [comment]
fix conflicts

**Comment by shashwatj07** [comment]
> fix conflicts

done

**Comment by shashwatj07** [comment]
Github, rebase

**Comment by timurt** [comment]
fix conflicts

**Comment by shashwatj07** [comment]
> fix conflicts

done

**Pull request merged**
