### PR TITLE
Issue #11163: Enforced file size on AbstractJavadocPosition

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Part of #11163 
Enforced file size on AbstractJavadocPosition.
The decided file size limit was 120 and I have implemented the same.

Part of #13213 
While modifying InputAbstractJavadocPosition.java , I noticed that there was an unnecessary '//ok' comment which I removed as a part of the commit. Hope that is fine.

### CODE REVIEW

**Comment by MANISH-K-07** [comment]
One ci for this PR is continuously failing. It is because of the java version that is being used by maven. I have tried changing path to java v17 multiple times but I am not sure why an older version is being detected. All other checks have passed, it would be great if I could get some help regarding this check : 
https://circleci.com/gh/checkstyle/checkstyle/475914

**Comment by MANISH-K-07** [comment]
Hey!!
_The failing check is ci/circleci: sonarqube_
The jdk being used for analysis is v11.0.20.1 while sonarcloud is only accepting v17 or later.
Correct me if I am wrong, Maybe this issue can be resolved by updating the jdk version. If yes, I would love to work on this issue under your guidance and resolve it as soon as possible!

**Comment by romani** [comment]
Please rebase to resolve conflict.

We will ignore sonar  until we migrate to jdk17

**Comment by romani** [comment]
Single commit always please.

**Comment by MANISH-K-07** [comment]
Sorry .. I am actually still working on rebasing it.
Will convert the PR into draft until done.

**Pull request closed without merging**
