### PR TITLE
Specify violation messages in input files for AnnotationLocationCheck

### PR DESCRIPTION
**Pull request by Shaman20**
Fixes Issue for #11214 

Hey I got this error while running mvn clean verify I don't understand what it means. Could you please help me on this

image

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
> Fixes Issue for #11214
> 
> Hey I got this error while running mvn clean verify I don't understand what it means. Could you please help me on this
> 
> image

@Shaman20 These errors tell that the file is expected to be empty which means after modifying the code, what you are expecting is the file to be empty, and` but was` is the section which checkstyle is informing you that these are the errors and checkstyle is not expecting the file to be empty.

It means that you have to investigate that were are the errors and specify a violation message at that place.

**Comment by Shaman20** [comment]
> > Fixes Issue for #11214
> > Hey I got this error while running mvn clean verify I don't understand what it means. Could you please help me on this
> > image
> 
> @Shaman20 These errors tell that the file is expected to be empty which means after modifying the code, what you are expecting is the file to be empty (no violations), and `but was` is the section which checkstyle is informing you that these are the errors and checkstyle is not expecting the file to be empty.
> 
> It means that you have to investigate where are the errors and specify a violation message at that place.

Hey I added the violation message only where checkstyle threw error. But when I ran mvn -e clean verify, it told me to add violation in the above line as well which wasn't told by checkstyle. But previously the error told me to do the other way around.
Should I do that?..

image

**Comment by Rahulkhinchi03** [comment]
@Shaman20 Please check other merged PR for the same issue. We have a lot of other PR already merged on this Issue with different checks. You can refer to those and get some understanding.

You can find them here in the comments: https://github.com/checkstyle/checkstyle/issues/11214

**Comment by Shaman20** [comment]
@Rahulkhinchi03 Hey I am not sure on how to resolve the error asked me to to maintain the regex pattern but I'm not sure about it. Could you please help

image

**Comment by Shaman20** [comment]
@Rahulkhinchi03 Can I check different for different violation of the same issue and change the PR description of this PR or should I open a new PR for that?

**Comment by Rahulkhinchi03** [comment]
Please read about the check and investigate which violation message is required: https://checkstyle.sourceforge.io/config_annotation.html#AnnotationLocation

**Review by nick-mancuso — CHANGES_REQUESTED** [review]
Documentation update is not required for this issue, please read https://github.com/checkstyle/checkstyle/issues/11214#issue-1106705357 attentively and see other linked PRs for this issue as examples.

**Comment by rnveach** [comment]
@Shaman20 ping

**Comment by romani** [comment]
Update is irrelevant to referenced issue

**Pull request closed without merging**
