### PR TITLE
Checking existance of config file before processing target file.

### PR DESCRIPTION
**Pull request by Bhavik3**

### CODE REVIEW

**Comment by romani** [comment]
please move that check close/under to "if (!cmdLine.hasOption("c")) {"

**Comment by Bhavik3** [comment]
@romani 

DONE

**Comment by romani** [comment]
good but please enforce "one return point from method" idea, as it was before.

**Comment by Bhavik3** [comment]
@romani 
DONE

**Comment by romani** [comment]
better, but:

1) 
> testNonExistingTargetFile()

as you change test you need to rename test - please rename it according to what you are checking.
Reasonably long name is ok. We already have  "testNonExistingConfigFile()" , so I am not sure why you change "testNonExistingTargetFile"

2) 
> /checkstyle/config-classname.xml" ,

please remove extra space.

**Comment by Bhavik3** [comment]
1)
Main.main("-c", "/google_checks.xml", "NonexistingFile.java");

Here, "/google_checks.xml" does not exist at specified directory. so, when new CliValidation() function check for it, it return from

**Comment by Bhavik3** [comment]
1)
testNonExistingTargetFile()
Main.main("-c", "/google_checks.xml", "NonexistingFile.java");
Here, google_checks.xml does not exist. so If i do not change to existing config file, CliValidation() function will return before checking for NonExistingTargetFile. that's why I change it.
As far as name is concerned, this check doing same as before. so no need to change name. it is completely appropriate. same goes for testNonExistingOutputFormat().

2)
DONE

**Comment by romani** [comment]
thanks a lot ! Now I got it - you are right.

**Pull request merged**
