### PR TITLE
Issue #270: LineWrappingHandler keeps same indentation level for syntactically parallel elements if forceStrictCondition is true

### LINKED ISSUE #270: IndentationCheck: keep the same indentation level for syntactically parallel elements
There are cases with the indentation for <a href="http://stackoverflow.com/questions/25611099/what-is-syntactically-parallel-elements-in-java">syntactically parallel elements</a> which should be handled properly by the check.

```
In general, two continuation lines use the same indentation level 
if and only if they begin with syntactically parallel elements.
```

In general, syntactically parallel elements are <a href="http://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.11">separators and operators</a> which are at the same level of nesting. The level of nesting can be figured out by the opening/closing parenthesis.

E.g.:

a) each line is started with "+" as syntactically parallel elements of the same scope

```
foo("bar"
    + "baz"
    + "boo");
```

b) each line is started with "+" but they are not syntactically parallel in same scope( see "(" , ")")

```
foo("bar"
    + foo2("bar"
           + "baz"));
```

There is a more complicated case with builder pattern usage:

```
private Something getSomething() {
    return feedBuilder("data", "/path", "ONE", "TWO").addFiles(
            zipBuilder("file1", "file2")
                    .setUpdateFileSchedule(Schedule.longWork(new LocalTime(1, 0)))
                    .addFiles(
                            coolBuilder("otherFile1").build(),
                            coolBuilder("otherFile2").build(),
                            coolBuilder("otherFile3").build(),
                            coolBuilder("otherFile4").build()
                    ).build(),
            zipBuilder("resource1", "resource2")
                    .setUpdateFileSchedule(Schedule.work(new LocalTime(11, 0)))
                    .addFile(coolBuilder("data").build())
                    .build()
            ).build();
}
```

where the first addFiles(...) method receives two parameters (the two zipBuilders) which separated by syntactically parallel elements ",". Each zipBuilder has its own parallel elements (calls of the setUpdateFileSchedule and addFiles methods) and so forth.

We also have to investigate other cases with parallel elements and put them into test inputs.

**NOTE:** the Indentation check's violations mustn't be conflicted with the current <a href="https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheck.java">SeparatorWrapCheck</a> and <a href="https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java">OperatorWrapCheck</a> checks.
##

### PR DESCRIPTION
**Pull request by plan3d**
Resolves #270

Only active if forceStrictCondition is true

Diff Regression projects: https://gist.githubusercontent.com/plan3d/ca91d8262d18c4c84f6b62fa1cb4bebc/raw/55f3df0043861c1c5c0eaf2ee7868b2b211d8771/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/plan3d/ca91d8262d18c4c84f6b62fa1cb4bebc/raw/0b5868a05497728b1ab705790eb3c411cb846b10/my_check_strict.xml

### CODE REVIEW

**Comment by romani** [comment]
@plan3d , please fix CI failures, ones CI pass, please generate report and self check it to make sure there is not side effect changes.

**Comment by plan3d** [comment]
@romani Can you please tell me the reason why wercker build fails?

**Comment by nmancus1** [comment]
From wercker:
`Caused by: javax.net.ssl.SSLException: Connection reset` - I've restarted it.

@romani last failing CI is Travis because this issue is not approved. 
@plan3d feel free to generate report if you are ready.

**Comment by plan3d** [comment]
Github, generate report

**Comment by nmancus1** [comment]
Github, rebase

**Comment by plan3d** [comment]
Github, generate report

**Comment by plan3d** [comment]
> https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b589957_2021071203/reports/diff/index.html

Report with forceStrictCondition=true

**Comment by rnveach** [comment]
@plan3d Files have conflicts.

**Comment by Rahulkhinchi03** [comment]
@plan3d  are you still working on this PR?

**Comment by Rahulkhinchi03** [comment]
@romani Can I reuse the code and try this issue?

**Comment by romani** [comment]
@Rahulkhinchi03 , sure please reuse code as much as reasonable.

This Check is most complicated check in whole checkstyle, I do not recommend new contributors to deal with it. Better to find somethig more easy.

**Pull request closed without merging**
