### PR TITLE
Issue #9987: Removed redundant throw statement and fixed catch block

### LINKED ISSUE #9987: Resolve Pitest Issues - AbstractHeaderCheck (1)
Child Issue of #7797 ,
https://github.com/checkstyle/checkstyle/blob/master/.ci/pitest.sh#L54

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
Fixes #9987 

Diff Regression config: https://gist.github.com/Devansu-Yadav/fe9085cbac24ad1843f30184dd296b06/raw/76cdcbbadaa82d4f85f523b3815263ac040b2f41/config.xml
Diff Regression projects: https://gist.githubusercontent.com/Devansu-Yadav/fe9085cbac24ad1843f30184dd296b06/raw/76cdcbbadaa82d4f85f523b3815263ac040b2f41/projects-to-test-on.properties
Report label: Diff Regression Report after fix

### CODE REVIEW

**Comment by Devansu-Yadav** [comment]
@romani @rnveach There is a test failure caused by `HeaderCheckPowerTest.java` located at [https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/powermock/HeaderCheckPowerTest.java#L56](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/powermock/HeaderCheckPowerTest.java#L56)
```
[ERROR] testIoExceptionWhenLoadingHeader  Time elapsed: 2.025 s  <<< FAILURE!
java.lang.AssertionError: Exception expected
	at com.puppycrawl.tools.checkstyle.internal.powermock.HeaderCheckPowerTest.testIoExceptionWhenLoadingHeader(HeaderCheckPowerTest.java:63)
```
Since, I have removed the `throw` statement and updated the `catch` block to ignore the exception, this Test fails. So I think we need to make changes in this Test or remove this Test as it only checks whether an `IOException` is thrown by `setHeader()` using `Powermock` which, as far as I understand the Test code, is purposely throwing the `IOException` and not thrown by `setHeader()` method in `AbstractHeaderCheck.java`. 

Also, we cannot entirely remove the `catch` block as I had stated in [issue #9987 - comment](https://github.com/checkstyle/checkstyle/issues/9987#issuecomment-841812981) since the exception thrown by `loadHeader()` method needs to be handled.
Pls guide me how I should go ahead with this issue.

**Comment by Devansu-Yadav** [comment]
@romani @timurt I have made a few changes in `HeaderCheckPowerTest.java`. There are still CI failures because of the line coverage ratio dropping to **0.98**.

`Rule violated for class com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck: lines covered ratio is 0.98, but expected minimum is 1.00`
This is because we are not able to cover this line `catch (final IOException ignored) {`

**Link to the Jacoco report**:- [https://devansu-yadav.github.io/Devansu-Yadav-Checkstyle-test-reports.github.io/jacoco_report_for_9987/com.puppycrawl.tools.checkstyle.checks.header/AbstractHeaderCheck.java.html#L146](https://devansu-yadav.github.io/Devansu-Yadav-Checkstyle-test-reports.github.io/jacoco_report_for_9987/com.puppycrawl.tools.checkstyle.checks.header/AbstractHeaderCheck.java.html#L146)

I am not able to figure out how to increase line coverage. Pls guide me how I should proceed with this PR.

**Comment by Devansu-Yadav** [comment]
GitHub, generate report

**Comment by Devansu-Yadav** [comment]
GitHub, generate report

**Comment by Devansu-Yadav** [comment]
GitHub, generate report

**Comment by Devansu-Yadav** [comment]
GitHub, generate report

**Comment by Devansu-Yadav** [comment]
GitHub, generate report

**Comment by rnveach** [comment]
> Pls guide me how I should proceed with this PR.

Please generate the coverage reports before and after this PR and provide us where (lines) coverage has diminished at.

**Comment by Devansu-Yadav** [comment]
Jacoco report before fix:- https://devansu-yadav.github.io/Devansu-Yadav-Checkstyle-test-reports.github.io/jacoco_report_before_fix/com.puppycrawl.tools.checkstyle.checks.header/AbstractHeaderCheck.java.html#L155

Jacoco report after fix:- https://devansu-yadav.github.io/Devansu-Yadav-Checkstyle-test-reports.github.io/jacoco_report_after_fix/com.puppycrawl.tools.checkstyle.checks.header/AbstractHeaderCheck.java.html#L155

@rnveach @romani After comparing the two reports it seems like there's actually no difference. But then I am getting CI failures since there is a drop in coverage. Is there some other way we could resolve this mutation? As I cannot think of one after a lot of brainstorming over this issue.

**Comment by rnveach** [comment]
Point to drop coverage error you are getting.

All I am seeing is checkstyle error:
````
[INFO] [checkstyle] Running Checkstyle  on 1416 files
[ERROR] [checkstyle] [ERROR] C:\projects\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\HeaderCheckPowerTest.java:22:47: Using the '.*' form of import should be avoided - org.junit.jupiter.api.Assertions.*. [AvoidStarImport]
````
which should be fixed.

**Comment by Devansu-Yadav** [comment]
> ```
> [INFO] [checkstyle] Running Checkstyle  on 1416 files
> [ERROR] [checkstyle] [ERROR] C:\projects\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\HeaderCheckPowerTest.java:22:47: Using the '.*' form of import should be avoided - org.junit.jupiter.api.Assertions.*. [AvoidStarImport]
> ```
> 
> which should be fixed.

@rnveach @romani Fixed it. There still seems to be the same coverage issue causing CI failures :(
I think there needs to be another way to handle the `catch` and `throw` statements in `setHeader()` for resolving the mutations without creating much chaos. Also, I think that `HeaderCheckPowerTest.java` might become redundant because it was previously used to increase the coverage by purposely hitting the `catch` block using `PowerMockito`. 
Do you think we can remove this file as it doesn't help with the coverage right now?

**Comment by nmancus1** [comment]
@Devansu-Yadav are you interested in continuing work on this PR?

**Comment by romani** [comment]
PR will be closed at the end of the month if no activity happens.

**Comment by nick-mancuso** [comment]
We lost contact with author of PR, anybody is welcome to reuse changes here to solve issue.

**Pull request closed without merging**
