### PR TITLE
Issue #11116: Added ELLIPSIS support to WhitespaceAfterCheck

### LINKED ISSUE #11116: WhitespaceAfter should support `ELLIPSIS` token
I have downloaded the latest cli from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

Check documentation at https://checkstyle.sourceforge.io/config_whitespace.html#WhitespaceAfter

**How it works Now:**

```bash

➜  javac Test.java
➜  cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="WhitespaceAfter">
          <property name="tokens" value="ELLIPSIS"/>
        </module>
    </module>
</module>

➜  cat Test.java  
public class Test {
    void method1(int...myVarargs) { // expected violation
    
    }
    void method2(int... myVarargs) { // ok
    
    }
}

➜  java -jar checkstyle-9.2-all.jar -c config.xml Test.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "ELLIPSIS" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:473)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:405)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:332)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:191)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "ELLIPSIS" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck
        at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:223)
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:133)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:468)
        ... 5 more
Checkstyle ends with 1 errors.

```

However, `WhitespaceAroundCheck` does support `ELLIPSIS`. But, this is not a frequently used style. In fact, the [JLS](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html) specifically mentions that

> Note that the ellipsis (...) is a token unto itself (§3.11). It is possible to put whitespace between it and the type, but this is discouraged as a matter of style.

**Is your feature request related to a problem? Please describe.**
I would expect `...` to be a valid token for `WhitespaceAfterCheck`, and for it to enforce style noted above.

**Describe the solution you'd like**

```bash
[ERROR] Test.java:2:21: '...' is not followed by whitespace. [WhitespaceAfter]
```

**Additional context**

Noticed at https://github.com/checkstyle/checkstyle/pull/11094#discussion_r775249437, WhitespaceAfterCheck does not currently support `ELLIPSIS` token.

`ELLIPSIS` should be a default token for `WhitespaceAfterCheck`. Since we use default module for this check in `checkstyle_checks.xml`, we may find some violations in the project.

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Resolves #11116
Final Report (Clean) : https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/7e745f8_2022191620/reports/diff/index.html

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by romani** [comment]
please send PR to xwiki to fix https://app.circleci.com/pipelines/github/checkstyle/checkstyle/11189/workflows/a123a7dc-6104-4ea2-817b-c0c0d2a6b2a3/jobs/111316?invite=true#step-102-2909

**Review by romani — APPROVED** [review]
ok to merge as CI pass

**Review by strkkk — APPROVED** [review]

**Comment by romani** [comment]
@Vyom-Yadav , please create PRs to referenced above projects

**Comment by Vyom-Yadav** [comment]
> Please create PRs to referenced above projects

Already done https://github.com/xwiki/xwiki-rendering/pull/198 https://github.com/pmd/pmd/pull/3744

**Comment by Vyom-Yadav** [comment]
wercker failure is on which project?

**Review by nmancus1 — APPROVED** [review]

**Comment by nmancus1** [comment]
> wercker failure is on which project?

PMD, wercker is restarted

**Comment by romani** [comment]
Wercker failing on PMD, let's wait their PR is merged

**Comment by romani** [comment]
Failing:
```
INFO] --- maven-checkstyle-plugin:3.1.2:check (checkstyle-check) @ pmd-visualforce ---
[INFO] There is 1 error reported by Checkstyle 9.3-SNAPSHOT with /net/sourceforge/pmd/pmd-checkstyle-config.xml ruleset.
[ERROR] src/main/java/net/sourceforge/pmd/lang/vf/DataType.java:[124,49] (whitespace) WhitespaceAfter: '...' is not followed by whitespace.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for PMD 6.42.0-SNAPSHOT:
[INFO] 
[INFO] PMD ................................................ SUCCESS [  2.490 s]
[INFO] PMD
```

Please run on your local:
```
./.ci/validation.sh no-error-pmd
```

And send PR with all changes required

**Comment by Vyom-Yadav** [comment]
PMD was passing successfully on local, can someone confirm that wercker failure is due to PMD or not?

**Comment by nmancus1** [comment]
Wercker output is consistent with comment at https://github.com/checkstyle/checkstyle/pull/11198#issuecomment-1014844192

**Review by pbludov — APPROVED** [review]

**Review by pbludov — APPROVED** [review]

**Comment by nmancus1** [comment]
@romani all related PR's are merged.

**Review by romani — APPROVED** [review]

**Pull request merged**
