### PR TITLE
Issue #11446: update TreeWalkerTest to remove verify usage

### PR DESCRIPTION
**Pull request by mahfouz72**
issue #11446:
continues: #14417
partial migration for TreeWalkerTest to discard verify usage

### CODE REVIEW

**Comment by mahfouz72** [comment]
CI will be green after rebase. we are very close to final fix one more PR

**Comment by MANISH-K-07** [comment]
> CI will be green after rebase. we are very close to final fix one more PR

There seems to be some sort of trouble with the CircleCI workflow.
It is affecting all new PRs.
For example : 
- #14419 
- #14425

**Comment by romani** [comment]
We reverted fix, I restarted your CIs

**Review by romani — APPROVED** [review]
Ok to merge, thanks a lot

**Comment by MANISH-K-07** [comment]
> We reverted fix, I restarted your CIs

@romani ,
The two PRs that you have restarted the CIs for have passed.
However, the list of my open PRs goes on .... **`:)`**
[Author : MANISH-K-07 : pulls](https://github.com/checkstyle/checkstyle/pulls/MANISH-K-07)

**Pull request merged**
