### PR TITLE
Issue #2886: Changed semantics of PropertyExpander

### PR DESCRIPTION
**Pull request by phejl**
Fix for #2886.

### CODE REVIEW

**Comment by mkordas** [comment]
@romani @phejl I'm on it

**Comment by mkordas** [comment]
@phejl please update commit message and PR title to contain hash before issue number - build has failed due to that: https://travis-ci.org/checkstyle/checkstyle/jobs/108404038#L753

**Comment by mkordas** [comment]
@romani looks good, please do final review

**Comment by romani** [comment]
@phejl ,

thanks a lot for fix. Merged as FF.

**Pull request closed without merging**
