### PR TITLE
Issue #3308: EqualsHashCode violation for hashCode without equals

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3308 

Added new violation, was a minor logic change.
Regression to come.

### CODE REVIEW

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/75/

**Comment by MEZk** [comment]
@rnveach 

I thing it is a false negative after the fix:

```java
public class InputEqualsHashCodeNoEquals {

    public int hashCode() {
        return 1;
    }

    public boolean equals(String o) {
        return true;
    }
}
```

Result: no violations.

A good practise is to override both hashCode and equals.
Correct signatures for overriding:
```int hashCode();```
```boolean equals(Object obj);```
As you can see from my example 'equals' overloads base 'equals' but not overrides it. I think you should also check the type of the equals parameter.

FYI: Effective Java 2nd Edition. Item 8. Says: "Don’t substitute another type for Object in the equals declaration

**Comment by rnveach** [comment]
@MEZk It makes sense, but I think that it should probably go in its own issue since it is separate from this specific issue/fix and might need more discussion. With current CS, it produces a violation when you code `boolean equals(String s);` with no `hashCode` method but your saying there should be no violation.

**Comment by romani** [comment]
@MEZk , I do not see that regression (that you point to) in this commit.
Please point me to it if see it.

If such case is reproducible on 7.1 it is ok to fix it in separate issue.

**Comment by MEZk** [comment]
@romani 

Before and after fix the check does not produce any violations if equals is overloaded. 
From your issue description:

>
EqualsHashCodeCheck checks that if equals is
overridden (either correctly with an Object parameter or
wrongly with some other Class), hashCode should also
be overridden.

Why?

From [the link](http://gee.cs.oswego.edu/dl/html/javaCodingStd.html#secRec) that you gave in issue description:
>
Avoid overloading methods on argument type. (Overriding on arity is OK, as in having a one-argument version versus a two-argument version)

From Effective Java 2nd Edition. Item 8: 
>"Don’t substitute another type for Object in the equals declaration".

**Comment by romani** [comment]
PR is merged as it is partial fix for issue.
Issue is not resolved for a reason described at https://github.com/checkstyle/checkstyle/pull/3387#issuecomment-236662960

**Comment by romani** [comment]
@rnveach , it might be interesting to open github issues on few projects that have problems with equals/hashcode. If find time to make few of them , please put them as reference to our issue.

**Pull request merged**
