### PR TITLE
Issue #9499: Update example of AST for TokenTypes.LITERAL_THROW

### LINKED ISSUE #9499: update example of AST for TokenTypes.LITERAL_THROW
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_THROW

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

### PR DESCRIPTION
**Pull request by bossever**
Closes #9499 

## Before Update
image

## After Update
image

### Source
`$ cat Test.java`
```java
class Test {

  void throwException() {
    throw new ArithmeticException("An arithmetic exception has occurred.");
  }
}
```

### AST
```sh
$ java -jar .\checkstyle-9.0.1-all.jar -t Test.java

COMPILATION_UNIT -> COMPILATION_UNIT [1:0]
`--CLASS_DEF -> CLASS_DEF [1:0]
    |--MODIFIERS -> MODIFIERS [1:0]
    |--LITERAL_CLASS -> class [1:0]
    |--IDENT -> Test [1:6]
    `--OBJBLOCK -> OBJBLOCK [1:11]
        |--LCURLY -> { [1:11]
        |--METHOD_DEF -> METHOD_DEF [3:2]
        |   |--MODIFIERS -> MODIFIERS [3:2]
        |   |--TYPE -> TYPE [3:2]
        |   |   `--LITERAL_VOID -> void [3:2]
        |   |--IDENT -> throwException [3:7]
        |   |--LPAREN -> ( [3:21]
        |   |--PARAMETERS -> PARAMETERS [3:22]
        |   |--RPAREN -> ) [3:22]
        |   `--SLIST -> { [3:24]
        |       |--LITERAL_THROW -> throw [4:4]
        |       |   |--EXPR -> EXPR [4:10]
        |       |   |   `--LITERAL_NEW -> new [4:10]
        |       |   |       |--IDENT -> ArithmeticException [4:14]
        |       |   |       |--LPAREN -> ( [4:33]
        |       |   |       |--ELIST -> ELIST [4:34]
        |       |   |       |   `--EXPR -> EXPR [4:34]
        |       |   |       |       `--STRING_LITERAL -> "An arithmetic exception has occurred." [4:34]
        |       |   |       `--RPAREN -> ) [4:73]
        |       |   `--SEMI -> ; [4:74]
        |       `--RCURLY -> } [5:2]
        `--RCURLY -> } [6:0]
```

### Expected Update For Javadoc
```
METHOD_DEF -> METHOD_DEF [3:2]
 |   |--MODIFIERS -> MODIFIERS [3:2]
 |   |--TYPE -> TYPE [3:2]
 |   |   `--LITERAL_VOID -> void [3:2]
 |   |--IDENT -> throwException [3:7]
 |   |--LPAREN -> ( [3:21]
 |   |--PARAMETERS -> PARAMETERS [3:22]
 |   |--RPAREN -> ) [3:22]
 |   `--SLIST -> { [3:24]
 |       |--LITERAL_THROW -> throw [4:4]
 |       |   |--EXPR -> EXPR [4:10]
 |       |   |   `--LITERAL_NEW -> new [4:10]
 |       |   |       |--IDENT -> ArithmeticException [4:14]
 |       |   |       |--LPAREN -> ( [4:33]
 |       |   |       |--ELIST -> ELIST [4:34]
 |       |   |       |   `--EXPR -> EXPR [4:34]
 |       |   |       |       `--STRING_LITERAL -> "An arithmetic exception has occurred." [4:34]
 |       |   |       `--RPAREN -> ) [4:73]
 |       |   `--SEMI -> ; [4:74]
 |       `--RCURLY -> } [5:2]
 `--RCURLY -> } [6:0]
```

### CODE REVIEW

**Comment by bossever** [comment]
@romani
Please add the 'hacktoberfest-accepted' label to my PRs if eligible, thanks.

**Comment by romani** [comment]
@bossever , please investigate CI failures

**Comment by bossever** [comment]
> @bossever , please investigate CI failures

Fixed.

**Comment by romani** [comment]
CI failing at 
Validation (openjdk11, slow pool) - CMD=mvn -e --no-transfer-progress clean install -Pno-validations && .ci/validation.sh no-error-pmd

Not related

**Pull request merged**
