### PR TITLE
Restricted suppression for gui-package, issue #1555.

### PR DESCRIPTION
**Pull request by MEZk**

### CODE REVIEW

**Comment by mkordas** [comment]
@MEZk @romani 
In `suppressions.xml` we have `<suppress checks="." files=".*[\\/]checkstyle[\\/]gui[\\/]"/>`. I believe we want to fix that and enforce proper style also in that package, what do you think?

There is one issue in this commit that normally would be detected - `private static final` fields should go before `private final` ones.

**Comment by MEZk** [comment]
@mkordas @romani 
After replacing Magic Numbers and removing ```suppress checks="." files=".*[\\/]checkstyle[\\/]gui[\\/]"/>.``` mvn verify reports that build success.
So should I make commit which will remove suppression?

@mkordas
>There is one issue in this commit that normally would be detected - private static final fields should go before private final ones.

Thank.

**Comment by mkordas** [comment]
@MEZk - sure, the less suppressions the better.

**Comment by romani** [comment]
usage of MagicNumber in UI code is searching for problems. That Check generate tons of violations, fixing them will make code unmanageable.
So, please 
1) activate all Check except for MagicNumber in GUI code, put  to suppression a reason as comment. 
2) revert all changes to MagicNumber in GUI code.

**Comment by MEZk** [comment]
@romani 
1) Done. Suppression has been added for MagicNumber.
2) Done.

**Comment by romani** [comment]
merged as FF.

thanks a lot, but please stay away from issues to resolve violation from static analysis, they are not obvious, you do not have that much experience to fix that correctly.

**Pull request closed without merging**
