### PR TITLE
Issue #12011: tweet-releasenotes.sh should be able to work on start and finish release names

### LINKED ISSUE #12011: tweet-releasenotes.sh should be able to generate release notes for any release of past
https://github.com/checkstyle/checkstyle/blob/master/.ci/tweet-releasenotes.sh

1)
it is not clear why we demand 
`checkForVariable "CS_RELEASE_VERSION"`

and in same time do
```
CS_RELEASE_VERSION="$(getCheckstylePomVersion)"
echo CS_RELEASE_VERSION="$CS_RELEASE_VERSION"
```

2)
This script should work in two modes:
`.ci/tweet-releasenotes.sh` - generation of twit for latest release
`.ci/tweet-releasenotes.sh 10.3.2` - generation of twit for release 10.3.2

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
Fixes #12011

### CODE REVIEW

**Comment by romani** [comment]
Please read https://github.com/checkstyle/checkstyle/issues/12011#issuecomment-1207446712

Please always show testing output.
Generate release notes for few past releases.

Script need to updated to get by API release that is previous before required.

**Comment by Rahulkhinchi03** [comment]
```
rahul@rk7:~/Desktop/opensource/checkstyle$ .ci/tweet-releasenotes.sh 10.1
Cloning into 'contribution'...
remote: Enumerating objects: 7886, done.
remote: Counting objects: 100% (1187/1187), done.
remote: Compressing objects: 100% (517/517), done.
remote: Total 7886 (delta 588), reused 1053 (delta 526), pack-reused 6699
Receiving objects: 100% (7886/7886), 2.85 MiB | 1.72 MiB/s, done.
Resolving deltas: 100% (4027/4027), done.
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< com.github.checkstyle:releasenotes-builder >-------------
[INFO] Building releasenotes-builder 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ releasenotes-builder ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ releasenotes-builder ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ releasenotes-builder ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 18 source files to /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/target/classes
[INFO] /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java: /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java uses or overrides a deprecated API.
[INFO] /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ releasenotes-builder ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ releasenotes-builder ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 18 source files to /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/target/classes
[INFO] /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java: /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java uses or overrides a deprecated API.
[INFO] /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ releasenotes-builder ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 20 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ releasenotes-builder ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/target/test-classes
[INFO] /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java: /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java uses or overrides a deprecated API.
[INFO] /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ releasenotes-builder ---
[INFO] Surefire report directory: /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.checkstyle.templates.TemplateProcessorTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.63 sec
Running com.github.checkstyle.github.CommitMessageTest
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

Results :

Tests run: 26, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ releasenotes-builder ---
[INFO] Building jar: /home/rahul/Desktop/opensource/checkstyle/.ci-temp/contribution/releasenotes-builder/target/releasenotes-builder-1.0.jar
[INFO] 
[INFO] --- maven-shade-plugin:2.4.2:shade (default) @ releasenotes-builder ---
[INFO] Including org.kohsuke:github-api:jar:1.99 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.9 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.13 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.6 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.12.6.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.12.6 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.12.6 in the shaded jar.
[INFO] Including org.eclipse.jgit:org.eclipse.jgit:jar:5.4.2.201908231537-r in the shaded jar.
[INFO] Including com.jcraft:jsch:jar:0.1.55 in the shaded jar.
[INFO] Including com.jcraft:jzlib:jar:1.1.1 in the shaded jar.
[INFO] Including com.googlecode.javaewah:JavaEWAH:jar:1.1.6 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.2 in the shaded jar.
[INFO] Including org.bouncycastle:bcpg-jdk15on:jar:1.61 in the shaded jar.
[INFO] Including org.bouncycastle:bcprov-jdk15on:jar:1.61 in the shaded jar.
[INFO] Including org.bouncycastle:bcpkix-jdk15on:jar:1.61 in the shaded jar.
[INFO] Including org.slf4j:slf4j-simple:jar:1.7.12 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:30.1.1-jre in the shaded jar.
[INFO] Including com.google.guava:failureaccess:jar:1.0.1 in the shaded jar.
[INFO] Including com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava in the shaded jar.
[INFO] Including com.google.code.findbugs:jsr305:jar:3.0.2 in the shaded jar.
[INFO] Including org.checkerframework:checker-qual:jar:3.8.0 in the shaded jar.
[INFO] Including com.google.errorprone:error_prone_annotations:jar:2.5.1 in the shaded jar.
[INFO] Including com.google.j2objc:j2objc-annotations:jar:1.3 in the shaded jar.
[INFO] Including org.freemarker:freemarker:jar:2.3.29 in the shaded jar.
[INFO] Including commons-cli:commons-cli:jar:1.4 in the shaded jar.
[INFO] Including commons-lang:commons-lang:jar:2.6 in the shaded jar.
[INFO] Including org.twitter4j:twitter4j-core:jar:4.0.7 in the shaded jar.
[INFO] Including javax.mail:mail:jar:1.5.0-b01 in the shaded jar.
[INFO] Including javax.activation:activation:jar:1.1 in the shaded jar.
[WARNING] bcprov-jdk15on-1.61.jar, jackson-annotations-2.12.6.jar, bcpg-jdk15on-1.61.jar, jackson-databind-2.12.6.1.jar, jackson-core-2.12.6.jar, bcpkix-jdk15on-1.61.jar define 1 overlapping classes: 
[WARNING]   - module-info
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Attaching shaded artifact.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.915 s
[INFO] Finished at: 2022-08-08T22:29:55+05:30
[INFO] ------------------------------------------------------------------------
Cloning into 'checkstyle'...
remote: Enumerating objects: 210121, done.
remote: Counting objects: 100% (1690/1690), done.
remote: Compressing objects: 100% (557/557), done.
remote: Total 210121 (delta 712), reused 1543 (delta 669), pack-reused 208431
Receiving objects: 100% (210121/210121), 82.20 MiB | 3.91 MiB/s, done.
Resolving deltas: 100% (120310/120310), done.
CS_RELEASE_VERSION=10.1
LATEST_RELEASE_TAG="checkstyle-10.3.2"

[WARN] Issue #12017 "Kill surviving mutations in pitest-api" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/12017
[WARN] Issue #11140 "Solve fb-contrib errors" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11140
[WARN] Issue #11720 "Pitest: Kill all surviving mutations" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11720

Execution succeeded!
rahul@rk7:~/Desktop/opensource/checkstyle$ 

```

**Comment by romani** [comment]
tweet should like https://twitter.com/checkstyle_java/status/1508102605314043906?s=20&t=aK-niouv-PuFHvT6zyfurQ

**Review by romani — CHANGES_REQUESTED** [review]
you can not use 

>LATEST_RELEASE_TAG=$(curl -s https://api.github.com/repos/checkstyle/checkstyle/releases/latest 

you have to take target release tag that is for "10.1", it is not a latest.

Please share content of tweet in CLI output, lets not publish actual tweet to twitter. Publishing works. Lets focus on content of tweet.

**Comment by romani** [comment]
It is the same logic as at https://github.com/checkstyle/checkstyle/pull/12007#discussion_r945223740

**Pull request closed without merging**
