### PR TITLE
Add test to verify that all checks are present on website, issue #783

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
> DO_NOT_CHECK_LIST

Please rename to "ignore _list"

**Comment by mkordas** [comment]
Done

**Comment by romani** [comment]
That logic will have skip catching if name of check is part of Another Check
http://checkstyle.sourceforge.net/availablechecks.html

Example:
Regexp
RegexpHeader
RegexpMultiline
RegexpSingleline
RegexpSinglelineJava

please search base on following chunk of text: 
```
<a href="config_misc.html#Regexp">

    Regexp

</a>
```

**Comment by mkordas** [comment]
Done. I needed to introduce two kinds of patterns:
- `(?s).*<a href="config_\w+\.html#Regex">Regex</a>.*` - standard one
- `(?s).*<a href="config_naming\.html#Modules">Regex</a>.*` - for naming checks

**Comment by alexkravin** [comment]
@romani 
Due to #691 
There will be no reason in analyzing available checks page after #768 will be merged, so all checks will be specified in checks.xml

Just to make merging less complex.

**Comment by romani** [comment]
merged as FF.

> There will be no reason in analyzing available checks page after #768 will be merged

thanks, I am controlling that PR, all will be fine.

**Pull request closed without merging**
