### PR TITLE
Rename variables with unused exceptions. #1555

### PR DESCRIPTION
**Pull request by mkordas**
Fixes `UnusedCatchParameter` inspection violations.

Description:
>Reports any catch parameters that are unused in their corresponding blocks. This inspection will not report any catch parameters named "ignore" or "ignored". Conversely this inspection will warn on any catch parameters named "ignore" or "ignored" that are actually used.

### CODE REVIEW

**Comment by romani** [comment]
>
```
        catch (ClassNotFoundException ignored) {
             // expected
```

if no ability to add "expected" to allowed list, please suppress that Rule , "ignored" != "expected" .

**Comment by romani** [comment]
@mkordas , please close that PR is you are not going to update it.

**Comment by mkordas** [comment]
@romani - not all of them are expected - I'll review each case and leave `ignored` in cases where exception is really ignored and not expected.

**Comment by mkordas** [comment]
I've reviewed all the cases and provided two separate commits as a solution.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
