### PR TITLE
Issue #10924: Update WhitespaceAfterCheck to use code points

### PR DESCRIPTION
**Pull request by MUzairS15**
Issue #10924: Updated WhitespaceAfterCheck to use code point.
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/b0e2f949855c6f9625f3287f4cca6670/raw/78de9bc3b0f904016fc250036d66b130b41ffe29/config.xml

### CODE REVIEW

**Comment by MUzairS15** [comment]
Github, generate report

**Comment by MUzairS15** [comment]
Pls review

**Comment by MUzairS15** [comment]
This check already uses codepoint, refactored this check to use code point utility methods

**Review by nick-mancuso — APPROVED** [review]
PR title in not wholly consistent, since we already used code points, but since we added inputs and updated check to use new method, let's keep it.

**Review by romani — APPROVED** [review]

**Pull request merged**
