### PR TITLE
Fix OneStatementPerLine on multiple field initialization bug, issue #1237

### PR DESCRIPTION
**Pull request by MEZk**
@romani 
I completely reworked the check, because it detected only expression statements which are on the same line. I provided a bundle of UTs with comments to explain new check logic.

[REPORTS] (http://mezk.github.io)

### CODE REVIEW

**Comment by romani** [comment]
1)
> * Restricts the number of statements per line to one.

please extend javadoc with all examples that we discussed in mail. I do not want to remember that that corner cases. All that was not clear for you in that Check on a moment you started to work with it, should be explained in javadoc and xdoc.

2)
> public int[] getAcceptableTokens() {

please override getRequiredTokens method too. Looks like it was missed during bulk update.


3) 
>                if (lastStatementEnd == ast.getLineNo()
                    && !inForHeader) {
                    //Two semicolons on the same line
                    log(ast, MSG_KEY);
                }
                else if (isMultilineStatement(ast)) {

it is not clear why you donot check for FOR in second IF at all, please explain , FOR could be multiline too

4) 
>             case TokenTypes.FOR_ITERATOR:
                inForHeader = false;
                break;
            case TokenTypes.SEMI:

please make the same order of cases as in visitToken()

**Comment by MEZk** [comment]
@romani 
1)
>please extend javadoc with all examples that we discussed in mail. I do not want to remember that that corner cases. All that was not clear for you in that Check on a moment you started to work with it, should be explained in javadoc and xdoc.

Done.

2) 
>please override getRequiredTokens method too. Looks like it was missed during bulk update.

Done, but 'getRequiredTokens' had not been overridden before I made changes that is why I decided not to override it. And [cobertura shows](http://mezk.github.io/cobertura_getRequiredTokens/com.puppycrawl.tools.checkstyle.checks.coding.OneStatementPerLineCheck.html) that this method is not invoked. And there are many checks where authors do not override this method, for example [DeclarationOrderCheck](http://mezk.github.io/cobertura_getRequiredTokens/com.puppycrawl.tools.checkstyle.checks.coding.DeclarationOrderCheck.html).
And 'getRequiredTokens' also is not invoked at [CovariantEqualsCheck](http://mezk.github.io/cobertura_getRequiredTokens/com.puppycrawl.tools.checkstyle.checks.coding.CovariantEqualsCheck.html). And please, could you explain the purpose of the method because I don't really understand javadoc at Check class:

````java
    /**
     * The tokens that this check must be registered for.
     * @return the token set this must be registered for.
     * @see TokenTypes
     */
    public int[] getRequiredTokens() {
        return new int[] {};
    }
````

3) 
>it is not clear why you donot check for FOR in second IF at all, please explain , FOR could be multiline too.

You are right. It was my mistake, I did not provide UTs for this situation that is why cobertura's coverage report showed that condition ```!inForHeader``` in second IF was dead code and there were not any exceptions while I was testing my changes with checkstyle-tester. 
Yet, here is an example of multiline 'for loop' statement where each semicolon is on its own line. But if we do not check for 'FOR LOOP' header in second IF this code rise violation:

````java
for(int n = 0,
            k = 1
            ; n<5
            ;
            n++, k--)
````

 I've fixed this.

4) 
> please make the same order of cases as in visitToken()

Done

5) We have merge conflict. I think because of the changing in pom.xml at master branch.

**Comment by romani** [comment]
please rebase your chnages on latest code to let me merge your code.

**Comment by MEZk** [comment]
@romani 
I've rebased my changes. After rebasing coverage increased to 100% due to the [testTokensNotNull](https://github.com/checkstyle/checkstyle/commit/1e0e7a7be85390fd94618eee5d631c9ff7fa3383#diff-66eae62442091e0a0ab390f54a5f2537R52) where 'getRequiredTokens' is invoked.

**Comment by romani** [comment]
good ....

1)
> The following 9 examples will be flagged as a warning.

please change all "warning" to violation, as user can define any severity/level to it even ERROR

2) 
>  *     Example #1: two variable declaration statements on the same line.
 * </p>
 * <pre>
 *     int var1; int var2; //warning here

will be be better to format as .... ?  
```
 int var1; int var2; //violation, two variable declaration statements on the same line.
```
example: http://checkstyle.sourceforge.net/config_whitespace.html#GenericWhitespace

3)
> for (int i = 0, j = 0, k = 1; i < 20; i++) {  one = i; } //warn

I do not think it is good idea to highlight such cases in that Check, as what is statement there is highly debatable question.  It is not a rare case when people do that. If you introduced that violation , please revert it. There should be no violation. In future we could make option for that case if smb request it.

4)
> but 'getRequiredTokens' had not been overridden before I made changes that is why I decided not to override it.

yes, it is not defined in all Check , but we will define it in all Checks eventually.

5)
please rebase your code one more time, sorry , I did a change that do conflicts in pom.xml .

**Comment by MEZk** [comment]
@romani 
1)
>please change all "warning" to violation, as user can define any severity/level to it even ERROR

Done

2)
>will be be better to format as .... ?
 int var1; int var2; //violation, two variable declaration statements on the same line.
example: http://checkstyle.sourceforge.net/config_whitespace.html#GenericWhitespace

I've done formatting in xdoc, but I have not done formatting in javadoc because I think it is difficult to read for future contributors lines which are over 80 characters and also formatting like this:
```
var1 = 1                        // violation, while theoretically being distributed over two lines,
; var2 = 2;                     // this is a sample of 2 statements on one line.

import java.io.EOFException; import java.io.BufferedReader; // violation, two import statements
                                                            // on the same line.
```
inside java class. 

3)
>I do not think it is good idea to highlight such cases in that Check, as what is statement there is highly debatable question. It is not a rare case when people do that. If you introduced that violation , please revert it. There should be no violation. In future we could make option for that case if smb request it.

 'for loop' is a java language statement and any other statement on the same line theoretically may be considered as violation. But I agree that it is not a rare case and that is why I allowed [this] (СССЫЛКА НА ТЕСТ)

5) Done, and I've also provided additional UT's to test 'for loop' and generated new [reports](ССЫЛКА НА РЕПОРТЫ). I also removed default block in visitToken, because  switch branches use all registered TokenTypes: SEMI,

**Comment by MEZk** [comment]
@romani 
1)
>please change all "warning" to violation, as user can define any severity/level to it even ERROR

Done

2)
>will be be better to format as .... ?
 int var1; int var2; //violation, two variable declaration statements on the same line.
example: http://checkstyle.sourceforge.net/config_whitespace.html#GenericWhitespace

I've done formatting in xdoc, but I have not done formatting in javadoc because I think it is difficult to read for future contributors lines which are over 80 characters and also formatting like this:
```
var1 = 1                        // violation, while theoretically being distributed over two lines,
; var2 = 2;                     // this is a sample of 2 statements on one line.

import java.io.EOFException; import java.io.BufferedReader; // violation, two import statements
                                                            // on the same line.
```
inside java class. 

3)
>I do not think it is good idea to highlight such cases in that Check, as what is statement there is highly debatable question. It is not a rare case when people do that. If you introduced that violation , please revert it. There should be no violation. In future we could make option for that case if smb request it.

 'for loop' is a java language statement and any other statement on the same line theoretically may be considered as violation. But I agree that it is not a rare case and that is why I allowed [this] (https://github.com/checkstyle/checkstyle/commit/70acef31ad12215c05e968457c26e6321d46d25e#diff-b303615be66d2d5eaf9f2a094d1256fcR228). And as you can see from [REPORTS](mezk.github.io), that cases are often used.

5) Done, and I've also provided additional UT's to test 'for loop' and generated new [REPORTS](mezk.github.io).

6) I've done refactoring of ['visitToken'](https://github.com/checkstyle/checkstyle/commit/70acef31ad12215c05e968457c26e6321d46d25e#diff-6036db109c9bbcf6379d74bda22adce9R152) to make it easy to read. It seams to me that check logic is clear now.

**Comment by romani** [comment]
good reports :)

1) please rebase over latest code

2) javadoc is too long and too much almost identical examples, make it compact:
```
 //Each line causes violations:
 int var1; int var2;
 var1 = 1; var2 = 2;
 int var1 = 1; int var2 = 2;
 Object obj1 = new Object(); Object obj2 = new Object();
 var1++; var2++;
 ;; //two empty statements on the same line.

 //Multi-line statements:
 int var1 = 1
 ; var2 = 2; //violation here
 int o = 1, p = 2,
 r = 5; int t; //violation here

```

**Comment by MEZk** [comment]
@romani 
1)
> please rebase over latest code

Done.

2) 
> javadoc is too long and too much almost identical examples, make it compact

Done.

**Comment by romani** [comment]
impressive update ! thanks a lot!

**Pull request closed without merging**
