### PR TITLE
Issue #13345: Enable examples tests for UncommentedMainCheck

### PR DESCRIPTION
**Pull request by AmitKumarDeoghoria**
### Title: Enable examples tests for UncommentedMainCheck

**Related Issue: #13345** 

**Summary**
This pull request aims to enable example tests for the **UncommentedMainCheck** in the project. The implementation focuses on ensuring that UncommentedMain checks are correctly validated through comprehensive test cases, improving overall code reliability and quality.

**Key Changes Made**

- Conversion of txt file to Java File
- Enable the test cases by adding expected violations in the expected array for all example tests
- Made corresponding changes in the xml and xml.template file

### CODE REVIEW

**Comment by AmitKumarDeoghoria** [comment]
@romani  there is no xml.template file for the check should I create one?

**Comment by romani** [comment]
Sad, can you create it? I hope you saw tons of examples on how they looks like

**Comment by AmitKumarDeoghoria** [comment]
Yeah I am on it.

**Comment by rnveach** [comment]
This shows a hole in our tests that this file is completely missed.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/checks/misc/uncommentedmain.xml.template

**Comment by AmitKumarDeoghoria** [comment]
my bad, Thanks for the help @rnveach

**Comment by AmitKumarDeoghoria** [comment]
GitHub, generate website

**Review by romani — APPROVED** [review]
Glad to merge

**Pull request merged**
