### PR TITLE
Issue #4437: Modified ImportControlLoaderTest.java and moved its input files to the importcontrolloader subdirectory

### PR DESCRIPTION
**Pull request by subkrish**
Issue #4437

This PR moves all inputs of ImportControlLoaderTest of the imports package to a new subdirectory 'importcontrolloader'.

### CODE REVIEW

**Comment by romani** [comment]
@subkrish , please review CIs violations and fix them

**Comment by subkrish** [comment]
Yes, I am fixing them. Will push once changed.

**Comment by subkrish** [comment]
@romani @rnveach Fixed. Please review.

**Comment by romani** [comment]
failure in Travis was a problem on Travis side.

**Pull request merged**
