### PR TITLE
Updated example of AST TokenTypes.LAMBDA

### PR DESCRIPTION
**Pull request by Hrushi20**
Solves Issue #9458 

Updated the example to 
Screenshot (12)

Terminal view of AST

Screenshot (8)

Web view

Screenshot (13)

### CODE REVIEW

**Comment by Hrushi20** [comment]
config/checkstyle_input_suppressions.xml  was updated by @shashwatj07 after I finished my code. I have merged both commits into a single commit.

**Review by shashwatj07 — CHANGES_REQUESTED** [review]
Hi @Hrushi20 , thanks for your contribution.
I see that your branch is 1 commit behind, if you rebase onto the latest master you won't need to merge commits. Please do so.

**Comment by romani** [comment]
thansks a lot for help, please look at https://github.com/checkstyle/checkstyle/pull/10367
on how javdoc should be updated and how to show prove of your changes in PR description.

**Comment by Hrushi20** [comment]
@romani  Do you need the entire AST to be displayed in the javadoc? In #10367, the developer didn't display the entire code in the javadoc. Can you tell me the required changes so that I can update the javadoc.

**Comment by romani** [comment]
In javadoc we have only chuck of ast in format that our cli prints. In referenced PR you can see all details how cli output converted to javadoc content

**Comment by romani** [comment]
fixed in other PR.

**Pull request closed without merging**
