### PR TITLE
config: update sevntu regression based on changes in sevntu

### PR DESCRIPTION
**Pull request by rnveach**
https://checkstyle.semaphoreci.com/jobs/b5111b2e-81b7-4a62-b1f3-acb6a9ce47ef#L661

> Unable to create Root Module: config {[https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-10.5.1-SNAPSHOT/config/checkstyle_non_main_files_checks.xml}](https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-10.5.1-SNAPSHOT/config/checkstyle_non_main_files_checks.xml%7D)

### CODE REVIEW

**Review by romani — APPROVED** [review]

**Comment by rnveach** [comment]
Missed adding `\` on the end for the new line.

**Comment by rnveach** [comment]
New failure
https://checkstyle.semaphoreci.com/jobs/f2cf2fc9-8cbc-42ca-9c09-5247686866db#L654
````
[ERROR] [checkstyle] [ERROR] /home/semaphore/checkstyle/.ci-temp/sevntu.checkstyle/.github/workflows/bump-cs-version.yml:28: curl command should start with --fail-with-body option [properCurlCommand] 01:08
[ERROR] [checkstyle] [ERROR] /home/semaphore/checkstyle/.ci-temp/sevntu.checkstyle/release.sh:151: curl command should start with --fail-with-body option [properCurlCommand] 01:08
[ERROR] [checkstyle] [ERROR] /home/semaphore/checkstyle/.ci-temp/sevntu.checkstyle/release.sh:162: curl command should start with --fail-with-body option [properCurlCommand] 01:08
[ERROR] [checkstyle] [ERROR] /home/semaphore/checkstyle/.ci-temp/sevntu.checkstyle/release.sh:169: curl command should start with --fail-with-body option [properCurlCommand]
````

**Comment by rnveach** [comment]
@romani Can `bump-cs-version.yml` get the curl update?

**Comment by romani** [comment]
GitHub action scripts, use not latest curl , we need to wait for 6 months to let GitHub update it's containers

**Comment by rnveach** [comment]
CI is passing now.

**Review by romani — APPROVED** [review]

**Pull request merged**
