### PR TITLE
Issue #6857: fix javadoc check on local variables

### PR DESCRIPTION
**Pull request by rnveach**
Issue #6857

Regression to come.

### CODE REVIEW

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/256/

There are new violations in `InvalidJavadocPosition` and surprisingly `SummaryJavadoc` and `JavadocParagraph` has violations being removed. Some javadoc parsing errors were also removed.

I didn't see anything wrong.

**Comment by romani** [comment]
code is good.
report awesome.

>There are new violations in InvalidJavadocPosition and surprisingly SummaryJavadoc and JavadocParagraph has violations being removed. Some javadoc parsing errors were also removed.

All items that I saw in report are good changes.

**Comment by romani** [comment]
@pbludov , please finalize review.

@rnveach , please rebase to resolve Travis.

**Comment by rnveach** [comment]
Rebased to pass CI.

**Pull request merged**
