### PR TITLE
config: removed unnecessary suppressions

### PR DESCRIPTION
**Pull request by rnveach**

### CODE REVIEW

**Comment by rnveach** [comment]
Not sure how 1 suppression turned out to be needed.

**Comment by rnveach** [comment]
I found the bug. I wasn't handling `|` correctly when nested with `(` and so it turned:
`<suppress checks="ClassDataAbstractionCoupling" files="(Checker|Main|CheckstyleAntTask|JavadocDetailNodeParser)\.java"/>`
into
`<suppress checks="ClassDataAbstractionCoupling" files="Main"/>`
instead of
`<suppress checks="ClassDataAbstractionCoupling" files="Main\.java"/>`

**Comment by romani** [comment]
What do you mean by bug ?

**Comment by rnveach** [comment]
I have 2 utilities that found these suppressions for me.
1) Flags suppressions as they are used and reports the rest as violations for not being used.
2) I have a utility that converts 1 suppression into multiple when it deals with regular expressions containing `|`.

The bug was found in the 2nd utility.

**Comment by romani** [comment]
Ok, squash commits and merge.

**Comment by rnveach** [comment]
squashed and merged as bbe73385003f57d21b4a2f2daa415105e43d0032

**Pull request closed without merging**
