### PR TITLE
Issue #6919: hide maven download text to prevent log overflow on Travis

### PR DESCRIPTION
**Pull request by romani**
Issue #6919

### CODE REVIEW

**Comment by romani** [comment]
this is an option .....
But it will require us to pull all "mvn ..." to travis.sh.
I think it is fine, we did not do this only we were lazy, and commands were short.

**Comment by romani** [comment]
I got better idea, instead of hacking ...
We just need to "mvn validate" in batch mode aand with novalidations profile if cache of maven is absent (in some prestep of Travis )

**Comment by rnveach** [comment]
> We just need to "mvn validate" in batch mode aand with novalidations profile if cache of maven is absent (in some prestep of Travis )

If downloads still occur in `novalidations profile`, then I am fine with that.

**Comment by rnveach** [comment]
Travis failure:
> [checkstyle] [ERROR] /home/travis/build/checkstyle/checkstyle/apache-maven-3.6.1-bin.zip:63739: Line should not be longer than 100 symbols [RegexpSingleline]

**Comment by romani** [comment]
>novalidations profile, then I am fine with that.

Yes, it will download all dependencies for execution, but execution will be skipped, so mvn execution will be quick in comparison to download.

**Comment by rnveach** [comment]
> execution will be skipped

It will still not skip the compile step, so there will be a bit of overhead. If compile fails, all CIs will show the same error then.

> batch mode aand with novalidations profile

We would still need `no-transfer-progress` as batch mode doesn't hide download text.

**Comment by romani** [comment]
> If compile fails, all CIs will show the same error then.

Yes, but it is ok, in such case, build is bad by all means.

>We would still need no-transfer-progress as batch mode doesn't hide download text.

We can try batch mode, if it doesn't hide logs, we will use maven 3.6.0  only to do this cache heating.

**Comment by romani** [comment]
moved to https://github.com/checkstyle/checkstyle/pull/6935

**Pull request closed without merging**
