### PR TITLE
Issue #8849: NoWhitespaceBeforeCheck String index out of range

### PR DESCRIPTION
**Pull request by nmancus1**
Issue #8849: NoWhitespaceBeforeCheck String index out of range

Fixed by simple modification to the text block lexer: changing tab width.

No modifications were made to the check, but we will do this anyway:
Diff Regression projects: https://gist.githubusercontent.com/nmancus1/e3988f8092d919b5cbe70f5359c4d9e8/raw/a0f6f5860f8025c19868061dee6e0e40960b992f/projects-to-test-on.properties

Diff Regression config: 
https://gist.githubusercontent.com/nmancus1/f5579d1ad36c5ebe441738ad9bf71d4a/raw/74a7356c0a6fc322b11013055046333136f0f3ae/NoWhitespaceBefore.xml

AST regression report: https://nmancus1.github.io/diff_whitespacebefore/

### CODE REVIEW

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
New AST for tab usage:
```
➜  nowhitespacebefore git:(issue-8849-nowhitespacebefore) cat -n InputNoWhitespaceBeforeTextBlocksTabIndent.java 
     1  //non-compiled with javac: Compilable with Java14
     2  package com.puppycrawl.tools.checkstyle.checks.whitespace.nowhitespacebefore;
     3  
     4  /* Config:
     5   * default
     6   */
     7  public class InputNoWhitespaceBeforeTextBlocksTabIndent {
     8  
     9      public static void main(String[] args) {}
    10  
    11      private void workingCheck() {
    12          String x = """
    13                  Some Text
    14                 """;
    15      }
    16  
    17      private void workingCheck_spaces() {
    18          String x = """
    19              Some Text
    20          """;
    21      }
    22  
    23      private void workingCheck_no_spaces() {
    24          String x = """
    25              Some Text
    26  """;
    27      }
    28  
    29      private void brokenCheck_space_before_tabs() {
    30          String x = """
    31              Some Text
    32                  """; // ok
    33      }
    34  
    35      private void brokenCheck_space_after_tabs() {
    36          String x = """
    37              Some Text
    38                   """; // ok
    39      }
    40  
    41      private void brokenCheck_just_tabs() {
    42          String x = """
    43              Some Text
    44                  """; // ok
    45      }
    46  }
➜  nowhitespacebefore git:(issue-8849-nowhitespacebefore) java -jar /home/nick/IdeaProjects/checkstyle/target/checkstyle-8.37-SNAPSHOT-all.jar -t InputNoWhitespaceBeforeTextBlocksTabIndent.java
PACKAGE_DEF -> package [2:0]
|--ANNOTATIONS -> ANNOTATIONS [2:57]
|--DOT -> . [2:57]
|   |--DOT -> . [2:46]
|   |   |--DOT -> . [2:39]
|   |   |   |--DOT -> . [2:28]
|   |   |   |   |--DOT -> . [2:22]
|   |   |   |   |   |--DOT -> . [2:11]
|   |   |   |   |   |   |--IDENT -> com [2:8]
|   |   |   |   |   |   `--IDENT -> puppycrawl [2:12]
|   |   |   |   |   `--IDENT -> tools [2:23]
|   |   |   |   `--IDENT -> checkstyle [2:29]
|   |   |   `--IDENT -> checks [2:40]
|   |   `--IDENT -> whitespace [2:47]
|   `--IDENT -> nowhitespacebefore [2:58]
`--SEMI -> ; [2:76]
CLASS_DEF -> CLASS_DEF [7:0]
|--MODIFIERS -> MODIFIERS [7:0]
|   `--LITERAL_PUBLIC -> public [7:0]
|--LITERAL_CLASS -> class [7:7]
|--IDENT -> InputNoWhitespaceBeforeTextBlocksTabIndent [7:13]
`--OBJBLOCK -> OBJBLOCK [7:56]
    |--LCURLY -> { [7:56]
    |--METHOD_DEF -> METHOD_DEF [9:4]
    |   |--MODIFIERS -> MODIFIERS [9:4]
    |   |   |--LITERAL_PUBLIC -> public [9:4]
    |   |   `--LITERAL_STATIC -> static [9:11]
    |   |--TYPE -> TYPE [9:18]
    |   |   `--LITERAL_VOID -> void [9:18]
    |   |--IDENT -> main [9:23]
    |   |--LPAREN -> ( [9:27]
    |   |--PARAMETERS -> PARAMETERS [9:34]
    |   |   `--PARAMETER_DEF -> PARAMETER_DEF [9:34]
    |   |       |--MODIFIERS -> MODIFIERS [9:34]
    |   |       |--TYPE -> TYPE [9:34]
    |   |       |   `--ARRAY_DECLARATOR -> [ [9:34]
    |   |       |       |--IDENT -> String [9:28]
    |   |       |       `--RBRACK -> ] [9:35]
    |   |       `--IDENT -> args [9:37]
    |   |--RPAREN -> ) [9:41]
    |   `--SLIST -> { [9:43]
    |       `--RCURLY -> } [9:44]
    |--METHOD_DEF -> METHOD_DEF [11:4]
    |   |--MODIFIERS -> MODIFIERS [11:4]
    |   |   `--LITERAL_PRIVATE -> private [11:4]
    |   |--TYPE -> TYPE [11:12]
    |   |   `--LITERAL_VOID -> void [11:12]
    |   |--IDENT -> workingCheck [11:17]
    |   |--LPAREN -> ( [11:29]
    |   |--PARAMETERS -> PARAMETERS [11:30]
    |   |--RPAREN -> ) [11:30]
    |   `--SLIST -> { [11:32]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [12:8]
    |       |   |--MODIFIERS -> MODIFIERS [12:8]
    |       |   |--TYPE -> TYPE [12:8]
    |       |   |   `--IDENT -> String [12:8]
    |       |   |--IDENT -> x [12:15]
    |       |   `--ASSIGN -> = [12:17]
    |       |       `--EXPR -> EXPR [12:19]
    |       |           `--TEXT_BLOCK_LITERAL_BEGIN -> """ [12:19]
    |       |               |--TEXT_BLOCK_CONTENT -> \n                Some Text\n                [12:22]
    |       |               `--TEXT_BLOCK_LITERAL_END -> """ [14:15]
    |       |--SEMI -> ; [14:18]
    |       `--RCURLY -> } [15:4]
    |--METHOD_DEF -> METHOD_DEF [17:4]
    |   |--MODIFIERS -> MODIFIERS [17:4]
    |   |   `--LITERAL_PRIVATE -> private [17:4]
    |   |--TYPE -> TYPE [17:12]
    |   |   `--LITERAL_VOID -> void [17:12]
    |   |--IDENT -> workingCheck_spaces [17:17]
    |   |--LPAREN -> ( [17:36]
    |   |--PARAMETERS -> PARAMETERS [17:37]
    |   |--RPAREN -> ) [17:37]
    |   `--SLIST -> { [17:39]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [18:8]
    |       |   |--MODIFIERS -> MODIFIERS [18:8]
    |       |   |--TYPE -> TYPE [18:8]
    |       |   |   `--IDENT -> String [18:8]
    |       |   |--IDENT -> x [18:15]
    |       |   `--ASSIGN -> = [18:17]
    |       |       `--EXPR -> EXPR [18:19]
    |       |           `--TEXT_BLOCK_LITERAL_BEGIN -> """ [18:19]
    |       |               |--TEXT_BLOCK_CONTENT -> \n            Some Text\n         [18:22]
    |       |               `--TEXT_BLOCK_LITERAL_END -> """ [20:8]
    |       |--SEMI -> ; [20:11]
    |       `--RCURLY -> } [21:4]
    |--METHOD_DEF -> METHOD_DEF [23:4]
    |   |--MODIFIERS -> MODIFIERS [23:4]
    |   |   `--LITERAL_PRIVATE -> private [23:4]
    |   |--TYPE -> TYPE [23:12]
    |   |   `--LITERAL_VOID -> void [23:12]
    |   |--IDENT -> workingCheck_no_spaces [23:17]
    |   |--LPAREN -> ( [23:39]
    |   |--PARAMETERS -> PARAMETERS [23:40]
    |   |--RPAREN -> ) [23:40]
    |   `--SLIST -> { [23:42]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [24:8]
    |       |   |--MODIFIERS -> MODIFIERS [24:8]
    |       |   |--TYPE -> TYPE [24:8]
    |       |   |   `--IDENT -> String [24:8]
    |       |   |--IDENT -> x [24:15]
    |       |   `--ASSIGN -> = [24:17]
    |       |       `--EXPR -> EXPR [24:19]
    |       |           `--TEXT_BLOCK_LITERAL_BEGIN -> """ [24:19]
    |       |               |--TEXT_BLOCK_CONTENT -> \n            Some Text\n [24:22]
    |       |               `--TEXT_BLOCK_LITERAL_END -> """ [26:0]
    |       |--SEMI -> ; [26:3]
    |       `--RCURLY -> } [27:4]
    |--METHOD_DEF -> METHOD_DEF [29:4]
    |   |--MODIFIERS -> MODIFIERS [29:4]
    |   |   `--LITERAL_PRIVATE -> private [29:4]
    |   |--TYPE -> TYPE [29:12]
    |   |   `--LITERAL_VOID -> void [29:12]
    |   |--IDENT -> brokenCheck_space_before_tabs [29:17]
    |   |--LPAREN -> ( [29:46]
    |   |--PARAMETERS -> PARAMETERS [29:47]
    |   |--RPAREN -> ) [29:47]
    |   `--SLIST -> { [29:49]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [30:8]
    |       |   |--MODIFIERS -> MODIFIERS [30:8]
    |       |   |--TYPE -> TYPE [30:8]
    |       |   |   `--IDENT -> String [30:8]
    |       |   |--IDENT -> x [30:15]
    |       |   `--ASSIGN -> = [30:17]
    |       |       `--EXPR -> EXPR [30:19]
    |       |           `--TEXT_BLOCK_LITERAL_BEGIN -> """ [30:19]
    |       |               |--TEXT_BLOCK_CONTENT -> \n            Some Text\n \t\t [30:22]
    |       |               `--TEXT_BLOCK_LITERAL_END -> """ [32:3]
    |       |--SEMI -> ; [32:6]
    |       `--RCURLY -> } [33:4]
    |--METHOD_DEF -> METHOD_DEF [35:4]
    |   |--MODIFIERS -> MODIFIERS [35:4]
    |   |   `--LITERAL_PRIVATE -> private [35:4]
    |   |--TYPE -> TYPE [35:12]
    |   |   `--LITERAL_VOID -> void [35:12]
    |   |--IDENT -> brokenCheck_space_after_tabs [35:17]
    |   |--LPAREN -> ( [35:45]
    |   |--PARAMETERS -> PARAMETERS [35:46]
    |   |--RPAREN -> ) [35:46]
    |   `--SLIST -> { [35:48]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [36:8]
    |       |   |--MODIFIERS -> MODIFIERS [36:8]
    |       |   |--TYPE -> TYPE [36:8]
    |       |   |   `--IDENT -> String [36:8]
    |       |   |--IDENT -> x [36:15]
    |       |   `--ASSIGN -> = [36:17]
    |       |       `--EXPR -> EXPR [36:19]
    |       |           `--TEXT_BLOCK_LITERAL_BEGIN -> """ [36:19]
    |       |               |--TEXT_BLOCK_CONTENT -> \n            Some Text\n\t\t  [36:22]
    |       |               `--TEXT_BLOCK_LITERAL_END -> """ [38:3]
    |       |--SEMI -> ; [38:6]
    |       `--RCURLY -> } [39:4]
    |--METHOD_DEF -> METHOD_DEF [41:4]
    |   |--MODIFIERS -> MODIFIERS [41:4]
    |   |   `--LITERAL_PRIVATE -> private [41:4]
    |   |--TYPE -> TYPE [41:12]
    |   |   `--LITERAL_VOID -> void [41:12]
    |   |--IDENT -> brokenCheck_just_tabs [41:17]
    |   |--LPAREN -> ( [41:38]
    |   |--PARAMETERS -> PARAMETERS [41:39]
    |   |--RPAREN -> ) [41:39]
    |   `--SLIST -> { [41:41]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [42:8]
    |       |   |--MODIFIERS -> MODIFIERS [42:8]
    |       |   |--TYPE -> TYPE [42:8]
    |       |   |   `--IDENT -> String [42:8]
    |       |   |--IDENT -> x [42:15]
    |       |   `--ASSIGN -> = [42:17]
    |       |       `--EXPR -> EXPR [42:19]
    |       |           `--TEXT_BLOCK_LITERAL_BEGIN -> """ [42:19]
    |       |               |--TEXT_BLOCK_CONTENT -> \n            Some Text\n\t\t [42:22]
    |       |               `--TEXT_BLOCK_LITERAL_END -> """ [44:2]
    |       |--SEMI -> ; [44:5]
    |       `--RCURLY -> } [45:4]
    `--RCURLY -> } [46:0]
```

This doesn't affect the printed AST's that we already tested against in `AstRegressionTest.java`, since they were all written with no tabs.

**Review by romani — CHANGES_REQUESTED** [review]
Please create one simple input with one tab only and compare it with AST tree, to clearly see that column for node is correct

**Comment by nmancus1** [comment]
> Please create one simple input with one tab only and compare it with AST tree, to clearly see that column for node is correct

```
➜  text-blocks-grammar /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 StringTest.java                    
Note: StringTest.java uses preview language features.
Note: Recompile with -Xlint:preview for details.

➜  text-blocks-grammar cat StringTest.java                                                                                    
public class StringTest {
    String test = """
        """;
}// ^ one tab

➜  text-blocks-grammar java -jar /home/nick/IdeaProjects/checkstyle/target/checkstyle-8.37-SNAPSHOT-all.jar -t StringTest.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> StringTest [1:13]
`--OBJBLOCK -> OBJBLOCK [1:24]
    |--LCURLY -> { [1:24]
    |--VARIABLE_DEF -> VARIABLE_DEF [2:4]
    |   |--MODIFIERS -> MODIFIERS [2:4]
    |   |--TYPE -> TYPE [2:4]
    |   |   `--IDENT -> String [2:4]
    |   |--IDENT -> test [2:11]
    |   |--ASSIGN -> = [2:16]
    |   |   `--EXPR -> EXPR [2:18]
    |   |       `--TEXT_BLOCK_LITERAL_BEGIN -> """ [2:18]
    |   |           |--TEXT_BLOCK_CONTENT -> \n\t [2:21]
    |   |           `--TEXT_BLOCK_LITERAL_END -> """ [3:1]
    |   `--SEMI -> ; [3:4]
    `--RCURLY -> } [4:0]
```

**Comment by romani** [comment]
Please move it to Input of grammar tests

**Comment by nmancus1** [comment]
>Please move it to Input of grammar tests

Done.

**Review by romani — APPROVED** [review]
Ok to merge

**Review by pbludov — APPROVED** [review]

**Pull request merged**
