### PR TITLE
Severity Name Upper/Lower Case conversation fix

### PR DESCRIPTION
**Pull request by precoder**
Conversation of Upper/Lower Case relies on Localization settings of the running Machine.
A possible result of this situation is referenced in:
http://sourceforge.net/p/eclipse-cs/bugs/295/

### CODE REVIEW

**Comment by romani** [comment]
@precoder , thanks a lot for pointing to the problem.

The problem is not only in this file, almost all usages of toUpperCase and toLowerCase.
Please let me know if you have time and desire to fix problem completely (in all files) and verify that it works on Turkish side.

if "yes" we need to create a issue with steps to reproduce problem from CLI, update all files(simple task) and create some UTs to ensure problem will not happen again.

if "no", it is ok, and we still appreciate and value your help. I will do merge right away and rest of potentially problematic cases I will put in a development queue.

**Comment by precoder** [comment]
@romani,
I am also affected from the problem, therefore I would be happy to help you and contribute to an open source project.
I can work on the Issue at Weekends and other free time.

I can reproduce the problem with my Eclipse with the check style plug-in as same as in the link.
For unit tests and reproducing without Eclipse plugin I need to take a further look at code in checkstyle repository.

Just to give an opinion, I made a rough investigation for the toUpperCase and toLowerCase usages in repository. They are totally, approximately 400 references to these methods, but maybe all of them do not need to be modified.

**Comment by romani** [comment]
> I can work on the Issue at Weekends and other free time.

this is how whole checkstyle is build :) .

> I can reproduce the problem with my Eclipse with 

Lets reproduce you problem from CLI - http://checkstyle.sourceforge.net/cmdline.html#Download_and_Run
just use config from eclispse-cs.  That will help you understand how to fix that and test that.

> They are totally, approximately 400 references to these methods

Let me guide you:

lower:
src/main/java/com/puppycrawl/tools/checkstyle/api/Scope.java
src/main/java/com/puppycrawl/tools/checkstyle/api/SeverityLevel.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java

upper:
src/main/java/com/puppycrawl/tools/checkstyle/api/Scope.java
src/main/java/com/puppycrawl/tools/checkstyle/api/SeverityLevel.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractOptionCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java

generated sources and test classes that have to be ignored:
src/test/resources/
target/generated-sources/antlr/
target/test-classes/com/

**Comment by precoder** [comment]
I can reproduce the problem from CLI. I have executed the following commands: 

git clone https://github.com/checkstyle/checkstyle.git
cd checkstyle
mvn clean package -Passembly
java -Duser.language=tr -Duser.country=TR -jar target/checkstyle-6.6-SNAPSHOT-all.jar -c /google_checks.xml src/main/java

I think we can reproduce the problem in unit tests easily by setting the Default Locale to a language (ex:TR) that causes this problem during setup and restore back during tear down.

Build in google_check configuration has
<property name="severity" value="warning"/>
setting, which causes this parsing problem during upper/lower case conversation. 
Build in sun_checks does not seems to effected from this situation.

**Comment by romani** [comment]
@precoder , release 6.6 will be on that weekends, do you have time to finish that PR ?

**Comment by precoder** [comment]
@romani ,
I have done changes for the artifacts, those you mentioned in your comment.
I have also enhanced two test classes with additional test methods, which are  only calling existing methods with different localisations. (Currently I found only TR for this upper / lower case problem.)

**Comment by romani** [comment]
@precoder, please squash all commits in one.

**Comment by romani** [comment]
please revert commit https://github.com/checkstyle/checkstyle/commit/d8f642d4e2c8b28388743d9a93115d99fcbb3ae9 and make sure that "mvn clean verify" pass without failures.

**Comment by precoder** [comment]
Seems like I have a history ordering problem.
I actually did not squashed commits from different history fractions.
Do you have any idea to do this?

**Comment by romani** [comment]
hmm not sure what you did, the simples approach will be:
1) backup your changes to separate folder
2) remove your fork, do fork again and https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/Development-workflow-with-Git%3A-Fork%2C-Branching%2C-Commits%2C-and-Pull-Request

**Comment by precoder** [comment]
Closing pull request due to conflicts in commit history.

**Comment by romani** [comment]
as you close a PR, please create issue with all details that you provided in that PR, and make ref to that issue from commit (that will help to track why that change was make)

**Pull request closed without merging**
