### PR TITLE
infra: run one checker to maintain windows compatibility

### PR DESCRIPTION
**Pull request by nrmancuso**
In order to prove resolution of #12221 and https://github.com/checkstyle/checkstyle/issues/12243, we should keep one checker execution in windows CI. I have added `|| VER>NUL` to the end of the checker command to allow checker execution to fail and CI still pass, until we resolve the above issues. `|| VER>NUL` should be removed in the scope of the above issues.

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by nrmancuso** [comment]
Link to passing checker build in windows: https://cirrus-ci.com/task/4578533786779648

Checker is failing, but execution of checker works

**Comment by rnveach** [comment]
> execution of checker works

@nrmancuso My concern is checker run is not producing anything. There are no new errors, and everything is being removed. It is almost like checker is not running at all and we are saying to remove all violations.

How can we say checker is working in this situation?

**Review by rnveach — CHANGES_REQUESTED** [review]
Just saying, I think my above comment is a blocker until it is decided otherwise.

**Comment by romani** [comment]
I thought Nick is just doing initial CI work to let us fix windows and quickly remove hack in this command to enable it.

We kind of merging infra change that should be easier activated when we ready for win support

**Comment by rnveach** [comment]
Unless @nrmancuso has something else, it will continue to not function even if groovy supports Windows fully. There is no output from Checker at all. The execution is not being skipped, it is just not happening.

**Comment by nrmancuso** [comment]
> Unless @nrmancuso has something else, it will continue to not function even if groovy supports Windows fully. There is no output from Checker at all. The execution is not being skipped, it is just not happening.

From the output, we can see that groovy script runs. This was really my only intention; from the execution time, it looks like checker based compilation is not working, and of course, we still have the maven bug that we are trying to work around for windows. We cannot claim "windows support" until this job runs exactly as it does in Linux CI. I am not sure how `echo` works in windows, but I have turned it on in the script now, hopefully we can get some more detailed output to figure out why checker compilation is not happening.

**Comment by rnveach** [comment]
@nrmancuso If it is unclear what the issue is, lets report this to Checker. I am ok to merge this it if we create a new issue that it is not working in cirrus and to follow up with Checker.

**Comment by nrmancuso** [comment]
> @nrmancuso If it is unclear what the issue is, lets report this to Checker. I am ok to merge this it if we create a new issue that it is not working in cirrus and to follow up with Checker.

I would like to debug a bit more before we do this.

**Comment by rnveach** [comment]
> I am not sure how echo works in windows, but I have turned it on in the script now

Echo just prints the commands being used. It doesn't do anything different in terms of maven execution. I believe it is on by default.
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/echo

**Comment by nrmancuso** [comment]
Ok, run of checker without script (just maven) and debug on results in:
```
[WARNING] Unable to autodetect 'javac' path, using 'javac' from the environment.
```

I wonder if we use other javac that we might not pick up all annotation processors or something. I also suspect that JAVA_HOME variable is not set by choco install, this could be a problem as well. @rnveach thoughts?

**Comment by nrmancuso** [comment]
Trying to set the `JAVA_HOME` environment variable, I have tried the following and none have worked:
```
JAVA_HOME="C:\Program Files\OpenJDK\jdk-17"
set JAVA_HOME="C:\Program Files\OpenJDK\jdk-17"
set JAVA_HOME "C:\Program Files\OpenJDK\jdk-17"
set JAVA_HOME = "C:\Program Files\OpenJDK/jdk-17"
```
Also in the cirrus environment variables: `JAVA_HOME: "C:\Program Files\OpenJDK\jdk-17"`

**Comment by nrmancuso** [comment]
I am closing this PR. Until our Checker script works reliably in Windows, I do not see value in continuing work here. Anyone is welcome to take over/ reuse code.

**Pull request closed without merging**
