### PR TITLE
Issue #13321: Kill mutation for BlockCommentPosition

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for BlockCommentPosition

------

# Mutations 
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/config/pitest-suppressions/pitest-utils-suppressions.xml#L12-L19

-----

# Explaination 
Loops run 1 time more

-------

# Regression 

Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/87515e8_2023123322/reports/diff/index.html

Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/87515e8_2023161333/reports/diff/index.html

-----

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/0582e64583a72448d7460e5e14ff1ac2/raw/ba487c241253f94d16b864e2556d956285a27727/BlockUtil.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/360a95ed7bb60d7a0956e531199d484c4d6f6617/test-projects.properties
Report label: R-2

### CODE REVIEW

**Comment by romani** [comment]
Failing CI restarted.
Please share reports.

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/87515e8_2023123322/reports/diff/intellij-community/index.html.

Null pointer exception is expected because their is no method body and it is a class.

**Comment by Kevin222004** [comment]
@romani report geneated

**Review by romani — APPROVED** [review]
Ok to merge.


Please add this PR to our issue of minor bad effects.

**Review by rdiachenko — APPROVED** [review]
lgtm

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

**Pull request merged**
