### PR TITLE
Fix PackageDeclaration check for files with comments only. #1149

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
1) please squash all commits in one, I do not see a reason to be them in separate.

2) 
```
> +        if (node == null) {
+            // do not check files without any nodes
+            return;
+        }
```

please move that logic out of checkTree to checkFile. That decision could be done ones and t belong to upper level of function.

3)
> ```final int lineNumber;```

please make assignment to DEFAULT_LINE_NUMBER as declaration place, and remove extra branch in IF.

**Comment by mkordas** [comment]
1) I try to keep commit message under 70 characters and sometimes I make multiple commits to explain reason for each change separately. In this case commits were describing that test was added to reveal NPE in the check, then this newly added input file revealed NPE in other test that uses all the files and the last commit was just fixing the check.
But OK, commits are squashed.
2) Thanks a lot for this hint, now it should be much cleaner.
3) I did it in two branches to mark variable as `final` and favour immutability. But OK, 
I've applied your comment - it's less code.

**Comment by romani** [comment]
> I try to keep commit message under 70 characters and sometimes I make multiple commits to explain reason for each change separately

There you need to distingush a rea > I try to keep commit message under 70 characters and sometimes I make multiple commits to explain reason for each change separately

There you need to distingush a reason of why you do multiple commits:
1) to ease PR review and merge 
2) to ease investigation of code changes that will happen somewhere in future (whole context of issue will be fogotten)

 in first case - you can put all that to PR description and it required only on moment of review
 
  in second case - you show that your change was attomic and related to the same problem/issue. 
  There is no intermediate commits that could fail a build.
  
   I prefer second case always.

> I did it in two branches to mark variable as final and favour immutability

in that case you need to use short form of IF ( final int value = (condition) ? smth : smth ).
But I personally do not like that as it is not human friendly form by its syntax, and by avoiding mutability problem you might introduce another problem. In my experience focus on mutability should is OK only when method is long and definition of variable is far from its usage. In other case "final" keyword is just a distraction and useless - as user will remove that keyword as soon as he need to change that variable.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
