### PR TITLE
Issue #6207: Add XPath IT Regression for VisibilityModifier

### PR DESCRIPTION
**Pull request by Lmh-java**
Part of Issue #6207. Add XPath Regression Test for VisibilityModifier

Documentation of VisibilityModifier: https://checkstyle.sourceforge.io/checks/design/visibilitymodifier.html

Hi, I am not sure whether these tests are sufficient enough to cover VisibilityModifier, could you please have a look.

Currently, there are tests for
1. field with default modifier
2. field with the annotation
3. field inside an anonymous class
4. field inside an inner class

### CODE REVIEW

**Comment by MANISH-K-07** [comment]
> Hi, I am not sure whether these tests are sufficient enough to cover VisibilityModifier, could you please have a look.

@Lmh-java ,
You can determine this from the input files of out `src/test` directory.
It is conventional and recommended to have one test-input here for each aspect that you find in above mentioned directory.

**Review by MANISH-K-07 — COMMENTED** [review]
> Hi, I am not sure whether these tests are sufficient enough to cover VisibilityModifier, could you please have a look.

@Lmh-java ,
You can determine this from the input files of out `src/test` directory.
It is conventional and recommended to have one test-input here for each aspect that you find in above mentioned directory.

**Comment by Lmh-java** [comment]
Got it! Thanks for answering.

**Review by romani — APPROVED** [review]
Ok to merge.

Just to cover xpath of this Check , it is enough.

**Pull request merged**
