### PR TITLE
doc: Updated demonstrative images on intellij documentation page

### PR DESCRIPTION
**Pull request by SteLeo1602**
Updated a couple of demonstrative images on the IntelliJ doc page, related to **organizing imports** and **inspections** instructions as a replacement to current with already obsolete program interface or insufficiently supplemented/specified in my opinion.

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
GitHub, generate website

**Comment by MANISH-K-07** [comment]
@SteLeo1602 , these images of interface are wrt which release of IDEA?

**Review by nrmancuso — APPROVED** [review]

**Comment by nrmancuso** [comment]
Thanks a lot @SteLeo1602 !

**Comment by SteLeo1602** [comment]
> @SteLeo1602 , these images of interface are wrt which release of IDEA?

I used the 2023.3.5 date release of IDEA to make images on if that's what you mean. So far it has a fresh interface look that is consistent with subsequent releases.

**Pull request merged**
