### PR TITLE
New option to print AST with comment nodes

### PR DESCRIPTION
**Pull request by baratali**
Issue  #652.

New option has been added. Also, a long option name added for ``-t`` option:
```
  -t,--tree               Print Abstract Syntax Tree(AST) of the file
  -T,--treeWithComments   Print Abstract Syntax Tree(AST) of the file including comments
```

Apache CLI doesn't support ``-`` character in option names, so new name is in CamelCase. (Apache CLI uses [Character.isJavaIdentifierPart](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isJavaIdentifierPart(char)) to validate option names)

Examples:
```java
/**My Class*/
class A {
        // no code
}
```
```
java -jar target/checkstyle-6.16-SNAPSHOT-all.jar --tree MyClass.java
CLASS_DEF -> CLASS_DEF [2:0]
|--MODIFIERS -> MODIFIERS [2:0]
|--LITERAL_CLASS -> class [2:0]
|--IDENT -> A [2:6]
`--OBJBLOCK -> OBJBLOCK [2:8]
    |--LCURLY -> { [2:8]
    `--RCURLY -> } [4:0]
```
```
java -jar target/checkstyle-6.16-SNAPSHOT-all.jar --treeWithComments MyClass.java
CLASS_DEF -> CLASS_DEF [2:0]
|--MODIFIERS -> MODIFIERS [2:0]
|--BLOCK_COMMENT_BEGIN -> /* [1:0]
|   |--COMMENT_CONTENT -> *My Class [1:2]
|   `--BLOCK_COMMENT_END -> */ [1:10]
|--LITERAL_CLASS -> class [2:0]
|--IDENT -> A [2:6]
`--OBJBLOCK -> OBJBLOCK [2:8]
    |--LCURLY -> { [2:8]
    |--SINGLE_LINE_COMMENT -> // [3:1]
    |   `--COMMENT_CONTENT ->  no code\r\n [3:3]
    `--RCURLY -> } [4:0]

```

### CODE REVIEW

**Comment by romani** [comment]
good.

but please update xdoc file to let users see how to use this option at our web site - https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/cmdline.xml.vm .

**Comment by romani** [comment]
Just an idea: what if we will use "-T" for full tree of java file ? So it will some how logical "-t" tree without comments, "-T" full tree of everithing that java file has.

**Comment by romani** [comment]
1)
> treeComment

please make it "treeWithComments", it is not that long but self descriptive

2)
```
 +                    + " -r,--treeComment   Print Abstract Syntax Tree(AST) of the file including%n"
+                    + "                    comments%n"
+                    + " -t,--tree          Print Abstract Syntax Tree(AST) of the file%n"
```

please put "-t" above "-T".
fix "-r" to "-T"
can you make description of "-T" on single line ? or you have problem with line length.

**Comment by baratali** [comment]
1) Done
2) It's weird, gitk and github show different changes. Looks like github incorrectly shows commits. I already changed ``-r`` to ``-T`` in that file (or else unit tests would have failed). 

> can you make description of "-T" on single line ?

Width of CLI help has been extended up to 100 characters.

3) Done

**Comment by romani** [comment]
github works fine , you have 3 commits:
```
commit ae322653b2104949033f5d69ee1b00b89652eb2d
Author: Baratali Izmailov <barataliba@gmail.com>
Date:   Tue Feb 23 14:31:45 2016 +0000

    Issue #652: Option renamed. CLI help width extended.

commit 351fcad0037891b5ce38364cc7221c095e24fd1a
Author: Baratali Izmailov <barataliba@gmail.com>
Date:   Sat Feb 20 19:56:11 2016 +0000

    Issue #652: Unit tests for print AST with comments

commit 9fdb62cae03c4e7738fd93e9a5aaca8ebba61b84
Author: Baratali Izmailov <barataliba@gmail.com>
Date:   Thu Feb 18 00:44:28 2016 +0000

    Issue #652: New option to print AST with comment nodes

```

redo them to have 2 commits or 1.

**Comment by baratali** [comment]
squashed to one commit

**Comment by romani** [comment]
merged as FF

**Pull request merged**
