### PR TITLE
Issue #9394: update example of AST for TokenTypes.ARRAY_DECLARATOR

### PR DESCRIPTION
**Pull request by vivek286**
"Closes: #9394 "

WhatsApp Image 2021-03-15 at 8 51 34 PM

Expected update example of AST for TokenTypes.ARRAY_DECLARATOR
    
WhatsApp Image 2021-03-15 at 8 58 17 PM

### CODE REVIEW

**Comment by anshuman10398** [comment]
@vivek286 
[https://github.com/checkstyle/checkstyle/pull/9431](url) 
Refer to this PR and change your PR description accordingly.

**Comment by vivek286** [comment]
How can i resubmit my commit for checks?

**Comment by anshuman10398** [comment]
*git commit --amend -m "Issue #9394: updated example of AST for
TokenTypes.ARRAY_DECLARATOR"*
*git push -f origin <branch_name>*

**Comment by nmancus1** [comment]
@vivek286 please close this PR now that you have opened https://github.com/checkstyle/checkstyle/pull/9605.

**Pull request closed without merging**
