### PR TITLE
Issue #3048: ParenPad now correctly evaluates precedence parens

### PR DESCRIPTION
**Pull request by subkrish**
Issue #3048

### CODE REVIEW

**Comment by subkrish** [comment]
Because of the changes I made in ParenPadCheck.java, do I also make the necessary changes in the input files of the ParenPadCheckTest.java file?

**Comment by Vladlis** [comment]
1) you should not change input files, but should change tests instead if changes make sense
2) diff report is required, point 5: https://github.com/checkstyle/checkstyle/wiki/PR-rules

**Comment by subkrish** [comment]
Should changes also be made in 'it' folder for the 'ParenPadTest.java' file? It is also causing build errors.

**Comment by Vladlis** [comment]
yes, but make sure your changes are not false negative/positives

**Comment by subkrish** [comment]
I have made the changes in 'it' as well but when I try to compile it I am getting the following error:

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.093 sec <<< FAILURE! - in com.google.checkstyle.test.chapter4formatting.rule462horizontalwhitespace.ParenPadTest
methodParenTest(com.google.checkstyle.test.chapter4formatting.rule462horizontalwhitespace.ParenPadTest)  Time elapsed: 0.093 sec  <<< FAILURE!
java.lang.AssertionError: unexpected warnings [112] expected:<0> but was:<1>
	at com.google.checkstyle.test.chapter4formatting.rule462horizontalwhitespace.ParenPadTest.methodParenTest(ParenPadTest.java:114)

**Comment by romani** [comment]
@subkrish ,
Tests are still failing - please resolve. CI should be green.

**Comment by romani** [comment]
Test case from issue need to be added to one of our input file. In addition please add more test cases

**Comment by subkrish** [comment]
Here is the diff report for the projects: https://subkrish.github.io/

**Comment by subkrish** [comment]
Should I just add it to an existing input file like 'InputParenPad.java'?

**Comment by romani** [comment]
> Should I just add it to an existing input file like 'InputParenPad.java'?

yes. And please add a bit more similar test cases.

**Comment by subkrish** [comment]
Sorry for that silly mistake. I have not done this previously. I will update the report accordingly.

**Comment by subkrish** [comment]
Here is the updated diff report: https://subkrish.github.io/

**Comment by romani** [comment]
There is a nuance ....

In Check description the there are no details that parentheses of user grouping should not be validated. 
If you take a look at https://subkrish.github.io/pmd/xref/Users/subbudantu/contribution/checkstyle-tester/repositories/pmd/pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/symboltable/MethodScope.java.html#L64
> `return ( (AbstractPLSQLNode) node.jjtGetChild(1) ) .getCanonicalImage();`

but there are code at line 40 in the same file:
> `((ASTName) n).setNameDeclaration(decl);`

So user intention was to have no spaces when parentheses are used just to visually group something - `((ASTName) n)`
`checker.setModule((Thread.currentThread()).getContextClassLoader());` --- extra parentheses but code is still compilable so it might mean smth for user.  
......

So probably user want to differentiate padding for method parentheses and for grouping, let me review initial issue and what user is actually want.

Hibernate-orm is definitely using http://checkstyle.sourceforge.net/property_types.html#parenPad as "space" , so by your report you just raised issues on all code.

**Pull request closed without merging**
