### PR TITLE
config: bump guava version

### PR DESCRIPTION
**Pull request by rnveach**
Continuation of #3527.

### CODE REVIEW

**Comment by rnveach** [comment]
TC is not listed in CI.

**Comment by rnveach** [comment]
@romani No change, TC still fails with the same violations.
We don't have to update TC config do we?

**Comment by rnveach** [comment]
https://confluence.jetbrains.com/display/TCD10/IntelliJ+Platform+Plugin+Compatibility
I don't think TC is on IDEA 2016.3 yet.

**Comment by romani** [comment]
on local there is no "Result of method call ignored" violations on IntelijIdea 2016.3, but there are hundred of new violations :) looks like as TC upgrade to new inspections, we will notice this by failed TC :).
Lets close this PR for now again.

**Comment by romani** [comment]
reopened for TC support review

**Comment by romani** [comment]
Vladislav Rassokhin­ (TeamCity)­
Dec 1, 19:13 MSK ­

Hello,­

Next teamcity.jetbrai­ns.com update would m­ost probably have IDE­A 2016.3 as inspectio­ns engine.

from Logs (­https://teamcity.jetb­rains.com/viewLog.htm­l?buildId=934639&buil­dTypeId=Checkstyle_Id­eaInspectionsPullRequ­est&tab=buildLog#_sta­te=221,24,5&focus=5) I do not see what v­ersion of IntellijIde­a is used. It would b­e good to print versi­on too.

FYI ­Here's line with that­ information - https://teamcity.jetbrains.com/viewLog.html?buildId=934639&buildTypeId=Checkstyle_IdeaInspectionsPullRequest&tab=buildLog&state=221%2C24%2C5#_state=221,24,5&focus=224 :­

Starting up IntelliJ ­IDEA 2016.2 (build IU­-162.1121.32) ...done­.

Vladislav Rassokhin­
Java developer (Team­City)
JetBrains­

**Comment by romani** [comment]
I close this PR for now, as update come to teamcity we will notice that, as new violations appear

**Pull request closed without merging**
