### PR TITLE
Issue #7107: remove deprecated constructors for DefaultLogger

### PR DESCRIPTION
**Pull request by rnveach**
Issue #7107

### CODE REVIEW

**Comment by rnveach** [comment]
@romani IDEA constantly keeps timing out now.

**Comment by rnveach** [comment]
To make TC pass requires changes in #7106

**Comment by rnveach** [comment]
Rebased since required PR is merged.

**Comment by romani** [comment]
TC still have issue, @rnveach , please take a look.

**Comment by rnveach** [comment]
TC is resolved.

**Pull request merged**
