### PR TITLE
Issue #3976: Split and Organize Checkstyle inputs by Test for EmptyForIteratorPad

### LINKED ISSUE #3976: Split and Organize Checkstyle inputs by Test for EmptyForIteratorPad
subtask of #3891 .

do a copy of all test input files to separate folder for EmptyForIteratorPad .
Not any other Check should use new inputs.

### PR DESCRIPTION
**Pull request by shivanshsoni**
fixes #3976

### CODE REVIEW

**Comment by rnveach** [comment]
@shivanshsoni You do not need to close and open a brand new PR. Just force push to the existing branch and the PR and CI will see the changes and automatically update.

CI is still failing and you still have multiple commits.

**Comment by shivanshsoni** [comment]
EmptyForInitializerPadCheckTest fails bcoz i have removed input for whitespace So, what should i do?

**Comment by romani** [comment]
this input is used in few other Tests, you can not do move of it, you need to do copy.

**Comment by rnveach** [comment]
> my commit message contains only one line of text then why it is failing at this?

@shivanshsoni Like I stated before, you need to squash all commits into 1. Then make sure that commit has only 1 line of text.
As it is right now, one of your 3 commits does have more than one line of text. CI will examine all your commits, not just the last one.

**Comment by shivanshsoni** [comment]
I squashed all commits into one

**Comment by shivanshsoni** [comment]
@rnveach This is last time I am closing this pull request as my git shell is not responding to this branch.

**Pull request closed without merging**
