### PR TITLE
Fix ThrowsCount check violations in Checkstyle code. #945

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
I do not agree that limit to 2 is reasonable, especially as a fix we hide more certain exception type to more general - it is not correct. If we follow that approach we could collapse all Checks to the most general that will not do any good to code.

Main idea of Check is to control the most weird cases of 10 throws or .... .
Default value of Check is main problem - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheck.java#L54 , we need to run this Check over some library like openJDK and define new default value as min from that code (that could be done as separate issue).

So for our code please get a "max" from code that we have now.

**Comment by romani** [comment]
that PR need rebase.

**Comment by mkordas** [comment]
The main point of this chek in the current form with default valule for `max` set to `1` are **security** concern (especially if using Java <7 when multi-catch was not available), keeping caller complexity small and following **Single Responsiblity Principle** Please see discussion on http://programmers.stackexchange.com/questions/263874/why-shouldnt-a-method-throw-multiple-types-of-checked-exceptions

So for me setting `max` to `2` is only intermediate step and we should pursue to have just one checked exception per method. Two additional chanes in this check are needed though:
* option to verify only public methods
* do not verify overridden methods (#1085)

I'll rebase PR whenever we'll reach agreement what needs to be done.

**Comment by romani** [comment]
thanks for a link, so there is my first part of comments:

http://programmers.stackexchange.com/questions/263874/why-shouldnt-a-method-throw-multiple-types-of-checked-exceptions

> This makes those exceptions fully part of the API of the method.

that is good phrase but, it is too general with reference to API. 
if method is not part of API - that rule does not work.

> Rationale: Exceptions form part of a method's interface. Declaring a method to throw too many differently rooted exceptions makes exception handling onerous and leads to poor programming practices such as writing code like catch(Exception ex).

"Too many" lead to catch Exception - that is true, so too many need to be defined and it is not  ">1" throws amount for sure.

> code like catch(Exception ex)

In this post slightly related problems are binded as dependent - itcorrect !
catch-all and trow too much are different problems! and should be considered separately.

It is already know fact that Checked exception was a design mistake, non of modern language have checked exceptions.
So Checked exceptions is legacy that we will use for long time just to keep java compatibility.
We could go a Springframework way - frap all chekcked exceptions to non-checked and forget about throws at all.

I am more an more in favour of catching Exception in static methods, where are i am sure that there is not side effect, so all exceptions are sign of conversion failure and nothing else.


>  The first approach violates DRY. Multiple blocks doing the same thing, again and again - once for each exception.

Such fanatic apprach will never do any good for design, and will create a lot of dependecies that wil lcause more probelms than simple copy-paste. Similar code is unaviodable , but it does not mean that we need to generalize all in speasial methods, ...... .
Reminder of a reasons of removing DuplicateCodeCheck from Checkstyle :) . 

>  The first approach violates DRY. Multiple blocks doing the same thing, again and again - once for each exception

When we look at a exceptions, the main rule is "Who will be able to hadle that exception? To what level of code should go checked/exact exception and on what level RuntimeException-like should wrap it ? "


> not only do you have to put in a lot more boilerplate code to support it as you move to higher-level methods

Good phrase in general, but it is up to implementation to deside where is that border when chekced exception should be wrapped to non-checked, to avoid a lot of throws.

> Single Responsibility

So, when it comes to reducing amount of throws by reason of Single Responsibility, you need to wrap all checked righaway and do not use throws at all. In Other case you have to in each level up method do catch all innner exception and produce new exception - that force you to forget about making decision on level that have to deal with all exception. I do not like that fanatic design enforcement (in in method is one enty point, so having multiple places to handle exceptions that terminate whole execution is not right).

**Comment by romani** [comment]
final part :

your changes are just to make Check happy, and not addressed to fix a design problem.  So lets go through all changes case by case:

1) 
```
-    protected AuditListener[] getListeners() throws ClassNotFoundException,
-            InstantiationException, IllegalAccessException, IOException
+    protected AuditListener[] getListeners() throws ReflectiveOperationException, IOException
```

update that method to "private" as at this level we do not know how to manage that errors and lets caller will handle that.
Check should ignore private methods as it does not harm code of others classes by separate option.

2)
```
-    public static void main(String... args) throws UnsupportedEncodingException,
-            CheckstyleException, FileNotFoundException
+    public static void main(String... args) throws CheckstyleException, IOException
```

that is end/entry point , so nobody will be harmed by that throws. Check need to skip "main" methods by separate option.

3)
```
-    private static int runCheckstyle(CliOptions cliOptions)
-            throws CheckstyleException, UnsupportedEncodingException, FileNotFoundException
+    private static int runCheckstyle(CliOptions cliOptions) throws CheckstyleException, IOException
```

"UnsupportedEncodingException, FileNotFoundException" is dues to loading of properties :(. Original idea of this method was to show how Checkstyle need to be initialized to work as embedded code, that is why I decided to use CliOptions class. It is method of main logic in whole Main class. After 2 days of thinking about this issue, i am ok to move properties load to "main" and have in CliOptions ready to use Property object. That will even show that "runCheckstyle" method will return one type of checked exception - CheckstyleException. That is good.

4)
```
-                 ClassLoader aLoader, boolean aReload) throws IllegalAccessException,
-                  InstantiationException, IOException
+                 ClassLoader aLoader, boolean aReload) throws IOException
```

I agree with that update as method already use the parent class. That is also api package , so we need to care about "throws".


=============================================

Does it make sense to you ?

As a summary I propose to apply updates that I described to code, create issues to update Check for new options, meanwhile we could add that few cases to suppresssion till this issue is resolved.

**Comment by romani** [comment]
@mkordas , does all that thoughts make sense ?

**Comment by mkordas** [comment]
@romani, yes it makes sense, thanks for really detailed analysis. I just wonder on couple additional things:
 * What value is brought to user when there is `throws UnsupportedEncodingException` in `main` signature with description _if there is a problem to use UTF-8_? This is just unfortunate checked exception. It makes sense when user provides encoding e.g. from command line, but if it is constant in the code, this exception should be caught and rethrown as unchecked one indicating programmer's mistake. You say it's boilerplate to wrap all checked exceptions as unchecked. But boilerplate is also to keep throwing this exception through entire chain and writing Javadocs in every method.

 * Let's go back to the roots - when checked exceptions are useful? It make sense to use them only when there is recovery/retry/fallback option. Otherwise IMO they should be immediately wrapped by unchecked exception and rethrown. So now the question is - should really one method return something and additionally provide more than one `throws` with some special retry/recovery needed?

>that is end/entry point , so nobody will be harmed by that throws

 It's possible to call `Main.main()` from other library or e.g. test code, so for me it also harms.

**Comment by romani** [comment]
@mkordas , http://vladlis.github.io/ is report on how ThrowCount is really following on real code. 4600 violations on not the worst sources in that world. So having "1" as default is too fanatic to my mind.

**Comment by romani** [comment]
> What value is brought to user when there is throws UnsupportedEncodingException in main signature with description if there is a problem to use UTF-8?

We do not let user smth useful, we just tell him that we do not know what to do with that Exception and user need to resolve/manage it himself. Or teat it as "Java compiler force me to do that, so I just transfer it to you, as I do not know how to manage it"

> Let's go back to the roots - when checked exceptions are useful?

Never :) , it was a mistake in Java design, it give illusion of exceptional cases control, non of modern languages do that.
But we have to live with them as Java is backward compatible. Checkstyle only need to have user ability to restrict usage of Checked exceptions to user's own level of fanatics. See report on real code - http://vladlis.github.io/ .

> should really one method return something and additionally provide more than one throws with some special retry/recovery needed?

that is too philosophical question. Answer is "it depends" . I would rather make a decision on each particular case, I am not ready to make any general rule for now ( too immature :( ).

> It's possible to call Main.main() from other library or e.g. test code, so for me it also harms.

Everything is possible, but it does not mean that it is right way. If smb use our Main.main() it is good sign that this code is HACK and he ok to have all side effects of that approach. He need only https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L208 method to run Checkstyle from his Java code. "Main.java" will always serve our CLI needs and could be changed at any time.

**Comment by mkordas** [comment]
@romani, great discussion, thanks for your time!

We both agree that checked exceptions in Java are rather design mistake. There are two ways of dealing with them:
* immediately rethrowing as unchecked ones
 * describes intentions well (there is no specific recovery option, so let's wrap as unchecked and use generic error handler)
  * sometimes may not be testable (e.g. how to test invalid encoding when it's hardcoded to UTF-8?)
  * `try` and `catch` needed instead of just `throws` (more lines of code)
* trying to get rid of them by declaring `throws`, especially when exit point is close
  * no tests needed to meet coverage (sometimes good, sometimes bad)
  * clearly stating that _I don't know how to deal with this issue_, let user decide

There are 2 aspects of this check:
* readability and code pollution (applies to all methods)
* having user friendly public API (public methods, probably in `api` package, excluding entry points like `main` or tests)

So indeed setting limit to 1 is too strict. On the other hand classes with e.g. 15 declared exceptions look really bad http://vladlis.github.io/xref/openjdk/src/share/classes/sun/security/tools/policytool/PolicyTool.html#L172. Even 5 in public method is not very-user friendly: http://vladlis.github.io/xref/openjdk/src/share/classes/com/sun/jmx/mbeanserver/JmxMBeanServer.html#L725

By looking at http://vladlis.github.io/ 3 or 4 are reasonable. We may provide a user a hint in docs, that there might be a reason to further decrease that limit because of reasons discussed above.

**Comment by mkordas** [comment]
Regarding your comments to the code:
> update that method to "private"

Done
> at this level we do not know how to manage that errors

`ReflectiveOperationExcepton` was added to Java to avoid a noise. It looks much better and is easier to understand compared to `ClassNotFoundException, InstantiationException, IllegalAccessException`. Look at previous Javadoc of this method:
```
     * @throws ClassNotFoundException if an error occurs
     * @throws InstantiationException if an error occurs
     * @throws IllegalAccessException if an error occurs
```
And indeed it doesn't matter for a caller which type of problem with reflection occurred.
>  It migth be good ideas to skip all "static" methods as they most likely utils methods and can not log or do any decision on wrapping.

I don't see any connection between `static` methods and throws count. Am I missing something?
>i am ok to move properties load to "main" and have in CliOptions ready to use Property object

Let's open separate issue for that, for now it's suppressed.

**Comment by romani** [comment]
> By looking at http://vladlis.github.io/ 3 or 4 are reasonable. 

#1143 

> And indeed it doesn't matter for a caller which type of problem with reflection occurred.

Question is not about what caller care about, you need to take a look at method that throws exceptions.
You can have multiple caller methods, but 'throw' method will always be one and it need to satisfy both of them. As throws-method can not wrap exceptions he has to deliver all that crap to caller. If caller to not like that he always have an option to use other methods or do ...... .

> I don't see any connection between static methods and throws count. Am I missing something?

That was my immature idea to suppress that check on static methods. Static methods should be like utils methods inside of class. So util method have no right to do logging or partly hide problems - report all or suppress all exceptions (example: string to int conversion or smth similar .... ). 
But I am not ready now to do detailed analysis of all java sources to claim that is good practice for all projects.  Please feel free to skip my note about static methods.

> Let's open separate issue for that, for now it's suppressed.

#1144

**Comment by romani** [comment]
About Reflection Exceptions:
https://docs.oracle.com/javase/7/docs/api/java/lang/ClassNotFoundException.html
https://docs.oracle.com/javase/7/docs/api/java/lang/InstantiationException.html
java.lang.ReflectiveOperationException is appeared in 1.7 Java.

That 2 Exceptions do report about different problems, so even class is found is user passed ClassNotFoundException, this class could non-creatable. 

So potentially some logic could give user more user friendly message of what is wrong.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
