### PR TITLE
Issue #5601: change all dtds to use https:\\checkstyle.org

### PR DESCRIPTION
**Pull request by romani**
Issue #5601

Reason:
https://github.com/checkstyle/checkstyle/issues/5601#issuecomment-396120018

Actual reason of CI failures was bad update for xml names, fixed at #5907 .
But we should continue migration to checkstyle.org

update was done by:
`$ find . -type f -name '*' -exec sed -r -i'' 's|http://checkstyle.sourceforge.net/dtds/|https://checkstyle.org/dtds/|g' '{}' \;`

### CODE REVIEW

**Comment by rnveach** [comment]
@romani CI is failing, is it related?

> Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to load schema with public ID null, system ID http://maven.apache.org/xsd/decoration-1.0.0.xsd: schema_reference.4: Failed to read schema document 'null', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.

**Comment by romani** [comment]
Looks like #5785 reproduced again.

**Comment by rnveach** [comment]
@romani Before merging just to confirm, this isn't a breaking change right?
`http://checkstyle.sourceforge.net` will still work for old configs.
I didn't see anything in the loader that examines the URL.

**Comment by romani** [comment]
I do not expect this to be breaking change.
It is just another location of DTD files. 
We have 3 places now:
http://puppycrawl.com/dtds/configuration_1_0.dtd
http://checkstyle.sourceforge.net/dtds/configuration_1_0.dtd (migrated here few years(1-3) ago only)
http://checkstyle.org/dtds/configuration_1_0.dtd (few month ago)

till we keep files on such domains, no one is affected.
I will have to keep http://checkstyle.sourceforge.net/dtds/ for long time to let users migrate slowly.
http://checkstyle.sourceforge.net/ will stay online for some time, but new DTD files will not be published to it, so users will be forced to switch if they need new features.

If all become clear to you, please merge PR.

**Pull request merged**
