### PR TITLE
Issue #9394 : update example of AST for TokenTypes.ARRAY_DECLARATOR

### PR DESCRIPTION
**Pull request by vivek286**
Issue: #9394

### CODE REVIEW

**Comment by vivek286** [comment]
@Abhishek-kumar09  Squashed all in one but still fails

**Comment by Abhishek-kumar09** [comment]
Please read the documentation. Don't delete the PR template blindly, it has already provided with informations on how a commit message should look like.
You commit message should look like
```
Issue #9394: <message>
```

use git ammend command to edit the commit message.

**Comment by Abhishek-kumar09** [comment]
Please don't open and close issue again and again.

**Comment by vivek286** [comment]
The cases were failing due to multiple commits in one PR . Now it shows
only one error PR validation failed how to resolve it please guide me.

**Comment by Abhishek-kumar09** [comment]
You should squash all the commits into one and rename it to  follow the template, that's it ecerything else should work fine

**Comment by vivek286** [comment]
Sorry for the inconvenience caused by opening and closing of multiple PR.

**Pull request closed without merging**
