### PR TITLE
Issure #12742: Badges in the README are missing

### PR DESCRIPTION
**Pull request by YehiaFarghaly**
# PLEASE READ before removing

Rules:
1) The issue you are trying to fix/resolve has to have the "approved" label.
2) Put in the description of Pull Request the reference to an issue if it exists.
   Example: "Issue: #XXXXXX"
3) Commit message should adhere to the following rules:
   a) MUST match one of the following patterns:
      ^Issue #\\d+: .*$
      ^Pull #\\d+: .*$
      ^(minor|config|infra|doc|spelling|dependency): .*$
   b) MUST contain only one line of text
   c) MUST NOT end with a period, space, or tab
   d) MUST be less than or equal to 200 characters

To avoid multiple iterations of fixes and CIs failures, please read
https://checkstyle.org/contributing.html

ATTENTION: We are not merging Pull Requests that are not passing our CIs,
but we will help to resolve issues.

Thanks for reading, remove whole this message and type what you need.

### CODE REVIEW

**Comment by YehiaFarghaly** [comment]
Please Help, I don't know what is wrong in my submission

**Comment by romani** [comment]
Just read PR description and follow what is written here.

**Comment by YehiaFarghaly** [comment]
But I followed the PR description, I cant see the rule that I did not match

**Comment by YehiaFarghaly** [comment]
@nrmancuso Thanks for your help it is my first contribution to open source so I had some problems. I tried to follow all the steps and it is much better now 😄 . However my new PR #12816 still failed in one CI 😞. is it because my update to the readme file was not correct?

**Pull request closed without merging**
