### PR TITLE
Issue: #7738 Update AbstractChecks to log DetailAST - JavadocContentLocation 

### LINKED ISSUE #7738: Update AbstractChecks to log DetailAST - JavadocContentLocation
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on JavadocContentLocation.

### PR DESCRIPTION
**Pull request by harsh-kukreja**
Issue resolves #7738 .
# 1. Site Changes.
Screenshot 2020-03-20 at 12 16 57 AM

# 2. Diff Report
(Default Config):
https://harsh-kukreja.github.io/diff%20report%20default%20config/diff/

(Config with location of first_line):
https://harsh-kukreja.github.io/diff%20report%20first_line%20config/diff/

# 3. Goal
Update AbstractChecks to log DetailAST - JavadocContentLocation

### CODE REVIEW

**Comment by harsh-kukreja** [comment]
@rnveach Please check now

**Comment by rnveach** [comment]
Configs for reports look good but reports need to be expanded to all projects. See https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#projects-to-test-onproperties

**Comment by harsh-kukreja** [comment]
Hey @rnveach can you please check again with the reports 
`checkstyle|local|/Users/Harsh/Desktop/checkstyle||` 
i wrote the above line in `project-to-test-on.properties`

**Comment by rnveach** [comment]
> i wrote the above line in project-to-test-on.properties

You need to uncomment all projects in project-to-test-on.properties .

> travis

It looks like a random timeout failure. I restarted it.

**Comment by harsh-kukreja** [comment]
Hey @rnveach the travis failed again

**Comment by rnveach** [comment]
https://travis-ci.org/github/checkstyle/checkstyle/jobs/664582536#L1040
> Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://repo.maven.apache.org/maven2/org/openjdk/jmh/jmh-core/1.23/jmh-core-1.23.pom'. Received status code 403 from server: Forbidden

Again, it looks like a random failure. I would ignore it for now unless it continues to keep happening.

**Comment by harsh-kukreja** [comment]
@rnveach Updated the links please check

**Comment by harsh-kukreja** [comment]
@rnveach can please review this PR

**Comment by rnveach** [comment]
@harsh-kukreja Please rebase the PR as there is conflicts.

**Comment by harsh-kukreja** [comment]
@rnveach done with that please check again

**Comment by harsh-kukreja** [comment]
Hey @strkkk please review this

**Comment by strkkk** [comment]
@harsh-kukreja sorry for taking so long, I somehow missed this review request

**Pull request merged**
