### PR TITLE
Issue#2974: EmptyLineSeparator check now validates newlines before comments

### PR DESCRIPTION
**Pull request by shivanshsoni**
fixes issue #2974

### CODE REVIEW

**Comment by shivanshsoni** [comment]
@romani  where I  am wrong?

**Comment by MEZk** [comment]
@shivanshsoni 
Please, follow [PR rules](https://github.com/checkstyle/checkstyle/wiki/PR-rules).

**Comment by romani** [comment]
do not close PR, do fixes and push with "--force" to your branch, PR will be refreshed automatically.

**Comment by rnveach** [comment]
@shivanshsoni squash all commits and keep them at 1 and fix all broken CIs.
Please read over https://github.com/checkstyle/checkstyle/wiki/PR-rules as it will guide you

**Pull request closed without merging**
