### PR TITLE
Issue #7190: remove deprecated setClassLoader methods

### PR DESCRIPTION
**Pull request by nmancus1**
Issue #7190: remove deprecated setClassLoader methods

### CODE REVIEW

**Comment by strkkk** [comment]
@nmancus1 wercker failed because of issue with maven plugin. Its version should be updated.

**Comment by rnveach** [comment]
@nmancus1 I am sorry, but as described in my new posts in the issue. I can't see us working more on this until `maven-checkstyle-plugin` changes their code to prevent the wercker failure we are seeing.

**Comment by nmancus1** [comment]
@strkkk thanks for posting the werker log!
@rnveach thanks for the update.  Ping me in the future if there's anything I can do to wrap this up. Should I close this PR?

**Comment by rnveach** [comment]
Yes, as I am not sure how long till the plugin releases an update to allow us to remove the methods.

**Comment by rnveach** [comment]
@nmancus1 It looks like it is not an issue. Sorry for the confusion.

The project that failed regression is using an outdated version of maven-checkstyle-plugin. For CI to pass, PRs have to be sent to those projects to upgrade their version of the plugin to the latest. Only then once all PRs are accepted will CI pass and allow us to merge in this change.

Let me know if you still wish to continue with this.

**Comment by nmancus1** [comment]
@rnveach so, you would like me to submit PRs to those projects that fail regression?

**Comment by rnveach** [comment]
Yes. It is required for CI to pass. You can run CI commands locally to identify which other projects will fail after the first one identified.

We give them some time to accept the PR, otherwise we can create an override on our side to move PR along. Usually this method is a bit more work than just getting them to accept a PR as we will need to create our own fork of their project.

**Comment by nmancus1** [comment]
I'll get on this.

**Comment by nmancus1** [comment]
Can I just run the travis `script:` section manually, or should I set up docker, etc., as outlined [here](https://gist.github.com/antonymarion/04aa87a2bb94c633bedb01174d9803a8)?

**Comment by rnveach** [comment]
You can look our YML files which tells our CI what to run. Example: https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L27

The YML specifies each command for each section of the CI. You can re-run these commands locally without having docker or anything special set up.

Please note that regression happens in Wercker and not travis.

**Comment by romani** [comment]
Please send PR with version bump to https://github.com/pgjdbc/pgjdbc/pulls and reference our issue in PR description. Pgjdbc team process our PRs quickly.

**Comment by nmancus1** [comment]
> Please send PR with version bump to https://github.com/pgjdbc/pgjdbc/pulls and reference our issue in PR description. Pgjdbc team process our PRs quickly.

Done.

**Comment by rnveach** [comment]
@nmancus1 Please reference the PRs back to here so we can track the progress. I would also re-open this PR so as things are fixed, we can re-run the CI and see if there are any other issues to resolve to merge this.

**Comment by nmancus1** [comment]
https://github.com/pgjdbc/pgjdbc/pull/1726

**Comment by nmancus1** [comment]
I deleted my fork and branch after closing this PR. New PR here: https://github.com/checkstyle/checkstyle/pull/7778

**Comment by romani** [comment]
> I deleted my fork 

Please always keep your fork, we look forward to collaborate on more other issues :)

**Comment by nmancus1** [comment]
> > I deleted my fork
> 
> Please always keep your fork, we look forward to collaborate on more other issues :)

I wish to collaborate more as well!  In the past, I've usually deleted and forked again instead of updating my fork, but this seems like a bad idea now.

**Pull request closed without merging**
