### PR TITLE
Issue #6462 and #6463

### LINKED ISSUE #6462: Remove PARAMETER_DEF from AnnotationLocation
With the reasoning from #6416:

Quote from @romani:
> All that tokens are not related to original idea of Check `Check enforce to locate annotations immediately after documentation block and before target element, annotation should be located on separate line from target element.` ... attention to `documentation block`.
Line wrapping that is possible with annotation usage should be covered by some other Check, I am not ready even tell about possible design for new Check .... live/users will show us what might be valuable in such validations.

`PARAMETER_DEF` should not be supported in `AnnotationLocation` check as parameters has no documentation and this Check is mostly for targets with javadocs. If somebody need to validate location of annotation in parameters  - new Check need to be created.

This would also simplify the implementation, because parameters are specially treated anyway, having a single annotation with or without parameters on the same line with the parameter is always allowed though the documentation does not indicate this. This special treatment can also be removed.

If the `PARAMETER_DEF` handling stays, then at least the documentation should be updated to describe the special treatment of parameters for which only a small subset like multiple annotations on the same line are checked.

### LINKED ISSUE #6463: Do not handle local variables for VARIABLE_DEF in AnnotationLocation
With the reasoning from #6416:

Quote from @romani:
> All that tokens are not related to original idea of Check `Check enforce to locate annotations immediately after documentation block and before target element, annotation should be located on separate line from target element.` ... attention to `documentation block`.
Line wrapping that is possible with annotation usage should be covered by some other Check, I am not ready even tell about possible design for new Check .... live/users will show us what might be valuable in such validations.

`AnnotationLocation` check for `VARIABLE_DEF` should only handle field definitions, but no local variable defintions as they have no documentation.

This would also simplify the implementation, because local variable definitions in for-each loops and for-loop-initializers are specially treated anyway, having a single annotation with or without parameters on the same line with the parameter is always allowed though the documentation does not indicate this. This special treatment can also be removed.

If the local variable defintion handling stays, then at least the documentation should be updated to describe the special treatment of local variable definitions in for-each loops and for-loop-initializers for which only a small subset like multiple annotations on the same line are checked.

Documentation should updated anyway, even if the local variable handling gets removed / local variables handling suppressed, the documentation should state that it is only effective on field definitions, not on local variable definitions.

ATTENTION: If users would like to validate location annotation over local variables , new Check should be created. That will have set of options to required to satisfy requirements, wihtout any conflicts with annotations over declaration elements that might have javadoc.

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #6462: Remove PARAMETER_DEF from AnnotationLocation
Fixes #6463: Only handle fields for VARIABLE_DEF in AnnotationLocation check, not local variables

### CODE REVIEW

**Comment by rnveach** [comment]
@Vampire It is probably best to bring separate PRs for separate issues.
You may be able to pass CI for 1 easier then the other. Looking at the failures, 6463 might be easier because of wercker.

pitest failure:
> `+AnnotationLocationCheck.java.html:<td class='covered'><pre><span  class='survived'>            || allowingCondition &#38;&#38; !hasNodeBefore(annotation)</span></pre></td></tr>`

Shippable failure can be ignored.

Wercker failure:
> NoExceptiontest - Apache Struts
> Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "PARAMETER_DEF" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationLocationCheck

Since wercker is showing regression problems in apache struts, you will have to make a PR to their repository to remove the token from their config we are removing here. Once it is approved and merged, CI should pass for them here and we can continue with regression.

**Comment by Vampire** [comment]
Well, both PRs would conflict as they touch the same lines, so I thought one PR with two commits should be appropriate.

Can you give me a hint on how to investigate the pitest failure?
I get it here two if I execute it, but I'm not sure how to interpret and fix it correctly.

**Comment by rnveach** [comment]
CI doesn't show pitest failure message, so you would have to give me the context the report says.
You can run pitest locally from main repo directory by running: `./.ci/pitest.sh pitest-annotation`

If you are not familar with mutation testing, pitest basically changes your code and expects a test to fail to show that the original code is enforced by a test. Pitest does various mutations like negating conditionals, replacing conditionals with true/false, turning plus into negative, removing calls to methods, etc... The reports usually given enough information that you can reproduce the mutation manually to examine why a test isn't failing.

> || allowingCondition &#38;&#38; !hasNodeBefore(annotation)

It could be negating conditionals or replacing conditionals with true/false. The report would have the direct information.

**Comment by Vampire** [comment]
I was not until I have seen it in CS project and read up on it already, I'm just not yet familiar with it.
Here the report: http://kautler.net/201903081132/com.puppycrawl.tools.checkstyle.checks.annotation/AnnotationLocationCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@3bc282bd_323
I tried to replace in that line both conditions with true or false but I always get failing tests like expected.

**Comment by rnveach** [comment]
> 323 | 4 | \|\| allowingCondition && !hasNodeBefore(annotation)
324 | 2 | \|\| !allowingCondition && !hasNodeBeside(annotation)

`if ((A && !B) || (!A && !B))` isn't this the same as just `if (!B)`?

**Comment by rnveach** [comment]
@Vampire it seems report put failure on wrong line. I don't think I have seen this happen before.
The following code produces no test failures:
````
        return allowSamelineMultipleAnnotations
            || allowingCondition && !hasNodeBefore(annotation)
            || true && !hasNodeBeside(annotation);
````

**Comment by Vampire** [comment]
Ah, thanks.
Now I'm still not sure what that exatly means to me and how to resolve it, but at least I'm one little step further. :-D

**Comment by Vampire** [comment]
> Since wercker is showing regression problems in apache struts, you will have to make a PR to their repository to remove the token from their config we are removing here. Once it is approved and merged, CI should pass for them here and we can continue with regression.

That was not nice, sending me to Pontius, just to see I need to go back to Pilatus: https://github.com/checkstyle/contribution/pull/346
Struts does not even use Checkstyle or at least I can find no trace in their repo.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh#L161
Sorry, I didn't realize this regression was using our own config.

https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/checks-nonjavadoc-error.xml#L143
This is the config that has to be updated.

**Comment by Vampire** [comment]
The mutant problem should be solved, now just my PR in the contribution project is missing to get this green hopefully. The mutant actually showed an effectively useless condition that cannot make any difference. Imho it made the code more readable and understandable, especially as no multiple return points are allowed, but well, now it's gone.

**Comment by rnveach** [comment]
wercker failure is waiting on https://github.com/checkstyle/contribution/pull/346

**Comment by Vampire** [comment]
I really think the code should be like I had it before the pitest thing.
As I just have seen that you also ignore certain pitest findings, I instead added it to the ignore list.
Please tell me if you don't agree.

**Comment by rnveach** [comment]
We are working towards 100% pitest coverage, so we try not to add something to the ignore list unless you can explain it more. The last time we added a bunch to the ignore list because powermock didn't play nicely with pitest, but I want back after that commit and changed a bunch of powermock tests to normal tests to try to restore the ignore list back to it's original contents.

One way I tackle the ignore list is by using regression ( https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#diffgroovy-diff-report-generation ) with the changed code in the commit and a lot of different check configurations to find differences. If no differences are found, I examine the code by debugging to see if I see any reason why it isn't possible to create a difference manually. If all that fails I remove the code and users will file an issue if there was a problem.

If you need help with anything, let me know.

**Comment by Vampire** [comment]
I'm not fully sure what you mean with the second paragraph or respectively what the outcome will be.

But I'll follow the first paragraph and explain why the pitest cannot be green for this particular change, then you can decide on what you like more.

The code in question is
```java
return allowSamelineMultipleAnnotations
    || allowingCondition && !hasNodeBefore(annotation)
    || !allowingCondition && !hasNodeBeside(annotation);
```
and what it complains about is that if you replace `!allowingCondition` with `true`, no tests fail which actually is correct and expected. Let me explain why.
For better understanding and explanation lets replace `hasNodeBeside(annotation)` by `hasNodeBefore(annotation) || hasNodeAfter(annotation)` which is exactly the same. So we are at 
```java
return allowSamelineMultipleAnnotations
    || allowingCondition && !hasNodeBefore(annotation)
    || !allowingCondition && !(hasNodeBefore(annotation) || hasNodeAfter(annotation));
```
Now the mutant replaces `!allowingCondition` by `true` which means in the mutant-free run that would kill the mutant it would have been `false`, so `allowingCondition` would have been `true`. So now we are at
```java
return allowSamelineMultipleAnnotations
    || true && !hasNodeBefore(annotation)
    || [true should be false] && !(hasNodeBefore(annotation) || hasNodeAfter(annotation));
```
That the mutant makes any difference, we need to get to the last of the three `||`-parts.
So to come past the first part `allowSamelineMultipleAnnotations` needs to be `false`.
To come past the second part `!hasNodeBefore(annotation)` needs to be `false` and thus `hasNodeBefore(annotation)` needs to return `true`.
Assuming `hasNodeBefore` does not return different results on successive calls we are now at
```java
return false
    || true && !true
    || [true should be false] && !(true || hasNodeAfter(annotation));
```
Applying some boolean simplification we are now at
```java
return false
    || false
    || [true should be false] && !(true);
```
So this shows that the `!allowingCondition` is effectively useless, because when it comes to the third `||`-part, its second `&&`-part will always be `false` and so the result does not change, no matter what the first `&&`-part is.

The intention to not remove it but ignore the pitest finding is for better code readability and understandability and for more robustness about condition change, if in the future the second `&&`-part of the last `||`-part could be `true` or `false` again by adding back a condition like the one I removed.

The options I see are:
- ignoring the pitest finding
- adding massive comment that explains the situation
- removing the `!allowingCondition` and hope for the best

**Comment by rnveach** [comment]
That is very detailed thanks.
Regression won't help here if you can logically prove it is never possible for the code to be hit in the way we need.

Right now when we have hit these situations, we remove the dead code. We are fine with a little issue in the future if it is something we can't see now.
So please make the change.

> I'm not fully sure what you mean with the second paragraph or respectively what the outcome will be.

You are familar with our no-exception regressions and our no warnings regression. We have another manual regression that is our difference regression. We run 1 config on multiple projects with 2 different versions of checkstyle, master and the PR branch, and we examine the difference in violations between the 2. If we expect no no violations, then no differences will show, otherwise it will show differences in violations and in which files and lines.

You can use this to help with pitest. 1 version of checkstyle will be the PR branch and the other version will be the PR branch with the pitest mutation hard coded in. If there is a difference in violations, those are your examples to keep the code and kill the mutation. If there are no differences, then either there is no code out there to help kill mutation or mutation can never be killed.

**Comment by Vampire** [comment]
Ah, nice, thanks for the explanation, I'll give that a try and see whether my boolean logic was flawed.
The sentence
> To generate a diff report before and after your changes manually please use the tool https://github.com/attatrol/ahsm
What does it mean?
What is the difference between running the Groovy script and "to generate a diff report before and after your changes", I thought that is exactly what the script is doing.
Besides that, the link is dead, this project is either private or no longer existent.

And you should either make the script workable with Java 11 or mention in the description that it is not compatible with Java 11. If your `JAVA_HOME` is set to Java 11, you get an error because of missing JAXB classes, as Java 11 removed those amongst other things.

**Comment by rnveach** [comment]
> you should either make the script workable with Java 11 

Please open an issue with details in that repo if it doesn't work with Java 11. We are not aware of any issues atm.

> https://github.com/attatrol/ahsm

I'm not sure why this is in the document. I will look over it and update it for this and to describe it's usage for pitest.

No other repo should be needed to work regression. I believe ahsm was the old location for `patch-diff-report-tool` which was now embedded into our contribution repo. `attatrol` was the user who helped us build it. So you can ignore this verbage in the document. Groovy script will build `patch-diff-report-tool` for you.

**Comment by Vampire** [comment]
Also it says `you can specify at projects-to-test-on.properties path to local file system if you have some repositories on your local, example: "checkstyle=/home/username/java/git-repos/checkstyle/checkstyle".`
Is this still true?
I didn't try because I was about to ask whether this will in any way modify the local repositories which could be bad e. g. if I have local modifications.
But looking at the code it doesn't seem like it would be supported, but actually it would be nice if it were as I have many projects on my disk and it would be nice if I could just reuse them for the checkstyle-tester.

**Comment by rnveach** [comment]
> Is this still true?

It should be but I never specifically used it.
Groovy script doesn't do anything like modify commits or delete branches.
It checks out branches and does a reset so working directory is what is expected, so beware of local unsaved/uncommitted changes that aren't pushed to the server.

**Comment by Vampire** [comment]
Ok, it seems my boolean logic was ok, regression on most of the projects in the properties file did not find any difference, ignorance removed.

**Comment by Vampire** [comment]
Why is Codecov failing now and saying "Commit was deleted by force push or pull request rebase."? o_O

**Comment by rnveach** [comment]
I am not sure for reason for failure. Code coverage is passing in travis/pitest, so it may be just a random issue and fix itself on next push.
Changes to regression config still need to be merged. https://github.com/checkstyle/contribution/pull/346

**Comment by Vampire** [comment]
I now run the regression again with 191 projects and there was no difference, so I'm pretty confident it really was useless code. :-)

**Comment by Vampire** [comment]
What problem does wercker have now?
contribution ticket is merged, build was retriggered.

**Comment by rnveach** [comment]
Wercker was timeout issue. I restarted the CI.

**Comment by romani** [comment]
@rnveach , please finish review as you are in context of this issue/PR for a while.
Simple hint is .... regression report is required to make sure changes are ok. UTs is not enough.

**Comment by rnveach** [comment]
@Vampire I still prefer these be split into 2 PRs. It is a shame that they touch the same files but I think it will make discussions and reviews lot easier.

While you are splitting them apart, please provide separate regression reports for each commit.

**Comment by romani** [comment]
I agree to split, it will be also beneficial during regression testing. Single change is easier to review, we will end up with more reliable fix.

**Comment by Vampire** [comment]
How should the regression report config for #6462 look like?
Both versions without the removed token?
One with the token one without (will of course show differences)?
Something else?

**Comment by rnveach** [comment]
> One with the token one without (will of course show differences)?

It should be atleast this so we can verify that removing the token is the right course.

**Pull request closed without merging**
