### PR TITLE
Issue #4805: fix HtmlTagCanBeJavadocTag in TokenTypes

### PR DESCRIPTION
**Pull request by Nimfadora**
Issue #4805

here are the changes in TokenTypes which cause build to fail

### CODE REVIEW

**Comment by romani** [comment]
I exended message at #4834 , after merge you will see more details on where is problem.
It is most likely jdk problem, you need to report issue to jdk.

Problems are like (the are a lot of them):
```
  [javadoc] javadoc: error - In doclet class com.puppycrawl.tools.checkstyle.doclets.TokenTypesDoclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
  [javadoc] java.lang.IllegalArgumentException: Should be only one tag for com.puppycrawl.tools.checkstyle.api.TokenTypes.ABSTRACT. Tags ["Text:The ", "@code:abstract", "Text: keyword."].
  [javadoc] 	at com.puppycrawl.tools.checkstyle.doclets.TokenTypesDoclet.start(TokenTypesDoclet.java:85)
  [javadoc] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

We cannot wait for jdk bug fix, as it will be in java9 in best scenario or even in jdk10.
Lets have one more update in docklet and skip all "Text" tags from validation(but demand only one non "Text") and select to print first non "Text" tag to result file.

**Comment by romani** [comment]
@Nimfadora , I merged update for Docklet, so please proceed with this PR.

**Comment by romani** [comment]
@Nimfadora , is there any progress ?

**Comment by Nimfadora** [comment]
@romani I have submitted bug report to Oracle, submit failed, I submitted bug report on submitting bug report, then resubmitted the first one. They say, that it will be reviewed, than I hope some mail will be sent to me on the review results. What should we do with this task? wait for the review or just write some common comment without specifying link to the bug?

**Comment by romani** [comment]
> We cannot wait for jdk bug fix, as it will be in java9 in best scenario or even in jdk10.

we need fix no-matter what. in comment please put any reference ID that you get from Oracle.

**Comment by Nimfadora** [comment]
@romani please help: when we use javadoc tags in TokenTypes it breaks TokenUtils.getShortDescription. Instead of `The {@code ==} (equal) operator` it now returns just `The `.
I don't know how to fix it.

**Comment by romani** [comment]
@Nimfadora , how update in docklet is related to util method that is used in test only (not docklet tests) ?
I expect changes only in docklet code, docklet generate plain text file.

**Comment by Nimfadora** [comment]
@romani please approve this issue, build fails

**Comment by romani** [comment]
distelli - relaunched.

Shippable has timeout in last profile `PROFILE="-Ppitest-checkstyle-gui,no-validations"` could be ignored.

**Pull request merged**
