### PR TITLE
Added 'validateAbstractClassNames' option for IllegalTypeCheck, issue #1805

### PR DESCRIPTION
**Pull request by MEZk**
@romani 
checkstyle-tester reported no violations/errors when I ran IllegalTypeCheck against checkstyle-6.10-SNAPSHOT with ```src/test/**/*``` as excludes.

### CODE REVIEW

**Comment by romani** [comment]
code is good.

1) please update our suppression file to remove suppression for this Check (as separate commit).

**Comment by MEZk** [comment]
@romani 
>1) please update our suppression file to remove suppression for this Check (as separate commit).

Left suppressions only for test folder.

**Comment by romani** [comment]
Why suppres on test is introduced for IllegalType ? We need to be strict in all parts of our code.

**Comment by MEZk** [comment]
@romani 
>1) please update our suppression file to remove suppression for this Check (as separate commit).

Done.

>Why suppres on test is introduced for IllegalType ? 
hastened) Fixed check's violations on all packages in ```src/test``` except resource folder.

**Comment by romani** [comment]
> ```<suppress checks="IllegalType" files=".*[\\/]src[\\/]test[\\/]resources[\\/]"/>```

Have you seen in suppression file that any Check do suppression in resources ?
please remove this, as this is done on level where we configure how to run Checkstyle over our code.

**Comment by MEZk** [comment]
@romani 
>Have you seen in suppression file that any Check do suppression in resources ?
please remove this, as this is done on level where we configure how to run Checkstyle over our code.

Fixed.

**Comment by romani** [comment]
merged as FF

**Comment by mkordas** [comment]
@romani, @MEZk, I think this one needs some more work. Just read current description:
> Checks that particular classes are never used as types in variable
           declarations, return values or parameters. Includes a pattern check
           that by default disallows abstract classes.

1. Abstract classes are no longer disallowed by default
2. Property is named `validateAbstractClassNames`. I don't think it describes well it's purpose. This check is not about _Names_. It is about _Types_. Maybe it should be named just `allowAbstractClasses` with default `true`?

**Comment by MEZk** [comment]
@mkordas 
>1. Abstract classes are no longer disallowed by default

Yes, should be corrected.

>2. Property is named validateAbstractClassNames. I don't think it describes well it's purpose. This check is not about Names. It is about Types. Maybe it should be named just allowAbstractClasses with default true?

Yes, I agree that the check is about Types, by we are a bit cheating here, because checkstyle is a static code analisis tool and we can check only "Abstract" names, not "Abstract types" itself and in that way the option is about names. But your proposal to rename is reasonable.

**Pull request closed without merging**
