### PR TITLE
Issue #11054: rewrote RightCurlyCheck avoid a possible exception

### PR DESCRIPTION
**Pull request by rnveach**
Issue #11054

Local pitest confirmed that duplicating the code is acceptable, though I don't think this is really desirable.

### CODE REVIEW

**Comment by rnveach** [comment]
semaphoreci failure with openjdk11 seems unrelated.

**Review by romani — APPROVED** [review]
Reasonable

**Comment by romani** [comment]
@rnveach , please generate regression report

**Comment by rnveach** [comment]
Here is the regression report:
http://rveach.no-ip.org/checkstyle/regression/301/

No differences reported.

**Review by strkkk — APPROVED** [review]

**Pull request merged**
