### PR TITLE
infra: move config for no-exception execution of javadoc in repo

### PR DESCRIPTION
**Pull request by romani**
reason: it is very strange that we keep config for CI of checkstyle in another repo.

file projects-for-circle.properties was added at https://github.com/checkstyle/contribution/pull/52
and it is clearly have bad name now as location was changed.

We should keep configs for checkstyle CI in checkstyle repo.

### CODE REVIEW

**Comment by nmancus1** [comment]
Just a thought, but since these are on all the same CI (travis) why not just un-comment the entire project file and make one job?

**Comment by romani** [comment]
> nevermind, this will be faster since travis runs in parallel.

yes, just a consideration on to avoid big/long executions.

**Review by nmancus1 — APPROVED** [review]

**Comment by rnveach** [comment]
> We should keep configs for checkstyle CI in checkstyle repo.
> projects-for-no-exception-javadoc.properties 

This is not a config file, just a regression properties. 

Are we moving all other properties to this repo?
````

projects-for-circle.properties
projects-for-travis.properties
projects-for-wercker.properties
projects-to-test-on-for-github-action.properties
projects-to-test-on.properties
````

**Comment by romani** [comment]
>Are we moving all other properties to this repo?

Yes, not a part of this PR.

**Review by pbludov — APPROVED** [review]

**Review by rnveach — APPROVED** [review]

**Pull request merged**
