### PR TITLE
Remove duplicate cobertura-maven-plugin declaration

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
Build is failed :)

**Comment by mkordas** [comment]
Build is fixed

**Comment by mkordas** [comment]
Instrumentation exclusions have one drawback - we get the following log during site generation:
```
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/ModuleFactory.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/PropertyResolver.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/api/AuditListener.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/api/Configurable.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/api/Configuration.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/api/Context.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/api/Contextualizable.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/api/DetailNode.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/api/FileSetCheck.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/api/Filter.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/api/MessageDispatcher.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/api/TextBlock.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/checks/regexp/MatchSuppressor.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/filters/IntFilter.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/grammars/CommentListener.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/grammars/GeneratedJavaTokenTypes.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParserListener.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParserVisitor.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/gui/FileDrop.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/puppycrawl/tools/checkstyle/gui/TreeTableModel.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
```
Maybe it would be better to instrument them but allow 0% coverage?

**Comment by romani** [comment]
merged as  FF.

> Maybe it would be better to instrument them but allow 0% coverage?

that are interfaces, there will never be any coverage. we could add them to ignore list, but that will overcomplicate our configuration,  maven generate a lot of stuff with INFO level, I believe that extra logs is better then extra configuration.

http://checkstyle.sourceforge.net/cobertura/index.html in api package you can see that all that files are N/A but that will not block us from ultimate goal - all is 100%.

**Pull request closed without merging**
