### PR TITLE
Issue #5124: removed final usages of branchContains

### PR DESCRIPTION
**Pull request by rnveach**
Issue #5124

5 cases are left.
Regression to come.

### CODE REVIEW

**Comment by rnveach** [comment]
> DetailAST.java

Shippable (`-Ppitest-checkstyle-api,no-validations`) is failing because we are removing uses of it's `branchContains`.
I will look into.

**Comment by rnveach** [comment]
http://rveach.no-ip.org/checkstyle/regression/reports/133/
Differences are only for `VariableDeclarationUsageDistance` and `AnnotationUseStyle`.

For `VariableDeclarationUsageDistance`:
http://rveach.no-ip.org/checkstyle/regression/reports/133/openjdk9/index.html#A1
http://rveach.no-ip.org/checkstyle/regression/reports/133/openjdk9/xref/openjdk9/src/demo/share/jfc/Metalworks/MetalworksFrame.java.html#L189
These changes look valid because it is not a loop but an anonymous class.
@romani Please confirm this change is valid for this check.

http://rveach.no-ip.org/checkstyle/regression/reports/133/openjdk9/index.html#A2
http://rveach.no-ip.org/checkstyle/regression/reports/133/openjdk9/xref/openjdk9/src/java.base/share/classes/java/io/BufferedReader.java.html#L333
This looks like a bug because the label and the `for` loop are considered to be one by the AST.
````
    |      |--LABELED_STAT -> : [3:4]
    |      |  |--IDENT -> test [3:0]
    |      |  `--LITERAL_FOR -> for [4:0]
````
I will need to make an override for the label to correct it's behavior.

http://rveach.no-ip.org/checkstyle/regression/reports/133/sevntu-checkstyle/index.html#A1
http://rveach.no-ip.org/checkstyle/regression/reports/133/sevntu-checkstyle/xref/sevntu-checkstyle/sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/annotation/InputForbidAnnotationElementValueCheck.java.html#L96
@romani Please confirm behavior for `AnnotationUseStyle` as I am not sure if annotations should depend on inner annotations. To me it looks like these violations are wrong.
Is `@Foo(@Bar)` invalid too?

**Comment by rnveach** [comment]
Regression for all checks that use `CheckUtils.isReceiverParameter`.
http://rveach.no-ip.org/checkstyle/regression/reports/134/
No differences.

**Comment by romani** [comment]
@rnveach ,

> Please confirm this change is valid for this check.

cases looks valid, I am with regression.

> This looks like a bug because the label and the for loop are considered to be one by the AST.
I will need to make an override for the label to correct it's behavior.

It is better to avoid such regression.

> Is @Foo(@Bar) invalid too?

wow, I was unaware that it is possible by syntax.
Please fix this in this PR.

**Comment by rnveach** [comment]
I am closing this for now. This and remaining cases are more complex to replace and it might require some more in depth look.

**Pull request closed without merging**
