### PR TITLE
Issue #11214: Specified violation messages in RegexpCheck

### PR DESCRIPTION
**Pull request by Bharath-Ganesh**
Issue https://github.com/checkstyle/checkstyle/issues/11214
Specified violation message in RegexpCheck.

### CODE REVIEW

**Comment by romani** [comment]
try to debug why it is same without your changes and different with your changes.

**Comment by Bharath-Ganesh** [comment]
sure @romani . I can understand the regex validation is failing.

The regex expressions are matching to the point prior to the character '^'. 
Needs to figure out how this can be done.

image

**Comment by romani** [comment]
try to escape it in Input file `\^`

**Comment by romani** [comment]
if no activity before 1 October, we will close this PR to let somebody else reuse this works and complete a task

**Pull request closed without merging**
