### PR TITLE
Fix PMD violations of AvoidCatchingGenericException rule. #959

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
1)
> config/import-control.xml

please explain that changes. Be more restrictive is ok to my mind, especially if that is already done.

2)
> PropertyCacheFile.java

Idea of a cache is - if any exception happen in it do not crash process and just skip returning values from cache. In there is problems with a cache pretending that it does not exists at all. So that is why Exception catch is used - any problem even unexpected. Exact `catch (final NoSuchAlgorithmException | IOException ex) {` that is declaration of expected exceptions. But what about NPE ? 

3)
> CustomImportOrderCheck.java

Here is another interesting case, it right update only in case if NumberFormatException is checked exception, fortunately it is not. If it is checked in that case you can guaranty that such exception should be expected from method "Integer.parseInt(rule)" , and after upgrade to java9 or java29 it will stay the  same. If smth will change in java, presume parseInt() start to throw another exception - you will have compilation error but never missed catch.
But we have runtime NumberFormatException (unchecked exception) it could potentially be substituted with new exception, for example NumericFormatException, and your code will fail. And find mistake could be painful.
What we could do ?
We need to create a static method that will wrap that execution catch Exception and return a default value. In this case isolate parsing problem from a context of class (stateless) , and clearly state - no matter what is failing during parsing a String to Integer I return default value.

4)
> JavadocUtils.java

here is almost the same problem as above catching Exception in static block (block that out of class context and state) is ok to my mind. It clearly state "if smth happen throw exception with clear message". if you refactor it to custom exception you will lose that information. How useful that information :) that is another issue.

5)
> RightCurlyCheck.java

cheating over a name of Exception but it is ok, in this particular case even good.

6)
> CheckstyleAntTask.java

interesting case ... after update it will be in case of IOException --> BuildException("Unable to create a Checker: ") , but in case of NPE or NumberFormatException ---> NPE or NumberFormatException :). If we do not guarantee a type of exception from our code why we should bother with BuildException at all ?
Please look at https://github.com/checkstyle/checkstyle/blob/master/config/findbugs-exclude.xml#L13
I do not claim that basic ANT taks are done in right approach, but will follow their pattern.
Here is an example of catching smth specific - https://git-wip-us.apache.org/repos/asf?p=ant.git;a=blob;f=src/main/org/apache/tools/ant/taskdefs/Chmod.java;h=ac0c3d8d143493706be0d1ae875177146db43f67;hb=HEAD#l197

I did more search and found : 
https://ant.apache.org/manual/tutorial-writing-tasks.html
```
Oh, what's that in execute()? Throw a BuildException? Yes, that's the usual way to show
 Ant that something important is missed and complete build should fail. The string 
provided there is written as build-failes-message. Here it's necessary because the log()
 method can't handle a null value as parameter and throws a NullPointerException.
 (Of course you can initialize the message with a default string.)
```

So it looks like ANT suggest to throw BuildException only if some arguments are missed or smth is not correct with initialization phase. 
So it mean that we are ok with your solution , but it would be better to somehow split initialization phase and processing and throw BuildException by initialization failure, and throw exception as is in all other cases. [That could be done as another issue]

7)
> Checker.java
```
 else {
throw new CheckstyleException(name
+ " is not allowed as a child in Checker");
}
}
catch (final CheckstyleException ex) {
throw new CheckstyleException("cannot initialize module " + name
+ " - " + ex.getMessage(), ex);
}
```

Throw exception to catch it rightaway - that is smth weird. We need more deep refactoring there.

**Comment by mkordas** [comment]
1) Changed to more restrictive.

2) Why you think that _Idea of a cache is - if any exception happen in it do not crash process_? It's code like any other code. If we have developer's mistake, we want to know about it ASAP. If it's expected exception, then we want to handle it as it is done now.

3) `Integer.parseInt()` throws checked exception. If anything will change in Java 29, then we'll get compilation error. Moreover, we should have test for that. I think that's enough, we don't need any more safety.

4) For me that message is not very useful - stacktrace should be enough.

6) and 7) Let's create another issues for that.

**Comment by romani** [comment]
1)
> Why you think that Idea of a cache is - if any exception happen in it do not crash process? 

it is not idea I like (I always in favour of fail-faster ), but that code existed before me and you, so we can not just brake it. In code that you propose I do not see that you do "fail-faster" approach, as you catch some exceptions. Why NoSuchAlgorithmException is different from NPE ?
If you want to do fail-faster - do not catch exceptions at all or rethrow them right away.
Keep in mind that checked exceptions is bad-design of Java language, that bad design should affect user experience with our project.

2)
> Integer.parseInt() throws checked exception.

eventually checked exception will be deprecated. ....
There was just an example , you can think of any method that throw Runtime-like exception, and there is no guranty after library update.

3)
> 4) For me that message is not very useful - stacktrace should be enough.

ok, now we rethrow exception and use catch only to avoid Checked exceptions in signature - that is good.

4)
> 6) and 7) Let's create another issues for that.

please revert your changes for that cases, keep that cases in supporessions (with links to new issues), create issues and make a note to remove such suppresions.

**Comment by romani** [comment]
> CustomImportOrderCheck.java

I am calling back my comments for that file change. I misread a code. It is not pure "doSmthOrReturnDefault()" model.

**Comment by romani** [comment]
release 6.8 will be in 4 days, it will be good to finish that PR before.

**Comment by mkordas** [comment]
1) NPE is purely programming mistake so we should fail-fast. Regarding `IOException` - we don't want to fail analysis in case of some problems with storage, as cache is not crucial. 

`NoSuchAlgorithmException` is interesting - first of all we were using non-standard algorithm (`SHA` instead of `SHA-1` - http://stackoverflow.com/questions/14903539/what-specific-hash-algorithm-does-messagedigest-getinstancesha-return). Next thing - should we require used to have SHA-1 available in JVM? Probably not. But I raised logging from `DEBUG` to `ERROR` in both cases.

2) Right - so if it will be changed to RuntimeException in future, we are safe, because this will be compilation error, as no checked exception will be thrown.

4) Done as #1244 and #1245

**Comment by romani** [comment]
1) 
> JavadocUtils.java

please add a comment that we catch checked and rethrow unchecked exception. To be clear why we catch only that exception.

2)
> PropertyCacheFile.java

I still do not understand why we do not use fail-fast approach there. We have only two option fail-fast or catch-all-and-continue-with-default. Any mixture of that models are not good, and will looks strange in runtime.

**Comment by mkordas** [comment]
1) Done
2) Done

**Comment by romani** [comment]
please add "// rethrow as unchecked exception" to "JavadocUtils.java" nobody remember all checked exceptions by names.

**Comment by mkordas** [comment]
This comment is already added :)

**Comment by romani** [comment]
sorry, add it to "PropertyCacheFile.java" .

**Comment by mkordas** [comment]
Done

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
