### PR TITLE
Refactoring of UnnecessaryParanthesesCheck. UT coverage was increased up to 100%

### PR DESCRIPTION
**Pull request by baratali**
Some refactoring of the Check.

### CODE REVIEW

**Comment by baratali** [comment]
I'm fixing it

**Comment by romani** [comment]
1) please make a ref to issue from commit message

2) as you did a refactoring for Check, please generate HTML reports over some projects (before and after changes) to make sure that nothing is changed in reports and logic of Check.

**Comment by baratali** [comment]
1) done
2) http://baratali.github.io/ (reports are identical)

**Comment by romani** [comment]
Please restore getAcceptableTokens method

**Comment by baratali** [comment]
getAcceptableTokens() is restored; getRequiredTokens() has been added.
I also made reports for guava+spring+hibernate; no difference in reports before and after my changes.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
