### PR TITLE
infra: update pmd CI execution to not use forked repository

### PR DESCRIPTION
**Pull request by romani**
stable failure of semaphoreci on pmd validation
https://checkstyle.semaphoreci.com/jobs/25bf624f-4f4c-4380-8de4-2ee08fe6d4b8

`[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.4.10:compile (kotlin-compile) on project pmd-lang-test: Execution kotlin-compile of goal org.jetbrains.kotlin:kotlin-maven-plugin:1.4.10:compile failed: A required class was missing while executing org.jetbrains.kotlin:kotlin-maven-plugin:1.4.10:compile: kotlin/reflect/full/KClasses 02:02`

commands is taken from https://github.com/pmd/pmd/blob/master/.ci/build.sh#L93

### CODE REVIEW

**Comment by romani** [comment]
On local it is passing, strange

**Comment by pbludov** [comment]
> On local it is passing, strange.

Same for me. I tried doing `sem debug` and clear the m2 cache, switch jdk to 17, build latest pmd master, build with `mvnw` as the [docs say](https://github.com/pmd/pmd/blob/master/BUILDING.md). No luck so far.

**Comment by rnveach** [comment]
> I tried ... clear the m2 cache

Do you mean the maven dependency cache in the CI?

**Comment by romani** [comment]
I disabled this job in master branch for now, until this PR.

**Comment by romani** [comment]
new command work:
```
✘-1 ~/java/github/checkstyle/checkstyle [pmd-failure L|✚ 1] 
16:53 $ git diff
diff --git a/.ci/validation.sh b/.ci/validation.sh
index 1e4f180..d18ed76 100755
--- a/.ci/validation.sh
+++ b/.ci/validation.sh
@@ -205,11 +205,11 @@ markdownlint)
 no-error-pmd)
   CS_POM_VERSION="$(getCheckstylePomVersion)"
   echo "CS_version: ${CS_POM_VERSION}"
-  checkout_from "https://github.com/pmd/build-tools.git"
+  # checkout_from "https://github.com/pmd/build-tools.git"
   cd .ci-temp/build-tools/
-  mvn -e --no-transfer-progress install
+  # mvn -e --no-transfer-progress install
   cd ..
-  git clone https://github.com/pmd/pmd.git
+  # git clone https://github.com/pmd/pmd.git
   cd pmd
   ./mvnw verify --show-version --errors --batch-mode --no-transfer-progress \
                 -DskipTests \
@@ -218,8 +218,8 @@ no-error-pmd)
                 -Dcheckstyle.skip=false \
                 -Dcheckstyle.version=${CS_POM_VERSION}
   cd ..
-  removeFolderWithProtectedFiles build-tools
-  removeFolderWithProtectedFiles pmd
+  #removeFolderWithProtectedFiles build-tools
+  #removeFolderWithProtectedFiles pmd
   ;;
 
 no-violation-test-configurate)
✔ ~/java/github/checkstyle/checkstyle [pmd-failure L|✚ 1] 
16:53 $ cd .ci-temp/pmd/
✔ ~/java/github/checkstyle/checkstyle/.ci-temp/pmd [master|✚ 1] 
16:53 $ git diff
diff --git a/pmd-core/src/main/java/net/sourceforge/pmd/AbstractConfiguration.java b/pmd-core/src/main/java/net/sourceforge/pmd/AbstractConfiguration.java
index 671cf74..304d6e4 100644
--- a/pmd-core/src/main/java/net/sourceforge/pmd/AbstractConfiguration.java
+++ b/pmd-core/src/main/java/net/sourceforge/pmd/AbstractConfiguration.java
@@ -5,6 +5,7 @@
 package net.sourceforge.pmd;
 
 import java.nio.charset.Charset;
+import java.nio.charset.Charset;
 
 /**
  * Base configuration class for both PMD and CPD.

```

```
[INFO] --- maven-checkstyle-plugin:3.1.2:check (checkstyle-check) @ pmd-core ---
[INFO] There is 1 error reported by Checkstyle 9.3-SNAPSHOT with /net/sourceforge/pmd/pmd-checkstyle-config.xml ruleset.
[ERROR] src/main/java/net/sourceforge/pmd/AbstractConfiguration.java:[8,1] (imports) RedundantImport: Duplicate import to line 7 - java.nio.charset.Charset.
```

**Comment by romani** [comment]
passed on [Wercker](https://app.wercker.com/checkstyle/checkstyle/runs/build/61c226520adbc8002aabb04e?step=61c23af3dca9a2000767221e):
```
[INFO] PMD Documentation Generator ........................ SUCCESS [  1.070 s]
[INFO] PMD Scala - Transitional package (deprecated) ...... SUCCESS [  0.130 s]
[INFO] PMD Scala for Scala 2.12 ........................... SUCCESS [  4.224 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Pull request merged**
