### PR TITLE
Update doc for MultipleStringLiterals

### PR DESCRIPTION
**Pull request by Jalend15**
Issue #7650
Updatedoc for MultipleStringLiterals 
Java file :MSL.java
XML file: config.xml

### CODE REVIEW

**Comment by wilcoln** [comment]
Hey buddy, 
You might want to take a look at the [PR-rules](https://github.com/checkstyle/checkstyle/wiki/PR-rules)

**Comment by Jalend15** [comment]
> Hey buddy,
> You might want to take a look at the [PR-rules](https://github.com/checkstyle/checkstyle/wiki/PR-rules)
> Also, reviewers left some useful comments at [your first PR](https://github.com/checkstyle/checkstyle/pull/7782), you might want to check that too.
> Hope It helps.

Hello
mvn clean verify is failing in the following way
[ERROR] Tests run: 3189, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:12 min
[INFO] Finished at: 2020-03-10T16:48:04+05:30
[INFO] Final Memory: 48M/766M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project checkstyle: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jalend-15/checkstyle/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

there is one failure 
can u please help me with what i should do
thank you

**Comment by Abhishek-kumar09** [comment]
Hey @Jalend15 please copy-paste the full log of mvn clean verify, Actually the error detail is some lines above `[ERROR] Tests run: 3189, Failures: 1, Errors: 0, Skipped: 0`. Also rebase the git branch and squash the commit. Ask for any help if needed.

**Comment by Jalend15** [comment]
> Hey @Jalend15 please copy-paste the full log of mvn clean verify, Actually the error detail is some lines above `[ERROR] Tests run: 3189, Failures: 1, Errors: 0, Skipped: 0`. Also rebase the git branch and squash the commit. Ask for any help if needed.

[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.254 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.internal.AllTestsTest
[ERROR] testAllTestsHaveProductionCode  Time elapsed: 0.06 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Test must be named after a production class and must be in the same package of the production class: com/puppycrawl/tools/checkstyle/checks/MSL.java ==> expected: <true> but was: <false>
	at com.puppycrawl.tools.checkstyle.internal.AllTestsTest.verifyHasProductionFile(AllTestsTest.java:220)
	at com.puppycrawl.tools.checkstyle.internal.AllTestsTest.lambda$testAllTestsHaveProductionCode$4(AllTestsTest.java:75)
	at com.puppycrawl.tools.checkstyle.internal.AllTestsTest.walk(AllTestsTest.java:81)
	at com.puppycrawl.tools.checkstyle.internal.AllTestsTest.testAllTestsHaveProductionCode(AllTestsTest.java:74)

this is the failure in the build mvn clean verify
i was searching for this in the terminal for a long time got it now
ok i will rebase and squash

**Comment by Abhishek-kumar09** [comment]
Hey! It looks like you are modifying wrong files.
Firstly rebase the branch to latest master branch.
You have to just make changes in `MultipleStringLiteralCheck.java` and `config_coding.xml`
Then once done check your site by `mvn clean site -Pno-validations` and take its screenshot.

**Comment by wilcoln** [comment]
> > Hey buddy,
> > You might want to take a look at the [PR-rules](https://github.com/checkstyle/checkstyle/wiki/PR-rules)
> > Also, reviewers left some useful comments at [your first PR](https://github.com/checkstyle/checkstyle/pull/7782), you might want to check that too.
> > Hope It helps.
> 
> Hello
> mvn clean verify is failing in the following way
> [ERROR] Tests run: 3189, Failures: 1, Errors: 0, Skipped: 0
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 13:12 min
> [INFO] Finished at: 2020-03-10T16:48:04+05:30
> [INFO] Final Memory: 48M/766M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project checkstyle: There are test failures.
> [ERROR]
> [ERROR] Please refer to /home/jalend-15/checkstyle/target/surefire-reports for the individual test results.
> [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> 
> there is one failure
> can u please help me with what i should do
> the java test file and the config file showed no build errors
> in intellijide the build was successful
> thank you

Hey, As the error message suggest, you need to go at your `/home/jalend-15/checkstyle/target/surefire-reports` directory to inspect the individual tests results, there you'll find exactly what goes wrong and why.
Then you'll be able to fix it.

**Comment by Jalend15** [comment]
getCheckMessage(MSG_KEY, "\"StringContents\"", 3)

what is the functionality of this function

**Comment by wilcoln** [comment]
> getCheckMessage(MSG_KEY, ""StringContents"", 3)
> 
> what is the functionality of this function

It returns the violation message to display.

**Comment by Jalend15** [comment]
Should i make changes in MultipleStringLiteralsCheckTest.java or InputMultipleStringLiterals.java OR
InputMultipleStringLiteralsNoWarnings.java

**Comment by wilcoln** [comment]
This issue doesn't require you to do so.
As @Abhishek-kumar09 mentioned, you only have make changes in two files. `MultipleStringLiteralCheck.java` and `config_coding.xml`

**Comment by wltan** [comment]
> Should i make changes in MultipleStringLiteralsCheckTest.java or InputMultipleStringLiterals.java OR
> InputMultipleStringLiteralsNoWarnings.java

The 3 files you mentioned above are related to (it looks like) unit testing, which is not relevant to this issue. You do not have to modify any of those.

I think it's possible that you're looking in the wrong area: `MultipleStringLiteralsCheck.java` can be found in `src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/`. From there, you need to update the javadoc to match the changes you made in `src/xdocs/config_coding.xml`.

**Comment by Jalend15** [comment]
public class Test {

  public void myTest() {

    string name1="ABC";
    string name2="CDE";
    string name3="GFH";
    string name4="ABC";  //violation
    /*more useful in a long 
    list of names to find r repetition*/

    string r="A"+"B"+"C";   //no violation 

    string x=", ";
    string y=", ";    
    /*no violation since comma(followed by a space) is ignored while
    checking for repetitions*/

    string z=". ";
    string h=". ";
    /*no violation since dot(followed by a space) is ignored while
    checking for repetitions*/

    /*
    value='^((". ")|(", "))$'/>
    */
    int y1=1;
    if(y1)
    {
      string d="Hello";
    }
    if(y1)
    {
      string d1="Hello";
    }               
    /*no violation because of the keyword LITERAL_IF which ignores the duplicates in if statements*/


  }

}


This is my java code for update doc
should i create a MyTest() method in MultipleStringLiteralsCheck.java or generate examples in the existing methods in that file

**Comment by wltan** [comment]
https://github.com/checkstyle/checkstyle/blob/e73ec41c667a6aa5bf3213be9fb0a853d372a1c6/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java#L35-L94

Add the examples that you added to `config_coding.xml` to this javadoc. You will notice that it looks similar to `config_coding.xml`, because **they must match**. Whatever changes you added to `config_coding.xml`, you add to this javadoc, and nothing else.

**Comment by Jalend15** [comment]
[example.txt](https://github.com/checkstyle/checkstyle/files/4317882/example.txt)
i edited a part of config_coding.xml
i put that in this txt file
can you tell me whether i am going in the right direction
and the three test methods i used should be copied to the java file right?

**Comment by romani** [comment]
@Jalend15 , please read in issue description section 
`PLEASE READ`, if PR is not formatted as we require, we will not review it.

**Comment by Jalend15** [comment]
OUTPUT 
$ cat config1.xml
Screenshot from 2020-03-13 03-50-55

 <?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
  	<module name="MultipleStringLiterals">
  <property name="allowedDuplicates" value="1"/>
  <property name="ignoreStringsRegexp"
    value='^((". ")|(", "))$'/>
  <property name="ignoreOccurrenceContext" value="ANNOTATION"/>
    </module>
  </module>
</module>


$cat M.java
@interface MyAnnotation {
 String   name();}
public class Test {

@MyAnnotation(name="ME")
  public void myTest() {

    String name1="ABC";
    String name2="CDE";
    String name3="GFH";  //ok
    String name4="ABC";  //violation
    String r="A"+"B"+"C";   //no violation 
    String x=", ";
    String y=", ";    //no violation
    String z="";
    String h="";  //no violation

 } 
  @MyAnnotation(name="ME")   //no violation
  public void foo()
  {
    String s="ME"; 
}

}






java -jar checkstyle-8.30-all.jar -c config1.xml M.java
Starting audit...
[ERROR] /home/jalend-15/M.java:13:18: The String "ABC" appears 2 times in the file. [MultipleStringLiterals]
Audit done.
Checkstyle ends with 1 errors.

**Comment by Jalend15** [comment]
i updated the config_coding.xml and the MultipleStringLiteralsCheck.java file 
i am performing mvn clean verify it is showing failure in 

	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.testAllCheckSections(XdocsPagesTest.java:486)

[INFO] Running com.puppycrawl.tools.checkstyle.internal.AllChecksTest
[Fatal Error] config_javadoc.xml:1168:2: The content of elements must consist of well-formed character data or markup.
[ERROR] Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.396 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.internal.AllChecksTest
[ERROR] testAllCheckstyleModulesHaveXdocDocumentation  Time elapsed: 0.189 s  <<< ERROR!
org.xml.sax.SAXParseException: The content of elements must consist of well-formed character data or markup.
	at com.puppycrawl.tools.checkstyle.internal.AllChecksTest.testAllCheckstyleModulesHaveXdocDocumentation(AllChecksTest.java:459)

[INFO] Running com.puppycrawl.tools.checkstyle.internal.CommitValidationTest

can you please help
thank you

**Comment by Jalend15** [comment]
> @Jalend15 , please read in issue description section
> `PLEASE READ`, if PR is not formatted as we require, we will not review it.

OK i am doing it

**Comment by Jalend15** [comment]
[INFO] Running com.puppycrawl.tools.checkstyle.internal.AllChecksTest
[Fatal Error] config_javadoc.xml:1168:2: The content of elements must consist of well-formed character data or markup.
[ERROR] Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.223 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.internal.AllChecksTest
[ERROR] testAllCheckstyleModulesHaveXdocDocumentation  Time elapsed: 0.249 s  <<< ERROR!
org.xml.sax.SAXParseException: The content of elements must consist of well-formed character data or markup.
	at com.puppycrawl.tools.checkstyle.internal.AllChecksTest.testAllCheckstyleModulesHaveXdocDocumentation(AllChecksTest.java:459)


why is this file showing error i havent even edited it
pleasehelp

**Comment by rdiachenko** [comment]
@Jalend15 please update your **first post** according to https://github.com/checkstyle/checkstyle/pull/7817#issuecomment-598226078

Also do rebase on master, your branch is too behind current master.

**Comment by strkkk** [comment]
Closed as abandoned

**Pull request closed without merging**
