### PR TITLE
Issue #13501: Kill mutation for JavadocTagContinuationIndentationCheck

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13501: Kill mutation for JavadocTagContinuationIndentationCheck

----

# Check
https://checkstyle.org/checks/javadoc/javadoctagcontinuationindentation.html#JavadocTagContinuationIndentation

-------

# Mutation 
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L507-L514

-----

# Explaination

Test added

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Review by romani — APPROVED** [review]
Ok to merge if reports are clean

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
@Kevin222004 , CI is red

**Comment by romani** [comment]
Rebased

**Comment by romani** [comment]
@Kevin222004 , hard CI failure https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/47838603/job/9xejjdqxipvuk0ja#L322 after your update.

**Comment by Kevin222004** [comment]
@romani done test added

I have done some mistake while evaluating this

**Review by romani — APPROVED** [review]

**Pull request merged**
