### PR TITLE
Issue #924: Fix enforcement of declaration order which leads to illegal forward reference

### PR DESCRIPTION
**Pull request by MEZk**
@romani 
OOM exception happened during Travis CI execution.

### CODE REVIEW

**Comment by romani** [comment]
@MEZk , CI items were relaunched.

**Comment by MEZk** [comment]
@romani 
It seams to me that there is a memory leak in my changes. I'll check it a bit later.

**Comment by romani** [comment]
I relaunched Travis for HEAD revision of master, if HEAD build is green it highly likely that OOM is introduced by your changes.

**Comment by MEZk** [comment]
@romani 
OOM exception has been fixed.

Circle CI log:
```
Cloning git repository 'lucene-solr' to src/main/java/lucene-solr folder ...
Cloning into 'src/main/java/lucene-solr'...
remote: Counting objects: 733040, done.
remote: Total 733040 (delta 0), reused 0 (delta 0), pack-reused 733040
Receiving objects: 100% (733040/733040), 201.21 MiB | 18.89 MiB/s, done.
Resolving deltas: 100% (425317/425317), done.
Checking connectivity... done.
Cloning git repository 'lucene-solr' - completed

Reseting git sources to commit 'lucene_solr_5_4_0'
fatal: ambiguous argument 'lucene_solr_5_4_0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:

'git <command> [<revision>...] -- [<file>...]' case $CIRCLE_NODE_INDEX in 0) eval $TEST_1 ;; 1) eval $TEST_2 ;; 2) eval $TEST_3 ;; 3) eval $TEST_4 ;; esac returned exit code 128
```

**Comment by romani** [comment]
please explain why we need additional whole tree traversing at the beginTree ?
I think you can extend set of acceptableTokens and collect this information by visitToken method.

**Comment by MEZk** [comment]
@romani 

>please explain why we need additional whole tree traversing at the beginTree ?

I had wrong tree model of illegal forward reference in my head)
Fixed.

**Comment by romani** [comment]
Please reset to empty collection `scopeStates` in beginTree method. All fields that used for collecting data for valudation has to be reset in this method to avoid very hard to reproduce problems on validation over multiple files

**Comment by romani** [comment]
6)
> `private Set<DetailAST> variableDefinitions;`

this collection contains only fields, so should be named appropriately.

7)
>
```
            if (!ignoreModifiers
                    && isLegalForwardReference(ast)) {
                 log(ast, MSG_ACCESS);
```

It is very strange why "Legal" lead to violation, please recheck method name.

8)
>
```
        for (DetailAST definition : variableDefinitions) {
            for (DetailAST identifier : expressionIdentifiers) {
```

please swap FORs as expressionIdentifiers will be shorter most of the time. Referencing other field is very rare case in code.

**Comment by MEZk** [comment]
@romani 
1) Done.

2) Done. PR:
https://github.com/checkstyle/checkstyle/pull/2859

3) Diff report were generated for the following projects: Guava, Spring, Hibernate, FindBugs, PMD, Hbase.
http://mezk.github.io/checkstyle_merged.html

Explanations:

3.1) Illegal forward reference detection:
* FindBugs:  ValueNumberAnalysis.java (62), 
* HBase: TestCoprocessorInterface.java (79), TestRegionObserverScannerOpenHook.java (74), TestRegionObserverStacking.java (48), TestHFileSeek.java (264), TestAssignmentManagerOnCluster.java (95), TestCompaction.java (89), TestMajorCompaction.java (77), TestMinorCompaction.java (57)

3.2) Cases similar to the [example](https://github.com/checkstyle/checkstyle/pull/2828/files#diff-2a65d159ef70f59f84b54c1bcf21271bR18) in UT input
The position of the current field definition depends on fields which are used in the expression that is assigned to the current field. We should determine the position of the fields which are used in the expression as identifiers first and then change the position of the field if nesseccarry. We cannot change the position of the current field first, because illegal forward reference may appear.

* HBase: KeyValue.java (127, 130, 140), TableName.java (77), AES.java (55), Bytes.java (89), IntegrationTestManyRegions.java (70), LocalHBaseCluster.java (71), HRegion.java (7268), PerformanceEvaluation.java (130), TestReplicationBase.java (70), TestVisibilityLabelsReplication.java (98), LoadTestTool.java (88, 97).
* PMD: AbstractPropertyDescriptorTester.java (43).
* FindBugs: FieldAnnotation.java (63), FindBugs2.java (92), Version.java (128), Analysis.java (65), ClassFeatureSet.java (322), LaunchBrowser.java (43).

4) Done.
5) Yes, you are making a point. Done.
6) Renamed.
7) Renamed.
8) Method logic has been changed to avoid such cases.

**Comment by romani** [comment]
postponed till 6.16

**Comment by romani** [comment]
1)
> if (!ignoreModifiers
                    && !isIllegalForwardReference(ast.getParent())) {

"incorrect forward reference" should not be used as it is compilation error and Checkstyle do not work on non-compiled sourced. So you will not have such situation in code. Please stop using this term at all.
Please add this link to javadoc/xdoc
http://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.3.3 , and make a note that we do keep in consideration this rule.

should be 
```
if (!ignoreModifiers
                    && !isForwardReference(ast.getParent())) {
```

2) 
> workDeque.clear();

please remove this, collection will be garbage-collected after method is finished. no need to preclean it.

3)
> if (!ScopeUtils.isLocalVariableDef(ast)) {

please update ScopeUtils to have isClassFieldDef, and please avoid "!" in Check code.

4)
> 
```
   /** Index of previous field name. */
    private static final int PREV_FIELD_NAME_INDEX = 2;

final String prevFieldName = fieldNames.get(fieldNames.size() - PREV_FIELD_NAME_INDEX);
```
I do not understand this. Fields could be located at any distance between each other. Why "2" is number that helps us ? Please explain.

5)
> reports

reports are strange. In "TestCoprocessorInterface" I see no forward refence , violation should be there.
"KeyValue.java" I see no reason to even move filed up, all of them are "public static final int" .

**Comment by MEZk** [comment]
@romani 
In TestCoprocessorInterface illegal forward reference will appear if we switch line 78 and 79. Before changes the check forces user to switch line 78 and 79.

> 1. Class (static) variables. First the public class variables, then protected, then package level (no access modifier), and then private. 

 This behaviour was the main problem which I fixed in the PR.

In KeyValue.java there is a field with private modifier on line 83 and package-level modifier on line 85. According to the documentation static members with public modifiers should be first. So, static members on lines 90, 92, 99, 104, 109, 112, 115, 118, ... should be placed before private static member on line 83. Package-level static member on line 85 should be placed before EMPTY_ARRAY_LIST.

If you have any questions concerning reports, we can discussed them via Skype on Thursday or weekends.

**Comment by romani** [comment]
after discussion, cases become clear to me.

**Comment by MEZk** [comment]
@romani 
1) Done.
2) Done.
3) Done.
4 and 5) Changed in accordance with the discussion in Skype.

New reports:
http://mezk.github.io/checkstyle_merged.html

**Pull request merged**
