### PR TITLE
Testing config gen

### PR DESCRIPTION
**Pull request by relentless-pursuit**
This is a test PR. 
activity in scope of https://github.com/checkstyle/test-configs/issues/16

Diff Regression config: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example1/config.xml

Diff Regression projects: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example1/list-of-projects.properties

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by romani** [comment]
running - https://github.com/checkstyle/checkstyle/actions/runs/9332920143

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
it was 50 min of execution - too much

image

**Comment by romani** [comment]
lets do https://github.com/checkstyle/test-configs/issues/17 and repeat.

**Pull request closed without merging**
