### PR TITLE
Issue #5777: converted line only checks to log ast

### PR DESCRIPTION
**Pull request by rnveach**
Issue #5777

Converted all easy loggers. There are still others in this issue.
Regression would show too many changes as violation change from line to line:column.

### CODE REVIEW

**Comment by romani** [comment]
>Regression would show too many changes as violation change from line to line:column.

Change is awesome work, but let's split it Check by Check. With updates for xpath suppress tests and regression for one Check. In such workflow we will control regression. Does it make sense ?

**Comment by rnveach** [comment]
jacoco is reporting this weird but I am missing coverage in `isSuppressedAfterEventStart`  for, I believe, `entry.getFirstLine() == line && column == 0`.

suppresswarningsholder

**Comment by rnveach** [comment]
Rebased for conflicts from other issue.

**Comment by romani** [comment]
whole idea of changes to report violation on line:column is for xpath support.
But if that update is not enough to suppress violation, this update have no reason to happen.
We need to have such tests, it is prove that update in reporting is reasonable.
It will cause each Check to be in separate PR, that is easy to review and validate.

**Comment by rnveach** [comment]
Its possible new violations can't be supported because there are bugs in areas of xpath that we already have opened issues on. I am waiting for them to be fixed before adding the full xpath regression I created for every token in every java file we have.

I will close this PR for now and make a note in issue.

**Pull request closed without merging**
