### PR TITLE
Issue #5738: remove author javadoc tag

### PR DESCRIPTION
**Pull request by romani**
Issue #5738

### CODE REVIEW

**Comment by romani** [comment]
> Suppression for author can be removed.

done.

All commits were squashed and merged manually.

**Comment by rnveach** [comment]
@romani Changes to configuration does not produce a violation on my old works that still have an author tag.

**Comment by romani** [comment]
New configuration should not violate any author tag anymore, we just skip it.

**Comment by rnveach** [comment]
So then we are not actively doing anything to prevent people from putting in this name and adding it to the whitelist.

**Pull request closed without merging**
