### PR TITLE
Update TranslationCheck.Java

### PR DESCRIPTION
**Pull request by harshitmalik03**
2 Typos corrected .

### CODE REVIEW

**Comment by romani** [comment]
Please review why CI are failing and update commit.
Commit message is wrong 
Strange that this typo was not detected by our spell checker 
And it is not extra whitelisted word https://github.com/checkstyle/checkstyle/blob/master/.ci/jsoref-spellchecker/whitelist.words#L895

**Comment by harshitmalik03** [comment]
Ive reviewed the checks and im not able to figure out why the checks are not working..... Please help me on this ! And sorry i did not know what we had to write in the commit message.

**Comment by romani** [comment]
Read message of failure, you can reproduce it on your local by `mvn verify`

You need to make commit message has prefix "minor: " and make commit message single line.

**Comment by romani** [comment]
wercker:
`fetch failed to pull image maven: API error (500): {"message":"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"} `

**Review by romani — APPROVED** [review]
ok to merge.

**Review by harshitmalik03 — COMMENTED** [review]
Minor: Documentation Changes

**Pull request merged**
