### PR TITLE
Refactored: updated Main.java to have system.exit be placed in one method Issue#596

### PR DESCRIPTION
**Pull request by dbngshuroy**
Instead of calling System.exit from each methods, now an ApplicationExitException is thrown which is finally handled in main method only.

### CODE REVIEW

**Comment by romani** [comment]
please remove formatting(extra spaces) changes from commit.

**Comment by dbngshuroy** [comment]
May you please guide me about formatting. I am using eclipse as IDE and
used this custom formatting
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/CheckstyleFormatterForEclipse.xml

But apparently is does not remove extra spaces.

**Comment by romani** [comment]
please do that manually, we do not have Eclipse formatter config yet for main project, sorry.
If you intrested you can try to invent it as separate issue.

**Comment by dbngshuroy** [comment]
Ok. I have to learn more about eclipse formatter in order to do so. Should
I open an issue?

**Comment by romani** [comment]
please fix that issue first , and then open new issue

**Comment by dbngshuroy** [comment]
I refactored and removed extra white space to make the commit compact. But the coverage decreased.

**Comment by romani** [comment]
coverage should not decrease, we need to extend tests :).

I still see 4 commit, it is not acceptable. I need only one commit.

**Comment by dbngshuroy** [comment]
I squashed all commits into one. If Coverage decrease then I will write add test cases,

**Comment by dbngshuroy** [comment]
Unfortunately I can not find any JUnit test for main class. Any addition in Main.java would decrease in coverage, I guess.

**Comment by romani** [comment]
Please create a new junit test file and do a testing.

**Comment by dbngshuroy** [comment]
The main class has four five private methods to load checker,properties,configs,audits etc and those are called from main method only. Normally we need not to test private methods as they can be tested from public methods indirectly. But I can not come up with an idea to indirectly test these private methods by testing main only without changing a lot in code.I cannot directly test private methods but I can use [reflection](http://stackoverflow.com/questions/34571/how-to-test-a-class-that-has-private-methods-fields-or-inner-classes) to access them. Should I do so? Most of the decrease in coverage is due to not testing main() and private methods called from main(). If I test them there should be increase in coverage.

**Comment by romani** [comment]
1) no reflection is required, all console applications are 100% testable from UTs - just do in test method "Main.main(arguments.....)" and do testing ,what you might need is too override console output to your stream to verify its content after "Main.main()" execution.

I still see a lot of "System.exit(1);" in  code and not only from "main" method - all of them have to be resolved - main method should have one "return/exit" point on error.

2) 
> ApplicationExitException

there is no constructor that have "cause" parameter, design of Exception is unacceptable. And you do not need special exception there, as all exceptions should stop main method with exit(1), just let Exception to go up to JVM and it will be printed in console by default.

**Comment by romani** [comment]
@dbngshuroy, are you planing to finish that update ? 
Can I reassign that issue to another contributor ? it is better to not block issue if you think that you will not have time in next few weeks.

**Comment by romani** [comment]
We lost connection with contributor, i am closing PR to let others fix that issue

**Pull request closed without merging**
