### PR TITLE
Fix xml structure at google_checks.xml, #1275

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by romani** [comment]
I need fixes for all points described in issue.

**Comment by Vladlis** [comment]
@romani, please review

**Comment by romani** [comment]
1) > Has unresolved violation.

please create issue on that and put link to it in that commit

2)
> ConfigurationBuilder.java
getmFiles()

What is does "getm" mean ? 
please rename "mFiles" to "files" , and make method named by English words. If you see other fields with "m" prefix  - remove that prefix by separate commit.

**Comment by romani** [comment]
compilation on java7 has to be resolved, as we support that version of java, and that is required for nemo.sounarqube.com build

try to install the same versions of java+maven as on Travis:
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation

**Comment by romani** [comment]
instead of "Has unresolved violation." should be link to issue like "commented till !!!!LINK!!!!"

**Comment by romani** [comment]
> for (Configuration config : config.getChildren()) {

field and variable are named the same, please fix that.

PS:
that is sad that our own Check http://checkstyle.sourceforge.net/config_coding.html#HiddenField is still unused https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L279 , one day , one day ......

**Comment by Vladlis** [comment]
> instead of "Has unresolved violation." should be link to issue like "commented till !!!!LINK!!!!"

Done
> field and variable are named the same, please fix that.

Done

**Comment by romani** [comment]
merged as FF.

verified, now we fail on incorrect xml structure at the beginning of verify stage and fail ITs if launch on whole config return error.

**Pull request closed without merging**
