### PR TITLE
Issue #3954 MethodParamPadCheckTest input files splited

### PR DESCRIPTION
**Pull request by GitToasterhub**
Issue #3954 created new methodparampad directory.Input files of MethodParamPadCheckTest moved to there.

### CODE REVIEW

**Comment by rnveach** [comment]
@GitToasterhub You don't need to redo the PR when squashing commits. Any updates you make to branch will be reflected in PR and CIs will trigger again.

**Comment by GitToasterhub** [comment]
Oh,I hadn't known it.I deleted that branch and pulled new branch,as you
said that only 1 commit must be,so the first what came to my mind is to
create new branch and pull then.Is it now OK,or still something wrong?

2017-03-10 23:43 GMT+02:00 rnveach <notifications@github.com>:

**Comment by rnveach** [comment]
@GitToasterhub One test is failing, please fix it.
See https://travis-ci.org/checkstyle/checkstyle/jobs/209879036#L873-L883

**Comment by GitToasterhub** [comment]
@rnveach Can it be caused because  I changed project,and hadn't rebuilt it before commit? Now I rebult the project and it was successful,or it the case is not in this?

**Comment by GitToasterhub** [comment]
oh probabbly not I got fail reason in CommitValidationTest

**Comment by GitToasterhub** [comment]
My issue is bad commit message,I am working on it to solve.

**Comment by rnveach** [comment]
@GitToasterhub As I said before, you don't need to close the PR to make changes. You can keep re-using the same PR and branch.
Each new PR makes it harder for us as we can't remember what we have told you before and you can't see it all in one place.

**Comment by GitToasterhub** [comment]
Sorry for that,I didn't meant to close,I made 2 commits that were useless
and when I reverted them PR get closed by itself.

2017-03-11 15:56 GMT+02:00 rnveach <notifications@github.com>:

**Pull request closed without merging**
