### PR TITLE
Issue #3898: Field check and splits done for whitespaceAround

### PR DESCRIPTION
**Pull request by nikshinde1996**
Issue: #3898

### CODE REVIEW

**Comment by MEZk** [comment]
@nikshinde1996 
Do not ignore my remarks.
https://github.com/checkstyle/checkstyle/pull/3981#issuecomment-285854109

CIs need to be green.

**Comment by nikshinde1996** [comment]
I did " mvn clean verify " check on the project and it showed me the errors on for the Scripts that I haven't written/modified.  How should I deal with such MojoFailureException

**Comment by rnveach** [comment]
@nikshinde1996 you don't need to keep creating new PRs. You can amend the previous commit and push to the same branch. Github and the CIs will recognize the changes and refresh everything.

**Comment by rnveach** [comment]
> it showed me the errors on for the Scripts that I haven't written/modified.

We can't help unless we see the results of the CI.
From the files you have changed, You shouldn't be adding new tests. We just want you to copy/move input files to a new folder and rename them to follow our new pattern.
See previous work as an example: https://github.com/checkstyle/checkstyle/commit/90f6cdc814f093a135ba1e50847dd86134120967

**Comment by romani** [comment]
@nikshinde1996, if you keep closing and opening PRs - I will block your account.
I give you last warning.

**Comment by nikshinde1996** [comment]
@romani .... I had deleted the previous branch and hence to continue to same branch I needed to restore and set PR branch.... I apologize ... I will be cautious next time.

**Pull request closed without merging**
