### PR TITLE
Issue #13213: Remove '//ok' comments from Input files (InputNoEnumTrailingComma)

### PR DESCRIPTION
**Pull request by MauryanKansara**
Part of #13213 

Link to documentation: [click here](https://checkstyle.org/checks/coding/noenumtrailingcomma.html#NoEnumTrailingComma)

proof that all supressions for this check are removed

```
Zopsss@Zops-Laptop MINGW64 /c/Open Source/checkstyle (master)
$ grep noenumtrailingcomma  config/checkstyle-input-suppressions.xml
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>
            files="checks[\\/]coding[\\/]noenumtrailingcomma[\\/]InputNoEnumTrailingComma.java"/>

Zopsss@Zops-Laptop MINGW64 /c/Open Source/checkstyle (master)
$ git checkout InputNoEnumTrailingComma#13213 
Switched to branch 'InputNoEnumTrailingComma#13213'

Zopsss@Zops-Laptop MINGW64 /c/Open Source/checkstyle (InputNoEnumTrailingComma#13213)
$ grep noenumtrailingcomma  config/checkstyle-input-suppressions.xml

Zopsss@Zops-Laptop MINGW64 /c/Open Source/checkstyle (InputNoEnumTrailingComma#13213)
$ echo $?
1
```

### CODE REVIEW

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Changes look good, please squash all into first commit and make sure that mvn clean verify passes on your local before pushing changes to your PR. Thanks!

**Comment by MauryanKansara** [comment]
> Changes look good, please squash all into first commit and make sure that mvn clean verify passes on your local before pushing changes to your PR. Thanks!

squashed both commits and ran `mvn clean verify` and the build was success.

**Comment by romani** [comment]
Keep single commit in your branch and PR

**Comment by nrmancuso** [comment]
@MauryanKansara please make CI happy

**Comment by MauryanKansara** [comment]
> @MauryanKansara please make CI happy

Done! Now all checks are passing including the CI checks.

**Comment by MauryanKansara** [comment]
@nrmancuso can you review the PR again?

**Review by romani — APPROVED** [review]
Ok to merge if ci pass

**Comment by MauryanKansara** [comment]
@nrmancuso

**Comment by MauryanKansara** [comment]
> Ok to merge if ci pass 

Hey @romani can you merge my PR if possible? So I can start working on other issues. Sorry for asking you this

**Comment by romani** [comment]
Please start working on other issue, this PR will hang until @nrmancuso confirm all is good.

**Comment by MauryanKansara** [comment]
> Please start working on other issue, this PR will hang until @nrmancuso confirm all is good.

Ohkayyy thanksss!

**Comment by MauryanKansara** [comment]
@nrmancuso

**Comment by romani** [comment]
Change is simple, @nrmancuso , did not have any specific review points. I merged this PR by single review as we agreed before

**Pull request merged**
