### PR TITLE
Issue #4845: added suppressions to allow slow issue fixing

### PR DESCRIPTION
**Pull request by rnveach**
Issue #4845

Everything reported is suppressed and tied to this issue.

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge if CI pass

**Comment by rnveach** [comment]
I restarted semaphoreci but it still fails with a weird error.
> Caused by: java.lang.ClassNotFoundException: org.stringtemplate.v4.STGroup

https://checkstyle.semaphoreci.com/jobs/c8e7b04e-f5e5-409b-beed-72033ec2eb75

**Comment by romani** [comment]
Same in other PR

**Comment by romani** [comment]
You can merge, it is not related and your update is checked by other CIs

**Pull request merged**
