### PR TITLE
Issue #2240: Fix false negatives in RequireThisCheck

### PR DESCRIPTION
**Pull request by Vladlis**
This fixes both false-negatives from the issue.
Report: https://vladlis.github.io/reports/requirethis
I've reviewed almost all violations from the report, except from a lot of similar ones against guava.

### CODE REVIEW

**Comment by romani** [comment]
please split name refactoring and functional changes in two separate commits. Functional changes and minor refactoring should always be separated. Minor refactoring is unlikely to be reverted. Functional changes could be reverted.

**Comment by mkordas** [comment]
@Vladlis 
Thanks, impressive update. We just need more test coverage:
```
[ERROR] com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck$LexicalFrame failed coverage check. Branch coverage rate of 95.0% is below 100.0%
[ERROR] com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck$ClassFrame failed coverage check. Branch coverage rate of 92.8% is below 100.0%
[ERROR] project failed coverage check. Branch coverage rate of 99.9% is below 100.0%
 ```

**Comment by romani** [comment]
this Check blow my mind :) .

Documentation also does not have a reason http://checkstyle.sourceforge.net/config_coding.html#RequireThis why Check is required and why all his options make sense.

does anybody know why the same for variable and method is trigger for this Check to put violation ? Java do not have method as first-class citizen (as it is in functional languages - Scala, ... ) so there could not be misunderstanding of that is used.  Even this is case, so what is expected when field and method have the same name ? 

If no good reason you can find, I would rather remove this matching between method and field or as minimum put it under option.

**Comment by romani** [comment]
```
class A {
   private pr;
   void pr() {}

   void example() {
       pr = 4;  //violation
       pr();   //violation
    }
}
```
vs

```
class A {
   private pr;
   void pr() {}

   void example() {
       this.pr = 4;  //OK ?
       this.pr();   //OK ?
    }
}
```

**Comment by Vladlis** [comment]
> this.pr();   //OK ?

Actually it doesn't make sense to me.

> I would rather remove this matching between method and field or as minimum put it under option.

The check has such an option and it is TRUE by default.

**Comment by romani** [comment]
@mkordas , please share your opinion on behaviour of this Check (disable completely or do field-method-match by option). 
If you also do not see a reason in it, I will merge this PR and create issue to change behaviour.

**Comment by mkordas** [comment]
@romani I do not understand the question. For me this check has two features:
* detecting instance field access not qualified with `this`
* detecting instance method call not qualified with `this`

The second feature can be enabled or disabled by `checkMethods` parameter, but I don't see any `field-method-match` logic.

BTW, my personal opinion is that this check should be deprecated (displaying warning in logs for everyone using it) and removed in 7.0 - it just does harm to Java community by unnecessarily increasing verbosity of code. Instead, we should implement `RedundantThis` check.

**Comment by romani** [comment]
> BTW, my personal opinion is that this check should be deprecated (displaying warning in logs for everyone using it) and removed in 7.0 - it just does harm to Java community by unnecessarily increasing verbosity of code

In general I agree but it is too late to do this. Here is case where it might be useful - https://github.com/checkstyle/checkstyle/issues/2362 . It is used a lot, see search on github. My idea is update this Check and let it used even on our Code. After fix at #2362 , it will be possible.

> Instead, we should implement RedundantThis check.

Yes, we can do. Please make as issue on this , if it is not created yet. But RedundantThis and RequireThis could work together.

**Comment by romani** [comment]
Current behaviour is weird by design:

```
/var/tmp $ cat 3.java 
package test;

class Test {
	private String value = "value";

	void foo(String value) {
		value = value; 
		foo1();                    //violation
	}

	void foo1() {
	    String value = "values";
	    value = value; 
	    foo2();                         //violation
	}

	void foo2(String value1) {
	    value = value1;           //violation
	}

} 
/var/tmp $ cat 3.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
	<module name="RequireThis" />
  </module>
</module>

/var/tmp $ java -jar checkstyle-6.12.1-all.jar -c 3.xml 3.java
Starting audit...
/var/tmp/3.java:8:17: error: Method call to 'foo1' needs "this.".
/var/tmp/3.java:14:13: error: Method call to 'foo2' needs "this.".
/var/tmp/3.java:18:13: error: Reference to instance variable 'value' needs "this.".
Audit done.
Checkstyle ends with 3 errors.
```

**Comment by mkordas** [comment]
Let's do it that way then. Current violations are corect but useless, so we should extend them to detect also suspicious self-assignments.

**Comment by romani** [comment]
I call back my "field-method-match" term, was misleaded by report line 
"near.1 	 Warning 	coding 	RequireThis 	Method call to 'a' needs "this.". 	276 	site_after" and discussion with @Vladlis . 
ReqireThis doesnot care about names matching and just demand this at any place, report after bug fix just add more violations that were missed from validation.

```
/var/tmp $ java -jar checkstyle-6.12.1-all.jar -c 3.xml Orekit/src/main/java/org/orekit/propagation/semianalytical/dsst/utilities/hansen/HansenTesseralLinear.java

....
/var/tmp/Orekit/src/main/java/org/orekit/propagation/semianalytical/dsst/utilities/hansen/HansenTesseralLinear.java:276:21: error: Method call to 'c' needs "this.".
/var/tmp/Orekit/src/main/java/org/orekit/propagation/semianalytical/dsst/utilities/hansen/HansenTesseralLinear.java:276:49: error: Method call to 'b' needs "this.".
...
```

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
