### PR TITLE
Issue #13675: add constructor call token to MethodParamPadCheck

### LINKED ISSUE #13675: MethodParamPad ignores explicit constructor invocation
I have read check documentation: https://checkstyle.sourceforge.io/checks/whitespace/methodparampad.html#MethodParamPad
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash

➜  src cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <property name="severity" value="error"/>
  <property name="fileExtensions" value="java, properties, xml"/>
  <module name="TreeWalker">
    <module name="MethodParamPad">
      <property name="option" value="space"/>
    </module>
  </module>
</module>

➜  src cat -n Test.java
     1  public class Test {
     2      public Test () {} // ok, whitespace between id and ()
     3  
     4      public Test (int x) {
     5          this (); // ok, 'this' seems to be ignored
     6          toString (); // ok, whitespace between id and ()
     7      }
     8      public Test (int x, int y) {
     9          this(x + y); // should be a violation
    10          toString(); // violation
    11      }
    12  
    13      public Test (int x, int y, int z) {
    14          super(); // violation, super constructor call is checked
    15          toString(); // violation
    16      }
    17  
    18      public Test (int x, int y, int z, int a) {
    19          super (); // ok, whitespace between 'super' and ()
    20          toString(); // violation
    21      }
    22  }

➜  src javac Test.java 

➜  src java -jar checkstyle-10.12.3-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:10:17: '(' is not preceded with whitespace. [MethodParamPad]
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:14:14: '(' is not preceded with whitespace. [MethodParamPad]
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:15:17: '(' is not preceded with whitespace. [MethodParamPad]
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:20:17: '(' is not preceded with whitespace. [MethodParamPad]
Audit done.
Checkstyle ends with 4 errors.

```

---

I would expect Checkstyle to show a violation for the following:
```java
this(x + y);
```

Example: 
```bash
➜  src java -jar checkstyle-10.12.3-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:9:13: '(' is not preceded with whitespace. [MethodParamPad]
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:10:17: '(' is not preceded with whitespace. [MethodParamPad]
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:14:14: '(' is not preceded with whitespace. [MethodParamPad]
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:15:17: '(' is not preceded with whitespace. [MethodParamPad]
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:20:17: '(' is not preceded with whitespace. [MethodParamPad]
Audit done.
Checkstyle ends with 4 errors.

```

The TLDR; is that if this check validates super constructor invocations, it should also validate explicit constructor invocations.

### PR DESCRIPTION
**Pull request by strkkk**
Closes #13675 

Diff Regression config: https://gist.githubusercontent.com/strkkk/238b6c97492ff6ffdb3be1603deca8fc/raw/f60ac5a16eb2fc4516ed203c4cf31e45c3e94ca6/config_single_2.xml

### CODE REVIEW

**Comment by strkkk** [comment]
github, generate report

**Review by romani — APPROVED** [review]
Ok to merge 

But please do one more report without `with_space` it produces bunch of noise. Better to keep them separately.

**Comment by strkkk** [comment]
github, generate report

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Please add a new test case with input similar to what is in the issue with constructor calls that have some arguments.

**Comment by strkkk** [comment]
@nrmancuso done

**Review by nrmancuso — APPROVED** [review]

**Pull request merged**
