### PR TITLE
Introduce new handler SynchronizedHandler for checking identation. Fixes #580

### LINKED ISSUE #580: Indentation and synchronized block
I think there is an issue with indentation tracking:
```java
public final class Singleton {
    // ...
    public static Singleton getInstance() {
        if (instance == null)
            synchronized (Singleton.class) {
                if (instance == null) // 'if' have incorrect indentation level 16, expected level should be 12.
                    instance = new Singleton();
            }
        return instance;
    }
}
```
Here is my checkstyle configuration:
```xml
<module name="Checker">
  <module name="TreeWalker">
    <module name="Indentation">
    </module>
  </module>
</module>

```

### PR DESCRIPTION
**Pull request by liscju**
Discussion what bad was going on is in discussion for issue #580. It introduces new SynchronizedHandler for synchronized expressions. To distinguish between synchronized method and synchronized block it has  isOnlyMethodModifier field which is determined by isMethodModifier method.

### CODE REVIEW

**Comment by romani** [comment]
Build is failed

**Comment by liscju** [comment]
Code Test Coverage is too small, im going to fix this soon

**Comment by romani** [comment]
please rebase a commit, I am close to review it.

**Comment by liscju** [comment]
@romani rebase done

**Comment by romani** [comment]
1)
> pom.xml

I expect no changes to POM, please do 100% coverage.

==========================

https://github.com/liscju/checkstyle/blob/5cc76be2460d5216e7de0f43ec40ffe80170aa68/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SynchronizedHandler.java

2) 
> Tells if synchronized is only modifier of method

should be :
Determine that "synchornized" token used as modifier of method.

3) 

> isOnlyMethodModifier

rename to "isMethodModifier"

4) 
> private void checkSynchronizedExpr()

please keep order of methods, that private have to be declared after first usage.

5) 
>  public void checkIndentation()

please do - one return point.

6) 
Please generate HTML report over Guava sources before your fix and after for only Indentation check, to verify that nothing else is changed.
please test your changes over wide set of opensource projects that have "synchronized" token - https://github.com/checkstyle/contribution/tree/master/checkstyle-tester (It will be very hard to check intentation, but lets check that there are no exceptions atleast)

7) please test https://github.com/checkstyle/google-style-config-test on your changes.

8) please run https://github.com/checkstyle/resources/blob/master/test-no-exceptions.sh to test for exceptions.

**Comment by romani** [comment]
@liscju , if you finish that PR before Saturday , you will be released in 6.5 .

**Comment by liscju** [comment]
1) DONE
2) DONE
3) DONE
4) DONE
5) DONE
6) TO BE DONE,i dont know how to generate HTML report, i looked at executing checkstyle from command line(from checkstyle page) and i dont see anything about it
7) i have no idea how to run it,i supposed it should work just with 'mvn clean install' but i encoured errors:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
3.2:testCompile (default-testCompile) on project google-style-config-test: Compi
lation failure: Compilation failure:
[ERROR] \Users\lee\Projects\ToRead\google-style-config-test\src\test\java\com\go
ogle\checkstyle\test\base\ConfigurationBuilder.java:[33,28] error: cannot find s
ymbol
[ERROR] \Users\lee\Projects\ToRead\google-style-config-test\src\test\java\com\go
ogle\checkstyle\test\base\IndentationConfigurationBuilder.java:[151,28] error: c
annot find symbol

8) I am developing in windows, does it exist version for windows?

**Comment by romani** [comment]
@liscju

> i dont know how to generate HTML report, i

https://github.com/checkstyle/contribution/tree/master/checkstyle-tester , just read README.md, it has all instructions how to do that. Let me know if that still a problem.

> with 'mvn clean install' but i encoured errors

please sync your fork and our repo, that problem was fixed yesterday.

> I am developing in windows, does it exist version for windows?

no :( . we deprecated windows development environment a long time ago. Do you have any virtual linux box ?

**Comment by romani** [comment]
please remove ".*.checks.indentation.SynchronizedHandler" from POM, as it 100% covered line is not required, finally we will remove all that exception(less then 100) lines from POM file .

**Comment by liscju** [comment]
@romani
I launched checkstyle-tester with 
./launch.sh -Dcheckstyle.config.location=my_check.xml

and got error:
Running Checkstyle on src/main/java - finished
Testing Checkstyle finished
linking report to index.html
mv: cant do stat on target/site/index.html, there is no such file or directory
ln: cant create link „target/site/index.html”: there is no such file or directory
Done.

**Comment by romani** [comment]
please push all changes to your remote fork to share with me all details

**Comment by romani** [comment]
@liscju , ping

**Comment by romani** [comment]
@liscju , I reproduced similar problem in checkstyle-tester. I update it , please read README.md "Attention: this project by deafult use released version of Checkstyle ............"

**Comment by romani** [comment]
@liscju, please let me know what cause you a problem to proceed.

**Comment by romani** [comment]
test-no-exceptions.sh - passed

need to test:
1) checkstyle-checker 
2) comparison for reports (before and after a fix) for Indentaiton Check only - https://github.com/checkstyle/checkstyle/wiki/How-to-generate-Checkstyle-report-for-Google-Guava-project

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
