### PR TITLE
test: regression-testing in sync with test-config

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Resolves: https://github.com/checkstyle/test-configs/issues/16

Diff Regression config: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example2/config.xml

Diff Regression projects: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example2/list-of-projects.properties

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
@romani as you mentioned of 50 mins duration, i assume i shall wait for my changes in test-config on new properties file to be merged and then i can test what has been discussed earlier i.e. testing example1, example2, example3 and getting the cummulative time.

**Comment by romani** [comment]
You need to remove from all configs all refereed.

Please read issue description attentively, you don't need to create new commit, just a PR from your infra branch to master of checkstyle.
Please do.

**Comment by relentless-pursuit** [comment]
> You need to remove from all configs all refereed.
> 
> Please read issue description attentively, you don't need to create new commit, just a PR from your infra branch to master of checkstyle. Please do.

Yes, now, i can see the PR merged. I will replicate the changes for all the properties file i.e. refactor them. I was waiting for your confirmation if the changes were right. Meanwhile, i can run report generation here for the specific example for which the PR is merged.

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by romani** [comment]
you removed only one project, but there to remove a bunch.

**Comment by relentless-pursuit** [comment]
> you removed only one project, but there to remove a bunch.

Yes, i know. I will raise a new PR to refactor all the project files.

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9338712845/job/25702184715

**Comment by romani** [comment]
I canceled action, please remove all that I referenced in issue.

**Comment by relentless-pursuit** [comment]
> I canceled action, please remove all that I referenced in issue.

Okay

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9344991208/job/25717060826

**Comment by relentless-pursuit** [comment]
For `AbbreviationAsWordInName/Example1/`

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example1/config.xml

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8f9f818_2024063214/reports/diff/index.html

Acttion: https://github.com/checkstyle/checkstyle/actions/runs/9344991208/job/25717060826

Time: **36 mins 36 secs**

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9345506290/job/25718479490

**Comment by relentless-pursuit** [comment]
For SummaryJavadoc/Example1/

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example1/config.xml

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8f9f818_2024063214/reports/diff/index.html

Acttion: https://github.com/checkstyle/checkstyle/actions/runs/9345506290/job/25718479490

Time: 45 mins

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/9346195897/job/25720545785

**Comment by relentless-pursuit** [comment]
For SummaryJavadoc/Example2/

Config file: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example2/config.xml

Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8f9f818_2024082623/reports/diff/index.html

Acttion: https://github.com/checkstyle/checkstyle/actions/runs/9346195897/job/25720545785

Time: **44 mins 39 secs**

**Comment by romani** [comment]
Please do PR
`relentless-pursuit wants to merge 1 commit into checkstyle:master from relentless-pursuit:all-ci-disabled`

Without any extra commit with extra spaces

**Comment by relentless-pursuit** [comment]
> Please do PR `relentless-pursuit wants to merge 1 commit into checkstyle:master from relentless-pursuit:all-ci-disabled`
> 
> Without any extra commit with extra spaces

@Romani, i didn't understand the above review. Since, you had made changes to the branch, i fetched those changes into my PR and rebased and pushed back.

**Comment by romani** [comment]
Please follow instructions at https://github.com/checkstyle/test-configs/issues/16 on how to create PR.

**Comment by romani** [comment]
I am closing this, as there correct PR

**Pull request closed without merging**
