### PR TITLE
 Issue #15475: Re-enable no-error-pmd validation

### LINKED ISSUE #15475: Re-enable no-error-pmd build
We dropped the no-error-pmd build because there were failures due to https://github.com/checkstyle/checkstyle/pull/15376.
We should re enable this build when PMD merge the PR that uses the new property to fix the violations. The PR can't be merged until checkstyle new release.
PMD PR: https://github.com/pmd/build-tools/pull/33

build failure URL: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/27241/workflows/ae4881cd-8f64-4245-a7c0-619e023f8e5e/jobs/662368

```
There are 8 errors reported by Checkstyle 10.18.0-SNAPSHOT with /net/sourceforge/pmd/pmd-checkstyle-config.xml ruleset.
[ERROR] src/main/java/net/sourceforge/pmd/lang/java/ast/ConstantFolder.java:[24,7] (modifier) RedundantModifier: Redundant 'strictfp' modifier.
[ERROR] src/main/java/net/sourceforge/pmd/lang/java/ast/ConstantFolder.java:[141,12] (modifier) RedundantModifier: Redundant 'strictfp' modifier.
...
```

### PR DESCRIPTION
**Pull request by mahfouz72**
closes #15475

### CODE REVIEW

**Comment by mahfouz72** [comment]
no-error-pmd test is passed. Other failures are unrelated

**Comment by rnveach** [comment]
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/27642/workflows/ff9b2d3f-dd23-4155-b922-3535fe6dc721/jobs/678799

**Review by rnveach — APPROVED** [review]

**Comment by romani** [comment]
Rebased, to let CI mostly pass

**Review by romani — APPROVED** [review]
Ok to merge

**Review by nrmancuso — APPROVED** [review]

**Pull request merged**
