### PR TITLE
Issue #2067: Fix false-negatives in EmptyLineSeparatorCheck

### PR DESCRIPTION
**Pull request by Vladlis**
Report against CS, Sevntu-CS, Guava, pmd, Orekit:
http://vladlis.github.io/reports/emptyLine/

The report looks OK, I've confirmed about a half of violations

### CODE REVIEW

**Comment by Vladlis** [comment]
Build is OK, please review.

**Comment by romani** [comment]
report is ok , I tested from the bottom about a half.

please send PR to fix - http://vladlis.github.io/reports/emptyLine/#Test.1.36

**Comment by Vladlis** [comment]
> There is some inconsistency in names "check..... , process......" please change method to return boolean and do "log" in visitToken.

Fixed

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
