### PR TITLE
Update AbstractChecks to log DetailAST - WriteTag #7767

### PR DESCRIPTION
**Pull request by yajna-pandith**
Issue #7767: Update AbstractChecks to log DetailAST - WriteTag

### CODE REVIEW

**Comment by strkkk** [comment]
@yajna-pandith 
Please see https://github.com/checkstyle/checkstyle/wiki/PR-rules
Please correct your PR to pass CI, and also generate regression report

**Comment by rdiachenko** [comment]
@yajna-pandith any update on this PR?

**Comment by yajna-pandith** [comment]
I am trying to generate the diff report. Mvn clean verify works just fine
now.

**Comment by rnveach** [comment]
> Mvn clean verify works just fine

CI is telling us otherwise. Please make sure you have everything pushed to the server. Squash all commits to 1 and make sure you are rebased on the latest master.

**Comment by yajna-pandith** [comment]
With respect to the point number 8 in checkstyle PR rules which states " If you made changes requested by reviewer, push them to the branch and PR and CI will automatically update."  Which branch should i be pushing. Currently i have forked checkstyle/checkstyle to yajna-pandith/checkstyle . Now I have comitted and pushed the changed code to my fork at yajna-pandith/checkstyle. I am not clear on which branch to push as per rule number 8 of PR rules. Can you please help/clarify.

**Comment by rnveach** [comment]
> Which branch should i be pushing.

The branch you used to create this PR, is what I would be saying, but it says `unknown repository` at the top and there is no mention of a branch or fork in this PR like there usually is, so I can only assume the branch/fork were removed.

> Currently i have forked checkstyle/checkstyle to yajna-pandith/checkstyle . Now I have comitted and pushed the changed code to my fork at yajna-pandith/checkstyle. 

Your for is https://github.com/yajna-pandith/checkstyle.
These are the list of branches in your repo. https://github.com/yajna-pandith/checkstyle/branches/all

I don't see any branch with your name on it. If you look at my fork at https://github.com/rnveach/checkstyle/branches/all , you will see a bunch of branches that say `Updated XXX ago by rnveach` which is what I would expect in your fork.

To start a PR, you have to have pushed your changes to some type of branch on the server in your fork. You can't have your changes not connected to a branch in git, as far as I am aware. The main checkstyle code is stored in the `master` branch. That is where things get merged to and what everyone bases their changes off of.

What commands did you use to push your changes in the first place?

**Comment by yajna-pandith** [comment]
I had done a few mistakes in the previous commit. I rectified the same and tried committing to this PR but accidentally I created another PR " [https://github.com/checkstyle/checkstyle/pull/7850]". This PR has passed all the 16 tests.

**Comment by rnveach** [comment]
Then close this PR since it is now a duplicate and you can't repush to it.

Don't delete your branch/fork until it is merged in.

**Pull request closed without merging**
