### PR TITLE
Need Braces Check, one-line statements option, issue #300

### PR DESCRIPTION
**Pull request by alexkravin**
According to reopened issue #300 

Fixed false-positives with one-line statements, extended option by supporting loops besides if statement.

### CODE REVIEW

**Comment by romani** [comment]
1) please put all changes from javadoc to xdoc.

2) you did processing only for default tokens
But what about rest of tokens ?  see getAcceptableTokens.
All of them have to be supported or special comment should be in javadoc/xdoc.

**Comment by romani** [comment]
3) 
> allowSingleLineStatement&quot; value=&quot;true&quot;/

default value is FALSE, we have to be strict by default.

**Comment by alexkravin** [comment]
1) Added code examples to xdoc

2) put a comment before method call which specifies only loops and if statements would be analyzed. Added this restriction to option's description in javadoc/xdoc

3) It's false by default, there is only example in xdoc which shows how to configure the Check to use this option:

```
To configure the check to allow one line statements
          (<code>if, while, do-while, for</code>) without braces:
         </p>
         <source>
 &lt;module name=&quot;NeedBraces&quot;&gt;
    &lt;property name=&quot;allowSingleLineStatement&quot; value=&quot;true&quot;/&gt;
 &lt;/module&gt;
         </source>
```

**Comment by romani** [comment]
Why it is not possible to add support to other tokens and we need to put restrictions to javadoc?

**Comment by alexkravin** [comment]
Please be more concrete, which other tokens has to be supported by single-line statements option?
As right now I see no reason to support CASE, DEFAULT and LAMBDA

**Comment by romani** [comment]
> As right now I see no reason to support CASE, DEFAULT and LAMBDA

I asking you one more time - What is a reason ? I need detailed explanation.

**Comment by alexkravin** [comment]
I think it's not necessary because user has to specify these tokens explicitly and writing something like:

```
case: dosomeStuff(); break;
```

is not good approach of writing and then reading, furthermore, if user specified such a token - he expects these statements framed by curly braces.

So, to be sure about this need the best way will be in accepting these changes and asking community about necessity of extending.

**Comment by romani** [comment]
1) 
> I think it's not necessary because user has to specify these tokens explicitly

And he will expect Check to work properly for new target token

2)
> is not good approach of writing and then reading

```if (herp.isValid()) return herp;```

This approach is also the worst that developer can do, as in debug it will not be clear condition was TRUE or FALSE. But it is up to a user to decide what is good and what is bad style.

in case of CASE it is absolutely the same : 
```
case 1: dosomeStuff(); break;
case 2: dosomeStuff(); break;
...
case 10: dosomeStuff(); break;
default  : dosomeStuff(); break;
```

3)
What about Lambda ?

4) 
> asking community about necessity of extending.

community already asked us

**Comment by alexkravin** [comment]
Yes, you are right, I have reread the issue, firstly I thought there was only case of loops.

So I have added support of all kinds of tokens which Check already supports.

**Comment by romani** [comment]
1) please create separate Input file for LAMBDA testing for this Check, Inputs should not be shared. Input belong to certain UT and as result to exact Check. Eventually we will enforce "//warn" trailing comments to make Input be more easy to read.

2) All other is fine, I am ready to do merge , please generate HTML reports over all (uncomment all lines) projects that are referenced at checkstyle-tester - https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties
```
git clone https://github.com/checkstyle/contribution.git
cd checkstyle-tester
activate your Check in my_check.xml
./launch.sh -Dcheckstyle.config.location=my_checks.xml
see result HTML report at target/site/index.html
```
no need to put online , just confirm that there are no Exceptions, and reports are different for some cases as expected.

**Comment by alexkravin** [comment]
1) Created separate input

2) Generated report.
Found and fixed one NPE and added support of unnoticed case with for loop:
```
for (...);
```

All other looks good and new options is supported well.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
