### PR TITLE
WIP: Update nondex - do not merge

### PR DESCRIPTION
**Pull request by romani**
it was green at https://travis-ci.org/github/checkstyle/checkstyle/jobs/675825399#L499
but failed inside

### CODE REVIEW

**Comment by rnveach** [comment]
If maven command does not fail, then it is not reproducing the same issue we saw.

**Comment by romani** [comment]
CI is failing in nondex, very sad.
So it was very unfortunate failure of Travis to fail build when script internal return non zero exit code. Nothing we can do, scary a bit.

I will try to make only one commit, the same as we did originally

**Comment by rnveach** [comment]
> Nothing we can do

I am not sure what you are referring to we can't do. Are you referring to travis being green before when we got a maven failure but execution continued and didn't fail?

**Comment by romani** [comment]
I meant that it is instability of Travis.

I removed by update to skip CIs, so now we have same update as originally, I hope problem will be reproduced.

**Comment by rnveach** [comment]
You won't reproduce the issue we saw in PR until you remove running the non-dex maven command to simiulate a maven failure. File generated by non-dex won't exist and execution will try to work with the non-existent file.

**Comment by romani** [comment]
ok, such line with grep was added at https://github.com/checkstyle/checkstyle/commit/6f2b7bdce7cbc8c78327a2c569fa0f5817a4bd69 , so root reason it `--fail-never` and `grep` on non-existing folder with ignoring of all.

@rnveach , can we remove `--fail-never` now ? looks like back in time we had problem with printing of actual error. if not ... we should update bash logic to be more smart.

**Comment by romani** [comment]
Travis is failing https://travis-ci.org/github/checkstyle/checkstyle/jobs/676588703#L3426 , do you know why it could happen that folder '.nondex' is not created ?

**Comment by rnveach** [comment]
> can we remove --fail-never now ? 

No. We do print out of failure in nondex files to help us debug the situation. As you can see from travis, it does an extra print out of the end when nondex fails. This is similar to pitest and its failure.

> we should update bash logic to be more smart.

This.

> Travis is failing https://travis-ci.org/github/checkstyle/checkstyle/jobs/676588703#L3426 , do you know why it could happen that folder '.nondex' is not created ?

This failure doesn't show any `.nondex` folders not being created. Original PR failure at https://travis-ci.org/github/checkstyle/checkstyle/jobs/675825399#L532 had a folder failure because `nondex` didn't even run since maven failure was with downloading dependencies. https://travis-ci.org/github/checkstyle/checkstyle/jobs/675825399#L504

**Comment by romani** [comment]
thanks a lot, not I got a root reason, it will addressed at https://github.com/checkstyle/checkstyle/issues/8133

**Pull request closed without merging**
