### PR TITLE
Issue #2451: removed excess hierarchy from IllegalThrowsCheck

### PR DESCRIPTION
**Pull request by rnveach**
IllegalThrowsCheck now extends Check.
Removed AbstractIllegalCheck as it isn't used anymore.

### CODE REVIEW

**Comment by romani** [comment]
please keep AbstractIllegalCheck, and put a deprecated on it in separate commit. We will keep it for 6 releases, most likely other people with custom Checks also use it.

**Comment by rnveach** [comment]
@romani 
Is it ok to hide this class from code coverage?
Since it's not used anywhere, it will have 0% coverage.

**Comment by romani** [comment]
yes, it is reasonable, do this by separate commit.

**Comment by rnveach** [comment]
TC keeps looping me on errors.
It first says "Abstract class AbstractIllegalCheck has no concrete subclass".
So I add suppression "noinspection AbstractClassNeverImplemented" to javadoc.
Then it complains "Redundant suppression" and the only thing I added was that "noinspection".

**Comment by romani** [comment]
Tc is passed https://github.com/checkstyle/checkstyle/pull/2509

**Comment by rnveach** [comment]
@romani thanks, it passed now.
My issue was I didn't have the noinspection tag last in the javadoc.
I also had to add a suppression for the CS error "Unknown tag 'noinspection'".

**Comment by romani** [comment]
instead of suppression by line, lets use http://checkstyle.sourceforge.net/config_javadoc.html#JavadocType option "allowUnknownTags" and put a comment above this option , that it is required to skip violation of custom IntelijIdea javadoc-tag ```@noinspection``` .

**Comment by rnveach** [comment]
@romani You realize updating the checkstyle_checks.xml requires to update all the xdocs and their line locations? This violation will only be here for the time these deprecated classes are kept, afterwards we won't have these type of errors.
You sure you want to continue with adding "allowUnknownTags" tag?

**Comment by romani** [comment]
keep suppression by Line number is also bad, any changes in code and user get a violation he will hardly understand a reason.

What if we remove config at https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L110-L112 with keeping lines as blank, and move config to the end of TreeWalker's checks. In this case we need to update only few modules https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L380-L409 .

Does it make sense ?

**Comment by romani** [comment]
@rnveach , it would be awesome if you update your Xdoc validator to control line numbers in URLs of "Example of usage".

**Comment by romani** [comment]
Lets finish this PR and do other issues with xdoc validation and configs changes separately

**Comment by rnveach** [comment]
@romani Done and passed.

**Comment by romani** [comment]
please rebase this PR.

**Comment by rnveach** [comment]
@romani Done.
Since we aren't using line numbers anymore, I moved the javadoctype check back to its original position.

**Comment by romani** [comment]
merged as FF.

**Pull request closed without merging**
