### PR TITLE
updated AbstractClassName

### PR DESCRIPTION
**Pull request by amritk07**
updated AbstractClassName

### CODE REVIEW

**Comment by rnveach** [comment]
@amritk07 Please look over https://github.com/checkstyle/checkstyle/wiki/PR-rules .
Specifically item 1, 3, and 4.

**Comment by rnveach** [comment]
@amritk07 ping

**Comment by rnveach** [comment]
@amritk07 ping

**Comment by strkkk** [comment]
Closed as abandoned

**Pull request closed without merging**
