### PR TITLE
Issue #7698: add code examples for RegexpSinglelineJava

### PR DESCRIPTION
**Pull request by wilcoln**
# Fix for issue #7698
examples

**Ouput of default example:**
```
$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
	<module name="RegexpSinglelineJava"/>
   </module>
</module>
                                                                                                          
$ cat Test.java 
public class Test {

	public void main(){
		System.out.println(""); // OK
		System.out.
			println(""); // OK		
		/* System.out.println */ // OK
	}
}

$ java -jar checkstyle-8.29-all.jar -c config.xml Test.java
Starting audit...
Audit done.
```
**Ouput of non-default example:**
```
$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
           <module name="RegexpSinglelineJava">
		<property name="format" value="System\.out\.println"/>
		<property name="ignoreComments" value="true"/>
	  </module>
    </module>
</module>

$ cat Test.java 
public class Test {

	public void main(){
		System.out.println(""); // violation, the illegal pattern is matched on a single line
		System.out.
			println(""); // OK		
		/* System.out.println */ // OK, comments are ignored
	}
}

$ java -jar checkstyle-8.29-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /var/tmp/Test.java:4: Line matches the illegal pattern 'System\.out\.println'. [RegexpSinglelineJava]
Audit done.
Checkstyle ends with 1 errors.
```

### CODE REVIEW

**Comment by wilcoln** [comment]
Hi,
May I have some feedback on the failing check please?

**Comment by rnveach** [comment]
https://travis-ci.org/checkstyle/checkstyle/jobs/656604888#L287
> Please put a reference to an Issue in the PR description,
this will bind the Issue to your PR in Github

See also https://github.com/checkstyle/checkstyle/wiki/PR-rules . Specifically item 1.

**Comment by romani** [comment]
No need to close PR, you can fix your branch on your local and push with force flag to remote (GitHub).

**Comment by wilcoln** [comment]
> No need to close PR, you can fix your branch on your local and push with force flag to remote (GitHub).

Got it, won't happen anymore

**Pull request closed without merging**
