### PR TITLE
Issue #6055: fix Travis CI build on OSX

### PR DESCRIPTION
**Pull request by pbludov**
Issue #6055

### CODE REVIEW

**Comment by pbludov** [comment]
xcode 9.4 is bundled with jdk version "10.0.1" 2018-04-17
xcode 9.3 and older are bundled with jdk 8

jdk 9 is not available on OSX platform.

**Comment by rnveach** [comment]
@romani MacOS is passing, but spell checker is failing horribly.

**Comment by romani** [comment]
Spell checker problem is the same as #6046 , file name is changed.

**Comment by pbludov** [comment]
The spell checker was broken in ba211e3fdfaa5cd63296994285f839a5d8391526
The URL is no more valid:
```
<p>The requested URL /linux/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/w/words-3.0-29.fc29.noarch.rpm was not found on this server.</p>

```

**Comment by romani** [comment]
I just merged workaround, but we need to update shell script to get name of from web page

**Comment by pbludov** [comment]
I vote for CentOS distro:
http://mirror.centos.org/centos/7/os/x86_64/Packages/words-3.0-22.el7.noarch.rpm

**Comment by pbludov** [comment]
Now it is
```
Review results
New misspellings found, please review:
xcode

If you are ok with the output of this run, you will need to
patch .ci/jsoref-spellchecker/whitelist.words <<EOF
@@ -1336,2 +1336,3 @@
 xargs
+xcode
 xcommons
EOF
```

My bad. The 'xcode' word wasn't used before this PR.
@romani please apply this patch.

**Comment by romani** [comment]
>I vote for CentOS distro

Let's try

**Pull request merged**
