### PR TITLE
Issue #11214: Specified violation message in OperatorWrapCheck

### PR DESCRIPTION
**Pull request by AmrDeveloper**
Issue #11214: Specified violation message in OperatorWrapCheck

### CODE REVIEW

**Comment by romani** [comment]
Please resolve conflict

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by AmrDeveloper** [comment]
> Please resolve conflict

Done

**Comment by romani** [comment]
pitest coding failure
`+EqualsAvoidNullCheck.java.html:<td class='covered'><pre><span  class='survived'>            if (field.findFirstToken(TokenTypes.IDENT) != null) {</span></pre></td></tr>`

**Review by nick-mancuso — APPROVED** [review]

**Pull request merged**
