### PR TITLE
Issue#2767

### PR DESCRIPTION
**Pull request by liscju**

### CODE REVIEW

**Comment by romani** [comment]
@liscju ,

awesome !

please enforce preferred size for "Type" column as 35 symbols (we have now 28 as max + 7 a cushion value for future ).

~/java/git-others/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api $ grep "public static final int" TokenTypes.java | sed -E 's/.* public static final int //' | sed -E 's/ =.*//' | wc -L
28

**Comment by liscju** [comment]
@romani 
1) 
```
please enforce preferred size for "Type" column as 28 symbols
 (we have now 28 as max and user can still change width of column ).
```
DONE

2) Problem with teambuild is with line:
```java
final int preferredTreeColumnWidth = (int) (getPreferredSize().getWidth() * 0.6);
```
and the problem is:
```
Cast to int from 'double' may result in loss of precision
```
Technically the rounding to int is what i want, i could use Math.round but that still would needed cast. It is because declaration of Math.round looks like:
```java
static long round(double a);
static int	round(float a);
```

getPreferredSize().getWidth() returns double so Math.round returns long which i would have to cast later to int( with possibility of loosing precision). I can use round(float) if only i would cast getPreferredSize().getWidth() from double to float - which is reduce precision cast. What should i do?

**Comment by romani** [comment]
> What should i do?

Please try http://stackoverflow.com/a/20773974/1015848 . Any other workaround to cheat IntelijIdea is ok. If now way to do workaround - we should suppress this violation by annotation `@noinspection`

**Comment by liscju** [comment]
@romani changed according to SO suggestion

**Comment by liscju** [comment]
Now error is from PMD: 
```
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.JTreeTable:141 Rule:UnnecessaryWrapperObjectCreation Priority:3 Unnecessary wrapper object creation.
```

**Comment by liscju** [comment]
I used @SuppressWarnings("NumericCastThatLosesPrecision") on method to overcome this issue, now everything should be fine

**Comment by liscju** [comment]
Now is failing with 
```
Inspection suppression annotation @SuppressWarnings("NumericCastThatLosesPrecision")
```

**Comment by romani** [comment]
Vicious circle .... of SATs violations.

lets come back to original , we should satifly IntelijIdea  by `static int  round(float a);` so lets enforce float type to be result of multiplication, make it 
`final int preferredTreeColumnWidth = Math.round(getPreferredSize().getWidth() * 0.6f);`

some links:
https://docs.oracle.com/javase/7/docs/api/java/lang/Math.html#round%28float%29
http://stackoverflow.com/a/14102962/1015848

**Comment by liscju** [comment]
@romani 
```java
final int preferredTreeColumnWidth = Math.round(getPreferredSize().getWidth() * 0.6f);
```
Unfortunately i can't do this because multiplying double by float gives double , which Math.round converts to long and make another losing precision casting. Now im trying with Ints.checkedCast from guava which casts long to int.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
