### PR TITLE
Issue #11140: resolve WOC_WRITE_ONLY_COLLECTION_FIELD

### PR DESCRIPTION
**Pull request by rnveach**
Issue #11140

No violations locally.

### CODE REVIEW

**Comment by rnveach** [comment]
semaphore:
````
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.metrics.AbstractClassCouplingCheck creates and initializes a collection but never reads or gains information from it [com.puppycrawl.tools.checkstyle.checks.metrics.AbstractClassCouplingCheck] In AbstractClassCouplingCheck.java WOC_WRITE_ONLY_COLLECTION_FIELD 05:56
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.metrics.AbstractClassCouplingCheck creates and initializes a collection but never reads or gains information from it [com.puppycrawl.tools.checkstyle.checks.metrics.AbstractClassCouplingCheck] In AbstractClassCouplingCheck.java WOC_WRITE_ONLY_COLLECTION_FIELD 05:56
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.metrics.AbstractClassCouplingCheck creates and initializes a collection but never reads or gains information from it [com.puppycrawl.tools.checkstyle.checks.metrics.AbstractClassCouplingCheck] In AbstractClassCouplingCheck.java WOC_WRITE_ONLY_COLLECTION_FIELD 05:56
[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.metrics.AbstractClassCouplingCheck creates and initializes a collection but never reads or gains information from it [com.puppycrawl.tools.checkstyle.checks.metrics.AbstractClassCouplingCheck] In AbstractClassCouplingCheck.java WOC_WRITE_ONLY_COLLECTION_FIELD
````

**Comment by rnveach** [comment]
@pbludov Failure does not show which field/variable or line number.

**Comment by pbludov** [comment]
This may be related https://github.com/mebigfatguy/fb-contrib/issues/408
Let's blacklist this detector as it is broken.

**Comment by rnveach** [comment]
Done.

**Review by pbludov — APPROVED** [review]

**Comment by romani** [comment]
Please put comment "until https://github.com/mebigfatguy/fb-contrib/issues/408 " to let us activate it later on, eventually

**Review by romani — APPROVED** [review]
Ok to merge with comment above

**Comment by rnveach** [comment]
Done.

**Pull request merged**
