### PR TITLE
Issue #2415: IllegalTypeCheck ignores tokens configuration parameter

### PR DESCRIPTION
**Pull request by lennartj**
Created patch.
Created unit test case.
Built to verify that it works.

### CODE REVIEW

**Comment by romani** [comment]
thanks for PR, but:

1) Please squash all commits in one.

2) Please provide details why you want to remove "final" on class and make final setters. In general I am ok, but for Checkstyle exposing itself too much to the world, I need to know details before making changes like this.

**Comment by lennartj** [comment]
Hello there.

Some answers here:

> 1) Please squash all commits in one, or keep changes to "final" in separate commit.

Ok. Can do.

> 2) Please provide details why you want to remove "final" on class and make final setters. In general I am ok, but for Checkstyle exposing itself too much to the world, I need to know details before making changes like this.

I believe it should be the other way around. The only reason that the ```IllegalTypeCheck``` was declared final - it seems - is that it calls its own setter methods from the constructor (hence requiring the class to be final not to break the ITs). Few or no other Checks need to be declared final, within the Checkstyle Codebase - and a non-final class supports subclassing to create a custom ```IllegalTypeCheck``` with different default values. This - in turn - can assist readability and usability for many projects (for example: ```JpaShouldUseJdk8DateTimeClassesInPublicAPIs``` as a check class basically says exactly what the problem is, rather than the more generic ```IllegalTypeCheck``` which would need comments in the configuration to let the developers know what was intended).

But turn the question around: Why should any of the checks be declared final?

> 3) please remove changes to .gitignore , I do not expect such changes, some of them I even do not understand.

Your current .gitignore lacks quite a lot of stuff. I would advice using the provided .gitignore - its statements are mostly generated from the really good [https://www.gitignore.io] site.

> 4) please update getRequiredTokens to have "TokenTypes.IMPORT" in other case Check will raise false-positives on classes that are matching by simple name.

I thought this would be intentional by design; in my custom and bug-fixed version of the ```IllegalTypeCheck``` class, I add classes both with fully qualified package names and simple class names. This is - if I understand things correctly - how the ```IllegalTypeCheck``` worked before the patch. 

On a more practical note - we need a unit test which fails if we use SimpleName-classes. As the code is committed now, all tests pass - yet you say there is something (potentially serious) that we do not test for. 

However, I am not familiar enough with the CheckStyle codebase to create that unit test.

**Comment by romani** [comment]
> Your current .gitignore lacks quite a lot of stuff. 

please create a separate PR for this, we will discuss it separately, I disagree on most of new stuff in your version of this file.

> in my custom and bug-fixed version of the IllegalTypeCheck class, I add classes both with fully qualified package names and simple class names. 

Very interesting, ... Lets go in details of bug-fix and examples of configuration.

> On a more practical note - we need a unit test which fails if we use SimpleName-classes

please create issue on this, to not forget to do this.

> But turn the question around: Why should any of the checks be declared final?

Both ways(final class and final methods) a valid , but have small difference.
Having final on a Class was old intention to not let user extend a class and force them to composite our implementation.
Extending from our classes will brake their implementation if we decide to do re-factoring. We do not want to make custom Checks to be one another braking compatibility point.
Right now we almost eliminated "protected" methods/members  from Checks, and public are only setters, but any changes in names for setter is braking compatibility already, so moving final from class to methods/members is more reasonable now.  One day we will do this (as separate issue/pr).
Feel free to open issue on this. 
Please remove your changes for "final" as it should be done separately.

> However, I am not familiar enough with the CheckStyle codebase to create that unit test. 

I could guide you, coding Checkstyle is so easy.
Test: https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
Test case: https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java#L134
Input file that is used in test case: https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java#L144
Input file: https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputIllegalTypeSameFileName.java
you can create your own input file and update existing.

**Comment by romani** [comment]
@lennartj 

release 6.12 is planned to be at 31 of October.
it would very good to finish this PR before release. Do you have time to finish PR ?

**Comment by lennartj** [comment]
> Both ways(final class and final methods) a valid , but have small difference.
> Having final on a Class was old intention to not let user extend a class and force them to composite our implementation. Extending from our classes will brake their implementation if we decide to do re-factoring. We do not want to make custom Checks to be one another braking compatibility point.

If you really want to go down that route, the design should be changed quite a lot from today's implementation. A 'final'-declared check implementation prevents users implement their custom checks by extending - so they have to implement a custom check (potentially to fix bugs in check style) by copy-and-pasting the source code from an existing check, including copying the messages resource bundle to the appropriate package. This is clunky and will also lead to compatibility breakage if the checkstyle code is refactored.

If this route is really preferred, you need to move most of the implementation to abstract superclasses which can be extended by users to achieve custom checks - and only permit a 'final' implementation class within the checkstyle codebase if it contains only a constructor (and nothing else).

> One day we will do this (as separate issue/pr). Feel free to open issue on this. Please remove your changes for "final" as it should be done separately.

Then the only remaining part of this PR is the snippet below, and the new method in the test case including the demonstration class. Seems like a trivial PR, perhaps better if you do what you want to do since you seem to disagree with what I have done in most other aspects.

```
  @Override
     public int[] getRequiredTokens() {
-        return getAcceptableTokens();
+        return ArrayUtils.EMPTY_INT_ARRAY;
     }```

**Comment by romani** [comment]
> and by the way, it should be an empty array. No reason to force the IMPORT token to be required.

please explain this. Why we should allow user to be less precise in marking invalid types ?

**Comment by romani** [comment]
@lennartj , do you want to continue this PR ?

For now I see only one solution is too make getRequired() to return only Tokens.IMPORT .

**Comment by romani** [comment]
Looks like our discussion is not going to finish in recent day, too much issues we try to discuss/change in the same time. I am closing the PR.

I created PR #2496 , to fix issue as I think it should be done.

Discussion could be continued if smth is left.

**Pull request closed without merging**
