### PR TITLE
Issue #11596: Update Checkstyle's Copyright

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
Updated #11596 

Shell Command:
`$ grep -rl '// checkstyle: Checks Java source code for adherence to a set of rules.' C:/Users/ASUS/Desktop/OpenSource/checkstyle/ | xargs sed -i 's_// checkstyle: Checks Java source code for adherence to a set of rules._// checkstyle: Checks Java source code and other text files for adherence to a set of rules._g'`

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
GitHub, rebase

**Review by rnveach — APPROVED** [review]
Header file changes look good.

**Comment by rnveach** [comment]
@romani I am sort of surprised CI did not fail for atleast sevntu which uses this header, but I believe this is because we do a no validation and regression tests only.

**Comment by romani** [comment]
Please add more `///` on top and bottom to make as before that text in length less than series of `///////`

**Comment by Rahulkhinchi03** [comment]
The current size of `//` is 81 and the line size is 93.
So I am making `//` to 100

Shell Command Used:
`grep -rl '////////////////////////////////////////////////////////////////////////////////' C:/Users/ASUS/Desktop/OpenSource/checkstyle/ | xargs sed -i 's_////////////////////////////////////////////////////////////////////////////////_///////////////////////////////////////////////////////////////////////////////////////////////////_g'`

**Review by romani — CHANGES_REQUESTED** [review]
Ok to merge

**Review by romani — APPROVED** [review]

**Comment by rnveach** [comment]
@romani @pbludov @nick-mancuso As a reminder for admins for when this is merged, any existing PRs with brand new files will need to be rebased. Existing CI runs may not show an error for the out of date copyright until that rebase.

**Review by pbludov — APPROVED** [review]

**Pull request merged**
