### PR TITLE
Issue #3735: added lambdas to NeedBraces for checkstyle config

### PR DESCRIPTION
**Pull request by rnveach**
Issue #3735

Are we sure we are ok with `allowSingleLineStatement`? This means no braces when it is a single line. We still require braces for if statements even if it is small.

### CODE REVIEW

**Comment by romani** [comment]
> Are we sure we are ok with allowSingleLineStatement? This means no braces when it is a single line. We still require braces for if statements even if it is small

we do experiments , I enforce a style when I know bad cases. I might not see them :) , please point.

**Comment by romani** [comment]
Another reason could be that all functionality should be applied to our codebase, so it was for extra testing.

**Comment by rnveach** [comment]
@romani Turning `allowSingleLineStatement` to `false` produces 30 violations in CS.
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L233
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java#L226
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheck.java#L126-L127

**Comment by romani** [comment]
to my mind it is ok to keep `allowSingleLineStatement=true` it is easy to read, but
another point is how to place breakpoint in debug mode easily ? (braces for blocks are used mostly for this reason)

@rnveach , what is your experience with single line LAMBDA ? is it convenient to debug (extra step-in are required) ?

**Comment by rnveach** [comment]
@romani I still write code in Java 6 grammar. I don't specifically write anything 7+ except when forced by CI in this project and I haven't really needed to debug lambdas yet.
I can see how it would make debugging easier as stepping in wouldn't take you to the lambda but the method that takes the lambda as an argument like `filter`.

**Comment by romani** [comment]
ok, while we do not have strick position, lets keep this option unchanged. Live will show us what is convenient.

**Pull request merged**
