### PR TITLE
Issue #13109: Kill mutation for IllegalTypeCheck

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13109: Kill mutation for IllegalTypeCheck

--------

# check
https://checkstyle.org/config_coding.html#IllegalType

------

# Mutation 
https://github.com/checkstyle/checkstyle/blob/eaed451ba71f543d7a98675d521ca8bb428f79d5/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L75-L91

----

# Explaination
Test added :)

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
@Kevin222004 , please consider to make single PR to fix all NonVoidMethodCallMutator at visitToken in all Checks. It will be simple win, and we already know how to do this by template.

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

**Comment by rdiachenko** [comment]
@Kevin222004 please resolve a conflict

**Comment by Kevin222004** [comment]
@rdiachenko  done

**Review by rdiachenko — APPROVED** [review]
lgtm

**Pull request merged**
