### PR TITLE
Issue #2638: Print parse tree from CLI to terminal

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by romani** [comment]
1)
> Main.main("-c", "/google_checks.xml", getPath("checks/metrics"), "-t");

please update code to skip "-c" argument , it is useless when user use "-t"

2)
> ` <code>-t</code> - print AST of the checked file.`

please explain that all other option will be ignored. Or we need to throw error is conflicting options are used "-c ... -p ...." vs "-t".

3)
>
```
            else if (cmdLine.hasOption(OPTION_T_NAME)
                && files.size() > 1) {
```

Could it be on single line ?

4)
> 
```
        String indentation = "";
        while (node.getParent() != null) {
```

Why not a StringBuilder to keep `indentation`?

**Comment by Vladlis** [comment]
@romani
1) 2) OK, I thought these options should have been used together

3) Sure

4) Cause I need put literal in front in these places:

``` indentation = "    " + indentation;```
```indentation = "|    " + indentation; ```

**Comment by Vladlis** [comment]
Can I suppress these violations?
https://travis-ci.org/checkstyle/checkstyle/jobs/105728828#L3187-L3188

**Comment by romani** [comment]
>  Anonymous inner class length is 33 lines (max allowed is 20).

need to be fixed. Move String concatenation to test method.

**Comment by Vladlis** [comment]
1) Done
2) Done
3) Such a condition is not needed anymore
4) Replaced with StringBuilder
5) Done
6) Done
7) Done

**Comment by romani** [comment]
please rebase your commit on latest code . CircleCI is still compiling 6.15-SNAPSHOT but we are already 6.16-SNAPSHOT

**Comment by Vladlis** [comment]
Build is fixed.

**Comment by romani** [comment]
1)
>  Class for printing AST to console.

to String.

2)
> stringTree.substring(0, stringTree.length() - 1);

please explain this in comment. Substring on such a big String will create a new String in memory.

3)
> result.add("Option '-p' cannot be used with either '-c' or '-p'.");

Option '-t'

4)
> + " -t         Print AST of the checked file%n"

Users are not aware of term AST, so put "Abstract Syntax Tree(AST)" instead. 

5)
> `-c &lt;configurationFile&gt; [-t] \ `

please add "-v" there too. And put "-v" and "-t" on separate line.

6)
> The option  cannot be used with either '-c' or '-p'.

Option "-f" is missed. It might be easy to say that all other options are not allowed to be used. Onle one file should be specified. Folder is not ok too.

**Comment by Vladlis** [comment]
1) Fixed
2) Not needed anymore
3) Fixed
4) Done
5) Done
6) Done
7) Only '\n' is used now

**Comment by romani** [comment]
please remove update from appveyour config.

**Comment by romani** [comment]
merged as FF

**Pull request merged**
