### PR TITLE
Issue #3976: Split and Organize Checkstyle inputs by Test for EmptyForIteratorPad

### LINKED ISSUE #3976: Split and Organize Checkstyle inputs by Test for EmptyForIteratorPad
subtask of #3891 .

do a copy of all test input files to separate folder for EmptyForIteratorPad .
Not any other Check should use new inputs.

### PR DESCRIPTION
**Pull request by shivanshsoni**
fixes #3976

### CODE REVIEW

**Comment by shivanshsoni** [comment]
@romani  and @rnveach   Please tell me if there is any other need of changes?
if not then i am going to squash all commits

**Comment by shivanshsoni** [comment]
and why i am failing CI

**Comment by shivanshsoni** [comment]
I made every possible changes required to solve this issue then why i am failing?

**Comment by shivanshsoni** [comment]
@rnveach I dont know why everytime these checks are failing.
Please suggest some changes

**Comment by rnveach** [comment]
@shivanshsoni Squash all commits to 1 and keep at 1.
Then I suggest you look over CI and read why it is failing. You can also run `mvn clean verify` locally to see failing areas.

https://travis-ci.org/checkstyle/checkstyle/jobs/211230812#L867-L869
Your input files can't be found. It seems you moved them to `src/test/java` when they are suppose to be in `src/test/resources` like CI log says.

**Pull request closed without merging**
