### PR TITLE
Issue #286

### PR DESCRIPTION
**Pull request by liscju**
Introduce new parameter in ModifiedControlVariable check ignoreForControlVariablesNotIterated to ignore changes in variable inside for loop which are not change in iterator part of for loop. To do it before adding all variables declared in for first part to current variable stack, we calculate all variables which are changed in iterator part of for loop. The cases in this iterator part which can change defined variables are: 
postincrement,preincrement,postdecrement,predecrement with IDENT operator in it(simple variable name),
assignment with IDENT as first child(assignment to simple variable name). We only add variable to variable stack when it is not changed in for iterator part or ignoreForControlVariablesNotIterated is false. When we are leaving for part we pop it according to how many variables was put in it.

### CODE REVIEW

**Comment by romani** [comment]
1) javadoc should be updated to contain description and example of usage fo new option

2) xdoc files should be updated too, too have the same description as in javadoc

**Comment by romani** [comment]
@liscju ,

https://github.com/liscju/checkstyle/blob/3d6e371a2528ce2539856ad276f74a13f4138636/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheck.java

I know that most of that is your changes, but lets do that while we are there.

3) please add yourself to authors

4) please look at https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java as example of javadoc that we should have for the Check.
one day in future we will do generation of xdoc files from javadoc, but for now we have to do copy-paste :( from javadoc to xdoc.

5) 
> /** */
    private boolean ignoreForControlVariablesNotIterated = true;

please provide javadoc

6) 
> /** Stack of block parameters. */

please put "\n" before that statement

7) 
>             case TokenTypes.FOR_EACH_CLAUSE:
                break;

please put a comment "//we need that Toekns only at leaveToken()"

8)
>             case TokenTypes.POST_DEC:
                // Do nothing
 
please put a comment "//we need that Toekns only at visitToken()"

9)
> if (currentVariables != null && !currentVariables.isEmpty()) {

can currentVariables be null ?

10)
> private Set<String> resolveVariablesManagedByForLoop(DetailAST ast)
 public Set<String> getForInitVariables(DetailAST ast)
    public Set<String> getForIteratorVariables(DetailAST ast)

can that methods be static ? if yes please make them and move to the end of file.

**Comment by liscju** [comment]
@romani ,changes was made as suggested

**Comment by romani** [comment]
@liscju , please : 
1) reply to me as "done" to each point next time. I had so much cases when people just forget to do a point, that will be recheck for you that you actually done.

2) please rebase on latest code, git can not do that automatically.

**Comment by liscju** [comment]
@romani rebase done, and sorry for not explicitly stating done for each point

**Comment by romani** [comment]
1) 
>```
 * for (int i = 0; i &lt; 1; i++) {
* i++;
* }
```

please add comments in code "//violation" to show where violation is, please do that for all examples.

2) 
> ignoreForControlVariablesNotIterated

I donot like name, let use JDK specification terms - http://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.14. What about ignoreOnEmptyUpdatePart ? please put a link to jdk spec in description.

3) 
>```
 * for(int j=0;j < 15;j++) {
* j = j + 2;
* }
```

Looks like the same as first example, so What a reason ? remove or explain in javadoc

4) 
>```
 Set<String> variablesToPutInScope;
if (ignoreForControlVariablesNotIterated) {
variablesToPutInScope = Sets.intersection(initializedVariables, iteratingVariables);
}
else {
variablesToPutInScope = initializedVariables;
}
```

please initiate variablesToPutInScope by default value as initializedVariables.
Does it sounds like idea fore new Chekstyle Check ? :) I you agree, please put as issue to experimental project.

5) 
>```
 DetailAST parameterDefAST =
forInitAST.findFirstToken(TokenTypes.VARIABLE_DEF);
for (; parameterDefAST != null;
parameterDefAST = parameterDefAST.getNextSibling())
```

Visibility scope of parameterDefAST should be hidden by FOR loop scope. the same problem in method getForIteratorVariables(....) . I think you tried to keep FOR as compact as possible, but it extra visibility does not do good for code, it is sign that something should be changed in method design for sure. 
Does it sounds like idea fore new Chekstyle Check ? :) I you agree, please put as issue to experimental project.

6)
>```
 final Set<Integer> possibleIterativeOperations =
Sets.newHashSet(TokenTypes.POST_INC, TokenTypes.POST_DEC, TokenTypes.DEC,
TokenTypes.INC, TokenTypes.ASSIGN);
```

I see no reason to create that each time method is executed.

7)
> private static Set<String> getForIteratorVariables(DetailAST ast)

I do not like that method implementation, It is very hard to read, please think howto make it more easy to read. I will be more exact in complains on next round of code-review.

**Comment by liscju** [comment]
@romani 
1) DONE
2) DONE - changed name as suggested and added link
3) DONE - removed redundant example
4) DONE - without introducing new issue
5) DONE - without introducing new issue
6) DONE - changed to private static field of class
7) DONE - refactored method,i hope you find it better

**Comment by romani** [comment]
> ignoreOnEmptyUpdatePart

The more I look at this option, the more I do notlike it, as it does not make sense, it should not be configurable (imply TRUE always). 

Please put in UT following case:
```
for (int i ,j = 0 ; i <10; i++) {
 j++
}
```
Should we raise violation there ? if yes -so we need to change name of option, it even one more sign that option for that us wrong concept (it you agree please remove option). But please keep explaination in javadoc how we process update part of FOR and keep link at class javadoc to JDK spec.

> 
```
 private static final Set<Integer> POSSIBLE_ITERATIVE_OPERATIONS =
Sets.newHashSet(TokenTypes.POST_INC, TokenTypes.POST_DEC, TokenTypes.DEC,
TokenTypes.INC, TokenTypes.ASSIGN);
```

bad naming, should be mutation_oprtation. Please describe be cases where TokenTypes.DEC,
TokenTypes.INC, is used.


> throw new IllegalStateException(ast.toString());

Please add string message to exception

>
```
 for (int i = 0; i < variablesToGetOutOfScope.size(); i++) {
currentVariables.pop();
}
```

Why we need "i" ? can you get rid of it.

>  ```
private static Set<String> getForIteratorVariables(DetailAST ast)
private static DetailAST getListOfUpdateExpressions(DetailAST ast)
```

please do one return point from function. please always try to do that.

**Comment by romani** [comment]
@liscju , if you finish that PR before Saturday , your changed will be released in 6.5 .

**Comment by liscju** [comment]
@romani 
1) DONE,ignoreOnEmptyUpdatePart removed,moved link to javadoc of class

2) DONE,changed name to MUTATION_OPERATIONS, 
example of inc and dec is ++i,--j(pre operators) - i added test case for this

3) TO DISCUSS,i dont know what exception message should be, as far as i checked in com.puppycrawl.tools.checkstyle.checks.coding package such exception handling is normal 

4) DONE,for (int i = 0; i < variablesToGetOutOfScope.size(); i++) replaced with for (String variableName : variablesToPutInScope) 

5) DONE,made one return point from both of function

**Comment by romani** [comment]
1)

for (int i ,j = 0 ; i <10; i++) {
 j++
}

I did not found  where you put a test case that I requested, please provide a link to it.

2)
>
TO DISCUSS,i dont know what exception message should be, as far as i checked in com.puppycrawl.tools.checkstyle.checks.coding package such exception handling is normal

#852

3)

> currentVariables = new ArrayDeque<>();

please use the same way of cleaning a collection with beginTree(), both approaches are fine, but need to be consistent.

4)
> private Set<String> resolveVariablesManagedByForLoop(DetailAST ast)

please name is as getXXXXXXXX

5)
 > final Set<String> variablesToGetOutOfScope = resolveVariablesManagedByForLoop(ast);
for (String variable : variablesToGetOutOfScope) {
currentVariables.pop();
}

variablesToGetOutOfScope - unclear name, and in FOR iterable var is not used , why ?

6)
> final DetailAST forUpdateListAST = getListOfUpdateExpressions(ast);

that method is used ones,  please combine is with "for (DetailAST iteratingExpressionAST : findChildsOfExpressionType(forUpdateListAST)) {" and simplify a code.

7)
> private static List<DetailAST> findChildsOfExpressionType(DetailAST ast)

Children

**Comment by romani** [comment]
@liscju , ping.

**Comment by liscju** [comment]
1) DONE, Added In InputModifiedControl.java as last case 
https://github.com/checkstyle/checkstyle/blob/c0071fb7e9569954963549a5b6e257f2894dc13d/src/test/resources/com/puppycrawl/tools/checkstyle/coding/InputModifiedControl.java#L70

2) From discussion in #852 it seems like that default part of switch should be removed, should i do this?

3) I really dont know what to do, please give further explanations

4) DONE

5) In for-each we always pop one variable which we use for iterating. In case of "typical for" we have to pop as many variables as we pushed. I introduce method popCurrentVariables to show this explicitly,i hope You find it more readable.

6) DONE?, Inline getListOfUpdateExpressions,i dont know how to simplify it more

7) DONE

**Comment by mkordas** [comment]
Let's give this PR some more meaningful name, _Issue #286_ does not mean much.

**Comment by romani** [comment]
@liscju 

0)
> From discussion in #852 it seems like that default part of switch should be removed, should i do this?

I am not sure when we will find time to fix that (it even blocked by another issue), so for now please stay with "default:" in switches and provide UTs coverage for them.

1) 
> currentVariables = new ArrayDeque<>();

currentVariables.clear();

2) 
>         for (DetailAST iteratingExpressionAST : findChildrenOfExpressionType(forUpdateListAST)) {
            final DetailAST expressionChildAST = iteratingExpressionAST.getFirstChild();

can we return from findChildrenOfExpressionType such objects that are already expressionChildAST ?
that is prvate function do it as convenient to implementation.

3) 

> final List<DetailAST> foundExpression = new LinkedList<>();


foundExpressions - plural form for collections.

**Comment by liscju** [comment]
0) I asked because You provided link to #852 in reply to my question about what string message in throwing IllegalStateException should be. I didnt find there information about it, i seeked usages of IllegalStateException,and nearly in all places it looks like :

<code>
throw new IllegalStateException(ast.toString())
</code>

1) currentVariables is already cleared in beginTree function, I am sorry but really dont know what You requested with it

2) DONE

3) DONE

**Comment by romani** [comment]
@liscju

> and nearly in all places it looks like 

Throw exception without message is bad practice,  i am sorry that checkstyle project has a lot of bad practices. All of them will be fixed eventually.
Please add a message to exception.

> I am sorry but really dont know what You requested with it

Just substitude clearence by ctor call to clearance by method "clear()".

**Comment by liscju** [comment]
1) DONE, added message to exception

2) TO DISCUSS,i finally get what You requested, but doing this is bad
<code>
<pre>variableStack.push(currentVariables);
currentVariables = new ArrayDeque<>();</pre>
</code>

if we change <code> currentVariables = new ArrayDeque<>() </code> to <code> currentVariables.clear()</code> it will clear already pushed variable stack(and breaks test). We can use clear only if we push copy of currentVariables(now reference is pushed).

**Comment by romani** [comment]
@liscju ,

> TO DISCUSS

ok i got it, that is not clear code, 

does it make sense  to remove that field at all and use method that receive top value from stack - peek() ? that will simplify structure of class

if you do not agree on a god reason please provide it and please add a comments there do describe a behavior.

**Comment by romani** [comment]
@liscju ,

please sync javadoc examples to xdoc content (please recheck all all javadoc changes reflected xdoc) and your good for merge.

**Comment by liscju** [comment]
@romani DONE, i checked it ,added example to xdoc

**Comment by romani** [comment]
merged as FF

**Comment by romani** [comment]
thanks a lot for your persistence to make code of good quality

**Pull request closed without merging**
