### PR TITLE
Issue #11163: Enforce file size on InputJavadocStyle5

### PR DESCRIPTION
**Pull request by varad64**
Hello, this is hopefully my first contribution to Checkstyle.
I have referred to https://github.com/checkstyle/checkstyle/issues/11163 in detail and have proceeded to enforce the file size constraint on InputJavadocStyle5.

Please let me know if there are any changes required.

Thanks!

### CODE REVIEW

**Comment by nrmancuso** [comment]
@varad64 please read through https://checkstyle.org/contributing.html, and then:

1. squash all commits to one
2. make sure that `mvn clean verify` passes on your local
3. push your changes to github
4. work through any CI failures, feel free to ping us for help

Also, please do not open/close multiple PRs, this just generates noise.

**Comment by varad64** [comment]
Noted @nrmancuso, will follow all guidelines and only then push my changes!
Thanks!

**Comment by varad64** [comment]
Hello @nrmancuso, I've squashed all commits and re-tested the changes with `mvn clean verify` . But it keeps raising the following warning:

> [WARNING] The POM for org.apache.maven.wagon:wagon-http:jar:1.0-beta-6 is invalid, transitive dependencies (if any) will not be available, enable verbose output (-X) for more details
[WARNING] The POM for org.apache.maven.wagon:wagon-webdav-jackrabbit:jar:1.0-beta-6 is invalid, transitive dependencies (if any) will not be available, enable verbose output (-X) for more details

> [INFO] Running com.puppycrawl.tools.checkstyle.internal.ArchUnitCyclesCheckTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

This is followed by 5 errors, 4 of which arise from JavaDocPropertiesGeneratorTest

I have tried re-installing maven, but to no avail.
Could you please tell me what I am doing wrong?

Thanks in advance!

**Comment by nrmancuso** [comment]
@varad64 ignore warnings that you shared, read errors attentively, and fix problems that errors describe. Also, make sure that you do not have unintended changes in your repo by using `git status`.

**Comment by varad64** [comment]
> @varad64 ignore warnings that you shared, read errors attentively, and fix problems that errors describe. Also, make sure that you do not have unintended changes in your repo by using `git status`.

Thanks @nrmancuso, I'll do this

**Comment by romani** [comment]
remove cloned repo and do this command in terminal https://github.com/checkstyle/checkstyle/blob/master/appveyor.yml#L23
reclone again

**Comment by nrmancuso** [comment]
> Usage: java com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator [-hV]

If this is the issue, it means that we can create some simple unit test to make windows users aware of  `git config core.autocrlf` if it fails.

**Comment by varad64** [comment]
> remove cloned repo and do this command in terminal https://github.com/checkstyle/checkstyle/blob/master/appveyor.yml#L23 reclone again

Getting the same set of errors after following these steps. Is there something else I should do?

**Comment by rnveach** [comment]
@varad64 Please confirm what OS you are using. Please provide us a text document (don't just paste big text) with the full results of the following commands.
````
git config core.autocrlf
git checkout origin/master
git status                       // stop if it doesn't say "nothing to commit, working tree clean"
mvn clean verify
````

**Comment by rnveach** [comment]
@romani 
> remove cloned repo and do this command in terminal https://github.com/checkstyle/checkstyle/blob/master/appveyor.yml#L23 reclone again

This is not the command. It is missing the setting of the value, this just displays the value.
See the old documentation at https://checkstyle.sourceforge.io/version/8.0/beginning_development.html#Before_development

**Comment by varad64** [comment]
> @varad64 Please confirm what OS you are using. Please provide us a text document (don't just paste big text) with the full results of the following commands.
> 
> ```
> git config core.autocrlf
> git checkout origin/master
> git status                       // stop if it doesn't say "nothing to commit, working tree clean"
> mvn clean verify
> ```

Hello @rnveach, I am using Windows 10 and the file with the results for the above commands is attached.
[output.txt](https://github.com/checkstyle/checkstyle/files/10395392/output.txt)

**Comment by rnveach** [comment]
> Already on 'master'
> Your branch is up to date with 'origin/master'.

Did you trim these commands or the output any? The command is `origin/master` not your local branch `master` and I was expecting more from the git status command from being on the remote branch.

> I am using Windows 10

Are you running this in pure Powershell or Command prompt? The `$` on the start looks like a linux terminal than windows.

**Comment by rnveach** [comment]
Just for clarity, showing my own new clone which has `core.autocrlf` off and still passes. No MinGW or anything besides pure Windows 10 Pro.

````
PS Z:\> git clone https://github.com/checkstyle/checkstyle.git
Cloning into 'checkstyle'...
remote: Enumerating objects: 213687, done.
remote: Counting objects: 100% (430/430), done.
remote: Compressing objects: 100% (239/239), done.
remote: Total 213687 (delta 156), reused 296 (delta 77), pack-reused 213257
Receiving objects: 100% (213687/213687), 84.62 MiB | 13.04 MiB/s, done.
Resolving deltas: 100% (122984/122984), done.
Checking out files: 100% (4860/4860), done.
PS Z:\> git config core.autocrlf
false
PS Z:\> cd .\checkstyle\
PS Z:\checkstyle> mvn clean verify
[INFO] Scanning for projects...
....
....
....
....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:42 min
[INFO] Finished at: 2023-01-11T14:38:49-05:00
[INFO] ------------------------------------------------------------------------
PS Z:\checkstyle> git config core.autocrlf
false
````

**Comment by varad64** [comment]
> > Already on 'master'
> > Your branch is up to date with 'origin/master'.
> 
> Did you trim these commands or the output any? The command is `origin/master` not your local branch `master` and I was expecting more from the git status command from being on the remote branch.

Oh alright, I checked out into my local branch. Re running the commands and will follow up with the new output file
> 
> > I am using Windows 10
> 
> Are you running this in pure Powershell or Command prompt? The `$` on the start looks like a linux terminal than windows. Your running this outside a MinGW or such?

Running it in Git Bash

**Comment by rnveach** [comment]
Ok, that looks like what the issue is as I reproduced on my local.

Git bash failed for me as described above, either with autocrlf on or off. When I examined the text files with autocrlf on, line endings were linux line ending `\n` and were not windows line endings `\r\n`. 

I can only assume when calling maven in the git-bash environment, Java or maven ignores the environment (or doesn't know about it) and defaults back to Windows and the tests run applying `\r\n`.

@romani @nrmancuso The only way we can verify this in a test is if we read a file and look at it's line ending and see if it matches the system's setting.

**Comment by varad64** [comment]
> > Running it in Git Bash
> 
> Can you run it in pure Windows outside Git Bash's terminal (git-bash.exe)? I am wondering if there is a conflict with it since I believe the bash version runs in some linux hybrid and that may be confusing line endings somewhere. There is git-cmd.exe with git bash and then there is pure git.
> 
> For example, I have git bash installed too. I don't run git-bash.exe or git-cmd.exe, but I run `bin\git.exe`.
> 
> I'll run my own tests too.



> > Running it in Git Bash
> 
> Can you run it in pure Windows outside Git Bash's terminal (git-bash.exe)? I am wondering if there is a conflict with it since I believe the bash version runs in some linux hybrid and that may be confusing line endings somewhere. There is git-cmd.exe with git bash and then there is pure git.
> 
> For example, I have git bash installed too. I don't run git-bash.exe or git-cmd.exe, but I run `bin\git.exe`.
> 
> I'll run my own tests too.

Sure, will do this!

**Comment by rnveach** [comment]
@varad64 @romani @nrmancuso I did some more testing and understand why the tests fail. I am still not sure how the Git Bash environment activities this or create a test for it yet.

Git Bash actually activating colors in output when executing maven/java. It has nothing to do with files or line endings. Picocli by default must have colors set to auto. In some environments, it doesn't print colors. Git Bash found some way to activate it.

I tried maven's `--batch-mode` and it had no effect, colors still came out.

The only way I could "fix" this for Git Bash (meaning the tests pass) was to force picocli to turn off colors.
````
diff --git a/src/main/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGenerator.java b/src/main/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGenerator.java
index 9489107..f746078 100644
--- a/src/main/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGenerator.java
+++ b/src/main/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGenerator.java
@@ -35,6 +35,7 @@
 import com.puppycrawl.tools.checkstyle.utils.JavadocUtil;
 import picocli.CommandLine;
 import picocli.CommandLine.Command;
+import picocli.CommandLine.Help.Ansi;
 import picocli.CommandLine.Option;
 import picocli.CommandLine.ParameterException;
 import picocli.CommandLine.Parameters;
@@ -92,7 +93,7 @@
         }
         catch (ParameterException ex) {
             System.err.println(ex.getMessage());
-            ex.getCommandLine().usage(System.err);
+            ex.getCommandLine().usage(System.err, Ansi.OFF);
         }
     }
 
````

This only fixed it for `JavadocPropertiesGeneratorTest`. `MainTest` is also failing in a similar way.

**Comment by varad64** [comment]
Getting a different error when I run the build process on Powershell

```
[INFO] Results:
[INFO]
[INFO] Tests run: 478, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- modernizer:2.4.0:modernizer (modernizer) @ checkstyle ---
[INFO] --------------------------------------------------------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] --------------------------------------------------------------------------------------------------------------------------
[INFO] Total time:  16:47 min
[INFO] Finished at: 2023-01-12T23:44:28+05:30
[INFO] --------------------------------------------------------------------------------------------------------------------------
[ERROR] Failed to execute goal org.gaul:modernizer-maven-plugin:2.4.0:modernizer (modernizer) on project checkstyle: Execution modernizer of goal org.gaul:modernizer-maven-plugin:2.4.0:modernizer failed: A required class was missing while executing org.gaul:modernizer-maven-plugin:2.4.0:modernizer: org/codehaus/plexus/util/StringUtils
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.gaul:modernizer-maven-plugin:2.4.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/ameya/.m2/repository/org/gaul/modernizer-maven-plugin/2.4.0/modernizer-maven-plugin-2.4.0.jar
[ERROR] urls[1] = file:/C:/Users/ameya/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[2] = file:/C:/Users/ameya/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[3] = file:/C:/Users/ameya/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[4] = file:/C:/Users/ameya/.m2/repository/org/ow2/asm/asm/9.2/asm-9.2.jar
[ERROR] urls[5] = file:/C:/Users/ameya/.m2/repository/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
[ERROR] urls[6] = file:/C:/Users/ameya/.m2/repository/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
[ERROR] urls[7] = file:/C:/Users/ameya/.m2/repository/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
[ERROR] urls[8] = file:/C:/Users/ameya/.m2/repository/org/gaul/modernizer-maven-annotations/2.4.0/modernizer-maven-annotations-2.4.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.puppycrawl.tools:checkstyle:10.7.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : org.codehaus.plexus.util.StringUtils
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the '-e' switch
[ERROR] Re-run Maven using the '-X' switch to enable verbose output
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```

**Comment by rnveach** [comment]
> A required class was missing 

To me this sounds like a dependency wasn't downloaded or is corrupted. I recently had a hard drive that was failing and it was constantly getting this error because of file corruption. `modernizer` can be skipped, so you can try looking up the command for that. It may be something like `-D"modernizer.skip=true"`.

**Comment by rnveach** [comment]
@nrmancuso found out how to disable colors in Git Bash.
`$ TERM=linux`

We can also build a test for this now that we know how it is getting enabled.

@nrmancuso believes the default value of TERM in Git Bash, which is `xterm`, defaults to 256 colors.

**Comment by romani** [comment]
@varad64, we merged fix for test failures. Please rebase and confirm that it works on your local

**Comment by varad64** [comment]
> @varad64, we merged fix for test failures. Please rebase and confirm that it works on your local

Hello @romani, I've been running the build process and as mentioned before, the modernizer plugin was still raising an error. So, as @rnveach had suggested, I skipped it.

But now, the raw github content to the JSON file for the validator plugin is not accessible via the bash. I looked into one of the previous issue [issue #10863](https://github.com/checkstyle/checkstyle/pull/10863/commits/b13601bb1251d54d7977b97957dafd93c248e121) where the link it had to be updated. The file was inaccessible when I tried accessing it via my browser too. Changed my DNS settings and it's working for the browser but the build process is still unable to access it.

I'm looking into what might be causing this. Will keep you posted. Thanks!

**Comment by romani** [comment]
Search in web how to configure proxy in maven config.

**Comment by nrmancuso** [comment]
@varad64 do you plan to continue working on this PR?

**Comment by varad64** [comment]
> @varad64 do you plan to continue working on this PR?
Hello @nrmancuso, the build kept failing even after configuring proxy in maven config. After it failed multiple times, I didn't circle back.

I can take this up sometime later. Thanks!

**Comment by nrmancuso** [comment]
@varad64 we will close this PR if there is no activity for awhile, you can reopen/create a new one as you become ready

**Pull request closed without merging**
