### PR TITLE
Issue #1930: Improve EqualsAvoidNull check

### PR DESCRIPTION
**Pull request by Vladlis**
http://vladlis.github.io/reports/ean/ - report against sevntu-checkstyle, guava, pmd, lombok-ast, spring-framework, hibernate-orm, elasticsearch, Hbase, Orekit. All new violations are confirmed.

### CODE REVIEW

**Comment by romani** [comment]
smth odd with collors in the diff site, after fix we introduce new violations, so color should be green for all of them. Red mean deletion.

I will review report and code the next day.

**Comment by Vladlis** [comment]
I did not bother about the order of arguments in the merge tool.
6 нояб. 2015 г. 8:06 AM пользователь "Roman Ivanov" <
notifications@github.com> написал:
>
> smth odd with collors in the diff site, after fix we introduce new
violations, so color should be green for all of them. Red mean deletion.

**Comment by romani** [comment]
Next time please keep order of arguments - it helps.

1) False-positive - http://vladlis.github.io/reports/ean/#heck.1.12
http://vladlis.github.io/reports/ean/#heck.1.1

**Comment by Vladlis** [comment]
> Next time please keep order of arguments - it helps.

OK

1) 
http://vladlis.github.io/reports/ean/#heck.1.1

both arguments are of String type
http://vladlis.github.io/reports/ean/xref/sevntu-checkstyle/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.html#L1006

http://vladlis.github.io/reports/ean/#heck.1.12

again, both arguments are of String type
http://vladlis.github.io/reports/ean/xref/sevntu-checkstyle/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidInstantiationCheck.html#L168
http://vladlis.github.io/reports/ean/xref/sevntu-checkstyle/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidInstantiationCheck.html#L161

**Comment by romani** [comment]
yes, my bad, validation is correct.

merged as FF.

**Pull request closed without merging**
