### PR TITLE
Issue #11230: Add Labeled_STAT token type in FallThroughCheck

### PR DESCRIPTION
**Pull request by yrfang**
Issue: #11230 

Hi there!
I'm trying to make some contributions to Checkstyle and learn from it. Thank you for reviewing.

https://github.com/checkstyle/checkstyle/blob/74747a21f4e1e1a9fa8495879bf85f058b7d9ba1/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java#L756

The main idea about the changes:
- Added Labeled_STAT token type when visiting token and converted it into string text
- Supported break to check if there is a label statement
- Added InputFallThroughLabelBreak input test file to verify new changes

### CODE REVIEW

**Comment by rnveach** [comment]
@yrfang Please look over CI failures as it is reporting issues with the changes you have provided.

**Comment by yrfang** [comment]
Ok, let me look into CI failures. Thanks.

**Review by romani — CHANGES_REQUESTED** [review]
You do not need extra token in Check, jus extend logic that operates with `return` and `break`.

**Comment by rnveach** [comment]
@yrfang ping

**Comment by nick-mancuso** [comment]
We have lost contact with author, anyone is welcome to reuse code and continue work on this issue.

**Pull request closed without merging**
