### PR TITLE
Issue #12978: Upgrade actions/cache to v3

### PR DESCRIPTION
**Pull request by 0xbakry**
Solves https://github.com/checkstyle/checkstyle/issues/12978

Upgradeing `actions/cache` to v3 upgrades `Node.js` to v16:
https://github.com/marketplace/actions/cache

### CODE REVIEW

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Please reference issue in commit message, this is not a minor update .

**Review by romani — APPROVED** [review]
Ok to merge when commit is fixed

**Comment by 0xbakry** [comment]
> Please reference issue in commit message, this is not a minor update .

Done.

**Comment by romani** [comment]
Circle CI is missed.
I am rebased PR.

**Comment by 0xbakry** [comment]
@nrmancuso Ping

**Pull request merged**
