### PR TITLE
Extended messages for CustomImportOrder

### PR DESCRIPTION
**Pull request by ivanov-alex**
to make them more informative

Reports to show how messages have changed and that no more new violations added:
Sevntu: [BEFORE](http://ivanov-alex.github.io/target_messages_sevntu_before/site/checkstyle.html), [AFTER](http://ivanov-alex.github.io/target_messages_sevntu_after/site/checkstyle.html), [comparison](https://www.diffchecker.com/geoblmsp)
Bazel: [BEFORE](http://ivanov-alex.github.io/target_messages_bazel_before/site/checkstyle.html), [AFTER](http://ivanov-alex.github.io/target_messages_bazel_after/site/checkstyle.html), [comparison](https://www.diffchecker.com/v8mmdxy1)

### CODE REVIEW

**Comment by romani** [comment]
Import statement for 'java.util.Set' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting group 'NOT_ASSIGNED_TO_ANY_GROUP' on this line.

http://checkstyle.sourceforge.net/config_imports.html#CustomImportOrder , STANDARD_JAVA_PACKAGE is defined there but NOT_ASSIGNED_TO_ANY_GROUP is not. 
Please make this as not a constant(upper case), so you need to define new variable in messages file as we can not hard-code part of message in Check code.

**Comment by ivanov-alex** [comment]
done

**Comment by romani** [comment]
Please regenerate report for last review

**Comment by ivanov-alex** [comment]
reports updated

**Comment by romani** [comment]
1) in new reports I can not find "without groups" 
2) reports are too different - uncomparable, because config is different - https://www.diffchecker.com/geoblmsp

**Comment by ivanov-alex** [comment]
My bad, fixed now:

Sevntu: [BEFORE](http://ivanov-alex.github.io/target_messages_sevntu_before/site/checkstyle.html), [AFTER](http://ivanov-alex.github.io/target_messages_sevntu_after/site/checkstyle.html), [comparison](https://www.diffchecker.com/aqotfrak)

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
