### PR TITLE
Issue #4587: Moved all necessary resource files for NewlineAtEndOfFilCheckTest

### PR DESCRIPTION
**Pull request by Kietzmann**
#4587
1) made a copy of InputNewlineCrAtEndOfFile
2) renamed one resource file cause it is using in another test 
3) changed suppressions due to file move

### CODE REVIEW

**Comment by romani** [comment]
@Kietzmann ,
I relaunched Appveyor , if fail again ... please address.

**Comment by Kietzmann** [comment]
@romani 
Ok, thanks.

**Comment by romani** [comment]
coverage is damaged for windows, please recheck your changes that you did not change end line symbols in files.
```
INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:04 min
[INFO] Finished at: 2017-07-06T14:48:28+00:00
[INFO] Final Memory: 120M/327M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:cobertura-maven-plugin:2.7:check (default) on project checkstyle: Coverage check failed. See messages above. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:cobertura-maven-plugin:2.7:check (default) on project checkstyle: Coverage check failed. See messages above.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Coverage check failed. See messages above.
	at org.codehaus.mojo.cobertura.tasks.CheckTask.execute(CheckTask.java:110)
	at org.codehaus.mojo.cobertura.CoberturaCheckMojo.execute(CoberturaCheckMojo.java:81)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
[ERROR] 
```

**Comment by rnveach** [comment]
Most likely it is because of moval of `NewlineCrAtEndOfFile` and it being listed in other places like [gitattributes](https://github.com/checkstyle/checkstyle/blob/master/.gitattributes).

**Comment by romani** [comment]
@Kietzmann , is there any progress on this issue ? do you have problems to reproduce CI failure ?

**Comment by Kietzmann** [comment]
@romani 
Fixed, please review

**Pull request merged**
