### PR TITLE
Issue #2642: ParseTreeBuilder was re-generated to have readable variable names

### PR DESCRIPTION
**Pull request by baratali**

### CODE REVIEW

**Comment by romani** [comment]
@baratali , this file has to have annotation ```@Generated``` and javadoc that explain a reason why this file was generated and link to generator.

**Comment by baratali** [comment]
@romani , I've added description and annotation. Please review again.

**Comment by romani** [comment]
this is PR should merged after https://github.com/checkstyle/contribution/pull/39. https://github.com/checkstyle/contribution/pull/39 still items to fix before merge.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
