### PR TITLE
Issue #4870: added UT to ensure multithread annotations on modules

### PR DESCRIPTION
**Pull request by rnveach**
Issue #4870

### CODE REVIEW

**Comment by romani** [comment]
Spell checker is not happy https://travis-ci.org/checkstyle/checkstyle/jobs/401464577#L673

**Comment by rnveach** [comment]
@romani This display is not intuitive. https://travis-ci.org/checkstyle/checkstyle/jobs/401506626#L672
Can you tell me where it is expecting the word to be placed?

**Comment by romani** [comment]
You just need to apply generated command that is printed in logs.

If you want to do this manually .... 
```
@@ -807 +806,0 @@
-multi
@@ -809,0 +809 @@
```

It is just a "patch" format, that you find format specification in web.
Looks like you placed new word to line 807 but it should be at line 809. 
Words just need to be aphabetically sorted in this file.

**Comment by rnveach** [comment]
````
@@ -806,5 +806,5 @@
 Multiset
-multi
 multithreading
 mutableexception
+mutli
 MVC
````
This sorting makes no sense.

**Comment by rnveach** [comment]
@romani ci is passing now

**Pull request merged**
