### PR TITLE
Issue #382: Fix HiddenField false positive violations for anonymous classes

### PR DESCRIPTION
**Pull request by MEZk**
[Reports & explanations](http://mezk.github.io).

### CODE REVIEW

**Comment by mkordas** [comment]
@MEZk,how do you generate so pretty reports? It would be great to give similar tool for that to every Checkstyle developer.

Just one remark: closure is rather uncommon word in context of Java. If anything, this can be common name for anonymous classes and lambdas. But this PR is just about anonymous classes, so I would:
* if this problem affects just anonymous classes change commit and PR name
* if this problem affects anonymous classes and lambdas, please add test case for lambdas

Does it make sense?

**Comment by romani** [comment]
1) 
please follow notes of mkordas

2)
> && ScopeUtils.getSurroundingScope(parent) != Scope.ANONINNER

if think it would be better to make new util method
ScopeUtils.isInScope(parent, Scope.ANONINNER)

3)
>  ```
           if ((isStaticFieldHiddenFromClosure(ast, name)
                        || isStaticOrInstanceField(ast, name))
                             && !isMatchingRegexp(name)
                              && !isIgnoredParam(ast, name)) {
```
proper indentation works better then braces!!!
make it
```
           if ((isStaticFieldHiddenFromClosure(ast, name)
                              || isStaticOrInstanceField(ast, name))
                     && !isMatchingRegexp(name)
                     && !isIgnoredParam(ast, name)) {
```

**Comment by MEZk** [comment]
@mkordas 
>how do you generate so pretty reports? It would be great to give similar tool for that to every Checkstyle developer.

It is just markdown editor, diff command, manual review of report for guava (to find lines which are differ), and checkstyle tester. 
Nevertheless, it will be good if important report information which is produced by checkstyle-tester in checkstyle.xml will not be printed as one line:

```html 
 </div>
    <div id="bodyColumn">
      <div id="contentBox">
        <div class="section"><h2>Checkstyle Results<a name="Checkstyle_Results"></a></h2><p>The following document contains the results of <a class="externalLink" ...
```

and we can use diff command to find the lines which are differ in report.

>Does it make sense?

Yes, it make sense. Problem affects anonymous classes. 
But a few words about closures in Java: http://stackoverflow.com/questions/5443510/closure-in-java-7

**Comment by romani** [comment]
> which is produced by checkstyle-tester in checkstyle.xml will not be printed as one line

we reuse checkstyle-maven-plugin to generate html and xml reports. We can generate xml report by checkstyle (we have XmlLogger), and we could PROBABLY change formatting of it.  BUT xml format use a lot of tools to read chekcstyle results so have to be careful with updates.

**Comment by MEZk** [comment]
@romani 
1) Done
2) Done
3) Done

**Comment by romani** [comment]
Merged as ff, but please address mkordas notes in next PR

**Pull request closed without merging**
