### PR TITLE
Issue #12571: update all release action to have 'Setup local maven ca…

### LINKED ISSUE #12571: update all release action to have 'Setup local maven cache' step to optimize download of artifacts
all actions that executes `mvn` takes a lot of time to download jars .... we need to use maven cache as we do in other actions that works on PRs 

example: https://github.com/checkstyle/checkstyle/blob/bef49aea4a923bc003b0ffd1338b8f1606f2badc/.github/workflows/pitest.yml#L54

### PR DESCRIPTION
**Pull request by stoyanK7**
Resolves #12571

### CODE REVIEW

**Comment by stoyanK7** [comment]
@romani In response to [your comment in the issue](https://github.com/checkstyle/checkstyle/issues/12571#issuecomment-1410405862)
> it was and issue at "release: prepare" https://github.com/checkstyle/checkstyle/actions/runs/4054790160/jobs/6977062039

Here are the results for `R: Maven Release Prepare ` in particular:
| Job | Time |
| :---:   | :---: |
| [First job without cache. Uploads cache after task is done](https://github.com/stoyanK7/checkstyle/actions/runs/4057026843/jobs/6982267658) | 3m 13s    |
| [Same job running for a second time with the cache from the first job](https://github.com/stoyanK7/checkstyle/actions/runs/4057076737/jobs/6982378354) | 1m 26s    |

**Comment by romani** [comment]
If we do caching by pom.xml, it will be always different when we do version bump.
So there will be no benefits for release actions.

@nrmancuso , do you have any good ideas from your experience on this?

**Comment by nrmancuso** [comment]
> If we do caching by pom.xml, it will be always different when we do version bump. So there will be no benefits for release actions.
> 
> @nrmancuso , do you have any good ideas from your experience on this?

I would say that it is good to create release with no cache, red CI from some bad package can be fixed whenever, but blocking release because we wanted to save 1-3 minutes is not good. 

But if you really want to use cache for release, just hash some other file.

**Review by romani — APPROVED** [review]
Ok to merge.

I have I my mind idea to create new file from pom.xml but removal of first 16 lines
https://github.com/checkstyle/checkstyle/blob/master/pom.xml
And making cache on such new file, for release related actions only. This speed up is good I think.

**Pull request merged**
