### PR TITLE
Corrected links on web site (addition), issue #751

### PR DESCRIPTION
**Pull request by MEZk**
@romani 

[Linkcheck report](http://mezk.github.io/linkcheck/linkcheck.html)

**Investigation:**

*  twitter (all links - false-positive, direct link)
https://twitter.com/checkstyle_java/

*  Not available any more
https://github.com/checkstyle/google-style-config-test

*  Unreachable from config files:
plugin-management.html
http://maven.apache.org/plugins/maven-release-plugin/
plugins.html
http://maven.apache.org/enforcer/maven-enforcer-plugin: 301 Moved Permanently
http://maven.apache.org/surefire/maven-failsafe-plugin: 301 Moved Permanently
http://maven.apache.org/surefire/maven-surefire-plugin: 301 Moved Permanently
http://maven.apache.org/surefire/maven-surefire-report-plugin: 301 Moved Permanently
http://mojo.codehaus.org/antlr-maven-plugin: 302 Found
http://mojo.codehaus.org/build-helper-maven-plugin: 302 Found
http://mojo.codehaus.org/cobertura-maven-plugin/: 302 Found
http://mojo.codehaus.org/jdepend-maven-plugin: 302 Found
http://mojo.codehaus.org/taglist-maven-plugin: 302 Found
http://mojo.codehaus.org/xml-maven-plugin: 302 Found
http://www.antlr.org/antlr4-maven-plugin: 404 Not Found
https://twitter.com/checkstyle_java/: 307 Temporary Redirect
sonar.html 
http://nemo.sonarqube.org/project/index/com.puppycrawl.tools:checkstyle: 302 Found (false-positive, direct link)

* apidocs/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheck.html
http://kclee.com/clemens/java/javancss/: 302 Found (false-positive, redirect directly to the http://kclee.com/clemens/java/javancss/)

* cmdline.html 
http://iweb.dl.sourceforge.net/project/checkstyle/checkstyle/6.10-SNAPSHOT/checkstyle-6.10-SNAPSHOT-all.jar: 302 Found (6.10-SNAPSHOT has not been uploaded on sourceforge)

All links which are mentioned above can be included in excludes section of maven-linkcheck-plugin except https://github.com/checkstyle/google-style-config-test and http://iweb.dl.sourceforge.net/project/checkstyle/checkstyle/6.10-SNAPSHOT/checkstyle-6.10-SNAPSHOT-all.jar

**Redirect tracers:**
http://www.wheregoes.com/retracer.php
http://www.internetofficer.com/seo-tool/redirect-check/
http://redirectdetective.com/

### CODE REVIEW

**Comment by romani** [comment]
> twitter (all links - false-positive, direct link)

As you think that is false-positive - please open issue to linkcheck plugin.

> https://github.com/checkstyle/google-style-config-test

please change to https://github.com/checkstyle/checkstyle/tree/master/src/it/java/com/google/checkstyle/test

> Unreachable from config files:

any proposals ?

> http://nemo.sonarqube.org/project/index/com.puppycrawl.tools:checkstyle: 302 Found (false-positive, direct link)

create issue against or propose workaround, please try to activate DEBUG logging for that plugin to get more details.

> 6.10-SNAPSHOT has not been uploaded on sourceforge)

we will never keep SNAPSHOT at sourceforge site, please add that link to ignorelist.

> 302 Found (false-positive, redirect directly to the 

please read more about that code 302, and propose workaround, may be we could add the code to "ignore", but we need to explain that.

**Comment by MEZk** [comment]
@romani 
>we will never keep SNAPSHOT at sourceforge site, please add that link to ignorelist.

When you make release you change version from 6.10-SNAPSHOT to 6.10
````xml
  <groupId>com.puppycrawl.tools</groupId>
  <artifactId>checkstyle</artifactId>
  <version>6.10</version>
  <packaging>jar</packaging>
````

The following link at cmdline.xml.vm uses ${projectVerion} reference:
````
http://iweb.dl.sourceforge.net/project/checkstyle/checkstyle/${projectVersion}/checkstyle-${projectVersion}-all.jar
````

So, when releasing, the  version will be set to 6.10 and the link will be correct:
````
http://iweb.dl.sourceforge.net/project/checkstyle/checkstyle/6.10/checkstyle-6.10-all.jar
````

**Comment by romani** [comment]
> But now version is set to 6.9-SNAPSHOT, that is why the link is incorrect.

yes, but I want to try linkcheck plugin to work on each PR, to validate links. So we need to configure plugin to skip validating SNAPSHOT on sourceforge.

On a this task completion, all errors should be resolved in report and plugin should be adjusted to fail build if bad link appear.

**Comment by MEZk** [comment]
@romani 
>So we need to configure plugin to skip validating SNAPSHOT on sourceforge.

Done. See [excludedLinks](https://github.com/MEZk/checkstyle/commit/4a267b9daeb9a4ba8af7283ed332e16d97c6eed1#diff-600376dffeb79835ede4a0b285078036R929) and report.

>plugin should be adjusted to fail build if bad link appear.

How can we use linkcheck to fail a build if bad link appear? There are not any failOnError or haltOnFailure, etc, flags in plugin's configuration. According to plugin [description](https://maven.apache.org/plugins/maven-linkcheck-plugin/):

```
The Linkcheck Plugin only has one goal.
    linkcheck:linkcheck Generates a Linkcheck report.
```

>please change to https://github.com/checkstyle/checkstyle/tree/master/src/it/java/com/google/checkstyle/test

Done.

>As you think that is false-positive - please open issue to linkcheck plugin.

[ISSUE#22: Linkcheck reports 307 Temporary Redirect on twitter.com](https://issues.apache.org/jira/browse/MLINKCHECK-22)

>apidocs/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheck.html
http://kclee.com/clemens/java/javancss/: 302 Found (false-positive, redirect directly to the http://kclee.com/clemens/java/javancss/)

[ISSUE#23: Linkcheck reports 302 Found on link that is redirected to itself.](https://issues.apache.org/jira/browse/MLINKCHECK-23)

>Unreachable from config files:
any proposals ?

I've not found any information on how maven generates urls at plugin-management.html, plugins.html or sonar.html. It seams to me that it uses links from it's repository or directly from library. I think we can exclude those links, but http://www.antlr.org/antlr4-maven-plugin and 404 confuses me.

See new [report](http://mezk.github.io/linkcheck/linkcheck.html).

**Comment by romani** [comment]
> The Linkcheck Plugin only has one goal. linkcheck:linkcheck Generates a Linkcheck report.

ok, please create issue against linkcheck to have "check" goal to be used in verify phase.

> Should we exclude http://kclee.com/clemens/java/javancss/ and https://twitter.com/checkstyle_java/ ?

yes, please do, and place link to issue as "till #xxxxxxxxx" to config 

> http://maven.apache.org/components/surefire/maven-failsafe-plugin/

such links are opening in browser correctly, that is strange why we have 301 code.

> I've not found any information on how maven generates urls at plugin-management.html

you can open code of linkcheck plugin and take a look.

**Comment by romani** [comment]
the  main point of final state is to have report with no warnings and errors, to let us easily catch then new problems are introduced or happen due to changes in the web.

**Comment by MEZk** [comment]
@romani 
Links on plugins.html, plugins-management.htmll are generated by Apache Maven Project Info Reports Plugin. The plugin has project-info-reports:plugin-management and project-info-reports:plugins goals which have property [customBundle](https://maven.apache.org/plugins/maven-project-info-reports-plugin/plugin-management-mojo.html#customBundle). customBundle property sets a path for a custom bundle instead of using the default one. Using this field, you could change the texts in the generated reports. According to [maven's documentation](https://maven.apache.org/plugins/maven-project-info-reports-plugin/examples/custom-report.html), all reports have a static renderer, only texts could be changed. So, we can change only static content, text, headers, etc.

**Investigation of plugins.html generation:**
All URLs on plugin-management.html are generated by using info from repository. Here is the code:
[renderSectionPlugins](https://github.com/apache/maven-plugins/blob/trunk/maven-project-info-reports-plugin/src/main/java/org/apache/maven/report/projectinfo/PluginsReport.java#L239)
[getPluginRow](https://github.com/apache/maven-plugins/blob/trunk/maven-project-info-reports-plugin/src/main/java/org/apache/maven/report/projectinfo/PluginsReport.java#L269)
So, we do not have an ability to change plugins urls on that page, because those links are specified by plugins developers.

**Investigation of plugin-management.html generation:**
All URLs on plugin-management.html are generated by using info from repository. Here is the code:
[renderSectionPluginManagement](https://github.com/apache/maven-plugins/blob/trunk/maven-project-info-reports-plugin/src/main/java/org/apache/maven/report/projectinfo/PluginManagementReport.java#L230)
[getPluginRow](https://github.com/apache/maven-plugins/blob/trunk/maven-project-info-reports-plugin/src/main/java/org/apache/maven/report/projectinfo/PluginManagementReport.java#L259)
So, we do not have an ability to change plugins urls on that page too. 

**Investigation of sonar.html generation:**
sonar.html is a page that can be reached from http://checkstyle.sourceforge.net/project-reports.html . The project-reports.html page is generated by maven-site-plugin. [CategorySummaryDocumentRenderer class]() is used to generate the page. Here is the code: 
https://github.com/apache/maven-plugins/blob/trunk/maven-site-plugin/src/main/java/org/apache/maven/plugins/site/render/CategorySummaryDocumentRenderer.java#L150
Again, we can do nothing to change those links.

Suggestion: exclude all links on that page from validation.

**Comment by MEZk** [comment]
@romani 
Links on plugins.html, plugins-management.htmll are generated by Apache Maven Project Info Reports Plugin. The plugin has project-info-reports:plugin-management and project-info-reports:plugins goals which have property [customBundle](https://maven.apache.org/plugins/maven-project-info-reports-plugin/plugin-management-mojo.html#customBundle). customBundle property sets a path for a custom bundle instead of using the default one. Using this field, you could change the texts in the generated reports. According to [maven's documentation](https://maven.apache.org/plugins/maven-project-info-reports-plugin/examples/custom-report.html), all reports have a static renderer, only texts could be changed. So, we can change only static content, text, headers, etc.

**Investigation of plugins.html generation:**
All URLs on plugin-management.html are generated by using info from repository. Here is the code:
[renderSectionPlugins](https://github.com/apache/maven-plugins/blob/trunk/maven-project-info-reports-plugin/src/main/java/org/apache/maven/report/projectinfo/PluginsReport.java#L239)
[getPluginRow](https://github.com/apache/maven-plugins/blob/trunk/maven-project-info-reports-plugin/src/main/java/org/apache/maven/report/projectinfo/PluginsReport.java#L269)
So, we do not have an ability to change plugins urls on that page, because those links are specified by plugins developers.

**Investigation of plugin-management.html generation:**
All URLs on plugin-management.html are generated by using info from repository. Here is the code:
[renderSectionPluginManagement](https://github.com/apache/maven-plugins/blob/trunk/maven-project-info-reports-plugin/src/main/java/org/apache/maven/report/projectinfo/PluginManagementReport.java#L230)
[getPluginRow](https://github.com/apache/maven-plugins/blob/trunk/maven-project-info-reports-plugin/src/main/java/org/apache/maven/report/projectinfo/PluginManagementReport.java#L259)
So, we do not have an ability to change plugins urls on that page too. 

**Investigation of sonar.html generation:**
sonar.html is a page that can be reached from http://checkstyle.sourceforge.net/project-reports.html . The project-reports.html page is generated by maven-site-plugin. [CategorySummaryDocumentRenderer class]() is used to generate the page. Here is the code: 
https://github.com/apache/maven-plugins/blob/trunk/maven-site-plugin/src/main/java/org/apache/maven/plugins/site/render/CategorySummaryDocumentRenderer.java#L150
Again, we can do nothing to change those links.

Suggestion: exclude all links on that page from validation.

**Comment by MEZk** [comment]
@romani 
So, I've opened 4 issues against maven plugins:

Linkcheck reports 307 Temporary Redirect on twitter.com
https://issues.apache.org/jira/browse/MLINKCHECK-22

Linkcheck reports 302 Found on link that is redirected to itself.
https://issues.apache.org/jira/browse/MLINKCHECK-23

Links on plugins.html and plugin-management.html are redirected
https://issues.apache.org/jira/browse/MPIR-331

Maven site plugin generates sonar.html page with redirection.
https://issues.apache.org/jira/browse/MSITE-749

[Report](http://mezk.github.io/linkcheck/linkcheck.html) problematic links were excluded.

Please, review last commit with excludes.

**Comment by romani** [comment]
you got answers on 2 issues, please update your PR.

**Comment by MEZk** [comment]
@romani 
issue against surefire
https://issues.apache.org/jira/browse/SUREFIRE-1173

sonarqube [issue tracker](http://jira.sonarsource.com/browse/SONAR?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel) is under maintenance.

**Comment by romani** [comment]
> https://issues.apache.org/jira/browse/MSITE-749

is resolved, so it should be referenced in comment

**Comment by MEZk** [comment]
@romani 
Done

**Pull request merged**
