### PR TITLE
Issue #8117: False negative with validateThrows in JavadocMethod

### LINKED ISSUE #8117: False negative with validateThrows in JavadocMethod
While designing additional UTs for #7955 I came across some unexpected behavior.

Check documentation: https://checkstyle.org/config_javadoc.html#JavadocMethod

```
D:\checkstyletest>type config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="severity" value="error"/>
    <module name="TreeWalker">
        <module name="JavadocMethod">
            <property name="validateThrows" value="true"/>
        </module>

    </module>
</module>

D:\checkstyletest>type test\*.java 
class Test {

    /**
     * No throws tags.
     *
     * @param x some input
     */
    void foo(int x) {
        if (x > 0) {
            throw new IllegalArgumentException("bar1"); // violation
        }
        if (x < 0) {
            throw new UnsupportedOperationException("bar2"); // violation?
        }
    }

}

D:\checkstyletest>set RUN_LOCALE="-Duser.language=en -Duser.country=US" 

D:\checkstyletest>java -jar "-Duser.language=en -Duser.country=US" checkstyle-8.31-all.jar -c config.xml test\*.java 
Starting audit...
[ERROR] D:\checkstyletest\test\Test.java:10:23: Expected @throws tag for 'IllegalArgumentException'. [JavadocMethod]
Audit done.

```

Expected: There should be 2 violations, one for `IllegalArgumentException` and another for `UnsupportedOperationException`.

This is a different issue from #7473 which is dealing with false positives. This is a false negative.

---

While I haven't figured out the exact conditions necessary to cause this, I suspect that it is due to a bug in this method, as it is simply not returning all the tokens that are necessary to check:
https://github.com/checkstyle/checkstyle/blob/0294924e4066aaa00080a876ab1268a4c8fd7cb3/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java#L728-L755

I'll start working on a fix once this is approved.

### PR DESCRIPTION
**Pull request by wltan**
Fix #8117 

~~Regression: https://wltan.github.io/checkstyle-reports/2020-04-18/javadocmethod-traverse/~~

Diff Regression projects: https://raw.githubusercontent.com/wltan/checkstyle-reports/master/auto-generate/pr-8213/projects-to-test-on.properties
Diff Regression config: https://raw.githubusercontent.com/wltan/checkstyle-reports/master/auto-generate/pr-8213/my_check.xml

There are violations within Checkstyle's own code that were not detected previously. I have fixed those in a separate commit, so that it is easier to tell apart from the main bug fix.

### CODE REVIEW

**Comment by timurt** [comment]
@wltan Please fix the following wercker erros:

```
[ERROR] src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java:[456,23] (javadoc) JavadocMethod: Expected @throws tag for 'IllegalStateException'.
[ERROR] src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java:[482,23] (javadoc) JavadocMethod: Expected @throws tag for 'IllegalStateException'.
[ERROR] src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java:[518,23] (javadoc) JavadocMethod: Expected @throws tag for 'IllegalStateException'.
[ERROR] src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java:[621,23] (javadoc) JavadocMethod: Expected @throws tag for 'IllegalStateException'.
[ERROR] src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java:[300,27] (javadoc) JavadocMethod: Expected @throws tag for 'IllegalArgumentException'.
[ERROR] src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java:[444,23] (javadoc) JavadocMethod: Expected @throws tag for 'IllegalArgumentException'.
```

**Comment by wltan** [comment]
@timurt I opened https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/816, hope that's the right place for it.

Could you also do a similar check for #8177 and see what the violations are? I believe it is facing the same problem as well.

**Comment by timurt** [comment]
@wltan 
> Could you also do a similar check for #8177 and see what the violations are? I believe it is facing the same problem as well. Thanks!

Access to `Travis CI`, `Appveyor` and `CircleCi` reports is open, so you can open failing CI and see logs

**Comment by wltan** [comment]
> Access to `Travis CI`, `Appveyor` and `CircleCi` reports is open, so you can open failing CI and see logs

@timurt Sorry, there were other CI failures due to #8002 merging. I've fixed them and it's back to a wercker failure which I cannot view.

**Comment by rnveach** [comment]
wercker is:
````
NoErrorTest - contribution
[INFO] There are 2 errors reported by Checkstyle 8.33-SNAPSHOT with ../../../config/checkstyle_checks.xml ruleset.
[ERROR] src/main/java/com/github/checkstyle/publishers/XdocPublisher.java:[137,23] (javadoc) JavadocMethod: Expected @throws tag for 'IllegalStateException'.
[ERROR] src/main/java/com/github/checkstyle/templates/TemplateProcessor.java:[110,27] (javadoc) JavadocMethod: Expected @throws tag for 'IllegalStateException'.
````

**Comment by wltan** [comment]
> wercker is:
> 
> ```
> NoErrorTest - contribution
> [INFO] There are 2 errors reported by Checkstyle 8.33-SNAPSHOT with ../../../config/checkstyle_checks.xml ruleset.
> [ERROR] src/main/java/com/github/checkstyle/publishers/XdocPublisher.java:[137,23] (javadoc) JavadocMethod: Expected @throws tag for 'IllegalStateException'.
> [ERROR] src/main/java/com/github/checkstyle/templates/TemplateProcessor.java:[110,27] (javadoc) JavadocMethod: Expected @throws tag for 'IllegalStateException'.
> ```

Opened https://github.com/checkstyle/contribution/pull/481

**Comment by romani** [comment]
@wltan , pelase rebase on latest master and please make CI to pass.

**Comment by wltan** [comment]
GitHub, generate report

**Review by pbludov — APPROVED** [review]

**Comment by wltan** [comment]
Fixed a pitest issue where logic was impossible to cover

**Review by strkkk — APPROVED** [review]

**Review by romani — APPROVED** [review]
ok to merge

**Pull request merged**
