### PR TITLE
Issue #6725: aligned javadoc/xdoc for VisibilityModifier

### PR DESCRIPTION
**Pull request by pbludov**
Issue #6725 (part of #5750)

No changes in the code.

### CODE REVIEW

**Comment by romani** [comment]
As sync it ok to merge.

Very strange that there are two rationale sentences.
@pbludov, please share result HTML rendering for documentation if you close to keyboard

**Comment by pbludov** [comment]
> Very strange that there are two rationale sentences.
> @pbludov, please share result HTML rendering for documentation if you close to keyboard

I need more time for this check. Here again the case when the documentation should not just be aligned, but completely rewritten.

**Comment by pbludov** [comment]
> please share result HTML rendering for documentation if you close to keyboard

Master
--------
old-desc
old-props

Patch
------
desc-new
props-new

**Comment by pbludov** [comment]
@rnveach please review

**Comment by rnveach** [comment]
> documentation should not just be aligned, but completely rewritten.

Are we going to treat this PR as a rewrite and fix it up more if needed?

> Very strange that there are two rationale sentences.

The 2 separate rationales are still there.

**Comment by romani** [comment]
in such updates we should not rewrite docs, lets keep it atomic to just technical formatting/sync.

**Pull request merged**
