### PR TITLE
Issue #6723: new check: LeadingAsteriskAlignCheck

### LINKED ISSUE #6723: new check: LeadingAsteriskAlignCheck
Checks that the leading asterisk on each line is vertically aligned.

It checks for vertical alignment of the leading asterisk, it ensures that the leading asterisk is vertically aligned properly under the first `*` of the starting javadoc block ( /** ). The Check also ensures the alignment of the ending block of the javadoc ( */ ). The ending block's `*` should be aligned vertically under the first `*` of `/**`.

Example:

```java
/**
 * properly aligned asterisk
 */
```

Violation example:

```java
/**
* // violation
  *  // violation
        * // violation
*/ // violation
``` 

If there is no leading asterisk for a line then that line will be ignored. If there is text before the `*/` then alignment for it will also be ignored. There is already a Check which checks for [missing leading asterisk](https://checkstyle.sourceforge.io/checks/javadoc/javadocmissingleadingasterisk.html) in javadoc. You have also suggested to ignore the line which does not contain leading asterisk, [here](https://github.com/checkstyle/checkstyle/issues/6723#issuecomment-493951547):

> We would just have to look for the first * starting the line and ignore the line if it's first character is not * and is a non-whitespace character.

Example:

```java
/**
          There is no leading asterisk,
So this will not cause error */
```

If there is a leading asterisk at last line i.e. the line containing the ending block ( */ ) then the leading asterisk's alignment will be considered.

Example:

```java
/**
 *
 * the leading asterisk is aligned properly, no error */

/**
 *
     * the leading asterisk is not aligned properly, will cause an error */
```

========

**Old Ideas:**

* property `align`: `left` for r-shaped comments, `right` for 1-shaped comments

*  align=left (default)
```
/**
 * OK (asterisk's column == left asterisk's column from `/**` )
   Missing asterisk ignored
 ** violation
  * violation
* violation
     * violation
 */
```
*  align=right
```
/**
  * OK (asterisk's column == right asterisk's column from `/**` )
   Missing asterisk ignored
 ** violation
 * violation
* violation
     * violation
 */

### PR DESCRIPTION
**Pull request by bossever**
Closes #6723 
Work in progress.

### CODE REVIEW

**Comment by bossever** [comment]
@pbludov @rnveach @romani 
Implementation of this check has started getting very complicated due to inclusion of tab character support. Please advise on whether I should drop tab support, or continue to implement it as mentioned in https://github.com/checkstyle/checkstyle/issues/6723#issuecomment-831916856

**Comment by rnveach** [comment]
@bossever do you still plan to continue? I would work on what is easier in this case, which is probably without tabs, and then we can go from there.

**Comment by bossever** [comment]
@rnveach  The check is almost finished, and works fine without tab support. I will drop it as you've suggested. I'll try to finish it over the weekend and commit soon.

**Comment by rnveach** [comment]
@bossever Do you still plan to finish this?

**Comment by bossever** [comment]
@rnveach 
Sorry for the delay, but I'm having some issues with my local setup, so I haven't been able to resume work on this yet.

**Comment by rnveach** [comment]
@bossever ping

**Comment by rnveach** [comment]
@bossever ping. Do you still plan to work on this?

**Comment by nmancus1** [comment]
We have lost contact with author, anyone is welcome to reuse code in PR to solve issue.

**Pull request closed without merging**
