### PR TITLE
Issue #11727: Include CDG Accelerator Plugin to boost pitest performance

### LINKED ISSUE #11727: Include CDG Accelerator Plugin to boost pitest performance
Pitest takes a significant amount of time to execute in the CI, there are ways in which this time can be improved. Fast feedback form CI will be important in long run and will be super important for this summer's project.

The CDG Accelerator Plugin or the JUnit 5 Accelerator Plugin claims to improves mutation test performance by reducing the overhead in running tests that use a limited set of JUnit Jupiter features. Tests that use only these features will run more quickly, tests that use features outside this set will be executed as normal.

See https://docs.arcmutate.com/docs/accelerator.html#eligible-tests section for the eligible tests.

A license needs to be acquired in order to use the plugin, it is free for open-source projects.
See https://www.arcmutate.com/pricing/ for more details.

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Resolves #11727 

---

### key
```diff
+ decreased execution time
- increased execution time
```

---

Compared with https://github.com/checkstyle/checkstyle/pull/11866

Run with accelerator: https://github.com/checkstyle/checkstyle/actions/runs/2640881429
Run without accelerator (#11866): https://github.com/checkstyle/checkstyle/actions/runs/2636912598
Run without licence: https://github.com/checkstyle/checkstyle/actions/runs/2641406919

```diff
@@ Profile                           New time               Previous time @@

+  pitest-annotation                 1m 44s                 2m 13s 
+  pitest-ant                        1m 42s                 1m 51s 
+  pitest-api                        2m 50s                 4m 30s 
+  pitest-blocks                     1m 54s                 3m 35s 
+  pitest-coding-1                   5m 58s                 6m 38s 
+  pitest-coding-2                   4m 7s                  6m 37s 
+  pitest-coding-require-this-check  15m 36s                16m 35s
+  pitest-common                     7m 32s                 7m 50s 
+  pitest-common-2                   4m 40s                 8m 23s 
+  pitest-design                     1m 54s                 3m 36s 
+  pitest-filters                    2m 44s                 3m 9s  
+  pitest-header                     2m 5s                  2m 26s 
+  pitest-imports                    2m 42s                 3m 43s 
+  pitest-indentation                4m 59s                 11m 36s
+  pitest-javadoc                    5m 43s                 10m 28s
+  pitest-main                       1m 49s                 3m 34s 
+  pitest-metrics                    1m 42s                 2m 24s 
+  pitest-misc                       3m 13s                 4m 21s 
+  pitest-modifier                   2m 39s                 2m 51s 
+  pitest-naming                     2m 21s                 4m 9s  
+  pitest-packagenamesloader         1m 7s                  1m 45s 
+  pitest-regexp                     2m 29s                 3m 28s 
+  pitest-sizes                      1m 57s                 3m 23s 
+  pitest-tree-walker                2m 51s                 4m 22s 
+  pitest-utils                      3m 17s                 6m 12s 
+  pitest-whitespace                 3m 9s                  3m 52s 
+  pitest-xpath                      4m 38s                 13m 36s
+  pitest-java-ast-visitor           3m 15s                 5m 24s 
```

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
Compared with https://github.com/checkstyle/checkstyle/pull/11866
### key
```diff
+ decreased execution time
- increased execution time
```
```diff
@@ Profile                           New time               Previous time @@

+  pitest-annotation                 1m 44s                 2m 13s 
+  pitest-ant                        1m 42s                 1m 51s 
+  pitest-api                        2m 50s                 4m 30s 
+  pitest-blocks                     1m 54s                 3m 35s 
+  pitest-coding-1                   5m 58s                 6m 38s 
+  pitest-coding-2                   4m 7s                  6m 37s 
+  pitest-coding-require-this-check  15m 36s                16m 35s
+  pitest-common                     7m 32s                 7m 50s 
+  pitest-common-2                   4m 40s                 8m 23s 
+  pitest-design                     1m 54s                 3m 36s 
+  pitest-filters                    2m 44s                 3m 9s  
+  pitest-header                     2m 5s                  2m 26s 
+  pitest-imports                    2m 42s                 3m 43s 
+  pitest-indentation                4m 59s                 11m 36s
+  pitest-javadoc                    5m 43s                 10m 28s
+  pitest-main                       1m 49s                 3m 34s 
+  pitest-metrics                    1m 42s                 2m 24s 
+  pitest-misc                       3m 13s                 4m 21s 
+  pitest-modifier                   2m 39s                 2m 51s 
+  pitest-naming                     2m 21s                 4m 9s  
+  pitest-packagenamesloader         1m 7s                  1m 45s 
+  pitest-regexp                     2m 29s                 3m 28s 
+  pitest-sizes                      1m 57s                 3m 23s 
+  pitest-tree-walker                2m 51s                 4m 22s 
+  pitest-utils                      3m 17s                 6m 12s 
+  pitest-whitespace                 3m 9s                  3m 52s 
+  pitest-xpath                      4m 38s                 13m 36s
+  pitest-java-ast-visitor           3m 15s                 5m 24s 
```

**Comment by romani** [comment]
pitest-annotation is 59s - https://github.com/checkstyle/checkstyle/runs/7264372519?check_suite_focus=true but in your report it is 1.44 .
do you provide numbers from your local execution ?

it make sense to do comparison of Github Action execution, as it will run it all the time.

**Comment by Vyom-Yadav** [comment]
> pitest-annotation is 59s - https://github.com/checkstyle/checkstyle/runs/7264372519?check_suite_focus=true but in your report it is 1.44 . do you provide numbers from your local execution ?
> 
> it make sense to do comparison of Github Action execution, as it will run it all the time.

I provided the total execution time, not just the time of generating the report. Basically, it was easier to copy from https://github.com/checkstyle/checkstyle/actions/runs/2641420843/usage rather than manually typing every step execution time.

**Comment by Vyom-Yadav** [comment]
> it would be awesome to make one more bar at https://docs.arcmutate.com/.
> We can try just for fun make single profile and run it on local.
> Or we can measure how much build takes time before pitest execution and reduce this time from each launch and sum up "pure" pitest execution.
> as we have this number, we can share it back to arcmutate, to let them be proud of their project.

Yes, of course, I will make 2 PRs, both with a single profile, that runs the complete pitest (ant, coding, ....). One with the accelerator plugin and the other without it, then we can compare the time and send the report to arcmutate. They are doing amazing work for the open-source community.

**Comment by romani** [comment]
>  I will make 2 PRs

be careful with this .... last time we did pitest as single run .... it took 12 hours to pass. I am not sure if same bad will be now, but be careful, run on local first.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/runs/7264372538?check_suite_focus=true 1m run.

if we spend 20 seconds on start/finish . and from 40 secnds of mvn execution, about 10 goes to compilation. So we spend 50% on non-pistest ...... it is time to rethink split of pitest execution and make them to run for ~5 minutes to spedn more on pitest rather then start/finish

**Comment by nick-mancuso** [comment]
> it would be awesome to make one more bar at https://docs.arcmutate.com/.

Agreed, but let's just create an issue on this, and come back to it after we use this plugin for awhile to let us gain some experience with the plugin and allow our new pitest execution/ report analysis to gain some maturity.

> if we spend 20 seconds on start/finish . and from 40 secnds of mvn execution, about 10 goes to compilation. So we spend 50% on non-pistest ...... it is time to rethink split of pitest execution and make them to run for ~5 minutes to spedn more on pitest rather then start/finish

Agreed, we can probably combine a few quicker profiles, @Vyom-Yadav let's create an issue on this and think of some logical grouping.

**Review by romani — APPROVED** [review]
Ok to merge, to speedup CI now and make counts and report later on

**Review by nick-mancuso — APPROVED** [review]
British spelling of `licence` vs American spelling of `license` is OK for all changes in this PR, since this spelling is consistent with the plugin's documentation.

**Pull request merged**
