### PR TITLE
Issue #15380: documentation for regression-report.yml workflow

### PR DESCRIPTION
**Pull request by romani**
Issue #15380

### CODE REVIEW

**Comment by romani** [comment]
conflict should be ignored in review as I am just changing location of file, no functional changes.

**Comment by relentless-pursuit** [comment]
LGTM

**Review by relentless-pursuit — APPROVED** [review]
LGTM. I just had one suggestion to simplify this:
`Configure links to configs in PR description as described at` to something like `Add the links of the config files in the PR description as described at`

**Comment by romani** [comment]
thanks a lot, suggestion is applied.

**Comment by romani** [comment]
@nrmancuso , 
I merged this PR to let all other changes to be based on new workflow location.
please review this PR and leave comments, I will followup on your review in new PR.

**Pull request merged**
