### PR TITLE
Issue #3902: Fixed formatting issue in documentation

### PR DESCRIPTION
**Pull request by sagar-shah94**
Issue #3902

### CODE REVIEW

**Comment by sagar-shah94** [comment]
At every other places formatting was fine but in this source tag only issue was so it is better if we add p tag at that place only but if we apply css then it will be applied in every source tag which is not required in every source tag pre tag is rendered so we require pre tag at other places.

**Comment by romani** [comment]
Your change is not a fix. Fix by html tags even better than CSS, but it should work.
screenshot-source-in-p

**Comment by sagar-shah94** [comment]
@romani applied css please verify and approve, I have already tested in chrome and firefox.

**Comment by rnveach** [comment]
@sagar-shah94 
> it is better if we add p tag at that place only

Why if this can be an issue anywhere? If you zoom in enough on any source tag, it will go outside the bounds.
What is the negativity of applying a fix to all sources regardless of if they go out or not?

If we can apply CSS to `p` tag inside one source, why won't it work if we apply it directly to the `source` tag?

**Comment by romani** [comment]
> If we can apply CSS to p tag inside one source, why won't it work if we apply it directly to the source tag?

`source` tag is tag of xdoc not a html. I am not sure how xdoc processor will process it.
@sagar-shah94, please try and give us details on how it works.

> What is the negativity of applying a fix to all sources regardless of if they go out or not?

lets test solution on one tag only, before applying to all. But as all agree on solution, it should be applied to all `source` tags.

**Comment by rnveach** [comment]
@sagar-shah94 ping

**Comment by sagar-shah94** [comment]
@rnveach Sir i searched about this issue , we can use javascript to add css to next child tag of all source tag.so css will be applied in every next child tag of source.
What do you suggest?Is it good idea to do that?

**Comment by romani** [comment]
if that is not possible to be done by CSS or tags I recommend to drop this issue.
All Javascript attempts will only overcomplicate website code.

**Comment by rnveach** [comment]
https://www.w3schools.com/tags/tag_p.asp

> Default CSS Settings
> Most browsers will display the <p> element with the following default values:
> p {
>    display: block;
>    margin-top: 1em;
>    margin-bottom: 1em;
>    margin-left: 0;
>    margin-right: 0;
> }

If this is accurate, then we should be able to apply this type of CSS along with @sagar-shah94 's current changes to the `source` tag and be fixed everywhere. Just looking at the above, the most likely fix needed is `display: block;`.

Current `<source>` tag in xdoc is converted in site to:
````
<div class="source">
<pre>[ERROR:0] Javadoc comment at column 1 has parse error. Missed HTML close tag 'audio'. Sometimes it means that close tag missed for one of previous tags.</pre>
</div>
````

So final CSS needs to be directed at `div.source pre`.
@sagar-shah94 Have you tested something like this?

**Comment by Vladlis** [comment]
@sagar-shah94 
1) CI is failing, please fix
2) please share site generated after your changes on github pages

**Pull request closed without merging**
