### PR TITLE
Issue #5139: Restored values of constants in 'JavadocTokenTypes' to that of checkstyle-8.2

### PR DESCRIPTION
**Pull request by ps-sp**
Issue #5139: Restored values of constants in 'JavadocTokenTypes' to that of checkstyle-8.2

### CODE REVIEW

**Comment by ps-sp** [comment]
tokens `DOT` and `CLASS` are not utilized and not even provided in `JavadocTokenTypes`. They have been added back just to restore the older token values.

**Comment by ps-sp** [comment]
Also, some public final fields in `JavadocParser` are different from what they were in checkstyle-8.1 (like `Char11`) but I hope that wouldn't be a problem since they are not made available in `JavadocTokenTypes`.

**Comment by ps-sp** [comment]
@romani @Vladlis Please have a look. Thanks

**Comment by romani** [comment]
diff looks good:
image
commands:
```
git checkout checkstyle-8.1 
mvn clean compile
cp target/generated-sources/antlr/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.java /var/tmp/JavadocParser-8.1.java
git checkout master
./.ci/fast-forward-merge.sh ps-sp issue_5139
mvn clean compile
meld /var/tmp/JavadocParser-8.1.java target/generated-sources/antlr/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.java
```

@rnveach , @Vladlis , please approve PR for merge.

**Comment by ps-sp** [comment]
@rnveach 

I had tried adding a similar test https://github.com/checkstyle/checkstyle/pull/5204#issuecomment-337680532. There were some conflicts with cobertura.

**Comment by rnveach** [comment]
@ps-sp I wasn't involved in that PR as I was on vacation.
I was ableto reproduce the problem and the extra field is `__cobertura_counters` which cobertura added.

We could just drop off anything that starts with `_`. This should fix the problem.

**Comment by ps-sp** [comment]
@rnveach 
Ok got it. Thanks :). 
Separate PR for that test though, right ? Should an issue be created ?

**Comment by rnveach** [comment]
@ps-sp another PR is fine. I am fine with a PR alone with the PR number in the commit message.

**Pull request merged**
