### PR TITLE
Issue #2603: add allowEmptyLambda parameter to WhitespaceAroundCheck

### PR DESCRIPTION
**Pull request by liscju**

### CODE REVIEW

**Comment by romani** [comment]
1)
> InputAllowEmptyLambdaExpressions

please add comment at the top of file that it is "java8" related, see other files for example.

2) Please add UTs case with non empty lambda too.

**Comment by liscju** [comment]
1) DONE - added java8 comment
2) Added non empty lambdas to InputAllowEmptyLambdaExpressions file, should i make another unit test to explicitly state that non empty lambdas are always allowed?

**Comment by romani** [comment]
>  should i make another unit test to explicitly state that non empty lambdas are always allowed? 

current tests are ok.


1) 
Please remove println and use smth else , reason - https://github.com/checkstyle/checkstyle/issues/2541

2)
please add cases:
```
Runnable noop = () -> {;};
Runnable noop = () -> {new Integer();};
```

**Comment by liscju** [comment]
1) DONE, changed to int x = 10
2) DONE, test cases exposed bug in isEmptyBlock private method, fix added in first commit

**Comment by romani** [comment]
1)
>  fix added in first commit

please reword message of this commit and make ref to issue. In Issue please make a reference to this PR (unfortunately github does not do this automatically). This will let us track reason of changes. "minor:" is not ok.

2)
> fixes isEmptyBlock in WhitespaceAroundCheck which recognised all RCURLY ast as empty

and now I have to demand from you html reports to prove that we do not have regression.
please use https://github.com/checkstyle/contribution/tree/master/checkstyle-tester , attention to https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L29 (as all other project most likely does not have lambda at all). 
Please generate report BEFORE and AFTER your fix, use https://github.com/attatrol/ahsm to generate compact diff report. 
Please recheck results yourself (I expect almost no changes in behaviour).
Please share diff-report online.

**Comment by liscju** [comment]
@romani 
>please reword message of this commit and make ref to issue. In Issue please make a reference to this PR (unfortunately github does not do this automatically). This will let us track reason of changes. "minor:" is not ok. You can even merge such commits together.

I split commits because i think it is easier to review commits when changes to current source code and codes adding new fuctionality are separated - but i have no idea how commits messages that are preparing current "source code" for new functionality should look like. Should it be sth like "PR 2757: ...." ? Or by default in checkstyle such commits should be sent as one big commit?

**Comment by romani** [comment]
> I split commits because i think it is easier to review commits when changes to current source code and codes adding new fuctionality are separated

yes, it is better, but need to describe this change , "minor" is not ok. If this is an issue, lets create separate PR or issue and provide full description of it and test that cover it. That would be ideal.

> Should it be sth like "PR 2757: ...." ?

We have format "Pull #2657: message message ....." but this PR description should contain of problem, and input file on how to reproduce a problem. Test driven development.

> Or by default in checkstyle such commits should be sent as one big commit?

We do not have very strict rules there. If another problem is found during current issue resolving - we usually combine commits. We do split(to separate issue) only then problem is big and could be done separately.
I recommend you to merge commits as your changes are required for LAMBDA implementation. If smb will question your update, he will see what UTs he need to conform with.

**Comment by liscju** [comment]
@romani:

>and now I have to demand from you html reports to prove that we do not have regression.
please use https://github.com/checkstyle/contribution/tree/master/checkstyle-tester , attention to https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L29 (as all other project most likely does not have lambda at all). 
Please generate report BEFORE and AFTER your fix, use https://github.com/attatrol/ahsm to generate compact diff report. 
Please recheck results yourself (I expect almost no changes in behaviour).
Please share diff-report online.

DONE for all projects that are marked as having lot of lambda expressions in https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L29 , the diff of result is on http://liscju.github.io/issue2603/diffresult/checkstyle_merged.html, before - http://liscju.github.io/issue2603/before/site/checkstyle.html , after - http://liscju.github.io/issue2603/after/site/checkstyle.html

> We do not have very strict rules there. If another problem is found during current issue resolving - we usually combine commits. We do split(to separate issue) only then problem is big and could be done separately.
I recommend you to merge commits as your changes are required for LAMBDA implementation. If smb will question your update, he will see what UTs he need to conform with.

Ok, i merged commits

**Comment by romani** [comment]
merged as FF, thanks a lot!

**Pull request closed without merging**
