### PR TITLE
Issue #7747: Update AbstractChecks to log DetailAST - MissingJavadocType

### PR DESCRIPTION
**Pull request by jokowncode**
Fixes Issue #7747
Update AbstractChecks to log DetailAST - MissingJavadocType

### CODE REVIEW

**Comment by rnveach** [comment]
@jokowncode please provide us regression. https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#checkstyle-tester

**Comment by jokowncode** [comment]
@rnveach 
When I was using checkstyle-tester, the following error occurred：
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed: For artifact {null:null:null:jar}: The groupId cannot be empty. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed: For artifact {null:null:null:jar}: The groupId cannot be empty.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```
But groupId exists.So can you help me solve this problem? Thank you.

**Comment by rnveach** [comment]
Are you working with the latest contribution? What command did you use to execute regression?

**Comment by jokowncode** [comment]
@rnveach Yes. The command is
```
groovy diff.groovy -r /d/checkstyle/clone6/checkstyle -b master -p missingjavadoc-gsoc -c my_check.xml -l projects-to-test-on.properties
```

**Comment by rnveach** [comment]
Please also provide console output.

> /d/checkstyle/clone6/checkstyle

Are you on linux or Windows?

**Comment by jokowncode** [comment]
@rnveach In windows, MINGW64
[output.txt](https://github.com/checkstyle/checkstyle/files/4365436/output.txt)

**Comment by rnveach** [comment]
> MINGW64

MINGW should not be needed for diff.groovy. It is complaint with Windows but you will need the command lines programs as part of the classpath like groovy, maven, and git.

**Comment by rnveach** [comment]
Also your branch is out of date and should rebase on the latest master.

**Comment by jokowncode** [comment]
> you will need the command lines programs as part of the classpath
I checked the environment variables, and I've already matched them. Then I tried to run it with cmd, but the result was the same.

**Comment by romani** [comment]
@jokowncode , please rebase to resolve conflicts.
Do you still have problems with diff report execution, if so it might be easier to install Linux in Virtualbox or similar too and generate it in linux.

**Comment by pbludov** [comment]
Fixed in https://github.com/checkstyle/checkstyle/pull/8295

**Pull request closed without merging**
