### PR TITLE
Issue #1566: MagicNumber violations fixed

### PR DESCRIPTION
**Pull request by rdiachenko**
Violations fixed:
- MagicNumber 'X' is a magic number.

### CODE REVIEW

**Comment by romani** [comment]
That is not a solution, that check can not be applied to Gui code at all, at any project -suppression should be used as in our config.

**Comment by rdiachenko** [comment]
@romani Why this check can not be applied to Gui? Please provide some arguments.

**Comment by mkordas** [comment]
@rdiachenko :+1: - I don't see any reason why GUI code should have different standards than other code. For me code after your changes is more readable.

**Comment by romani** [comment]
@rdiachenko , please confirm that your question is actual , or do not remmember to whom I explain that few days ago to you or @baratali .

@baratali , can you step in and explain ?  If you fail to explain, most likely I we need to have a conf call to discuss that.

**Comment by baratali** [comment]
@romani, as I remember, we discussed constants in GUI-related classes.
In GUI code you always need to specify height, weight, columns number, lines number, etc. And if you start to define all these values as constants there will be dozens of confusing constants that are used only once.
But @rdiachenko use local variables for this purporse (which is not bad idea, I think).

**Comment by rdiachenko** [comment]
@romani my question is still actual, we didn't discuss with you anything about this case

**Comment by mkordas** [comment]
Guys, on [Wikipedia](https://en.wikipedia.org/wiki/Magic_number_(programming)#Unnamed_numerical_constants) there are multiple pros of extracting magic numbers to constants and IMO some of them apply also to GUI code:
* It is easier to read and understand. A programmer reading the first example might wonder, What does the number 52 mean here? Why 52? The programmer might infer the meaning after reading the code carefully, but it is not obvious.
* The declarations of "magic number" variables are placed together, usually at the top of a function or file, facilitating their review and change.

Moreover keeping them in constants support extension in the future if we wanted to create similar components with the same dimensions.

As a side note - hardcoding dimensions `frame.setSize(1500, 800);` is bad practice itself. The dimensions should be rather calculated based on available screen resolution...

**Comment by romani** [comment]
ok, that is sad that even baratali did not get an idea.
I am pretty firm on this topic , I will call each of you when I come back from vacation. 
We will discuss that in detail and examples.

@sabaka , please share your opinion on this issue too.

PS: fixing that problem for Checkstyle code is not a big damage for code, but by our code we should show others how to use Checkstyle and where that line between following the rule and suppressions. In real GUI code usage of MagicNumber is a disaster.

**Comment by sabaka** [comment]
As for me, we should rewrite our gui and avoid approaches like this one :)
But now: in case of switches - I agree with others. It's easier to read constants, then numbers.
But I think, if we have something like this: ``frame.setSize(1500, 800);`` and if we don't process window size, we can leave it. I mean it's bad, but height and width will not help, if we set them right above.

**Comment by mkordas** [comment]
@sabaka, do you always remember which is first parameter - width or height? :)

**Comment by sabaka** [comment]
@mkordas I don't, but usually you can check it same way, as Ruslan did before naming numbers.
I don't thing it's good way, but not as bad as set frame size 1500*800, when lots of laptops have resolution 1376*768. I'm sure we can avoid this numbers, but not like this.

**Comment by romani** [comment]
Cases with "switch" should be redone to use inner enums.
Other cases with simple naming width/height by variable is not acceptable. In our code is not damaging as scale is minimal, but we could use waiver option of MagicNumber to skip violations on arguments of method

**Pull request closed without merging**
