### PR TITLE
Issue #157: fix java grammar for unicode escape

### PR DESCRIPTION
**Pull request by rnveach**
Fixed grammar for '\u005C\uXXXX' and added 2 test cases for the issue.

### CODE REVIEW

**Comment by romani** [comment]
@sabaka , can you review that PR ?
from my point it looks ok.

**Comment by sabaka** [comment]
Sorry, I don't remember why we don't have just a sequence of unicode characters in grammar. :(
Now it looks a bit weird (after long time without grammars), that we have subrule, but we have lots of such cases in grammar, so if it works fine on real sources - it's ok for me too.

**Comment by rnveach** [comment]
@romani I think we are good to go.

**Comment by romani** [comment]
to merge that PR , I need prove that we word fine on real projects that have such escapes. UTs is not enough.

@rnveach , can you find a project that do have that in code and generate HTML report by checkstyle-tester to prove that all works fine.

**Comment by rnveach** [comment]
@romani 
HTML Report: http://rnveach.github.io/checkstyle/checkstyle.html
Repository: unistroke-mozc
File with unicode case: org/mozc/android/inputmethod/japanese/SymbolData.java line 74

**Comment by mkordas** [comment]
Thanks @rnveach, report looks OK. @romani, are we good to merge?

**Comment by romani** [comment]
1) 
> 	Number of public methods is 134 (max allowed is 100).

Please make limit of 1000. 

2)
All unicode is simple and typical, like in UTs. We need a project that use unicode at String values (not a simple cases). Do you know projects like that ?

**Comment by rnveach** [comment]
@romani 
1) Done.
2) Refreshed. Is this case better?

**Comment by romani** [comment]
Awesome report.

we might need to add lucene to our testing project set, it has non conventional sources.

I will merge you tomorrow.

**Comment by romani** [comment]
please do last update:
1)
extend UTs Input with unicode in String: only unicode, few unicode  at the beginig rest is simple chars, ....(all variants)....
Example: http://rnveach.github.io/checkstyle/xref/test/org/apache/lucene/analysis/ja/TestJapaneseAnalyzer.html#L205

**Comment by rnveach** [comment]
@romani Everything is updated.
Are new tests enough?

**Comment by romani** [comment]
codecov could be ignored.

@mkordas , pelase recheck teamcity (violations are not shown again).

**Comment by mkordas** [comment]
@rnveach, @romani, just rebase over latest code and issues on TC should be gone

**Comment by romani** [comment]
Merged as ff

**Pull request closed without merging**
