### PR TITLE
minor: test

### PR DESCRIPTION
**Pull request by rnveach**
Test only. Looking at travis.

### CODE REVIEW

**Comment by rnveach** [comment]
Non-main sevntu fix has an issue here.
https://checkstyle.semaphoreci.com/jobs/b5111b2e-81b7-4a62-b1f3-acb6a9ce47ef#L661
> Unable to create Root Module: config {https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-10.5.1-SNAPSHOT/config/checkstyle_non_main_files_checks.xml}

**Comment by rnveach** [comment]
@romani It is up to you if we want to enforce this Newline config. This was in response to the `\r\n` we found in contribution.

The only reason why I am not closing this, is we are and have gotten reports of Windows users still need `core.autocrlf` to be enabled though we went through an issue saying its not needed anymore. Gitattributes fixed it for me as shown by my changes in contribution, but it seems there some windows utilities who don't enforce it and got by `autorcrlf` instead. Current user in gitter reported they used git bash.

Current files being reported by CI are known different line ending files. Those not reported are already being suppressed, so we have partial "fixes" without this it seems.

https://app.circleci.com/pipelines/github/checkstyle/checkstyle/16558/workflows/51b88428-94c4-4443-9baf-ad5fa23763f1/jobs/215060?invite=true#step-103-155
> InputAntlr4AstRegressionEmbeddedBlockComments.java

(Linux User)
https://github.com/checkstyle/checkstyle/blob/5a27d12e76a27894e43dae1834da40a154ef6523/src/test/resources/com/puppycrawl/tools/checkstyle/grammar/antlr4/InputAntlr4AstRegressionEmbeddedBlockComments.java#L3
This is CR file.

https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/45599600/job/lbelimewg6ihorr1#L190
> idea_inspection.bat
> InputXpathQueryGeneratorTextBlockCrlf.java
> InputAntlr4AstRegressionEmbeddedBlockComments.java

(Windows user)
Batch need to be `\r\n`. `InputXpathQueryGeneratorTextBlockCrlf` is `\r\n` for testing.

**Comment by romani** [comment]
We need rebase on this PR 
We can try to merge this PR and get feedback from users one more time.

**Comment by nrmancuso** [comment]
Looks like we lost interest in pursuit of this PR, I am going to close it. We can reopen this PR one day in the future or allow some contributor to reuse the changes here.


If we need to make a related issue for what's going on here, please do.

**Pull request closed without merging**
