### PR TITLE
Issue #2428: Remove commons-lang3 dependency.

### PR DESCRIPTION
**Pull request by kaj**
#2428 . 
A new attempt.  I hope the build checkers will like it better this time.

### CODE REVIEW

**Comment by romani** [comment]
ok, first step is done to clearly see what is required to be redone to avoid apache commons

lets reuse guava as much as possible

1)
> `public static <T> T defaultIfNull(final T object, final T defaultValue) {`

http://stackoverflow.com/a/8040294/1015848

2)
> public static boolean isNotBlank(String str) {

we use this method only ones, please remove this method and use `!isBlank`

3)
> `public static String join(final Iterator<?> iterator, final String separator) {`

can we use http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Joiner.html ?

4)
> private static String getSystemProperty(final String property) {

it is forbidden to use `System.err.println` . The only way out is to swallow exception silently.
We use this method only in UTs, lets create TestsUtils class in test area and use it only there.

5)
> public static int[] toPrimitive(Integer[] array) {

This method is used only in one place, and in Chekstyle it is called only ones during runtime.
I am ok to change it to reuse guava http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/primitives/Ints.html#toArray%28java.util.Collection%29 even we would need extra conversion to array to collection before usage of it. 
Moving this method to TokenUtils as private method is also good.

6)
> public static boolean isBlank(String str) {

Guava does not have such method, but try to force users to use other methods . 
Can we keep thi method in out Utils but do processing base on Guava utils (with similar performance )?

**Comment by kaj** [comment]
I don't understand how I caused some of the problems the build system is complaining about.  E.g. src\main\java\com\puppycrawl\tools\checkstyle\Checker.java:315:13: Catching 'Exception' is not allowed. [IllegalCatch] where that same catch is present in master?

Thanks for feedback, @romani , I'll try to address your 6 points shortly.

**Comment by kaj** [comment]
@romani 0) please squash all commit on one.

Ok, I'll do that when happy with the other points.  Until then, I'll keep adding small individual commits.

**Comment by romani** [comment]
> I don't understand how I caused some of the problems the build system is complaining about

line numbers are shifted , suppressions base on line numbers are not working.
update line numbers at https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml

**Comment by kaj** [comment]
line numbers are shifted , suppressions base on line numbers are not working.

Ah, thanks for the hint!  :-)

I think I fixed all the problems except number 0 now (and we'll see in a while if the build checkers agree).  Number 4 was fixed simply by not catching the exception. It shouldn't happen, and if it does it will fail the build, which seems right.  Using guave Ints.toArray for number 5 actually made the calling code simpler as well.

**Comment by romani** [comment]
Teamcity should be fixed too: https://teamcity.jetbrains.com/viewLog.html?buildId=721538&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsPullRequest

please squash commits (point "0") to let me do code review while you are fighting with TeamCity.

**Comment by kaj** [comment]
Hm. The issues teamcity is complaining about is that the variable expected has too large scope in methods that look like this:

    @Test
    public void testDefaultConfiguration() throws Exception {
        final DefaultConfiguration checkConfig =
            createCheckConfig(CustomImportOrderCheck.class);
        final String[] expected = CommonUtils.EMPTY_STRING_ARRAY;
    
        createChecker(checkConfig);
        verify(checkConfig, getPath("InputCustomImportOrder.java"), expected);
    }

I don't see how this became worse from the fact that expected comes from CommonUtils instead of ArrayUtils (and in most cases, the line numbers hasn't changed either.  On the other hand, the expected parameter is a varargs parameter.  So I think the good looking solution would be to remove the "expected" variable entirely, like this:

    @Test
    public void testDefaultConfiguration() throws Exception {
        final DefaultConfiguration checkConfig =
            createCheckConfig(CustomImportOrderCheck.class);
    
        createChecker(checkConfig);
        verify(checkConfig, getPath("InputCustomImportOrder.java"));
    }

Thoughts on that, @romani ?  I think it is clearer, but on the other hand, the the existing code explicitly states that it expected nothing (I ask before i change, since there is about 300 tests that I'll change if you agree to this).

**Comment by romani** [comment]
> final String[] expected = CommonUtils.EMPTY_STRING_ARRAY;

we like this approach as it keep all out tests looks the same.
ok, I will take a look at TC violation....., please proceed with other issues.

**Comment by kaj** [comment]
This PR is now a single commit (point 0).  Also, I rebased it on top of other commits to master.

**Comment by romani** [comment]
1)
>
```
        final String[] expected = ArrayUtils.EMPTY_STRING_ARRAY;

        createChecker(checkConfig);
        verify(checkConfig, getPath("InputJavaNCSS.java"), expected);
```

TC is kind of right, as expected variable should declared as close to it first usage as possible/reasonable. Please move `createChecker(checkConfig);` above `final String[] expected`.
It is not clear why this become a problem only now, as you do not touch this code. 
We have no other choice as to resolve it - I can not merge code that fail CI.


2)
>
```
 +     * @since 2.0
+     */
+    public static boolean isBlank(String str) {
```

please remove old javadoc tag `@since`, please make a single point of return/exit from method `isBlank`.

**Comment by kaj** [comment]
1) Strange indeed, but ok.  I fix. `src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheckTest.java` got particularly ugly, but I don't see a way to booth write it nice and clean and have TeamCity accept it.

2) Yes, the since has to go, since it refers a commons version and not a checkstyle version.  Sorry I missed that.  Personally, I think the most readable version of isBlank has tree return statements, but if you prefer a single one I can fix that (I brought it down to two earlier for a CI requirement).

Or actually, I just found there is an implementation of isBlank in guava, instead of `isBlank(string)`, we can do `CharMatcher.WHITESPACE.matchesAllOf(string)`, except that throws NPE rather than returning true if string is null.  So the new implemenatation of isBlank looks like this:

    public static boolean isBlank(String str) {
        return str == null || CharMatcher.WHITESPACE.matchesAllOf(str);
    }

Maybe we should inline that where used instead?  I guess the null check will be redundant and can be removed in most cases, and WHITESPACE can be imported statically, so `isBlank(something)` becomes just `WHITESPACE.matchesAllOf(something)`.

**Comment by kaj** [comment]
Actually, there was only 3 cases where the null check was obviously redundant, and 5 where it should be kept.  Still, I think it's nicer to use WHITESPACE.matchesAllOf even with an extra null check than to keep a utility methods with a rather long javadoc string and three tests ...

So I went ahead and removed the isBlank method from CommonUtils.

**Comment by kaj** [comment]
Apparently, static imports is not considered kosher in this project.  That makes some lines a little longer, but no real difference ...

**Comment by kaj** [comment]
Ah, but inlining the null check made it a separate branch, and so the branch test coverage check fails.  One more thing to fix ...

**Comment by kaj** [comment]
Known problems fixed and updated to upstream master.  Anything else, @romani ?

**Comment by romani** [comment]
Sorry for delay, your PR is too big to review it on the go.

Merged as FF to keep major changed in main repo.

What i do not like and need to be done in separete PR is create isBlank function in our util class. Now Check need to care about null , that is bad distruction from algorithm.

**Comment by kaj** [comment]
No problem.  Thanks for merging!  :-)

**Pull request closed without merging**
