### PR TITLE
Extended newbie guide, issue #606

### PR DESCRIPTION
**Pull request by alexkravin**
According to #606 

Extended newbie guide:

Added instructions of development and debugging via UTs with screenshots, steps for creating PRs

Current version: http://alexkravin.github.io/tutorial/contributing.html

### CODE REVIEW

**Comment by romani** [comment]
1)
> 3. Checkout 

should be on it own line

2)
> 4. Develop the changes:

bad name, remove it or rename

3)
> all images

please make them separated by some space from text and align them to center

4) 
images and text are to close to each other - it is very hard to read.

5) 
> git push origin my-new-check

please make a command line with bigger font size, it should be convenient to read a text

6)
from issue: 
> Eclipse , Netbeans, IDEA

Please make all your text as separate Segment and consider to move Eclipse images and explanation in separate page as we need also instructions for Netbeans and IDEA (please propose a solution on how to host that instructions).

**Comment by alexkravin** [comment]
1) Updated

2) Renamed to "Steps for beginning development"

3) Made separated, but in writing_checks images are not aligned to center and I think it is not necessary.

4) Separated

5) Done

6) This tutorial's extension is now in separate section, I think images showing debug with UTs can be left here, there's no need to add the same image from another IDE as process is the same.
I propose to add instructions to each IDE in text format in writingchecks.html as I have already written, but removed from previous commit.

7) Used this template

Current site: http://alexkravin.github.io/tutorial/contributing.html

**Comment by romani** [comment]
1) that page is UGLY, please make it looks good, please read it by yourself. If that is not convenient to read redo it.

2) 
> Ensure that Git, Java JDK 1.7/8 are installed.

what about java 9 ? refrase that sentence.

3) 
> debug it by putting the breakpoint a

How to run in bebug and how to make a brake point.

4) 
 do not understand reason of picture after "ebug mode to start the debug process"

5) 
> 
right-click on UT (or one of it's test m

after that text ..... trash ... 

6) 
> Beginning development

I think that we need to move that in separate page - too much details ot it, I still do not see design/layout for other IDEs pages.

**Comment by alexkravin** [comment]
Updated

Created separate page for instructions and separate page for each IDE (Eclipse, Netbeans, Idea)

http://alexkravin.github.io/tutorial/index.html

See contributing, beginning development pages

**Comment by romani** [comment]
good,

0) 
> Debug the Check by putting the breakpoint at controversial place

Please make a screen of how you selected an Check in project source tree(we have bunch of code along with Checks) lets focus user to certain location. 

1) 
> Then right-click the corresponding Unit-test file

For all IDEs, please make a picture of context menu(with required selected menu item) and UT location in tree of project sources to let new developers do the same (as they could not know what is UT).

2) Please add IDEs pages to left (navigation) panel. We show all pages there.

**Comment by alexkravin** [comment]
1,2) Added screenshots for each IDE

2) Added pages to the left panel as sub-items of page Beginning Development

http://alexkravin.github.io/tutorial/index.html

**Comment by romani** [comment]
Almost ideal, please redo second image at http://alexkravin.github.io/tutorial/eclipse.html to place root node of project at picture, as you did for other IDEs. User need to understand how to come to that part of tree

**Comment by alexkravin** [comment]
Updated this image:
http://alexkravin.github.io/tutorial/eclipse.html

**Comment by romani** [comment]
Please resolve compilation error on a project and redo a picture

**Comment by alexkravin** [comment]
@romani,
It's not a compilation error, some feature of eclipse or smth like that.

**Comment by romani** [comment]
No matter what is it, it looks like error, we have to have picture with project at good state. In other case user will thins that red icon is OK.

**Comment by alexkravin** [comment]
Ok, I've forced my Eclipse to get rid of this error mark, updated picture.

**Comment by romani** [comment]
please make a pictures for selection on certain Check, screen for code fromthat Check  and then exact UT for selected Check (not any other Test), user should follow your pictures and appear in DEBUG on brake-point.

that is affecting all pictures for all IDEs.

**Comment by alexkravin** [comment]
Updated
http://alexkravin.github.io/tutorial/beginning_development.html

**Comment by romani** [comment]
good, last problems before merge:

> Fork your copy from Checkstyle main project

please put a link to official page how to do that https://help.github.com/articles/fork-a-repo/

> checkstyle/checkstyle.git

please change all appearances with "you_user_name/checkstyle.git" (as you already did at the beginning) and please try to do all steps yourself to recheck that nothing is missed.

**Comment by alexkravin** [comment]
Added link of "how to fork copy"

Updated instruction about project cloning with <b>user_name</b>.
This update was needed at one place

**Comment by romani** [comment]
merged, thanks a lot !!!

**Pull request closed without merging**
