### PR TITLE
Issue #3619: NeedBraces need clear description of allowSingleLineStat…

### PR DESCRIPTION
**Pull request by aayushRedHat**
Related: https://github.com/checkstyle/checkstyle/issues/3619

Diff Regression Config: https://gist.github.com/aayushRedHat/aaceea1c55de2d1341ae11bad9a39b75

### CODE REVIEW

**Comment by rnveach** [comment]
This pr doesn't make sense. Issue is to update documentation but in this pr, code was changed. If there is an issue with check, it needs it's own issue.

**Comment by romani** [comment]
@aayushRedHat , please read https://github.com/checkstyle/checkstyle/issues/3619#issuecomment-1817544760

And explain why you think this is defect I. check not a lack of documentation.

In addition , let generate diff regression report to see how much new violations will appear in real life code.

**Comment by aayushRedHat** [comment]
GitHub, generate report

**Comment by aayushRedHat** [comment]
> @aayushRedHat , please read [#3619 (comment)](https://github.com/checkstyle/checkstyle/issues/3619#issuecomment-1817544760)
> 
> And explain why you think this is defect I. check not a lack of documentation.
> 
> In addition , let generate diff regression report to see how much new violations will appear in real-life code.

Using two statements in a single statement even strictly mentioning in the check  <property name="allowSingleLineStatement" value="true"/> seems like a violating the check.  @romani @rnveach that's why i was raised a PR for this.

**Comment by aayushRedHat** [comment]
> > @aayushRedHat , please read [#3619 (comment)](https://github.com/checkstyle/checkstyle/issues/3619#issuecomment-1817544760)
> > And explain why you think this is defect I. check not a lack of documentation.
> > In addition , let generate diff regression report to see how much new violations will appear in real-life code.
> 
> Using two statements in a single statement even strictly mentioning in the check seems like a violating the check. @romani @rnveach that's why i wraised a PR for this.

@romani Any update

**Comment by romani** [comment]
GitHub, generate report

**Comment by romani** [comment]
We usually do some exception from rules as we see that people like some patterns. Being fanatic on rule is not always work in practice.
It is better for validation module to know about such patterns and skip them.

We need regression diff report to see how frequent such pattern.
As it is referenced in example, it means , it is done on purpose. We can reconsider it, but we need to be prepared that it is desirable behavior, not a defect.

**Comment by romani** [comment]
GitHub, generate website

**Comment by aayushRedHat** [comment]
@romani Can we consider this or Do i need to update the doc to add exceptions statements

**Comment by romani** [comment]
Please update doc

**Comment by aayushRedHat** [comment]
> Please update doc

Closing this PR opening new for updating the doc

**Pull request closed without merging**
