### PR TITLE
Issue #13321: Kill mutation for DetailAstImpl

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for DetailAstImpl

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java

--------

# Mutation 
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L66-L82
and 
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L93-L109

# Explaintaion 
Expanded unmodifiableCollectionUtil class

### CODE REVIEW

**Review by romani — APPROVED** [review]
Ok to merge.

Requesting more reviews just to share awareness, all other such updates will need only single review

**Comment by nrmancuso** [comment]
@romani please share link to discussion on creation of this utility class, I would like to understand why we did this.

**Comment by romani** [comment]
@nrmancuso , you should have all or most details in git blame.
Please look at https://github.com/checkstyle/checkstyle/blob/d6cee1a33536f65f29462d3f97e8f6699f9b1a02/src/main/java/com/puppycrawl/tools/checkstyle/utils/UnmodifiableCollectionUtil.java#L26

https://github.com/checkstyle/checkstyle/pull/13127#discussion_r1225637093

**Comment by romani** [comment]
@rnveach , please glance at this trick to bypass pitest mutation that we can not cover.

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by nrmancuso** [comment]
@Vyom-Yadav please complete review

**Review by Vyom-Yadav — APPROVED** [review]
LGTM! Sorry for the delay.

**Pull request merged**
