### PR TITLE
Issue #9486: updated AST for TokenTypes.LITERAL_NEW

### LINKED ISSUE #9486: update example of AST for TokenTypes.LITERAL_NEW
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_NEW

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
fixes #9486 

Format

Generated Java Doc

Final JavaDoc

> Code used for generating example:
<pre>
<code>
import java.util.ArrayList;
public class MyClass {
     public static void main(String[] args) {
        new ArrayList<>(50);
    }
}
</code>
</pre>

> Output in AST Format:
<pre>
<code>
IMPORT -> import [1:0]
|--DOT -> . [1:16]
|   |--DOT -> . [1:11]
|   |   |--IDENT -> java [1:7]
|   |   `--IDENT -> util [1:12]
|   `--IDENT -> ArrayList [1:17]
`--SEMI -> ; [1:26]
CLASS_DEF -> CLASS_DEF [2:0]
|--MODIFIERS -> MODIFIERS [2:0]
|   `--LITERAL_PUBLIC -> public [2:0]
|--LITERAL_CLASS -> class [2:7]
|--IDENT -> MyClass [2:13]
`--OBJBLOCK -> OBJBLOCK [2:21]
    |--LCURLY -> { [2:21]
    |--METHOD_DEF -> METHOD_DEF [3:5]
    |   |--MODIFIERS -> MODIFIERS [3:5]       
    |   |   |--LITERAL_PUBLIC -> public [3:5] 
    |   |   `--LITERAL_STATIC -> static [3:12]
    |   |--TYPE -> TYPE [3:19]
    |   |   `--LITERAL_VOID -> void [3:19]
    |   |--IDENT -> main [3:24]
    |   |--LPAREN -> ( [3:28]
    |   |--PARAMETERS -> PARAMETERS [3:35]
    |   |   `--PARAMETER_DEF -> PARAMETER_DEF [3:35]
    |   |       |--MODIFIERS -> MODIFIERS [3:35]
    |   |       |--TYPE -> TYPE [3:35]
    |   |       |   `--ARRAY_DECLARATOR -> [ [3:35]
    |   |       |       |--IDENT -> String [3:29]
    |   |       |       `--RBRACK -> ] [3:36]
    |   |       `--IDENT -> args [3:38]
    |   |--RPAREN -> ) [3:42]
    |   `--SLIST -> { [3:44]
    |       |--EXPR -> EXPR [4:8]
    |       |   `--LITERAL_NEW -> new [4:8]
    |       |       |--IDENT -> ArrayList [4:12]
    |       |       |--TYPE_ARGUMENTS -> TYPE_ARGUMENTS [4:21]
    |       |       |   |--GENERIC_START -> < [4:21]
    |       |       |   `--GENERIC_END -> > [4:22]
    |       |       |--LPAREN -> ( [4:23]
    |       |       |--ELIST -> ELIST [4:24]
    |       |       |   `--EXPR -> EXPR [4:24]
    |       |       |       `--NUM_INT -> 50 [4:24]
    |       |       `--RPAREN -> ) [4:26]
    |       |--SEMI -> ; [4:27]
    |       `--RCURLY -> } [5:4]
    `--RCURLY -> } [6:0]
</code>
</pre>

> Expected Java Doc to be Updated:

<pre>
<code>
     * LITERAL_NEW -> new
     *  |--IDENT -> ArrayList
     *  |--TYPE_ARGUMENTS -> TYPE_ARGUMENTS
     *  |   |--GENERIC_START -> <
     *  |   `--GENERIC_END -> >
     *  |--LPAREN -> (
     *  |--ELIST -> ELIST
     *  |       |   `--EXPR -> EXPR
     *  |       |       `--NUM_INT -> 50
     *  `--RPAREN -> )
    </code>
</pre>

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
@pbludov please check my changes and approve for the same.

**Review by AkMo3 — APPROVED** [review]
LGTM

**Review by pbludov — APPROVED** [review]

**Review by timurt — APPROVED** [review]

**Comment by Rahulkhinchi03** [comment]
what are these 2 workflow awaiting approval? @timurt ?

**Comment by timurt** [comment]
@Rahulkhinchi03 merged, thank you for contribution :)

**Pull request merged**
