### PR TITLE
Issue #1296: 'SuppressionsLoader' refactored, UT coverage improved

### PR DESCRIPTION
**Pull request by rdiachenko**
Test coverage improved to 100%.

### CODE REVIEW

**Comment by romani** [comment]
Please explain removal of "check to see if the file is in the cla.." block, please prove that .

**Comment by romani** [comment]
@rdiachenko , please take a look.

**Comment by rdiachenko** [comment]
@romani you are right! We need this block of code. I'll do revert and cover it with UTs.

**Comment by romani** [comment]
please review class that is similar to that, I already did a coverage so you can reuse code in UT

**Comment by rdiachenko** [comment]
@romani I reverted the change and added tests. Please have a look

**Pull request merged**
