### PR TITLE
Issue checkstyle#3110: Removing hard coded messages for PackageObject

### PR DESCRIPTION
**Pull request by HarshtyagiHT**
Issue checkstyle#3110: Removing hard coded messages for PackageObject

### CODE REVIEW

**Comment by rnveach** [comment]
@HarshtyagiHT Please do not close PR just because CI is failing. You can force push the branch with updates and CI will take the appropriate action.
See https://github.com/checkstyle/checkstyle/wiki/PR-rules

**Comment by HarshtyagiHT** [comment]
Sorry about that. I'm not sure why this CI is failing, could you please help me with this.

**Comment by rnveach** [comment]
Did you read item 3 and verify that it all passes on your local?

For CI, you click on the details for each one and looks at the logs to see what it says for failure.
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=12467&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=788
Looking at the log it appears one of the tests is failing. This is part of the run I was talking about above, so all this you can reproduce on your local.

**Comment by HarshtyagiHT** [comment]
Thank you for your response. It is because of the commit message. I have changes it according to the standards but it keeps on adding the new line character at the end. 

image

**Comment by rnveach** [comment]
Do you see the bottom text that says which rule is broken? It is not saying the new line character is an issue.

**Comment by nrmancuso** [comment]
We have lost contact with PR author, anyone is welcome to pick up the changes here and use them to resolve issue.

**Pull request closed without merging**
