### PR TITLE
minor: Update workflows/README.md to let it work for all workflows

### PR DESCRIPTION
**Pull request by romani**
related to https://github.com/checkstyle/checkstyle/issues/15380
We can not use folders due to https://github.com/orgs/community/discussions/18055

### CODE REVIEW

**Comment by romani** [comment]
@nrmancuso , fyi

**Comment by romani** [comment]
@mahfouz72 , fyi.
documentation of that is possible.
https://github.com/checkstyle/checkstyle/blob/master/.github/workflows/README.md

**Comment by mahfouz72** [comment]
Thanks a lot!!

**Comment by mahfouz72** [comment]
https://github.com/checkstyle/checkstyle/blob/5eca53ce31f48b61fae0612a2092815009772b48/.github/workflows/README.md?plain=1#L52-L54

@romani link is broken here.

**Comment by romani** [comment]
@mahfouz72 , fixed, thanks a lot.

**Pull request merged**
