### PR TITLE
Issue #13321: Kill mutation for CheckUtil-8

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13321: Kill mutation for CheckUtil-8

------

# Mutations
https://github.com/checkstyle/checkstyle/blob/bb64c20cbcf6e543b297b6e809f379bd8746b5e7/config/pitest-suppressions/pitest-utils-suppressions.xml#L84-L118
and 
https://github.com/checkstyle/checkstyle/blob/bb64c20cbcf6e543b297b6e809f379bd8746b5e7/config/pitest-suppressions/pitest-utils-suppressions.xml#L129-L163

-----

# Explaintaion 

this method is used for check wether the method is setter or not.
https://github.com/checkstyle/checkstyle/blob/bb64c20cbcf6e543b297b6e809f379bd8746b5e7/src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java#L348
is useless to check and the reason is lets suppose as per pit suggestion we change it as true then after execution 
https://github.com/checkstyle/checkstyle/blob/bb64c20cbcf6e543b297b6e809f379bd8746b5e7/src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java#L355
we are checking the slist's child count and the value of it should be 3 only and it is only possible if there is no return statment 
ex for code 
```
    public void setNumber(final int number) {
        mNumber = number; 
    }
```
and 
```
    public int setNumber2(int num) {
        mNumber = num;
        return num;
    }
```

the ast looks 
```
    |   `--SLIST -> { [20:44]
    |       |--EXPR -> EXPR [21:16]
    |       |   `--ASSIGN -> = [21:16]
    |       |       |--IDENT -> mNumber [21:8]
    |       |       `--IDENT -> number [21:18]
    |       |--SEMI -> ; [21:24]
    |       `--RCURLY -> } [22:4]

```
and 
```
    |   `--SLIST -> { [24:35]
    |       |--EXPR -> EXPR [25:16]
    |       |   `--ASSIGN -> = [25:16]
    |       |       |--IDENT -> mNumber [25:8]
    |       |       `--IDENT -> num [25:18]
    |       |--SEMI -> ; [25:21]
    |       |--LITERAL_RETURN -> return [26:8]
    |       |   |--EXPR -> EXPR [26:15]
    |       |   |   `--IDENT -> num [26:15]
    |       |   `--SEMI -> ; [26:18]
    |       `--RCURLY -> } [27:4]

```

so it is just a double checking

------

# Regression 

Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/eb84bf9_2023201812/reports/diff/index.html

Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/eb84bf9_2023164422/reports/diff/index.html

------

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/e68ff3727846e014d16ab79850e397c9/raw/ed2a46a684de49b6e500e30c1e1a5f867c6c6695/MissingJavadocMethodCheck.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/360a95ed7bb60d7a0956e531199d484c4d6f6617/test-projects.properties
Report label: Regression-2

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
@Kevin222004 , plaase do report2

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by romani** [comment]
```
public void setNumber(final int number) {
        {  mNumber = number;  mNumber++; } 
    }
```

**Comment by Kevin222004** [comment]
@romani https://github.com/checkstyle/checkstyle/pull/13457#issuecomment-1656756973 I tested this in various way 
https://github.com/checkstyle/checkstyle/blob/bb64c20cbcf6e543b297b6e809f379bd8746b5e7/src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java#L357

as per this condition the first child of slist we require as assign 
so if we see the ast
```
    public int setNumber(final int number) {
        mNumber = number;
        {  return mNumber; }
    }
```
of above code
```
    |   `--SLIST -> { [24:43]
    |       |--EXPR -> EXPR [25:16]
    |       |   `--ASSIGN -> = [25:16]
    |       |       |--IDENT -> mNumber [25:8]
    |       |       `--IDENT -> number [25:18]
    |       |--SEMI -> ; [25:24]
    |       |--SLIST -> { [26:8]
    |       |   |--LITERAL_RETURN -> return [26:11]
    |       |   |   |--EXPR -> EXPR [26:18]
    |       |   |   |   `--IDENT -> mNumber [26:18]
    |       |   |   `--SEMI -> ; [26:25]
    |       |   `--RCURLY -> } [26:27]
    |       `--RCURLY -> } [27:4]

```

I think their would not be any case where we ignore the semi token and make the count 3 of  SLIST child

**Review by romani — APPROVED** [review]
You are right.

Ok to merge.

**Comment by romani** [comment]
@Kevin222004 , conflict.

**Comment by Kevin222004** [comment]
Conflict resolved

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by Kevin222004** [comment]
conflict resloved

**Comment by romani** [comment]
@Kevin222004 , please put report links to PR description

**Comment by Kevin222004** [comment]
https://github.com/checkstyle/checkstyle/pull/13457#issuecomment-1666602056 done

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

**Pull request merged**
