### PR TITLE
Solution to wrong variable reported because of name shadowing in Fina…

### PR DESCRIPTION
**Pull request by Bhavik3**
…lLocalVariableCheck. solves #1142

### CODE REVIEW

**Comment by romani** [comment]
1)
> private DetailAST findClassOrMethodInWhichItIsDefined(DetailAST ast)

should be static

2)
> removeVariable(DetailAST ast) 

please move newly created code out of this method(you even can make it as method) and place it before "removeVariable" is called

3)
> private void insertVariable(DetailAST ast)

I know that us not your change, but please move "if (!ast.branchContains(TokenTypes.FINAL)) {" out of it and place it before "insertVariable" is called. "insertVariable"/"removeVariable" should just do insert or remove as it defined in their names (no skip conditions inside).

4)
> final DetailAST astNode1 = findClassOrMethodInWhichItIsDefined(obj);

please use good names for variables


5)
> astNode1.findFirstToken(TokenTypes.IDENT).getText().equals(
+                        astNode2.findFirstToken(TokenTypes.IDENT).getText())

unreadable , make it as "id1.equals(id2)" but with good names.

6) 
please generate HTML reports by "checkstyle-tester" to see that there are no exceptions , and that we did not change in validation smth else. reports before and after fix should be different only by that cases. Please share them in github.io as prove.

**Comment by Bhavik3** [comment]
@romani 
2)
All the changes I have made in removeVariable() method are in between method (not before or after). Then how can I make it happen before or after calling removeVariable()?

Even if I manage to do it. removeVariable is not removing variable that we give as argument (It should remove variable that is given as argument according to method description). Instead, it is removing the variable by its name (e.g. If there are two variable with same name, It will remove first variable doesn't matter where it is defined). So, I think it is good to  make changes in the method (not just for this issue, but to make it work correctly (as description provided) in all cases).

**Comment by romani** [comment]
please apply all other changes and I will take a look to "2)" after that one more time.

**Comment by Bhavik3** [comment]
1)
Done

3)
Done

4)
Done
Name of variable given by me are long but precise. If you think it is not appropriate let me know.

5)
Done

6)
Checkstyle-tester Configuration : https://github.com/Bhavik3/checkstyle-tester/tree/nameShadowing
Checkstyle-tester Report : http://bhavik3.github.io/checkstyle.html

**Comment by romani** [comment]
> identifierOfAst identifierOfObj

1)
> 2)

OK, yes it is ok to keep it as is.

2)
please name the to explain content of them .  What is "class Or Method Of Obj ? "
that variable are for indentifiers of variables one is current other is from scope/stored

currentVariableName , stored(scoped)VaribleName .

Please change names of all other variables. All ofthe nshould get meaningful (sefexplainable) name.

**Comment by romani** [comment]
0) please do not forget to put a comment after you did a fixes, II receive notification only when comment appear

1)
```
                final DetailAST classOrMethodOfStoredVariable =
                    findClassOrMethodInWhichItIsDefined(storedVariable);
                final DetailAST classOrMethodOfCurrentVariable =
                    findClassOrMethodInWhichItIsDefined(ast);

                final String identifierOfStoredVariable =
                    classOrMethodOfStoredVariable.findFirstToken(TokenTypes.IDENT).getText();
                final String identifierOfCurrentVariable =
                    classOrMethodOfCurrentVariable.findFirstToken(TokenTypes.IDENT).getText();

                if (identifierOfStoredVariable.equals(identifierOfCurrentVariable)) {
```

 final change: please make that code as static method isSameVariables(ast, storedVariable) to make removeVariable readable easily.

**Comment by Bhavik3** [comment]
@romani 
Done

**Comment by romani** [comment]
> private static boolean isSameVariables(DetailAST storedVariable, DetailAST ast) {

Where is no "stored" in this context, that method is static - so it does not know about Class context at all and both arguments are the same meaning for this. So it should be as isSameVariables(DetailAST ast1, DetailAST ast2) .

**Comment by Bhavik3** [comment]
@romani 
Done

**Comment by romani** [comment]
code is ok, now I tried to review a report, but it is unreadable - too much violations.

Please do it the same way it done by http://vladlis.github.io/ and share it.
Please do reports before and after your fix to make sure only reported case is fixed and nothing other is changed (regression). Please do analysis yourself and share summary with me.

**Comment by Bhavik3** [comment]
Of course, there will be too much violations, as guava is big project and they have not declared final variable anywhere...

**Comment by Bhavik3** [comment]
@romani 
Report on Seventu-Checkstyle: No differences
Before: http://bhavik3.github.io/Before/Seventu-Checkstyle/checkstyle.html
After: http://bhavik3.github.io/After/Seventu-Checkstyle/checkstyle.html

Report on Material Design Library: No differences
Before: http://bhavik3.github.io/Before/Material%20Design%20Library/checkstyle.html
After: http://bhavik3.github.io/After/Material%20Design%20Library/checkstyle.html

Report on Java-Design-Pattern: No differences
Before: http://bhavik3.github.io/Before/Java-Design-Pattern/checkstyle.html
After: http://bhavik3.github.io/After/Java-Design-Pattern/checkstyle.html

Report on Rx Java: No differences
Before: http://bhavik3.github.io/Before/Rx%20Java/checkstyle.html
After: http://bhavik3.github.io/After/Rx%20Java/checkstyle.html

Report on guava: No differences
Before: http://bhavik3.github.io/Before/guava/checkstyle.html
After: http://bhavik3.github.io/After/guava/checkstyle.html

**Comment by romani** [comment]
merged as FF. Thanks a lot! I appreciate you persistence !

**Comment by Bhavik3** [comment]
Thanks for making me member of organization.

**Comment by romani** [comment]
@Bhavik3 ,

please, before your start doing smth for any issue please put a comment on it "I am on it" or similar - I will make you as assignee.

That helps team never conflict other the same task (unfortunately it is not possible now in github to grant you permission to do assignee yourself).

**Pull request closed without merging**
