### PR TITLE
removing dead code and refactoring in VisibilityModifierCheck, #1107

### PR DESCRIPTION
**Pull request by Vladlis**

### CODE REVIEW

**Comment by romani** [comment]
that PR have problems with NPE on launch on real sources.

**Comment by Vladlis** [comment]
fixed

**Comment by romani** [comment]
@Vladlis , please provide list of projects your tested on.

**Comment by Vladlis** [comment]
@romani, http://vladlis.github.io/xref/index.html
https://github.com/Vladlis/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties

**Comment by romani** [comment]
please run on all projects from that file.

**Comment by romani** [comment]
Please add in UT additional case that caused an exception, as all mistakes should be caught by Uts.

**Comment by Vladlis** [comment]
report: http://vladlis.github.io/

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
