### PR TITLE
Issue #1257: Fixed NPE in FinalLocalVariableCheck.findClassOrConstructorOrMethodInWhichItIsDefined .

### PR DESCRIPTION
**Pull request by rnveach**
@romani You still want me to generate a site for this?

### CODE REVIEW

**Comment by rnveach** [comment]
Fail:
> InputReturnCount.java:[50,1] duplicate class: com.puppycrawl.tools.checkstyle.coding.Test

@romani I was getting this same error on my machine and thought it was something wrong with my settings. Is something wrong with test settings?

**Comment by romani** [comment]
No, your fix is ok, no changes that could cause new exceptions or falsepositives

**Comment by romani** [comment]
merged as FF

**Comment by Bhavik3** [comment]
I would suggest to change method name to findScopeOfDefinition()  or something other generic name which can make it less confusing. because it can be anything enum, class, Method, constructor...

**Comment by romani** [comment]
@Bhavik3 , good point.

**Pull request closed without merging**
