### PR TITLE
infra: activate josm again

### PR DESCRIPTION
**Pull request by romani**
not for merge ... 
testing what is wrong with this validation item

### CODE REVIEW

**Comment by romani** [comment]
Github, rebase

**Comment by romani** [comment]
Github, rebase

**Comment by romani** [comment]
```

/usr/bin/docker run --name e33463e55081439f741e987a6bd42208c8d3c_99749d --label 9e3346 --workdir /github/workspace --rm -e GITHUB_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/checkstyle/checkstyle":"/github/workspace" 9e3346:3e55081439f741e987a6bd42208c8d3c
Collecting information about PR #8843 of checkstyle/checkstyle...
Base branch for PR #8843 is master
+ git fetch origin master
From https://github.com/checkstyle/checkstyle
 * branch                master     -> FETCH_HEAD
+ git fetch fork ci-restore-josm
From https://github.com/romani/checkstyle
 * branch                ci-restore-josm -> FETCH_HEAD
 * [new branch]          ci-restore-josm -> fork/ci-restore-josm
+ git checkout -b ci-restore-josm fork/ci-restore-josm
Switched to a new branch 'ci-restore-josm'
Branch 'ci-restore-josm' set up to track remote branch 'ci-restore-josm' from 'fork'.
+ git rebase origin/master
Rebasing (1/1)

                                                                                
Successfully rebased and updated refs/heads/ci-restore-josm.
+ git push --force-with-lease fork ci-restore-josm
To https://github.com/romani/checkstyle.git
 ! [remote rejected]     ci-restore-josm -> ci-restore-josm (refusing to allow a 
GitHub App to create or update workflow `.github/workflows/rebase.yml` 
without `workflows` permission)

```

**Comment by romani** [comment]
@strkkk, lets test rebase action here

**Comment by romani** [comment]
Github, rebase

**Comment by romani** [comment]
on local passed as:
```
checkstyle:
[checkstyle] checkstyle version 8.37-SNAPSHOT
[checkstyle] 0) Adding 1747 files from directory /home/rivanov/java/github/romani/checkstyle/.ci-temp/josm/src/org/openstreetmap/josm
[checkstyle] 1) Adding 613 files from directory /home/rivanov/java/github/romani/checkstyle/.ci-temp/josm/test
[checkstyle] 2) Adding 5 files from directory /home/rivanov/java/github/romani/checkstyle/.ci-temp/josm/scripts
[checkstyle] To locate the files took 48 ms.
[checkstyle] Running Checkstyle 8.37-SNAPSHOT on 2365 files
[checkstyle] Using configuration /home/rivanov/java/github/romani/checkstyle/.ci-temp/josm/tools/checkstyle/josm_checks.xml
[checkstyle] To process the files took 19085 ms.
[checkstyle] Total execution took 19351 ms.

BUILD SUCCESSFUL
Total time: 44 seconds
Checkstyle Errors:
Size of output: 0
```

**Review by pbludov — APPROVED** [review]

**Comment by pbludov** [comment]
@romani is this PR ready to merge?

**Pull request merged**
