### PR TITLE
Issue #2268: require all checks appear in checkstyle_checks.xml

### PR DESCRIPTION
**Pull request by rnveach**
Added override for "FileContentsHolder" to "isCheckstyleModule".
Only 1 change to XML file, added FileContentsHolder.

Currently skipping Filters. Issue said to "discuss with before".

### CODE REVIEW

**Comment by rnveach** [comment]
These are the Filters not in the XML and being skipped currently:

SuppressionCommentFilter
SeverityMatchFilter
SuppressWithNearbyCommentFilter
SuppressWarningsFilter

**Comment by romani** [comment]
we can not add modules in the middle of checkstyle_checks.xml as we reference this file at each Check javadoc - http://checkstyle.sourceforge.net/config_annotation.html#AnnotationUseStyle, see "Example of Usage". Please add to the bottom, if not possible, so we need to update all xdocs :( .

**Comment by rnveach** [comment]
@MEZk
I didn't see method "getSimpleNames", and I can't use if I am going to keep the current Filter override. Once we remove the override, I will switch to that.
I didn't see "getCheckStyleChecksReferencedInConfig", and I can't use it since it doesn't give me the filters. I was going to make 1 test cover everything and remove the current override after discussing the filters.

@romani 
I fixed it.

**Comment by rnveach** [comment]
@MEZk 
I had to remove "SuppressionFilter" from "getCheckStyleChecksReferencedInConfig" otherwise it wouldn't show up as in the config.

All changes applied now.

**Comment by romani** [comment]
from TC: "Field configFilePath may be 'static' "

**Comment by rnveach** [comment]
@romani fixed

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
