### PR TITLE
Issue #3962: Use try-with-resources to fix leaking unclosed InputStream

### PR DESCRIPTION
**Pull request by gaganis**
Issue #3962

This PR does fix the leaking file resource but I was unable to write a test to satisfy the coverage requirements. 

I am submitting this to show what I tried to do and request help on how to fix the drop in coverage.

Thanks!
Giorgos

### CODE REVIEW

**Comment by rnveach** [comment]
> request help on how to fix the drop in coverage

@gaganis We have this same problem which is why we don't convert everything to `try-with-resource`.

No matter what, the only way your going to get even close to 100% coverage is to use `PowerMock` on the test. Even then, there is hidden code being generated in the `try-with-resource` which may make it harder.

**Comment by gaganis** [comment]
I have tried writting this test using mocks but I didn't do progress because of a very weird issue I was seeing. This wasn't behaving as I expected and I tried to debug it  and I got to the point that breakpoints Inside testAutoClausable() were seeing uri as mocked but breakpoints inside ImportControlLoader.load() uri appeared as not mocked!

Very very buffling... :( 

the test code is the following:
```
@Test
    public void testAutoCloseable() throws Exception {
        try {
            final InputStream inputStream = PowerMockito.mock(InputStream.class);
            Mockito.doThrow(IOException.class).when(inputStream).close();
            Mockito.doThrow(IOException.class).when(inputStream).available();

            final URL url = PowerMockito.mock(URL.class);
            BDDMockito.given(url.openStream()).willReturn(inputStream);

            final URI uri = PowerMockito.mock(URI.class);
            BDDMockito.given(uri.toURL()).willReturn(url);

            ImportControlLoader.load(uri);
            fail("exception expected");
        }
        catch (CheckstyleException ex) {
            assertSame(IOException.class, ex.getCause().getClass());
        }
    }
```

**Comment by rnveach** [comment]
> but breakpoints inside ImportControlLoader.load() uri appeared as not mocked!

@gaganis Your test doesn't mock `ImportControlLoader` class anywhere.
It will only mock the classes and methods you specify.

**Comment by gaganis** [comment]
Thanks for the comment @rnveach.

It seems that I am looking but not seeing something basic... 

Will try again with a more clear mind 😵

**Comment by gaganis** [comment]
I have managed to make my test actually run but it did not affect the coverage. I have tried various permutations with no result.

I have no other ideas on how to do progress so I am stopping my efforts on this :(

Thanks
Giorgos

**Comment by rnveach** [comment]
@gaganis From what I read, you will need more than 1 test to achieve 100% coverage. Some were saying you would need as many as 8.

What about dropping the `try-with-resource` and using a normal `try`?
````
    public static ImportControl load(final URI uri) throws CheckstyleException {
        InputStream inputStream = null;

        try {
            InputStream inputStream = uri.toURL().openStream();
            final InputSource source = new InputSource(inputStream);
            return load(source, uri);
        }
        catch (final MalformedURLException ex) {
            throw new CheckstyleException("syntax error in url " + uri, ex);
        }
        catch (final IOException ex) {
            throw new CheckstyleException("unable to find " + uri, ex);
        }
        finally {
            if (inputStream != null)
                inputStream.close();
        }
}
````

**Comment by gaganis** [comment]
Thank you @rnveach for your detailed comment. 

I will give it one more go.

**Comment by MEZk** [comment]
@rnveach @gaganis 
It it known Cobertura problem with try-with-resources. Cobertura checks bytecode. Try-with-resources will be transformed to the code of block which was described by @rnveach. Cobertura does not have workaround or suppression for this problem.

**Comment by romani** [comment]
@gaganis, it is completely ok to make code a bit weird and unpleasant to make it happen.
try-with-resources is not allowed till cobertura become to support it. We gain enormous benefit from 100% coverage, so we are ok if that force us to make UTs a bit ugly and probably main code too.

Please use simple try-catch. If you have problems with code coverage - please share changes in this PR to let us help you.

**Comment by gaganis** [comment]
> We gain enormous benefit from 100% coverage, so we are ok if that force us to make UTs a bit ugly and probably main code too.

I totally understand.

_It has been very frustrating for me though.  I have been fruitlessly fighting with coverage for days. And I believe this is a good fix for the library as no library should leak resources._

I must also admit that the coverage fails due to branch coverage not being 100% and I do not fully understand what it means. Line coverage I am comfortable with and I managed to get it to 100%. 

It would be really helpful to me if you could provide tips on the concept of branch coverage.

**Comment by gaganis** [comment]
I will update my PR with my latest main code and UT attempt.

**Comment by rnveach** [comment]
> It has been very frustrating for me though

You can let us help you.

> branch coverage not being 100% and I do not fully understand what it means

I assume you mean you don't know what 'branch' coverage is.
It just means if you have an `if` condition, you must condition's `true` and `false` result. It is similar to line coverage for `if (condition) { ... } else { ... }` as you want to make sure you hit `if` and `else`.
It is multiplied if that condition uses `&&` or `||` operator as it is like nested single `if` conditions.
Ex: `if (condition1 && condition2) { ... }` -> `if (condition1) { if (condition2) { ... } else { ... } ... } else { ... }`

**Comment by MEZk** [comment]
@rnveach @gaganis 
It is all about [Cyclomatic Complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity). There are many examples of how to calculate Cyclomatic Complexity for java code-blocks.

**Comment by gaganis** [comment]
Hello, I have pushed my WIP commits with my attempt to increase the coverage.

Thanks,
Giorgos

**Comment by romani** [comment]
image

I did extension of you code to print inputStream variable, and it do has null and not null values.
So it is a problem of covertura, ..... we need to find workaround ....

**Comment by romani** [comment]
@gaganis , release will happen on this weekends (26th March), it would be good if finish PR till this time.
Let us know if you have no more time to continue.

**Comment by gaganis** [comment]
Hello @romani and thank you for your investigation. I missed the edit you did on your one before last comment.

I will try what you suggested now.

Thanks!

**Comment by gaganis** [comment]
This fix seems to be doing better now(4/6 checks pass). Unfortunately I have no access to the ones that fail so I have no information on what the problem is. Please advise.

Once this is PR is good to be merged, I would like to squash all my commits into one. Please let me know if it is OK.

**Comment by romani** [comment]
@gaganis , thanks for fixes.....

1) Teamcity violations need to be resolved - please fix (login as guest).

2) wercker problems is recently fixed in our repo, to fix please rebase over the latest our master.

3) please squash all commit in one.

**Comment by gaganis** [comment]
Getting this done was a true journey, yet destination reached! :tada: 

Thank you @romani @rnveach @MEZk for your help and patience to get this done! 

Cheers!

**Pull request merged**
