### PR TITLE
minor: Fix triggerRules in teamcity pull request config

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
minor: Fix triggerRules in teamcity pull request config

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
Teamcity is not using rules configured in this PR:
```
Retrieve settings, revision: 35208d3cf7404145647e07fc05361cbab5546948
```
`35208d3cf7404145647e07fc05361cbab5546948` is https://github.com/checkstyle/checkstyle/commit/35208d3cf7404145647e07fc05361cbab5546948, it is not picking up the latest revision in the config, instead using the earlier revision.

**Comment by nick-mancuso** [comment]
Mulitple asterisks will not work in TeamCity, they only allow one for any config setting that I have seen. I am closing this since we are not currently pursuing in-project config anymore, see https://github.com/checkstyle/checkstyle/issues/11876#issuecomment-1222302560 for details.

**Comment by Vyom-Yadav** [comment]
> Multiple asterisks will not work in TeamCity, they only allow one for any config setting that I have seen. I am closing this since we are not currently pursuing in-project config anymore, see https://github.com/checkstyle/checkstyle/issues/11876#issuecomment-1222302560 for details.

Try changing it to what I have in the PR, https://www.jetbrains.com/help/teamcity/configuring-vcs-triggers.html#General+Syntax covers it all, I feel it will work.

**Comment by nick-mancuso** [comment]
> Ant_like_wildcard: A [wildcard](https://www.jetbrains.com/help/teamcity/wildcards.html) to match the changed file path. Only * and ** patterns are supported, the ? pattern is not supported.

Note that this is for on-premises, I could not find similar syntax for whatever the alternative is (what we use, in-cloud?).

**Comment by Vyom-Yadav** [comment]
> VCS_comment_regexp: if specified, limits the rule only to the changes that contain specified text in the VCS comment. Use the [Java Regular Expression](http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#sum) pattern for matching the text in a comment (see examples below). The rule matches if the comment text contains a matched text portion; to match the entire text, include the ^ and $ special characters

You can also try `^.*skip TC$:**`

**Pull request closed without merging**
