### PR TITLE
Issue #3732: fix NPE for Java 8's 'receiver parameter'

### PR DESCRIPTION
**Pull request by maggu2810**
Issue #3732

### CODE REVIEW

**Comment by rnveach** [comment]
@maggu2810 
Code coverage should fail if you don't add a test.
Please add a sample test and input to [JavadocMethodCheckTest](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java).

**Comment by romani** [comment]
All CI are green is mandatory requirements

**Comment by maggu2810** [comment]
Sorry about that. I know it is not a good thing if contributors does not follow the guidelines.
I like your template on issue and pull request creation!
Will fix it later, thanks for your patient.

**Comment by romani** [comment]
It is impossible for contributors to know all rules . We and CIs are here to let you do good contribution. We will guide you.

**Comment by maggu2810** [comment]
Added a test case and now all checks are green.
Sorry for the delay.

**Comment by avandeursen** [comment]
+1 for having a super clear test case that immediately told me that the problem I had was fixed. Thanks!!

**Pull request merged**
