### PR TITLE
Issue #6207: Add Xpath IT Regression Testing for FinalLocalVariable

### PR DESCRIPTION
**Pull request by suniti0804**
Issue #6207 

Link to Check's Documentation - https://checkstyle.org/checks/coding/finallocalvariable.html#FinalLocalVariable

### CODE REVIEW

**Review by romani — CHANGES_REQUESTED** [review]
Please be a bit more creative in creation of test input files 

Put violation on variable in inner class, in anonymous class, in multiple if-for , in try blocks.

To let generated xpath be different by content and complexity.

**Comment by suniti0804** [comment]
> Please be a bit more creative in creation of test input files
> 
> Put violation on variable in inner class, in anonymous class, in multiple if-for , in try blocks.
> 
> To let generated xpath be different by content and complexity.

done

**Review by romani — APPROVED** [review]
ok to merge , thanks a lot for update.

**Review by nrmancuso — APPROVED** [review]
@suniti0804 FYI: if you take up any more of these issues, you only need to have one test per violation message (so this PR only needed one test), eight tests is overkill in this case.

**Pull request merged**
