### PR TITLE
Switched Checkstyle and all resources to UTF-8 encoding, issue #489

### PR DESCRIPTION
**Pull request by alexkravin**
According to #489 

Fixed all errors caused by switching, moved InputGrammar from resources-noncompilable to resources folder

### CODE REVIEW

**Comment by romani** [comment]
In UTF-8 there almost all characters from all languages. 
I am not sure why you use escape code there:
```
- * @author Lars Kühne
+ * @author Lars K&#xFC;hne
```

I am more worry about translated messages during that encoding change, they are should look fine, please confirm that messages are not affected.

**Comment by alexkravin** [comment]
hm.. escaping looked weird, I was afraid github wouldn't show changed letters well, but it does

**Comment by romani** [comment]
Please explain why translated messages are not affected

**Comment by alexkravin** [comment]
Is there any need to switch them too?

**Comment by romani** [comment]
Please change all reference to encoding , example https://github.com/alexkravin/checkstyle/commit/0b63cbeb0b40cafe92022420ea30b0d767e39e8e

**Comment by romani** [comment]
Property files are simple text files that are sources of checkstyle, all of them could be declated as strings in java files. They  are in text files only for convenience, but they are sources too. As text file have encoding, i could presume that encoding could be old, so we have to sure that our translation to other languages still works fine

**Comment by alexkravin** [comment]
Switched all messages' properties encoding to UTF-8 and all references to encoding specifying.

Tested Checkstyle's translated messages, e.g.:
```

<property name="localeLanguage" value="de"/>
  <property name="localeCountry" value="DE"/>

[checkstyle] /home/asus/sources/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java:193:20: Überflüssige Klammern um den return-Wert.

<property name="localeLanguage" value="tr"/>
  <property name="localeCountry" value="TR"/>

[checkstyle] /home/asus/sources/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java:193:20: Geri dönüş değeri etrafında gereksiz parantez mevcut.

<property name="localeLanguage" value="ja"/>
  <property name="localeCountry" value="JA"/>

[checkstyle] /home/asus/sources/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java:35:21: 'String' の後にホワイトスペースがあります。
```

As property files have default encoding ISO-8859-1 - there was need to make a conversion:
https://github.com/alexkravin/checkstyle/blob/5530b351dee6266999b595c8b5437fddc97357e1/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java#L278
and catch possible encoding exceptions in stack.

**Comment by romani** [comment]
good step forward, but : 

1) 
>  src/main/java/com/puppycrawl/tools/checkstyle/api/AuditEvent.java 

Please explain that fix, why it is required in that update, and why you did it.

2) 
> + final String pattern = new String(bundle.getString(mKey).
+ getBytes("ISO-8859-1"), "UTF-8")

I do not see a reason to have after update code that reference to encoding other then UTF-8. 
What is a reason of "ISO-8859-1" there ?

3) 
> + try {
+ return getMessage().compareTo(aOther.getMessage());
+ }
+ catch (UnsupportedEncodingException e) {
+ e.printStackTrace();
+ }

swallowing of Exceptions is a sin, please read about it and lets discuss in a skype.
In all other places where you do that - it is wrong.

**Comment by alexkravin** [comment]
Java ResourceBundles assume ISO-8859-1 encoding, so the ways of solution is:
1) Using InputStreamReader with specified UTF-8 encoding and Properties instead of ResourceBundle:
InputStream in = getClass().getClassLoader().getResourceAsStream(...);
Reader reader = new InputStreamReader(in, "UTF-8");
Properties props = new Properties();
props.load(reader);

2) Use alternative String constructor as I have already used.

Let's discuss the good way of processing such exceptions.

**Comment by romani** [comment]
Please find me in skype in few days(i try to recover from flu).

Fot now think as all propery files are in utf8 why you load them from bundle as iso ? As all propery files are converted correctly, no encoding referencing is required, as java use utf8 by default.

**Comment by alexkravin** [comment]
Threw unchecked exception in one place, so no redundant catches spreading by copy-paste now

**Comment by romani** [comment]
remove https://github.com/alexkravin/checkstyle/commit/90f14d1d595c5adaa4cfcc27c8081497178cff49#diff-4cd17638e0ac98de46e3603a0473be44R261

Following let me think in what encoding property filess should be stored:
 http://docs.oracle.com/javase/8/docs/api/java/util/Properties.html

**Comment by romani** [comment]
@alexkravin , please keep property files in UTF-8 format as it ease translations and ease contribution for translations files  by means of Github as user only need to open file and edit it right-away in web - on save , github will create PR automatically.

please check that approach for utf-8 property files - http://stackoverflow.com/a/4660195/1015848

**Comment by alexkravin** [comment]
Removed throws tag.

About keeping property files in UTF-8: I do not understand you because I have already switched them all without any escapings, e.g.: https://github.com/alexkravin/checkstyle/blob/90f14d1d595c5adaa4cfcc27c8081497178cff49/src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_ja.properties

I have also already used this approach from stackoverlflow

**Comment by romani** [comment]
You use loading by iso encoding, that is weird, we need to load directly by utf8.

**Comment by alexkravin** [comment]
http://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle/4660195#4660195

If I could read directly there wouldn't be any need of encoding conversion

**Comment by romani** [comment]
Please load directly in utf8 without  any intremidiate encoding, see code sample in that answer

**Comment by alexkravin** [comment]
so, use Properties?
```
Properties properties = new Properties();
try (Reader reader = Files.newReader(file, Charsets.UTF_8)) {
    properties.load(reader);
  } catch (IOException e) {
    // Do something
  }```

**Comment by romani** [comment]
Use:
bundle = new PropertyResourceBundle(new InputStreamReader(stream, "UTF-8"));

**Comment by alexkravin** [comment]
So.. where to put ```sLocale``` in that case? what about synchronized usage of BUNDLE_CACHE enum? How it will look like due to this changes?

**Comment by romani** [comment]
at line https://github.com/alexkravin/checkstyle/blob/a65ea739c4bf2c747d60cecfb6e90eaee72b5477/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java#L314
you need to use getBundle method that receive Control object
http://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html#getBundle(java.lang.String,%20java.util.Locale,%20java.lang.ClassLoader,%20java.util.ResourceBundle.Control)

in that last argumetn you will put UTF8Control  , see stackoverflow link
```
public class UTF8Control  extends Control {
 .....
```

nothing should be done with BUNDLE_CACHE or syncronization.

**Comment by alexkravin** [comment]
Thanks, this approach works, e.g.:
```
<property name="localeLanguage" value="de"/>
  <property name="localeCountry" value="DE"/>

[checkstyle] /home/asus/sources/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java:337:35: Überflüssige Klammern um die rechte Seite der Zuweisung.
[checkstyle] /home/asus/sources/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java:105:25: Überflüssige Klammern um den Bezeichner 'setInActive'.
[checkstyle] /home/asus/sources/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java:372:17: Überflüssige Klammern um die rechte Seite der Zuweisung.
[checkstyle] /home/asus/sources/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java:372:20: Überflüssige Klammern um den Bezeichner 'aLocale'.
```

**Comment by romani** [comment]
merged as FF.
thanks for prove output from terminal, It helps me trust changes without additional recheck.

**Pull request closed without merging**
