### PR TITLE
Issue #11719: Activate all group for pitest-indentation

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
#11719
Activating `ALL` group for `pitest-indentation`

Every mutator has been activated except `INLINE_CONSTS`

- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-indentation/index.html

### CODE REVIEW

**Comment by nick-mancuso** [comment]
@pbludov @baratali  this PR extends execution of pitest on indentation to 27 minutes... If we do not plan to pursue surviving mutations in this check, the only value that activation of ALL provides is to prevent future survivors. Is it worth extending execution of this profile by 21 minutes?

**Comment by baratali** [comment]
@Vyom-Yadav , can you please remove RETURN_VALS and mutator groups in this PR too? I wonder if it improves execution time

**Comment by Vyom-Yadav** [comment]
@nick-mancuso @baratali @pbludov I divided it into two profiles, one with the old mutants and one with the new mutants (ALL - old mutants), there is no significant performance improvement, 22 minutes is the execution time of new mutants. 

I think we are better off combining these profiles with an execution time of 27min rather than splitting these up into 22min and 5 min.

**Review by nick-mancuso — CHANGES_REQUESTED** [review]
> I think we are better off combining these profiles with an execution time of 27min rather than splitting these up into 22min and 5 min.
> 
> Edit- Same goes for `pitest-require-this-check`

We will revisit requirethis in it's own PR, but I am OK with anything less than 30 minutes. Let's go back to consolidated mutator model and get this merged.

**Comment by romani** [comment]
+20 minutes is big hit for verification that we know for sure will not be addressed until special gsoc like project + good student.

I am voting to not extend this config. Create separate issue on this, label it with indentation and let it wait for proper time.

We will reopen this PR in that proper time.

**Comment by nick-mancuso** [comment]
> +20 minutes is big hit for verification that we know for sure will not be addressed until special gsoc like project + good student ( few more years from now).
> 
> I am voting to not extend this config. Create separate issue on this, label it with indentation and let it wait for proper time.
> 
> We will reopen this PR in that proper time.

Agreed.

**Comment by romani** [comment]
@Vyom-Yadav, please create issue to activate All pitest group for Indentation Check, and reference this PR as example how to do this.
And close this PR
code under PR will stay forever, this is how GitHub works, so even you remove your fork, your commit in PR will stay forever available.

**Comment by rnveach** [comment]
> please create issue to activate All pitest group for Indentation Check

This is the package, not the check.

**Comment by Vyom-Yadav** [comment]
Done, created #12003

**Pull request closed without merging**
