### PR TITLE
Fix PMD violations from SimplifyStartsWith rule, issue #949

### PR DESCRIPTION
**Pull request by mkordas**
This is very controversial change, let's discuss.

### CODE REVIEW

**Comment by romani** [comment]
That is serious damage on readability of code, please prove that such micro optimization make sense.

**Comment by mkordas** [comment]
I agree that it damages readability and micro optimizations don't make sense.

It's just follow-up after our discussion in #942:
>> SimplifyStartsWith - will decrease readability, possible coverage decrease

> lets try see what it reports, yes we could ignore it if do not benefit to readability.

This rule is explained in https://developers.google.com/java-dev-tools/codepro/doc/features/audit/audit_rules_com.instantiations.assist.eclipse.auditGroup.performance#com.instantiations.assist.eclipse.audit.useCharAtRatherThanStartsWith
> The use of these rules is in no way a substitute for the use of a good performance profiling tool, but they can be used to **promote programming practices that minimize performance problems**.

**Comment by romani** [comment]
I can agree on that update only if you create special methods in our Util class "startsWithChar(char c)", "endsWithChar(char c)".

If google are really care about optimization, it is not clear why such methods are absent in Guava, we might need to propose that to Guava team, it will be interesting to see their resolution.
I failed to find any other implementation of that methods in web - so we are ok to create our own, with special note in javadoc why we do that :).

**Comment by romani** [comment]
looks good.
do you plan to open issue against Guava ?

**Pull request merged**
