### PR TITLE
Issue #11637: Resolve shellcheck SC2126

### PR DESCRIPTION
**Pull request by shubh220922**
Related to #11637 
Info referred to: https://www.shellcheck.net/wiki/SC2126
> Problematic code:
grep foo | wc -l
Correct code:
grep -c foo

Checking CI .

### CODE REVIEW

**Comment by shubh220922** [comment]
@romani @rnveach 

Problem reported by CI:

https://github.com/checkstyle/checkstyle/actions/runs/4096882495/jobs/7064844789#logs

Problem fixed in CI:

https://github.com/checkstyle/checkstyle/actions/runs/4099143078/jobs/7068770332#logs

CI is reporting other errors. Fixing that.

**Comment by rnveach** [comment]
Failed CI was re-run and failed again. It looks like the failure is related to your change. You will need to debug the original code and the new code to understand why it is failing.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
@shubh220922 in this case, `wc` mitigates failure of `grep`.  We probably also have some “useless” `cat`s around that serve the same purpose. Please try to append `&& true` to both changed commands in this PR, and test them (remove wildcards from a few pitest target classes, etc.)

**Comment by shubh220922** [comment]
@nrmancuso 

Before I proceed with what you have asked for, I am facing some problems.
I have ``xmlstarlet`` installed on my PC yet, look what is happening below:

```
PS C:\Users\shubh\OneDrive\Desktop\checkstyle project\checkstyle> bash .ci/validation.sh check-wildcards-on-pitest-target-classes
.ci/validation.sh: line 1135: xmlstarlet: command not found
```
_Image of the command that fails to run:_
image

Now, if i copy paste this command in my windows powershell and run, it runs without any problem and gives all the output:
```
PS C:\Users\shubh\OneDrive\Desktop\checkstyle project\checkstyle> bash .ci/validation.sh check-wildcards-on-pitest-target-classes                                                                   
.ci/validation.sh: line 1135: xmlstarlet: command not found
PS C:\Users\shubh\OneDrive\Desktop\checkstyle project\checkstyle> xmlstarlet sel -N x=http://maven.apache.org/POM/4.0.0 -t -v "/x:project/x:profiles/x:profile//x:targetClasses/x:param"  -n pom.xml
com.puppycrawl.tools.checkstyle.checks.ArrayTypeStyleCheck*

                  com.puppycrawl.tools.checkstyle.checks.AvoidEscapedUnicodeCharactersCheck*
                
com.puppycrawl.tools.checkstyle.checks.DescendantTokenCheck*
com.puppycrawl.tools.checkstyle.checks.FinalParametersCheck*
com.puppycrawl.tools.checkstyle.checks.LineSeparatorOption*
com.puppycrawl.tools.checkstyle.checks.NewlineAtEndOfFileCheck*
com.puppycrawl.tools.checkstyle.checks.NoCodeInFileCheck*
com.puppycrawl.tools.checkstyle.checks.OrderedPropertiesCheck*
com.puppycrawl.tools.checkstyle.checks.OuterTypeFilenameCheck*
com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder*
com.puppycrawl.tools.checkstyle.checks.TodoCommentCheck*
com.puppycrawl.tools.checkstyle.checks.TrailingCommentCheck*
com.puppycrawl.tools.checkstyle.checks.TranslationCheck*
com.puppycrawl.tools.checkstyle.checks.UncommentedMainCheck*
com.puppycrawl.tools.checkstyle.checks.UniquePropertiesCheck*
com.puppycrawl.tools.checkstyle.checks.UpperEllCheck*
com.puppycrawl.tools.checkstyle.checks.annotation.*
com.puppycrawl.tools.checkstyle.checks.blocks.*
com.puppycrawl.tools.checkstyle.checks.coding.AbstractSuperCheck*
com.puppycrawl.tools.checkstyle.checks.coding.ArrayTrailingCommaCheck*
com.puppycrawl.tools.checkstyle.checks.coding.AvoidDoubleBraceInitializationCheck*
com.puppycrawl.tools.checkstyle.checks.coding.AvoidInlineConditionalsCheck*
com.puppycrawl.tools.checkstyle.checks.coding.AvoidNoArgumentSuperConstructorCallCheck*
com.puppycrawl.tools.checkstyle.checks.coding.CovariantEqualsCheck*
com.puppycrawl.tools.checkstyle.checks.coding.DeclarationOrderCheck*
com.puppycrawl.tools.checkstyle.checks.coding.DefaultComesLastCheck*
com.puppycrawl.tools.checkstyle.checks.coding.EmptyStatementCheck*
com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck*
com.puppycrawl.tools.checkstyle.checks.coding.EqualsHashCodeCheck*
com.puppycrawl.tools.checkstyle.checks.coding.IllegalCatchCheck*
com.puppycrawl.tools.checkstyle.checks.coding.IllegalThrowsCheck*
com.puppycrawl.tools.checkstyle.checks.coding.IllegalTokenCheck*
com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck*
com.puppycrawl.tools.checkstyle.checks.coding.UnnecessaryParenthesesCheck*
com.puppycrawl.tools.checkstyle.checks.coding.SuperCloneCheck*
com.puppycrawl.tools.checkstyle.checks.coding.SuperFinalizeCheck*
com.puppycrawl.tools.checkstyle.checks.coding.PackageDeclarationCheck*
com.puppycrawl.tools.checkstyle.checks.coding.ParameterAssignmentCheck*
com.puppycrawl.tools.checkstyle.checks.coding.ReturnCountCheck*
com.puppycrawl.tools.checkstyle.checks.coding.SimplifyBooleanExpressionCheck*
com.puppycrawl.tools.checkstyle.checks.coding.SimplifyBooleanReturnCheck*
com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck*
com.puppycrawl.tools.checkstyle.checks.coding.HiddenFieldCheck*
com.puppycrawl.tools.checkstyle.checks.coding.IllegalInstantiationCheck*
com.puppycrawl.tools.checkstyle.checks.coding.InnerAssignmentCheck*
com.puppycrawl.tools.checkstyle.checks.coding.MagicNumberCheck*
com.puppycrawl.tools.checkstyle.checks.coding.MatchXpathCheck*
com.puppycrawl.tools.checkstyle.checks.coding.MissingCtorCheck*
com.puppycrawl.tools.checkstyle.checks.coding.MissingSwitchDefaultCheck*
com.puppycrawl.tools.checkstyle.checks.coding.ModifiedControlVariableCheck*
com.puppycrawl.tools.checkstyle.checks.coding.MultipleStringLiteralsCheck*
com.puppycrawl.tools.checkstyle.checks.coding.MultipleVariableDeclarationsCheck*
com.puppycrawl.tools.checkstyle.checks.coding.NestedForDepthCheck*
com.puppycrawl.tools.checkstyle.checks.coding.NestedIfDepthCheck*
com.puppycrawl.tools.checkstyle.checks.coding.NestedTryDepthCheck*
com.puppycrawl.tools.checkstyle.checks.coding.IllegalTokenTextCheck*
com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck*
com.puppycrawl.tools.checkstyle.checks.coding.UnnecessarySemicolonInTryWithResourcesCheck*
com.puppycrawl.tools.checkstyle.checks.coding.UnusedLocalVariableCheck*
com.puppycrawl.tools.checkstyle.checks.coding.OneStatementPerLineCheck*
com.puppycrawl.tools.checkstyle.checks.coding.FallThroughCheck*
com.puppycrawl.tools.checkstyle.checks.coding.NoArrayTrailingCommaCheck*
com.puppycrawl.tools.checkstyle.checks.coding.NoCloneCheck*
com.puppycrawl.tools.checkstyle.checks.coding.NoEnumTrailingCommaCheck*
com.puppycrawl.tools.checkstyle.checks.coding.NoFinalizerCheck*
com.puppycrawl.tools.checkstyle.checks.coding.OverloadMethodsDeclarationOrderCheck*
com.puppycrawl.tools.checkstyle.checks.coding.StringLiteralEqualityCheck*
com.puppycrawl.tools.checkstyle.checks.coding.ExplicitInitializationCheck*
com.puppycrawl.tools.checkstyle.checks.coding.UnnecessarySemicolonAfterOuterTypeDeclarationCheck*
com.puppycrawl.tools.checkstyle.checks.coding.UnnecessarySemicolonAfterTypeMemberDeclarationCheck*
com.puppycrawl.tools.checkstyle.checks.coding.UnnecessarySemicolonInEnumerationCheck*
com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck*
com.puppycrawl.tools.checkstyle.checks.design.*
com.puppycrawl.tools.checkstyle.checks.header.*
com.puppycrawl.tools.checkstyle.checks.imports.*
com.puppycrawl.tools.checkstyle.checks.indentation.*
com.puppycrawl.tools.checkstyle.checks.javadoc.*
com.puppycrawl.tools.checkstyle.checks.metrics.*
com.puppycrawl.tools.checkstyle.checks.modifier.*
com.puppycrawl.tools.checkstyle.checks.naming.*
com.puppycrawl.tools.checkstyle.checks.regexp.*
com.puppycrawl.tools.checkstyle.checks.sizes.*
com.puppycrawl.tools.checkstyle.checks.whitespace.*
com.puppycrawl.tools.checkstyle.ant.*
com.puppycrawl.tools.checkstyle.PackageNamesLoader*
com.puppycrawl.tools.checkstyle.AuditEventDefaultFormatter*
com.puppycrawl.tools.checkstyle.ConfigurationLoader*
com.puppycrawl.tools.checkstyle.DefaultConfiguration*
com.puppycrawl.tools.checkstyle.DefaultContext*
com.puppycrawl.tools.checkstyle.DefaultLogger*
com.puppycrawl.tools.checkstyle.Definitions*
com.puppycrawl.tools.checkstyle.LocalizedMessage*
com.puppycrawl.tools.checkstyle.XMLLogger*
com.puppycrawl.tools.checkstyle.SarifLogger*
com.puppycrawl.tools.checkstyle.MetadataGeneratorLogger*
com.puppycrawl.tools.checkstyle.PackageObjectFactory*
com.puppycrawl.tools.checkstyle.PropertiesExpander*
com.puppycrawl.tools.checkstyle.PropertyCacheFile*
com.puppycrawl.tools.checkstyle.Checker*
com.puppycrawl.tools.checkstyle.ThreadModeSettings*
com.puppycrawl.tools.checkstyle.grammar.CrAwareLexerSimulator*
com.puppycrawl.tools.checkstyle.AuditEventFormatter*
com.puppycrawl.tools.checkstyle.XdocsPropertyType*
com.puppycrawl.tools.checkstyle.PropertyType*
com.puppycrawl.tools.checkstyle.FileStatefulCheck*
com.puppycrawl.tools.checkstyle.ModuleFactory*
com.puppycrawl.tools.checkstyle.PropertyResolver*
com.puppycrawl.tools.checkstyle.StatelessCheck*
com.puppycrawl.tools.checkstyle.TreeWalkerFilter*
com.puppycrawl.tools.checkstyle.GlobalStatefulCheck*
com.puppycrawl.tools.checkstyle.grammar.CommentListener*
com.puppycrawl.tools.checkstyle.DetailAstImpl*
com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator*
com.puppycrawl.tools.checkstyle.XmlLoader*
com.puppycrawl.tools.checkstyle.JavaParser*
com.puppycrawl.tools.checkstyle.Main*
com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser*
com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter*
com.puppycrawl.tools.checkstyle.AstTreeStringPrinter*
com.puppycrawl.tools.checkstyle.SuppressionsStringPrinter*
com.puppycrawl.tools.checkstyle.TreeWalker*
com.puppycrawl.tools.checkstyle.TreeWalkerAuditEvent*
com.puppycrawl.tools.checkstyle.CheckstyleParserErrorStrategy*
com.puppycrawl.tools.checkstyle.api.*
com.puppycrawl.tools.checkstyle.filefilters.*
com.puppycrawl.tools.checkstyle.filters.*
com.puppycrawl.tools.checkstyle.utils.*
com.puppycrawl.tools.checkstyle.gui.*
com.puppycrawl.tools.checkstyle.xpath.*
com.puppycrawl.tools.checkstyle.XpathFileGeneratorAuditListener*
com.puppycrawl.tools.checkstyle.XpathFileGeneratorAstFilter*
com.puppycrawl.tools.checkstyle.JavaAstVisitor*
PS C:\Users\shubh\OneDrive\Desktop\checkstyle project\checkstyle>
```

How am I supposed to check if the bash files are failing to run?


> (remove wildcards from a few pitest classes target classes, etc.)

Also what do you mean by ``wildcards`` here? There are these ``targetClasses`` and ``targetTests`` in pom.xml. Are these the wildcards that i have to remove in order to check whether the script is running properly or not? (Image below)
image

**Comment by nrmancuso** [comment]
@shubh220922 I do not use windows, so I have no idea what `bash …` is doing in this case. Either way, whatever this command does in windows does not allow bash to access executable files in your windows machine apparently (and I presume that it wouldn’t be able to use it anyway), so for all intents and purposes, you do not have xmlstarlet installed anywhere that bash can use it.

**Comment by shubh220922** [comment]
@nrmancuso no problem for the time being. Using fedora, I'm able to run the shell files. Will see how I can overcome the issue on windows.

**Comment by shubh220922** [comment]
Due to some issue on my local, further progress of this PR is continued in .

**Pull request closed without merging**
