### PR TITLE
Issue #5480: investigate and resolve compilation warning -add configu…

### LINKED ISSUE #5480: investigate and resolve compilation warnings
from build https://travis-ci.org/checkstyle/checkstyle/jobs/328807259#L642 :

[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ checkstyle ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1335 source files to /home/travis/build/checkstyle/checkstyle/target/test-classes
[WARNING] /home/travis/build/checkstyle/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/XmlLoaderTest.java:[36,47] com.sun.org.apache.xerces.internal.impl.Constants is internal proprietary API and may be removed in a future release
[WARNING] /home/travis/build/checkstyle/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/XmlLoaderTest.java:[41,13] com.sun.org.apache.xerces.internal.impl.Constants is internal proprietary API and may be removed in a future release
[WARNING] /home/travis/build/checkstyle/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/XmlLoaderTest.java:[41,44] com.sun.org.apache.xerces.internal.impl.Constants is internal proprietary API and may be removed in a future release
[INFO] /home/travis/build/checkstyle/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/BriefUtLogger.java: Some input files use or override a deprecated API.
[INFO] /home/travis/build/checkstyle/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/BriefUtLogger.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckOnDifferentTokens.java: Some input files use unchecked or unsafe operations.
[INFO] /home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckOnDifferentTokens.java: Recompile with -Xlint:unchecked for details.

if issues are complicated or might affect users, it might be better to split them to separate issues.
Not clear why compiler try to analyse "src/test/resources" - during this phase, validation should be skipped.

### PR DESCRIPTION
**Pull request by SinmoWay**
resolve #5480.

### CODE REVIEW

**Comment by romani** [comment]
suppression is last resort, please provide a reasons why them can not be fixed.

**Comment by SinmoWay** [comment]
`<fork>` Allows us to perform an operation to suppress warnings in a separate jvm stream. Why ignore i'm writing in #5480.

**Comment by romani** [comment]
@SinmoWay ,
please squash commits and rebase on latest master to resolve wercker problem.

**Comment by SinmoWay** [comment]
@romani  
No problems.
Changes in the BriefLogger are caused by the deprecated method called from the constructor.
This is reported at the info level in the Issue  #5480. 
If this change is not required, the commit will be deleted.

**Comment by SinmoWay** [comment]
Sorry, but for some reason wercker failed. 
Rebase master did not help.

**Comment by romani** [comment]
you are not based on latest master:HEAD (https://github.com/checkstyle/checkstyle/commits/master) , do rebase one more time.

**Pull request merged**
