### PR TITLE
Issue #4353: refactoring: remove 'final' modifier from all arguments of method/c-tor at ImportControlCheck and around

### PR DESCRIPTION
**Pull request by sharang108**
PR for Issue #4353

### CODE REVIEW

**Comment by sharang108** [comment]
@rnveach @romani  Please review

**Comment by rnveach** [comment]
@sharang108 Look at first sentence in issue, link to discussion also mentioned issue in `ImportControl` in main code.
Example: https://github.com/sharang108/checkstyle/blob/622b9ae998652e1742da476603cd17042e50db7e/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControl.java#L68

Please go through this file too and remove `final` in parameters.
Please keep at 1 commit.

**Comment by romani** [comment]
Please also rebase on latest master to test travis fix.
As all CI passed, we will merge

**Comment by sharang108** [comment]
@romani  I've updated the commit with latest commits to the main repository

**Pull request merged**
