### PR TITLE
Issue #5832: Code samples for Naming Checks

### PR DESCRIPTION
**Pull request by jack870131**

### CODE REVIEW

**Comment by romani** [comment]
make sure you pass `mvn verify` on your local before you send a PR.

**Comment by rnveach** [comment]
@jack870131 as you make fixes, please keep number of commits as 1.

**Comment by jack870131** [comment]
I am so careless that I just change the pull request online directly. The number of commit just went to 2. How should I solve it?

**Comment by rnveach** [comment]
@jack870131 If you are closing this to add new changes, you can just amend the existing commit and force push the new changes to the server.

**Pull request closed without merging**
