### PR TITLE
Issue #7608 : Update doc for DesignForExtension

### PR DESCRIPTION
**Pull request by HarshSharma0801**
Issue #7608 
Added example for each existing config to show what code is ok and what code cause violation.

### CODE REVIEW

**Comment by HarshSharma0801** [comment]
can anyone guide me why these tests failed , its showing something related to xml files .

**Comment by romani** [comment]
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=13809&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=42

Xml formatting is damaged, please follow what CI demands.

**Comment by romani** [comment]
Before push, run `mvn verify` and fix all errors it raising.

**Comment by romani** [comment]
Close this , if you continue at https://github.com/checkstyle/checkstyle/pull/12925

**Pull request closed without merging**
