### PR TITLE
Deprecated methods have been removed.

### PR DESCRIPTION
**Pull request by sabaka**
Issue #46

I'm not sure in these changes because somebody outside the project may use it, but it have been marked deprecated for a while and I think it's expected.
Let's discuss.

Btw there are couple false positive in sonar and I'll notify sonar team about it.

### CODE REVIEW

**Comment by sabaka** [comment]
Looks like call hierarchy doesn't work properly in my eclipse.
Will fix it soon

**Comment by romani** [comment]
commit message has to have link to issue

**Comment by romani** [comment]
you can remove Deprecated only at gui/ParseTreeInfoPanel.java , all other deprecations were restored due to user requests as other projects use that, we will remove them in next major version.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
