### PR TITLE
Update index.xml.vm

### PR DESCRIPTION
**Pull request by AlenJoseph55**
Corrected some typos. 
Is it okay for me to continue?

### CODE REVIEW

**Comment by romani** [comment]
please fix CI failures.
All CIs should be green.

you need to have commit message in specific format as we demand.

**Comment by AlenJoseph55** [comment]
Thank you, I will try and fix ci failures.

**Comment by AlenJoseph55** [comment]
I ran  `mvn checkstyle:check` command and this is the result.

image
Should I solve these violations to fix CI failures?

**Comment by AlenJoseph55** [comment]
How can I make these tests pass?
Here is what all I done.
After making changes to the documentation I ran
`mvn test jacoco:restore-instrumented-classes jacoco:report@default-report`
command and this is the result:
image
I tried to solve this but no luck. can you help me with this?

**Comment by romani** [comment]
your local failures are weird, try to do `mvn clean .....` before verification on local.

look at CIs for now, there are bunch of items to fix, for example - https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=14452&view=logs&j=eb841e9f-6e1e-5c29-3ad5-74ec2c658069&t=a9b761e6-b8d5-50cf-467a-54967189cab2&l=1247, all others also should be green, fix them all.

**Comment by AlenJoseph55** [comment]
Yeah Okay, I will try and resolve CI's for now.

**Comment by AlenJoseph55** [comment]
I was following instructions on `https://checkstyle.org/beginning_development.html` now I think I made it worse.

**Comment by romani** [comment]
back up your changes on your local, remove all your local, remove your fork, fork us again 
and start from scratch 
https://checkstyle.org/beginning_development.html#Starting_Development

**Comment by AlenJoseph55** [comment]
Yeah okay. I can close the PR now right?

**Pull request closed without merging**
