### PR TITLE
Issue #2095: Fix false negative in AtclauseOrder check

### PR DESCRIPTION
**Pull request by Vladlis**
Reports over guava with google config of the check [before](http://vladlis.github.io/reports/atclauseorder/before/) and [after](http://vladlis.github.io/reports/atclauseorder/after/) changes are identical.

### CODE REVIEW

**Comment by mkordas** [comment]
@Vladlis, thanks for the report over Guava. 

1. Can you explain why do we need `orderIndicesOfPreviousTags`? Maybe you can find better name for it like ? If you can't think of better name, shouldn't it be `orderOfIndicesInPreviousTag`? Anyway, some comment would be useful there. 
2. Why do we refer to 'tags' in code if we operate on atclauses?

**Comment by Vladlis** [comment]
1. <code>orderIndicies</code> -> indecies of order
    <code>ofPreviousTags</code> -> of tags, which are located before the one, which is processed in the moment
    I suppose it is an appropriate name, but ok, I'll add a comment.

2. Google calls [block tags](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#javadoctags) "at-clauses" and on the one hand it would be better to refer to "at-clauses", because the name of the Check is "AtclauseOrder", but on the other hand we already have option "tagOrder" and ArrayList tagOrder is used to determine order indicies of tags.

**Comment by romani** [comment]
@Vladlis, pleaese move fix for #2074 in separate PR that will allow us merge it quickly and review functional changes easily.

**Comment by Vladlis** [comment]
@romani, done

**Comment by mkordas** [comment]
>we already have option "tagOrder" and ArrayList tagOrder is used to determine order indices of tags.

OK

1) Introducing `final List<Integer> orderIndicesOfPreviousTags = new ArrayList<>();` and looping over entire list for each at-clause will cause quadratic complexity of this check. Can you somehow measure how much time it takes to execute this check over Open JDK before and after your changes?
2) Minor: I think `Fix behavior` instead of `Fix work` sounds better, but still it doesn't say what was wrong and what was fixed. Can you reword commit message so it is more descriptive?
3) `contains indices of order of tags, which are located before the processed one` - comma is unnecessary here. Also I don't understand what `indices of order of tags` does mean.

**Comment by Vladlis** [comment]
@mkordas,
1. It takes quite some time, I'll say results later today.
2. I cannot imagine a more descriptive message which would fit in a single line.
3. Is it clearer now? - [link](https://github.com/checkstyle/checkstyle/commit/361b2fcaefc779669e4a45cd646f0536ab7ccb57#diff-6d4b0d5911e5ed5f47a227650ec06fa0R161)

**Comment by romani** [comment]
> I cannot imagine a more descriptive message which would fit in a single line.

problem is comming from bad name for issue. @mkordas , please update issue name as you would like it to be. @Vladlis , please copy new issue name to commit message.

**Comment by romani** [comment]
1) 
> private static final String COMMA_SEPARATOR = ",";

please add "\n"

2)
>```                 final int indexOrderOfCurrentTag = tagOrder.indexOf(tagText);
                if (tagOrder.contains(tagText)) {
```

tagOrder.indexOf and tagOrder.contains(tagText) do give alsmost the same answer , result of one should be reused.

3)
>```
for (int orderIndex: orderIndicesOfPreviousTags) {
                        if (orderIndex > indexOrderOfCurrentTag) {
                            log(node.getLineNumber(), MSG_KEY, tagOrder.toString());
                            break;
                        }
                    }
```

no need to keep a collection of indexes, jsut keep last index and compare it to new index.

**Comment by mkordas** [comment]
@Vladlis 
>  Is it clearer now?

`contains ordinal indices in tagOrder of tags which are located before the processed one` is still not clear for me
>please update issue name as you would like it to be

renamed to `False negative in AtclauseOrder check`

**Comment by Vladlis** [comment]
@romani,
1) Done.
2) Done.
3) Fixed, only maximal last index is kept now.

**Comment by mkordas** [comment]
@Vladlis, thanks for great effort here and applying all the comments.
@romani, PR looks good to me, can you do final review?

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
