### PR TITLE
Issue #5003: increased pitest coverage for whitespace package to 100%

### PR DESCRIPTION
**Pull request by rnveach**
Issue #5003

Regression to come.
Some proof of changes at https://github.com/checkstyle/checkstyle/issues/5003#issuecomment-350560290 .

### CODE REVIEW

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/142/

No differences.

**Comment by romani** [comment]
please rebase.

**Comment by rnveach** [comment]
@romani Done.

**Comment by romani** [comment]
I still think that code of whole method "getTypeLastNode" could changed to make same but in different way to avoid problems with pitest.
@rnveach , please keep in mind that pitest only point to probelm, it does not dictate how to write a code. So whole method refactoring is ok, end it is better than +1 +2 ,.... changes.

**Comment by rnveach** [comment]
@romani Please make new issue if you think the method could be refactored better.

**Pull request merged**
