### PR TITLE
Issue #5916: add header for non-compiled sources

### PR DESCRIPTION
**Pull request by romani**
WIP , not for merge.

Issue #5916

all non-compilable should have header, if we run into case when test case can not have such header we can exclude it from search

### CODE REVIEW

**Comment by romani** [comment]
@rnveach , are you ok with such update ?

**Comment by romani** [comment]
now PR should pass, and we can update step by step (continuous).

**Comment by rnveach** [comment]
I am fine with the update but this still doesn't change that I think we shouldn't be moving compilable code to non-compilable because of eclipse's custom compiler.
Also now we have to remember to add these comments to the files to force a check on their compile status. This kind of situation should be an opt-out, not an opt-in, imo.

**Comment by romani** [comment]
you do not need to remember anything, if you miss comment on file that should be compiled - CI will fail (as it will try to compile it).
https://github.com/checkstyle/checkstyle/blob/master/.ci/travis/travis.sh#L70

**Pull request closed without merging**
