### PR TITLE
Issue #569: Move TreeWalker cache to Checker

### PR DESCRIPTION
**Pull request by MEZk**

### CODE REVIEW

**Comment by MEZk** [comment]
@romani 
Moving cache property from TreeWalker to Checker will break compatibility with checkstyle-maven-plugin^
https://travis-ci.org/checkstyle/checkstyle/jobs/107586768#L440

**Comment by romani** [comment]
1) please restore field in Treewalker , 
2) create an issue to remove that field in Chekcstyle 8.0
3) mark field as Deprecated and make a note that it does not do anything now (put a suppression on non-used field with link to issue) , we just keep field for transition period to the same option in Checker. Make a link to new location. 

We will remove that option completely in Checkstyle 8.0 version.

**Comment by MEZk** [comment]
@romani 
1) Done.
2) Done.
3) Done.

**Comment by romani** [comment]
@MEZk , thanks a lot, only one minor need to be resolved. All other code is good.

@lkoe , please review and lets us know if we miss smth and you need smth else. I am ready to merge this PR.

**Comment by MEZk** [comment]
@romani 
>only one minor need to be resolved.

Done.

**Comment by lkoe** [comment]
Looks splendid. Thanks guys.

**Comment by romani** [comment]
merged as FF

**Pull request merged**
