### PR TITLE
Issue #5060: activate eclipse's rawTypeReference and uncheckedTypeOperation

### PR DESCRIPTION
**Pull request by romani**
#5060

### CODE REVIEW

**Comment by rnveach** [comment]
These eclipse errors complained about the way we wrote the bean converters in `AutomaticBean`.
Specifically:
````
        @SuppressWarnings({"unchecked", "rawtypes"})
        @Override
        public Object convert(Class type, Object value) {
````

I was going to look into if these could be re-written.

**Comment by romani** [comment]
I might not see something, but eclipse violations are conflicting with each other. Or it might have issue with matching suppression to whole method and all parts of it, and probably need placement of annotation on argument , on return type, ... .
```
1. ERROR in /home/travis/build/checkstyle/checkstyle/src/main/java/
com/puppycrawl/tools/checkstyle/api/AutomaticBean.java (at line 294)
	@SuppressWarnings({"unchecked", "rawtypes"})
	                   ^^^^^^^^^^^
Unnecessary @SuppressWarnings("unchecked")
----------

2. ERROR in /home/travis/build/checkstyle/checkstyle/src/main/java/
com/puppycrawl/tools/checkstyle/api/AutomaticBean.java (at line 294)
	@SuppressWarnings({"unchecked", "rawtypes"})
	                                ^^^^^^^^^^
Unnecessary @SuppressWarnings("rawtypes")

----------

3. ERROR in /home/travis/build/checkstyle/checkstyle/src/main/java/
com/puppycrawl/tools/checkstyle/api/AutomaticBean.java (at line 296)
	public Object convert(Class type, Object value) {
	       ^^^^^^
Type safety: The return type Object for convert(Class, Object) from the type
AutomaticBean.PatternConverter needs unchecked conversion to conform 
to T from the type Converter

----------

4. ERROR in /home/travis/build/checkstyle/checkstyle/src/main/java/
com/puppycrawl/tools/checkstyle/api/AutomaticBean.java (at line 296)
	public Object convert(Class type, Object value) {
	                      ^^^^^
Class is a raw type. References to generic type Class<T> should be parameterized
```

@rnveach , can you try in Eclipse how it like suppression to be ?

avoiding of raw type, should be done in separate issue, as it might result in API changes....

**Comment by rnveach** [comment]
@romani Turning something to `error` in eclipse means you can't suppress it. Suppressing is only for warnings.
CI errors look correct to me.

**Comment by romani** [comment]
Ok, make sense.
Should we just move such two options out of ignore section ?
They should stay warning

**Comment by rnveach** [comment]
I am fine with that.

**Comment by romani** [comment]
moved to separate commit of PR #7168

**Pull request closed without merging**
