### PR TITLE
Issue #5934: remove old ant configs

### PR DESCRIPTION
**Pull request by romani**
Issue #5934

### CODE REVIEW

**Comment by rnveach** [comment]
> Caused by: java.util.MissingResourceException: Can't find bundle for base name checkstylecompilation, locale 
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.execute(CheckstyleAntTask.java:275)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by romani** [comment]
I was surprised by failure, as `mvn clean verify` passed before push, or  may be lost track of executions....

fixed.

**Comment by romani** [comment]
generated xml report is identical with what is in master
```
java -jar /home/....../target/checkstyle-8.11-SNAPSHOT-all.jar -f xml -c config.xml Test.java
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="8.11-SNAPSHOT">
<file name="/var/tmp/Test.java">
</file>
</checkstyle>
```

**Comment by romani** [comment]
rebased, squshed and merged manually

**Pull request closed without merging**
