### PR TITLE
Issue #7705: add no error regression for methods distance repo

### PR DESCRIPTION
**Pull request by rnveach**
Issue #7705

Expecting similar errors from wercker as repo hasn't been updated to 8.30 and already confirmed it needs changes.

### CODE REVIEW

**Comment by rnveach** [comment]
> CheckstyleException: Unable to instantiate 'AvoidDoubleBraceInitialization'

Not the error I was looking for, because the project used `checkstyle-version` instead of `checkstyle.version`

**Comment by rnveach** [comment]
> [INFO] Starting audit...
[ERROR] /pipeline/source/.ci-temp/methods-distance/methods-distance/src/main/java/com/github/sevntu/checkstyle/domain/MethodDefinition.java:64: Comment text should start with space. [commentStartWithSpace]
Audit done.

Failing as expected.

**Comment by rnveach** [comment]
Blocked by https://github.com/sevntu-checkstyle/methods-distance/pull/51

**Comment by romani** [comment]
referenced PR is merged, please proceed.

**Comment by romani** [comment]
for some reason I skip such project at https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#update-for-released-version-reference , it might be mistake in wiki.

**Comment by rnveach** [comment]
@romani Nothing more should need to be done here since blocked PR is merged. All we need here is to rerun CI and wait for it to pass.

**Comment by rnveach** [comment]
> for some reason I skip such project at https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#update-for-released-version-reference , it might be mistake in wiki.

Besides method-distance, sevntu-checks is also missing. If you wish, I can add them to the wiki.

**Comment by romani** [comment]
>If you wish, I can add them to the wiki.

Let's add them after enforcement them in CI. I remember I tired to update all projects after release. If this become errorless, we can do all.

**Comment by rnveach** [comment]
Rebased to resolve conflict from other PR merged.

**Pull request merged**
