### PR TITLE
Issue 3001: All messages translated to Chinese. 

### PR DESCRIPTION
**Pull request by ybbpgfjtey**
Issue #3001 

- Issue fix;
- I changed MainTest, set default locale to root, to prevent it fail in language environment other than English;
- Did not find xdoc file to be updated.

### CODE REVIEW

**Comment by romani** [comment]
please squash all in one commit. 
CIs need to be fixed.

**Comment by ybbpgfjtey** [comment]
@romani How to squash commited message.

**Comment by romani** [comment]
No need to squash messages, just make one commit with message `Issue #3000: Chinese messages`

**Comment by ybbpgfjtey** [comment]
@romani 
Checks failed for earlier message.
What should I do?

**Comment by romani** [comment]
look at PR, you have 6 commits, but there should be 1 commit.

please read : https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/Development-workflow-with-Git%3A-Fork%2C-Branching%2C-Commits%2C-and-Pull-Request
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

please do:
```
git rebase -i HEAD~6
git push origin my-branch --force
```

**Comment by ybbpgfjtey** [comment]
@romani Thanks you for your help.

**Comment by romani** [comment]
> 4) Travis need to have testing for Chinese locale -

please update Travis config base on example for other languages.

**Pull request merged**
