### PR TITLE
Issue #6213: warning during build of site with equalsverifier-3.0.2

### PR DESCRIPTION
**Pull request by romani**
#6213

### CODE REVIEW

**Comment by romani** [comment]
@rnveach ,
please investigate how we missed such failure to master branch:
https://travis-ci.org/checkstyle/checkstyle/jobs/456151612#L792
```
execute:
     [echo] Checkstyle started (checkstyle_checks.xml): 16/11/2018 08:49:54 PM
[checkstyle] Running Checkstyle  on 1012 files
     [echo] Checkstyle finished (checkstyle_checks.xml) : 16/11/2018 08:50:44 PM
     [echo] Checkstyle started (checkstyle_non_main_files_checks.xml): 16/11/2018 08:49:54 PM
[checkstyle] Running Checkstyle  on 1640 files
[checkstyle] [ERROR] /home/travis/build/checkstyle/checkstyle/.github/CONTRIBUTING.md:10: Line should not be longer then 100 symbols [RegexpSingleline]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

I fixed it  - https://github.com/checkstyle/checkstyle/commit/adcb43c99bcf35ec6eddf650c2f722c343e661da

**Comment by romani** [comment]
wercker problem is unrelated:
`[INFO] Building Hibernate Search Documentation 6.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (default-cli) @ hibernate-search-documentation ---
[INFO] Starting audit...
[ERROR] /pipeline/source/.ci-temp/hibernate-search/documentation/src/test/java/org/hibernate/search/documentation/gettingstarted/withouthsearch/GettingStartedWithoutHibernateSearchIT.java:9:15: Unused import - org.assertj.core.api.Assertions.assertThat. [UnusedImports]
Audit done.
`
looks like a violation leek in hibernate project, we probably need to do checkout to stable version to avoid such regression.

**Comment by rnveach** [comment]
> please investigate how we missed such failure to master branch:

PR was fully green and CI ran travis and passed: https://github.com/checkstyle/checkstyle/pull/6208
Merged commit in master ran in travis and passed: https://travis-ci.org/checkstyle/checkstyle/builds/455767825
It wasn't until the next merge commit with picocli that master failed with long line violation: https://travis-ci.org/checkstyle/checkstyle/builds/456170055

But if we go back and look at "bad" merged commit CI, and dive into the details we see checkstyle was never run in CI.
https://travis-ci.org/checkstyle/checkstyle/jobs/455767828#L629
> CI is skipped

@romani It seems our CI skip command is not correct.

https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L212-L216
`.github` is part of our skipping but we run checkstyle on it so we should never be skipping.

I think we should add `- SKIP_CI="false"` to the `checkstyle and sevntu-checkstyle` job in travis. At some point, we will be running checkstyle on all files, especially to prevent long lines.

The only other option is to make specific list of files that are allowed to be skipped for each travis job.

**Comment by romani** [comment]
>I think we should add - SKIP_CI="false" to the checkstyle and sevntu-checkstyle job in travis. At some point, we will be running checkstyle on all files

Yes, let's do it

**Pull request merged**
