### PR TITLE
Issue #2729: Support of arrays in java8 method references has been added to grammar.

### PR DESCRIPTION
**Pull request by sabaka**
Reports with line length check (https://github.com/sabaka/contribution/blob/own_config/checkstyle-tester/my_check.xml)
On projects: https://github.com/sabaka/contribution/blob/own_config/checkstyle-tester/projects-to-test-on.properties
origin:
http://sabaka.github.io/issue2729/master/checkstyle.html
after changes:
http://sabaka.github.io/issue2729/checkstyle.html

### CODE REVIEW

**Comment by romani** [comment]
Travis found exceptions during parsing, please put that cases to UTs some where.

**Comment by mkordas** [comment]
@sabaka did you have time to work on this PR recently?

**Comment by sabaka** [comment]
@mkordas , yes, I work on this PR when I have time.

**Comment by romani** [comment]
@sabaka , you can send update `sed -i '' ` in separate PR to make it persistent and be ready to be used for MacOs straightaway.

**Comment by romani** [comment]
@sabaka , please rebase this PR

**Comment by romani** [comment]
hmmm, on MacOS such testing were passed . 
Can you confirm that this problem is not reproduced on MacOS (I just curions) ?

**Comment by sabaka** [comment]
@romani , current parsing problem is reproduced on macos. I'm trying to fix it.

**Comment by romani** [comment]
I am closing this PR, fix is not ready, fixing it is not so easy, we will do new PR when we are ready.

**Pull request closed without merging**
