### PR TITLE
fixes #48 StackOverflow in com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch

### LINKED ISSUE #48: StackOverflow in com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch
MultilineDetector.findMatch is a recursive function which will return only if it was not able to find a match. Otherwise it will call itself again which will cause StackOverflow.
There is some check for exceeded number of matches but that check only logs such situation but does not stops the recursion. Probably that check should also break recursion in some way.
Below is Eclipse's stack trace which encountered this problem.
java.lang.StackOverflowError
	at java.util.AbstractCollection.toArray(AbstractCollection.java:175)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:236)
	at com.puppycrawl.tools.checkstyle.DefaultConfiguration.getMessages(DefaultConfiguration.java:144)
	at com.puppycrawl.tools.checkstyle.api.AbstractViolationReporter.getCustomMessages(AbstractViolationReporter.java:132)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.log(AbstractFileSetCheck.java:147)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.log(AbstractFileSetCheck.java:140)
	at com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch(MultilineDetector.java:83)
	at com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch(MultilineDetector.java:88)
	at com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch(MultilineDetector.java:88)
	at com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch(MultilineDetector.java:88)

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
I’m sure I’m missing something non-obvious (and not covered by a test...) if I were to suggest that https://github.com/checkstyle/checkstyle/issues/48 could simply be resolved like this? Could this ever lead to an infinite loop?

PS: The GitHub ?w=1 don't show whitespace trick allows you to see more clearly what this proposes, look at https://github.com/checkstyle/checkstyle/pull/1225/files?w=1 instead of https://github.com/checkstyle/checkstyle/pull/1225/files.

**Comment by romani** [comment]
1)
>   private void findMatch() {

please fix javadoc


2) 
> } while (true);

good step forward , but infinite loop and not a single exit point from method are never good , please refactor to :
```
final boolean foundMatch = matcher.find();
while(!foundMatch) {
....
foundMatch = matcher.find();
}
```
that will be much better to read.

**Comment by romani** [comment]
release 6.8 will be in 4 days, it will be good to finish that PR before.

**Comment by vorburger** [comment]
implemented both code review feedbacks

**Comment by romani** [comment]
please squash commits in one ans put at the end of commit message reference to github issue like (". #xxxxxxx")

**Comment by vorburger** [comment]
@romani  did you see I actually did do the squash 4 days ago? I was hoping you could merge this in time for 6.8 .. released yesterday, you missed to merge this one? Anything else holding you back from merging this?

**Comment by romani** [comment]
@vorburger , sorry I missed that, github did not notify about such changes, amount of posts did not change in PRs page so I did not take a look inside, preparation for 6.8 was busy ..... . Next time please do not hesitate to bother me with additional post to PR like "done".

I did gig regression in 6.8 release so I am going to do 6.8.1 - your changes will be included.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
