### PR TITLE
minor: Remove an ArchUnit Frozen Violation

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
The second commit is under review. For demonstration purposes, DO NOT MERGE.

### CODE REVIEW

**Comment by romani** [comment]
Can you point to exact line where violation is printed in log, I tried to find at https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=11311&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111 but failed

**Comment by nrmancuso** [comment]
You cannot see it, test passes and suppression is automatically added to freeze file

**Comment by Vyom-Yadav** [comment]
One more thing, if the user pushes PR which will change the ArchUnit store, but he did not execute the test on his local machine, then it will be caught in the CI as we do:
https://github.com/checkstyle/checkstyle/blob/ba66ce2ff1eedfe2d9df3cb22d80f8b892d2bf9d/.ci/validation.sh#L1041-L1049

It will be similar to when we update something in the module and don't run the Metadata related tests which update the check metadata and later it can be seen in the CI.

**Comment by nrmancuso** [comment]
Closing this PR, it has served it's purpose and we have merged https://github.com/checkstyle/checkstyle/pull/12190

**Pull request closed without merging**
