### PR TITLE
minor: extract maven execution from pitest

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
From discussion at https://github.com/checkstyle/checkstyle/pull/11731#discussion_r903910867 and https://github.com/checkstyle/checkstyle/issues/11720#issuecomment-1164365831:

Extract maven execution from `pitest.sh` script.

Failed pitest run (for proof): https://github.com/checkstyle/checkstyle/actions/runs/2555422670

### CODE REVIEW

**Comment by nick-mancuso** [comment]
This PR depends on https://github.com/checkstyle/checkstyle/pull/11762, adding blocked label until then.

**Comment by Vyom-Yadav** [comment]
@nick-mancuso #11762 has been merged, this can be reviewed.

**Review by nick-mancuso — APPROVED** [review]

**Review by rnveach — APPROVED** [review]
I am told this is more temporary so I am ok with this, but I am not liking we are losing a simple command to run the pitest process locally and now splitting up with no replacement.

**Comment by Vyom-Yadav** [comment]
> I am hoping this is more temporary and am more ok with this if that is the case, but I am not liking we are losing a simple command to run the pitest process locally and now splitting up with no replacement.

Exactly, that will be a habit breaker too, and generating pit reports first and then evaluating them just adds a step.

**Comment by nick-mancuso** [comment]
I am merging this to move project along, @romani please see comments above from maintainers regarding this change.

**Pull request merged**
