### PR TITLE
Update maven-jxr-plugin to 2.5 for issue #644

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
Please recheck that before and after changes link are the same "mvn clean site", please use diff tools for that (ui or console). Please recheck result of linkcheck maven plugun, see that maven report on our site.

**Comment by romani** [comment]
merged as FF

**Comment by mkordas** [comment]
Are you sure everything is OK after update? I planned to do thorough comparison during the weekend.

**Comment by romani** [comment]
I did comparison myself, looks ok.

**Pull request closed without merging**
