### PR TITLE
Issue #13109: Kill mutation for MultipleVariableDeclarationsCheck

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13109: Kill mutation for MultipleVariableDeclarationsCheck

--------

# Check 
https://checkstyle.org/config_coding.html#MultipleVariableDeclarations

--------

# Mutation 
https://github.com/checkstyle/checkstyle/blob/3f25c37d731544f47d13020b47bfbec2a1bf57b6/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L66-L82

-------

# Explaination
Test added

---------

# Regression 

Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/47e3287_2023184215/reports/diff/index.html

Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/47e3287_2023211141/reports/diff/index.html

------------

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/201dae231798cb048eca902b7b21d6ea/raw/6655ab3c5cff01a88fcbc704e671b6be0c441a98/MultipleVariableDeclarationsCheck.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/21e3934e85f802e2fbd48af06d122364/raw/604256badd733d8568064f371d55657c04b00dfd/test-projects-2.properties
Report label: Latest-Report-2

### CODE REVIEW

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/18962/workflows/ecff56cf-2820-438a-ae44-8bb5be478e44/jobs/309926 similar error noticed in multiple pr

**Comment by Kevin222004** [comment]
Github, generate report

**Comment by Kevin222004** [comment]
Github, generate report

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by Vyom-Yadav** [comment]
@Kevin222004 This is not the correct analysis, you missed 2 test cases:
```java
void method4() {                                                                    
    int c = // violation 'Only one variable definition per line allowed.'           
            12; int a = 1;                                                          
                                                                                    
    int cb = 12; java. // violation 'Only one variable definition per line allowed.'
            lang.String                                                             
            asd = "123";                                                            
}                                                                                                                                                  
```

This is being detected by the code in the master branch, but since you resort to `final DetailAST lastNode = ast.getLastChild();` the last child has more children, which are on the next line and `nextNode` directly instead of `final DetailAST firstNextNode = CheckUtil.getFirstNode(nextNode);` this is not being detected anymore.

---

I don't think the current logic is redundant, please use the above-mentioned test cases killing the mutation.

**Review by Vyom-Yadav — CHANGES_REQUESTED** [review]
https://github.com/checkstyle/checkstyle/pull/13197#issuecomment-1604031090

**Comment by Kevin222004** [comment]
> his is being detected by the code in the master branch, but since you resort to final DetailAST lastNode = ast.getLastChild(); the last child has more children, which are on the next line and nextNode directly instead of final DetailAST firstNextNode = CheckUtil.getFirstNode(nextNode); this is not being detected anymore.

Yes you are right I missed this test and my calculation become wrong

**Comment by romani** [comment]
@Kevin222004 , please resolve conflict and and lets finalize review.

**Comment by romani** [comment]
Circleci is restarted

**Review by romani — APPROVED** [review]
Ok to merge

**Review by romani — APPROVED** [review]
Ok to merge

**Pull request merged**
