### PR TITLE
Issue #2889: Adds skipNoJavadoc option to MissingDeprecated check

### PR DESCRIPTION
**Pull request by liscju**

### CODE REVIEW

**Comment by romani** [comment]
from issue:

> `I think it would make sense to add an option to MissingDeprecated to allow it to ignore cases when JavaDoc is missing, but still warn when JavaDoc is present but either @deprecated is missing from JavaDoc or @Deprecated is missing from the element`

main point "... but still warn when ...." please put this to javadoc/xdoc/examples . In other case it is hard to catch a reason of this option as it is looks like disablement of whole Check.

**Comment by liscju** [comment]
@romani 
1) DONE, snippet from javadoc:
```java
 * <p>
 * In addition you can configure this check with skipNoJavadoc
 * option to allow it to ignore cases when JavaDoc is missing,
 * but still warns when JavaDoc is present but either
 * {@link Deprecated Deprecated} is missing from JavaDoc or
 * {@link Deprecated Deprecated} is missing from the element.
 * To configure this check to allow it use:
 * </p>
```

2) DONE, it looks like this:
```
<subsection name="Examples">
        <p> To configure the check:</p>
        <source> &lt;module name=&quot;MissingDeprecated&quot;/&gt;
        </source>
        <p> In addition you can configure this check with skipNoJavadoc option: </p>
        <source>   &lt;property name="skipNoJavadoc" value="true" /&gt;</source>
        <p>This statement would be allowed:</p>
        <source>
        @deprecated
        public static final int MY_CONST = 123456;
        </source>
        <p>But this statement would raise violation:</p>
        <source>
        /** This javadoc is missing deprecated tag. */
        @deprecated
        public static final int COUNTER = 10;
        </source>
      </subsection>
```

**Comment by romani** [comment]
html is bad, next time please put a picture of how html looks like.

screenshot-missingdeprected-bad-html

1) please fix table of options.

2) remove indentation in Examples

3) provide full config of module

4) make one example 
```
        @deprecated
        public static final int MY_CONST = 123456; // no violation

        /** This javadoc is missing deprecated tag. */
        @deprecated
        public static final int COUNTER = 10; // violation as javadoc exists
        
````

**Comment by liscju** [comment]
@romani,
1) DONE
2) DONE
3) DONE, If by full config option You mean:
```
<module name="AnnotationLocation">
    <property name="skipNoJavadoc" value="true" />
</module>
```
4) DONE

now javadoc looks like this:
image

**Comment by romani** [comment]
merged as FF

>  If by full config option You mean:

yes, user need to be easily copy-paste example and make it work.

**Pull request closed without merging**
