### PR TITLE
Issue #461: Antlr4 grammar has been edited to support custom javadoc tags with dots and colons

### PR DESCRIPTION
**Pull request by baratali**

### CODE REVIEW

**Comment by romani** [comment]
please prove that it runs without exceptions on all projects from checkstyle-tester.

**Comment by romani** [comment]
@baratali , release will happen on Sunday, it would be good to finish this PR before release.

**Comment by baratali** [comment]
@romani , no exceptions detected.
Details.
Checkstyle report generation on OpenJDK sources:
```
bizmailov@vdu-bizmailov:~/git/contribution/checkstyle-tester$ ./launch.sh -Dcheckstyle.config.location=my_check.xml
Testing Checkstyle started
openjdk is synchronized

Running 'mvn clean' on src/main/java ...
...............
Done. Result report is locates at: target/site/index.html
bizmailov@vdu-bizmailov:~/git/contribution/checkstyle-tester$ grep "Got an exception" target/site/checkstyle.html 
bizmailov@vdu-bizmailov:~/git/contribution/checkstyle-tester$
```
One more project([nbia-dcm4che-tools](https://github.com/thprakash/nbia-dcm4che-tools)) with some custom Javadoc tags:
```
bizmailov@vdu-bizmailov:~/git/contribution/checkstyle-tester-2$ ./launch.sh -Dcheckstyle.config.location=my_check.xml
Testing Checkstyle started
untar thprakash-nbia-dcm4che-tools file is done to src/main/java/nbia-dcm4che-tools - completed

nbia-dcm4che-tools is synchronized

Running 'mvn clean' on src/main/java ...
..................
Done. Result report is locates at: target/site/index.html
bizmailov@vdu-bizmailov:~/git/contribution/checkstyle-tester-2$ grep "Got an exception" target/site/checkstyle.html
bizmailov@vdu-bizmailov:~/git/contribution/checkstyle-tester-2$ 
```

**Comment by romani** [comment]
merged as FF

**Comment by romani** [comment]
> One more project(nbia-dcm4che-tools) with some custom Javadoc tags

I added it to https://github.com/checkstyle/contribution/commit/7e3d2e44d2ee8ab4cf08eb80df4a8ca08f1d996b

> http://xdoclet.sourceforge.net/xdoclet/cvs-usage.html

unfortunately deprecated project and use CVS , can not be added to chekcstyle-tester

@baratali , if you know any other active project with custom tags - please set PR with update of  https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties
one day all of them will be used for testing in CIs.

**Pull request closed without merging**
