### PR TITLE
Issue #3601: MethodParamPad example added

### PR DESCRIPTION
**Pull request by ImmortalRabbit**
Issue #3601

### CODE REVIEW

**Comment by romani** [comment]
@ImmortalRabbit , please make examples for all properties and is properties have enum values, please make example for their enum values.

**Comment by romani** [comment]
I just rebased ...

**Review by esilkensen — APPROVED** [review]

**Comment by romani** [comment]
Github, generate web site

**Comment by romani** [comment]
failures are unrelated, I am merging...

**Pull request merged**
