### PR TITLE
Issue #5279: ImportOrder: static imports can be separated by local gr…

### PR DESCRIPTION
**Pull request by djydewang**
…oups when they are at the top/bottom

Fix for Issue #5279

### CODE REVIEW

**Comment by romani** [comment]
@djydewang , please rebase.

**Comment by djydewang** [comment]
[Regression report](https://djydewang.github.io/diffReport_Issue5279_bottom_false/index.html) for `separatedStaticImports=false`.
[Regression report](https://djydewang.github.io/diffReport_Issue5279_bottom_true/index.html) for `separatedStaticImports=true`.

**Comment by romani** [comment]
@djydewang ,

> for separatedStaticImports=false sortStaticImportsAlphabetically=false separated=false

this report should have no diff, as it should work the same as before.
Please explain if I miss smth.

**Comment by djydewang** [comment]
@romani 
It depands on how we define checkstyle's behaviou when `sortStaticImportsAlphabetically=false`.
static imports can be  unordered in old version as we discuss in Issue #5253. 
And I think we misunderstood the funtion of sortStaticImportsAlphabetically property in that issue. 
Sorry for my mistake:(
Now, when `sortStaticImportsAlphabetically=false` and you specify package groupings inside ImportOrder, that same ordering is applied to the single group of static imports.

**Comment by romani** [comment]
I need to think one more time about all of this ....
I postpone your fix to next month release. Sorry.
I will reply in few days.

**Comment by djydewang** [comment]
@romani ping

**Comment by romani** [comment]
thanks for ping, but I did not lost this issue from my todo, I some some draft notes already, but I need to review them one more time to give you good feedback. Your issues is not simple :) .

**Comment by romani** [comment]
@djydewang , please look at my reply at https://github.com/checkstyle/checkstyle/issues/5279#issuecomment-357390199

**Comment by romani** [comment]
@djydewang, 
sorry for delay in reply...

at https://github.com/checkstyle/checkstyle/issues/5279#issuecomment-357447644
you asked me to review reports. 
Did you regenerated them or they are still actual ?
Do you think it is better to introduce "separatedStaticImports" first ?
please rebase on latest master to resolve conflicts in this PR.

**Comment by romani** [comment]
@djydewang, ping.
please rebase to let me proceed with review.

**Comment by romani** [comment]
@djydewang, please let us know if do not have time to continue, we will unblock PR to let smb else to continue with fix.
We appreciated your time for contribution, but we cannot be blocked.

**Comment by romani** [comment]
PR is closed in favor of #5760

**Pull request closed without merging**
