### PR TITLE
dependency: bump Error Prone 2.15.0 -> 2.18.0

### PR DESCRIPTION
**Pull request by rickie**
Bumps Error Prone from 2.15.0 to 2.18.0.

Suggested commit message:
```
dependency: bump Error Prone 2.15.0 -> 2.18.0

See:
- https://github.com/google/error-prone/releases/tag/v2.16
- https://github.com/google/error-prone/releases/tag/v2.17.0
- https://github.com/google/error-prone/releases/tag/v2.18.0
- https://github.com/google/error-prone/compare/v2.15.0...v2.18.0
```

I'm not sure why Dependabot didn't open PRs for this dependency, but it would be nice to upgrade Error Prone.

### CODE REVIEW

**Review by Vyom-Yadav — APPROVED** [review]
Thanks a lot! 

Travis failure is unrelated

**Review by nrmancuso — CHANGES_REQUESTED** [review]
@rickie thanks for noticing this, please make commit message like `dependency: bump error-prone.version from 2.15.0 to 2.18.0`

**Comment by rickie** [comment]
Done! @nrmancuso

**Review by romani — APPROVED** [review]
ok to merge on green CI

**Review by nrmancuso — APPROVED** [review]
CI failures are not related to changes here.

**Pull request merged**
