### PR TITLE
Issue #13345: Enabled test cases MemberNameCheckTest

### PR DESCRIPTION
**Pull request by Rohanraj123**
Part of #13345

### CODE REVIEW

**Comment by romani** [comment]
CI is not happy, please may it green.
Make sure that `mvn clean verify` passing on your local before push.
Let us know if you need help.

**Comment by Rohanraj123** [comment]
> CI is not happy, please may it green. Make sure that `mvn clean verify` passing on your local before push. Let us know if you need help.

`mvn clean very` build was successful ! Can you please suggest what should I change.

**Comment by Rohanraj123** [comment]
@romani Sir, can you please review the changes I have made whether it is correct or not.

**Comment by romani** [comment]
please look at Ci 
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=16634&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=1760

and apply suggested by CI changes to your commit.

**Review by romani — APPROVED** [review]
Ok to merge.

Ideally I would remove all comments and keep only `// violation ` without any extra text.
As this check is very simple. But we can do this in separate PR

**Comment by Rohanraj123** [comment]
> Ok to merge.
> 
> Ideally I would remove all comments and keep only `// violation ` without any extra text. As this check is very simple. But we can do this in separate PR

No worries I will do the required changes in this PR only.

**Comment by romani** [comment]
What you have now is very good.

**Review by nrmancuso — APPROVED** [review]

**Pull request merged**
