### PR TITLE
Issue #13501: Kill mutation for AnnotationUtil

### PR DESCRIPTION
**Pull request by Kevin222004**
Issue #13501: Kill mutation for AnnotationUtil

------

# Mutations 
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/config/pitest-suppressions/pitest-utils-suppressions.xml#L3-L10

-------

# Explaination 
**Method 1**
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java#L90-L96
This method 
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java#L91 
is mutated and the usage of this method is only in the check `PackageAnnotationCheck`
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheck.java#L107-L109
at line no 109 as this is visit token and no other such operation is perfoming on ast it will only be the acceptaed token which is `PACKAGE_DEF` so 
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java#L91-L93
this removal will not make any affect

*Second reason*
may be stronger then above one 
lets suppose above we have not condition `ast == null` and by chance ast is null then while calling https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java#L94
getAnnotationHolder already have this condition https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java#L178-L181.

**Method 2**
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java#L113-L116
in which similar mutation at line 114

know this method is called by one method in same class at 
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java#L165-L167

and this method is used by 5 Checks
1) ParameterNumberCheck :- https://checkstyle.org/checks/sizes/parameternumber.html#ParameterNumber
2) MissingOverrideCheck :- https://checkstyle.org/checks/annotation/missingoverride.html#MissingOverride
3) MethodNameCheck :- https://checkstyle.org/checks/naming/methodname.html#MethodName
4) IllegalTypeCheck :- https://checkstyle.org/checks/coding/illegaltype.html
5) IllegalThrowsCheck :- https://checkstyle.org/checks/coding/illegalthrows.html

***1) ParameterNumberCheck :-***
usage of method is at
https://github.com/checkstyle/checkstyle/blob/
8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheck.java#L177-L181
line 180 know this method in ast is called only at visit token at line 164 https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheck.java#L161-L164
over here directly ast is used which is in parameter so it is also bever going to null

***2) MissingOverrideCheck :-***
Similar reason as above the usage is at 
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheck.java#L227-L253
the method is used at line 248 and similar ast is direclty passed from parameter.

***3) MethodNameCheck :-***
Similar reason for method name check 
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheck.java#L231-L235

***4) IllegalThrowsCheck :-***
Similar reason 
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java#L228-L232

***5) IllegalTypeCheck :-***
Similar reasons
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java#L807-L812

*Second reason* 
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java#L125 
call 
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java#L255-L257 
and it is calling 
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java#L178-L181
so here ast is checked again

### CODE REVIEW

**Comment by Kevin222004** [comment]
https://kevin222004.github.io/PitestReport/com.puppycrawl.tools.checkstyle.utils/AnnotationUtil.java.html 
This contains 2 mutation may be this is issue.

**Comment by Kevin222004** [comment]
@romani 
https://checkstyle.semaphoreci.com/jobs/01ed458d-ea27-4b03-9c02-06e28c81f883
```
[ERROR] Errors: 03:03
[ERROR]   ParenPadCheckTest.testNoStackoverflowError:466->AbstractModuleTestSupport.verifyWithLimitedResources:390 » Execution java.lang.Error: Error was thrown while processing /home/semaphore/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadNoStackoverflowError.java03:03
[INFO] 
```
Again NoStackoverFlowError 

As far I don't remember we have done any changes in favour of pitest which create this type of issue

**Review by romani — APPROVED** [review]
I ok to remove such null validation.
I see no value in them, it is still exception, absolutely sae details user will get from NPE.

`throw new IllegalArgumentException("annotations cannot be null");` also can be removed and all similar

**Review by Vyom-Yadav — APPROVED** [review]
LGTM!

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by rdiachenko** [comment]
@Kevin222004 please resolve conflicts

**Comment by romani** [comment]
@Kevin222004 , conflict

**Comment by romani** [comment]
@Kevin222004 , CI is failing

**Comment by Kevin222004** [comment]
Can you please re run circle ci

**Comment by Vyom-Yadav** [comment]
> Can you please re run circle ci

@Kevin222004 Just add some change, push the commit, remove that change, push again, that will re trigger the CI with current changes. You can use this if no one is around.

**Comment by romani** [comment]
CIs were restarted

**Comment by romani** [comment]
@Kevin222004 , please resolve conflict

**Comment by Kevin222004** [comment]
conflict resolved

**Pull request merged**
