### PR TITLE
CommentsIndentationCheck: Fix FP at the end of the block and issue with the "DOT" token

### PR DESCRIPTION
**Pull request by MEZk**
@romani 
1) Fixed FP violations at the end of the block.
2) Also fixed issue #2077 with the "DOT" token , because it can appear at the end of the block too. Issues #2078 and #2077 are both closely connected and resolved by this PR.
3) Rearranged UTs and ITs: one test - one input file, minimal dependencies between tests. Move all test input files to appropriate package.
4) Updates UTs and ITs to cover problematic cases of comments placement.
5) Fixed CommentsIndentationCheck violations on checkstyle source code after 1 and 2.

Please review and I'll generate reports.

### CODE REVIEW

**Comment by romani** [comment]
1) 
please explain why two commits "Update UTs for CommentsIndentationCheck" exists.

2) please provide HTML reports before/after to make sure that there is no regression. Covered cases are rare so diff should be minimal in most projects.

**Comment by MEZk** [comment]
@romani 
1) One for UTs and one for ITs.

**Comment by romani** [comment]
we still have false-positives:

http://mezk.github.io/i2078_guava_after/checkstyle.html 

http://mezk.github.io/i2078_guava_after/xref/guava/guava-gwt/test-super/com/google/common/cache/super/com/google/common/cache/CacheBuilderTest.html#L122
on code like:
```
119     CacheBuilder.newBuilder()
120         .expireAfterWrite(1, NANOSECONDS)
121         .build(identityLoader());
122     // well, it didn't blow up.
```

no violation is expected.

**Comment by romani** [comment]
please rebase your PR, find me in web for call

**Comment by romani** [comment]
@MEZk ,

release 6.12 is planned to be at 31 of October.
it would very good to finish this PR before release. Do you have time to finish PR ?

**Comment by MEZk** [comment]
@romani 
Rebased onto the latest master.
Reports: http://mezk.github.io/index.html
Xdoc: http://mezk.github.io/i2078_site/config_misc.html#CommentsIndentation

**Comment by romani** [comment]
merged as FF.

functionality is awesome, please contact me after release to regenerate report for Guava and write them a comment about your New check.

I will do code review a bit later for your code to make non-fucntional changes to code design.

**Pull request closed without merging**
