### PR TITLE
Update Maven Surefire Plugin to 2.18.1 for Travis profile, issue #787

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by romani** [comment]
Why you left configuration tag in travis profile ? i see no reason to keep them different.

**Comment by mkordas** [comment]
Done, configuration unified for them according to http://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html

**Comment by romani** [comment]
I do not like that general name "argLine" is placed at global properties that could cause unexpected and hard to detectproblems, I would rather keep a copy/paste , can you propose any other solutions ?

**Comment by mkordas** [comment]
I cannot do copy&paste. Build fails if I have `<argLine>${argLine} ...</argLine>` without JaCoCo. Argument lines either need to be different or we decide to have global property.

**Comment by romani** [comment]
sorry, I can not apply that, lets keep code as is, that changes are not going to make POM is simpler or easy.
Please close PR yourself.

**Comment by mkordas** [comment]
Do you mean that we should have Surefire declared twice? So maybe at least I'll extract `<maven.surefire.plugin.version>` global property?

**Comment by romani** [comment]
ok, lets have version be global property, please change PR.

**Comment by mkordas** [comment]
done

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
