### PR TITLE
Issue #6123: ignore parameters of methods with modifiers not in 'memberModifiers'

### PR DESCRIPTION
**Pull request by ebruneton**
Issue #6123

### CODE REVIEW

**Comment by rnveach** [comment]
@romani How should we configure the check for regression?

**Comment by rnveach** [comment]
@romani ping

**Comment by romani** [comment]
@rnveach  and @ebruneton , sorry for delay.

I think in regression report we should simply use config that is defined in issue description.
Default set of classes is pretty aggressive, so there will be some code that is using HashSet in private method, especially in some old projects like `ant`.

@ebruneton , please run regression https://github.com/checkstyle/contribution/tree/master/checkstyle-tester on all project (if too much violations, cut set of projects to keep amount of diff less than 300 violations).  Please do not forget to change config to have your config.
Please share report with us to verify.

**Comment by rnveach** [comment]
@romani Here is the regression for this PR. I ran it for @ebruneton .

http://rveach.no-ip.org/checkstyle/regression/reports/185/

**Comment by romani** [comment]
@rnveach , thanks a lot!!!
report looks good.

**Pull request merged**
